### PR TITLE
bpo-31286: Fixed stack usage in absolute imports with binding a submo…

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
…dule to a name.

https://bugs.python.org/issue30024

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]
LGTM.

Should we bump the magic number for this?

**Comment by ncoghlan** [comment]
Yes, we should bump the magic number, as otherwise cached pyc files will still exhibit the bug - we need the interpreter to clear them out and recompile them.

**Comment by serhiy-storchaka** [comment]
I'm not sure this is needed. The version with the bug was not released. The bug affects only pre-alpha testers. AFAIK there are no precedences of bumping the magic number at pre-alpha stage for fixing a bug.

**Comment by ncoghlan** [comment]
Fair point, especially as the new test case is the only example of the problem in the code base.

We can probably skip the NEWS entry for the same reason (i.e. it fixes a bug in never-released code, so the fact the bug existed isn't exactly relevant to most users)

**Pull request merged**
