### PR TITLE
gh-110209: Add __class_getitem__ for generator and coroutine

### PR DESCRIPTION
**Pull request by Gobot1234**
* Issue: gh-110209

### CODE REVIEW

**Comment by Gobot1234** [comment]
Windows failure seems unrelated

**Review by graingert — CHANGES_REQUESTED** [review]
Can you add a test for this?

**Review by graingert — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Do we also need to do this for async generators? (Will look more later today but don't have a ton of time right now.)

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
> Do we also need to do this for async generators? (Will look more later today but don't have a ton of time right now.)

No, async generators are already subscriptable.

```
>>> x = type(f())
>>> 
>>> x
<class 'async_generator'>
>>> x[1]
async_generator[1]
>>> 
```

**Pull request merged**
