### PR TITLE
gh-108765: Python.h no longer includes <unistd.h>

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-108765

----
:books: Documentation preview :books:: https://cpython-previews--108783.org.readthedocs.build/

### CODE REVIEW

**Comment by vstinner** [comment]
I merged my PR.

If it causes too many trouble in 3rd party C extensions (require to update too many C extensions before Python 3.13 beta1), I can make this change conditional only in the limited C API version 3.13, as I did for other headers in ``Python.h``:

```
// errno.h, stdio.h, stdlib.h and string.h headers are no longer used by Python
// headers, but kept for backward compatibility (no introduce new compiler
// warnings). They are not included by the limited C API version 3.11 and
// above.
#if !defined(Py_LIMITED_API) || Py_LIMITED_API+0 < 0x030b0000
#  include <errno.h>              // errno
#  include <stdio.h>              // FILE*
#  include <stdlib.h>             // getenv()
#  include <string.h>             // memcpy()
#endif
```

I consider that ``<unistd.h>`` is less commonly used by than the very common ``<errno.h>``, ``<stdio.h>``, ``<stdlib.h>`` and  ``<string.h>``. Again, if it causes too much burden, I can make the change conditional.

**Comment by jibal** [comment]
breaks signalmodule.c

**Comment by vstinner** [comment]
> breaks signalmodule.c

Would you mind to elaborate your comment "a little bit"? What is broken? Is it a build issue? On which Python version? On which OS (name, version) and compiler (name, version)?

**Comment by jibal** [comment]
signalmodule.c calls pause() and alarm() (under #ifdef HAVE_{PAUSE,ALARM} guards), which are defined in unistd.h

On the Python version where you deleted unistd.h from Python.h, of course.

**Comment by vstinner** [comment]
> signalmodule.c calls pause() and alarm() (under #ifdef HAVE_{PAUSE,ALARM} guards), which are defined in unistd.h

Hum, in fact, <unistd.h> is included indirectly by pycore_pythread.h. But well, I wrote PR #111402 to make it extra clear.

**Comment by jibal** [comment]
> Hum, in fact, <unistd.h> is included indirectly by pycore_pythread.h. 

Which is not necessarily included ... it wasn't in my build. (Which I've abandoned ... I never actually intended to build the top of tree.)

> But well, I wrote PR https://github.com/python/cpython/pull/111402 to make it extra clear.

Seems like the right thing to do.

**Comment by vstinner** [comment]
> Which is not necessarily included when signalmodule.c is compiled ... it wasn't in my build. (Which I've abandoned ... I never actually intended to build the top of tree.)

You didn't reply to my question about OS and compiler... Also, pycore_pythread.h was modified recently.

**Pull request merged**
