### PR TITLE
[3.8] bpo-46400: Update libexpat from 2.4.1 to 2.4.4 (GH-31022)

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue46400

### CODE REVIEW

**Comment by dil022dixith** [comment]
When can we expect this will merged and available for 3.8 Version.

**Comment by corona10** [comment]
@dil022dixith It's up to @ambv :)

**Comment by corona10** [comment]
@ambv 
I would like to request merging this PR anyway since the main branch is already merged.
And for better diff comparison when upgrading libexpat, this way will be more convenient.

**Comment by ambv** [comment]
@corona10 fair enough!

**Comment by corona10** [comment]
Thanks!

**Pull request merged**
