### PR TITLE
gh-103559: Update bundled pip version to 23.1.1

### LINKED ISSUE #103559: Upgrade the bundled version of pip to 23.1.1
# Feature or enhancement

This is the latest pip release.

# Pitch

This ensures that users who install newest release of Python get the newest version of pip.

### Linked PRs
* gh-103560
* gh-103752

### PR DESCRIPTION
**Pull request by pfmoore**
closes: #103559
x-ref: https://github.com/pypa/pip/issues/11902

* Issue: gh-103559

### CODE REVIEW

**Review by warsaw — APPROVED** [review]

**Comment by pfmoore** [comment]
We'll be releasing a 23.1.1, so I will update this PR once that happens, rather than creating a new PR.

**Comment by warsaw** [comment]
> We'll be releasing a 23.1.1, so I will update this PR once that happens, rather than creating a new PR.

Cool.  Ping me if I don't give you an approval quickly.  Also, do you want me to merge it, automerge it, or leave it to you (if you can)?  I haven't tested it but I believe this will help unblock #98040

**Comment by pfmoore** [comment]
@warsaw I'm fine with merging myself once the release is done, and I think it's uncontroversial enough that I won't bother waiting for you to re-approve (unless you'd prefer that I did).

I'll try to get the pip release done tomorrow (UK time).

**Comment by warsaw** [comment]
Sounds good @pfmoore - I'll leave it to you.  I agree it's uncontroversial.  And thanks!

**Comment by pfmoore** [comment]
Sorry, @warsaw, we've just found a further issue that needs to be included in pip 23.1.1. Would it help you if I merged this PR now, on the understanding that there will be a subsequent PR upgrading to 23.1.1? It's not much extra work, so if it's useful to you, just let me know.

**Review by furkanonder — APPROVED** [review]

**Comment by pfmoore** [comment]
@pradyunsg It appears that #95299 was *not* backported to Python 3.11. Is that intentional, or simply an oversight? As it stands, that makes it messy to backport this PR to 3.11. What is the expectation regarding 3.11?

To be explicit:

1. Do I need to backport pip 23.1.1 to Python 3.11?
2. Do I need to do so while retaining the inclusion of setuptools, or can I expect #95299 to be backported?

**Comment by pfmoore** [comment]
Never mind, fixing the backport wasn't too hard, so I did it. #95299 can be dealt with however you prefer.

**Pull request merged**
