### PR TITLE
bpo-38652: Remove provisional note for asyncio.BufferedProtocol

### PR DESCRIPTION
**Pull request by Anj-A**
https://bugs.python.org/issue38652

Automerge-Triggered-By: @asvetlov

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Anj-A

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by JamoBox** [comment]
@Anj-A 
Are you sure this is the right BPO issue number? Looks like it should be under bpo-38652

**Review by aeros — APPROVED** [review]
Thanks for the PR @Anj-A, this looks exactly as I described in the issue, with removing the provisional note while retaining a `versionadded` note. I'll add a label to backport it to the 3.8 branch as well.

**Comment by aeros** [comment]
Also, if you could update the PR title to be more specifically descriptive of the changes made, that would be helpful. The actual changes made are correct though.

**Comment by Anj-A** [comment]
Have signed the CLA and updated the title as suggested.

**Comment by Anj-A** [comment]
Hi, could you please get this PR approved if everything looks fine?

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks!

**Comment by asvetlov** [comment]
The fix should not be backported to 3.8, that's perfectly fine if 3.8 still states that BufferedProtocol is still provisional.
Changing something in 3.8.1 is worse than keeping the status quo until 3.9

**Comment by aeros** [comment]
@asvetlov 
> The fix should not be backported to 3.8, that's perfectly fine if 3.8 still states that BufferedProtocol is still provisional.

Okay, I'll remove the backport label then.

Does this also apply to other provisional APIs as well, as in they remain provisional for the major version they were released on?

**Comment by asvetlov** [comment]
I doubt if we have a strong rule for the provisional status cleanup.
I only recall discussions for removal something in 3.X, and never for 3.X.Y.

**Pull request merged**
