### PR TITLE
bpo-43995: Fix test_grammar

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue43995

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@pablogsal, does this belong in issue 43901?

**Comment by erlend-aasland** [comment]
FYI, Azure Pipelines failure is unrelated.

**Comment by pablogsal** [comment]
> @pablogsal, does this belong in issue 43901?

Yeah, but having an issue for this is also ok. Can you leave a comment in 43901 regarding this fix?

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks a lot @erlend-aasland !

**Comment by erlend-aasland** [comment]
Thank you, @pablogsal! I'll add a short note about this at 43901 :)

**Pull request merged**
