### PR TITLE
gh-107450: Raise OverflowError when parser column offset overflows

### PR DESCRIPTION
**Pull request by lysnikolaou**
* Issue: gh-107450

### CODE REVIEW

**Comment by lysnikolaou** [comment]
Should we backport this?

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
I think it makes sense to backport. How crazy is to add a test case?

**Comment by lysnikolaou** [comment]
> I think it makes sense to backport. How crazy is to add a test case?

Added.

**Comment by colesbury** [comment]
@lysnikolaou the testMemoryErrorBigSource seems to fail on 32-bit Windows

**Comment by vstinner** [comment]
Right, the test fails on 32-bit, at least on GHA Windows x86 CI:

```
FAIL: testMemoryErrorBigSource (test.test_exceptions.ExceptionTests.testMemoryErrorBigSource)
----------------------------------------------------------------------
OverflowError: cannot fit 'int' into an index-sized integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_exceptions.py", line 322, in testMemoryErrorBigSource
    with self.assertRaisesRegex(OverflowError, "column offset overflow"):
AssertionError: "column offset overflow" does not match "cannot fit 'int' into an index-sized integer"
```

**Pull request merged**
