### PR TITLE
[3.8] bpo-43077: Update bundled pip to 21.0.1 and setuptools to 52.0.0 (GH-24386)

### PR DESCRIPTION
**Pull request by pfmoore**
Update bundled pip to 21.0.1 and setuptools to 52.0.0.
(cherry picked from commit 4d11ecbb5ed78e6259ee27289c7638aad795f473)

Co-authored-by: Paul Moore <p.f.moore@gmail.com>

https://bugs.python.org/issue43077

### CODE REVIEW

**Comment by pfmoore** [comment]
:-( Looks like ensurepip changed between 3.9 and 3.10, probably to handle the fact that we're no longer shipping `py2.py3` wheels. I'll look at backporting that fix and hopefully that will address this.

**Comment by pfmoore** [comment]
https://github.com/pypa/pip/issues/9540

**Comment by sbidoul** [comment]
Superseded by #25579

**Comment by matrixise** [comment]
Hi @pfmoore

I close this PR because it is superseded by #25579.

Thank you so much for your PR.

**Pull request closed without merging**
