### PR TITLE
gh-91052: Add PyDict_Unwatch for unwatching a dictionary

### PR DESCRIPTION
**Pull request by carljm**
This API should have been in https://github.com/python/cpython/pull/31787 but we forgot about it.

Also clean up some minor things: add to whatsnew, add versionadded tags, use `test.support.catch_unraisable_exceptions` instead of reinventing it.

* Issue: gh-91052

### CODE REVIEW

**Comment by carljm** [comment]
Added "skip news" label since this is already covered by the NEWS entry from #31787.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by markshannon** [comment]
I don't know what the docs failure is, but everything else looks good.

**Comment by JelleZijlstra** [comment]
The docs failure is unrelated, #98056 will fix it.

**Comment by vstinner** [comment]
Thanks for adding ``.. versionadded:: 3.12`` and documenting the new functions in What's New. The test looks better with catch_unraisable_exception.

**Pull request merged**
