### PR TITLE
gh-116303: Don't build xxlimited and xxlimited_35 if --disable-test-modules is given

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-116303

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I consider this a non-controversial change; I'll merge it tomorrow morning.

**Comment by erlend-aasland** [comment]
We could consider backporting this to 3.12. What do you think, @corona10?

**Comment by corona10** [comment]
Yeah go ahead :)

**Comment by erlend-aasland** [comment]
Since it does not backport cleanly, I won't bother :)

**Pull request merged**
