### PR TITLE
bpo-42237: Fix os.sendfile() on illumos

### PR DESCRIPTION
**Pull request by jstasiak**
https://bugs.python.org/issue42237

### CODE REVIEW

**Review by wiedi — APPROVED** [review]
With this patch on SmartOS:

```
testCount (test.test_socket.SendfileUsingSendfileTest) ... ok
testCountSmall (test.test_socket.SendfileUsingSendfileTest) ... ok
testCountWithOffset (test.test_socket.SendfileUsingSendfileTest) ... ok
testEmptyFileSend (test.test_socket.SendfileUsingSendfileTest) ... ok
testNonBlocking (test.test_socket.SendfileUsingSendfileTest) ... ok
testNonRegularFile (test.test_socket.SendfileUsingSendfileTest) ... ok
testOffset (test.test_socket.SendfileUsingSendfileTest) ... ok
testRegularFile (test.test_socket.SendfileUsingSendfileTest) ... ok
testWithTimeout (test.test_socket.SendfileUsingSendfileTest) ... ok
testWithTimeoutTriggeredSend (test.test_socket.SendfileUsingSendfileTest) ... ok
test_errors (test.test_socket.SendfileUsingSendfileTest) ... ok

----------------------------------------------------------------------
Ran 11 tests in 0.280s

OK
```

**Comment by kulikjak** [comment]
Thanks! I tested this on Oracle Solaris and it still works as expected. Checking inside the `do while` loop is certainly a right move because before it could incorrectly handle `EINTR`.

You should probably also write a NEWS entry.

Lastly, I don't know if you have to be that verbose with the comments (especially the _in one confirmed case the destination socket had a 5 second timeout set and errno was EAGAIN_  part - it's expected behavior, not an obscure bug), but hey, those are just details ;).

**Comment by jstasiak** [comment]
I will fiercely defend the verbosity of that comment. :) The [illumos sendfile man page](https://illumos.org/man/3ext/sendfile) even has this in the `EINVAL` section:

```
Fewer bytes were transferred than were requested.
```

which makes partial write + errno set to `EAGAIN` combination totally unexpected (and quite obscure) to me. As a code reader I found it invaluable to have such things documented (even repeatedly and redundantly) in source code comments so I'm writing comments I myself would like to see there. The only part I'll admit that's too specific is the value of 5 seconds, I think it's about non-zero timeout, naturally.

I thought fixing a bug is not worth a NEWS entry but I'm happy to write one.

**Comment by kulikjak** [comment]
Ah, you are right. Partial writes are expected, `EAGAIN` not so much (this might even be an Illumos bug - not just implementation difference).

I am not sure whether the NEWS entry is necessary, but generally, I was asked to write one even for minor fixes (and this is a pretty important fix).

**Review by kulikjak — APPROVED** [review]

**Comment by jstasiak** [comment]
Fair enough! Just added the NEWS entry.

**Comment by jstasiak** [comment]
Regarding code review from core developers and no access to illumos boxes: I reproduced this on a VM using [a Vagrant image](https://app.vagrantup.com/openindiana/boxes/hipster) recommended by the [OpenIndiana documentation](http://docs.openindiana.org/handbook/getting-started/#vagrant). The steps as I remember them:

1. Do the vagrant up && vagrant ssh dance
2. `sudo pkg install git gcc-10`
3. Clone the repository, `./configure` etc as usual

**Review by asvetlov — APPROVED** [review]

**Comment by jstasiak** [comment]
Thanks @asvetlov, I'll see about manually backporting this to 3.8.

**Comment by asvetlov** [comment]
Welcome!
Up to you, I don't insist at all but happy to merge if the backport exists.

**Comment by asvetlov** [comment]
again sslproto related failure :(
Unrelated to the PR

**Comment by jstasiak** [comment]
Roger. #23246 is a 3.8 backport of this PR.

**Pull request merged**
