### PR TITLE
bpo-35348: Fix platform.architecture()

### PR DESCRIPTION
**Pull request by vstinner**
Fix platform.architecture(): add the -b option to the "file" command.

https://bugs.python.org/issue35348

### CODE REVIEW

**Comment by vstinner** [comment]
I'm not sure if the "file" command supports the -b option on all platforms. It seems like platform used file -b in the past and nobody complained.

**Comment by vstinner** [comment]
@serhiy-storchaka: you wrote PR #11160, but I'm confident that it will be fine to use "file -b -- executable" command. I propose to make this change in the master branch and leave stable branches (2.7 and 3.7) unchanged. If something goes wrong, we can easily revert this change.

**Comment by vstinner** [comment]
I removed "--" from "file -b -- target". If target starts with "-", file will fail since the filename miss. Example:

```
$ file -b -b
Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] <file> ...
       file -C [-m <magicfiles>]
       file [--help]

$ echo $?
1
```

This change should prevent portability issue.

> Could you then borrow other changes from #11160?

Sure. I picked your changes into my PR and I credited you.

I replaced env={'LC_ALL': 'C'} with env=dict(os.environ, LC_ALL='C'). Few programs like to run in an (almost) empty environment.

I wasn't sure if you preferred to push your changes separately or not.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by vstinner** [comment]
I propose to not backport this fix. At least not the addition of the -b flag.

**Pull request merged**
