### PR TITLE
gh-90815: Define WITH_MIMALLOC macro in PC/pyconfig.h

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-90815

### CODE REVIEW

**Comment by vstinner** [comment]
Example of a [recent PR](https://github.com/python/cpython/pull/111522), [test.pythoninfo of Windows x64](https://github.com/python/cpython/actions/runs/6698954837/job/18202162028) says:

```
build.WITH_MIMALLOC: No
```

**Comment by vstinner** [comment]
The build fails on Windows. Example:

```
obmalloc.obj : error LNK2005: _mi_free already defined in alloc.obj [D:\a\cpython\cpython\PCbuild\_freeze_module.vcxproj]
```

cc @DinoV

**Comment by DinoV** [comment]
> The build fails on Windows. Example:
> 
> ```
> obmalloc.obj : error LNK2005: _mi_free already defined in alloc.obj [D:\a\cpython\cpython\PCbuild\_freeze_module.vcxproj]
> ```
> 
> cc @DinoV

I think the issue here is that we're including the files in the Windows build but they're now included via obmalloc.c (this had changed along the way).  I'll let the build bots see if https://github.com/python/cpython/pull/111532 fixes it.

**Comment by vstinner** [comment]
@DinoV wrote the correct fix: https://github.com/python/cpython/pull/111532

**Pull request closed without merging**
