### PR TITLE
remove support for BSD/OS (closes bpo-31624)

### PR DESCRIPTION
**Pull request by benjaminp**
https://bugs.python.org/issue31624

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
Look also at configure.ac:2495, configure.ac:2563, configure.ac:2563, configure.ac:2588, sysconfig.py:636, distutils/util.py:57.

Is BSD/OS and BSDI the same?

**Comment by benjaminp** [comment]
Yes, BSDi is the old name for BSD/OS.

**Comment by serhiy-storchaka** [comment]
Are there supported OS containing a slash in a name?

**Comment by benjaminp** [comment]
I'm not sure. It's possible we can remove that distutils code. However, I didn't want to make a functional change (for non-BSD/OS platforms) in this PR.

**Comment by vstinner** [comment]
FYI I removed MS-DOS support in october 2014: commit b71c7dc9ddd6997be49ed6aaabf99a067e2c0388
https://bugs.python.org/issue22591

```
commit b71c7dc9ddd6997be49ed6aaabf99a067e2c0388
Author: Victor Stinner <victor.stinner@gmail.com>
Date:   Fri Oct 10 11:55:41 2014 +0200

    Issue #22591: Drop support of MS-DOS
    
    Drop support of MS-DOS, especially of the DJGPP compiler (MS-DOS port of GCC).
    
    Today is a sad day. Good bye MS-DOS, good bye my friend :'-(
```

**Comment by vstinner** [comment]
Honestly, I never heard anything about BSD/OS.
https://en.wikipedia.org/wiki/BSD/OS
"Wind River discontinued sales of BSD/OS at the end of 2003, with support terminated at the end of 2004."

Thank you @benjaminp for the cleanup! A few more OSes support removal, and soon we will be close to only support the best OS, Linux! ;-)

**Comment by serhiy-storchaka** [comment]
I am impressed by the amount of special cases for BSD/OS.

**Comment by vstinner** [comment]
> I am impressed by the amount of special cases for BSD/OS.

Hum, look at @tiran commit to remove VMS support: commit af01f668173d4061893148b54a0f01b91c7716c2

```
commit af01f668173d4061893148b54a0f01b91c7716c2
Author: Christian Heimes <christian@cheimes.de>
Date:   Sat Dec 21 16:19:10 2013 +0100

    Issue #16136: Remove VMS support and VMS-related code

 Doc/whatsnew/3.4.rst     |   1 +
 Include/pyerrors.h       |   3 ---
 Lib/test/test_pep3151.py |   2 --
 Misc/NEWS                |   2 ++
 Modules/_cryptmodule.c   |   7 ------
 Modules/fcntlmodule.c    |   4 ----
 Modules/fpectlmodule.c   |  29 ------------------------
 Modules/getpath.c        |   6 +----
 Modules/grpmodule.c      |   5 -----
 Modules/main.c           |  29 ------------------------
 Modules/mmapmodule.c     |   6 -----
 Modules/posixmodule.c    |  23 -------------------
 Modules/pwdmodule.c      |   8 -------
 Modules/selectmodule.c   |  25 +++++++++------------
 Modules/socketmodule.c   | 106 +++++++--------------------------------------------------------------------------------
 Objects/exceptions.c     |   6 -----
 Parser/myreadline.c      |   8 -------
 Python/dynload_shlib.c   |  26 ----------------------
 Python/random.c          |  37 ++++---------------------------
 Python/sysmodule.c       |  19 ----------------
 20 files changed, 27 insertions(+), 325 deletions(-)
```

**Comment by benjaminp** [comment]
RICOS even had its own top-level directory!

**Comment by vstinner** [comment]
macOS has its Mac/ top-level directory, Windows has *two* top-level
directories: PC and PCbuild!

**Pull request merged**
