### PR TITLE
Fix typo in _PyMethodDef_RawFastCallKeywords error message

### PR DESCRIPTION
**Pull request by jdemeyer**
`skip news` and `skip issue` because it's a triviality.

### CODE REVIEW

**Review by matrixise — APPROVED** [review]
Thank you 🙏

**Comment by matrixise** [comment]
@jdemeyer I think we need this PR for 3.7, do you confirm?

**Comment by jdemeyer** [comment]
> I think we need this PR for 3.7, do you confirm?

I doesn't matter that much. But sure, why not?

**Comment by matrixise** [comment]
Thank you @jdemeyer for your contribution.

**Comment by matrixise** [comment]
@jdemeyer the backport has been merged, thanks again

**Pull request merged**
