### PR TITLE
Update shutil.py

### PR DESCRIPTION
**Pull request by YoSTEALTH**
improved "copyfileobj" function to use less memory

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by skrah** [comment]
I know GitHub is not very user friendly, but you can view your pull requests before opening them.

**Comment by skrah** [comment]
Ah, apparently @zware did the right magic now.  Reopening.

**Comment by YoSTEALTH** [comment]
I did run the test and got "Tests result: SUCCESS"

**Comment by zware** [comment]
It looks like you made this change against the 3.6 branch, so I changed the base branch.  However, our workflow is to patch `master` first, then backport to any other applicable branches.  Could you please recreate your pull request as a single commit against the `master` branch?

**Comment by YoSTEALTH** [comment]
@zware I am new to github, i will try and see if i can do what you recommend.

**Comment by bitdancer** [comment]
You also need to open an issue at bugs.python.org (follow the bedevere/issue-number details link for more).

**Pull request closed without merging**
