### PR TITLE
bpo-28367: Add additional baud rates for termios

### PR DESCRIPTION
**Pull request by tonybaloney**
https://bugs.python.org/issue28367

### CODE REVIEW

**Comment by tonybaloney** [comment]
requesting review from @pitrou

**Comment by ZackerySpytz** [comment]
Hi, @tonybaloney. The [developer's guide](https://devguide.python.org/pullrequest/#converting-an-existing-patch-from-b-p-o-to-github) states that one should provide attribution to the original patch author when converting a patch to a pull request.

**Comment by tonybaloney** [comment]
thanks, I put it in the news entry. I wasn't aware of the news entry requirement.

https://github.com/python/cpython/pull/13142/files#diff-1c47238a6c1f8e56b2135b189fd52773R13

**Comment by tonybaloney** [comment]
Revised commit message

**Comment by tonybaloney** [comment]
@Yhg1s please can you review (going by experts index)

**Pull request merged**
