### PR TITLE
Fix typo in Path.iterdir docs

### PR DESCRIPTION
**Pull request by milliams**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@milliams

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by milliams** [comment]
I have now signed the CLA so will wait for the systems to catch up.

**Comment by AlexWaygood** [comment]
> I have now signed the CLA so will wait for the systems to catch up.

Thanks! It could take a few working days -- it needs to be manually reviewed by a human at the PSF :)

It's probably not actually necessary for a typo fix anyway, but having signed it will make future contributions to CPython much less painful :)

**Review by AlexWaygood — APPROVED** [review]

**Review by DanielNoord — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Congratulations on your first contribution to CPython!

**Pull request merged**
