### PR TITLE
[3.4] bpo-34656: Avoid relying on signed overflow in _pickle memos (GH-9261)

### PR DESCRIPTION
**Pull request by vstinner**
(cherry picked from commit a4ae828ee416a66d8c7bf5ee71d653c2cc6a26dd)

https://bugs.python.org/issue34656

### CODE REVIEW

**Comment by vstinner** [comment]
Please double-check this one, I had to fix compilation error on Windows (second commit). cc @mcepl

**Comment by mcepl** [comment]
Yeah, it looks sensible. I had the same problem with Windows compilers myself many times. +1 from me.

**Comment by vstinner** [comment]
> Yeah, it looks sensible. I had the same problem with Windows compilers myself many times. +1 from me.

Can you please officially "approve" the change?

**Comment by vstinner** [comment]
> AppVeyor build succeeded

Aha, my 2nd commit fixed compilation on Windows (and tests pass).

**Comment by mcepl** [comment]
> > Yeah, it looks sensible. I had the same problem with Windows compilers myself many times. +1 from me.
> 
> Can you please officially "approve" the change?

I don't see the button anywhere. I don't think I have any bits required.

**Comment by vstinner** [comment]
> I don't see the button anywhere. I don't think I have any bits required.

Anyone can approve/reject a change: go to the "Files changes" tab and click on [Review changes] button, then select (o) Approve.

**Review by mcepl — APPROVED** [review]
It is basically my original patch (which is running in openSUSE) with additional fixes for Windows compilation. Looks good.

**Comment by mcepl** [comment]
Like this?

**Comment by vstinner** [comment]
> Like this?

Yes! Thanks :-)

**Review by gpshead — APPROVED** [review]

**Comment by larryhastings** [comment]
Thanks for the backport!

**Pull request merged**
