### PR TITLE
gh-76568: Remove ability to import non-version-tagged C extensions

### PR DESCRIPTION
**Pull request by pitrou**
This excludes HP-UX, AIX and Cygwin for which we haven't migrated to version-tagged C extension names.

* Issue: gh-76568

### CODE REVIEW

**Comment by AraHaan** [comment]
What about C extensions in PCbuild\pcbuild.sln? Will those get tagged or no?

**Comment by pitrou** [comment]
@AraHaan you're right. Unfortunately those files are static but the tag is varying (platform-dependent and version-dependent), so I'm not sure how to solve this issue. Perhaps @zooba can help.

**Comment by AraHaan** [comment]
I think the solution is to have ``python.props`` sort out the tag and on the static file ext field have ``.$(PyTag).pyd``

**Comment by pitrou** [comment]
I'm probably unable to do it myself. Would you like to propose a patch?

**Comment by AraHaan** [comment]
oh, looking at python.props it already has this at line 174~176:

```
    <!-- The version and platform tag to include in .pyd filenames -->
    <PydTag Condition="$(ArchName) == 'win32'">.cp$(MajorVersionNumber)$(MinorVersionNumber)-win32</PydTag>
    <PydTag Condition="$(ArchName) == 'amd64'">.cp$(MajorVersionNumber)$(MinorVersionNumber)-win_amd64</PydTag>
```

So basically all I need to do is propose an patch that has ``.$(PydTag).pyd`` on all those project files that builds pyd's.

**Comment by pitrou** [comment]
Thanks for the fix! There seems to be two remaining references in `PCbuild/prepare_ssl.py` and `PCbuild/_testconsole.vcxproj`. Would welcome your help there too, if you are able to try and test changes on Windows :-)

**Comment by pitrou** [comment]
Also, there are now the following warnings when building:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(1199,5): warning MSB8012: TargetExt(.cp37-win32.pyd) does not match the Linker's OutputFile property value (.pyd). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile). [C:\projects\cpython\PCbuild\_hashlib.vcxproj]
```

**Comment by AraHaan** [comment]
Yeah, I just seen those warnings too.

**Comment by AraHaan** [comment]
Seems like test_ssl is crashing too.

**Comment by pitrou** [comment]
I have now reverted the Windows changes. This is now a very simple PR for POSIX systems only.

**Comment by AraHaan** [comment]
Alright, I will will work on the Windows changes eventually though to see if we can get it all to work on Windows too.

**Comment by pitrou** [comment]
@AraHaan, please @zooba's message at https://bugs.python.org/issue32387#msg308878 before attempting anything. We may not want to do any changes on the Windows side.

**Comment by AraHaan** [comment]
Alright, just read it, so the Windows code that was changed here was causing some conflicts.

**Comment by ned-deily** [comment]
See additional comments on bpo-32387.

**Comment by ncoghlan** [comment]
At a technical level, it's a straightforward change, but at a design level, it isn't clear that it's a change worth making given the compatibility risks associated with it: https://bugs.python.org/issue32387#msg311309

So the PR itself is stalled until the design question has been addressed.

**Comment by brettcannon** [comment]
Flagging this a `DO-NOT-MERGE` until the discussion on the issue tracker is resolved.

**Comment by brettcannon** [comment]
Removing the import team from reviewing as the appropriateness of this PR has not been decided yet. We can be added back when it's ready to go.

**Comment by AraHaan** [comment]
I think that the ability to import non-version tagged C extensions should be supported still (for now).

**Comment by arhadthedev** [comment]
> At a technical level, it's a straightforward change, but at a design level, it isn't clear that it's a change worth making given the compatibility risks associated with it: https://bugs.python.org/issue32387#msg311309
>
> So the PR itself is stalled until the design question has been addressed.

Five years passed with no final decision (covering versions 3.5-3.12). Should we recognize that the existing approach is good enough and close this PR and its parent issue for good?

BTW, the last message in the issue is https://github.com/python/cpython/issues/76568#issuecomment-1093771138:

> I think it'd be worth doing on POSIX systems for some 3.8 alpha/beta release cycles before making a final call there.

**Comment by ned-deily** [comment]
At this point, I think it is up to the 3.12 Release Manager (@Yhg1s) to decide what should be done for 3.12 and whether this is a significant enough risk to ask for Steering Council input. While I think such a change would be positive long term, I would be cautious about making it now without more data on potential breakage, especially with the removal of distutils and the increase in the number of alternate package builders in the intervening years. If there were some way to perhaps query file names in existing 3.11 and 3.12 PyPI packages, the risks could be more confidently assessed?

**Comment by AraHaan** [comment]
Honestly at this point, I can see this as potentially breaking for standalone python (with the stlib in a zip file) for windows as well (which would not be a good idea to break as there are people who do not want to install python because not everyone has administrator privileges (think colleges for example) and so they do the next best thing, use python from a zip file that has everything the interpreter needs all in a single folder).

**Comment by Yhg1s** [comment]
Simply removing the support for untagged extension doesn't sound like a reasonable change. I see no reason why this can't follow the normal deprecation process first. (FWIW, Google uses untagged extension modules all over the place, partly because it doesn't use distutils/setuptools to build them but also because it just works, it's simpler that way, nothing ever complains about it and we have no reason to tag them -- we build everything from source and there's no mixing of Python versions.)

**Comment by zooba** [comment]
I don't see why we'd ever want to get rid of it. Certainly we need a longer-than-usual deprecation cycle to change the Windows side (there's currently no supported ABI suffix there for `abi3`, so extensions using the limited API just use `.pyd`) as we need to let all the external build tools catch up with whatever change we make. Besides, Windows will already reject incompatible modules on load, so the main motivation from the original email thread doesn't apply.

But honestly, I can't see why this is a big enough issue to need changing anywhere else either. At most, wherever it's documented (is it even documented?) we could warn "hey, here's how this may bite you, and here's the recommended approach". Unless there's a spate of people being caught by this mildly rough edge that I haven't heard about, I'd just drop the whole idea.

**Comment by arhadthedev** [comment]
I forgot that `distutils` is removed from 3.12 anyway. So proposing features here instead of [pypa/setuptools](https://github.com/pypa/setuptools) has no sense.

**Comment by brettcannon** [comment]
I closed the issue for this due to lack of enthusiasm for the idea, so I'm closing this PR.

**Pull request closed without merging**
