### PR TITLE
gh-121404: rename compiler_addop* to codegen_addop*, and replace direct usages by the macros

### PR DESCRIPTION
**Pull request by iritkatriel**
Also organises them at the top with the macros next to the functions they are invoking.

(e.g., `ADDOP` needed to move before the `codegen_addop_*` functions that now use it).

* Issue: gh-121404

### CODE REVIEW

**Review by picnixz — COMMENTED** [review]
Just to be sure, but you are not introducing new macros right? it's just moving them around right and replacing parts of the code with existing macros? if so, could you maybe consider merging #120018 first so that those macros use do-while constructions and then apply your changes? (you can also first merge your PR and I'll take care of conflicts in my branch if you don't want to be held up).

**Comment by iritkatriel** [comment]
> Just to be sure, but you are not introducing new macros right? it's just moving them around right and replacing parts of the code with existing macros? if so, could you maybe consider merging #120018 first so that those macros use do-while constructions and then apply your changes? (you can also first merge your PR and I'll take care of conflicts in my branch if you don't want to be held up).

I think I added one or two macros with `*_IN_SCOPE`. I forgot about your outstanding PR. We can merge in either order, it should be quite straightforward to resolve.

**Comment by picnixz** [comment]
Let's merge your PR first. It'll be easier for me to solve the conflicts afterwards and that way, you don't have to change this branch in particular (my PR is not outstanding btw but I appreciate the qualifier :smile:)

**Review by markshannon — APPROVED** [review]
Looks good.

**Pull request merged**
