### PR TITLE
gh-102151: Correctly fetch CONFIG_ARGS in Tools/freeze/test/freeze.py

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-102151

### CODE REVIEW

**Review by corona10 — APPROVED** [review]
Awesome LGTM!

**Comment by erlend-aasland** [comment]
Thanks for the review, Dong-hee! I'll wait a day or two for one of the freeze experts to chime in, just in case.

**Review by kumaraditya303 — APPROVED** [review]

**Comment by thesamesam** [comment]
This commit has caused https://bugs.gentoo.org/900429 (and https://bugs.gentoo.org/903890 because of the backport to Python 3.11) but it's unclear to me why yet.

It leads to a PGO build hanging in test_tools (or running very very slowly) until disk is filled and then it'll move on.

**Comment by shr-project** [comment]
From my understanding which I've reported in https://bugs.gentoo.org/900429#c19 this change didn't directly cause the test_tools to hang.

It just fixed another error which was preventing test_tools from starting properly.

Before this it quickly failed with:
```
In file included from config.c:18:
/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha5/temp/test_python_6mu7qr8z/tmp8l4okaqw/cpython/Include/Python.h:12:10: fatal error: pyconfig.h: No such file or directory
   12 | #include "pyconfig.h"
      |          ^~~~~~~~~~~~
```

while with this fix it shows different error and then continues for hours and hours (until killed or runs out of disk space or something):

```
while alpha6 shows an error and then continues for 100+ minutes even with using -j42 (from 64 on my builder):
```
1:44:19 load avg: 1.61 [427/427] test_tools failed (1 error)
creating the script to be frozen at /tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/app.py
copying the source tree into /tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/cpython...
configuring python in /tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-build...
CalledProcessError: Command '['/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/cpython/python', '-c', 'import sysconfig; print(sysconfig.get_config_var("CONFIG_ARGS"))']' returned non-zero exit status 1.
--- STDOUT ---
 
--- STDERR ---
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/cpython/Lib/sysconfig.py", line 740, in get_config_var
    return get_config_vars().get(name)
           ^^^^^^^^^^^^^^^^^
  File "/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/cpython/Lib/sysconfig.py", line 723, in get_config_vars
    _init_config_vars()
  File "/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/cpython/Lib/sysconfig.py", line 670, in _init_config_vars
    _init_posix(_CONFIG_VARS)
  File "/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/cpython/Lib/sysconfig.py", line 536, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'

---- END ----
building python parallel='-j42' in /tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-build...
installing python into /tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-installation...
CalledProcessError: Command '['/usr/bin/make', '-C', '/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-build', 'install']' returned non-zero exit status 2.
--- STDOUT --- 
make[2]: Entering directory '/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-build'
Creating directory /tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-installation/bin
Rebuilding with profile guided optimizations:
Creating directory /tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-installation/include
rm -f profile-clean-stamp
make[2]: Leaving directory '/tmp/tmpfs/portage/dev-lang/python-3.12.0_alpha6/temp/test_python_fx7r8c03/tmplr4kzl3i/python-build'
test test_tools failed

--- STDERR ---
/usr/bin/install: cannot remove '/usr/lib64/libpython3.12.so.1.0': Permission denied
make[2]: *** [Makefile:2031: altbininstall] Error 1
make[2]: *** Waiting for unfinished jobs....

---- END ----

Total duration: 1 hour 44 min
Tests result: FAILURE
```

**Comment by thesamesam** [comment]
Thanks Martin. I'm sorry for the noise - I think there is an issue here, but it might be on our end, and it wasn't introduced by this commit (it just exposed some pre-existing issue).

**Pull request merged**
