### PR TITLE
gh-120602: Support LLVM_VERSION_SUFFIX

### PR DESCRIPTION
**Pull request by xarblu**
PR for #120602 

* Issue: gh-120602

### CODE REVIEW

**Review by savannahostrowski — APPROVED** [review]
Keeping the suffix piece of the regex flexible seems reasonable so this looks good to me, thanks!

**Review by brandtbucher — APPROVED** [review]
Thanks, @xarblu!

**Comment by brandtbucher** [comment]
Can you add a [NEWS entry](https://blurb-it.herokuapp.com/)? Just something simple, like:

```rst
Correctly handle LLVM installs with ``LLVM_VERSION_SUFFIX`` when building with ``--enable-experimental-jit``.
```

**Comment by xarblu** [comment]
@brandtbucher Just added your suggested news entry

**Pull request merged**
