### PR TITLE
bpo-39837: Remove .azure-pipelines/ directory

### PR DESCRIPTION
**Pull request by vstinner**
Remove the Azure Pipelines integration: now superseded by GitHub
actions which already runs the same jobs on Azure as well.

https://bugs.python.org/issue39837

### CODE REVIEW

**Comment by vstinner** [comment]
@zooba @brettcannon: Is there a reason to keep the Azure Pipelines job on GitHub PRs? If not, would mind to have a look at this PR?

This PR removes .azure-pipelines/ directory which contains 32 files:

```
ci.yml
docs-steps.yml
macos-steps.yml
posix-deps-apt.sh
posix-steps.yml
pr.yml
prebuild-checks.yml
windows-layout-steps.yml
windows-release.yml
windows-release/build-steps.yml
windows-release/checkout.yml
windows-release/find-sdk.yml
windows-release/gpg-sign.yml
windows-release/layout-command.yml
windows-release/mingw-lib.yml
windows-release/msi-steps.yml
windows-release/stage-build.yml
windows-release/stage-layout-embed.yml
windows-release/stage-layout-full.yml
windows-release/stage-layout-msix.yml
windows-release/stage-layout-nuget.yml
windows-release/stage-msi.yml
windows-release/stage-pack-msix.yml
windows-release/stage-pack-nuget.yml
windows-release/stage-publish-nugetorg.yml
windows-release/stage-publish-pythonorg.yml
windows-release/stage-publish-store.yml
windows-release/stage-sign.yml
windows-release/stage-test-embed.yml
windows-release/stage-test-msi.yml
windows-release/stage-test-nuget.yml
windows-steps.yml
```

I don't know if .github/workflows/ is related to GitHub actions for Azure or not:

```
$ ls .github/workflows/
build.yml  coverage.yml  doc.yml  posix-deps-apt.sh*
```

**Comment by vstinner** [comment]
Hum, there is still a "Azure Pipelines PR" job on this PR. Maybe something should be changed in https://github.com/python/cpython/ administration page to disable/remove Azure Pipelines.

**Comment by brettcannon** [comment]
If we decide to merge this I have to switch off the required status check for Azure Pipelines and turn it on for GH Actions.

**Comment by vstinner** [comment]
> If we decide to merge this I have to switch off the required status check for Azure Pipelines and turn it on for GH Actions.

Oh, I expected GH Actions to also be required. Is it possible to choose per job? Like having Windows (x64) required, but macOS "non voting" (not required) for example? The macOS job on Azure had some issues in the last months (seems to be solved now, but it's just an example).

**Comment by vstinner** [comment]
https://bugs.python.org/issue39837#msg363289

**Pull request closed without merging**
