### PR TITLE
gh-127082: Replace "Windows only: ..." with the `.. availability:: Windows` directive in `ctypes` doc.

### PR DESCRIPTION
**Pull request by junkmd**
This is a follow-up to gh-126615.

* Issue: gh-127082

----
📚 Documentation preview 📚: https://cpython-previews--127099.org.readthedocs.build/

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM but it would be better to not reformat paragraphs to keep the change as small as possible: only change the first line of the modified paragraphs.

**Review by Eclips4 — APPROVED** [review]
LGTM. +1 to Victor's words.

**Comment by vstinner** [comment]
Merged, thanks.

Backports to 3.12 and 3.13 failed with a conflict. Do you want to try to backport the change manually to 3.13?

**Comment by junkmd** [comment]
The replacement with directives included the newly added `COMError` in #126686.
Since the `COMError` section did not exist prior to Python 3.14, this likely caused the conflict.


> Do you want to try to backport the change manually to 3.13?


Yes.
Please let me know what I should do.

**Comment by junkmd** [comment]
I’ll try using cherry_picker as suggested by the miss-islington app.

**Pull request merged**
