### PR TITLE
bpo-32221: makeipaddr(): remove interface part + speedup (GH-5449)

### PR DESCRIPTION
**Pull request by socketpair**
https://bugs.python.org/issue32221

### CODE REVIEW

**Comment by socketpair** [comment]
@1st1 I fixed only tests comparing to previous try. Please review, but don't merge. I will double-check Linux, Windows and Mac OS X builds by hand. I will notify you when my manual checks will be done.

**Comment by socketpair** [comment]
@1st1 everything works as expected. Please review again and merge.

**Comment by socketpair** [comment]
Again: only tests were changed.

**Comment by socketpair** [comment]
@1st1

**Comment by socketpair** [comment]
@1st1 ping

**Comment by socketpair** [comment]
:(

**Comment by socketpair** [comment]
@1st1 @asvetlov What  should I do in order to merge that ?

**Comment by 1st1** [comment]
Please be a bit more patient.  I was offline the last 10 days and couldn't take care of this.

**Pull request merged**
