### PR TITLE
bpo-24739: allow argparse.FileType to accept 'newline' keyword argument

### PR DESCRIPTION
**Pull request by iamalbert**
allow argparse.FileType to accept 'newline' keyword argument

### CODE REVIEW

**Review by phispi — COMMENTED** [review]
I would include ('newline', self._newline) in kwargs (line 1194).

**Comment by berkerpeksag** [comment]
Thanks for the PR! Please see http://bugs.python.org/issue24739#msg291941 for the details about the rejection.

**Comment by phispi** [comment]
Hmmm. In many of my small programs using the argparse and csv modules together I have implemented my own version of `argparse.FileType` (to support `newline=''`). At the end I decided to make a pull request - just to realize that it has already been done a few days before.

I don't really understand why this was rejected. The few more characters `argparse.FileType` grows enable the interaction of modules within the standard library. A unittest is provided as well. In http://bugs.python.org/issue24739#msg291941 two arguments are given:

- `argparse.FileType` should serve as an example of user defined types. It still does after accepting this pull request because the change doesn't make `argparse.FileType` more complicated.
- User `paul.j3` who's post was cited as explanation of the reject did not (as I understand it) recommend not to do the change - he just lists the options: 

> I suppose it could be modified to accept the full range of parameters that the modern 'open' takes:
>
>    open(file, mode='r', buffering=-1, encoding=None,
>       errors=None, newline=None, closefd=True, opener=None) 
>
> either explicitly, or as a pass through **kwargs.
>
> But it is also something that you could easily subclass or modify for your own purposes.

At the time he wrote this there was no patch/merge request available.

I would recommend to reconsider the decision - at least I see plenty advantages of having this merged and no disadvantages. In case you need people doing an update of the documentation page, I volunteer.

**Comment by Horb** [comment]
No idea why this was snubbed. `FileType` is clearly just a cute wrapper around `open`. Half the interface should not be arbitrarily hidden when such a succinct PR was provided. Here's the kind of hackery that turning something like this down creates;

```
parser.add_argument('-i', '--input', nargs='?',
                    type=lambda s: sys.stdin if '-' == s else open(s, 'r'),
                    default=sys.stdin)
parser.add_argument('-o',
                    '--output',
                    nargs='?',
                    type=lambda s: sys.stdout if '-' == s else open(s, 'w', newline=''),
                    default=sys.stdout)
```

**Pull request closed without merging**
