### PR TITLE
bpo-29162: IDLE: import sys before we use it on line 9

### PR DESCRIPTION
**Pull request by JelleZijlstra**

### CODE REVIEW

**Review by Mariatta — APPROVED** [review]

**Comment by terryjreedy** [comment]
Thank you both for the catch and review.  This is a continuation of bpo-29162 (correct spelling?) and its incomplete fix.  This time, there is no substitute for moving the import of sys.  

Can either of you modify the title appropriately, so this will (maybe) get linked to the issue?  I have not yet gotten up to speed with git and github.  I will then hit [Squash and merge].

3.6 is the only backport needed, and no revision will be needed.

**Comment by terryjreedy** [comment]
Can one of you do the backport/cherry-pick?

**Comment by Mariatta** [comment]
Thanks for the merge, @terryjreedy :) I'll backport this to 3.6

**Comment by Mariatta** [comment]
backport PR at GH-828

**Comment by Mariatta** [comment]
Wrong link earlier. Backport PR was at GH-833, and it's been merged to 3.6.

Thanks :)

**Pull request merged**
