### PR TITLE
GH-98831: Elaborate some cases_generator tests

### PR DESCRIPTION
**Pull request by gvanrossum**
@Fidget-Spinner The first commit is an example of the (current) output for a macro instruction.

* Issue: gh-98831

### CODE REVIEW

**Comment by gvanrossum** [comment]
PS To run these tests, install pytest and run it in the Tools/cases_generator directory. (That's kind of lame, but pytest tests are so much easier to write. :-)

**Comment by Fidget-Spinner** [comment]
Ahh ok. So that's how you deal with colliding declarations.

I proposed the alternative (where we define instructions as `prelude`s, `test`s, and `rest` using labels) because I didn't like the redundant work done for a macro instruction when it combines the micro instructions together. (an example that's not in this PR would be reading from the cache twice)

**Comment by gvanrossum** [comment]
> However, I think I would have to modify the interpreter generator to make that work.

I'd be happy to review such changes. I'll continue the design discussion on the other issue. Meanwhile, I'll just merge this one.

**Comment by gvanrossum** [comment]
That buildbot is out of disk space.

**Pull request merged**
