### PR TITLE
gh-100049: fix `repr` for `mappingproxy` in dictionary view example doc

### PR DESCRIPTION
**Pull request by ramvikrams**
gh-100049: the output is changed for dictionary view objects example in the `doc/library/stdtypes.rst`

### CODE REVIEW

**Comment by eklunko** [comment]
@ramvikrams
You suggest the fix as follows:
```
- mappingproxy({'eggs': 2, 'sausage': 1, 'bacon': 1, 'spam': 500})
+ {'bacon': 1, 'spam': 500}
```
It seems the correct fix would be:
```
- mappingproxy({'eggs': 2, 'sausage': 1, 'bacon': 1, 'spam': 500})
+ mappingproxy({'bacon': 1, 'spam': 500})
```

**Comment by ramvikrams** [comment]
> @ramvikrams
> You suggest the fix as follows:
> ```
> - mappingproxy({'eggs': 2, 'sausage': 1, 'bacon': 1, 'spam': 500})
> + {'bacon': 1, 'spam': 500}
> ```
> It seems the correct fix would be:
> ```
> - mappingproxy({'eggs': 2, 'sausage': 1, 'bacon': 1, 'spam': 500})
> + mappingproxy({'bacon': 1, 'spam': 500})
> ```
Thanks I'll fix it

**Review by kumaraditya303 — APPROVED** [review]

**Comment by kumaraditya303** [comment]
Thanks

**Comment by ramvikrams** [comment]
> Thanks

Thank you

**Pull request merged**
