### PR TITLE
bpo-33018: Improve issubclass() error checking and message.

### PR DESCRIPTION
**Pull request by jab**
If you try something like `issubclass('not a class', str)`, you get a helpful error message that immediately clues you in on what you did wrong:

```python
>>> issubclass('not a class', str)
TypeError: issubclass() arg 1 must be a class
```

("AHA! I meant *isinstance* there. Thanks, friendly error message!")

But if you try this with some ABC, the error message is much less friendly!
```python
>>> from some_library import SomeAbc
>>> issubclass('not a class', SomeAbc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 230, in __subclasscheck__
    cls._abc_negative_cache.add(subclass)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_weakrefset.py", line 84, in add
    self.data.add(ref(item, self._remove))
TypeError: cannot create weak reference to 'str' object
```

("WTF just went wrong?" Several more minutes of head-scratching ensues. Maybe a less experienced Python programmer who hits this hasn't seen weakrefs before and gets overwhelmed, maybe needlessly proceeding down a deep rabbit hole before realizing no knowledge of weakrefs was required to understand what they did wrong.)

Or how about this example:

```python
>>> from collections import Reversible
>>> issubclass([1, 2, 3], Reversible)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_collections_abc.py", line 305, in __subclasshook__
    return _check_methods(C, "__reversed__", "__iter__")
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_collections_abc.py", line 73, in _check_methods
    mro = C.__mro__
AttributeError: 'list' object has no attribute '__mro__'
```

Here you don't even get the same *type* of error (`AttributeError` rather than `TypeError`), which seems unintentionally inconsistent.

This trivial patch fixes this, and will hopefully save untold numbers of future Python programmers some time and headache.

Let me know if any further changes are required, and thanks in advance for reviewing.

https://bugs.python.org/issue33018

### CODE REVIEW

**Comment by jab** [comment]
Here's a build with this patch applied showing the fix in action:
```
Python 3.8.0a0 (heads/master-dirty:f0daa880a4, Mar  1 2018, 10:46:05)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections.abc import Reversible
>>> issubclass([1, 2, 3], Reversible)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/_pants/tmp/cpython/Lib/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Comment by zhangyangyu** [comment]
Check bpo-32999 please, some core devs don't want to limit the first arg only to type objects.

**Comment by methane** [comment]
Please create new issue and discuss on it.

**Comment by jab** [comment]
https://bugs.python.org/issue33018

**Review by ilevkivskyi — APPROVED** [review]
Thanks! I think this looks good. Could you please add a NEWS item?

**Review by methane — CHANGES_REQUESTED** [review]
Would you revert fc7df0e664198cb05cafd972f190a18ca422989c too?

`((PyTypeObject *)subclass)->tp_mro` must be valid tuple.

**Comment by ilevkivskyi** [comment]
> Would you revert fc7df0e too?

I don't think we need to revert it. First of all the tests should stay, so I would just make another PR in addition to this one. Or you want to add the change to `->tp_mro` to this PR?

**Comment by methane** [comment]
> I don't think we need to revert it. First of all the tests should stay, so I would just make another PR in addition to this one. Or you want to add the change to ->tp_mro to this PR?

Yes.  I didn't mean revert adding test.
I want to minimize diff between 3.7 and 3.8 as possible at this time.
It's OK to make another change (before 3.7b3) to use `->tp_mro` if it will be merged into 3.7 branch too.

**Comment by jab** [comment]
Just added the NEWS entry: I have made the requested changes; please review again.

First time (getting a patch accepted (🎉!) and) using `blurb`. Hopefully that turned out ok.

Thanks for helping to get this landed!

**Review by methane — APPROVED** [review]
OK, I will create another PR later.

**Comment by ilevkivskyi** [comment]
@methane 
> OK, I will create another PR later.

Thanks! Don't forget to backport your PR to 3.7, as I am backporting this one to 3.7 as @gvanrossum suggested.

**Review by ilevkivskyi — APPROVED** [review]
LGTM, thanks!

**Comment by ilevkivskyi** [comment]
@jab Congrats on your first contribution!

**Comment by jab** [comment]
Thanks for making it possible!

**Pull request merged**
