### PR TITLE
gh-111277: In summarize_stats.py, don't fail fast on invalid ratios

### PR DESCRIPTION
**Pull request by mdboom**
* Issue: gh-111277

### CODE REVIEW

**Comment by markshannon** [comment]
Don't we want to fail if the denominator is zero? That seems like a logic bug to me.

**Review by gvanrossum — APPROVED** [review]
I'll merge. Do you need this backported?

**Comment by gvanrossum** [comment]
Actually let me wait until you have answered Mark's question about `den == 0` being an error.

**Comment by mdboom** [comment]
> Don't we want to fail if the denominator is zero? That seems like a logic bug to me.

I thought so too, but the tricky bit is that logic bug, if it happens, happens *way over* during stats collection at Python runtime.  If we fail hard here, we don't get any stats out at all.  With this change, we know there is an error (the `!!`), but we can at least see everything else and attempt to fix the error within CPython.

**Pull request merged**
