### PR TITLE
bpo-27141: Fix collections.UserList and UserDict shallow copy

### PR DESCRIPTION
**Pull request by bharel**
Hey guys, fixed according to the requested method.

https://bugs.python.org/issue27141

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by bharel** [comment]
Hello dear bots, I've updated my bpo profile to include my github username, I do have a CLA :-)
I did not update the news however. Doing so right now. Thank you lovely bots for reminding me. :-)

**Comment by icemac** [comment]
I stumbled across this issue today while having the same problem as described in zopefoundation/persistent#42. This PR seems reasonable to me and should fix the problem.
What needs to be done to get it merged into master?

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by icemac** [comment]
@serhiy-storchaka Thank you for the approval of the PR. What would be the next steps to get it merged?

**Pull request merged**
