### PR TITLE
GH-79033: Fix asyncio.Server.wait_closed()

### PR DESCRIPTION
**Pull request by gvanrossum**
wait_closed() was a no-op when used as recommended (after close()).

I had to debug one test (test__sock_sendfile_native_failure) -- the cleanup sequence for the test fixture was botched.

Hopefully that's not a portend of problems in user code -- this has never worked so people may well be doing this wrong. :-(

* Issue: gh-79033

### CODE REVIEW

**Comment by gvanrossum** [comment]
Needs test and news entry

**Comment by gvanrossum** [comment]
@kumaraditya303 Can you suggest a test for this?

**Comment by kumaraditya303** [comment]
Something like should work: 
```diff
diff --git a/Lib/test/test_asyncio/test_server.py b/Lib/test/test_asyncio/test_server.py
index 860d62d52e..ceea4059ae 100644
--- a/Lib/test/test_asyncio/test_server.py
+++ b/Lib/test/test_asyncio/test_server.py
@@ -120,6 +120,26 @@ async def main(srv):
                 self.loop.run_until_complete(srv.serve_forever())
 
 
+class TestServer2(unittest.IsolatedAsyncioTestCase):
+
+    async def test_wait_closed(self):
+        async def serve(*args):
+            pass
+
+        srv = await asyncio.start_server(serve, socket_helper.HOSTv4, 0)
+
+        # active count = 0
+        wait = asyncio.create_task(srv.wait_closed())
+        await asyncio.sleep(0)
+        self.assertTrue(wait.done())
+
+        # active count != 0
+        srv._attach()
+        wait = asyncio.create_task(srv.wait_closed())
+        await asyncio.sleep(0)
+        self.assertFalse(wait.done())
+
+
 @unittest.skipUnless(hasattr(asyncio, 'ProactorEventLoop'), 'Windows only')
 class ProactorStartServerTests(BaseStartServer, unittest.TestCase):
 

```

Creating a test with an actual client seems rather flaky as it requires a heavy load on server so will be unreliable.

**Comment by gvanrossum** [comment]
Thanks! `_attach` exists for the transport to indicate that it's active. We should probably also call `_detach` (after closing the server) and then check that the `wait_closed` task finishes.

**Review by kumaraditya303 — APPROVED** [review]
LGTM, thanks!

**Comment by gvanrossum** [comment]
Let’s not backport, I fear it will surprise some users since it never worked.

**Pull request merged**
