### PR TITLE
bpo-42128: Add 'missing :' syntax error message to match statements

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue42128

### CODE REVIEW

**Review by gvanrossum — COMMENTED** [review]
Is this safe? While `match x` is invalid, `match (x)` should be a function call.

**Comment by pablogsal** [comment]
> Is this safe? While `match x` is invalid, `match (x)` should be a function call.

Hummmm, that's a good point. if `match(x)` is by itself this will probably fail. Let me think how can we workaround that

**Comment by pablogsal** [comment]
I will add also a test for that case

**Comment by pablogsal** [comment]
Fixed in the last ammend

**Comment by brandtbucher** [comment]
For my own understanding... does double-ampersand raise a SyntaxError at that token's location suggesting it if it doesn't exist? That's really nice.

**Comment by pablogsal** [comment]
> For my own understanding... does double-ampersand raise a `SyntaxError` at that token's location suggesting it if it doesn't exist? That's really nice.

Yeah, is a "forced token" operator. Notice that it also hard-stops the parsing: no other alternative will be considered.

**Review by gvanrossum — COMMENTED** [review]
I don't understand why e.g. `match(1)` doesn't reach `invalid_match_stmt`, so I'm still concerned.

**Comment by pablogsal** [comment]
> I don't understand why e.g. `match(1)` doesn't reach `invalid_match_stmt`, so I'm still concerned.

The `invalid_*` rules are now only checked in a second pass of the parser if the first one fails.

**Review by gvanrossum — APPROVED** [review]
Ehh! I totally forgot about that!

**Comment by brandtbucher** [comment]
Does `invalid_match` Still need to be guarded with `CHECK_VERSION`?

**Comment by pablogsal** [comment]
> Does `invalid_match` still need to be guarded with `CHECK_VERSION`?

Not really because is a syntax error, but it certainly won't hurt.

**Review by brandtbucher — APPROVED** [review]
Thanks!

**Pull request merged**
