### PR TITLE
gh-103731: Remove checks for TCL_WIDE_INT_TYPE

### PR DESCRIPTION
**Pull request by chrstphrchvz**
* Issue: gh-103731

### CODE REVIEW

**Review by nanjekyejoannah — COMMENTED** [review]
Is this something we can have a  test for, if possible.
cc @ronaldoussoren

**Comment by chrstphrchvz** [comment]
I do not think there is anything that can be tested for this change beyond whether _tkinter.c still compiles. Preprocessed _tkinter.c should be identical except for line numbers.

tcl.h has:

```c
typedef TCL_WIDE_INT_TYPE		Tcl_WideInt;
typedef unsigned TCL_WIDE_INT_TYPE	Tcl_WideUInt;
```

If `TCL_WIDE_INT_TYPE` was somehow not available, then `Tcl_WideInt` would not be available either, which would cause `fromWideIntObj()` in _tkinter.c to not compile.

**Review by nanjekyejoannah — APPROVED** [review]

**Review by nanjekyejoannah — COMMENTED** [review]
I am inclined to accept this change since we dont do the check in `fromWideIntObj()` too. 
I am trying to verify something about the tcl requirement before merge.

**Comment by nanjekyejoannah** [comment]
I confirm the dependency requirement but curious if we need a doc update for purposes of other things @serhiy-storchaka like what Victors does here: https://docs.python.org/dev/using/configure.html#build-requirements

I can merge this PR without this other dep doc nevertheless.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
It is a pure cosmetic change which makes the code cleaner. Perhaps these checks were never needed at first place. It has no effect on the end users.

**Pull request merged**
