### PR TITLE
GH-101291: Refactor the `PyLongObject` struct

### PR DESCRIPTION
**Pull request by markshannon**
There is no change to the implementation, apart from the refactoring of the struct. Even the binary layout remains the same.

This is the first step in improving int performance. The real changes will come later, but this PR will help keep later PR small and manageable.

* Issue: gh-101291

### CODE REVIEW

**Review by mdickinson — APPROVED** [review]
Changes seem fine to me, though it's a little bit disturbing to see how much the longobject internals have leaked into the rest of the codebase.

Have we looked into the possible impact of these changes on 3rd party libraries? Most shouldn't care, but I'd imagine it'll affect Cython at least, and possibly also things like NumPy and gmpy2.

**Comment by markshannon** [comment]
> Changes seem fine to me, though it's a little bit disturbing to see how much the longobject internals have leaked into the rest of the codebase.

It is, but at least it gives us a guide for what API functions we need to add.

> Have we looked into the possible impact of these changes on 3rd party libraries? Most shouldn't care, but I'd imagine it'll affect Cython at least, and possibly also things like NumPy and gmpy2.

I guess we need to clearly document the changes and recommended API functions.
I will do that in the next PR.

**Comment by tacaswell** [comment]
>  but I'd imagine it'll affect Cython at least,

Does indeed hit cython!  Can not tell if it hits numpy independent of cython because the cythonized files fail to build.

**Comment by encukou** [comment]
> I guess we need to clearly document the changes and recommended API functions.
> I will do that in the next PR.

Did you get around to this? I can't see it in What's New.

**Pull request merged**
