### PR TITLE
dict insertion order is guaranteed since 3.7

### PR DESCRIPTION
**Pull request by andresdelfino**

### CODE REVIEW

**Review by rhettinger — APPROVED** [review]

**Comment by tirkarthi** [comment]
I think auto merge is not triggered here since 2 checks fail with issue number and news entry. Maybe adding skip-news and skip-issue labels will help.

**Comment by andresdelfino** [comment]
> I think auto merge is not triggered here since 2 checks fail with issue number and news entry. Maybe adding skip-news and skip-issue labels will help.

I don't think so, this PR didn't have those labels and it was automerged:

https://github.com/python/cpython/pull/10098

**Comment by tirkarthi** [comment]
The linked PR had both an issue number and a NEWS entry so it didn't require those labels and all checks passed. skip label is required when there is no issue in title and adding it makes the check pass and same for skip news. I hope it's the reason auto merge doesn't but I might be wrong.

**Comment by andresdelfino** [comment]
> The linked PR had both an issue number and a NEWS entry so it didn't require those labels and all checks passed. skip label is required when there is no issue in title and adding it makes the check pass and same for skip news. I hope it's the reason auto merge doesn't but I might be wrong.

I see, sorry :sweat_smile:

**Comment by andresdelfino** [comment]
> The linked PR had both an issue number and a NEWS entry so it didn't require those labels and all checks passed. skip label is required when there is no issue in title and adding it makes the check pass and same for skip news. I hope it's the reason auto merge doesn't but I might be wrong.

You are right, reading the source tells miss-islington excepts those checks to be successful too:

https://github.com/python/miss-islington/blob/2e69ff6506767bbfa6436585bfdad9d43f888ced/miss_islington/status_change.py#L98

**Comment by tirkarthi** [comment]
No problem, TIL for me :)

**Comment by Mariatta** [comment]
Yes, the PR will only be automerge if:
- all status checks passed,
- and it's been approved by core dev, 
- and CLA has been signed.

**Pull request merged**
