### PR TITLE
bpo-46852: Building Python requires IEEE 754 support

### PR DESCRIPTION
**Pull request by vstinner**
Building Python now requires IEEE 754 (floating point) support.

sys.float_repr_style is now always 'short'.

Remove the _PY_SHORT_FLOAT_REPR macro.

https://bugs.python.org/issue46852

### CODE REVIEW

**Comment by vstinner** [comment]
@mdickinson: Is it ok to require an implementation of the HAVE_PY_SET_53BIT_PRECISION macro if the X87_DOUBLE_ROUNDING macro is defined? I'm not sure about the error message:

```
// Double rounding is symptomatic of use of extended precision on x86.
// If we're seeing double rounding, and we don't have any mechanism available
// for changing the FPU rounding precision, then don't use Python/dtoa.c.
#if defined(X87_DOUBLE_ROUNDING) && !defined(HAVE_PY_SET_53BIT_PRECISION)
#  error "Building Python requires IEEE 754 support"
#endif
```

**Comment by mdickinson** [comment]
@vstinner The change you're making here is stronger than merely requiring IEEE 754. This change will break CPython on platforms where:

- The platform _does_ use IEEE 754 floating-point
- The FPU being used is an Intel x87 or something like it (e.g., think 32-bit Linux)
- The `HAVE_PY_SET_53BIT_PRECISION` and associated macros are not defined.

Such platforms have certainly existed historically.

**Comment by mdickinson** [comment]
> Is it ok to require an implementation of the HAVE_PY_SET_53BIT_PRECISION macro if the X87_DOUBLE_ROUNDING macro is defined?

No, I don't think it's okay, at least not without any warning.

**Comment by mdickinson** [comment]
> Such platforms have certainly existed historically.

Here's an example report: https://stackoverflow.com/questions/29920294/what-causes-pythons-float-repr-style-to-use-legacy

> On an [ARM926EJ-S](http://www.arm.com/products/processors/classic/arm9/arm926.php), you don't get the short representation:

**Comment by mdickinson** [comment]
@vstinner You've linked this PR to https://bugs.python.org/issue46852, but that issue looks completely different. This PR goes _way_ beyond anything to do with removing `float.__setformat__`. Please could you fix?

**Comment by vstinner** [comment]
I misunderstood the relationship between requiring IEEE 754 support and the ability to get short float repr. I started from:

```
#if !defined(DOUBLE_IS_LITTLE_ENDIAN_IEEE754) && \
    !defined(DOUBLE_IS_BIG_ENDIAN_IEEE754) && \
    !defined(DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754)
#  define _PY_SHORT_FLOAT_REPR 0
#endif
```

And then followed the breadcrumb.

**Pull request closed without merging**
