### PR TITLE
bpo-30947: Update libexpat from 2.2.1 to 2.2.3

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue30947

### CODE REVIEW

**Comment by vstinner** [comment]
The CI checks failed because of patchcheck: see https://bugs.python.org/issue31221

**Review by gpshead — APPROVED** [review]
seems sane.  i'm not reviewing the changed to expat itself, just that it appears to be a rational update.  you might also consider checking in your cpython_rebuild_expat_dir.sh script that you've attached to the bpo issue.

**Comment by vstinner** [comment]
@gpshead: "you might also consider checking in your cpython_rebuild_expat_dir.sh script that you've attached to the bpo issue."

My script is crappy: the version is hardcoded and uses the libexpat tag format, it requires a libexpat repository with an hardcoded path on my disk, etc. :-) I'm not interested to include it right now.

cc @serhiy-storchaka

**Comment by vstinner** [comment]
Oh, compilation fails on Travis CI at:

```

#if !defined(HAVE_GETRANDOM) && !defined(HAVE_SYSCALL_GETRANDOM) \
    && !defined(HAVE_ARC4RANDOM_BUF) && !defined(HAVE_ARC4RANDOM) \
    && !defined(XML_DEV_URANDOM) \
    && !defined(_WIN32) \
    && !defined(XML_POOR_ENTROPY)
# error  \
    You do not have support for any sources of high quality entropy \
    enabled.  For end user security, that is probably not what you want. \
    \
    Your options include: \
      * Linux + glibc >=2.25 (getrandom): HAVE_GETRANDOM, \
      * Linux + glibc <2.25 (syscall SYS_getrandom): HAVE_SYSCALL_GETRANDOM, \
      * BSD / macOS >=10.7 (arc4random_buf): HAVE_ARC4RANDOM_BUF, \
      * BSD / macOS <10.7 (arc4random): HAVE_ARC4RANDOM, \
      * libbsd (arc4random_buf): HAVE_ARC4RANDOM_BUF + HAVE_LIBBSD, \
      * libbsd (arc4random): HAVE_ARC4RANDOM + HAVE_LIBBSD, \
      * Linux / BSD / macOS (/dev/urandom): XML_DEV_URANDOM \
      * Windows (RtlGenRandom): _WIN32. \
    \
    If insist on not using any of these, bypass this error by defining \
    XML_POOR_ENTROPY; you have been warned. \
    \
    For CMake, one way to pass the define is: \
        cmake -DCMAKE_C_FLAGS="-pipe -O2 -DHAVE_SYSCALL_GETRANDOM" . \
    \
    If you have reasons to patch this detection code away or need changes \
    to the build system, please open a bug.  Thank you!
#endif
```

**Pull request merged**
