### PR TITLE
bpo-41371: Handle lzma lib import error in test_zoneinfo.py

### PR DESCRIPTION
**Pull request by nmaynes**
https://bugs.python.org/issue41371

Automerge-Triggered-By: @pganssle

### CODE REVIEW

**Comment by nmaynes** [comment]
My apologies for the possible deluge of notifications. I messed up the commit history and cleaned it up inefficiently to put it lightly. This should have the approach mentioned by vstinner on issue https://bugs.python.org/issue41476

**Review by rougeth — APPROVED** [review]

**Review by tirkarthi — APPROVED** [review]
LGTM, thanks. Note, `import_helper` is not present in 3.9 and hence automatic backport might fail.

**Comment by nmaynes** [comment]
I am happy to do the backport for this PR as long as my understanding is correct. According to the "[Accepting Pull Requests](https://devguide.python.org/committing/#backporting-changes-to-an-older-version)" document, once the PR is merged, another PR should be created that backports this fix to 3.9. The backport PR title should be "[3.9] bpo-41371: Handle lzma lib import error in test_zoneinfo.py" Am I understanding the process correctly?

**Comment by pganssle** [comment]
@nmaynes You don't have to worry about the backport, the label is a signal that triggers a bot that does it automatically on merge.

**Review by pganssle — APPROVED** [review]

**Pull request merged**
