### PR TITLE
gh-104372: Cleanup _posixsubprocess `make_inheritable` for async signal safety

### PR DESCRIPTION
**Pull request by gpshead**
We move all of the Python C API calls into the parent process up front instead of doing `PyLong_AsLong` and `PyErr_Occurred` and `PyTuple_GET*` from the post-fork/vfork child process.

Much of this was long overdue. We shouldn't have been using PyTuple and PyLong APIs within all of the lower level functions anyways.

* Issue: gh-104372

### CODE REVIEW

**Comment by gpshead** [comment]
This is a code cleanup that https://github.com/python/cpython/pull/104515 mentions as desirable so that a nicer PR can be made for the larger issue.

**Comment by Eclips4** [comment]
Fails in test_gzip, test_httpservers, test_nntplib, test_tarfile, test_xmlrpc related to isolation of io module.

**Comment by gpshead** [comment]
!buildbot root

**Comment by gpshead** [comment]
!buildbot Debian root

**Comment by gpshead** [comment]
!buildbot AMD64 Debian root

**Comment by gpshead** [comment]
!buildbot AMD64 Debian root

**Pull request merged**
