### PR TITLE
gh-90994: Improve error messages upon call arguments syntax errors

### PR DESCRIPTION
**Pull request by lysnikolaou**
* Issue: gh-90994

Automerge-Triggered-By: GH:pablogsal

### CODE REVIEW

**Comment by lysnikolaou** [comment]
@pablogsal friendly ping.

**Comment by pablogsal** [comment]
I am terribly sorry for the delay @lysnikolaou. Somehow this has fly under my radar :(

**Comment by pablogsal** [comment]
@lysnikolaou I have fixed for you a conflict in `Parser/parser.c` (I have rebased this PR)

**Review by pablogsal — APPROVED** [review]
🚀 Excellent work!

**Comment by lysnikolaou** [comment]
Thanks for the review @pablogsal! Merging this by hand since Azure pipelines failed.

**Pull request merged**
