### PR TITLE
gh-96197: Add `del sys.breakpointhook` behavior test

### PR DESCRIPTION
**Pull request by youknowone**
* Issue: gh-96197

### CODE REVIEW

**Review by corona10 — COMMENTED** [review]
I would like to check PyPy's behavior also.

**Comment by youknowone** [comment]
```
Python 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Mar 29 2022, 09:54:47)
[PyPy 7.3.9 with GCC Apple LLVM 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import sys
>>>> del sys.breakpointhook 
>>>> breakpoint()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: lost sys.breakpointhook
>>>> 
```
I think this is not a part to leave as implementation details. Debugging tools will expect a single way to check problems across multiple python versions.

**Comment by corona10** [comment]
> I think this is not a part to leave as implementation details. 

This could be. I needed to check what's happening on PyPy we del the `sys.breakpointhook`.
But looks same.

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by youknowone** [comment]
It could be, but it should not be. This is a sort of external api

**Pull request merged**
