### PR TITLE
Spell Bitbucket correctly

### PR DESCRIPTION
**Pull request by bittner**
Automerge-Triggered-By: @Mariatta

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@bittner

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by bittner** [comment]
I have now signed the contributor agreement and added my GitHub user name to my Python.org account.

### Side note

Unfortunately, due to the slightly unclear login form, I accidentally created an additional account ("Peter Bittner"). I didn't find a way to delete that account again, though. Can some admin do that on my behalf?

**Comment by bittner** [comment]
Related to this change, I have a question:

* Is there a reason why the @PyPA has repositories on GitHub and Bitbucket, but not on GitLab? (This paragraph in the docs is probably aged, and the characteristics of the main VCS's have changed over time.)

Should we mirror some of the PyPA's repositories to GitLab, at least? (I'm not sure where is the right place to ask this. Please, apologize if this question disturbs.)

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks for the PR, once we have record that CLA has been signed, the PR will be automatically approved.

Re question about GitLab mirror for pypa, this is not the place to ask about it.
Perhaps try the pypa project: https://github.com/pypa

**Review by eamanu — APPROVED** [review]

**Comment by bittner** [comment]
Have I done something wrong with the CLA? I even signed it twice, and it's still declared "not signed".

Is there some manual process involved? And we just need to be patient?

**Comment by Mariatta** [comment]
@bittner the user https://bugs.python.org/user32717 in bpo does not have GitHub username associated, without it we can't tell if that user is linked to your GitHub.

Please add your GitHub username there, and then use this website to recheck https://check-python-cla.herokuapp.com/

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
Could you please fix also Doc/distributing/index.rst?

**Comment by serhiy-storchaka** [comment]
I think such trivial change does not need signing the CLA.

**Comment by bittner** [comment]
> @bittner the user https://bugs.python.org/user32717 in bpo does not have GitHub username associated, without it we can't tell if that user is linked to your GitHub.
> 
> Please add your GitHub username there, and then use this website to recheck https://check-python-cla.herokuapp.com/

That is the wrong account: I asked in https://github.com/python/cpython/pull/16862#issuecomment-544245991 if someone could delete it. It doesn't seem to be possible that one could do that themselves.

The correct user account is https://bugs.python.org/user15528, and that has the GitHub user name included. I've signed the CLA twice for this account. How can we find out what's broken here?

**Comment by bittner** [comment]
I have made the requested changes; please review again.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by Mariatta** [comment]
I don't have admin access to bpo, so I can't delete users.
You might just need to sign another CLA for the user https://bugs.python.org/user15528, or perhaps write to  contributors@python.org to clarify the situation, and mentioned that the CLA should be received under the first account.

**Pull request merged**
