### PR TITLE
gh-104341: Add a Separate "Running" Lock for Each Thread

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
Having a separate lock means `Thread.join()` doesn't need to wait for the thread to be cleaned up first.  It can wait for the thread's Python target to finish running.  This gives us some flexibility in how we clean up threads.

(This is ~a minor cleanup as~ part of a fix for gh-104341.)

### CODE REVIEW

**Comment by terryjreedy** [comment]
This merge is likely the cause of multiple `Address sanitizer` CI failures afterwards.  See the core discord, core-workflow-and-bots.  For me, `threading_cleanup` left 2 dangling thread 4 times, once in test_importlib, making an Environment Change failure in 3 of 4 runs.

**Comment by ericsnowcurrently** [comment]
I'll take a look first thing in the morning.

**Comment by gpshead** [comment]
I'd revert this PR.  This was not a "minor cleanup".

**Comment by gpshead** [comment]
Reverted to unblock everybody else.  Please do not make changes to threading without code review and buildbot tests.

**Comment by ericsnowcurrently** [comment]
thanks

**Pull request merged**
