### PR TITLE
bpo-39386: Prevent double awaiting of async iterator

### PR DESCRIPTION
**Pull request by asvetlov**
https://bugs.python.org/issue39386

### CODE REVIEW

**Comment by asvetlov** [comment]
@1st1 would be very nice if you can find time for the PR review.

**Comment by asvetlov** [comment]
@njsmith I appreciate your review as well

**Review by njsmith — APPROVED** [review]

**Review by 1st1 — APPROVED** [review]

**Comment by 1st1** [comment]
LGTM, Andrew. Thank you.

**Comment by asvetlov** [comment]
Thanks for the review, @njsmith and @1st1

**Review by aeros — COMMENTED** [review]
Would it be redundant to explicitly test `asend()` as well?

For example:

```py
     def test_async_gen_await_asend_twice(self):
         async def async_iterate():
             yield 1
             yield 2
  
         async def run():
             it = async_iterate()
             nxt = it.asend(None)
             await nxt
             with self.assertRaisesRegex(
                      RuntimeError,
                      r"cannot reuse already awaited __anext__\(\)/asend\(\)"
              ):
                  await nxt
  
         self.loop.run_until_complete(run())
```

This seems effectively covered by `test_async_gen_await_anext_twice`, but I don't think it hurts to include both (especially since it's straightforward and a quick test).

Otherwise, LGTM.

**Comment by aeros** [comment]
Oh oops, looks like I was typing that just as it was being reviewed by Yury, never mind.

**Comment by asvetlov** [comment]
@aeros sorry, I've pressed "Merge" button before reading your message.
New tests don't hurt, and they should be pretty fast.
I would say that both `__anext__` and `asend` are processed by single `async_gen_asend_send` function, so tests doubling is redundant a little.

**Comment by aeros** [comment]
@asvetlov No worries! It was more of an afterthought than anything, and I don't think it will have a significant impact on the long-term stability if we don't include the explicit `asend()` test. As you said, both `__anext__` and `asend` are called by the same C-API function and I doubt that would realistically end up changing at any point in the future.

**Pull request merged**
