### PR TITLE
bpo-39352: Remove the formatter module

### PR DESCRIPTION
**Pull request by vstinner**
Remove the formatter module. It was deprecated since Python 3.4 and
was not tested.

https://bugs.python.org/issue39352

### CODE REVIEW

**Comment by vstinner** [comment]
cc @brettcannon @tiran

**Comment by corona10** [comment]
@vstinner 
https://github.com/python/cpython/blob/188ebfa475a6f6aa2d0ea14ca8e1fbe7865b6d27/Doc/library/misc.rst#miscellaneous-services reference formatter module.

**Comment by vstinner** [comment]
> @vstinner
https://github.com/python/cpython/blob/188ebfa475a6f6aa2d0ea14ca8e1fbe7865b6d27/Doc/library/misc.rst#miscellaneous-services reference formatter module.

Oh right, fixed. I also rebased my PR to fix a merge conflict.

**Review by corona10 — APPROVED** [review]
LGTM, good bye formatter

**Comment by vstinner** [comment]
PR rebased to fix the conflict.

**Comment by vstinner** [comment]
I closed https://bugs.python.org/issue39352

**Pull request closed without merging**
