### PR TITLE
bpo-41857: Document timeout arguments in select module

### PR DESCRIPTION
**Pull request by zaneb**
The docstring for the poll() methods of the [select.poll](https://docs.python.org/3/library/select.html#select.poll.poll
) and
[select.devpoll](https://docs.python.org/3/library/select.html#select.devpoll.poll) classes did not describe the expected units of the
timeout argument (milliseconds). Previously this information was only
available from the online documentation.

This is a potential source of confusion, because other poll() methods in
the select module, such as epoll and kqueue Polling objects, use units
of seconds (and were documented).

Include the units in the docstring description so that this information
is at least available from interactive help.

https://bugs.python.org/issue41857

### CODE REVIEW

**Comment by zaneb** [comment]
This is just a docs change so I believe it should be given the "skip news" label.

**Review by taleinat — CHANGES_REQUESTED** [review]
Thanks @zaneb, this would certainly be an improvement!

A small request: I suggest more closely imitating the wording used by `select.kqueue.control()`:

```
    timeout as otimeout: object = None
        The maximum time to wait in seconds, or else None to wait forever.
        This accepts floats for smaller timeouts, too.
```

**Comment by zaneb** [comment]
Thanks for the suggestion. I have made the requested changes; please review again.

**Review by taleinat — APPROVED** [review]
LGTM

**Pull request merged**
