### PR TITLE
[3.7] bpo-47138: Fix documentation build by pinning Jinja version to 3.0.3

### PR DESCRIPTION
**Pull request by m-aciek**
https://bugs.python.org/issue47138

~~https://bugs.python.org/issue45618#msg415979~~

### CODE REVIEW

**Comment by ned-deily** [comment]
See my comments on [the bug issue](https://bugs.python.org/issue45618).

**Review by hugovk — APPROVED** [review]
This PR looks good, it only adds a jinja2 pin and doesn't modify the others.

The `doc-html` preview downloadable at https://github.com/python/cpython/actions/runs/2041354404 looks good too.

---

Should we use this new bpo number? https://bugs.python.org/issue47138

**Comment by m-aciek** [comment]
I've updated the commit message with a new ticket number.

**Review by ned-deily — APPROVED** [review]

**Comment by m-aciek** [comment]
Yes, sorry for the branch name, it probably made it  harder to work with it locally. I used to use git pull --rebase, which should avoid the problem, but thank you for the hint nevertheless. And thank you for the cooperation on the fix!

**Pull request merged**
