### PR TITLE
gh-115999: Specialize `LOAD_SUPER_ATTR` in free-threaded builds

### PR DESCRIPTION
**Pull request by nascheme**
Use existing helpers to atomically modify the bytecode.  Fix thread safety issue with `cell_set_contents()`.  Add unit tests to ensure specializing is happening as expected.

Note: this needs gh-127272 to be merged as well in order to avoid thread safety issues.  

* Issue: gh-115999

### CODE REVIEW

**Review by mpage — COMMENTED** [review]
This looks pretty good to me, but is a significant [regression](https://github.com/facebookexperimental/free-threading-benchmarking/tree/main/results/bm-20241125-3.14.0a2+-a515a0d-NOGIL) on the free-threaded builds. I think the regression is coming from the critical section that is acquired in `BEGIN_TYPE_LOCK` before calling `super_lookup_lock_held`. It looks like some of the functions called by `super_lookup_lock_held` already acquire the type lock when necessary (e.g. [`_super_lookup_descr`](https://github.com/python/cpython/blob/6da9d252ac39d53342455a17bfec7b1087fba697/Objects/typeobject.c#L11444-L11451)); we are forced to release and reacquire the critical section each time these functions are called. Do we need to hold the type lock before calling `super_lookup_lock_held`?

Edit: For completeness, this looks [perf neutral](https://github.com/facebookexperimental/free-threading-benchmarking/tree/main/results/bm-20241125-3.14.0a2+-a515a0d) on default builds.

**Comment by nascheme** [comment]
> It looks like some of the functions called by `super_lookup_lock_held` already acquire the type lock when necessary (e.g. `_super_lookup_descr`

I see.  In that case, it seems `do_super_lookup()` is also safe.  The other function called by `_PySuper_Lookup()` is `supercheck()`.  I think that might be safe as well (the `super_descr_get()` slot function uses it without a critical section).  If so, then I would conclude `_PySuper_Lookup()` doesn't need any changes.

**Comment by nascheme** [comment]
This is the worst regression on the benchmark suite:

> richards_super	103 ms	1.82 sec: 17.69x slower

A new benchmark run is in-progress and it looks like that regression is gone (which would be expected since the code hasn't changed).

**Comment by mpage** [comment]
New [benchmark results](https://github.com/facebookexperimental/free-threading-benchmarking/tree/main/results/bm-20241126-3.14.0a2+-ab3af14-NOGIL) look good. Performance is neutral / slightly improved overall; the benchmarks that we expect this to help (e.g. `richards_super`) are clearly improved.

I think you need to fix the merge conflicts before CI will run tests.

**Review by mpage — APPROVED** [review]
LGTM!

**Pull request merged**
