### PR TITLE
bpo-41005: Fixed perrmission error

### PR DESCRIPTION
**Pull request by KrishnaSai2020**
[bpo-41005](https://bugs.python.org/issue41005): Fixed if/else bug in code

https://bugs.python.org/issue41005

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@KrishnaSai2020

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by KrishnaSai2020** [comment]
I've signed the CLA but it will take one business day to come through should I close this pull request and create new one once the cla goes through??

**Comment by remilapeyre** [comment]
> I've signed the CLA but it will take one business day to come through should I close this pull request and create new one once the cla goes through??

Hi @KrishnaSai2020, welcome to Python! You can wait a few days and use https://check-python-cla.herokuapp.com/ to check the CLA again.

**Comment by KrishnaSai2020** [comment]
@remilapeyre ok then will do 👍

**Comment by KrishnaSai2020** [comment]
@remilapeyre yeah its come through please review

**Comment by KrishnaSai2020** [comment]
@remilapeyre please review

**Review by ronaldoussoren — CHANGES_REQUESTED** [review]
IMHO this is not the correct fix, this just removes the xdg-settings path on macOS, event without changing the comment in the macOS specific path that says macOS also uses the unix behaviour.

A better fix is to catch and ignore PermissionError when starting xdg-settings (not being allowed to start xdg-settings is similar to it not being on the system at all)

**Comment by KrishnaSai2020** [comment]
@ronaldoussoren so you're suggesting a try except block to catch the xdg settings error?

**Comment by KrishnaSai2020** [comment]
I have made the requested changes; please review again

**Comment by KrishnaSai2020** [comment]
@ronaldoussoren please re-review the changes that were made

**Review by ronaldoussoren — APPROVED** [review]
Patch looks good to me.

**Comment by ronaldoussoren** [comment]
@KrishnaSai2020: Thanks for your PR!

**Comment by KrishnaSai2020** [comment]
@ronaldoussoren np!

**Pull request merged**
