### PR TITLE
gh-114911: Add CPUStopwatch test helper

### PR DESCRIPTION
**Pull request by encukou**
A few of our tests measure the time of CPU-bound operation, mainly to avoid quadratic or worse behaviour.
Add a helper to ignore GC and time spent in other processes.

* Issue: gh-114911

### CODE REVIEW

**Comment by encukou** [comment]
@vstinner, do you like this test helper?

**Comment by vstinner** [comment]
> @vstinner, do you like this test helper?

I'm not sure that it's going to fix the root issue: https://github.com/python/cpython/issues/114911#issuecomment-1939126431

**Comment by encukou** [comment]
It's not; I want to add it to help diagnosing similar issues (by filtering out unrelated causes).

**Comment by encukou** [comment]
The WASI buildbot fails because... on WASI time runs a million times faster: https://github.com/python/cpython/issues/115714

**Comment by vstinner** [comment]
> I'm not sure that it's going to fix the root issue: https://github.com/python/cpython/issues/114911#issuecomment-1939126431

Please, ignore my comment. I didn't find time to fully review this change and dig into this issue ;-)

**Comment by encukou** [comment]
The WASI clock has been sacked; tests are green.

@vstinner Thank you for digging in! Any objections to merging this? 
(I'm not asking for a full formal review, unless you want to do one -- but I don't want to merge if you're still looking at this.)

**Pull request merged**
