### PR TITLE
Document actual string.punctuation value

### PR DESCRIPTION
**Pull request by andresdelfino**
I feel the actual value (which won't change) is more helpful than the existing description.

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Please preserve the description. Check that the added string is rendered correctly in HTML and PDF.

**Comment by andresdelfino** [comment]
> Please preserve the description. Check that the added string is rendered correctly in HTML and PDF.

Done! Added string renders correctly on both HTML and PDF.

**Comment by serhiy-storchaka** [comment]
Add a rule in `Doc/tools/susp-ignored.csv`.

**Comment by andresdelfino** [comment]
> Add a rule in `Doc/tools/susp-ignored.csv`.

Done, sorry!

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
