### PR TITLE
gh-104683: `clinic.py`: Improve coverage for the `parse_converter` method

### PR DESCRIPTION
**Pull request by AlexWaygood**
Unblocks #104696

* Issue: gh-104683

### CODE REVIEW

**Review by erlend-aasland — APPROVED** [review]
Thanks!

**Comment by AlexWaygood** [comment]
I'll leave the decision to you as to whether to backport this!

**Comment by erlend-aasland** [comment]
I (almost) always backport tests :) We need good test coverage in all active releases.

**Comment by AlexWaygood** [comment]
> I (almost) always backport tests :) We need good test coverage in all active releases.

I do the same over at `typing.py`, but I know opinions differ!

**Pull request merged**
