### PR TITLE
bpo-44516: update vendored pip to 21.1.3

### PR DESCRIPTION
**Pull request by sbidoul**
https://bugs.python.org/issue44516

### CODE REVIEW

**Comment by sbidoul** [comment]
@pfmoore can you label this for backport to 3.10 and 3.9 ? I understand this should not be backported to 3.8, correct ?

**Comment by pfmoore** [comment]
This needs a news file and for some reason the bpo issue check is failing as well. Backport labels added.

**Comment by pfmoore** [comment]
@sbidoul I don't know what the Azure failure is, it looks unrelated, but I don't have any way to restart the job to check if it's a one-off.

**Comment by sbidoul** [comment]
It was a transient. It's green now.

**Pull request merged**
