### PR TITLE
importlib doc: Fix required Python version of an example

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by vstinner** [comment]
I closed/reopened the PR to schedule a new AppVeyor job.

**Comment by vstinner** [comment]
Copy of the original description:

[31.5.6.3. Importing a source file directly](https://github.com/python/cpython/blob/65b5ef02ec1f44e3a19b689a1ecf73d01c82161b/Doc/library/importlib.rst#importing-a-source-file-directly)
To import a Python source file directly, use the following recipe (Python 3.4 and newer only):

```python
import importlib.util
import sys

# For illustrative purposes.
import tokenize
file_path = tokenize.__file__
module_name = tokenize.__name__

spec = importlib.util.spec_from_file_location(module_name, file_path)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
# Optional; only necessary if you want to be able to import the module
# by name later.
sys.modules[module_name] = module
```

---

The above example requires at least 3.5 because of `module_from_spec`.

The example code in [31.5.6.5. Approximating `importlib.import_module()`](https://github.com/python/cpython/blob/65b5ef02ec1f44e3a19b689a1ecf73d01c82161b/Doc/library/importlib.rst#approximating-funcimportlibimport_module) also uses `module_from_spec`, but I'm not sure it is "the importlib usage", so didn't modify.

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
This change will be merged once the CI pass, please don't change the title nor the description.

**Comment by e-kwsm** [comment]
> This change will be merged once the CI pass,

Do I have to remove `[ci skip]` from the commit message?

**Comment by vstinner** [comment]
Sadly, the AppVeyor CI job never started :-( I closed/reopened the PR to schedule new CI jobs.

**Comment by vstinner** [comment]
> Do I have to remove [ci skip] from the commit message?

"automerge" uses the PR title and description.

**Comment by vstinner** [comment]
@e-kwsm: I am sorry, but something is broken with this PR. CI jobs never start. I close it. Please create a new PR. Since it's a single character, it should be easy :-)

Then add the comment "cc @vstinner" to make sure that I don't miss your new PR ;-)

**Comment by e-kwsm** [comment]
[`[ci skip]` prevents AppVeyor CI.](
https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message)

I removed `[ci skip]` and `git push -f` but the commit message in this PR does not change, probably because this is closed.

**Comment by e-kwsm** [comment]
@vstinner  I'm sorry but would you reopen?

**Comment by vstinner** [comment]
Please just create a new one, it will be simpler for me.

**Comment by e-kwsm** [comment]
@vstinner I created #10118. Would you check if the CI works?

**Pull request closed without merging**
