### PR TITLE
bpo-33281: Change some ifs to be elifs so the correct find_library is not later overridden.

### PR DESCRIPTION
**Pull request by mingwandroid**
https://bugs.python.org/issue33281

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Comment by mingwandroid** [comment]
I have signed the CLA now and associated my `github` tag with my account on bugs.python.org, what next?

**Comment by ned-deily** [comment]
@mingwandroid, It looks you still need to add your GitHub user name to your bugs.python.org user account (https://bugs.python.org/user16077).  I'll do it for you here.

**Comment by ned-deily** [comment]
@mingwandroid, The patch looks good to me, thanks!  If, in the next few hours, you could also push a NEWS entry to the PR using the blurb utility, that would be great.

**Pull request merged**
