### PR TITLE
bpo-12202: Properly check MsiSummaryInfoGetProperty() calls in msilib

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue12202

### CODE REVIEW

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
Thanks!

**Comment by ZackerySpytz** [comment]
Thanks for the merge, @berkerpeksag!

Can you please apply the "needs backport to 3.7" and "needs backport to 2.7" labels? The bot should be able to create the backport to 3.7 cleanly, and I will manually create a backport for 2.7.

**Comment by berkerpeksag** [comment]
No need to backport this. msilib is effectively deprecated and the issue is 8 years old.

**Comment by ZackerySpytz** [comment]
> No need to backport this. msilib is effectively deprecated and the issue is 8 years old.

@berkerpeksag Three bug fixes for the msilib module have been merged within the last four months: GH-13688, GH-12074, and GH-4517. **All** of them have been backported (GH-13688 was merged and backported to 3.7 and 2.7 just today). The BPO issue for GH-4517 was created in 2007 (almost 12 years ago), yet it was still backported.

**Comment by berkerpeksag** [comment]
Thanks for the lecture. See commit history of `PC/_msi.c` next time.

**Comment by ZackerySpytz** [comment]
> Thanks for the lecture. 

@berkerpeksag I'm sorry. I don't want to offend. I'm stating why I believe this patch should be backported.
> See commit history of PC/_msi.c next time.

What do you mean exactly? When looking at the commit history of `PC/_msi.c`, one can see that bug fixes have occurred very infrequently, but all of the ones that have occurred since the GitHub migration have been backported to maintenance branches, except for a compiler warning fix.

**Pull request merged**
