### PR TITLE
bpo-33885: Replace "hook function" with "callable"

### PR DESCRIPTION
**Pull request by andresdelfino**
https://bugs.python.org/issue33885

### CODE REVIEW

**Review by terryjreedy — APPROVED** [review]

**Review by orsenthil — APPROVED** [review]

**Comment by terryjreedy** [comment]
Andres, the backports are yours if you think them worthwhile.  Ditto for 'complete progams', if the issue comes up.

**Comment by andresdelfino** [comment]
@terryjreedy 

1. I just noticied I select the wrong branch when making this PR, see that it points to 3.6.
2. I'll gladly take the backports. 
3. What do you mean by: Ditto for 'complete progams', if the issue comes up.

Regarding the first item, the backport to 3.6 is no need, as the commit has merged into that branch already. I'll make the backport for 2.7. And a forwardport(?) for this to master. Or should we proceed otherwise?

**Comment by andresdelfino** [comment]
Regarding the third item, I see you were talking about #7744 :)

**Comment by terryjreedy** [comment]
There are 3 options.  I am going to ask on core_mentorship which is preferred.

**Comment by andresdelfino** [comment]
OK, I'll wait. Sorry for the inconvenience...

**Comment by terryjreedy** [comment]
On core_mentorship, Nick Coughlin said "Just cherry pick to the full set of destinations from the original
commit rather than trying to revert anything."  Go ahead.
He also had idea how Bedevere could catch mistake on submission.

**Comment by andresdelfino** [comment]
Great! I'll do it right away. Sorry for the hassle.

**Comment by terryjreedy** [comment]
Repositories are intentionally mistake resilient.  The guaranteed way to never make a bad merge is to never make a merge.  There have been people who have done the latter after getting commit privileges.
We still need a cherry-pick to master.

**Comment by andresdelfino** [comment]
I guess "needs backport to 3.6" tag should be removed.

**Pull request merged**
