### PR TITLE
gh-82073: Use space indents in IDLE Shell

### PR DESCRIPTION
**Pull request by terryjreedy**
Adding a newline to the prompt moves it out of the way of
user code input, which now starts at the left margin,
along with continuation lines.

* Issue: gh-82073

### CODE REVIEW

**Comment by terryjreedy** [comment]
@taleinat I hope I am not surprising you too much.  Unless you find reason why not, I am inclined to merge this tomorrow and leave it to you to merge this in with master, add a toggle*, and test that this works with sidebar toggled off.  Or make the 3 little changes to the other PR to test.  Or I will tomorrow (it is 2:40 am here).

* for the beta, I think we can skip configdialog, and instead add something like the following to the startup message.
```
Enter a statement on the line *after* the last '>>>' prompt.  Indents will be spaces instead of tabs.
Or hit Alt-? to try out the new Shell sidebar.  Doing so will clear this window.
```
Then switch to this addition.
```
Enter a statement to the right of the last '>>>' prompt.  But indents will be spaces instead of tabs.
Or hit Alt-? to return to the prompt above input mode.  Doing so will clear this window.
```

Actually, I intend to revise the current mostly useless help message.  It could instead be removed and permanently replaced with something more useful.  People should know about Help -> About.

**Comment by terryjreedy** [comment]
For beta, we might mention sending feedback to idle-dev@python.org.  (I just posted to that address to test and it worked.)

**Comment by gvanrossum** [comment]
I tried this too. I think I have a slight preference for Tal's version (with the prompts in the margin) because in his version it's easier to distinguish input from output that way, and because it's easier to copy/paste blocks of code that span multiple prompts.

**Comment by terryjreedy** [comment]
Shell with sidebar looks even better with proper indents.

**Comment by taleinat** [comment]
@terryjreedy, this is great! (Sorry for not getting to comment on this earlier.)

I'm pleasantly surprised that this simple change appears to "just work" so nicely.

**Comment by terryjreedy** [comment]
please merge origin/master into your branch to include this, and the test fix.

**Pull request merged**
