### PR TITLE
gh-122544: Change OS image in GitHub Actions to ubuntu-24.04

### LINKED ISSUE #122544: Change base OS image  to Ubuntu-24.04 in CI testing
In current `ci.yml`, base OS image is `ubuntu-22.04`, should we move to the latest LTS verion: `ubuntu-24.04` ?

> 
>   pool:
>     vmImage: ubuntu-22.04

To go further, if we should replace all current CI testing which run on `ubuntu-22.04` to `ubuntu-24.04` ?

### Linked PRs
* gh-122566
* gh-122568
* gh-122570
* gh-122593
* gh-122594
* gh-125344
* gh-126479
* gh-126480
* gh-126619
* gh-126621
* gh-130260
* gh-130268
* gh-130295

### PR DESCRIPTION
**Pull request by Damien-Chen**
Change base OS image in Github Actions from `ubuntu-22.04` to `ubuntu-24.04`

* Issue: gh-122544

### CODE REVIEW

**Comment by AA-Turner** [comment]
Failing due to `Unable to locate package libmpdec-dev`, as [the libmpdec-dev package](https://packages.ubuntu.com/jammy/libmpdec-dev) does not appear in Ubuntu 24.04 LTS. According to [this comment](https://askubuntu.com/questions/1520401/#comment2670969_1520401), the removal is intentional as it is no longer needed, see [the debian mailing list post](https://tracker.debian.org/news/1518602/removed-251-2-from-unstable/).

@Damien-Chen are you able to test this please?

A

**Comment by Damien-Chen** [comment]
> Failing due to `Unable to locate package libmpdec-dev`, as [the libmpdec-dev package](https://packages.ubuntu.com/jammy/libmpdec-dev) does not appear in Ubuntu 24.04 LTS. According to [this comment](https://askubuntu.com/questions/1520401/#comment2670969_1520401), the removal is intentional as it is no longer needed, see [the debian mailing list post](https://tracker.debian.org/news/1518602/removed-251-2-from-unstable/).
> 
> @Damien-Chen are you able to test this please?
> 
> A

Sure!. No problem!

**Comment by AA-Turner** [comment]
The `regen-all` check is failing, I assume something changed between LTS versions -- can you run `make regen-all` on 24.04 and push that?

A

**Comment by Damien-Chen** [comment]
> The `regen-all` check is failing, I assume something changed between LTS versions -- can you run `make regen-all` on 24.04 and push that?
> 
> A

Let me check if I can test it locally on my WSL2 `ubuntu-24.04` or use another local machine to install `ubuntu-24.04`. Or if I can trigger all pipline on my fork repo so that I I don’t have to confirm the result every time I commit to this PR.

**Comment by Damien-Chen** [comment]
> The `regen-all` check is failing, I assume something changed between LTS versions -- can you run `make regen-all` on 24.04 and push that?
> 
> A
It means that adding `make regen-all` before `git add -u` like the below image show?
      - name: Check for changes
        run: |
          make regen-all
          git add -u
          changes=$(git status --porcelain)

**Comment by Damien-Chen** [comment]
It seems same error, I run on my forked repo in [this](https://github.com/Damien-Chen/cpython/actions/runs/10229054834/job/28302247216)

**Comment by AA-Turner** [comment]
Sorry, I meant you need to run `make regen-all` locally and commit the output of that to your branch.

**Comment by Damien-Chen** [comment]
> Sorry, I meant you need to run `make regen-all` locally and commit the output of that to your branch.

I run it locally on `ubuntu-24.04`, and convert the whole output of that into a single script, and run that script, the result is [here](Just as soon as gradle stops being broken).
But it seems still same error.

**Comment by Damien-Chen** [comment]
> Sorry, I meant you need to run `make regen-all` locally and commit the output of that to your branch.

It seems that the below three file cause error in `ubuntu-24.04`
`aclocal.m4`, `config.guess`, `configure`.

I test it in several method. First is run `make regen-all` on my local `ubuntun-24.04` machine, and convert the whole output into a script, and then execute it before running `Check for changes` test but it fails. 
Then I copy the above three mention file generated in `ubuntu-24.04`, and overwrite the original three file that in `ubuntu-22.04` and it seems pass the check. 

Maybe there are some modification between `ubuntu-22.04` and `ubuntu-24.04` cause the above mentioned three file different ?

The whole process and result were conduct in my fork repo [here](https://github.com/Damien-Chen/cpython/actions/runs/10234489178/job/28314028711) 

[ubuntu-24.04output.txt](https://github.com/user-attachments/files/16486774/ubuntu-24.04output.txt)

And the attached file is the output of running `make regen-all` in `ubuntu-24.04`.

**Comment by Damien-Chen** [comment]
For `ubuntu-24.04`, these three file `aclocal.m4`, `config.guess`, `configure` are different than `ubuntu-22.04`. Maybe we should update these file together.

**Comment by hugovk** [comment]
(Updating branch to re-trigger CLA bot, which got stuck a few days ago.)

**Review by hugovk — APPROVED** [review]
Thanks, CI changes look good to me. I'd like someone else (@corona10? @erlend-aasland?) to review the configure + libmpdec-dev changes.

**Comment by hugovk** [comment]
@Damien-Chen Please could you resolve the conflicts?

@erlend-aasland @corona10 Please could you check the configure + libmpdec-dev changes here?

We'll also need to upgrade doctest soon (see https://github.com/python/cpython/pull/125236), but that can be a separate PR.

**Comment by erlend-aasland** [comment]
I'll check it later today, when I'm back on my laptop.

**Comment by Damien-Chen** [comment]
Should we merge this as early as possible?

**Comment by AA-Turner** [comment]
There's no rush to merge this, it is currently blocked on review of the autoconf / configure changes. Most likely we will need to co-ordinate updating e.g. the [docker images](https://github.com/python/cpython-devcontainers/blob/main/autoconf/Dockerfile) to Ubuntu 24 too.

cc @corona10 

A

**Comment by corona10** [comment]
I will try to take a look at overall status through this weekend

**Comment by corona10** [comment]
https://github.com/python/cpython-devcontainers/pull/28

**Comment by corona10** [comment]
@Damien-Chen cc @erlend-aasland 

Would you like to update  
https://github.com/python/cpython/blob/4b421e8aca7f2dccc5ac8604b78589941dd7974c/Tools/build/regen-configure.sh#L8

to IMAGE="ghcr.io/python/autoconf:2024.10.19.11417401087"

And rerun `(sudo) make regen-configure`?

**Comment by Damien-Chen** [comment]
@corona10 
Sure! NP.
Thanks for your support.

**Comment by corona10** [comment]
Hmm did you rerun `sudo make regen-configure`?
From my local checkout, there diff exists

**Comment by Damien-Chen** [comment]
I rerun `sudo make regen-configure` on my local ubuntu-24.04 laptop and put the resulted three file,
`aclocal.m4`, `configure.guess`, `configure` into my test branch.

However it fails on the following check:
`Check if generated files are up to date`, 
`WASI`

I ran it on my test branch, you can take a look at [here](https://github.com/Damien-Chen/cpython/actions/runs/11418591132/job/31772384992).

**Comment by corona10** [comment]
You should re-generate files, that are correct if the CI should be updated, than we should fix the CI.

**Review by corona10 — CHANGES_REQUESTED** [review]
https://github.com/python/cpython/blob/4b421e8aca7f2dccc5ac8604b78589941dd7974c/.github/workflows/build.yml#L43-L47

Please update above file and please rerun `make regen-configure`. (again it's not an optional)
And let's take a look at what should we fix more. (maybe WASI)

**Comment by Damien-Chen** [comment]
Yes, I updated the above CI file and add `make regen-configure` before check change, and still got the same result in my [test branch](https://github.com/Damien-Chen/cpython/actions/runs/11419289633/job/31773722422). I wonder if your branch can pass all check, or if there`s necessary to modify CI ?

**Review by corona10 — CHANGES_REQUESTED** [review]
@Damien-Chen cc @erlend-aasland @hugovk 
Okay, so I think that we should modify CI to use the container image that we published rather than using baseimage
See how can we do that: https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container

So please revert related files to follow https://github.com/python/cpython/pull/125740
I will submit the PR soon

**Review by corona10 — APPROVED** [review]

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
@hugovk, I guess we want to backport this to 3.13 and 3.12.

**Comment by erlend-aasland** [comment]
Thanks, @Damien-Chen, for the PR (hope you don't mind I regenerated `configure` for you), and thanks you all for the review.

**Comment by erlend-aasland** [comment]
@Damien-Chen, can you create the backports? See [the devguide](https://devguide.python.org/core-developers/committing/#backporting-changes-to-an-older-version) for details.

**Comment by Damien-Chen** [comment]
Sure, I will take some time on it.

**Comment by hugovk** [comment]
Let's backport this to 3.9-3.11, they're still using some `ubuntu-20.04` which is deprecated and will be fully unsupported by 2025-04-01, with brownouts in March:

https://github.com/actions/runner-images/issues/11101

**Pull request merged**
