### PR TITLE
bpo-40645: Fix ref leaks in _hashopenssl

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue40645

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @encukou

**Review by pablogsal — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Backport to 3.10, @pablogsal ?

**Comment by pablogsal** [comment]
Yup, and to any version that has this problem. Can you add the labels?

**Comment by erlend-aasland** [comment]
> Yup, and to any version that has this problem. Can you add the labels?

GH-26072 is (currently) only being backported to 3.10, so for now I'm only adding the 3.10 label. I'll check 3.9 asap and add to both PR's if necessary. BTW, #26072 needs manual backporting.

**Comment by pablogsal** [comment]
> > Yup, and to any version that has this problem. Can you add the labels?
> 
> [GH-26072](https://github.com/python/cpython/pull/26072) is (currently) only being backported to 3.10, so for now I'm only adding the 3.10 label. I'll check 3.9 asap and add to both PR's if necessary. BTW, #26072 needs manual backporting.
> 
> **UPDATE**: Seems like the code in question was added in [933dfd7](https://github.com/python/cpython/commit/933dfd7504e521a27fd8b94d02b79f9ed08f4631). Backporting to 3.10 should be sufficient.

Fantastic. Thanks a lot for the patch :tada:

**Pull request merged**
