### PR TITLE
gh-101409: Improve generated clinic code for self type checks

### PR DESCRIPTION
**Pull request by erlend-aasland**
Store the self type pointer in a local variable.

* Issue: gh-101409

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @colorfulappl

**Comment by colorfulappl** [comment]
> I'm not sure if this improvement is worth it, though; it may be churn for no benefit.

IMHO, this improvement is worth it.

1. If the `clinic_state()` macro is fairly complicated, the compiler won't eliminate the redundant function invocations.

2. The generated code after this patch is more concise and readable.

**Comment by erlend-aasland** [comment]
> 1. If the `clinic_state()` macro is fairly complicated, the compiler won't eliminate the redundant function invocations.

That is true; we cannot guarantee that the compiler will eliminate the redundant calls.

> 2. The generated code after this patch is more concise and readable.

I agree with this.

Thanks for the review, @colorfulappl; highly appreciated.

**Review by serhiy-storchaka — COMMENTED** [review]
`self_tp` may be not a good name. It is not a type of `self`. Maybe `base_type` or `declared_type` or something?

**Comment by erlend-aasland** [comment]
> `self_tp` may be not a good name. It is not a type of `self`. Maybe `base_type` or `declared_type` or something?

`base_type` sounds good; thanks!

**Comment by erlend-aasland** [comment]
I'm considering landing this PR in a day or two.

**Review by kumaraditya303 — APPROVED** [review]
LGTM

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for the reviews, y'all!

**Pull request merged**
