### PR TITLE
bpo-29464: Rename METH_FASTCALL to METH_FASTCALL|METH_KEYWORDS and make

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
the bare METH_FASTCALL be used for functions with positional-only
parameters.

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
@serhiy-storchaka: Can you please rebase your change and then merge it?

**Comment by vstinner** [comment]
Cool! Let's (micro)optimize this ;-)

**Comment by rhettinger** [comment]
This was a nice improvement.  Thank you.

**Pull request merged**
