### PR TITLE
bpo-31955: Correct distinguish of list and string values in set_executable() 

### PR DESCRIPTION
**Pull request by PavelStishenko**
The check "if isinstance(value, str)" is incorrect, because type of value can be unicode, while it should be splitted as well.

https://bugs.python.org/issue31955

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by PavelStishenko** [comment]
I do not understand how to add the label "skip news".  And I have signed CLA.

**Comment by vstinner** [comment]
> And I have signed CLA.

Thank you: this part is correct :-)

> I do not understand how to add the label "skip news"

Since it's a bug fix, it would be better to document the bugfix in a NEWS entry, rather than skipping this part. Use the blurb tool to add a NEWS entry, see:
https://devguide.python.org/committing/#what-s-new-and-news-entries

**Review by vstinner — CHANGES_REQUESTED** [review]
I'm not sure that we need to fix Python 3: see https://bugs.python.org/issue31955

**Comment by PavelStishenko** [comment]
Submitted new PR #4316 Closing this one because it is not needed for Python 3.

**Pull request closed without merging**
