### PR TITLE
Add Third-party resources section

### PR DESCRIPTION
**Pull request by rohitnishad613**
Add Third-party resources section

### CODE REVIEW

**Comment by rohitnishad613** [comment]
Hi, Please review my code so we can further look into this PR.

**Comment by rohitnishad613** [comment]
Hi, there why PR is not getting reviewed its almost a week now.

**Comment by rohitnishad613** [comment]
Hi, Please review my code so we can further look into this PR.

**Comment by rohitnishad613** [comment]
Hi, Please review my code so we can further look into this PR.

**Comment by rohitnishad613** [comment]
Hi, Please review my code so we can further look into this PR.

**Comment by rohitnishad613** [comment]
Hi, Please review my code so we can further look into this PR.

**Comment by JelleZijlstra** [comment]
What is the motivation here? Third-party links seem more appropriate in https://docs.python.org/3/howto/pyporting.html, not in the 2to3 docs.

Also, the Python 2 migration is mostly over by now, so I'm not sure it's still worth adding these links.

**Comment by slateny** [comment]
I'd agree that they don't seem too necessary - I'll close this, but if there's a good reasoning then feel free to reopen.

**Pull request closed without merging**
