### PR TITLE
bpo-41241: Unnecessary Type casting in 'if condition'

### PR DESCRIPTION
**Pull request by archsyscall**
This is my first issue!
So, if there's anything wrong, please tell me!

Also, thank you always for all the contributors!

https://bugs.python.org/issue41241

Automerge-Triggered-By: GH:asvetlov

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@marload

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by marload** [comment]
I wrote the NEWS file and it seems that all the tests have passed!

Thank You!

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
This doesn't need a NEWS entry.  Otherwise, the PR is fine.

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
