### PR TITLE
Added indents that prevented Pygubu from working

### PR DESCRIPTION
**Pull request by theOtterWizard**
Pygubu didn't work for me without them. Other programs may rely on them too.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/23276970/d14a380c-f9d1-11e6-883d-e13b6b211239.png)
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/). The "bugs.python.org username " requested by the form is the "Login name" field under "Your Details".
4. If you just signed the CLA, please **wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by louisom** [comment]
@Silver-Void your patch makes CI break, and I think this is not a bug for cpython itself.

**Review by berkerpeksag — COMMENTED** [review]
```py
for i in range(10):
    ...
else:
    ...
```

is valid Python code and your patch actually broke `test_locale`:

```
======================================================================
ERROR: test_option_locale (test.test_calendar.CommandLineTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/python/cpython/Lib/test/test_calendar.py", line 765, in test_option_locale
    lang, enc = locale.getdefaultlocale()
TypeError: 'NoneType' object is not iterable
```

Please report your problem to Pygubu developers.

**Comment by theOtterWizard** [comment]
Sorry, I thought it was wrong. I'm quite an amateur.

**Pull request closed without merging**
