### PR TITLE
gh-103583: Add ref. dependency between multibytecodec modules

### PR DESCRIPTION
**Pull request by erlend-aasland**
The cjk codec modules now always outlive _multibytecodec

* Issue: gh-103583

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Depends on gh-103588

**Comment by erlend-aasland** [comment]
For the record, `PyMultibyteCodec_CAPSULE_NAME` is not exposed through Python.h:

```console
$ echo '#include "Python.h"' | gcc -E $(./python.exe ./python-config.py --includes) - | grep PyMultibyteCodec_CAPSULE_NAME
$
```

**Comment by corona10** [comment]
@erlend-aasland Please rebase the PR, I will review the PR by tomorrow :)

**Comment by erlend-aasland** [comment]
Thanks, I will :)

**Comment by erlend-aasland** [comment]
@corona10, ready for your second review :)

**Review by corona10 — APPROVED** [review]
lgtm, patch itself looks pretty straightforward :)

**Pull request merged**
