### PR TITLE
CI: Process stale issues four times per day

### PR DESCRIPTION
**Pull request by hugovk**
Follow on from https://github.com/python/cpython/pull/116636, twice a day is not enough:

> The saved state was not found, the process starts from the first issue.

* https://github.com/python/cpython/actions/runs/8257386961/job/22587844299#step:2:24
* https://github.com/python/cpython/actions/runs/8264321477/job/22607678470#step:2:24
* https://github.com/python/cpython/actions/runs/8273399574/job/22637098149#step:2:24
* https://github.com/python/cpython/actions/runs/8280384019/job/22656774950#step:2:24
* https://github.com/python/cpython/actions/runs/8289314116/job/22685512167#step:2:24

Let's try [four times per day](https://crontab.guru/#0_*/6_*_*_*).

### CODE REVIEW

**Review by itamaro — APPROVED** [review]

**Comment by merwok** [comment]
I don’t know where to discuss this stale bot.

Is the label that useful, given the possibility of sorting by last-updated?

If yes, can the comment be skipped, to avoid unhelpful notification? (They are only helpful on repos that auto-close valid issues just because of time elapsed, which is annoying too.)

**Comment by hugovk** [comment]
> I don’t know where to discuss this stale bot.

Perhaps a new core-workflow issue? 

> Is the label that useful, given the possibility of sorting by last-updated?

I'm using it as an opportunity to check the current status of old PRs, and consider whether they're still needed. For example, on one I reminded the author to sign the CLA or we'll need to close it, and added `pending` to follow up. 

> If yes, can the comment be skipped, to avoid unhelpful notification? (They are only helpful on repos that auto-close valid issues just because of time elapsed, which is annoying too.)

We used to autoclose stale PRs with no CLA. This needs reimplementing: https://github.com/python/core-workflow/issues/441.

**Comment by StanFromIreland** [comment]
> We used to autoclose stale PRs with no CLA. This needs reimplementing: https://github.com/python/core-workflow/issues/441.

Should we have a system where we convert old PRs that need a little update to 'easy' issues for someone to pick up? For example https://github.com/python/cpython/pull/30097, which was marked stale today. The author abandoned it, but the change still needs to be done.

**Comment by hugovk** [comment]
Close the PR, create an issue.

**Pull request merged**
