### PR TITLE
bpo-43788: Generate version specific _ssl_data.h

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <christian@python.org>

https://bugs.python.org/issue43788

Automerge-Triggered-By: GH:tiran

### CODE REVIEW

**Comment by stefanrad25** [comment]
is this all
 are source cords

**Comment by stefanrad25** [comment]
# [('X509_R_AKID_MISMATCH', 'X509', 'AKID_MISMATCH', 110), ...]
reasons = []
reasons.extend(parse_openssl_error_text(args))
reasons.extend(parse_extra_reasons(args))
# sort by libname, numeric error code
args.reasons = sorted(reasons, key=operator.itemgetter(0, 3))

lines = [
"/* File generated by Tools/ssl/make_ssl_data.py */"
f"/* Generated on {datetime.datetime.utcnow().isoformat()} */" is this
cords are correct can anyone teel me about this cords

**Review by benjaminp — APPROVED** [review]
this is definitely a lot better than parsing the headers

**Comment by tiran** [comment]
Thanks for the wording fix!

**Pull request merged**
