### PR TITLE
gh-105879: Add support for keyword arguments to eval and exec

### PR DESCRIPTION
**Pull request by rtpg**
* Issue: gh-105879

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks for suggesting and adding this feature! I've definitely confused the ordering of these before :-) This looks good to me (although I think I still have a vague preference for keeping the `source` argument positional-only)

**Comment by iritkatriel** [comment]
Does this need a doc change?

**Comment by rtpg** [comment]
@iritkatriel i believe that the docstring changes (derived from the arg clinic changes) are sufficient, as I did not see anything being explicit about positional-only-ness beyond that

**Comment by JelleZijlstra** [comment]
I fixed the (trivial) merge conflict, undid an unnecessary formatting change, and added a documentation note as @iritkatriel suggested. I'll merge the PR in a bit so we can get this change into 3.13.

**Comment by JelleZijlstra** [comment]
Thinking about it again I agree with @hauntsaninja's suggestion above that we should leave the first argument positional-only. I'll make that change.

**Pull request merged**
