### PR TITLE
bpo-30462: urllib: NO_PROXY env. variable can contain domain with asterisk

### PR DESCRIPTION
**Pull request by jirihnidek**
* The method proxy_bypass_environment() is possible to bypass
   host, when NO_PROXY or no_proxy variable include domain
   specified with asterisk at the begining. e.g.: *.python.org.
* http://bugs.python.org/issue30462

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by jirihnidek** [comment]
I signed CLA before I created this PR.

**Comment by serhiy-storchaka** [comment]
I don't see how this PR is related to [bpo-12345](http://bugs.python.org/issue12345).

**Comment by jirihnidek** [comment]
@serhiy-storchaka sorry, I copy pasted the the name of issue from template :-(. I update the name and of course the right link to issue: http://bugs.python.org/issue30462 was already there.

**Comment by Mariatta** [comment]
@jirihnidek can you add your GitHub username to your account in bugs.python.org?

Thanks.

**Comment by jirihnidek** [comment]
@Mariatta I just added my username to bugs.python.org.

**Review by zhangyangyu — CHANGES_REQUESTED** [review]
This PR needs updated according to the comments in the issue.

**Comment by csabella** [comment]
@jirihnidek, please make the changes requested by @zhangyangyu in the code review.  Thanks!

**Comment by jirihnidek** [comment]
@csabella I will do. :-)

**Comment by csabella** [comment]
@jirihnidek, please address the comments and resolve the merge conflicts.  If it's something you're not interested in anymore, feel free to close the PR.  Thanks!

**Comment by csabella** [comment]
I'm going to close this PR as inactive.  If the original author is interested in pursuing this, then this can be reopened or someone else can create a new PR to replace it.  If a new PR is created, please give credit to the original author.  Thanks!

**Pull request closed without merging**
