### PR TITLE
bpo-33833: Fix ProactorSocketTransport AssertionError

### PR DESCRIPTION
**Pull request by twisteroidambassador**
https://bugs.python.org/issue33833

### CODE REVIEW

**Comment by 1st1** [comment]
Can we have a unittest for this?

**Comment by twisteroidambassador** [comment]
>Can we have a unittest for this?

It may require a bit of advanced Mock() magic. The preconditions are somewhat complex, and the exception is raised in a done_callback, so usually it just goes to the log and nowhere else.

**Comment by 1st1** [comment]
> It may require a bit of advanced Mock() magic. The preconditions are somewhat complex

Yeah, let's not add more complex mock tests. But if it's possible to recreate the preconditions with a functional test it would be enormously helpful.

>  and the exception is raised in a done_callback, so usually it just goes to the log and nowhere else.

We have `assertLogs` or something like that :)

**Comment by twisteroidambassador** [comment]
Now we have a unit test and blurb.

(I am reminded of this joke when writing the test:

Patient: "Doctor, it hurts when I do this."
Doctor: "Don't do that.")

**Pull request closed without merging**
