### PR TITLE
bpo-20928: support base-URL and recursive includes in etree.ElementInclude

### PR DESCRIPTION
**Pull request by scoder**
https://bugs.python.org/issue20928

### CODE REVIEW

**Comment by ruffsl** [comment]
I like the new configurable `base_url`!

As mentioned in [this message](https://bugs.python.org/issue20928#msg312325) from the originating issue, would it at all be possible to add the `xml:base` attribute to elements included from locations with a different base URI, as to comply with the XInclude standard? Just tested bc8bfc2, and this still seems to be missing.

**Comment by scoder** [comment]
Added news entry, rebased to latest (3.8) master.

**Comment by scoder** [comment]
Lacks a documentation update, because there is no documentation for the overall `ElementInclude` feature in CPython. I created [issue 33187](https://bugs.python.org/issue33187) for this. When someone writes documentation, this addition is easy to include there.

**Comment by scoder** [comment]
One remaining issue: how can users disable recursive include processing if they want to?

**Pull request merged**
