### PR TITLE
[3.11] gh-119506: fix _io.TextIOWrapper.write() write during flush (#119507)

### PR DESCRIPTION
**Pull request by methane**
This PR is backport of https://github.com/python/cpython/pull/119507

This PR fixes TextIOWrapper's inner buffer breakage.
The bug caused assertion error when Python debug build.
I am not sure it can cause crash on release build. The bug will cause:

* Lost buffered data, and,
* NUL bytes can be written instead of the lost data.

Since this bug is not verified to cause crash (and DoS) in release build, I am not sure this PR is merged into security fix branches.
But this bug can cause serious bug (data lost/breakage). So I created this PR before details went away from my head.

* Issue: gh-119506

### CODE REVIEW

**Comment by hugovk** [comment]
@pablogsal Can this be merged into 3.11 or 3.10?

**Comment by pablogsal** [comment]
I think it makes sense to back port although doesn't seem too critical IMHO

**Review by pablogsal — APPROVED** [review]

**Comment by terryjreedy** [comment]
Only 'special' people can merge into 3.11 and before.
@pablogsal Can you still do so as release manager? @ambv I know you can.  Pablo approved.
Please one of you merge or close this orphaned backport.

**Comment by hugovk** [comment]
I can do it, let's update the PR from `3.11` first to be sure the CI still passes.

**Pull request merged**
