### PR TITLE
bpo-31370: Remove support for threads-less builds

### PR DESCRIPTION
**Pull request by pitrou**
https://bugs.python.org/issue31370

### CODE REVIEW

**Review by gpshead — APPROVED** [review]
yay!  i skimmed over everything, it looks good.  lots of mechanical changes. :)

**Review by vstinner — APPROVED** [review]
Please keep the "#define WITH_THREAD 1" for backward compatibily. Maybe in pyport.h?

LGTM if you keep the define, but I would like to see a review of another core dev like @ericsnowcurrently.

See https://bugs.python.org/issue27961#msg276881 and commit a251fb02f4400a2ea32677110e430742fd1444bc.

**Review by bitdancer — COMMENTED** [review]
The test_email change looks fine :)

I think this needs a mention in What's New as well.

**Comment by pitrou** [comment]
> Please keep the "#define WITH_THREAD 1" for backward compatibily. Maybe in pyport.h?

Ok, done.

**Comment by pitrou** [comment]
> I think this needs a mention in What's New as well.

Ok, done.

**Comment by vstinner** [comment]
Thanks, I merged your change ;-)

**Comment by mscuthbert** [comment]
**Ignore below;  forgot to copy Modules/Setup.dist to Modules/Setup**

Anyone else getting this error when trying to build Python on OS X after the merge?

```
File "/Users/cuthbert/git/cpython/Lib/reprlib.py", line 7, in <module>
    from _thread import get_ident
ModuleNotFoundError: No module named '_thread'
```

It seems that `_thread` is no longer being made in the build process.

Full part of the make process:

```
./python.exe -E -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
Could not import runpy module
Traceback (most recent call last):
  File "/Users/cuthbert/git/cpython/Lib/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "/Users/cuthbert/git/cpython/Lib/importlib/__init__.py", line 57, in <module>
    import types
  File "/Users/cuthbert/git/cpython/Lib/types.py", line 175, in <module>
    import functools as _functools
  File "/Users/cuthbert/git/cpython/Lib/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/Users/cuthbert/git/cpython/Lib/collections/__init__.py", line 32, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/Users/cuthbert/git/cpython/Lib/reprlib.py", line 7, in <module>
    from _thread import get_ident
ModuleNotFoundError: No module named '_thread'
```

**Pull request merged**
