### PR TITLE
bpo-42142: Try to fix timeouts in ttk tests

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Check whether the widget is already visible before waiting a `<VisibilityNotify>` event.

https://bugs.python.org/issue42142

### CODE REVIEW

**Comment by E-Paine** [comment]
Also addresses bpo-42370

**Comment by serhiy-storchaka** [comment]
It does not address bpo-42370, it just adds new checks. If the error like in bpo-42370 happens they can give more information. This is a rare failure, after having more information we can try to write a workaround.

**Comment by terryjreedy** [comment]
Putting repeated problematic test im a function is a great idea.

Pipelines Windows tests failed consistently with "RuntimeError: Widget .!labeledscale is still not mapped".   Presume same for GH Actions.  Maybe revert to wait_visibility on Windows, where it apparently always worked?

**Comment by serhiy-storchaka** [comment]
Actually, using `update()` seems enough.

`wait_visibility()` just waits VisibilityNotify or DestroyNotify events in dead loop. If the widget is already visible it never ends. `winfo_ismapped()` could be used to check that the widget is already visible, but it does not work on Windows.

**Pull request merged**
