### PR TITLE
gh-105293: Do not call SSL_CTX_set_session_id_context on client side SSL context

### PR DESCRIPTION
**Pull request by grantramsay**
* Issue: gh-105293

### CODE REVIEW

**Comment by grantramsay** [comment]
For back-compatibility, possibly `SSL_CTX_set_session_id_context` should also be called in `ssl.wrap_socket` if `server_side` and using one of the deprecated `ssl.PROTOCOL_*` enums. I can make that changes if reviewers think it is necessary

**Comment by gpshead** [comment]
> For back-compatibility, possibly `SSL_CTX_set_session_id_context` should also be called in `ssl.wrap_socket` if `server_side` and using one of the deprecated `ssl.PROTOCOL_*` enums. I can make that changes if reviewers think it is necessary

It sounds like that makes sense.  go for it in this PR and we'll take a look.

add some form of news entry once you've done that as well.

**Comment by grantramsay** [comment]
> > For back-compatibility, possibly `SSL_CTX_set_session_id_context` should also be called in `ssl.wrap_socket` if `server_side` and using one of the deprecated `ssl.PROTOCOL_*` enums. I can make that changes if reviewers think it is necessary
> 
> It sounds like that makes sense. go for it in this PR and we'll take a look.
> 
> add some form of news entry once you've done that as well.

Maybe I should just remove the call to `SSL_CTX_set_session_id_context` and only call `SSL_set_session_id_context` on the `SSL` object? This would avoid doing the same thing in two places

**Comment by gramsay0** [comment]
@gpshead I've updated this to only call `SSL_set_session_id_context` on the SSL object

**Review by gpshead — APPROVED** [review]

**Pull request merged**
