### PR TITLE
bpo-43008: Make IDLE respect sys.excepthook

### PR DESCRIPTION
**Pull request by Kenny2github**
This applies to default 2-process mode as excepthook already works in -n mode.

https://bugs.python.org/issue43008

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Kenny2github

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Kenny2github** [comment]
CLA signed, it'll take a bit to update tho

**Review by terryjreedy — DISMISSED** [review]
I answered on the issue what is required and desired.  
Recording of CLA is also required.  Won't happen before Monday at earliest.

**Review by terryjreedy — CHANGES_REQUESTED** [review]
Summary of issue post.  Require
1. Guard excepthook call, imitating standard result of excepthook exception.
2. Short blurb.
3. Minor doc change.
Want
4. Tests

**Comment by Kenny2github** [comment]
Besides the tests, I have made the requested changes; please review again. I didn't manage to figure out how to go about testing an excepthook in the first place, let alone a good or bad one. Hope that's not an issue.

**Review by terryjreedy — APPROVED** [review]

**Comment by terryjreedy** [comment]
Deleted bogus buildbot splat: test_asyncio altered the execution environment.

**Pull request merged**
