### PR TITLE
gh-116608: Apply style and compatibility changes from importlib_metadata.

### PR DESCRIPTION
**Pull request by jaraco**
* Issue: gh-116608

### CODE REVIEW

**Comment by jaraco** [comment]
I applied some [changes against importlib_resources 6.4](https://github.com/python/importlib_resources/compare/v6.4.0...81ddbef7bd95aef5eeb58a26000fe05e9276b8e4) and then merged those with the cpython branch of importlib_resources, then copied the remaining diff over to CPython. These changes represent the re-synchronization of the two codebases, mainly getting the style to align with the linter/formatter's opinion, but also one change to the context managers to be compatible with Python 3.8 syntax.

**Comment by jaraco** [comment]
I just noticed that "metadata" appears in the commit message. These changes pertain to "resources".

**Comment by encukou** [comment]
Well, to me this looks like style fixes that are traditionally avoided in CPython, but it does look harmless.

**Comment by jaraco** [comment]
> Well, to me this looks like style fixes that are traditionally avoided in CPython, but it does look harmless.

The problem is that it's untenable given the constraints on the CPython repo to have divergent styles between the CPython implementation and the third-party package. Due to its shared maintenance with other [skeleton](/jaraco/skeleton) projects, importlib_resources has a stricter standard for format, types, and lint. There's no VCS metadata to track the differences, so the process of contributing changes from `importlib_resources` (upstream) to `importlib.resources` will overwrite any changes that weren't applied upstream. This change does that overwriting so that it's not folded into a subsequent contribution.

**Comment by encukou** [comment]
Yeah, and from the other side, the custom tooling in `importlib_resources` makes it harder than it could be to properly contribute to `importlib.resources`.
I wonder if we should we add `importlib.resources` to PEP-360, or otherwise make `importlib_resources`'s style requirements, or contribution instructions in general, more discoverable?

**Comment by jaraco** [comment]
> I wonder if we should we add `importlib.resources` to [PEP-360](https://peps.python.org/360), or otherwise make `importlib_resources`'s style requirements, or contribution instructions in general, more discoverable?

I don't think adding it to PEP 360 would help much, given that the external project already provides most of that context (who maintains it, which versions are compatible), and the two codebases are maintained jointly. I note also that `importlib_metadata` and `zipp` follow the same regime, and at least for those, the CPython docs to provide a link to the external mirror / backport. I note also that I run into similar issues with [configparser](/jaraco/configparser), even though it follows a [more conventional backport role](https://github.com/jaraco/configparser?tab=readme-ov-file#conversion-process), `backports.tarfile`, `singledispatch`, and probably others.

On several occasions, I've wanted to have a good place to document this regime, to include contribution instructions and maintenance instructions, but the main thing that's held me back is lack of an appropriate shared space (it felt awkward to put the docs in one project that apply equally to three). I seem to recall at one point I did document the process, but I'm unable to find it. Correction, I [found it here](https://gitlab.com/python-devs/importlib_metadata/-/wikis/Refreshing-CPython). That guidance is still somewhat relevant, but also out of date and incomplete. I should probably just revive that doc in a maintained repo/wiki (probably importlib_metadata), and just link to it from the relevant projects. We should also update the `importlib.resources` docs to provide a reference to `importlib_resources`.

My preference is to accept changes in the external project first for several reasons, that I'll document in the contributing guide, but I'm happy to accept contributions in CPython as long as the contribution is amenable to a backport.

**Pull request merged**
