### PR TITLE
[3.12] Generalize reusable Windows CI jobs (#121766)

### PR DESCRIPTION
**Pull request by webknjaz**
(cherry picked from commit 7982363b479e22fffc72481e54c9f40ace8a0021)

### CODE REVIEW

**Comment by webknjaz** [comment]
@hugovk this is mergeable now.

**Comment by webknjaz** [comment]
@hugovk conflicts fixed!

**Comment by webknjaz** [comment]
@hugovk here's another backport

**Comment by hugovk** [comment]
Thanks for the reminder, will check it now!

**Pull request merged**
