### PR TITLE
bpo-39761: dtrace build fix for Linux and non Linux systems.

### PR DESCRIPTION
**Pull request by devnexen**
https://bugs.python.org/issue39761

### CODE REVIEW

**Comment by hroncok** [comment]
I can verify this fixes the build on Fedora. Not sure if this is the best or even the proper fix, not sure how it affects other unix-ish systems, but it get's the job done for us.

**Comment by encukou** [comment]
I don't think Linux should be an exception. ISTM that the issue is not with Linux, but rather with empty `DFLAGS`.

**Comment by encukou** [comment]
See https://github.com/python/cpython/pull/18766 for another approach.

**Comment by ned-deily** [comment]
It appears this issue was resolved with the change in #18766. Thanks for submitting the PR and sorry this remained open for so long.

**Pull request closed without merging**
