### PR TITLE
gh-115382: Fix cross compiles when host and target use same SOABI

### PR DESCRIPTION
**Pull request by vfazio**
Previously, when a build was configured to use a host interpreter via --with-build-python, the PYTHON_FOR_BUILD config value included a path in PYTHONPATH that pointed to the target's built external modules.

For "normal" foreign architecture cross compiles, when loading compiled external libraries, the target libraries were processed first due to their precedence in sys.path. These libraries were then ruled out due to a mismatch in the SOABI so the import mechanism continued searching until it found the host's native modules.

However, if the host interpreter and the target python were on the same version + SOABI combination, the host interpreter would attempt to load the target's external modules due to their precedence in sys.path.

Despite the "match", the target build may have been linked against a different libc or may include unsupported instructions so loading or executing the target's external modules can lead to crashes.

Now, the path to the target's external modules is no longer defined in PYTHONPATH to prevent accidentally loading these foreign modules.

One caveat is that during certain build stages, the target's sysconfig module requires higher precedence than the host's version in order to accurately query the target build's configuration.

This worked previously due to the target's sysconfig data module having precedence over the host's (see above). In order to keep this desired behavior, a new environment variable, _PYTHON_SYSCONFIGDATA_PATH, has been defined so sysconfig can search this directory for the target's sysconfig data.

* Issue: gh-115382

### CODE REVIEW

**Comment by vfazio** [comment]
Note, I did _not_ convert some of the other places that seem to replicate the PYTHONPATH pattern, specifically the wasm paths:

https://github.com/python/cpython/blob/3cac2af5ecfa9e2a47bfdd15e114b65780836b9d/Tools/wasm/wasm_build.py#L335
https://github.com/python/cpython/blob/3cac2af5ecfa9e2a47bfdd15e114b65780836b9d/Tools/wasm/build_wasi.sh#L28
https://github.com/python/cpython/blob/3cac2af5ecfa9e2a47bfdd15e114b65780836b9d/Tools/wasm/wasi.py#L212
https://github.com/python/cpython/blob/3cac2af5ecfa9e2a47bfdd15e114b65780836b9d/configure.ac#L1587

I expect those should still work as is, though they could certainly change to using `_PYTHON_SYSCONFIGDATA_PATH` if their intent is purely to import sysconfig and not any other modules that may be in that directory.

**Comment by vfazio** [comment]
@FFY00 @erlend-aasland @corona10 please let me know if is there any other information I can provide to help move this along.

**Comment by erlend-aasland** [comment]
@vfazio, I don't have the bandwidth to review this any time soon :( Hopefully in a few weeks.

**Comment by yann-morin-1998** [comment]
`Tested-by: Yann E. MORIN <yann.morin.1998@free.fr>`

**Comment by bkuhls** [comment]
```
Tested-by: Bernd Kuhls <bernd@kuhls.net>
```

**Review by FFY00 — APPROVED** [review]
@vfazio, thank you so much for working on this, and sorry for the delay it took to get the PR reviewed. Also, thanks to everyone who tested it.

The proposed solution seems okay, I am just gonna trigger the tests to run on the buildbots to make sure nothing is unexpectedly broken there before merging.

**Comment by vfazio** [comment]
> @vfazio, thank you so much for working on this, and sorry for the delay it took to get the PR reviewed. Also, thanks to everyone who tested it.
> 
> The proposed solution seems okay, I am just gonna trigger the tests to run on the buildbots to make sure nothing is unexpectedly broken there before merging.

Thanks for taking a look and kicking this off! 

If this gets accepted, is there any chance i could follow it up with a patch for 3.12 or other earlier versions?

At the time of writing, one test is failing due to a disk space error and another due to PEG parser errors which I cant imagine are related to my PR.

**Comment by vfazio** [comment]
I don't think any of the failures are related to this MR. Im not sure if any of the buildbots attempt to cross compile, it may be worth adding a couple of those scenarios at some point in the future.

**Comment by vfazio** [comment]
@FFY00 Do you want me to rebase this PR on main or can this be merged as is?

**Comment by vfazio** [comment]
> @FFY00 @erlend-aasland @corona10 please let me know if there is any other information I can provide to help move this along.

Apologies in advance for the bump, but I just want to make sure there's no additional followup necessary from me on this PR.

**Comment by vfazio** [comment]
@FFY00 @erlend-aasland @corona10 just wanted to reach out again on this PR and see if there are changes necessary and if there's a chance of getting it merged and ported to 3.12/3.13. It will require minor tweaks to target 3.12 I think.

**Comment by erlend-aasland** [comment]
@vfazio: I'll review this at the PyCon sprints next week! Thanks for your patience.

**Comment by vfazio** [comment]
> @vfazio: I'll review this at the PyCon sprints next week! Thanks for your patience.

Thanks, I realize you're all busy people so I apologize for the pings, I just want to make sure there's nothing blocking on me.

**Comment by vfazio** [comment]
@erlend-aasland should i rebase this PR occasionally?

**Comment by vfazio** [comment]
i'm using `spec = FileFinder(path, (SourceFileLoader, SOURCE_SUFFIXES)).find_spec(name)` but i wonder if it would be better to use `importlib.util.spec_from_file_location` ?

**Comment by vfazio** [comment]
@FFY00 @erlend-aasland @corona10 friendly ping

**Comment by vfazio** [comment]
@FFY00 @erlend-aasland @corona10 friendly ping

**Comment by FFY00** [comment]
Sorry for the delay! GIthub notifications are out of hand and it's difficult to keep track of everything.

**Comment by vfazio** [comment]
> Sorry for the delay! GIthub notifications are out of hand and it's difficult to keep track of everything.

I totally understand. Thanks again for your help with this, I sincerely appreciate it! 

Do you think there's a chance of porting this back to 3.13?

**Comment by FFY00** [comment]
Personally, I am fine with it, though I would like the release manager to approve it since it introduces a behavior change when the `_PYTHON_SYSCONFIGDATA_PATH` environment variable is specified.

@Yhg1s what do you think?

**Comment by Yhg1s** [comment]
Yeah, I'm okay with this being backported. It seems like a reasonable bugfix and it shouldn't affect anything else. (Anything already setting _PYTHON_SYSCONFIGDATA_* environment variables should realise they're explicitly meddling with Python sysconfig internals ;p)

**Comment by vfazio** [comment]
> Yeah, I'm okay with this being backported. It seems like a reasonable bugfix and it shouldn't affect anything else. (Anything already setting `_PYTHON_SYSCONFIGDATA_*` environment variables should realise they're explicitly meddling with Python sysconfig internals ;p)

The last time i backported something, miss Islington did the grunt work. Im not sure if it ports back cleanly, im out of town so wont be able to check for a couple of weeks.

**Comment by terryjreedy** [comment]
@vfazio Do not rebase PRs ever.  Update merges on your working copy branch before pushing edits to your fork are a good idea to make sure no conflicts have arisen and to test locally with current code.  The merged 3.13 backport should have been listed after the 'working' message.

**Comment by vfazio** [comment]
> @vfazio Do not rebase PRs ever. Update merges on your working copy branch before pushing edits to your fork are a good idea to make sure no conflicts have arisen and to test locally with current code. The merged 3.13 backport should have been listed after the 'working' message.

Every repo/maintainer has a different flow. I'm now aware of CPython's workflow so it shouldnt be a problem going forward.

**Pull request merged**
