### PR TITLE
bpo-30346: Exhaust groupby() sub-iterator when move the primary iterator

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue30346

### CODE REVIEW

**Comment by DimitrisJim** [comment]
It seems you have created two PRs (by accident?) for this issue (this PR and #1568).

**Comment by serhiy-storchaka** [comment]
Yes, I have created two alternate PRs by intention.

**Comment by kristjanvalur** [comment]
I prefer the other solution (PR #1568)

**Review by rhettinger — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thank you @rhettinger! I prefer the other solution (#1568), but this also LGTM.

**Pull request merged**
