### PR TITLE
gh-94916: change Py_buffer::format const char*

### PR DESCRIPTION
**Pull request by maxbachmann**
How does Python handle issues like this? Strictly speaking changing this parameter to `const char*` is a breaking change, since users might rely on this:
```cpp
Py_buffer* buffer = ...;
char* format = buffer->format;
```
even though this is documented in this way.
The alternative would be to update the documentation to state that the type is `char*`, but any modification leads to UB. This would allow users to cast the constness away:
```cpp
Py_buffer* buffer = ...;
const char* format = ...;
buffer->format = const_cast<char*>(format);
```

related issue: #94916

* Issue: gh-94916

### CODE REVIEW

**Comment by maxbachmann** [comment]
Looking at the github actions warnings, Cpython appears to rely on this not being const as well. So I assume this should be fixed in the documentation instead.

**Comment by hauntsaninja** [comment]
> Looking at the github actions warnings, Cpython appears to rely on this not being const

Which warning are you looking at? The failed check is because most changes to CPython require a news entry (changelog entry)

**Comment by maxbachmann** [comment]
https://github.com/python/cpython/pull/94917/files
shows that CPython uses e.g. `PyMem_Free(self->master.format);` which would need to be `PyMem_Free((char*)self->master.format);` after the change.

**Comment by maxbachmann** [comment]
@hauntsaninja is this change possible from a backwards compatibility standpoint, or is it better to just update the docs to state that while the variable is not of type `const char*` it should be treated that way.

**Pull request closed without merging**
