### PR TITLE
bpo-39849: Fix compiler warning in _testcapimodule

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue39849

### CODE REVIEW

**Review by corona10 — APPROVED** [review]
LGTM, I 've checked on my local machone, no warning is now showing.

**Comment by corona10** [comment]
@serhiy-storchaka @vstinner Please take a look.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by corona10** [comment]
@serhiy-storchaka  I will merge it after my mentor's approval :) cc @vstinner

**Comment by vstinner** [comment]
If I recall correctly, `(void) res;` doesn't silence the warning in some cases. Sorry, I don't recall in which case (which compiler, which compiler flags). Maybe it's enough for most cases.

I'm unhappy with the fix: _testcapi.test_buildvalue_issue38913() ensures that `Py_BuildValue()` returns NULL and raises an exception. If it's not the case, the test must fail.

For me, the assertion is part of the test and _testcapi must never be compiled without assertions.

@shihai1991: Can you please write a different PR which ensure that _testcapimodule.c and _testinternalcapi.c always enable assertions? Just put the following code at the top:

```
/* Always enable assertions */
#undef NDEBUG
```

**Comment by shihai1991** [comment]
> If I recall correctly, `(void) res;` doesn't silence the warning in some cases. Sorry, I don't recall in which case (which compiler, which compiler flags). Maybe it's enough for most cases.
> 
> I'm unhappy with the fix: _testcapi.test_buildvalue_issue38913() ensures that `Py_BuildValue()` returns NULL and raises an exception. If it's not the case, the test must fail.
> 
> For me, the assertion is part of the test and _testcapi must never be compiled without assertions.
> 
> @shihai1991: Can you please write a different PR which ensure that _testcapimodule.c and _testinternalcapi.c always enable assertions? Just put the following code at the top:
> 
> ```
> /* Always enable assertions */
> #undef NDEBUG
> ```

Sure, let me try it ;)

**Comment by shihai1991** [comment]
@vstinner Hi, victor. I enable assertions in #19623

**Comment by vstinner** [comment]
@corona10: I suggest to merge PR #19623 instead, it's a more generic solution and it may help to catch more bugs in release builds. You can merge PR #19623 if you want.

**Pull request closed without merging**
