### PR TITLE
GH-82604: fix docs about configuring event loop

### LINKED ISSUE #82604: Event loop implementation docs advertise set_event_loop which doesn't work with asyncio.run
BPO | [38423](https://bugs.python.org/issue38423)
--- | :---
Nosy | @hniksic, @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-09.17:14:39.175>
labels = ['3.8', 'docs', '3.7', '3.9', 'expert-asyncio']
title = "Event loop implementation docs advertise set_event_loop which doesn't work with asyncio.run"
updated_at = <Date 2020-01-27.15:18:48.508>
user = 'https://github.com/hniksic'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-27.15:18:48.508>
actor = 'Cilyan Olowen'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'asyncio']
creation = <Date 2019-10-09.17:14:39.175>
creator = 'hniksic'
dependencies = []
files = []
hgrepos = []
issue_num = 38423
keywords = []
message_count = 4.0
messages = ['354288', '354289', '360770', '360772']
nosy_count = 5.0
nosy_names = ['hniksic', 'asvetlov', 'docs@python', 'yselivanov', 'Cilyan Olowen']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38423'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-82604

Closes https://github.com/python/cpython/issues/82604

### CODE REVIEW

**Review by gvanrossum — COMMENTED** [review]
I'm not a fan of this approach. Let's instead update the example to use `set_event_loop_policy()` instead. That _is_ honored by `asyncio.run()` so we won't need the note.

(Didn't the OP mention this is also a problem with the proactor docs?)

**Comment by kumaraditya303** [comment]
> Let's instead update the example to use set_event_loop_policy() instead. That is honored by asyncio.run() so we won't need the note.

Do you mean to subclass the policy and then override the selector?

> (Didn't the OP mention this is also a problem with the proactor docs?)

I didn't find any mention in proactor docs.

**Comment by gvanrossum** [comment]
> Do you mean to subclass the policy and then override the selector?

Yeah, it looks like you can do something like this (untested)

```py
class MyPolicy(asyncio.DefaultEventLoopPolicy):
    def new_event_loop(self):
        selector = <what the example had>
        return asyncio.SelectorEventLoop(selector)

asyncio.set_event_loop_policy(MyPolicy())
```

**Comment by gvanrossum** [comment]
> I didn't find any mention in proactor docs.

Okay no worries about that then.

**Review by gvanrossum — APPROVED** [review]
Let's do it!

**Pull request merged**
