### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by Nemo2011**
#98122

### CODE REVIEW

**Comment by sobolevn** [comment]
Please, don't do this :)
Right now this looks like a spam.

There are actual work pieces in issue tracker, solving which can benefit to everyone :)

**Comment by sobolevn** [comment]
I am sorry, this is not a spam.

@Nemo2011 please, next time describe the problem / solution better :)

This PR removes a garbled character. Reopening.

**Comment by AlexWaygood** [comment]
(Cc. @carljm as well)

**Comment by AlexWaygood** [comment]
For the benefit of other reviewers: this PR removes a `U+000c` character that is present on line 28 of `Lib/email/__init__.py`. This unicode character is "invisible", so the change doesn't show up on the GitHub diff, making it look like this is an "empty" PR. However, if you open `Lib/email/__init__.py` (as it exists on the `main` branch) in VSCode or IDLE, you can see the character:

image.

Interestingly enough, it looks like the character has been in the source code for around 15 years now, since https://github.com/python/cpython/commit/8b3febef2f96c35e9aad9db2ef499db040fdefae.

**Comment by gvanrossum** [comment]
I am rejecting this proposal. It is not well motivated and the Python source code has long contained ^L characters, strategically placed to allow certain Emacs users to jump to them as "page" level separators. ^L is treated as a newline in the Python lexer.

**Pull request closed without merging**
