### PR TITLE
[2.7] bpo-30450: Don't use `where`, it doesn't exist on XP

### PR DESCRIPTION
**Pull request by zware**
https://bugs.python.org/issue30450

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM even if I don't know Windows error codes :-)

**Review by zooba — APPROVED** [review]

**Comment by zooba** [comment]
Do builds on XP even work? I thought we supported it as a target, but not a build OS.

**Comment by vstinner** [comment]
Don't skip the issue, if there is an issue :-) https://bugs.python.org/issue30450

**Comment by zware** [comment]
@zooba http://buildbot.python.org/all/builders/x86%20Windows%20XP%202.7/builds/276

**Pull request merged**
