### PR TITLE
bpo-33130

### PR DESCRIPTION
**Pull request by vreuter**
The collection argument to `functools.reduce` need only be an iterable, not necessarily a sequence.

https://bugs.python.org/issue33130

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by JulienPalard** [comment]
> since a user may apply a non-commutative function.

You looks to imply that a iterable is unordered, which is wrong, an iterable is as ordered as a sequence, the sequence only has the property to access any member efficiently by integer indice.

> the docstring refers to sequence

And the implementation uses the iterator protocol. I would fix the docstring instead of the documentation.

Would you also open an issue on bugs.python.org and rename your PR with "bpo-xxx" with the issue number, and please sign the CLA?

**Comment by vreuter** [comment]
Got it, thanks for clarifying; the changes now reflect that logic. I've signed the CLA, but it looks like it takes a bit to update, perhaps?

**Review by rhettinger — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Please make the title of the PR more descriptive.

**Comment by ncoghlan** [comment]
(Note: the CLA *has* been signed, there was just a filing issue getting the records updated on the PSF side - I'll adjust the label again once the user record has been updated on b.p.o)

**Comment by vstinner** [comment]
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

**Comment by brettcannon** [comment]
There doesn't seem to be any changed files. I'm assuming the proposed changes were already made in another PR at some point, so I'm going to close this PR.

**Pull request closed without merging**
