### PR TITLE
bpo-44872: use new trashcan macros in framobject.c

### PR DESCRIPTION
**Pull request by iritkatriel**
https://bugs.python.org/issue44872

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]
Thanks @iritkatriel for the PR!

**Comment by iritkatriel** [comment]
Should we backport this?  The issue goes back to 3.8 so I think yes.

**Comment by pablogsal** [comment]
For 3.10 for sure, for 3.9 and 3.8 I think we should but we should check first with @ambv

**Comment by ambv** [comment]
Segfaulting the interpreter with code that worked fine in 3.7 sounds like a potential security-grade bug. Thus, please backport to 3.8 as well.

**Pull request merged**
