### PR TITLE
gh-89519: Remove classmethod descriptor chaining, deprecated since 3.11

### PR DESCRIPTION
**Pull request by rhettinger**
* Issue: gh-89519

----
:books: Documentation preview :books:: https://cpython-previews--110163.org.readthedocs.build/

### CODE REVIEW

**Comment by rhettinger** [comment]
I'm still working on the doctest for the descriptor howto.  It looks like the classmethod emulation is imperfect after the classproperty has been removed.

**Comment by KevinMGranger** [comment]
Will this break [the pattern described as an alternative to `abc.abstractclassmethod`](https://docs.python.org/3/library/abc.html#abc.abstractclassmethod)?

**Comment by rhettinger** [comment]
@KevinMGranger The examples for combining `abstractmethod` with `classmethod` and `staticmethod` will still work.  This is tested in `test_abstractclassmethod_basics()` in `Lib/test/test_abc`.  Also, here's a live demonstration:

```
% ./python.exe
Python 3.13.0a0 (heads/remove_classmethod_descriptor_chaining:8336eb0b87, Oct 24 2023, 14:41:05) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from abc import ABC, abstractmethod
>>> class C(ABC):
...     @classmethod
...     @abstractmethod
...     def my_abstract_classmethod(cls, arg):
...         ...
...
>>> C()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class C without an implementation for abstract method 'my_abstract_classmethod'

```

Note, these examples have worked since Python 3.3 which was long before the broken descriptor chaining arrived in Python 3.9.  So, they are independent of the change being reverted.  Thanks for asking.

**Comment by itamaro** [comment]
Looking forward to see this getting merged!

fwiw, I ran into an issue related to classmethod descriptor chaining in the Meta codebase -- some code (that was written for Python 3.8, doing a bunch of signature and type inspection of decorated methods) started breaking under Python 3.10.
I backported the deprecation from 3.11 and this removal into Cinder 3.10, and it resolved the issue.

If it helps with confidence in the removal - this PR ([cleanly backported to 3.10](https://github.com/facebookincubator/cinder/commit/6f02c7f5024c84fc027baa2280548938de42bd30)) is running in production (in Instagram and other Meta Python services), after all internal test suites passed (including the full Instagram test suite).

**Comment by rhettinger** [comment]
@itamaro Thank you for your comment.  Indeed, it does increase the confidence in the PR.

**Pull request merged**
