### PR TITLE
bpo-43958: Document importlib.metadata.PackagePath.locate method

### PR DESCRIPTION
**Pull request by pfmoore**
https://bugs.python.org/issue43958

### CODE REVIEW

**Comment by jaraco** [comment]
I intend to look at this this weekend. I don’t expect it to be controversial but want to be sure the docs appear in the backport also.

**Comment by jaraco** [comment]
Also pushed to python/importlib_metadata@edb1d44223.

**Comment by domdfcoding** [comment]
Can this be backported to 3.9 as it is still wrong/confusing when viewing https://docs.python.org/3/library/importlib.metadata.html#distribution-files

**Comment by domdfcoding** [comment]
Thanks

**Pull request merged**
