### PR TITLE
bpo-40956: [regression] first argument in sqlite3.Connection.backup is mandatory

### PR DESCRIPTION
**Pull request by erlend-aasland**
Regression introduced by GH-23838.

https://bugs.python.org/issue40956

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@berkerpeksag would you please review?

**Comment by erlend-aasland** [comment]
skip news

**Review by berkerpeksag — CHANGES_REQUESTED** [review]
Could you please add a test case to confirm that the regression is fixed by this?

You can rename `test_bad_target_none` to `test_bad_target` and add the new test here:

https://github.com/python/cpython/blob/749d40a53f8bbb9bb9d4eda345e54e3b3be7b459/Lib/sqlite3/test/backup.py#L20-L22

**Comment by berkerpeksag** [comment]
And this is actually need a NEWS entry because the previous PR has already been released in 3.10 alphas.

**Comment by erlend-aasland** [comment]
> Could you please add a test case to confirm that the regression is fixed by this?

Sure, I'll do it first thing tomorrow.

> And this is actually need a NEWS entry because the previous PR has already been released in 3.10 alphas.

I see. Thanks for the heads-up.

**Comment by erlend-aasland** [comment]
BTW, will you have time to review #24203 and  #24421 any time soon?

**Comment by berkerpeksag** [comment]
> BTW, will you have time to review #24203 and #24421 any time soon?

I'm on holidays at the moment so will see :) They are definitely on my TODO list, though.

**Comment by erlend-aasland** [comment]
> > BTW, will you have time to review #24203 and #24421 any time soon?
> 
> I'm on holidays at the moment so will see :) They are definitely on my TODO list, though.

Oops, sorry! Enjoy your days off :) Thanks!

(I have made the requested changes; please review again)

**Review by berkerpeksag — APPROVED** [review]
LGTM!

**Comment by erlend-aasland** [comment]
Thanks, @berkerpeksag 🙏🏻

**Pull request merged**
