### PR TITLE
gh-102809: Remove `Misc/gdbinit`

### PR DESCRIPTION
**Pull request by sobolevn**
Looks like the consensus is that we don't need this file anymore.
Old version can be always found here: https://github.com/python/cpython/blob/094cf392f49d3c16fe798863717f6c8e0f3734bb/Misc/gdbinit

* Issue: gh-102809

### CODE REVIEW

**Comment by sobolevn** [comment]
Do we need news for it? 🤔

**Comment by gpshead** [comment]
> Do we need news for it? 🤔

It is good to include a tiny NEWS note. "Misc/gdbinit was removed."

**Comment by sobolevn** [comment]
Thank you!

**Comment by hroncok** [comment]
The file is still referenced in [the README](https://github.com/python/cpython/blob/main/Misc/README)

**Comment by hroncok** [comment]
Oh, https://github.com/python/cpython/pull/103269

**Pull request merged**
