### PR TITLE
bpo-36922: implement Py_TPFLAGS_METHOD_DESCRIPTOR

### PR DESCRIPTION
**Pull request by jdemeyer**
CC @encukou @markshannon 

https://bugs.python.org/issue36922

### CODE REVIEW

**Comment by jdemeyer** [comment]
Petr: do you think this should be `_Py_TPFLAGS_METHOD_DESCRIPTOR` (with underscore) or is this useful enough to make public right away?

This PR is otherwise independent from the rest of PEP 590, so it's possible to make it public.

**Comment by encukou** [comment]
I don't see this one changing, so I'm OK with making this public.

**Review by encukou — COMMENTED** [review]
This looks good, thank you! It should go in after PEP is accepted.

**Comment by jdemeyer** [comment]
Rebased to latest master (no other changes).

**Pull request merged**
