### PR TITLE
CI: Configure macOS build as per updated devguide recommendations

### PR DESCRIPTION
**Pull request by erlend-aasland**
The devguide was recently updated: python/devguide#1058

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Regarding backporting, didn't we backport as far as possible last time we did this?

**Comment by ned-deily** [comment]
I think you'll find that 3.7 through 3.10 have already been backported :)  So it should be just 3.11, 3.12, and main that need changing.

**Comment by ned-deily** [comment]
#105304
#105303 
#105302 
#104998

**Comment by erlend-aasland** [comment]
> I think you'll find that 3.7 through 3.10 have already been backported :) So it should be just 3.11, 3.12, and main that need changing.

Great, thanks! :)

**Pull request merged**
