### PR TITLE
gh-108416: Mark slow test methods with @requires_resource('cpu')

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-108416

### CODE REVIEW

**Comment by vstinner** [comment]
How did you decide if a function is "slow" or not?

**Comment by ambv** [comment]
Results from macOS 13.5 on M1 Max: from 5 minutes 11 seconds down to 2 minutes 25 seconds.

I would prefer if there was some indication in the summary of how many tests were skipped due to not enabling various resources. We can add this in a separate PR but I consider this important. Right now it's easy to miss the fact that you ran fewer tests. It says "428 tests OK" in both cases.

### -m test -j12 -ucpu (with slow tests)
```
428 tests OK.

10 slowest tests:
- test_math: 3 min 18 sec
- test_tools: 2 min 38 sec
- test_concurrent_futures: 2 min 31 sec
- test_capi: 1 min 39 sec
- test.test_multiprocessing_spawn.test_processes: 1 min 25 sec
- test_faulthandler: 1 min 17 sec
- test_tokenize: 1 min 11 sec
- test_unparse: 1 min 9 sec
- test.test_multiprocessing_forkserver.test_processes: 59.9 sec
- test_signal: 56.2 sec

1 test altered the execution environment:
    test_tools

27 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils
    test.test_multiprocessing_fork.test_manager
    test.test_multiprocessing_fork.test_misc
    test.test_multiprocessing_fork.test_processes
    test.test_multiprocessing_fork.test_threads test_curses
    test_dbm_gnu test_devpoll test_epoll test_gdb test_ioctl
    test_launcher test_perf_profiler test_perfmaps test_smtpnet
    test_socketserver test_startfile test_tkinter test_ttk
    test_urllib2net test_urllibnet test_winconsoleio test_winreg
    test_winsound test_wmi test_zipfile64

Total duration: 5 min 11 sec
Tests result: ENV CHANGED

________________________________________________________
Executed in  312.17 secs    fish           external
   usr time   31.05 mins   48.00 micros   31.05 mins
   sys time    2.44 mins  379.00 micros    2.44 mins
```

### -m test -j12 -u-cpu (without slow tests)
```
428 tests OK.

10 slowest tests:
- test_concurrent_futures: 1 min 26 sec
- test.test_multiprocessing_spawn.test_processes: 1 min 14 sec
- test_capi: 1 min 10 sec
- test_faulthandler: 1 min 4 sec
- test.test_multiprocessing_forkserver.test_processes: 49.6 sec
- test_tarfile: 39.9 sec
- test.test_multiprocessing_spawn.test_misc: 37.3 sec
- test_ssl: 35.8 sec
- test_socket: 33.1 sec
- test.test_multiprocessing_spawn.test_manager: 33.0 sec

28 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils
    test.test_multiprocessing_fork.test_manager
    test.test_multiprocessing_fork.test_misc
    test.test_multiprocessing_fork.test_processes
    test.test_multiprocessing_fork.test_threads test_curses
    test_dbm_gnu test_devpoll test_epoll test_gdb test_ioctl
    test_launcher test_peg_generator test_perf_profiler test_perfmaps
    test_smtpnet test_socketserver test_startfile test_tkinter
    test_ttk test_urllib2net test_urllibnet test_winconsoleio
    test_winreg test_winsound test_wmi test_zipfile64

Total duration: 2 min 25 sec
Tests result: SUCCESS

________________________________________________________
Executed in  146.01 secs    fish           external
   usr time   16.23 mins   47.00 micros   16.23 mins
   sys time    1.16 mins  373.00 micros    1.16 mins
```

**Comment by serhiy-storchaka** [comment]
> Results from macOS 13.5 on M1 Max: from 5 minutes 11 seconds down to 2 minutes 25 seconds.

Is it the time of running all tests? It is impressive, I did not expect such difference.

This PR adds `@requires_resource('cpu')` to 86 tests out of 41665, i.e. it allows to skip 0.2% of tests. And it leads to reducing the time more than twice?! :exploding_head:

> I would prefer if there was some indication in the summary of how many tests were skipped due to not enabling various resources. We can add this in a separate PR but I consider this important.

I'll do this. Currently the summary only shows if the test file was skipped completely, but not if a TestCase class or separate method was skipped. Although I afraid that the output can be very verbose, because normally many tests are skipped for different reasons. But it would be useful to have such option.

**Comment by gpshead** [comment]
Sync and merge past the parallelization refactorings that Victor merged before measuring again.

I don't think we should be abusing the 'cpu' resource for this. Many of these are not CPU hogs so that becomes misleading.  Some are important to have run so that we don't break everything. (the AST test that parses the stdlib for example)

Should I go through all 86 tests and give a thumbs up / thumbs down to them being annotated?  I'm against merging this as it is... but I think we can get something in sensible shape.

(deeper thoughts recorded on the issue)

**Comment by serhiy-storchaka** [comment]
Some tests (`test_random_files` in `Lib/test/test_tokenize.py`, `test_files` in `Lib/test/test_unparse.py`) test if the cpu resource is enabled, and if it is not, they are not skipped, but run with a small subset of the inputs. I use the same approach in my work-in-progress patch for `test_unicodedata`. I think that we should use this approach more if it is appropriate (not all tests can be downscaled). But first we should know what tests are slow and for what cause.

**Comment by vstinner** [comment]
> they are not skipped, but run with a small subset of the inputs

Please log a message in verbose mode, to help debugging. It's surprising when a test pass and then fail on the same machine.

**Comment by serhiy-storchaka** [comment]
> Please log a message in verbose mode, to help debugging. It's surprising when a test pass and then fail on the same machine.

They print full lists of tested files in verbose mode.

**Comment by serhiy-storchaka** [comment]
> Should I go through all 86 tests and give a thumbs up / thumbs down to them being annotated?

It would help. There are now half as many of them. I have reviewed each case several times and can justify them. But there is always the possibility of missing something and my criteria could be wrong.

**Comment by serhiy-storchaka** [comment]
`test_sumprod_stress` kills a buildbot: https://buildbot.python.org/all/#/builders/256/builds/1211/steps/6/logs/stdio

**Comment by vstinner** [comment]
> test_sumprod_stress kills a buildbot

It's a test_math test.

**Review by gpshead — APPROVED** [review]
These all make sense as `cpu` hogs to me.

**Comment by vstinner** [comment]
I'm a bit worried that you might forget to un-skip tests in the future, like ``test_crashers`` which only run for 3 hours, and then was always skipped for 12 years.

So I wrote PR #108793 to write a more detailed report on tests statistics. To remind that some tests are skipped (for good or bad reasons).

**Comment by serhiy-storchaka** [comment]
`test_crashers` was run for 3 days, not hours!

These tests are not skipped. I almost always run tests with `-uall`, and buildbots usually do the same. Well, now there will be more reasons to me to run them with `-uall,-cpu` by default, but I'll still continue to run them with `-uall` sometimes.

On other hand, bigmem tests are disabled by default, and run very infrequently. Some of them require over 200GB of memory, so they are never run.

**Comment by serhiy-storchaka** [comment]
Thank you for your review @gpshead. Could you look also at #108480?

**Pull request merged**
