### PR TITLE
added initial .travis.yml

### PR DESCRIPTION
**Pull request by krichter722**

### CODE REVIEW

**Comment by holdenweb** [comment]
Thanks for your pull request. Please note that this repository is a mirror, and so pull requests are not actioned. Please visit the [Python Developer's Guide page](https://docs.python.org/devguide/) for further information.

**Comment by yarikoptic** [comment]
since no issues page, I will hijack this PR ;)
Could you please push fresh tags?  the last one atm is v3.3.1 while there were 3.4 and 3.5 release

**Comment by krichter722** [comment]
>  Could you please push fresh tags? the last one atm is v3.3.1 while there were 3.4 and 3.5 release
Please explain!

**Comment by yarikoptic** [comment]
not sure what else could I add, may be this would help:
```
$> git fetch -a
$> git tag | sort -n | tail
v3.3.0a2
v3.3.0a3
v3.3.0a4
v3.3.0b1
v3.3.0b2
v3.3.0rc1
v3.3.0rc2
v3.3.0rc3
v3.3.1
v3.3.1rc1
$> git describe --tags master
v3.3.0-33743-g0851c46
$> ls -l ./Doc/whatsnew/3.[456]*
-rw------- 1 yoh yoh 110550 Jul 30 14:27 ./Doc/whatsnew/3.4.rst
-rw------- 1 yoh yoh  42880 Jul 30 14:27 ./Doc/whatsnew/3.5.rst
-rw------- 1 yoh yoh   3900 Jul 30 14:27 ./Doc/whatsnew/3.6.rst
```

**Comment by yarikoptic** [comment]
doh -- now I see that there is no tags whatsoever in this github repo  (where did I get mine then? ;) ) -- so why not to push release tags in general since there are none ?

**Comment by krichter722** [comment]
I guess this is a `hg` -> `git` conversion issue. No idea where you got the tags. `git` isn't supported well by `cpython` project, so we might be stuck with the situation.

Anyway, you can just checkout the PR's branch travis-2.7 and rebase it on any branch you want.

**Comment by yarikoptic** [comment]
doh -- github didn't post my reply sent by email:

On Thu, 30 Jul 2015, krichter722 wrote:

>    I guess this is a hg -> git conversion issue.

FWIW -- gh -> git conversion usually works just fine (well -- depending
how it is done of cause), but for reference:

```
$> git clone hg::https://hg.python.org/cpython cpython-hggit
Cloning into 'cpython-hggit'...
requesting all changes
adding changesets
...
$> cd cpython-hggit
$> git tag | tail
v3.4.3
v3.4.3rc1
v3.5.0a1
v3.5.0a2
v3.5.0a3
v3.5.0a4
v3.5.0b1
v3.5.0b2
v3.5.0b3
v3.5.0b4
```

**Comment by krichter722** [comment]
I can't push the `hggit` tags to this github fork (`git` pushes all blobs and aborts after 2 GB which is the max. from githubs side). Please explain again, why you need them and why it's worth spending time to workaround the fact that the tags are initially missing (with the workaround to `rebase` the PR branch in mind).

**Comment by yarikoptic** [comment]
1. Not quite following here (.git of this repo seems to be only ~300MB) or you thought to redo it with "hggit" way I have demonstrated? and push that in addition?  how was syncing (hg->git) was done before?
2. why tags are useful ? for variety of "activities" such as e.g. the "Git describe" I have already noted or checking out/building specific releases

**Comment by krichter722** [comment]
> Not quite following here (.git of this repo seems to be only ~300MB) or you thought to redo it with "hggit" way I have demonstrated? and push that in addition? how was syncing (hg->git) was done before?

I have to get the tags from a seperate `hggit` clone because it's the only source for tags (you must have gotten them from there as well). I tried to pushing them to this fork by adding a `git` remote and issueing `git push --tags fork` where `fork` is this fork and it died after 2 GB upload as described.

> why tags are useful ?

My question was why you need them. Please explain by distinguishing necessity and help/usefulness.

**Comment by yarikoptic** [comment]
My obvious use is to identify my "location" in the code base. E.g. I cloned this repository, and want to know "Where am I" respectively to the last release (assuming that releases got done from the master branch), so I do "git describe".  that is what I did here and got confused with v3.3.0-33743-g0851c46. Then often I want to see where (again respective to releases) any given change (commit) was done (e.g. this time was investigating the life line of `getargspec` deprecation, for which `git describe ` is again useful and again needs tags.

But if it is a pain, just forget about it I guess ;)

**Comment by krichter722** [comment]
Since you don't know where you got your tags from, you shouldn't rely on them at all. The git mirror and this fork don't contain tags originally and thus `git describe` works correctly (fails with `fatal: No names found`). If you want to add tags that's up to you, but it doesn't have anything to do with this PR.

**Comment by yarikoptic** [comment]
it definetly has nothing to do with this PR, but since issues are disabled -- as I have stated -- I hijacked it ;)

btw, for completeness if it happens to come useful to anyone -- you can greatly shrink the size of .git/objects after initial clone hg:: by repacking it:

```
(git)smaug:~/proj/misc/cpython-hggit[master]
$> du -scm .git
3072	.git
3072	total

$> git re
Counting objects: 748924, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (650195/650195), done.
Writing objects: 100% (748924/748924), done.
Total 748924 (delta 488160), reused 244404 (delta 0)
git re  843.63s user 15.04s system 530% cpu 2:41.96 total

$> du -scm .git
455	.git
455	total

$> git re --help
`git re' is aliased to `repack -a -d -f --window=100'
```

So overall, I don't really even care about this mirror, since now I have full featured direct clone into git from hg, which also comes with tags etc

**Comment by techtonik** [comment]
Hi Jack. Travis would be nice, but no chance.

**Comment by brettcannon** [comment]
Thanks for the PR, but https://github.com/python/cpython is a cpython mirror repository; pull requests are not accepted on this repo. Please submit bugs and patches at https://bugs.python.org.

**Pull request closed without merging**
