### PR TITLE
fix typo in fastsearch comments

### PR DESCRIPTION
**Pull request by esc**
too vs. two vs. to

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by aeros — COMMENTED** [review]
@esc Thanks for the contribution! If you have already signed the CLA over 24 hours ago, try manually updating the status on GitHub. This can be done by clicking on the "check yourself" link posted by the CLA bot @the-knights-who-say-ni. I had to do perform this process for my CLA status to be updated, so I figured it'd be worth mentioning. 

Otherwise, it looks like all of the tests are passing, and typo corrections are always welcome. Once the CLA is updated, a core developer will be able to review your PR and potentially have it merged into the repository.

**Comment by esc** [comment]
@aeros167 thanks for pointing towards that, but I haven't actually signed it yet, will do that now.

**Comment by esc** [comment]
O.K. I have just signed it, now I wait.

**Comment by aeros167** [comment]
@esc No problem. After the CLA has been verified, feel free to also check out the Python bug tracker for specific issues that could use assistance: https://bugs.python.org/

I'd recommend starting with the ones under the "easy issues" category. Also, another great resource for new contributors is the dev guide: https://devguide.python.org/

**Comment by esc** [comment]
Alright, CLA is signed, what next?

**Comment by aeros167** [comment]
> Alright, CLA is signed, what next?

Next, we just have to wait for a core python developer to check out the PR. Usually it takes no longer than a week or so depending on how busy they are. They have to provide the final "stamp of approval" in order for it to be auto-merged into the CPython repository.

**Review by mangrisano — APPROVED** [review]
LGTM.

**Comment by esc** [comment]
@mangrisano great! What do I need to do next to get this merged!

**Comment by mangrisano** [comment]
You need to wait for a core-dev.

**Comment by aeros167** [comment]
@esc 

> great! What do I need to do next to get this merged!

As I had said a bit earlier: 

>Next, we just have to wait for a core python developer to check out the PR.

The changes can't be merged until a core dev approves them. On average, this usually takes around a week or two, but can take longer depending on how busy they are. For more information, see the [devguide](https://devguide.python.org/pullrequest/#reviewing). I'd recommend reading over the pull request page, but the "Review" section in particular is the most relevant to your question.

**Comment by matrixise** [comment]
Thank you for your contribution, your PR has been merged into master and will be backported to 3.8.

**Pull request merged**
