### PR TITLE
bpo-38478: Correctly handle keyword argument with same name as positional-only parameter

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue38478

### CODE REVIEW

**Comment by pablogsal** [comment]
CC: @tirkarthi

**Review by tirkarthi — APPROVED** [review]
LGTM. I too had the same solution in mind since it's simple . Thanks Pablo :)

**Comment by pablogsal** [comment]
Thanks @tirkarthi :)

**Comment by pablogsal** [comment]
The buildbot failure is unrelated: `test_start_tls_server_1`

**Pull request merged**
