### PR TITLE
[issue39165][bpo-39165][Lib/re] implement findalliter() and findfirst()

### PR DESCRIPTION
**Pull request by apalala**
* Implement `findfirst()` in terms of `first()` and `findalliter()`. 
* Reimplement `findall(...)` as `return list(findalliter(...))`

https://bugs.python.org/issue39165

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@apalala

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by tirkarthi** [comment]
The code change introduces new API that needs to be discussed. Please open an issue at https://bugs.python.org

**Comment by apalala** [comment]
Reported as bug in https://bugs.python.org/issue39165

**Comment by apalala** [comment]
Note that this PR is incomplete as it does not implement `Pattern.findalliter()` nor `Pattern.findfirst()`.

**Review by terryjreedy — CHANGES_REQUESTED** [review]
The PR serves to define the proposal, but there is not yet core developer agreement that the addition is a good idea.  I would not bother completing the patch until there is.  Also, most people will not review the code until the CLA is signed.

**Pull request closed without merging**
