### PR TITLE
gh-104773: PEP 594: Remove the nntplib module

### PR DESCRIPTION
**Pull request by vstinner**
* socket_helper.transient_internet() no longer imports nntplib to catch nntplib.NNTPTemporaryError.
* ssltests.py no longer runs test_nntplib.
* "make quicktest" no longer runs test_nntplib.
* WASM: remove nntplib from OMIT_NETWORKING_FILES.
* Remove mentions to nntplib in the email documentation.

* Issue: gh-104773

----
:books: Documentation preview :books:: https://cpython-previews--104894.org.readthedocs.build/

### CODE REVIEW

**Comment by vstinner** [comment]
cc @mcepl

**Comment by mcepl** [comment]
For those who might be interested in this module, let’s continue with the fun on https://git.sr.ht/~mcepl/nntplib (and on PyPI as https://pypi.org/project/nntplib/).

**Comment by Julien-Elie** [comment]
Thanks @mcepl for having created nntplib on PyPi and making it still alive :)
It is greatly appreciated as this module works pretty fine, has a great documentation, and implements the latest version of the NNTP standard (RFC 3977).  Too bad that its test suite had too many false alerts :(

And thanks @vstinner too for all your work on Python!

**Review by hugovk — APPROVED** [review]

**Comment by vstinner** [comment]
> Too bad that its test suite had too many false alerts :(

Running a CI on a live server is hard. Each time that the server is busy, being upgraded, or has some network issues, the test fails. Sadly, no one managed to modify test_nntplib to tolerate temporary server/network issues.

IMO it's better to maintain such project outside Python to **ease** contributions. These days, ``pip install nntplib`` is trivial. And it's possible to only have a requirement on ``Python >= 3.13`` using environment markers.

**Comment by vstinner** [comment]
> For those who might be interested in this module, let’s continue with the fun on https://git.sr.ht/~mcepl/nntplib (and on PyPI as https://pypi.org/project/nntplib/).

If you look carefully to my PR, you will see that I recommend this replacement in What's New in Python 3.13, where the removal is documented ;-)

**Comment by vstinner** [comment]
Using ``import nntplib|from nntplib`` regex, I found a single project on PyPI top 5,000 projects (2023-04-13) using nntplib: **zipfile36** project.

zipfile36 only uses ``nntplib`` in a copy of the Python ``test/support/__init__.py`` file:

```
zipfile36-0.1.3.tar.gz: zipfile36-0.1.3/test/support/__init__.py: import nntplib
```

https://pypi.org/project/zipfile36/ is a backport of the zipfile module **from Python 3.6** "which contains some improvements". Suggested usage:

```
if sys.version_info >= (3, 6):
    import zipfile
else:
    import zipfile36 as zipfile
```

I suppose that Python 3.13 users are not supposed to use a backport of the Python 3.6 zipfile module :-)

**Comment by mcepl** [comment]
> If you look carefully to my PR, you will see that I recommend this replacement in What's New in Python 3.13, where the removal is documented ;-)

Thanks!

**Comment by mcepl** [comment]
> Using `import nntplib|from nntplib` regex, I found a single project on PyPI top 5,000 projects (2023-04-13) using nntplib: **zipfile36** project.

I use it in my https://pypi.org/project/pygn/ (which certainly isn’t in any Top anything ;)).

**Comment by vstinner** [comment]
> I use it in my https://pypi.org/project/pygn/ (which certainly isn’t in any Top anything ;)).

Maybe add a requirement to your own PyPI nntplib module? :-) (with a env markers to only install it on Python 3.13 and newer).

**Comment by mcepl** [comment]
> Thanks @mcepl for having created nntplib on PyPi and making it still alive :) It is greatly appreciated as this module works pretty fine, has a great documentation, and implements the latest version of the NNTP standard (RFC 3977). Too bad that its test suite had too many false alerts :(

Any patches are hugely welcome! Especially if somebody helped with mocking out the servers. It doesn't make a sense to run the test suite against real servers.

**Comment by merwok** [comment]
How can the module be under the BSD license, as it was copied from the stdlib that’s under the Python license? (not the same thing as the PSF license)

**Comment by mcepl** [comment]
> How can the module be under the BSD license, as it was copied from the stdlib that’s under the Python license? (not the same thing as the PSF license)

You are right, I have to investigate this https://todo.sr.ht/~mcepl/pygn/9

**Comment by hugovk** [comment]
Via https://pypi.org/classifiers/ here's the PyPI packages with the "License :: OSI Approved :: Python License (CNRI Python License" Trove classifier:

* https://pypi.org/search/?q=&o=-created&c=License+%3A%3A+OSI+Approved+%3A%3A+Python+License+%28CNRI+Python+License%29

(There's also a PSF licence one, but I guess you need Python licence.)

**Comment by mcepl** [comment]
Any comments on https://git.sr.ht/~mcepl/nntplib/commit/4cb431e3e40d

**Pull request merged**
