### PR TITLE
bpo-14322: added test case for invalid update to hmac

### PR DESCRIPTION
**Pull request by CCLDArjun**
https://bugs.python.org/issue14322

### CODE REVIEW

**Review by nanjekyejoannah — COMMENTED** [review]
Did we have to create a new test class with just one test? 

Why do I think this test could live under `class TestVectorsTestCase`, there seem to be many cases exercising `update` or am I missing something?

**Comment by CCLDArjun** [comment]
@nanjekyejoannah 
I was going to add it to TestVectorsTestCase but I wasn't sure it belonged there. It seems those tests are to check the accuracy of the hash digests? 

There are indeed other tests testing the update function, but I'm adding a test to check if there is an Error raised for invalid inputs to the function (i.e. anything other than `bytes` object)

**Review by nanjekyejoannah — COMMENTED** [review]
I suggest you comment on bpo, to solicit ideas from others on a better place, I may also be eluded.

**Comment by hugovk** [comment]
I think a new test case is fine, `TestVectorsTestCase` is doing something else, and no-one replied on the issue.

Let's re-open, update and retest.

**Review by hugovk — APPROVED** [review]

**Comment by hugovk** [comment]
Thank you for the PR!

**Pull request merged**
