### PR TITLE
bpo-42892 Fix AttributeError in email.message.get_body()

### PR DESCRIPTION
**Pull request by xkobal**
https://bugs.python.org/issue42892

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@xkobal

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by desmondcheongzx — COMMENTED** [review]
Would it also make sense to raise a warning when handling the exception?

From the example you included to reproduce the error, it seems that the message contains multiple candidates for the body, just that the message was badly formatted. Might be useful to inform the user about this.

**Comment by iritkatriel** [comment]
https://bugs.python.org/issue42892 is closed. What is the status of this PR?

**Comment by encukou** [comment]
The issue was closed with a different PR.

If there is still a bug here, please open a new issue. We'll need a new reproducer in that case.

**Pull request closed without merging**
