### PR TITLE
[3.11] GH-109408: Move the C file whitespace check from patchcheck to pre-commit (GH-109890)

### PR DESCRIPTION
**Pull request by AA-Turner**
(cherry picked from commit f5edb56328b46f262b74a53343b8098a3934f761)

* Issue: gh-109408

### CODE REVIEW

**Comment by AA-Turner** [comment]
To be merged following #110641.

A

**Comment by AA-Turner** [comment]
Both this PR and #110641 are failing due to valid lint failures -- (in ``Tools/c-analyzer/cpython/_capi.py`` and ``Modules/_ctypes/darwin/dlfcn.h``). We could add exclusions for these files, or perhaps just not backport? Unsure how best to proceed.

A

**Comment by AlexWaygood** [comment]
> Both this PR and #110641 are failing due to valid lint failures -- (in `Tools/c-analyzer/cpython/_capi.py` and `Modules/_ctypes/darwin/dlfcn.h`). We could add exclusions for these files, or perhaps just not backport? Unsure how best to proceed.
> 
> A

Adding excludes (or fixing the failures) seems like a good idea to me. It's useful to keep CI stuff in sync for all the maintenance branches.

**Comment by AlexWaygood** [comment]
Thanks! Closing for now, though, since the PR to `main` was reverted

**Pull request closed without merging**
