### PR TITLE
gh-53203: Fix strptime() tests for %X on glibc < 2.29

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-53203

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
!buildbot AMD64 RHEL8 3.x

**Comment by serhiy-storchaka** [comment]
!buildbot AMD64 RHEL8

**Comment by zware** [comment]
CI failures are (probably) unrelated; see gh-125472.

**Comment by zware** [comment]
!buildbot AMD64 RHEL8 LTO

**Review by hugovk — APPROVED** [review]

**Pull request merged**
