### PR TITLE
bpo-45684: Add ``__class_getitem__`` method to ``singledispatchmethod``

### PR DESCRIPTION
**Pull request by AlexWaygood**
https://bugs.python.org/issue45684

### CODE REVIEW

**Comment by merwok** [comment]
Is there anything to add to the doc of singledispatch?

TBH I don’t fully understand what the bug is.  Is it that typeshed suggests you can type a callback parameter with `functools.singledispatch[int]` rather than `Callable` but it’s not correctly supported by CPython?

**Comment by AlexWaygood** [comment]
> Is there anything to add to the doc of singledispatch?

I don't think so -- when ``__class_getitem__`` has been added to other classes such as ``functools.partial`` or ``os.PathLike``, nothing was added to the documentation for either of those classes. Though I'm happy to add a note if you think it's warranted 🙂

> TBH I don’t fully understand what the bug is. Is it that typeshed suggests you can type a callback parameter with `functools.singledispatch[int]` rather than `Callable` but it’s not correctly supported by CPython?

Yes, essentially. It's probably quite improbable that anybody would ever need to use ``singledispatchmethod`` in a type annotation. But, if they do, they'll find themselves in an impossible situation if they're using mypy with the ``--strict`` setting.  If you're using ``--strict`` (as I always do), mypy will complain if you leave unparameterised *any* class that is marked as a generic in typeshed, as leaving such classes unparameterised gives mypy less information to work with when checking your code. But if you try to parameterise ``singledispatchmethod``, and you're not using ``from __future__ import annotations``, your code will fail at runtime.

[Minimal reproducible example](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-codes%2Cstrict) showing the error message mypy will give.

**Comment by merwok** [comment]
Thanks!  Can you add this info to the bug report for clarity?

**Comment by AlexWaygood** [comment]
> Thanks! Can you add this info to the bug report for clarity?

Yes, of course!

**Comment by AlexWaygood** [comment]
I'm closing this for now. I still find the inconsistency between typeshed and cpython annoying, but I don't think the use case I presented is strong enough, and there are ultimately more important things to worry about. A better solution to this kind of problem might be something like https://github.com/python/typing/issues/956.

**Pull request closed without merging**
