### PR TITLE
[2.7] bpo-5755: don't use compiler flag -Wstrict-prototypes (GH-7395)

### PR DESCRIPTION
**Pull request by jdemeyer**
https://bugs.python.org/issue5755

### CODE REVIEW

**Comment by methane** [comment]
While the title says "extensions", isn't this affects all CPython source?

Anyway, I don't think it's worth enough to backporting.
It only suppress some noise while compiling C++ extensions.  It's not so critical problem.
We lived with them for several (or dozen) years.

Python 2.7.16 will be released on late 2018 or early 2019.
But how many people use it?  Any major distributions will preinstall it?

**Comment by jdemeyer** [comment]
> While the title says "extensions", isn't this affects all CPython source?

Right, I fixed the title.

> Anyway, I don't think it's worth enough to backporting.
> It only suppress some noise while compiling C++ extensions. It's not so critical problem.
> We lived with them for several (or dozen) years.

The fact that a bug is not critical and has existed for a long time is a bad excuse to not fix it. It's still a bug.

**Comment by methane** [comment]
> The fact that a bug is not critical and has existed for a long time is a bad excuse to not fix it. It's still a bug.

I agree if there are enough resource (core developer's time and energy for review and discussion). 

In this pull request, there is downside, and I don't think it's worth enough to use time and energy for discussion about the downside.

If proposed fix is easy to review, low risk to degrade, and has no downside, I'm OK to merge it.

**Comment by jdemeyer** [comment]
I this case, I would argue that the downside (removing `-Wstrict-prototypes` when compiling CPython) is so small that it doesn't really matter. But of course, I'm not the one to judge that...

**Pull request closed without merging**
