### PR TITLE
bpo-40956: Fix sqlite3 AC code

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue40956

### CODE REVIEW

**Comment by corona10** [comment]
This PR is the fixed code that I missed through the code review.
https://github.com/python/cpython/pull/23341#pullrequestreview-555534665
cc @erlend-aasland

**Comment by corona10** [comment]
@serhiy-storchaka Can you please take a look?

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by erlend-aasland** [comment]
> This PR is the fixed code that I missed through the code review.
> [#23341 (review)](https://github.com/python/cpython/pull/23341#pullrequestreview-555534665)
> cc @erlend-aasland

Thanks, @corona10 & @serhiy-storchaka !

**Comment by corona10** [comment]
Thanks! @serhiy-storchaka @erlend-aasland

**Pull request merged**
