### PR TITLE
gh-109317: Replaced `mktemp` with `mkstemp`

### PR DESCRIPTION
**Pull request by nydelzaf**
* Issue: gh-109317

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Sorry, it does not make the code more safer, and introduces new bugs.

**Comment by fazledyn** [comment]
Thank you @serhiy-storchaka for sharing your insights.

Can you please elaborate how this introduces new bugs? We're triaging OSS projects in Python everyday and would like to learn about the possible downside of using `mkstemp`.

**Comment by fazledyn-or** [comment]
Thank you @serhiy-storchaka for sharing your insights.

Can you please elaborate how this introduces new bugs? We're triaging OSS projects in Python everyday and would like to learn about the possible downside of using `mkstemp`.

**Comment by serhiy-storchaka** [comment]
I explained on the issue. The bugs are leaks of file descriptors.

**Pull request closed without merging**
