### PR TITLE
bpo-45187: Collect test_socket tests using unittest.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Previously, test classes ISOTPTest, J1939Test, BasicUDPLITETest and
UDPLITETimeoutTest were not included in the list of tests and
were not run by regrtest.

https://bugs.python.org/issue45187

### CODE REVIEW

**Comment by ambv** [comment]
The refleaks are real.

**Comment by serhiy-storchaka** [comment]
Yes, re-ordering tests exposed some issues in tests. They should be fixed in bpo-45212.

**Comment by serhiy-storchaka** [comment]
Building on Windows is broken for unknown causes.

**Comment by ambv** [comment]
`threading_helper` doesn't exist in 3.9, this will need a bit of a different backport. I'll deal with that.

**Pull request merged**
