### PR TITLE
bpo-46126: Disable 'descriptions' when running tests internally.

### PR DESCRIPTION
**Pull request by jaraco**
https://bugs.python.org/issue46126

Automerge-Triggered-By: GH:jaraco

### CODE REVIEW

**Comment by jaraco** [comment]
Hey Victor. Github thinks you might be a good reviewer, so I've requested your review. Please take a look, or re-assign to someone else (Łukasz maybe), or suggest another avenue. Thanks.

**Review by Makmudik — APPROVED** [review]

**Review by Makmudik — APPROVED** [review]

**Review by vstinner — APPROVED** [review]
LGTM.

Displaying test method docstrings caused me many practical issues when analyzing buildbot results. For example, it's harder to apply a regular expression to convert a test output to a list of test method which have been executed. I need to do that to re-run the same test methods, usually to bisect a reference leak.

@pablogsal: do you want to also have a look into this regrtest output change?

**Review by pablogsal — APPROVED** [review]
LGTM 

Thanks for the PR @jaraco !

**Comment by jaraco** [comment]
Test failures are "no space left on device". Seems to be a buildbot issue and not related to the patch.

**Pull request merged**
