### PR TITLE
GH-94108: Specialize for int & operation

### PR DESCRIPTION
**Pull request by kumaraditya303**
Benchmark: 
```console
./python -m pyperf timeit -s "a, b= 100, 200" "a & b" 
```

Result:
| Benchmark | base    | patch                 |
|-----------|:-------:|:---------------------:|
| int &| 18.2 ns | 16.8 ns: 1.08x faster |

### CODE REVIEW

**Comment by markshannon** [comment]
Looking at the stats shows the `int & int` is the most common specialization failure.
The question is, is it worth its own instruction, or is it worth waiting for a more general mechanism?

**Comment by kumaraditya303** [comment]
> Is `int & int` common enough to justify the extra instruction?

I created this PR based on stats and 33% (largest failure) seemed significant to me but if you don't think this is worth it, I have no objection if you reject this :).

**Comment by markshannon** [comment]
I'm not rejecting this. I'm just not sure whether it is a good idea.
I think we should go with the more general mechanism long term, but that doesn't mean that we can't add this specialization until then.

I'm going to benchmark it first.

**Comment by brandtbucher** [comment]
> We have discussed having some sort of double-dispatching mechanism and cache, to allow fast dispatching of binary operators without an explosion of instructions, but I can't find the original discussion. Maybe @brandtbucher can find it?

Here you go: https://github.com/faster-cpython/ideas/discussions/162

**Comment by markshannon** [comment]
I'm inclined to reject this in favor of a table based approach: https://github.com/faster-cpython/ideas/discussions/162.

The table based approach won't give as much of a speedup per specialization, but will allow many more specializations for fewer new opcodes.

**Pull request closed without merging**
