### PR TITLE
GH-118289: Fix handling of non-directories in `posixpath.realpath()`

### PR DESCRIPTION
**Pull request by barneygale**
In strict mode, raise `NotADirectoryError` if we encounter a non-directory while we still have path parts left to process.

We use a `part_count` variable rather than `len(rest)` because the `rest` stack also contains markers for unresolved symlinks.

* Issue: gh-118289

### CODE REVIEW

**Comment by barneygale** [comment]
Follow-up to #118290, where I messed up a rebase and notified everyone (whoops!)

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. Thanks.

How does it work on Windows? Could you add generic tests for these cases?

**Comment by nineteendo** [comment]
Wouldn't this be easier to implement when `rest` can't include markers for unresolved symlinks? #119172

**Comment by barneygale** [comment]
Thanks for the review, Serhiy. Playing around with this in Windows, it seems that `nt._getfinalpathname()` resolves features like `.` and `..` segments, and extraneous slashes (such as trailing slashes) up-front, rather than progressively like POSIX does. Also, it can raise `FileNotFoundError` rather than `NotADirectoryError` when treating a file as a directory. So I think this fix is pretty POSIX-specific.

**Pull request merged**
