### PR TITLE
Don't crash if there exists an EGG-INFO directory on sys.path

### PR DESCRIPTION
**Pull request by asottile**
cross-port of https://gitlab.com/python-devs/importlib_metadata/merge_requests/72

### CODE REVIEW

**Review by warsaw — APPROVED** [review]
@asottile Now we just have to figure out why CI fails.

**Comment by warsaw** [comment]
Looks like a permission problem on Windows.

**Comment by asottile** [comment]
interesting, I guess we need to catch that too in importlib-metadata.  I'll iterate here and then backport that to importlib-metadata :man_facepalming:

**Review by warsaw — APPROVED** [review]

**Comment by asottile** [comment]
sweet windows passed, I'll go make the same PR to importlib-metadata :D

**Pull request merged**
