### PR TITLE
gh-114091: Reword error message for unawaitable types

### PR DESCRIPTION
**Pull request by swfarnsworth**
Currently, attempting to await something that cannot be awaited results in this error message:

```py
import asyncio

async def main():
    await 1

asyncio.run(main())

# TypeError: object int can't be used in 'await' expression
```

I recently encountered this for the first time when the unawaitable object was a method (which was not being called), and found the phrase "object method" unclear. This PR changes the error message so that the name of the class precedes the word "object" and appears in single quotes. A similar construction appears elsewhere in the code base.

```python
>>> 1[2]
TypeError: 'int' object is not subscriptable
 ```
 
Thank you to @JelleZijlstra and @godlygeek for their input to this PR (though they do not necessarily endorse it).

* Issue: gh-114091

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This will need a NEWS entry since it's a user-visible change. That means you'll also need to create an issue, then rename this PR with the issue number (e.g., `"gh-110491: Reword error message...`) and use that issue number in the NEWS entry (step 8 in https://devguide.python.org/#quick-reference).

As for the contents, I like the change. What do you think though of instead changing the text of "'int' object is not awaitable'? That is even shorter, seems just as clear, and matches other errors like the subscript one.

**Comment by swfarnsworth** [comment]
>  What do you think though of instead changing the text of "'int' object is not awaitable"?
I agree and will implement this change.

**Comment by gvanrossum** [comment]
This doesn't look like something that would require an issue (though it does need a news blurb). IIRC it's possible to have a news entry without an issue? (You can try using the PR number as issue number in the blurb form.)

**Comment by JelleZijlstra** [comment]
> IIRC it's possible to have a news entry without an issue? 

I don't think so.

**Review by kumaraditya303 — APPROVED** [review]

**Pull request merged**
