### PR TITLE
gh-89427: Provide the original prompt value for VIRTUAL_ENV_PROMPT

### PR DESCRIPTION
**Pull request by jimporter**
This improves the implementation in gh-106643.

Previously, venv passed `"(<prompt>) "` to the activation scripts, but we want to provide the original value so that users can inspect it in the `$VIRTUAL_ENV_PROMPT` env var.

Note: Lib/venv/scripts/common/Activate.ps1 surrounded the prompt value with parens a second time, so no change was necessary in that file.

---

Sorry for the noise; I didn't quite understand the flow of this code until I started comparing it more closely to the implementation in the `virtualenv` package.

I was careful to test this change in action (only using the Bash version of the activation script, since that's the shell I have), but I also checked the generated scripts and they all look correct to me. After calling `python -m venv foobar` (results are also as expected if I pass `--prompt=something`):

# activate
```
VIRTUAL_ENV_PROMPT="foobar"
export VIRTUAL_ENV_PROMPT

# ...

if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1:-}"
    PS1="(foobar) ${PS1:-}"
    export PS1
fi
```

# activate.csh
```
setenv VIRTUAL_ENV_PROMPT "foobar"


set _OLD_VIRTUAL_PROMPT="$prompt"

if (! "$?VIRTUAL_ENV_DISABLE_PROMPT") then
    set prompt = "(foobar) $prompt"
endif
```

# activate.fish
```
set -gx VIRTUAL_ENV_PROMPT "foobar"

# ...

if test -z "$VIRTUAL_ENV_DISABLE_PROMPT"
    # ...
    function fish_prompt
        # ...
        # Output the venv prompt; color taken from the blue of the Python logo.
        printf "(%s%s%s) " (set_color 4B8BBE) "foobar" (set_color normal)
        # ...
    end

    set -gx _OLD_FISH_PROMPT_OVERRIDE "$VIRTUAL_ENV"
end
```

* Issue: gh-89427

### CODE REVIEW

**Comment by jimporter** [comment]
@vsajip Is there anything else I should do with this patch before it merges? This change will keep venv's behavior in-sync with virtualenv (see https://github.com/pypa/virtualenv/pull/2606).

**Comment by vsajip** [comment]
Sorry, not had time to review this. Hope to get to it soon.

**Comment by jimporter** [comment]
> Sorry, not had time to review this. Hope to get to it soon.

No problem! Just wanted to make sure you weren't waiting on me for something.

**Comment by jimporter** [comment]
@vsajip I rebased this and fixed the merge conflicts, which had the nice benefit of actually making the diff smaller.

**Comment by jimporter** [comment]
@vsajip Just checking again to see if you have bandwidth to review. I rebased again so it should merge cleanly.

**Review by vsajip — APPROVED** [review]

**Pull request merged**
