### PR TITLE
bpo-32701: Fix typo in quopri documentation.

### PR DESCRIPTION
**Pull request by JulienPalard**
https://bugs.python.org/issue32701

### CODE REVIEW

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Looks good, thanks! Since you're a core dev now, please merge when you're ready 😄

**Comment by Mariatta** [comment]
You can apply the `skip news` and `needs backport to 3.6` labels.

**Review by orsenthil — APPROVED** [review]
Looks good to me.

I found the module docstring succinct.  That could be adopted if you feel it is better.

```
 The 'quotetabs' flag indicates whether embedded tabs and spaces should be quoted.
```

**Comment by Mariatta** [comment]
@JulienPalard If it's ok with you, I'd like to use this PR to test out if miss-islington correctly adds the `Co-authored-by:` footer in the backport, so I'll merge this myself.

**Pull request merged**
