### PR TITLE
Fixed the message "float modulo by zero"

### PR DESCRIPTION
**Pull request by R1senDev**

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks for the patch! Would you mind signing the CLA?

**Comment by R1senDev** [comment]
> Thanks for the patch! Would you mind signing the CLA?

The mail with which I created the commit is different from the one linked to my account. As a result, I am not allowed to sign the CLA.

**Comment by hauntsaninja** [comment]
Hmm, can you reauthor the commit and force push to this PR?

**Comment by R1senDev** [comment]
> Hmm, can you reauthor the commit and force push to this PR?

Everything worked out, thanks for the hint!

**Comment by hauntsaninja** [comment]
Thank you!

**Pull request merged**
