### PR TITLE
bpo-44676: Fix reference leaks in union_reduce

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue44676

Automerge-Triggered-By: GH:pablogsal

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]
This is a neat fix :). Didn't know about the ``N`` format string.

**Comment by Fidget-Spinner** [comment]
Woops I just realized we didn't backport GH-27244. So we don't need to backport this. Thanks the quick fix Pablo!

**Comment by pablogsal** [comment]
I am backporting GH-27244 with this fix in https://github.com/python/cpython/pull/27333

**Review by corona10 — APPROVED** [review]
`````

0:00:00 load avg: 3.08 Run tests sequentially
0:00:00 load avg: 3.08 [1/1] test_types
beginning 6 repetitions
123456
......

== Tests result: SUCCESS ==

1 test OK.

Total duration: 1.1 sec
Tests result: SUCCESS
`````

I also checked that this PR fix the leak issue :)

**Comment by pablogsal** [comment]
Thanks for the review @corona10 and @Fidget-Spinner !

**Pull request merged**
