### PR TITLE
gh-92986: Make level of ImportFrom not optional on ASDL

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Review by isidentical — APPROVED** [review]
LGTM

**Comment by pablogsal** [comment]
This needs a news entry at the very least and also an entry in what's new as this is technically backwards incompatible no? Users not passing this in will be broken by the change if I am not mistaken

**Comment by hauntsaninja** [comment]
Yes, it is backwards incompatible, and looks like we have a test for this: https://github.com/python/cpython/blob/e8e737bcf6d22927caebc30c5d57ac4634063219/Lib/test/test_ast.py#L1112

Maybe we should just fix ast.unparse instead?

**Comment by pablogsal** [comment]
> Maybe we should close this and change ast.unparse instead?

That would be my recommendation

**Comment by hauntsaninja** [comment]
Okay, opened a PR for ast.unparse at https://github.com/python/cpython/pull/92992

**Pull request closed without merging**
