### PR TITLE
bpo-26897: Clarify Popen stdin, stdout, stderr file object docs

### PR DESCRIPTION
**Pull request by kumaraditya303**
https://bugs.python.org/issue26897

https://bugs.python.org/issue26897

### CODE REVIEW

**Comment by kumaraditya303** [comment]
@iritkatriel Can you review this ? Thanks

**Comment by iritkatriel** [comment]
> https://bugs.python.org/issue7262

This is linking to the wrong issue

**Comment by kumaraditya303** [comment]
> > https://bugs.python.org/issue7262
> 
> This is linking to the wrong issue

Fixed

**Comment by vadmium** [comment]
I guess this helps, although the original reporter in the bug was referring to the paragraph under the "Popen Constructor" heading, not the duplicate under "Frequently Used Arguments".

**Comment by kumaraditya303** [comment]
> I guess this helps, although the original reporter in the bug was referring to the paragraph under the "Popen Constructor" heading, not the duplicate under "Frequently Used Arguments".

@vadmium I have add it under "Popen Constructor"  now

**Review by JelleZijlstra — APPROVED** [review]

**Comment by kumaraditya303** [comment]
cc @Fidget-Spinner I think this is ready for merge.

**Comment by Fidget-Spinner** [comment]
@kumaraditya303 sorry but you've got the wrong person. You probably know more about subprocess than I do :). I'm useless here and cant verify the accuracy of any new docs.

**Comment by kumaraditya303** [comment]
> @kumaraditya303 sorry but you've got the wrong person. You probably know more about subprocess than I do :). I'm useless here and cant verify the accuracy of any new docs.

Oh, that's fine I thought that you would be interested in reviewing this doc PR.

**Comment by kumaraditya303** [comment]
@JelleZijlstra This is can be merged.

**Comment by JelleZijlstra** [comment]
Sure. @gvanrossum I'm planning to merge this change (a docs change to subprocess).

**Review by gvanrossum — APPROVED** [review]
I just wish the OP had not reflowed the paragraphs, to make the actual additions and changes stand out more in the diff.

**Comment by JelleZijlstra** [comment]
Agree, maybe we should change https://devguide.python.org/documenting/#use-of-whitespace to say not to reflow text unnecessarily.

**Pull request merged**
