### PR TITLE
bpo-36766: Typos in docs and code comments

### PR DESCRIPTION
**Pull request by GiantRobato**
Resolves [bpo-36766](https://bugs.python.org/issue36766)

https://bugs.python.org/issue36766

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by ericvsmith — APPROVED** [review]
These look okay to me.

**Review by tirkarthi — APPROVED** [review]
LGTM. IMO, code comments are also worth fixing. I will leave it to reviewer on the same. Thank you for the contribution :)

**Comment by matrixise** [comment]
@terryjreedy keep me informed when I can close the associated PRs and the issue.

Thank you so much.

**Comment by matrixise** [comment]
@terryjreedy I have merged the backport for 3.7.

**Comment by terryjreedy** [comment]
A PR is permanently closed when merged.  The issue can be closed when the last merge is done (easy to forget).  I did it since I wanted to leave a thank you message anyway.

**Pull request merged**
