### PR TITLE
gh-67565: Add tests for the remove redundant C-contiguity checks

### PR DESCRIPTION
**Pull request by furkanonder**
* Issue: gh-67565

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Comment by furkanonder** [comment]
@serhiy-storchaka The bot couldn't backport the changes because of the conflicts. I opened it manually. Can you merge these PRs?

**Comment by serhiy-storchaka** [comment]
Thank you Furkan. Were they all conflicts in Argument Clinic generated code?

**Comment by furkanonder** [comment]
> Thank you Furkan. Were they all conflicts in Argument Clinic generated code?

The only file that creates conflict is test `test_binascii.py`.  It seems that the [previous test case](https://github.com/python/cpython/pull/107863/files#diff-aeec59865b47d3778520e9e507ff5ee4c06d96434433669b1abc4d36d425bde5R468) and [my test case ](https://github.com/python/cpython/pull/110951/files#diff-aeec59865b47d3778520e9e507ff5ee4c06d96434433669b1abc4d36d425bde5R477)created a conflict.

```sh
--- a/Lib/test/test_binascii.py
+++ b/Lib/test/test_binascii.py
@@@ -428,6 -465,21 +428,24 @@@ class BinASCIITest(unittest.TestCase)
          self.assertEqual(binascii.b2a_base64(b, newline=False),
                           b'aGVsbG8=')
  
++<<<<<<< HEAD
++=======
+     @hypothesis.given(
+         binary=hypothesis.strategies.binary(),
+         newline=hypothesis.strategies.booleans(),
+     )
+     def test_base64_roundtrip(self, binary, newline):
+         converted = binascii.b2a_base64(self.type2test(binary), newline=newline)
+         restored = binascii.a2b_base64(self.type2test(converted))
+         self.assertConversion(binary, converted, restored, newline=newline)
+ 
+     def test_c_contiguity(self):
+         m = memoryview(bytearray(b'noncontig'))
+         noncontig_writable = m[::-2]
+         with self.assertRaises(BufferError):
+             binascii.b2a_hex(noncontig_writable)
+ 
++>>>>>>> 9376728ce4 (gh-67565: Add tests for C-contiguity checks (GH-110951))
  
  class ArrayBinASCIITest(BinASCIITest):
      def type2test(self, s):
```

**Pull request merged**
