### PR TITLE
bpo-40128: Fix IDLE autocomplete on macOS

### PR DESCRIPTION
**Pull request by thsubaku9**
This PR allows autocomplete to work as expected in the MacOS IDLE

https://bugs.python.org/issue40128

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@thsubaku9

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by nanjekyejoannah — COMMENTED** [review]
Thanks for the PR @thsubaku9, please follow the guidelines here: https://devguide.python.org/pullrequest/#submitting to link the issue to the PR correctly.

**Comment by terryjreedy** [comment]
Kaustubh: I normally do not look as substantive (behavior-changing) diffs until the CLA is recorded as signed.  Because completions have been such an issue on macOS, I peeked.  Because the fix, which I regard as a bug workaround, is so trivial, I finished the PR and will merge it when CE passes.  However, I hope you sign if you have not and look at more bugs.

If you do not know, merging a PR branch into main is not needed; you can made the PR directly from the branch.  When the branch is checked out, update-merge upstream/main into the branch with the same command used to update local main.

**Comment by thsubaku9** [comment]
> Kaustubh: I normally do not look as substantive (behavior-changing) diffs until the CLA is recorded as signed. Because completions have been such an issue on macOS, I peeked. Because the fix, which I regard as a bug workaround, is so trivial, I finished the PR and will merge it when CE passes. However, I hope you sign if you have not and look at more bugs.
> 
> If you do not know, merging a PR branch into main is not needed; you can made the PR directly from the branch. When the branch is checked out, update-merge upstream/main into the branch with the same command used to update local main.

Alright, I'll keep this in mind for my future submits. I've signed the CLA but I guess it takes some time to update on the site

**Comment by taleinat** [comment]
@terryjreedy 
Please note that this broke completions for me with Tcl/Tk 8.6.11 on Ubuntu 20.04.

**Comment by taleinat** [comment]
Apparently also with Tcl/Tk 8.6.10, which is the current default.

Also broken in my latest install of Python 3.9.7 (not built from source).

**Comment by terryjreedy** [comment]
See issue.

**Comment by dvd101x** [comment]
I noticed that selecting **Edit>Show Completions** works as expected on Python 3.10.2 and macOS 12.1

IDLE edit menu

But trying the default keyboard shortcut **^S** only highlights the edit menu but doesn't work.

I understand that it's supposed to be **^space** because that's how it works on windows and it also works in macOS after disabling the default behavior for **^space** but this doesn't highlight the edit menu.

So the mismatch is like this:

|Shortcut|Works|Conflict with macOS|Displayed|Highlights menu|
|---|---|---|---|---|
|**^S**|No|No|Yes|Yes|
|**^space**|Yes|Yes|No|No|

**Comment by taleinat** [comment]
Hey @dvd101x, that looks like a separate issue. Would you mind opening a new ticket on bugs.python.org with these details?

**Comment by dvd101x** [comment]
Yes of course. I saw this referenced on the original issue https://bugs.python.org/issue40128 but it also makes sense for to separate into a different issue. Thanks

**Pull request merged**
