### PR TITLE
switch descriptor howto to return value annotation

### PR DESCRIPTION
**Pull request by NotAFile**
This is a quick thing I noticed. This text was written before python type annotation were widely used, so I've modified to use those instead. That way, readers will immediately recognize it as a return type.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by NotAFile** [comment]
CLA review is now complete. I didn't read the "full business day" thing...

**Comment by pablogsal** [comment]
Hi @NotAFile and thank you for your contribution!

Do you mind modifying the Pull Request title to include the issue in the bug tracker that this PR is adressing? You can find more information here:

https://devguide.python.org/pullrequest/#submitting

If there is no issue created you can open a new one al add that number to the PR title.

**Comment by NotAFile** [comment]
@pablogsal I forgot to mention this in the PR title. I did not create a bpo issue for this, as "simple documentation/spelling fixes" are mentioned as not requiring an issue in the python (docs) contribution guide. I have also looked through similar edits in the PR history and seen the skip-issue tag on them.

**Review by taleinat — APPROVED** [review]
LGTM

**Pull request merged**
