### PR TITLE
bpo-38360: macOS: support alternate form of -isysroot flag

### PR DESCRIPTION
**Pull request by jmroot**
It is possible to use either '-isysroot /some/path' or
'-isysroot/some/path' (no space in between). Support both forms in
places where special handling of -isysroot is done, rather than just
the first form.

https://bugs.python.org/issue38360

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@jmroot

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by jmroot** [comment]
https://bugs.python.org/issue38360

**Comment by ned-deily** [comment]
(Ack)

**Comment by jmroot** [comment]
@ned-deily Ping. It would be nice to get this in to the 3.9.0 alphas.

**Review by ned-deily — APPROVED** [review]
Thanks, @jmroot, for the nice PR. Few are brave enough to enter those waters.  In the interests of time, I took the liberty of pushing a few changes into the PR, namely extending a couple of existing test cases to cover the singe-argument case and a minor style nit.

**Pull request merged**
