### PR TITLE
gh-107816: use lf as line ending for generated files

### PR DESCRIPTION
**Pull request by maxbachmann**
* Issue: gh-107816

### CODE REVIEW

**Review by serhiy-storchaka — DISMISSED** [review]
LGTM.

**Comment by gvanrossum** [comment]
I'm not a fan, see my comment in the issue.

**Comment by erlend-aasland** [comment]
Marking as do-not-merge; see discussion on issue.

**Comment by encukou** [comment]
It's intentional, see the issue.
But thank you for bringing it up, anyway!

**Pull request closed without merging**
