### PR TITLE
gh-89474: Improve Semaphore/BoundedSemaphore.release() for multiple thread waiting

### LINKED ISSUE #89474: Threading Semaphore and BoundedSemaphore release method implementation improvement
BPO | [45311](https://bugs.python.org/issue45311)
--- | :---
Nosy | @rhettinger, @pitrou, @serhiy-storchaka, @Fidget-Spinner, @akulakov

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-28.13:32:03.133>
labels = ['type-feature', 'library', '3.11']
title = 'Threading Semaphore and BoundedSemaphore release method implementation improvement'
updated_at = <Date 2021-10-21.08:42:59.621>
user = 'https://bugs.python.org/besi7dollma'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-21.08:42:59.621>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-09-28.13:32:03.133>
creator = 'besi7dollma'
dependencies = []
files = []
hgrepos = []
issue_num = 45311
keywords = []
message_count = 4.0
messages = ['402779', '404461', '404570', '404571']
nosy_count = 6.0
nosy_names = ['rhettinger', 'pitrou', 'serhiy.storchaka', 'kj', 'andrei.avk', 'besi7dollma']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45311'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by corona10**
closes: gh-89474

### CODE REVIEW

**Comment by corona10** [comment]
CI failure is due to following logs

`````

Generated files not up to date.
Perhaps you forgot to run make regen-all or build.bat --regen. ;)
configure files must be regenerated with a specific version of autoconf.
M  configure

diff --git a/configure b/configure
index b57c6f3..e956de9 100755
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by GNU Autoconf 2.69 for python 3.11.
+# Generated by GNU Autoconf 2.69 for python 3.12.
 #
 # Report bugs to <https://bugs.python.org/>.
 #
@@ -580,8 +580,8 @@ MAKEFLAGS=
 # Identity of this package.
 PACKAGE_NAME='python'
 PACKAGE_TARNAME='python'
-PACKAGE_VERSION='3.11'
-PACKAGE_STRING='python 3.11'
+PACKAGE_VERSION='3.12'
+PACKAGE_STRING='python 3.12'
 PACKAGE_BUGREPORT='https://bugs.python.org/'
 PACKAGE_URL=''
`````

**Review by serhiy-storchaka — COMMENTED** [review]
The test of the NEWS entry is not clear. What is the user-visible effect of this change?

**Comment by corona10** [comment]
> The test of the NEWS entry is not clear. What is the user-visible effect of this change?

https://github.com/python/cpython/blob/e466faa9df9a1bd377d9725de5484471bc4af8d0/Lib/threading.py#L372-L381

I think that there might be no user-visible effect except slight performance improvement, I will remove the NEWS.d

**Comment by corona10** [comment]
@serhiy-storchaka Rebased! PTAL :)

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
