### PR TITLE
gh-115480: Type / constant propagation for float binary uops

### PR DESCRIPTION
**Pull request by lazorchakp**
WIP

* Issue: gh-115480

### CODE REVIEW

**Comment by lazorchakp** [comment]
@Fidget-Spinner - opening this as a draft because I still have a few questions and it's waiting on some code from #115507.

- Currently, the main changes are essentially untested. None of the tests actually hit the `if (is_const(left) && is_const(right))` case. I get the feeling that this is expected for now, but it's entirely possible that I've just written bad tests.
- how much do we care about runtime performance of the tier 2 optimizer? Should I prefer
safety or speed? For example: PyFloat_AsDouble vs PyFloat_AS_DOUBLE
  - related: I was wishing for something like `_PyFloat_Add`, but ended up performing each calculation manually; this feels unsafe

**Comment by lazorchakp** [comment]
Also, I'll be on vacation until Tuesday and may be slow to respond. Please feel free to use / modify this code however you see fit if you're waiting on it

**Comment by Fidget-Spinner** [comment]
Nice work! This is pretty close, I will just push some changes since you're on holiday. Some points for possible consideration are that the tests should test for the float guard being eliminated as well.

**Review by Fidget-Spinner — APPROVED** [review]

**Comment by lazorchakp** [comment]
Thanks for finalizing and merging this 🎉

**Pull request merged**
