### PR TITLE
GH-116313: get WASI builds to run under wasmtime 18 w/ WASI 0.2/preview2 primitives

### PR DESCRIPTION
**Pull request by brettcannon**
* Issue: gh-116313

### CODE REVIEW

**Comment by brettcannon** [comment]
!buildbot wasi

**Comment by brettcannon** [comment]
I think the WASI failures will be fixed by https://github.com/python/buildmaster-config/pull/469 (we were forcibly using the old wasmtime CLI).

**Comment by zware** [comment]
!buildbot wasi

**Comment by brettcannon** [comment]
!buildbot wasi

**Comment by brettcannon** [comment]
I'm going to see if @kushaldas can update his buildbot before I merge this.

**Comment by kushaldas** [comment]
!buildbot wasi

**Review by kushaldas — APPROVED** [review]
All good here.

**Pull request merged**
