### PR TITLE
bpo-38018: increase code coverage for multiprocessing.shared_memory

### PR DESCRIPTION
**Pull request by vinay0410**
https://bugs.python.org/issue38018

### CODE REVIEW

**Review by brandtbucher — APPROVED** [review]

**Review by applio — COMMENTED** [review]
The first two checks look like good additions.
The use of mock to control the name of the shared memory segments does not look right to me -- have you verified that this test passes?

**Comment by vinay0410** [comment]
@applio , I have verified that the test passes. Also, I have verified that it covers [these](https://github.com/python/cpython/blob/9d607061c9c888913ae2c18543775cf360d55f27/Lib/multiprocessing/shared_memory.py#L94-L95) lines.
I wanted to add a test case which verifies the fact that nothing breaks, if `_make_filename` generates name of already existing segment.
I only could ensure that using mock.

**Review by applio — COMMENTED** [review]
The test involving mock appears use two distinct names for the two `SharedMemory(create=True, size=1)` invocations.  Crudely adding a `print()` to show `shm1.name` and `shm2.name` seems to confirm this.  Hence the two tests that pass are against `names[0]` and later `names[1]`.

Perhaps I misunderstood but I thought the intent was to verify that `_make_filename` creating duplicate names does not trigger a problem in and of itself.

**Comment by vinay0410** [comment]
@applio, The intent of the test is to verify if a problem is caused when `_make_filename` returns as **existing** name. So, the first call `shm1 = shared_memory.SharedMemory(create=True, size=1)` will create a shared memory with name `test01_fn`, since such a name(shared memory) doesn't exists yet.

Then I reset the side effect function of the mock object by `mock_make_filename.side_effect = names`

So, _make_filename will now again return `test01_fn` on first call. And, `test01_fn` is now a name of existing shared memory segment, which was created by the first call.
This will result in a `FileExistsError` [here](https://github.com/python/cpython/blob/9d607061c9c888913ae2c18543775cf360d55f27/Lib/multiprocessing/shared_memory.py#L94-L95)

And then the loop will continue, calling `_make_filename` again, which will then return `test02_fn`, and since no shared memory with such name exists, it will be created.

So, therefore it verifies existing segment names returned by `_make_filename` will be skipped, and it will be called again.

**Comment by applio** [comment]
Ahhh, thank you for the clarification.  Got it.

**Comment by pablogsal** [comment]
This PR introduced a regression in FreeBSD buildbots:

https://buildbot.python.org/all/#/builders/168/builds/1417

**Pull request merged**
