### PR TITLE
gh-104426: PGO build now uses test_asyncio for the profiling

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-104426

### CODE REVIEW

**Comment by mdboom** [comment]
I'm going to run this branch on the Faster CPython team's standard machine, just to confirm the results @corona10 already reported in #104426.

**Comment by corona10** [comment]
> I'm going to run this branch on the Faster CPython team's standard machine, just to confirm the results @corona10 already reported in https://github.com/python/cpython/issues/104426.

Thanks, Cross-checking is always great.

**Review by itamaro — APPROVED** [review]
looks good, thank you for adding this to the PGO suite!

**Comment by mdboom** [comment]
[Here's the results on our hardware](https://github.com/faster-cpython/benchmarking-public/tree/main/results/bm-20230513-3.12.0a7%2B-343bdd1).  It's 1% slower overall, but that's within the 2.25% noise we usually see.  [The plot](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230513-3.12.0a7%2B-343bdd1/bm-20230513-linux-x86_64-corona10-gh_104426-3.12.0a7%2B-343bdd1-vs-base.png) is probably the easiest way to look at the result.

**Comment by corona10** [comment]
@mdboom 
cc @carljm @gvanrossum @itamaro 

Thanks for the share, 
I also agree that -1 to +1% would be a noise level range.
So we can conclude that adding test_asyncio does not downgrade overall performance.
(What we want to check)

One good thing that we can notice from the cross-checking is that we can observe consistent performance improvement for asycnio benchmark group.

So if there is no major objection by next week, I will try to merge this PR.

**Comment by gvanrossum** [comment]
Why is the conclusion not that we needn’t do this?

**Comment by corona10** [comment]
> Why is the conclusion not that we needn’t do this?

Oh, when I heard that it was helpful for Instagram workload, 
I thought that it would be helpful to them and for people who are using asyncio heavily on their workload from the practical view.

**Comment by carljm** [comment]
To be clear, IG today uses profiles from the production workload instead of the test suite for PGO, so adding this here isn't something we're asking for. Back when we did PGO from test suite, this exact same change was a 5% improvement in prod, so based on that experience I would _expect_ this to help others with async heavy workloads who use the default PGO profiling setup. But it's all pretty mysterious, so who knows :)

**Comment by gpshead** [comment]
I wouldn't add this unless it shows up highly meaningful in our generalized performance benchmarks. It doesn't look like it does.

PGO builds are really painful if you make them wait for long running tests with instrumentation to complete which is why we settled on a simpler default PGO training suite.  We used to run most of the entire test suite which wasn't adding meaningful value vs what we run today.  See https://github.com/python/cpython/issues/80225 for that change.

As Carl notes, we expect people who have serious reasons to care will do their own task specific measurement and find their own training workloads.

https://github.com/faster-cpython/ideas/issues/547 and its linked to 99 also sort of cover this topic.

**Comment by corona10** [comment]
> I wouldn't add this unless it shows up highly meaningful in our generalized performance benchmarks. It doesn't look like it does.

I agree with the general view about adding PGO profiling task and I agree when caring about PGO profiling.
However asyncio is commonly used in Python web frameworks today, its proportion in pyperformance is relatively small, which necessitates adopting an exceptional perspective despite it being a general workload

I believe it is challenging to determine the contribution of test_asyncio to general-purpose performance from the beginning because the asyncio workload accounts for a very small portion in pyperformance. However, I think we should focus on observing how test_asyncio improves the asyncio workload without downgrading the general workload. 
This means we need to focus on the enhancement in asyncio-specific performance[1-3%+] without negatively impacting the overall performance.

WDYT?

**Comment by corona10** [comment]
> As Carl notes, we expect people who have serious reasons to care will do their own task specific measurement and find their own training workloads.

Well, high workload is quite relative, for some companies, they need to use a relatively small amount of hardware than big tech companies and I don't think that those companies don't have the resources to tune Python source code for their own workload.

**Pull request closed without merging**
