### PR TITLE
bpo-39127: Make _Py_HashPointer's argument be const

### PR DESCRIPTION
**Pull request by petdance**
`_Py_HashPointer` in Python/pyhash.c takes a pointer argument that can be made `const`.  This will let compiler and static analyzers know that the pointer's target is not modified.  You can also change calls to `_Py_HashPointer` that are down-casting pointers.

For example, in `meth_hash` in Objects/methodobject.c, this call can have the `void *` changed to `const void *`.

    y = _Py_HashPointer((void*)(a->m_ml->ml_meth));

https://bugs.python.org/issue39127

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@petdance

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by petdance** [comment]
I have indeed signed the CLA, but it was just earlier this evening.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by petdance** [comment]
@serhiy-storchaka If I find more instances of changes like this, should I submit each one individually, or put them all together in a single PR?

**Comment by petdance** [comment]
It looks like my CLA has gone through.  I have my asterisk in bpo.  Should I do something to retrigger the checks?

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Baljak, @damani42

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by petdance** [comment]
I'm sorry, I synced up my branch with master and pushed it, which seems to have churned up a bunch of activity here.

**Comment by terryjreedy** [comment]
I verified that bpo has user `petdance` with `petdance` as the github name and with CLA marked signed.  I don't know why the bot keeps adding back the unsigned label.

Properly merging the master into this (with `git merge origin/master` after updating local and origin/master and creating a pr branch) on my machine removed all but 1 of the spurious comments.

The latter was for a duplicate blurb for another issue, which I removed.  I don't think that this needs a news item, but however merges can decide.

**Comment by terryjreedy** [comment]
@serhiy-storchaka Do you want to merge as is or should Andy look for other places to add `const`?

**Comment by petdance** [comment]
>  Do you want to merge as is or should Andy look for other places to add const?

There are plenty of other places to add `const`.  I suggest that they make the most sense on a case-by-case basis, and this should be merged as-is.  I have another branch of `const`able candidates that I can start working on if this one works out OK.

**Comment by serhiy-storchaka** [comment]
Sorry for the delay. I approved the PR, but I was going to look whether previous additions of `const` was documented in a NEWS file or elsewhere. I was not sure.

They did not. So this PR does not need a NEWS entry.

As for other places to add `const`, I want to look on them. I think there should not be much places where `const` can be added without breaking backward compatibility.

I am merging this PR now because it was open enough time and I do not want to lost it again. Thank you for your contribution @petdance.

**Comment by petdance** [comment]
I'm glad to help. i'll keep looking for other `const`able functions.  I've done lots of `const`ing in the Perl core over the years.

**Pull request merged**
