### PR TITLE
typo fix : identify referent

### PR DESCRIPTION
**Pull request by wudenggang**
typo fix : identify referent

### CODE REVIEW

**Comment by furkanonder** [comment]
You can open a issue at https://bugs.python.org/ so that issue-number test case succeeds.

**Comment by tirkarthi** [comment]
Issue and news are not necessary. I have added skip-issue and skip-news labels.

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Review by pitrou — APPROVED** [review]
+1

**Pull request merged**
