### PR TITLE
gh-111138: Test the public PyList C API

### PR DESCRIPTION
**Pull request by vstinner**
Add test_capi.test_list tests.

* Issue: gh-111138

### CODE REVIEW

**Comment by vstinner** [comment]
@serhiy-storchaka: Would you mind to review this change?

**Comment by serhiy-storchaka** [comment]
See also #111562.

**Comment by vstinner** [comment]
I rebased my branch on main to fix a merge conflict.

**Comment by vstinner** [comment]
I merged https://github.com/python/cpython/pull/111562 instead.

**Pull request closed without merging**
