### PR TITLE
[Feature] Add mean centering to statistics library

### PR DESCRIPTION
**Pull request by knowmoe**
Sorry, I don't have a GH issue number.

A quick one-over the docs should make sense of things :wink:

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Hi, thanks for the PR! Adding a new function to the stdlib is a significant change, so I'd definitely advise opening an issue to discuss your proposed new feature. If you do so, and then change the title of your PR to reference your issue, the CI check will go green.

You might also consider starting a discussion thread at https://discuss.python.org/c/ideas/6

**Comment by nomothane** [comment]
Shall do, cheers @AlexWaygood!

**Comment by rhettinger** [comment]
I think this is beyond the scope for statistics, doesn't meet any known user needs, and should not be added.

**Comment by stevendaprano** [comment]
Thanks @nomothane.

I have never heard of mean-centering in this sense before. I know of it 
in the sense of modifying the data set by subtracting the mean from each 
data point to make the new mean be zero.

https://link.springer.com/article/10.3758/s13428-015-0624-x

https://www.theanalysisfactor.com/center-on-the-mean/

@nomothane do you have a link to more information about why somebody 
might use this? The provided documentation is unclear to me. It appears 
to be just multiplying the provided mean by (n-1)/n, where n = number of 
data points.

Without a solid justification, I agree with @rhettinger that this should 
not be added.

I think that we're going to reject this PR one way or another, but just 
to be sure (and for future reference) it would be good if you could 
provide a link to something explaining what this "mean centering" is 
used for.

**Comment by rhettinger** [comment]
No champions have emerged for this.  Am marking a closed.

**Pull request closed without merging**
