### PR TITLE
Use current name for macOS

### PR DESCRIPTION
**Pull request by paulschreiber**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in "Your Details" at b.p.o
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least a day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Review by ned-deily — APPROVED** [review]

**Comment by vstinner** [comment]
@paulschreiber: please sign the CLA.

**Comment by paulschreiber** [comment]
I'm paulschreiber on bugs.python.org. I signed the CLA.

**Comment by willingc** [comment]
@paulschreiber If you haven't put your GitHub user name in your bugs.python.org account, you will need to do that. If you have, then you should be good 👍

**Comment by brettcannon** [comment]
It also takes one US business day for the CLA to get updated by a human being, so hopefully this will get cleared up sometime today or tomorrow (and I checked that the GitHub username is filled in properly on bpo).

**Comment by methane** [comment]
@paulschreiber would you resolve conflict?

**Comment by methane** [comment]
thanks

**Comment by Mariatta** [comment]
I think this needs to be backported to 3.6, 3.5, and 2.7.
I'm now getting conflict while cherry-picking my commit from GH-283.
Is it ok if I cherrypick this into 3.6, 3.5, and 2.7? 
Thanks.

**Comment by ned-deily** [comment]
Go ahead, I think it's OK to cherry-pick to those releases, certainly for 3.6.

**Pull request merged**
