### PR TITLE
bpo-40275: Use new test.support helper submodules in tests

### PR DESCRIPTION
**Pull request by shihai1991**
Use test helpers in the following test cases:
* tests of eintrdata
* test_email
* test_mmap
* test_multibytecodec
* test_pdb
* test_urllib2_localnet
* test_warnings
* test_discovery
* test_result

https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by shihai1991** [comment]
cc @vstinner

**Comment by vstinner** [comment]
It seems like they are now conflicts. Can you please fix them?

**Comment by shihai1991** [comment]
> It seems like they are now conflicts. Can you please fix them?

done.

**Comment by shihai1991** [comment]
thanks, victor.

**Pull request merged**
