### PR TITLE
bpo-35202:  Remove more unused imports in idlelib

### PR DESCRIPTION
**Pull request by srinivasreddy**
https://bugs.python.org/issue35202

### CODE REVIEW

**Comment by srinivasreddy** [comment]
@terryjreedy  Requesting review since it is `idlelib`

**Review by terryjreedy — APPROVED** [review]

**Comment by pablogsal** [comment]
These buildbots had a connectivity problem, all these are false positives.

**Comment by terryjreedy** [comment]
@pablogsal @vstinner  To me, splattering a PR and participants' mailboxes with such (false) reports is pretty obnoxious. With our current CI, perhaps 99% of such reports that I would see, and this is not the first, will be false.

It seems to me that test failure reports should be sent to the person or persons responsible for the failing test.  If test_idle fails, I should be informed regardless of which PR triggered the test run.

It seems to me that connection failures should be reported to the buildbot owner.  Or the tests that depend on external connections should be skipped when the connection fails.

**Comment by pablogsal** [comment]
@terryjreedy One reason why we started reporting here is precisely to raise awareness when the buildbots are broken. Having a failing test persisting in the buildbots is a cascading effect and debugging and fixing those is much more difficult. For this reason there is the rule of reverting Pull Requests if there is not a fix in less than a couple of hours.

IMHO if there are false positives (normally due to race conditions and similar) the correct thing is fixing the test suite, not muting the reporting system. Right now there are very few people subscribed to the buildbot failure mailing list and reporting in the PR was proposed by multiple core developers as an improvement to help people understand when there is a buildbot failing.

We receive the real failures and the false positives in the mailing list and we need to triage all of them. This notification system helps notifying people of such failures, including the core dev that merged the PR and the author and since then we have much more general collaboration from everyone triaging and fixing tests, which I would say is a great improvement compared with the previous situation. @vstinner can provide more details on how taxing and hard was (and still is) watching the buildbots.

**Comment by terryjreedy** [comment]
Pablo, I already understood the *rationale*.  What I said above is that the *implementation* is so faulty from my viewpoint that it is pointless for me to pay any attention to these reports.

**Comment by pablogsal** [comment]
@terryjreedy Oh, I understand. The problem is that the buildbot report system extensions makes very difficult to improve the implementation. For example, there is no way other than parsing stdout to even know which test failed. It may be possible to use junit files or similar approaches but a lot more infrastructure would be needed. I can try to spend some time in the future to improve the situation, what parts of the implementation do you found faulty? 

IMHO the biggest problem is the present of false positives in general. I look **every** failure reported by any buildbot to triage them in case there are real positives. More than 60% of all emails I procees are false positives and as you can imagine I spend a lot of time doing this process. Sadly we cannot just stop looking at the reports because real failures will pass inadvertently and will cascade when there are multiple ones. Is a very hard problem to solve :(

**Comment by vstinner** [comment]
@terryjreedy Taking care of the CI is the duty of all core developers. Flaky tests are common. The purpose of annoying enough developers is that some day, one will show up and propose a fix :-)

**Comment by vstinner** [comment]
> https://buildbot.python.org/all/#builders/21/builds/1902

"fatal: unable to access 'https://github.com/python/cpython.git/': Failed connect to github.com:443; Connection refused"

This is bug in the CI which exists for years, but nobody found any solution yet. @terryjreedy: do you have an idea how to fix this exact bug?

**Pull request merged**
