### PR TITLE
bpo-39482: Add a fixer to handling abstract base classes

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue39482

### CODE REVIEW

**Comment by corona10** [comment]
@tirkarthi @benjimin @vstinner @rhettinger 

Dear core developers,
Please take a look and is it good for add what's new of 3.9?

**Comment by vstinner** [comment]
This fixer drops compatibility with Python 2, right? Is it a good idea? I don't know.

I stopped to use 2to3 a few years ago, since this tool adds many useless changes (to support early Python 3.x versions) and it drops support for Python 2.

**Comment by corona10** [comment]
> This fixer drops compatibility with Python 2, right? Is it a good idea? I don't know.

Yes, that's true and also a pain point. 
To use the abstract base class on Python 3.10+, this change is inevitable. 😢 

> I stopped to use 2to3 a few years ago, 

I've often seen a use case using lib2to3 where the external network is blocked for security reason(e.g Privacy-related or sensitive financial systems), or someone just simply trying to convert with lib2to3 and use it. 

In the latter case, they didn't expect much of the conversion quality of lib2to3. They just wanted to check how much the code is needed to change.

This change would be helpful for them.

**Comment by corona10** [comment]
bpo-40360 is now talking about deprecating lib2to3. So thie PR might be not needed. :)

**Pull request closed without merging**
