### PR TITLE
[doc] Fix typo

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Review by nanjekyejoannah — APPROVED** [review]

**Review by nanjekyejoannah — COMMENTED** [review]
Thanks for the fix, can you check why CI is failing?

**Comment by srinivasreddy** [comment]
I do not know why it is failing. Looks very similar to https://github.com/python/cpython/pull/26990. Maybe @iritkatriel  can shed some light on this?

**Comment by iritkatriel** [comment]
The CI failure is unrelated. Does this need backporting to 3.10 and 3.9?

**Comment by Fidget-Spinner** [comment]
I fixed the news item causing the CI to fail at https://github.com/python/cpython/pull/26994. Please take a look if y'all have the time.

**Comment by nanjekyejoannah** [comment]
> The CI failure is unrelated. Does this need backporting to 3.10 and 3.9?

I think so

**Comment by srinivasreddy** [comment]
@nanjekyejoannah  The build is passing now. I think we should merge this PR and backport it to 3.9 and 3.10

**Review by nanjekyejoannah — COMMENTED** [review]
Thanks, @srinivasreddy for the fix!

**Pull request merged**
