### PR TITLE
gh-89121: Keep the number of pending SQLite statements to a minimum

### LINKED ISSUE #89121: [sqlite3] only reset statements when needed
BPO | [44958](https://bugs.python.org/issue44958)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @pablogsal, @miss-islington, @erlend-aasland, @Fidget-Spinner
PRs | <li>python/cpython#27844</li><li>python/cpython#28490</li><li>python/cpython#28574</li><li>python/cpython#30379</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-19.20:05:09.432>
labels = ['extension-modules']
title = '[sqlite3] only reset statements when needed'
updated_at = <Date 2022-01-03.23:42:52.964>
user = 'https://github.com/erlend-aasland'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-03.23:42:52.964>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2021-08-19.20:05:09.432>
creator = 'erlendaasland'
dependencies = []
files = []
hgrepos = []
issue_num = 44958
keywords = ['patch']
message_count = 14.0
messages = ['399939', '399984', '401186', '402312', '402317', '402319', '402402', '402423', '402424', '402425', '402427', '402490', '402677', '402683']
nosy_count = 6.0
nosy_names = ['berker.peksag', 'serhiy.storchaka', 'pablogsal', 'miss-islington', 'erlendaasland', 'kj']
pr_nums = ['27844', '28490', '28574', '30379']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44958'
versions = []
```

</p></details>

### PR DESCRIPTION
**Pull request by erlend-aasland**
SQLite runs smooth when we keep the number of pending statements low.
Do  everything we can to reset statements when they are completely
stepped through (SQLITE_DONE), or when `sqlite3_step` returns an
error.

Also, on the cursor, Py_CLEAR the current statement object whenever possible.

Fixes #89121 

https://bugs.python.org/issue44958

### CODE REVIEW

**Comment by erlend-aasland** [comment]
There should be no performance regression this time, @Fidget-Spinner :)

**Comment by erlend-aasland** [comment]
@felixxm, would you mind running this through the Django test suite? (I haven't been able to set it up myself.)

**Comment by felixxm** [comment]
> @felixxm, would you mind running this through the Django test suite? (I haven't been able to set it up myself.)

Confirmed :heavy_check_mark: This doesn't break anything in Django tests.

**Comment by erlend-aasland** [comment]
BTW, @felixxm: I'm setting up Django tests on my machine; do I need to run the augmented test suite, or is the core test suite sufficient for all things SQLite?

**Comment by felixxm** [comment]
> BTW, @felixxm: I'm setting up Django tests on my machine; do I need to run the augmented test suite, or is the core test suite sufficient for all things SQLite?

The core test suite is sufficient, see ["Running the unit tests"](https://docs.djangoproject.com/en/stable/internals/contributing/writing-code/unit-tests/#quickstart).

**Comment by erlend-aasland** [comment]
> The core test suite is sufficient, see "Running the unit tests" [...]

Thanks. Yes, that's the recipe I followed :)

**Review by MaxwellDupre — APPROVED** [review]
All sqlite tests passed. Looks ok.

**Comment by erlend-aasland** [comment]
> All sqlite tests passed. Looks ok.

Thanks for you interest in improving CPython, by reviewing PRs! Could you also review that all statement "exit paths" are covered? This is the important part of the PR.

A statement should be reset if:

- it is replaced by another statement in the cursor (for example: `cur.execute("select 1"); cur.execute("select 2")`)
- it is removed from a cursor because the cursor is closed
- it is removed from a cursor because the cursor is deallocated
- it is completely stepped through (`sqlite3_step` returned `SQLITE_DONE`)
- stepping through the statement returned an error (`sqlite3_step` returned something else than `SQLITE_ROW` and `SQLITE_DONE`)
- a Python API call returned an error while processing the statement (typically `PyErr_Occurred()` is true during statement execution)

Did I forget an exit path?

Note; statement execution includes all the C interfaces to the `execute*` methods, and also all the C interfaces to the `fetch*` (and iter) methods.

**Comment by erlend-aasland** [comment]
Follow-up on my own post (notes to self); checking again for the umpteenth time that a statement is reset _when it is not used anymore_.

- [x] iternext, reset when statement is done (SQLITE_DONE)
- [x] iternext, reset when statement failed (SQLITE_ERROR-ish)
- [ ] reset when cursor is closed
- [ ] reset when cursor is dealloc'ed
- [ ] reset when cursor is free'd
- [ ] reset when LRU cache is cleared
- [ ] reset when statement is dealloc'ed
- [ ] reset when replaced in cursor
- [ ] cursor execute, reset when done
- [ ] cursor execute, reset upon error

**Comment by erlend-aasland** [comment]
cc. @coleifer, can you please test this and see if it fixes #94028? I can verify that your repro pass with this PR applied onto main.

**Comment by erlend-aasland** [comment]
@felixxm, do you mind if I call on you once more to verify this PR on the Django side?

**Comment by erlend-aasland** [comment]
@serhiy-storchaka, would you mind reviewing this PR? I is a proposed fix for the 3.11 release blocker #94028.

**Comment by erlend-aasland** [comment]
FTR, it is the `pysqlite_cursor_iternext()` changes that fix #94028. We could split those out in a separate PR just for the release blocker. cc. @pablogsal

**Comment by felixxm** [comment]
> @felixxm, do you mind if I call on you once more to verify this PR on the Django side?

:heavy_check_mark: Django checked, everything works.

**Comment by erlend-aasland** [comment]
I've sync'ed this PR with main after #94042 was merged. This PR is now pretty small and easy to comprehend. The buildbots are ok; Django is ok. I plan to merge it in a day or two.

We do not backport this PR.

**Pull request merged**
