### PR TITLE
bpo-44283: Add jump table for match-cases of None, int, and str constants, as well as or-patterns of these.

### PR DESCRIPTION
**Pull request by sweeneyde**
https://bugs.python.org/issue44283

### CODE REVIEW

**Review by MaxwellDupre — APPROVED** [review]
Looks good on my machine, unfortunately cant check on windoz.

**Review by MaxwellDupre — APPROVED** [review]
good

**Review by brandtbucher — CHANGES_REQUESTED** [review]
This was a cool experiment, but I think it's too big of a change right now (especially considering PEP 669 was just implemented, which doesn't support multi-way branches). Plus, most of the bytecode compiler and interpreter have been refactored since this change was implemented.

I suggest we close this. Thoughts, @sweeneyde? We could always refer to it if we decide this is worth doing in the future.

**Comment by sweeneyde** [comment]
Sounds good to me. It is a little fishy to only work on literals anyway.

**Pull request closed without merging**
