### PR TITLE
gh-74468: Fix name attribute of extracted object

### PR DESCRIPTION
**Pull request by xondrejk**
Attribute name of the extracted file object should hold filename of
itself rather than then of the archive it is contained in.

* Issue: gh-74468

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by xondrejk** [comment]
Out of multiple options to tackle this, I've opted to not add another argument to `_FileInFile` retrieving the value for `tarinfo.name` on call and instead pass complete `TarInfo` instance and get the data from that. It seems to be OK with respect to the immediate state of code in the repo. I hope it's not too far off and move in the wrong direction.

**Review by auvipy — CHANGES_REQUESTED** [review]
please add tests & release notes to ensure these changes won't create any regression

**Review by iritkatriel — CHANGES_REQUESTED** [review]
See @auvipy’s comment at https://github.com/python/cpython/pull/1483#pullrequestreview-612859401

**Comment by erlend-aasland** [comment]
No response since Irit commented; marked as pending close.

**Comment by arhadthedev** [comment]
The OP had no PR/issue/review activity for last three years. I'll create an alternative fix to successfully close the issue despite an unsigned CLA.

**Comment by erlend-aasland** [comment]
Superseded by #102424

**Pull request closed without merging**
