### PR TITLE
bpo-38942: Fix possible assertion failures in csv.Dialect()

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue38942

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Do you mind to write a test?

Just create a class with a property which raises an exception and pass its instance to csv.Dialect(). Test for different attribute names and for AttributeError and non-AttributeError exceptions.

**Comment by iritkatriel** [comment]
This is labelled awaiting merge, but from the discussion it looks like it should be labelled awaiting changes.

**Review by iritkatriel — CHANGES_REQUESTED** [review]
See discussion above.

**Comment by iritkatriel** [comment]
Actually this was already done in bio-44630.

**Pull request closed without merging**
