### PR TITLE
bpo-44806: Fix issue with typing.Protocol __init__ method generation

### PR DESCRIPTION
**Pull request by uriyyo**
https://bugs.python.org/issue44806

https://github.com/python/typing/issues/644

### CODE REVIEW

**Comment by uriyyo** [comment]
cc @Fidget-Spinner

**Comment by uriyyo** [comment]
@serhiy-storchaka Could you please review this PR? I have covered case that you mentioned at a issue tracker.

**Comment by Fidget-Spinner** [comment]
> I curios about why github did not add you as a reviewer? I can see that you at at CODEOWNERS for typing but every time it's add only Guido.

CODEOWNERS only works for people with write access, not for triagers :).

Also sorry, I won't be able to review this PR in time for 3.10rc1. So I'll let Serhiy decide. Both of your PRs look quite similar, just his searches `__mro__` and yours searches `__bases__`.

**Comment by ambv** [comment]
Closing in favor of GH-27545.

**Comment by serhiy-storchaka** [comment]
I am sorry, @uriyyo. I started working on a patch at a time with you, and when I finished, I saw your PR, but since my PR covered more cases and contained more tests, I kept it for comparison and discussion. Then I had a problem with connection (resolved only few hours ago), so I did not have opportunity to discuss your PR.

In general, they are almost same. There are subtle differences in corner cases, but for now I cannot say what is more correct.

**Comment by uriyyo** [comment]
@serhiy-storchaka No worries, I am happy that this issue has been resolved🙂

**Pull request closed without merging**
