### PR TITLE
bpo-38202: PyObject_GetIter() should be checked for failure

### PR DESCRIPTION
**Pull request by ZackerySpytz**
An exception may occur during a PyObject_GetIter() call.

https://bugs.python.org/issue38202

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Could you add a test?

**Comment by ZackerySpytz** [comment]
@serhiy-storchaka The fatal error I reported on the BPO issue was due to a `MemoryError` in `PyObject_GetIter()`. I don't think an exception in this `PyObject_GetIter()` call could be triggered from the Python side.

**Comment by serhiy-storchaka** [comment]
It can be. For example:
```
$ ./python -c '{}.keys() & 1'
python: Objects/typeobject.c:3148: _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.
Aborted (core dumped)
```

**Review by corona10 — CHANGES_REQUESTED** [review]
Please add misc/news through the blurb.
And add unit tests based on @serhiy-storchaka suggested.
`intersection`, `or`, `xor`, `sub` operations should be added.

**Review by methane — APPROVED** [review]

**Comment by corona10** [comment]
@methane @serhiy-storchaka 
I'd like to add the unit test if this PR is merged without unit test.
Is it okay?

**Comment by pablogsal** [comment]
I have added a unit test. Without the current PR:

```
❯ ./python -m test test_dictviews
Run tests sequentially
0:00:00 load avg: 1.94 [1/1] test_dictviews
python: Objects/typeobject.c:3125: _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.
Fatal Python error: Aborted

Current thread 0x00007f0fa489c740 (most recent call first):
[1]    26485 abort (core dumped)  ./python -m test test_dictviews
```

now:

```
 ./python -m test test_dictviews
Run tests sequentially
0:00:00 load avg: 0.69 [1/1] test_dictviews

== Tests result: SUCCESS ==

1 test OK.

Total duration: 45 ms
Tests result: SUCCESS
```

**Comment by pablogsal** [comment]
Thanks @serhiy-storchaka !

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thanks @pablogsal!

**Comment by pablogsal** [comment]
The buildbot failure is very likely unrelated, I am investigating.

**Pull request merged**
