### PR TITLE
gh-108297: Remove test_crashers

### PR DESCRIPTION
**Pull request by vstinner**
The test was skipped in 2011 by
commit 89ba56d5fb1335ef808b87cd33cba95ea141c65d.

Scripts in Lib/test/crashers/ do not crash on a reliable way. They rely on undefined behaviors, like state of the stack memory, and so may or may not crash. It is not worth it to make sure that they crash in a continious integration, they should be run manually time to time instead.

* Issue: gh-108297

### CODE REVIEW

**Comment by vstinner** [comment]
I do not want to backport the change to stable branches, it's fine to keep test_crashers.py there, it is skipped since 2011 anyway.

**Comment by vstinner** [comment]
cc @serhiy-storchaka

**Review by sobolevn — COMMENTED** [review]
What about `crashes/` dir?

**Comment by vstinner** [comment]
Lib/test/crashes/ should stay.

**Comment by serhiy-storchaka** [comment]
`test_crashers` was added in 2011 and disabled 3 days and 2 minutes later. It was not used since.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by vstinner** [comment]
> test_crashers was added in 2011 and disabled 3 days and 2 minutes later. It was not used since.

LOL. Really? Oh wow... that's the shortest test lifetime in the Python test suite :-)

**Pull request merged**
