### PR TITLE
gh-117482: Fix Builtin Types Slot Wrappers When Embedded

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
While gh-121602 solved most of the problem, it did not resolve the case where the runtime gets re-initialized.  In that case, we end up in the same situation as before, where the inherited "tp" slots are set, which makes `add_operators()` do the wrong thing.  We fix that by resetting the static type to the preserved values during finalization.  We also make sure the type substructs are preserved.

(Given that this fix is for a more unlikely case, I'm inclined to not backport this to 3.12.)

* Issue: gh-117482

### CODE REVIEW

**Comment by AraHaan** [comment]
I feel like while we are at it, properly implementing a full cleanup of the runtime state as mentioned in the ``_PyRuntime_Finalize()`` function's comments and doing a full reinitialize of it's variables inside of ``_PyRuntime_Initialize()``. I think doing that would help fix this issue permanently.

**Comment by ericsnowcurrently** [comment]
Yep.  It's on my TODO list. 😄

**Comment by freakboy3742** [comment]
!buildbot iOS

**Comment by ericsnowcurrently** [comment]
I'm going to go with gh-122865.  We can circle back to this later.

**Pull request closed without merging**
