### PR TITLE
gh-124153: Remove `_PyType_GetModuleByDef2` private function

### PR DESCRIPTION
**Pull request by neonene**
This function was introduced in #117578, which will no longer be used superseded by #124261.

cc @encukou

* Issue: gh-124153

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
You must update Modules/_decimal/_decimal.c: see the warnings.

**Comment by vstinner** [comment]
I suggest to mark this PR as a draft and wait until https://github.com/python/cpython/pull/124261 is merged.

**Comment by neonene** [comment]
Is it better for a sub function to walk the MRO?

**Comment by neonene** [comment]
Migrated to #124261.

**Pull request closed without merging**
