### PR TITLE
[3.10] bpo-43882 - Mention urllib.parse changes in Whats new section.

### PR DESCRIPTION
**Pull request by orsenthil**
https://bugs.python.org/issue43882

### CODE REVIEW

**Comment by gpshead** [comment]
I applied some formatting fixes to the rst.  It'd be good to pull and update and do a manual docs build to make sure it formats okay.

**Comment by orsenthil** [comment]
> I applied some formatting fixes to the rst. It'd be good to pull and update and do a manual docs build to make sure it formats okay.

I had copied the last merge from 3.7, and 3.6 for these to be consistent.

**Comment by orsenthil** [comment]
I will try building, and if I get any errors will update it. Not sure why the github diff is showing red.

**Comment by orsenthil** [comment]
@gpshead - Thank you. :) This renders well and hyperlinks to RFC and modules are good.

image

**Comment by orsenthil** [comment]
The text was reviewed in https://github.com/python/cpython/pull/26268 these PR's port the text (with some format changes) to other active branches. Merging this.

**Pull request merged**
