### PR TITLE
gh-102542 Remove unused bytes object and bytes slicing

### PR DESCRIPTION
**Pull request by JosephSBoyle**
Some small changes that were agreed to on the issue.

* Issue: gh-102542

### CODE REVIEW

**Review by warsaw — APPROVED** [review]
Looks great @JosephSBoyle thanks!

**Comment by warsaw** [comment]
I see there was a problem with doc builds.  @CAM-Gerlach maybe knows what's going on?  I'll leave this unmerged for the moment, but will set auto-merge for when it's fixed (but also, as this PR doesn't touch the docs, I also won't block on it too long).

**Comment by hauntsaninja** [comment]
Github has been having some weird failures all day. I've seen this one before and then another one where pushing commits to remotes doesn't reflect in PRs.

**Comment by warsaw** [comment]
Looks like the RTD failure is resolved now.

**Pull request merged**
