### PR TITLE
Fix ast.rst demo code

### PR DESCRIPTION
**Pull request by clumsyme**
Missing `copy_location` in demo code.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@clumsyme

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by tirkarthi** [comment]
The change was done in https://github.com/python/cpython/pull/17172 cc: @pablogsal @isidentical

**Comment by clumsyme** [comment]
got it

**Comment by isidentical** [comment]
I don't get why you closed and re-opened this PR? Is that a mistake or you want this version to be reviewed?

**Comment by clumsyme** [comment]
> I don't get why you closed and re-opened this PR? Is that a mistake or you want this version to be reviewed?

Sorry I didn't read tirkarthi's comment clearly and mistakenly thought the correction was done in pr17172.

**Comment by isidentical** [comment]
Did you read the issue about why this 'copy_locations' removed in the first place?

**Comment by clumsyme** [comment]
> Did you read the issue about why this 'copy_locations' removed in the first place?

OK, I see. I'm closing this.

But there's two issues after removing `copy_locations`:

1. Syntax error in last line of code:

```py
class RewriteName(NodeTransformer):

    def visit_Name(self, node):
        return Subscript(
            value=Name(id='data', ctx=Load()),
            slice=Index(value=Constant(value=node.id)),
            ctx=node.ctx
        ), node)
```

2.  Inconsistent with the docstring in [`ast.py`](https://github.com/python/cpython/blob/master/Lib/ast.py#L446)

**Comment by pablogsal** [comment]
@clumsyme Thanks for reporting those. Opened https://github.com/python/cpython/pull/18946 to fix them!

**Pull request closed without merging**
