### PR TITLE
bpo-43888: Remove coverage builds from CI

### PR DESCRIPTION
**Pull request by ammaraskar**
We introduced code coverage a while ago as part of https://bugs.python.org/issue23721 and https://github.com/python/core-workflow/issues/2 but it looks like this feature isn't really utilized by many people based on searching for "codecov" on github and bpo. These builds take way longer due to the instrumentation and this is cutting into valuable CI time. The builds are now also failing on master with the new timeout mechanism.

Let's just get rid of the coverage builds and see if anyone complains :)

https://bugs.python.org/issue43888

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
Before this can be merged there are probably some changes required over on the devguide to go with this.

@ammaraskar are you up to do a PR for that? We should probably drop the devguide mentions before we actually drop things.

**Comment by ammaraskar** [comment]
Sounds good, let me check up on what changes need to be made in the devguide.

**Comment by vstinner** [comment]
I never used this feature.

**Comment by ammaraskar** [comment]
Brett, the only mention I found in the devguide about coverage that seemed relevant to codecov was in the committing checklist, I made a PR for that here: https://github.com/python/devguide/pull/685

The rest is a guide on how to determine coverage locally which should stay in the devguide.

**Comment by Mariatta** [comment]
DevGuide PR has been merged. Thanks.

**Comment by RodrigoDornelles** [comment]
I missed it the same day, but now I had time to mention it, I usually check the coverage status to analyze and study more about construct languages.

**Comment by hugovk** [comment]
This missed `Misc/requirements-test.txt`, please see https://github.com/python/cpython/pull/110240 to remove it.

**Pull request merged**
