### PR TITLE
gh-92391: Add __class_getitem__ to csv.DictReader and csv.DictWriter

### LINKED ISSUE #92391: `csv.DictReader` and `DictWriter` not subscriptable at runtime
**Feature or enhancement**

Add PEP 585 style `__class_getitem__` to `csv.DictReader` and `csv.DictWriter`.

**Pitch**

With PEP 585 most generic stdlib types are now subscriptable at runtime. Both [DictReader](https://github.com/python/typeshed/blob/46fc7768c4df6f713e81a0078e72b9805679c25f/stdlib/csv.pyi#L75) and [DictWriter](https://github.com/python/typeshed/blob/46fc7768c4df6f713e81a0078e72b9805679c25f/stdlib/csv.pyi#L107) are generic in typeshed but don't yet implement `__class_getitem__`.

```py
from csv import DictWriter
from typing import IO

def f(fp: IO[str]) -> DictWriter[str]:
    return DictWriter(fp, ["id", "name"])
```

**Previous discussion**
* #19423
* https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

### PR DESCRIPTION
**Pull request by cdce8p**
Closes #92391

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
This makes sense to me.

I'm not 100% confident that the stubs for these classes in typeshed are "stable" -- I'm slightly nervous that we'll continue to fiddle with the stubs for these classes in typeshed. More detailed thoughts here: https://github.com/python/typeshed/issues/7787#issuecomment-1119544366.

However, I _am_ fairly confident that these classes will continue to be generic in typeshed, even if we do make other changes to the stubs. And that's the only thing that's relevant to whether `__class_getitem__` should be added to the classes.

**Comment by AlexWaygood** [comment]
I believe we may have _just_ missed the 3.11 feature freeze, however. So I guess we'll have to wait for 3.12 :)

**Comment by AlexWaygood** [comment]
I see the Azure Pipelines failure is a docs failure relating to "What's New in 3.11", which you haven't changed in this PR 🙃

**Comment by Fidget-Spinner** [comment]
Yeah we missed 3.11 by around an hour. Bummer :(.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by cdce8p** [comment]
Merged `upstream/main` to see if that resolves the docs issue.

**Comment by JelleZijlstra** [comment]
First new feature for 3.12!

**Comment by cdce8p** [comment]
> First new feature for 3.12!

Nice! Also my first CPython PR 😄

**Comment by AlexWaygood** [comment]
> > First new feature for 3.12!
> 
> Nice! Also my first CPython PR 😄

Congrats! :D

**Pull request merged**
