### PR TITLE
bpo-42917: Made block stack for frame objects dynamically sizable

### PR DESCRIPTION
**Pull request by tomKPZ**
This removes the hardcoded block stack size of 20 since typical
functions have far less than 20 nested blocks.  When running an empty
program, 256 frame objects get created with an old average size of
420.281 bytes.  This change reduces the average size to less than
half: 197.000 bytes on x86_64.  The goal is not necessarily to reduce
memory usage, but to make it more likely for stack frames to stay in
L1 cache.

In addition, the maximum of 20 blocks is removed.  This should make it
easier to write code generators that produce deeply nested code.

https://bugs.python.org/issue42917

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@tomKPZ

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by markshannon** [comment]
It looks like this PR includes a fix for block handling for `ASYNC_COMPREHENSION_GENERATOR` that should be included even if we reject https://bugs.python.org/issue42917.

Could you put that fix in a separate PR? Thanks.

**Comment by markshannon** [comment]
@tomKPZ any progress on this?

**Comment by tomKPZ** [comment]
Sorry for the late response.  ASYNC_COMPREHENSION_GENERATOR PR uploaded: https://github.com/python/cpython/pull/24865

Are there any changes I need to make on this PR (besides rebasing)?  It would be nice to know if it will be merged or not.

**Comment by markshannon** [comment]
This is now obsolete. There is no block stack: https://github.com/python/cpython/pull/25729

**Pull request closed without merging**
