### PR TITLE
bpo-32339: Make csv.DictReader returning regular dict instead of OrderedDict.

### PR DESCRIPTION
**Pull request by shangdahao**
https://bugs.python.org/issue32339

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by rhettinger** [comment]
Normally, we would have a deprecation period before switching the return type.  Potentially, this patch could break existing code that relied on methods like move_to_end() which are present in OrderedDict() but not in dict().

That said, I think such code is either unlikely or rare, so it would be net less disruptive for users to just go forward with this patch.

Since this would be a break from our usual policies, you would need to get the support of other core-devs before this patch could be applied.

**Comment by gvanrossum** [comment]
Let's not do this -- see the python-dev thread. It's no big deal anyways.

**Comment by shangdahao** [comment]
Thanks rhettinger and gvanrossum, I am going to close this PR.

**Pull request closed without merging**
