### PR TITLE
gh-64019: Have attribute table in inspect docs link to module attributes instead of listing them

### PR DESCRIPTION
**Pull request by slateny**
See also https://docs.python.org/dev/library/importlib.html#importlib.machinery.ModuleSpec

* Issue: gh-64019

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
Looks good.

@ericsnowcurrently would you like to take a look since you reviewed the previous version of this PR?

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

However, before merging, I recommend you get the opinion of @warsaw and @brettcannon; they are currently working on removing some of these attributes.

**Review by AA-Turner — APPROVED** [review]
I think https://github.com/python/cpython/issues/65961 is the correct issue for the deprecations/removals.

A

**Comment by brettcannon** [comment]
I personally think the table shouldn't exist in the first place. The common attributes for objects is not `inspect`-specific, and so this is an odd place to document such things. It also leads to it being out-of-date when folks don't even know about it. So my preference it to instead remove the entire table.

Barring that, `__cached__`, `__package__`, and `__loader__` should not be documented as they are deprecated in Python 3.12.

**Comment by slateny** [comment]
I see, what about removing the table section on modules and adding a sentence above it linking to https://docs.python.org/dev/reference/import.html#import-related-module-attributes? It would preserve the info in this page if needed and avoid having two sources of information.

**Comment by brettcannon** [comment]
> see, what about removing the table section on modules and adding a sentence above it linking

Works for me!

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

FWIW, it might be more clear to move the new sentence (parenthetical reference) to below the table, but I'll leave that to your (or others') discretion.

**Comment by slateny** [comment]
I considered putting it at the bottom, but since the module was at the top of the table I didn't want to move it too far away. But it does look a bit awkward, especially if more sections if the table will be removed, so if others feel the same I have no problem with moving it down.

**Comment by smontanaro** [comment]
(I'm working my way through some PRs which have been approved and are labeled "awaiting merge", hence my seemingly bolt from the blue comment. Why? [Read here](https://discuss.python.org/t/prs-awaiting-merge/21313).)
 
This has been idle for awhile. It's been approved by @ericsnowcurrently and @JelleZijlstra. @brettcannon is there any reason not to merge?

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
> is there any reason not to merge?

Nope, just not at the top of my review queue. 😅

**Comment by brettcannon** [comment]
> I had trouble checking out the `3.11` backport branch.

Due to the backport problem I am going to close the 3.10 branch to make backporting easier. But I'm also not going to worry about backporting to 3.11 since this is a minor clean-up. If someone wants to create a PR for 3.11 I'm willing to review, but I have too much other PRs to review to do the backport myself.

**Comment by AlexWaygood** [comment]
> > I had trouble checking out the `3.11` backport branch.
> 
> Due to the backport problem I am going to close the 3.10 branch to make backporting easier. But I'm also not going to worry about backporting to 3.11 since this is a minor clean-up. If someone wants to create a PR for 3.11 I'm willing to review, but I have too much other PRs to review to do the backport myself.

Removing and re-adding the label fixed the problem!

**Pull request merged**
