### PR TITLE
(merge after 3.8.6 final) [3.8] bpo-41855: Fix duplicate results in FastPath.zip_children()

### PR DESCRIPTION
**Pull request by jaraco**
https://bugs.python.org/issue41855

### CODE REVIEW

**Comment by jaraco** [comment]
Sorry for the noise. I did not intentionally create all of those review requests. I simply used the `hub pull-request -c` command :(.

**Comment by jaraco** [comment]
Not sure why the PR was closed by Guido. I do want to get a review on this PR and plan to merge it ASAP once the branch is unfrozen.

**Comment by ned-deily** [comment]
I think Guido was suggesting you create a new clean PR from an uptodate 3.8 branch to avoid all the unnecessary notices etc.

**Comment by jaraco** [comment]
I can do that.

**Pull request closed without merging**
