### PR TITLE
Make "iterable" singular in chain.from_iterable doc

### PR DESCRIPTION
**Pull request by andresdelfino**

### CODE REVIEW

**Comment by pganssle** [comment]
In this case, I think "iterables" is intended to refer to the thing that the iterable *contains*, not the the object itself, in the same way that you might have:

```python
def capitalize_names(names: List[str]):
    ...
```

Where the list describes the *names*.

I don't know the degree to which type hints are being adopted in the standard library documentation, but I wonder if this might be a case where it would be useful to use them? Possibly:

```python
def from_iterable(iterables: Iterable[Iterable]) -> chain:
    ...
```

Would make things clearer (assuming that is the right syntax...).

**Comment by andresdelfino** [comment]
> In this case, I think "iterables" is intended to refer to the thing that the iterable _contains_, not the the object itself, in the same way that you might have:
> 
> ```python
> def capitalize_names(names: List[str]):
>     ...
> ```
> 
> Where the variable describes the names contained in the list.
> 
> I don't know the degree to which type hints are being adopted in the standard library documentation, but I wonder if this might be a case where it would be useful to use them? Possibly:
> 
> ```python
> def from_iterable(iterables: Iterable[Iterable]) -> chain:
>     ...
> ```
> 
> Would make things clearer (assuming that is the right syntax...).

Sorry the delay in replying :) While I see your point, IMHO it would be better for the Python pure implementation to match the signature of the actual function. Also, from_iterable(iterable**s**) seems weird.

Regarding type hints being used in the documentation, I don't believe that is happening except specific cases like dataclasses or singledispatch, where they are actually used by the implementation.

**Comment by pganssle** [comment]
> While I see your point, IMHO it would be better for the Python pure implementation to match the signature of the actual function.

I don't see a pure python implementation of `itertools` (maybe I'm missing it?), but the actual function takes its only argument by position only:

```python
>>> chain.from_iterable(iterable=[[1], [2], [3]])
----> 1 chain.from_iterable(iterable=[[1], [2], [3]])
TypeError: from_iterable() takes no keyword arguments
```

Though you are right the docstring seems to call its argument `iterable`:

```
In [1]: from itertools import chain

In [2]: chain.from_iterable?
Docstring:
chain.from_iterable(iterable) --> chain object

Alternate chain() constructor taking a single iterable argument
that evaluates lazily.
Type:      builtin_function_or_method
```

I think the docs and docstring probably should be harmonized. I'm slightly in favor of `iterables` because I prefer arguments to describe what they represent and not the type they represent, but it's a super minor thing so I defer to whoever makes the decision (@rhettinger I presume).

Even if we go with `iterable`, the docstring should probably be updated to reflect the fact that the argument is positional-only, so it should be:

```
chain.from_iterable(iterable, /) --> chain object
```

**Comment by rhettinger** [comment]
I prefer to leave this as is.

**Pull request closed without merging**
