### PR TITLE
bpo-35561: Fix valgrind warnings in selectmodule.c

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue35561

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
I don't think this needs a news entry.

**Review by corona10 — APPROVED** [review]
@ZackerySpytz 
Thanks for the patch.
Looks good to me.

**Comment by vstinner** [comment]
I dislike this approach: https://bugs.python.org/issue35561#msg359434

**Comment by ZackerySpytz** [comment]
Victor suggested to open a new PR to update `Misc/valgrind-python.supp`, so I have created GH-18060.

**Pull request closed without merging**
