### PR TITLE
bpo-39507: add HTTP status 418 "I'm a Teapot"

### PR DESCRIPTION
**Pull request by rrhodes**
### What?
Adding HTTP status 418 "I'm a Teapot" to HTTPStatus in http library.

### Why?
HTTP status code documented in RFC 2324: Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0).

https://bugs.python.org/issue39507

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@rrhodes

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by rrhodes** [comment]
Signed the CLA now. Following the given documentation and waiting at least one US business day for this to processs.

**Review by corona10 — CHANGES_REQUESTED** [review]
https://github.com/python/cpython/blob/master/Doc/library/http.rst

The document should be updated :)

**Comment by rrhodes** [comment]
Only outstanding action: waiting at least one business day for CLA records to update to include me.

**Comment by rrhodes** [comment]
@corona10, I think I’ve completed all outstanding tasks: CLA signed and all checks have passed. Anything further you require from me?

**Review by corona10 — CHANGES_REQUESTED** [review]
- This PR should be reviewed after core developers approved :)
- A unit test should be added also, see: https://github.com/python/cpython/blob/4d96b4635aeff1b8ad41d41422ce808ce0b971c8/Lib/test/test_httplib.py#L1442

**Comment by rrhodes** [comment]
How long typically before a core developer is available to review and approve?

**Comment by corona10** [comment]
@vadmium 
Martin, Can you please take a look at this issue and also for PR?

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @rrhodes.

Please add the `versionadded` directive in the module documentation and a What's New entry (like in #18294).

**Review by serhiy-storchaka — APPROVED** [review]
:+1:

**Comment by rrhodes** [comment]
Thank you for the feedback and approval, @serhiy-storchaka. Do you have permissions to merge?

**Pull request merged**
