### PR TITLE
[skip issue] Trivial correction for the docs on datamodel

### PR DESCRIPTION
**Pull request by bombs-kim**
I just added a comma, but without it, the sentence just looks wrong

### CODE REVIEW

**Comment by Mariatta** [comment]
Thanks for the PR. But I think the original sounded better.

**Comment by Mariatta** [comment]
Thanks again for the PR. But I don't think we'll be accepting this. The existing sentence reads fine.

**Comment by bombs-kim** [comment]
@serhiy-storchaka @Mariatta 
Thank you for checking it! I know it's not a change but I still think sth is wrong.. How about the latter part of the sentence? Is it wrong, too?

>    to a new value, *value*.

To me, the usages of commas looked inconsistent in the sentence, so I made this PR.

**Comment by bombs-kim** [comment]
@serhiy-storchaka Oh thank you but I think I already understood it. My point is it should be either

> instance, *instance* of the owner class  to a new value, *value*. (two commas)

or

> instance *instance* of the owner class  to a new value *value*. (no comma)

. Because the original version had command for the latter part only, it looked confusing to me.

**Pull request closed without merging**
