### PR TITLE
bpo-40670: Calling timeit.timeit with empty string uses 'pass' by default

### PR DESCRIPTION
**Pull request by DahlitzFlorian**
The changes proposed in this PR refer to the discussion over at https://bugs.python.org/issue40670.
The suggestion is to adopt the behaviour of the command-line usage for timeit and use `'pass'` if called with `''` (empty string).

@remilapeyre what do you think about it?

https://bugs.python.org/issue40670

### CODE REVIEW

**Comment by SimiCode** [comment]
@DahlitzFlorian Can you please add news? 
Reviewers are more likely to skip a PR if it does not pass all checks.

**Review by remilapeyre — CHANGES_REQUESTED** [review]
@DahlitzFlorian, I don't think it's a good idea, it will just mask the error and others inputs will make it fail in the same way.

Serhiy Storchaka and Terry Reedy seem to also think that the code should keep behaving that way.

Maybe the documentation could be improved thought?

**Comment by SimiCode** [comment]
When I looked into this; I realized that there are many edge cases that need to be covered for the method to be considered error free. 
As per now, First step should be improving the documentation as Terry suggested.
Later, If a comprehensive re-design of the method can be reviewed.

**Comment by DahlitzFlorian** [comment]
The PR was opened pretty early in the discussion. Based on the discussion‘s progress I think, we can close the PR.

**Pull request closed without merging**
