### PR TITLE
bpo-35821: Fix restructuredtext code formatting in logging.rst

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
https://bugs.python.org/issue35821

### CODE REVIEW

**Review by bateller — APPROVED** [review]

**Comment by Fidget-Spinner** [comment]
Merging this to unblock other things. Thanks @bateller for taking a look.

**Comment by vsajip** [comment]
> caused rstlint (and azure pipelines) to fail.
@Fidget-Spinner  Sorry, missed that. How come the Docs build on GH-29841 reported success? I didn't check the Azure build, because often seems to fail for no apparent reason and with no diagnostics :disappointed:

**Comment by Fidget-Spinner** [comment]
@vsajip no worries! Docs build doesn't seem to run rstlint. I suspect that's because rstlint previously generated many false positives, so we disabled that for normal docs builds. @JulienPalard probably knows more about this than I do.

**Comment by Fidget-Spinner** [comment]
Only on the Azure build.

**Comment by JulienPalard** [comment]
Adding a bit of context:

Previously `make suspicious` was throwing a lot of false positives and was slow, so I disabled it and now I'm trying to replace `make suspicious` by `make check` which is fast and should not give false positives (or at least, reported false positives should be considered a bug, not the norm).

I missed the fact that the azure pipeline was ~ignored and the .github/workflow/doc was not running `make check`. Victor fixed it yesterday by adding `make check` to the github workflow \o/

**Pull request merged**
