### PR TITLE
optimize all_name_chars

### PR DESCRIPTION
**Pull request by benjaminp**
Remove redundant PyUnicode_Check call. Use a static table for checking chars.

### CODE REVIEW

**Review by tiran — APPROVED** [review]
LGTM

**Comment by benjaminp** [comment]
For posterity, here's how I generated the table:
```
for i in range(128):
    if chr(i) in "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz":
        print "1,",
    else:
        print "0,",
    if i % 16 == 15:
        print
```

**Comment by tiran** [comment]
I take back my LGTM ... you seriously used Python 2 to generate the table? Shame on you! :)

**Comment by tiran** [comment]
```
for i in range(128):
    print('{:d}, '.format(chr(i) in "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"), end='')
    if i % 16 == 15:
        print()
```

**Comment by benjaminp** [comment]
It's just nostalgia.

**Comment by serhiy-storchaka** [comment]
LGTM too. I have found a bug in `all_name_chars()`, but this is different issue.

**Comment by serhiy-storchaka** [comment]
Only one nit: please update the comment before `all_name_chars()`.

**Comment by serhiy-storchaka** [comment]
You could use `!Py_ISALNUM(*s) && *s != '_'` and get rid of `ok_name_char`.

**Pull request merged**
