### PR TITLE
bpo-33768: IDLE: Clicking on code context line moves it to top of editor

### PR DESCRIPTION
**Pull request by csabella**
https://bugs.python.org/issue33768

### CODE REVIEW

**Comment by terryjreedy** [comment]
I expect to merge this tomorrow after I finish reviewing.

**Review by terryjreedy — APPROVED** [review]
I changed the yview arg to f'{n}.0'.

1. I don't like passing floats as indexes, because A) they are not.  They usually work because _tkinter calls str(float), but B) this is potentially fragile; for instance, float(3*.1) ==   0.30000000000000004.  We now C. have f-strings in addition to %-formatting as a way to create a string index.  Both are D. 50% faster than str(float(n)).  I prefer f-strings as the clearest way to make an index string.

2. I like yview(int) even less than yview(float).  A. Having yview(n+1) = yview(float(n)) is wretched.  This made the tests confusing.  B. the tk doc calls it obsolete.  It could disappear from tkinter, as has happened with other obsolete tk features.

Otherwise, this is great.  Thanks for the PR.

**Comment by csabella** [comment]
> I changed the yview arg to f'{n}.0'.
Thanks!  I had copied this from the `center` method in editor.py and didn't even think about it, but your explanation makes sense.

**Comment by terryjreedy** [comment]
IDLE has had multiple authors, without a tkinter style guide ;-).  I could see using the float trick when the alternative was % or .format, even though I did not like it, but then I realized that we have the new option since 3.6 that I like even better.  So I did the timing test.  While float alone is faster than f-string, _tkinter has to apply str, and the combination is slower., and I am fairly sure it still is even in C (where the lookup of 'str' is done at compile time).

There is also a matter of consistency.  If row and column are known constants, such as 1 and 5 in the test, writing `r.c` (`1.5`) instead of `'r.c'` (`'1.5'`), deferring string conversion to _tkinter, seems a bit silly to me, and I notice that you did not do that.  A float() call is only useful for variable line, fixed column 0.  The new f-strings always work when either line or column is a computed name rather than a literal or symbolic (`end`) constant.

**Pull request merged**
