### PR TITLE
Fix typos in documentation.  Patch by tirkarthi.

### PR DESCRIPTION
**Pull request by terryjreedy**

### CODE REVIEW

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Comment by terryjreedy** [comment]
Somehow my working file did not have the 'millesecond' => 'millisecond' correction someone did about a month ago, even though everything was supposed to be up to date.

**Comment by tirkarthi** [comment]
I think this was missed in https://github.com/python/cpython/pull/13116 though my report had it as an item for idle.rst : https://bugs.python.org/issue36766#msg341194

**Comment by terryjreedy** [comment]
You message specified idle.html rather than idle.rst, and there is what got edited.  I should have noticed.  help.html should not be directly edited since it is a generated file -- a trailing whitespace trimmed copy of the file generated from idle.rst by Sphinx.  So when I generated it the first time today, I noticed the reversion and added the change to idle.rst.  This clears up why.

**Pull request merged**
