### PR TITLE
no-issue: Fix typo TestContentTyopeHeader to TestContentTypeHeader

### PR DESCRIPTION
**Pull request by jenner9212**
The word "TestContentTyopeHeader " seems a typo. This PR corrects the typo to "TestContentTypeHeader".

### CODE REVIEW

**Comment by jenner9212** [comment]
@kumaraditya303 Hello, can you add skip issue and skip news label if you don't mind?

**Comment by jenner9212** [comment]
@cjw296 Hello, could you review and add skip issue, skip news label if you don't mind?

**Comment by cjw296** [comment]
@jenner9212 - please don't randomly tag people like you've done above.

**Review by corona10 — APPROVED** [review]
LGTM, Thank you for contribution :)

**Pull request merged**
