### PR TITLE
bpo-34749: Improved performance of binascii.a2b_base64().

### PR DESCRIPTION
**Pull request by sir-sigurd**
https://bugs.python.org/issue34749

### CODE REVIEW

**Comment by csabella** [comment]
@encukou, there are now merge conflicts between this and GH-4108 (bpo-31862).  Do you think the changes here would be compatible with the other changes being proposed for upcoming PEPs?  Thanks!

**Comment by encukou** [comment]
The conflicts look minor (though Git rightly thinks they're better left to humans). I don't know about all upcoming PEPs, but I'm not aware of conflicts.
Unfortunately I won't have time for review in the next few months :(

**Comment by csabella** [comment]
@encukou, thank you for the response.  This one may need to wait a little longer until a reviewer is available then.

**Review by encukou — APPROVED** [review]
I've rebased on top of the module state changes in master.
I can still see the speedup, can't find any new bugs, and I haven't been able to speed it up more :)

**Comment by sir-sigurd** [comment]
@encukou, thanks for rebasing it!

**Pull request merged**
