### PR TITLE
Fix bpo-30589: improve Process.exitcode with forkserver

### PR DESCRIPTION
**Pull request by pitrou**
When the child is killed, Process.exitcode should return -signum, not 255.

### CODE REVIEW

**Comment by pitrou** [comment]
@cf-natali

**Comment by pitrou** [comment]
@cf-natali, do you know if the SIGCHLD strategy used here is reliable?

**Comment by cf-natali** [comment]
Yes, the patch looks good (now that we correctly handle EINTR, which will
happen now that SIGCHLD has a handler).

Slight nit: in theory, the read-end of the self-pipe (sig_r) should also be
set non-blocking, because it's in theory possible to get spurious
notification in select, in which case the read would hang: but I'm not
aware of any reason this could happen on a pipe.


2017-06-08 18:52 GMT+01:00 Antoine Pitrou <notifications@github.com>:

**Comment by pitrou** [comment]
Thanks for the review @cf-natali. There are other places in forkserver where spurious notifications are not considered, so I'm gonna judge that the `sig_r` pipe doesn't warrant special care.

**Comment by pitrou** [comment]
I've determined that this PR suffers from a race condition (a well-known one, admittedly): SIGCHLD can arrive just before `epoll_wait` is called, in which case the latter doesn't return EINTR and our event loop just sits waiting for further events. Then some forkserver-based test randomly hangs (seen in some CI builds).

The solution seems to be to use `signal.set_wakeup_fd`.

**Pull request merged**
