### PR TITLE
bpo-33497: Add errors param to cgi.parse_multipart and make an encoding in FieldStorage use the given errors

### PR DESCRIPTION
**Pull request by hawkowl**
https://bugs.python.org/issue33497

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Review by zooba — APPROVED** [review]

**Comment by zooba** [comment]
@hawkowl The change looks good to me - can you click "Details" on that failed check and follow the instructions to add the NEWS entry? (It's very easy - thank Larry :) )

@ned-deily I think this is fine, but I'll leave it to you to merge/backport (feel free to remove the label)

**Comment by hawkowl** [comment]
(sorry I couldn't resist)

multipart

**Comment by hawkowl** [comment]
@zooba it'd be easier with towncrier ;) -- but, I don't think it needs a new news entry, from looking at the details?

**Comment by hawkowl** [comment]
(it doesn't need one as it's under a current 'what's new', I think?)

**Pull request merged**
