### PR TITLE
Remove duplicate address in CommonTestMixin_v4.test_leading_zeros().

### PR DESCRIPTION
**Pull request by felixxm**
The same as in https://github.com/python/cpython/blob/3ad101b3175c102e252161a1b8b928e694de8c94/Lib/test/test_ipaddress.py#L103

Automerge-Triggered-By: GH:pablogsal

### CODE REVIEW

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
@pablogsal I'm applying _skip issue_ to this; let me know if that's impropriate.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks for the PR @felixxm and thanks @erlend-aasland for the review!

**Comment by felixxm** [comment]
Thanks both :+1:

**Comment by pablogsal** [comment]
@Mariatta Seems that the `automerge` label is not working on this PR :(

**Pull request merged**
