### PR TITLE
Move pathlib implementation out of `__init__.py`

### PR DESCRIPTION
**Pull request by barneygale**
Use the `__init__.py` file only for imports that define the API, following the example of `asyncio`.

See https://discuss.python.org/t/make-pathlib-extensible/3428/172

### CODE REVIEW

**Comment by barneygale** [comment]
@eryksun you mentioned renaming `_abc.py` to `_pathlib_abc.py` on the forum. Do you mean something like this?

```
Lib/pathlib.py
Lib/_pathlib_abc.py
Lib/_pathlib_glob.py
Lib/_pathlib_local.py
```

... because that would speed up the import of `pathlib._glob` from the `glob` module I think.

**Comment by eryksun** [comment]
Great if that really helps with performance. My issue was more trivial. I like to have easily recognizable names on tabs in my IDE. "\_pathlib\_abc.py" is a name that I can recognize in an instant without having to hover or use the document viewer.

**Comment by barneygale** [comment]
Hm. If I thumb through the standard library, there are quite a few submodules with generic basenames: `asyncio.log`, `ctypes.util`, `email.errors`, `re._constants` etc. I don't really mind either way, but it seems more consistent with the rest of `Lib/` to consider the entire package path as the name. Can you configure your IDE to do that perhaps?

**Comment by eryksun** [comment]
No, not on tabs, and I wouldn't want qualified names on tabs. That's what the tree view of the documents viewer is for if I really need it. I know the standard library doesn't generally use easily recognizable module names in packages. That's why I qualified the asyncio example for what I personally prefer, and only for generic private names. Some names are easy for me to remember in context, such as "pool.py" in multiprocessing. It's just generic private names like "_errors.py" and "_constants.py" that I wish had better names, since they aren't meant to be used in the public API anyway. But really almost anything is better than staring at a bunch of tabs labeled "\_\_.init.\_\_.py" is mind numbing.

**Review by eryksun — APPROVED** [review]

**Comment by barneygale** [comment]
Well, the `__init__.py` problem is improved at least. I'm not sure about adding a `pathlib_` prefix to the other module names - I suspect other folks might find it overly repetitive and out of line with the rest of the stdlib. I hope you'll eventually forgive me if I merge this as-is. I'm open to renaming the modules in future if it becomes more obviously the correct thing to do.

**Comment by PeterJCLaw** [comment]
Great to see the work going into pathlib for the next version of Python :).

Apologies if this isn't the right place to bring this up and/or if this is already known/expected, but I wanted to highlight that moving the implementations of pathlib prevents pickles coming from Python 3.13 (specifically I'm testing at 3.13.0b2) being loaded on earlier versions of Python (the other way around works fine). I realise that this probably isn't something where backwards compatibility is expected and that moving pickles between versions maybe not desirable, though it is used in a few places -- notably [Jedi](https://github.com/davidhalter/jedi/) does so.
I've seen that pickle supports the notion of fixing imports for various standard library moves, so I'm not sure if this is something which might be a candidate for including in those fix lists? (I realise this would need to be a fix applied to older versions of Python rather than to 3.13)

For Jedi I've worked around this pretty easily by adding a custom [`Unpickler`](https://docs.python.org/3/library/pickle.html#pickle.Unpickler), which I'm guessing might be what's expected?

I'm not sure what's expected around moves like this, so if the default is "nothing" that's probably fine! It might be nice to call out the refactoring in the release notes though?

**Pull request merged**
