### PR TITLE
bpo-38119: fix shared memory's resource tracking

### PR DESCRIPTION
**Pull request by vinay0410**
- [ ] Update tests
- [ ] Update documentation (if necessary)

https://bugs.python.org/issue38119

### CODE REVIEW

**Review by MaxwellDupre — CHANGES_REQUESTED** [review]
I see there are auto tests which fail, including my own test:
./python Lib/test/test_multiprocessing_main_handling.py
Ran 39 tests in 11.392s
FAILED (failures=26)
cpython on  fix-issue-38119 [$?] via 🐍 v3.11.0a5+ took 11s
Can you check and fix?

**Review by iritkatriel — CHANGES_REQUESTED** [review]
This has merge conflicts now.

**Comment by ambv** [comment]
This is an impressive PR but I think the solution here is wrong. See https://github.com/python/cpython/issues/82300#issuecomment-1336166761.

**Comment by ambv** [comment]
We're going with a simpler solution per the comment on the issue.

**Pull request closed without merging**
