### PR TITLE
bpo-47190: Initial async tk loop stuff

### PR DESCRIPTION
**Pull request by smontanaro**
This is far from complete. I have never done any GUI or asyncio testing before. Combining the two is probably way above my pay grade. I did try to add some useful library documentation (including an example), which will hopefully help whoever also works on this understand what I was thinking.

Also, I imagine there is more than one way to skin this cat. I chose to add a method run from the `asyncio` side of things which keeps the Tk event queue updated. The reverse is probably also possible (force `asyncio` to use the Tk `mainloop`).

https://bugs.python.org/issue47190

### CODE REVIEW

**Comment by smontanaro** [comment]
I also don't expect this to be accepted in its current form. I'm just putting it out there as the basis for discussion.

**Comment by smontanaro** [comment]
I don't understand the Docs/Docs errors. This occurs several times:

> Error: [2] library/tkinter.async.rst:12: default role used

The docs built fine with no errors in my checkout.

**Comment by TeamSpen210** [comment]
It'd be better to figure out a way to run asyncio inside the tkinter event loop - that way if both are waiting for something, the whole process can go to sleep.

**Comment by smontanaro** [comment]
I make no claim that this way is the best (or only) way to get the desired result. I chose this approach, at least in part, because I had an `asyncio` example of using `pynput` listeners to monitor keyboard and mouse activity.

I'll see if I can flip the script.

**Comment by iritkatriel** [comment]
https://bugs.python.org/issue47190 is closed. What is the status of this PR?

**Comment by graingert** [comment]
> https://bugs.python.org/issue47190 is closed. What is the status of this PR?
It was closed as duplicate of
https://github.com/python/cpython/issues/71733

**Pull request closed without merging**
