### PR TITLE
bpo-42257: handle empty string in variable executable in platform.libc_ver()

### PR DESCRIPTION
**Pull request by kurochan**
https://bugs.python.org/issue42257

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@kurochan

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by kurochan** [comment]
Can anyone review this PR? 🤔

**Comment by malemburg** [comment]
The patch looks good. Could you please also add a NEWS entry ?

**Comment by malemburg** [comment]
The nntplib test fails, preventing a merge. This doesn't seem to be related to this PR, so I guess we'll have to wait and then rebase the PR after this is fixed in the master branch.

**Comment by malemburg** [comment]
@kurochan Could you please rebase the PR. The nntplib issue (https://github.com/python/cpython/pull/24037/) should be resolved now.

**Comment by malemburg** [comment]
Thanks for the patch @kurochan.

**Pull request merged**
