### PR TITLE
bpo-30659: Use ** for kwargs in namedtuple._replace() signature

### PR DESCRIPTION
**Pull request by benhoyt**
Note that this is purely a documentation tweak. bpo link is http://bugs.python.org/issue30659

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by benhoyt** [comment]
FYI, I didn't have the "GitHub Name" field set in bpo, so I just set that now. I've previously signed the CLA for my os.scandir() contributions.

**Comment by Mariatta** [comment]
Thanks @benhoyt :) CLA looks good, and I added bpo-30659 to the PR title.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks 🎉

**Comment by Mariatta** [comment]
@benhoyt Can you backport to the other versions.
You can use [cherry_picker.py](https://github.com/python/core-workflow/tree/master/cherry_picker)

The commit hash is `184bd82ba8106785ba22f0d2477dbd08bef821fb`

Thanks.

**Comment by benhoyt** [comment]
I can, but it might be a few days before I get to that (need to get a block of time and learn how to use cherry_picker.py etc). If you want to do that in the meantime, go ahead, otherwise I'll do it in the next couple of weeks.

**Comment by benhoyt** [comment]
Excellent, thank you!

**Pull request merged**
