### PR TITLE
gh-92603: add upstream fix to macOS installer

### PR DESCRIPTION
**Pull request by chrstphrchvz**
* Issue: gh-92603

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
I have not already attempted to build the macOS installer myself. Does the CI build the installer? I would think it does not.

**Comment by ned-deily** [comment]
Thanks, I'll take a look at this before the next releases.

**Comment by chrstphrchvz** [comment]
See also #108806

**Comment by ned-deily** [comment]
Thanks for the PR. To simplify merging, I have incorporated these changes into your subsequent PR gh-111041.

**Pull request closed without merging**
