### PR TITLE
gh-126780: Fix `ntpath.normpath()` for drive-relative paths

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-126780

### CODE REVIEW

**Comment by nineteendo** [comment]
cc @zooba, @barneygale

**Review by barneygale — APPROVED** [review]
The test cases LGTM but I haven't reviewed the C code. Thanks

**Review by ruidazeng — APPROVED** [review]

**Comment by zooba** [comment]
Not sure if we need to go back to 3.12, but letting the bot decide... guess not!

**Comment by nineteendo** [comment]
Thanks.

**Pull request merged**
