### PR TITLE
gh-101329: fix: decimal.to_eng_string gives wrong engineering notation in some cases

### PR DESCRIPTION
**Pull request by MichaDit**
* Issue: gh-101329

### CODE REVIEW

**Review by ericvsmith — COMMENTED** [review]
You'll need to add tests that fail before this change, and succeed after this change.

**Comment by MichaDit** [comment]
> You'll need to add tests that fail before this change, and succeed after this change.

Sure, but before doing more work I want to know if the change would be accepted.

**Comment by ericvsmith** [comment]
> Sure, but before doing more work I want to know if the change would be accepted.

I was hoping to answer that very question by looking at examples that are failing!

**Comment by ericvsmith** [comment]
Given the failing tests, I'd say that the current behavior is deliberate.

**Pull request closed without merging**
