### PR TITLE
bpo-44231: Remove _PyTuple_FromArray from the public C API

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue44231

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I'm not sure if this calls for a NEWS item.

**Comment by pablogsal** [comment]
> I'm not sure if this calls for a NEWS item. Gut feeling says yes :) @pablogsal

It won't hurt, but notice this function is not exposed in the public headers (is in `Include/internal`) and the removal is not very useful for readers of the changelog as they won't be able to use it.

**Review by pablogsal — APPROVED** [review]
LGTM

I would like @vstinner to review this as well, but if he has no time, please ping me in some days so I can land this :)

**Comment by erlend-aasland** [comment]
> LGTM
> 
> I would like @vstinner to review this as well, but if he has no time, please ping me in some days so I can land this :)

Great, thanks Pablo! :)

**Comment by erlend-aasland** [comment]
> > I'm not sure if this calls for a NEWS item. Gut feeling says yes :) @pablogsal
> 
> 
> 
> It won't hurt, but notice this function is not exposed in the public headers (is in `Include/internal`) and the removal is not very useful for readers of the changelog as they won't be able to use it.

There was no NEWS entry when it was introduced. That does not imply that we shouldn't include one now, but I believe it's best to keep this strictly internal; a NEWS item may be more confusing than useful in this case.

**Comment by vstinner** [comment]
Merged. I changed the commit message. It's still part of the internal C API, it's just that the symbol is no longer exported.

**Comment by vstinner** [comment]
> There was no NEWS entry when it was introduced. That does not imply that we shouldn't include one now, but I believe it's best to keep this strictly internal; a NEWS item may be more confusing than useful in this case.

You must not document changes in the **internal** C API. People must not use it outside CPython. If they use it, they are on their own.

**Comment by erlend-aasland** [comment]
> You must not document changes in the **internal** C API. People must not use it outside CPython. If they use it, they are on their own.

Aye! Thanks for reviewing!

**Pull request merged**
