### PR TITLE
bpo-34014: Added support of contextvars for BaseEventLoop.run_in_executor

### PR DESCRIPTION
**Pull request by hellysmile**
An updated version of https://github.com/python/cpython/pull/8035

according to latest discussion on https://bugs.python.org/issue34014

If proposed solution looks good I'll start updating related docs changes

https://bugs.python.org/issue34014

### CODE REVIEW

**Review by 1st1 — CHANGES_REQUESTED** [review]
[Blocking this to prevent accidental merge.]

As per the bpo discussion: our goal is to provide a new API for working with threadpools and processpools.  If we end up having their design ready in a few months we might want to revisit this PR.  If not, we'll likely merge this PR as is.

**Comment by hellysmile** [comment]
@1st1 thanks for the update!

Is there any PEP/API spec/ideas available?

**Comment by hellysmile** [comment]
master was just merged

**Comment by hellysmile** [comment]
I have made the requested changes; please review again.

**Comment by 1st1** [comment]
I'm still not sure about this -- we can't make contextvars work with process pools. :( Need to design a new API for 3.9.  You can champion that; first we need to start a discussion.  We'll need to assess the current situation, what are the alternatives (curio, trio, twisted), and what's the best possible api we can design for asyncio given its constraints.

**Comment by hellysmile** [comment]
@1st1 seems using something rather then `ThreadPoolExecutor` will be prohibited in `3.9` 

https://github.com/python/cpython/blob/master/Lib/asyncio/base_events.py#L811

what about to restrict same way using not `ThreadPoolExecutor` instances as `executor` argument in `run_in_executor`

and silently apply propagation of `contextvars`

then we can point this changes to `Python 3.9`

**Comment by 1st1** [comment]
> and silently apply propagation of contextvars

Yeah, that's another problem, as we didn't do so in 3.7/3.8.

@asvetlov what do you think?

**Comment by asvetlov** [comment]
process pool executor is forbidden as *default* because things like DNS resolving doesn't work with it IIRC.
Passing explicit ProcessPoolExecutor into `run_in_executor()` is still supported.

Sorry, I don't follow what the proposal is? Please elaborate *silently apply propagation of contextvars* part

**Comment by NargiT** [comment]
any news about this ?

**Comment by NargiT** [comment]
@asvetlov is there an alternative to this ?

**Comment by asvetlov** [comment]
> @asvetlov is there an alternative to this ?

Take a look at `asyncio.to_thread()`

**Pull request closed without merging**
