### PR TITLE
gh-118299: Re-use old indent in `json.loads()`

### PR DESCRIPTION
**Pull request by nineteendo**
#### macOS

<details><summary>script</summary>

```sh
# speedup-json.dumps.sh
echo depth 1
              main/python.exe -m timeit -s "import json; data = []" "json.dumps(data, indent=1)"
speedup-json.dumps/python.exe -m timeit -s "import json; data = []" "json.dumps(data, indent=1)"
echo depth 10
              main/python.exe -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(10)" "json.dumps(data, indent=1)"
speedup-json.dumps/python.exe -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(10)" "json.dumps(data, indent=1)"
echo depth 100
              main/python.exe -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(100)" "json.dumps(data, indent=1)"
speedup-json.dumps/python.exe -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(100)" "json.dumps(data, indent=1)"
```
</details>

```none
depth 1
50000 loops, best of 5: 4.49 usec per loop # before
50000 loops, best of 5: 4.53 usec per loop # after
# -> no difference
depth 10
20000 loops, best of 5: 19.2 usec per loop # before
20000 loops, best of 5: 17 usec per loop # after
# -> 1.13x faster
depth 100
1000 loops, best of 5: 318 usec per loop # before
1000 loops, best of 5: 291 usec per loop # after
# -> 1.09x faster
```

#### Windows

<details><summary>script</summary>

```bat
::speedup-json.dumps.bat
@echo off
echo depth 1
call               main\python -m timeit -s "import json; data = []" "json.dumps(data, indent=1)"
call speedup-json.dumps\python -m timeit -s "import json; data = []" "json.dumps(data, indent=1)"
echo depth 10
call               main\python -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(10)" "json.dumps(data, indent=1)"
call speedup-json.dumps\python -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(10)" "json.dumps(data, indent=1)"
echo depth 100
call               main\python -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(100)" "json.dumps(data, indent=1)"
call speedup-json.dumps\python -m timeit -s "import json; nest = lambda depth: [] if depth < 1 else [nest(depth - 1)]; data = nest(100)" "json.dumps(data, indent=1)"
```
</details>

```none
depth 1
50000 loops, best of 5: 4.56 usec per loop # before
50000 loops, best of 5: 4.56 usec per loop # after
# -> no difference
depth 10
10000 loops, best of 5: 21 usec per loop # before
10000 loops, best of 5: 19 usec per loop # after
# -> 1.11x faster
depth 100
500 loops, best of 5: 398 usec per loop # before
1000 loops, best of 5: 372 usec per loop # after
# -> 1.07x faster
```

* Issue: gh-118299

### CODE REVIEW

**Review by ericvsmith — COMMENTED** [review]
This seems like too complex of a change, unless the performance impact justifies a more thorough code review. Have you measured the performance improvement?

And why rename the function parameter names? That's not making this easier to review. Renaming does not seem important. At best it should be a separate commit, although I doubt it's worth doing.

**Comment by nineteendo** [comment]
> Have you measured the performance improvement?

Yes, see the description of the pull request. If there are other cases you would like me to benchmark, let me know.

> And why rename the function parameter names?

We're no longer passing the indent level, we're passing the newline indent now. I can keep the names, but it'll make the code more confusing for future readers.

**Comment by aspizu** [comment]
Can the entire json module be written in C?

**Comment by nineteendo** [comment]
Can we use it for the Python implementation now #118105 is merged?

**Comment by serhiy-storchaka** [comment]
#118105 has been merged, but the story does not end here. See #118636 which uses a different approach.

**Comment by nineteendo** [comment]
Do you mean we will also be able to use caching in Python with improved performance? Aren't strings always copied when passed around?

**Comment by serhiy-storchaka** [comment]
> Do you mean we will also be able to use caching in Python with improved performance?

I have doubts. Even this PR is too complicated for such small gain (taking into account that normally the C implementation is used). More complex caching scheme increases the cost. On other hand, the complicated C code can be translated to simple Python code, and the benefit/ratio cost can be very good. We cannot say until we try.

> Aren't strings always copied when passed around?

Objects are never copied when passed as arguments in Python. And strings are never copied, they are immutable.

**Pull request closed without merging**
