### PR TITLE
bpo-44257: Fix typo and change to more compact grammar

### PR DESCRIPTION
**Pull request by ShinWonho**
[bpo-44257](https://bugs.python.org/issue44257)

https://bugs.python.org/issue44257

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@ShinWonho

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by lysnikolaou — CHANGES_REQUESTED** [review]
Hey @ShinWonho and congrats on your first PR!

Your refactorings of the `star_expressions` and `expressions` rules are wrong. Notice how the alternatives have different actions, so that if we have only one expression, that gets returned by itself, without being wrapped in a tuple. So leave those be for now.

If you want, you can remove those changes and I'd be happy to merge this to fix the typo in `assignment_expression`.

Also, please take care of the CLA by following @the-knights-who-say-ni's instructions.

**Comment by ShinWonho** [comment]
Thanks for the response!
However, I mistakenly clicked the requested a review button.
Sorry for the confuse.
I'll check again and update it (also take care of CLA)

**Comment by pablogsal** [comment]
I'm closing this for the time being. Please, feel free to reopen a new PR if you wish to continue the work!

**Pull request closed without merging**
