### PR TITLE
gh-91134: Correct docstrings for built-in in-place operators

### PR DESCRIPTION
**Pull request by nickovs**
The whitespace in the example code included in the doc string has also been made PEP-8 compliant.

https://bugs.python.org/issue46978

Automerge-Triggered-By: GH:rhettinger

* Issue: gh-91134

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@nickovs

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by MaxwellDupre — APPROVED** [review]
Couldn't find out how to test slots so ran full suite:
412 tests OK.
2 tests failed:
    test_asyncio test_embed
I think this qualifies as a pass. Anyway this has no side effects.

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
Closing and reopening to trigger the bots.

**Comment by rhettinger** [comment]
Please sign the CLA or we can't go forward.

**Comment by nickovs** [comment]
I already signed the CLA, back on March 11th, but it seems that there is a bug in the CLA-checking bot that means that if you have multiple email addresses on your GitHub account it needs you to sign multiple CLAs, in the same name but listing the different addresses. I've signed a second CLA so hopefully this can proceed.

**Comment by JelleZijlstra** [comment]
Unfortunately the CLA check is still failing.

As a workaround, maybe you can re-commit with the email address you signed up for and force-push the branch.

**Comment by iritkatriel** [comment]
Removed "awaiting merge" and marked "pending" as we can't merge this without the CLA check passing.

**Comment by JelleZijlstra** [comment]
Feel free to ping me for a merge once the CLA issue is resolved.

**Comment by CuriousLearner** [comment]
Hey @nickovs 👋🏼 

Can you please sign the Contributor License Agreement (CLA)? We can then get this merged in.

Thank you for your contribution!

**Comment by nickovs** [comment]
@CuriousLearner I just signed the CLA again, with the other email address on my GitHub account. Hopefully that will unblock it. If not then I'll try a `git commit --amend` with my primary email address and force-push another version.

**Review by CuriousLearner — APPROVED** [review]
LGTM.

Strange that it's not recognizing the CLA yet. I merged main into this branch, so it should've picked it up. Can you double-check once on the email used?

**Comment by CuriousLearner** [comment]
Hi @nickovs 

Can you click on the CLA signing action as shown in the picture below, and then sign-in with your Github account and sign the agreement?

bpo-46978__Correct_docstrings_for_built-in_in-place_operators_by_nickovs_·_Pull_Request__31802_·_python_cpython

I think then the check should automatically pick it up.

**Comment by nickovs** [comment]
OK. The system seems to now be showing the CLA is signed and all checks are passing.

**Comment by CuriousLearner** [comment]
That's amazing!! Thanks for your help Nicko! 

@rhettinger / @JelleZijlstra We can get this merged in now :)

**Comment by arhadthedev** [comment]
The CLA check is green; merging `main` to retrigger the `automerge` label processing.

**Comment by arhadthedev** [comment]
MacOS failure is known and is being fixed on the GitHub side. @iritkatriel could you merge this PR (with its backports) manually please? All other tests successfully pass.

**Comment by arhadthedev** [comment]
@iritkatriel I backported the PR but the bot failed to link them here:

- https://github.com/python/cpython/pull/102043
- https://github.com/python/cpython/pull/102042

**Comment by merwok** [comment]
Before backporting, could people go to the issue first to discuss the relevance of this change?

@rhettinger does not agree that there is a bug to be fixed here and requested to revert.

**Comment by iritkatriel** [comment]
> @rhettinger does not agree that there is a bug to be fixed here and requested to revert.

This PR was approved by @rhettinger .

**Comment by JelleZijlstra** [comment]
For ease of reference, the issue is #91134 and the relevant comment is https://github.com/python/cpython/issues/91134#issuecomment-1435989625.

**Pull request merged**
