### PR TITLE
[docs] Correct typos in SSLContext.sni_callback.

### PR DESCRIPTION
**Pull request by joernheissler**

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Review by hugovk — APPROVED** [review]
The docs build is unrelated: https://bugs.python.org/issue40066#msg410711

(Rebasing should fix it.)

```
File "library/enum.rst", line ?, in default
Failed example:
    Color(0)
Exception raised:
    Traceback (most recent call last):
      File "/home/runner/work/cpython/cpython/Lib/doctest.py", line [13](https://github.com/python/cpython/runs/4833263884?check_suite_focus=true#step:9:13)46, in __run
        exec(compile(example.source, filename, "single",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest default[0]>", line 1, in <module>
        Color(0)
        ^^^^^
    NameError: name 'Color' is not defined
```

**Comment by joernheissler** [comment]
Should I rebase+force-push?

**Comment by joernheissler** [comment]
I merged main. Seems to be all green no.

**Review by JelleZijlstra — APPROVED** [review]
Planning to merge in a few days (another small doc fix, cc @gvanrossum).

**Review by gvanrossum — APPROVED** [review]
Yeah

**Pull request merged**
