### PR TITLE
gh-113317: Add ParseArgsCodeGen class

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-113317

### CODE REVIEW

**Comment by vstinner** [comment]
This PR is based on PR gh-117626.

**Comment by vstinner** [comment]
PR rebased on top of merged https://github.com/python/cpython/pull/117626.

**Comment by erlend-aasland** [comment]
The previous PR used the `Codegen` spelling. This PR uses `CodeGen`. Consider using only one variant :)

**Comment by erlend-aasland** [comment]
This is nice!

Should we consider adding this as a separate module? Or would `libclinic.codegen` be a better home for it?

**Comment by vstinner** [comment]
> Should we consider adding this as a separate module?

CLanguage uses ParseArgsCodeGen which uses CLanguage... There is an inter-dependency. It's more convenient to have both classes in the same file.

**Comment by vstinner** [comment]
> The previous PR used the Codegen spelling. This PR uses CodeGen. Consider using only one variant :)

I updated this PR to rename Codegen to CodeGen.

**Comment by vstinner** [comment]
> Should we consider adding this as a separate module?

I broke the inter-dependency between CLanguage and ParseArgsCodeGen, and I moved declare_parser() and ParseArgsCodeGen to a new `libclinic.parse_args` module.

**Comment by erlend-aasland** [comment]
> I broke the inter-dependency between CLanguage and ParseArgsCodeGen, and I moved declare_parser() and ParseArgsCodeGen to a new `libclinic.parse_args` module.

Nice, so now we can make the parser templates globals of the `libclinic.parse_args` module, instead of class members.

**Comment by vstinner** [comment]
> Nice, so now we can make the parser templates globals of the libclinic.parse_args module, instead of class members.

Done.

**Review by erlend-aasland — APPROVED** [review]

**Pull request merged**
