### PR TITLE
gh-66783: Automate update of Unicode data version in documentation

### PR DESCRIPTION
**Pull request by nmassman**
Added a sphinx extension and modified makeunicodedata.py to automate updating documentation with the current Unicode version when it changes.

https://bugs.python.org/issue22593

* Issue: gh-66783

### CODE REVIEW

**Review by aeros — CHANGES_REQUESTED** [review]
Thanks for the PR @nmassman and welcome!

I agree with the general idea behind the PR, it doesn't seem practical to maintain the latest Unicode version in 6 different locations, or for additional ones that are added in the future. 

However, a few points (I might think of more later):

1) You could store the version as a global constant in `conf.py`, I don't think we need a dedicated text file *just* to store the latest unicode version.
2) `UNICODE_VERSION` or `UCS_VERSION` would be a far more explicit name for the constant. As far as I'm aware, "UCD" is not a commonly known acronym for Unicode.
3) IANAL, but I believe there are legal issues associated with copyrighting your own file additions. Our primary means of providing credit/acknowledgement to contributors these days is by adding a `Contributed by <name>.` sentence at the end of the news entry for the PR. You can add this in yourself.

/cc @merwok

**Comment by nmassman** [comment]
Thanks for the feedback @aeros 

> 1. You could store the version as a global constant in `conf.py`, I don't think we need a dedicated text file _just_ to store the latest unicode version.

I waffled on this a bit, but I went back and took another crack at it. Mostly I wanted to avoid having makeunicodedata.py accidentally mangle conf.py. I think I got it working reliably, though.

> 2. `UNICODE_VERSION` or `UCS_VERSION` would be a far more explicit name for the constant. As far as I'm aware, "UCD" is not a commonly known acronym for Unicode.

Kinda embarrassed that I didn't clean that up before submitting the PR. I should have slept first. :) I renamed everything to 'UNIDATA_VERSION' to match the original variable in makeunicodedata.py. This could just as easily be changed to 'UNIDATA_VERSION', but I erred on the side of staying consistent to what was already in place.

> 3. IANAL, but I believe there are legal issues associated with copyrighting your own file additions. Our primary means of providing credit/acknowledgement to contributors these days is by adding a `Contributed by <name>.` sentence at the end of the news entry for the PR. You can add this in yourself.


I wasn't sure of the convention. I copied the heading format from what was in a few of the other sphinx extensions in the same directory. I inserted the bpo link instead (which was also in one of the other extensions), and updated the news entry.

**Comment by merwok** [comment]
I think the comments in the file constitute a change log, not a copyright notice.  The copyright situation is already handled by the CLA check, which ensures that the contribution has a suitable license.

It seems OK to me to add a line there, even though there is external history in VCS metadata.

**Comment by JulienPalard** [comment]
I feel this would be easier by using [rst_prolog](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_prolog) like:

```
rst_prolog = f"""
.. |UNIDATA_VERSION| replace:: {UNIDATA_VERSION}
"""
```

it would not need an extension.

**Review by furkanonder — APPROVED** [review]

**Comment by AA-Turner** [comment]
Closing per https://github.com/python/cpython/issues/66783#issuecomment-1890054849

A

**Pull request closed without merging**
