### PR TITLE
gh-100795: avoid unexpected `freeaddrinfo` after failed `getaddrinfo`

### PR DESCRIPTION
**Pull request by sebres**
Proposed PR fixes segfault gh-100795 - avoid unexpected `freeaddrinfo` if `res` becomes not NULL during invocation of `getaddrinfo` if it fails.
Previously this could cause double freeing and other hardly reproducible aftereffects, especially in multithreaded environment.

One could surely do `return -1` instead of `res = NULL` & `goto fail` (in second case), like in https://github.com/python/cpython/blob/5ef90eebfd90147c7e774cd5335ad4fe69a7227c/Modules/socketmodule.c#L1095
but this way it is minimal invasive (more consistent, remains safe against some merges or future implementations expecting goto fail to free some other handles, etc).

### CODE REVIEW

**Comment by kumaraditya303** [comment]
You need to create a PR against main branch will be backported if required to older branches.

**Comment by sebres** [comment]
> You need to create a PR against main branch 

Don't you know one is able to change the target branch of pull request? The change is trivial and module rarely modified, so there wouldn't be any conflicts, otherwise I'll fix them.
Please reopen.

**Comment by kumaraditya303** [comment]
> Don't you know one is able to change the target branch of pull request?

I didn't know that, how can one do that?

**Comment by arhadthedev** [comment]
Your patch attempt to modify 1670 files. It seems you've created your branch not from `main` but from way older branch.

**Comment by sebres** [comment]
Oh goodness... What's a Chaos... Don't they have common ancestor?
I'll rebase few related commits later...

**Comment by arhadthedev** [comment]
> Don't they have common ancestor?

  According to [history of `patch-1` branch](https://github.com/sebres/cpython/commits/patch-1), you've created it from `3.9` instead of `main`.

**Comment by cjw296** [comment]
Please base this off main

**Comment by sebres** [comment]
I know therefore I wrote that a rebase is needed.
This happens if development takes places in branches independently without any interim merge point to mainline.
Please reopen, I'll cherry pick that commits main-based.

**Comment by sebres** [comment]
OK, the [branch](https://github.com/python/cpython/compare/main...sebres:cpython:patch-1) is main-based now.
You can reopen it or forget it (because I don't understand why your time should be more valuable than my).
As I saw this chaos I marked this PR as draft, there was no reason at all to close it.

**Comment by arhadthedev** [comment]
> there was no reason at all to close it.

Apologises if the swift closure appeared to be rude. GitHub fails to update PR's *Commits* and *Files Changed* tabs if a push creates massive changes. So it's way easier to create a new PR for a fixed branch instead of trying to somehow reset notifications and the tabs.

**Comment by arhadthedev** [comment]
By the way, branch miscreation happens regularily in the CPython repo so closing and recreation anew became a standard (and default / someway unquestionable) practice.

**Comment by vsajip** [comment]
> branch miscreation happens regularily in the CPython repo

Yes, because new contributors apparently have missed [this bit](https://devguide.python.org/getting-started/pull-request-lifecycle/index.html) in the documentation ("Lifecycle of a Pull Request"):

> Here is a quick overview of how you can contribute to CPython:

> * Create an issue that describes your change
> * Create a new branch in Git from the `main` branch

> (later steps omitted)

**Comment by sebres** [comment]
OK, new PR #101220 is there now.
FWIW, as already said, few simplest interim merge-marks of primary branches to each other up top main (simple merge-points of 3.9 -\> 3.10 -\> 3.11 -\> main, without data/conflicts resolution, just to obtain **new** common ancestor, e. g. after some releases) could help again such kind of disaster, avoid large unmerged trees again and again and prevent such a chaos on GH side (regardless of possible user confusion)... let alone it'd help people actively developing against different branches or else often switching them (to find a bug source or target branch to backport, to bisect, blame etc pp).

**Pull request closed without merging**
