### PR TITLE
[2.7] bpo-31675: Fix memory leaks in Tkinter's methods splitlist() and split() (GH-3866)

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
when pass a string larger than 2 GiB.
(cherry picked from commit 27c623c845dd6e4b8e1782666ca3a956636da266)

https://bugs.python.org/issue31675

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
While the PR seems good to me, I'm not sure that a NEWS entry is really needed. _tkinter.c doesn't have "#define PY_SSIZE_T_CLEAN" in Python 2.7, and so already rejected strings longer than INT_MAX in PyArg_ParseTuple(), no?

**Comment by serhiy-storchaka** [comment]
PY_SSIZE_T_CLEAN affects the type of the size variable. But "et" doesn't return a size.

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
> PY_SSIZE_T_CLEAN affects the type of the size variable. But "et" doesn't return a size.

Oh, I see. Thank you for checking. Your PR now LGTM.

**Pull request merged**
