### PR TITLE
bpo-37493: use _PyObject_CallNoArg in more places

### PR DESCRIPTION
**Pull request by jdemeyer**
CC @vstinner @methane 

https://bugs.python.org/issue37493

### CODE REVIEW

**Review by skrah — DISMISSED** [review]
I'm a bit surprised --- we discussed on bpo to use fewer places, but you add more.

So please take out the decimal changes.  I'll add new functions as I see fit.

**Comment by jdemeyer** [comment]
> we discussed on bpo to use fewer places, but you add more.

I'm not sure what you mean. The only thing that we discussed (on bpo-37483 which relates to a different PR) is that maybe we should not use private functions in `_decimal.c`. However, in this case I'm using a documented public function, belonging to the limited API `PyObject_CallNoArgs`.

So please let me know whether the changes to `_decimal.c` should be reverted anyway.

**Comment by skrah** [comment]
The PR title mentions `_PyObject_CallNoArg()`.  I see now that there are other functions in the `_decimal.c` diff, but again not in speed sensitive locations.

So perhaps there are too many new functions.  I'll decide later if to use any of these, so yes, please take them out.

**Comment by jdemeyer** [comment]
> not in speed sensitive locations.

Even if it's not speed sensitive, I see no reason to prefer `PyObject_CallObject(func, NULL)` over `PyObject_CallNoArgs(func)`.

**Comment by jdemeyer** [comment]
`I have made the requested changes; please review again`

**Review by skrah — COMMENTED** [review]
Thanks for the changes.

**Pull request merged**
