### PR TITLE
bpo-38980: Only apply -fno-semantic-interposition if available

### PR DESCRIPTION
**Pull request by encukou**
https://bugs.python.org/issue38980

Automerge-Triggered-By: GH:encukou

### CODE REVIEW

**Comment by pablogsal** [comment]
Seems that the failing buildbot is now working:

https://buildbot.python.org/all/#/builders/192/builds/16

**Review by pablogsal — APPROVED** [review]
Thanks a lot @encukou

**Review by gpshead — APPROVED** [review]

**Comment by encukou** [comment]
There are still failing buildbots, but I don't see new issues.

**Comment by encukou** [comment]
Thanks for the reviews!

**Pull request merged**
