### PR TITLE
gh-86179: Skip test case that fails on POSIX with unversioned binary

### PR DESCRIPTION
**Pull request by zooba**
* Issue: gh-86179

### CODE REVIEW

**Comment by encukou** [comment]
FWIW, I saw this failure on the s390x PR buildbot. I thought it's a configuration/transient issue and didn't prioritize it.
Agree that skipping first and fixing later is the right approach. But first let's try:

**Comment by encukou** [comment]
!buildbot s390x Fedora Clang

**Comment by vsajip** [comment]
> The command will test the builders whose names match following regular expression

Useful feature! Thanks for bringing it to my attention :smile:

**Comment by zooba** [comment]
Ah, thought I hit merge on this one last night. Unblocking the release now!

**Pull request merged**
