### PR TITLE
Add lysnikolaou to CODEOWNERS for the new parser

### PR DESCRIPTION
**Pull request by lysnikolaou**

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]

**Comment by lysnikolaou** [comment]
Thanks @pablogsal for not merging this. My first ever merge in CPython. Let's do this!

**Comment by pablogsal** [comment]
> Thanks @pablogsal for not merging this. My first ever merge in CPython. Let's do this!

go go go! :rocket: (Remember to change the '#' to GH- or the bots will be angry :robot: )

**Comment by lysnikolaou** [comment]
Yes! 🎉

**Comment by pablogsal** [comment]
Congrats :tada:  The first of many :)

**Pull request merged**
