### PR TITLE
bpo-25430: improve performance of IPNetwork.__contains__

### PR DESCRIPTION
**Pull request by gescheit**
make a compare in bit-operation manner
see http://bugs.python.org/issue25430 for detail

https://bugs.python.org/issue25430

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by pitrou** [comment]
Changed the CLA label as @gescheit is recorded as having signed it in Roundup: https://bugs.python.org/user15300

**Comment by BoboTiG** [comment]
Thanks @gescheit, changes looks good to me!
I think adding a NEWs entry would be good too, don't you?

**Comment by asvetlov** [comment]
What is performance boost?

**Comment by BoboTiG** [comment]
@asvetlov you can find numbers in the description of the BPO.

**Comment by asvetlov** [comment]
Got you. Thanks.
Could you please add a NEWS entry? 
https://devguide.python.org/committing/?highlight=blurb#what-s-new-and-news-entries

**Review by asvetlov — DISMISSED** [review]
NEWS entry is requered

**Comment by tirkarthi** [comment]
Ping @gescheit . This seems to be blocking only on NEWS entry. Can you please add one? It would be nice to see this as part of next release. You can add it from the web interface using https://blurb-it.herokuapp.com/ or using the blurb tool at https://pypi.org/project/blurb/

Thanks

**Review by Cant2 — APPROVED** [review]
****

**Pull request merged**
