### PR TITLE
bpo-19896: Add typecodes 'q' and 'Q' to multiprocessing.sharedctypes

### PR DESCRIPTION
**Pull request by gareth-rees**
Patch by Antony Lee.

https://bugs.python.org/issue19896

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by pitrou** [comment]
I think the AppVeyor failure is unrelated -- I got it on another PR.

**Comment by pitrou** [comment]
Thank you. This looks fine to me. This is still missing a NEWS entry as generated using the [blurb tool](https://pypi.org/project/blurb/). Do you want to do that?

**Comment by pitrou** [comment]
I'm gonna close and reopen the issue to try and schedule a new AppVeyor build.

**Comment by pitrou** [comment]
Ok, AppVeyor build passed. i'm merging now. Thank you for submitting this PR!

**Pull request merged**
