### PR TITLE
bpo-44079: Strip superfluous statement cache from sqlite3.Connection

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue44079

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@corona10 I'm considering adding _skip news_ label here, as this only affects the internal machinery of the `sqlite3` module.

**Comment by corona10** [comment]
> Statement instances are no longer weakly referencable

I think that this should be added to the NEWS.d

**Comment by corona10** [comment]
>  as this only affects the internal machinery of the sqlite3 module
@erlend-aasland 
I don't think so


> Statement instances are no longer weakly referencable

IMHO, At least the statement instance is changed, we can add the news.d about chacing mechanism changed.

**Comment by corona10** [comment]
@erlend-aasland 
Hmm okay, I changed my mind, let's add `skip news` label :)

**Comment by berkerpeksag** [comment]
True, this is an implementation detail and we don't need to add a NEWS entry.

**Comment by erlend-aasland** [comment]
On hold until #26026 is merged.

**Review by pablogsal — APPROVED** [review]

**Pull request merged**
