### PR TITLE
bpo-35267: warning deadlock in multiprocessing.Pool

### PR DESCRIPTION
**Pull request by Windsooon**
We also discussed in https://python.zulipchat.com/#narrow/stream/116742-core.2Fhelp/topic/issue35267

https://bugs.python.org/issue35267

### CODE REVIEW

**Comment by Windsooon** [comment]
Thank you @ZackerySpytz, I updated it.

**Comment by ZackerySpytz** [comment]
Not quite. Please also fix the commit message and the link in the first post.

**Review by vstinner — CHANGES_REQUESTED** [review]
I would prefer to see the issue fixed rather than documented.

**Comment by Windsooon** [comment]
@vstinner any ideas to fix it?

**Comment by vstinner** [comment]
> @vstinner any ideas to fix it?

Sorry, I have no idea.

**Comment by Windsooon** [comment]
I don't know how to fix it. As Nathaniel J. Smith said:

> you might be thinking of PIPE_BUF, which POSIX says has to be >= 512 bytes, and on linux is 4096 bytes. This a magic number where if you send < PIPE_BUF bytes in a single write, then the kernel isn't allowed to break it up into pieces. This means that if you have a non-blocking pipe, then select can only report it as being writable if it as at least PIPE_BUF bytes of free space available.

Some new ideas are needed.

**Comment by JulienPalard** [comment]
As said here by Victor and in b.p.o by Davin, there may be a fix, so we better work on fixing it than documenting the bug.

**Pull request closed without merging**
