### PR TITLE
Fix typo: `iff` to `if`

### PR DESCRIPTION
**Pull request by zygiss**
Hello.  This commit fixes a few typos in `Lib/fileinput.py` docstring.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Thanks, but this is not a typo: https://en.wikipedia.org/wiki/If_and_only_if

**Comment by CuriousLearner** [comment]
Thanks for your contribution, but this isn't a typo. Iff - means `if and only if`.

**Comment by zygiss** [comment]
TIL, thanks for your quick review folks.

**Comment by nedbat** [comment]
FWIW, we shouldn't be using mathematics jargon in these docs.  We should replace `iff` with English.

**Comment by AlexWaygood** [comment]
> FWIW, we shouldn't be using mathematics jargon in these docs. We should replace `iff` with English.

True. @zygiss, would you be interested in amending your PR (or opening a new one) replacing `iff` with `if and only if`?

**Comment by zygiss** [comment]
> > FWIW, we shouldn't be using mathematics jargon in these docs. We should replace `iff` with English.
> 
> True. @zygiss, would you be interested in amending your PR (or opening a new one) replacing `iff` with `if and only if`?

Hey folks, pardon the delay; I'd be happy to do that.

There're quite a few uses of `iff` across Python, C and C header files https://gist.github.com/zygiss/c3ddeb0729a7de3bc20be25bf23b11e6.

Let me know if I should leave any of those untouched.  At a glance, I think https://github.com/python/cpython/blob/main/Misc/HISTORY should remain unedited for posterity.

**Pull request closed without merging**
