### PR TITLE
bpo-45633 Fix typo in extending/newtypes documentation

### PR DESCRIPTION
**Pull request by dmitrysmirnov931**
https://bugs.python.org/issue45633

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@dmitrysmirnov931

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by sobolevn — APPROVED** [review]
Thanks, @dmitrysmirnov931!

You need to sign CLA to be able to contribute. 
Also, don't be scared of `news` CI failure. I guess this is a good candidate for `skip:news` label (it will be done on merge  by someone else) 🙂 

Congrats on your first PR to CPython! 🎉

**Comment by dmitrysmirnov931** [comment]
@sobolevn Yeah, thank you for sharing the issue! I have already signed the CLA actually, I'm waiting now for it to be processed

**Review by Fidget-Spinner — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
