### PR TITLE
[3.9] bpo-41950: Typo in Python 3.9 what's new page

### PR DESCRIPTION
**Pull request by kigawas**
https://bugs.python.org/issue41950

### CODE REVIEW

**Comment by corona10** [comment]
@kigawas Please open this PR to the master branch, we will backport this patch after the PR to the master is merged :)

**Comment by kigawas** [comment]
Oh...tons of commits 😮

**Comment by corona10** [comment]
Please reopen the PR with the new branch which is checked out from master branch :)

**Comment by kigawas** [comment]
I'll rebase later

**Comment by gvanrossum** [comment]
Actually, the text that this corrects is not (yet?) present in the master branch -- it was added (with the fix being corrected here) by @ambv when he released 3.9.0.

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Thanks!

**Comment by terryjreedy** [comment]
For some reason, https://github.com/python/cpython/branches shows a closed but active sync-39-whatsnew branch.  It probably should be deleted, but I don't know for sure how.

**Pull request merged**
