### PR TITLE
bpo-33595: Fix lambda parameters being refered as arguments

### PR DESCRIPTION
**Pull request by andresdelfino**
https://bugs.python.org/issue33595

### CODE REVIEW

**Comment by JulienPalard** [comment]
@andresdelfino Thanks!

**Comment by andresdelfino** [comment]
Should I cherry-pick the commit to backport the fix to 2.7?

**Comment by terryjreedy** [comment]
Julien, The commit message did not have the "bpo-33595: " prefix.  Hence the backports were missing the prefixes.  Hence the backports were not listed on the issue, and one could not tell from the issue that the backports had been done.

Andres, I added a 2.7 backport label, but there is a conflict.  While checking why (the function name in the def equivalent), I made the changes and 2.7 PR.

**Comment by terryjreedy** [comment]
Andrés, it appears that you created the PR without the bpo prefix, and that it was added later (due to the CI message).  Unfortunately, Github's default title for commits is the original PR title, not the corrected title.

**Comment by andresdelfino** [comment]
Yes, that is exactly what happened!

**Comment by JulienPalard** [comment]
@terryjreedy woops I in fact missed this point, sorry for this. I followed closely https://devguide.python.org/committing/#is-the-pr-ready-to-be-accepted but jumped a bit fast on the "squash and merge", overlooking https://devguide.python.org/gitbootcamp/#accepting-and-merging-a-pull-request, my bad.

**Comment by terryjreedy** [comment]
I consider it a Github bug that it resurrects the initial version of the title to use as the default merge title.  I still occasionally forget to replace '#' with 'GH-', so I now make myself pause between initial and confirmatory clicks.  Slower can be faster ;-).

**Pull request merged**
