### PR TITLE
bpo-36333: Fix leak in _PyRuntimeState_Fini

### PR DESCRIPTION
**Pull request by matrixise**
https://bugs.python.org/issue36333

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM, but I would prefer that @ericsnowcurrently review it since he added _PyRuntime.xidregistry (and its mutex).

**Comment by vstinner** [comment]
Python 3.7 is not affected: it doesn't have _PyRuntime.xidregistry.

**Review by eamanu — APPROVED** [review]
LGTM!

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

Thanks for working on this!

**Comment by ericsnowcurrently** [comment]
FWIW, `_PyRuntime.ceval.pending.lock` may be leaking too.

**Comment by vstinner** [comment]
> FWIW, _PyRuntime.ceval.pending.lock may be leaking too.

@matrixise: Can you try to free _PyRuntime.ceval.pending.lock in _PyEval_FiniThreads()?

**Comment by matrixise** [comment]
@ericsnowcurrently I will check in an other PR. Thanks for the review

**Comment by matrixise** [comment]
Ok i will do it

**Comment by vstinner** [comment]
I merged this PR, thanks @matrixise.

Oh, there are now too many leaks... I merged https://bugs.python.org/issue36356 PR and I wrote PR #12432 to free the pending lock, to have a better view of remaining leaks.

**Pull request merged**
