### PR TITLE
bpo-42010: [docs] Clarify subscription of types

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
https://bugs.python.org/issue42010

### CODE REVIEW

**Review by terryjreedy — COMMENTED** [review]
Looks good to me, but someone else should verify and merge.
This should have a news entry.

**Comment by Fidget-Spinner** [comment]
A burb entry has been added, however the tests that were previously successful are now failing with the message "GitHub Actions has encountered an internal error when running your job.".

**Comment by terryjreedy** [comment]
I don't know if this is a random glitch or a result of markup.  I triggered rerun of the actions.  Otherwise, try deleting markup.

**Comment by terryjreedy** [comment]
That worked.  It is nice that GHAs have an easy to find and use Re-run button that only re-runs the stuff in that action.  Much better than re-running everything.

**Review by gvanrossum — APPROVED** [review]
Yes. Thanks!

**Pull request merged**
