### PR TITLE
bpo-29585: Define PYTHONFRAMEWORK in PC/pyconfig.h

### PR DESCRIPTION
**Pull request by vstinner**
Fix also PC/pyconfig.h whitespaces: run "make patchcheck".

### CODE REVIEW

**Comment by vstinner** [comment]
Crap. Tests fail on Windows:

```
======================================================================
FAIL: test_get_path (test.test_site.HelperFunctionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\test\test_site.py", line 188, in test_get_path
    sysconfig.get_path('purelib', os.name + '_user'))
AssertionError: 'C:\\Users\\appveyor\\AppData\\Roaming\\Python/Python37/site-packages' != 'C:\\Users\\appveyor\\AppData\\Roaming\\Python\\Python37\\site-packages'
- C:\Users\appveyor\AppData\Roaming\Python/Python37/site-packages
?                                         ^        ^
+ C:\Users\appveyor\AppData\Roaming\Python\Python37\site-packages
?                                         ^        ^
======================================================================
FAIL: test_s_option (test.test_site.HelperFunctionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\test\test_site.py", line 195, in test_s_option
    self.assertIn(usersite, sys.path)
AssertionError: 'C:\\Users\\appveyor\\AppData\\Roaming\\Python/Python37/site-packages' not found in ['', 'C:\\projects\\cpython\\PCbuild\\win32\\python37.zip', 'C:\\projects\\cpython\\DLLs', 'C:\\projects\\cpython\\lib', 'C:\\projects\\cpython\\PCbuild\\win32', 'C:\\projects\\cpython', 'C:\\projects\\cpython\\lib\\site-packages']
```

**Comment by vstinner** [comment]
This PR fixes a regression of the PR #136.

**Comment by methane** [comment]
thanks

**Comment by vstinner** [comment]
> thanks

You're welcome. I hesitated to just revert your PR to get more time to fix it, but at the end, I found a way to repair the Windows buildbots, so it's fine.

Hey, don't forget our macOS buildbots which are also broken!

**Pull request merged**
