### PR TITLE
Improve sqlite3 documentation of the new autocommit attribute

### PR DESCRIPTION
**Pull request by geryogam**
Issue https://github.com/python/cpython/issues/99670.

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Please open an issue so we can discuss the problems you've identified first.

**Comment by maggyero** [comment]
> Please open an issue so we can discuss the problems you've identified first.

@erlend-aasland I have opened issue https://github.com/python/cpython/issues/99670.

Prior to that, I have further subdivided one of the commits which was too big, for better isolation of the problems and easier review.

**Comment by erlend-aasland** [comment]
> I have opened issue #99670.
> 
> I have further subdivided this PR in 9 logical commits instead of 6 for better isolation of the problems and easier review.

This issue just lists the summary of the various commits in this PR; it does not describe any issues at all. A lot of these commits are changes completely unrelated to the PR title (for example normalising the use of "open transaction" versus "pending transaction"). Some of these changes might be worth doing. A lot of them are IMO unneeded churn. I suggest closing this PR and the accompanying issue. Try instead to _isolate_ each problem, describe it accurately and explain _why_ it is a problem. Then it will be possible to discuss the issue, decide if it is a real problem, and what the suggested solution should be.

**Comment by maggyero** [comment]
> Some of these changes might be worth doing.

Could you list them? To me the 5 first commits are the most important as they add new information. The 4 remaining ones are just rephrasing so a matter of opinion.

> Try instead to _isolate_ each problem,

That is what I did by splitting this PR into 9 commits.

> describe it accurately and explain _why_ it is a problem.

That is what I did with the commit messages. At this point I am not sure what more I can add so I kindly suggest that you list the commits that you agree with, otherwise we will not make any progress.

**Pull request closed without merging**
