### PR TITLE
bpo-40045: Make "dunder" method documentation easier to locate

### PR DESCRIPTION
**Pull request by ghost**
[Issue 40045](https://bugs.python.org/issue40045)

https://bugs.python.org/issue40045

### CODE REVIEW

**Review by aeros — APPROVED** [review]
Thanks for the PR @javadmokhtari; LGTM.

**Review by nanjekyejoannah — APPROVED** [review]
Since there was consensus from bpo here : https://bugs.python.org/issue40045, this LGTM. Thanks for your contribution @javadmokhtari .

**Comment by aeros** [comment]
IMO, this should be backported to 3.8 and 3.7.

**Review by nanjekyejoannah — COMMENTED** [review]
Let us give @rhettinger time to look. If he doesn't, I will merge this tomorrow.

**Comment by aeros** [comment]
Congrats on your first merged PR, @javadmokhtari! :-)

**Pull request merged**
