### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by xyb**

### CODE REVIEW

**Comment by Wulian233** [comment]
LGTM

**Comment by xyb** [comment]
@sobolevn @terryjreedy Could you please take a look?

**Comment by terryjreedy** [comment]
Thanks.  I backported the one applicable change to 3.12.

**Comment by terryjreedy** [comment]
Deleted test_socketserver failure on buildbot.

**Comment by xyb** [comment]
@terryjreedy Thank you!

**Pull request merged**
