### PR TITLE
setup: support linking openssl staticly

### PR DESCRIPTION
**Pull request by ghost**
Currently, it's easy to compile CPython even on old distributions like RHEL5, RHEL6, Ubuntu14.04 etc. **except for ssl module**.

This PR adds a new _./configure_ option _--with-openssl-static_ which makes it easy to compile statically against OpenSSL so CPython with ssl module can be easily compiled on systems with OpenSSL <1.0.2 (you usually don't want to install newer openssl as system libary nor mess with rpath/set LD_LIBRARY_PATH every time you run python). 

With this change, if _--with-openssl-static_ is not set everything behaves like before.

**When/if this PR is merged, autoreconf needs to be run to regenerate bundled ./configure script etc.**. I am not sure what's the recommended process to run autoreconf (version, parameters, ...) so I have not comitted the generated files.

Installing CPython including ssl on system as old as RHEL5 with this option only takes (after installing required build depencies from rhel5 repositories):

```
wget https://www.openssl.org/source/openssl-1.0.2t.tar.gz
tar xf openssl-1.0.2t.tar.gz
cd openssl-1.0.2t
./config --openssldir=/etc/pki/tls -fPIC
make

wget https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tgz
tar xf Python-3.7.5.tgz
cd Python-3.7.5
./configure --with-openssl-static=path_to_just_compiled_ssl --prefix=prefix_path
make
make install
```

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@luv

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by luv** [comment]
I have added my github username to bugs.python.org

**Comment by brandtbucher** [comment]
Thanks for your time @luv, and welcome to CPython!

Our workflow is to make PRs against the `master` branch, then backport the changes to maintenance branches. Can you close this PR and open a new one against `master`?

You should also open [a BPO issue](https://bugs.python.org) for discussing this change.

**Review by brandtbucher — CHANGES_REQUESTED** [review]
Our workflow is to make PRs against the `master` branch, then backport the changes to maintenance branches. Can you close this PR and open a new one against `master`?

You should also open [a BPO issue](https://bugs.python.org) for discussing this change.

**Comment by luv** [comment]
Sure, will do, thanks for quick reply.

**Pull request closed without merging**
