### PR TITLE
bpo-42327: Add PyModule_Add().

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue42327

### CODE REVIEW

**Review by tiran — CHANGES_REQUESTED** [review]
Could you please move your changes of ``_ssl.c`` to another PR? This PR will cause major conflicts with two of my PRs.

I also like to get your opinion on https://discuss.python.org/t/define-module-constants-in-pymoduledef/5749 . I have suggested a radically different approach for module constant initialization that is even more convenient than ``PyModule_Add()``.

**Comment by serhiy-storchaka** [comment]
I will most likely break this PR into several parts and merge them separately. It grew more than I expected because for each modified module I fixed all potential leaks, and some module expose many constants.

**Comment by serhiy-storchaka** [comment]
Created #23443 which does not include large changes.

**Comment by serhiy-storchaka** [comment]
Split and merged as a number of smaller PRs.

**Pull request closed without merging**
