### PR TITLE
gh-121562: optimized hex_from_char

### PR DESCRIPTION
**Pull request by LimaBD**
# Optimized hex_from_char performance

issue https://github.com/python/cpython/issues/121562

Timing with old hex_from_char:

```
$ ./python -m pyperf timeit --duplicate 100 "float.fromhex('0x123456.ffffp10')"
.....................
Mean +- std dev: 86.0 ns +- 0.9 ns
```

With new hex_from_char:

```
$ ./python -m pyperf timeit --duplicate 100 "float.fromhex('0x123456.ffffp10')"
.....................
Mean +- std dev: 81.8 ns +- 1.0 ns
```

If we measure `hex_from_char` directly, probably we will get a much better % improvement because there is additional calls that `float.fromhex` makes apart from this one.

* Issue: gh-121562

### CODE REVIEW

**Review by mdickinson — APPROVED** [review]
LGTM in principle. The old code is agnostic to character encoding (works equally well with ASCII / EBCDIC / whatever), while the new code is based on the bytes of the UTF8-encoded string. That's fine, since the only use-case is applying this to a UTF-8-encoded value. But please could we add a comment that makes it clear that this table should only be used with encodings whose lower half is ASCII (like UTF-8).

**Comment by LimaBD** [comment]
Hello @mdickinson, thanks for your time, I just added the comment clarifying it but my English is average, anything let me know!

**Review by mdickinson — APPROVED** [review]
Thanks for the update; the comment looks good.

**Comment by mdickinson** [comment]
@LimaBD Merged. Thank you for the contribution!

**Pull request merged**
