### PR TITLE
bpo-40439: Update broken link in lexical analysis docs

### PR DESCRIPTION
**Pull request by Akarys42**
https://bugs.python.org/issue40439

Automerge-Triggered-By: @csabella

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Akarys42

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by remilapeyre — APPROVED** [review]
Hi @Akarys42, thanks for opening a new PR for this change!

While it is not always required for small documentation updates, the CLA will be needed if you want to contribute bigger changes in the future so it you should sign it if you plan to contribute again later.

**Comment by Akarys42** [comment]
Hello! I've signed the CLA just before opening the PR, 14h ago 😁

**Review by csabella — APPROVED** [review]
lgtm.   Thank you for the contribution!  🎉

**Pull request merged**
