### PR TITLE
gh-112069: Add _PySet_NextEntryRef to be thread-safe.

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-112069

* Add _PySet_NextEntryRef to be thread-safe.
* Use FrozenSet if possible to use _PySet_NextEntry without locking.

### CODE REVIEW

**Comment by corona10** [comment]
> Tests / Thread sanitizer (free-threading) / Thread sanitizer (pull_request) 

OKay, it's too slow.

**Review by colesbury — COMMENTED** [review]
I'm not sure what the right approach here is, but as written `_PySet_NextEntry` still returns a borrowed reference, so the cases that were not thread-safe are probably still not thread-safe.

I don't think it makes sense to try to make individual calls to `_PySet_NextEntry` thread-safe. The whole loop of `while(_PySet_NextEntry(...))` is generally what needs to be thread-safe. For example, the comment in `set_next` says:

https://github.com/python/cpython/blob/fccedbda9316d52d93b2db855c07f947fab26ae2/Objects/setobject.c#L477-L478

I think we should add locking in the use sites of `_PySet_NextEntry` as necessary. Most look like they're already okay to me: either they already do locking (`listobject.c` and `dictobject.c`) or operate on private or immutable data (`pylifecycle.c`, `codeobject.c`).

The two cases that concern me and may need locking are:
* `_pickle.c`
* `marshal.c`

**Comment by corona10** [comment]
buildbot/AMD64 RHEL7 Refleaks PR: Unrelated
```
In file included from ./Include/internal/mimalloc/mimalloc/types.h:24:0,
                 from ./Include/internal/pycore_mimalloc.h:40,
                 from ./Include/internal/pycore_interp.h:30,
                 from ./Include/internal/pycore_runtime.h:17,
                 from ./Include/internal/pycore_pystate.h:12,
                 from Parser/myreadline.c:14:
./Include/internal/mimalloc/mimalloc/atomic.h:39:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
In file included from ./Include/internal/mimalloc/mimalloc/types.h:24:0,
                 from ./Include/internal/pycore_mimalloc.h:40,
                 from ./Include/internal/pycore_interp.h:30,
                 from ./Include/internal/pycore_runtime.h:17,
                 from ./Include/internal/pycore_long.h:13,
                 from Objects/boolobject.c:4:
./Include/internal/mimalloc/mimalloc/atomic.h:39:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
```

**Review by colesbury — COMMENTED** [review]
- We should not change the reference count behavior of `_PySet_NextEntry` as it's exposed publicly and used outside of CPython (like in Cython). If needed, add a new function `_PySet_NextEntryRef`.
- I don't think `_PyFrozenSet_NextEntry` is needed. `_PySet_NextEntry` (or `_PySet_NextEntryRef`) looks sufficient.

**Comment by corona10** [comment]
```
test_compile leaked [2, 2, 2] references, sum=6
test_compile leaked [4, 4, 4] memory blocks, sum=12
```

Need to check.

**Comment by corona10** [comment]
test_compile: https://github.com/python/cpython/issues/118023
test_logging: https://github.com/python/cpython/pull/102412#issuecomment-2061174970

So not related to this PR.

**Review by colesbury — APPROVED** [review]

**Pull request merged**
