### PR TITLE
bpo-29728: Provide socket.TCP_NOTSENT_LOWAT

### PR DESCRIPTION
**Pull request by njsmith**
New TCP option available on recent MacOS and Linux.

### CODE REVIEW

**Comment by alex** [comment]
This should probably be documented in `socket.rst`

**Comment by Mariatta** [comment]
Please create a ticket in bugs.python.org to track this :)

**Comment by njsmith** [comment]
@Alex: good point, done.

@Mariatta: https://bugs.python.org/issue29728

**Comment by Mariatta** [comment]
@njsmith seems like there's trailing whitespace issue with the docs change :sweat_smile: 

Will you be able to fix it? (see travis output)

**Comment by Mariatta** [comment]
I think this should be added to Misc/NEWS too.

**Comment by njsmith** [comment]
@Mariatta: whoops, I somehow missed the notification on your earlier comments. Thanks for fixing things up!

**Comment by Mariatta** [comment]
Well... in my attempt to clean this however... I actually messed up your branch :sweat_smile: Sorry about this. I will try to clean it up later..

**Comment by njsmith** [comment]
Rebased and cleaned up

**Comment by njsmith** [comment]
no idea what that travis failure is about

**Comment by Mariatta** [comment]
Thanks @njsmith :)

I think the travis failure is a separate matter, tracked in https://github.com/python/core-workflow/issues/54

**Pull request merged**
