### PR TITLE
Changes to the documentation of normpath

### PR DESCRIPTION
**Pull request by kianasun**

### CODE REVIEW

**Review by mangrisano — APPROVED** [review]

**Comment by asvetlov** [comment]
We should add `Raise a TypeError if the type of path is not str or bytes...` to every module's function for consistency.
Not sure if this improves readability.

**Comment by kianasun** [comment]
Hi @asvetlov , thanks for your reply. Some other functions, such as `normcase` have this sentence in the document. I think we should add it to improve consistency and readability.

**Comment by willingc** [comment]
Hi @kianasun. I agree with @asvetlov. If you have the time, please update the PR as recommended by @asvetlov. Thanks :D

**Comment by kianasun** [comment]
@willingc I removed the sentence `Raise a TypeError if the type of path...` in `normcase` to be consistent.

**Comment by kianasun** [comment]
Hi @willingc, is there anything else that I need to change? Thanks :)

**Comment by matrixise** [comment]
Thank you for your pull request, I have started the merge process. Have a nice day.

**Pull request merged**
