### PR TITLE
Doc: Show object descriptions in the table of contents

### PR DESCRIPTION
**Pull request by AA-Turner**
Alternative to #125754, for discussion.

A

----
📚 Documentation preview 📚: https://cpython-previews--125757.org.readthedocs.build/

### CODE REVIEW

**Comment by willingc** [comment]
@AA-Turner I love it! Thank you for your Sphinx expertise. I'm going to close #125754 since this exceeds my expectations. :tada:

**Comment by willingc** [comment]
I've been going through this page by page and it's a definite enhancement on most pages. I would recommend checking out the os module and built-in types to see if offering the ability to collapse a level would make sense, or if there is another way, short of a righthand sidebar that would shorten those pages. It may be that some of those pages could be split.

**Review by willingc — APPROVED** [review]

**Comment by AA-Turner** [comment]
I'll merge this for now as it's had some support here and on [Discourse](https://discuss.python.org/t/68474/), but if it turns out to be too disruptive we can revert quite easily.

A

**Comment by hugovk** [comment]
> I'll merge this for now as it's had some support here and on [Discourse](https://discuss.python.org/t/68474/), but if it turns out to be too disruptive we can revert quite easily.
> 
> A

Unfortunately this has proved a bit too disruptive, I've opened https://github.com/python/cpython/pull/128406 to revert.

**Pull request merged**
