### PR TITLE
gh-112536: Add support for thread sanitizer (TSAN)

### PR DESCRIPTION
**Pull request by samety**
Adds `--with-thread-sanitizer` as a configure option and defines `_Py_THREAD_SANITIZER` when thread sanitizer is enabled.

* Issue: gh-112536

----
:books: Documentation preview :books:: https://cpython-previews--112648.org.readthedocs.build/

### CODE REVIEW

**Comment by colesbury** [comment]
@samety - this looks good. When you feel the PR is ready, please mark it as "ready for review"

**Comment by colesbury** [comment]
Oh, and I think this change should have a NEWS entry. (Use the "blurb" tool: https://pypi.org/project/blurb/)

**Review by colesbury — APPROVED** [review]
LGTM.

FYI, I updated the PR message.

**Comment by colesbury** [comment]
We'll want to make some changes after this. For example, I think we'll want to define `MI_TSAN` to `1` when `_Py_THREAD_SANITIZER` is defined. But those can be done in later PRs as we find and fix thread sanitizer issues.

**Comment by corona10** [comment]
Sorry for the delay, I will take a look at this PR by end of this week.

**Review by corona10 — APPROVED** [review]

**Pull request merged**
