### PR TITLE
bpo-40561: Provide docstrings for public-facing webbrowser functions

### PR DESCRIPTION
**Pull request by bsolomon1124**
Which are open, open_new, and open_new_tab.

https://bugs.python.org/issue40561

### CODE REVIEW

**Review by remilapeyre — APPROVED** [review]
Thanks for your contribution! 

I'm not sure the NEWS entry here thought.

**Comment by bsolomon1124** [comment]
cc @birkenfeld

**Review by terryjreedy — APPROVED** [review]
Approved with my edits.
@remilapeyre Thank you for the comment.  I agree and changed the news item.

@bsolomon1124 I removed the duplication from the open docstring (which you copied from the doc, which I undestand) and made it clearer that autoraise may be ignored either way (which the doc seems to say.  I will wait at least a day for you to comment before merging.

**Comment by bsolomon1124** [comment]
Thanks for giving this your attention @terryjreedy. Your changes are good by me.

**Pull request merged**
