### PR TITLE
bpo-31787: Prevent refleaks when calling __init__() more than once

### PR DESCRIPTION
**Pull request by orenmn**
https://bugs.python.org/issue31787

### CODE REVIEW

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
Please add some tests that exercise doubled calls to `__init__` (showing refleaks before the patch and not showing refleaks after the patch).

**Review by methane — APPROVED** [review]
Would you merge master again?

**Comment by orenmn** [comment]
I merged with master on my Windows 10, and now `test_asyncio` fails.
I am sorry, but i am too busy these days, and don't have time to work on this.

So it would be great if you took it from here...

**Comment by methane** [comment]
Hm, it seems calling `Task.__init__()` is not allowed.
I'll revert test and fix for asyncio.

**Pull request merged**
