### PR TITLE
GH-104787: use managed dict in `_asyncio`

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-104787

### CODE REVIEW

**Review by PixelCode01 — APPROVED** [review]

**Comment by gvanrossum** [comment]
From reading the 3.12 docs this seems to be primarily meant as a "better" way to support `__dict__` , letting the standard object infrastructure manage the dict instead of managing it "by hand". (The dict is still present, so it doesn't really save memory, but there's a potential for future optimizations once a type adopts this.)

@kumaraditya303 Shouldn't we do this for weakrefs too? There's a corresponding `Py_TPFLAGS_MANAGED_WEAKREF` flag.

**Comment by kumaraditya303** [comment]
> From reading the 3.12 docs this seems to be primarily meant as a "better" way to support __dict__ , letting the standard object infrastructure manage the dict instead of managing it "by hand". (The dict is still present, so it doesn't really save memory, but there's a potential for future optimizations once a type adopts this.)

See https://github.com/python/cpython/issues/95707, it does save memory as the dict isn't really allocated, the values pointer is used directly so it saves memory. 

> Shouldn't we do this for weakrefs too? There's a corresponding Py_TPFLAGS_MANAGED_WEAKREF flag. 

Haven't thought about using that yet, will check it in another PR for now.

**Comment by gvanrossum** [comment]
I see. I've forgotten how this works, I've added a ping asking for more documentation.

**Comment by kumaraditya303** [comment]
> I see. I've forgotten how this works, I've added a ping asking for more documentation.

Ok, I'll merge this now.

**Pull request merged**
