### PR TITLE
Test reviewdog/action-suggester

### PR DESCRIPTION
**Pull request by tiran**

### CODE REVIEW

**Comment by tiran** [comment]
The action cannot create suggestions, yet. Our GH token does not include write access to review API:

```
reviewdog: This GitHub token doesn't have write permission of Review API [1], 
so reviewdog will report results via logging command [2] and create annotations similar to
github-pr-check reporter as a fallback.
[1]: docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
[2]: help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands

**Comment by arhadthedev** [comment]
As far as I know GitHub once didn't allow to leave suggestions on untouched lines:

> https://github.com/getsentry/action-git-diff-suggestions
>
> This doesn't work as intended as you can not leave a review comment on lines that are not modified in the PR. Due to this limitation, this action can potentionally have undesired results.
>
> *This repository has been archived by the owner. It is now read-only.*

However, looking at this screenshots in readme of action-suggester I suspect this limitation was fixed:

> 

That's curious considering I haven't seen any related announcement on https://github.blog.

**Comment by arhadthedev** [comment]
> Our GH token does not include write access to review API

You can try to clone cpython into your profile and enable actions there.

**Comment by tiran** [comment]
action suggester is useless for our use case. It cannot add comments to files unless the file has been modified in the same PR.

**Comment by arhadthedev** [comment]
For interlinking purposes: this PR is superseded with GH-30117.

**Pull request closed without merging**
