### PR TITLE
bpo-25359: Add missed "goto error" after setting an exception.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue25359

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
Can you try to write an unit test? Something like:

```
import io
import _bootlocale

def getpreferredencoding(do_setlocale=True):
    return 1
_bootlocale.getpreferredencoding = getpreferredencoding

# current raises:
# TypeError: bad argument type for built-in operation
with open(__file__, encoding=None) as fp:
    pass
```

**Comment by serhiy-storchaka** [comment]
Originally I have wrote this test, but it looks too implementation depending and fragile. See https://bugs.python.org/issue31565.

TypeError is raised by patched and unpatched code. Testing exact error message makes the test yet more implementation specific. Python implementation raises ValueError.

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
Ok, fine, your answer makes sense ;-)

**Pull request merged**
