### PR TITLE
bpo-36783: Added C API Documentation for Time_FromTimeAndFold and PyDateTime_FromDateAndTimeAndFold

### PR DESCRIPTION
**Pull request by edison12a**
https://bugs.python.org/issue36783

### CODE REVIEW

**Comment by SimiCode** [comment]
@pganssle @Mariatta 
I have added the requested documentation. Please review.

**Comment by pganssle** [comment]
This can be backported to at least 3.7.

**Review by csabella — APPROVED** [review]
LGTM.

**Comment by SidhdhARTH** [comment]
Thanks for the update.

**Pull request merged**
