### PR TITLE
bpo-41817: use new StrEnum to ensure all members are strings

### PR DESCRIPTION
**Pull request by ethanfurman**
https://bugs.python.org/issue41817

### CODE REVIEW

**Comment by ethanfurman** [comment]
Terry, if the default for stdlib `__str__` for stdlib enums changes to `module.enum_member_name` are you okay with changing the custome `__str__` you are using for the `EventType` enum at the moment?

**Comment by serhiy-storchaka** [comment]
I think it would be better to restore the default `__str__`: `__str__ = str.__str__` (it looks not safe to change `__str__` of `str` subclass) and change `self.type` in `Event.__repr__()` to `getattr(self.type, 'name', self.type)`.

**Comment by terryjreedy** [comment]
Serhiy is indeed the one to answer the question as he is the tkinter maintainer.  As a user, my concern is with breaking existing code and the possible uses of str().  EventTypes are used for the event.type attributes of events passed to event handlers.   If a handler can be triggered by more that one type of event and the handler cares which, one condition would be `event.type == EventType.sometype`, for which the string representations matter not.  (I would probably define `Ev = tk.EventType if doing much of this.)

Conditions like `str(event.type) == 'KeyPress'` would break, and I don't consider their existence to be out of the question, as we use strings to bind the event.  Before this issue, I might have done this.  The NMT tkinter reference does not mention `EventType`.   For output to a user, the module prefix might be noisy.

**Comment by ethanfurman** [comment]
Terry, fair enough.

Serhiy, there are no issues with a custom `__str__` on an `Enum` class, even when it is subclassing `str`.  The question is whether we want `str(EventType.KeyPress)` to be `"KeyPress"` or `"2"`.

**Comment by serhiy-storchaka** [comment]
I am also the one who introduced `EventType`. And I now think that maybe making `__str__` returning a name instead of value was mistake. The main reason of defining `__str__` was to use it in `Event.__repr__()`.

But this is a different issue (I am working on it, the hard part is writing tests). This issue is about trailing commas which convert values into tuples. Thank you Ethan for catching this! Let to fix it.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Would be nice to add a NEWS entry. This was a serious bug.

**Comment by ethanfurman** [comment]
Adding news entry.

**Comment by terryjreedy** [comment]
I cannot think of any use for the arbitrary numbers, whether string or int, added by tkinter to the tk strings.

**Comment by ethanfurman** [comment]
Serhiy, thank you for the explanation on Python-Dev about `str()` vs `__str__`.  I'm fixing `StrEnum` now to use `str.__str__`.

**Pull request merged**
