### PR TITLE
gh-100174: [Enum] Correct PowersOfThree example.

### PR DESCRIPTION
**Pull request by Beweeted**
Changed from multiples of 3 to powers of 3 to match the class name.

* Issue: gh-100174

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Thanks! Unfortunately, nearly all Python PRs are made against the `main` branch, and then backported to maintenance branches after they've been merged. The best thing to do is to recreate the PR based against `main`.

**Comment by Beweeted** [comment]
This is against `main`. I'm sure I missed something, but I couldn't find the button to make a new branch from the docs. I hit `edit` on the file, and it auto-forked it and gave me the option to merge it back in.

If you can point me in the right direction @AlexWaygood I'm happy to do the extra steps. Unless those steps are to sync & build the whole repo on my local, which is what the cpython docs were telling me to do.

Really, the most confusing thing is talking about backporting. Which I don't understand how that's applicable to this at all.

**Comment by AlexWaygood** [comment]
> This is against `main`. I'm sure I missed something, but I couldn't find the button to make a new branch from the docs. I hit `edit` on the file, and it auto-forked it and gave me the option to merge it back in.
> 
> If you can point me in the right direction @AlexWaygood I'm happy to do the extra steps. Unless those steps are to sync & build the whole repo on my local, which is what the cpython docs were telling me to do.
> 
> Really, the most confusing thing is talking about backporting. Which I don't understand how that's applicable to this at all.

Apologies! Your PR title confused me. We usually use the `[3.11]` tag for PRs that are against the 3.11 branch

**Comment by AlexWaygood** [comment]
We will need you to sign the CLA, however :)

**Comment by Beweeted** [comment]
Oh, oh oh. That makes sense. I had been seeing the other PRs and most seemed to have the version in the name. It wasn't mentioned in the comment, but I thought I was being a keener. I'll keep this in mind next time!

**Review by ethanfurman — APPROVED** [review]
Looks good!  As soon as you sign the CLA we can merge this in.

**Pull request merged**
