### PR TITLE
bpo-40859: Update Windows build to use xz-5.2.5

### PR DESCRIPTION
**Pull request by ghost**
https://bugs.python.org/issue40859

### CODE REVIEW

**Comment by zooba** [comment]
I'll get the sources pushed to the repo we use later tonight. (Can't seem to mark this as unread, so mention me again if it seems like I've forgotten.)

**Comment by zooba** [comment]
The xz sources are up now, and I copied the config.h into the right place, so all should be fine.

**Comment by animalize** [comment]
> The xz sources are up now, and I copied the config.h into the right place, so all should be fine.

I updated project configure files, it works if don't copy `config.h` manually.

**Comment by zooba** [comment]
The change for include directory isn't any worse than what we had before, but we might want to make it conditional on VS version if it starts breaking for people using earlier/later releases (though I don't see why there'd be differences between the files)

**Comment by animalize** [comment]
I compared, the contents of these 3 files are same, except the comment at the first line.  
- vs2013/config.h
- vs2017/config.h
- vs2019/config.h

Earlier version MSVC can also use `vs2019/config.h`.

**Pull request merged**
