### PR TITLE
Align .suffixes example with .suffix example in pathlib doc

### PR DESCRIPTION
**Pull request by hoffmann**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@hoffmann

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by taleinat** [comment]
> Can you say more? I don’t understand the change being proposed.

"Align" seems to mean making this consistent with the examples given above for `.suffix`.

This does seems like an improvement to me, because:
* ".tar.gar" is unusual and a bit confusing.
* Having an example with a single extension (the most common case) seems useful.
* It parallels the examples for the similar `.suffix`, and so clearly highlights the differences.

**Comment by taleinat** [comment]
(Oops! I changed the base branch from 3.10 to main, and this requested a review from about half of the maintainers... sorry for the noise!)

**Comment by taleinat** [comment]
@hoffmann, I'm inclined to merge this PR, and for such a minor docs change we can forgo signing the CLA.

However, could you rebase this against the main branch, and then change the PR to be against the main branch, rather than 3.10?

**Comment by terryjreedy** [comment]
The title puzzled me also until I read Tal's explanation; I changed it accordingly.  I agree that this is an improvement, though trivial enough to forego CLA for this PR.  It might be easier to close this and start over with a checkout branched from 'main'.

@Peter: 'main' is our development branch and we nearly always patch it first and backport if appropriate.

**Comment by brettcannon** [comment]
Ignoring the CLA issue, is there a reason this is targeting Python 3.10 and not `main`?

**Comment by terryjreedy** [comment]
Targeting 3.10 is an error, which I why I suggested closing and starting over (versus trying to fix by rebasing), as retargeting this one failed.

**Comment by brettcannon** [comment]
I am closing this as the CLA is still not signed.

**Pull request closed without merging**
