### PR TITLE
bpo-23937: IDLE maximise on load

### PR DESCRIPTION
**Pull request by E-Paine**
https://bugs.python.org/issue23937

### CODE REVIEW

**Comment by terryjreedy** [comment]
@Mariatta The knight failed to add CLA labels.  It initially said unsigned, now your check app says signed.

**Comment by E-Paine** [comment]
> @Mariatta The knight failed to add CLA labels. It initially said unsigned, now your check app says signed.

That would be my fault, as my CLA was still pending when I created this request.

**Comment by terryjreedy** [comment]
That is OK.  The problem is that there was and is no CLA label under labels, on the right.

I am surprised at the zoom issue.  I want to check the tk docs.  I can write a small tkinter program on my Macbook to see what works there.

**Comment by terryjreedy** [comment]
@vstinner  The issue is still open and this PR was still a work in progress.  Was closing an accidental side effect of switching to main not working right?  How do we reopen?

**Comment by vstinner** [comment]
> In any case, Paine already recreated this as PR 25946, as indicated above, and we can move forward.

Cool ;-)

**Pull request closed without merging**
