### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Harry-Lees**
Fixed possible typo in comment

Automerge-Triggered-By: GH:Mariatta

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Harry-Lees

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by Mariatta — APPROVED** [review]
Thanks

**Comment by pganssle** [comment]
I think this is not a typo, or if it is this is not the right solution. There is no method or calls called `datetime.timetz`.

**Comment by pganssle** [comment]
Oh wait, ignore that. Wrong on both counts, apparently.

**Comment by Mariatta** [comment]
So, is this ready to merge, or do you want to do it @pganssle ? I added backport labels.

**Pull request merged**
