### PR TITLE
bpo-46252: Prevent _SelectorSocketTransport from closing on SSLWantRe…

### PR DESCRIPTION
**Pull request by matan1008**
https://bugs.python.org/issue46252

### CODE REVIEW

**Review by asvetlov — CHANGES_REQUESTED** [review]
I think `self._sock.recv()` can never throw `ssl.SSLWant*` exception.
The `self._sock` is a plain TCP socket always, `ssl.SSLSocket` and `ctx.wrap_socket()` are never used by asyncio.
SSL encoding/decoding is done in-memory by [BIO](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_bio), see `sslproto.py`.

**Comment by matan1008** [comment]
> I think `self._sock.recv()` can never throw `ssl.SSLWant*` exception. The `self._sock` is a plain TCP socket always, `ssl.SSLSocket` and `ctx.wrap_socket()` are never used by asyncio. SSL encoding/decoding is done in-memory by [BIO](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_bio), see `sslproto.py`.

I am facing this issue when calling to `asyncio.open_connection` with `sock` argument set to a `SSLSocket` object.
From your comment I assume that I might be using open_connection in a wrong way. If that is the case, how can `StreamReader` and `StreamWriter` can be created with an existing `SSLSocket`?

**Comment by matan1008** [comment]
I found out it happens both in writing and reading data, so I think that now it is handled better - I have made the requested changes; please review again

**Comment by asvetlov** [comment]
Using SSLSocket is forbidden in asyncio, sorry.
Because SSLSocket cannot be switched into non-blocking mode, it is always blocking by design.

The only thing that asyncio can do is raise a `TypeError` fast if `SSLSocket` is passed.

Actually, it has this check already for `sock_*` operations but not for `create_connection()` / `create_server()`.

**Comment by matan1008** [comment]
Thanks you for your response!
I am probably missing something but from the `SSLSocket` documentation is seems that there is a `setblocking()` method, and the discussed changes solved the issues (at least in my case), so I would really appreciate if you could explain some more about why it is forbidden.
More specific question if I may - In my case I am implementing one of lockdown's services protocol (see [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) )  and the protocol requires creating a socket, exchanging some messages, establishing SSL connection over the same socket, and after that doing some asynchronous logic - if using `asyncio` is not the solution, how can it be done in python?

**Comment by asvetlov** [comment]
Sorry, [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) discussion is out of the project scope. Try to ask there.

**Pull request closed without merging**
