### PR TITLE
bpo-36974: document PEP 590

### PR DESCRIPTION
**Pull request by jdemeyer**
**Work in progress**

CC @encukou @markshannon 

https://bugs.python.org/issue36974

### CODE REVIEW

**Comment by encukou** [comment]
I'll work on updating the docs today.
@jdemeyer I'll push changes your branch directly, if you don't mind.

**Comment by encukou** [comment]
Rebased & updated

**Comment by jdemeyer** [comment]
In `Doc/c-api/structures.rst`, I planned to give a high-level explanation of the vectorcall protocol (basically a short version of PEP 590). Right now this is not really explained. That's why I defined `vectorcallfunc` there.

Do you still think that this is a good idea?

**Comment by encukou** [comment]
I don't think `c-api/structures` is a good place, since vectorcall is not a structure.
But perhaps a new chapter on calling under "Abstract Objects Layer" would make sense – calling takes up half of `c-api/object` already.

**Pull request merged**
