### PR TITLE
gh-119132: Log sys._is_gil_disabled() in test.pythoninfo

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-119132

### CODE REVIEW

**Comment by vstinner** [comment]
cc @corona10

**Review by corona10 — APPROVED** [review]
lgtm!

**Review by erlend-aasland — APPROVED** [review]

**Comment by vstinner** [comment]
Example on "Tests / Windows (free-threading) / build and test (x64) (pull_request)":

```
sys._is_gil_enabled: False
```

It works as expected.

**Comment by vstinner** [comment]
Merged, thanks for reviews.

**Pull request merged**
