### PR TITLE
[3.6] bpo-31340: Change to building with MSVC v141 (included with Visual Studio 2017) (GH-3311)

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue31340

### CODE REVIEW

**Comment by emmatyping** [comment]
~~Im concerned about this change, as VS 2015 cannot build v141 binaries. I know v141 is binary compatible with v140, but shouldn't the VS version that builds Python stay consistent in a minor release? Or at least, shouldn't this be discussed more before this change is made? It requires the user to update VS which is a non-trivial change.~~

Ah, I see this seems to support both. Great!

**Comment by zooba** [comment]
@ethanhs It shouldn't require any update for existing users - VS 2015 can be used to build v140 binaries which are compatible with v141. This is why I explicitly enabled both versions of VS in AppVeyor.

**Comment by zooba** [comment]
But I did briefly forget about Tcl/Tk not supporting VS 2017 builds... guess we can't backport this change after all.

**Comment by emmatyping** [comment]
@zooba thanks, "Change to building with MSVC v141" sounds like "replace v140 with v141" so I was concerned. Too bad this cannot be backported :(

**Comment by zooba** [comment]
Trying again - I merged the fix for Tcl/Tk into master and merged it into this branch, so we should have success now.

**Pull request merged**
