### PR TITLE
bpo-33816: Remove outdated metaclass example

### PR DESCRIPTION
**Pull request by andresdelfino**
https://bugs.python.org/issue33816

### CODE REVIEW

**Comment by ncoghlan** [comment]
Perhaps it would make sense to keep the example, but caveat it as being redundant given the move to class namespaces being ordered by default?

**Review by ncoghlan — APPROVED** [review]
Outright removal is better than keeping the misleading example, so approving as is. However, see my comment above about potentially qualifying the example as no longer being necessary, rather than removing it entirely.

**Comment by andresdelfino** [comment]
> Perhaps it would make sense to keep the example, but caveat it as being redundant given the move to class namespaces being ordered by default?

The thing is that the example also depends on the fact that OrderedDict was the only way to get an insertion-order-preserving dictionary. I think examples of the like "that thing can be implemented with this API like this:" are good, but this particular example depends on several things that have changed.

IMHO, a new example that shows a real benefit from metaclasses would be better.

**Comment by methane** [comment]
I think we must not waiting removing bad document until someone writing better document
when we don't know when the better document is finished.

Additionally, metaclass is very complex feature.  I don't want to promote using it.
Actually, Python is evolved to solve typical problem without metaclass: `__init_subclass__`, `__class_getitem__`, and PEP 520.  (Maybe more)

Lack of "typical usecase" is OK.  Lack of "example of typical usecase" is OK too.
People can read stdlib's code to know how metaclass is used.

**Pull request merged**
