### PR TITLE
gh-86404: Doc: Drop now unused make suspicious and rstlint.

### LINKED ISSUE #86404: Deprecate suspicious.py?
BPO | [42238](https://bugs.python.org/issue42238)
--- | :---
Nosy | @birkenfeld, @rhettinger, @ned-deily, @ambv, @willingc, @JulienPalard, @pablogsal, @erlend-aasland, @AlexWaygood
PRs | <li>python/cpython#23313</li><li>python/cpython#23802</li><li>python/cpython#26575</li><li>python/cpython#26966</li><li>python/cpython#27238</li><li>python/cpython#27945</li><li>python/cpython#28137</li><li>python/cpython#28827</li><li>python/cpython#29636</li><li>python/cpython#29652</li><li>python/cpython#30879</li><li>python/cpython#30981</li><li>python/cpython#31097</li><li>python/cpython#31977</li><li>python/cpython#32070</li><li>python/cpython#32292</li><li>python/cpython#32329</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/JulienPalard'
closed_at = None
created_at = <Date 2020-11-01.23:49:23.937>
labels = ['docs']
title = 'Deprecate suspicious.py?'
updated_at = <Date 2022-04-06.11:53:50.624>
user = 'https://github.com/JulienPalard'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-06.11:53:50.624>
actor = 'mdk'
assignee = 'mdk'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-11-01.23:49:23.937>
creator = 'mdk'
dependencies = []
files = []
hgrepos = []
issue_num = 42238
keywords = ['patch']
message_count = 56.0
messages = ['380167', '380169', '380171', '381075', '381802', '382219', '383149', '383171', '383292', '390898', '390904', '391163', '391164', '391177', '391182', '391185', '391209', '391212', '392165', '392177', '395311', '396567', '396568', '396774', '396891', '397792', '397802', '400259', '400324', '401123', '403523', '404067', '406575', '406604', '406654', '406810', '406978', '408724', '411565', '411571', '411636', '411642', '411983', '412135', '412136', '412355', '412377', '412382', '412403', '412980', '414984', '415860', '416639', '416643', '416759', '416861']
nosy_count = 9.0
nosy_names = ['georg.brandl', 'rhettinger', 'ned.deily', 'lukasz.langa', 'willingc', 'mdk', 'pablogsal', 'erlendaasland', 'AlexWaygood']
pr_nums = ['23313', '23802', '26575', '26966', '27238', '27945', '28137', '28827', '29636', '29652', '30879', '30981', '31097', '31977', '32070', '32292', '32329']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42238'
versions = []
```

</p></details>

### PR DESCRIPTION
**Pull request by JulienPalard**
They have been replaced by
[sphinx-lint](https://github.com/sphinx-contrib/sphinx-lint).

closes gh-86404.

### CODE REVIEW

**Review by ezio-melotti — COMMENTED** [review]
LGTM.
Does this need an entry in the 3.12 whatsnew?

**Review by vstinner — APPROVED** [review]
LGTM. sphinx-lint is a great success!

It's good that ``Doc/tools/susp-ignored.csv`` can be removed. It can be removed because sphinx-lint has less false positives, right?

**Comment by vstinner** [comment]
It seems like ``make suspicious`` is no longer used by Python releases: good.

* I cannot find ``suspicious`` in https://github.com/python/release-tools/
* I cannot find ``suspicious`` in https://peps.python.org/pep-0101/ neither

cc @pablogsal @yhg1s

---

sphinx-lint is run by the "Docs / Docs" CI job on this PR: "Check documentation" step:

```
PATH=./venv/bin:$PATH sphinx-lint --enable default-role ../Misc/NEWS.d/next/
```

In short, sphinx-lint is now run on all documentation changes, not only late during releases. Issues are catched earlier: good!

**Comment by JulienPalard** [comment]
> Does this need an entry in the 3.12 whatsnew?

I don't think so as it's not a new thing, it's an old thing being cleared (it was a tool to help migration from LaTeX documentation to Sphinx documentation, so its removal is long overdue).

It's been one year that the CI no longer uses `make suspicious`, I bet everybody just forgot about it existence. And the few humans running `make suspicious` manually are getting a deprecated message since November 2021.

**Comment by JulienPalard** [comment]
> It's good that `Doc/tools/susp-ignored.csv` can be removed. It can be removed because sphinx-lint has less false positives, right?

`sphinx-lint` has 0 false positives on a growing list of watched repositories, as of today:

```
https://github.com/jazzband/django-oauth-toolkit
https://github.com/neo4j/neo4j-python-driver
https://github.com/pandas-dev/pandas
https://github.com/python/peps
https://github.com/python/cpython
https://github.com/python/devguide/
https://github.com/spyder-ide/spyder-docs
https://github.com/sympy/sympy
https://github.com/sphinx-doc/sphinx
```

This list of repositories are automatically checked by sphinx-lint CI to "guarantee" no false positive are introduced as release time, like it happened a few days ago with the "default-role debacle" (which happened because this checker is not enabled by default, to it went under the radar, it's fixed now, we test each repos with their real set of checkers).

The goal is to stick to 0 false positive (aiming at the impossible... because why not).

**Comment by ezio-melotti** [comment]
> I don't think so as it's not a new thing, it's an old thing being cleared (it was a tool to help migration from LaTeX documentation to Sphinx documentation, so its removal is long overdue).

The whatsnew also has a section for deprecated/removed APIs/modules/tools.

See for example 
https://github.com/python/cpython/blob/e0ae9ddffe0a708d0d3f5b8cc10488d466fc43c4/Doc/whatsnew/3.12.rst?plain=1#L212-L223

**Comment by JulienPalard** [comment]
> The whatsnew also has a section for deprecated/removed APIs/modules/tools.

OK, so, why not :)

**Comment by JulienPalard** [comment]
> The whatsnew also has a section for deprecated/removed APIs/modules/tools.

Done.

**Review by ezio-melotti — APPROVED** [review]
Thanks!

**Review by AA-Turner — APPROVED** [review]
Thanks @JulienPalard!

A

**Comment by AlexWaygood** [comment]
@JulienPalard, looks like the 3.11 and 3.10 branches still run `make suspicious` -- should this PR be backported?

**Comment by ezio-melotti** [comment]
3.11 isn't running it anymore, since it got removed here:
* #26575

3.10 however is still running it.  If this is a problem we could just switch to `sphinx-lint` in 3.10 too, but the removal of `make suspicious` and `rstlint.py` shouldn't be backported.

**Comment by AlexWaygood** [comment]
> 3.11 isn't running it anymore, since it got removed here:
> 
> * [bpo-42238: Doc CI: Disable suspicious checks. #26575](https://github.com/python/cpython/pull/26575)
> 
> 3.10 however is still running it. If this is a problem we could just switch to `sphinx-lint` in 3.10 too, but the removal of `make suspicious` and `rstlint.py` shouldn't be backported.

Thanks, that makes sense! I thought I'd seen some false positives recently on some backports — they must have been on some backports to 3.10.

Agreed that backports should also be as minimal as possible!

**Comment by JulienPalard** [comment]
I propose just disabling `make suspicious` in 3.10 in https://github.com/python/cpython/pull/98221.

I don't feel the need to add sphinx-lint there: the PR will come from main, where they have already been checked, and as victor says, better not touch those stable branches too much (I mean let's remove pain, not add some).

**Pull request merged**
