### PR TITLE
Docs: PyUnstable_Long_IsCompact() docs now mention PyLong_AsNativeBytes()

### PR DESCRIPTION
**Pull request by skirpichev**
----
📚 Documentation preview 📚: https://cpython-previews--116634.org.readthedocs.build/

### CODE REVIEW

**Comment by skirpichev** [comment]
Probably could skip news.

**Review by erlend-aasland — APPROVED** [review]
cc. @zooba

**Comment by zooba** [comment]
LGTM

**Comment by erlend-aasland** [comment]
Thanks, Sergey.

**Pull request merged**
