### PR TITLE
gh-86650: get_obs_local_part() fails to handle empty local part

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue42484

* Issue: gh-86650

### CODE REVIEW

**Comment by spacefreak86** [comment]
What exactly is missing for this PR to get applied? It would be great because this bug is affecting my productive system and I have to monkey-patch the email library by myself.

**Review by MaxwellDupre — APPROVED** [review]
Ran 1654 tests in 6.561s
OK (skipped=1)
Looks ok.

**Comment by lesleyxyz** [comment]
I am getting this bug in a production environment.
It seems emails from the sender `azuredevops@microsoft.com` have a message id starting with `<[`

How is this PR not yet reviewed after- all this time? How can we notify the right people to review this?

**Comment by arhadthedev** [comment]
@python/email-team

**Comment by mdavranche** [comment]
Same here, got this on my production environment, preventing me to upgrade from Python 3.7.3 (bug not present) to a more recent version (bug confirmed in 3.8, 3.9, 3.10, 3.11).

Easy to trigger:
```
import email.parser
import email.policy
faulty_header = "Message-ID: <[9f83415a58f84675bac8ab3e6047a157-JFBVALKQOJXWILKCJQZFA7CJIFGVGU2QKJ6FGU2QKJCW2YLJNR6EK6DPKNWXI4A=@example.com]>"
message = email.parser.BytesParser(policy=email.policy.default).parsebytes(faulty_header.encode("utf-8"))
message.as_bytes()
```

**Comment by lesleyxyz** [comment]
Is there an ETA for this please?

**Comment by fsc-eriker** [comment]
I have a competing PR which does not simply silently ignore the problem, but instead raises a defect. My proposed implementation returns a partial message-id which is perhaps less than ideal.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution, @ZackerySpytz, but I think that it is not a correct solution. Invalid Message-ID should not be silently truncated. The parsing code should raise HeaderParseError, this will allow to preserve its literal value. See #117934.

**Pull request closed without merging**
