### PR TITLE
gh-108303: Move all `pydoc` related files to `test_pydoc`

### PR DESCRIPTION
**Pull request by sobolevn**
I hope that this will be one of the latest commits to this issue! 🎉 
There are only a couple of things left to do. Most files were cleaned up.

The change itself is rather simple.

* Issue: gh-108303

### CODE REVIEW

**Comment by sobolevn** [comment]
Very strange, why windows build fails. I will investigate.

**Comment by vstinner** [comment]
> Very strange, why windows build fails. I will investigate.

Tell me if you need help to investigate.

**Comment by vstinner** [comment]
test_pydoc is failing!

**Comment by sobolevn** [comment]
yes, this is expected. I am still debugging :(
No idea what's wrong.

**Comment by vstinner** [comment]
> No idea what's wrong.

Try: `git mv Lib/test/pydoc_mod.py Lib/test/test_pydoc/`. Does it help?

**Comment by vstinner** [comment]
Also, there are now merge conflicts.

**Comment by sobolevn** [comment]
> Try: git mv Lib/test/pydoc_mod.py Lib/test/test_pydoc/. Does it help?

No, that's not the case :)

I am trying to debug the initial Windows failure: 

```
 ======================================================================
FAIL: test_text_doc (test.test_pydoc.test_pydoc.PydocDocTest.test_text_doc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_pydoc\test_pydoc.py", line 435, in test_text_doc
    self.assertEqual(expected_text, result)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "NAME[76 chars]DULE DOCS\n    https://docs.python.org/3.13/li[2235 chars]d.py" != "NAME[76 chars]DULE REFERENCE\n    https://docs.python.org/3.[2567 chars]d.py"
  NAME
      test.test_pydoc.pydoc_mod - This is a test module for test_pydoc
  
- MODULE DOCS
+ MODULE REFERENCE
      https://docs.python.org/3.13/library/test.test_pydoc.pydoc_mod.html
+ 
+     The following documentation is automatically generated from the Python
+     source files.  It may be incomplete, incorrect or include features that
+     are considered implementation detail and may vary between Python
+     implementations.  When in doubt, consult the module reference at the
+     location listed above.
  
```

The problem is that I cannot reproduce it locally on my macos.

**Comment by vstinner** [comment]
You should update pydoc as well:

```diff
diff --git a/Lib/pydoc.py b/Lib/pydoc.py
index 17f7346e5c..6d145abda9 100755
--- a/Lib/pydoc.py
+++ b/Lib/pydoc.py
@@ -552,7 +552,7 @@ def getdocloc(self, object, basedir=sysconfig.get_path('stdlib')):
                                  '_thread', 'zipimport') or
              (file.startswith(basedir) and
               not file.startswith(os.path.join(basedir, 'site-packages')))) and
-            object.__name__ not in ('xml.etree', 'test.pydoc_mod')):
+            object.__name__ not in ('xml.etree', 'test.test_pydoc.pydoc_mod')):
             if docloc.startswith(("http://", "https://")):
                 docloc = "{}/{}.html".format(docloc.rstrip("/"), object.__name__.lower())
             else:

```

**Comment by sobolevn** [comment]
@vstinner thanks a lot, you suggestions worked!
Not gonna lie, I still not fully understand the difference between macos / linux / win builds, but since all CI is green now, I think that it is fine :)

**Comment by vstinner** [comment]
Merged. I just edited the commit message. Oh, sorry, I forgot that you can now merge changes by yourself! Oops.

Well, sadly, automated backports fail as usual. Can you try to backport them manually?

**Pull request merged**
