### PR TITLE
bpo-16024: Doc cleanup regarding path_fd, dir_fd, follow_symlinks

### PR DESCRIPTION
**Pull request by csabella**
Patch by Larry Hastings.

https://bugs.python.org/issue16024

### CODE REVIEW

**Review by BoboTiG — APPROVED** [review]
Thank you! It seems good to me :)

**Comment by larryhastings** [comment]
I'm about to leave a quick review, but first I just wanted to say--thanks, Cheryl, for resurrecting this old patch!  I always meant to dig it up myself but never got around to it.

**Review by larryhastings — COMMENTED** [review]
My one bit of feedback, after looking over this patch with fresh eyes: do you like the "For POSIX systems, Python will call the f... variant of the function" text?  I was thinking it was a little abstruse.

Is this any better? "For POSIX systems, Python will call the variant of the function prefixed with f (e.g. call fchdir instead of chdir)."

**Comment by csabella** [comment]
@larryhastings Thanks!  I agree that your new suggestion for the functions prefixed with an f is clearer than the original, so I've made a commit with that change.

**Pull request merged**
