### PR TITLE
gh-107603: AC only includes pycore_gc.h if needed

### PR DESCRIPTION
**Pull request by vstinner**
Argument Clinic now only includes pycore_gc.h if PyGC_Head is needed, and only includes pycore_runtime.h if _Py_ID() is needed.

Add Py_ARGUMENT_CLINIC_AVOID_INTERNAL_CAPI macro to opt-out for the internal C API in Argument Clinic.

The following extensions avoids the internal C API by defining the macro Py_ARGUMENT_CLINIC_AVOID_INTERNAL_CAPI:

* Modules/_csv.c
* Modules/_multiprocessing/posixshmem.c
* Modules/_testcapi/exceptions.c
* Modules/grpmodule.c
* Modules/syslogmodule.c

* Issue: gh-107603

### CODE REVIEW

**Comment by vstinner** [comment]
> The following extensions avoids the internal C API by defining the macro Py_ARGUMENT_CLINIC_AVOID_INTERNAL_CAPI:
>    Modules/_csv.c
>    Modules/_multiprocessing/posixshmem.c
>    Modules/_testcapi/exceptions.c
>    Modules/grpmodule.c
>    Modules/syslogmodule.c

If we convert these modules to the limited C API, see issue #85283, the Py_ARGUMENT_CLINIC_AVOID_INTERNAL_CAPI macro can be removed (from AC and from these modules).

**Comment by vstinner** [comment]
Oh, global objects are outdated in the main branch, see PR #108714.

**Comment by vstinner** [comment]
This approach doesn't work. I abandon this PR in favor of PR #108726 which is implemented differently.

**Comment by gvanrossum** [comment]
Victor, next time can you use a draft PR for such experiments so 17 core devs aren't bombarded with review requests and internal monologue?

**Comment by vstinner** [comment]
> Victor, next time can you use a draft PR for such experiments so 17 core devs aren't bombarded with review requests and internal monologue?

If I create a PR as draft, no notification is sent?

Well, I expected this PR to be ready, but then I saw that tests failed on Windows. I wrote a new PR from scratch with a different approach to avoid this.

I'm not sure why so many developers are requested for reviews, the vast majority of modified files are generated files (``*/clinic/*.h`` files generated by Argument Clinic).

**Comment by AlexWaygood** [comment]
> If I create a PR as draft, no notification is sent?

yes, code owners are only requested for review when you take it out of draft mode

> I'm not sure why so many developers are requested for reviews, the vast majority of modified files are generated files (`*/clinic/*.h` files generated by Argument Clinic).

I don't think the GitHub CODEOWNERS feature takes any notice of whether files are generated or not when figuring out whether people should be pinged for review -- it just looks at whether the modified files match any of the globs provided in https://github.com/python/cpython/blob/main/.github/CODEOWNERS

**Pull request closed without merging**
