### PR TITLE
Revert "gh-112301: Enable warning emitting options and ignore warnings in CI (#123020)"

### LINKED ISSUE #124064: Lots of new compiler warnings
```
In file included from ./Include/internal/pycore_global_objects.h:12:
./Include/internal/pycore_gc.h:230:21: warning: implicit conversion changes signedness: 'int' to 'uintptr_t' (aka 'unsigned long') [-Wsign-conversion]
    gc->_gc_prev &= ~_PyGC_PREV_MASK_FINALIZED;
                 ~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
In file included from ./Include/internal/pycore_code.h:13:
./Include/internal/pycore_backoff.h:78:66: warning: implicit conversion loses integer precision: 'int' to 'uint16_t' (aka 'unsigned short') [-Wimplicit-int-conversion]
        return make_backoff_counter((1 << (counter.backoff + 1)) - 1, counter.backoff + 1);
               ~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

```
In file included from ./Include/internal/pycore_mimalloc.h:45:
./Include/internal/mimalloc/mimalloc/internal.h:489:84: warning: implicit conversion changes signedness: 'int' to 'mi_thread_free_t' (aka 'unsigned long') [-Wsign-conversion]
  return (mi_block_t*)(mi_atomic_load_relaxed(&((mi_page_t*)page)->xthread_free) & ~3);
                                                                                 ~ ^~
./Include/internal/mimalloc/mimalloc/internal.h:508:29: warning: implicit conversion changes signedness: 'int' to 'mi_thread_free_t' (aka 'unsigned long') [-Wsign-conversion]
  return (mi_block_t*)(tf & ~0x03);
                          ~ ^~~~~
./Include/internal/mimalloc/mimalloc/internal.h:806:10: warning: implicit conversion changes signedness: 'int' to 'size_t' (aka 'unsigned long') [-Wsign-conversion]
  return __builtin_clzl(x);
  ~~~~~~ ^~~~~~~~~~~~~~~~~
./Include/internal/mimalloc/mimalloc/internal.h:814:10: warning: implicit conversion changes signedness: 'int' to 'size_t' (aka 'unsigned long') [-Wsign-conversion]
  return __builtin_ctzl(x);
  ~~~~~~ ^~~~~~~~~~~~~~~~~
./Modules/getpath.c:264:48: warning: implicit conversion changes signedness: 'Py_ssize_t' (aka 'long') to 'unsigned long' [-Wsign-conversion]
    wchar_t **parts = (wchar_t **)PyMem_Malloc(n * sizeof(wchar_t *));
                                               ^ ~
./Modules/getpath.c:269:22: warning: implicit conversion changes signedness: 'Py_ssize_t' (aka 'long') to 'unsigned long' [-Wsign-conversion]
    memset(parts, 0, n * sizeof(wchar_t *));
                     ^ ~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:77:33: note: expanded from macro 'memset'
                __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                              ^~~~~~~~~~~
./Modules/getpath.c:295:61: warning: implicit conversion changes signedness: 'Py_ssize_t' (aka 'long') to 'unsigned long' [-Wsign-conversion]
    wchar_t *final = cchFinal > 0 ? (wchar_t *)PyMem_Malloc(cchFinal * sizeof(wchar_t)) : NULL;
                                                            ^~~~~~~~ ~
./Modules/getpath.c:318:57: warning: implicit conversion changes signedness: 'Py_ssize_t' (aka 'long') to 'size_t' (aka 'unsigned long') [-Wsign-conversion]
            } else if (_Py_add_relfile(final, parts[i], cchFinal) < 0) {
                       ~~~~~~~~~~~~~~~                  ^~~~~~~~
./Modules/getpath.c:385:63: warning: implicit conversion changes signedness: 'size_t' (aka 'unsigned long') to 'Py_ssize_t' (aka 'long') [-Wsign-conversion]
    wchar_t *wbuffer = _Py_DecodeUTF8_surrogateescape(buffer, cb, &len);
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^~
./Modules/getpath.c:663:43: warning: implicit conversion changes signedness: 'size_t' (aka 'unsigned long') to 'Py_ssize_t' (aka 'long') [-Wsign-conversion]
            u = PyUnicode_FromWideChar(w, len);
                ~~~~~~~~~~~~~~~~~~~~~~    ^~~
./Modules/getpath.c:707:43: warning: implicit conversion changes signedness: 'size_t' (aka 'unsigned long') to 'Py_ssize_t' (aka 'long') [-Wsign-conversion]
            u = PyUnicode_FromWideChar(w, len);
                ~~~~~~~~~~~~~~~~~~~~~~    ^~~
13 warnings generated.
```

Related https://github.com/python/cpython/pull/123020

### Linked PRs
* gh-124070
* gh-124174
* gh-124177
* gh-124181
* gh-124204
* gh-124216

### PR DESCRIPTION
**Pull request by hugovk**
This reverts commit cfe6074d1fa81cf0684fbf8a623616441a1966e7 from https://github.com/python/cpython/pull/123020.

Fixes https://github.com/python/cpython/issues/124064.

There are too many warnings showing up when building locally.

We'll need to think of something else for https://github.com/python/cpython/pull/123020, perhaps only enable these when on the CI (for example, there's a [`CI=true` environment variable](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)).

* Issue: gh-112301

### CODE REVIEW

**Comment by sethmlarson** [comment]
@hugovk FYI, `--disable-safety` configure option would disable the warnings, but maybe we should flip from opt-out to opt-in for these new warnings until we get to a place with fewer in the codebase?

See: https://github.com/python/cpython/blob/9f42b62db998131bb5cd555e2fa72ba7e06e3130/configure.ac#L2509

**Comment by sethmlarson** [comment]
Concretely I'm wondering if we could instead of reverting the whole PR switch the option instead or something else to maintain the CI testing?

**Comment by sobolevn** [comment]
Or maybe we can maintain the list of files that currently have these warnings and exclude them. It will allow us to fix these warnings in files one by one.

**Comment by sethmlarson** [comment]
@sobolevn We have that already, but for determining whether to fail CI. The warnings still occur locally, but as you've seen there is quite a few of them.

**Comment by sethmlarson** [comment]
@hugovk I think it's also okay to revert the whole PR and then squash everything and re-add w/ the proper opt-in configure option instead of opt-out. Don't want to be too disruptive to core devs if you think any of the above suggestions might take too long.

**Comment by nohlson** [comment]
@hugovk @sethmlarson This is a PR that makes the "safety" options opt-in to allow the CI warning checking to remain: https://github.com/python/cpython/pull/124070 . @hugovk Maybe this could be a suitable alternative to reverting #123020

**Review by colesbury — APPROVED** [review]
I think reverting first is the right approach. Currently the "Ubuntu / build and test" CI is failing on "Check compiler warnings" on new PRs.

See:
* https://github.com/python/cpython/actions/runs/10854542283/job/30125214880?pr=124069
* https://github.com/python/cpython/actions/runs/10854746319/job/30125872824?pr=124070

**Review by sobolevn — APPROVED** [review]
I also agree on reverting, because the very same PR that is alternative to this one (https://github.com/python/cpython/pull/124070) has lots of warnings.
Снимок экрана 2024-09-13 в 22 41 30

**Comment by hugovk** [comment]
Thanks @nohlson for the quick response!

@colesbury Hmm, then let's revert.

We can then update https://github.com/python/cpython/pull/124070 to "un-revert" and also fix the CI failure (or create a fresh PR, whichever is easier).

**Comment by hugovk** [comment]
> See:
> 
> * [python/cpython/actions/runs/10854542283/job/30125214880?pr=124069](https://github.com/python/cpython/actions/runs/10854542283/job/30125214880?pr=124069)
> * [python/cpython/actions/runs/10854746319/job/30125872824?pr=124070](https://github.com/python/cpython/actions/runs/10854746319/job/30125872824?pr=124070)

Correcting myself: that sort of thing is expected, those PRs introduced new warnings. The devguide link in the CI failure tells what to do: ideally fix your new warning, or add it to the ignore list if that's not possible.

**Comment by hugovk** [comment]
Correcting myself again! _Those_ look like the failure in https://github.com/python/cpython/pull/124070, and needs fixing. [_This_](https://github.com/python/cpython/actions/runs/10854542283/job/30126414793?pr=124069) sort of thing is expected. Now I'll close my laptop for the evening :)

**Comment by nohlson** [comment]
> I think reverting first is the right approach. Currently the "Ubuntu / build and test" CI is failing on "Check compiler warnings" on new PRs.
> 
> See:
> 
> * https://github.com/python/cpython/actions/runs/10854542283/job/30125214880?pr=124069
> * https://github.com/python/cpython/actions/runs/10854746319/job/30125872824?pr=124070

In #124069 the tool is failing to parse the compiler output because it looks mangled
```
../cpython-ro-srcdir/Modules/_hacl/Hacl_Hash_Blake2s_Simd128.c:108:67: warning: conversion to ‘int’ from ‘uint32_t’ {aka ‘unsigned int’} may change theIn file included from ../cpython-ro-srcdir/Modules/_hacl/include/krml/FStar_UInt128_Verified.h:10,
```

And that is the same for #124070 
```
../cpython-ro-srcdir/Modules/expat/xmlparse.c:3101:46: warning: conversion to ‘size_t’ {aka ‘long unsigned int’} from ‘int’ may change the sign of the result [-Wsign-Modules/_hacl/Hacl_Hash_Blake2s_Simd128.c:80:3: note: in expansion of macro ‘KRML_MAYBE_FOR10’

```
This might be the cmake jobs racing to write to the log so it might just need cmake option `--output-sync` 

> I also agree on reverting, because the very same PR that is alternative to this one (#124070) has lots of warnings. Снимок экрана 2024-09-13 в 22 41 30

The warnings will still be generated in CI for the Ubuntu build and test and macOS build and test jobs.

**Comment by hugovk** [comment]
Here's take two: https://github.com/python/cpython/pull/124070

**Pull request merged**
