### PR TITLE
bpo-38388 Document pickle protocol version 5

### PR DESCRIPTION
**Pull request by dimaqq**
https://bugs.python.org/issue38388

### CODE REVIEW

**Comment by dimaqq** [comment]
Can someone add `skip news` and `type-documentation` labels on this PR?

P.S. I'm not sure how to request this PR to be backported to 3.8 branch.

**Comment by tirkarthi** [comment]
The backport PR will be done as backport label is added by core dev/triager and this PR is merged to master.

**Review by taleinat — CHANGES_REQUESTED** [review]
In the paragraph preceding the list of protocols, the line "There are currently 5 different protocols..." needs to be updated as well.

**Comment by dimaqq** [comment]
> In the paragraph preceding the list of protocols, the line "There are currently 5 different protocols..." needs to be updated as well.

Done, thanks!

**Review by tirkarthi — APPROVED** [review]
LGTM. I think you need to add "I have made the requested changes; please review again." as a comment for the bot to change labels and request a review. Thanks.

**Review by taleinat — APPROVED** [review]

**Pull request merged**
