### PR TITLE
gh-102033: Fix syntax error in `Tools/c-analyzer`

### PR DESCRIPTION
**Pull request by sobolevn**
The easiest way to format strings with `{}` meaningful chars is via `%`.

* Issue: gh-102033

Automerge-Triggered-By: GH:ericsnowcurrently

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Hmm, if this has had a syntax error for the last three years, is it still useful?

**Comment by sobolevn** [comment]
@hauntsaninja good idea! I went trough all files in `c-analyzer` and:
- Remove empty ones
- Removed ones that are unused (like `_dparse`, `_alt`, `_state_machine`)
- Removed unused imports
- Removed unused variables

I double checked that:
- It does not affect semantics
- It does not affect runtime

To test that everyting is still working I've triggered https://github.com/python/cpython/pull/102066/commits/3dc3bd99d3475033350ce208fdfe20e02101ddd3 with a partial revert of https://github.com/python/cpython/pull/101657 to test the warning.

However, right now `Lib/test/test_check_c_globals.py` is disabled :(

**Comment by sobolevn** [comment]
Any idea - why `patchcheck` fails?

**Comment by hauntsaninja** [comment]
@sobolevn It wants you to apply this diff:
```
diff --git a/Tools/c-analyzer/cpython/_capi.py b/Tools/c-analyzer/cpython/_capi.py
index 5584677dae..dc453cb828 100644
--- a/Tools/c-analyzer/cpython/_capi.py
+++ b/Tools/c-analyzer/cpython/_capi.py
@@ -611,7 +611,7 @@ def _render_item_full(item, groupby, verbose):
     yield f'  {"filename:":10} {item.relfile}'
     for extra in ('kind', 'level'):
         #if groupby != extra:
-            yield f'  {extra+":":10} {getattr(item, extra)}'
+        yield f'  {extra+":":10} {getattr(item, extra)}'
     if verbose:
         print('  ---------------------------------------')
         for lno, line in enumerate(item.text, item.lno):
```

**Comment by ericsnowcurrently** [comment]
I'm hesitant to do any significant cleanup on this tool before we've re-enabled the CI check for globals.  Would you mind if we tabled this until then?

**Comment by sobolevn** [comment]
Sure, seems reasonable!

**Comment by sobolevn** [comment]
Since https://github.com/python/cpython/pull/102506 was merged, I think we can return to this PR.

Re-running the CI.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

This change is almost entirely deleting unused code.  I don't expect that any of that code is important to keep at this point.  Thanks for doing this!

**Comment by sobolevn** [comment]
Thanks everyone!

Is there anything else I need to do? :)
If not, can someone please click "merge"?

**Pull request merged**
