### PR TITLE
Fix atexitmodule doc

### PR DESCRIPTION
**Pull request by linchiwei123**

### CODE REVIEW

**Review by eamanu — COMMENTED** [review]
The currently inline docs  looks good.  IMHO this PR doesn't give us any
improve.

But, to be according with other inline docs, this PR is good.

**Comment by eamanu** [comment]
The NEWS could be skipppd.

**Comment by linchiwei123** [comment]
> The currently inline docs looks good. IMHO this PR doesn't give us any
> improve.
> 
> But, to be according with other inline docs, this PR is good.

Yes, and help(atexit) would look better.
```python
>>> import atexit
>>> help(atexit)
```
Before:
```python
:Help on built-in module atexit:

NAME
    atexit - allow programmer to define multiple exit functions to be executedupon normal program termination.

DESCRIPTION
    Two public functions, register and unregister, are defined.
```
After:
```python
:Help on built-in module atexit:

NAME
    atexit

DESCRIPTION
    allow programmer to define multiple exit functions to be executed
    upon normal program termination.

    Two public functions, register and unregister, are defined.
```

**Review by merwok — APPROVED** [review]

**Review by nanjekyejoannah — APPROVED** [review]
LGTM. Thanks @linchiwei123 for the patch.

**Pull request merged**
