### PR TITLE
Fix comments

### PR DESCRIPTION
**Pull request by MandarJKulkarni**
I have signed the CLA and received the copy.
But the label 'CLA not signed' is still not removed.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by mdickinson** [comment]
> But the label 'CLA not signed' is still not removed.

That's odd. What's your bugs.python.org username?

**Comment by MandarJKulkarni** [comment]
> > But the label 'CLA not signed' is still not removed.
> 
> That's odd. What's your bugs.python.org username?

mjkool

**Comment by MandarJKulkarni** [comment]
I have signed the CLA again, however when I check with my github username, the CLA verifying page says "MandarJKulkarni" has not signed the CLA. Do I need to have bugs.python.org username same as my gihub username?

**Review by asvetlov — APPROVED** [review]

**Comment by MandarJKulkarni** [comment]
Seems this file is renamed.
Created a separate PR https://github.com/python/cpython/pull/13636

**Comment by csabella** [comment]
Closing for #13636.

**Pull request closed without merging**
