### PR TITLE
bpo-42053: fixed fwalk incorrect boolean test for non-fd arguments

### PR DESCRIPTION
**Pull request by AliyevH**
https://bugs.python.org/issue42053

### CODE REVIEW

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
Please add a test (calling `fwalk()` with an object implementing `__index__`).

The NEWS entry is also required.

**Comment by AliyevH** [comment]
I have made the requested changes; please review again

**Comment by akulakov** [comment]
It looks like we don't have a test for fwalk(top=fd) where `fd` would be a valid fd obj that fwalk() can successfully use. It might be nice to add a test for that because the current test would logically build on top of that, as a non-int obj implementing __index__ is meant to be usable as an fd, as implied by current code (and I assume that would actually work).

**Comment by AliyevH** [comment]
@akulakov thanks for review.
You suggest to rewrite logic of test? sorry didn't understand. Can you please provide more information?

@serhiy-storchaka. Can you please review too?

**Comment by akulakov** [comment]
@AliyevH fwalk doesn't seem to be working for valid fd in my testing:

```
[ins] In [69]: fw=os.fwalk(fd, follow_symlinks=True)

[ins] In [70]: list(fw)

TypeError: open: path should be string, bytes or os.PathLike, not int
```

**Comment by serhiy-storchaka** [comment]
I confirm that fwalk() does not support integer first argument, and never supported (this is why there are no tests). The check is misleading and should be removed.

**Pull request closed without merging**
