### PR TITLE
Correct some typos in comments

### PR DESCRIPTION
**Pull request by jonasdlindner**
Automerge-Triggered-By: GH:AlexWaygood

### CODE REVIEW

**Comment by musvaage** [comment]
Community policy in general is not to merge pull requests fixing typos.

**Comment by jonasdlindner** [comment]
@musvaage I don't get your point. The policy is that there is no need to create an Github Issue or a News entry for such simple changes.

**Comment by musvaage** [comment]
> don't understand

@jonasdlindner

A core dev stated [context being source code files] that was policy.

**Comment by musvaage** [comment]
I have no opinion whether or not this PR should be merged; merely reiterating Community policy as was explained to me.

**Comment by AlexWaygood** [comment]
@musvaage is correct that we don't really want to encourage this kind of PR, as typos in comments don't really have any impact on end users, and PRs like this distract from more important issues. But since you've already made the PR, I'm okay with merging it.

**Review by AlexWaygood — APPROVED** [review]

**Comment by musvaage** [comment]
@AlexWaygood 

Comment noted.

That being said, .h files might be considered as more exposed than .c files.

```
$ python3 --version
Python 3.9.15
$ find /usr/include/python3.9 -type f | wc -l
176
$ 
```

**Pull request merged**
