### PR TITLE
gh-91810: ElementTree: Use text file's encoding by default in XML declaration

### LINKED ISSUE #91810: ElementTree should use UTF-8 for xml declaration.
**Feature or enhancement**

Currently, `ElementTree.tostring(root, encoding="unicode", xml_declaration=True)` uses locale encoding.

I think ElementTree should use UTF-8, instead of locale encoding.

Example:

```pycon
$ LANG=ja_JP.eucJP ./python.exe
Python 3.11.0a7+ (heads/bytes-alloc-dirty:7fbc7f6128, Apr 19 2022, 16:53:54) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xml.etree.ElementTree as ET
>>> et = ET.fromstring("<t>hello</t>")
>>> ET.tostring(et, encoding="unicode", xml_declaration=True)
"<?xml version='1.0' encoding='eucJP'?>\n<t>hello</t>"
```

Code:

https://github.com/python/cpython/blob/bcf14ae4336fced718c00edc34b9191c2b48525a/Lib/xml/etree/ElementTree.py#L732-L742

**Pitch**

* UTF-8 is the most common encoding for XML.
* Locale encoding name (e.g. `cp932` or `eucJP`) would be different from XML encoding name recommended by w3c (e.g. `Shift_JIS` or `EUC-JP`).

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
ElementTree method write() and function tostring() now use the text file's
encoding ("UTF-8" if not available) instead of locale encoding in XML
declaration when encoding="unicode" is specified.

Closes #91810.

### CODE REVIEW

**Review by methane — APPROVED** [review]

**Comment by Yhg1s** [comment]
FYI, @pablogsal @ambv: this change broke existing behaviour in a subtle way. I'm not sure if it's worth rolling back in 3.9, especially considering it went into the final regular bugfix release. It may be worth fixing the regression in 3.10 or 3.11, or it may be deemed to be a documentation issue.

The [documentation of ElementTree.write()](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write) says: `xml_declaration controls if an XML declaration should be added to the file. Use False for never, True for always, None for only if not US-ASCII or UTF-8 or Unicode (default is None).`

Before this change, passing a file opened in text mode _regardless of the encoding used_ and passing `encoding='unicode'` to ElementTree.write() would not make ElementTree.write() produce the XML declaration.

After this change, passing a file opened in text mode with UTF-8 or ascii as encoding, and passing `encoding='unicode'` to ElementTree.write(), no XML declaration is produced (as before). However, passing a file opened in any other encoding (e.g. `iso-8859-1`) implicitly or explicitly, with `encoding='unicode'` passed to ElementTree.write() now _does_ produce an XML declaration. This may come as a surprise to code that was manually adding an XML declaration before. For example:

```
from xml.etree import ElementTree as et

XML_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE myelement>
"""

root = et.Element("myelement")
tree = et.ElementTree(root)

with open("myfile.xml", "w", encoding="iso-8859-1") as f:
    f.write(XML_HEADER)
    tree.write(f, encoding='unicode')
with open("myfile.xml", encoding="iso-8859-1") as f:
    print(f.read())
```

... will produce invalid XML because of this change:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE myelement>
<?xml version='1.0' encoding='iso-8859-1'?>
<myelement />
```

... where before this change it would not emit the second XML declaration. (This is arguably problematic code, but unfortunately the file's encoding can of course be implicit, which makes it harder to tell what's going on. This was synthesized from real code found while upgrading to 3.9.13 at Google.)

**Comment by pablogsal** [comment]
I am a bit worried that for 3.10 people have already developed workarounds for this and we are going to break them again. On the other hand, one could argue that the situation is too specific and that's why nobody has raised issues so far. I am ok rolling it back, though, if that's the consensus.

**Comment by Yhg1s** [comment]
Actually, this change didn't make it into 3.10.4, so it's only in 3.9.13 and 3.11 at this point.

**Comment by serhiy-storchaka** [comment]
#93426 fixes this.

**Comment by ambv** [comment]
I think we should fix it in 3.9.14 as well since it's a regression only in 3.9.13.

**Comment by ambv** [comment]
(In the mean time we *did* release 3.10.5 with the bug which made this version affected too)

**Pull request merged**
