### PR TITLE
bpo-39916: Use os.scandir() as context manager in Path.glob().

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue39916

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM.

**Review by aeros — APPROVED** [review]
LGTM. Would it also be worthwhile to add a brief test case in `test_pathlib` to make sure a ResourceWarning is no longer raised when `Path.glob()` is interrupted? For example:

```py
def test_interrupt_path_glob(self):
    rc, out, err = assert_python_ok('-c', """if True:
         import os
         from signal import SIGINT
         from pathlib import Path
         from test.support import TESTFN

         BASE = os.path.realpath(TESTFN)
         test_path = Path(BASE)
         for _ in test_path.glob("fileA"):
             # Simulate interruption in first iteration
             pid = os.getpid()
             os.kill(pid, SIGINT)
        """)
    # Ensure ResourceWarning didn't occur
    self.assertNotIn("ResourceWarning", err.decode())
```

The above will likely have to be adjusted, but I wanted to check if something along those lines was worth pursuing before investing more time into it.

**Comment by serhiy-storchaka** [comment]
Thank you for your test @aeros, but it does not work. It is passed with unpatched pathlib. This is because at the time when when you get an item from the glob iterator you already have finished iterating the scandir iterator and closed it. I have not add tests for this PR because It is very uneasy. I would need to monkey-patch scandir and create a detailed working implementation of scandir, DirEntry, etc which fails at specific moment. And keep it synchronized with future changes in the main implementation. It is too much work for tiny benefit.

**Comment by aeros** [comment]
@serhiy-storchaka Ah, I see. The above was mostly a very rough draft idea, I was unaware how much the actual implementation of the test would involve (but figured you might have an idea). Thanks for the explanation.

With that in mind, I would agree that it's not worthwhile to go through that much effort (and added long-term maintenance cost) for a minor test to ensure resource warnings don't occur.

**Pull request merged**
