### PR TITLE
gh-115119: Update Windows installer to mpdecimal 4.0.0

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-115119

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@SethMichaelLarson, I tried to use `generate_sbom.py`:

```console
$ python3 Tools/build/generate_sbom.py
Version '4.0.0' for package 'mpdecimal not in all 'externalRefs[].referenceLocator' fields
```

Do I have to manually edit `Misc/sbom.spdx.json`?

**Comment by Eclips4** [comment]
> @SethMichaelLarson, I tried to use `generate_sbom.py`:
> 
> ```
> $ python3 Tools/build/generate_sbom.py
> Version '4.0.0' for package 'mpdecimal not in all 'externalRefs[].referenceLocator' fields
> ```
> 
> Do I have to manually edit `Misc/sbom.spdx.json`?

I think you mean @sethmlarson :)

**Comment by sethmlarson** [comment]
Thanks for reporting this @erlend-aasland and apologies for the trouble. It wasn't the intent to require the user to update the CPE value, I've [opened a PR to automatically update the CPE version value](https://github.com/python/cpython/pull/118521).

If you need to get this update in ASAP, I recommend updating the CPE value manually in `Misc/externals.spdx.json`.

**Comment by erlend-aasland** [comment]
> Thanks for reporting this @erlend-aasland and apologies for the trouble. It wasn't the intent to require the user to update the CPE value, I've [opened a PR to automatically update the CPE version value](https://github.com/python/cpython/pull/118521).

Thank you so much!

> If you need to get this update in ASAP, I recommend updating the CPE value manually in `Misc/externals.spdx.json`.

I tried to manually update the value in 3031684f1a4c11563333092518af81c560a7318b.

**Review by zooba — APPROVED** [review]

**Review by sethmlarson — APPROVED** [review]
LGTM!

**Review by zware — APPROVED** [review]

**Pull request merged**
