### PR TITLE
gh-108303: Move config parser data to `Lib/test/configparserdata/`

### PR DESCRIPTION
**Pull request by sobolevn**
There are two options:
- a data dir (because it is also used by `idlelib`)
- `test_configparser` package with these files and `test_configparser.py` (it is more complex to add, since requires several build-step changes, while in my opinion does not add much)

What do others think?

* Issue: gh-108303

### CODE REVIEW

**Comment by sobolevn** [comment]
Failures look related

**Comment by ambv** [comment]
They are indeed related because looks like the data files don't get installed.

**Comment by sobolevn** [comment]
Fixing

**Comment by vstinner** [comment]
> They are indeed related because looks like the data files don't get installed.

Ooooh, right. It's good that we have buildbots to test that :-)

**Comment by jaraco** [comment]
> > They are indeed related because looks like the data files don't get installed.
> 
> Ooooh, right. It's good that we have buildbots to test that :-)

Better would be to fail faster (#81224).

This change is also implicated In jaraco/configparser#70.

It's probably good to learn that the backport was inadvertently depending on fixtures in the Python test suite.

Additionally, it's an indication that this change has implications for the backport's test suite and it would be good for me to get notified when there are such changes. I think what that means is that I just need to add my username to the codeowners for the relevant paths.

**Pull request merged**
