### PR TITLE
gh-114577: colorsys code optimization

### PR DESCRIPTION
**Pull request by Wulian233**
# colorsys code optimization

This is my first issue and submitting PR to Python.\
If I have any questions, please let me know. Thank you.

Lib/colorsys.py\
In this PR, I made the following changes: 
~~1. Simple Code~~
~~2. Using elif~~

Because no new features have been added or actually changed, the [test](https://github.com/python/cpython/blob/main/Lib/test/test_colorsys.py) can be used

* Issue: gh-114577

### CODE REVIEW

**Comment by hugovk** [comment]
Please can you change the line ending from Windows (CRLF) back to Unix (LF)?

Currently it's showing every line as changed, which makes it hard to review. Thanks.

**Comment by hugovk** [comment]
Building non-debug, with PGO and LTO enabled (https://devguide.python.org/getting-started/setup-building/#optimization) on macOS:

```console
❯ GDBM_CFLAGS="-I$(brew --prefix gdbm)/include" \
  GDBM_LIBS="-L$(brew --prefix gdbm)/lib -lgdbm" \
  ./configure --config-cache \
              --with-openssl="$(brew --prefix openssl@3.0)" -enable-optimizations --with-lto \
               && make -s -j10
```

And running this on `main`:

```console
❯ ./python.exe -m timeit -s "from colorsys import hsv_to_rgb" "hsv_to_rgb(0.5, 0.5, 0.4)"
2000000 loops, best of 5: 197 nsec per loop
```

But this PR is slower:

```console
❯ ./python.exe -m timeit -s "from colorsys import hsv_to_rgb" "hsv_to_rgb(0.5, 0.5, 0.4)"
1000000 loops, best of 5: 251 nsec per loop
```

**Comment by Wulian233** [comment]
Thanks, I'm thinking about revert the `hsv_to_rgb` change, it might be better to just change `if` to `elif`

**Comment by hugovk** [comment]
Yeah, looking specifically at the `hsv_to_rgb` changes, it's replacing `int(h*6.0); i = int(h*6.0)` and early return, with `i, f = divmod(h * 6.0, 1.0); i = int(i) % 6` and a list construction and lookup.

For the first bits, we can see the original is quicker:

```console
❯ python3.13 -m timeit -s "h = 0.5" "i = int(h*6.0)" "i = i%6"
10000000 loops, best of 5: 30.1 nsec per loop

❯ python3.13 -m timeit -s "h = 0.5" "i, f = divmod(h * 6.0, 1.0)" "i = int(i) % 6"
5000000 loops, best of 5: 82 nsec per loop
```

**Comment by Wulian233** [comment]
I revert the `hsv_to_rgb` change, and change `if` to `elif`

**Comment by hugovk** [comment]
Changing those `if`s to `elif`s makes no performance difference.

Simple example:

```pycon
>>> import dis
>>> def a(i):
...     if i == 0:
...             return 0
...     if i == 1:
...             return 1
...
>>> def b(i):
...     if i == 0:
...             return 0
...     elif i == 1:
...             return 1
...
>>> dis.dis(a)
  1           0 RESUME                   0

  2           2 LOAD_FAST                0 (i)
              4 LOAD_CONST               1 (0)
              6 COMPARE_OP              40 (==)
             10 POP_JUMP_IF_FALSE        1 (to 14)

  3          12 RETURN_CONST             1 (0)

  4     >>   14 LOAD_FAST                0 (i)
             16 LOAD_CONST               2 (1)
             18 COMPARE_OP              40 (==)
             22 POP_JUMP_IF_FALSE        1 (to 26)

  5          24 RETURN_CONST             2 (1)

  4     >>   26 RETURN_CONST             0 (None)
>>> dis.dis(b)
  1           0 RESUME                   0

  2           2 LOAD_FAST                0 (i)
              4 LOAD_CONST               1 (0)
              6 COMPARE_OP              40 (==)
             10 POP_JUMP_IF_FALSE        1 (to 14)

  3          12 RETURN_CONST             1 (0)

  4     >>   14 LOAD_FAST                0 (i)
             16 LOAD_CONST               2 (1)
             18 COMPARE_OP              40 (==)
             22 POP_JUMP_IF_FALSE        1 (to 26)

  5          24 RETURN_CONST             2 (1)

  4     >>   26 RETURN_CONST             0 (None)
```

Both of those have identical bytecode.

There's no point adding `elif`s when we're returning early, it's all the same. 

However, I'd argue there is a cognitive cost to adding `elif`s, it's a bit more thinking when reading.

Please revert those too.

**Comment by gaogaotiantian** [comment]
If we are talking about micro-optimization here, the changes in `yiq_to_rgb` would probably make the code observably slower due to the extra function calls. To be honest, I don't think `max(0.0, min(r, 1.0))` makes it clearer either. It would be better if we have something like `r = clip(r, 0, 1)`, but other than that, `if`s are very easy to follow.

Without that, it seems like this PR would be a purely cosmetic change - adding spaces in lines. Not saying that it's not helpful, but it might be against the contribution guideline.

**Comment by hugovk** [comment]
Indeed, benchmarking `yiq_to_rgb`, which replaces `if`s with `max` and `min`, shows worse performance.

`main`:

```console
❯ ./python.exe -m timeit -s "from colorsys import yiq_to_rgb" "yiq_to_rgb(0.5, 0.5, 0.4)"
2000000 loops, best of 5: 171 nsec per loop
```

PR:

```console
❯ ./python.exe -m timeit -s "from colorsys import yiq_to_rgb" "yiq_to_rgb(0.5, 0.5, 0.4)"
2000000 loops, best of 5: 199 nsec per loop
```

**Comment by Wulian233** [comment]
It seems that this is a bad change, as gaogaotiantian said, just adding spaces does not help

**Pull request closed without merging**
