### PR TITLE
bpo-39693: tarfile extractfile documentation

### PR DESCRIPTION
**Pull request by dorosch**
https://bugs.python.org/issue39693

### CODE REVIEW

**Review by akuchling — APPROVED** [review]
Looks fine to me.

**Comment by dorosch** [comment]
> Looks fine to me.

Thanks for review)

**Review by ethanfurman — CHANGES_REQUESTED** [review]
What you have looks good!  Please also update `Doc/library/tarfile.rst` with the same information.

Also make sure you are in `Misc/ACKS`.

**Comment by csabella** [comment]
@dorosch, please make the changes requested by @ethanfurman.  Thanks!

**Comment by dorosch** [comment]
@ethanfurman Could you please review changes?
Thanks

**Review by ethanfurman — APPROVED** [review]

**Pull request merged**
