### PR TITLE
gh-111178: fix USAN failures for `partialobject`

### PR DESCRIPTION
**Pull request by picnixz**
Before reviewing this one, I'll add a suppression file with all the incriminating functions. And whenever I make a new PR for fixing USAN failures, I'll just remove the corresponding entries so that we can really check the changes by running the build bot.

* Issue: gh-111178

### CODE REVIEW

**Comment by picnixz** [comment]
> What's the status of this PR? 

Forgotten :D

> Why is it a draft?

I wanted to add the suppression before but since it wouldn't have worked anyway, I can mark it as ready (I'll just check that the warnings for partialobjects indeed disappeared).

**Comment by picnixz** [comment]
@vstinner Do you want me to add some `_PyPartialObject_CAST`?

**Review by vstinner — COMMENTED** [review]
If you want to fix UBSan issues for partial(), you should patch more methods like: partial_dealloc, partial_repr, partial_traverse, etc.

**Comment by picnixz** [comment]
> If you want to fix UBSan issues for partial(), you should patch more methods like: partial_dealloc, partial_repr, partial_traverse, etc.

Oups, I forgot to do it. I think I only checked the warnings thinking that the rest would be reported. I'll do it tomorrow (hence reconverting into a draft).

**Comment by picnixz** [comment]
I haven't touched the utilities functions since they are not used as callbacks and shouldn't lead to undefined behaviours (e.g., `partial_setvectorcall`).

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
Merged, thanks.

**Pull request merged**
