### PR TITLE
bpo-26264: Added new key words to keyword lib

### PR DESCRIPTION
**Pull request by Arfey**
https://bugs.python.org/issue26264

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by rhettinger** [comment]
You also need to patch Lib/test/test_keywords.py before this can go forward.

**Comment by bitdancer** [comment]
Raymond, I closed the originating issue as a duplicate of bpo-26264; any PR should be targeted to that issue.  The questions raised in that issue need to be resolved/decided before anything happens.  I dislike the idea of adding special casing, but I suppose we could add a manually-maintained category of "transitional keywords" to keyword.py.  test_keyword shouldn't need any fixes, though if we do add such a special category we may want additional tests for the new functionality.

**Comment by 1st1** [comment]
This is only a tiny part (1%) of what needs to be done in 3.7 (async/await to become proper keywords). Closing this PR.

**Comment by 1st1** [comment]
> manually-maintained category of "transitional keywords" to keyword.py.

We don't need this. The plan is for async and await to become regular keywords in 3.7.  That means we'll remove some code from tokenizer that made them "soft" keywords from tokenizer (C and Python), as well as some hacks from `compiler.c`, lot's of hacks from lib2to3, etc. Please let me handle this myself in a separate PR (soon) as it involves a lot of code that I wrote.

**Comment by terryjreedy** [comment]
https://bugs.python.org/issue30120
was closed as a duplicate of
https://bugs.python.org/issue26264

**Pull request closed without merging**
