### PR TITLE
gh-109408: Azure Pipelines: test 3.12 branch

### PR DESCRIPTION
**Pull request by hugovk**
As noted in https://github.com/python/cpython/issues/109408#issuecomment-1719732306, [Azure Pipelines CI (`ci.yml`)](https://dev.azure.com/Python/cpython/_build?definitionId=4) runs tests on version branches _post-merge_.

But it's only running on `main` and `3.11` and older, and not on `3.12`, because we forgot to add it when branching `3.12` from `main` in May:

<details>
<summary>Screenshot</summary>

image

</details>

Also, [Azure Pipelines PR (`pr.yml`)](https://dev.azure.com/Python/cpython/_build?definitionId=9) only runs for PRs to `main`, but I added the missing `3.12` anyway (and am planning on eventually removing it in https://github.com/python/cpython/issues/109408):

<details>
<summary>Screenshot</summary>

image

</details>

Should we remove 3.7 from these lists?

* Issue: gh-109408

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
It should be added to PEP 101 release process to not forget it next time.

**Comment by hugovk** [comment]
> It should be added to PEP 101 release process to not forget it next time.

Looking at [PEP 101](https://peps.python.org/pep-0101/#how-to-make-a-release), should it be added to https://github.com/python/release-tools/blob/master/release.py?

> * Bump version numbers via the release script:
>   `$ .../release-tools/release.py --bump X.Y.ZaN`

**Comment by vstinner** [comment]
I didn't understand well the future of Azure Pipelines. If it goes away, updating the release tool is not needed.

**Comment by hugovk** [comment]
There are two Azure Pipelines runs.

One for PRs (`pr.yml`) - we're planning on removing this one, it's the one most people would notice.

The other runs on version branches _after_ merging PRs (`ci.yml`), and it's not visible in PRs. Steve would like to keep this one running to do some extra Windows packaging checks (https://github.com/python/cpython/issues/109408#issuecomment-1720066764), so that can stay.

**Comment by hugovk** [comment]
Apologies for the force push, it was a mistake! No changes to the PR other than rebasing on `main`.

**Comment by hugovk** [comment]
> > It should be added to PEP 101 release process to not forget it next time.
> 
> Looking at [PEP 101](https://peps.python.org/pep-0101/#how-to-make-a-release), should it be added to [python/release-tools@`master`/release.py](https://github.com/python/release-tools/blob/master/release.py?rgh-link-date=2023-09-15T18%3A38%3A27Z)?
> 
> > * Bump version numbers via the release script:
> >   `$ .../release-tools/release.py --bump X.Y.ZaN`

Issue created: https://github.com/python/release-tools/issues/56

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
> The other runs on version branches after merging PRs (ci.yml), and it's not visible in PRs. Steve would like to keep this one running to do some extra Windows packaging checks (https://github.com/python/cpython/issues/109408#issuecomment-1720066764), so that can stay.

Sure, it makes sense. Thanks for the explanation.

**Pull request merged**
