### PR TITLE
bpo-39301: State that floor division is used for right shift operations

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue39301

### CODE REVIEW

**Review by mdickinson — APPROVED** [review]
LGTM. It may not completely resolve confusion, but it's a clear incremental improvement.

**Comment by mdickinson** [comment]
One thought: while we're here, could we remove the "without overflow check" part? I have no idea what it means, and I suspect no-one else does either. It may have made sense before long integers were the norm (though even then, I'm not sure what it means).

**Comment by mdickinson** [comment]
@ZackerySpytz Do you want to remove the "without overflow check" wording in this PR? If not, I'll merge this one and make a separate PR for changing that wording.

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
This looks good.  Please do remove the "without overflow check" wording as well.

**Comment by mdickinson** [comment]
Ah, 3.6 is in security mode; I'll close that backport.

**Pull request merged**
