### PR TITLE
bpo-35545: Fix asyncio discarding IPv6 scopes 

### PR DESCRIPTION
**Pull request by lepaperwan**
This PR proposes a solution to [bpo-35545](https://bugs.python.org/issue35545) by adding an optional `flowinfo` and `scopeid` to `asyncio.base_events._ipaddr_info` to carry the full address information into `_ipaddr_info` and avoid discarding IPv6 specific information.

Changelog entry & regression tests to come.

https://bugs.python.org/issue35545

### CODE REVIEW

**Comment by 1st1** [comment]
Please add a NEWS file.

**Review by 1st1 — APPROVED** [review]

**Comment by 1st1** [comment]
@asvetlov what do you think?

**Review by asvetlov — APPROVED** [review]
I think we need NEWs entry, everything is fine.

**Comment by asvetlov** [comment]
@lepaperwan there is a possibility to merge the PR as is but if you add a simple regression test it would be awesome!

**Comment by asvetlov** [comment]
Thanks for the PR.
I know asyncio is full of mock-based tests but we are working to get rid of them where is possible.
The reason is: *real* tests are much more stable on changing asyncio internals but mocked tests require fixes to reflect new objects structure/methods/signatures etc.

From my understanding, the test can create asyncio local server, connect to it and check the socket peer name or something like this.
Would you try this strategy?

**Comment by lepaperwan** [comment]
Sure, I can't get around to it today but I'll fix the tests to avoid mocks
sometime this week.

**Comment by lepaperwan** [comment]
I hadn't thought this through the other night while answering so I'll try to make this as complete as possible.

Testing that the scope is properly kept through the internals of `asyncio` actually requires that the test host has a usable scoped IP address (which is unusual on the loopback interface).

Should it be the case, the test would have to either dynamically acquire that IP and use it to bind the server, or know it beforehand and have it hardcoded. Binding to an invalid address, of course, fails.


```python
>>> import socket

>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
>>> s.bind(("fe80::1", 80, 0, 1))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 99] Cannot assign requested address
```

Another solution is to rely on scoped IPs failing to be used if the scope ID is not explicitly given.

```python
>>> import socket

>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
>>> s.connect(("fe80::1", 80))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

However if there is no server to answer, as expected, the call fails as well.

```python
>>> import socket

>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
>>> s.connect(("fe80::1", 80, 0, 1))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 101] Network is unreachable
```

The `Invalid argument` method works with `asyncio` as well. (This is on 3.7.2)

```python
>>> import asyncio

>>> asyncio.run(asyncio.open_connection("fe80::1%1", 80))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 77, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 959, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
OSError: [Errno 22] Invalid argument
```

Imposing additional constraints on the test host isn't ideal because while it might be possible to setup the CIs appropriately, it isn't desirable and contributors might not have identical setups.

I'm not certain what Python's test policy is at this stage. I'd assume expecting errors for anything other than error detection/handling isn't great, constraining the test host isn't great, and mocks aren't great either.

If anyone has ideas on how to best go about testing this please chime in :)

**Comment by asvetlov** [comment]
Sorry, I've missed the fact that IPv6 scopes require specific host configuration.
Let's keep mocking here.

Thank you very much for your contribution!

**Pull request merged**
