### PR TITLE
bpo-40296: Fix supporting generic aliases in pydoc

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue40296

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
Looks good. Sorry I took so long for the review!

**Review by raghavthind2005 — APPROVED** [review]

**Comment by gvanrossum** [comment]
@serhiy-storchaka If you still care please merge.

**Comment by serhiy-storchaka** [comment]
Sorry, I was going to review it myself yet once and maybe add more tests if not all changes are covered.

**Comment by serhiy-storchaka** [comment]
Will merge after fixing pydoc tests (#31959) and adding some new tests.

**Pull request merged**
