### PR TITLE
gh-106797: Remove warning logs from Python/generated_cases.c.h

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-106797

### CODE REVIEW

**Comment by corona10** [comment]
```
In file included from Python/ceval.c:770:
Python/generated_cases.c.h:3437:48: warning: code will never be executed [-Wunreachable-code]
            if (0) { stack_pointer[-(1 + 0)] = res2; }
                                               ^~~~
Python/generated_cases.c.h:3437:17: note: silence by adding parentheses to mark code as explicitly dead
            if (0) { stack_pointer[-(1 + 0)] = res2; }
                ^
                /* DISABLES CODE */ ( )
Python/generated_cases.c.h:3415:48: warning: code will never be executed [-Wunreachable-code]
            if (0) { stack_pointer[-(1 + 0)] = res2; }
                                               ^~~~
Python/generated_cases.c.h:3415:17: note: silence by adding parentheses to mark code as explicitly dead
            if (0) { stack_pointer[-(1 + 0)] = res2; }
                ^
                /* DISABLES CODE */ ( )
clang -c -fno-strict-overflow -Wsign-compa
```

Warning logs are reduced, but not sure this is a safe way.

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
The `if (0)` and `if (1)` can easily be simplified too. It's these lines in `assign()`:
```py
            stmt = f"{dst.name} = {cast}{src.name};"
            if src.cond:
                stmt = f"if ({src.cond}) {{ {stmt} }}"
            self.emit(stmt)
```

**Comment by corona10** [comment]
@gvanrossum 

It works except it will introduce another warning :) 
This issue should be solved separately 

````
Python/generated_cases.c.h:3394:23: warning: unused variable 'res2' [-Wunused-variable]
            PyObject *res2 = NULL;
````

**Comment by corona10** [comment]
Looks like it needs a kind of keyword for `res2 if (0)` case, which `unused` keyword can not replace.

**Comment by corona10** [comment]
> It looks like it needs a keyword for res2 if (0) case, which unused keyword can not replace.

I solved the issue by using the same approach of assigning rule for declaring rule :)

**Review by gvanrossum — APPROVED** [review]
Thanks -- that should do it, merge it!

**Pull request merged**
