### PR TITLE
[3.9] bpo-41735: Fix thread locks in zlib module may go wrong in rare case

### PR DESCRIPTION
**Pull request by ghost**
https://bugs.python.org/issue41735

### CODE REVIEW

**Comment by iritkatriel** [comment]
backporting to branches other than master is automated, you don't need to create additional PRs for that.

**Comment by animalize** [comment]
> backporting to branches other than master is automated, you don't need to create additional PRs for that.

There is a code conflict, a few hours ago zlib module was changed by another issue.

**Comment by iritkatriel** [comment]
What I mean is that you shouldn't have created this PR and 22132.    You only needed to create PR 22126. When a core reviewer approves PR 22126 they can choose to back port the change to other branches. They have buttons that do this.

So you only make PRs against master branch. Core reviewers backport them.

**Comment by animalize** [comment]
There is a code confilct, this line was added to master branch recently:

`zlibstate *state = PyType_GetModuleState(cls);`

**Pull request merged**
