### PR TITLE
bpo-41132: Use pymalloc allocator in the f-string parser

### PR DESCRIPTION
**Pull request by lysnikolaou**
https://bugs.python.org/issue41132

### CODE REVIEW

**Review by ericvsmith — COMMENTED** [review]
LGTM

**Comment by pablogsal** [comment]
@lysnikolaou Manual backport party :tada:

**Comment by lysnikolaou** [comment]
> @lysnikolaou Manual backport party :tada: 

On it!

**Comment by pablogsal** [comment]
@lysnikolaou In general is preferable to wait for the PRs to land before closing the issue, so we don't forget to land them if something goes wrong, as closing the issue removes it from the front page and the main search

**Comment by lysnikolaou** [comment]
Oh, sorry! I thought it was ok to close the issue before landing the backport PRs, but you're right that it is a bit easier to forget things this way. Thanks for the advise! I'll do that in the future.

**Comment by pablogsal** [comment]
> Oh, sorry!

No worries! Is just that this has happened to us several times so I want to transfer the knowledge acquired from past mistakes :wink:

**Comment by ericvsmith** [comment]
> @lysnikolaou Manual backport party 🎉

Hah!

Thanks for all the work, @lysnikolaou and @pablogsal !

**Pull request merged**
