### PR TITLE
bpo-33131: Upgrade ensurepip to pip 10.0.1

### PR DESCRIPTION
**Pull request by pfmoore**
Pip 10 has been released - this upgrades the version in ensurepip to 10.0.1

https://bugs.python.org/issue33131

### CODE REVIEW

**Review by dstufft — APPROVED** [review]

**Comment by dstufft** [comment]
We should also backport this to all the relevant versions that are still accepting backports.

**Comment by pfmoore** [comment]
Agreed - thanks for the reminder. I had that on my list to do just before merge (it's just adding labels and letting the bot do its thing, I believe)

**Comment by ncoghlan** [comment]
Given the pip level API compatibility break, I think the main branches it would make sense to backport to are 2.7 and 3.7.

For 3.6.x, even though it's nominally still open to general bug fixes, I figure it makes sense to let folks decide for themselves if they want to stick with 9.0.x for now.

**Comment by ncoghlan** [comment]
The test failure is genuine - `ensurepip` currently relies on `pip.main` to let it run `pip` directly from the wheel archive without unpacking it to a temporary directory first.

**Comment by pfmoore** [comment]
@ncoghlan Yeah my bad. I saw it earlier, it's an easy fix just getting to it now.

**Comment by ned-deily** [comment]
If we're upgrading 2.7, we should upgrade 3.6, too.  Otherwise, 3.6 users are going to be harangued by pip upgrade messages.

**Comment by ncoghlan** [comment]
The bots can even cope if you miss that they already created the backport PR and mistakenly re-add the backport label. They're pretty cool :)

**Comment by pfmoore** [comment]
The bots are incredibly impressive. Genuinely feels like magic.

**Pull request merged**
