### PR TITLE
Make clear that lower priority numbers mean higher priority.

### PR DESCRIPTION
**Pull request by berdt**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by serhiy-storchaka** [comment]
Please open an issue on the tracker for discussing your changes.

The PR should be for the master branch (unless this issue already is resolved in master).

**Comment by rhettinger** [comment]
I'm happy with the edit so I don't think a tracker issue is necessary.

Please do make the PR against the master branch and then label as a backport to 3.6

**Comment by berdt** [comment]
I do not know how to do that so feel free to make the proper pull request yourself :)

**Comment by Mariatta** [comment]
I made a PR on master based on this, with slightly adjusted wording.
I'll close this. Thanks :)

**Comment by Mariatta** [comment]
My PR is at https://github.com/python/cpython/pull/4556

**Pull request closed without merging**
