### PR TITLE
bpo-19756: Change remote NNTP server to localhost server for most tests

### PR DESCRIPTION
**Pull request by berkerpeksag**
* Local server is based on the existing NNTPv2Handler class
* Reintegrate test_starttls() into NetworkedNNTPTestsMixin
* Only test_with_statement() talks to the remote NNTP_HOST now
* Make tests in NetworkedNNTPTestsMixin stricter, because the server
  responses are predetermined now
* Add mock comp.lang.python support to NNTPv1Handler.handle_GROUP()
* Add support for rejecting passwords in NNTPv1Handler.handle_AUTHINFO()
* New message number with non-UTF-8 message body for ARTICLE, HEAD, BODY, and
  non-UTF-8 subject for OVER, XOVER

Initial patch by Martin Panter.

https://bugs.python.org/issue19756

### CODE REVIEW

**Comment by mcepl** [comment]
What is the status of this PR? Was it already merged? Should it be merged?

**Comment by hugovk** [comment]
I think we can close this PR and its [old issue](https://github.com/python/cpython/issues/63955) because the nntplib module is deprecated in 3.11 and set for removal in 3.13?

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by mcepl** [comment]
@berkerpeksag Hi, I am trying to recreate nntplib as an independent module on https://sr.ht/~mcepl/nntplib/ . It [builds successfully](https://builds.sr.ht/~mcepl/job/734478) with the original code, but when I apply this PR (with some attempts to make it work for Python 3.10) https://git.sr.ht/~mcepl/nntplib/tree/testing-localhost [the test suite fails](https://builds.sr.ht/~mcepl/job/734482).

I have apparently got lost somewhere around the `TcpServer` class, but not sure where. Any ideas?

**Comment by AlexWaygood** [comment]
> I think we can close this PR and its [old issue](https://github.com/python/cpython/issues/63955) because the nntplib module is deprecated in 3.11 and set for removal in 3.13?
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

I agree. Given that this PR solely concerns tests, given that the PR has been open for nearly 3 years without activity, and given that the module has no active maintainer in the core dev team, I'm closing this PR as per [the policy in the dev guide](https://devguide.python.org/triaging/#python-triage-team).

**Pull request closed without merging**
