### PR TITLE
gh-83852: Clarify semantics of asyncio.wait with FIRST_COMPLETED/EXCEPTION

### PR DESCRIPTION
**Pull request by embray**
I had a couple (potential) bugs due to the assumption that when using `return_when=FIRST_COMPLETED` or `return_when=FIRST_EXCEPTION` the `done` set would contain only the first completed future.

I did however become suspicious that this may not be the case, and indeed it is not.  I wouldn't claim that this behavior is inconsistent with how the function is already documented, but I think it would be helpful to clarify this.

* Issue: gh-83852

### CODE REVIEW

**Comment by tirkarthi** [comment]
This seems to be related to https://bugs.python.org/issue39671

**Comment by embray** [comment]
Ah, I didn't see that issue. Thanks for pointing it out.

**Comment by willingc** [comment]
Hi @embray, Please sign the CLA and correct the failing Docs/Docs CI job. I will be happy to review after the changes are made. Thanks.

**Comment by willingc** [comment]
I'm going to go ahead and close this open PR as stale. The original issue has been closed and referenced to be addressed in a future asyncio tutorial. https://github.com/python/cpython/issues/83852#issuecomment-2181828513

Thanks @embray for the PR.

**Pull request closed without merging**
