### PR TITLE
bpo-37547: add _PyObject_CallMethodOneArg

### PR DESCRIPTION
**Pull request by jdemeyer**
https://bugs.python.org/issue37547

### CODE REVIEW

**Review by aeros — COMMENTED** [review]
In a similar theme to the proposed `CallMethodOneArg()` and existing `CallNoArg()`, `CallOneArg()`, and `CallMethodNoArgs()`, would it make sense to also have a  `VectorcallNoKws()`? There's several instances where `Vectorcall()` is being used with a null value for the kwnames argument. 

Edit: This would probably be in it's own separate PR and issue, not this one

**Comment by jdemeyer** [comment]
> There's several instances where `Vectorcall()` is being used with a null value for the kwnames argument.

There are only very few such use cases. It we would add another function in similar spirit, I think that `_PyObject_CallTwoArgs()` would make the most sense and that was rejected.

**Comment by methane** [comment]
> would it make sense to also have a `VectorcallNoKws()`?

No.  Passing `NULL` is not so hard, compared to `(PyObject*[]){self, arg}`.

**Comment by aeros167** [comment]
@jdemeyer @methane Thanks for the clarification.

**Pull request merged**
