### PR TITLE
[3.8] bpo-38304: Remove PyConfig.struct_size

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue38304

### CODE REVIEW

**Comment by vstinner** [comment]
If this change is merged, it should be forward-ported to the master branch.

**Comment by vstinner** [comment]
See https://mail.python.org/archives/list/python-dev@python.org/thread/C7Z2NA2DTM3DLOZCFQAK5A2WFYO3PHHX/ and https://bugs.python.org/issue38326 for the rationale and discussion.

**Review by pitrou — APPROVED** [review]
+1 from me. Leaves us time to discuss any further change without hurrying.

**Comment by vstinner** [comment]
> +1 from me. Leaves us time to discuss any further change without hurrying.

I'm a strong believer that a "stable ABI world" is possible... But we cannot implement everything today before 3.8.0rc1 final cut :-)

It seems like we need more time to properly design the overall use story "provide a stable ABI for embedded Python". PyConfig is just a small piece. I didn't notice that vim is directly linked to libpython3.7.so for example.

**Comment by pitrou** [comment]
The "struct size" field didn't define a stable ABI, so it's moot anyway.

**Comment by vstinner** [comment]
See also PR #16496: @ncoghlan proposes to replace struct_size with header_version.

**Review by ncoghlan — APPROVED** [review]
Thanks Victor. This update did convince that a stable embedding APi is more plausible than I previously thought it was, but just before an RC isn't the right time for us to be designing the initial pieces of that feature :)

**Pull request merged**
