### PR TITLE
bpo-40170: Move 3 NEWS entries to the C API section

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue40170

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @vstinner 

_skip issue_
_skip news_

**Comment by erlend-aasland** [comment]
Ref. https://github.com/python/cpython/pull/24553#issuecomment-780479231

**Comment by vstinner** [comment]
Merged, thanks.

**Comment by erlend-aasland** [comment]
Thank you, @vstinner

**Pull request merged**
