### PR TITLE
gh-116381: Specialize CONTAINS_OP

### LINKED ISSUE #116381: Specialize `CONTAINS_OP`
# Feature or enhancement

### Proposal:

I'll work on the following specializations:
* `list`
* `dict`
* `tuple`
* `set`
* `str`

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

_No response_

### Linked PRs
* gh-116385
* gh-116464

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Closes https://github.com/python/cpython/issues/116381

* Issue: gh-116381

### CODE REVIEW

**Review by gvanrossum — COMMENTED** [review]
LG (it's all just boilerplate :-) but I am curious about whether it makes any difference in perf. It doesn't strike me as all that common an operation, and I also don't think that we gain much here (just the dispatch via the type object, which for most of these ops isn't all that much compared to the actual work that the data type has to do to compute the result).

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
@Fidget-Spinner Sadly I forgot to check for warnings. On macOS I now get the following warnings:
```
In file included from Python/optimizer_analysis.c:380:
Python/optimizer_cases.c.h:1133:29: warning: variable 'right' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *right;
                            ^
Python/optimizer_cases.c.h:1134:29: warning: variable 'left' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *left;
                            ^
Python/optimizer_cases.c.h:1150:29: warning: variable 'right' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *right;
                            ^
Python/optimizer_cases.c.h:1151:29: warning: variable 'left' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *left;
                            ^
Python/optimizer_cases.c.h:1162:29: warning: variable 'right' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *right;
                            ^
Python/optimizer_cases.c.h:1163:29: warning: variable 'left' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *left;
                            ^
Python/optimizer_cases.c.h:1174:29: warning: variable 'right' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *right;
                            ^
Python/optimizer_cases.c.h:1175:29: warning: variable 'left' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *left;
                            ^
Python/optimizer_cases.c.h:1186:29: warning: variable 'right' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *right;
                            ^
Python/optimizer_cases.c.h:1187:29: warning: variable 'left' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *left;
                            ^
Python/optimizer_cases.c.h:1198:29: warning: variable 'right' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *right;
                            ^
Python/optimizer_cases.c.h:1199:29: warning: variable 'left' set but not used [-Wunused-but-set-variable]
            _Py_UopsSymbol *left;
                            ^
```
I suspect that the fix is to rename the args of those specialized ops to `unused`.

**Comment by Fidget-Spinner** [comment]
> This consumes quite a few tier 1 bytecodes, which is quite a limited resource. What is the advantage of this PR? I see no advantage in terms of performance for either tier 1 or tier 2.
> 
> We really shouldn't be merging performance PR without a solid justification. It doesn't have to be a clear improvement on pyperformance, but there must be some quantifiable improvement.

It helps propagate more information to tier 2.

**Comment by Fidget-Spinner** [comment]
Also you listed it in your TODO list. Unless you had in mind something with fewer specializations?

**Comment by markshannon** [comment]
Yes, I did. https://github.com/faster-cpython/ideas/issues/660.

**Pull request merged**
