### PR TITLE
[3.9] bpo-42057: Fix peephole optimizer

### PR DESCRIPTION
**Pull request by methane**
https://bugs.python.org/issue42057

### CODE REVIEW

**Comment by markshannon** [comment]
Looks good.
Could you add the following test to `test_peepholer.py`

```python
def test_42057():
    for i in range(10):
         try:
             raise Exception
         except Exception or Exception:
             pass
```

Putting the try-except in a loop causes a consistent crash due to stack underflow.

**Comment by methane** [comment]
Oh, I'm sorrry. I forget to push the requested test case.

**Comment by methane** [comment]
Ah! I had pushed it to python/cpython repository instead of my fork.

**Comment by methane** [comment]
#22878

**Pull request merged**
