### PR TITLE
gh-103180: Add CI timeouts to all GitHub Actions jobs

### PR DESCRIPTION
**Pull request by sobolevn**
See https://github.com/python/cpython/issues/103180#issuecomment-1502977283 on why I used the numbers I used.

Docs: https://docs.github.com/ru/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

* Issue: gh-103180

### CODE REVIEW

**Review by hugovk — APPROVED** [review]
Thanks for the analysis at https://github.com/python/cpython/issues/103180#issuecomment-1502977283.

We could probably skip timeouts for the short ones: timeouts tend to occur in the more complex and therefore slower ones, but I'm also fine adding them just in case.

**Comment by Ismaelkadir** [comment]
version https://git-lfs.github.com/spec/v1

**Comment by sobolevn** [comment]
@Ismaelkadir sorry, I don't understand your message :(

**Comment by Ismaelkadir** [comment]
> @Ismaelkadir sorry, I don't understand your message :(
> 

Ok otw

**Review by hauntsaninja — APPROVED** [review]
Thanks for doing this!

**Comment by sobolevn** [comment]
Do you want me to backport this to 3.11 as well?

**Comment by hugovk** [comment]
Yes please, could be useful there too :)

**Pull request merged**
