### PR TITLE
gh-95724: Clarify taskgroups.py license.

### PR DESCRIPTION
**Pull request by 1st1**
* Issue: gh-95724

### CODE REVIEW

**Review by gvanrossum — CHANGES_REQUESTED** [review]
Need the same for test_taskgroups.py

**Comment by gvanrossum** [comment]
@graingert Does this work for you?

**Comment by 1st1** [comment]
> Need the same for test_taskgroups.py

Done.

**Comment by gvanrossum** [comment]
LGTM but let's wait for @graingert (though not too long).

**Review by graingert — APPROVED** [review]
Yeah I think this is quite a bit more obvious

Maybe this is better?

```
# Adapted for use in CPython with permission from the EdgeDB project;
# license: PSFL
```

**Comment by gvanrossum** [comment]
@1st1 -- what do you think of Thomas's alternative? If that pleases you, just make it so and we can put this to rest (a backport to 3.11 should be fine since it's just a comment). If not, let us know and we'll just land this as you have it now.

**Comment by 1st1** [comment]
I think my version is more broad, but IANAL, and I'm kinda surprised that Thomas is. ;)

At least to my knowledge (and I have a bit of experience with this) my version is better so I'll just merge this PR as is.

**Comment by graingert** [comment]
> I think my version is more broad, but IANAL, and I'm kinda surprised that Thomas is. ;)
> 
> At least to my knowledge (and I have a bit of experience with this) my version is better so I'll just merge this PR as is.

I'm certainly not a lawyer!

**Pull request merged**
