### PR TITLE
gh-117636: Remove redundant type check in `os.path.join()`

### LINKED ISSUE #117636: Remove redundant type check in `os.path.join()`
# Feature or enhancement

### Proposal:

These type checks were introduced a long time ago in https://github.com/python/cpython/commit/5bfc03f430ab13ed84c2c30f2c87e9800b5670a4 and became redundant in https://github.com/python/cpython/commit/3f9183b5aca568867f37c38501fca63911580c66 with the addition of `os.fspath()`. They can be safely removed, slightly speeding up `os.path.join()` in the process:

```diff
 def join(path, *paths):
     path = os.fspath(path)
     if isinstance(path, bytes):
         sep = b'\\'
         seps = b'\\/'
         colon_seps = b':\\/'
     else:
         sep = '\\'
         seps = '\\/'
         colon_seps = ':\\/'
     try:
-        if not paths:
-            path[:0] + sep  #23780: Ensure compatible data type even if p is null.
```

```diff
 def join(a, *p):
     """Join two or more pathname components, inserting '/' as needed.
     If any component is an absolute path, all previous path components
     will be discarded.  An empty last part will result in a path that
     ends with a separator."""
     a = os.fspath(a)
     sep = _get_sep(a)
     path = a
     try:
-        if not p:
-            path[:0] + sep  #23780: Ensure compatible data type even if p is null.
```

I also noticed we're concatenating `b` to an empty string in `posixpath.join()` in case `path` has a length of 0. Which we can fix quite easily:

```diff
-if b.startswith(sep):
+if b.startswith(sep) or not path:
     path = b
-elif not path or path.endswith(sep):
+elif path.endswith(sep):
     path += b
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #117610

### Linked PRs
* gh-117638

### PR DESCRIPTION
**Pull request by nineteendo**
#### ntpath.py

<details><summary>script</summary>

```bat
::test.bat
@echo off
echo 1 item && python -m timeit -s "import before.ntpath" "before.ntpath.join('foo')" && python -m timeit -s "import after.ntpath" "after.ntpath.join('foo')"
echo 10 items && python -m timeit -s "import before.ntpath; paths = ['foo'] * 10" "before.ntpath.join(*paths)" && python -m timeit -s "import after.ntpath; paths = ['foo'] * 10" "after.ntpath.join(*paths)"
echo 100 items && python -m timeit -s "import before.ntpath; paths = ['foo'] * 100" "before.ntpath.join(*paths)" && python -m timeit -s "import after.ntpath; paths = ['foo'] * 100" "after.ntpath.join(*paths)"
```
</details>

```none
1 item
500000 loops, best of 5: 699 nsec per loop # before
500000 loops, best of 5: 648 nsec per loop # after
# -> 1.08x faster
10 items
50000 loops, best of 5: 5.48 usec per loop # before
50000 loops, best of 5: 5.52 usec per loop # after
# -> no difference
100 items
5000 loops, best of 5: 54.1 usec per loop # before
5000 loops, best of 5: 54 usec per loop # after
# -> no difference
```

#### posixpath.py

<details><summary>script</summary>

```shell
# test.sh
echo 1 item && python -m timeit -s "import before.posixpath" "before.posixpath.join('foo')" && python -m timeit -s "import after.posixpath" "after.posixpath.join('foo')"
echo 10 items && python -m timeit -s "import before.posixpath; paths = ['foo'] * 10" "before.posixpath.join(*paths)" && python -m timeit -s "import after.posixpath; paths = ['foo'] * 10" "after.posixpath.join(*paths)"
echo 100 items && python -m timeit -s "import before.posixpath; paths = ['foo'] * 100" "before.posixpath.join(*paths)" && python -m timeit -s "import after.posixpath; paths = ['foo'] * 100" "after.posixpath.join(*paths)"
```
</details>

```none
1 item
1000000 loops, best of 5: 335 nsec per loop # before
1000000 loops, best of 5: 271 nsec per loop # after
# -> 1.24x faster
10 items
50000 loops, best of 5: 3.43 usec per loop # before
100000 loops, best of 5: 3.35 usec per loop # after
# -> 1.02x faster
100 items
10000 loops, best of 5: 34.4 usec per loop # before
10000 loops, best of 5: 34.1 usec per loop # after
# -> no difference
```

* Issue: gh-117636

### CODE REVIEW

**Comment by nineteendo** [comment]
@serhiy-storchaka, you're the one who added this check, so you can probably best evaluate if it's still needed.

**Comment by serhiy-storchaka** [comment]
The first check was for cases like `join(None)` or `join(['a', 'b'])`. The second checks was for cases like `join('', b'a')`,  `join(b'', 'a')`,  `join(None, 'a')`, or something like this.

It seems that after adding `fspath()` they are no longer needed.

**Comment by nineteendo** [comment]
Apparently this unnecessary concatenation has been here since the first iteration of `posixpath`! So it wasn't even intended as a check:

https://github.com/python/cpython/blob/c636014c430620325f8d213e9ba10d925991b8d7/Lib/posixpath.py#L11-L14

**Review by hauntsaninja — APPROVED** [review]
Thank you!

**Comment by nineteendo** [comment]
@serhiy-storchaka, can this be merged?

**Pull request merged**
