### PR TITLE
Added TelegramHandler to logging module 

### PR DESCRIPTION
**Pull request by snaiffer**
Suggest to add TelegramHandler to logging module. It has been necessary for my project to send some important messages to my Telegram chat. So I could more quickly notice any problems.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by asvetlov** [comment]
-10

1. The proposal is a subject for third party library on PyPI
2. `requests` is external library, not part of batteries
3. Sending HTTP POST on every log record kills performance

Missing test and documentation update is very minor problems after issues mentioned above.

**Comment by snaiffer** [comment]
Then why do we have SMTPHandler ?
From your point of view, it also could be moved to third party library. 
What about performance: it's of course bad idea to send any low-level log information via HTTP, but the idea of TelegramHandler to inform about error and fatal cases quickly. Such kinds of messages shouldn't be a lot.

**Comment by asvetlov** [comment]
`SMTPHandler` uses stdlib only (`smtplib` and `email`) and has unittests.
Also it was added in 2002, when pip was not exist and installing third party libraries was very complex procedure.

**Pull request closed without merging**
