### PR TITLE
bpo-38449: Revert "bpo-22347: Update mimetypes.guess_type to allow oper parsing of URLs (GH-15522)"

### PR DESCRIPTION
**Pull request by maxking**
This reverts commit 87bd2071c756188b6cd577889fb1682831142ceb.

https://bugs.python.org/issue38449

Automerge-Triggered-By: @maxking

### CODE REVIEW

**Review by yarikoptic — COMMENTED** [review]
Could a unit test been added to verify (current and future) correct operation on a file name with `;` and may be other tricky symbols legit to be in a file name but not a URL?

**Comment by maxking** [comment]
@yarikoptic This is just reverting the previous change which caused the regression so release managers can pick this up for the final releases.

Fixes and more unit tests should be best added in the next PR which should fix the original issue and the issue raised in bpo-38449.

**Review by ned-deily — CHANGES_REQUESTED** [review]
LGTM, except it needs a news (blurb) entry about the revert since it introduces a change between 3.8.0rc1/3.7.5rc1 and 3.8.0final/3.7.5final.

**Comment by maxking** [comment]
I have made the requested changes; please review again

**Review by ned-deily — APPROVED** [review]

**Pull request merged**
