### PR TITLE
Delete leftover clinic-generated file for C zipimport.

### PR DESCRIPTION
**Pull request by gnprice**
This module was rewritten into pure Python in commit 79d1c2e6c, and
both Modules/zipimport.c and Modules/clinic/zipimport.c.h were
deleted in that commit.

Then a little later, 4a934d490 edited the Argument Clinic script and
made a sweep through its generated files; and it added back a version
of Modules/clinic/zipimport.c.h , presumably by accident.

Nothing includes this file, so it hasn't been having any effect,
but it is a bit confusing.  Clean it up.

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by gnprice** [comment]
Thanks @serhiy-storchaka !

I'm betraying my ignorance of the workflow here, but: what's the next step to merge this? Do you hit the merge button, or does something auto-merge it under certain conditions?

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @gnprice!

Yes, I just waited until the CI tests be passed before hitting the merge button. I was busy yesterday, so do it today.

**Comment by gnprice** [comment]
> Yes, I just waited until the CI tests be passed before hitting the merge button. I was busy yesterday, so do it today.

Got it. Perfectly sensible, and thanks for the help understanding the workflow!

**Comment by gnprice** [comment]
(It seems like the pattern is: backport cherry-picks get auto-merged once they're approved and the CI passes. But original PRs to master don't -- a human must merge them. Is that right?

I think I'd seen the former happen on some PRs and so knew that a bot sometimes auto-merged things, but hadn't quite twigged that "backport vs. original non-backport" was the key variable in the pattern.

Anyway, thanks again for your help, and for merging!)

**Pull request merged**
