### PR TITLE
bpo-40959: Remove unused and unneeded declarations from sqlite3 headers

### PR DESCRIPTION
**Pull request by erlend-aasland**
I guess skipping NEWS is ok for this one.

https://bugs.python.org/issue40959

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@berkerpeksag If you feel I'm flooding you with PR's/code reviewing, please let me know. Also, I might have missed a point or two in the devs guide, so if I'm proceeding with PR's/issues in a totally incorrect matter, feel free to point me in the right direction.

**Comment by erlend-aasland** [comment]
FYI, rebased onto master

**Comment by erlend-aasland** [comment]
@corona10 would you mind reviewing this? It's a straight-forward cleanup of the `_sqlite3` header files:
- remove function declarations for functions that are not used by other .c files
- remove function declarations for functions that don't exist anymore

Diffstat:
```
 Modules/_sqlite/cache.h            |  5 -----
 Modules/_sqlite/connection.h       |  7 -------
 Modules/_sqlite/cursor.h           | 10 ----------
 Modules/_sqlite/prepare_protocol.h |  3 ---
 Modules/_sqlite/statement.h        |  1 -
 5 files changed, 26 deletions(-)
```

**Review by berkerpeksag — APPROVED** [review]
LGTM! Could you please fix merge conflicts?

**Comment by erlend-aasland** [comment]
> LGTM! Could you please fix merge conflicts?

Sure. 2 sec...

**Review by berkerpeksag — APPROVED** [review]
LGTM!

**Pull request merged**
