### PR TITLE
getpass: update docstring

### PR DESCRIPTION
**Pull request by ghost**
EasyDialogs was removed in 3.x.
ff47a133e1eee9dab60b86fb0d56ccd1022f841a

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least a day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Review by vstinner — APPROVED** [review]

**Comment by vstinner** [comment]
Thanks for your contribution, but please sign the CLA ;-) https://www.python.org/psf/contrib/contrib-form/

**Comment by ghost** [comment]
@the-knights-who-say-ni I have completed the above steps.

**Comment by zhangyangyu** [comment]
Does this backport?

**Pull request merged**
