### PR TITLE
bpo-43894: Editor reformat

### PR DESCRIPTION
**Pull request by E-Paine**
https://bugs.python.org/issue43894

### CODE REVIEW

**Comment by E-Paine** [comment]
I presume this doesn't need a news entry, but I am happy to added one if necessary.

**Comment by E-Paine** [comment]
Following the changes proposed in #25479, I would like a little more time on this PR before review (no point commenting on exactly the same things).

**Comment by terryjreedy** [comment]
OK, say when done.

**Comment by E-Paine** [comment]
@terryjreedy I think this is ready now. I would appreciate your particular scrutiny of where I have added an explicit check for `is (not) None`, as I had to revert a few because they caused issues during testing (despite me thinking I checked they were safe...).

**Comment by terryjreedy** [comment]
Can you describe the 'issues'?  Could you have uncovered a bug?  Or are you really convinced that your initial thought was wrong?

**Comment by E-Paine** [comment]
Sorry, just things like passing a blank string to tkinter and so getting an error. This was a regression with my change (a blank string would be treated as false but my `is not None` would evaluate to true) and has been reverted.

**Comment by E-Paine** [comment]
Given that it is highly unlikely this is going to be merged (at least in the current form), I am closing this PR. I will leave the issue on bpo open for now.

**Comment by terryjreedy** [comment]
Yes, leave issue open.  My quick review is that I eventually want most but not all of the changes.  (In particular, "Return xyz." is a legal docstring.)  Some of the changes I would like one type at a time.  There is an existing issue with more tests that is probably about ready to merge once I review it.  But working on shell indents and sidebar now.  So wait until I ask for something in particular.

**Pull request closed without merging**
