### PR TITLE
bpo-29523: Update setuptools to 34.2.0 and bundle its dependencies.

### PR DESCRIPTION
**Pull request by stratakis**
setuptools as of version 34.0.0, unbundled its dependencies and it started
depending on them, so in order to update the, bundled with python, setuptools
we also need to bundle its dependencies: pyparsing, packaging, appdirs and six.

See also: https://setuptools.readthedocs.io/en/latest/history.html#v34-0-0

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in "Your Details" at b.p.o
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least a day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by stratakis** [comment]
Relevant issue: https://bugs.python.org/issue29523

Added also my github username to bpo, hopefully the bot will update the CLA label.

**Comment by stratakis** [comment]
Also I think this change should be made as well for the 3.6 branch (maybe 3.5 as well?).

**Review by dstufft — CHANGES_REQUESTED** [review]
I'm generally against this change, and would prefer to instead wait for pip to implement PEP 518 which will allow us to remove setuptools from being bundled at all (See https://github.com/pypa/pip/pull/4144).

**Comment by pfmoore** [comment]
I'm also reluctant to do this. It seems too likely that people will start to assume that the unbundled dependencies (six, appdirs, ...) are shipped with Python, and not specify their own dependencies correctly.

**Comment by stratakis** [comment]
@dstufft Your point is quite reasonable from the upstream point of view.

As a downstream packager where setuptools is being unbundled and the system one is being used (thus updating it now means breakage due to missing wheels as is now), I'll have to follow this approach until PEP 518 is implemented.

Anyway feel free to close it if you disagree with the changes, I'll have to carry the patch downstream to fix the current Fedora issues but it can be removed later on.

**Comment by jaraco** [comment]
I don't see any reason not to accept this contrib. It helps align with the current known state of affairs. When PEP 518 lands, this code can be readily replaced with the PEP 518 solution and until then, ensurepip isn't blocked from working with the latest setuptools versions. I don't think anyone here sees this change as a precedent or reason not to adopt PEP 518.

> people will start to assume that the unbundled dependencies (six, appdirs, ...) are shipped with Python

I really doubt it. First off, you have to `ensurepip`, so it doesn't come with Python by default. But more importantly, most users currently upgrade pip and setuptools to install packages, so will end up with these packages installed anyway in virtualenvs and system envs. So if the presence of these packages is going to lead to incomplete dependency declarations, that risk is already present. Even so, these issues will shake out in short order when setuptools and pkg_resources aren't a standard dependency.

**Comment by zooba** [comment]
I'm against this PR too. In chatting with people at PyCon, many were shocked that `setuptools` is not guaranteed to be installed by default (mostly on Windows/Mac) and might be removed in the future, and if we add more packages then it will cause further angst when/if we remove those.

Though since [PEP 518 has been merged](https://github.com/pypa/pip/pull/4144), presumably the next release of pip will be good to embed without setuptools?

**Comment by stratakis** [comment]
Setuptools is bundling its dependencies again [0] as of version 36.0.0. Closing this PR.

[0] https://github.com/pypa/setuptools/issues/980#issuecomment-305042868

**Pull request closed without merging**
