### PR TITLE
bpo-44324: Error message gives "expected an expression" when nothing is given during an assignment

### PR DESCRIPTION
**Pull request by CCLDArjun**
https://bugs.python.org/issue44324

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@CCLDArjun

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by CCLDArjun** [comment]
I've signed the cla already, just waiting for Ewa Jodlowska to add me to the list I guess.

**Review by pablogsal — CHANGES_REQUESTED** [review]
This has several problems:

* The rule needs to be named "invalid_" so it doesn't run in the first pass.

* This rule is very limited as only is able to identify missing expressions at the end of a line. It doesn't work with things like `f(x, y= , a)`

* The rule is not covering all possibilities of the target in the left-hand side or taking into account start targets of multi-assigment.

* You are duplicating the  symbols. IIRC we have rules for the augmented operators already

* This doesn't work with chained expressions like `x = y =`

* Assignment is just a dimension of the problem. For instance, an expression may be missing in many other places such as `x == `. This would need a much more generic solution.

**Comment by pablogsal** [comment]
Thanks @CCLDArjun for the effort and for thinking about this problem, but unfortunately this is not resilient enough. Is I mentioned in BPO, this rule is very difficult to get right in a generic way and in my opinion is not that common to justify the cost

**Pull request closed without merging**
