### PR TITLE
bpo-42588: Update static_order method docs

### PR DESCRIPTION
**Pull request by akulakov**
This PR is based on the suggested clarification of the docs by Ran Benita (see the issue comments).

https://bugs.python.org/issue42588

### CODE REVIEW

**Review by nanjekyejoannah — COMMENTED** [review]
Do we really need a news entry for this?

**Comment by akulakov** [comment]
@nanjekyejoannah it probably does not, I wasn't quite sure -- I can remove if you think so.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks @nanjekyejoannah for the review and thanks @akulakov  for the PR! 🚀

**Comment by akulakov** [comment]
@nanjekyejoannah thanks for reviewing :)

**Pull request merged**
