### PR TITLE
gh-103578: Fix pdb reading code with non-utf8 encoding

### PR DESCRIPTION
**Pull request by gaogaotiantian**
`pdb` should use `io.open_code` to open code to avoid encoding issue.

* Issue: gh-103578

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Thanks for this PR!

We should probably mention in the news entry that because we use `io.open_code`, we'll now trigger auditing ~events~ hooks

**Comment by gaogaotiantian** [comment]
> Thanks for this PR!
> 
> We should probably mention in the news entry that because we use `io.open_code`, we'll now trigger auditing events

`io.open()` also raise auditing events. According to the [docs](https://docs.python.org/3/library/io.html#io.open_code),

> However, assuming that path is a str and an absolute path, open_code(path) should always behave the same as open(path, 'rb')

`io.open_code()` should behave the same as `io.open(path, 'rb')`, so is there an auditing event difference?

**Comment by hauntsaninja** [comment]
Ah, I meant the `PyFile_SetOpenCodeHook()` hook from PEP 578. I'm not sure what the best phrase is, but it was described as auditing hook in https://github.com/python/cpython/pull/17127 ... that PR got regressed in #26992, this PR fixes :-)

**Comment by gaogaotiantian** [comment]
So it seems like changing it to `io.open_code()` makes it possible to call into the hook set by ``PyFile_SetOpenCodeHook()``? Is that something expected in the news entry?

**Comment by hauntsaninja** [comment]
Yup! I think can't hurt to mention it in the news entry, since it is a change in behaviour and one that seems potentially noteworthy.

**Comment by gaogaotiantian** [comment]
> Yup! I think can't hurt to mention it in the news entry, since it is a (good) change in behaviour and one that seems potentially noteworthy.

I updated the news entry. Let me know if you think that requires extra polish!

**Review by hauntsaninja — APPROVED** [review]
Looks great, thanks!

**Comment by zooba** [comment]
No backport needed - this was fine in 3.8-3.10 and was regressed in 3.11.

**Pull request merged**
