### PR TITLE
gh-102137: Update turtle docs to rename wikipedia demo to rosette

### PR DESCRIPTION
**Pull request by SectorCorruptor**
# gh-102137

### CODE REVIEW

**Review by hugovk — APPROVED** [review]
Thank you for the issue and your PR!

**Comment by UndoneStudios** [comment]
Just one question: how long will it be before the docs update?

**Comment by hugovk** [comment]
They update once per day, so it should be live tomorrow.

You can see the "Last updated on Feb 22, 2023" at the bottom of the page.

https://docs.python.org/3/library/turtle.html

**Comment by UndoneStudios** [comment]
> They update once per day, so it should be live tomorrow.
> 
> You can see the "Last updated on Feb 22, 2023" at the bottom of the page.
> 
> https://docs.python.org/3/library/turtle.html

About the link you attached, it seems the update is on 3.12, not 3.11. Which I understand mainly as this GitHub repo is for 3.12, not 3.11.

**Comment by hugovk** [comment]
This repo is for all versions, we use different branches for different versions. (More info about the branches at https://devguide.python.org/versions/)

* So the default branch `main` is currently for the upcoming 3.12, with docs at https://docs.python.org/3.12/library/turtle.html

* There's a `3.11` branch for current stable version, with docs at https://docs.python.org/3/library/turtle.html (and https://docs.python.org/3.11/library/turtle.html)

* And then also `3.10` with docs at https://docs.python.org/3.10/library/turtle.html

After I merged your fix to `main` = 3.12, I also "backported" it to `3.11` and `3.10`, so we can now see it on 3.10 and 3.12 (both "Last updated on Feb 22, 2023"), and it should on 3.11 within a few hours (it's still "Last updated on Feb 22, 2023").

**Comment by UndoneStudios** [comment]
Also totally unrelated pointout: for `penrose`, in 3.11 docs, the description should be 
>a periodic tiling with kites and darts

not 

>aperiodic tiling with kites and darts

**Comment by hugovk** [comment]
"aperiodic" is correct here, see [Wikipedia](https://en.wikipedia.org/wiki/Penrose_tiling):

> A **Penrose tiling** is an example of an [aperiodic tiling](https://en.wikipedia.org/wiki/Aperiodic_tiling). Here, a tiling is a covering of [the plane](https://en.wikipedia.org/wiki/Two-dimensional_space) by non-overlapping polygons or other shapes, and _aperiodic_ means that shifting any tiling with these shapes by any finite distance, without rotation, cannot produce the same tiling.

**Pull request merged**
