### PR TITLE
bpo-46178: remove unusued `.travis.yml` file

### PR DESCRIPTION
**Pull request by sobolevn**
We now use GitHub Actions.

Permanent link for the last version of this file: https://github.com/python/cpython/blob/078abb676cf759b1e960f78390b6e80f256f0255/.travis.yml
Last Travis builds (6 month ago): https://app.travis-ci.com/github/python/cpython/builds

https://bugs.python.org/issue46178

### CODE REVIEW

**Comment by sobolevn** [comment]
CC @tiran

**Review by zware — APPROVED** [review]
I'm not sure this even needs a NEWS entry, but LGTM.

**Comment by sobolevn** [comment]
Agreed, removed NEWS 🙂

**Comment by sobolevn** [comment]
@Mariatta this is the last PR in this series. 
Sorry for a lot of pings! 🙂 

And Happy New Year.

**Review by Mariatta — APPROVED** [review]
Thanks!

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/30309 for some extra Travis bits and pieces.

**Pull request merged**
