### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by tnqn**

### CODE REVIEW

**Comment by willingc** [comment]
Thanks @tnqn for the PR. 

@vstinner What is the general feeling for PRs in the C code that are correct typos in comments? Merge or defer and update the comments when the underlying C code changes? Thanks.

**Comment by vstinner** [comment]
> @vstinner What is the general feeling for PRs in the C code that are correct typos in comments?

Merge them :-)

**Review by vstinner — APPROVED** [review]
LGTM.

@willingc: Do you want to merge it?

**Comment by vstinner** [comment]
Thanks @tnqn, I merged your PR!

**Comment by willingc** [comment]
Thanks @tnqn for the PR and @vstinner for following up and the merge. :cake:

**Comment by vstinner** [comment]
> Hi! The buildbot AMD64 Windows7 SP1 3.x has failed when building commit 3bd0d62.

The failure is unrelated to this PR.

**Pull request merged**
