### PR TITLE
Docs: shutil: Hide module name from local (anchor) links

### PR DESCRIPTION
**Pull request by aureliojargas**
Inside all the methods descriptions, local links to other `shutil` methods do not show the module name.

For example, it's: 

- copy2() uses copystat() to copy the file metadata.

not:

- **shutil**.copy2() uses **shutil**.copystat() to copy the file metadata.

This commit fixes the very few outliers that were not following that pattern.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Comment by aureliojargas** [comment]
I've signed the CLA.

No issue number since this is a very simple documentation fix.

No news entry is necessary.

**Comment by BoboTiG** [comment]
Thanks @aureliojargas! Do you mind updating you branch to resolve the conflict?

**Comment by aureliojargas** [comment]
Done. Tests are green again.

**Review by csabella — APPROVED** [review]

**Comment by csabella** [comment]
@aureliojargas Thank you for the suggestion and the pull request.  Your change has now been merged.  :tada: :tada:

**Pull request merged**
