### PR TITLE
bpo-13601: Mention stderr's line buffering in What's New

### PR DESCRIPTION
**Pull request by hauntsaninja**
https://bugs.python.org/issue13601

Automerge-Triggered-By: @gvanrossum

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Alternative, terser phrasing from sys.rst:
> Non-interactive stderr is now line-buffered instead of fully buffered.

I gave credit based on https://github.com/python/cpython/pull/17646/files#diff-c32d9a73be8db9e122317d9c23b6c0da — not sure if anyone else should be credited.

**Comment by hauntsaninja** [comment]
cc @gvanrossum

**Review by gvanrossum — APPROVED** [review]
There's one subtle point. This really only applies to the *initial* value of `sys.stderr`. If you assign something else to `sys.stderr` its buffering isn't magically going to change. But I'm not sure that most readers of this document would appreciate the extra words we'd need to add to make this distinction (since few people ever assign anything to `sys.stderr`), and to more advanced readers this would be obvious.

**Comment by gvanrossum** [comment]
Thinking about it some more, the place to note that subtle point would've been the Misc/NEWS entry for the original PR, and since that didn't, let's say we won't need it here. So I'll mark this as automerge and go to bed.

**Comment by hauntsaninja** [comment]
The "defaults to" phrasing helps hedge that (and `-u`), too, since if you assign to `sys.stderr` you aren't using the default.

**Pull request merged**
