### PR TITLE
bpo-33875: Add optional passwordeval field for pypirc server configuration.

### PR DESCRIPTION
**Pull request by jperras**
Allows for calling an arbitrary external program, e.g. `gpg`, so that a cleartext password is not necessary in the distutils `.pypirc` server configuration file sections.

https://bugs.python.org/issue33875?

https://bugs.python.org/issue33875

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by jperras** [comment]
I have e-signed the CLA.

**Comment by jperras** [comment]
Judging from the build failure, it seems as though the `passwordeval` feature availability should be made dependent upon the availability of this functionality?

**Comment by merwok** [comment]
subprocess is always present in the standard library, but not available during the build of Python itself that uses distutils.  This is fixed by moving the import to the function that needs it.

**Comment by jperras** [comment]
Hm, I'm running into a bit of an impasse as to how best ensure the test for this can function on Windows; I lack any experience with that operating system, sadly, and am unsure as to what would be considered a valid test for this feature.

Should the test have separate cases for Windows vs. *nix?

**Comment by merwok** [comment]
I think the idea should have more discussion on the ticket or python-ideas first!
(Sorry I didn’t have time to comment on the ticket yet)

**Comment by jperras** [comment]
@merwok Of course - pardon my eagerness and lack of knowledge with regards to the typical process for adding a feature such as this. I'm happy to participate wherever the discussion would be most useful.

**Comment by merwok** [comment]
No need to apologise! :)

Here the context is special as distutils has a ton of backward compat issues, we have setuptools that’s mostly installed everywhere and can ship features faster to users, there is a keyring extension that integrates with distutils or setuptools, but also the PyPA recommends using twine and not setup.py upload, so it’s not a simple feature addition like it could be in other parts of the stdlib.

**Pull request closed without merging**
