### PR TITLE
Fix some deprecation warnings in Doc/conf.py

### PR DESCRIPTION
**Pull request by refi64**
*crosses fingers* (My crappy computer never finishes building the docs, so let's see how far Travis goes...)

### CODE REVIEW

**Comment by vstinner** [comment]
I guess that it's related to my bug report http://bugs.python.org/issue29527

See also my PR #7.

**Comment by methane** [comment]
Travis uses newest Sphinx.
But docs.python.org seems using sphinx-1.3.3. (see footer in https://docs.python.org/3/).

So changing `latex_paper_size` should be done after docs.python.org update.

**Comment by refi64** [comment]
@methane `latex_paper_size` has been [depreciated since Sphinx 0.5](http://www.sphinx-doc.org/en/stable/config.html#confval-latex_paper_size), when `latex_elements` was introduced. This shouldn't cause any problems unless someone has updated their Sphinx version since 2008.

**Review by methane — APPROVED** [review]
You're right. Thanks.

**Pull request merged**
