### PR TITLE
gh-123418: Update OpenSSL to 3.0.15 on Windows

### PR DESCRIPTION
**Pull request by zware**
* Issue: gh-123418

### CODE REVIEW

**Comment by sethmlarson** [comment]
@zware These tags don't exist yet in the source-deps and bin-deps repositories, shall I create pull requests updating those places?

**Comment by zware** [comment]
> @zware These tags don't exist yet in the source-deps and bin-deps repositories, shall I create pull requests updating those places?

Right; I probably should have marked this as a draft :).  Those updates will need to happen first; @zooba has historically been the only one able to update the binary builds, but if you have that capability now please go ahead!

**Comment by zooba** [comment]
Theoretically any of the release managers can do the builds now, but I'm on, so I'll do it.

**Comment by zooba** [comment]
The tag is updated so I restarted the CI checks.

**Comment by sethmlarson** [comment]
@zware Since the dependency was updated the SBOM also needs to be regenerated, either run `make regen-sbom` locally or apply this diff to `Misc/externals.spdx.json`:

```
diff --git a/Misc/externals.spdx.json b/Misc/externals.spdx.json
index 758d4191005..f7aea9e8f99 100644
--- a/Misc/externals.spdx.json
+++ b/Misc/externals.spdx.json
@@ -70,21 +70,21 @@
       "checksums": [
         {
           "algorithm": "SHA256",
-          "checksumValue": "e6a77c273ebb284fedd8ea19b081fce74a9455936ffd47215f7c24713e2614b2"
+          "checksumValue": "1550c87996a0858474a9dd179deab2c55eb73726b9a140b32865b02fd3d8a86b"
         }
       ],
-      "downloadLocation": "https://github.com/python/cpython-source-deps/archive/refs/tags/openssl-3.0.13.tar.gz",
+      "downloadLocation": "https://github.com/python/cpython-source-deps/archive/refs/tags/openssl-3.0.15.tar.gz",
       "externalRefs": [
         {
           "referenceCategory": "SECURITY",
-          "referenceLocator": "cpe:2.3:a:openssl:openssl:3.0.13:*:*:*:*:*:*:*",
+          "referenceLocator": "cpe:2.3:a:openssl:openssl:3.0.15:*:*:*:*:*:*:*",
           "referenceType": "cpe23Type"
         }
       ],
       "licenseConcluded": "NOASSERTION",
       "name": "openssl",
       "primaryPackagePurpose": "SOURCE",
-      "versionInfo": "3.0.13"
+      "versionInfo": "3.0.15"
     },
     {
       "SPDXID": "SPDXRef-PACKAGE-sqlite",
```

**Review by sethmlarson — APPROVED** [review]

**Pull request merged**
