### PR TITLE
[3.8] gh-115349: Pin theme to fix code snippets (GH-115351)

### PR DESCRIPTION
**Pull request by ambv**
Pin theme to fix code snippets
(cherry picked from commit 3fcea416f8261790ce700c52c4262ccb668716d6)

* Issue: gh-115349

### CODE REVIEW

**Review by hugovk — APPROVED** [review]
Built locally:

image

**Comment by ambv** [comment]
@hugovk I appreciate it but this was about the dark theme, no?

**Comment by hugovk** [comment]
Yes, we're pinning to the last version _before_ the dark theme was added.

This the minimal fix, because the dark theme requires Sphinx 3 for proper syntax highlighting, and the 3.8/3.9 docs use Sphinx 2.4.4.

We can look into bumping Sphinx to 3+, but it will likely also require bumping other dependencies, and for security branches I felt it would be easier/safer to pin to an older python-docs-theme.

**Comment by ambv** [comment]
Ah, got it. Right. Okay then, let's go.

**Pull request merged**
