### PR TITLE
Bump test deps: `ruff` and `pre-commit-hooks`

### PR DESCRIPTION
**Pull request by sobolevn**
Release post: https://astral.sh/blog/ruff-v0.1.0

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Want to do the ones in https://github.com/python/cpython/blob/main/Tools/requirements-dev.txt at the same time?

**Review by AlexWaygood — APPROVED** [review]
thanks!

**Comment by AlexWaygood** [comment]
@hugovk, reckon we should backport this? We backported #110933, but we didn't backport #110175

**Comment by hugovk** [comment]
Yes, let's backport these things.

**Comment by sobolevn** [comment]
I will do the backports manually :)

**Pull request merged**
