### PR TITLE
bpo-40246: Report a different error message for invalid string prefixes

### PR DESCRIPTION
**Pull request by lysnikolaou**
https://bugs.python.org/issue40246

### CODE REVIEW

**Comment by lysnikolaou** [comment]
CC: @pablogsal @gvanrossum

**Review by gvanrossum — APPROVED** [review]
LGTM. One other core dev please?

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by pablogsal** [comment]
Great job @lysnikolaou 🎉

**Pull request merged**
