### PR TITLE
gh-125660: Python implementation of `json.loads()` accepts invalid unicode escapes

### PR DESCRIPTION
**Pull request by nineteendo**
This condition in `json.decoder` is insufficient:

https://github.com/python/cpython/blob/f203d1cb52f7697140337a73841c8412282e2ee0/Lib/json/decoder.py#L61

```python
>>> import sys
>>> sys.modules["_json"] = None
>>> import json
>>> json.loads(r'["\u 000", "\u-000", "\u+000", "\u0_00"]')
['\x00', '\x00', '\x00', '\x00']
```

* Issue: gh-125660

### CODE REVIEW

**Review by ZeroIntensity — APPROVED** [review]
For other reviewers, see also: #125687

I think this is fine, but per @taleinat, this shouldn't get backported--it's technically a very minor breaking change.

**Comment by taleinat** [comment]
> I think this is fine, but per @taleinat, this shouldn't get backported--it's technically a very minor breaking change.

After further consideration, I do consider this to be a clear bugfix, which should be backported to versions in "bugfix" status.

**Comment by ZeroIntensity** [comment]
Are you sure? I'm not certain what policy PyPy, IronPython, Jython, etc. have for changes that we backport, but point of pure-Python modules was almost exclusively for other Python implementations--I don't want to accidentally cause any surprises.

**Comment by taleinat** [comment]
> Are you sure?

No, I am not sure, I've been away from Python development for several years. I would be good to get another core dev's perspective.

**Comment by taleinat** [comment]
Upon further consideration, yes, the chance of breaking something with a backport is large relative to the likely pain caused by the current, buggy, state. Let's avoid backporting.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. :+1:

**Comment by serhiy-storchaka** [comment]
This is clearly a bug. `json.loads()` can be a part of validation. If it accepts an invalid JSON, it can fail later, in other program with more strict JSON parser. I do not think that anybody depends on such buggy behavior.

**Pull request merged**
