### PR TITLE
Docs: amend note about incompatible dbm file formats

### PR DESCRIPTION
**Pull request by erlend-aasland**
----
📚 Documentation preview 📚: https://cpython-previews--114597.org.readthedocs.build/

### CODE REVIEW

**Comment by erlend-aasland** [comment]
This PR tries to address @serhiy-storchaka's concerns in https://github.com/python/cpython/pull/114549#discussion_r1467480343

**Review by ezio-melotti — APPROVED** [review]

**Review by serhiy-storchaka — COMMENTED** [review]
My concern is that the definition of `incompat_note` is far from its use. So the text of the note can be de-synchronized with the text to which it relates, especially if it is not identical in both cases.

**Comment by erlend-aasland** [comment]
> My concern is that the definition of `incompat_note` is far from its use. So the text of the note can be de-synchronized with the text to which it relates, especially if it is not identical in both cases.

Would it help if we named the placeholder `ndbm_gdbm_incompat_note` instead of `incompat_note`?

**Review by serhiy-storchaka — DISMISSED** [review]

**Comment by serhiy-storchaka** [comment]
Sorry, wrong PR.

**Comment by serhiy-storchaka** [comment]
The text of the note is related to the text of one or two paragraphs before it, which are different. It just happens that the text of this one sentence is the same in both cases. But if we reword the previous paragraphs, the text of the note should be reworded as well. First of all it should be consistent with the words in the same section, and only after this with a similar note in other section.

**Pull request closed without merging**
