### PR TITLE
bpo-29933: improving set_write_buffer_limits description

### PR DESCRIPTION
**Pull request by kojoidrissa**
Improved the description of the high and low parameters for set_write_buffer_limits. Also fixed a small grammatical issue.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks @kojoidrissa and congrats on your first contribution to CPython :tada: 
Can you backport this to 3.6 and 3.5 branches? 

If you have Python 3.6 installed, then you can use [cherry_picker.py ](https://github.com/python/core-workflow/tree/master/cherry_picker)

**Comment by vstinner** [comment]
>  Can you backport this to 3.6 and 3.5 branches?

Can someone please backport these changes? @kojoidrissa maybe?

**Comment by kojoidrissa** [comment]
I'm getting ready to travel internationally. I'll look into it this weekend.

**Pull request merged**
