### PR TITLE
gh-93820: Pickle enum.Flag by name

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
#93820.

### CODE REVIEW

**Comment by tiran** [comment]
A Flag instance with multiple members is serialized like this:

```
>>> (re.A | re.I | re.DOTALL | 0x1000).__reduce_ex__(1)
(<built-in function or_>, (re.ASCII, re.IGNORECASE|re.DOTALL|0x1000))
```

It looks like only the first member is reduced by name.

**Comment by serhiy-storchaka** [comment]
The rest is reduced recursively.
```
>>> pickletools.dis(pickletools.optimize(pickle.dumps(re.A | re.I | re.DOTALL | 0x1000, protocol=3)))
    0: \x80 PROTO      3
    2: c    GLOBAL     '_operator or_'
   17: q    BINPUT     0
   19: c    GLOBAL     'builtins getattr'
   37: q    BINPUT     1
   39: c    GLOBAL     're RegexFlag'
   53: q    BINPUT     2
   55: X    BINUNICODE 'ASCII'
   65: \x86 TUPLE2
   66: R    REDUCE
   67: h    BINGET     0
   69: h    BINGET     1
   71: h    BINGET     2
   73: X    BINUNICODE 'IGNORECASE'
   88: \x86 TUPLE2
   89: R    REDUCE
   90: h    BINGET     0
   92: h    BINGET     1
   94: h    BINGET     2
   96: X    BINUNICODE 'DOTALL'
  107: \x86 TUPLE2
  108: R    REDUCE
  109: h    BINGET     2
  111: M    BININT2    4096
  114: \x85 TUPLE1
  115: R    REDUCE
  116: \x86 TUPLE2
  117: R    REDUCE
  118: \x86 TUPLE2
  119: R    REDUCE
  120: \x86 TUPLE2
  121: R    REDUCE
  122: .    STOP
highest protocol among opcodes = 2
```

**Comment by tiran** [comment]
``copy.copy`` does not recurse. Is that ok?

```
>>> copy.copy(re.A | re.I | re.DOTALL | 0x1000)
re.ASCII 4114
re.ASCII|re.IGNORECASE|re.DOTALL|0x1000
>>> copy.deepcopy(re.A | re.I | re.DOTALL | 0x1000)
re.ASCII 4114
re.ASCII 0
re.IGNORECASE 4112
re.IGNORECASE 0
re.DOTALL 4096
re.DOTALL 0
re.ASCII|re.IGNORECASE|re.DOTALL|0x1000
```

output with ``print(m, rest)`` in ``__reduce_ex__``.

**Comment by serhiy-storchaka** [comment]
I think that it is okay. Enums are considered singletons (it allows to pickle them by name). It would be even better to add the `__copy__` method which returns `self`.

This PR is not ideal:
1. The residual member is reduced as `re.RegexFlag(0x1000)` instead of just `0x1000`.
2. Named flags are reduced as `getattr(re.RegexFlag, 'ASCII')` instead of global `re.RegexFlag.ASCII` or even `re.ASCII`.

It is a matter of the following optimizations.

**Pull request merged**
