### PR TITLE
Clarify secrets.token_urlsafe() removes Base64 padding

### PR DESCRIPTION
**Pull request by mattbaker-digital**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@mattbaker-digital

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by JelleZijlstra — COMMENTED** [review]
Confirmed this is true and the text looks reasonable.

Could you explain more though about why this should be in the docs? Is there confusion about this behavior?

**Comment by mattbaker-digital** [comment]
> Could you explain more though about why this should be in the docs? Is there confusion about this behavior?
@JelleZijlstra, on reflection, this was a poor suggestion on my part as 'url_safe' already implies that it is not using any reserved or unreserved characters as per RFC 3986.

**Comment by JelleZijlstra** [comment]
Thanks for the response! Closing this PR then.

**Pull request closed without merging**
