### PR TITLE
gh-121151: Fix wrapping of long usage text of arguments inside a mutually exclusive groups in argparse

### PR DESCRIPTION
**Pull request by hamdanal**
See the linked issue for the details. The fix here is to not group the arguments in a mutually exclusive group in a single string but to keep them separate so that they can be wrapped if necessary.

* Issue: gh-121151

### CODE REVIEW

**Comment by ZeroIntensity** [comment]
Looks like this patch differs from what the behavior used to be. On older versions, the `op3` part looked like:

```
--op3 [OP3 [OP3 ...]]
```

But on this patch, it looks like this:

```
--op3 [OP3 ...] |
```

**Comment by hamdanal** [comment]
> Looks like this patch differs from what the behavior used to be. On older versions, the `op3` part looked like:
> 
> ```
> --op3 [OP3 [OP3 ...]]
> ```
> 
> But on this patch, it looks like this:
> 
> ```
> --op3 [OP3 ...] |
> ```

No this was changed in Python 3.9. Which version did you use for testing?

**Comment by ZeroIntensity** [comment]
> > Looks like this patch differs from what the behavior used to be. On older versions, the `op3` part looked like:
> > ```
> > --op3 [OP3 [OP3 ...]]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But on this patch, it looks like this:
> > ```
> > --op3 [OP3 ...] |
> > ```
> 
> No this was changed in Python 3.9. Which version did you use for testing?

It might have been 3.8, oops!

**Review by ZeroIntensity — APPROVED** [review]
LGTM, then.

**Comment by hamdanal** [comment]
@encukou sorry to tag you again but if you could please take a look at this PR it would be great to get it merged before the final release of 3.13 as it fixes a 3.13 regression.

**Comment by encukou** [comment]
Looks good, thank you!
However, it missed 3.13.0rc1, and we want as few code changes as possible between the release candidate and the final. The backport will need to wait until 3.13.1.

**Pull request merged**
