### PR TITLE
bpo-34065: Fix wrongly written basicConfig document rst syntax about force

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue34065

### CODE REVIEW

**Comment by corona10** [comment]
@Mariatta Can you take a look?

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
Please fix also the markup in versionchanged notes below. And sort notes in the order of the version.

**Comment by corona10** [comment]
@serhiy-storchaka 
Thanks for the comment.

The mark up of `The ``force`` argument was added.` looks like correct without version sort since 
`The ``style`` argument was added.` is using the same syntax.

Should I update this markup into `The *force* argument was added.`?

Thanks!

**Comment by corona10** [comment]
Okay I will fix them all, I understand what you are saying.

**Comment by serhiy-storchaka** [comment]
`*name*` is usually used for all arguments.

**Comment by corona10** [comment]
I have made the requested changes; please review again

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Do you mind to make backports to 3.6 and 3.7 manually @corona10?

**Comment by corona10** [comment]
@serhiy-storchaka Sure

**Pull request merged**
