### PR TITLE
Fixed a typo in the HTMLParser.feed docstrings

### PR DESCRIPTION
**Pull request by dasdachs**
The docstring started with an 'r', like a rawstring.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thank you for your patch @dasdachs. Do you mind to backport your change to other active branches (3.6, 3.5, and maybe 2.7)?

**Comment by dasdachs** [comment]
Thank you @serhiy-storchaka! I'll backport the changes as soon as I can.

**Comment by vadmium** [comment]
This looks wrong to me. It looks like it will have a real newline rather than the literal \n escape sequence. See commit 39f180b.

**Comment by serhiy-storchaka** [comment]
Oh, my bad! I read the patch as *adding* the "r" prefix!

**Comment by dasdachs** [comment]
Of course it does. Sorry for the unnecesary work @serhiy-storchaka and thank you @vadmium!

**Pull request merged**
