### PR TITLE
bpo-35212: fix col_offset in f-strings

### PR DESCRIPTION
**Pull request by matanagasauce**
https://bugs.python.org/issue35212

### CODE REVIEW

**Comment by pablogsal** [comment]
Hi @yangyangxcf. Unfortunately, the `ast.c` module has changed recently and all the functionality has been ported to some new files under the `Parser` directory. Could you update your PR for the new layout? If you don't have time, I could do it for you if you wish.

**Comment by taleinat** [comment]
Ping, @yangyangxcf, @pablogsal?

**Comment by pablogsal** [comment]
> Ping, @yangyangxcf, @pablogsal?

This PR still needs to be rebased as per https://github.com/python/cpython/pull/19398#issuecomment-684048195. As I mentioned, I am fine to take it over if @yangyangxcf is ok with that

**Comment by taleinat** [comment]
Let's give this another couple of weeks then, @pablogsal?

**Comment by ericvsmith** [comment]
@DanielNoord :Thanks for the reminder!

**Pull request closed without merging**
