### PR TITLE
gh-84353: fix old zip filename corruption, emit cp437 when possible; utf-8 with the flag otherwise

### PR DESCRIPTION
**Pull request by yudilevi2**
https://bugs.python.org/issue40172

* Issue: gh-84353

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@nergall2

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by csabella** [comment]
@yudilevi2, please sign the CLA as per @the-knights-who-say-ni bot's message.

**Comment by yudilevi2** [comment]
@csabella done

**Comment by csabella** [comment]
@yudilevi2, also please make this PR against master instead of the 3.8 branch.  Typically, changes are made against master and then we have a bot that backports the change to the other releases, if applicable.  Thanks!

**Comment by csabella** [comment]
@yudilevi2, the bot (and I) cannot find a bug tracker profile that matches your github name.  Can you check it using [this link](https://check-python-cla.herokuapp.com/)?  Also, please see my comment about the base branch for the change.  Thanks!

**Comment by yudilevi2** [comment]
> @yudilevi2, the bot (and I) cannot find a bug tracker profile that matches your github name. Can you check it using [this link](https://check-python-cla.herokuapp.com/)? Also, please see my comment about the base branch for the change. Thanks!

Sorry, had multiple github accounts and things got messed up - I updated my profile with the correct github user name now.

**Comment by gpshead** [comment]
this PR needs to be re-created by someone against the `main` branch.

**Comment by arhadthedev** [comment]
@gpshead gh-104347.

**Pull request closed without merging**
