### PR TITLE
gh-128277: use relaxed atomics for `sock_fd`

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-128277

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]
Looks good after the brief look

**Review by colesbury — COMMENTED** [review]
I'm not sure it's worth doing these sorts of changes for file descriptors. We still have unfixable race conditions when sockets are closed concurrently (see https://github.com/python/cpython/issues/121544)

**Comment by colesbury** [comment]
The PR is fairly straightforward, so it's fine with me if you want to merge it. I just don't think we should bother with this sort of thing in the future.

**Comment by kumaraditya303** [comment]
> I'm not sure it's worth doing these sorts of changes for file descriptors. We still have unfixable race conditions when sockets are closed concurrently (see https://github.com/python/cpython/issues/121544)

I see, I did this just for asyncio because tsan was complaining while running the existing test suite and this fixes all of this AFAICS. If we aren't planning to fix this maybe we should add some tsan suppressions for these for the time being?

**Pull request merged**
