### PR TITLE
gh-98576: Fix types in dataclass.InitVar example

### PR DESCRIPTION
**Pull request by hauntsaninja**
* Issue: gh-98576

### CODE REVIEW

**Comment by hauntsaninja** [comment]
cc @JelleZijlstra

**Review by AlexWaygood — APPROVED** [review]
LGTM

**Review by JelleZijlstra — APPROVED** [review]

**Comment by AlexWaygood** [comment]
@ericvsmith, are you okay with this change? :)

It brings the example in the `dataclasses` docs up to date with revisions to PEP 484 that were made in 2018, in https://github.com/python/peps/commit/0630155b47c27f25e66267d247f0205aa953f113

**Comment by ericvsmith** [comment]
Looks good. Thanks!

Does someone want to look at the 3.11 merge conflict?

**Comment by AlexWaygood** [comment]
> Looks good. Thanks!
> 
> Does someone want to look at the 3.11 merge conflict?

There was no merge conflict; just some sort of race condition that meant that @miss-islington was unable to check out the 3.11 branch. She succeeded on the second attempt :)

**Comment by ericvsmith** [comment]
Thanks!

**Comment by hauntsaninja** [comment]
@AlexWaygood where did you see the missislington logs? If you link me, I could take a look at fixing it :-)

**Comment by JelleZijlstra** [comment]
It's just the posted message I think. I recently improved the message in https://github.com/python/miss-islington/commit/868b6bac7e7a1749c9482fcc10b25795cdde880a; from there it may be possible to trace the code to figure out the actual bug.

This condition most frequently happens when trying to do multiple backports at once, like on this PR, which makes me think it may be a race condition where both backports try to use the same resource. However, I've also seen it happen on PRs that were backported only to a single branch.

**Comment by AlexWaygood** [comment]
Yes — to be clear, I don't have solid confirmation that a race condition is to blame; that's just my suspicion, given that removing and re-adding the label almost always seems to work :)

**Pull request merged**
