### PR TITLE
Fix typo in asyncio.streams.FlowControlMixin documentation

### PR DESCRIPTION
**Pull request by johnchen902**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
@joelthelion the patch is good but please sign a Contributor Agreement: https://www.python.org/psf/contrib/contrib-form/

Without this step I cannot merge the Pull Request, it is Python's policy.
Thanks.

**Comment by joelthelion** [comment]
@asvetlov I think you got the wrong person.

**Comment by asvetlov** [comment]
Sorry, autocomplete is not always perfect.

**Comment by asvetlov** [comment]
@johnchen902  please sign a Contributor Agreement: https://www.python.org/psf/contrib/contrib-form/

**Comment by johnchen902** [comment]
I signed one right before sending this pull request.

> Contributor Form Received | Yes        on: 2017-11-27.08:00:00

**Comment by asvetlov** [comment]
Thanks!
Processing CLA is not automatic, a person should review all CLAs.
Let's wait for a few days.

**Comment by johnchen902** [comment]
I thought mine has been reviewed, but the 'cla-not-signed' label has to be removed for @the-knights-who-say-ni to recheck.

**Comment by asvetlov** [comment]
Aha, I see that CLA is signed on https://bugs.python.org/user27450

**Comment by asvetlov** [comment]
Thanks for contribution!

**Pull request merged**
