### PR TITLE
Typo in minidom documentation

### PR DESCRIPTION
**Pull request by brandelune**

### CODE REVIEW

**Review by AA-Turner — APPROVED** [review]

**Comment by brandelune** [comment]
Is there a reason why a typo takes 1 month to be fixed?

**Comment by AlexWaygood** [comment]
> Is there a reason why a typo takes 1 month to be fixed?

This probably just fell off the radar. There are a lot of PRs filed against CPython, and not enough core devs to review them all. Please try to be patient, and remember that everybody helping to maintain CPython is a volunteer giving up their free time.

**Comment by brandelune** [comment]
I totally understand and I'm also a volunteer giving up my free time in other project, so I'm not blaming anybody here. Just asking.

Because this is *Python*, not some obscure free software project, and this is a 1 word typo.

Is there a triage issue (why are core devs involved in reviewing typos?)

**Comment by AlexWaygood** [comment]
> I totally understand and I'm also a volunteer giving up my free time in other project, so I'm not blaming anybody here.

I know, and thank you for giving up your free time to file this PR! I'm sorry this has taken a little while.

> Is there a triage issue (why are core devs involved in reviewing typos?)

This has already been triaged — Adam's a triager, and has already approved it, and I'm also a triager, and have just pinged a core dev for you. But only core devs have merge privileges (and personally, i think that's as it should be), so every PR does ultimately need to be approved by a core dev, even if it's just a trivial typo fix.

There are broader discussions underway at the moment about how we can do better at triaging issues and PRs. I wrote about them last month: https://pyfound.blogspot.com/2022/05/the-2022-python-language-summit-dealing.html?m=1

**Review by JelleZijlstra — APPROVED** [review]

**Comment by ambv** [comment]
Rebased to get rid of the Windows build failures.

**Pull request merged**
