### PR TITLE
bpo-35814: Allow unpacking in r.h.s of annotated assignment expressions

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue35814

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
Are there no affected docs?

**Comment by pablogsal** [comment]
Yup, I will make another PR to not risk this one missing feature freeze.

**Comment by pablogsal** [comment]
The buildbot failure is unrelated. Is known asyncio problem.

**Comment by ilevkivskyi** [comment]
@pablogsal Thanks for helping with this!

**Pull request merged**
