### PR TITLE
Re-enable the OverflowError test for test_truediv on test_complex

### PR DESCRIPTION
**Pull request by corona10**
This code was added 17 years ago. It works well today.

### CODE REVIEW

**Comment by corona10** [comment]
@serhiy-storchaka Please take a look

**Comment by serhiy-storchaka** [comment]
I think @mdickinson is more accomplished in this.

**Review by mdickinson — APPROVED** [review]
LGTM

**Comment by corona10** [comment]
@serhiy-storchaka  
Merge this PR please :)

**Pull request merged**
