### PR TITLE
bpo-17446: Get line numbers of properties in doctest

### PR DESCRIPTION
**Pull request by mscuthbert**
Doctests currently don’t know the line numbers of tests of properties. Fixes error messages on doctest failures for properties.

https://bugs.python.org/issue17446

#61648

### CODE REVIEW

**Comment by mscuthbert** [comment]
Hoping that someone might be willing to take time out of their busy schedule to review this -- it already had reviews from the prior bugs-python discussion. @serhiy-storchaka you gave me a fantastic review with great comments on the wave-pathlib request, do you have time or know someone who has time to review this? For those of us using `@property` and PyDev, having line-numbers (which get hyperlinked to the appropriate code) would be a great time-saver.

**Comment by serhiy-storchaka** [comment]
The test is passed if revert changes in `Lib/doctest.py`. Therefore it doesn't test the changed behavior. Could you provide a test that is passed with the patched code and failed with the unpatched code?

**Comment by AA-Turner** [comment]
Reopening per https://github.com/python/cpython/issues/61648#issuecomment-1148596435

A

**Comment by serhiy-storchaka** [comment]
The test is passed because it tests `lineno` attributes of `Example` instances instead of `DocTest` instances. Also, the code can be much simpler.

I created an alternative PR #113161.

**Pull request closed without merging**
