### PR TITLE
bpo-45890: Add tests for tracing try-except-finally blocks

### PR DESCRIPTION
**Pull request by iritkatriel**
https://bugs.python.org/issue45890

### CODE REVIEW

**Comment by markshannon** [comment]
OOI, what is the reason for adding these to `test_trace`, instead of `test.test_sys_settrace`? 
E.g. https://github.com/python/cpython/blob/main/Lib/test/test_sys_settrace.py#L638

The expected output in `test.test_sys_settrace` is stricter (as it is ordered) and a clearer, IMO.

**Comment by iritkatriel** [comment]
I didn't notice test.test_sys_settrace, let me check.

**Comment by iritkatriel** [comment]
test.test_sys_settrace. has some of these, maybe I can add a case or two.

Why are the tests there numbered? Can I change the numbers?

**Comment by markshannon** [comment]
Thanks

**Pull request merged**
