### PR TITLE
gh-115383: Install `ncurses` in reusable macos workflow

### PR DESCRIPTION
**Pull request by sobolevn**
Let's try this!

* Issue: gh-115383

### CODE REVIEW

**Comment by sobolevn** [comment]
It, obviously, didn't help :(

**Comment by ned-deily** [comment]
@sobolevn, See the **Install Homebrew Dependencies** section of the workflow log. Just installing `ncurses` from Homebrew isn't enough because Homebrew ncurses is `keg-only`:

```
For pkg-config to find ncurses you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig"
```

**Comment by ned-deily** [comment]
And, of course, Homebrew uses different install paths for Intel Mac systems and Apple Silicon Mac systems so perhaps a better solution would be to adapt the GDBM_CFLAGS and GDBM_LIBS boilerplate from [the devguide recipe](https://devguide.python.org/getting-started/setup-building/#install-dependencies).

**Comment by sobolevn** [comment]
We can continue to experiment here :)

**Comment by ambv** [comment]
> perhaps a better solution would be to adapt the GDBM_CFLAGS and GDBM_LIBS boilerplate

You mean creating NCURSES_CFLAGS and NCURSES_LIBS?

**Comment by erlend-aasland** [comment]
> > perhaps a better solution would be to adapt the GDBM_CFLAGS and GDBM_LIBS boilerplate
> 
> You mean creating NCURSES_CFLAGS and NCURSES_LIBS?

That would be `CURSES_CFLAGS` and `CURSES_LIBS`.

```console
$ ./configure --help| grep -i curses
  CURSES_CFLAGS
              C compiler flags for CURSES, overriding pkg-config
  CURSES_LIBS linker flags for CURSES, overriding pkg-config
```

**Comment by ned-deily** [comment]
> > > perhaps a better solution would be to adapt the GDBM_CFLAGS and GDBM_LIBS boilerplate
> > 
> > 
> > You mean creating NCURSES_CFLAGS and NCURSES_LIBS?
> 
> That would be `CURSES_CFLAGS` and `CURSES_LIBS`.
> 
> ```
> $ ./configure --help| grep -i curses
>   CURSES_CFLAGS
>               C compiler flags for CURSES, overriding pkg-config
>   CURSES_LIBS linker flags for CURSES, overriding pkg-config
> ```

Yeah, I meant adapting the devguide's GDBM_CFLAGS and GDBM_LIBS recipe for CURSES_FLAGS and CURSES_LIBS but, as it appears the root causes were actually [a caching issue](https://github.com/python/cpython/pull/115409) and using [a newer Apple SDK on an older system](https://github.com/python/cpython/pull/111258), that we shouldn't need to use the Homebrew ncurses going forward so this can probably safely closed.

**Pull request closed without merging**
