### PR TITLE
[3.12] gh-114965: Regenerate SBOM after pip upgrade

### PR DESCRIPTION
**Pull request by ambv**
This wasn't regenerated in GH-114971.

* Issue: gh-114965

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
LGTM, I tried to do the same in https://github.com/python/cpython/pull/115088/commits/a1710df038a056a8f8bb8944088b3a9901a1cc91 for https://github.com/python/cpython/pull/115088. Will rebase mine once this is merged.

**Comment by sethmlarson** [comment]
@ambv  Looks like my referenced PR was merged, I think this is fixed now.

**Comment by ambv** [comment]
Something is not right. If this got merged, then this PR should be null.

**Comment by ambv** [comment]
Ah, this just got merged now. Makes sense, this can be closed.

**Pull request closed without merging**
