### PR TITLE
gh-92651: Remove the Include/token.h header file

### PR DESCRIPTION
**Pull request by vstinner**
Remove the token.h header file. There was never any public tokenizer
C API. The token.h header file was only designed to be used by Python
internals.

Move Include/token.h to Include/internal/pycore_token.h. Including
this header file now requires that the Py_BUILD_CORE macro is
defined. It no longer checks for the Py_LIMITED_API macro.

Rename functions:

* PyToken_OneChar() => _PyToken_OneChar()
* PyToken_TwoChars() => _PyToken_TwoChars()
* PyToken_ThreeChars() => _PyToken_ThreeChars()

### CODE REVIEW

**Comment by vstinner** [comment]
@pablogsal @lysnikolaou @iritkatriel: Do you see any reason to expose token.h as part of the public C API? Or are you fine with removing this header file from the public C API?

Issue: https://github.com/python/cpython/issues/92651

**Comment by vstinner** [comment]
> These functions and _PyParser_TokenNames symbols are no longer exported.

I tried to no longer export these symbols, but it broke test_peg_generator. I reverted this change.

**Review by serhiy-storchaka — COMMENTED** [review]
Update also the default value in `make_h()`.

Should PyAPI_FUNC and PyAPI_DATA be used in declarations?

**Comment by vstinner** [comment]
> Update also the default value in make_h().

Oh right, I updated my PR.

> Should PyAPI_FUNC and PyAPI_DATA be used in declarations?

As I wrote in my previous comment, first, I removed PyAPI_FUNC() and PyAPI_DATA() but it broke test_peg_generator. This test builds C extensions which are linked dynamically.

I added ``// Symbols exported for test_peg_generator`` comment to future readers.

**Comment by pablogsal** [comment]
> Do you see any reason to expose token.h as part of the public C API? 

No, and is a bad idea to have it as part of the public C API, so if we can move it to the internal heafers folder, that would be great :)

**Review by pablogsal — APPROVED** [review]

**Comment by vstinner** [comment]
Merged. Thanks for the reviews!

**Pull request merged**
