### PR TITLE
bpo-40939: Remove PEG parser easter egg

### PR DESCRIPTION
**Pull request by lysnikolaou**
https://bugs.python.org/issue40939

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]

**Comment by lysnikolaou** [comment]
Closing and reopening for the CI.

**Review by pablogsal — APPROVED** [review]

**Comment by lysnikolaou** [comment]
@pablogsal I don't know if the commit message goes into the squash commit message, but here it's currently wrong, since it mentions renaming and not removing. Should I change it or will you just take the PR title as the commit message of the squash commit?

**Comment by pablogsal** [comment]
> Should I change it or will you just take the PR title as the commit message of the squash commit?

I will customize it when I merge :)

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Honestly I wouldn't back port this. In 3.9 this *does* serve a purpose.

**Comment by pablogsal** [comment]
> Honestly I wouldn't back port this. In 3.9 this _does_ serve a purpose.

A PR is still needed to fix the build bot errors.

**Comment by gvanrossum** [comment]
Okay, can you do it? I don't even know what the buildbot error is.

**Comment by pablogsal** [comment]
> Okay, can you do it? I don't even know what the buildbot error is.

Yep, I will take care of it don't worry

**Comment by lysnikolaou** [comment]
> worry

Already got something ready. I'll push soon.

**Comment by laloch** [comment]
There seem to still be some leftovers present:
```
$ docker run -i -t python:3.9-rc /usr/local/bin/python
Python 3.9.0rc1 (default, Aug 12 2020, 18:31:30) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyword
>>> keyword.iskeyword("__peg_parser__")
True
>>> assert "__peg_parser__" not in keyword.kwlist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

**Comment by gvanrossum** [comment]
The removal applies to 3.10.

**Comment by laloch** [comment]
Oh, I see! I should have read the comments I guess. Sorry for the noise.
I would like the change to get backported, bacause it prevents [Xonsh](http://github.com/xonsh/xonsh) from building its parser table right now, but never mind, we'll adjust. Thanks!

**Pull request merged**
