### PR TITLE
Changed Documentation

### PR DESCRIPTION
**Pull request by ghost**
Changed Documentation to be a bit more readable

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by eamanu — CHANGES_REQUESTED** [review]
Hello @GeorgeWalt!

Thanks for the PR. Please sign the CLA for future contributions :-)

IMO capitalize comments is not an improve. It would be great if you can clarify
some comments (if is necessary).

**Review by tirkarthi — COMMENTED** [review]
There are places where comments start with lowercase letter. Apart from capitalizing the letter I don't see any changes that change the meaning of these code comments so I am not sure these should be merged.

**Review by isidentical — COMMENTED** [review]
I think it is good right now, they dont need to be capitalized.

**Comment by matrixise** [comment]
Hi @GeorgeWalt 

Thank you for your contribution but I think you should work instead on the documentation because we need to have a lot of contributors/reviewers for that part. I say the documentation because you have modified the comments and your experience could be really useful for that part and especially for the end-users.

Have a nice day and thank you again for your contribution.

**Pull request closed without merging**
