### PR TITLE
Include soft keywords in keyword.py

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by pablogsal** [comment]
Given that soft keywords are still unused I have not included a news file: Tell me if you would prefer to include one.

**Review by gvanrossum — APPROVED** [review]
Thanks! I think no news is needed, this is essentially an internal tool.

**Comment by gvanrossum** [comment]
Since soft keywords are supported in 3.9 (even though there are none), should we backport the API there???

**Comment by pablogsal** [comment]
> Since soft keywords are supported in 3.9 (even though there are none), should we backport the API there???

I think so, to make future backports easier more than anything.

**Comment by srittau** [comment]
Since the keyword module is documented (https://docs.python.org/3.10/library/keyword.html), I believe this should be added to the docs as well.

**Comment by pablogsal** [comment]
> Since the keyword module is documented (https://docs.python.org/3.10/library/keyword.html), I believe this should be added to the docs as well.

Good catch, I will open a PR soon

**Comment by pablogsal** [comment]
Opened https://github.com/python/cpython/pull/21185

**Pull request merged**
