### PR TITLE
gh-125579: Change code examples to help when searching for 'capture' …

### PR DESCRIPTION
**Pull request by epa**
Please see https://github.com/python/cpython/issues/125579

* Issue: gh-125579

----
📚 Documentation preview 📚: https://cpython-previews--125580.org.readthedocs.build/

### CODE REVIEW

**Comment by willingc** [comment]
@epa If you wish to move this PR forward, please complete the CLA by clicking the badge above.

**Comment by epa** [comment]
Hi, I have clicked to sign the CLA but the email address on the patch is different from my Github account's email address so it doesn't let me.  I will remake the patch.

However, I had imagined that this change is both too trivial to copyright, and so simple that it might be easiest for the Python developers to make an equivalent change directly rather than merge the pull request.

**Comment by terryjreedy** [comment]
Replacing 8 chars by 5 reduces 'quickly' found location by 3.  I think this is a good enough change (see issue comment) rather than merge churn.

I agree that this is a trivial enough change that should not need CLA, but I don't know is someone like @ambv can still merge without it.

**Comment by terryjreedy** [comment]
Closing as explained in https://github.com/python/cpython/issues/125579#issuecomment-2455529674

**Pull request closed without merging**
