### PR TITLE
bpo-30613: Fix that the distutils register command generates invalid HTTP multipart data

### PR DESCRIPTION
**Pull request by kb-1000**
https://bugs.python.org/issue30613

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Comment by brettcannon** [comment]
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

**Comment by kaeptmblaubaer1000** [comment]
Ok, it should be ok now. @brettcannon

**Comment by csabella** [comment]
I'm going to close and reopen this to retrigger the CI builds.

**Comment by csabella** [comment]
@kb-1000, please fix the CI test failures.   Thanks!

**Comment by kb-1000** [comment]
Ok, tests are fixed, now only a NEWS entry is missing. Can you help me with writing one?

**Comment by nanjekyejoannah** [comment]
@kb-1000 please use [blurb it](https://blurb-it.herokuapp.com/) to add a news entry.

**Comment by iritkatriel** [comment]
Closing this PR following the closure of its b.p.o issue (https://bugs.python.org/issue30613)

**Pull request closed without merging**
