### PR TITLE
gh-68272: add sub-millisecond display in pstats

### PR DESCRIPTION
**Pull request by romuald**
When running pstats with functions that take less than 0.5 millisecond
(per call for example), the value shown is '0.000, which isn't really
helpful.

This patch aims to show the value in microseconds instead of seconds for
values that would otherwise be displayed as '0.000'

https://bugs.python.org/issue24084

* Issue: gh-68272

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by romuald** [comment]
(Note that I have only tested this patch against the 3.6 branch, as I can't currently compile the master branch on my development machine)

**Comment by romuald** [comment]
(added my github account to my bpo account just now)

**Comment by guillochon** [comment]
Any update here? Would make pstats a bit more useful...

**Comment by arhadthedev** [comment]
Closing as per https://github.com/python/cpython/issues/68272#issuecomment-1429126518.

**Pull request closed without merging**
