### PR TITLE
Fix indentation in logging.handlers.setStream

### PR DESCRIPTION
**Pull request by andresdelfino**
See commit https://github.com/python/cpython/commit/2543f50033208c1a8df04999082b11aa09e82a04

### CODE REVIEW

**Review by eamanu — APPROVED** [review]
LGTM. Good catch.

Could you take a look, please,  on line 111 and 116  IMO there are unnecessary lines

**Comment by andresdelfino** [comment]
> LGTM. Good catch.
> 
> Could you take a look, please, on line 111 and 116 IMO there are unnecessary lines

I remove the blank line from 111, but kept the one from 116 because it's custom to leave two blank lines between class documentation.

**Comment by eamanu** [comment]
> > LGTM. Good catch.
> > Could you take a look, please, on line 111 and 116 IMO there are unnecessary lines
> 
> I removed the blank line from 111, but kept the one from 116 because it's custom to leave two blank lines between class documentation.

(Y) :-)

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks. cc: @vsajip

**Pull request merged**
