### PR TITLE
Fix missing bracket

### PR DESCRIPTION
**Pull request by azalea**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Comment by matrixise** [comment]
Hi @azalea , please could you create a BPO account and associated your github account to the bpo account. Thank you.

**Comment by azalea** [comment]
Hi @matrixise, I just registered a [BPO account](https://bugs.python.org/user31257) and signed the CLA. but when I [checked](https://check-python-cla.herokuapp.com/) it says otherwise. Sorry I am new here. What am I missing?

**Pull request merged**
