### PR TITLE
bpo-35802: Clean up code which checked presence of os.{stat,lstat,chmod}

### PR DESCRIPTION
**Pull request by asottile**
https://bugs.python.org/issue35802

### CODE REVIEW

**Comment by pablogsal** [comment]
Hummmm, I do not feel very comfortable removing these checks. Autotools actually is checking at least for `lstat`.

**Comment by asottile** [comment]
> 
> 
> Hummmm, I do not feel very comfortable removing these checks. Autotools actually is checking at least for `lstat`:
> 
> https://github.com/python/cpython/blob/master/configure.ac#L3505

Unless I'm reading incorrectly, it is unconditionally defined in the `os` module: https://github.com/python/cpython/blob/7a2368063f25746d4008a74aca0dc0b82f86ff7b/Modules/clinic/posixmodule.c.h#L68-L69

The actual implementation chooses whether to use `lstat` or not and does the platform-specific dances: https://github.com/python/cpython/blob/7a2368063f25746d4008a74aca0dc0b82f86ff7b/Modules/posixmodule.c#L2123-L2170

**Comment by pablogsal** [comment]
Note that the os module falls back outside `posix` if the `posixmodule` is not compiled :+1: 

https://github.com/python/cpython/blob/master/Lib/os.py#L68

Windows systems `nt`) usually will have `chmod` and `lstat` and friends, but I am not sure if they can be missing for some reason.

**Comment by asottile** [comment]
On windows, the `nt` module is created from the very same `posixmodule.c` (yes it's confusing 😭):

https://github.com/python/cpython/blob/7a2368063f25746d4008a74aca0dc0b82f86ff7b/Modules/posixmodule.c#L4-L5

**Comment by pablogsal** [comment]
Apparently there is nothing missing in the logic that leads to clean un the code as this PR is doing, but I would like Gregory to take a look in case I am missing something.

**Comment by asottile** [comment]
@giampaolo @gpshead friendly ping :)

**Review by giampaolo — APPROVED** [review]
LGTM (good change).

**Review by gpshead — APPROVED** [review]

**Comment by asottile** [comment]
@gpshead @giampaolo anything left for me to do here?

**Comment by giampaolo** [comment]
It was already approved. You can merge.

**Comment by asottile** [comment]
I am a mere pleb without green-button access <3

**Comment by giampaolo** [comment]
Sorry, my bad.

**Pull request merged**
