### PR TITLE
gh-93839: Use load_package_tests() for testmock

### PR DESCRIPTION
**Pull request by tiran**
Fixes failing tests on WebAssembly platforms.

Automerge-Triggered-By: GH:tiran

### CODE REVIEW

**Review by cjw296 — APPROVED** [review]
Less code is always better!

**Comment by tiran** [comment]
The old code did ``__import__`` without capturing and handling ``SkipTest`` exception from the import.

**Comment by vstinner** [comment]
Example of error before the fix: https://buildbot.python.org/all/#/builders/1044/builds/35

```
FAIL: testSelectedTestNamesFunctionalTest (test.test_unittest.test_program.TestCommandLineArgs.testSelectedTestNamesFunctionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/test_program.py", line 468, in testSelectedTestNamesFunctionalTest
    self.assertIn('Ran 7 tests', run_unittest(['discover', '-p', '*_test*', '-k', 'TestWarnings']))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'Ran 7 tests' not found in '/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:24: DeprecationWarning: Please use assertEqual instead.\n  self.assertEquals(2+2, 4)\n./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:38: DeprecationWarning: dw\n  warnings.warn(\'dw\', DeprecationWarning)\n/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:39: DeprecationWarning: dw\n  warnings.warn(\'dw\', DeprecationWarning)\n/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:40: DeprecationWarning: dw\n  warnings.warn(\'dw\', DeprecationWarning)\n./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:29: DeprecationWarning: Please use assertTrue instead.\n  self.failUnless(1)\n./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:18: RuntimeWarning: rw\n  warnings.warn(\'rw\', RuntimeWarning)\n./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:43: ImportWarning: iw\n  warnings.warn(\'iw\', ImportWarning)\n/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:44: ImportWarning: iw\n  warnings.warn(\'iw\', ImportWarning)\n/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:45: ImportWarning: iw\n  warnings.warn(\'iw\', ImportWarning)\n../opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:49: UserWarning: uw\n  warnings.warn(\'uw\')\n/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:50: UserWarning: uw\n  warnings.warn(\'uw\')\n/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:51: UserWarning: uw\n  warnings.warn(\'uw\')\n.E\n======================================================================\nERROR: testmock (unittest.loader._FailedTest.testmock)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/testmock/__init__.py", line 14, in load_tests\n    __import__(modname)\n    ^^^^^^^^^^^^^^^^^^^\n  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/__init__.py", line 2, in <module>\n    from test.support import load_package_tests\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/support/__init__.py", line 1229, in <module>\n    not sysconfig.get_config_var(\'WITH_DOC_STRINGS\'))\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/sysconfig.py", line 714, in get_config_var\n    return get_config_vars().get(name)\n           ^^^^^^^^^^^^^^^^^\n  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/sysconfig.py", line 669, in get_config_vars\n    _init_posix(_CONFIG_VARS)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/sysconfig.py", line 530, in _init_posix\n    _temp = __import__(name, globals(), locals(), [\'build_time_vars\'], 0)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nModuleNotFoundError: No module named \'_sysconfigdata__emscripten_wasm32-emscripten\'\n\n----------------------------------------------------------------------\nRan 8 tests in 0.001s\n\nFAILED (errors=1)\n'
```

Reformatted output:

```
/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:24: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(2+2, 4)
./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:38: DeprecationWarning: dw
  warnings.warn(\'dw\', DeprecationWarning)
/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:39: DeprecationWarning: dw
  warnings.warn(\'dw\', DeprecationWarning)
/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:40: DeprecationWarning: dw
  warnings.warn(\'dw\', DeprecationWarning)
./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:29: DeprecationWarning: Please use assertTrue instead.
  self.failUnless(1)
./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:18: RuntimeWarning: rw
  warnings.warn(\'rw\', RuntimeWarning)
./opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:43: ImportWarning: iw
  warnings.warn(\'iw\', ImportWarning)
/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:44: ImportWarning: iw
  warnings.warn(\'iw\', ImportWarning)
/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:45: ImportWarning: iw
  warnings.warn(\'iw\', ImportWarning)
../opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:49: UserWarning: uw
  warnings.warn(\'uw\')
/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:50: UserWarning: uw
  warnings.warn(\'uw\')
/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/_test_warnings.py:51: UserWarning: uw
  warnings.warn(\'uw\')
.E
======================================================================
ERROR: testmock (unittest.loader._FailedTest.testmock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/testmock/__init__.py", line 14, in load_tests
    __import__(modname)
    ^^^^^^^^^^^^^^^^^^^
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/test_unittest/__init__.py", line 2, in <module>
    from test.support import load_package_tests
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/test/support/__init__.py", line 1229, in <module>
    not sysconfig.get_config_var(\'WITH_DOC_STRINGS\'))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/sysconfig.py", line 714, in get_config_var
    return get_config_vars().get(name)
           ^^^^^^^^^^^^^^^^^
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/sysconfig.py", line 669, in get_config_vars
    _init_posix(_CONFIG_VARS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/buildbot/bcannon-wasm/3.x.bcannon-wasm.emscripten-node/build/Lib/sysconfig.py", line 530, in _init_posix
    _temp = __import__(name, globals(), locals(), [\'build_time_vars\'], 0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named \'_sysconfigdata__emscripten_wasm32-emscripten\'

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (errors=1)
```

**Comment by vstinner** [comment]
Oh, more context about this change:

* https://github.com/python/cpython/pull/94043#issuecomment-1161507217
* https://github.com/python/cpython/issues/93839#issuecomment-1161600894

On WebAssemble, ``Lib/test/test_unittest/testmock/testasync.py`` raises ``unittest.case.SkipTest: requires socket support``.

**Comment by tiran** [comment]
Yeah, ``ModuleNotFoundError: No module named \'_sysconfigdata__emscripten_wasm32-emscripten\'`` is red herring. It took me a while to realize that it was a side-effect of bug gh-94052.

**Pull request merged**
