### PR TITLE
gh-93008: refactor compiler functions that add instructions to take only a basicblock* (not the whole compiler)

### LINKED ISSUE #93008: Refactor compiler so that the low level code generation functions operate on a basicblock*
The compiler's functions that add instructions (compiler_addop, etc) take a ``struct compiler *`` arg, so they cannot be reused by the optimiser/assembler. They should be refactored so that they only take a basicblock*.

While I'm at it, I will roll compiler_check_if_end_of_block into the subsequent compiler_use_new_implicit_block_if_needed (which can look at the last instruction in the block).

### PR DESCRIPTION
**Pull request by iritkatriel**
This makes these functions available for use in the optimiser and assembler, when it is necessary to change basic blocks. 

Closes #93008.

### CODE REVIEW

**Review by sweeneyde — APPROVED** [review]
Looks correct and makes things a bit more flexible.

Out of interest, what are the use-cases for adding instructions at assembly time?

**Comment by iritkatriel** [comment]
> Looks correct and makes things a bit more flexible.
> 
> Out of interest, what are the use-cases for adding instructions at assembly time?

Thanks. I need to do this [here](https://github.com/python/cpython/pull/92769/) line 7465.

**Comment by markshannon** [comment]
Looks good.

**Comment by markshannon** [comment]
Looks good.

**Pull request merged**
