### PR TITLE
[INVALID] efficient backward read operations for `IOBase` [WIP] 

### PR DESCRIPTION
**Pull request by picnixz**
Per Guido's comment (https://github.com/python/cpython/issues/44691#issuecomment-1236054834):

> Last activity was 2014. Anyone interested in getting this over the finish line?

This PR is a WIP where I wanted to revive an old issue, namely reverse readinhg for IO objects in general (I've added a minimal blurb entry just for the CI/CD but I'll update it when the PR is done). 

While the original issue is only for lines, https://github.com/python/cpython/issues/44691#issuecomment-1094029571 suggested to have the interface on `BufferedReader` rather than `TextIOWrapper` since *[for] full-speed scanning of log files, you probably want to open them in binary mode*. Similarly, it was suggested, instead of a full-blown iterator, to implement simpler primitives. 

I only implemented something in Python for now, but I prepared the interface that is needed in C (for now, all but 1 implementations raise an exception). It might make sense to have the possibility for backward iteration independently of whether it is a FileIO, BytesIO or BufferedIO. For now, I've only implemented something for BytesIO and BufferedIO, leaving the rest unimplemented.

The design choices are as follows:

- The `backread` method behaves like `read` but reads bytes from the end of the right to left (e.g., `abcdef -> fedbca`). It should be roughly equivalent to read the whole buffer in memory, and read from the end (obviously, I don't read the whole buffer first...). A similar observation holds for the `backreadinto` method.
- There is an equivalent of `readall` that I called `backreadall` which simply reads the whole buffer from the right. It's mostly used as a shortcut to avoid duplications, e.g., when you call `backread()` without a limit.

There is also an equivalent of `readline()` named `backreadline()` which is a bit different than `backread()` and `backreadall()`. I'll illustrate the behaviour with an example. Say that
the text is `"abc\n1234\nthis is the last line"`. Then, `backreadline(9)` would return `"last line"` and `backreadline()` would return `"this is the last line\n"`.

In practice, `backreadline()` would be used to retrieve the lines of a log file for instance, so I think it would make sense that it behaves like that. I don't really know whether it's preferrable, when halting in the middle of the line, to return the last bytes of the line or to return the first bytes. In the first case, I don't need to read the entire line if the number of bytes I want to read are less than the line's length but in the second case, I need to first know where my line ended in order to read its first *n* bytes.

----

### Tasks

- [x] Add Python implementation
- [ ] Add documentation
- [ ] Add Whats New's entry
- [ ] Add tests
- [ ] Add C implementation
  - [ ] in `_io/iobase.c`
  - [ ] in `_io/bytesio.c`
  - [ ] in `_io/bufferedio.c`
  - [ ] in `_io/fileio.c`
- [ ] (optional) benchmarks

### CODE REVIEW

**Comment by nineteendo** [comment]
Hmm, this might become a big pull request. It might be worth it to split it up (maybe per method). But you can always do that later.

**Comment by picnixz** [comment]
Yes that's what I observed afterwards.. I'm not sure which is the best the direction now. At first I wanted to implement method by method, but almost all methods require the other ones. 

The most pressing thing was about the design choices so until I get a feedback by @pitrou or someone else, I don't think I'll go further.

**Comment by picnixz** [comment]
And I am quite happy that this one was a **draft**, otherwise there would have been unnecessary noises.

**Comment by nineteendo** [comment]
Maybe start with just `backread()` now?

**Pull request closed without merging**
