### PR TITLE
Convert code of conduct to markdown for Github

### PR DESCRIPTION
**Pull request by ammaraskar**
Trivial patch, doesn't need issue or news entry

### CODE REVIEW

**Comment by matrixise** [comment]
just one question, why do you convert it to markdown? the document already exists in ReST...

**Comment by ammaraskar** [comment]
Github only accepts code of conducts in markdown: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

I think this allows them to show up in various places in the interface like this:
capture

and visible to this api https://developer.github.com/v3/codes_of_conduct/

**Comment by matrixise** [comment]
ok, but they don't specify only markdown, they use markdown, that could be .rst

but ok

**Comment by ammaraskar** [comment]
No it can't, see here: https://github.com/python/cpython/community

**Comment by JulienPalard** [comment]
Hi @ammaraskar thanks for noticing and fixing!

**Pull request merged**
