### PR TITLE
closes bpo-42938: Replace snprintf with Python unicode formatting in ctypes param reprs.

### PR DESCRIPTION
**Pull request by benjaminp**
https://bugs.python.org/issue42938

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Comment by ericonr** [comment]
Isn't the commit message here rather misleading? These weren't snprintf calls, which is exactly what allowed them to overflow. If this PR did what it claims to do, this would only be a bug fix for truncated precision when printing some values, not a security patch.

One can clearly see in the code that sprintf is being used, not snprintf.

**Comment by Jennes** [comment]
> Isn't the commit message here rather misleading? These weren't snprintf calls, which is exactly what allowed them to overflow. If this PR did what it claims to do, this would only be a bug fix for truncated precision when printing some values, not a security patch.
> 
> One can clearly see in the code that sprintf is being used, not snprintf.

It is. But I guess this is to be interpreted as "even better than just fixing it with the second best solution, which would be `snprintf`"

**Comment by ahesford** [comment]
> It is. But I guess this is to be interpreted as "even better than just fixing it with the second best solution, which would be snprintf"

That would be the wrong interpretation. To replace means to take the place of, and `snprintf` has no place in the affected changes.

**Comment by use931** [comment]
AAA

**Pull request merged**
