### PR TITLE
bpo-35885: configparser indent

### PR DESCRIPTION
**Pull request by idomic**
https://bugs.python.org/issue35885

### CODE REVIEW

**Comment by idomic** [comment]
@taleinat You were right somehow the changes of another PR leaked into my master. I was able to fix it and opened a clean PR.

**Comment by idomic** [comment]
I have made the requested changes; please review again

**Comment by idomic** [comment]
@taleinat I think you were assigned to the old PR but not to this one for some reason

**Review by remilapeyre — CHANGES_REQUESTED** [review]
I'm worried about the risk about mixing spaces and tabs for indentation with this change. The tests only test writing, but not reading back. 

Could you add a test that reads the data back?

Are we sure all clients will be able to read those files?

**Comment by taleinat** [comment]
@idomic, I'd like to wait with reviewing this PR until more discussion about whether such a feature addition should be made. Let's continue the discussion on the b.p.o. issue, or perhaps also on Python-Ideas.

**Comment by ambv** [comment]
We won't be adding this per comments on the issue.

**Pull request closed without merging**
