### PR TITLE
gh-81403: Fix for CacheFTPHandler in urllib

### PR DESCRIPTION
**Pull request by hemberger**
A call to FTP.ntransfercmd must be followed by FTP.voidresp to clear
the "end transfer" message. Without this, the client and server get
out of sync, which will result in an error if the FTP instance is
reused to open a second URL. This scenario occurs for even the most
basic usage of CacheFTPHandler.

Reverts the patch merged as a resolution to [bpo-16270](https://bugs.python.org/issue16270) and adds a test
case for the CacheFTPHandler in test_urllib2net.py.

https://bugs.python.org/issue37222

* Issue: gh-81403

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by orsenthil** [comment]
This change looks good to me. This fell out of attention due to lack of news and I cannot edit this PR. I will merge this and make a minor change and NEWS as a separate PR commit.

The NEWS entry I will add is

> Fix ftplib endtransfer method to call void response. Fixes the issue when ftp url is reused or with CacheFTPHandler.

**Review by orsenthil — APPROVED** [review]
LGTM

**Comment by arhadthedev** [comment]
> Fix ftplib endtransfer method to call void response. Fixes the issue when ftp url is reused or with CacheFTPHandler.

maybe it's worth copying the issue text? Like, `:class:`urllib.request.CacheFTPHandler` no longer raises :class:`URLError` if a cached FTP instance is reused.`

**Comment by orsenthil** [comment]
@arhadthedev - sounds good to me.

**Comment by arhadthedev** [comment]
It seems <kbd>automerge<kbd> was ignored.

**Pull request merged**
