### PR TITLE
gh-119853:  Add Include/refcount.h file 

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-119853

### CODE REVIEW

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by vstinner** [comment]
* `Python.h` includes `object.h` before `refcount.h`.
* `object.h` refers to 2 macros defined in `refcount.h`: `PyObject_HEAD_INIT` refers to `_Py_IMMORTAL_REFCNT_LOCAL` and `PyObject_HEAD_INIT` refers to `_Py_IMMORTAL_REFCNT`. It works since the macro is not expanded before refcount.h is included.

**Comment by vstinner** [comment]
I prefer to not backport this change to 3.13, but it can make backport from 3.14 to 3.13 more complicated (doable, it's just more manual work if Git fails to track code move).

**Comment by corona10** [comment]
IMO, Backporting to 3.13 is worth doing it since we modified a lot of code at 3.13

**Comment by vstinner** [comment]
> IMO, Backporting to 3.13 is worth doing it since we modified a lot of code at 3.13

IMO it's too later after beta1.

**Review by colesbury — APPROVED** [review]

**Comment by vstinner** [comment]
Merged, thanks for the review. I don't plan to backport the change to 3.13 since we are past the feature freeze.

**Pull request merged**
