### PR TITLE
gh-112532: Fix peg generator build.py for mimalloc build

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-112532

### CODE REVIEW

**Comment by corona10** [comment]
@colesbury 
## AS-IS
```
➜  cpython git:(main) ✗ ./python.exe -m test test_peg_generator
Using random seed: 2669052678
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 3.38 Run 1 test sequentially
0:00:00 load avg: 3.38 [1/1] test_peg_generator
/Users/user/oss/cpython/build/test_python_worker_29863æ/tempcwd/venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/_envs.py:111: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pip._vendor.pkg_resources import find_distributions
Processing /Users/user/oss/cpython/Lib/test/setuptools-67.6.1-py3-none-any.whl
/Users/user/oss/cpython/build/test_python_worker_29863æ/tempcwd/venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/_dists.py:73: DeprecationWarning: Unimplemented abstract methods {'locate_file'}
  return cls(files, info_location)
Processing /Users/user/oss/cpython/Lib/test/wheel-0.40.0-py3-none-any.whl
Installing collected packages: wheel, setuptools
/Users/user/oss/cpython/build/test_python_worker_29863æ/tempcwd/venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/_dists.py:73: DeprecationWarning: Unimplemented abstract methods {'locate_file'}
  return cls(files, info_location)
Successfully installed setuptools-67.6.1 wheel-0.40.0
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
         ^~~~~~~~~~~~
1 error generated.
In file included from /Users/user/oss/cpython/Python/Python-ast.c:6:
In file included from /Users/user/oss/cpython/Include/internal/pycore_ceval.h:13:
In file included from /Users/user/oss/cpython/Include/internal/pycore_interp.h:32:
In file included from /Users/user/oss/cpython/Include/internal/pycore_tstate.h:11:
/Users/user/oss/cpython/Include/internal/pycore_mimalloc.h:32:10: fatal error: 'mimalloc.h' file not found
#include "mimalloc.h"
```

## TO-BE
```
➜  cpython git:(gh-112532-fix) ✗ ./python.exe -m test test_peg_generator
Using random seed: 3314716989
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 3.00 Run 1 test sequentially
0:00:00 load avg: 3.00 [1/1] test_peg_generator
/Users/user/oss/cpython/build/test_python_worker_29244æ/tempcwd/venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/_envs.py:111: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pip._vendor.pkg_resources import find_distributions
Processing /Users/user/oss/cpython/Lib/test/setuptools-67.6.1-py3-none-any.whl
/Users/user/oss/cpython/build/test_python_worker_29244æ/tempcwd/venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/_dists.py:73: DeprecationWarning: Unimplemented abstract methods {'locate_file'}
  return cls(files, info_location)
Processing /Users/user/oss/cpython/Lib/test/wheel-0.40.0-py3-none-any.whl
Installing collected packages: wheel, setuptools
/Users/user/oss/cpython/build/test_python_worker_29244æ/tempcwd/venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/_dists.py:73: DeprecationWarning: Unimplemented abstract methods {'locate_file'}
  return cls(files, info_location)
Successfully installed setuptools-67.6.1 wheel-0.40.0
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: -undefined dynamic_lookup may not work with chained fixups

== Tests result: SUCCESS ==

1 test OK.

Total duration: 14.3 sec
Total tests: run=92
Total test files: run=1/1
Result: SUCCESS
```

**Review by pablogsal — APPROVED** [review]
I assume we can do this unconditionally on the mimalloc build no?

**Comment by corona10** [comment]
> I assume we can do this unconditionally on the mimalloc build no?

Or we can use `support.with_mimalloc()`, but not a good use case for this script.

**Comment by pablogsal** [comment]
Nah is fine, just wanted to ensure that the header include is correct independently if we have mimalloc or not

**Review by colesbury — APPROVED** [review]
Thanks for fixing this. 

Yeah, I think the include path is fine even if we are not compiling with mimalloc support.

**Comment by corona10** [comment]
We always include `mimalloc` headers through makefile.pre.in, so it's technically fine.
https://github.com/python/cpython/blob/acf3bcc8861983dcd6896682283a480450f9a1e3/Makefile.pre.in#L1798

**Pull request merged**
