### PR TITLE
Doc: tutorial/classes: refs to dataclasses & NamedTuple

### PR DESCRIPTION
**Pull request by westurner**
Links to dataclasses and NamedTuple

### CODE REVIEW

**Comment by methane** [comment]
I want to keep the tutorial necessary and sufficient.
I don't want to write everything which may be useful for readers.

So I don't think this note is not needed in the tutorial.

**Comment by westurner** [comment]
I understand your objectives.

I don't think class attributes are a good recommendation as an analogue for
structs. NamedTuple and classes or dataclasses with `__slots__` are closer
to comparably performant.

Run %timeit with classes and compare that to structs.

**Comment by methane** [comment]
It is not enough reason to confuse tutorial readers.  I strong -1 about referring "type checking" and `__slots__`.  Readers may not know anything about them yet.

I think we should:

* Remove the paragraph completely, or
* Add simple note (e.g. `..note ::`) without referring any technical detail.

```
.. note::
    The :mod:`dataclasses` module provides better way to create record-like classes.
```

**Comment by westurner** [comment]
A .. note:: would be good.

NamedTuple is closer to struct and so also worth mentioning?

I'll update the PR later today to remove mention of __slots__ and enclose
these sentences in a .. note:: directive.

On Monday, November 11, 2019, Inada Naoki <notifications@github.com> wrote:
> It is not enough reason to confuse tutorial readers. I strong -1 about
referring "type checking" and __slots__. Readers may not know anything
about them yet.
>
> I think we should:
>
> Remove the paragraph completely, or
> Add simple note (e.g. ..note ::) without referring any technical detail.
>
> .. note::
> The :mod:`dataclasses` module provides better way to create record-like
classes.

**Comment by methane** [comment]
> NamedTuple is closer to struct and so also worth mentioning?

It is tuple, and immutable.  It is far from struct in the example above.

**Comment by westurner** [comment]
A class dict (even with `__slots__` defined) is also far from a const
struct.

NamedTuple is closer to struct in terms of performance.

**Comment by westurner** [comment]
How would you suggest this should be worded?

On Tuesday, November 12, 2019, Wes Turner <wes.turner@gmail.com> wrote:
> A class dict (even with `__slots__` defined) is also far from a const
struct.
>
> NamedTuple is closer to struct in terms of performance.
>
> On Tuesday, November 12, 2019, Inada Naoki <notifications@github.com>
wrote:

**Comment by methane** [comment]
> A class dict (even with `__slots__` defined) is also far from a const struct.

Why "const struct"?  This paragraph refers C "struct" and Pascal "record".

> NamedTuple is closer to struct in terms of performance.

It is out of scope of this tutorial.  Namedtuple can't replace the example above because it is immutable.

The goal of this chapter is intorducing class, not useful parts of stdlibs.

My preference is removing the paragraph and example about struct completely, or even entire the "Odds and Ends" section.

**Comment by methane** [comment]
As looking through the chapter, I still +1 to remove the paragraph or entire section.

Defining class with members is described in 9.3.2 "Class Objects", and 9.3.3 "Instance Objects".
This paragraph only introduces a dirty hack.  If the hack is not recommended why not remove it?

On the other hand, if you really want to introduce dataclass and namedtuple, I'm OK to adding new section before 9.4 "Random Remarks".

The section will intorduce dataclass first, and namedtuple later.

**Pull request closed without merging**
