### PR TITLE
docs: fix dangling `tp_alloc` [bug] in extending/newtypes_tutorial

### PR DESCRIPTION
**Pull request by casperdcl**
Fixes a pretty major malloc error in the docs.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@casperdcl

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by casperdcl** [comment]
Ping

**Comment by casperdcl** [comment]
@vstinner @serhiy-storchaka maybe you could take a look?

**Comment by vstinner** [comment]
> Fixes a pretty major malloc error in the docs.

Please elaborate. I don't understand which problem you are trying to solve.

**Comment by casperdcl** [comment]
The CPython API docs currently effectively suggest `malloc(0 * sizeof(T))` when it should be `malloc(1 * sizeof(T))` to create a new object. This PR fixes this.

**Comment by vstinner** [comment]
> The CPython API docs currently effectively suggest malloc(0 * sizeof(T)) when it should be malloc(1 * sizeof(T)) to create a new object. This PR fixes this.

tp_alloc(type, 0) doesn't call malloc().

The default allocator function is PyType_GenericAlloc() which uses:

```
    const size_t size = _PyObject_VAR_SIZE(type, nitems+1);
```

which is defined as:

```
#define _PyObject_VAR_SIZE(typeobj, nitems)     \
    _Py_SIZE_ROUND_UP((typeobj)->tp_basicsize + \
        (nitems)*(typeobj)->tp_itemsize,        \
        SIZEOF_VOID_P)
```

tp_alloc(type, 0) allocates types->tp_basicsize. In the tutorial, tp_basicsize is defined as:

```
.tp_basicsize = sizeof(CustomObject),
```

In short, IMO the current code is correct, and your change wastes memory.

**Comment by casperdcl** [comment]
Hmm `nitems+1`... curious. I had a code snippet which crashed and changing `tp_alloc(type, 0)` to `tp_alloc(type, 1)` fixed it. Will see if I can reproduce it again and post a minimal example.

**Pull request closed without merging**
