### PR TITLE
bpo-40077: Add traverse/clear/free to arraymodule

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue40077

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@encukou, would you mind reviewing this?

**Review by shihai1991 — APPROVED** [review]
LGTM.
Just a nitpick: `PyObject *m`--> `PyObject *module` or `PyObject *mod` would be more exact.

**Comment by erlend-aasland** [comment]
> LGTM.
> 
> Just a nitpick: `PyObject *m`--> `PyObject *module` or `PyObject *mod` would be more exact.

I agree. I'll fix it.

**Comment by encukou** [comment]
Thank you!

**Pull request merged**
