### PR TITLE
[3.11] GH-93354: Use exponential backoff to avoid excessive specialization attempts (GH-93355)

### PR DESCRIPTION
**Pull request by markshannon**
Backport of #93355

This doesn't fix any obvious bugs in 3.11, but it is a preventative fix.

Specialization of some instructions can be quite expensive (relative to the cost of executing the instruction), so we want to avoid excessive numbers of failed specializations for corner cases that we might not yet be aware of.

@pablogsal 

* Issue: gh-93354

### CODE REVIEW

**Comment by pablogsal** [comment]
Seems there is a bunch of compiler warnings (check the "Files" tab in this PR). Also, there is a lot of code here and I am not sure I feel very confident merging this so I suppose it depends on how bd is the regression we are fixing. Could you elaborate with some benchmarks on the cases this is fixing (I know there is an explanation on the issue, but I want some discussion here specific for 3.11).

Also, if we decided to go with this, we are going to need at least 2 other core devs to review and approve this change.

**Review by Fidget-Spinner — APPROVED** [review]
This LGTM.

Re: what Pablo said. IMO the risk of introducing bugs with this change is low. At worst we degrade performance a little. I don't see how this could introduce anything majorly breaking.

**Review by Fidget-Spinner — CHANGES_REQUESTED** [review]
Wait, I think we need to apply the changes to these lines too:

https://github.com/python/cpython/blob/6b330002b19d8cc3a5733b5ce030b199deb37f95/Python/ceval.c#L5605-L5613

I suddenly noticed on my main branch that it now takes 53 misses to deopt an instruction. That seems high.

**Comment by Fidget-Spinner** [comment]
> I suddenly noticed on my main branch that it now takes 53 misses to deopt an instruction. That seems high.

I opened https://github.com/python/cpython/pull/93860 to fix that.

**Review by Fidget-Spinner — APPROVED** [review]
My bad, that was confusion on my part. Once again this LGTM.

**Comment by pablogsal** [comment]
@markshannon Can you please rebase this so I can land it to the new beta?

**Pull request merged**
