### PR TITLE
Fix `dl_nt.c` incorrect indentation

### PR DESCRIPTION
**Pull request by rruuaanng**

### CODE REVIEW

**Comment by rruuaanng** [comment]
cc @skirpichev

**Comment by skirpichev** [comment]
See https://devguide.python.org/getting-started/pull-request-lifecycle/#making-good-prs

"Pull requests with only code formatting changes are usually rejected." (c)

**Comment by rruuaanng** [comment]
> See https://devguide.python.org/getting-started/pull-request-lifecycle/#making-good-prs
> 
> "Pull requests with only code formatting changes are usually rejected." (c)

This commit only fixes the indentation, I don't think any other extra changes are needed.

**Comment by zooba** [comment]
The point @skirpichev is making is that we don't accept cosmetic PRs. When some functionality is causing us to change code in that area, we'll fix up the formatting, but we don't want people spending time going through tweaking cosmetics all the time.

**Pull request closed without merging**
