### PR TITLE
gh-113234: Add remaining TOML types to conversation table

### LINKED ISSUE #113234: Add remaining TOML types to tomllib conversation table documentation
# Documentation

[The conversion table for Python's TOML parser](https://docs.python.org/3/library/tomllib.html#conversion-table) does not contain entries for two types listed on the TOML specification:

1. inline table (dict)
2. array of tables (list of dicts)

Adding those entries to the conversion table will make it more clear how the objects are represented in Python when using `tomllib.load`.

### Linked PRs
* gh-113236
* gh-113283
* gh-113284

### PR DESCRIPTION
**Pull request by ryan-duve**
Resolves #113234

This adds two entries to the documentation for the conversion table for TOML.

* Issue: gh-113234

----
📚 Documentation preview 📚: https://cpython-previews--113236.org.readthedocs.build/

### CODE REVIEW

**Comment by encukou** [comment]
There's value in matching the TOML spec, and technically-redundant entries won't hurt. (For sufficiently advanced users, all of the table falls under “common sense” anyway...)

Given that the spec lists these types last, and they're technically redundant (so, less important to document), could you move them to the end of the table?

Maybe it would be best to then try to match the spec even more. (The spec has a well-thought ordering, IMO!):
- Move “table” between “Array” and the new “Inline table”, to match its position in the TOML spec
- Add a new entry “TOML document → dict” to the beginning.

@hukkin & @hauntsaninja, any opinions?

**Comment by ryan-duve** [comment]
> Given that the spec lists these types last, and they're technically redundant (so, less important to document), could you move them to the end of the table?

@encukou I reordered these rows and added "_TOML document_" in aa96a62b9e5237891c8949199012b76f8bc65fbe

**Review by hauntsaninja — APPROVED** [review]
Seems reasonable enough to me! :-)

**Comment by hugovk** [comment]
@ryan-duve Congratulations and thank you for your first CPython PR! 🎉

**Pull request merged**
