### PR TITLE
Backport bd583ef 3.6

### PR DESCRIPTION
**Pull request by Soares**
I think I followed the backporting instructions at https://docs.python.org/devguide/committing.html?highlight=backport correctly, but this is my first time, so please let me know if I erred, as is fairly likely.

### CODE REVIEW

**Comment by Soares** [comment]
I'm also planning to backport PR #678, which depends on this backport (of PR #527). I assume that I shouldn't begin that backport until this one is accepted, but let me know if I can begin the backport of #678 now.

**Comment by vstinner** [comment]
There is an issue on the Misc/NEWS merge :-/

**Comment by Soares** [comment]
Oops. I don't see an easy way to fix this using the cherry_picker tool, so I'm going to abandon this PR and make a new one (merging correctly) this time, unless you object.

Also, I note that there's a "No issue number in the title or "trivial" label" problem listed in 'checks'. Do you want me to add the issue label of the original issue (for which this is a backport), or stick with the auto-generated backport PR name?

**Comment by ncoghlan** [comment]
@Soares The preferred format for backport PR titles is "[X.Y] bpo-NNNNN: ...", where X.Y is the target branch and NNNNN is the bugs.python.org issue number

**Pull request closed without merging**
