### PR TITLE
gh-125698: Replace EXEEXT with EXE_SUFFIX

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-125698

### CODE REVIEW

**Comment by erlend-aasland** [comment]
We might need a NEWS entry for this for the build section. I'm not sure yet.

**Review by ned-deily — APPROVED** [review]
From a visual inspection (without any build testing), the changes look OK and harmless to me. It appears that the current `EXEEXT` is used only for creating the configured `Makefile` and doesn't appear as a variable directly in the finished product. So that doesn't seem like it counts as an external interface requiring documentation.

**Comment by erlend-aasland** [comment]
Thank for the review, Ned. Yeah, that was my conclusion as well.

**Comment by erlend-aasland** [comment]
I'll land this in a couple of days, in case anyone has objections.

**Comment by erlend-aasland** [comment]
Reverted in:

- #125758

**Pull request merged**
