### PR TITLE
gh-99108: Import SHA2-384/512 from HACL*

### PR DESCRIPTION
**Pull request by msprotz**
Followup on #99108, and almost identical to #99109 

* Issue: gh-99108

### CODE REVIEW

**Comment by msprotz** [comment]
(I pulled the wrong revision of HACL*, hence the build breakage -- I'll fix this shortly.)

**Review by erlend-aasland — APPROVED** [review]
Build system changes look good to me.

**Review by gpshead — APPROVED** [review]

**Comment by msprotz** [comment]
Thanks for merging, @gpshead. It looks like this broke the wasm build because there are now duplicate symbols. If I had to guess, I would say that the use-case where two C files in Modules/ depend on the *same* C file did not show up before in the build.

Would it be enough to remove one of the two references to Hacl_Streaming_SHA2.c in Modules/Setup.stdlib.in?

**Comment by gpshead** [comment]
I _doubt_ just removing one reference is enough?  Looking at things I _suspect_ what we want is for the _hacl/ stuff to be built into a single .a library and the sha256module.c and sha512module.c to both link against that.  so that they pull only the symbols they use in, instead of what appears to be happening today where both extension module libraries wind up with all of the symbols from the `Modules/_hacl/Hacl_Streaming_SHA2.c` present and exported.

This should require some `Makefile.pre.in` work.  similar to how `_decimal` uses `libmpdec` and `expat` uses `libexpat.a`.

I untangling this.

**Comment by gpshead** [comment]
That fixes 2/4 of the build bot failures. the remaining wasm32-enscripten dynamic failures are because that uses --whole-archive linking so the duplicates (duplicate as in the .a file is listed twice on the wasm-ld command line at this point) cause trouble. I'm going to follow up with a refactoring PR that merges _sha256 and _sha512 into a single _sha2 module. Those two don't need to be separate modules, that is a historical oddity.

**Pull request merged**
