### PR TITLE
bpo-29869: Allow underscores in numeric literals in lib2to3.

### PR DESCRIPTION
**Pull request by nevsan**
I found this while debugging https://github.com/google/yapf/issues/370. The fix is quite simple and quick.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/). The "bugs.python.org username" requested by the form is the "Login name" field in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/23276970/d14a380c-f9d1-11e6-883d-e13b6b211239.png)
2. **Wait at least one US business day** and then check the "Contributor form received entry under "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by nevsan** [comment]
I have completed the above steps.

**Comment by brettcannon** [comment]
Could you open an issue for this on bugs.python.org, @nevsan and mention it in the title? (see the [contributing guidelines](https://github.com/python/cpython/blob/master/.github/CONTRIBUTING.rst#contribution-guidelines) for info.)

**Comment by nevsan** [comment]
The existing regular expressions weren't actually strict enough as is, so I made them even more correct. In particular, we must have at least one digit following `0[xXbBoO]` and must be before any underscores.

I have a small set of test cases to examine correctness of these regular expressions: https://gist.github.com/nevsan/7fc78dc61d309842406d67d6839b9861

**Comment by nevsan** [comment]
Updated regular expressions to avoid catastrophic backtracking. Gist updated with new test cases (still passes).

**Comment by brettcannon** [comment]
@nevsan looks like Travis disagrees that the tests still pass 😉

**Comment by nevsan** [comment]
Took a few iterations, but I managed to fix up the regexes. I also added a test case to test numeric literals with underscores (and verified that it fails for the un-patched HEAD).

**Comment by rhettinger** [comment]
LGTM

**Comment by brettcannon** [comment]
@rhettinger would you mind officially registering your review approval? You can do that by going under "Files changed", clicking the green "Review changes", and then you can choose "Approve" and submit the review. Perk of this is your approval will show up under Reviewers so if another core dev has the time to merge and backport they know someone else already cleared the code.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
@nevsan Can you create the PR against the `master` branch?

**Pull request merged**
