### PR TITLE
[3.5] bpo-31095: fix potential crash during GC

### PR DESCRIPTION
**Pull request by methane**
(cherry picked from commit a6296d34a478b4f697ea9db798146195075d496c)

https://bugs.python.org/issue31095

### CODE REVIEW

**Comment by larryhastings** [comment]
Hi, Steve, this is failing on link, can you look in to it?

**Comment by methane** [comment]
Link error message in AppVeyor:

```
[00:03:36]   Finished generating code
[00:03:37]      Creating library C:\projects\cpython\PCBuild\win32\_elementtree.lib and object C:\projects\cpython\PCBuild\win32\_elementtree.exp
[00:03:37] xmlparse.obj : error LNK2001: unresolved external symbol __Expat_LoadLibrary [C:\projects\cpython\PCbuild\_elementtree.vcxproj]
[00:03:37] C:\projects\cpython\PCBuild\win32\_elementtree.pyd : fatal error LNK1120: 1 unresolved externals [C:\projects\cpython\PCbuild\_elementtree.vcxproj]
```

**Comment by zooba** [comment]
Looks like the pyexpat.vcxproj file was never updated with the last update, and whoever merged that updated didn't run appveyor (or they ignored the failure).

I'll send a PR to update the file. Looks like 3.6 got the change okay, so guessing it's just 3.5.

**Comment by zooba** [comment]
See #3751 for the fix.

**Pull request merged**
