### PR TITLE
Minor refactoring to use enumerate in loops

### PR DESCRIPTION
**Pull request by rth**
# Minor refactoring to use enumerate in loops

The overall goal is to replace code of the form,
```py
for i in range(len(x)):
   val = x[i]
```
with,
```py
for i, val in enumerate(x):
```

Which should be around 2x faster,
```
In [8]: x = list(range(10))                                                                                                                                  

In [9]: %timeit [(idx, x[idx]) for idx in range(len(x))]                                                                                                     
1.29 µs ± 11.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [10]: %timeit list(enumerate(x))                                                                                                                          
641 ns ± 12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [5]: x = list(range(1000))                                                                                                                                

In [6]: %timeit [(idx, x[idx]) for idx in range(len(x))]                                                                                                     
80.7 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [7]: %timeit list(enumerate(x))                                                                                                                           
42.8 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
and a bit more readable.

Also refactored to use `zip` in places where it made sense instead.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by serhiy-storchaka** [comment]
This is a pure cosmetic change which involves a lot of files. Usually we do not perform such kind of changes.

**Comment by rth** [comment]
@serhiy-storchaka Thanks for the feedback!

What would be the preferred way to incorporate such changes: taking a single stdlib module and making them there, preferably proving that they could have an impact on performance in some cases (this PR probably doesn't)? Is there a standard benchmark suite somewhere? Or are you generally against refactoring changes for the sake of stability and due to the risk of regressions?

**Comment by terryjreedy** [comment]
Balancing the benefits and costs of updates is tricky and different core developers sometimes disagree.  Accepted  patches to multiple unrelated files tend make local changes within single lines that can be reviewed in isolation, and perhaps backported  -- to avoid introducing potential bugfix merge conflicts.  Examples are spelling fixes (though there are people who would leave them alone), replacement of deprecated synonyms such as some unittest assertXXX names, and (today) replacement of '1/0' with '1//0' in 2.7 tests to avoid DeprecationWarnings.

These changes are not so trivial and require more review, and I would want to check the corresponding tests before merging.  (Those I looked at looked good, so I hope you do not disappear.)  So the single-file alternative you asked about applies: update in the process of fixing a bug or improving performance, likely with a test upgrade.

Time comparisons should compare the actual before and after.  Comparing list(enumerate) and a list comprehension is not the save as comparing two versions of a for loop.

Non-trivial PRs, such as this, should start with a tracker issue and CLA signing.  This should be in the devguide somewhere.

(As main IDLE maintainer, I could apply and backport the debugger.py change, but the double implied de-structuring of  "for i, (frame, lineno) in enumerate(stack):" makes it the least favorite of those I checked.)

**Comment by rth** [comment]
Thanks for the detailed explanations @terryjreedy ! I understand, will try to make smaller PRs with an associated issue.

**Pull request closed without merging**
