### PR TITLE
[3.11] gh-108822: Backport libregrtest changes from the main branch

### PR DESCRIPTION
**Pull request by vstinner**
* regrtest computes statistics (#108793)
* gh-108388: regrtest splits test_asyncio package (#108393)
* gh-90791: test.pythoninfo logs ASAN_OPTIONS env var (#108289)
* gh-108223: test.pythoninfo and libregrtest log Py_NOGIL (#108238)
* gh-101634: regrtest reports decoding error as failed test (#106169)
* Display the sanitizer config in the regrtest header. (#105301)
* gh-82054: allow test runner to split test_asyncio to execute in parallel by sharding. (#103927)
* bpo-46523: fix tests rerun when `setUp[Class|Module]` fails (#30895)
* gh-100086: Add build info to test.libregrtest (#100093)
* gh-98903: Test suite fails with exit code 4 if no tests ran (#98904)
* gh-95027: Fix regrtest stdout encoding on Windows (#98492)
* gh-96465: Clear fractions hash lru_cache under refleak testing (GH-96689)
* gh-94026: Buffer regrtest worker stdout in temporary file (GH-94253)
* Run Tools/scripts/reindent.py (#94225)
* gh-94052: Don't re-run failed tests with --python option (#94054)
* gh-84461: Fix Emscripten umask and permission issues (GH-94002)
* gh-93353: regrtest supports checking tmp files with -j2 (#93909)
* gh-93353: Fix regrtest for -jN with N >= 2 (GH-93813)
* gh-93353: regrtest checks for leaked temporary files (#93776)
* Revert "[3.11] gh-84461: Fix Emscripten umask and permission issues (GH-94002) (GH-94006)"
* Revert "gh-94052: Don't re-run failed tests with --python option (GH-94054)"
* Revert "Run Tools/scripts/reindent.py (GH-94225)"
* Revert "[3.11] gh-94026: Buffer regrtest worker stdout in temporary file (GH-94253) (GH-94408)"
* Revert "gh-95027: Fix regrtest stdout encoding on Windows (GH-98492)"
* Revert "[3.11] bpo-46523: fix tests rerun when `setUp[Class|Module]` fails (GH-30895) (GH-103342)"
* Revert "[3.11] gh-101634: regrtest reports decoding error as failed test (#106169) (#106175)"

* Issue: gh-108822

### CODE REVIEW

**Comment by vstinner** [comment]
I had to revert multiple changes and cherry-pick them again to reduce the number of merge conflicts.

This PR adds 5 NEWS entries.

---

regrtest now checks if a test leaks temporary files or directories if run
with -jN option. Patch by Victor Stinner.

On Windows, when the Python test suite is run with the ``-jN`` option, the
ANSI code page is now used as the encoding for the stdout temporary file,
rather than using UTF-8 which can lead to decoding errors. Patch by Victor
Stinner.

The Python test suite now fails wit exit code 4 if no tests ran. It should
help detecting typos in test names and test methods.

The Python test runner (libregrtest) now logs Python build information like
"debug" vs "release" build, or LTO and PGO optimizations. Patch by Victor
Stinner.

When running the Python test suite with ``-jN`` option, if a worker stdout
cannot be decoded from the locale encoding report a failed testn so the
exitcode is non-zero. Patch by Victor Stinner.

**Comment by vstinner** [comment]
I will wait until the NEW entry is added by https://github.com/python/cpython/pull/108821 to also include it in this 3.11 backport.

**Comment by vstinner** [comment]
Ok, I added the Changelog entry for statistics:

```
``regrtest`` now computes statistics on all tests: successes, failures and
skipped. ``test_netrc``, ``test_pep646_syntax`` and ``test_xml_etree`` now
return results in their ``test_main()`` function. Patch by Victor Stinner
and Alex Waygood.
```

**Comment by vstinner** [comment]
> regrtest now checks if a test leaks temporary files or directories

This change is related the issue #93353. It was a bug triggered by pip fixed in May 2022 by fixing importlib.resources._tempfile() finalizer: commit https://github.com/python/cpython/commit/dc6dd8ee873ed96027d30c8a2e96518657d46241 (backport to 3.11). The issue was also reported to pip: issue https://github.com/pypa/pip/issues/10753.

Python 3.11 test suite should not leak temporary files. It should be fine to backport this new check.

**Comment by serhiy-storchaka** [comment]
Wow, wow, WOW!

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

You cannot believe that I reviewed all these changes. I did not. I compared the result with the main branch.

**Comment by vstinner** [comment]
Merged, thanks for the review.

**Comment by vstinner** [comment]
> You cannot believe that I reviewed all these changes. I did not. I compared the result with the main branch.

Sure, I would do the same :-) I also trust ``test_regrtest`` to catch the most obvious issues ;-)

**Comment by vstinner** [comment]
> Hi! The buildbot wasm32-wasi 3.11 has failed when building commit https://github.com/python/cpython/commit/79f7a4c0a4ae6c39e6a893b060b4557e09d0ac18.
> test_tomllib

I created PR #108851 for this issue.

**Pull request merged**
