### PR TITLE
Also fail DO-NOT-MERGE when "awaiting changes" or "awaiting change review" present on PR

### PR DESCRIPTION
**Pull request by ambv**
"awaiting changes" means somebody put a review that requested changes.

"awaiting change review" means that the PR author published changes after a red review and then requested a re-review.

### CODE REVIEW

**Review by Mariatta — DISMISSED** [review]
Re-review this

**Comment by hugovk** [comment]
If we merge this, we need to add this new job name as a required check:

image

And remove the old one.

We'll have some PRs out of sync (unless we keep the old name).

**Comment by ambv** [comment]
I have made the requested changes; please review again.

**Comment by ambv** [comment]
(I didn't actually make the changes, I wanted to see if it still jumps to the red check, which it did.)

**Comment by ambv** [comment]
I believe we sadly have to change the name of the check because it is otherwise too misleading for the case of "awaiting changes".

**Comment by ambv** [comment]
It does!

**Pull request merged**
