### PR TITLE
bpo-46072: Include length in stats for UNPACK_SEQUENCE.

### PR DESCRIPTION
**Pull request by markshannon**
Even more stats!

https://bugs.python.org/issue46072

### CODE REVIEW

**Review by brandtbucher — APPROVED** [review]
Nice, I'm curious to see the results.

(I'm gonna be *really* surprised if anybody is out here unpacking zero-length iterables, though.)

**Comment by sweeneyde** [comment]
> (I'm gonna be _really_ surprised if anybody is out here unpacking zero-length iterables, though.)

To my surprise, this works:
```
() = []
```

**Comment by brandtbucher** [comment]
> > (I'm gonna be _really_ surprised if anybody is out here unpacking zero-length iterables, though.)
> 
> 
> 
> To my surprise, this works:
> 
> ```
> 
> () = []
> 
> ```

...for some definition of "works". The whole thing gets peepholed out. ;)

I think maybe once long ago I used something like this to "assert" that an iterator I used was completely exhausted (the idea being that it would raise a `TypeError` if not):

```py
it = iter(something)
# Do some stuff.
[] = it  # Fails if there are remaining items.
```

**Comment by markshannon** [comment]
`UNPACK_SEQUENCE 0` does occur. In this:

```Python
def f(x):
    match x:
        case T():
            pass
```

```
  1           0 RESUME                   0

  2           2 LOAD_FAST                0 (x)

  3           4 LOAD_GLOBAL              0 (T)
              6 LOAD_CONST               1 (())
              8 MATCH_CLASS              0
             10 COPY                     1
             12 POP_JUMP_IF_NONE        10 (to 20)
             14 UNPACK_SEQUENCE          0

  4          16 LOAD_CONST               0 (None)
             18 RETURN_VALUE

  3     >>   20 POP_TOP
             22 LOAD_CONST               0 (None)
             24 RETURN_VALUE
```

**Comment by brandtbucher** [comment]
> `UNPACK_SEQUENCE 0` does occur.

Interesting. That's a common case that's worth improving.

**Pull request merged**
