### PR TITLE
Fix typos in HISTORY documentation

### PR DESCRIPTION
**Pull request by xyb**

### CODE REVIEW

**Review by blaisep — APPROVED** [review]
Hello @xyb , thank you very much for these corrections, they look very good. I will ask @CAM-Gerlach to consider merging this PR because it looks clean.

**Comment by blaisep** [comment]
@CAM-Gerlach , this PR will need labels for skip-issue (and maybe skip-news). I don't think I can add those labels myself.

**Comment by xyb** [comment]
@CAM-Gerlach @hauntsaninja @serhiy-storchaka @AlexWaygood Please take a look, thank you!

**Comment by hugovk** [comment]
> @CAM-Gerlach @hauntsaninja @serhiy-storchaka @AlexWaygood Please take a look, thank you!

Thanks for the PR, but no need to ping four core devs about it 👍

**Pull request merged**
