### PR TITLE
bpo-40066: Revert "Revert "bpo-40066: [Enum] update str() and format() output..."

### PR DESCRIPTION
**Pull request by kumaraditya303**
https://bugs.python.org/issue40066

### CODE REVIEW

**Comment by kumaraditya303** [comment]
cc @vstinner  fixed doc CI

**Comment by vstinner** [comment]
I would prefer that @ethanfurman makes this PR to keep the ownership of the large change (that I reverted). But thanks for the doc fix! ``>>> Color(0) # doctest: +SKIP`` seems to work.

**Review by ethanfurman — APPROVED** [review]

**Comment by vstinner** [comment]
Oh it's now merged, thanks!

**Comment by ethanfurman** [comment]
Woops.  Guess my merging etiquette still needs some work.  :-/

**Pull request merged**
