### PR TITLE
Remove unused `Any` from Concatenate example

### PR DESCRIPTION
**Pull request by michaeloliverx**

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Good catch!

PS. Do you plan to sign the CLA? While I can merge small changes like these without the CLA, if you plan for bigger contributions in the future, you'll need to sign the CLA eventually.

**Comment by michaeloliverx** [comment]
Hi, yes I have just signed it. It might take a while for it to update.

**Review by Fidget-Spinner — APPROVED** [review]
> Hi, yes I have just signed it. It might take a while for it to update.

Great to hear! Thank you for fixing up the docs. I'll merge this in a day or two.

**Comment by Fidget-Spinner** [comment]
@michaeloliverx congrats! You're now a CPython contributor.

**Pull request merged**
