### PR TITLE
bpo-33852: Remove misplaced parentheses around 'list'.

### PR DESCRIPTION
**Pull request by andresdelfino**
https://bugs.python.org/issue33852

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
I think parentheses are intentional. "list must evaluate to an integer" looks weird.

Please open an issue on the bug tracker and discuss this change with the original author.

**Comment by andresdelfino** [comment]
Thanks for the review, Serhiy!

I'm adding the issue number now.

**Review by gvanrossum — APPROVED** [review]
Yeah, the previous paragraph uses similar words without parentheses.

**Comment by terryjreedy** [comment]
It is 'expression list' that must evaluate to whatever, referring back to `expression_list` in the grammar production.
```
subscription: `primary` "[" `expression_list` "]"
```
I don't think this needs a news entry.

**Pull request merged**
