### PR TITLE
gh-126731: Update outdated project information in `pprint.pp` doc

### PR DESCRIPTION
**Pull request by Wulian233**
Details please see the issue:)

skip news

* Issue: gh-126731

----
📚 Documentation preview 📚: https://cpython-previews--126732.org.readthedocs.build/

### CODE REVIEW

**Comment by Eclips4** [comment]
Sorry, but I'm against this change. It looks too big for our documentation, and it doesn't add any clarification, in my opinion. I think the suggestion from Brian (https://github.com/python/cpython/issues/126731#issuecomment-2470346389) would look more accurate.

**Comment by Wulian233** [comment]
Oops, I saw the suggestion in the issue first and pin version, do I need to cancel the change again and just change the fixed version (I'd love to do it)

**Comment by Eclips4** [comment]
> Oops, I saw the suggestion in the issue first and pin version, do I need to cancel the change again and just change the fixed version (I'd love to do it)

Yeah, I would like to see just a pinning to 1.2.0

**Comment by Eclips4** [comment]
> If pinning to anything, shall we pin to the old version 1.2.0 because it's much shorter? It doesn't matter what is in the response, merely that we get a bunch of JSON and that it's printed prettily.

I would like to see a pin to 1.2.0, just because it is shorter, yes.

**Comment by Wulian233** [comment]
Thanks your suggestions! I have made changes!

**Review by Eclips4 — APPROVED** [review]
LGTM. Thank you!

**Review by hauntsaninja — APPROVED** [review]
Looks like PyPI now also returns `yanked` and `yanked_reason`, but I don't think adding those really helps anything here. Thanks for the update!

**Pull request merged**
