### PR TITLE
bpo-40928 osx malloc real fix

### PR DESCRIPTION
**Pull request by jdevries3133**
Blocking any allocation call greater than 4TB prevents warnings appearing in STDERR on OS X.

https://bugs.python.org/issue40928

### CODE REVIEW

**Comment by jdevries3133** [comment]
This is one of two potential fixes I've provided for bpo-40928. This fix gets more to the core of the problem and silences the warnings we are concerned about.

The other fix, #26783 , is more of a band-aid.

**Comment by ambv** [comment]
What I don't like about this is that it will slow down all legit allocations to protect against stderr warnings for humongous allocations. Seems like a tough compromise.

**Comment by jdevries3133** [comment]
@ambv I got these results from the test-suite-as-a-benchmark approach:

| configuration          | jdevries3133:bpo-40928-osx-malloc-realfix | python:main  |
| ---------------------- | ----------------------------------------- | ------------ |
| --with-pydebug         | 3 min 42 sec                              | 3 min 44 sec |
| --enable-optimizations | 2 min 28 sec                              | 2 min 28 sec |

So, based on this rough test, it seems like the performance implications are very small. I don't know whether this is a reliable or valid metric, though.

**Comment by ambv** [comment]
ASAN failure is real, possibly this use case needs some build configuration adjustment. Currently reports:
```
Objects/obmalloc.c: In function ‘pymem_darwin_alloc_limit_exceeded’:
Error: Objects/obmalloc.c:97:16: error: ‘_Py_OSX_ALLOC_LIMIT’ undeclared (first use in this function)
   97 |     if (size > _Py_OSX_ALLOC_LIMIT) {
      |                ^~~~~~~~~~~~~~~~~~~
Objects/obmalloc.c:97:16: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by ambv** [comment]
I still feel like modifying malloc just to appease chatty diagnostics in super-unlikely conditions is not the right way to go about this, even if the perf cost is minimal in your benchmarks. Since this problem is isolated to test_decimal, I went with your string notice patch instead (GH-26783).

**Pull request closed without merging**
