### PR TITLE
bpo-32087: Set appropriate "translatable" attributes for nodes

### PR DESCRIPTION
**Pull request by cocoatomo**
see [bpo-32087](https://bugs.python.org/issue32087).

https://bugs.python.org/issue32087

### CODE REVIEW

**Comment by cocoatomo** [comment]
Could someone attach a label "skip news"?

**Comment by methane** [comment]
I think translatable message shouldn't have fixed wording order.
Would you replace `%s` to `{deprecated}` and `{removed}`, and use `.format(deprecated=self.arguments[0], removed=self.arguments[1])` instead of `%`?

**Comment by cocoatomo** [comment]
Thank you for your comment.
I considered only the case of translating into Japanese.
For some languages, a reversed order of words may be natural.

I will change to use field name syntax.

**Comment by methane** [comment]
Python 2.7 doesn't have "deprecated-removed" directive.

**Pull request merged**
