### PR TITLE
bpo-40656: Clean up detect_socket()

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue40656

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Ref. discussion in #19526, @ned-deily.

**Comment by erlend-aasland** [comment]
@ned-deily would you mind taking a look at this?

**Review by ned-deily — APPROVED** [review]
Looks much cleaner, thanks. I think we can dispense with a news entry for this.

**Comment by erlend-aasland** [comment]
Thanks for reviewing, @ned-deily !

**Pull request merged**
