### PR TITLE
bpo-37193: remove thread objects which finished process its request

### PR DESCRIPTION
**Pull request by jaraco**
Reverts python/cpython#23107 (re-submit of python/cpython#13893)

https://bugs.python.org/issue37193

Automerge-Triggered-By: GH:jaraco

### CODE REVIEW

**Comment by jaraco** [comment]
I was able to replicate the reported failure locally by building a debug version of Python and running with refchecks:

```
$ ./configure --with-pydebug && make
$ ./python.exe Tools/scripts/run_tests.py -R 3:3 test.test_socketserver
```

**Comment by jaraco** [comment]
I've confirmed that the there are leaks in tests not added in this patch, including `test_ThreadingUnixStreamServer`.

**Comment by jaraco** [comment]
I've tried:

- removing the `lock` object on `_Threads`
- deleting the `_threads` property on `server_close`
- other miscellaneous tweaks

But I've been unsuccessful in identifying the cause of the leaks.

@vstinner Do you have any insight into the cause of the leaks?

**Comment by jaraco** [comment]
I've found that applying this diff stops the memory leaks:

```
diff --git a/Lib/socketserver.py b/Lib/socketserver.py
index 6859b69682..751772ef65 100644
--- a/Lib/socketserver.py
+++ b/Lib/socketserver.py
@@ -646,7 +646,7 @@ def remove(self, thread):
         with self._lock:
             # should not happen, but safe to ignore
             with contextlib.suppress(ValueError):
-                super().remove(thread)
+                pass  # super().remove(thread)
 
     def remove_current(self):
         """Remove a current non-daemon thread."""
```

But it also causes the new test to fail.

**Comment by jaraco** [comment]
Is it the case that you can't from within a thread remove the last known reference to that thread?

**Comment by jaraco** [comment]
This latest commit addresses the issue by leaving the dead threads in the list and reaping them when a new connection is created. It's a little sloppy, meaning that any number of dead threads could be left lying around, but for an active server will not see a continuous growth. It also means that the test is now sloppy, only testing that at least one of the threads got cleaned up. I can't think of another way to more reliably clean up a thread reference from within the thread, short of having another thread responsible for doing the cleanup and signaling from one thread to the other to perform cleanup each time a connection is closed.

**Comment by pablogsal** [comment]
The `buildbot/AMD64 Fedora Stable LTO PR` and `buildbot/PPC64LE Fedora Stable LTO PR` can be ignored as the failures are related to some gcc problems:

https://bugs.python.org/issue42164

**Comment by jaraco** [comment]
I'm unsure if the buildbots tests passed, so starting them again.

**Comment by jaraco** [comment]
I keep running the buildbots, but by the time they're done running, I've forgotten and gone on to something else. Plus, I can't tell which buildbots are expected to fail and which aren't.

@pablogsal Would you be willing to help determine if this PR is safe to merge?

**Comment by pablogsal** [comment]
> @pablogsal Would you be willing to help determine if this PR is safe to merge?

Absolutely, give me a sec as I schedule a run myself to see the results :)

**Comment by pablogsal** [comment]
There is some problem with the `nntplib` tests that are unrelated to this PR (this test is also failing in the CI). We just need to inspect the Refleaks PR and see that nothing else is failing. If that's the case, this should be safe to merge. Thanks for the patience!

**Comment by pablogsal** [comment]
To speeds things up I run the refleaks in `test_socketserver` manually:

```
venv ❯ ./python -m test test_socketserver -uall -R :
0:00:00 load avg: 2.60 Run tests sequentially
0:00:00 load avg: 2.60 [1/1] test_socketserver
beginning 9 repetitions
123456789
.........

== Tests result: SUCCESS ==

1 test OK.

Total duration: 5.0 sec
Tests result: SUCCESS
```

everything looks good. In the unlikely case we missed anything, you can blame me :)

**Review by pablogsal — APPROVED** [review]

**Comment by vstinner** [comment]
Should the fix be backported to other branches?

**Comment by jaraco** [comment]
Yes. Tagging...

**Pull request merged**
