### PR TITLE
Fix spelling of patching in wave.py

### PR DESCRIPTION
**Pull request by micha2718l**
This PR fixes the spelling of the word patching in the wave module.
`pathing` -> `patching`

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@micha2718l

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by brandtbucher** [comment]
Thanks for your time @micha2718l, and welcome to CPython! :sunglasses:

**Review by brandtbucher — APPROVED** [review]
This looks like a good change to me! I assume that you've seen the bot's message about the CLA?

**Comment by micha2718l** [comment]
> This looks like a good change to me! I assume that you've seen the bot's message about the CLA?

Good to hear!
I did, I followed the steps and filled it out, though the check yourself link still says not signed. I assume it is taking a bit of time to get through the system?

**Comment by brandtbucher** [comment]
Yeah, as I understand it, it's checked by a human at the PSF. Just give it a full business day and the label should change.

The good news is, you only have to do this once. So future contributions should be easier!

**Review by zware — APPROVED** [review]

**Comment by zware** [comment]
Thanks for the patch @micha2718l, the review @brandtbucher, and for bringing it to my attention @ammaraskar!

**Pull request merged**
