### PR TITLE
gh-71936: Fix race condition in multiprocessing.Pool

### PR DESCRIPTION
**Pull request by hattya**
Proxes of shared objects register a Finalizer in BaseProxy._incref(), and it will call BaseProxy._decref() when it is GCed. This may cause a race condition with Pool(maxtasksperchild=None) on Windows.

A connection will be closed and raised TypeError when a GC occurs between _ConnectionBase._check_writable() and _ConnectionBase._send_bytes() in _ConnectionBase.send() in the second or later task.

BaseProxy does not count references well.

* Issue: gh-71936

### CODE REVIEW

**Comment by hattya** [comment]
Steps to reproduce:

```console
> xcopy /I "%ProgramFiles%\Python310\Lib\multiprocessing" multiprocessing
> type a.patch
--- a/multiprocessing/connection.py
+++ b/multiprocessing/connection.py
@@ -282,6 +282,8 @@
             _CloseHandle(self._handle)

         def _send_bytes(self, buf):
+            if (10, 1) in util._finalizer_registry:
+                import gc; gc.collect()
             ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
             try:
                 if err == _winapi.ERROR_IO_PENDING:
> patch -p1 < a.patch
> type a.py
#!/usr/bin/env python
import multiprocessing as mp

def foo(lock, i):
    def func(x):
        # for circular reference
        with lock:
            pass
        if x > 0:
            return func(x - 1)

    func(i)

if __name__ == '__main__':
    m = mp.Manager()
    lock = m.Lock()
    with mp.Pool(2) as pool:
        for _ in pool.starmap(foo, ((lock, i) for i in range(10))):
            pass
> a.py
```

**Comment by basnijholt** [comment]
Like I mentioned here https://github.com/python/cpython/issues/71936#issuecomment-2164009639, this patch resolves the problem I am running into on Python 3.12.3.

@hattya, could you add a news entry like the bot suggests?

**Comment by basnijholt** [comment]
I just ran into this exact problem again in a slightly different context than [my previous comment](https://github.com/python/cpython/pull/98274#issuecomment-2164011023).

@encukou, @gpshead, @vstinner, and @AlexWaygood (most recent reviewers – apologies for direct tag), would any of you be able to take a look at this?

This PR solves the race condition I keep running into. For example, see [this build of the documentation](https://readthedocs.org/projects/pipefunc/builds/25588857/).

**Comment by encukou** [comment]
My review led to a “competing” PR: #124973 
@basnijholt, could you check if that also solves the issue for you?

**Comment by encukou** [comment]
I have merged the PR that builds on this one.
Thank you for the fix, @hattya!

**Comment by basnijholt** [comment]
@encukou, I also replied in https://github.com/python/cpython/issues/71936#issuecomment-2477839579 and it indeed solves my problem!

With this fix hopefully Readthedocs will not randomly fail now 👍

**Pull request closed without merging**
