### PR TITLE
gh-109118: Allow lambdas in annotation scopes in classes

### PR DESCRIPTION
**Pull request by JelleZijlstra**
* Issue: gh-109118

----
📚 Documentation preview 📚: https://cpython-previews--118019.org.readthedocs.build/

### CODE REVIEW

**Review by carljm — APPROVED** [review]
Looks fine! I do think this will probably be the most intuitive behavior, though it's a little weird in principle for visibility to not be transitive. I guess it didn't turn out to be the case at all that this non-transitivity would require re-working abstractions in `symtable.c`!

I apologize in advance for the difficulties I assume you will encounter in making this work for comprehensions :/

**Comment by JelleZijlstra** [comment]
Thanks! Yes, I tried locally to do the same thing for comprehensions and couldn't get it to work yet. The naive change (just remove the code that throws a SyntaxError for comprehensions in annotation scopes) no longer crashes like it did in #109118, but due to inlining it doesn't produce the right scoping semantics. I tried to do something like what we did last year in #104528 but couldn't get it to work yet. I haven't had time yet to get back to this.

**Comment by JelleZijlstra** [comment]
One approach I thought of was to simply not inline comprehensions in annotation scopes, but that doesn't seem right as comprehensions would now behave differently in annotation scopes versus elsewhere.

**Comment by carljm** [comment]
If you want to (at some point when you get back to it, no rush) push a non-working version with inlined comprehensions in annotation scopes, I'm also willing to take a look and see what I can figure out.

**Comment by JelleZijlstra** [comment]
Thanks! I opened #118160 with what I have so far.

**Pull request merged**
