### PR TITLE
[3.10] bpo-46978: Correct docstrings for in-place builtin operators (#31802)

### PR DESCRIPTION
**Pull request by arhadthedev**
(cherry picked from commit 128379b8cdb88a6d3d7fed24df082c9a654b3fb8)

### CODE REVIEW

**Comment by abalkin** [comment]
@arhadthedev - are you sure this massive pull request is what you wanted me to review?

**Comment by arhadthedev** [comment]
@abalkin Thank you, retargeted to the 3.10 branch.

**Comment by arhadthedev** [comment]
Reopening to retrigger failed Netlify deployment and other stuck checks.

**Comment by arhadthedev** [comment]
Something stange is happening with this PR. Where did the CLA bot take this e-mail from? It's from 374b0a2aceb378da6a3df9beffe35acd0c11c06d and has no relation to this backport branch.

Since the branch retargeting breaks bots, I'll redo it in a new PR.

**Comment by arhadthedev** [comment]
The cla-bot no longer picks a wrong e-mail from a wrong commit. I retriggered the bot to check it for https://github.com/edgedb/cla-bot/issues/54.

However, the 3.10 no longer accepts bugfixes so closing this PR back.

**Pull request closed without merging**
