### PR TITLE
CI: Bump GitHub Actions

### PR DESCRIPTION
**Pull request by hugovk**
These are all `actions/checkout@v3` -> `actions/checkout@v4` ~except one `actions/add-to-project@v0.1.0` -> `actions/add-to-project@v0.5.0` whilst we're at it~.

To workaround https://github.com/actions/checkout/issues/1448.

### CODE REVIEW

**Comment by sobolevn** [comment]
CC @Zac-HD for hypothesis failures: https://github.com/python/cpython/actions/runs/6074529494/job/16478809374?pr=108879

**Review by sobolevn — APPROVED** [review]
We have the same problem in mypy.

**Comment by Zac-HD** [comment]
This is a new health check which warns if the same function object (ie method decorated before being bound) is called with multiple distinct values of `self`, usually because of inheritance.

We added this check because that can lead to database collisions and in some very rare cases spurious failures, but for CPython and Mypy I'd probably just globally disable the check.

**Comment by hugovk** [comment]
@Zac-HD Please could you open a PR to disable it? Thank you!

**Pull request merged**
