### PR TITLE
gh-91265: Make old ctypes.macholib tests runned by `python -m test`

### LINKED ISSUE #91265: Old ctypes.macholib tests are ignored by python -m test
BPO | [47109](https://bugs.python.org/issue47109)
--- | :---
Nosy | @arhadthedev
PRs | <li>python/cpython#32094</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-24.10:44:34.631>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.11', '3.7', 'tests']
title = 'Old ctypes.macholib tests are ignored by python -m test'
updated_at = <Date 2022-03-24.10:44:47.148>
user = 'https://github.com/arhadthedev'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-24.10:44:47.148>
actor = 'arhadthedev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2022-03-24.10:44:34.631>
creator = 'arhadthedev'
dependencies = []
files = []
hgrepos = []
issue_num = 47109
keywords = ['patch']
message_count = 1.0
messages = ['415935']
nosy_count = 1.0
nosy_names = ['arhadthedev']
pr_nums = ['32094']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue47109'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by arhadthedev**
Some tests for `ctypes.macholib.dyld` and all tests for `ctypes.macholib.dylib` and `ctypes.macholib.framework` are located outside of expected `ctypes.test` module and were not ported from `assert` to `unittest` facilities. This causes the following problems:

- the tests aren't run by `python -m test` so they are effectively dead
- an end user can run them by `python -m ctypes.macholib.dyld`, `python -m ctypes.macholib.dylib`, and `python -m ctypes.macholib.framework`
- they are available even if a user chose to install CPython without tests

This PR moves these tests into `ctypes.test.test_macholib` suit and wraps them as `unittest.TestCase`. 

I believe this PR should be backported to not export unintended features in unintended places.

Fixes GH-91265.

### CODE REVIEW

**Comment by MaxwellDupre** [comment]
After rebuild against this PR: tests:
cpython on  pr/32094 via 🐍 v3.11.0a6+ 
✦ ❯ ./python -m unittest -vvv Lib/ctypes/test/test_macholib.py
Ran 3 tests in 0.000s
OK (skipped=3)

Or
./python -m test -vvv test_macholib
0:00:00 load avg: 1.07 Run tests sequentially
0:00:00 load avg: 1.07 [1/1] test_macholib
test test_macholib crashed -- Traceback (most recent call last):
  File "/home/me/Documents/cpython/Lib/test/libregrtest/runtest.py", line 352, in _runtest_inner
    refleak = _runtest_inner2(ns, test_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/Documents/cpython/Lib/test/libregrtest/runtest.py", line 292, in _runtest_inner2
    the_module = importlib.import_module(abstest)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/Documents/cpython/Lib/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test.test_macholib'

**Comment by arhadthedev** [comment]
Ping.

This PR doesn't add extra logic, it just collects stuff into `Lib/ctypes/test/test_macholib.py` and replaces `assert` with `self.assertEqual`/`self.assertIsNone`.

**Review by ronaldoussoren — APPROVED** [review]
I finally had some time to seriously look at this. The PR looks good to me, as the description says this moves some tests to explicit test files to ensure they are picked up by the regular test runs.

**Comment by ronaldoussoren** [comment]
@arhadthedev : Sorry about the delay in reviewing, I had to find some time to seriously look at this and be sure that tests are correctly moved.

Did you sign the CLA?  The CLA check is blocking the merge of your PR.

**Comment by arhadthedev** [comment]
> Sorry about the delay in reviewing

No worries! The issue needed the chance to collect feedback anyway.

> Did you sign the CLA? The CLA check is blocking the merge of your PR.

Yes, both on the bpo (https://bugs.python.org/user40922) and after the migration (https://github.com/python/cpython/pull/91453#issuecomment-1095487875, I'm one of authors there). So it's just a matter of waiting for the bot to be sorted out.

---

P. S.: @ronaldoussoren (because I know that the "Mentioned" queue is an order of magnitude less that the "Participating" one).

**Comment by arhadthedev** [comment]
@ronaldoussoren I've reopened the PR to retrigger the bot; it worked.

**Pull request merged**
