### PR TITLE
bpo-46214: remove unused opcode ROT_FOUR

### PR DESCRIPTION
**Pull request by iritkatriel**
https://bugs.python.org/issue46214

### CODE REVIEW

**Comment by iritkatriel** [comment]
I repeated this measurement twice (not old and new) because I didn't believe it the first time, but it came out the same. I don't know how removing an unused opcode makes us 2% slower.

```
+------------------------+----------+-----------------------+
| Benchmark              | baseline | rot_four              |
+========================+==========+=======================+
| 2to3                   | 297 ms   | 303 ms: 1.02x slower  |
+------------------------+----------+-----------------------+
| chaos                  | 81.8 ms  | 83.6 ms: 1.02x slower |
+------------------------+----------+-----------------------+
| crypto_pyaes           | 95.2 ms  | 96.9 ms: 1.02x slower |
+------------------------+----------+-----------------------+
| django_template        | 43.4 ms  | 44.7 ms: 1.03x slower |
+------------------------+----------+-----------------------+
| dulwich_log            | 93.2 ms  | 95.8 ms: 1.03x slower |
+------------------------+----------+-----------------------+
| fannkuch               | 424 ms   | 428 ms: 1.01x slower  |
+------------------------+----------+-----------------------+
| float                  | 85.3 ms  | 86.9 ms: 1.02x slower |
+------------------------+----------+-----------------------+
| go                     | 162 ms   | 167 ms: 1.03x slower  |
+------------------------+----------+-----------------------+
| hexiom                 | 7.47 ms  | 7.53 ms: 1.01x slower |
+------------------------+----------+-----------------------+
| json_dumps             | 14.0 ms  | 13.9 ms: 1.01x faster |
+------------------------+----------+-----------------------+
| json_loads             | 27.4 us  | 27.9 us: 1.02x slower |
+------------------------+----------+-----------------------+
| logging_format         | 7.82 us  | 8.24 us: 1.05x slower |
+------------------------+----------+-----------------------+
| logging_silent         | 135 ns   | 138 ns: 1.02x slower  |
+------------------------+----------+-----------------------+
| logging_simple         | 7.09 us  | 7.39 us: 1.04x slower |
+------------------------+----------+-----------------------+
| mako                   | 13.3 ms  | 13.6 ms: 1.02x slower |
+------------------------+----------+-----------------------+
| meteor_contest         | 106 ms   | 105 ms: 1.01x faster  |
+------------------------+----------+-----------------------+
| nbody                  | 104 ms   | 108 ms: 1.04x slower  |
+------------------------+----------+-----------------------+
| nqueens                | 98.7 ms  | 99.4 ms: 1.01x slower |
+------------------------+----------+-----------------------+
| pathlib                | 49.4 ms  | 50.3 ms: 1.02x slower |
+------------------------+----------+-----------------------+
| pickle                 | 11.2 us  | 11.5 us: 1.02x slower |
+------------------------+----------+-----------------------+
| pickle_pure_python     | 389 us   | 403 us: 1.04x slower  |
+------------------------+----------+-----------------------+
| pyflate                | 520 ms   | 534 ms: 1.03x slower  |
+------------------------+----------+-----------------------+
| python_startup         | 20.3 ms  | 20.9 ms: 1.03x slower |
+------------------------+----------+-----------------------+
| python_startup_no_site | 10.2 ms  | 10.5 ms: 1.03x slower |
+------------------------+----------+-----------------------+
| regex_compile          | 155 ms   | 158 ms: 1.02x slower  |
+------------------------+----------+-----------------------+
| regex_dna              | 177 ms   | 189 ms: 1.07x slower  |
+------------------------+----------+-----------------------+
| regex_v8               | 24.7 ms  | 24.9 ms: 1.01x slower |
+------------------------+----------+-----------------------+
| scimark_fft            | 390 ms   | 398 ms: 1.02x slower  |
+------------------------+----------+-----------------------+
| scimark_monte_carlo    | 73.9 ms  | 74.8 ms: 1.01x slower |
+------------------------+----------+-----------------------+
| scimark_sor            | 142 ms   | 144 ms: 1.01x slower  |
+------------------------+----------+-----------------------+
| spectral_norm          | 138 ms   | 135 ms: 1.02x faster  |
+------------------------+----------+-----------------------+
| sqlalchemy_declarative | 148 ms   | 154 ms: 1.04x slower  |
+------------------------+----------+-----------------------+
| sqlalchemy_imperative  | 22.8 ms  | 23.5 ms: 1.03x slower |
+------------------------+----------+-----------------------+
| sympy_expand           | 577 ms   | 581 ms: 1.01x slower  |
+------------------------+----------+-----------------------+
| sympy_integrate        | 23.0 ms  | 23.3 ms: 1.01x slower |
+------------------------+----------+-----------------------+
| sympy_sum              | 194 ms   | 198 ms: 1.02x slower  |
+------------------------+----------+-----------------------+
| sympy_str              | 345 ms   | 350 ms: 1.01x slower  |
+------------------------+----------+-----------------------+
| telco                  | 6.84 ms  | 7.09 ms: 1.04x slower |
+------------------------+----------+-----------------------+
| tornado_http           | 153 ms   | 155 ms: 1.01x slower  |
+------------------------+----------+-----------------------+
| unpack_sequence        | 52.5 ns  | 55.8 ns: 1.06x slower |
+------------------------+----------+-----------------------+
| unpickle               | 15.9 us  | 16.3 us: 1.02x slower |
+------------------------+----------+-----------------------+
| unpickle_list          | 4.81 us  | 4.87 us: 1.01x slower |
+------------------------+----------+-----------------------+
| xml_etree_parse        | 168 ms   | 172 ms: 1.03x slower  |
+------------------------+----------+-----------------------+
| xml_etree_iterparse    | 115 ms   | 118 ms: 1.02x slower  |
+------------------------+----------+-----------------------+
| xml_etree_generate     | 95.8 ms  | 98.2 ms: 1.02x slower |
+------------------------+----------+-----------------------+
| xml_etree_process      | 67.9 ms  | 69.8 ms: 1.03x slower |
+------------------------+----------+-----------------------+
| Geometric mean         | (ref)    | 1.02x slower          |
+------------------------+----------+-----------------------+
```

**Comment by gvanrossum** [comment]
It's a familiar story. I recall ~20 years ago removing an unused fprintf() call having a similar effect.

It's likely due to the idiosyncrasies of code layout and the I-cache -- two common blocks of code that used to hash to different cache lines now hash to the same cache line, or something like that.

I wouldn't worry about it -- the next tiny change to the code may move things around again.

This phenomenon is one of the reasons why Mark likes to talk about code layout randomizers. (Did you watch the Emery Berger talk on YouTube?) Alas, it seems there's no working one that we could just adopt, and writing one is a bit tricky. (Though @brandtbucher has a randomizer for just the cases in the big switch here, maybe you could try that.)

**Comment by iritkatriel** [comment]
Yes, I watched the Emery Berger talk. It is quite interesting. Makes our benchmarks a little hard to trust.

I guess removing dead code is never controversial.

**Comment by iritkatriel** [comment]
> Yes, I watched the Emery Berger talk. It is quite interesting. Makes our benchmarks a little hard to trust.

To clarify- IIUC Emery is not describing a methodology for optimising code through randomisation, but only a methodology to compare performance of two programs by comparing the distributions of their perf numbers through randomising something that we believe impacts it.

In our case we would need to take some (day 10) random permutations of the switch statement, get 10 perf numbers for main and 10 for this branch and compare the sets of 10.  Then we will know whether the expected perf of this branch is better than main.

But unless I’m missing something, there is no point finding the ‘optimal’ permutation, because it’s only optimal for this compiler on this system.

**Comment by gvanrossum** [comment]
Yeah, I meant to use the randomization to feel less bad about the perf results for this diff.

In theory there would be a way to use this to get an "optimal" build, if we could afford to do this for each build (or for each production build). You could take N random (or not so random) permutations, compare them, and use the best one, doing all of that at "build" time. But it sounds like there would be easier ways...

**Review by ericsnowcurrently — APPROVED** [review]
The change itself LGTM.

(I'm assuming the question of utility will answered.)

**Comment by iritkatriel** [comment]
Marking as do-not-merge for now. We have an interesting discussion on https://github.com/faster-cpython/ideas/issues/200  (TLDR - ROT_FOUR is generated implicitly from ROT_N(4) in pattern matching code, and it is twice as fast).

**Pull request closed without merging**
