### PR TITLE
Supress errors from repr/str in specialization stats

### PR DESCRIPTION
**Pull request by Fidget-Spinner**

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
@markshannon while working on function specialization, I started getting segfaults for un-repr-able things. This was caused by PyObject_Repr/Str expecting no exception to be set with ``assert(!_PyErr_Occurred(tstate));``. This PR fixes that.

I assume we can skip issue and news, because this is a purely internal change for our own use?

**Comment by markshannon** [comment]
`name` and `kind` should always be strings, and thus shouldn't raise an exception.
Maybe add an assert that they are strings in the function specialization branch?

**Comment by Fidget-Spinner** [comment]
Sorry I wasn't clear in my original comment.

Yes this only happens when I'm passing the callable object directly as the `name`. I didn't want to write special code just for them and the existing print_stats is generic enough.

**Comment by Fidget-Spinner** [comment]
We don't need this anymore since we no longer print the type.

**Pull request closed without merging**
