### PR TITLE
bpo-34160: Preserve user specified order of Element attributes in html.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue34160

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
This change deserves a NEWS entry, no?

**Comment by serhiy-storchaka** [comment]
This is just a follow up of #10163. It doesn't need  additional documenting.

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
> This is just a follow up of #10163. It doesn't need additional documenting.

I checked, ok, I agree.

**Pull request merged**
