### PR TITLE
gh-100372: Use BIO_eof to detect EOF for SSL_FILETYPE_ASN1

### PR DESCRIPTION
**Pull request by davidben**
In PEM, we need to parse until error and then suppress `PEM_R_NO_START_LINE`, because PEM allows arbitrary leading and trailing data. DER, however, does not. Parsing until error and suppressing `ASN1_R_HEADER_TOO_LONG` doesn't quite work because that error also covers some cases that should be rejected.

Instead, check `BIO_eof` early and stop the loop that way.

* Issue: gh-100372

Automerge-Triggered-By: GH:Yhg1s

### CODE REVIEW

**Comment by davidben** [comment]
@tiran This PR look reasonable? Anything missing on my end?

**Review by Yhg1s — APPROVED** [review]

**Comment by davidben** [comment]
> Do you disagree, @davidben, or is there a security angle I'm missing?

Nah, can't think of any security angle. Just generally improving behavior and reducing dependency on OpenSSL error codes. (Conditioning on OpenSSL error codes can be a bit messy. Sometimes you have to, like the PEM case here, but other times the error codes don't correspond enough to clear, stable conditions to condition on. :-( )

**Comment by h-vetinari** [comment]
> I'm not sure if this should be backported to 3.11/3.10 either. It's a bug, but it doesn't feel important enough to backport and risk breaking users who rely on the old broken behaviour.

FWIW, the fact that this was _not_ backported is now affecting 3.10/3.11 versions together with the newest set of openssl versions (e.g. 3.6.3, 3.5.7): https://github.com/conda-forge/openssl-feedstock/issues/237

The patch backports cleanly to 3.10 & 3.11 (and fixes the regression), which is what I'm looking towards doing as a fix for this in conda-forge.

**Comment by encukou** [comment]
It now fails on macOS on GitHub Actions; I made backports to run the CI.

It's up to the RMs. Not a security issue; it can make an OpenSSL upgrade break working code.
The alternative is of course to skip (or ignore) the relevant tests.

**Comment by nerijus** [comment]
Should be backported to 3.9 too, as it fails on CentOS 9 after openssl update.

**Comment by vstinner** [comment]
> Should be backported to 3.9 too, as it fails on CentOS 9 after openssl update.

Sadly, Python 3.9 no longer get bugfixes nor security fixes:
https://devguide.python.org/versions/#supported-versions

**Pull request merged**
