### PR TITLE
Trivial Change: Remove unhelpful doc in `datetime.timedelta`

### PR DESCRIPTION
**Pull request by meawoppl**
I use timedelta's often in my work, and it always makes me a little sad to see this when I mouse over to look at the docstring.

### CODE REVIEW

**Review by abalkin — APPROVED** [review]
LGTM

**Comment by abalkin** [comment]
@meawoppl - Thank you for your contribution! I don't think small changes like this should require a signed CLA, but it is probably easier to sign it with two clicks than to figure out how to make an exception.

Please follow the instructions above at https://github.com/python/cpython/pull/100164#issuecomment-1345436649.

**Comment by pganssle** [comment]
> I use timedelta's often in my work, and it always makes me a little sad to see this when I mouse over to look at the docstring.

I don't really understand why you are seeing this at all. The docstring for `timedelta` should be coming from `_datetimemodule.c`, and it's this:

```
Difference between two datetime values.

timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)

All arguments are optional and default to 0.
Arguments may be integers or floats, and may be positive or negative.
```

I am not super attached to the "Why? Because I felt like it" wording, but it is also kind of useful information to know that this was an arbitrary choice and not one that was the result of a great amount of deliberation. It's a guard against a future where changes to the structure of `timedelta` are held up by [Chesterton's Fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton's_fence). If we can find an appropriate place to put a comment of this sort, that would be best.

**Comment by meawoppl** [comment]
@pganssle I noticed it because some of the VSCode hover-for-help features show it as part of the docstring. Not sure why it isn't being masked....

The signature process produces a 500 error:
image
...but seems to have worked anyway?

**Comment by meawoppl** [comment]
@abalkin I signed the agreement. Also, I suspect this is below the "news entry" level of diff, but happy to update if not.

**Comment by abalkin** [comment]
>  it is also kind of useful information to know that this was an arbitrary choice and not one that was the result of a great amount of deliberation. 

I will leave it to @pganssle to make a final call on this.  Even though git attributes the authorship to me, I suspect that it was @tim-one who wrote that docstring.  We   can compromise on moving the "unhelpful" comment to a `#` comment below the docstring.

**Comment by meawoppl** [comment]
Happy to change it up that way, just let me know if that is what is desired.

**Review by CuriousLearner — APPROVED** [review]
LGTM!

I agree with @abalkin that the comment on rationale of having that representation can be moved to a separate comment below docstring, and maybe we can also improve it saying the original author found that representation useful/helpful.

**Comment by pganssle** [comment]
I've gone ahead and added a comment below the docstring and pushed directly to @meawoppl 's branch.  I also did a rebase against `main`.

I think we can go ahead and merge this, but I'll give it 24 hours for @meawoppl and/or @abalkin to weigh in on the new wording if desired.

**Review by CuriousLearner — APPROVED** [review]
LGTM!

**Pull request merged**
