### PR TITLE
Add myself as a codeowner for Windows-specific files

### PR DESCRIPTION
**Pull request by zooba**

### CODE REVIEW

**Comment by zooba** [comment]
@zware @tjguk @pfmoore Feel free to also add yourselves to any of these categories (or if you let me know on this PR soon enough I can add you)

**Comment by zware** [comment]
How about a Windows team?

**Comment by zooba** [comment]
No strong opinion - do we just ping @brettcannon for one of those?

**Comment by brettcannon** [comment]
@zooba yep, you can just ask me. Tell me who should be on it initially and I will create a `python/windows-team` (which all team members can then manage on their own going forward).

**Comment by tjguk** [comment]
Just chipping in for long enough to say: please do include me in any 
Windows team, in the hope that I'll actually find enough time to do 
something useful any time soon!

**Comment by zooba** [comment]
@brettcannon Start with the @'s I put above - that's our current set of listed experts.

**Comment by brettcannon** [comment]
@zooba Done! https://github.com/orgs/python/teams/windows-team/members. Now you can update your PR to reference @python/windows-team instead of yourself.

**Comment by zooba** [comment]
Done. Briefly considered not signing you all up for installer change notifications, but then did it anyway. Enjoy :)

**Pull request merged**
