### PR TITLE
GH-69564: Clarify use of octal format of mode argument in help(os.chmod)

### PR DESCRIPTION
**Pull request by amaajemyfren**
https://bugs.python.org/issue25377

* Issue: gh-69564

### CODE REVIEW

**Review by remilapeyre — CHANGES_REQUESTED** [review]
Should `os.rst` be updated too? Also, I think the docstring of `os.fchmod()` should be updated as well.

**Comment by amaajemyfren** [comment]
Hi @remilapeyre,

apologies for responding after a long time.

> Should `os.rst` be updated too? 

Currently the main documentation does not have the ambiguity that exists in help('os.chmod'):

image

It avoids this in part by not getting into the details of what the values of mode are; by abstracting away some of that complexity in the stat module.

I feel that changing it could be changing documentation that has little issues to make it align with the help blurb?

> Also, I think the docstring of `os.fchmod()` should be updated as well.

On my system it currently (3.8.3) says: 

image

Would you like to be added explicit descriptions for `fd` and `mode`?

**Comment by amaajemyfren** [comment]
Hi, @remilapeyre,
I have changed `help(os.fchmod)` but not `os.rst`.

I need to know if this is still considered a documentation change that does not need a NEWS entry or whether I should generate one please.

**Comment by remilapeyre** [comment]
Thanks for making the changes @amaajemyfren ! Can you please fix the conflicts with the `master` branch?

**Review by rhettinger — APPROVED** [review]

**Comment by merwok** [comment]
@amaajemyfren sorry this PR fell out of people’s radar — could you merge the main branch and regenerate the file?

**Review by kumaraditya303 — APPROVED** [review]

**Pull request merged**
