### PR TITLE
bpo-40967: Remove deprecated asyncio.Task.current_task() and asyncio.Task.all_tasks()

### PR DESCRIPTION
**Pull request by remilapeyre**
https://bugs.python.org/issue40967

Automerge-Triggered-By: @aeros

### CODE REVIEW

**Comment by remilapeyre** [comment]
@aeros apparently we can go ahead with this according to the discussion on bpo. Let me know if this needs some changes.

**Comment by aeros** [comment]
Yep! I should have some time to take a look tomorrow. Thanks for the PR.

**Review by aeros — CHANGES_REQUESTED** [review]
The following DeprecationWarning should also be removed:

https://github.com/python/cpython/blob/0968bb6b1d9ee6fe1033a0936df59d8d1118a08d/Lib/test/test_asyncio/test_tasks.py#L3002-L3003

Also, the "What's New" 3.9 document should be updated, specifically the removals should be mentioned in the [dedicated section](https://docs.python.org/3.9/whatsnew/3.9.html#removed), with a link to the `asyncio.current_task()` and `asyncio.all_tasks()` functions that can be used instead.

Other than that, it mostly looks good. I'll double check later to make sure the PR covers everything.

**Comment by ambv** [comment]
I don't mean to scare you, especially given my late response on the issue, but this is blocking the release of 3.9.0b4. Please prioritize this :-)

**Comment by remilapeyre** [comment]
Sorry, I will address the review in the next couple of hours

**Comment by remilapeyre** [comment]
It should be good now, I fixed the C module that I had completely missed for some reason, updated the tests and added a note in What's New. Let me know if it needs anything else.

**Comment by remilapeyre** [comment]
I have made the requested changes; please review again

**Review by aeros — APPROVED** [review]
Thanks for also taking care of removing the deprecated C-API part as well, I just recalled that we also needed to remove that earlier today. With the latest round of changes, it looks good to me.

I'll proceed with merging now since this is a release blocker for 3.9b4, but would greatly appreciate a post-commit review from @1st1 or @asvetlov to make sure we didn't miss anything.

**Pull request merged**
