### PR TITLE
gh-92547: Remove deprecated sqlite3 features

### LINKED ISSUE #92547: sqlite3: remove features deprecated in 3.10
The following sqlite3 features were deprecated in Python 3.10, and are scheduled for removal in Python 3.12:

- sqlite3.OptimizedUnicode: #23163
- sqlite3.enable_shared_cache: #24008

3.12 development was just opened, so these features can now be removed.

### Linked PRs
* gh-101873

### PR DESCRIPTION
**Pull request by erlend-aasland**
The following sqlite3 features were deprecated in 3.10, scheduled for
removal in 3.12:

- sqlite3.OptimizedUnicode (gh-23163)
- sqlite3.enable_shared_cache (gh-24008)

Signed-off-by: Erlend E. Aasland <erlend.aasland@protonmail.com

Closes #92547

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
Code looks good, but let's hold off on merging until the nltk usage of OptimizedUnicode is fixed.

**Comment by erlend-aasland** [comment]
> Code looks good, but let's hold off on merging until the nltk usage of OptimizedUnicode is fixed.

FTR, nltk/nltk#3000 was just merged.

**Comment by JelleZijlstra** [comment]
Feel free to merge!

**Comment by erlend-aasland** [comment]
Thanks for helping, Jelle and Victor!

**Comment by vstinner** [comment]
Removed code contained instructions to port existing code to avoid the deprecation warning: replace OptimizedUnicode with str and use URI with cache=shared: https://github.com/python/cpython/commit/00f22e8cc234aa52ec1f28094a170d7b87d0d08f

Would you mind to copy these information in What's New in Python 3.12?

**Comment by erlend-aasland** [comment]
> Removed code contained instructions to port existing code to avoid the deprecation warning: replace OptimizedUnicode with str and use URI with cache=shared: [00f22e8](https://github.com/python/cpython/commit/00f22e8cc234aa52ec1f28094a170d7b87d0d08f)
> 
> Would you mind to copy these information in What's New in Python 3.12?

Yes, I'll amend What's New. Thanks for the heads-up!

**Comment by erlend-aasland** [comment]
> Would you mind to copy these information in What's New in Python 3.12?

Something like this? #93872

**Pull request merged**
