### PR TITLE
gh-108767: Replace ctype.h functions with pyctype.h functions

### PR DESCRIPTION
**Pull request by vstinner**
Replace <ctype.h> locale dependent functions with Python "pyctype.h" locale independent functions:

* Replace isalpha() with Py_ISALPHA().
* Replace isdigit() with Py_ISDIGIT().
* Replace isxdigit() with Py_ISXDIGIT().
* Replace tolower() with Py_TOLOWER().

Leave Modules/_sre/sre.c unchanged, it uses locale dependent functions on purpose.

* Issue: gh-108767

### CODE REVIEW

**Comment by vstinner** [comment]
> Replace isdigit() with Py_ISDIGIT().
> Replace isxdigit() with Py_ISXDIGIT().

On Linux, they don't seem to be locale dependent:

```
$ man isalpha
(...)

       isdigit()
              checks for a digit (0 through 9).

(...)

       isxdigit()
              checks for hexadecimal digits, that is, one of
              0 1 2 3 4 5 6 7 8 9 a b c d e f A B C D E F.
```

But I prefer to avoid <ctype.h> functions anyway, just in case.

**Comment by vstinner** [comment]
cc @serhiy-storchaka

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by vstinner** [comment]
Merged. Thanks for the review @serhiy-storchaka.

I'm not sure that there is currently a bug being solved here, so in case of doubt, **I prefer to not backport the change**. This change is more to help me reducing the number of standard header files included by ``<Python.h>``.

**Comment by serhiy-storchaka** [comment]
I have been thinking about making these changes for a long time, but there were always more urgent matters. So thank you for doing this.

There was a possible pitfall if the argument is EOF or larger than 255. But I checked and found no such cases.

**Comment by serhiy-storchaka** [comment]
It also fixes #86842.

**Pull request merged**
