### PR TITLE
GH-90699: fix ref counting of static immortal strings

### PR DESCRIPTION
**Pull request by kumaraditya303**
Without this they can cause negative refcount in `_Py_RefTotal`.

* Issue: gh-90699

### CODE REVIEW

**Comment by kumaraditya303** [comment]
> Thanks for the work, Would you like to provide a reproducible way for detecting leaks?

The following script causes negative ref count:
```py
for i in range(1000):
    a = repr(False)
```

Output:
```console
@kumaraditya303 ➜ /workspaces/cpython (main ✗) $ ./python -X showrefcount main.py 
[-1001 refs, 0 blocks]
```

**Review by corona10 — APPROVED** [review]
lgtm

I reproduced the issue with the attached scripts and issues are solved by @kumaraditya303 's patch :)

Thanks for the work!

**Review by corona10 — CHANGES_REQUESTED** [review]
@kumaraditya303 

Sorry Kumar, Looks like leaks exist through this patch.
PTAL

## With patch

`````

beginning 6 repetitions
123456
......
test_io leaked [2, 2, 2] references, sum=6
test_io failed (reference leak) in 3 min 23 sec

== Tests result: FAILURE ==

1 test failed:
    test_io

Total duration: 3 min 23 sec
Tests result: FAILURE
`````

## Without Patch

`````

Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 2.90 Run tests sequentially
0:00:00 load avg: 2.90 [1/1] test_io
beginning 6 repetitions
123456
......
test_io passed in 3 min 23 sec

== Tests result: SUCCESS ==

1 test OK.

Total duration: 3 min 23 sec
Tests result: SUCCESS
`````

**Comment by kumaraditya303** [comment]
Looking, I wonder why only two bots failed if there are refleaks.

**Comment by corona10** [comment]
> Looking, I wonder why only two bots failed if there are refleaks.

It is also leaking at my local environment :(

**Comment by kumaraditya303** [comment]
> It is also leaking at my local environment :(

Yeah, I am also able to reproduce, bisecting which one is causing leak

**Comment by kumaraditya303** [comment]
I am getting refleak on main branch too, `test.test_io.CTextIOWrapperTest.test_reconfigure_locale` is failing.

**Comment by kumaraditya303** [comment]
The refleak will be fixed by https://github.com/python/cpython/pull/94858

**Comment by kumaraditya303** [comment]
Refleak buildbots are failing on main too, see https://github.com/python/cpython/issues/94979

**Review by corona10 — APPROVED** [review]
LGTM 
Thank you, Kumar!

**Comment by kumaraditya303** [comment]
Thanks for the review @corona10!

**Pull request merged**
