### PR TITLE
[3.6] bpo-36983: Fix typing.__all__ and add test for exported names (GH-13456)

### PR DESCRIPTION
**Pull request by asottile**
https://bugs.python.org/issue36983

https://bugs.python.org/issue36983

### CODE REVIEW

**Comment by asottile** [comment]
CC @gvanrossum

**Comment by tirkarthi** [comment]
3.6 is in security fixes only mode : https://devguide.python.org/#status-of-python-branches

**Comment by ZackerySpytz** [comment]
At this point, 3.6 only takes security fixes.

**Comment by asottile** [comment]
@tirkarthi ah ok, I made this PR as the original PR was tagged [backport to 3.6], feel free to close this :+1:

**Comment by gvanrossum** [comment]
Sorry I keep forgetting that.

**Pull request closed without merging**
