### PR TITLE
Add return value type of import functions to docs

### PR DESCRIPTION
**Pull request by worldmind**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@worldmind

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by worldmind** [comment]
Not sure that BPO needed for this changes. CLA signed.

**Comment by brandtbucher** [comment]
Thanks for your time @worldmind, and welcome to CPython! :sunglasses:

**Comment by worldmind** [comment]
Request updated - info about exceptions added.

**Review by brettcannon — CHANGES_REQUESTED** [review]
So there's an issue with this in that the import system in no way guarantees that a `ModuleType` object will be returned by either `__import__()` or `import_module()`. Both functions will return whatever is in `sys.modules` and that can be anything (and code does put various things into `sys.modules` so this isn't hypothetical).

So I think it would be better to change this PR to just be about the raising of `ModuleNotFoundError` if the requested module and/or attribute(s) could not be found and leave out any details of what object will be returned.

**Comment by worldmind** [comment]
@brettcannon thanks for review and suggestions, it is my mistake, I know nothing about so, **not** obvious, behavior.

> return whatever is in sys.modules and that can be anything

Is it documented anywhere? [Documentation](https://docs.python.org/3/library/sys.html#sys.modules) says just about modules. Or module can have other types?

> leave out any details of what object will be returned.

I suppose documentation must have much more details or links to details.
I think it is a goal of documentation, thus, we must write something like: "No guarantee that `ModuleType` object will be returned because ..."

**Comment by brettcannon** [comment]
@worldmind It's going to be covered by the language spec under how import works. But trying to spell everything out for these functions will be never-ending due to how configurable and involved the import system is, so I would rather try to keep the documentation as straight-forward as possible without being wrong and simply not discuss return types here.

**Comment by worldmind** [comment]
@brettcannon IMHO if return value unpredictable it's even more important to describe such behavior, even without details, because if documentation says nothing people will just do: `type(import_module('sys')) is types.ModuleType` and will think that is correct for all cases.
PR updated.

**Comment by brettcannon** [comment]
@worldmind it's fine that you disagree, but I still don't think it's worth documenting. I'll leave it up to another core dev to come and work with you on the PR if they happen to disagree with me.

**Comment by slateny** [comment]
Since there hasn't been any takers just yet, I'll close the PR for the time being but any core devs who'd like to take this up can feel free to reopen.

**Pull request closed without merging**
