### PR TITLE
gh-91102: Use Argument Clinic for str_iterator

### LINKED ISSUE #91102: Port core types to Argument Clinic
BPO | [46946](https://bugs.python.org/issue46946)
--- | :---
Nosy | @arhadthedev
PRs | <li>python/cpython#31725</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-07.14:12:29.924>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'Port core types to Argument Clinic'
updated_at = <Date 2022-03-07.14:13:12.489>
user = 'https://github.com/arhadthedev'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-07.14:13:12.489>
actor = 'arhadthedev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-03-07.14:12:29.924>
creator = 'arhadthedev'
dependencies = []
files = []
hgrepos = []
issue_num = 46946
keywords = ['patch']
message_count = 1.0
messages = ['414670']
nosy_count = 1.0
nosy_names = ['arhadthedev']
pr_nums = ['31725']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46946'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by arhadthedev**
Closes #91102, a followup of #31725.

### CODE REVIEW

**Comment by rhettinger** [comment]
-0

I don't see how this makes us better-off.  We typically use argument clinic on user facing APIs that need a signature object or that have some sort of efficiency gain.  For iterator objects, there is almost no payoff.

**Review by JelleZijlstra — APPROVED** [review]
I support these changes. Using Argument Clinic makes the C code more consistent and readable and allows performance and introspection improvements.

**Comment by rhettinger** [comment]
@JelleZijlstra IMO, it makes tends to make the C code less readable (with the AC codes, having run a tool on every edit, breaking up the natural flow of the C code, and making it more difficult to see where the costs are because the input processing is in a separate file).

Putting all C code into the ArgumentClinic was never a goal.  That seems to be have been a new, contagious, and made up meme.   Significant AC work was done in the first few years.  Almost everything that wasn't done was omitted on purpose because there was no payoff.

**Comment by arhadthedev** [comment]
@rhettinger I agree that carpet conversion of `METH_NOARGS`/`METH_O`s brings little to no complexity benefit.

That's why I limit scope of changes to a very few small class declarations with unusual naming (here `it` vs `self` first method parameter and a private structure with full-fledged typedef).

**Comment by arhadthedev** [comment]
> Significant AC work was done in the first few years. Almost everything that wasn't done was omitted on purpose because there was no payoff.

Thanks for clarification. Initially I've thought that such functions were just missed because of a low priority or would use then-nonexistent AC features.

In this case this PR is the last one in the series.

**Comment by rhettinger** [comment]
Thanks for explaining your thoughts.   FWIW, there is no value in converting the *it* to *self* in the internal code and it is a step backwards from the norms (like we use *so* for setobject instances rather than *self*).   Also, I believe it was decided (and don't remember when or why) to not sweep through and convert all the object structs to the ``.tp_name`` style.  That is mostly being done for new ones.  One further thought is that code churn like this creates it own new problems, making it difficult to backport fixes, and risking small API changes when applying AC (that has happened a few times).

I'm going to mark this one as closed.  Thanks for the PR but I think we're better off without it. No user is going to benefit from this PR, it would just churn code that has been stable for a good while.

Please do keep contributing.  Perhaps aims you time and skills at some of the 5,000 open issues where we know something needs to be fixed :-)

**Pull request closed without merging**
