### PR TITLE
Revert "bpo-33608: Factor out a private, per-interpreter _Py_AddPendingCall(). (gh-13714)"

### PR DESCRIPTION
**Pull request by vstinner**
This reverts commit 6a150bcaeb190d1731b38ab9c7a5d1a352847ddc.

https://bugs.python.org/issue33608

### CODE REVIEW

**Comment by ericsnowcurrently** [comment]
Please wait. :)  I'm going to take a look.

**Comment by vstinner** [comment]
> Please wait. :) I'm going to take a look.

There is a release scheduled for today. Nobody is able to reproduce nor debug the issue. The change was pushed 2 days ago: the buildbot policy says that you have 24h to fix regressions:
https://pythondev.readthedocs.io/ci.html#revert-on-fail

Sorry but we are busy enough with enough other bugs:
https://mail.python.org/pipermail/python-dev/2019-June/157826.html

I don't want to have to investigate this issue. Moreover, this bug is known for months: see https://bugs.python.org/issue33608 history.

The only motivation for the revert is to repair the CI. It doesn't mean that your change is wrong.

Your change doesn't have to be in the master branch to be able to investigate: use "git checkout 6a150bcaeb190d1731b38ab9c7a5d1a352847ddc" to get it.

**Comment by vstinner** [comment]
> I don't want to have to investigate this issue.

Hum, to be clear, I already spent 2 hours today to attempt to investigate this issue, Pablo also investigated the issue:

* https://bugs.python.org/issue37135
* https://bugs.python.org/issue37143

**Review by ericsnowcurrently — APPROVED** [review]
As noted in the tracker, I agree that this should be reverted for the sake of the beta 1 release.

**Comment by ericsnowcurrently** [comment]
Thanks for again spending time trying to figure this out!  The worst thing for me is wasting other people's time.

**Pull request merged**
