### PR TITLE
bpo-46607: Add DeprecationWarning to LegacyInterpolation

### PR DESCRIPTION
**Pull request by hugovk**
`LegacyInterpolation` has been deprecated in docs since its introduction in Python 3.2:

```python
class LegacyInterpolation(Interpolation):
    """Deprecated interpolation used in old versions of ConfigParser.
    Use BasicInterpolation or ExtendedInterpolation instead."""
```

Let's add a `DeprecationWarning` for a couple of releases before removal.

https://bugs.python.org/issue46607

### CODE REVIEW

**Comment by hugovk** [comment]
Moving to draft, let's deal with the [revert](https://bugs.python.org/issue45173#msg411810) OF https://github.com/python/cpython/pull/28292 first, and then this.

**Comment by hugovk** [comment]
Rebased to use new issue number: bpo-46607.

**Comment by hugovk** [comment]
Merge conflict resolved!

**Review by gvanrossum — APPROVED** [review]
Looks good. Let’s do this!

**Review by gpshead — APPROVED** [review]

**Comment by tirkarthi** [comment]
@hugovk  The PR introduces deprecation warnings in tests that need to be handled : 

```
PYTHONWARNINGS=always ./python -Wall -m test test_configparser
0:00:00 load avg: 2.29 Run tests sequentially
0:00:00 load avg: 2.29 [1/1] test_configparser
/home/karthikeyan/stuff/python/cpython/Lib/test/test_configparser.py:1031: DeprecationWarning: LegacyInterpolation has been deprecated since Python 3.2 and will be removed from the configparser module in Python 3.13. Use BasicInterpolation or ExtendedInterpolation instead.
  interpolation = configparser.LegacyInterpolation()

== Tests result: SUCCESS ==

1 test OK.

Total duration: 300 ms
Tests result: SUCCESS
```

**Comment by hugovk** [comment]
@tirkarthi Thanks, will check it!

**Comment by hugovk** [comment]
Please see https://github.com/python/cpython/pull/91480.

**Pull request merged**
