### PR TITLE
gh-123407: Docs: enable translations of code blocks

### LINKED ISSUE #123407: Docs: enable translations of code blocks
# Documentation

Code blocks, e.g. in the tutorial, include comments that are complement to the regular content of tutorial articles. An example in tutorial's introduction in [section “Numbers”](https://docs.python.org/3/tutorial/introduction.html#numbers):
```python
>>> 17 / 3  # classic division returns a float
5.666666666666667
>>>
>>> 17 // 3  # floor division discards the fractional part
5
>>> 17 % 3  # the % operator returns the remainder of the division
2
>>> 5 * 3 + 2  # floored quotient * divisor + remainder
17
```

I'd like to propose changing gettext builder configuration by allowing `'literal-block'` [element types translation](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-gettext_additional_targets).

The topic previously was brought up on [doc-sig mailing list](https://mail.python.org/pipermail/doc-sig/2020-January/004190.html) without a conclusion.

### Linked PRs
* gh-123408
* gh-123530
* gh-123531
* gh-123852

### PR DESCRIPTION
**Pull request by m-aciek**
Closes #123407.

* Issue: gh-123407

----
📚 Documentation preview 📚: https://cpython-previews--123408.org.readthedocs.build/

### CODE REVIEW

**Review by AA-Turner — APPROVED** [review]
Can we confirm that the new text shows up in gettext builds?

A

**Comment by m-aciek** [comment]
Yes, I've run it locally and got code blocks in put in the POT files, e.g.
```gettext
#: ../../tutorial/introduction.rst:76
msgid ">>> 17 / 3  # classic division returns a float\n"
"5.666666666666667\n"
">>>\n"
">>> 17 // 3  # floor division discards the fractional part\n"
"5\n"
">>> 17 % 3  # the % operator returns the remainder of the division\n"
"2\n"
">>> 5 * 3 + 2  # floored quotient * divisor + remainder\n"
"17"
msgstr ""
```
in `introduction.pot`

**Review by Seluj78 — APPROVED** [review]

**Comment by AA-Turner** [comment]
If this turns out to be too annoying for translators, we can revert it later. But it's worth a try!

A

**Comment by m-aciek** [comment]
👍 Thank you!

**Pull request merged**
