### PR TITLE
Mark importlib and clinic headers as generated

### PR DESCRIPTION
**Pull request by methane**
We can specify generated files in `.gitattributes`.
Github doesn't render diff for generated files by default.

[Sample pull request](https://github.com/methane/cpython/pull/13/files)

### CODE REVIEW

**Review by zware — COMMENTED** [review]
Looks good, but there are several other generated files that we could also list here, like the unicodedata files, graminit, python-ast, etc.

**Comment by zware** [comment]
I removed the `needs backport to 2.7` branch; clinic and importlib*.h don't exist in 2.7.

**Review by zware — APPROVED** [review]
LGTM.

**Comment by serhiy-storchaka** [comment]
It doesn't hide diffs completely, but just makes them collapsed by default? Then LGTM!

**Comment by methane** [comment]
> It doesn't hide diffs completely, but just makes them collapsed by default?
>

You are right.  Generated files are collapsed by default. Reviewer can
uncollapse them when they want.
-- 
INADA Naoki  <songofacandy@gmail.com>

**Pull request merged**
