### PR TITLE
bpo-33482: fix codecs.StreamRecoder.writelines

### PR DESCRIPTION
**Pull request by JelleZijlstra**
A very simple fix. I found this while writing typeshed stubs for StreamRecoder.

https://bugs.python.org/issue33482

### CODE REVIEW

**Comment by gvanrossum** [comment]
Probably needs a test.

**Comment by JelleZijlstra** [comment]
Just added a test. (There were no tests at all for StreamRecoder, so I also added a test for the write() method.)

**Comment by JelleZijlstra** [comment]
The CI errors don't look real.

**Comment by csabella** [comment]
@JelleZijlstra, can you fix the merge conflict?  That should re-trigger the CI runs.  Thanks!

**Comment by JelleZijlstra** [comment]
@csabella done, thanks!

**Review by gvanrossum — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
I'll open PRs for 3.7 and 3.6.

**Pull request merged**
