### PR TITLE
bpo-35614: Fix pydoc help() on metaclasses

### PR DESCRIPTION
**Pull request by CuriousLearner**
https://bugs.python.org/issue35614

### CODE REVIEW

**Comment by merwok** [comment]
Would you mind adding tests?

**Comment by serhiy-storchaka** [comment]
Just check that `help(type)` does not fail.

**Comment by CuriousLearner** [comment]
@serhiy-storchaka @merwok Fixed. Can you please have a look now?

**Comment by merwok** [comment]
Can you confirm that `./python -m pydoc abc` with your fix doesn’t error?

**Review by merwok — APPROVED** [review]

**Comment by CuriousLearner** [comment]
@merwok I'm on mac, and for `abc` it shows me the doc.

**Review by ncoghlan — APPROVED** [review]

**Comment by ncoghlan** [comment]
Bleh, GitHub didn't accept my commit message edits, but then went ahead and merged the change anyway :(

**Pull request merged**
