### PR TITLE
use github issue tracker (configure.ac)

### PR DESCRIPTION
**Pull request by ghost**
configure.ac

```
$ cd cpython
$ grep -n https:\/\/bugs configure
5:# Report bugs to <https://bugs.python.org/>.
270:$0: https://bugs.python.org/ about your system, including
585:PACKAGE_BUGREPORT='https://bugs.python.org/'
1969:Report bugs to <https://bugs.python.org/>.
2192:## Report this to https://bugs.python.org/ ##
28836:Report bugs to <https://bugs.python.org/>."
$ sed -i "s#https://bugs.python.org/#https://github.com/python/cpython/issues#g" configure.ac
$ rm configure
$ autoreconf -if
$ grep -n github configure
5:# Report bugs to <https://github.com/python/cpython/issues>.
270:$0: https://github.com/python/cpython/issues about your
585:PACKAGE_BUGREPORT='https://github.com/python/cpython/issues'
1957:Report bugs to <https://github.com/python/cpython/issues>.
2180:## Report this to https://github.com/python/cpython/issues ##
28824:Report bugs to <https://github.com/python/cpython/issues>."
$ 
```

### CODE REVIEW

**Comment by fluesvamp** [comment]
X Tests / Check if generated files are up to date (pull_request) 

Check Autoconf version 2.6.9 and aclocal 1.16.3

Error: process completed with exit code 1.

```
$ aclocal --version | head -n 1
aclocal (GNU automake) 1.16.2
$ 
```

didn't modify aclocal.m4 as the aclocal version older than 1.16.3

if that was the cause of the failure and somebody wants to resubmit this PR here's the sed line

`sed -i "s#https://bugs.python.org/#https://github.com/python/cpython/issues#g" configure.ac`

**Comment by fluesvamp** [comment]
@tiran my presumption is this PR should closed and possibly resubmitted by someone with the specified Autotools versions

**Comment by fluesvamp** [comment]
Closing this PR but will open an Issue.

I now have access to a box with Debian 11 with the specified Autotools versions.

autoconf 2.6.9
aclocal 1.16.3

**Comment by tiran** [comment]
There is a much easier way:
* install podman or docker
* run `./configure` to generate the Makefile
* run `make regen-configure`
* done

**Comment by ptsneves** [comment]
@fluesvamp can you please provide the link to the issue?

**Comment by fluesvamp** [comment]
the Debian 11 box generated aclocal.m4 file reflects that a newer pkg-version is installed

aside from some indentation changes the following lines don't appear in the generated file

so there are 68 less lines
 
```
$ ed -s cpython/aclocal.m4 <<<'554,620p'
dnl PKG_WITH_MODULES(VARIABLE-PREFIX, MODULES,
dnl   [ACTION-IF-FOUND],[ACTION-IF-NOT-FOUND],
dnl   [DESCRIPTION], [DEFAULT])
dnl ------------------------------------------
dnl
dnl Prepare a "--with-" configure option using the lowercase
dnl [VARIABLE-PREFIX] name, merging the behaviour of AC_ARG_WITH and
dnl PKG_CHECK_MODULES in a single macro.
AC_DEFUN([PKG_WITH_MODULES],
[
m4_pushdef([with_arg], m4_tolower([$1]))

m4_pushdef([description],
           [m4_default([$5], [build with ]with_arg[ support])])

m4_pushdef([def_arg], [m4_default([$6], [auto])])
m4_pushdef([def_action_if_found], [AS_TR_SH([with_]with_arg)=yes])
m4_pushdef([def_action_if_not_found], [AS_TR_SH([with_]with_arg)=no])

m4_case(def_arg,
            [yes],[m4_pushdef([with_without], [--without-]with_arg)],
            [m4_pushdef([with_without],[--with-]with_arg)])

AC_ARG_WITH(with_arg,
     AS_HELP_STRING(with_without, description[ @<:@default=]def_arg[@:>@]),,
    [AS_TR_SH([with_]with_arg)=def_arg])

AS_CASE([$AS_TR_SH([with_]with_arg)],
            [yes],[PKG_CHECK_MODULES([$1],[$2],$3,$4)],
            [auto],[PKG_CHECK_MODULES([$1],[$2],
                                        [m4_n([def_action_if_found]) $3],
                                        [m4_n([def_action_if_not_found]) $4])])

m4_popdef([with_arg])
m4_popdef([description])
m4_popdef([def_arg])

])dnl PKG_WITH_MODULES

dnl PKG_HAVE_WITH_MODULES(VARIABLE-PREFIX, MODULES,
dnl   [DESCRIPTION], [DEFAULT])
dnl -----------------------------------------------
dnl
dnl Convenience macro to trigger AM_CONDITIONAL after PKG_WITH_MODULES
dnl check._[VARIABLE-PREFIX] is exported as make variable.
AC_DEFUN([PKG_HAVE_WITH_MODULES],
[
PKG_WITH_MODULES([$1],[$2],,,[$3],[$4])

AM_CONDITIONAL([HAVE_][$1],
               [test "$AS_TR_SH([with_]m4_tolower([$1]))" = "yes"])
])dnl PKG_HAVE_WITH_MODULES

dnl PKG_HAVE_DEFINE_WITH_MODULES(VARIABLE-PREFIX, MODULES,
dnl   [DESCRIPTION], [DEFAULT])
dnl ------------------------------------------------------
dnl
dnl Convenience macro to run AM_CONDITIONAL and AC_DEFINE after
dnl PKG_WITH_MODULES check. HAVE_[VARIABLE-PREFIX] is exported as make
dnl and preprocessor variable.
AC_DEFUN([PKG_HAVE_DEFINE_WITH_MODULES],
[
PKG_HAVE_WITH_MODULES([$1],[$2],[$3],[$4])

AS_IF([test "$AS_TR_SH([with_]m4_tolower([$1]))" = "yes"],
        [AC_DEFINE([HAVE_][$1], 1, [Enable ]m4_tolower([$1])[ support])])
])dnl PKG_HAVE_DEFINE_WITH_MODULES
$ 
```

**Pull request closed without merging**
