### PR TITLE
gh-93839: Move Lib/unttest/test/ to Lib/test/test_unittest/

### PR DESCRIPTION
**Pull request by vstinner**
* Remove Lib/test/test_unittest.py
* Move Lib/unittest/test/ to Lib/test/test_unittest/
* Replace unittest.test with test.test_unittest
* Remove unittest.load_tests()
* Rewrite ``__init__.py`` and ``__main__.py``
* Update build system, CODEOWNERS, wasm_assets.py

### CODE REVIEW

**Comment by vstinner** [comment]
``./python -m test test_unittest -v`` and ``./python -m test test_unittest --list-cases|wc -l`` give 1006 test cases with this change.

I also tested that ``make install`` (on Linux) installs test/test_unittest/ sub-directory as expected. I tested that the installed Python can run ``python -m test test_unittest -v`` .

In all cases, I get a count of: ``1006 tests``.

**Review by cjw296 — APPROVED** [review]
This looks like a straight move, right?
If so, go for it!
More power to you if you fix the whitespace ;-)

**Review by ezio-melotti — APPROVED** [review]

**Comment by vstinner** [comment]
I will update the https://github.com/python/cpython/pull/94041 NEWS entry later to also mention unittest.

**Comment by vstinner** [comment]
Merged, thanks for reviews.

>  More power to you if you fix the whitespace ;-)

Which whitespace issue?

**Comment by tiran** [comment]
Looks like the PR broken WASM buildbots: https://buildbot.python.org/all/#/builders/1046/builds/30

**Comment by tiran** [comment]
There are more problem. This test execution works fine if I undo your commit and clear ``__pycache__`` directories


```
# wasmtime run --mapdir .::../../ -- python.wasm -m test -v test_unittest
== CPython 3.12.0a0 (heads/main-dirty:c735d545343, Jun 21 2022, 09:30:50) [Clang 14.0.4 (https://github.com/llvm/llvm-project 29f1039a7285a5c3a9c353d05414
== wasi-0.0.0-wasm32-32bit little-endian
== cwd: /python-wasm/cpython/builddir/wasi/build/test_python_859108æ
== CPU count: 1
== encodings: locale=UTF-8, FS=utf-8
0:00:00 Run tests sequentially
0:00:00 [1/1] test_unittest
Failed to call load_tests:
Traceback (most recent call last):
  File "/Lib/unittest/loader.py", line 130, in loadTestsFromModule
    return load_tests(self, tests, pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/test/test_unittest/testmock/__init__.py", line 14, in load_tests
    __import__(modname)
    ^^^^^^^^^^^^^^^^^^^
  File "/Lib/test/test_unittest/testmock/testasync.py", line 9, in <module>
    support.requires_working_socket(module=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/test/support/__init__.py", line 543, in requires_working_socket
    raise unittest.SkipTest(msg)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unittest.case.SkipTest: requires socket support

test test_unittest crashed -- Traceback (most recent call last):
  File "/Lib/test/libregrtest/runtest.py", line 360, in _runtest_inner
    refleak = _runtest_inner2(ns, test_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Lib/test/libregrtest/runtest.py", line 317, in _runtest_inner2
    test_runner()
    ^^^^^^^^^^^^^
  File "/Lib/test/libregrtest/runtest.py", line 280, in _test_module
    raise Exception("errors while loading tests")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: errors while loading tests

test_unittest failed (uncaught exception)

== Tests result: FAILURE ==

1 test failed:
    test_unittest

Total duration: 132 ms
Tests result: FAILURE
```

**Pull request merged**
