### PR TITLE
bpo-30262: Don't expose sqlite Cache and Statement 

### PR DESCRIPTION
**Pull request by palaviv**
https://bugs.python.org/issue30262

### CODE REVIEW

**Comment by matrixise** [comment]
Hi @palaviv

Would you be interested to upgrade your PR to the last master?

Thank you

**Review by berkerpeksag — CHANGES_REQUESTED** [review]
@palaviv if you port the NEWS entry to blurb, and add a note to `Doc/whatsnew/3.8.rst`, I can merge this PR. Thank you!

**Comment by palaviv** [comment]
Done @berkerpeksag. I am happy to see that there is a new interest in the sqlite3 module :)

**Comment by palaviv** [comment]
I have made the requested changes; please review again

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
Thank you!

@palaviv your pull requests have been on my TODO list, but unfortunately I've been pretty busy with life lately. Sorry for my late response times!

**Comment by palaviv** [comment]
Thank you @berkerpeksag. I saw you took charge on the sqlite3 module. I am very familiar with the code there and would love to help if needed.

**Pull request merged**
