### PR TITLE
bpo-34170: Fix pymain_run_file()

### PR DESCRIPTION
**Pull request by vstinner**
[bpo-34170](https://www.bugs.python.org/issue34170), [bpo-34326](https://www.bugs.python.org/issue34326): Fix pymain_run_file(): use
PyRun_AnyFileExFlags(closeit=1) instead of calling fclose(fp)
explicitly to close the input file before running the code.

https://bugs.python.org/issue34170

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
Thanks for the review @pablogsal!

**Comment by matrixise** [comment]
:/ I didn't find it but I was thinking about this function.

**Comment by pablogsal** [comment]
@matrixise I am afraid that nothing on earth is faster than @vstinner, not even unladen swallows!

**Comment by vstinner** [comment]
> @matrixise I am afraid that nothing on earth is faster than @vstinner, not even unladen swallows!

African or european?

**Comment by vstinner** [comment]
> @matrixise I am afraid that nothing on earth is faster than @vstinner, not even unladen swallows!

More seriously, I knew that I modifed PyRun_AnyFileExFlags() to change when the file is closed. But the full test passed on Linux. It seems like it only failed on specific platforms. Strange. It might be related to os.urandom() private FD, I don't know.

I also noticed that test_subprocess failed on VSTS: macOS, before I merged my PR (the one which introduced the fix), but I don't trust VSTS since this CI has many random failures.

Note: FYI I wrote this fix in my car. But no, I wasn't driving hopefully ;-) I'm now in holiday, see you back in a few weeks!

**Pull request merged**
