### PR TITLE
Revert "bpo-43693: Add the MAKE_CELL opcode and interleave fast locals offsets. (gh-26396)"

### PR DESCRIPTION
**Pull request by pablogsal**
This reverts commit 631f9938b1604d4f893417ec339b9e0fa9196fb1 as it has broken the ASAN buildbots:

https://buildbot.python.org/all/#/builders/585

https://bugs.python.org/issue43693

### CODE REVIEW

**Comment by pablogsal** [comment]
CC: @ericsnowcurrently @markshannon  I have tried to find the error myself and debug this issue for 30 min, but the patch in 631f9938b1604d4f893417ec339b9e0fa9196fb1 is quite involved and I need to catch up with the rest of changes made to the compiler so I was not able to find it quickly :(

**Comment by pablogsal** [comment]
The problem is that `PyFrame_LocalsToFast(frame, 1);` calls into `PyFrame_LocalsToFast` where `co->co_nlocals` has a value of 3, and this causes `co->co_cell2arg[i - co->co_nlocals];` to access outside the bounds of the array.

**Comment by ericsnowcurrently** [comment]
@pablogsal, sorry to impose again!  I was watching the buildbots after but ran out of time to wait for them all to finish.  Lesson learned.

**Comment by pablogsal** [comment]
> @pablogsal, sorry to impose again!  I was watching the buildbots after but ran out of time to wait for them all to finish.  Lesson learned.

No problem! I will try to improve the experience a bit better if I managed to find the time. Will try to propose some improvements so maybe the failures are reported in a comment or something

**Comment by ericsnowcurrently** [comment]
What's the best way for me to run the address sanitizer locally, to reproduce the failure?

**Comment by pablogsal** [comment]
> What's the best way for me to run the address sanitizer locally, to reproduce the failure?

I mentioned it in https://bugs.python.org/msg395321 but I should have mentioned it here as well:

```
$ export ASAN_OPTIONS=detect_leaks=0:allocator_may_return_null=1:handle_segv=0
$ ./configure --with-address-sanitizer --without-pymalloc
$ make -j -s
$ ./python -m test test_sys_settrace
```

**Comment by pablogsal** [comment]
I used gcc 10 for this, but I think clang works as well as any recent version of gcc.

**Comment by pablogsal** [comment]
giphy (1)

**Pull request merged**
