### PR TITLE
bpo-38706: Capitalise word in assertTrue/assertFalse error message (GH-17049)

### PR DESCRIPTION
**Pull request by mkarots**
https://bugs.python.org/issue38706

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@michael-karotsieris

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by michael-karotsieris** [comment]
@brandtbucher

**Comment by brandtbucher** [comment]
Thanks for your time @michael-karotsieris, and welcome to CPython!

This one definitely needs a bugs.python.org issue and [a NEWS entry](https://blurb-it.herokuapp.com), since it changes test output. I'm not *entirely* convinced that this change is necessary (we're getting the *truthiness*  of `expr`, not checking to see if it literally `is True` or `is False`), but a BPO discussion would be a good place to start.

**Review by brandtbucher — CHANGES_REQUESTED** [review]
This one definitely needs [a BPO issue](https://bugs.python.org) and [a NEWS entry](https://blurb-it.herokuapp.com), since it changes test output.

I'm not *entirely* convinced that this change is necessary (we're getting the *truthiness*  of `expr`, not checking to see if it literally `is True` or `is False`), but a BPO discussion would be a good place to start.

**Comment by michael-karotsieris** [comment]
> This one definitely needs [a BPO issue](https://bugs.python.org) and [a NEWS entry](https://blurb-it.herokuapp.com), since it changes test output.
> 
> I'm not _entirely_ convinced that this change is necessary (we're getting the _truthiness_ of `expr`, not checking to see if it literally `is True` or `is False`), but a BPO discussion would be a good place to start.

Thanks for the fast review, I will make a bpo for it and take it from there.

**Comment by michael-karotsieris** [comment]
Just got the chance to create an issue , thanks for the suggestion!

**Review by brandtbucher — CHANGES_REQUESTED** [review]
Thanks @michael-karotsieris! However, it seems that others agree with me.

Since the BPO issue has been closed as "not a bug", I suggest that this be closed as well.

**Comment by brandtbucher** [comment]
I would love to see more from you in the future, though, now that you have the process down. Look for existing issues on BPO!

**Comment by terryjreedy** [comment]
This version of a change was rejected on the issue.  I agree with that rejection.

**Pull request closed without merging**
