### PR TITLE
bpo-27777 Fix for several reported cgi.py issues

### PR DESCRIPTION
**Pull request by eykamp**
This is primarily a repackaging of the fixes proposed by Bert JW Regeer.

https://bugs.python.org/issue27777

### CODE REVIEW

**Comment by ned-deily** [comment]
@eykamp Looks like the change causes another test case to fail.  See the Travis or VSTS CI details:

```
======================================================================
2018-06-19T19:19:06.7474160Z ERROR: test_parse_multipart_invalid_encoding (test.test_cgi.CgiTests)
2018-06-19T19:19:06.7490910Z ----------------------------------------------------------------------
2018-06-19T19:19:06.7507040Z Traceback (most recent call last):
2018-06-19T19:19:06.7522140Z   File "/Users/vsts/agent/2.134.2/work/1/s/Lib/test/test_cgi.py", line 146, in test_parse_multipart_invalid_encoding
2018-06-19T19:19:06.7537280Z     self.assertEqual(result, expected)
2018-06-19T19:19:06.7552850Z   File "/Users/vsts/agent/2.134.2/work/1/s/Lib/unittest/case.py", line 839, in assertEqual
2018-06-19T19:19:06.7567860Z     assertion_func(first, second, msg=msg)
2018-06-19T19:19:06.7582800Z   File "/Users/vsts/agent/2.134.2/work/1/s/Lib/unittest/case.py", line 1132, in assertDictEqual
2018-06-19T19:19:06.7597610Z     if d1 != d2:
2018-06-19T19:19:06.7612250Z BytesWarning: Comparison between bytes and string
```

**Comment by PierreQuentel** [comment]
I have submitted another PR, #10771, to solve the issue.

**Comment by MoodyMudit** [comment]
Hi, This change seems to fix the bug. When is this change going to be merged and sent out?

**Comment by AlexWaygood** [comment]
@eykamp, thanks for the PR. Unfortunately m the `cgi` module is now deprecated following the acceptance of PEP 594, so bugfixes and improvements for this module will no longer be accepted. I am therefore closing this PR.

I hope that this does not dissuade you from contributing to CPython in the future 🙂

**Pull request closed without merging**
