### PR TITLE
bpo-46015: Fixes calculation of sys.path in a venv on Windows

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue46015

### CODE REVIEW

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Comment by pablogsal** [comment]
Seems that some of the Windows buildbots still fail :(

https://buildbot.python.org/all/#/builders/577/builds/479

**Comment by zooba** [comment]
Yeah, I think I have a repro, but only by manually breaking my build directory. At least it's a step closer!

**Comment by zooba** [comment]
My current guess is that the older version of MSBuild on the buildbot is running two final steps in a different order, which causes the latter one to fail first and abort the necessary one. For some reason it isn't causing the whole build to fail, and so we're left with a build that doesn't have its `pybuilddir.txt` file.

**Comment by zooba** [comment]
Looks like that has done it. I'd assume we'll get more issues post-release, but that's kind of the point of an alpha release.

**Pull request merged**
