### PR TITLE
Remove new line in pickle error message

### PR DESCRIPTION
**Pull request by harshil21**
Removes the new line in the error message. Encountered this while testing something and found it a little weird that there would be a new line character when the error message is short anyway.

### CODE REVIEW

**Comment by harshil21** [comment]
Hi, is this change going to be implemented? If not, I'll just close.

**Review by nanjekyejoannah — APPROVED** [review]

**Review by nanjekyejoannah — COMMENTED** [review]
I doubt we need a news entry for this. Also docs seem to be failing.

**Comment by harshil21** [comment]
I think it's failing because there isn't an issue for this PR. Maybe I should delete the NEWS.d entry then?

**Review by nanjekyejoannah — COMMENTED** [review]
Yes, remove the news entry

**Comment by iritkatriel** [comment]
@serhiy-storchaka - as someone who's been looking at pickle issue recently, do you see any problem with this change? Does it need a news entry?

**Review by serhiy-storchaka — APPROVED** [review]
It is a very old code. It was added in fdde96ce98f3e77dc27cac034bcb8b548b3c0046.

I do not know reasons of adding a newline at the first place, but the change LGTM.

**Pull request merged**
