### PR TITLE
bpo-22087: Fix Policy.get_event_loop() to detect fork

### PR DESCRIPTION
**Pull request by 1st1**
Original patch by Dan O'Reilly.

https://bugs.python.org/issue22087

### CODE REVIEW

**Comment by pitrou** [comment]
I think it would be nice if the test did a bit more, for example run some coroutine or perhaps even some simple socket ping-pong. That would check that other infrastructure is also fork-safe, not just the event loop instantiation logic.

**Comment by 1st1** [comment]
Sure, added a basic test for that. Don't think we need more than that though, as the entirety of "other infrastructure" should be initialized via the loop's constructor.

**Review by pitrou — APPROVED** [review]
LGTM. I'm assuming the test isn't run on Windows?

**Review by asvetlov — APPROVED** [review]
lgtm

**Pull request merged**
