### PR TITLE
bpo-36785: PEP 574 What's New entry

### PR DESCRIPTION
**Pull request by pitrou**
https://bugs.python.org/issue36785

### CODE REVIEW

**Comment by pitrou** [comment]
@ambv @ncoghlan

**Comment by ncoghlan** [comment]
@Mariatta Is @miss-islington OK at the moment? (wondering if I should try removing and re-adding the backport label)

**Comment by Mariatta** [comment]
Retrying fixed it 🤷🏻‍♀️

**Comment by ncoghlan** [comment]
Thanks :)

**Pull request merged**
