### PR TITLE
gh-122237: Fix repl auto indentation wrong with comments

### PR DESCRIPTION
**Pull request by AnsonTrapani**
* Issue: gh-122237

### CODE REVIEW

**Comment by devdanzin** [comment]
There's also a proposed fix in #122238.

**Comment by AnsonTrapani** [comment]
> There's also a proposed fix in #122238.

Hi [devdanzin](https://github.com/devdanzin),

Does that one get the priority then or is this merge request going to be closed without a merge? Sorry, this is my first time contributing here so I'm not sure of the procedure!

Thank you!

**Comment by terryjreedy** [comment]
If two PRs have different solutions, 'priority' is not an issue.  (I have not looked at either.)  A core dev needs to decide which is superior and merge that, possibly after further changes.  Reviewers can test both and give opinions.

**Comment by ambv** [comment]
Fixed in GH-123196.

**Pull request closed without merging**
