### PR TITLE
bpo-30394: smtplib leaves open sockets around if SMTPConnectError is raised in __init__

### PR DESCRIPTION
**Pull request by jhillacre**
Opening PR based on patch file from https://bugs.python.org/issue30394

### CODE REVIEW

**Review by giampaolo — APPROVED** [review]
LGTM

**Review by zhangyangyu — APPROVED** [review]

**Review by bitdancer — CHANGES_REQUESTED** [review]
I made a suggestion for a test on the issue.

**Review by bitdancer — APPROVED** [review]

**Comment by bitdancer** [comment]
Nevermind, my suggestion was wrong-headed :)

**Comment by zhangyangyu** [comment]
Thanks @jhillacre ! Would you like to make backport PRs?

**Comment by matrixise** [comment]
Hi @zhangyangyu I just created some PR for the backports for 2.7, 3.5 and 3.6

**Comment by zhangyangyu** [comment]
Thanks @matrixise , I'll merge them when able to.

**Pull request merged**
