### PR TITLE
bpo-40334: Produce better error messages for non-parenthesized genexps

### PR DESCRIPTION
**Pull request by lysnikolaou**
The error message, generated for non-parenthesized generator expression
in function calls, was still the generic `invalid syntax`, when the
generator expression wasn't appearing as the first argument in the call.
Now, even on inputs like `f(a, b, c for c in d, e)`, the correct error
message gets produced.

PS Last one with this bpo number. Promise!

https://bugs.python.org/issue40334

### CODE REVIEW

**Comment by pablogsal** [comment]
Humm, there are still some mistmatches. For instance:

```
>>> f(x=3,x for x in L,)
  File "<stdin>", line 1
    f(x=3,x for x in L,)
            ^
SyntaxError: positional argument follows keyword argument
```

with the old parser:

```
>>> f(x=3,x for x in L,)
  File "<stdin>", line 1
SyntaxError: Generator expression must be parenthesized
```

**Comment by lysnikolaou** [comment]
> Humm, there are still some mistmatches. For instance:
> 
> ```
> >>> f(x=3,x for x in L,)
>   File "<stdin>", line 1
>     f(x=3,x for x in L,)
>             ^
> SyntaxError: positional argument follows keyword argument
> ```
> 
> with the old parser:
> 
> ```
> >>> f(x=3,x for x in L,)
>   File "<stdin>", line 1
> SyntaxError: Generator expression must be parenthesized
> ```

Fixed in https://github.com/python/cpython/pull/20153/commits/ed6487671ea081799142e4b9abf4f70c502440c4.

**Comment by lysnikolaou** [comment]
@pablogsal Would you be able to give this another review?

**Comment by pablogsal** [comment]
> @pablogsal Would you be able to give this another review?

Absolutely, will try to review this tonight :)

**Comment by lysnikolaou** [comment]
> > @pablogsal Would you be able to give this another review?
> 
> Absolutely, will try to review this tonight :)

No rush, whenever you find the time.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
LGTM

I have been playing with some edge cases and it behaves as expected :tada:

**Comment by lysnikolaou** [comment]
Thanks thanks!

**Pull request merged**
