### PR TITLE
Closes bpo-20216: Correct a misleading docstring

### PR DESCRIPTION
**Pull request by srinivasreddy**
https://bugs.python.org/issue20216

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
You need to regenerate Argument Clinic files.
```
make clinic
```
or
```
python3 Tools/clinic/clinic.py --make -f
```

**Comment by srinivasreddy** [comment]
@serhiy-storchaka  Did i change files which are supposed to be auto generated? Not sure why build is failing.

**Comment by serhiy-storchaka** [comment]
Build is failing because you edited generated code but didn't update hashes.

**Comment by srinivasreddy** [comment]
@serhiy-storchaka What do you think now? merge?

**Pull request merged**
