### PR TITLE
Make devguide link in README more prominent

### PR DESCRIPTION
**Pull request by ncoghlan**

### CODE REVIEW

**Review by zware — APPROVED** [review]
LGTM.

**Review by aktech — APPROVED** [review]

**Comment by Mariatta** [comment]
I think this needs to be backported to 3.6, 3.5, and 2.7.
I'm now getting conflict while cherry-picking my commit from GH-283.
Is it ok if I cherrypick this into 3.6, 3.5, and 2.7?
Thanks.

**Comment by ncoghlan** [comment]
@Mariatta Please go ahead - neglecting to do that was just an oversight on my part at the PyCon Pune sprints.

**Comment by Mariatta** [comment]
Thanks @ncoghlan. It's been backported to 3.6. But it seems that we are not backporting readme changes to 3.5 or 2.7 as it broke Windows installer. http://bugs.python.org/issue29579

**Pull request merged**
