### PR TITLE
gh-94972: document that shield users need to keep a reference to their task

### PR DESCRIPTION
**Pull request by hendrikmakait**
I will take over the original PR (#94973) from @graingert to get it over the finish line. 

* Issue: gh-94972

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
Thanks for finishing this! I'll merge now.

**Comment by gvanrossum** [comment]
Oh wait, it's still in draft. I'll leave it up to you to remove draft mode; ping the PR and I'll merge it then.

**Review by graingert — APPROVED** [review]

**Comment by hendrikmakait** [comment]
@gvanrossum: Moved out of draft, thanks for the early review.

**Comment by gvanrossum** [comment]
Thanks Hendrik for finishing this up!

Thomas I hope you’re doing okay.

**Comment by Dreamsorcerer** [comment]
Sorry that I'm bringing this up so late. But, is this actually needed?

It seems to me that `shield()` has a reference to the task, so this should not be needed (i.e. It returns `outer`, which has a reference to `_outer_done_callback`, which has a reference to `inner` in the enclosing scope, which is the task. As long as you have a reference to `outer` (i.e. by `await`ing it), I don't think `inner` can be garbage collected).

If I'm wrong about that somewhere, shouldn't we just fix `shield()` to keep a reference, rather than asking the user to make this extra, non-obvious step every time they use it?

**Comment by graingert** [comment]
@Dreamsorcerer when the result of shield is cancelled the reference to the original task is dropped

**Pull request merged**
