### PR TITLE
bpo-37207: enable vectorcall for type.__call__

### PR DESCRIPTION
**Pull request by jdemeyer**
Base PR for other PRs that want to play with `type.__call__` such as #13930 and #14589.

The author is really @markshannon I just made the PR.

https://bugs.python.org/issue37207

Automerge-Triggered-By: @encukou

### CODE REVIEW

**Comment by jdemeyer** [comment]
CC @encukou

**Comment by jdemeyer** [comment]
Ping?

**Review by encukou — APPROVED** [review]
Let's use this.
Apologies for the time it took me to get to this. Life got in the way.

**Comment by jdemeyer** [comment]
> Life got in the way.

No problem. Thanks!

**Pull request merged**
