### PR TITLE
Remove a redundant assignment in Tools/unittestgui/unittestgui.py

### PR DESCRIPTION
**Pull request by shidenko97**
I've just removed duplicated defining an attribute `__rollbackImporter` in class `BaseGUITestRunner`, module `unittestgui`. It's not important, but Python code should be clear.

Automerge-Triggered-By: GH:iritkatriel

### CODE REVIEW

**Review by eamanu — APPROVED** [review]
Hi! Good catch @shidenko97 LGTM. 

IMO is very simple change, and I'm curious why this line is there.

**Comment by iritkatriel** [comment]
closing and reopening to get a current test run.

**Review by iritkatriel — APPROVED** [review]

**Comment by iritkatriel** [comment]
This probably needs to be rebased.

**Comment by shidenko97** [comment]
> This probably needs to be rebased.

@iritkatriel Main merged to current branch

**Pull request merged**
