### PR TITLE
gh-101047: Remove LIBTOOL_CRUFT

### PR DESCRIPTION
**Pull request by indygreg**
This variable has been unused since commit
19199830f7f880b1e9cff5d92d30706fd8bb4700 in 2011.

I noticed it because the `arch` logic breaks when cross-compiling on macOS.

* Issue: gh-101047

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Please, run `make regen-configure` to fix the CI :)

**Comment by indygreg** [comment]
I saw the configure failure and was kinda hoping some automation would suggest a fix since I didn't feel like shaving the yak of installing autoconf 2.69. But now that I'm enlightened about the existence of a make rule that pulls a container image with autoconf 2.69, there's no yak to shave. Nice!

Force pushed with the `configure` regen.

**Review by ned-deily — CHANGES_REQUESTED** [review]
Thanks for the PR. It looks OK to me. But, if we're going to clean up vestigial libtool code from the early days of MacOS X, we should also remove the few references to OTHER_LIBTOOL_OPT in configure.ac, configure, and Makefile.pre.in.

**Comment by indygreg** [comment]
> Thanks for the PR. It looks OK to me. But, if we're going to clean up vestigial libtool code from the early days of MacOS X, we should also remove the few references to OTHER_LIBTOOL_OPT in configure.ac, configure, and Makefile.pre.in.

I agree with you on the desire for some ancient macOS support code to get purged. But one of the things I learned from being a maintainer of Firefox's build system for several years (and submitting + reviewing thousands of commits to the build system) is that scope bloating build system changes is a recipe for unexpected regressions. Due to the nuance and sensitivity of build systems, I've learned it is best to keep changes small and tightly scoped.

So I'm gently pushing back on the request to scope bloat an otherwise _looks OK_ PR.

(FWIW I'm sitting on a pile of patches to CPython's build system that I'd love to get upstreamed. Many of them involve Apple OS support code. I could potentially add `OTHER_LIBTOOL_OPT` to that set.)

**Comment by ned-deily** [comment]
I agree with the desire to avoid "scope bloat" but I think the key here is what is the reason for making this change at all. In general, we don't make code cleanup changes without a reason. But this PR identifies a good reason, that is, the commit you cited, 19199830f7f880b1e9cff5d92d30706fd8bb4700, was incomplete; since it removed the last use of libtool for macOS builds, it should have removed the remaining references to it. The PR as it stands removes one of those; a quick grep of the source identifies the other, the `OTHER_LIBTOOL_OPT` variable (also seen in the cited commit). So the reason for making this change is to remove `libtool cruft`, not just `LIBTOOL_CRUFT`, and, if we make such a change, we need to finish the job not just leave it partially done. It's pretty clear that this is a low-risk change but we would further mitigate risk of problems by only making such a change in the main branch for the next feature release; i.e. we would not backport it to existing releases as it fixes no bugs.

**Comment by indygreg** [comment]
I refreshed the commit to also delete code related to `OTHER_LIBTOOL_OPT`.

**Review by ned-deily — APPROVED** [review]
Thanks for making the changes!

**Pull request merged**
