### PR TITLE
Correctly exclude @skrah's PRs from mentionbot

### PR DESCRIPTION
**Pull request by dstufft**

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Comment by berkerpeksag** [comment]
It looks like it's already fixed in master: https://github.com/python/cpython/commit/460b1cc152630079adef8a9923089de734cbb26a

**Comment by dstufft** [comment]
Looks like a fix got pushed directly to master right after I opened this PR.

**Comment by skrah** [comment]
@dstufft @brettcannon  It was pushed before I had knowledge of the existence  this PR.  Unlike @dstufft I don't have time to follow GitHub all day long.

You are making contributing to CPython a complete pain. How about doing some real work?

**Comment by dstufft** [comment]
@skrah I would note that if you had made a PR, the mention-bot would have mentioned me and I would have noticed your error before you committed it. Maybe it would be more helpful for you to leave it on.

**Comment by alex** [comment]
Lots of us are finding the new process to be an improvement. There are ways to register your feedback without being a jerk.

**Comment by skrah** [comment]
@alex Other people are jerks in certain IRC channels (as you well know: shall I post some excerpts?).

But you don't see that, since they're part of your clique.

**Comment by dstufft** [comment]
@skrah I noticed that you committed something directly to `master` that was broken, so I quietly opened a PR to resolve that. There was no value judgements made about you in that. When it was pointed out that you had since then committed a fix to that directly to `master` I quietly again closed the PR.

Picking fights with people or putting down their efforts because you don't like the new thing is not an OK thing to do. It is childish, rude, and it violates the PSF CoC.

**Comment by skrah** [comment]
@dstufft You know perfectly well what has been said on IRC some time ago that drastically violates the CoC.  In public you manage to appear mature and politically correct.

In this case, I took "Looks like a fix got pushed directly to master right after I opened this PR." to imply that I saw the PR and then tried to sneak in my own commit -- this is false, I saw the PR afterwards.

*That* made me angry.   You *always* have a subtle way of painting other people in a bad light while leaving an escape hatch when called out on it.

Instead of "push ... right after I opened the PR", a more neutral phrasing would have been "in the meantime".  No implications, you see.

**Comment by ncoghlan** [comment]
@skrah Race conditions happen, and it doesn't do you any credit to continue holding grudges over the removal of external hosting support from PyPI (I am assuming that's the origin of the ongoing animosity here).

We're in a world where the web won, and those of us that were quite happy with a text-only internet are the ones that are going to have to adjust to the expectations of the generations that came after us if we'd like to be able to continue to recruit new contributors.

Yes, that approach does mean that imposed workflow changes become an ongoing source of irritation and annoyance for existing contributors, but the alternative is seeing projects we care about decline and fail as the generation that first created them gets older and subsequent generations direct their attention elsewhere.

**Comment by AraHaan** [comment]
@ncoghlan I agree with some of the things you said.
Also there was and is no point in fighting about the fact that someone pushes a fix before someone else can. I know how annoying it can be but in some cases the patches that/those person(s) does/did could be less error prone but not always the case.

**Comment by skrah** [comment]
@ncoghlan You are misrepresenting me here.

Timeline:

14:01:22: I committed the glitch.
14:08:49: I committed the fix.
14.09:??: Mr Stufft *opens* the issue.
14:13:??: Berker says issue is already fixed.
14:14:??: Mr Stufft falsely claims the fix got committed right after he opened the issue.


Sorry Nick, you also were involved in removing external packages and I don't have issues with you -- from my side at least :).

The reason is that *you* never do these things that upset me.

**Comment by dstufft** [comment]
This is a silly point of contention @skrah but committing is not the same as pushing and what I *said* was the fix got pushed right after. Here's the #python-dev logs:

```
[08:03:48]  <github>	[cpython] skrah pushed 1 new commit to master: https://github.com/python/cpython/commit/4be6cc11ae09c158bcaa21f664462f6ef3c53799
[08:03:48]  <github>	cpython/master 4be6cc1 Stefan Krah: Find my own reviewers for PRs.
[08:10:04]  <github>	[cpython] dstufft opened pull request #427: Correctly exclude @skrah's PRs from mentionbot (master...fix-mention-bot) https://github.com/python/cpython/pull/427
[08:10:58]  <github>	[cpython] skrah pushed 1 new commit to master: https://github.com/python/cpython/commit/460b1cc152630079adef8a9923089de734cbb26a
[08:10:58]  <github>	cpython/master 460b1cc Stefan Krah: Fix config file syntax (hopefully).
[08:14:58]  <github>	[cpython] dstufft closed pull request #427: Correctly exclude @skrah's PRs from mentionbot (master...fix-mention-bot) https://github.com/python/cpython/pull/427
```

**Comment by brettcannon** [comment]
OK, I'm locking down this thread before this thread gets any worse.

@skrah your attitude is uncalled for. If you have been mistreated on IRC then please bring that up with either the IRC admin for the channel or the PSF board for proper handling. But past indiscretions do not warrant the negativity you showed here; being treated poorly does not mean you then get to treat others poorly in retaliation.

**Pull request closed without merging**
