### PR TITLE
bpo-35132: Fixes missing target in gdb pep0393 check.

### PR DESCRIPTION
**Pull request by lisroach**
https://bugs.python.org/issue35132

It looks like it only happens when built with optimizations which means many of the tests don't run, possibly why this was missed. 

I believe target() is unneeded here since 'data' would exist regardless of the type of the target. Perhaps @vstinner or @ambv have more insight.

https://bugs.python.org/issue35132

### CODE REVIEW

**Comment by vstinner** [comment]
> I believe target() is unneeded here since 'data' would exist regardless of the type of the target. Perhaps @vstinner or @ambv have more insight.

I bet that it depends on the gdb version, I'm waiting for the reply of the bug reporter: https://bugs.python.org/issue35132#msg335518

**Comment by vstinner** [comment]
@lisroach: Would you mind to add a NEWS entry? Something like "Fix py-list and py-bt commands of python-gdb.py on gdb7."

**Comment by lisroach** [comment]
Sure thing. Maybe it would be better to wrap it in a try: except, if target() fails we try again without target?

**Review by vstinner — APPROVED** [review]
LGTM. You can merge it @lisroach, but this fix will need a backport to 3.7.

**Comment by vstinner** [comment]
Oh, this change is specific to Python 3 and doesn't make sense in Python 2 which doesn't have the "pep393" code.

**Comment by vstinner** [comment]
Thanks @lisroach for the fix ;-)

**Pull request merged**
