### PR TITLE
bpo-32529: Replace read with readinto in shutil.copyfileobj

### PR DESCRIPTION
**Pull request by YoSTEALTH**
improved "copyfileobj" function to use less memory

https://bugs.python.org/issue32529

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by asvetlov** [comment]
Please add NEWS entry

**Comment by YoSTEALTH** [comment]
@asvetlov i am new to github where exactly do you add this "NEWS entry" ?

**Comment by asvetlov** [comment]
https://devguide.python.org/committing/?highlight=news#what-s-new-and-news-entries has detailed info

**Comment by YoSTEALTH** [comment]
Looks like i created a new pull request, closing this one.

**Pull request closed without merging**
