### PR TITLE
bpo-43930: Update bundled pip to 21.1 and setuptools to 56.0.0

### PR DESCRIPTION
**Pull request by sbidoul**
https://bugs.python.org/issue43930

### CODE REVIEW

**Review by pradyunsg — APPROVED** [review]
LGTM!

**Review by pfmoore — APPROVED** [review]

**Comment by Mariatta** [comment]
Does this still need backport to 3.10 and 3.9? If not, please remove the labels.

**Comment by sbidoul** [comment]
Yes, backports to 3.8 and 3.9 are merged. I can't remove the labels myself.

**Comment by pfmoore** [comment]
Done

**Pull request merged**
