### PR TITLE
bpo-39797 Changes to socketserver.BaseServer's shutdown() method.

### PR DESCRIPTION
**Pull request by amaajemyfren**
https://bugs.python.org/issue39797

Automerge-Triggered-By: @ned-deily

### CODE REVIEW

**Review by ned-deily — CHANGES_REQUESTED** [review]
Thanks for the PR.  Generally, for doc-only changes, there is no need to include a [NEWS entry](https://devguide.python.org/committing/#what-s-new-and-news-entries) so please update the PR to remove it.  Also as was noted elsewhere, in general you should just submit one PR and against the master branch (or whatever the highest applicable branch is).  If accepted, the core developer will mark the PR to be automatically backported to appropriate maintenance branches.  So I'm going to close the PRs you submitted against other branches so you don't need to update them.

**Comment by amaajemyfren** [comment]
> Thanks for the PR. Generally, for doc-only changes, there is no need to include a [NEWS entry](https://devguide.python.org/committing/#what-s-new-and-news-entries) so please update the PR to remove it. 

Thanks. Will do so.

> Also as was noted elsewhere, in general you should just submit one PR and against the master branch (or whatever the highest applicable branch is). If accepted, the core developer will mark the PR to be automatically backported to appropriate maintenance branches. So I'm going to close the PRs you submitted against other branches so you don't need to update them.

Thanks. I was not sure what to do and so I decided to write to the previous ones. Sorry for that.

**Comment by amaajemyfren** [comment]
Apologies for closing and reopening the PR. I clicked the wrong button when responding.

**Comment by amaajemyfren** [comment]
I have made the requested changes; please review again

**Review by ned-deily — APPROVED** [review]

**Pull request merged**
