### PR TITLE
Fix typo in `__match_args__` documentation.

### PR DESCRIPTION
**Pull request by icecream17**

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
Looks good, thanks for the fix! I can merge this as soon as the CLA is signed.

**Comment by icecream17** [comment]
unfortunately, I'm using my school's chromebook which blocks the site, so this will take a while...

**Comment by AlexWaygood** [comment]
No worries, there's no rush :)

**Comment by iritkatriel** [comment]
@icecream17 We can accept a typo fix without CLA, but do sign it so you can make more meaty contributions in the future.

**Review by iritkatriel — APPROVED** [review]

**Comment by terryjreedy** [comment]
Steven, I made of copy PR,  #99785, so we can proceed with this.

**Pull request closed without merging**
