### PR TITLE
bpo-36642: make unicodedata const

### PR DESCRIPTION
**Pull request by methane**
https://bugs.python.org/issue36642

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM.

But I don't think that it deserves to be backported.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by methane** [comment]
@benjaminp Should I update `VERSION = "3.3"` in makeunicodedata.py?

**Comment by vstinner** [comment]
> @benjaminp Should I update VERSION = "3.3" in makeunicodedata.py?

Since the script is part of Python, I don't see the point of having a version for the tool. As the changelog, since the script is tracked in Git, I don't see the point of having a dedicated changelog (but keeping the old changelog is fine).

**Comment by vstinner** [comment]
I would suggest to just remove VERSION = "3.3" from Tools/unicode/makeunicodedata.py :-)

**Comment by benjaminp** [comment]
FWIW, I agree with vstinner that the `VERSION` string is useless.

**Pull request merged**
