### PR TITLE
bpo-29237:  Add missing NEWS entry

### PR DESCRIPTION
**Pull request by ethanfurman**
https://bugs.python.org/issue29237

### CODE REVIEW

**Review by methane — APPROVED** [review]

**Comment by Mariatta** [comment]
Hm, news entry already present in the original PR? https://github.com/python/cpython/pull/5103/files#diff-b1662ec7a5e858b21ea9fe160546636f

**Comment by Mariatta** [comment]
Also, usually we add "Patch by ..."

**Comment by ethanfurman** [comment]
NEWS request was there, I just wasn't seeing it.

**Comment by ethanfurman** [comment]
Thanks, everyone!  Just started trying to use GitHub, so experiencing the growing pains now (and pining for mercurial, but C'est la vie).

**Pull request closed without merging**
