### PR TITLE
gh-111062: Add nogil build test on GitHub Actions

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-111062

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
IMO NoGIL is too experimental to hold merging PRs as this point. I would prefer to rely on buildbots for now.

cc @colesbury

**Comment by vstinner** [comment]
> Then what about adding CI that allows failure? (It's possible)

When I added a FreeBSD CI, people get annoyed by CI failures even if the CI was non-voting since FreeBSD is only a "Tier-3" buildbot.

**Comment by corona10** [comment]
> When I added a FreeBSD CI, people get annoyed by CI failures even if the CI was non-voting since FreeBSD is only a "Tier-3" buildbot.

Did it allowed pass status even if the CI itself is failed?

**Comment by vstinner** [comment]
> Did it allow pass status even if the CI itself failed?

People complained that the whole PR was marked as "failed" when the FreeBSD CI, whereas the FreeBSD CI was not mandatory.

**Comment by corona10** [comment]
> People complained that the whole PR was marked as "failed" when the FreeBSD CI

In Github Action we can ignore the "failed" status as the false postive. We did samething in pyperformance project.

**Comment by hugovk** [comment]
If people don't like seeing an (occasional?) red result, even if non-voting (i.e. doesn't block merge), another option is to append something like `|| true` to the test command to always make it "pass". 

The utility of this is debatable, as you have to click through to check if it really passed or failed.

**Comment by itamaro** [comment]
> The utility of this is debatable, as you have to click through to check if it really passed or failed.

I agree with this. I don't see the value of signal that always passes and requires a human to dig in to check for the real result.
in that sense, the manual buildbot triggerring seems preferable to me.

**Comment by hugovk** [comment]
We're probably best off waiting for the official SC acceptance so we know more about *how* this should be tested. Hopefully it'll be ready soon.

(And if something like this PR, we should do some refactoring of build.yml, it's getting pretty big. See https://github.com/python/cpython/pull/110794#issuecomment-1763470794.)

**Pull request closed without merging**
