### PR TITLE
[3.13] gh-116608: Revert "[3.13] gh-116608: Apply style and compatibility changes from importlib_resources. (GH-123028) (#123051)"

### PR DESCRIPTION
**Pull request by jaraco**
This reverts commit 5ac14eeea60328128ea9e7a588e2fad241db957d.

This commit should be re-applied after 3.13.0 final.

* Issue: gh-116608

### CODE REVIEW

**Comment by jaraco** [comment]
I guess technically this change should also be reviewed.

**Comment by FFY00** [comment]
@jaraco feel free to request a review from me in such cases. I do tend to keep up with the ongoing work in the `importlib_metadata` and `importlib_resources` backports, so it might be easier for me to have a look compared to others.

**Comment by jaraco** [comment]
An alternative to approving and merging this change could be to retroactively review and accept the changes for 3.13. I know we wouldn't normally apply such style-sync changes in an RC, but I also note that the AST doesn't change for the non-test code and changes only very modestly in tests. If @encukou would be okay with not applying this PR, that would be my preference.

**Comment by encukou** [comment]
I agree that, since the mistake is made, it's better to keep the style changes in than to revert them and re-introduce later.
@Yhg1s, do you agree?

**Comment by Yhg1s** [comment]
Yes, the changes seem benign enough that there's no point in reverting and reapplying.

**Pull request closed without merging**
