### PR TITLE
gh-103334: Ignore `Tools/c-analyzer/cpython/_parser.py` from `patchcheck`

### PR DESCRIPTION
**Pull request by sobolevn**
I've also added a small comment to `Tools/c-analyzer/cpython/_parser.py` to trigger the `patchcheck` CI. It must pass now.

* Issue: gh-103334

Automerge-Triggered-By: GH:ericsnowcurrently

### CODE REVIEW

**Comment by sobolevn** [comment]
Are there any other files to ignore?

**Review by ericsnowcurrently — APPROVED** [review]
This seems reasonable.  Ideally the reindent tool would ignore tabs in string literals, but that would be a messier change without much benefit.

**Comment by ericsnowcurrently** [comment]
I'm not aware of any other files to ignore.

**Comment by sobolevn** [comment]
@ericsnowcurrently I guess this now can be merged, any new files can be added afterwards if needed.

**Comment by ericsnowcurrently** [comment]
Thanks, @sobolevn!

**Pull request merged**
