### PR TITLE
[3.11] GH-92678: Fix tp_dictoffset inheritance. Backport of GH-95596

### PR DESCRIPTION
**Pull request by markshannon**
Backport of #95596

* Issue: gh-92678

### CODE REVIEW

**Comment by markshannon** [comment]
Bah, Modules/_testcapi/heaptype.c doesn't exist in 3.11. I'll need to fix it up manually.

**Review by pablogsal — APPROVED** [review]

**Comment by gvanrossum** [comment]
What about the Windows warnings (see the Files section of this PR)?

**Comment by pablogsal** [comment]
> What about the Windows warnings (see the Files section of this PR)?

Yeah, those are legitimate errors, it should return `NULL`. I will open a PR

**Comment by pablogsal** [comment]
https://github.com/python/cpython/pull/95664

**Pull request merged**
