### PR TITLE
bpo-46541: Remove usage of _Py_IDENTIFIER from lzma module

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue46541

### CODE REVIEW

**Comment by kumaraditya303** [comment]
Wrong bpo number ?

**Review by erlend-aasland — APPROVED** [review]
Check bpo number; else looks good to me.

**Review by kumaraditya303 — APPROVED** [review]
LGTM

**Comment by corona10** [comment]
I will merge this PR once the adding label is available, it looks like the outage situation.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Pull request merged**
