### PR TITLE
bpo-37219: Remove errorneous optimization for differencing an empty set

### PR DESCRIPTION
**Pull request by rhettinger**
https://bugs.python.org/issue37219

### CODE REVIEW

**Review by tirkarthi — COMMENTED** [review]
Could this case have a test for `TypeError` since this looks like reverting https://github.com/python/cpython/commit/4103e4dfbce .

**Comment by serhiy-storchaka** [comment]
LGTM, but would be nice to add a test.

We can check the size of the set in the loop. This would give the nefit not only for empty set, but in the case of substracting the larger set from the smaller set. But this is new feature and different issue.

**Comment by rhettinger** [comment]
FYI, I don't want to put a size check inside the loop.

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Comment by serhiy-storchaka** [comment]
Please add also a test for an iterable of unhasables, e.g. `[[]]`. It will trigger different error.

**Comment by rhettinger** [comment]
I don't know what you're talking about.  That gives a TypeError just like the existing test.

**Pull request merged**
