### PR TITLE
 gh-76106: Remove the cleanup lock in test_socket 

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-76106

### CODE REVIEW

**Comment by vstinner** [comment]
I suppose that it's a draft PR:

```py
    def create_run_tests(self, tests: TestTuple):
        tests = ('test_s
ocket',)
```

**Comment by serhiy-storchaka** [comment]
Yes, I used your recipe to run tests on buildbots. Sad, there are no longer buildbots for NetBSD, AIX, etc.

**Comment by vstinner** [comment]
For a draft PR, you can click on "Still in progress? Convert to draft". It prevents sending notifications and disallow merging a PR by mistake.

**Comment by vstinner** [comment]
> Sad, there are no longer buildbots for NetBSD, AIX, etc.

There are still AIX buildbots, but they are always failing:

* https://buildbot.python.org/all/#/builders/438
* https://buildbot.python.org/all/#/builders/704

**Comment by serhiy-storchaka** [comment]
I added label DO-NOT-MERGE while it was work in progress, as you suggested. Next time I'll also make it a draft (didn't I do it this time?).

**Comment by vstinner** [comment]
Thanks for the cleanup. I recently removed doCleanups() since it caused a race condition, whereas the lock was not needed: commit 318f5df27109ff8d2519edefa771920a0ec62b92 of issue gh-110167.

**Pull request merged**
