### PR TITLE
gh-103186: In test_tools.freeze, fetch CONFIG_ARGS from original source directory

### PR DESCRIPTION
**Pull request by TabLand**
instead of fetching from intermediate instance. As "make clean" is called against the intermediate instance, the build directory is cleared and the config arguments lookup fails with a ModuleNotFoundError:

```
# /opt/python/test/cpython/python -c 'import sysconfig; print(sysconfig.get_config_var("CONFIG_ARGS"))'
CalledProcessError: Command '['/opt/python/test/cpython/python', '-c', 'import sysconfig; print(sysconfig.get_config_var("CONFIG_ARGS"))']' returned non-zero exit status 1.
--- STDOUT ---

--- STDERR ---
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/test/cpython/Lib/sysconfig.py", line 740, in get_config_var
    return get_config_vars().get(name)
           ^^^^^^^^^^^^^^^^^
  File "/opt/python/test/cpython/Lib/sysconfig.py", line 723, in get_config_vars
    _init_config_vars()
  File "/opt/python/test/cpython/Lib/sysconfig.py", line 670, in _init_config_vars
    _init_posix(_CONFIG_VARS)
  File "/opt/python/test/cpython/Lib/sysconfig.py", line 536, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_sysconfigdata_d_linux_x86_64-linux-gnu'
```

More context here: https://github.com/python/cpython/issues/103186#issuecomment-1494217156

* Issue: gh-103186

### CODE REVIEW

**Comment by TabLand** [comment]
Hello @erlend-aasland: I saw you worked on a similar change recently, would appreciate any feedback.

Hello freeze experts: There is probably another way to capture the same info from the intermediate instance as long as we do so before "make clean" is called - but that solution felt messy. Please let me know whether I should have a go at improving the variable naming here as SRCDIR (original), srcdir (intermediate) and builddir (frozen) could cause confusion...

**Comment by arhadthedev** [comment]
@terryjreedy (as a participant of the parent issue)

**Comment by TabLand** [comment]
The following new exception for missing make file in the intermediate python instance is passing on all platforms except Ubuntu as part of the Github CI pipeline builds:

```
     if os.path.exists(os.path.join(newroot, 'Makefile')):
         _run_quiet([MAKE, 'clean'], newroot)
+    else:
+        raise Exception("new frozen build Makefile missing!")
```
I'm happy to remove this, as technically the existence of the Makefile depends on ./configure being run successfully first?

**Comment by arhadthedev** [comment]
Closing as a duplicate of gh-102152.

**Comment by erlend-aasland** [comment]
> Closing as a duplicate of [gh-102152](https://github.com/python/cpython/pull/102152).

This is not a duplicate of gh-102152, which fetched CONFIG_ARGS from the copied source directory instead of from the build directory. This PR fetches CONFIG_ARGS from the original source directory, so it is slightly different, and possibly more correct; I don't have the bandwidth to look at this right now. I'll definitely be able to review it around the summit in a couple of weeks.

**Comment by TabLand** [comment]
Hi @erlend-aasland / @terryjreedy,
Appreciate you're very busy...
Please let me know your thoughts on this PR?

**Comment by terryjreedy** [comment]
This PR involves things beyond my knowledge.  Erland, if you cannot finish this, can you suggest another reviewer?

**Comment by erlend-aasland** [comment]
@kumaraditya303, should we backport this to 3.12?

**Comment by kumaraditya303** [comment]
>  should we backport this to 3.12?

Yes

**Pull request merged**
