### PR TITLE
bpo-38465: Convert the type of ob_exports in PyByteArrayObject to Py_ssize_t

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue38465

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
LGTM. Thanks @shihai1991.

Do you mind to add a NEWS entry? Something like:
```
:class:`bytearray`, :class:`~array.array` and :class:`~mmap.mmap` objects allow now to export more than 2**31 buffers at a time.
```

**Comment by shihai1991** [comment]
> LGTM. Thanks @shihai1991.
> 
> Do you mind to add a NEWS entry? Something like:
> 
> ```
> :class:`bytearray`, :class:`~array.array` and :class:`~mmap.mmap` objects allow now to export more than 2**31 buffers at a time.
> ```

Thanks, serhiy. Your desc is good enough, so i copied your desc ;). 
But I have two questions, Maybe you can give me the answer:) :
1) do we have the clear criteria about adding new or not? i have faced this question many times~
2) what the meaning of tilde, such as you said: `~array.array`?

**Comment by animalize** [comment]
>     1. do we have the clear criteria about adding new or not? i have faced this question many times~

I understand if a change is visible to the users, then needs a News Entry.
 
>     2. what the meaning of tilde, such as you said: `~array.array`?

Here is an [explanation](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-syntax):

> If you prefix the content with ~, the link text will only be the last component of the target. For example, :py:meth:`~Queue.Queue.get` will refer to Queue.Queue.get but only display get as the link text. This does not work with all cross-reference roles, but is domain specific.

**Comment by shihai1991** [comment]
> > 1. do we have the clear criteria about adding new or not? i have faced this question many times~
> 
> My understand if a change is visible to the users, then needs a News Entry.

Good explanation. That make senses.

> 
> > 1. what the meaning of tilde, such as you said: `~array.array`?
> 
> Here is an [explanation](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-syntax):
> 
> > If you prefix the content with ~, the link text will only be the last component of the target. For example, :py:meth:`~Queue.Queue.get` will refer to Queue.Queue.get but only display get as the link text. This does not work with all cross-reference roles, but is domain specific.

I am not sure  I understand clearly or not: this means that we emphasize the last word(such as `get` of `Queue.Queue.get`)

**Comment by animalize** [comment]
> > Here is an [explanation](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-syntax):
> > > If you prefix the content with ~, the link text will only be the last component of the target. For example, :py:meth:`~Queue.Queue.get` will refer to Queue.Queue.get but only display get as the link text. This does not work with all cross-reference roles, but is domain specific.
> 
> I am not sure I understand clearly or not: this means that we emphasize the last word(such as `get` of `Queue.Queue.get`)

The displayed "link text" will only be `get`, when the reader click the `get`, will navigate to `Queue.Queue.get`.

**Comment by serhiy-storchaka** [comment]
@animalize already answered the questions, and I have nothing to add. Thank you @animalize.

**Pull request merged**
