### PR TITLE
gh-96706: [doc] Fix deprecated use of get_event_loop()

### PR DESCRIPTION
**Pull request by zhanpon**
#96706

### CODE REVIEW

**Review by gvanrossum — COMMENTED** [review]
Alas, it's not so straighforward. :-(

The Hello World with call_soon() section has a label `asyncio_example_lowlevel_helloworld` which is referenced from asyncio-llapi-index.rst, where it is used as an example for `get_event_loop()`. So the change would make that link confusing.

(The other two are fine.)

I'm not sure what to suggest.

**Comment by zhanpon** [comment]
@gvanrossum Thank you for the review! I didn't notice that.

How about we just change the link text?

```
$ git diff
diff --git a/Doc/library/asyncio-llapi-index.rst b/Doc/library/asyncio-llapi-index.rst
index cdadb7975a..3cec4c69f8 100644
--- a/Doc/library/asyncio-llapi-index.rst
+++ b/Doc/library/asyncio-llapi-index.rst
@@ -267,7 +267,7 @@ See also the main documentation section about the

 .. rubric:: Examples

-* :ref:`Using asyncio.get_event_loop() and loop.run_forever()
+* :ref:`Using asyncio.new_event_loop() and loop.run_forever()
   <asyncio_example_lowlevel_helloworld>`.

 * :ref:`Using loop.call_later() <asyncio_example_call_later>`.
 ```

**Comment by gvanrossum** [comment]
> How about we just change the link text?

That sounds like a good idea. Just add a commit to the PR!

**Comment by zhanpon** [comment]
@gvanrossum I've added the commit. Thanks for the confirmation!

**Review by gvanrossum — APPROVED** [review]
I'll merge!

**Pull request merged**
