### PR TITLE
[3.6] bpo-30217: add the operators ~ and | to the index (GH-1502)

### PR DESCRIPTION
**Pull request by marco-buttu**
Backport of #1502

### CODE REVIEW

**Comment by Mariatta** [comment]
Since this is a backport, I changed the base to `3.6` instead of `master`.

**Comment by serhiy-storchaka** [comment]
How you did this @Mariatta?

**Comment by Mariatta** [comment]
@serhiy-storchaka, next to the PR title, you should see the Edit button. I clicked on it: 

screen shot 2017-06-12 at 11 18 04 am

There you can change the base branch:

screen shot 2017-06-12 at 11 18 12 am


screen shot 2017-06-12 at 11 18 21 am


screen shot 2017-06-12 at 11 18 12 am



Hope this helps :)

There's a bug with `cherry_picker.py`, when it could not detect the proper maintenance branch, it selected the `master` branch. I think that's what happened here. I'll need to work on a solution for it.

**Comment by Mariatta** [comment]
But travis seems to hang? Not sure how we can retrigger it.

**Comment by Mariatta** [comment]
Seems like closing and reopening the PR will retrigger travis build.

**Comment by serhiy-storchaka** [comment]
I used the Edit button for editing the title but didn't notice the possibility of changing the basic branch. Thank you @Mariatta, now I came to know something new. It may help me once. :smile:

**Review by Mariatta — APPROVED** [review]

**Pull request merged**
