### PR TITLE
[3.9] bpo-43434: Move sqlite3.connect audit event to sqlite3.Connection.__init__ (GH-25818)

### PR DESCRIPTION
**Pull request by erlend-aasland**
(cherry picked from commit c96cc089f60d2bf7e003c27413c3239ee9de2990)

Co-authored-by: Erlend Egeberg Aasland <erlend.aasland@innova.no>

https://bugs.python.org/issue43434

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@zooba I left the tests. Let me know if I should remove them, as they were not present in 3.9.

**Comment by erlend-aasland** [comment]
@zooba Let me remove them; those PR's were not backported. Give me one minute.

**Review by zooba — APPROVED** [review]

**Comment by erlend-aasland** [comment]
There's a tiny spelling bug in the NEWS entry (were => was). I'll push a commit to fix it, if you don't mind.

**Comment by erlend-aasland** [comment]
I did the cherry-picking from the commit in `main`, iso. this one. Hope that's ok.

**Comment by erlend-aasland** [comment]
BTW, I'm logging off for tonight. If there's an issue, I'll look at it first thing in the morning.

**Pull request merged**
