### PR TITLE
gh-98822: Add missing test directories to TESTSUBDIRS

### PR DESCRIPTION
**Pull request by erlend-aasland**
Also sort the list

* Issue: gh-98822

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Simply the sorted output of `find Lib/test -type d`.

**Comment by erlend-aasland** [comment]
BTW, obviously needs a manual backport.

**Review by zware — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for the review, Zach.

**Comment by erlend-aasland** [comment]
Oh, I merged before the macOS CI was finished; sorry 'bout that!

**Comment by asottile** [comment]
this shouldn't have been backported verbatim to 3.11 -- the subdirs added there are incorrect (for example the tkinter ones)

**Comment by zware** [comment]
Ah, whoops; we did miss some differences.  See GH-103970.

**Comment by erlend-aasland** [comment]
> this shouldn't have been backported verbatim to 3.11 -- the subdirs added there are incorrect (for example the tkinter ones)

It wasn't backported verbatim at all.

**Pull request merged**
