### PR TITLE
gh-93649: Split pytime and datetime tests from _testcapimodule.c

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-93649

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
What do you think about separating "time" and "datetime" tests in two files?

The _PyTime_ObjectToTimespec() and _PyTime APIs are not directly related to the datetime module.

**Comment by erlend-aasland** [comment]
> What do you think about separating "time" and "datetime" tests in two files?
> 
> The _PyTime_ObjectToTimespec() and _PyTime APIs are not directly related to the datetime module.

Sounds good to me :)

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by erlend-aasland** [comment]
Thanks for the review, Victor!

**Pull request merged**
