### PR TITLE
bpo-33316: PyThread_release_lock always fails

### PR DESCRIPTION
**Pull request by native-api**
https://bugs.python.org/issue33316

### CODE REVIEW

**Comment by ned-deily** [comment]
@zooba Is this ready to merge?

**Comment by serhiy-storchaka** [comment]
Could you add any tests?

**Comment by native-api** [comment]
I don't see how it's possible to test this. There's no error code or anything, only an error message, and only if I patch the source (set `thread_debug` to `1` at https://github.com/python/cpython/blob/master/Python/thread.c#L48.

**Comment by vstinner** [comment]
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

**Pull request merged**
