### PR TITLE
Add version directives to ast docs

### PR DESCRIPTION
**Pull request by hauntsaninja**
----
:books: Documentation preview :books:: https://cpython-previews--108788.org.readthedocs.build/

### CODE REVIEW

**Review by JelleZijlstra — CHANGES_REQUESTED** [review]
The versionadded directives for a bunch of the match nodes are rendered within the code blocks: https://cpython-previews--108788.org.readthedocs.build/en/108788/library/ast.html#ast.MatchAs

I didn't add these initially because other recently added objects didn't have them. Not sure if there's a reason behind that, but it seems useful to add the directives.

You might also want to add 3.8 for NamedExpr, which incidentally is misindented (https://docs.python.org/3.10/library/ast.html#ast.NamedExpr).

**Comment by hauntsaninja** [comment]
Thank you! (I have made the requested changes; please review again)

**Review by JelleZijlstra — APPROVED** [review]
The build preview didn't update but I built locally and everything looks fine now, thanks!

We'll have to do a manual backport for 3.11.

**Comment by hugovk** [comment]
Aside: maybe the build preview was slow to upload or cached or something, here's the new versionadded above the "Subscripting" header:

image

https://cpython-previews--108788.org.readthedocs.build/en/108788/library/ast.html#subscripting

**Pull request merged**
