### PR TITLE
[3.11] GH-102456 Fix docstring and getopt options for base64

### PR DESCRIPTION
**Pull request by arhadthedev**
(cherry picked from commit d828b35785eeb590b8ca92684038f33177989e46)

* Issue: gh-102456

### CODE REVIEW

**Comment by arhadthedev** [comment]
I *hate* manual backporting. This task is extremely rare so it's impossible to learn all actions necesary, and in case of mistake everything needs to be done from scratch.

**Comment by arhadthedev** [comment]
(and I cannot use the same branch name anymore)

**Comment by brettcannon** [comment]
> I cannot use the same branch name anymore

Why not? If you delete the branch in both your local and remote clones then you should be able to use it again.

**Comment by brettcannon** [comment]
> This task is extremely rare so it's impossible to learn all actions necesary, and in case of mistake everything needs to be done from scratch.

Would you be writing to write some docs for https://devguide.python.org/ on how to do it?

**Pull request closed without merging**
