### PR TITLE
gh-78722: Fixed, pathlib.Path.iterdir now throws an exception when path is not valid

### PR DESCRIPTION
**Pull request by prudvinit**
* Issue: gh-78722

### CODE REVIEW

**Comment by wimglenn** [comment]
Please add test coverage.

**Comment by prudvinit** [comment]
Hi wim glenn,
Thanks for your interest. I'm a new contributor to python. Can you tell me
what is meant by test coverage. Please provide me any existing pull request
which has test coverage.

Thanks
Prudvi RajKumar M

**Comment by remilapeyre** [comment]
Hi @prudvinit, thanks for opening a PR. I'm not sure that your fix is correct but "test coverage" means writing a test to show code that was broken by the previous behavior of the function you changed so `iterdir()` in your case, and that your changed fixed. This serves multiple purposes, it shows the bug, shows your solution work and the test will fail if someone make another change that ends up breaking your fix.

The tests for the pathlib module are in test_pathlib.py, you can look at the other tests of `iterdir()` to try and write your own. I would be happy to help you if you get stuck.

**Comment by prudvinit** [comment]
Hi
I'd like to continue working on that. I'll add whatever is required and
reach out to you if I need any help.
Thanks
Prudvi M

**Comment by iritkatriel** [comment]
@prudvinit are you still working on this? Otherwise, could we close the PR so that someone else may pick it up?

**Comment by prudvinit** [comment]
Hi Katriel.

Haven't worked on it for a while. I'll work on it during the weekend and
try to finish it. I'll keep you updated,

Thanks
Prudvi M

**Comment by barneygale** [comment]
Hey @prudvinit - do you think you might have time to resolve conflicts and add tests? This looks like a useful fix!

**Comment by barneygale** [comment]
Thanks for this PR @prudvinit! In the discussion on the issue, we reached the conclusion that changing behaviour would be too disruptive, and that `list(path.iterdir())` is a reasonable workaround. As such I'm closing both the issue and this PR.

**Pull request closed without merging**
