### PR TITLE
bpo-36523: Add docstring to io.IOBase.writelines

### PR DESCRIPTION
**Pull request by n0npax**
Add docs to `io.IOBase.writelines`

https://bugs.python.org/issue36523

### CODE REVIEW

**Comment by terryjreedy** [comment]
The text is copied from the io module docs and looks correct.  I am not familiar with the proper formatting in .c files, in particular, the initial blank line. I changed the titles and news items because 'add documentation' usually means 'add to the .rst doc file'.

**Comment by vadmium** [comment]
Looks okay to me.

If you are worried about the Arg Clinic formatting Terry, I would compare it to the surrounding functions (e.g. _readlines_ directly above), or the existing _io.BytesIO.writelines_ Clinic code, and check the resulting `__doc__` attributes.

**Comment by n0npax** [comment]
Hi,
Seems a blank line is required due to: https://mail.python.org/pipermail/python-dev/2013-June/127110.html
Lack of blank line casues a clinic error (`vim Tools/clinic/clinic.py +4807` )

**Comment by methane** [comment]
Same docstring should be added to Lib/_pyio.py

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by n0npax** [comment]
@methane Thanks for the suggestion, I just added requested docs to `_pyio`

Anyway, I'm really sorry for notification to all reviewers. Accidentally I made a merge in my branch and a lot of reviewers were added to this PR. I'm really Sorry guys.

**Pull request merged**
