### PR TITLE
gh-126259: Fix warning in doctest of `sqlite3`

### PR DESCRIPTION
**Pull request by sobolevn**
After:
Снимок экрана 2024-11-01 в 01 32 18

* Issue: gh-126259

----
📚 Documentation preview 📚: https://cpython-previews--126260.org.readthedocs.build/

### CODE REVIEW

**Comment by graingert** [comment]
Is it possible to use a `with contextlib.closing(...` here?

**Review by graingert — COMMENTED** [review]
.

**Comment by sobolevn** [comment]
But why? I would need to import this lib and use a different syntax from other examples.

**Comment by graingert** [comment]
Ah I see there's a lot of other manual closing in the other doctests. This is not the recommended way to use this module, but it is consistent with the other tests. Perhaps this should be fixed in another ticket

**Review by graingert — APPROVED** [review]

**Comment by erlend-aasland** [comment]
> This is not the recommended way to use this module [...]

This comment does not make sense to me, given what we're discussing. The doctests are all example code either in the reference or in the tutorial; showing the user how to set up and close a connection for each example would be contra-productive. Also, adding unneeded `.. testsetup`/`.. testcleanup` boilerplate for setting up and tearing down a connection in sqlite3.rst would not add any value at all.

**Review by erlend-aasland — APPROVED** [review]

**Pull request merged**
