### PR TITLE
gh-124612: Use ghcr.io/python/autoconf instead of public image

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-124612

### CODE REVIEW

**Comment by corona10** [comment]
@erlend-aasland Ready to review!

**Comment by corona10** [comment]
@erlend-aasland I am merging this PR, please let me know if we need to fix more things :)

**Comment by erlend-aasland** [comment]
Looks good :)

**Comment by erlend-aasland** [comment]
@corona10, next time remember to edit the commit message ;) But more importantly, what do you think of backporting this to 3.13 and 3.12? cc. @hugovk

**Comment by hugovk** [comment]
A backport will probably make it easier to maintain all three branches.

**Comment by erlend-aasland** [comment]
> A backport will probably make it easier to maintain all three branches.

Let's backport it, then.

**Pull request merged**
