### PR TITLE
gh-104882: Docs: fix description of relationship between `socket.getblocking()` and `socket.gettimeout()`

### PR DESCRIPTION
**Pull request by joegeisbauer-ce**
* Issue: gh-104882

----
:books: Documentation preview :books:: https://cpython-previews--105026.org.readthedocs.build/

### CODE REVIEW

**Comment by joegeisbauer** [comment]
This issue with the documentation goes back to v3.7.

**Comment by joegeisbauer** [comment]
Will this automatically get marked for review or do I need to do anything special here?

**Review by AlexWaygood — APPROVED** [review]
Thanks!

**Comment by AlexWaygood** [comment]
Thanks @joegeisbauer! I've merged the PR, and backported it to 3.12 and 3.11. Earlier versions of Python now only accept patches if they relate to security issues (which this isn't!), so it won't be backported to 3.10 or earlier.

I removed the NEWS entry before merging, as we don't usually include them for docs-only changes :-)

**Pull request merged**
