### PR TITLE
bpo-29924: Remove useless argument

### PR DESCRIPTION
**Pull request by SylvainDe**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by SylvainDe** [comment]
I've signed the CLA.

**Comment by SylvainDe** [comment]
@haypo may be the most relevant reviewer for this.

**Comment by vstinner** [comment]
> I've signed the CLA.

The change LGTM, but it seems like the signature wasn't validated yet. Let's wait 1 or 2 days and check again if the bot is happy.

Did you set your GitHub username in your bugs.python.org profile?

**Review by vstinner — DISMISSED** [review]
LGTM but wait for the CLA tag.

**Comment by SylvainDe** [comment]
@haypo Thanks for the quick reply. I've just added my Github handle to my profile on the bug.report. Let's wait and see :-)

**Comment by vstinner** [comment]
On this tiny change, I didn't ask you to add yourself to Misc/ACKS, but you may have to do it for your next change.

Thanks for your first contribution to CPython! I made the mistake, but I'm happy that someone found it, and even better, fixed it!

**Pull request merged**
