### PR TITLE
GH-110894: Call loop exception handler for exceptions in client_connected_cb

### LINKED ISSUE #110894: Asyncio stream doesn't handle exceptions in callback
# Bug report

### Bug description:

Consider the following server that always just crashes:
```python
import asyncio

async def handle_echo(reader, writer):
    raise Exception("I break everything")

async def main():
    server = await asyncio.start_server(
        handle_echo, '127.0.0.1', 8888)
    async with server:
        await server.serve_forever()

asyncio.run(main(), debug=True)
```
Together with the following client:
```python
import asyncio

async def tcp_echo_client(message):
    reader, writer = await asyncio.open_connection(
        '127.0.0.1', 8888)

    data = await reader.read(100)
    print(data)
    writer.close()
    await writer.wait_closed()
    print("closed")

asyncio.run(tcp_echo_client('Hello World!'), debug=True)
```
When running this in Python 3.8, the server prints a `Task exception was never retrieved` message with an exception. I guess this is acceptable. However, the connection is never closed, and the client is kept hanging. That should not happen in my opinion.

Furthermore, in newer Python versions, due to https://github.com/python/cpython/pull/96323, the internal task is being kept alive indefinitely. Therefore, the `Task exception was never retrieved` message is only printed when you kill the server. Otherwise, the failure is completely silent. This is extremely counter-intuitive behavior.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-111601
* gh-111632
* gh-111634

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-110894

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
Thanks, good fix!

**Comment by vstinner** [comment]
The test fails on many buildbots: see previous comments and issue #111644.

**Comment by markshannon** [comment]
@kumaraditya303 Please revert this ASAP. CI is failing on main, meaning we cannot merge bug fixes for other issues.

**Comment by vstinner** [comment]
> @kumaraditya303 Please revert this ASAP. CI is failing on main, meaning we cannot merge bug fixes for other issues.

I fixed the issue with PR #111713. Sadly, on existing PRs, either failing jobs should be re-run, or the PR should be rebased on the main branch.

> Sorry, @kumaraditya303, I could not cleanly backport this to 3.11 due to a conflict.

@kumaraditya303: Do you plan to backport the change to 3.11? If yes, please include my fix in your backport ;-)

**Comment by vstinner** [comment]
> @kumaraditya303: Do you plan to backport the change to 3.11? If yes, please include my fix in your backport ;-)

Oh, PR #111634 already exists. I included my fix in this backport.

**Pull request merged**
