### PR TITLE
gh-120572: add missing parentheses in TypeIs documentation

### PR DESCRIPTION
**Pull request by BlueGlassBlock**
* Issue: gh-120572

----
📚 Documentation preview 📚: https://cpython-previews--120573.org.readthedocs.build/

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks for the fix! (and looks like the spec https://typing.readthedocs.io/en/latest/spec/narrowing.html uses parentheses for this phrasing)

**Comment by terryjreedy** [comment]
As is, the doc could be read as meaning the third parameter, which the second after the first.  If applicable, backport to 3.12.

**Comment by BlueGlassBlock** [comment]
> As is, the doc could be read as meaning the third parameter, which the second after the first. If applicable, backport to 3.12.

The wording seems to be from `TypeGuard`'s documentation in 3.10 - 3.12. I guess they all need backports?

**Comment by hauntsaninja** [comment]
`TypeIs` is new in 3.13, so this PR should only be backported to 3.13.

I'd accept a PR targeting the 3.12 branch that changes the wording for `TypeGuard` that exists in that branch!

**Comment by BlueGlassBlock** [comment]
Thanks for reviewing and explaining @hauntsaninja! I'll look into it.

**Pull request merged**
