### PR TITLE
bpo-31060: IDLE: Finish regrouping ConfigDialog methods

### PR DESCRIPTION
**Pull request by terryjreedy**
* In configdialog: collect hightlight functions under create_page_hightlight.
WIP

https://bugs.python.org/issue31001

### CODE REVIEW

**Review by csabella — COMMENTED** [review]
The diff on the commit for moving things around is impossible, but I ran the htests and it worked without any issues.

**Comment by mlouielu** [comment]
Diff is dead. I'm not sure about this, but can the tab be split to a module that contain different parts of the tab? 

e.g.
```
 \configdialog
      |---- __init__.py
      |---- tab_font.py
      |---- tab_highlight.py
      |---- .....
```

**Comment by mlouielu** [comment]
P.S. For appveyor not building CI, @haypo gave the workaround to fix this: close the PR and re-open   it.

**Comment by csabella** [comment]
@mlouielu   Yes, this is the first steps to moving this into its own class and maybe even into separate modules (Terry hasn't talked about splitting the modules yet.)

**Comment by terryjreedy** [comment]
I take the comments above to mean that you both noticed also that the diff is crazy and not humanly readable.  I did not mean for either of you to try.  Git diff insisted on creating replace blocks, with _ and + lines.  This diff would be simple if it had one add block with + lines and about five delete blocks with - lines, mimicking what I actually did.  Instead git deletes lines I never deleted and adds them back, in little chunks.  Perhaps if I had copied everything first, committed, then deleted the old and commited, there would have been two simple commit diffs.  But the net result would be the same.

Github can apply its own patch, as indicated by 'Merging can be performed'.  Travis did so and tests padded.  I just did 'git pr 2908' to make a new branch and the tests ran in the branch.

The human review for the re-arrangement is to verify that var_change methods for all the vars in the docstring (except fg-bg toggle) and all the methods listed actually follow the page method.  I just did so by copying the var list and method list into Notepad and checking off each with an X.  No need to repeat.

The methods currently have the order they had in the file.  I am about to re-arrange them is a more sensible order, though it won't necessarily be the final order.  I was planning to continue by redoing the docstring as I have before.  Then possibly rename while writing tests.  But the net diff for configdialog mixing method movements with real edits would be even worse to read.  Instead, I will finish rearranging by page and button groups and within groups as well as I can determine now.  I will open a new issue for this.

**Comment by terryjreedy** [comment]
I have no plan to split the module, just to rearrange and then split the class within the module.

**Pull request merged**
