### PR TITLE
bpo-27103: regrtest disables -W if -R is used

### PR DESCRIPTION
**Pull request by vstinner**
Workaround for a regrtest bug.

### CODE REVIEW

**Comment by vstinner** [comment]
This change is not a proper fix, just a workaround to be able to move forward on the new "Refleaks" buildbot that @zware just created:
http://buildbot.python.org/all/builders/x86%20Gentoo%20Refleaks%203.6/

**Comment by zware** [comment]
I think I'd rather change the builder config, possibly by adding a new make target for it (`make refleaktest`?).

**Comment by vstinner** [comment]
I was bitten multiple timed by this bug. The rationale is non obvious. I
would like to fix it.

**Comment by zware** [comment]
Ok, fair enough.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. Could you add a test for this? It should be easy in ParseArgsTestCase.

I don't know whether it is worth to make this an error rather than a warning.

**Review by zware — APPROVED** [review]

**Comment by vstinner** [comment]
Could you add a test for this? It should be easy in ParseArgsTestCase


Since it's a temporary workaround, I don't want to write a test for it.

I'm quite sure that it's possible to really fix the bug by reorganizing the
code.

**Pull request merged**
