### PR TITLE
bpo-30367: fix _testcapi to work when statically linked into Cpython3

### PR DESCRIPTION
**Pull request by Nan-Zhang**
*Edit by @pganssle to add easy BPO link*:
https://bugs.python.org/issue30367

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Nan-Zhang** [comment]
The CLA has been signed right now.

**Comment by Nan-Zhang** [comment]
Ping!

**Comment by benjaminp** [comment]
Can you simply define `PyDateTime_IMPORT` to be an empty statement if `Py_BUIlD_CORE` is defined?

**Pull request closed without merging**
