### PR TITLE
bpo-35177: Add dependencies between header files

### PR DESCRIPTION
**Pull request by vstinner**
* ast.h now includes Python-ast.h and node.h
* parsetok.h now includes node.h and grammar.h
* symtable.h now includes Python-ast.h
* Modify asdl_c.py to enhance Python-ast.h:

  * Add #ifndef/#define PYTHON_AST_H to be able to include the header
    twice
  * Add "extern { ... }" for C++
  * Undefine "Yield" macro conflicting with winbase.h

* Remove "#undef Yield" from C files, it's now done in Python-ast.h
* Remove now useless includes in C files

https://bugs.python.org/issue35177

### CODE REVIEW

**Comment by vstinner** [comment]
I added the "skip news" label: my changes don't impact the public C API, and is not backward incompatible.

**Comment by vstinner** [comment]
@serhiy-storchaka @ncoghlan: I tried to go further in this PR, but also add more missing includes. Tell if it looks better than my previous attempt, or if you prefer to leave C file unchanged for example (only remove #undef Yield?).

**Comment by vstinner** [comment]
I plan to merge this PR next week if I don't get feedback before.

**Review by ncoghlan — APPROVED** [review]

**Comment by vstinner** [comment]
This PR doesn't try to fix "all dependencies issues", but it fix a few of them :-) See https://bugs.python.org/issue35197 for another example of funny header issue.

**Pull request merged**
