### PR TITLE
gh-91547: Remove "Undocumented modules" page

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by hauntsaninja** [comment]
cc @JelleZijlstra

**Comment by arhadthedev** [comment]
You can add:

> Closes gh-91547.

into the first message of this PR so GitHub will autoclose the issue on merge.

**Comment by JelleZijlstra** [comment]
I think this is worth documenting in NEWS, since we're removing a whole page. I'll also ask for feedback from the docs WG.

**Comment by Mariatta** [comment]
Yes there is a Documentation section for the news. I think it makes sense to remove this page. The info is already captured in os.path documentation.

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
