### PR TITLE
bpo-29862: Fixed grammar error in TypeError exception message in reload function

### PR DESCRIPTION
**Pull request by mandeep**
Fixed the grammar error found by Brett in the TypeError exception message on Line 140. All tests passed after making the change so I went ahead and created this pull request. If I need to add a test that checks the exception message, please let me know.

### CODE REVIEW

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Looks good :) Thanks, @mandeep :tada:

**Comment by Mariatta** [comment]
@mandeep Could you add a test for this change? Thanks :)

**Comment by orsenthil** [comment]
@Mariatta , we only assert the Exception Type, and we don't test the contents of the Exception Str. So, the change LGTM as it is.

**Comment by Mariatta** [comment]
Ah ok, Thanks @orsenthil :) I thought we needed to get codecov green by adding test. In that case I can merge this. Still wondering whether this needs to be backported at all?

**Comment by orsenthil** [comment]
Since it is a grammar / spell fix, backporting seems harmless to me. +1 if you were planning to do that.

**Comment by mandeep** [comment]
@Mariatta sorry I couldn't respond sooner. Thanks for submitting the backport changes. :smiley:

**Comment by Mariatta** [comment]
Thanks again @orsenthil  and @mandeep :)
This has been backported into 3.5 and 3.6, and I closed the b.p.o issue. :tada:

**Pull request merged**
