### PR TITLE
bpo-37111: Added encoding keyword parameter to basicConfig.

### PR DESCRIPTION
**Pull request by vsajip**
https://bugs.python.org/issue37111

### CODE REVIEW

**Comment by vsajip** [comment]
@zooba Please review just to ensure I haven't missed anything ... thanks.

**Comment by zooba** [comment]
@vsajip We normally add `encoding` and `errors` parameters as pairs (at least, this is what I was asked to do when adding them to `subprocess`)

**Comment by zooba** [comment]
To be clear, I mean you should add an `errors` parameter as well. But the change overall looks good 👍

**Comment by vsajip** [comment]
Whoops, I made a mistake by doing a rebase - should I just kill this PR and start again?

**Comment by zooba** [comment]
@vsajip Yeah, looks like you undid some other changes, so probably best to restart.

FWIW, once you submit a PR and people start looking it at, you're best to just do regular merges and we'll squash it all at the end. That way you don't break the review workflow.

**Comment by vsajip** [comment]
That's what I normally do, I just had a brain-fade this time :-(

**Pull request closed without merging**
