### PR TITLE
Add UseDisableGil to test build of Windows installer

### PR DESCRIPTION
**Pull request by cartercanedy**

### CODE REVIEW

**Comment by hugovk** [comment]
Please can you include some justification for this change?

**Comment by hugovk** [comment]
And this is shown in the logs:

```
Run pwsh -ExecutionPolicy ByPass -NoLogo -c "$env:UseDisableGil = $true; .\Tools\msi\build.bat --doc -x86"
=: The term '=' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

https://github.com/python/cpython/actions/runs/7586245816/job/20663954126?pr=114320

**Comment by cartercanedy** [comment]
> And this is shown in the logs:
> 
> ```
> Run pwsh -ExecutionPolicy ByPass -NoLogo -c "$env:UseDisableGil = $true; .\Tools\msi\build.bat --doc -x86"
> =: The term '=' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> ```
> 
> https://github.com/python/cpython/actions/runs/7586245816/job/20663954126?pr=114320

Apologies, I was trying to figure out some issues that I was having with the windows msi build on my local machine.

**Comment by cartercanedy** [comment]
I intended to create a pr for my fork, not to upstream

**Pull request closed without merging**
