### PR TITLE
Fix outdated comment in _strptime.py

### PR DESCRIPTION
**Pull request by cool-RR**
Can I please get the tags for skipping bpo and skipping a news item?

Automerge-Triggered-By: @pganssle

### CODE REVIEW

**Comment by cool-RR** [comment]
@taleinat Could you help with the "skip news" and "skip issue" tags?

**Review by taleinat — APPROVED** [review]
LGTM

**Comment by taleinat** [comment]
@cool-RR, please check whether this needs back-porting to 3.8 and 3.7.

**Comment by cool-RR** [comment]
@taleinat LOL, that code is 17 years old. I'm not sure I understand all the criteria for backporting, but as far as I understand, backporting this fix would be valid, though not very important.

**Review by pganssle — APPROVED** [review]
I am indifferent about backporting this. I suppose it depends on what we normally do for inaccurate code comments?

**Pull request merged**
