### PR TITLE
GH-93533: Shrink the `LOAD_ATTR` caches

### PR DESCRIPTION
**Pull request by brandtbucher**
This adds a fixed array of cached methods to the `PyTypeObject` struct. This approach saves memory if there are ~23x more `LOAD_ATTR` sites than there are types.

A size of 16 was chosen because:
- A size of 8 is [1% slower](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230323-3.12.0a6%2B-bde6bec/bm-20230323-linux-x86_64-brandtbucher-type_cache_fixed-3.12.0a6%2B-bde6bec-vs-base.png) and has a [81.0% `LOAD_ATTR` hit rate](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230323-3.12.0a6%2B-bde6bec/bm-20230323-azure-x86_64-brandtbucher-type_cache_fixed-3.12.0a6%2B-bde6bec-pystats.md) on `pyperformance`, with 32.5% of specialization failures due to a too-small cache.
- A size of 16 is [0% faster](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230323-3.12.0a6%2B-212046c/bm-20230323-linux-x86_64-brandtbucher-type_cache_fixed-3.12.0a6%2B-212046c-vs-base.png) and has a [82.2% `LOAD_ATTR` hit rate](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230323-3.12.0a6%2B-212046c/bm-20230323-azure-x86_64-brandtbucher-type_cache_fixed-3.12.0a6%2B-212046c-pystats.md) on `pyperformance`, with 8.7% of specialization failures due to a too-small cache.
- A size of 32 is [0% faster](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230323-3.12.0a6%2B-cc70763/bm-20230323-linux-x86_64-brandtbucher-type_cache_fixed_lar-3.12.0a6%2B-cc70763-vs-base.png) and has a [82.6% `LOAD_ATTR` hit rate](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230323-3.12.0a6%2B-cc70763/bm-20230323-azure-x86_64-brandtbucher-type_cache_fixed_lar-3.12.0a6%2B-cc70763-pystats.md) on `pyperformance`, with 3.3% of specialization failures due to a too-small cache.

A flexible buffer was also considered, but that was [1% slower](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230322-3.12.0a6%2B-c87e8bd/bm-20230322-linux-x86_64-brandtbucher-type_cache-3.12.0a6%2B-c87e8bd-vs-base.png), likely due to the additional indirection and management of the buffer.

* Issue: gh-93533

### CODE REVIEW

**Comment by TeamSpen210** [comment]
So if I'm understanding this correctly, for each class only 16 methods/attributes can be specialised, with everything after just failing? If so 16 seems fairly small, especially for larger libraries/applications. Something like `ndarray` or `flask.Flask` for instance has 50+ methods. I could imagine a larger application using different sets of methods in different areas, filling up the cache. That wouldn't be the sort of thing showing up on benchmarks.

**Comment by brandtbucher** [comment]
> So if I'm understanding this correctly, for each class only 16 methods/attributes can be specialised, with everything after just failing?

Correct (not including instance attributes). I definitely prefer a growable cache to this approach, except that the numbers we have are slower.

I'm also open to using a larger number of entries, like 32 or 64, if others feel similarly.

**Comment by brandtbucher** [comment]
I'm also not sure if this causes problems for interpreter isolation. Maybe putting this sort of state on static built-in types is a bad idea, whether it's resizable or not.

CC @ericsnowcurrently

**Comment by hugovk** [comment]
(Docs now passing now https://github.com/python/cpython/pull/103019 is merged, and updating this with `main`. Thanks for flagging!)

**Comment by markshannon** [comment]
From a correctness point of view, adding the cache for static classes should be fine. All the attributes of superclasses of static classes must also be static.
If they aren't that's a bug, and this isn't the place to fix it.
No harm in adding some asserts, though.

However, we would like static classes to be `const` so that they can be properly shared, which would mean that the cache would need to be pre-populated with all attributes of the class and all its superclasses.
The caches would be a bit big, but not that bad: `len(object.__dict__ | int.__dict__) == 74`; much smaller if we exclude special methods.

**Comment by brandtbucher** [comment]
Closing because of the various issues outlined above.

**Pull request closed without merging**
