### PR TITLE
gh-101100: Fix Py_DEBUG dangling references

### PR DESCRIPTION
**Pull request by smontanaro**
Per conversation with @AlexWaygood, here is a small proposed fix to a few broken Py_DEBUG links. My suggestion was to reference the `_debug-build` anchor. Aside from that, all this does so far is suppress dangling `Py_DEBUG` references in the same paragraphs where the `_debug-build` anchor is referenced.

* Issue: gh-101100

----
📚 Documentation preview 📚: https://cpython-previews--115003.org.readthedocs.build/

### CODE REVIEW

**Comment by AlexWaygood** [comment]
It seems like this PR also includes all the changes from your unrelated other PR:  #114825. Was that intentional? Perhaps you had that branch checked out, instead of your `main` branch, before creating this branch locally? :)

**Comment by smontanaro** [comment]
*sigh* I just branched from my main. Apologies.

Not sure how to proceed at this point.

**Comment by AlexWaygood** [comment]
> _sigh_ I just branched from my main. Apologies.
> 
> Not sure how to proceed at this point.

I fixed things up for you by pushing to your branch (you'll have to `git pull` locally to update your local clone and make further updates locally 🙂).

I don't work much with the C API, so I don't have strong opinions on the C API docs -- it'd be great if @serhiy-storchaka might be able to take a look at this one

**Comment by smontanaro** [comment]
Thanks Alex. I'll review and see what else looks like it needs to be changed.

As an aside, I saw a GitHub Actions warning which was new to me:

Screenshot 2024-02-04 at 1 28 29 PM

Is there maybe a parsing problem in whatever tool is involved in that particular GitHub action?

**Comment by smontanaro** [comment]
Oh, maybe it's complaining about the section below the message, not above it.

**Comment by AlexWaygood** [comment]
> As an aside, I saw a GitHub Actions warning which was new to me:
> Screenshot 2024-02-04 at 1 28 29 PM
> 
> Is there maybe a parsing problem in whatever tool is involved in that particular GitHub action?

That is warning you about a separate dangling reference later on in the same paragraph (line 820). It's fine to leave that reference warning unsolved in this PR. The reason why you're seeing the warning in the "files changed" tab in this PR is because you have made other changes to that paragraph

**Comment by smontanaro** [comment]
> That is warning you about a separate dangling reference later on in the same paragraph (line 820). It's fine to leave that reference warning unsolved in this PR. The reason why you're seeing the warning in the "files changed" tab in this PR is because you have made other changes to that paragraph

Too late. I will revert it if it's a deal breaker, but I see no reason that it needs to actually be documented in Python's documentation.

**Comment by AlexWaygood** [comment]
> Too late. I will revert it if it's a deal breaker, but I see no reason that it needs to actually be documented in Python's documentation.

I don't think it's a deal-breaker :)

**Review by serhiy-storchaka — APPROVED** [review]
It would be nice to add the `Py_DEBUG` macro to the index.

Add the `.. macro:: Py_DEBUG` directive, look what index is generated for it, and add the same index with the `.. index::` directive.

**Comment by smontanaro** [comment]
@serhiy-storchaka I added an explicit `:c:macro: PyDEBUG` target in `intro.rst` and referenced it from `test.rst`. This generates both an anchor for other references and an index entry.

While I was at it, I simplified the text in `test.rst`. Since it already refers the reader to the debug build details in `using/configure.rst`, I saw no reason to actually duplicate the `configure` command example here.

**Review by serhiy-storchaka — APPROVED** [review]

**Review by AlexWaygood — APPROVED** [review]
Looks great!

**Pull request merged**
