### PR TITLE
bpo-9566: Fix some Windows x64 compiler warnings

### PR DESCRIPTION
**Pull request by segevfiner**
I tried to fix the x64 compiler warnings on Windows. Here is a list of the ones I encountered: [python-x64-warnings.txt](https://github.com/python/cpython/files/1113327/python-x64-warnings.txt)

The following remain:
- [x] `LINK : warning LNK4013: image size 0x29B000 exceeds specified maximum 0x200000`
  Caused by externals\tcl-core-8.6.6.0\win\coffbase.txt not giving enough room for an x64 debug build.
  &ndash; "Fixed" by pre-building tcl in [bpo-30916](https://bugs.python.org/issue30916) (https://github.com/python/cpython/pull/2688)
- [x] `..\Modules\gcmodule.c(1085): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data`
  Caused by DTrace stubs being defined as taking `int`. It might be correct to change them to take a larger type since it's possible the real ones take something bigger, but I don't know what the real ones take...
  **EDIT:** The real one takes a long ([Include/pydtrace.d:12](https://github.com/python/cpython/blob/5b4feb7e86ecb813b2c56560f86cda2fd46b9579/Include/pydtrace.d#L12)), which is probably 64-bit on architectures where DTrace is available but it is 32-bit on Windows x64. So just changing the stub to the correct type won't help (Though I think we can simply change the stub to a larger integer type without it causing issues...) It might be possible to redefine the real probe to take a larger integral type (It really needs `Py_ssize_t` but I'm not sure we can use it there. But I'm not familiar with enough...
   &ndash; https://github.com/python/cpython/pull/2852
- [x] `..\Modules\_tracemalloc.c(88): warning C4359: '<unnamed-tag>': Alignment specifier is less than actual alignment (8), and will be ignored.`
  This optimization doesn't really work as is. Need to use [#pragma pack](https://msdn.microsoft.com/en-us/library/2e70t5y1.aspx) instead.
  &ndash; [bpo-31018](http://bugs.python.org/issue31018) (https://github.com/python/cpython/pull/2848)
- [x] `..\Python\getargs.c(2058): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data`
  I'm not sure about this one.
  &ndash; https://github.com/python/cpython/pull/2890
- [ ] `peephole.c warnings`
  They seem to be related to mixing opcode args which are unsigned int with size_t/Py_ssize_t.
- ~~`..\Modules\_ssl.c(2947): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data`
  The Py_buffer can *theoretically* be larger... But I'm not sure that the protocol even supports that...
  Should this be casted away or fixed some other way??~~ &ndash; Split to #2495
- ~~`..\Modules\_ssl.c(4158): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data`
  Someone can *theoretically* pass a buffer big enough... But I doubt such a buffer is going to be written at once...
  Should this be casted away...?~~ &ndash; Split to #2495

cc @zooba

https://bugs.python.org/issue9566

### CODE REVIEW

**Comment by vstinner** [comment]
Oh, this change is big. I will take time to review it. Reviewers must be careful. The goal is not to make warnings quiet, but to make sure that warnings didn't show a real bug.

Can you please revert change son ssl.c and create a dedicated review. Since it's a sensitive module, I would prefer to have more reviewers on this specific file.

**Review by zooba — APPROVED** [review]
Looks good to me, but wait for @haypo to approve too.

**Comment by zooba** [comment]
I merged #2890 because it looked fine. Despite @haypo's request for changes on the SSL one, I think it's alright. The others probably need to be checked by people closer to the modified code (particularly dtrace, though I'm not sure who is the best person there, given it's a non-functional change...)

**Comment by vstinner** [comment]
Sorry, but each time I open this PR, I say "hum, it's too big, I will try to review it next time"... :-p

**Comment by zooba** [comment]
Okay, I reviewed it again and I'm still happy, so I'm going to merge.

**Comment by zooba** [comment]
@segevfiner I think all of your PRs are merged now apart from #2852, right?

**Comment by segevfiner** [comment]
@zooba The ones related to Windows x64 warnings. Yes.

**Pull request merged**
