### PR TITLE
bpo-41199: Docstring convention not followed for dataclasses documentation page

### PR DESCRIPTION
**Pull request by archsyscall**
https://bugs.python.org/issue41199

Automerge-Triggered-By: @ericvsmith

### CODE REVIEW

**Review by ericvsmith — CHANGES_REQUESTED** [review]
I don't think this change is important enough for a News entry. So if you delete that, I'll go ahead and accept the change.

**Review by ericvsmith — APPROVED** [review]
Thanks!

**Comment by marload** [comment]
@ericvsmith 
I deleted NEWS. Actually, I don't know what NEWS file is yet. I wrote this file just because of the failure test.

Could you please tell me what NEWS is?

I've read most of the guides for contribution, but I haven't been to cpython for a long time, so I'm not used to everything yet.

I'm really sorry to bother you. 😢

**Comment by ericvsmith** [comment]
No worries. The News entries are how we keep track of what bugs have been fixed or features have been added. For a change like this, there's no reason to clutter the News entries.

**Comment by marload** [comment]
Thank you for your kind reply.

This PR is my first contribution that merged to cpython/master. 
So thank you more for your answer.

**Comment by ericvsmith** [comment]
Thank you for your contribution!

**Pull request merged**
