### PR TITLE
bpo-39434: Improve float __floordiv__ performance and error message

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue39434

### CODE REVIEW

**Comment by corona10** [comment]
@mdickinson, @vstinner 
If this proposal is accepted, I am going to add news.d since the error message is changed.

**Review by mdickinson — APPROVED** [review]
Neat trick: I was worried about duplicated code (see the issue discussion), but it seems we can rely on the compiler to inline `_float_div_mod` and then strip out the redundant stuff.

LGTM

**Comment by mdickinson** [comment]
Is there benefit to applying the same approach to `float_rem`? Apart from the possibility of a performance boost, it looks as though it would actually make the code simpler (removing existing duplication) and safer. And for floats, `%` is possibly used more often than `//` (for argument reduction, for example).

**Comment by mdickinson** [comment]
> Apart from the possibility of a performance boost,

Sorry, of course that doesn't apply, since `float_rem` is already special-cased and doesn't go via `divmod`.

**Comment by corona10** [comment]
@vstinner @pablogsal If you don't mind can you please take a look? :)

**Comment by mdickinson** [comment]
I've done some manual testing as well as reviewing. Still LGTM.

**Pull request merged**
