### PR TITLE
bpo-44512: Fix handling of extrasactions arg with mixed or upper case

### PR DESCRIPTION
**Pull request by akulakov**
https://bugs.python.org/issue44512

### CODE REVIEW

**Review by MaxwellDupre — APPROVED** [review]
Looks ok.

**Review by iritkatriel — DISMISSED** [review]
This PR has merge conflicts now.

**Comment by akulakov** [comment]
I have made the requested changes; please review again

**Comment by iritkatriel** [comment]
Is this documented as case insensitive?

**Comment by akulakov** [comment]
@iritkatriel it's not documented as case insensitive but it was already being implemented partly as case insensitive, so this PR is to fix the inconsistency in a way that doesn't break valid old code.

**Comment by iritkatriel** [comment]
Got it. Please add a news file.

**Review by iritkatriel — APPROVED** [review]

**Comment by akulakov** [comment]
@iritkatriel thanks for reviewing!

**Pull request merged**
