### PR TITLE
gh-101266: Fix __sizeof__ for subclasses of int

### PR DESCRIPTION
**Pull request by mdickinson**
This PR fixes the behaviour of the `__sizeof__` method (and hence the results returned by `sys.getsizeof`) for subclasses of `int`.

* Issue: gh-101266

### CODE REVIEW

**Comment by mdickinson** [comment]
@ionite34 This should fix the `int` portion of the bug you reported.

@corona10 Do you have enough spare cycles to review?

**Comment by mdickinson** [comment]
Darnit; this fails for `bool`; looks like we'll have to special case in `boolobject.c`. Working on it.

**Comment by mdickinson** [comment]
> this fails for `bool`

That's because we had somewhat bogus numbers for `tp_basicsize` and `tp_itemsize` for the `bool` class. Now fixed.

I'm going to remove the "backport to 3.10" label: the bug does technically still exist in 3.10, but it's messier to fix - it looks like we _would_ need to add a dedicated `__sizeof__` implementation for `bool` in that case, and it doesn't seem worth the effort.

**Comment by corona10** [comment]
> Do you have enough spare cycles to review?

Thanks I will take a look

**Comment by corona10** [comment]
@mdickinson We have to resolve the conflict before reviewing this PR.
Mark Shannon refactored the longobject ;)
https://github.com/python/cpython/commit/c1b1f51cd1632f0b77dacd43092fb44ed5e053a9

**Comment by mdickinson** [comment]
@corona10 

> @mdickinson We have to resolve the conflict before reviewing this PR.

Thanks! Updated.

**Review by corona10 — APPROVED** [review]
lgtm, 

Just one more thing,
Would you like to change the PyBool_Type initialization with C99 style through this chance?

````c

PyTypeObject PyBool_Type = {
    PyVarObject_HEAD_INIT(&PyType_Type, 0)
    "bool",
     .tp_basicsize = offsetof(struct _longobject, long_value.ob_digit),
     .tp_itemsize = sizeof(digit),
     .tp_dealloc = bool_dealloc,
      ...
     .tp_vectorcall = bool_vectorcall
````

**Comment by corona10** [comment]
>  It may make sense to do that in a separate PR,

Great! Feel free to merge anytime you want :)

**Comment by mdickinson** [comment]
Hmm. Looks like I'll need to do a manual cherry-pick backport to 3.11, excluding the last few commits. I'll do that later today.

**Comment by mdickinson** [comment]
See #101579 for a manual backport to 3.11 (cherry-picking the commits up to but excluding the `main` merge).

**Comment by sobolevn** [comment]
This PR was the first one to fail refleak bot (`test_importlib` for some reason): https://buildbot.python.org/all/#/builders/802/builds/582

See https://github.com/python/cpython/issues/101766

**Comment by mdickinson** [comment]
@sobolevn 

Hmm. We could try reverting it in a PR, and then running the refleak buildbots on that PR to see what happens. It seem rather implausible that it was this particular PR that introduced the refleak, though.

**Comment by sobolevn** [comment]
Yes, seems suspicious. I will investigate!

**Pull request merged**
