### PR TITLE
gh-118689: fix ePub build

### PR DESCRIPTION
**Pull request by methane**
* Issue: gh-118689

----
📚 Documentation preview 📚: https://cpython-previews--118690.org.readthedocs.build/

### CODE REVIEW

**Comment by methane** [comment]
glossary.json caused unknown mimetype error. I don't know when this error starts.

#116966 introduced JavaScript in ePub.

#109438 introduced duplicated ToC error.

**Comment by methane** [comment]
With this fix, I can open the epub file with Books.app in macOS.

There are many other errors reported by epubcheck.
Some of them are caused by opengraph.
https://github.com/wpilibsuite/sphinxext-opengraph/pull/120

**Comment by methane** [comment]
Another issue:
https://github.com/readthedocs/sphinx-notfound-page/issues/230

**Comment by methane** [comment]
Remaining errors:

$ epubcheck --locale en-US build/epub/Python.epub 2>python-epub-errors.txt

https://gist.github.com/methane/03a569934bec14a2b4b2a783f96d01b3

**Comment by methane** [comment]
I found epub_use_index option so I use it to disable index.
Index page has been broken from start. When I show index page in Books.app, the app show only erro and I can not use the book.
Since index pages are very inaccessible (no link from toc), no one care it.

**Review by hugovk — APPROVED** [review]
Thank you for the fixes.

> With this fix, I can open the epub file with Books.app in macOS.

Same here 👍 

> There are many other errors reported by epubcheck.

This sounds like something we should aim to add to the CI, even if we start with a subset of passing checks.

Thanks also for opening issues in the extensions.

**Pull request merged**
