### PR TITLE
Remove _bootsubprocess workaround

### PR DESCRIPTION
**Pull request by tiran**
The ``_bootsubprocess`` module was added to solve a bootstrapping issue
with subprocess module on POSIX. The ``_posixsubprocess`` is now a built-in
module and always available in ``setup.py``.

Signed-off-by: Christian Heimes <christian@python.org>

### CODE REVIEW

**Comment by tiran** [comment]
The subprocess module uses select C extension and selector Python module. The math code in selector could be replaced with ``min``, which I would find more readable, too.

**Review by gpshead — APPROVED** [review]

**Comment by vstinner** [comment]
If _posixsubprocess is always available when setup.py is called, I'm fine with removing _bootsubprocess.

If I recall correctly, I wrote _bootsubprocess for AIX. But I forgot about the details :-) It was to be able to use subprocess in distutils, rather than a custom code using fork+exec: subprocess is safer and more reliable.

**Comment by AA-Turner** [comment]
Trigger CLA

**Comment by tiran** [comment]
Closing as wontfix. It's too late to merge the change into 3.11 and we are going to remove ``setup.py`` in 3.12.

**Pull request closed without merging**
