### PR TITLE
bpo-29549: Fixes docstring for str.index

### PR DESCRIPTION
**Pull request by CuriousLearner**
This fixes issue  http://bugs.python.org/issue29549

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by CuriousLearner** [comment]
CLA is signed and now visible in my account.

cc @ncoghlan

**Review by Carreau — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
See my comment on http://bugs.python.org/issue29549#msg288027.

I do not see much sense in this one change. In any case, it will have to be rewritten. This is far from what is required.

**Comment by Mariatta** [comment]
Hi @CuriousLearner . The issue referenced in the BPO is currently assigned to another person. I would suggest that you choose a different issue to work on, one that is not assigned to anyone. 
In case it is assigned, please ask first before starting working on it.
Thanks.

**Comment by CuriousLearner** [comment]
@Mariatta Alright. I apologize for this. I didn't notice this issue was already assigned. Thanks.

**Comment by ncoghlan** [comment]
Added the sprint label, as this PR was submitted at the PyCon Pune 2017 core development sprint.

**Pull request closed without merging**
