### PR TITLE
Interpeter -> Interpreter

### PR DESCRIPTION
**Pull request by sobolevn**
All credit for finding this goes to @PallHaraldsson
This is the re-creation of https://github.com/python/cpython/pull/108625

### CODE REVIEW

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Review by AA-Turner — APPROVED** [review]

**Review by sunmy2019 — APPROVED** [review]

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
Not sure why Eric or Adam didn't merge this ... 😉

**Comment by ericsnowcurrently** [comment]
I forgot @sobolevn isn't a committer. 😄

**Comment by sunmy2019** [comment]
Neither me nor Adam is a committer, all that we can do is to click approve. 😂

**Comment by sobolevn** [comment]
Adam is, congrats 🎉 
https://discuss.python.org/t/vote-to-promote-adam-turner/35269/5

**Pull request merged**
