### PR TITLE
gh-126618: fix repr(itertools.count(sys.maxsize))

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-126618

### CODE REVIEW

**Comment by skirpichev** [comment]
cc @vstinner (as this also include reversion of #126617)

**Review by picnixz — APPROVED** [review]
I assume that you picked up my tests and NEWS entry so it should be fine.

**Comment by skirpichev** [comment]
Yes.  And tests from https://github.com/python/cpython/pull/126617 aren't reverted, of course.

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
@skirpichev @picnixz: Does the 3.12 branch have the bug? If yes, can you propose a backport @skirpichev?

**Comment by picnixz** [comment]
I think so. The reason why I didn't put the 3.12 label before was because my branch used free-threaded special code. This fix is 3.12+ compatible (the fix that was reverted in this PR was backported up to 3.12).

**Comment by skirpichev** [comment]
I'm working on backport.

**Review by Redeyder723 — APPROVED** [review]

**Pull request merged**
