### PR TITLE
bpo-44165: Add tests for sqlite3 SQL string length

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue44165

### CODE REVIEW

**Comment by erlend-aasland** [comment]
This slows down the `sqlite3` tests considerably:

```
# with this PR
$ ./python.exe -m test test_sqlite
0:00:00 load avg: 2.67 Run tests sequentially
0:00:00 load avg: 2.67 [1/1] test_sqlite

== Tests result: SUCCESS ==

1 test OK.

Total duration: 10.6 sec
Tests result: SUCCESS

# without this PR
$ ./python.exe -m test test_sqlite
0:00:00 load avg: 2.14 Run tests sequentially
0:00:00 load avg: 2.14 [1/1] test_sqlite

== Tests result: SUCCESS ==

1 test OK.

Total duration: 1.3 sec
Tests result: SUCCESS

**Comment by erlend-aasland** [comment]
Test time reduced with ~5 seconds after 3687feaa7f38cc0d1134a000747bfe6514091ba2, but it's still a massive slow-down.

**Comment by pablogsal** [comment]
> This slows down the `sqlite3` tests considerably:

Oh :( I thought this was going to be faster. I think that 5 seconds is quite expensive for this check in particular. Unfortunately there is no easy way to go around `PyUnicode_AsUTF8AndSize` even with subclasses. Well, then I assume we would need to proceed without the extra tests. Sorry for the inconvenience

**Comment by erlend-aasland** [comment]
No problem, it was a nice little excercise :) Perhaps we could disable it by default and use some kind of flag to decide if to run it?

**Comment by pablogsal** [comment]
> No problem, it was a nice little excercise :) Perhaps we could disable it by default and use some kind of flag to decide if to run it?

I was thinking about that but given si just checking this code path I am still not super enthusiastic. Normally those kind of test with -u test behaviour

**Pull request closed without merging**
