### PR TITLE
gh-104572: Improve error messages for invalid constructs in PEP 695 contexts

### PR DESCRIPTION
**Pull request by JelleZijlstra**
* Issue: gh-104572

### CODE REVIEW

**Review by terryjreedy — COMMENTED** [review]
I approve of test additions, possible with change, and what to me are close to typo fixes.  Both are routinely backported.

**Comment by AlexWaygood** [comment]
@terryjreedy, PEP 695 was only merged into `main` a few days ago; this PR can't be backported to 3.11

**Review by AlexWaygood — APPROVED** [review]
LGTM

**Review by Eclips4 — APPROVED** [review]
LGTM.
Does it make sense to add a cases with a function definition?
(test_syntax)

**Pull request merged**
