### PR TITLE
bpo-41425: Make tkinter doc example runnable

### PR DESCRIPTION
**Pull request by nerandell**
https://bugs.python.org/issue41425

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@nerandell

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by terryjreedy** [comment]
Ankit: since the code you added was, as requested, copied from another example, I consider it 'trivial' enough to merge without your CLA signature.  If you had changed the comments to conform to PEP-8, with other slight revisions, as I did, the CLA would have been required.  If you intend to ever make another contribution, which I hope you do, please sign the CLA now, if you have not yet, so this will be done before your next PR.

**Comment by terryjreedy** [comment]
I first removed the 3-space .rst indents to test the execution of the revised code.  I then added them back and rebuilt the docs with the windows equivalent of 'make html' to test the html presentation of the code.

**Comment by terryjreedy** [comment]
The change in the last line of the file ("Constants ...") might have been the addition of a final '\n'. as might be done by patchcheck.  There is one now and I don't see any other change.

**Pull request merged**
