### PR TITLE
[doc] Fix padding in some typing definitions

### PR DESCRIPTION
**Pull request by andresdelfino**
Automerge-Triggered-By: @gvanrossum

### CODE REVIEW

**Review by gvanrossum — COMMENTED** [review]
What does this fix?

**Comment by andresdelfino** [comment]
@gvanrossum compare the definition of AbstractSet and ByteString. You'll see how the AbstractSet paragraph has an incorrect padding, because of the additional space in the RST.

**Comment by andresdelfino** [comment]
Check the definition in the actual rendered documentation: https://docs.python.org/3.10/library/typing.html

**Comment by gvanrossum** [comment]
> Check the definition in the actual rendered documentation: https://docs.python.org/3.10/library/typing.html

Gotcha! Now I see. Will land once tests pass.

**Review by gvanrossum — APPROVED** [review]
Thanks!

**Comment by gvanrossum** [comment]
Can you take care of the backport to 3.8? AFAIK these docs are nearly the same on 3.8-3.10, but there are occasional differences that throw off the auto-backport.

**Comment by andresdelfino** [comment]
Sure!

**Comment by andresdelfino** [comment]
@gvanrossum 3.8 doesn't have the problem. I think we can remove the "needs backport to 3.8" label.

**Pull request merged**
