### PR TITLE
[3.7] bpo-34725: Adds _Py_SetProgramFullPath so embedders may override sys.executable (GH-9860)

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue34725

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Why `_Py_SetProgramFullPath`and not `Py_SetProgramFullPath`?

**Comment by zooba** [comment]
Because if someone uses it in 3.7.2, their code won't be compatible with 3.7.1 and earlier, so it shouldn't be a public API. (The use I have planned is internal, but requires the API to be exposed.)

**Comment by serhiy-storchaka** [comment]
Have you planned to use it in CPython or in a tied third-party project?

**Comment by zooba** [comment]
CPython. It's needed for https://bugs.python.org/issue34977, and there's no reason to delay that until 3.8 since it isn't a new platform.

**Pull request merged**
