### PR TITLE
gh-85984: Remove legacy Lib/pty.py code.

### PR DESCRIPTION
**Pull request by 8vasu**
This follows #29658. This is one in a series of PRs aimed at cleaning-up, fixing bugs in, introducing new features in, and updating the code in "Lib/pty.py".

Signed-off-by: Soumendra Ganguly <soumendraganguly@gmail.com>

* Issue: gh-85984

### CODE REVIEW

**Comment by 8vasu** [comment]
@gpshead Please take a look at this when you have time.

Two changes are being made.

1. Remove code for `pty.openpty()` that uses the "old SGI method or the manual BSD open-a-pty code" that was marked as deprecated way back in year 2000 by [Thomas Wouters](https://github.com/python/cpython/commit/8cef4cf737878bd8eec648426eebe9b9019b18be); this includes `pty.master_open()`, `pty._open_terminal()`, and `pty.slave_open()`; these are not even in the `test_pty.py` anymore.

2. Make the fallback code in `pty.fork()` use `os.login_tty()`. Please note that the replacement code in `pty.fork()` is different from the removed code in the following way.
* The removed code is using the legacy `System V` method of `open()`-ing a tty device to make it a controlling terminal;
* The replacement code is using `os.login_tty()`, which uses `login_tty(3)` if available, or else uses the `TIOCSCTTY` `ioctl()`, which even `System V` derivatives support now:  https://marc.info/?l=glibc-help&m=164436296715753&w=3

@asvetlov @ethanfurman @aeros please take a look if you have time as well.

**Review by gpshead — APPROVED** [review]

**Comment by 8vasu** [comment]
@gpshead thank you for the review.

@kumaraditya303 thank you for the review request.

I have many other improvements planned (and to a large extent ready) for this module for which I will make pull requests once this is merged (after December since I am busy applying for postdocs now).

**Comment by smontanaro** [comment]
(I'm working my way through some PRs which have been approved and are labeled "awaiting merge", hence my seemingly bolt from the blue comment. Why? [Read here](https://discuss.python.org/t/prs-awaiting-merge/21313).)

Maybe this didn't get addressed in the sprint? Is it ready to merge or does it need more work? If it needs more work, maybe the ``DO-NOT-MERGE`` label should be added.

**Comment by 8vasu** [comment]
@smontanaro Thank you for the review. This does not need more work unless @gpshead has any suggestions. This is a part of a series of PRs aimed at improving the pty library. A few have been merged before, and if this one gets merged, then I have more to follow, which I will work on right after December (I am still applying for postdocs).

**Comment by 8vasu** [comment]
@gpshead If/when you have time, please let me know if you need me to make any changes to this.

**Review by gpshead — APPROVED** [review]

**Review by gpshead — CHANGES_REQUESTED** [review]
While `master_open()` and `slave_open()` are ancient and undocumented, even way back in 2.7, with "Deprecated" in the docstrings... they do appear in real code:

https://cs.github.com/?scopeName=All+repos&scope=&q=%2F%28pty.slave_open%7Cpty.master_open%29%2F+language%3Apython

So lets not delete those two in 3.12.  Instead have them use warnings.warn(DeprecationWarning, "use os.openpty() instead").
We can remove their implementations in 3.14+.

**Comment by 8vasu** [comment]
I have made the requested changes; please review again.

**Review by gpshead — APPROVED** [review]

**Comment by 8vasu** [comment]
@gpshead Just realized that I had forgotten to add the deprecation warnings.
Thank you for adding them.

**Comment by gpshead** [comment]
Refactored the implementation of `pty.fork` to use `os.login_tty`.

A `DeprecationWarning` is now raised by `pty.master_open()` and `pty.slave_open()`. They were
undocumented and deprecated long long ago in the docstring in favor of `pty.openpty`.

**Pull request merged**
