### PR TITLE
bpo-34677: Change ouput of example code according to task queue event's priorities

### PR DESCRIPTION
**Pull request by miburk**
https://bugs.python.org/issue34677

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by ZackerySpytz** [comment]
Why is issue 36503 linked in the first post?

**Comment by miburk** [comment]
Sorry for the wrong link. Changed it.

**Comment by MakDon** [comment]
As @tirkarthi said in [issue34677](https://bugs.python.org/issue34677), there would be a delay in running each s.enter(), so the 
```
s.enter(5, 2, print_time, argument=('positional',))
s.enter(5, 1, print_time, kwargs={'a': 'keyword'})
```
actually creates 
```
Event(time=1560138148.058157, priority=2, action=<function print_time at 0x1046ef598>, argument=('positional',), kwargs={})
Event(time=1560138148.058175, priority=1, action=<function print_time at 0x1046ef598>, argument=(), kwargs={'a': 'keyword'})
```

Is it an issue that the *priority* of scheduler.enter() is invaild even the *delay* is the same?
Why not just deprecate the argument *priority*?

**Comment by MakDon** [comment]
Hi, @csabella .Is it better to mark the *priority* argument in scheduler.enter() as deprecated and remove it at the next version? Because it almost never vaild for the same *delay* and it would lead to error guiding.
Thanks!

**Comment by MakDon** [comment]
Or we could add a description on the *priority* argument in scheduler.enter() to explain that the delay makes the *priority* hard to come into effect.

**Comment by tirkarthi** [comment]
> Is it better to mark the priority argument in scheduler.enter() as deprecated and remove it at the next version? Because it almost never vaild for the same delay and it would lead to error guiding.

Delay being same is one case and there could be other cases with different values of delay. Adding a `DeprecationWarning` and removing priority doesn't sound like a good idea to me. 

The example is subtle on the difference and I am not sure if it's intentional.

**Comment by MakDon** [comment]
Hi, @serhiy-storchaka . Could you have a look at it? we are not sure if the example is intentional. The example is added at [issue#16641](https://bugs.python.org/issue16641), [commit 238f3cb](c04957bff3a53ba3d051b7c4148a48ec5238f3cb).

**Pull request closed without merging**
