### PR TITLE
Update controlflow.rst

### PR DESCRIPTION
**Pull request by slackuj**
f100 doesn't writes the result.We need to use print(f100) to write the result.

----
📚 Documentation preview 📚: https://cpython-previews--125036.org.readthedocs.build/

### CODE REVIEW

**Comment by skirpichev** [comment]
> f100 doesn't writes the result.

Why do you think so?!  You should run examples in the interactive interpreter.

```pycon
>>> def fib2(n):
...     result = []
...     a, b = 0, 1
...     while a < n:
...         result.append(a)
...         a, b = b, a+b
...     return result
...     
>>> f100 = fib2(100)
>>> f100
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
```

**Comment by skirpichev** [comment]
@slackuj, I would suggest you next time - first ask for help in https://discuss.python.org/c/help/7.  Just in case you miss something.

Of course if you are absolutely sure that have found a bug, feel free to report it here: https://github.com/python/cpython/issues

**Comment by slackuj** [comment]
> > f100 doesn't writes the result.
> 
> Why do you think so?! You should run examples in the interactive interpreter.
> 
> ```
> >>> def fib2(n):
> ...     result = []
> ...     a, b = 0, 1
> ...     while a < n:
> ...         result.append(a)
> ...         a, b = b, a+b
> ...     return result
> ...     
> >>> f100 = fib2(100)
> >>> f100
> [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
> ```

Sorry, I was not using the interactive interpreter!? .

**Comment by skirpichev** [comment]
It happens.

Keep in mind, that error in the CPython Tutorial - a very severe issue.  That's why it's a good idea - first ask for help in forum.

**Pull request closed without merging**
