### PR TITLE
gh-103053: Fix make check-clean-src: check "python" program

### PR DESCRIPTION
**Pull request by vstinner**
"make check-clean-src" now also checks if the "python" program is found in the source directory: fail with an error if it does exist.

* Issue: gh-103053

### CODE REVIEW

**Comment by vstinner** [comment]
cc @erlend-aasland: Another build fix ;-)

**Comment by erlend-aasland** [comment]
> cc @erlend-aasland: Another build fix ;-)

Seems this fix broke some build bots ;)

**Comment by vstinner** [comment]
> Seems this fix broke some build bots ;)

Nah, it didn't break buildbots, it just made a bug more visible :-) My following change is the real fix for test_freeze: PR #110451. It runs ``make distclean`` instead of ``make clean``. I'm not sure why ``make clean`` doesn't remove ``python`` which was created by ``make``! Maybe it's just more convenient like that.

**Comment by vstinner** [comment]
> Nah, it didn't break buildbots, it just made a bug more visible :-) My following change is the real fix for test_freeze: PR https://github.com/python/cpython/pull/110451.

This following change fixed all buildbots. If I knew that it would be break something, I would do the two changes in the opposite order.

**Comment by erlend-aasland** [comment]
Great! Thanks :)

**Pull request merged**
