### PR TITLE
gh-89022: Improve sqlite3 exceptions related to binding params and API misuse

### LINKED ISSUE #89022: Improve some sqlite3 errors
BPO | [44859](https://bugs.python.org/issue44859)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @JelleZijlstra, @erlend-aasland
PRs | <li>python/cpython#27654</li><li>python/cpython#27695</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-07.14:14:16.688>
labels = ['extension-modules', '3.11']
title = 'Improve some sqlite3 errors'
updated_at = <Date 2022-03-17.05:58:28.684>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-17.05:58:28.684>
actor = 'JelleZijlstra'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2021-08-07.14:14:16.688>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 44859
keywords = ['patch']
message_count = 8.0
messages = ['399183', '399185', '399187', '399211', '399241', '399289', '399441', '415388']
nosy_count = 4.0
nosy_names = ['berker.peksag', 'serhiy.storchaka', 'JelleZijlstra', 'erlendaasland']
pr_nums = ['27654', '27695']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44859'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by erlend-aasland**
- Map SQLITE_MISUSE to InterfaceError instead of ProgrammingError
- Raise more accurate exceptions when binding parameters fail

Fixes gh-89022

### CODE REVIEW

**Comment by erlend-aasland** [comment]
See also https://sqlite.org/rescode.html#misuse

**Comment by erlend-aasland** [comment]
Example of snippets with improved messages; this PR compared to latest official 3.11 release:

Limiting the length of string literals:
```py3
import sqlite3
cx = sqlite3.connect(":memory:")
cx.set_trace_callback(print)
cx.setlimit(sqlite3.SQLITE_LIMIT_LENGTH, 7)
cx.execute("select ?", ("a"*10,))
```

```console
$ python3.11 lim.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/lim.py", line 5, in <module>
    cx.execute("select ?", ("a"*10,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
$ ./python.exe lim.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/lim.py", line 5, in <module>
    cx.execute("select ?", ("a"*10,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.DataError: string or blob too big
```

Trying to bind to an unsupported type (note, SQLite parameters are 1-indexed, not 0-indexed):
```py3
import sqlite3
cx = sqlite3.connect(":memory:")
val = dict()
cx.execute("select ?", (val,))
```

```console
$ python3.11 type.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/type.py", line 4, in <module>
    cx.execute("select ?", (val,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
$ ./python.exe type.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/type.py", line 4, in <module>
    cx.execute("select ?", (val,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Error binding parameter 1: type 'dict' in not supported
```

**Comment by erlend-aasland** [comment]
Example of snippets with improved messages; this PR compared to latest official 3.11 release:

Limiting the length of string literals:
```py3
import sqlite3
cx = sqlite3.connect(":memory:")
cx.set_trace_callback(print)
cx.setlimit(sqlite3.SQLITE_LIMIT_LENGTH, 7)
cx.execute("select ?", ("a"*10,))
```

```console
$ python3.11 lim.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/lim.py", line 5, in <module>
    cx.execute("select ?", ("a"*10,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
$ ./python.exe lim.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/lim.py", line 5, in <module>
    cx.execute("select ?", ("a"*10,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.DataError: string or blob too big
```

Trying to bind to an unsupported type (note, SQLite parameters are 1-indexed, not 0-indexed):
```py3
import sqlite3
cx = sqlite3.connect(":memory:")
val = dict()
cx.execute("select ?", (val,))
```

```console
$ python3.11 type.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/type.py", line 4, in <module>
    cx.execute("select ?", (val,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
$ ./python.exe type.py 
Traceback (most recent call last):
  File "/Users/erlendaasland/src/cpython-build/type.py", line 4, in <module>
    cx.execute("select ?", (val,))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Error binding parameter 1: type 'dict' in not supported
```

**Review by JelleZijlstra — APPROVED** [review]
This makes sense to me when comparing with https://peps.python.org/pep-0249/#exceptions

**Comment by malemburg** [comment]
Hi Erlend, the explicit exception changes look fine to me, since anything that a programmer using the module can potentially do wrong in terms of e.g. passing wrong number of parameters, using binding parameters where they are not allowed, etc. should result in a ProgrammingError.

I'm not sure about the SQLITE_MISUSE, though, since the SQLite docs are rather unspecific on what exactly can cause such an error. The one example they give (using a [prepared statement](https://sqlite.org/c3ref/stmt.html) after that prepared statement has been [finalized](https://sqlite.org/c3ref/finalize.html)) does point to an error which originates in the API itself rather than an error caused by the programmer using the API, so InterfaceError sounds correct.

In mxODBC, I use InterfaceError for e.g. using invalid attribute values passed to an ODBC API, or invalid lengths, options, invalid cursor state, etc. I.e. things where mxODBC itself would be doing something wrong, not necessarily the programmer. Sometimes the distinction is not a very clear one, though, so I wouldn't call the mapping I'm using the only correct one.

**Review by malemburg — APPROVED** [review]
LGTM, modulo the comments I made on the PR.

**Comment by malemburg** [comment]
> LGTM, modulo the comments I made on the PR.

Strange, I clicked on the "Add your review" button and approved the changes, but the bar at the top of the PR still says that Github is waiting for a review.

**Comment by erlend-aasland** [comment]
> I'm not sure about the SQLITE_MISUSE, though, since the SQLite docs are rather unspecific on what exactly can cause such an error. The one example they give (using a [prepared statement](https://sqlite.org/c3ref/stmt.html) after that prepared statement has been [finalized](https://sqlite.org/c3ref/finalize.html)) does point to an error which originates in the API itself rather than an error caused by the programmer using the API, so InterfaceError sounds correct.

Yes, the example you point to is definitely an InterfaceError. Also note this sentence, quoted from the SQLITE_MISUSE docs:

> If SQLite ever returns SQLITE_MISUSE from any interface, that means that the application is incorrectly coded and needs to be fixed. Do not ship an application that sometimes returns SQLITE_MISUSE from a standard SQLite interface because that application contains potentially serious bugs.

I think this justifies mapping SQLITE_MISUSE to InterfaceError.

> In mxODBC, I use InterfaceError for e.g. using invalid attribute values passed to an ODBC API, or invalid lengths, options, invalid cursor state, etc. I.e. things where mxODBC itself would be doing something wrong, not necessarily the programmer.

Exactly; this is also my understanding of InterfaceError.

Thanks for reviewing, and thanks for your input; highly appreciated.

**Comment by erlend-aasland** [comment]
> Strange, I clicked on the "Add your review" button and approved the changes, but the bar at the top of the PR still says that Github is waiting for a review.

Looks like GitHub forked you! :)
Screenshot 2022-05-03 at 13 46 17

**Comment by erlend-aasland** [comment]
FYI, I've resolved the conflicting files, so this is ready to land when the CI finishes.

**Comment by JelleZijlstra** [comment]
Windows x64 was stuck, I restarted it.

**Pull request merged**
