### PR TITLE
gh-119205: Fix autocompletion bug in new repl

### PR DESCRIPTION
**Pull request by koxudaxi**
If the interpreter shows a warning, the new repl prompt cursor moves after the warning.

* Issue: gh-119205

### CODE REVIEW

**Comment by lysnikolaou** [comment]
@koxudaxi Can you please rebase onto main and move the tests to the newly created `test_pyrepl` directory?

**Review by lysnikolaou — APPROVED** [review]
LGTM! 🎉

**Comment by koxudaxi** [comment]
@ambv @lysnikolaou 
Thank you for reviewing and rebasing my PR.
I apologize I was moving to Pittsburgh airport from the conference center.

**Comment by ambv** [comment]
@koxudaxi let the tests complete, don't rebase until there are conflicts.

**Comment by ambv** [comment]
The buildbot failure is an unrelated timeout:
```
command timed out: 1800 seconds without output running [b'make', b'buildbottest', b'TESTOPTS=-j2 --junit-xml test-results.xml ${BUILDBOT_TESTOPTS}', b'TESTPYTHONOPTS=', b'TESTTIMEOUT=1200'], attempting to kill
```

**Pull request merged**
