### PR TITLE
Remove duplicate versionadded

### PR DESCRIPTION
**Pull request by hongshaoyang**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@hongshaoyang

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by gvanrossum** [comment]
Those are not duplicate -- several features really was added twice to two different bugfix releases.

**Comment by hongshaoyang** [comment]
For features with multiple `versionadded`'s, would it help to specify what was added in that version? To me the docs look slightly confusing currently.

Screenshot 2021-07-03 at 12 34 18 PM

**Comment by gvanrossum** [comment]
When it says "New in version X" under the description of a class, function etc., it means that that thing was introduced in that version and wasn't present in the previous versions. So for these examples, these were not present in 3.5.3 or 3.6.0.

Maybe it helps you understand to know that "minor" versions (3.5, 3.6 etc.) are descendents/ancestors of each other, but "bugfix" versions (3.5.4, 3.6.1 etc.) are descendants of the previous bugfix version? E.g. 3.6.1 is a descendant of 3.6.0, i.e. 3.6.

**Comment by hongshaoyang** [comment]
Thank you for the detailed explanation.

**Pull request closed without merging**
