### PR TITLE
bpo-34204: Use pickle.DEFAULT_PROTOCOL in shelve

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Use pickle.DEFAULT_PROTOCOL (currently 5) in shelve instead of a
hardcoded 3.

https://bugs.python.org/issue34204

Automerge-Triggered-By: GH:csabella

### CODE REVIEW

**Review by corona10 — APPROVED** [review]

**Review by corona10 — COMMENTED** [review]
Would you like to add NEWS on what's new?
It looks like noticiable changing for user.

**Comment by vstinner** [comment]
>@vstinner Do you have any ideas?

I would prefer to get the approval of @pitrou or @applio on such change. pickle can be used to share data between different Python versions. I'm not sure about the backward compatibility here.

**Comment by pitrou** [comment]
I don't think this is ok to change. cc @rhettinger

**Review by rhettinger — APPROVED** [review]

**Comment by vstinner** [comment]
Oh sorry, I misunderstood the PR. I read that it changes the default pickle version in multiprocessing (oops), but it's about the shelve module :-)

**Comment by csabella** [comment]
@corona10 @vstinner @pitrou @applio There are two approvals on this PR, but I'm not sure if there's consensus.  Does it need more discussion on the bug tracker or should it be merged?

**Comment by corona10** [comment]
@csabella 
> Does it need more discussion on the bug tracker 

IMHO, we need more discussion.

**Review by vstinner — APPROVED** [review]
LGTM if the PR is updated for Python 3.10 (right now, it says "new in 3.9").

Sorry, first I read that this PR was for multiprocessing... For shelve, IMO it's reaonsable to use the latest pickle version. The main drawback is that shelve files created by Python 3.10 can no longer be read by  Python 3.7 and older: protocol 5 was introduced in Python 3.8.
https://docs.python.org/dev/library/pickle.html#data-stream-format

IMHO it's a reasonable limitation. Also, it's well documented that the pickle protocol can easily controlled by the protocol parameter of shelve.open():
https://docs.python.org/dev/library/shelve.html#shelve.open

@pitrou @corona10: What do you think?

**Comment by vstinner** [comment]
Oh, @serhiy-storchaka created https://bugs.python.org/issue34204 so it would be nice to also hear @serhiy-storchaka on this PR :-)

**Comment by serhiy-storchaka** [comment]
We can also use just `None` instead of `pickle.DEFAULT_PROTOCOL`.

**Comment by vstinner** [comment]
> We can also use just None instead of pickle.DEFAULT_PROTOCOL.

I prefer to have `s._protocol = pickle.DEFAULT_PROTOCOL` than `s._protocol = None`, it's more explicit.

**Comment by pitrou** [comment]
> Also, it's well documented that the pickle protocol can easily controlled by the protocol parameter of shelve.open()

Yes, so if it's well documented, what's the point of changing the default and breaking compatibility?

**Comment by vstinner** [comment]
Hum, I measured the file disk depending on the pickle protocol. The efficiency depends on values: https://bugs.python.org/issue34204

**Comment by marco-c** [comment]
@ZackerySpytz are you going to update the PR?
I have opened a new issue and PR as I didn't notice this, I will close my PR if you are planning on updating yours.

**Comment by marco-c** [comment]
My PR to fix the same issue is #22751.

**Comment by ZackerySpytz** [comment]
I have just pushed an update.

**Comment by marco-c** [comment]
> I have just pushed an update.

Thanks, I'll close mine then!

**Pull request merged**
