### PR TITLE
gh-110397: Add Py_IsFinalizing() to the stable ABI

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-110397

----
:books: Documentation preview :books:: https://cpython-previews--110441.org.readthedocs.build/

### CODE REVIEW

**Comment by vstinner** [comment]
@ericsnowcurrently @serhiy-storchaka: @wjakob explains that reimplementing this function with the existing limited C API is likely to crash if calling during or after Python finalization. See: https://github.com/python/cpython/issues/110397#issuecomment-1749624289 Would you be ok to add Py_IsFinalizing() directly to the limited C API version 3.13, knowing that this function was added to Python 3.13?

This Py_IsFinalizing() function looks special and it's hard to workaround the lack of this API with the stable ABI.

**Comment by erlend-aasland** [comment]
I'm fine with adding it to the Stable ABI, FWIW.

**Review by erlend-aasland — APPROVED** [review]

**Comment by ericsnowcurrently** [comment]
FWIW, before we add the function to the stable ABI, it may be worth being clear about what "finalizing" means here.  Consequently, we should consider actually making the `Py_IsFinalizing()` behavior match its name or change the name.

I've written up my thoughts in detail in gh-110490.

I realize that the stable ABI (and limited API) are specifically focused on memory layout, function signatures, and symbols (so it isn't critical if we change behavior later).  Yet, there is also an implication of semantic stability (within reason) that we should avoid setting ourselves up to later break with this function.  On the other hand, a different name might make sense, so we should avoid locking the symbol into the ABI prematurely.

**Comment by vstinner** [comment]
> FWIW, before we add the function to the stable ABI, it may be worth being clear about what "finalizing" means here.

This API is just the same as `sys.is_finalizing()` which is already part of the "stable" Python API.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by vstinner** [comment]
@ericsnowcurrently: I merged this PR since I'm feeling responsible of breaking applications relying on Python 3.12 private _Py_IsFinalizing() API. This C API exposes Python ``sys.is_finalizing()`` API which exists since Python 3.5.

For sure, there is always room for enhancement. It's a very complex topic, I wrote articles about it and I'm keeping notes about it: [Python Finalization](https://pythondev.readthedocs.io/finalization.html).

While it's possible to enhance the API, make finalization more reliable, reduce the risk of crashes, IMO we need "something" for people who are already affected by known issues. @wjakob elaborated issues that this API is solving in https://github.com/python/cpython/issues/110397#issuecomment-1749624289 and just for that, I think that such API is worth it.

Python 3.13 didn't get an alpha1 release. We still have time until October 2024 to refine the documentation, the function name, come with a better API, etc. There is a non-zero risk that we will keep the name and so we will be good :-)

**Pull request merged**
