### PR TITLE
bpo-40471: Fix grammar typo in 'issubclass' docstring

### PR DESCRIPTION
**Pull request by alexpovel**
Just a brief grammar fix.

See also <https://bugs.python.org/issue40471>.

https://bugs.python.org/issue40471

Automerge-Triggered-By: @orsenthil

### CODE REVIEW

**Review by remilapeyre — COMMENTED** [review]
Thanks for making the change @alexpovel !

While we are fixing this docstring, maybe we should change 

> This is equivalent to ``issubclass(x, A) or issubclass(x, B)
or ...`` etc.

to 

> This is equivalent to ``issubclass(x, A) or issubclass(x, B)
or ...``.

as it looks to me like `...` and `etc` are redundant.

**Comment by alexpovel** [comment]
@remilapeyre , what do you think about

> A tuple, as in ``issubclass(x, (A, B, ...))``, may be given as the target to
check against. This is equivalent to ``issubclass(x, A) or issubclass(x, B)
or issubclass(x, ...)`` etc.

This seems to read fluently and be in line with the previous sentence.

Otherwise, I agree with you and will update the PR with your suggestion.

**Comment by remilapeyre** [comment]
Not sure about the wording with `...` in the call to `issubclass()` as the part that gets repeated is the whole `issubclass(x, A)`, not just the arguments.

**Comment by alexpovel** [comment]
Okay! The PR is updated according to your original suggestion.

**Review by remilapeyre — APPROVED** [review]
Thanks @alexpovel, looks great!

**Review by rhettinger — APPROVED** [review]

**Review by corona10 — COMMENTED** [review]
@alexpovel 

Sorry for the delayed.
Please rebase your PR to solve the conflict :)

**Comment by alexpovel** [comment]
@corona10 Done!

**Review by orsenthil — APPROVED** [review]

**Comment by orsenthil** [comment]
The fix can be ported to other maintained versions of python (3.9, 3.8, 3.7). It looks like automated backport failed. 

@alexpovel ,  would you like to create backport PRs as suggested by the bot?

**Pull request merged**
