### PR TITLE
Add support for Yandex Browser

### PR DESCRIPTION
**Pull request by nagayev**
Hello!
In CIS countries alot of people use Yandex browser by Russian Yandex company.
This browser is Chromium based browser and so it's easy to implement Yandex's browser support.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by Mariatta** [comment]
Hi this is in fact new feature, and requires an issue, and news entry.

**Review by auvipy — APPROVED** [review]

**Comment by asvetlov** [comment]
I don't follow how the PR adds a support for yandex browser?
Should `yandex` be handled by `register_X_browser()` as we do it for `chromium` and `chromium-browser`?

**Comment by serhiy-storchaka** [comment]
Changes other than trivial (like fixing a type) needs opening an issue on the bug tracker.

Also, I do think that this PR does anything useful. It just adds unused private variable.

Also, I do not think that Yandex Browser needs special support in the webbrowser module. It is just one of tens or hundreds custom builds of Chrome. The are more popular browsers. No code is needed for supporting it, you just specify it as system browser or as user default browser by configuring Windows registry or setting an environment variable.

**Pull request closed without merging**
