### PR TITLE
bpo-31191: Fix grammar in threading.Barrier docs

### PR DESCRIPTION
**Pull request by schedutron**
https://bugs.python.org/issue31191

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by rhettinger — APPROVED** [review]

**Comment by JulienPalard** [comment]
@schedutron Thanks for your contribution!

This paragraph, and the whole documentation, are line-wrapped at the 80th column, would you please wrap your modification at the 80th too?

c.f.: https://devguide.python.org/documenting/?highlight=documentation#style-guide

**Comment by schedutron** [comment]
I care about PEP8 while programming still I missed this text wrapping! Anyways, thanks @JulienPalard, I've implemented the wrapping now.

**Comment by JulienPalard** [comment]
LGTM

**Comment by schedutron** [comment]
I think I've signed the CLA, still the tag persists.

**Comment by JulienPalard** [comment]
@schedutron yes, removing the tag is not automatic, see: https://github.com/python/the-knights-who-say-ni/issues/110

**Comment by schedutron** [comment]
@the-knights-who-say-ni I've signed the CLA.

**Comment by Mariatta** [comment]
Thanks for the reviews @rhettinger and @JulienPalard 

@schedutron, You submitted the CLA two days ago, which was a weekend day in the US.
[DevGuide](https://devguide.python.org/pullrequest/#licensing) explains that it can take one US business day to process the CLA. Thanks for the patience.

**Comment by Mariatta** [comment]
Thanks @schedutron and congrats on your first contribution to CPython :taco:

**Pull request merged**
