### PR TITLE
Upload NEWS file as artifact

### LINKED ISSUE #147: Run blurb as part of Travis
Maybe as part of the doc build we run `blurb merge` or `blurb release` to verify all news entries render appropriately?

@larryhastings

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/python/core-workflow/issues/147.

Since that issue was opened, we've moved testing from Travis CI to GitHub Actions.

And more recently the blurb tool is now being as part of `make build` called as part of `make ... doctest` in the "Check documentation" step (https://github.com/python/cpython/pull/30009).

So let's also upload the generated `NEWS` file as an artifact so it can be inspected after the build.

For example, it's available to download here:

* https://github.com/hugovk/cpython/actions/runs/1657861881

### CODE REVIEW

**Review by sumeshir26 — APPROVED** [review]

**Review by erlend-aasland — APPROVED** [review]
Neat!

**Comment by hugovk** [comment]
Conflict resolved!

Would be nice to get this merged, it'd make reviewing docs PRs much easier: can download the generated files rather than checking out the branch locally and building them manually.

**Comment by hugovk** [comment]
Conflict resolved!

**Review by merwok — APPROVED** [review]

**Review by brettcannon — APPROVED** [review]

**Comment by smontanaro** [comment]
(I'm working my way through some PRs which have been approved and are labeled "awaiting merge", hence my seemingly bolt from the blue comment. Why? [Read here](https://discuss.python.org/t/prs-awaiting-merge/21313).)

Can this be merged or are you still waiting for @Mariatta and @ezio-melotti to review?

**Review by ezio-melotti — COMMENTED** [review]
Do we know how much storage is the `python` org using?
I don't expect the `NEWS` file to be particularly large, but if it gets generated for each PR it will add up and we might eventually reach the limit.  We can also tweak the number of day the artifact is stored before being automatically deleted.

Other than that, the PR LGTM.

**Comment by hugovk** [comment]
The current usage will be visible under https://github.com/organizations/python/settings/billing for org admins.

**Comment by hugovk** [comment]
Also the NEWS file is only 2% the size of the docs artifact we've been uploading for a long time and apparently that's not been a problem.

image

**Review by ezio-melotti — APPROVED** [review]
In that case I guess it's not a problem.  FWIW the artifact retention period is currently set at 90 days.  We can lower it if space becomes a problem.

**Pull request merged**
