### PR TITLE
bpo-37032: Add CodeType.replace() method

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue37032

### CODE REVIEW

**Comment by vstinner** [comment]
The docstring shows default values whereas... there are no default values. I'm not sure how to fix the Argument Clinic part. @serhiy-storchaka: any idea?

```
replace(self, /, *, co_argcount=-1, co_posonlyargcount=-1, co_kwonlyargcount=-1,
  co_nlocals=-1, co_stacksize=-1, co_flags=-1, co_firstlineno=-1, co_code=None,
  co_consts=None, co_names=None, co_varnames=None, co_freevars=None,
  co_cellvars=None, co_filename=None, co_name=None, co_lnotab=None)
    Return a new code object with new specified fields.
```

**Review by isidentical — APPROVED** [review]

**Comment by pablogsal** [comment]
>The docstring shows default values whereas... there are no default values. I'm not sure how to fix the Argument Clinic part. @serhiy-storchaka: any idea?

I don't know if is possible to eliminate the defaults but if you want all to display `None` you can use something like:

```
Py_ssize_t(accept={int, NoneType}, c_default="self->the_argument") = None
```

**Review by pablogsal — APPROVED** [review]
LGTM

I left a comment on a possible way to have al defaults to None

**Comment by vstinner** [comment]
> Py_ssize_t(accept={int, NoneType}, c_default="self->the_argument") = None

I expect that "code.replace(co_argcount=None)" raises a TypeError, since None is an invalid value. Moreover, Py_ssize_t requires to manually downcast to int... I prefer to keep "=-1" for int parameters and "=None" for other types.

I will go with the current implementation ;-)

**Comment by serhiy-storchaka** [comment]
> I'm not sure how to fix the Argument Clinic part.

Currently it is not possible.

**Comment by pitrou** [comment]
@pierreglaser @ogrisel You may like this change.

**Comment by asottile** [comment]
Is there a place where this can be documented? I had to find this PR to see how to use this function

**Comment by haiden77** [comment]
no

**Comment by vstinner** [comment]
> Is there a place where this can be documented? I had to find this PR to see how to use this function

CodeType is only documented at:
https://docs.python.org/dev/library/types.html#types.CodeType

The replace() method can be documented there.

**Comment by asottile** [comment]
I'm a little slow on the draw here, but I wrote up a PR to document this: #17776

**Pull request merged**
