### PR TITLE
gh-97930: Apply changes from importlib_resources 5.12.

### PR DESCRIPTION
**Pull request by jaraco**
* Issue: gh-97930

### CODE REVIEW

**Review by warsaw — APPROVED** [review]

**Review by FFY00 — APPROVED** [review]

**Comment by jaraco** [comment]
Those test failures are interesting. They certainly seem related to the changes. But that doesn't explain why the tests pass for me locally or why they pass in importlib_resources. I'll continue to investigate.

**Comment by jaraco** [comment]
Aah. The issue was that new files were added but not included in the commit (the usual foot gun aka git). I probably wouldn't have encountered that error had I been using [jj](/martinvonz/jj).

**Comment by jaraco** [comment]
The remaining test is failing for unrelated reasons. Merging. Thanks for the review!

**Comment by jaraco** [comment]
I suspect the buildbot failures are due to missing directory declarations. Will investigate.

**Pull request merged**
