### PR TITLE
Reword docs to avoid saying things that aren't accurate

### PR DESCRIPTION
**Pull request by Rosuav**

### CODE REVIEW

**Comment by Rosuav** [comment]
(Trivial)

**Comment by wm75** [comment]
Compare to https://docs.python.org/3/tutorial/controlflow.html#the-range-function, which has the same problem. PR #273 proposes to change this section, but leaves the range is a function part unaltered. It introduces the returned object as an iterable instead of a sequence and, of course, either is correct.

**Comment by rhettinger** [comment]
Sorry, but I don't see any improvement here.

**Comment by Rosuav** [comment]
Fine, whatevs. I opened the PR in direct response to someone who was asking about how come range() wasn't behaving like an iterator, so there definitely is some inaccuracy and some confusion.

**Pull request closed without merging**
