### PR TITLE
gh-85046: Add EHWPOISON error code

### PR DESCRIPTION
**Pull request by rruuaanng**
* Issue: gh-85046

----
📚 Documentation preview 📚: https://cpython-previews--126397.org.readthedocs.build/

https://man7.org/linux/man-pages/man3/errno.3.html
The errno module is quite complete, but it lacks this EHWPOISON.

### CODE REVIEW

**Comment by rruuaanng** [comment]
And some error codes are missing in the document. I'll finish them tomorrow.

**Comment by ZeroIntensity** [comment]
@rruuaanng Please don't edit out the `Issue: ` section that the bot adds.

**Comment by rruuaanng** [comment]
Sorry, I didn't seem to pay attention.

**Comment by erlend-aasland** [comment]
> Sorry, I didn't seem to pay attention.

You've been told **multiple times** to read the devguide; _please pay attention and do so_. It is clear from your pattern of behaviour that you do not have a clear concept of our development workflow. Please focus on the first section, _Getting Started_.

https://devguide.python.org

**Comment by erlend-aasland** [comment]
> And some error codes are missing in the document. I'll finish them tomorrow.

This is why you should _test your changes locally before creating a PR_. Please read the devguide.

**Comment by rruuaanng** [comment]
> > And some error codes are missing in the document. I'll finish them tomorrow.
> 
> 
> 
> This is why you should _test your changes locally before creating a PR_. Please read the devguide.

It refers to my other PR.

**Comment by rruuaanng** [comment]
> > Sorry, I didn't seem to pay attention.
> 
> 
> 
> You've been told **multiple times** to read the devguide; _please pay attention and do so_. It is clear from your pattern of behaviour that you do not have a clear concept of our development workflow. Please focus on the first section, _Getting Started_.
> 
> 
> 
> https://devguide.python.org

I know, but I didn't pay attention when editing.

**Comment by erlend-aasland** [comment]
Please add this change to #126420.

**Comment by rruuaanng** [comment]
> Please add this change to #126420.

No problem. I think it might be better this way.

**Comment by erlend-aasland** [comment]
> Please add this change to #126420.

Ah, this actually adds a new constant. Then it does not belong to the _**documentation**_ issue you've linked this to. Please see if there is an open issue; if not, create an issue for this.

**Comment by rruuaanng** [comment]
> > Please add this change to #126420.
> 
> 
> 
> Ah, this actually adds a new constant. Then it does not belong to the _**documentation**_ issue you've linked this to. Please see if there is an open issue; if not, create an issue for this.

It's issue is what the PR title point to. If you don't mind, you can help me reopen this PR first and then let me do other work :)

**Comment by erlend-aasland** [comment]
No, it is not. The issue is about missing documentation, not missing code. There is a big difference! Missing documentation would be a bug in the documentation, so any linked PRs would be backported to all supported branches. On the other side, missing error codes are _new features_; they cannot be backported! Please understand this. This is explained in the devguide; **_please read it_**!

Please do not reopen this PR; _focus only on your existing PRs before opening **any** new PR at all_.

**Comment by rruuaanng** [comment]
Oh, I apologize. My thought is that new content should be reviewed separately from documentation changes. Thank you for your attention to this!

**Comment by erlend-aasland** [comment]
> My thought is that new content should be reviewed separately from documentation changes. Thank you for your attention to this!

That is a correct assumption, but they are (mostly) also separated by issue. The general idea is that you should think of [issues](https://devguide.python.org/triage/issue-tracker/#reporting-an-issue) like you would think of [Good Commits](https://devguide.python.org/getting-started/pull-request-lifecycle/#making-good-commits) (devguide-link; please read it!): don't mix features and bug-fixes in the same issue (and definitely not in a commit).

Again, I urge you to focus only on your currently open PRs. Try not to lose focus by opening new PRs/issues nor by reviewing other work. I think you will learn more and be more successful by being more focused (and I also think this will greatly reduce reviewer friction). Please consider my advice.

**Comment by rruuaanng** [comment]
Erlend, thank you so much. It seems like most of my PRs have been reviewed by you. I know you've mentioned these points many times, and I apologize for that. I really have been reading the development guidelines, but sometimes I might not notice when I violate them, which stems from my mindset being stuck in another development mode (in fact, I didn't even know what CI was at first). If I violate the development rules again while working on other PRs, I hope you can remind me! In the future, I will focus on completing the PRs I open, and although I may spend some time helping others or reviewing, it won't detract from my commitment to my own PRs. Thank you for taking the time to guide me. I really appreciate it!

**Comment by erlend-aasland** [comment]
> I really have been reading the development guidelines, but sometimes I might not notice when I violate them, which stems from my mindset being stuck in another development mode [...]

This is why I'm suggesting that you focus on your open PRs. You will learn better by focusing your efforts. Remember also that landing a PR can be time-consuming. It may take several months in some cases! Also remember that it is ok for PRs to be rejected; that happens all the time, so do not take it personally.

> [...] although I may spend some time helping others or reviewing, it won't detract from my commitment to my own PRs [...]

I will advice you again from doing this; after resolving your open PRs, you can try again to perform a couple of reviews, but I would rather not encourage you to learn these two development workflows at the same time. Please consider my advice.

> If I violate the development rules again while working on other PRs, I hope you can remind me!

It is ok to forget things, especially for early contributors, but the repeated patterns of not following our development workflow indicates that more time needs to be spent with the devguide before continuing your contributions. This is perfectly fine. I do not expect you to know the entire devguide by heart (none of us do!), _but_ I do expect you to read the sections I link to and learn from your failures. I know I'm very direct with you, but it is with the best intentions.

**Comment by rruuaanng** [comment]
@erlend-aasland here :)

**Comment by rruuaanng** [comment]
I should probably open a new PR.

**Pull request closed without merging**
