### PR TITLE
Fix typo in asynchronous generator iterator documentation

### PR DESCRIPTION
**Pull request by tiangolo**
Remove an unnecessary "that":
... will execute that the body ... ->  ... will execute the body ...

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks. Waiting for CLA.

**Comment by tiangolo** [comment]
Thanks! I just signed it an hour ago or so. So I guess it will appear in a couple of days.

**Comment by Mariatta** [comment]
Thanks, please recheck the CLA in a day. After that, this will get automatically merged.
Thanks again and congrats on your first contribution to CPython 🌮

**Pull request merged**
