### PR TITLE
bpo-32409: Revert "bpo-32409: Fix regression in activate.bat on international Windows (GH-10295)"

### PR DESCRIPTION
**Pull request by pablogsal**
This reverts commit c64583b6d3e8516a8cd2b5f84fc1e300bfac2206 as it broke several Windows buildbots:

Original PR:

https://github.com/python/cpython/pull/10295

Broken buildbot links:

https://buildbot.python.org/all/#/builders/32/builds/1707
https://buildbot.python.org/all/#/builders/113/builds/733
https://buildbot.python.org/all/#/builders/40/builds/1137
https://buildbot.python.org/all/#/builders/130/builds/420
https://buildbot.python.org/all/#/builders/3/builds/1634

Revert policy:

https://discuss.python.org/t/policy-to-revert-commits-on-buildbot-failure/404/4

Custom run in the buildbot of this revert:

https://buildbot.python.org/all/#/builders/22/builds/4

https://bugs.python.org/issue32409

### CODE REVIEW

**Comment by pablogsal** [comment]
CC @samstagern @eryksun @vsajip

**Review by vstinner — APPROVED** [review]
LGTM. I'm always in favor of reverting changes which break the CI :-)

**Comment by vstinner** [comment]
If your buildbot-custom branch change is this PR, it failed on: https://buildbot.python.org/all/#builders/42/builds/5

**Comment by pablogsal** [comment]
> If your buildbot-custom branch change is this PR, it failed on: https://buildbot.python.org/all/#builders/42/builds/5

No, that is basically the same error but with extra printing to see what exactly was failing in the original PR. Check the diff here:

https://github.com/python/cpython/commit/67ef3deef50b784821f6e7e4a77d817f70f576ce

**Comment by pablogsal** [comment]
@vstinner > If your buildbot-custom branch change is this PR, it failed on: https://buildbot.python.org/all/#builders/42/builds/5

No, that is basically the same error but with extra printing to see what exactly was failing in the original PR. Check the diff here:

https://github.com/python/cpython/commit/67ef3deef50b784821f6e7e4a77d817f70f576ce

**Comment by pablogsal** [comment]
The commit was not backported to 3.6, so is no need to backport this to 3.6. :)

Good job @miss-islington !

**Pull request merged**
