### PR TITLE
gh-97681: Remove Tools/demo/ directory

### PR DESCRIPTION
**Pull request by vstinner**
Remove the following old demo scripts:

* beer.py
* eiffel.py
* hanoi.py
* life.py
* markov.py
* mcast.py
* queens.py
* redemo.py
* rpython.py
* rpythond.py
* sortvisu.py
* spreadsheet.py
* vector.py

Changes:

* Remove a reference to the redemo.py script in the regex howto documentation.
* Remove a reference to the removed Tools/demo/ directory in the curses documentation.
* Update PC/layout/ to remove the reference to Tools/demo/ directory.

* Issue: gh-97681

### CODE REVIEW

**Comment by vstinner** [comment]
> Remove a reference to the removed Tools/demo/ directory in the curses documentation.

In fact, only ``Tools/demo/life.py`` uses the curses module.

**Comment by vstinner** [comment]
cc @gvanrossum

**Review by gvanrossum — APPROVED** [review]
LGTM.

I kept a copy of these files in a personal repo: https://github.com/gvanrossum/old-demos

**Comment by vstinner** [comment]
> I kept a copy of these files in a personal repo: https://github.com/gvanrossum/old-demos

Should I add a link to it in the changelog entry ?

**Comment by gvanrossum** [comment]
Sure!

**Comment by vstinner** [comment]
I added a link to https://github.com/gvanrossum/old-demos in the change documentation, and I documented the removal of Demos in What's New in Python 3.12.

**Comment by vstinner** [comment]
Goodbye old demos, enjoy your new home: https://github.com/gvanrossum/old-demos

**Comment by gvanrossum** [comment]
Thanks!

**Comment by vstinner** [comment]
I looked at the first author of each removed demo:

- Guido van Rossum:

  * mcast (1992)
  * vector (1992)
  * markov (1993)
  * hanoi (1994)
  * rpython (1995)
  * sortvisu (1997)
  * beer (1998)
  * redemo (1998)
  * queens (2000)
  * spreadsheet (2002)

- Andrew M. Kuchling: life (2000)
- Jeremy Hylton: eiffel (2002)

Demos were created between 1992 and 2002, and Guido wrote most of them (10 of 12).

**Pull request merged**
