### PR TITLE
Docs: Resolve Sphinx warnings in dis.rst

### PR DESCRIPTION
**Pull request by erlend-aasland**
- Link to the code objects reference
- Suppress link to deliberately undocumented builtins.\_\_build_class\_\_
- Suppress links for example methods

----
:books: Documentation preview :books:: https://cpython-previews--108476.org.readthedocs.build/

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
LGTM

**Comment by erlend-aasland** [comment]
Thanks for the review, Alex!

**Comment by erlend-aasland** [comment]
I'll wait with the backports until Thomas gets around to merging the other queued 3.12 doc PRs.

**Comment by serhiy-storchaka** [comment]
LGTM.

**Comment by erlend-aasland** [comment]
dis.rst looks a lot more different in 3.11 than in 3.12; I'm not sure that backport is worth it.

**Pull request merged**
