### PR TITLE
GH-94851: fix immortal objects refcounting in compiler

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-94851

Found while working on https://github.com/python/cpython/pull/95001

### CODE REVIEW

**Comment by kumaraditya303** [comment]
> There are several _Py_STR related codes that don't increase reference count when they are used.

it depends on its usage, if you are owning the object or returning it from a function then incref is required else it is not required.

**Comment by kumaraditya303** [comment]
> It will be helpful to review if you can suggest reproducible code as you did before.

If you follow the macro, it is capturing a reference to the new object or incref is required.

**Comment by corona10** [comment]
@kumaraditya303 

````python

a = 1
print(f'{a:d} {a:d}  {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d}')
````

**Comment by kumaraditya303** [comment]
> 
> ```python
> a = 1
> print(f'{a:d} {a:d}  {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d} {a:d}')
> ```
> 
> ```
> ./python.exe -X showrefcount tt.py
> 1 1  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
> [-1 refs, 0 blocks]
> ```

Nice repro, thanks!

**Comment by corona10** [comment]
And I checked that your patch fix this issue.

`````bash

./python.exe -X showrefcount tt.py
1 1  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[0 refs, 0 blocks]
`````

**Review by corona10 — APPROVED** [review]
LGTM.

Please submit the reproducible code if possible it can reduce the reviewer's time and help understanding context :)
I know your patch is correct but reproducible code makes sure what your patch fixes exactly.

**Comment by corona10** [comment]
I will merge backport patch after my dinner :)

**Pull request merged**
