### PR TITLE
gh-98040: Remove just the `imp` module

### PR DESCRIPTION
**Pull request by warsaw**
@ericsnowcurrently - here's a branch that removes just the `imp` module.  It still has failures because of [this pip issue](https://github.com/pypa/pip/issues/11501).

* Issue: gh-98040

### CODE REVIEW

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

(pending the pip fix, of course)

**Comment by ericsnowcurrently** [comment]
Thanks for splitting this out.  It was much easier to review. 😄

**Review by iritkatriel — DISMISSED** [review]
This has a merge conflict now.

**Comment by arhadthedev** [comment]
It seems that whoever wanted to merge `main` into this PR cherry-picked it instead.

The previous head was f45d6a48f79656ae4a4e3a9099713e03ba025cc5. I would like to leave the restoration force-push to core developers.

**Comment by CAM-Gerlach** [comment]
FYI, the actual head of this PR branch was 6159e52 . It actually turned out to be fairly straightforward to fix with some rebaseing, i.e.

```bash
git fetch upstream
git rebase upstream/main 6159e52ea7000499260d18cee833761811a67fa1
```

I've (force) pushed the fixed version.

**Comment by CAM-Gerlach** [comment]
So, grepping a bit, looks like `imp` is still referred to various potentially problematic places:

* A few places in the docs, including at least one spot that's causing the docs build to fail, as its resulting in a broken reference in a clean file—I can help fix those
* The `stdlib_module_names.h` file, which is causing the check for generated files to fail—should it just be removed there?
* Some comments in the code that still refer to it
* A couple references in the opcode generation as well
* Used in the legacy `importbench` script in `Tools`—should that just be removed, is there a drop in replacement or does it need to be manually converted to `importlib`? Not sure if its still actually used now that we have other benchmark sources.

I'm assuming the test failures due to `ensurepip` are expected, as referred to above. I'm also assuming the `_imp` module is intended to stay.

Here's a full list, pruned for false positives and instances that should stay (NEWS, what's new, historical notes, etc):


```
Doc/c-api/import.rst:189:      Uses :func:`imp.source_from_cache()` in calculating the source path if
Doc/library/functions.rst:1990:      module: imp
Doc/reference/import.rst:1078:   :class:`imp.NullImporter` in the :data:`sys.path_importer_cache`.  It
Doc/tools/.nitignore:155:Doc/library/imp.rst
Lib/pydoc.py:515:            (object.__name__ in ('errno', 'exceptions', 'gc', 'imp',
Lib/test/test_importlib/util.py:134:        if name in ('sys', 'marshal', 'imp'):
Lib/test/test_runpy.py:201:        self.expect_import_error("sys.imp.eric")
Modules/_testmultiphase.c:889:/*** Helper for imp test ***/
Python/import.c:594:    for the first time or via imp.load_dynamic().
Python/import.c:596:    Here's a summary, using imp.load_dynamic() as the starting point:
Python/import.c:598:    1.  imp.load_dynamic() -> importlib._bootstrap._load()
Python/import.c:3789:"(Extremely) low-level import machinery bits as used by importlib and imp.");
Python/makeopcodetargets.py:13:    import imp
Python/makeopcodetargets.py:20:        return imp.load_module(modname, *imp.find_module(modname, [modpath]))
Python/pylifecycle.c:2172:    /* Main is a little special - imp.is_builtin("__main__") will return
Python/stdlib_module_names.h:167:"imp",
Tools/c-analyzer/TODO:498:Python/import.c:PyImport_ReloadModule():PyId_imp                 _Py_IDENTIFIER(imp)
Tools/importbench/importbench.py:9:import imp
Tools/importbench/importbench.py:43:    module = imp.new_module(name)
Tools/importbench/importbench.py:68:            assert not os.path.exists(imp.cache_from_source(mapping[name]))
Tools/importbench/importbench.py:83:        bytecode_path = imp.cache_from_source(module.__file__)
Tools/importbench/importbench.py:111:            os.unlink(imp.cache_from_source(mapping[name]))
Tools/importbench/importbench.py:113:            assert not os.path.exists(imp.cache_from_source(mapping[name]))
Tools/importbench/importbench.py:124:            os.unlink(imp.cache_from_source(module.__file__))
Tools/importbench/importbench.py:144:        assert os.path.exists(imp.cache_from_source(mapping[name]))
```

**Comment by CAM-Gerlach** [comment]
Also, not totally sure why, but when I build this commit, I get this delta in the generated files which I cannot reproduce on the `main` parent commit, adding `zipimporter` a few places:

```diff
diff --git a/Include/internal/pycore_global_objects_fini_generated.h b/Include/internal/pycore_global_objects_fini_generated.h
index 14dfd9ea582..d79b56574f7 100644
--- a/Include/internal/pycore_global_objects_fini_generated.h
+++ b/Include/internal/pycore_global_objects_fini_generated.h
@@ -1232,6 +1232,7 @@ _PyStaticObjects_CheckRefcnt(PyInterpreterState *interp) {
     _PyStaticObject_CheckRefcnt((PyObject *)&_Py_ID(x));
     _PyStaticObject_CheckRefcnt((PyObject *)&_Py_ID(year));
     _PyStaticObject_CheckRefcnt((PyObject *)&_Py_ID(zdict));
+    _PyStaticObject_CheckRefcnt((PyObject *)&_Py_ID(zipimporter));
     _PyStaticObject_CheckRefcnt((PyObject *)&_Py_SINGLETON(strings).ascii[0]);
     _PyStaticObject_CheckRefcnt((PyObject *)&_Py_SINGLETON(strings).ascii[1]);
     _PyStaticObject_CheckRefcnt((PyObject *)&_Py_SINGLETON(strings).ascii[2]);
diff --git a/Include/internal/pycore_global_strings.h b/Include/internal/pycore_global_strings.h
index 6f430bb25eb..77169765294 100644
--- a/Include/internal/pycore_global_strings.h
+++ b/Include/internal/pycore_global_strings.h
@@ -718,6 +718,7 @@ struct _Py_global_strings {
         STRUCT_FOR_ID(x)
         STRUCT_FOR_ID(year)
         STRUCT_FOR_ID(zdict)
+        STRUCT_FOR_ID(zipimporter)
     } identifiers;
     struct {
         PyASCIIObject _ascii;
diff --git a/Include/internal/pycore_runtime_init_generated.h b/Include/internal/pycore_runtime_init_generated.h
index 0452c4c6155..82014a8b10d 100644
--- a/Include/internal/pycore_runtime_init_generated.h
+++ b/Include/internal/pycore_runtime_init_generated.h
@@ -1224,6 +1224,7 @@ extern "C" {
     INIT_ID(x), \
     INIT_ID(year), \
     INIT_ID(zdict), \
+    INIT_ID(zipimporter), \
 }

 #define _Py_str_ascii_INIT { \
diff --git a/Include/internal/pycore_unicodeobject_generated.h b/Include/internal/pycore_unicodeobject_generated.h
index 7114a5416f2..6d4dcc229aa 100644
--- a/Include/internal/pycore_unicodeobject_generated.h
+++ b/Include/internal/pycore_unicodeobject_generated.h
@@ -2007,6 +2007,9 @@ _PyUnicode_InitStaticStrings(PyInterpreterState *interp) {
     string = &_Py_ID(zdict);
     assert(_PyUnicode_CheckConsistency(string, 1));
     _PyUnicode_InternInPlace(interp, &string);
+    string = &_Py_ID(zipimporter);
+    assert(_PyUnicode_CheckConsistency(string, 1));
+    _PyUnicode_InternInPlace(interp, &string);
 }
 /* End auto-generated code */
 #ifdef __cplusplus
```

**Comment by warsaw** [comment]
> @warsaw, FYI, I'm moving the tests I recently added to test_imp over to test_import: [gh-102561](https://github.com/python/cpython/pull/102561).
> 
> While I was doing that, I noticed there are other tests in test_imp that seem to be more about exercising the import system than the imp module itself, which may make it worth it to keep them. Assuming those ones really aren't imp-specific, do you know if any of them are not already covered by other tests, e.g. in test_import or test_importlib? If so, we should move them out before test_imp is deleted. I'd be glad to do so if it would help (if there are any).

I missed this comment earlier but yes, we should audit `test_imp.py` for general import system tests and move them over.  I plan on working on this at Pycon.

**Comment by warsaw** [comment]
> So, grepping a bit, looks like imp is still referred to various potentially undesired places

Thanks for doing this audit @CAM-Gerlach !

**Comment by vstinner** [comment]
The ``imp`` module is deprecated for 9 years, since Python 3.4 (2014). Problem: a search for ``(from imp\b|import imp\b)`` regex in PyPI top 5,000 projects match 153 projects (260 lines).

That's why I didn't propose a PR to remove it in Python 3.12.

It would be *nice* for the Python community to collaborate with these projects to reduce the number of impacted projects *before* removing the ``imp`` module.

Example of projects:

* ansible-7.4.0
* boto-2.49.0
* **cffi**-1.15.1
* conda-4.3.16
* django-compat-1.0.15
* eventlet-0.33.3
* lxml-4.9.2
* matplotlib-3.7.1
* mercurial-6.4.1
* nose-1.3.7
* Paste-3.5.2
* **pip**-23.0.1
* **pipenv**-2023.3.20
* reportlab-3.6.12
* setuptools-67.6.1
* **Twisted**-22.10.0
* virtualenv-20.21.0

Full list of projects:

<details>
* aiosmtpd-1.4.4.post2
* ansible-7.4.0
* ansible-core-2.14.4
* ansiwrap-0.8.4
* apache-libcloud-3.7.0
* argcomplete-3.0.5
* Arpeggio-2.0.0
* asttokens-2.2.1
* audioread-3.0.0
* auth-0.5.3
* Autologging-1.3.2
* autopep8-2.0.2
* better_exceptions-0.3.3
* boto-2.49.0
* bottle-0.12.25
* cachy-0.3.0
* casadi-3.6.0
* cement-3.0.8
* Cerberus-1.3.4
* cffi-1.15.1
* Cheetah3-3.2.6.post1
* circus-0.18.0
* comtypes-1.1.14
* conda-4.3.16
* conda-pack-0.6.0
* coremltools-6.3.0
* crochet-2.0.0
* Cython-0.29.34
* databricks-cli-0.17.6
* datalab-1.2.1
* dateparser-1.1.8
* dbnd-1.0.12.12
* ddtrace-1.11.2
* debugpy-1.6.7
* diff-match-patch-20200713
* distlib-0.3.6
* distribute-0.7.3
* django-compat-1.0.15
* django_compressor-4.3.1
* django-configurations-2.4.1
* django-filter-23.1
* django-grappelli-3.0.5
* django-heroku-0.3.1
* django-nine-0.2.7
* django-user_agents-0.4.0
* dominate-2.7.0
* dtale-2.14.0
* dvc-2.54.0
* eventlet-0.33.3
* fastrlock-0.8.1
* fire-0.5.0
* flasgger-0.9.5
* Flask-AppBuilder-4.3.1
* flatbuffers-23.3.3
* func_timeout-4.3.5
* future-0.18.3
* gevent-22.10.2
* glom-23.3.0
* google-compute-engine-2.8.13
* grafanalib-0.7.0
* gsutil-5.23
* h2o-3.40.0.3
* hachoir-3.2.0
* hdfs-2.7.0
* hjson-3.1.0
* hyper-0.7.0
* imageio-2.27.0
* IMAPClient-2.3.1
* importlab-0.8
* invoke-2.0.0
* j2cli-0.3.10
* joblib-1.2.0
* Kivy-2.1.0
* logilab-common-1.9.8
* lxml-4.9.2
* markdown2-2.4.8
* matplotlib-3.7.1
* mercurial-6.4.1
* metaflow-2.8.3
* ml_collections-0.1.1
* multiprocessing-2.6.2.1
* mysql-connector-2.2.9
* mysql-connector-python-rf-2.2.2
* newrelic-8.8.0
* nose-1.3.7
* numba-0.56.4
* oletools-0.60.1
* os_sys-2.1.4
* Paste-3.5.2
* pathtools-0.1.2
* pbr-5.11.1
* pdm-2.5.2
* pep562-1.1
* pex-2.1.131
* pip-23.0.1
* pipenv-2023.3.20
* plac-1.3.5
* ply-3.11
* psutil-5.9.4
* ptvsd-4.3.2
* pvlib-0.9.5
* py2neo-2021.2.3
* pycryptodome-3.17
* pycryptodomex-3.17
* pydevd-2.9.5
* pydevd-pycharm-231.8109.197
* pydoop-2.0.0
* pyexcel-0.7.0
* pyhocon-0.3.60
* pyinstaller-5.10.0
* pyLDAvis-3.4.0
* Pympler-1.0.1
* pynose-1.4.2
* pyodbc-4.0.38
* pyopencl-2022.3.1
* pyrepl-0.9.0
* Pyro4-4.82
* pysaml2-7.4.1
* pysmi-0.3.4
* pysnmp-4.4.12
* pytest-openfiles-0.5.0
* pytest-shutil-1.7.0
* python-crfsuite-0.9.9
* python-i18n-0.3.9
* PyXB-1.2.6
* pyxdg-0.28
* raven-6.10.0
* rcssmin-1.1.1
* reportlab-3.6.12
* rjsmin-1.2.1
* SCons-4.5.2
* scrypt-0.8.20
* selinux-0.3.0
* setupmeta-3.4.0
* setuptools-67.6.1
* simplejson-3.19.1
* snapshottest-0.6.0
* social-auth-core-4.4.1
* sox-1.4.1
* sqlalchemy-migrate-0.13.0
* stone-3.3.1
* strip-hints-0.1.10
* sympy-1.11.1
* tecton-0.6.5
* Theano-1.0.5
* Twisted-22.10.0
* twofish-0.3.0
* uwsgi-2.0.21
* virtualenv-20.21.0
* vowpalwabbit-9.8.0
* workflow-2.1.6
* yacs-0.1.8
* Yapsy-1.12.2
</details>

**Comment by vstinner** [comment]
pip and setuptools:

```
PYPI-2023-04-13/pip-23.0.1.tar.gz: pip-23.0.1/src/pip/_vendor/distlib/wheel.py: import imp
PYPI-2023-04-13/pip-23.0.1.tar.gz: pip-23.0.1/src/pip/_vendor/pkg_resources/__init__.py: import imp as _imp
PYPI-2023-04-13/setuptools-67.6.1.tar.gz: setuptools-67.6.1/pkg_resources/__init__.py: import imp as _imp
```

**Comment by graingert** [comment]
distlib only uses imp on python 2 and pkg_resources only uses imp on python <= 3.2, otherwise it uses `_imp`. Will the `_imp` module remain after the `imp` removal?

**Comment by ericsnowcurrently** [comment]
> Will the _imp module remain after the imp removal?

yes

**Comment by CAM-Gerlach** [comment]
@vstinner Is it possible to perform a more limited search of only top-level (no indent) lines that import `imp`, which would exclude mostly false positives (fallbacks, version-specific imports, conditional imports, imports only in certain specialized/per-version scopes, etc)? I.e. `^(from|import) imp\b`?

**Comment by hugovk** [comment]
Yes (here's how: https://dev.to/hugovk/how-to-search-5000-python-projects-31gk):

Found 105 matching lines in 71 projects

<details>
<summary>Details</summary>

```console
❯ python3 ~/github/misc/cpython/search_pypi_top.py -q . "^(from|import) imp\b"
./django-compat-1.0.15.tar.gz: django-compat-1.0.15/compat/tests/test_module_loading.py: import imp
./hyper-0.7.0.tar.gz: hyper-0.7.0/test/test_import.py: import imp
./hdfs-2.7.0.tar.gz: hdfs-2.7.0/hdfs/config.py: from imp import load_source
./hdfs-2.7.0.tar.gz: hdfs-2.7.0/test/test_examples.py: from imp import load_source
./Kivy-2.1.0.tar.gz: Kivy-2.1.0/kivy/garden/__init__.py: import imp
./reportlab-3.6.12.tar.gz: reportlab-3.6.12/tools/docco/codegrab.py: import imp
./reportlab-3.6.12.tar.gz: reportlab-3.6.12/tools/docco/yaml2pdf.py: import imp
./reportlab-3.6.12.tar.gz: reportlab-3.6.12/tools/pythonpoint/stdparser.py: import imp, sys, os, copy
./twofish-0.3.0.tar.gz: twofish-0.3.0/twofish.py: import imp
./gevent-22.10.2.tar.gz: gevent-22.10.2/src/greentest/2.7/test_socketserver.py: import imp
./gevent-22.10.2.tar.gz: gevent-22.10.2/src/greentest/2.7pypy/test_socketserver.py: import imp
./autopep8-2.0.2.tar.gz: autopep8-2.0.2/test/example_with_reduce.py: import imp
./django_compressor-4.3.1.tar.gz: django_compressor-4.3.1/compressor/tests/test_utils.py: from imp import reload
./nose-1.3.7.tar.gz: nose-1.3.7/nose/importer.py: from imp import find_module, load_module, acquire_lock, release_lock
./nose-1.3.7.tar.gz: nose-1.3.7/unit_tests/mock.py: import imp
./nose-1.3.7.tar.gz: nose-1.3.7/unit_tests/test_loader.py: import imp
./nose-1.3.7.tar.gz: nose-1.3.7/unit_tests/test_multiprocess_runner.py: import imp
./nose-1.3.7.tar.gz: nose-1.3.7/unit_tests/test_suite.py: import imp
./sox-1.4.1.tar.gz: sox-1.4.1/docs/conf.py: import imp
./sox-1.4.1.tar.gz: sox-1.4.1/docs/tmp_conf.py: import imp
./sox-1.4.1.tar.gz: sox-1.4.1/setup.py: import imp
./logilab-common-1.9.8.tar.gz: logilab-common-1.9.8/logilab/common/modutils.py: from imp import find_module, load_module, C_BUILTIN, PY_COMPILED, PKG_DIRECTORY
./Flask-AppBuilder-4.3.1.tar.gz: Flask-AppBuilder-4.3.1/bin/db_migrate.py: import imp
./dominate-2.7.0.tar.gz: dominate-2.7.0/setup.py: import imp
./datalab-1.2.1.tar.gz: datalab-1.2.1/datalab/data/commands/_sql.py: import imp
./markdown2-2.4.8.tar.gz: markdown2-2.4.8/test/testlib.py: import imp
./os_sys-2.1.4.tar.gz: os_sys-2.1.4/pywintypes.py: import imp, sys, os
./pydoop-2.0.0.tar.gz: pydoop-2.0.0/pydoop/test_utils.py: import imp
./pydoop-2.0.0.tar.gz: pydoop-2.0.0/test/common/test_pydoop.py: from imp import reload
./os_sys-2.1.4.tar.gz: os_sys-2.1.4/win32_extentions/pywintypes.py: import imp, sys, os
./pysaml2-7.4.1.tar.gz: pysaml2-7.4.1/src/saml2/tools/parse_xsd2.py: import imp
./pydevd-pycharm-231.8109.197.tar.gz: pydevd-pycharm-231.8109.197/_pydev_imps/_pydev_pkgutil_old.py: import imp
./pydevd-pycharm-231.8109.197.tar.gz: pydevd-pycharm-231.8109.197/_pydev_imps/_pydev_inspect.py: import imp
./pydevd-pycharm-231.8109.197.tar.gz: pydevd-pycharm-231.8109.197/_pydevd_bundle/pydevd_reload.py: import imp
./ml_collections-0.1.1.tar.gz: ml_collections-0.1.1/ml_collections/config_flags/config_flags.py: import imp
./flasgger-0.9.5.tar.gz: flasgger-0.9.5/flasgger/utils.py: import imp
./mysql-connector-python-rf-2.2.2.tar.gz: mysql-connector-python-rf-2.2.2/tests/__init__.py: from imp import load_source
./mysql-connector-python-rf-2.2.2.tar.gz: mysql-connector-python-rf-2.2.2/tests/test_setup.py: import imp
./oletools-0.60.1.zip: oletools-0.60.1/oletools/thirdparty/xxxswf/xxxswf.py: import imp
./joblib-1.2.0.tar.gz: joblib-1.2.0/joblib/test/test_format_stack.py: import imp
./j2cli-0.3.10.tar.gz: j2cli-0.3.10/j2cli/cli.py: import imp, inspect
./auth-0.5.3.tar.gz: auth-0.5.3/setup.py: import imp
./PyXB-1.2.6.tar.gz: PyXB-1.2.6/tests/drivers/test-external.py: import imp
./audioread-3.0.0.tar.gz: audioread-3.0.0/setup.py: import imp
./boto-2.49.0.tar.gz: boto-2.49.0/boto/pyami/launch_ami.py: import imp
./boto-2.49.0.tar.gz: boto-2.49.0/boto/plugin.py: import imp
./diff-match-patch-20200713.tar.gz: diff-match-patch-20200713/diff_match_patch/tests/speedtest.py: import imp
./diff-match-patch-20200713.tar.gz: diff-match-patch-20200713/diff_match_patch/tests/diff_match_patch_test.py: import imp
./ansiwrap-0.8.4.zip: ansiwrap-0.8.4/ansiwrap/core.py: import imp
./Paste-3.5.2.tar.gz: Paste-3.5.2/paste/urlparser.py: import imp
./mercurial-6.4.tar.gz: mercurial-6.4/contrib/python-zstandard/tests/common.py: import imp
./pyexcel-0.7.0.tar.gz: pyexcel-0.7.0/tests/test_examples.py: import imp
./mercurial-6.4.tar.gz: mercurial-6.4/mercurial/extensions.py: import imp
./mercurial-6.4.tar.gz: mercurial-6.4/mercurial/utils/resourceutil.py: import imp
./pytest-shutil-1.7.0.tar.gz: pytest-shutil-1.7.0/pytest_shutil/run.py: import imp
./uwsgi-2.0.21.tar.gz: uwsgi-2.0.21/plugins/pypy/pypy_setup.py: import imp
./asttokens-2.2.1.tar.gz: asttokens-2.2.1/tests/testdata/python2/astroid/nonregr.py: import imp
./asttokens-2.2.1.tar.gz: asttokens-2.2.1/tests/testdata/python3/astroid/nonregr.py: import imp
./mysql-connector-2.2.9.tar.gz: mysql-connector-2.2.9/tests/__init__.py: from imp import load_source
./pyrepl-0.9.0.tar.gz: pyrepl-0.9.0/pyrepl/python_reader.py: import imp, sys, os, re, code, traceback
./mysql-connector-2.2.9.tar.gz: mysql-connector-2.2.9/tests/test_setup.py: import imp
./sqlalchemy-migrate-0.13.0.tar.gz: sqlalchemy-migrate-0.13.0/migrate/tests/versioning/test_script.py: import imp
./pex-2.1.131.tar.gz: pex-2.1.131/pex/vendor/_vendored/pip/pip/_vendor/distlib/wheel.py: import imp
./metaflow-2.8.2.tar.gz: metaflow-2.8.2/metaflow/R.py: import imp
./pep562-1.1.tar.gz: pep562-1.1/setup.py: import imp
./Cython-0.29.33.tar.gz: Cython-0.29.33/Cython/Build/IpythonMagic.py: import imp
./Cython-0.29.33.tar.gz: Cython-0.29.33/pyximport/pyximport.py: import imp
./strip-hints-0.1.10.tar.gz: strip-hints-0.1.10/src/strip_hints/import_hooks.py: import imp
./pathtools-0.1.2.tar.gz: pathtools-0.1.2/setup.py: import imp
./gsutil-5.21.tar.gz: gsutil-5.21/gslib/vendored/boto/boto/plugin.py: import imp
./gsutil-5.21.tar.gz: gsutil-5.21/gslib/vendored/boto/boto/pyami/launch_ami.py: import imp
./django-heroku-0.3.1.tar.gz: django-heroku-0.3.1/test/test_django_heroku.py: import imp
./django-configurations-2.4.tar.gz: django-configurations-2.4/configurations/importer.py: import imp
./crochet-2.0.0.tar.gz: crochet-2.0.0/crochet/tests/test_api.py: import imp
./ptvsd-4.3.2.zip: ptvsd-4.3.2/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_reload.py: import imp
./ptvsd-4.3.2.zip: ptvsd-4.3.2/src/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_pkgutil_old.py: import imp
./numba-0.56.4.tar.gz: numba-0.56.4/numba/tests/test_llvm_version_check.py: import imp
./numba-0.56.4.tar.gz: numba-0.56.4/numba/tests/test_pycc.py: import imp
./future-0.18.3.tar.gz: future-0.18.3/docs/other/auto2to3.py: import imp
./future-0.18.3.tar.gz: future-0.18.3/src/past/translation/__init__.py: import imp
./future-0.18.3.tar.gz: future-0.18.3/src/future/backports/test/support.py: import imp
./future-0.18.3.tar.gz: future-0.18.3/src/future/standard_library/__init__.py: import imp
./pbr-5.11.1.tar.gz: pbr-5.11.1/pbr/tests/test_packaging.py: import imp
./IMAPClient-2.3.1.zip: IMAPClient-2.3.1/livetest.py: import imp
./social-auth-core-4.4.1.tar.gz: social-auth-core-4.4.1/social_core/backends/shopify.py: import imp
./lxml-4.9.2.tar.gz: lxml-4.9.2/src/lxml/html/tests/test_html5parser.py: import imp
./workflow-2.1.6.tar.gz: workflow-2.1.6/bin/run_workflow.py: import imp
./pyinstaller-5.9.0.tar.gz: pyinstaller-5.9.0/PyInstaller/lib/modulegraph/find_modules.py: import imp
./pyinstaller-5.9.0.tar.gz: pyinstaller-5.9.0/PyInstaller/lib/modulegraph/modulegraph.py: import imp
./pyinstaller-5.9.0.tar.gz: pyinstaller-5.9.0/PyInstaller/lib/modulegraph/util.py: import imp
./invoke-2.0.0.tar.gz: invoke-2.0.0/tests/loader.py: import imp
./invoke-2.0.0.tar.gz: invoke-2.0.0/invoke/loader.py: import imp
./pyinstaller-5.9.0.tar.gz: pyinstaller-5.9.0/tests/functional/scripts/pyi_hooks/hook-pkg_without_hook_for_pkg.sub1.py: import imp
./pyinstaller-5.9.0.tar.gz: pyinstaller-5.9.0/tests/unit/test_modulegraph/test_modulegraph.py: import imp
./cement-3.0.8.tar.gz: cement-3.0.8/cement/ext/ext_plugin.py: import imp
./pynose-1.4.2.tar.gz: pynose-1.4.2/nose/importer.py: from imp import find_module, load_module, acquire_lock, release_lock
./glom-23.3.0.tar.gz: glom-23.3.0/setup.py: import imp
./databricks-cli-0.17.6.tar.gz: databricks-cli-0.17.6/setup.py: import imp
./coremltools-6.2.tar.gz: coremltools-6.2/setup.py: import imp
./Theano-1.0.5.tar.gz: Theano-1.0.5/theano/tests/breakpoint.py: import imp
./Twisted-22.10.0.tar.gz: Twisted-22.10.0/src/twisted/conch/scripts/ckeygen.py: from imp import reload
./Twisted-22.10.0.tar.gz: Twisted-22.10.0/src/twisted/python/rebuild.py: from imp import reload
./stone-3.3.1.tar.gz: stone-3.3.1/stone/cli.py: import imp  # pylint: disable=deprecated-module
./distribute-0.7.3.zip: distribute-0.7.3/setuptools/depends.py: from imp import PKG_DIRECTORY, PY_COMPILED, PY_SOURCE, PY_FROZEN
./snapshottest-0.6.0.tar.gz: snapshottest-0.6.0/snapshottest/module.py: import imp

Time: 0:00:16.968345
Found 105 matching lines in 71 projects
```

</details>

We can ignore nose, it's been unmaintained for 7 years and no longer works with Python 3.12 for other reasons.

---

> The `imp` module is deprecated for 9 years, since Python 3.4 (2014).

Some more dates:

* `PendingDeprecationWarning` since 3.4 (2014): https://github.com/python/cpython/commit/e4f41deccf94ccc798b1eb1f44657ade66669a60
* Upgraded to `DeprecationWarning` since 3.5 (2015): https://github.com/python/cpython/commit/c0d91aff9a3b91307b26e8b7c34dfbf27bbdd43a
* Updated `DeprecationWarning` to say removal in 3.12 since 3.10 (2021): https://github.com/python/cpython/commit/dc6d3e1e4c0c1e4b2210edab8fb4762569dc2936

**Comment by warsaw** [comment]
Thanks @hugovk !  I think the next step is to lightly audit some of those project to see if there's a pattern and work up some documentation about how to migrate any common usage/APIs that we see.

**Comment by vstinner** [comment]
> work up some documentation about how to migrate any common usage/APIs that we see

Great, thanks :-)

**Comment by warsaw** [comment]
Now that the `pip` blocker is resolved, I'm moving this out of draft status, even though some work still needs to be done.

**Comment by warsaw** [comment]
Now that the `pip` blocker is resolved, I'm moving this out of draft status, even though some work still needs to be done.

**Comment by warsaw** [comment]
I believe I've now removed all inconsequential references to the `imp` module, comments, likely legacy code, etc.   I have not done the audit as suggested above, nor documentation about replacements.  I think if this branch passes though, and it passes a final review, we can land it before Python 3.12 beta 1 and then work on the audit and documentation after the feature freeze deadline.

**Comment by warsaw** [comment]
@ericsnowcurrently or @brettcannon Would you take another quick look?

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Pull request merged**
