### PR TITLE
bpo-43570: Doc: Fix i18n issue with audit hooks.

### PR DESCRIPTION
**Pull request by JulienPalard**
https://bugs.python.org/issue43570

### CODE REVIEW

**Comment by humitos** [comment]
I wanted to confirm here that this patch makes the Spanish translation to work as well. I didn't dig too much on the HTML generated yet, but at least Sphinx finishes with no warning at all with this patch.

We found this the same problem in our translation and we are tracking it at https://github.com/python/python-docs-es/issues/1221

**Comment by JulienPalard** [comment]
I tried running `sphinx -b gettext` with this patch and it correctly removes unused strings:

```diff
-#: library/sys.rst:1246
-msgid ""
-"Raises an :ref:`auditing event <auditing>` ``sys.setprofile`` with no "
-"arguments."
-msgstr ""
-"Lève un :ref:`évènement d'audit <auditing>` ``sys.setprofile`` sans "
-"arguments."
-
 #: library/sys.rst:1329
 msgid "The events have the following meaning:"
 msgstr "Les événements ont la signification suivante :"
@@ -2659,13 +2657,6 @@ msgstr ""
 "Pour plus d'informations sur les objets code et objets représentant une "
 "*frame* de la pile, consultez :ref:`types`."

-#: library/sys.rst:1380
-msgid ""
-"Raises an :ref:`auditing event <auditing>` ``sys.settrace`` with no "
-"arguments."
-msgstr ""
-"Lève un :ref:`évènement d'audit <auditing>` ``sys.settrace`` sans arguments."
-

```

**Review by zooba — CHANGES_REQUESTED** [review]
I'm not sure exactly what's wrong, but the non-customised text paragraphs are empty.

image

I'm looking at the HTML files attached to the docs check on this PR.

**Comment by JulienPalard** [comment]
I have made the requested changes; please review again.

**Comment by JulienPalard** [comment]
@humitos would you please check if this new patch works for the spanish translation?

**Comment by JulienPalard** [comment]
I `diff -r`ed before and after this patch and the HTML does not change.

And wow, I feel good, I understand my own patch (it was NOT the case for the previous one):

As we translate restructuredtext, the rawsource (1rst parameter of `paragraph`) is important for translators. Before the patch, it was always set to the pyspecific text, even if overloaded a few line later with the rst content, so we translators were only seeing the pyspecific text.

**Comment by JulienPalard** [comment]
Gentle ping @zooba.

**Comment by JulienPalard** [comment]
I'm closing this as I want to see how https://github.com/python/cpython/pull/19470 will change all of this, before. I'll reopen if needed.

**Pull request closed without merging**
