### PR TITLE
bpo-36127: Fix _PyArg_UnpackKeywords() warning

### PR DESCRIPTION
**Pull request by vstinner**
Use Py_ssize_t type rather than int for the 'i' variable.

https://bugs.python.org/issue36127

### CODE REVIEW

**Comment by vstinner** [comment]
This change fix the following warning on Windows:

```
c:\projects\cpython\python\getargs.c(2425): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data [C:\projects\cpython\PCbuild\pythoncore.vcxproj]
```

@serhiy-storchaka: Would you mind to review this change?

**Comment by serhiy-storchaka** [comment]
I do not think this is the best way to fix this warning. All corresponding variables except `nargs` have type `int`, and I want to preserve this.

**Comment by vstinner** [comment]
> I do not think this is the best way to fix this warning. All corresponding variables except nargs have type int, and I want to preserve this.

Why is it wrong to use Py_ssize_t for 'i'?

I don't want to use Py_ssize_t for other variables, since _PyParser uses int.

Feel free to fix the warning differently. I only worry of having no compiler warning on Windows :-)

**Comment by vstinner** [comment]
Serhiy wrote a diffrent fix:  PR #12353.

**Pull request closed without merging**
