### PR TITLE
bpo-45162: Remove many old deprecated unittest features

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* "fail*" and "assert*" aliases of TestCase methods.
* Broken from start TestCase method assertDictContainsSubset().
* Ignored TestLoader.loadTestsFromModule() parameter use_load_tests.
* Old alias _TextTestResult of TextTestResult.

https://bugs.python.org/issue45162

### CODE REVIEW

**Comment by erlend-aasland** [comment]
See also GH-20400. Should I reopen?

**Comment by serhiy-storchaka** [comment]
I do not know why GH-20400 was closed. Seems there were no objections against it.

But many of these functions are still used in Python tests, so we should first clean up tests from them. Also, we need to research how often they are used in third-party code. The deprecation period can be prolonged if there are many occurrences. All features removed in this PR were deprecated for at least 6 releases.

**Comment by erlend-aasland** [comment]
> I do not know why [GH-20400](https://github.com/python/cpython/pull/20400) was closed. Seems there were no objections against it.

I closed it because I got no response, and I had enough to do already with my sqlite3 PR's :)

> Also, we need to research how often they are used in third-party code. The deprecation period can be prolonged if there are many occurrences. All features removed in this PR were deprecated for at least 6 releases.

Absolutely.

**Comment by jiasli** [comment]
@tirkarthi, what is the best drop-in replacement for `assertDictContainsSubset`? https://stackoverflow.com/a/19221301/2199657 mentioned:

> Drop in replacement is to use `assertLessEqual` and `.items()` on the dicts.

That is:

```diff
- self.assertDictContainsSubset(a, b)
+ self.assertLessEqual(a.items(), b.items())
```

**Pull request merged**
