### PR TITLE
bpo-44131: Py_FrozenMain() uses PyConfig_SetBytesArgv()

### PR DESCRIPTION
**Pull request by vstinner**
Moreover, Py_FrozenMain() relies on Py_InitializeFromConfig() to
handle the PYTHONUNBUFFERED environment variable and configure C
stdio streams like stdout (make the stream unbuffered).

https://bugs.python.org/issue44131

### CODE REVIEW

**Comment by vstinner** [comment]
@corona10: Would you mind to review this change?

**Comment by vstinner** [comment]
PR rebased on top of commit 6ba6d069997bd8f1b1382690423489fc692365c3 fix.

**Comment by corona10** [comment]
@vstinner I will review this PR tonight :)

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by vstinner** [comment]
Thanks for the review @corona10.

It's a pleasure to remove code which calls directly Py_DecodeLocale() without preinitializing Python :-p

**Pull request merged**
