### PR TITLE
bpo-39209: Manage correctly multi-line tokens in interactive mode

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue39209

### CODE REVIEW

**Comment by pablogsal** [comment]
CC: @corona10 

Could you check if this fixes the problem on your system?

**Comment by corona10** [comment]
@pablogsal I will report it by today :)

**Comment by pablogsal** [comment]
Unfortunately, there's no way to automatically test the fully interactive REPL, since that code path only gets executed when stdin is an interactive tty.

**Comment by corona10** [comment]
@pablogsal Work correctly with this PR :)

**Review by corona10 — APPROVED** [review]
lgtm

**Review by asottile — APPROVED** [review]

**Pull request merged**
