### PR TITLE
bpo-27755: IDLE: Convert configdialog DynOptionMenu to ttk OptionMenu

### PR DESCRIPTION
**Pull request by csabella**
I know you may want to get rid of Option Menus, but I wanted to show you the ttk version.  This was too much of a change to include with the first patch.

https://bugs.python.org/issue30781

### CODE REVIEW

**Comment by terryjreedy** [comment]
This is a definite improvement.  A single OptionMenu could work for a unified list of keysets.  For themes, I am thinking of a listbox, as with fonts, so one can move around to see the effect of different choices without having the box close.

**Comment by terryjreedy** [comment]
Why?  The change is still needed.

**Comment by csabella** [comment]
I was reading through the bug tracker and it looked like Spinbox and/or Combobox would be used instead.

https://bugs.python.org/issue33962

**Comment by terryjreedy** [comment]
Right.  I found where I rejected this in its current form, and added more on current uses and replacements.

**Pull request closed without merging**
