### PR TITLE
gh-117873: Deprecate grp keyword arguments

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-117873

----
📚 Documentation preview 📚: https://cpython-previews--118010.org.readthedocs.build/

### CODE REVIEW

**Comment by nineteendo** [comment]
Do we need to change the deprecation version to 3.16 now?

**Comment by vstinner** [comment]
> Do we need to change the deprecation version to 3.16 now? And does it need to be in the 3.14 news file?

Done, I rebased my PR on the main branch which is now Python 3.14.

**Comment by vstinner** [comment]
@erlend-aasland @corona10: Do you want to review this change?

**Comment by corona10** [comment]
Not now but at Pittsburgh

**Review by corona10 — COMMENTED** [review]
So deprecate keyword arguments to avoid METH_VARARGS in the future?

**Comment by corona10** [comment]
If yes, I am not sure that it is a good approach since we require the user to change their use case to optimize our implementation.

For me, this is a better approach
* Optimize METH_VARARGS to become faster.
* Not to declare METH_VARARGS as possible for the new APIs.

**Comment by vstinner** [comment]
Ok, I close my PR. Thanks for the review!

**Pull request closed without merging**
