### PR TITLE
bpo-1635741: Calling Py_INCREF() after PyModule_AddObject() success to run

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue1635741

### CODE REVIEW

**Comment by shihai1991** [comment]
Oh, it is generated file, i will check this operation soon.

**Comment by shihai1991** [comment]
cc @vstinner Hi, victor. It's a small fix. pls review it if you have free time.

**Comment by vstinner** [comment]
cc @pablogsal @isidentical

**Comment by isidentical** [comment]
I recently saw a PR from @brandtbucher about a more general change that already includes this if I am not mistaken. Check out #17276 (it moves incref after the check by moving check upper). I am in favor of #17276 because it handles the case better also it opened before this PR

**Comment by brandtbucher** [comment]
Yes, my PR #17276 is a more comprehensive fix.

**Review by brandtbucher — CHANGES_REQUESTED** [review]
Yes, my PR #17276 is a more comprehensive fix.

**Comment by shihai1991** [comment]
Oh, thank you for quick feedback, guys.
I checked Brandt's PRs, its enhance very nice. Pls go ahead, thanks. I will subscribe your PRs ;)

**Pull request closed without merging**
