### PR TITLE
bpo-38045: Avoid quadratic complexity when creating composite IntFlags.

### PR DESCRIPTION
**Pull request by anntzer**
When one creates all possible combos of an IntFlag, e.g. with

    from enum import Flag
    F = Flag("F", list("abcdefghijklm"))
    for idx in range(2**len(F) - 1):
        F(idx)

the previous version would exhibit quadratic complexity because
`_value2member_map_` would grow bigger over each iteration.

Iterate over "true" flag members rather than `_value2member_map_`,
to avoid this problem.  For a 13-member flag (so 8192 combinations),
the speedup is more than 100x.

https://bugs.python.org/issue38045

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@anntzer

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by hongweipeng** [comment]
I think it's better not to create members in `_decompose()`. Just like its name, it only does decomposition work.

**Comment by hongweipeng** [comment]
I created a commit without creating members https://github.com/hongweipeng/cpython/commit/a5f06010962cafa457a876835e7789ec30eb783e . the speedup is aslo more than 100x in the example and passes test_enum.py.

**Comment by anntzer** [comment]
Your patch fixes the problem with Flag, but not with IntFlag (replace Flag by IntFlag in the original example and the slow behavior still exists with your patch, but not with mine).

**Comment by hongweipeng** [comment]
@anntzer Thanks for your response. You are right. The previous commit did not resolve `IntFlag`, but I think there are still ways to solve `Flag` and `IntFlag` without creating members. So I create another commit, see in https://github.com/hongweipeng/cpython/commit/9ae31f416b0d4be4e12f746da08dfe750a5a3d7b .

**Comment by anntzer** [comment]
Superseded by https://github.com/python/cpython/pull/16483.

**Pull request closed without merging**
