### PR TITLE
gh-126433: Fix compiler warnings on 32-bit Windows

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-126433

### CODE REVIEW

**Comment by vstinner** [comment]
I didn't fix these two warnings on purpose, I will fix them separately:

> C:\victor\python\main\Modules\_hacl\Lib_Memzero0.c(39,27): warning C4244: 'function': conversion from 'uint64_t' to 'SIZE_T', possible loss of data [C:\victor\python\main\PCbuild\pythoncore.vcxproj]
> C:\victor\python\main\Modules\_interpchannelsmodule.c(2096,30): warning C4244: '=': conversion from 'int64_t' to 'Py_ssize_t', possible loss of data [C:\victor\python\main\PCbuild\pythoncore.vcxproj]

**Comment by vstinner** [comment]
cc @sobolevn

**Review by sobolevn — APPROVED** [review]
Thank you!

**Comment by vstinner** [comment]
Python 3.12 doesn't have these warnings.

**Pull request merged**
