### PR TITLE
bpo-36751: Deprecate getfullargspec and report positional-only args as regular args

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue36751

### CODE REVIEW

**Review by zooba — APPROVED** [review]
Looks good to me. Thanks, Pablo! 👍

**Review by tirkarthi — CHANGES_REQUESTED** [review]
This generates `DeprecationWarning` in two tests in `Lib/unittest/test/testmock/testhelpers.py`. Please wrap it with `self.assertWarns(DeprecationWarning)` or better use `inspect.signature` in the two assert calls to remove the `DeprecationWarning`.

```
➜  cpython git:(pr_13016) ./python.exe Lib/unittest/test/testmock/testhelpers.py
...................................................../Users/karthikeyansingaravelan/stuff/python/cpython/Lib/inspect.py:1114: DeprecationWarning: Use inspect.signature() instead of inspect.getfullargspec()
  warnings.warn("Use inspect.signature() instead of inspect.getfullargspec()",
.............
----------------------------------------------------------------------
Ran 66 tests in 0.832s

OK
```

**Comment by pablogsal** [comment]
Done in 74639b3. Thanks @tirkarthi, good catch!

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks @pablogsal .

**Comment by ncoghlan** [comment]
Please revert this change - this API was deliberately undeprecated, as per https://bugs.python.org/issue27172 and PEP 570 isn't sufficient justification to deprecate it again.

**Comment by ncoghlan** [comment]
Slight correction: the API fixes to restore compatibility with 3.7 are a good thing, the problem is the reintroduction of the programmatic deprecation warnings, even though the reasons for leaving them out still hold.

**Comment by pablogsal** [comment]
@ncoghlan I have opened #13245 to handle the undeprecation. Sorry for the inconvenience.

**Pull request merged**
