### PR TITLE
bpo-31836: Test_code_module now passes with sys.ps1, ps2 set

### PR DESCRIPTION
**Pull request by terryjreedy**
The code module uses sys.ps1 if present or sets it to '>>> ' if not.
Test_code_module now properly tests both behaviors.  Ditto for ps2.

https://bugs.python.org/issue31836

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Wouldn't be better to restore `sys.ps1` in test_idle if it is changed here?

**Comment by terryjreedy** [comment]
A program that needs sys.ps1/2 in particular states should set the state it needs.  Test_code_module needs them both unset and set to a non-default string.  Running test_code_module after test_idle exposed the same bug that was exposed previously by running autotest in a Python shell.  The current patch prevents the autotest test_code_module failure that I saw previously.  See the issue for more.

**Comment by terryjreedy** [comment]
The full test suite passes on my Win10 machine.

**Comment by serhiy-storchaka** [comment]
I think this issue should be fixed on both sides. Tests that change module globals should restore them after testing. And `test_code_module` should not depend on the current value of `sys.ps1`, but test all possible situations. The `test.support.swap_attr()` context manager can help here.

**Comment by terryjreedy** [comment]
Tests routine mutate sys.modules and add attributes to other modules without 'restoring' them.  For instance, test_tk adds at least .font, .test, and .ttk to tkinter.  sys.ps1 is at least as expected as these.

However, on reading the IDLE code, I decided it would be improved by adding a PyShell() attribute set from sys.ps1 when it exists, and never modifying sys.  (The code module could do the same.)  I made this a separate issue (bpo-31858) and PR (#4143).  I plan to push both tomorrow.

**Comment by serhiy-storchaka** [comment]
I suggest to not change `sys.ps1` permanently, but restore the old values after testing.

Actually `test_code_module` already contains necessary code for restoring the `sys` module. It only needs to initialize `ps1` and `ps2` properly when they already were set.

**Comment by terryjreedy** [comment]
After the update merge, which included the change to IDLE not setting sys.ps1, test_code_module continues to pass the real test, which is running with `import test.autotest`.

**Pull request merged**
