### PR TITLE
gh-117431: Optimize str.startswith

### PR DESCRIPTION
**Pull request by eendebakpt**
We apply two optimizations in `tailmatch` (which is used in both `str.startswith` and `str.endswith`).

* For one and two character arguments we avoid a call to `memcmp` as all characters have already been checked
* In the call to `memcmp` we can reduce the number of bytes compared since the first and last character have already been checked.

Notes:

Two possible optimizations not included in this PR:

* For the single character case we still do some double work as `PyUnicode_READ(kind_self, data_self, offset) == PyUnicode_READ(kind_sub, data_sub, 0) ` and `PyUnicode_READ(kind_self, data_self, offset + end_sub) ==
        PyUnicode_READ(kind_sub, data_sub, end_sub)` are equal in that case. We can eliminate that by adding something like
```
int first_character_equal = PyUnicode_READ(kind_self, data_self, offset) == PyUnicode_READ(kind_sub, data_sub, 0)
if (PyUnicode_GET_LENGTH(substring)==1) {
   return first_character_equal ;
...
```
This makes the code for the single character case a bit faster, but the code a bit more complex.
* We can make the number of bytes compared even smaller, but we would have calculate a different offset which does not seem worth the effort.

Benchmark (on top of #117466): `python -m timeit -s "s = 'abcdef'" "s.startswith('a')"`
```
main: 10000000 loops, best of 5: 27.2 nsec per loop
PR: 10000000 loops, best of 5: 26.3 nsec per loop
```

* Issue: gh-117431

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Could you add the other optimisations as separate commits?

**Comment by serhiy-storchaka** [comment]
The difference between 27.2 and 26.3 ns is too small and can be the result of unrelated factors. I get a nanosecond variation when run the same command several times.

**Comment by erlend-aasland** [comment]
> The difference between 27.2 and 26.3 ns is too small and can be the result of unrelated factors. I get a nanosecond variation when run the same command several times.

Yes, so I'm curious about the other two mentioned optimisations that are not (yet) part of this PR. Perhaps they have a greater impact.

**Comment by eendebakpt** [comment]
> > The difference between 27.2 and 26.3 ns is too small and can be the result of unrelated factors. I get a nanosecond variation when run the same command several times.
> 
> Yes, so I'm curious about the other two mentioned optimisations that are not (yet) part of this PR. Perhaps they have a greater impact.

I created a PR with the other approach: #117782.

**Comment by eendebakpt** [comment]
Closing this in favor of the alternate PR.

**Pull request closed without merging**
