### PR TITLE
gh-93649: Split unicode tests from _testcapimodule.c & add some more

### PR DESCRIPTION
**Pull request by encukou**
- Move PyUnicode tests to a separate file
- Add some more tests for PyUnicode_FromFormat

This is the refactoring & tests for existing functionality from #95505, leaving the change (and its tests) for another PR.

In addition to the changes in #95505, I made `CHECK_FORMAT_*` to check for SystemError when it gets NULL as the expected result. Some tests need that, as the behavior changed in #95784.

* Issue: gh-93649

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
@encukou, could you please backport this PR to 3.11 and 3.10? It is necessary for backporting #99613, #99651, #99868, and others.

**Comment by encukou** [comment]
I'd rather not -- `_testcapi` is only split up in 3.12. It would need backporting at least some of the other PRs in #93649.
I can rebase #99613 instead, would that help?

**Comment by serhiy-storchaka** [comment]
Are you volunteering to backport also #99651, #99868 and future tests?

**Comment by encukou** [comment]
I can put them on my TODO list.
The C changes are mostly about adding new functions, aren't they?

**Comment by serhiy-storchaka** [comment]
I think that it would be less work to split `_testcapi` in 3.11 and 3.10, so I will try this way.

**Pull request merged**
