### PR TITLE
bpo-37363: Add audit events to the `http.client` module

### PR DESCRIPTION
**Pull request by gousaiyang**
https://bugs.python.org/issue37363

### CODE REVIEW

**Comment by matrixise** [comment]
Hello @gousaiyang 

Thank you for your contribution, really appreciated.

Could you add some tests, for example, you could check in `Lib/tests/test_audit.py` if you need some pointers.

**Comment by gousaiyang** [comment]
Hi @matrixise. If you had time could you review this PR again? Thanks!

**Comment by matrixise** [comment]
Hi @gousaiyang 

Your PR is on my list. I will check it asap.

Thank you

**Comment by matrixise** [comment]
Just forgot to approve the branch, but everything seems fine to me.

@gousaiyang Thank you for your contribution, this one will be only in 3.10

**Pull request merged**
