### PR TITLE
bpo-34426: Fix typo in Misc/SpecialBuilds.txt

### PR DESCRIPTION
**Pull request by danishprakash**
https://bugs.python.org/issue34426

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by pablogsal** [comment]
Hi @prakashdanish and thank you for your contribution. Some things here:

1) You made your PR against the 3.6 branch. Please, direct the PR against the current master and we will backport this if needed.

2) You need to sign the CLA first.

**Comment by pablogsal** [comment]
@prakashdanish Please, branch out from current master and direct the PR against that as stated [here](https://devguide.python.org/pullrequest/).

**Comment by prakashdanish** [comment]
@pablogsal could you look at this again?

**Comment by berkerpeksag** [comment]
@prakashdanish please rebase your branch. It looks like AppVeyor and Bedevere didn't notice the base branch change you've made. They may notice the push event.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks @prakashdanish and congrats on your first contribution to CPython :taco:

**Comment by prakashdanish** [comment]
@Mariatta wow, been reading your posts lately, thanks for the heads up! Looking forward to being a regular contributor.

**Pull request merged**
