### PR TITLE
bpo-5028: fix doc bug for tokenize

### PR DESCRIPTION
**Pull request by andrewnc**
https://bugs.python.org/issue5028

### CODE REVIEW

**Review by eamanu — APPROVED** [review]
LGTM. Please, sign CLA. News could be skipped here.

**Comment by andrewnc** [comment]
I signed the CLA on Saturday

**Comment by asottile** [comment]
I think the "continuation lines are included" bit should be dropped from the doc as well (since it's irrelevant for physical lines)

**Review by csabella — APPROVED** [review]

**Comment by csabella** [comment]
@andrewnc, thank you for your first contribution to CPython!  🎉

**Comment by asottile** [comment]
> I think the "continuation lines are included" bit should be dropped from the doc as well (since it's irrelevant for physical lines)

@csabella oh, I was hoping this would get addressed as part of this PR -- oh well :)

**Comment by csabella** [comment]
@asottile, yes, I probably should have requested that change before merging, but I didn't want to drag this one out.  If you can, please open another PR with that change and I'll see if we can get a quick review on it.  Thanks!

**Comment by asottile** [comment]
@csabella sounds good!  done here: https://github.com/python/cpython/pull/13686 :tada:

**Pull request merged**
