### PR TITLE
bpo-46479: add typing.reveal_locals

### PR DESCRIPTION
**Pull request by JelleZijlstra**
An introspection helper for type checkers that shows the types
of all local variables.

Done on top of the #30646 branch so I can cross-reference the documentation.

We should give the typing-sig thread some more time before moving forward with this, but I'm opening this PR now to gather feedback on the implementation.

https://bugs.python.org/issue46479

### CODE REVIEW

**Review by erictraut — APPROVED** [review]
LGTM

**Comment by JelleZijlstra** [comment]
@gvanrossum this one should also be ready.

**Comment by gvanrossum** [comment]
I thought there was less agreement on this? Or is it a done deal now that reveal_type() is in? (Personally I use the latter all the time but I don't think I've ever used reveal_locals(), so I'm rather lukewarm.)

**Comment by JelleZijlstra** [comment]
I'm also not as enthusiastic about this one as reveal_type. The main reason I added it was that you wrote (on typing-sig):

> I think we should also add reveal_locals() and assert_type(), to promote, document and standardize them.

@erictraut and Martin DeMello also supported adding reveal_locals(); others in the typing-sig thread just discussed the implementation or reiterated concerns about reveal_type().

**Comment by gvanrossum** [comment]
IIRC I wrote that after it seemed many people wanted reveal_locals() if we
were going for reveal_type(). I'd be happy to skip it. assert_type() sounds
more useful.

**Comment by JelleZijlstra** [comment]
I'll send another message to the thread asking people to speak up if they really want reveal_locals(). If nobody likes it we can close this.

**Comment by erictraut** [comment]
FWIW, I don't feel strongly one way or another about `reveal_locals`. I suggested it for completeness.

I agree that `assert_type` is more useful.

**Comment by JelleZijlstra** [comment]
Nobody has spoken out in favor of reveal_locals(), so let's close this. We can always bring it back later if there's more demand.

**Pull request closed without merging**
