### PR TITLE
gh-111506: Implement Py_SET_REFCNT() as opaque function in limited C API

### PR DESCRIPTION
**Pull request by vstinner**
In the limited C API version 3.13, Py_SET_REFCNT() function is now implemented as an opaque function call.

Add _Py_SetRefcnt() to the stable ABI.

* Issue: gh-111506

### CODE REVIEW

**Comment by vstinner** [comment]
> I'd rather not commit to supporting setting the reference count to an arbitrary value in the long term.

I also have concerns about that. But this change is a practical change to make the situation less bad.

I plan to work on a whole PEP to disallow accessing directly PyObject.ob_refcnt and convert more functions to opaque function calls in the limited C API, as Sam describes in the issue.

**Comment by vstinner** [comment]
@colesbury @serhiy-storchaka @erlend-aasland: Would you mind to review this change?

**Comment by erlend-aasland** [comment]
I'll leave this to @colesbury.

**Review by colesbury — APPROVED** [review]
LGTM

I think this only improves our compatibility story going forward. We have already committed to this functionality as part of the API and ABI. Using an opaque function instead of an inline function does not change this.

**Comment by encukou** [comment]
+1 API-wise -- keeping it `abi_only` is the way to go.

**Comment by vstinner** [comment]
Merged, thanks for reviews.

**Pull request merged**
