### PR TITLE
bpo-42064: Move `sqlite3` exceptions to global state, part 1 of 2

### PR DESCRIPTION
**Pull request by erlend-aasland**
Also adds a test to verify the (borrowed) exceptions in `sqlite3.Connection`.

https://bugs.python.org/issue42064

Automerge-Triggered-By: GH:encukou

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@encukou Whenever you have time, would you mind reviewing this as well? I've split this operation in two; moving all exceptions was too large a diff.

**Comment by erlend-aasland** [comment]
I just remembered that all the connection object keeps borrowed references to all the `sqlite3` exception types; we should use that instead of the module state where possible. See 4fe9d983dfa98baaf460eca480df526211c41542.

**Comment by encukou** [comment]
> I just remembered that all the connection object keeps borrowed references to all the sqlite3 exception types

I see the connection type is created with `PyType_FromModuleAndSpec`, so connections hold a reference to the module through their type. (So the module is kept alive and the connections can borrow from it safely).
But, borrowed references tend to be confusing – you always have to think about things like this, even in the future as changes made in seemingly unrelated parts.
Is it worth it to update them to strong references? Or just one strong reference to the module?

**Review by encukou — APPROVED** [review]
The changes themselves look OK!

**Comment by erlend-aasland** [comment]
> But, borrowed references tend to be confusing – you always have to think about things like this, even in the future as changes made in seemingly unrelated parts.
> Is it worth it to update them to strong references? Or just one strong reference to the module?

Yes, I've thought about this. I think updating them to strong references is a good idea.

**Comment by erlend-aasland** [comment]
Thanks for reviewing, Petr!

**Pull request merged**
