### PR TITLE
gh-112213: Update _weakref module to use new AC feature

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-112213

### CODE REVIEW

**Review by colesbury — APPROVED** [review]
Great! Much nicer than manually writing the `Py_BEGIN/END_CRITICAL_SECTION`

**Comment by corona10** [comment]
@colesbury 
One thing needs to be discussed:
Do we have to care about the thread-safe for `is_dead_weakref`?
https://github.com/python/cpython/blob/1a969b4f55f92a17bec82ce0366021a53afdb2c3/Modules/_weakref.c#L45-L56
Or should it be handled from `_PyDict_DelItemIf` since it is only used for `_PyDict_DelItemIf`
https://github.com/python/cpython/blob/1a969b4f55f92a17bec82ce0366021a53afdb2c3/Modules/_weakref.c#L74
https://github.com/python/cpython/blob/1a969b4f55f92a17bec82ce0366021a53afdb2c3/Objects/dictobject.c#L2062-L2069

**Comment by colesbury** [comment]
@corona10, we'll need to handle the thread-safety issues in `_PyWeakref_IS_DEAD()`.

**Comment by corona10** [comment]
> @corona10, we'll need to handle the thread-safety issues in _PyWeakref_IS_DEAD().

Okay let's handle it with upcoming PR :)

**Pull request merged**
