### PR TITLE
bpo-46541: Remove usage of _Py_IDENTIFIER from array module

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue46541

### CODE REVIEW

**Comment by corona10** [comment]
@ericsnowcurrently Should we create the separate bpo issue if module changes are too verbose?

**Comment by ericsnowcurrently** [comment]
This is an extension module so let's avoid using `_Py_ID()`.  I see the module defines `Py_BUILD_CORE_MODULE`, but ideally we wouldn't.  So let's not expand the reliance on internal API.

**Comment by corona10** [comment]
@ericsnowcurrently @erlend-aasland 
PTAL

I try to remove the usage of Py_BUILD_CORE_BUILTIN, but things needed to be discussed before removing them.
So let's handle them as separate issues.

**Comment by ericsnowcurrently** [comment]
> I try to remove the usage of Py_BUILD_CORE_BUILTIN, but things needed to be discussed before removing them. So let's handle them as separate issues.

Yeah, something like that should be handled separately, after any relevant discussion.  Note that not everyone may agree with me that stdlib extensions should not use internal API.  It may be worth asking on python-dev.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Comment by erlend-aasland** [comment]
> This is an extension module so let's avoid using `_Py_ID()`. I see the module defines `Py_BUILD_CORE_MODULE`, but ideally we wouldn't. So let's not expand the reliance on internal API.

FYI, relevant bpo's:
- https://bugs.python.org/issue43974
- https://bugs.python.org/issue41111

As far as I can remember, there has not been any discussion on python-dev or Discourse (yet). I'm pretty sure Victor is interested in starting such a discussion. He's off CPython this week, but we can hear with him sometime next week.

**Comment by erlend-aasland** [comment]
BTW, this PR looks good to me :)

**Comment by ericsnowcurrently** [comment]
> FYI, relevant bpo's:

Thanks for the links!

> As far as I can remember, there has not been any discussion on python-dev or Discourse (yet). I'm pretty sure Victor is interested in starting such a discussion. He's off CPython this week, but we can hear with him sometime next week.

Sounds good.

**Pull request merged**
