### PR TITLE
Fix trivial typo in idlelib/config.py (GH-2309)

### PR DESCRIPTION
**Pull request by 18z**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by 18z** [comment]
@the-knights-who-say-ni  Sorry about this. I signed the agreement and fixed the github name. 
This is my first PR to cpython. If anything else is missing, please guide me through. : )

**Comment by mlouielu** [comment]
@18z Hi, the CLA signed need to removed by member then it will check it again. otherwise the changed LGTM.

**Comment by 18z** [comment]
@mlouielu thanks : )

**Comment by Mariatta** [comment]
@18z Can you create an account in bugs.python.org, and in that account, add your GitHub username. See this [example](https://cloud.githubusercontent.com/assets/2680980/23276970/d14a380c-f9d1-11e6-883d-e13b6b211239.png) of where to set your GitHub username. Thanks.

**Review by Mariatta — APPROVED** [review]

**Comment by 18z** [comment]
@Mariatta I added my github username in my bugs.python.org account. Thanks. : )

**Comment by Mariatta** [comment]
Ah I see. Is your b.p.o username KunYuChen? In there it KunYuChen is set as the GitHub username, not 18z.

**Comment by 18z** [comment]
Yes, my b.p.o username is KunYuChen. 
I set KunYuChen as the Github username, not 18z. Should I change it to 18z?

**Comment by mlouielu** [comment]
@18z You should used `18z` on bugs.python.org, since this is your GitHub username (not the nickname) I think.

**Comment by Mariatta** [comment]
Since you created this PR using GitHub username `18z`, then in your b.p.o account `18z` should be listed as your GitHub username. That's the only way the bot can check that `KunYuChen` in b.p.o is the same person as `18z` on GitHub.
Hope this makes sense.
Alternatively, if you own the GitHub account `KunYuChen`, then you can keep the current setting, but recreate this PR as using that account.

**Comment by 18z** [comment]
@Mariatta I changed it to 18z. : )

**Comment by Mariatta** [comment]
Great, thanks @18z and congrats on your first contribution to CPython :tada:

Can you please backport this to the 3.6 branch? You can use [cherry_picker.py](https://github.com/python/core-workflow/tree/master/cherry_picker)
or manually using `git cherry-pick -x <hash>` to the 3.6 branch.

The hash to be cherry-picked is `f3e8209152dffd201620c5b5936946a9250ac359`.
Thanks.

**Comment by 18z** [comment]
@Mariatta Sure, I'll do that. Thanks for your guidance. : )
@mlouielu Thanks again. : )

**Comment by Mariatta** [comment]
Thanks @18z and @mlouielu

**Comment by terryjreedy** [comment]
Mariatta, please nosy me (or add me as a reviewer, even though a 2nd review is not needed) on anything involving idlelib so I can make sure the backport happens.

**Pull request merged**
