### PR TITLE
gh-85427: Prevent exits if `ArgumentParser.exit_on_error` is False

### LINKED ISSUE #85427: Argparse.parse_args exits on unrecognized option with exit_on_error=False
BPO | [41255](https://bugs.python.org/issue41255)
--- | :---
Nosy | @rhettinger, @tirkarthi, @matthewhughes934, @jacobtylerwalls, @bigbirdcode, @joshmeranda
PRs | <li>python/cpython#27295</li><li>python/cpython#30832</li>
Files | <li>[exit_on_error_tests.patch](https://bugs.python.org/file49310/exit_on_error_tests.patch "Uploaded as text/plain at 2020-07-09.13:59:50 by @matthewhughes934")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-09.08:40:33.198>
labels = ['type-bug', 'library', '3.9']
title = 'Argparse.parse_args exits on unrecognized option with exit_on_error=False'
updated_at = <Date 2022-01-29.03:10:17.942>
user = 'https://github.com/matthewhughes934'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-29.03:10:17.942>
actor = 'jacobtylerwalls'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-07-09.08:40:33.198>
creator = 'mhughes'
dependencies = []
files = ['49310']
hgrepos = []
issue_num = 41255
keywords = ['patch']
message_count = 10.0
messages = ['373382', '373383', '373385', '373405', '373437', '373440', '373470', '396345', '397975', '401629']
nosy_count = 7.0
nosy_names = ['rhettinger', 'paul.j3', 'xtreak', 'mhughes', 'jacobtylerwalls', 'bigbird', 'joshmeranda']
pr_nums = ['27295', '30832']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41255'
versions = ['Python 3.9']
```

</p></details>

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
[bpo-41255](https://bugs.python.org/issue41255)

The `exit_on_error` docs read:
```
   * exit_on_error_ - Determines whether or not ArgumentParser exits with
     error info when an error occurs. (default: ``True``)
```

From this, I agree with the reporter that all exit paths should raise an exception rather than exit.

https://bugs.python.org/issue46440

Fixes #85427

* Issue: gh-85427

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Looking inside `_parse_known_args`, I see some error paths doing `raise ArgumentError` and others calling `self.error`, without any apparent pattern. If they all did `raise ArgumentError`, that would fix this bug.

**Comment by JelleZijlstra** [comment]
There are other calls to `self.error` elsewhere in the class that may be invoked from `_parse_known_args`, so this still leaves some paths where it may exit. In that sense, your original solution was more robust. I am honestly not sure which solution is better.

**Comment by jacobtylerwalls** [comment]
I found a duplicate with some more discussion: bpo-41255.

From the penultimate comment:

> I'm not sure I like the idea of changing the exit or error methods since they have a a clear purpose and don't need to be repurposed to also include error handling. It seems to me that adding checks to self.exit_on_error in _parse_known_args to handle the missing required arguments and in parse_args to handle unknown arguments is probably a quick and clean solution.

**Comment by jacobtylerwalls** [comment]
Alternative to #27295

**Comment by AA-Turner** [comment]
Backref to #85427 (@jacobtylerwalls please could you update the title to start with gh-85427?).

A

**Comment by jacobtylerwalls** [comment]
@JelleZijlstra Forgive the ping! I just I noticed a duplicate issue (#103498) and PR (#103519) rolled in for this. Do you have a reviewer you might recommend to take a look?

Where we left off was comparing 1.) guarding the calls to `self.error()` or 2.) altering `self.error()` itself.
> I am honestly not sure which solution is better.

I was somewhat convinced by the comment quoted in https://github.com/python/cpython/pull/30832#issuecomment-1024819272. Plus it's more backwards compatible to leave `error()` alone.

**Comment by JelleZijlstra** [comment]
@sobolevn and @barneygale expressed some interest in argparse issues recently. I don't feel strongly here but I'll try to find some time to read up again and form an opinion.

**Comment by sobolevn** [comment]
Also closes: https://github.com/python/cpython/issues/103498

**Comment by sobolevn** [comment]
So, we have at least two PRs that do opposite things.
This PR uses `raise ArgumentError`: https://github.com/python/cpython/pull/30832
And the alternative uses `self.error()` instead: https://github.com/python/cpython/pull/103519

Now, we need to decide what is better :)

**Comment by olgarithms** [comment]
I came across the same issue where creating an `ArgumentParser` with `exit_on_error=False` and passing the wrong type of argument would raise an `argparse.ArgumentError`, but passing an unknown argument would exit the task.

```py
import argparse

parser = argparse.ArgumentParser(exit_on_error=False)
parser.add_argument("--integers", type=int)
parser.parse_args(["--integers", "a"]).  
> argparse.ArgumentError: argument --integers: invalid int value: 'a'
parser.parse_args(["--unknown", "a"])
> usage: olga.py [-h] [--integers INTEGERS]
> olga.py: error: unrecognized arguments: --unknown a
```

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @jacobtylerwalls. I apologize for the fact that this PR was neglected for a long time. The problem has already been solved in a way similar to the way proposed in your PR.

**Pull request closed without merging**
