### PR TITLE
bpo-14156: Make argparse.FileType work correctly for binary file mode…

### PR DESCRIPTION
**Pull request by MojoVampire**
…s when argument is '-'

Also made modes containing 'a' or 'x' act the same as a mode containing 'w' when argument is '-' (so 'a'/'x' return sys.stdout like 'w', and 'ab'/'xb' return sys.stdout.buffer like 'wb').

Expanded tests to cover binary mode, as well as covering mode 'x'/'xb' in general (we had no tests verifying that opening in exclusive write mode actually behaved correctly).

https://bugs.python.org/issue14156

### CODE REVIEW

**Comment by MojoVampire** [comment]
For the record, the failures in the Azure Pipelines environment appear to be caused by the tests being run in some manner that causes sys.stdout/sys.stderr to be replaced with io.StringIO before the tests even start. The tests work fine on AppVeyor and Travis CI because this isn't happening, and work fine locally; I'm having a hard time figuring out what the Azure Pipelines are doing that triggers the problem. It does look like a number of the test support packages will replace stdout/stderr with StringIO instances, but it's not obvious what I can do to trigger that behavior locally so I can try and fix it (possibly by using the same TextIOWrapper subclass I changed test_argparse to use precisely to support this use case).

**Review by auvipy — APPROVED** [review]
good job.

**Comment by Lekensteyn** [comment]
As suggested in the linked Python bug, what about gracefully falling back to plain sys.stdin/sys.stdout if the buffer attribute is not available? That should hopefully reduce the need to add special cases to the test suite and result in simpler test code.

The code looks reasonable otherwise.

**Comment by woodruffw** [comment]
@MojoVampire are you still interested in shepherding this? If not, I can pick up from where you've left off and try to respond to feedback both here and on BPO.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM!

**Comment by serhiy-storchaka** [comment]
Please add a `versionchanged` directive in the docs. And maybe an entry in What's New.

**Comment by serhiy-storchaka** [comment]
Or maybe consider it a bugfix?

**Comment by woodruffw** [comment]
> Or maybe consider it a bugfix?

As an end user: I think it's worth considering a bugfix!

**Pull request merged**
