### PR TITLE
gh-101100: amend references starting with `!~` in gh-127054

### PR DESCRIPTION
**Pull request by ghost**
The references starting with `!~` are not rendered correctly (as pointed out in https://github.com/python/cpython/pull/127054#discussion_r1873069896)

----
📚 Documentation preview 📚: https://cpython-previews--127684.org.readthedocs.build/

* Issue: gh-101100

### CODE REVIEW

**Comment by skirpichev** [comment]
I would rather suggest to revert the datastructures.rst change (and its backports!).  Note that before - short method names were used.

CC @vstinner

**Comment by koyuki7w** [comment]
@skirpichev The purpose of this change is to suppress sphinx warnings (gh-101100). If the short method names are preferable, I think these should be changed to `!append`, `!pop`, etc.

**Comment by skirpichev** [comment]
> I think these should be changed to !append, !pop, etc.

Ah, indeed.  That an option.

**Review by vstinner — APPROVED** [review]

**Review by hugovk — APPROVED** [review]
Thanks!

**Pull request merged**
