### PR TITLE
bpo-38034: Fix typo in logging.handlers.rst

### PR DESCRIPTION
**Pull request by wwuck**
https://bugs.python.org/issue38034

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Review by corona10 — APPROVED** [review]
@tomascassidy Looks good to me. Could you like to sign the CLA, please?

**Comment by corona10** [comment]
@vsajip 
This PR looks good to me.
Can you please take a look this PR as the core developer?

**Comment by vsajip** [comment]
Yes, the patch is fine, and can be merged once the CLA is signed.

**Review by willingc — APPROVED** [review]

**Comment by willingc** [comment]
Thanks @wwuck for the PR and @corona10 and @vsajip for the reviews.

**Pull request merged**
