### PR TITLE
bpo-40258: add type hints to random module

### PR DESCRIPTION
**Pull request by nikvaessen**
https://bugs.python.org/issue40258

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@nikvaessen

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by tirkarthi** [comment]
typeshed has the relevant hints : https://github.com/python/typeshed/blob/master/stdlib/3/random.pyi.  Many of the standard library modules are also not hinted.

**Comment by nikvaessen** [comment]
I wasn't aware of the existence of typeshed. Is the general stance on type hints of standard library modules that they should be added to typeshed instead of the source code?

**Comment by rhettinger** [comment]
> . Is the general stance on type hints of standard library modules 
> that they should be added to typeshed instead of the source code?

Yes.

**Pull request closed without merging**
