### PR TITLE
update

### PR DESCRIPTION
**Pull request by abhaychaturvedii**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@abhaychaturvedii

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by brandtbucher** [comment]
Hi @abhaychaturvedii, and welcome to CPython!

I'm not if this PR was made by accident or not. What exactly are you trying to change?

Either way, I'm going to tag this as "invalid" for now since it doesn't have a [bugs.python.org](bugs.python.org) issue, and seems to just be a Polish translation of the comment on line 26 of the same file.

**Review by brandtbucher — CHANGES_REQUESTED** [review]
Either way, I'm going to tag this as "invalid" for now since it doesn't have a [bugs.python.org](bugs.python.org) issue, and seems to just convert our `Grammar` file to Markdown (which breaks everything) with an added Polish translation of the comment on line 26.

**Comment by Mariatta** [comment]
Yes I think this is invalid. Closing.

**Pull request closed without merging**
