### PR TITLE
GH-101777: `queue.rst`: use 2 spaces after a period to be consistent.

### PR DESCRIPTION
**Pull request by OTheDev**
In #102026, I put one space after a period instead of two. The latter is used throughout the file. This PR reintroduces the space that I removed.

cc @ericvsmith 

EDIT: After looking a bit closer, there are other instances where a single space is used after a sentence-ending period rather than two. If desired, I can change those too.

* Issue: gh-101777

### CODE REVIEW

**Comment by ericvsmith** [comment]
If you saw another instance, then yes, I think you should correct that one, too.

**Review by ericvsmith — APPROVED** [review]
Looks good to me. Thanks!

**Comment by erlend-aasland** [comment]
Can we please not start encouraging PRs like this? IMO this is churn and nothing else. Can we please just close this PR, @ericvsmith?

**Comment by hugovk** [comment]
Generally speaking, I wouldn't bother going through fixing more: we usually aim to avoid churn, this doesn't make any difference to end users, and the [devguide](https://devguide.python.org/documentation/style-guide/#use-of-whitespace) says to use one or two.

> A sentence-ending period may be followed by one or two spaces; while reST ignores the second space, it is customarily put in by some users, for example to aid Emacs’ auto-fill mode.

**Comment by erlend-aasland** [comment]
(For the record, I'm _not_ criticising you for anything, @OTheDev)

**Comment by erlend-aasland** [comment]
@OTheDev:
> My aim was to keep the diff to a minimum.

BTW, that is a very good rule to follow for future PRs, both for code and documentation.

**Comment by rhettinger** [comment]
@erlend-aasland In general, I agree that this is mostly a waste of time, but this was specifically requested by a senior core dev in another issue.

**Comment by erlend-aasland** [comment]
@rhettinger, please do not merge PRs marked with _DO-NOT-MERGE_. Merging such PRs is an encouragement for churn in itself.

**Comment by ericvsmith** [comment]
I requested the original change because the PR I was responding to removed a second space, which made the style inconsistent within that file. I don't think it's a problem to restore the recently made inconsistent change, and I also don't think it's a big deal to change the other few places that file was inconsistent.

**Comment by gvanrossum** [comment]
Let’s just not encourage such PRs in the future. They really don’t add any value to the code base, they introduce noise in the commit history, and waste resources.

Also note the prominent heading in PEP 8, https://peps.python.org/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds.

**Comment by erlend-aasland** [comment]
Also, this now has to be backported, in order to minimise conflicts with future backports, thus creating even more churn.

**Pull request merged**
