### PR TITLE
gh-104683: Rename clinic.test => clinic.test.c

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-104683

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Might be worth backporting this; it'll reduce the risk of merge conflicts in future backport PRs

**Comment by serhiy-storchaka** [comment]
I intentionally made this file having extension different from `.c`, so `clinic.py --make` will not regenerate it.

It makes regenerating it inconvenient, but on other hand, it prevents unintentional regeneration. Otherwise the breaking changes in clinic.py can pass unnoticed, because `make clinic` is ran before clinic tests.

**Comment by erlend-aasland** [comment]
There was consensus on the core dev Discord for this change.

**Comment by erlend-aasland** [comment]
Ideally, I would like to get rid of clinic.test.c, and move all those test to _testclinic.c, to make sure the generated code actually works as expected in Python.

**Comment by erlend-aasland** [comment]
> It makes regenerating it inconvenient, but on other hand, it prevents unintentional regeneration. Otherwise the breaking changes in clinic.py can pass unnoticed, because `make clinic` is ran before clinic tests.

IMO, a better option is to add an `--exclude` option to the clinic CLI and explicitly exclude that file when running `make clinic`.

**Comment by erlend-aasland** [comment]
See https://github.com/python/cpython/pull/107770 for my suggestion to preserve `make clinic` behaviour.

**Comment by serhiy-storchaka** [comment]
Initially I introduced `Lib/test/clinic.test` as a temporary solution, because I was not very familiar with the AC code and did not know how to use it programmatically to generate only an interesting part of output (I still does not know this).  `clinic.test` contains a lot of generated noise unrelated to a purpose of specific test. For example all these ugly struct initializers for `_kwtuple` and `_parser` take too much space.

My hope is that someday someone (maybe you, maybe me) will turn most or all of these tests into proper unit tests.

**Comment by erlend-aasland** [comment]
It sounds to me that your intention harmonises with my desire to turn `clinic.test.c` into functional tests. So we agree, I think.

**Pull request merged**
