### PR TITLE
gh-75743: Remove test_timeout.testConnectTimeout()

### PR DESCRIPTION
**Pull request by vstinner**
Remove test_timeout.testConnectTimeout() which is always skipped since 2009, commit 5b95a1507e349da5adae6d2ab57deac3bdd12f15.

No replacement was found for blackhole.snakebite.net and whitehole.snakebite.net online servers.

* Issue: gh-75743

### CODE REVIEW

**Comment by vstinner** [comment]
cc @serhiy-storchaka 

I don't think that it's worth it to backport this change to stable branches (Python 3.11 and 3.12).

**Comment by serhiy-storchaka** [comment]
Thank you @ewdurbin!

Do you mind to create a PR? You better know what should be changed in comments (currently they contain a recipe for BSD).

**Comment by ewdurbin** [comment]
Sure. I'll send a PR.

**Comment by vstinner** [comment]
> @serhiy-storchaka see https://github.com/python/cpython/pull/109087.

**Running** tests is way better than **removing** them, I close my PR.

**Comment by vstinner** [comment]
> Awesome to see this finally get resolved, some 12-13 years after I initially set up the OpenBSD pf rules on Snakebite :-)

Thanks for snakebites @tpn, it was a great service! I recall it :-)

**Pull request closed without merging**
