### PR TITLE
bpo-32903: Fix a memory leak in os.chdir() on Windows

### PR DESCRIPTION
**Pull request by izbyshev**
https://bugs.python.org/issue32903

### CODE REVIEW

**Comment by izbyshev** [comment]
Should I create a bug report for such simple fixes?

**Review by zhangyangyu — COMMENTED** [review]
Makes sense. But I suggest removing the empty lines to keep code style consistent. And it's better to `return True` instead of `return result` in UNC condition. Also, add a NEWs entry please.

**Comment by izbyshev** [comment]
@zhangyangyu Thank you for reviewing! I've removed the empty lines and also realized that checking for `//` prefix doesn't make sense.
>And it's better to return True instead of return result in UNC condition

Do you mean that `SetEnvironmentVariable` return value should be ignored?

**Comment by zhangyangyu** [comment]
> Do you mean that SetEnvironmentVariable return value should be ignored?
@izbyshev , No, I mean before when it's a UNC path, `TRUE` is returned. Now, `result`(the return value of `GetCurrentDirectoryW`) is returned. Although usually there should be no difference, it's better not to do this.

**Comment by izbyshev** [comment]
> Although usually there should be no difference, it's better not to do this.

Actually, there must *never* be any difference, otherwise it is a bug (if `result` is `0` after `GetCurrentDirectoryW`, we shouldn't even check for UNC condition). I can add `assert(result)` before checking for UNC, but IMO changing the code to explicitly return `TRUE` only in case of UNC path would unnecessarily complicate it.

**Comment by zhangyangyu** [comment]
> but IMO changing the code to explicitly return TRUE only in case of UNC path would unnecessarily complicate it.

The function is declared to return `BOOL`, so it's expected to return `TRUE` or `FALSE`. If you want to return any integer, just declare it as `int`. In the extreme case, is it my fault or the API's fault if `result == TRUE` is false for a function declared `BOOL`.

**Comment by izbyshev** [comment]
@zhangyangyu I totally misunderstood your point, sorry. I thought you were arguing that `result` may somehow be zero before UNC condition check.

If you worry about somebody using `BOOL` constants for testing for truth, I think it's better to simply use `int` since the only caller uses `int` for its own `result`.

**Comment by zhangyangyu** [comment]
Don't change the signature plz. Just add another check to let it return `TRUE`. It's not that bad.

**Comment by izbyshev** [comment]
@zhangyangyu Done!

**Comment by zhangyangyu** [comment]
@izbyshev Seems you can't remove the check for `//`: https://github.com/python/cpython/blob/master/Lib/pathlib.py#L127. I could find some other samples by searching that UNC starts with forward slashes.

And the code would be more explicit if you still use `is_unc_path` and `return is_unc_path ? TRUE : result`.

**Comment by izbyshev** [comment]
`//` or even `/\` can be used when you pass paths to Win32 APIs, but you can't get them back from `GetCurrentDirectory` because they are normalized.

If you want to go deeper, the original `is_unc_path` name is also misleading because a path starting with `\\` is not always a UNC path. It could also be a "local device" path (`\\.\nul`) or a "root local device" path (`\\?\C:\`). See [this post](https://googleprojectzero.blogspot.ru/2016/02/the-definitive-guide-on-win32-to-nt.html) if you're interested. So I've changed the test to be more explicit.

**Comment by izbyshev** [comment]
Regarding `return is_unc_path ? TRUE : result`, this would violate your own concern about returning an `int` from a function that should return `BOOL`.

**Comment by zhangyangyu** [comment]
Okay. But I would suggest changing the checks by a new issue if you are sure and asking our Windows gurus to decide, I really can't decide on that since I don't Windows :-(. Leave this issue only about the memory issue.

> Regarding return is_unc_path ? TRUE : result, this would violate your own concern about returning an int from a function that should return BOOL.

Why? if `is_unc_path` is true, we always return `TRUE` now, if not, `result` is always the return value of `SetEnvironmentVariableW`, a `BOOL`. But wait, the Windows doc of it says it's return value is a just a nonzero but not `TRUE`. :-(

**Comment by izbyshev** [comment]
@zhangyangyu 

> Leave this issue only about the memory issue.

I wanted to take the opportunity to perform a minor cleanup by changing path checks since it doesn't distract from this small issue. But if you insist, I can revert the changes and use the original checks.

> Why? if is_unc_path is true, we always return TRUE now, if not, result is always the return value of SetEnvironmentVariableW, a BOOL. But wait, the Windows doc of it says it's return value is a just a nonzero but not TRUE. :-(

If you care about explicit code, the type of `result` is `int`, and I don't think that making a person track data flow to verify that it's in fact can only be assigned to a `BOOL` value at the particular program point is explicit, especially since it involves looking at MSDN or headers to check `SetEnvironmentVariableW` signature.

**Comment by zhangyangyu** [comment]
Sorry for much bikeshedding. But believe me it's not a good idea to do the cleanup in this issue. Feel free to open a new issue to push that.

**Comment by izbyshev** [comment]
Thank you for reviewing. I don't think it's worth opening a new issue for cleanup since the checks are correct, they are just a bit less clean and optimal than they could be.

**Pull request merged**
