### PR TITLE
turtledemo enhancements

### PR DESCRIPTION
**Pull request by EZLiang**
# [bpo-40056](https://bugs.python.org/issue40056): enhance turtledemo
This is a minor change.
 - Replace underscores with spaces in menu
 - Allow running custom code

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@EZLiang

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by terryjreedy** [comment]
I won't review until you add your github name, EZLiang, to your Evin Liang bpo profile and the red label disappears.

**Comment by csabella** [comment]
@EZLiang, please sign the CLA as per @the-knights-who-say-ni bot's message.

**Comment by csabella** [comment]
@EZLiang, if you are unable to sign the CLA, please close this pull request as we cannot accept it without the CLA.  Thank you!

**Comment by csabella** [comment]
Closing this as the CLA has not been signed after several requests.  It can be reopened once the CLA is signed.

**Pull request closed without merging**
