### PR TITLE
bpo-13691: Fixes pydoc help (or help('help')) to show the doc for help

### PR DESCRIPTION
**Pull request by CuriousLearner**
This is an attempt to fix issue http://bugs.python.org/issue13691

This is another approach which we could take to resolve the issue around the use of help.

Otherwise we could define a protocol such as introducing `__help__` magic method as Nick suggested on the bug.

Please let me know if this needs changes :)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by CuriousLearner** [comment]
CLA is signed and now visible in my account.

cc @ncoghlan

**Comment by ncoghlan** [comment]
Sorry for taking so long to review this @CuriousLearner.

I'm afraid I really don't like the notion of making `pydoc` natively aware of `_sitebuiltins._Helper` - that's two distinct cases of coupling a general purpose module shared across Python implementations to interpreter implementation details that aren't guaranteed to exist outside of CPython.

**Comment by ncoghlan** [comment]
Added the sprint label, as this PR was submitted at the PyCon Pune 2017 core development sprint.

**Pull request closed without merging**
