### PR TITLE
 Improve consistency of colorsys.rgb_to_hsv

### PR DESCRIPTION
**Pull request by seb-hub**
Cache repeated difference to make code easier to read and consistent with colorsys.rgb_to_hls.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@seb-hub

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by nanjekyejoannah — APPROVED** [review]
LGTM, thanks @seb-hub

**Comment by seb-hub** [comment]
Thanks for the fast review, @nanjekyejoannah and @Fidget-Spinner.

**Comment by Fidget-Spinner** [comment]
@seb-hub congrats on landing your first PR in cpython. Hope to see you around :).

**Comment by seb-hub** [comment]
@Fidget-Spinner: It's been quite exciting for me :-)
I will look out for other posibilities to contribute!

**Pull request merged**
