### PR TITLE
Perform 'blurb split' for 3.3.

### PR DESCRIPTION
**Pull request by larryhastings**

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]
Quick perusal LGTM.

**Comment by ned-deily** [comment]
See comments on #2719 for master, e.g. breaking doc builds of `Doc/whatsnew/changelog.rst`.  But I wonder whether we should even bother doing this for 3.3 since it is so close to end-of-life and the `Doc/Makefile` for 3.3 is *much* older, e.g. it doesn't use venv or pip to build docs but rather downloads build tools using svn!  At least, let's hold off on 3.3 until I've had a chance to play with it a bit more.

**Comment by larryhastings** [comment]
I hear and obey--I'll hold off.

If any of the cherry-picks back into 3.3 have `Misc/NEWS.d` blurb entries, I guess you'll have two choices:

1. Manually merge them into `Misc/NEWS`, or
2. Run `blurb split` and `blurb merge` yourself as part of the release process, without checking in any of the intermediary files, just to regenerate `Misc/NEWS`.  Then check your changes to `Misc/NEWS` in. 
 This will have the happy side-effect of also updating your `Misc/NEWS` to the modern aesthetics (e.g. bpo-, section name "macOS").

I think 2. is the way to go, personally; it seems like a very sensible approach to handling the end-of-life 3.3 branch overall.  `Misc/NEWS` will remain where it is so it won't affect the Doc build process.

**Comment by ned-deily** [comment]
Yeah, I think running `blurb split` and `blurb merge` manually during the release tagging makes sense to get the updated references.  I'll plan to do that.

**Pull request closed without merging**
