### PR TITLE
gh-94584: Clarify `tomllib` docs

### LINKED ISSUE #94584: Improve tomllib docs
**Documentation**

The `tomllib` docs could be a bit more clearly written.

### PR DESCRIPTION
**Pull request by kj7rrv**
Closes gh-94584

### CODE REVIEW

**Review by DanielNoord — CHANGES_REQUESTED** [review]
This seems unnecessary as there is no real change to the text other than using `Deserialize` vs. `Read` and `Load`. Although technically correct I'm not even sure if it improves the readability that much.

This doesn't need a news entry.

**Comment by kj7rrv** [comment]
@DanielNoord I made a few other changes, e.g.I combined a few short sentences into longer ones.

**Comment by kj7rrv** [comment]
Okay. Should I close this?

**Comment by DanielNoord** [comment]
I think so, also based on the 👍 my other comment received.

You can look for issues with the `easy` label if you want to find an issue that might be a good starting point for contributing to the project!

**Comment by merwok** [comment]
We do appreciate your efforts to contribute!  If you find something that interests you in the list of issues, and if you’re not sure about some details, feel free to tag me (or ask on the core-mentorship mailing list if you prefer a more private channel).

**Comment by kj7rrv** [comment]
@merwok I've opened a few other PRs, #94583 #94611 and #94612. I'm not sure I did #94612 correctly, because the issue it fixes has been open since 2009. I did check and the bug still exists, so I made a PR. Does it look good?

**Pull request closed without merging**
