### PR TITLE
Remove duplicated text for iterable unpacking

### PR DESCRIPTION
**Pull request by jiasli**
This text is duplicated several lines later in L139-L141: 

https://github.com/python/cpython/blob/c56f9df0498498d17972fe02046fd235c9a6017f/Doc/reference/simple_stmts.rst#L139-L141

Putting it after the first `Else:` causes confusion.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@jiasli

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Numerlor** [comment]
I don't think the else and indentation really improves the readability of the text here as it is implied by it being an another condition. For example something like this would suffice in my opinion
```
Assignment of an object to a target list, optionally enclosed in parentheses or
square brackets, is recursively defined as follows.

* If the target list is a single target with no trailing comma,
  optionally in parentheses, the object is assigned to that target.

* If the target list contains one target prefixed with an asterisk, called a
  "starred" target: <...>

* Otherwise the object must be an iterable with the same number of items as there
  are targets in the target list, and the items are assigned, from left to
  right, to the corresponding targets.
```

**Comment by jiasli** [comment]
@Numerlor, I agree, but I only want to eliminate duplication in this PR as it is obviously wrong. As for the content itself, I will leave it to the python maintainer.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Thanks for your contribution, and sorry it had to wait for so long!

**Pull request merged**
