### PR TITLE
bpo-33266: Add support for all string literals to lib2to3

### PR DESCRIPTION
**Pull request by zsol**
https://bugs.python.org/issue33266

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by ambv** [comment]
Sigh, looks like we need to wait for the bot to update the signed CLA list.

**Comment by ned-deily** [comment]
@ambv, It's not a bot problem.  It's that the PSF administrators need to update the user entry in bugs.python.org (which causes the * to appear).  That's a manual process.  And, apparently, right now they aren't always being notified when someone submits a contributor agreement.   Best to send email to contributors@python.org.

**Comment by ned-deily** [comment]
Of course, once the * appears then you will have a bot problem (and need to remove the CLA not signed label!

**Comment by ambv** [comment]
I'll add a NEWS entry in a separate PR.

**Pull request merged**
