### PR TITLE
docs: macos - change "versiona" to "versions"

### PR DESCRIPTION
**Pull request by RandyMcMillan**
correct a typo.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@RandyMcMillan

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by RandyMcMillan** [comment]
signed CLA

**Comment by tirkarthi** [comment]
Please raise a PR to master. It will be backported once the fix was merged.

**Review by eamanu — CHANGES_REQUESTED** [review]
There are 1165 files to review? please check the PR. :)

**Comment by tirkarthi** [comment]
@RandyMcMillan I suggested to create a new branch from master and then to make a PR.

**Comment by willingc** [comment]
Please resubmit a pull request that only includes the documentation change not other development history. If you do your development on a branch, that should prevent the extra commits from being part of the PR.

**Pull request closed without merging**
