### PR TITLE
bpo-30156: Fix a crash in debug build when PYTHONDUMPREFS is set.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Apply an alternate patch from bpo-26811.

https://bugs.python.org/issue30156

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
See discussion on the issue.

**Comment by serhiy-storchaka** [comment]
Excuse me, @haypo, I have not understood what changes did you request.

**Comment by vstinner** [comment]
"See discussion on the issue." means see my comment on the issue: http://bugs.python.org/issue30156#msg292239 Basically, I asked if the optimization is worth it.

**Comment by vstinner** [comment]
I removed the optimization instead: PR #9541.

**Pull request closed without merging**
