### PR TITLE
gh-111128: Remove `expectedFailure` from `test_bad_new` in `test_descr`

### PR DESCRIPTION
**Pull request by sobolevn**
* Issue: gh-111128

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
It is wrong. You changed the meaning of the test.

**Comment by sobolevn** [comment]
@serhiy-storchaka can you please clarify: what was the meaning of this test? It is rather hard to decipher though years and the fact that it is expected to fail.

**Comment by sobolevn** [comment]
Found https://github.com/python/cpython/issues/49572

**Comment by vstinner** [comment]
What is the point of keeping a test which is skipped for a long time?

**Comment by serhiy-storchaka** [comment]
It is not skipped. It tests that the bug is still here. When the bug is fixed, the `@expectedFailure` decorated test will suddenly fail and we finally remove the decorator.

**Comment by vstinner** [comment]
Oh ok, now I get it. It's unusual to write a test in the "reverse" way.

**Comment by serhiy-storchaka** [comment]
There was a solution of the bug, but it had a side effect, so it was reverted. Any new solution should pass these tests.

**Pull request closed without merging**
