### PR TITLE
[3.6] bpo-29854 Backport for 3.6

### PR DESCRIPTION
**Pull request by nirs**
Backport the related patches for this bug to 3.6.

@berkerpeksag, @haypo this will merge the related patches into one patch in 3.6, is this the way we backport patches?

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Yes, this is the correct way to backport multiple PRs that are related to the same issue.

I think we can skip backporting 6618e1fc8e2f06a13407c26b47a29b4777f845b5 for now. It was mainly merged to debug the test failure that we already fixed in 76dde7df682a7753e3e5ae38b2c9da872c3dfae2.

**Comment by Mariatta** [comment]
I added [3.6] to the title :)

**Comment by nirs** [comment]
Changes in version 2:
- remove 6618e1f (berkerpeksag)

Thanks for fixing the title @Mariatta.

**Comment by berkerpeksag** [comment]
Thanks, @nirs!

**Pull request merged**
