### PR TITLE
bpo-29703: asyncio: Fix creating new event loops in child processes.

### PR DESCRIPTION
**Pull request by 1st1**
Proxy issue for https://github.com/python/asyncio/pull/497

### CODE REVIEW

**Comment by 1st1** [comment]
The PR is already reviewed by @fafhrd91.

**Comment by tiran** [comment]
Minor nit pick: The title is slightly confusing. To me a subprocess implies fork+exec. The fix is about fork, so 'child process' or 'forked child' is more descriptive.

**Comment by 1st1** [comment]
@tiran It's not only about explicitly forked (with `os.fork()`) child processes, it's also about subprocesses created with `multiprocessing`, or even `concurrent.futures.ProcessPoolExecutor`. All in all I agree you wording is better, will update the commit/news message.

**Comment by 1st1** [comment]
@tiran @haypo Could you please approve this PR? This needs to go in 3.6.1 tomorrow.

**Comment by 1st1** [comment]
See also 902e9c50e31209e796b6bbe26f8d2f57ec12071b, 80fbacc9369c07daeea6a50a61d214820bb29874, 2ef08d3be780457c444741b67e6181675b044be9.

**Pull request merged**
