### PR TITLE
bpo-41611: IDLE: fix freezing on completion on macOS

### PR DESCRIPTION
**Pull request by taleinat**
https://bugs.python.org/issue41611

### CODE REVIEW

**Comment by taleinat** [comment]
CC @E-Paine, @csabella, if one of you can confirm this on macOS that would be helpful.

**Comment by E-Paine** [comment]
Fix works on my system.

**Comment by taleinat** [comment]
> Fix works on my system.

Thanks @E-Paine!

**Comment by E-Paine** [comment]
Can we add a test for this, to ensure it doesn't occur in the future?

**Comment by taleinat** [comment]
> Can we add a test for this, to ensure it doesn't occur in the future? Edit: is that possible?

Possible but hard, and we don't have the infrastructure for it yet.

We'd need a way to run IDLE in a sub-process, send events, inspect what happens, and close it cleanly.

We could add a specific h-test for this, but IMO that wouldn't be worth it.

**Comment by terryjreedy** [comment]
I verified the fix on installed .0b1 on Mac by #ing the line.  Both Tab and .[popup] work great.  Thank you Tal and others for fixing this and getting it, I hope, into .0b2!!!

The last line of autocomplete_w.py: `# TODO: autocomplete/w htest here`.  I added this, and now put it on my classified list of issues to work on.  It is definitely worthwhile because part of the test, besides working, is 'Does this widget look OK?'.  This must be about the last visible widget that is not h-tested.

@E-Paine If you want to try this, use the calltip h-test as a model.  (and that one should be extended if possible to test force-open).

**Pull request merged**
