### PR TITLE
Issue 46771

### PR DESCRIPTION
**Pull request by Tinche**
Turned the CancelScope into a slotted dataclass. It's how I would do it, but dunno if it's ok for the stdlib sensibilities.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Tinche

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Tinche** [comment]
I've signed the CLA FWIW, guess it takes a while to process.

**Comment by Tinche** [comment]
@asvetlov I don't think this is the best way to collaborate on this.

Instead of your main PR being `python->python`, and my PRs being `asvetlov->python`, can your PR be `asvetlov->python`, and my PRs be `asvetlov->asvetlov`? That just makes more sense to me.

@JelleZijlstra these arguments are essentially all internal, the end users will use wrappers in the module. And for broader context, I am trying to collaborate with Andrew on a different PR, so this was meant for Andrew first.

**Comment by asvetlov** [comment]
> an your PR be asvetlov->python, and my PRs be asvetlov->asvetlov? 

Now the PR is set up exactly to this. Base branch selects where the PR lands.

**Comment by asvetlov** [comment]
I don't like dataclass usage here:
1. All other asyncio classes don't use dataclasses
2. The dataclass usage is not completely hidden, `dataclass.replace()`, `dataclass.fields()`, `dataclass.asdict()` are implicitly supported. Do you really want to provide this?
3. If we decide to provide C Extension in the future, dropping dataclass support can break backward compatibility potentially.

**Comment by Tinche** [comment]
Ok, noted.

**Pull request closed without merging**
