### PR TITLE
gh-120560: Mark `zip64` tests in `test_zipimport` as cpu-heavy

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-120560

### CODE REVIEW

**Comment by ncoghlan** [comment]
I think bedevere is right on this one: there should be a NEWS entry in the test section noting that running these tests now requires the `cpu` resource.

The change itself looks fine, though.

**Comment by nineteendo** [comment]
From [the devguide](https://devguide.python.org/core-developers/committing/index.html#changes-that-require-news-entries):

> Most changes made to the codebase deserve an entry in [Misc/NEWS.d](https://github.com/python/cpython/blob/main/Misc/NEWS.d), except for the following:
>
> - test changes

**Comment by Eclips4** [comment]
> I think bedevere is right on this one: there should be a NEWS entry in the test section noting that running these tests now requires the `cpu` resource.
> 
> The change itself looks fine, though.

Previously when were doing the same thing, we didn't write a NEWS entry, for example: #118801. 
But if you want a NEWS entry, I wouldn't argue 🙂. We could write something like ``Due to high CPU utilization, zip64 tests in test_zipimport were marked as a cpu-heavy tests.``

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
Thanks!

**Pull request merged**
