### PR TITLE
[3.13] gh-118658: Modify cert generation script to extract cert3.pem (GH-124598)

### PR DESCRIPTION
**Pull request by felixfontein**
(cherry picked from commit 480354dc236af9ae9d47b2520aa85fb7293c7b68)

* Issue: gh-118658

### CODE REVIEW

**Comment by felixfontein** [comment]
The failed CI run seems to be unrelated.

**Comment by picnixz** [comment]
I've manually relaunched the tests just to have a green mark.

**Comment by picnixz** [comment]
cc @Yhg1s since this could be something worth integrating

**Comment by encukou** [comment]
This should go into 3.13.1, not the upcoming .0.

**Pull request merged**
