### PR TITLE
bpo-42584: Update macOS installer to use SQLite 3.34.0

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue42584

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Thanks, @ned-deily!

**Comment by erlend-aasland** [comment]
BTW, I'm (currently) unable to open PR's for 3.8 and 3.9 using the cherry-picker bco. GitHub connection issues. You may have better luck, @ned-deily.

**Comment by ned-deily** [comment]
@erland-aasland, are you able to use "git cherry-pick <master-hash>" from the command line? It's a useful skill for a maintainer :) What sort of problem are you having?

**Comment by erlend-aasland** [comment]
> @erlend-aasland, are you able to use "git cherry-pick " from the command line? It's a useful skill for a maintainer :) What sort of problem are you having?

I have no problem running the cherry-picker, thank you ;) As you see from the PR log, my backports reference this PR. However, if I try to _create_ the PR's (from my fork to cpython), GH times out. At first I assumed it was a network issue, but I've been getting the same timeout error until today, so now I assume it's a permission error of some sort. I'll restore the branches and give it another shot.

**Comment by ned-deily** [comment]
Looking good!  Cherry-picking from the commit in the cpython master branch is the way to go rather than from your own branches.

**Comment by erlend-aasland** [comment]
Indeed. I'll remember not to use the `--no-push` option the next time.

**Pull request merged**
