### PR TITLE
bpo-5680: IDLE: Add run module with arguments to Key-F7 in editor

### PR DESCRIPTION
**Pull request by louisom**

### CODE REVIEW

**Comment by Blacksilver42** [comment]
Please merge this.

**Comment by Forkest** [comment]
Such an important feature that makes debugging of programs with mandatory arguments impossible without ugly code change. At least for `argparse`-based scripts, and `argparse` is a part of the default library...

**Comment by rhettinger** [comment]
It would be nice if this would move forward.

**Comment by mcepl** [comment]
@louisom well, this needs certainly rebase on the top of the current master to fix those conflicts.

**Comment by terryjreedy** [comment]
Three requests in 10 days raises the priority of this issue.  As explained on the issue, I am closing this in favor of starting fresh.
@mcepl, @Forkest, @Blacksilver42 If you have tracker accounts and add yourselves as nosy to bpo-5680, you will ge notified of a new PR and can test and comment on the design.

**Comment by csabella** [comment]
@terryjreedy, would you like me to open a new PR with this one as the starting point?  Since this has 'unknown repository', we wouldn't be able to push to it anyway.

**Comment by Forkest** [comment]
The new pull request is #13763

**Pull request closed without merging**
