### PR TITLE
bpo-9495: argparse unittest tracebacks are confusing if an error is raised when not expected

### PR DESCRIPTION
**Pull request by alclarks**
Hi,

This is my first contribution to CPython - fixing the issue at https://bugs.python.org/issue9495

@brandtbucher 

https://bugs.python.org/issue9495

### CODE REVIEW

**Comment by brandtbucher** [comment]
Thanks for the PR @alclarks!

**Review by brandtbucher — APPROVED** [review]
This looks like a good change to me!

**Comment by brandtbucher** [comment]
@rhettinger

**Comment by alclarks** [comment]
Hi @rhettinger, if this change looks good can it please be merged?

**Review by aeros — APPROVED** [review]
Thanks for the PR @alclarks! Sorry for the wait, LGTM.

**Review by taleinat — APPROVED** [review]
LGTM too :)

**Comment by taleinat** [comment]
Congrats on your first contribution to Python, @alclarks! 🎉

**Pull request merged**
