### PR TITLE
bpo-46399: Expose DictKeysType, DictValuesType, and DictItemsType in …

### PR DESCRIPTION
**Pull request by kumaraditya303**
…types module

https://bugs.python.org/issue46399

### CODE REVIEW

**Comment by AlexWaygood** [comment]
It would be good to add a line into the NEWS entry about _why_ we're exposing them in `types` — something like "this makes it easier to add type annotations to certain mapping types"

**Comment by kumaraditya303** [comment]
> It would be good to add a line into the NEWS entry about _why_ we're exposing them in `types` — something like "this makes it easier to add type annotations to certain mapping types"

That would be better in whatsnew of 3.11 I think.

**Comment by AlexWaygood** [comment]
> > It would be good to add a line into the NEWS entry about _why_ we're exposing them in `types` — something like "this makes it easier to add type annotations to certain mapping types"
> 
> That would be better in whatsnew of 3.11 I think.

Good point.

**Review by AlexWaygood — CHANGES_REQUESTED** [review]
As part of this PR, could you add an entry in "What's New in Python 3.11", as discussed in the BPO issue? Thanks!

**Pull request closed without merging**
