### PR TITLE
[3.12] gh-108303: Move all inspect test files to `test_inspect/` (GH-109607)

### PR DESCRIPTION
**Pull request by sobolevn**
(cherry picked from commit 732532b0af9d1b5c7ae4932526c8d20d86c15507)

* Issue: gh-108303

### CODE REVIEW

**Comment by vstinner** [comment]
> @vstinner we need this PR to get backported: https://github.com/python/cpython/pull/109403

It became impossible to backport a single regrtest change, the 3.12 and main branches became too different. So I wrote PR #110758 to copy regrtest files from main to 3.12 branch.

**Comment by vstinner** [comment]
Can you please rebase your PR on the 3.12 branch to solve the libregrtest merge conflict?

**Comment by sobolevn** [comment]
Should be good now! Thanks a lot for your backport PRs! They are really helpful.

**Comment by vstinner** [comment]
I was feeling lucky and tried automated backport...

@sobolevn: Do you want to try to backport to 3.11? Otherwise, I can try to backport.

**Comment by sobolevn** [comment]
Will do tomorrow.

**Pull request merged**
