### PR TITLE
Correct some "-operator" mentions

### PR DESCRIPTION
**Pull request by andresdelfino**

### CODE REVIEW

**Comment by andresdelfino** [comment]
> 
> 
> What is wrong with the current wording?

"X operator" is not a compound term to be written as "X-operator".

**Comment by serhiy-storchaka** [comment]
What is wrong in `double-star-operator`? And what about ``` ``*``\ -operator ```?

**Comment by andresdelfino** [comment]
> 
> 
> What is wrong in `double-star-operator`? And what about `` ``*``\ -operator ``?

My previous reply applies to both cases: "X-operator" is not a compound term to be written as such.

Regarding "double-star": it isn't referred with that name in any other place in the documentation, while "**" is, even where the "double-star-operator" reference point to.

**Comment by andresdelfino** [comment]
> 
> 
> Sorry, I'm not competent to review this PR.

It' alright :) Neither of us is a native English speaker. We are just doing our best.

**Review by scotchka — APPROVED** [review]
I think the changes are reasonable. The meaning is clear without the dash, which is visually cluttering. And "**" is more explicit than "double star".

**Review by merwok — APPROVED** [review]

**Comment by andresdelfino** [comment]
@merwok perhaps we can merge this?

**Comment by rhettinger** [comment]
IMO, this should not have been committed.  The prior wording made it clear that the double-star for dictionary unpacking was distinct from the ``**`` operator used to call ``__pow__``.

Please place preference on the intent of the original writer of the docs.

**Comment by andresdelfino** [comment]
Hi, @rhettinger ! While I agree that making it clear that ** does not refer to the operator implemented by __pow__ is great, I don't see how the previous wording made that explicit. Also, note that we are saying "*" instead of "star" while talking about tuple/list unpacking in the previous paragraph, which would cause the same confusion.

I think we could improve the wording by explicitly saying that "**" does not refer to the operator implemented by the special method "__pow__", likewise for "*". What do you think? If you agree, I'll make the PR.

**Comment by scotchka** [comment]
There is an example immediate below the change in collections.rst that should make it clear in context that `**` is not exponentiation:

```
>>> d = {'x': 11, 'y': 22}
>>> Point(**d)
Point(x=11, y=22)
```

A clarifying remark (e.g. "not to be confused with exponentiation") could be helpful, but I don't have a sense of how likely that confusion is.

**Pull request merged**
