### PR TITLE
gh-120057: Rename os.environ.refresh() to invalidate_cache()

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-120057

----
📚 Documentation preview 📚: https://cpython-previews--120808.org.readthedocs.build/

### CODE REVIEW

**Comment by barneygale** [comment]
`reload_from_process()`?

**Comment by vstinner** [comment]
> reload_from_process() maybe?

@barneygale: I suggest you to propose other names in https://discuss.python.org/t/method-to-refresh-os-environ/54774 discussion.

**Review by zooba — APPROVED** [review]
LGTM, but probably get an acknowledgement from someone who might argue against this before merging.

**Comment by vstinner** [comment]
cc @erlend-aasland

**Comment by vstinner** [comment]
According to https://discuss.python.org/t/method-to-refresh-os-environ/54774/101 poll, `refresh()` name is the favorite name. I close this issue.

**Comment by zooba** [comment]
Votes in Ideas are not binding, they're just informative. You should take the proposal to Core Development and see what the actual team thinks.

**Pull request closed without merging**
