### PR TITLE
[2.7] bpo-19225: Lack of c api exceptions doc

### PR DESCRIPTION
**Pull request by cocoatomo**
backports to 2.7 for #881

### CODE REVIEW

**Comment by cocoatomo** [comment]
Travis-CI bypassed docs build (https://travis-ci.org/python/cpython/jobs/217905127) for some reason.
Additional build is needed.

**Comment by cocoatomo** [comment]
> Travis-CI bypassed docs build (https://travis-ci.org/python/cpython/jobs/217905127) for some reason.
> Additional build is needed.

@serhiy-storchaka Would you like to re-run Travis CI build?

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. Is this PR ready for merging or I have missed something?

**Comment by cocoatomo** [comment]
Thank you for the review.

I wonder Travis-CI skipped docs build process of CI build.

> Docs weren't updated, stopping build process.

(from https://travis-ci.org/python/cpython/jobs/217905127#L159)

**Comment by cocoatomo** [comment]
So, I want to confirm that docs merged with this PR can be built successfully.

**Comment by cocoatomo** [comment]
(Sorry, I made a mistake in operation.)

**Comment by cocoatomo** [comment]
@serhiy-storchaka I have built and checked docs on my local machine. Would you like to merge this PR into the 2.7 branch?

**Pull request merged**
