### PR TITLE
Fix typos in docs and docstrings

### PR DESCRIPTION
**Pull request by tirkarthi**
I have limited typos to user facing output and avoided typos in source code comments to reduce diff.

perfoming -> performing
specifiy -> specify
accross -> across
filname -> filename
prepand -> prepend
reminaing -> remaining
atttributes -> attributes
inherints -> inherits
brower -> browser
Informaton -> Information
hostame -> hostname
imput -> input
toogles betweem -> toggles between
Coersion -> Coercion

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
I'm curious did you use spell-checker?
If yes -- what tool?

**Comment by tirkarthi** [comment]
I used aspell and the following command to get a list of words it thinks is a typo. I manually skimmed through the list looking for typos since it also reports variable names, function names etc as typo with the word not in the dictionary and also sometimes reports US/UK spelling difference as typo since the built-in dictionary is not smart. So there might be few typos I could have overlooked.

`aspell list < Lib/**/*py | tr '[:upper:]' '[:lower:]' | sort -u | less`

**Comment by encukou** [comment]
`test_asyncio` seems flaky, it sometimes "alters the execution environment". The same failure happened in the build GH-13754, for example. This looks unrelated to recent changes.
I don't know what I can do to fix it :(

**Comment by asvetlov** [comment]
I hope asyncio tests flakyness was fixed by #13754

**Comment by encukou** [comment]
Yet, a buildbot run for that PR has failed on an asyncio test:  https://github.com/python/cpython/pull/13754#issuecomment-498072913

**Comment by asvetlov** [comment]
I see the comment.
Sorry, I don't see asyncio errors.
The log contains SSL compilation errors, e.g.
```
In file included from /home/dje/cpython-buildarea/3.x.edelsohn-rhel-z/build/Modules/_ssl.c:536:0:
/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z/build/Modules/_ssl/debughelpers.c: In function ‘_PySSL_msg_callback’:
/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z/build/Modules/_ssl/debughelpers.c:34:20: error: ‘SSL3_MT_CHANGE_CIPHER_SPEC’ undeclared (first use in this function)
         msg_type = SSL3_MT_CHANGE_CIPHER_SPEC;
                    ^
/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z/build/Modules/_ssl/debughelpers.c:34:20: note: each undeclared identifier is reported only once for each function it appears in
```
Perhaps it is related to @tiran work for adding ssl debug helpers. I read the error as *s390x RHEL 3.x* has too old OpenSSL version that has no support for debug helpers API (completely or partially).

After that I see tests run.
asyncio test suite has several noisy outputs like 
```
test_communicate_ignore_broken_pipe (test.test_asyncio.test_subprocess.SubprocessFastWatcherTests) ... Future exception was never retrieved
future: <Future finished exception=BrokenPipeError()>
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z/build/Lib/asyncio/subprocess.py", line 173, in _feed_stdin
    await self.stdin.drain()
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z/build/Lib/asyncio/streams.py", line 1415, in drain
    await self._protocol._drain_helper()
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel-z/build/Lib/asyncio/streams.py", line 594, in _drain_helper
    await waiter
BrokenPipeError
ok
```
the test is ok but `BrokenPipeError` print-out should be suppressed.
Unfortunately, these lines are present for a very long time.
I'll fix it soon.
I've scrolled the message down and see 
```
Ran 2206 tests in 71.915s

OK (skipped=101)
test_tk skipped -- Tk unavailable due to TclError: no display name and no $DISPLAY environment variab [...]
make: *** [buildbottest] Error 3
```
No failure report except non-zero build bot exit code.
How to understand this? @encukou could you help me figure out what is wrong? What test is failed?

**Comment by encukou** [comment]
The test was run with `--fail-env-changed` and the result is `ENV CHANGED`, so I assume the issue is reported by:
```
0:16:26 load avg: 16.00 [348/423/1] test_asyncio failed (env changed) (1 min 12 sec)
[...]
1 test altered the execution environment:
    test_asyncio
```

I don't see the actual error, though :(

**Comment by asvetlov** [comment]
Got you. Thanks!

**Pull request merged**
