### PR TITLE
bpo-37305: add MIME type for Web App Manifest

### PR DESCRIPTION
**Pull request by filips123**
Add `.webmanifest` -> `application/manifest+json` to list of recognized file types and content type headers.

Note that `application/manifest+json` is currently not registered with IANA (but it will be soon), so I can move it to `common_types` if needed.

Issue: https://bugs.python.org/issue37305

https://bugs.python.org/issue37305

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by filips123** [comment]
I signed the CLA today so it is currently not updated.

**Comment by filips123** [comment]
Ok, it is now confirmed to be signed.

**Comment by tirkarthi** [comment]
I think you have also reformatted the dictionary and the indentation change makes the diff larger than the one line change done.

**Comment by filips123** [comment]
@tirkarthi I indented all lines because `.webmanifest` key was too long.

**Review by jaraco — APPROVED** [review]
This change looks right to me.

**Comment by jaraco** [comment]
I notice that previously the mapping was ordered by value alphabetically. We should retain that form.

**Pull request merged**
