### PR TITLE
Update unittest.mock.rst

### PR DESCRIPTION
**Pull request by drewmarshburn**
Small grammatical change.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@drewmarshburn

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by bharel — APPROVED** [review]

**Review by bharel — COMMENTED** [review]
Only to Python 3.6? Why not master?

**Comment by tirkarthi** [comment]
Please raise PRs to master unless it's an issue with the specific release branch. 3.6 accepts only security patches. As for the change I am not a native speaker but both versions sound same to me.

**Comment by drewmarshburn** [comment]
Apologies, was not paying attention; changed it to master.

**Comment by csabella** [comment]
Sorry, this is marked as a small change that affected > 1400 files, so I'm going to close it.  Please make a new PR against the master branch with just the change you intend to make.  Thank you!

**Pull request closed without merging**
