### PR TITLE
bpo-40077: Remove redundant cast in _json extension module

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue40077

### CODE REVIEW

**Comment by shihai1991** [comment]
@corona10 Hi, Dong-hee Na, congratulations!

this cast is redundant, right?

**Review by corona10 — APPROVED** [review]
Thanks for catching this :)
Since PyScannerType and PyEncoderType is PyObject*.
Casting is unnecessary things.

lgtm!

**Comment by corona10** [comment]
cc @vstinner

**Comment by shihai1991** [comment]
> Thanks for catching this :)
> Since PyScannerType and PyEncoderType is PyObject*.
> Casting is unnecessary things.
> 
> lgtm!

Thanks,  MAYBE you can try use your merge right in this PR ;)

**Review by vstinner — APPROVED** [review]
LGTM. Usually, we don't accept coding style only changes. But I think that it's ok to make an exception here.

**Comment by vstinner** [comment]
@corona10: Congrats for your first merge ;-)

**Comment by corona10** [comment]
@vstinner Thank you, it is the singularity of life

**Pull request merged**
