### PR TITLE
bpo-20548: Use specific asserts in warnings and exceptions tests

### PR DESCRIPTION
**Pull request by serhiy-storchaka**

### CODE REVIEW

**Review by terryjreedy — APPROVED** [review]
Given         obj = 'abc'
Replacing   self.assertTrue(obj is None, "%s" % obj)
producing  False is not true : abc
with            self.assertIsNone(obj)
producing  'abc' is not None
is a real improvement.

**Comment by terryjreedy** [comment]
The details of the coverage 'failure' seem bogus.  (I guess this has been noticed before.)

**Review by zhangyangyu — APPROVED** [review]
enhancement or bugfix? the labels?

**Comment by terryjreedy** [comment]
I said on the equivalent bytes issue that I consider backports unnecessary since we are very unlikely to introduce a regression that does not affect default.

**Comment by serhiy-storchaka** [comment]
I think that backporting will help to backport new tests.

**Comment by terryjreedy** [comment]
New tests are sometimes not backported either.  I don't know what criteria others use.  For the present case, I believe some of the specific asserts are not in 2.7, and I think that 3.5 should already be security fix only.  I might backport this just to 3.6, or I might decide that other issues are more pressing.  Your decision.

**Pull request merged**
