### PR TITLE
bpo-37304: compiler dosen't support in(de)crement operation

### PR DESCRIPTION
**Pull request by shihai1991**
Before(3.6 version):
image

After this PR merged:
image

https://bugs.python.org/issue37304

### CODE REVIEW

**Comment by shihai1991** [comment]
This PR break back compatibility, so it's need core developers support.

**Comment by skrah** [comment]
I don't think anything needs to be changed here.  Whenever I see something like `x++y` it is probably deliberate like in the following example:

```
>>> from decimal import *
>>> c = getcontext()
>>> c.prec = 1
>>> Decimal("1.9") + Decimal("1.5")
Decimal('3')
>>> Decimal("1.9")++Decimal("1.5")
Decimal('4')
```

Forbidding the latter would be a massive change for (IMO) little gain.

**Comment by skrah** [comment]
I think you should try to gain support for this before a PR; like in bpo-37304, but that one seems closed. :)

**Comment by serhiy-storchaka** [comment]
I concur with @skrah. In addition:

* `Parser/token.c` is autogenerated. You should not edit it manually.
* Your change in `Lib/_pydecimal.py` breaks the algorithm.
* Your change in `Lib/test/sortperf.py` breaks the purpose of the test.

You are trying to solve non-existing problem. It would be more productive to focus on existing problems.

**Comment by shihai1991** [comment]
Thanks, guys. This PR shows my  thought but the scope of influence is beyond my imagination~
Thanks again for everbody's comment about this PR.

**Pull request closed without merging**
