### PR TITLE
bpo-28556: Various updates to typing

### PR DESCRIPTION
**Pull request by ilevkivskyi**
This PR contains various updates from upstream ``python/typing`` repo:
* Added ``typing.Counter`` and ``typing.ChainMap`` generics
* More flexible ``typing.NamedTuple``
* Improved generic ABC caching
* More tests
* Bugfixes
* Other updates

This should be backported to 3.6 and 3.5 branches.

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Oh, this should probably also include a Misc/NEWS update.

**Comment by ilevkivskyi** [comment]
I added a short entry (note that there is no issue for this, so that I referenced this PR #28)

**Comment by gvanrossum** [comment]
How about http://bugs.python.org/issue28556 ?

**Comment by ilevkivskyi** [comment]
OK, I added the reference to the omnibus issue.

**Comment by gvanrossum** [comment]
I'm hoping some core dev will take kindly to this and merge it.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
LGTM, but I don't have the time to do the merge + cherry-picks on this.

**Comment by Mariatta** [comment]
Will cherry-pick shortly

**Comment by Mariatta** [comment]
Cherry-picked in:
https://github.com/python/cpython/pull/78
https://github.com/python/cpython/pull/77

**Comment by ilevkivskyi** [comment]
@Mariatta Thank you very much for taking care of this!

**Comment by gvanrossum** [comment]
Thank you both! I love the new workflows.

**Pull request merged**
