### PR TITLE
gh-93202: Always use %zd printf formatter

### PR DESCRIPTION
**Pull request by vstinner**
Python now always use the ``%zu`` and ``%zd`` printf formats to
format a size_t or Py_ssize_t number. Building Python 3.12 requires a
C11 compiler, so these printf formats are now always supported.

* PyObject_Print() and _PyObject_Dump() now use the printf %zd format
  to display an object reference count.
* Update PY_FORMAT_SIZE_T comment.
* Remove outdated notes about the %zd format in PyBytes_FromFormat()
  and PyUnicode_FromFormat() documentations.
* configure no longer checks for the %zd format and no longer defines
  PY_FORMAT_SIZE_T macro in pyconfig.h.
* pymacconfig.h no longer undefines PY_FORMAT_SIZE_T: macOS 10.4 is
  no longer supported. Python 3.12 now requires macOS 10.6 (Snow
  Leopard) or newer.

### CODE REVIEW

**Comment by vstinner** [comment]
@Yhg1s: Better late than never! The XXX note was added in 2006 by commit 8b87a0b5fcc3db361d720c365273114eef5d9467 ;-)

**Comment by vstinner** [comment]
@methane: Would you mind to review this change?

I found more code to update. I completed my PR. I created the issue #93202 and I added a NEWS entry just in case (if someone gets a build error).

**Review by methane — APPROVED** [review]
LGTM.
Would you add "test-with-buildbot" label before merging this?

**Comment by vstinner** [comment]
>  Would you add "test-with-buildbot" label before merging this?

Sure! That's a good idea!

**Review by erlend-aasland — APPROVED** [review]
lgtm

**Comment by vstinner** [comment]
I'm not sure why the list of pending buildbot jobs is still long 3 hours later. But remaining jobs are very similar of already completed jobs, I don't think that it's worth it to wait for them.

test_launcher is failing on a Windows job, but it's a known and unrelated issue: https://github.com/python/cpython/issues/93005

So far so good, there is no build error.

**Comment by vstinner** [comment]
I also removed this note in the doc as part of this change:

```
.. % Similar comments apply to the %ll width modifier and
```

The ``ll`` printf specifier (ex: ``%lli``) is also part of C99.

**Comment by vstinner** [comment]
Thanks for the review @methane and @erlend-aasland! It's now merged.

**Pull request merged**
