### PR TITLE
Remove name pollution from importlib

### PR DESCRIPTION
**Pull request by NeilGirdhar**

### CODE REVIEW

**Comment by ambv** [comment]
Where do you notice this name polution? Most modules have imports that they don't clear at the end of the module file. This file additionally has `__all__`, ensuring that a star-import won't import non-exported names from this module.

**Comment by NeilGirdhar** [comment]
@ambv 
```python
import importlib
print('sys' in dir(importlib))  # True
from importlib import sys  # succeeds
```
I just thought it would be nice to start cleaning these up.  I usually `dir` packages that I don't know, which is complicated by extraneous names.   It also helps with tab completion in Jupyter.

A lot of libraries like `numpy` keep the list of exported symbols really clean for these reasons.

**Comment by ambv** [comment]
Thanks for your input. We don't do this within the standard library unless there's a memory-related reason. Seems like numpy doesn't either:

```py3
>>> from numpy import sys
>>> sys
<module 'sys' (built-in)>
```

**Comment by NeilGirdhar** [comment]
@ambv I see your point.  The projects I've been looking at recently have started to do this, like JAX.  They put all their source in a _src folder, and then carefully export only the names related to their package.  But I see your point.

**Comment by NeilGirdhar** [comment]
Also, `sys` is not in `dir` of `numpy` even if you can import it, so at least it's not messing with tab completion or discoverability.

**Comment by NeilGirdhar** [comment]
Oh, just to note that it seems that in some places, the library does do this: https://github.com/python/cpython/blob/main/Lib/types.py#L65

**Pull request closed without merging**
