### PR TITLE
gh-75203: Add support for custom compressor in tarfile

### PR DESCRIPTION
**Pull request by insomniacslk**
Exposed interface to specify a custom compressor for `tarfile`.
To achieve this, a new compression type, "custom", and a new keyword argument `compressor` have been added. The compressor has to be a callable with the interface as explained below.

This change just exposes the internal interface. Ideally the interface should be simpler, and just require an input and an output streams to compress/decompress and some modifiers. Additionally the classmethod is not necessary and any callable with the below interface should work. This could be done iteratively in a subsequent commit.

The compressor has to be a class method that takes as input `cls`, `name`, `mode`, `fileobj`, `compresslevel` and `**kwargs`. This is exactly the same interface as the open methods referenced by OPEN_METH in tarfile.py, e.g. `TarFile.gzipopen` or `TarFile.bz2open`.

The stream interface via the internal `_Stream` class is not exposed. As a consequence it is not possible to specify a compressor that uses such interface.

https://bugs.python.org/issue31020

* Issue: gh-75203

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by insomniacslk** [comment]
Update my account on BPO to include my github handle, should be ok now

**Comment by insomniacslk** [comment]
Any chance this could get a look?

**Comment by Mariatta** [comment]
Thanks for the PR. The changes proposed aren't considered trivial, and requires an issue to be created in https://bugs.python.org

Can you first create the issue? Thanks.

**Comment by insomniacslk** [comment]
Sure! Just created http://bugs.python.org/issue31020

**Comment by insomniacslk** [comment]
What are the next steps here? I created the bug on BPO, not sure if now it's just matter of waiting until someone looks at the issue or if there's something to be done on my side. Thanks!

**Comment by encukou** [comment]
To use a custom compressor, pass a file-like object like [`LZMAFile`](https://docs.python.org/3/library/lzma.html#lzma.LZMAFile) as *fileobj*.
Adding dedicated support, as in this PR, would complicate the API and test matrix too much.
See the issue for discussion.

Sorry for the delay in responding. Hopefully, it's better late than never.

**Pull request closed without merging**
