### PR TITLE
gh-74623: Avoid untar errors when write-protected files are tarred twice

### PR DESCRIPTION
**Pull request by catherinedevlin**
Test to demonstrate the problem described in bug 30438, and proposed fix.

* Issue: gh-74623

### CODE REVIEW

**Comment by brettcannon** [comment]
@catherinedevlin there's other changes to tarfile.py. Is that also part of the test or accidental inclusion?

**Comment by catherinedevlin** [comment]
Ah, the latest commit includes a fix for the issue, but I forgot to describe it.  I just edited the PR description.  More here: http://bugs.python.org/issue30438#msg294440

**Comment by brettcannon** [comment]
@catherinedevlin could you also update the title of the PR itself to describe what it's for?

**Comment by MaxwellDupre** [comment]
Tests ok but the line

"Issue 30438: tarring a readonly file twice, then extracting, should succeed"

Appears in test results, please remove or make just simple comment.

**Comment by arhadthedev** [comment]
@catherinedevlin Could you sign the new CLA by clicking `not signed` button in the cpython-cla-bot's message, please?

**Comment by terryjreedy** [comment]
The Ubuntu/pipelines/sanitizer failures are due to 'environment changed'.  Do TEMPDIR files need some sort of manual cleanup?

**Comment by arhadthedev** [comment]
I'll look into the tests this weekend since the author seems to be missing for a while.

**Comment by arhadthedev** [comment]
@terryjreedy The tests are passing now.

To fix the CLA issue, I squashed this PR into gh-103174.

**Comment by terryjreedy** [comment]
Closing since cannot merge due to unfixable CLA issue. 

Note: Not using linux, I know nothing about tarfile.

**Pull request closed without merging**
