### PR TITLE
bpo-35683: Improve Azure Pipelines steps

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue35683

### CODE REVIEW

**Comment by zooba** [comment]
The full APPX test was only in the PR build for testing. The idea is to run it against commits only to avoid adding extra time to PRs while still having a way to check whether we've broken various parts of the distro.

For anyone who doesn't know, you can view CI build status at https://github.com/python/cpython/commits/master (including all the buildbots :) )

**Comment by zooba** [comment]
@reaperhulk Not at all, since the container isn't actually suitable for our needs anyway (nor was the previous one in the build files, which is why I left it referenced). We probably need to set up our own container with the right dependencies for building and testing CPython itself - the base definition for manylinux containers goes past this point, so any derived ones are going to be missing things. They're fine for building binaries (I assume), but not for running our entire test suite.

**Comment by pablogsal** [comment]
This is a false positive/race condition, a re-run is successful:

https://buildbot.python.org/all/#/builders/116/builds/993

**Comment by njsmith** [comment]
Yeah, the standard manylinux image intentionally deletes some libraries that cpython needs to build (because we don't want the particular versions we used to accidentally become something package maintainers depending on).

**Pull request merged**
