### PR TITLE
Run Tools/scripts/reindent.py

### PR DESCRIPTION
**Pull request by vstinner**
Reindent files which were not properly formatted (PEP 8: 4 spaces).

Remove also some trailing spaces.

Leave Lib/test/coding20731.py and Tools/c-analyzer/ unchanged.

### CODE REVIEW

**Comment by vstinner** [comment]
I added labels to backport the changes to reduce the risk of conflicts when backporting other changes. And also to avoid "make patchcheck" issues on backports.

**Review by iritkatriel — APPROVED** [review]

**Comment by vstinner** [comment]
I ran the following command to prepare this change:

```
find -name "*.py" -print0|xargs -0 -n 1 ./python Tools/scripts/reindent.py
```

As I wrote, I reverted changes of Lib/test/coding20731.py and in Tools/c-analyzer/.

**Comment by vstinner** [comment]
I wrote this PR because sometimes I got strange "make patchcheck" errors on the Ubuntu job of Azure Pipelines.

**Comment by terryjreedy** [comment]
In iomenu.py, I am condensing the 4 lines above to 1 and am removing the tab in that PR.

**Comment by vstinner** [comment]
> In iomenu.py, I am condensing the 4 lines above to 1 in https://github.com/python/cpython/pull/94228 and am removing the tab in that PR.

Ok, thanks.

**Comment by vstinner** [comment]
Oh sadly, the test_enum change was wrong. enum does generate a trailing tab.

**Comment by zware** [comment]
In `test_enum`, you could change the trailing tab to `\x09` like the other `\x20\x20` lines.

**Review by ezio-melotti — APPROVED** [review]

**Comment by vstinner** [comment]
> In test_enum, you could change the trailing tab to \x09 like the other \x20\x20 lines.

I mean that enum should not create such tab :-) If someone else wants to change test_enum in a separated PR, please go ahead ;-)

**Comment by vstinner** [comment]
I wrote this PR for socket.py ;-)

**Comment by zware** [comment]
> I mean that enum should not create such tab :-)

Fair enough; that's more on `pydoc` than `enum`, though.

**Comment by vstinner** [comment]
Merged, thanks for reviews!

**Pull request merged**
