### PR TITLE
[3.10] bpo-43739: Fixing the example code in Doc/extending/extending.rst to declare and initialize the pmodule variable to be of the right type (GH-25207)

### PR DESCRIPTION
**Pull request by shreyanavigyan**
In the example code of the Extending Python with C/C++ documentation the pmodule variable (that stores the return value of PyImport_ImportModule) was never declared. This PR fixes the problem by declaring and initializing the pmodule variable.  

(This PR is for documentation version 3.10.)

Issue URL:  https://bugs.python.org/issue43739

https://bugs.python.org/issue43739

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@shreyanavigyan

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by shreyanavigyan** [comment]
Please have a review of my change in the documentation.

(Note: I have not signed the Python CLA because I think a simple fix in the documentation doesn't require it.)

**Comment by shreyanavigyan** [comment]
Please have a review of my PR.

**Comment by shreyanavigyan** [comment]
Please don't pay attention to the unsuccessful checks . Both Travis CI and Azure Pipelines fail with this error in the Documentation Build :- 

```
python3 tools/rstlint.py ../Misc/NEWS.d/next/
[2] ../Misc/NEWS.d/next/Library/2021-04-10-03-30-36.bpo-43478.iZcBTq.rst:1: default role used
1 problem with severity 2 found.
Makefile:204: recipe for target 'check' failed
make: *** [check] Error 1
```
I haven't messed with this file at all but the build fails.

(The same change in the https://github.com/python/cpython/pull/25330 doesn't result in a error).

**Pull request merged**
