### PR TITLE
Fixed incorrect example in functions documentation

### PR DESCRIPTION
**Pull request by hashAbhiBytes**
----
📚 Documentation preview 📚: https://cpython-previews--127293.org.readthedocs.build/

### CODE REVIEW

**Comment by skirpichev** [comment]
It seems you just change indentation.  Now docs even not rendered.  I would appreciate if you start with describing your changes in the pr description.  What you are trying to fix?

I suggest you next time to try build docs locally (see https://devguide.python.org/documentation/start-documenting/), before creating a non-draft pr.

**Review by StanFromIreland — CHANGES_REQUESTED** [review]
You need to fix the indentation as otherwise it will not render.

**Comment by hauntsaninja** [comment]
Closing, the docs render just fine: https://docs.python.org/3/library/functions.html#complex

**Comment by StanFromIreland** [comment]
You linked the current official build and not yours! The link to your build is automatically added to your PR. [Here it is.](https://cpython-previews--127293.org.readthedocs.build/) If you click in to it you will see it crashes.

**Pull request closed without merging**
