### PR TITLE
bpo-36501: Remove POSIX.1e ACLs from temporary test paths in tests that check pe…

### PR DESCRIPTION
**Pull request by native-api**
…rmissions against the default POSIX behavior

https://bugs.python.org/issue36501

### CODE REVIEW

**Comment by zooba** [comment]
You should remove the workaround from .azure-pipelines/posix_steps.yml to see if this fix works independently of mine.

**Comment by native-api** [comment]
@zooba Done. I already tested it locally in CentOS 7, too.

**Comment by native-api** [comment]
Okay, that does it.
See the ticket for general commentary.

**Comment by native-api** [comment]
Since I discovered unexpected drawbacks, I leave it up to you whether it's worth it.

**Comment by native-api** [comment]
Upon consideration, this is a hacky solution and I don't feel good about it.

**Pull request closed without merging**
