### PR TITLE
bpo-39290: Add support for import_as_names for traverse_imports

### PR DESCRIPTION
**Pull request by isidentical**
https://bugs.python.org/issue39290

### CODE REVIEW

**Comment by encukou** [comment]
Could you also add a test for this?

(Note: the suggested reviewers were autoselected by the `import` keyword, and might not know too much about this part of the stdlib. Adding Benjamin as the lib2to3 expert.)

**Review by brettcannon — CHANGES_REQUESTED** [review]
Please add tests.

**Comment by isidentical** [comment]
This is a nice to have feature for outside usages but unfortunately, the current test suite doesn't offer a direct way to test it with the given interface of fixers. 

Also, I am now reconsidering if this suits the concept of lib2to3 fixers and their public utilities. @benjaminp what do you think about supporting these symbols in the fixer for outside usages (e.g: packages like [unimport](https://github.com/hakancelik96/unimport/blob/master/unimport/refactor.py#L7-L20)) ?

**Comment by isidentical** [comment]
[closing as this was an nice-to-have enhancement, and lib2to3 will be deprecated soon and this will probably not going to be in time for 3.9]

**Pull request closed without merging**
