### PR TITLE
typo in difflib

### PR DESCRIPTION
**Pull request by ghost**
Just 3 typos in difflib.

### CODE REVIEW

**Review by corona10 — APPROVED** [review]

**Review by eamanu — APPROVED** [review]

**Comment by tirkarthi** [comment]
Not a native speaker butiff is used with the meaning "if and only if" : https://www.dictionary.com/browse/iff . So the author might have meant the same. cc: @tim-one for review.

**Comment by javadmokhtari** [comment]
@tirkarthi if your idea is true, then I think  `lambda seq: True` can violate this sentence:
`a one-argument function that takes a sequence element and returns true iff the element is junk.`

**Comment by aeros** [comment]
I'm in agreement with @tirkarthi here. It doesn't seem like "iff" is a clear typo, so let's wait for feedback from Tim before moving forward with the PR.

**Comment by tim-one** [comment]
Yes, "iff" is a common technical abbreviation for "if and only if"

https://en.wikipedia.org/wiki/If_and_only_if

You could spell in out in full instead, but removing the "and only if" part would be wrong.

**Comment by aeros** [comment]
@tim-one 
> You could spell in out in full instead, but removing the "and only if" part would be wrong.

Thanks for clarifying, Tim. In that case, I think the PR can be closed. 

@javadmokhtari If you're looking for a good first PR to work on, I'd highly recommend looking into our list of ["newcomer friendly" issues on bpo](https://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=&type=&components=&versions=&dependencies=&assignee=&keywords=22&priority=&status=1&%40columns=status&resolution=&nosy_count=&message_count=&%40group=&%40pagesize=50&%40startwith=0&%40sortdir=on&%40queryname=&%40old-queryname=&%40action=search). I just recently opened a documentation issue that's easy to implement and clearly defined; it would be perfect for a first PR if you're interested: https://bugs.python.org/issue40045.

**Review by nanjekyejoannah — COMMENTED** [review]
I think this is resolved as close. Thanks for your contribution @javadmokhtari .  I will close this. If anyone gets more reasons, please reopen it.

**Pull request closed without merging**
