### PR TITLE
bpo-38371: Remove deprecated `tkinter` split() method

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue38371

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Has been deprecated since Python 3.9.

**Review by serhiy-storchaka — COMMENTED** [review]
Should not function `SplitObj()` be removed?

**Comment by erlend-aasland** [comment]
> Should not function `SplitObj()` be removed?

Indeed. Function 'SplitObj' is not needed anymore. Thanks for the heads up.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for reviewing, Serhiy!

**Pull request merged**
