### PR TITLE
bpo-41521: Replace whitelist/blacklist with allowlist/denylist

### PR DESCRIPTION
**Pull request by vstinner**
Rename "blacklist" parameter of test.support.check__all__() to
"denylist".

https://bugs.python.org/issue41521

### CODE REVIEW

**Comment by vstinner** [comment]
This change is backward incompatible, but test.support doesn't provide any backward compatibility warranty:

"The test package is meant for internal use by Python only."
https://docs.python.org/dev/library/test.html

At least, I wrote a NEWS entry to document the change.

**Comment by serhiy-storchaka** [comment]
Is `denylist` a good name? It does not deny anything. It is just a sequence of non-underscored names which are found in the module's `dir()`, but are absent in `__all__`. It is an opposite to the `extra` parameter. Maybe `skip` or `exclude` be better name?

**Comment by vsajip** [comment]
I agree with Serhiy about `denylist` in this specific instance. Since the parameter intended to specify public-seeming names that should in fact be private, I would suggest a name such as `keep_private` would be most in keeping with the desired intent.

**Comment by serhiy-storchaka** [comment]
They are not necessary private. They are just not imported by star-import. For example `from calendar import *` does not add `January` and `MONDAY` to your globals, but `calendar.January` and `calendar.MONDAY` are public names.

**Comment by vsajip** [comment]
Fair point. So then `dont_export` for the parameter name? (Or maybe `dont_wildcard_export`.)

**Comment by vstinner** [comment]
``dont_export``: check__all__() function doesn't export anything. Maybe ``not_exported``?

> Is denylist a good name? It does not deny anything.

Well, nobody said that "blacklist" was a best term in the first place :-D

@serhiy-storchaka, @vsajip: What do you think of ``ignore`` or ``ignore_list`` name?

**Comment by vsajip** [comment]
IMO `ignore` doesn't convey what the effect of ignoring is, so `not_exported` seems more expressive.

**Comment by vstinner** [comment]
@vsajip: Ok, I modified my PR to use *not_exported* name instead. It's a better name than "blacklist".

**Comment by vstinner** [comment]
@serhiy-storchaka @vsajip: Would you mind to review the updated PR?

**Review by vsajip — APPROVED** [review]

**Comment by vstinner** [comment]
@vsajip @serhiy-storchaka: Thank you for your reviews, "not_exported" is a better name than "denylist" (or "blacklist") ;-)

**Pull request merged**
