### PR TITLE
bpo-42584 : Update Windows installer to use SQLite 3.34.0

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue42584

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@zooba Would you prefer to update the sources repo yourself, or do you want me to create a PR for the amalgamation sources over there?

**Comment by wbrycki** [comment]
Sorry for my question maybe not 100% related to the PR, but:
Is sqlite3 python module installing its own version of sqlite3 system lib?
I'm having trouble basically with the same, to tell sqlite3 python module to use sqlite 3.34 and not some older one provided by the system (debian buster in this case (stable distro), which comes with the older version).

What I have until now is that I compile from source locally and I'm overwriting a symlink to sqlite3 lib:
`ln -sfn $(pwd)/sqlite-3.34/sqlite3 $(which sqlite3)`

but the still, in python, when I import sqlite3 module and check the version with sqlite3.sqlite_version, the older one is shown. Do you maybe know, how can I configure sqlite3 to use a lib from different installation path?

**Comment by erlend-aasland** [comment]
> Is sqlite3 python module installing its own version of sqlite3 system lib?

The Windows and macOS installers found on python.org build their own SQLite library.

> I'm having trouble basically with the same, to tell sqlite3 python module to use sqlite 3.34 and not some older one provided by the system (debian buster in this case (stable distro), which comes with the older version).

Try this:
```
bash$ SQLITE_CFLAGS="-I<path to SQLite 3 include dir>"
bash$ SQLITE_LDFLAGS="-L<path to SQLite 3 lib dir>"
bash$ ./configure CFLAGS=$SQLITE_CFLAGS LDFLAGS=$SQLITE_LDFLAGS
bash$ make
```

**Comment by wbrycki** [comment]
> > Is sqlite3 python module installing its own version of sqlite3 system lib?
> 
> The Windows and macOS installers found on python.org build their own SQLite library.
> 
> > I'm having trouble basically with the same, to tell sqlite3 python module to use sqlite 3.34 and not some older one provided by the system (debian buster in this case (stable distro), which comes with the older version).
> 
> Try this:
> 
> ```
> bash$ SQLITE_CFLAGS="-I<path to SQLite 3 include dir>"
> bash$ SQLITE_LDFLAGS="-L<path to SQLite 3 lib dir>"
> bash$ ./configure CFLAGS=$SQLITE_CFLAGS LDFLAGS=$SQLITE_LDFLAGS
> bash$ make
> ```

I used binary version from here: https://github.com/coleifer/pysqlite3
Thanks anyway!

**Pull request merged**
