### PR TITLE
bpo-44229: In`test_ssl`, ignore spurious EPROTOTYPE on macOS

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue44229

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Backport though to 3.9?

**Comment by pablogsal** [comment]
> Backport though to 3.9? (...maybe even 3.8, since it's breaking CI)

Is the error happening on 3.9 and 3.8? I though this only happened in 3.10 and main

**Comment by pablogsal** [comment]
Ok, I saw https://bugs.python.org/msg396471 :)

**Comment by erlend-aasland** [comment]
I think we've just let it pass as a flakey ssl test earlier. With PEP 644, the ssl tests have been heavily scrutinised :)

**Comment by pablogsal** [comment]
Also, question, in your message there are 3 different exceptions:

```
ConnectionResetError: [Errno 54] Connection reset by peer
```

```
 OSError: [Errno 41] Protocol wrong type for socket
```

```
ConnectionRefusedError: [Errno 61] Connection refused

```

are all of this fixed by this PR?

**Comment by erlend-aasland** [comment]
Yes. Errno 41 always happens in the mock server set up by the test. On the client side, this results in either errno 54 or errno 61.

**Review by pablogsal — APPROVED** [review]

**Pull request merged**
