### PR TITLE
bpo-34397: Remove redundant overflow checks in list and tuple implementation.

### PR DESCRIPTION
**Pull request by sir-sigurd**
https://bugs.python.org/issue34397

Automerge-Triggered-By: @csabella

### CODE REVIEW

**Review by jdemeyer — CHANGES_REQUESTED** [review]
I agree with the comments of Tim Peters on https://bugs.python.org/issue34397: the assertions should check what is actually required.

**Comment by sir-sigurd** [comment]
I reworked assertions as requested.

**Comment by sir-sigurd** [comment]
@tim-one
Does it look OK now?

**Review by tim-one — APPROVED** [review]
Good enough!  Thank you :smiley:.

**Comment by csabella** [comment]
Merging based on @tim-one's approval.

**Pull request merged**
