### PR TITLE
bpo-43434: Clean up after GH-25818

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue43434

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @zooba

**Review by zooba — APPROVED** [review]
Does not require backporting, as the backport of the original issue has the changes already applied.

Whoever merges should make the commit message a little more detailed.

**Comment by erlend-aasland** [comment]
Thanks, @zooba. How about "Remove variable and if statement made redundant in GH-25818"

BTW, the macOS test failure is unrelated (spurious ssl failure).

**Comment by zooba** [comment]
I think having a reference to the function that was changed will be more helpful for searching later.

**Comment by erlend-aasland** [comment]
Good point.

**Pull request merged**
