### PR TITLE
Update susp-ignored.csv

### PR DESCRIPTION
**Pull request by Frenchy408**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by eamanu — CHANGES_REQUESTED** [review]
Hello!, I think some that will be great a comment on the PR explaining it :-)

This PR is open becauase a issue exist?

**Comment by ammaraskar** [comment]
I think this was meant to be a more permanent fix for https://bugs.python.org/issue37644

Let's see if the line change there holds up, if it causes more issues then this sort of fix can be implemented.

**Comment by zware** [comment]
It's not clear what this branch or PR is for (or how exactly it came to be opened in the main repo), so I'm killing it off.

**Pull request closed without merging**
