### PR TITLE
bpo-37472: Remove Lib/test/outstanding_bugs.py

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue37472

### CODE REVIEW

**Comment by jdemeyer** [comment]
I would remove the `NEWS` entry:
- it's not useful for users since it doesn't change CPython in any way
- it's not useful for developers since clearly nobody uses it

**Comment by vstinner** [comment]
> it's not useful for developers since clearly nobody uses it

It's unclear if a developer still uses it or not, so I prefer to document its removal.

**Comment by vstinner** [comment]
I made the NEWS entry way shorter, to not pollute the change.

**Review by zware — APPROVED** [review]

**Comment by vstinner** [comment]
@zware: Thanks for your review. It makes me confident to remove this file ;-)

**Pull request merged**
