### PR TITLE
bpo-35114: Make ssl.RAND_status() return a bool (GH-20063)

### PR DESCRIPTION
**Pull request by ZackerySpytz**
~~ssl.RAND_status() returns either 1 or 0.~~

https://bugs.python.org/issue35114

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
This is a "skip news" PR.

**Review by tiran — CHANGES_REQUESTED** [review]
Please fix the code instead of the documentation. ``RAND_status()`` should return a boolean.

The code is in ``Modules/_ssl.c``, use ``PyBool_FromLong`` instead ``PyLong_FromLong``, update the doc string, then run ``make clinic``.

**Comment by ZackerySpytz** [comment]
I have made the requested changes; please review again.

**Review by tiran — CHANGES_REQUESTED** [review]
Please add news entry with [blurb](https://pypi.org/project/blurb/)

**Comment by ZackerySpytz** [comment]
I originally thought this PR didn't need a news entry.

I have made the requested changes; please review again.

**Review by tiran — CHANGES_REQUESTED** [review]
Could you please rebase the PR and re-generate the clinic file? Thanks!

**Comment by tiran** [comment]
@ZackerySpytz Did you forget to tell Bederver that ``I have made the requested changes; please review again``? This triggers a workflow change and puts the PR back on my plate.

**Pull request merged**
