### PR TITLE
gh-110907: AC: Disallow using `*` with vararg

### PR DESCRIPTION
**Pull request by sobolevn**
* Issue: gh-110907

### CODE REVIEW

**Review by JelleZijlstra — COMMENTED** [review]
Thanks. I don't feel this matters much: it improves consistency with Python, but I feel the TypeVar signature is clearer at a glance with the extra `*`. Maybe cc @erlend-aasland or @AlexWaygood for other opinions.

**Comment by AlexWaygood** [comment]
I haven't taken a proper look at this yet (though at first glance, it looks good). But I agree with @sobolevn that this is a problem worth fixing. I think AC should aim to be as consistent as possible with normal Python syntax in a case like this; doing otherwise leaves room for ambiguity in how it should be parsed, and is going to be confusing for people new to AC, I feel

**Review by AlexWaygood — APPROVED** [review]
LGTM. I chatted to @erlend-aasland offline and I think he's also in favour

**Comment by AlexWaygood** [comment]
Not sure if this will cleanly backport (and probably not worth spending too much time on it if it doesn't), but we may as well give it a go

**Comment by AlexWaygood** [comment]
As I thought!

**Pull request merged**
