### PR TITLE
gh-126357: Remove gettext import guards

### PR DESCRIPTION
**Pull request by tomasr8**
* Issue: gh-126357

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Can this affect other implementations like PyPy?

**Comment by tomasr8** [comment]
I don't know enough about PyPy to be able to answer that :/ Do you know how I could verify that?

**Comment by sobolevn** [comment]
You can take a look at the source code (https://github.com/pypy/pypy prefered way) or ping one of PyPy maintainers :)

I suspect that it won't, but just to be sure.

**Comment by tomasr8** [comment]
Ok so I applied this patch to the vendored stdlib in PyPy and built pypy3.11 without any issues. Importing these modules at runtime does not cause any issues either so I think it should be fine.

The 4 buildbot failures also seem unrelated to this change.

**Review by sobolevn — COMMENTED** [review]
LGTM then! Thanks for checking!

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Comment by serhiy-storchaka** [comment]
I think that if there are some bootstrapping issues with the `gettext` module, they most likely should be solved in the `gettext` module. If there are some issues.

**Pull request merged**
