### PR TITLE
gh-99593: Add tests for Unicode C API

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-99593

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
I have found a bug during testing. I'll extract it into a separate issue later.

I'll write the remaining tests after some rest.

**Review by vstinner — COMMENTED** [review]
If you want me to review this PR, can you please split it into smaller PR? Like start with a shorter PR, wait until it's merged, then move to the next one.

**Comment by serhiy-storchaka** [comment]
I'll split it on three parts:

* higher-level C API corresponding to `str` methods
* lower-level C API
* codecs

**Comment by vstinner** [comment]
> I'll split it on three parts:

Are you talking about creating 3 PRs modifying the same files, or do you consider to have separated C and Python files for "higher-level C API corresponding to str methods"? Maybe it's just fine to put most "unicode" tests in "unicode.c" and "unicode.py" tests.

**Comment by serhiy-storchaka** [comment]
As you suggested, I'll add codecs tests in a separate Python file. The rest of tests will be in `Lib/test/test_capi/test_unicode.py`.

All wrappers will be defined in `Modules/_testcapi/unicode.c`. It is nice that it was separated from `_testcapi.c`.

**Comment by serhiy-storchaka** [comment]
* [ ] #99651
* [ ] https://github.com/serhiy-storchaka/cpython/pull/19
* [ ] https://github.com/serhiy-storchaka/cpython/pull/20

**Comment by erlend-aasland** [comment]
Since part 1 and 2 are merged, and part 3 (gh-104728) is in the queue, I recon we can close this :)

**Pull request closed without merging**
