### PR TITLE
gh-95707: Fix function signature

### PR DESCRIPTION
**Pull request by tiran**
* Issue: gh-95707

### CODE REVIEW

**Comment by markshannon** [comment]
Thanks for fixing this.

It's nice to have runtime type checking, but the error message is not very informative.

> RuntimeError: null function or function signature mismatch

Is it null or not? What function?
Would it be possible to improve the error message, so those of us less familiar with web assembly can fix them?

**Comment by markshannon** [comment]
@tiran Want to run the buildbots on this? 
I'm happy to merge it, otherwise.

**Comment by markshannon** [comment]
I'll take that as a "merge" then :slightly_smiling_face:

**Comment by tiran** [comment]
No need to run buildbots. I verified the patch locally.

It is a bit unfortunate that WASM runtimes and Emscripten do not provide more debug information. The error message is coming from NodeJS, probably from the V8 JavaScript engine itself. There is an outstanding feature request to improve the situation, https://github.com/emscripten-core/emscripten/issues/16126 . `-Wbad-function-cast -Wcast-function-type` detects some mismatches, but it would not detect this mismatch.

@hoodmane has been looking into the problem, too.

**Pull request merged**
