### PR TITLE
Fix changelog phrasing

### PR DESCRIPTION
**Pull request by Siecje**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
@Siecje thank you for the PR! This is a small patch but it would be great if you could sign the CLA. Did you signed it? I can't find your bugs.python.org account at https://bugs.python.org/user?@sort=username

**Comment by Siecje** [comment]
Okay I have signed now.

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
