### PR TITLE
bpo-46644: Fix test_typing test broken by GH-31151 due to a merge race

### PR DESCRIPTION
**Pull request by JelleZijlstra**
https://bugs.python.org/issue46644

### CODE REVIEW

**Comment by vstinner** [comment]
"fix test" is not a great commit title, it doesn't help future developers who will read commits. Would you mind to elaborate that?

Which test? Why was it failing? Is it related to a recent change? etc.

**Comment by JelleZijlstra** [comment]
Good point, how is the new title?

**Comment by vstinner** [comment]
> Good point, how is the new title?

Much better. Practical issue: be careful when you click on the Merge button, GitHub uses the commit title and commit message from Git, not the one on the web page. It's confusing. You can fix it with the form open by GitHub.

I avoid the automerge label to avoid this trap.

**Comment by JelleZijlstra** [comment]
Yes, I always read over the commit message when I merge :)

**Pull request merged**
