### PR TITLE
bpo-29861: release references to multiprocessing Pool tasks

### PR DESCRIPTION
**Pull request by pitrou**
Release references to tasks, their arguments and their results as soon as they are finished, instead of keeping them alive until another task arrives.

### CODE REVIEW

**Comment by pitrou** [comment]
Note that, for some reason, the multiprocessing tests are excluded of the coverage runs, therefore codecov.io is complaining that my PR gets 0 coverage. @brettcannon might know more about this.

**Comment by brettcannon** [comment]
The tests that are being skipped are due to the fact that they re-run a ton of tests that slows the whole coverage run down by a lot. It's possible I was overly aggressive or there's some flag to pass (or create) to minimize going overboard in the coverage report.

**Comment by pitrou** [comment]
I think you could improve the coverage runtimes by using gcc instead of clang. gcc uses `-Og` which speeds up the debug builds a lot (see Travis-CI runtimes). Another possibility would be to use a non-debug interpreter.

**Comment by brettcannon** [comment]
The coverage build is non-debug: https://github.com/python/cpython/blob/master/.travis.yml#L55. As for switching it over to gcc, I'm fine with that (but that's off-topic for this PR and can be discussed in python/core-workflow#46).

**Comment by pitrou** [comment]
> The coverage build is non-debug

Oh, I see. The test suite is slow because it doesn't run in parallel mode. Switching to gcc wouldn't change anything then.

**Comment by brettcannon** [comment]
@pitrou There might be a way to set it up to run in parallel and still correct the proper information, but I have not tried to make that work.

**Pull request merged**
