### PR TITLE
bpo-39235: Check end_lineno and end_col_offset of AST nodes.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue39235

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Should this be backported to 3.8?

Which should be merged first, this one or GH-17925?

Should I still add the test that @pablogsal suggested in GH-17925?

**Comment by serhiy-storchaka** [comment]
I do not want to backport this, because I am not sure that all end positions are correct. If there are incorrect end positions, this can break tests for alternate Python implementations which calculate them correctly.

https://github.com/python/cpython/pull/17926/commits/bab2c121afda5f864bb78b7d833b9d1149c80350 shows the effect of #17925.

**Comment by gvanrossum** [comment]
OK. I suppose you have to recalculate now that GH-17925 has landed?

**Comment by serhiy-storchaka** [comment]
Yes, see https://github.com/python/cpython/commit/bab2c121afda5f864bb78b7d833b9d1149c80350.

**Pull request merged**
