### PR TITLE
gh-89928: consume dev_t with PyLong_FromUnsignedLongLong

### PR DESCRIPTION
**Pull request by AMDmi3**
https://bugs.python.org/issue45767

* Issue: gh-89928

### CODE REVIEW

**Comment by kumaraditya303** [comment]
Can you add a news entry ? https://blurb-it.herokuapp.com/

**Comment by AMDmi3** [comment]
> Can you add a news entry ? https://blurb-it.herokuapp.com/

Sure, done.

**Comment by MaxwellDupre** [comment]
I dont see the following:
`#if defined(__FreeBSD__)
#define DEVICE_MAJORMINOR_T int
#else
#define DEVICE_MAJORMINOR_T unsigned int
#endif`
In your Files changed, please explain?

**Comment by AMDmi3** [comment]
> I dont see the following:

Because it's not there, obviously. This PR only addresses one aspect of the problem.

**Review by MaxwellDupre — APPROVED** [review]
Looks ok.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution, but more complex #31794 was merged instead.

**Pull request closed without merging**
