### PR TITLE
Run make regen-global-objects

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by erlend-aasland** [comment]
When was this regression introduced? There is no linked issue.

**Comment by vstinner** [comment]
> When was this regression introduced? There is no linked issue.

I don't know if it can be qualified as a regression.

It's unclear to me how it is possible to merge a PR if "generated files" are outdated: the GitHub Action job is supposed to fail.

It **seems** like ``make regen-global-objects`` is not deterministic. I don't understand how this issue happened.

**Comment by erlend-aasland** [comment]
I suspect it was 9205dfeca54cb24aa9a984c12a6419d71635be9f

**Comment by vstinner** [comment]
> I suspect it was https://github.com/python/cpython/commit/9205dfeca54cb24aa9a984c12a6419d71635be9f

Yep, this change removes ``_Py_ID(arg)`` in code generated by Argument Clinic. **But** the "Check if generated files are up to date" job on the PR succeeded.

The job does:

```
          # Deepfreeze will usually cause global objects to be added or removed,                    
          # so we run it before regen-global-objects gets rum (in regen-all).                       
          make regen-deepfreeze
          make -j4 regen-all                                                                        
          make regen-stdlib-module-names
```

where `make regen-all`` does depend on ``regen-global-objects``. This target is declared as phony: ``.PHONY: regen-global-objects``. So the ``generate_global_objects.py`` script was run.

Maybe depending on the order in which ``regen-all`` dependencies are executed, the result is different?

**Comment by erlend-aasland** [comment]
> Maybe depending on the order in which `regen-all` dependencies are executed, the result is different?

It sounds like a build system bug to me.

**Comment by vstinner** [comment]
That's the non-deterministic build system bug: https://github.com/python/cpython/issues/108740

**Pull request merged**
