### PR TITLE
Fixed syntax error in asyncio/queues.py

### PR DESCRIPTION
**Pull request by imlegend19**
There was a small syntax error in queues.py pushed in commit [6370f345e1d5829e1fba59cd695c8b82c5a8c620](https://github.com/python/cpython/commit/6370f345e1d5829e1fba59cd695c8b82c5a8c620).

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@imlegend19

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by remilapeyre — CHANGES_REQUESTED** [review]
This is not a syntax error but a format specifier, this is the current repr of Queue:

```
>>> Queue()
<Queue at 0x7ff0f021e970 maxsize=0>
```

The address of the object is using hexadecimal like all other objects. This is the repr of Queue with this change:

```
>>> Queue()
<Queue at 4316397648 - maxsize=0>
```

The old one is correct.

**Comment by imlegend19** [comment]
Sir, the `'` opened is not closed, how is that valid?

**Comment by remilapeyre** [comment]
> Sir, the `'` opened is not closed, how is that valid?

It's closed at the end of the line:

`         return f'<{type(self).__name__} at {id(self):#x} {self._format()}>'`

The f-string is `f'<{} at {} {}>'` with three expressions:

- `type(self).__name__`
- `id(self):#x`
- `self._format()`

The first and the last are simple, the second is `id(self)` with the format specifier `#x` whose meaning is "hexadecimal with `0x` in front" (https://docs.python.org/3.8/library/string.html).

As you can see `#` here is not a command so the f-string is correct.

**Comment by imlegend19** [comment]
Okay, thank you for the clarification.

**Pull request closed without merging**
