### PR TITLE
Revers 25134 regen stable abi

### PR DESCRIPTION
**Pull request by IchspontenEr**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@IchspontenEr

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by IchspontenEr** [comment]
> _Keine Beschreibung angegeben._

CHIKER DELS

**Comment by IchspontenEr** [comment]
<a href="https://twitter.com/TwitterDev?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @TwitterDev</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by IchspontenEr** [comment]
CHIKER DELS
CHOKER-MODELLE

**Comment by terryjreedy** [comment]
There are clearly multiple things wrong with this PR.  It mixes old master commits with buildbot changes; github cannot display the diff; no issue is referenced; is comes from a first-time contributor who has not signed the CLA; the last comments look like spam.  Closing.

**Comment by terryjreedy** [comment]
The `revert-25134-regen_stable_abi` source branch is also a python/cpython branch rather than a fork branch, as I expect it should be.  I believe it should be deleted but I am leaving this to Brett or another cpython admin.

**Comment by IchspontenEr** [comment]
www .sudo .ws /
repos / sudo #25090

**Pull request closed without merging**
