### PR TITLE
bpo-32726: macOS installer and framework enhancements and changes for 3.7.0

### PR DESCRIPTION
**Pull request by ned-deily**
This issue covers various changes for the macOS installers provided via python.org for 3.7.0.

- Provide a provisional new installer variant for macOS 10.9 and later systems with 64-bit (x86_64) architecture only.  Apple has made it known that future versions of macOS will only fully support 64-bit executables and some other third-party software suppliers have chosen 10.9 as their oldest supported system.
 
- Support **Tcl/Tk 8.6** with the 10.9 installer variant.
 
- Upgrade **OpenSSL** to 1.1.0g and **SQLite** to 3.22.0.
 
- The compiler name used for the interpreter build and for modules built with **Distutils / pip** is now _gcc_ rather than _gcc-4.2_. And extension module builds will no longer try to force use of an old SDK if present.

https://bugs.python.org/issue32726

### CODE REVIEW

**Comment by matrixise** [comment]
seems to be ok but I can't test it because I have a linux system maybe at home on this evening with my mac. what are the process for a build on OSX?

**Comment by ned-deily** [comment]
Thanks for the look. Building an installer for review isn't worth attempting; what matters is whether it works for me when I need to build release installers.

**Comment by matrixise** [comment]
Yep, but I am interested by the build of the installer on OSX

**Comment by ihnorton** [comment]
> provisional new installer variant for macOS 10.9 and later systems with 64-bit (x86_64) 

I'd like to make a gentle request for this to be the primary, recommended installer so that the extension ecosystem can definitively standardize on targeting the 10.9 SDK for the 3.7 release cycle. Standardizing on 10.9 would:
- end the [libc++/libstdc++ ABI (in)compatibility issues for extensions using C++](https://github.com/conda-forge/conda-forge.github.io/issues/183)
- dramatically reduce complication for library authors (e.g. Google's [tensorflow won't support 10.6](https://github.com/tensorflow/tensorflow/issues/7294) -- the average library developer community has far fewer resources. Also many C++ packages are now requiring C++11 support, which the 10.6 SDK does not)

A quick look at some stats ([1](https://update.omnigroup.com/), [2](http://gs.statcounter.com/macos-version-market-share/desktop/worldwide)) hints that the share of macOS users on versions < 10.9 is well under 10%, possibly in low single-digits. Though I suppose the most-relevant number may be python.org visitors -- they appear to use google analytics, which provides a breakdown by macOS version...

**Pull request merged**
