### PR TITLE
bpo-46602: Do not append conftest.c

### PR DESCRIPTION
**Pull request by ghost**
The heredoc creation statements use >> to append conftest.c.  This can cause
tricky build issues if the file is not correctly removed prior to its
name being reused (such name is reused several times for different
contextual tests during the build).  One such result from appending may
cause #include <ac_nonexistent.h> to persist when testing to acquire
PLATFORM_TRIPLET.  This can then lead to downstream issues concerning SOABI.

https://bugs.python.org/issue46602

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@adanhawth

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by arhadthedev** [comment]
You also need to change the corresponding lines of `configure.ac` (so both original `configure.ac` and generated `configure` are amended by this PR):

https://github.com/python/cpython/blob/bebaa95fd0f44babf8b6bcffd8f2908c73ca259e/configure.ac#L835-L836

https://github.com/python/cpython/blob/bebaa95fd0f44babf8b6bcffd8f2908c73ca259e/configure.ac#L1030-L1031

**Comment by ned-deily** [comment]
Thanks for the PR; the changes to `configure.ac` do not seem to present in it and those are more important than the auto-generated `configure` changes.

**Comment by arhadthedev** [comment]
@adanhawth Looking through a list of checks I noticed failed *bedevere/news — No news entry in Misc/NEWS.d/next/ or "skip news" label found*.

I forgot to say that you also need to add a short changelog entry using https://blurb-it.herokuapp.com/add_blurb. It can be, for example, `Fix configure.ac so it fully regenerates conftest.c instead of appending to its previous content.`

I cannot do it by myself because I have no push access to your PR, but it will look like this:

image

**Review by ned-deily — COMMENTED** [review]
The changes look good to me. I gather from the comments that you have experienced "tricky build problems" as configure now stands. For that reason, I think it might be a good idea to add a [NEWS item](https://docs.python.org/dev/whatsnew/changelog.html)  for this change since others might have also run into the problem, assuming the problem description can be meaningfully described in a few lines; see [the description of blurb and blurb-it in the devguide](https://devguide.python.org/#quick-reference).

**Comment by ned-deily** [comment]
@arhadthedev, sorry, I didn't see your comment before I made mine :)

**Comment by ned-deily** [comment]
Thanks again for the PR and congrats on your first cpython PR.

**Comment by adanhawth** [comment]
You're welcome.  Thank you, both, for the timely feedback.

**Pull request merged**
