### PR TITLE
add a feature on my updater billbill

### PR DESCRIPTION
**Pull request by et2300**
#

### CODE REVIEW

**Comment by et2300** [comment]
Screenshot_2023-06-17-18-23-49-26_a2cf8efcdd42a8e6f7906303f104fb67
#
Screenshot_2023-06-17-18-24-16-10_a2cf8efcdd42a8e6f7906303f104fb67

**Comment by et2300** [comment]
@phsilva ping

**Comment by arhadthedev** [comment]
It seems you've cheated a pull request in a wrong repository. This is https://github.com/python/cpython, a home of the reference Python interpreter.

**Comment by arhadthedev** [comment]
It seems you've created a pull request in a wrong repository. This is https://github.com/python/cpython, a home of the reference Python interpreter.

**Comment by arhadthedev** [comment]
`git bisect` points to 8af8f52d175959f03cf4a2786b6a81ec09e15e95 (gh-102003). @barneygale

<details><summary>How I performed the search, for reproducibility</summary>

- script

   ```bat
   git bisect start
   git bisect good v3.11.0
   git bisect bad main
   git bisect run .\gh-105881.cmd
   ```

- `gh-105881.cmd`:

   ```bat
   @echo off
   setlocal EnableDelayedExpansion

   git clean -fx -e gh-105881*
   call pcbuild\clean
   call pcbuild\build

   for /F "usebackq delims=" %%a IN (`call python.bat gh-105881.py`) do (
       if "%%a" == "PureWindowsPath('///tmp')" exit /b 1
   )
   ```

- `gh-105881.py`:

   ```python
   from pathlib import PureWindowsPath
   print(repr(PureWindowsPath(r"\\\tmp")))
   ```

</details>

**Pull request closed without merging**
