### PR TITLE
bpo-34204: Make the shelve library use Pickle's default protocol version instead of defaulting to version 3

### PR DESCRIPTION
**Pull request by marco-c**
https://bugs.python.org/issue34204

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@marco-c

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by marco-c** [comment]
@vstinner r?

**Comment by ZackerySpytz** [comment]
@marco-c Please close this PR -- it is a duplicate. If you want, I can add your name to `Doc/whatsnew/3.10.rst` in my PR.

**Comment by csabella** [comment]
Closing this as the original PR has been merged.

**Pull request closed without merging**
