### PR TITLE
bpo-36139: release GIL around munmap()

### PR DESCRIPTION
**Pull request by sorcio**
https://bugs.python.org/issue36139

https://bugs.python.org/issue36139

### CODE REVIEW

**Comment by vstinner** [comment]
Hum, https://github.com/python/cpython/commit/bb9593af0ac835b93c2834d44b72fa34e30efed0 has been merged. What is this PR?

**Comment by vstinner** [comment]
It seems like this PR isn't written on top of the master branch, currently it means the commit bb9593af0ac835b93c2834d44b72fa34e30efed0.

**Comment by sorcio** [comment]
> It seems like this PR isn't written on top of the master branch, currently it means the commit [bb9593a](https://github.com/python/cpython/commit/bb9593af0ac835b93c2834d44b72fa34e30efed0).

@vstinner I rebased on master now

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
Thanks @sorcio for the quick fix!

FYI I tested manually the fix on my Windows VM with Python compiled in debug mode before merging the PR.

**Pull request merged**
