### PR TITLE
bpo-28331: fix "CPython implementation detail:" label is removed when content is translated.

### PR DESCRIPTION
**Pull request by methane**
[[bpo-28331](https://bugs.python.org/issue28331)]

### CODE REVIEW

**Review by berkerpeksag — CHANGES_REQUESTED** [review]
Sorry, I'm strongly against introducing yet another hack for a pretty small use case.

**Comment by methane** [comment]
@JulienPalard We (Japanese translation team) fixed this in our fork.
I think French documentation should apply same fix too.

**Comment by methane** [comment]
I keep this PR open, until another "NO" from core dev.

**Review by vstinner — APPROVED** [review]

**Comment by methane** [comment]
@berkerpeksag
This pull request changes two thing:

1. Fix "CPython implementation detail:" label disappears when it's body is translated.
   This must be fixed, otherwise people think it's Python's guarantee.
   (Imagine that "CPython implementation detail: This is the address of the object in memory." becomes "This is the address of the object in memory.")

   And this change make the implementation same to version(added|changed) directive in Sphinx.  So I think it's proper implementation rather than hack.  I strongly want to fix this in upstream.

2. Make "CPython implementation detail:" label translatable.
   Untranslatable label is minor problem compared to (1), and this change uses hack (dummy.html to expose label text to pot file via {% trans %} tag).

If you still strong -1 about adding hack,  I'll remove dummy.html. Downstream translation project can add dummy.html by themselves, without touching python source.
But I feel "add this in downstream project" is also hack.

**Comment by berkerpeksag** [comment]
I think matching the implementation of the imp-detail directive with the other custom directives is a good idea -- I don't have an objection to that part of the PR. However, I'm still -1 on adding a dummy HTML.

Customizing the tools of an upstream project is a very common practice in open source world. Downstream projects are doing a lot of different things with Python and this doesn't mean that all these hacks should go into upstream (we've rejected most of them in the past)

**Comment by vstinner** [comment]
I started a thread on python-dev to get an official go for the translated
doc:
https://mail.python.org/pipermail/python-dev/2017-February/147416.html

**Comment by methane** [comment]
I saw most replies on the ML thread is positive.
And I checked this fix works on Sphinx 1.3.3 (docs.python.org uses this version) without any warnings too.

Now I think this change is safe enough to merge, and small enough to maintain.
Feel free to revert it if it cause any regression.

**Comment by methane** [comment]
Since translation will be focus on latest stable release, I removed "needs backport to (2.7|3.5)" labels.
I'll backport this to 3.6 later, if no problem happened at 3.7-dev document.

**Pull request merged**
