### PR TITLE
gh-108303: Move `zip` and `tar` archives to `Lib/test/archivetestdata`

### PR DESCRIPTION
**Pull request by sobolevn**
All archives now live in the same place.

* Issue: gh-108303

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
It's surprising that "ziptestdata" is used by test_tarfile and contains TAR archives. Maybe rename the directory to "archivetestdata"?

**Review by vstinner — COMMENTED** [review]
Lib/test/archivetestdata/README.md says "Test data for test_zipfile". Maybe mention somewhere that now it's also used by test_tarfile, and also test_contextlib?

Also, the README file says "Purpose: These are used to test executable files with an appended zipfile". Is it still the case?

**Comment by vstinner** [comment]
If some test files are specific to "test executable files with an appended zipfile", maybe they should live in a separated directory? I'm not sure if it's worth it. Maybe just list files related to these specific tests?

**Review by vstinner — COMMENTED** [review]
Can you please try to fix the merge conflict?

**Comment by sobolevn** [comment]
Done!

**Comment by vstinner** [comment]
Merged, thanks. I don't know how feasible it is to backport the change to 3.11 and 3.12? @sobolevn: try maybe to add the backport labels?

**Pull request merged**
