### PR TITLE
bpo-44225: Fix bug with asyncio BaseEventLoop.run_forever()

### PR DESCRIPTION
**Pull request by astrobits1**
https://bugs.python.org/issue44225

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@megahypex

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by iritkatriel — CHANGES_REQUESTED** [review]
Please add a unit test which is failing without the fix and passing with it.

**Comment by megahypex** [comment]
```py
import asyncio
loop  = asyncio.get_event_loop()
async def coro(x):
    print(x)
    if x < 10:
        asyncio.create_task(coro(x+1))
    else:
        loop.stop()

loop.create_task(coro(0))
loop.stop()
loop.run_forever()
```
The following code produces the output
```
0
```
(replicated on python version 3.11, 3.10 and 3.9)
With the fixes applied, it produces the following output:
```
0
1
2
3
4
5
6
7
8
9
10
```

**Comment by megahypex** [comment]
I have made the requested changes; please review again

**Comment by iritkatriel** [comment]
The unit tests for this script are in Lib/test/test_asyncio/test_base_events.py
https://github.com/python/cpython/blob/main/Lib/test/test_asyncio/test_base_events.py
This will need to be added as one of the unit tests there.

This might help: https://devguide.python.org/runtests/

**Comment by megahypex** [comment]
I have added a test for this particular bug called ``test_run_forever_iteration_break`` in the file ``Lib/Test/test_asyncio/test_base_events.py``, kindly check.

**Pull request closed without merging**
