### PR TITLE
gh-124855: Fix refleak in sys.activate_stack_trampoline

### PR DESCRIPTION
**Pull request by pablogsal**
* Issue: gh-124855

### CODE REVIEW

**Comment by pablogsal** [comment]
Thanks @Fidget-Spinner for the catch!

**Comment by Fidget-Spinner** [comment]
Not sure what's up with the diff. Think you might've merged something else in :)?

**Comment by pablogsal** [comment]
I will fix it tomorrow :(

**Comment by Fidget-Spinner** [comment]
This is superseded by https://github.com/python/cpython/pull/126166. Sorry Pablo!

**Pull request closed without merging**
