### PR TITLE
Add references to other glossary items

### PR DESCRIPTION
**Pull request by yiannis-had**

### CODE REVIEW

**Comment by hugovk** [comment]
Re-opening, as [GitHub mysteriously closed](https://discuss.python.org/t/what-is-closing-these-prs-and-why/15423/5?u=hugovk) this when the fork was deleted.

**Comment by JelleZijlstra** [comment]
Looks like you incorrectly merged your branch. I'm not sure that's salvageable, could you just open a new PR?

**Comment by yiannis-had** [comment]
Oops, used the GitHub PR UI to change base branch from `3.10` to `main` but it seems to have rebased?

**Comment by hugovk** [comment]
Ah yes, changing the base branch can get a bit messy! Please create a new PR, thanks!

**Pull request closed without merging**
