### PR TITLE
bpo-32637: Set sys.platform to "android" on Android

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue32637

### CODE REVIEW

**Comment by vstinner** [comment]
I abandoned my previous attempt to modify MACHDEP in configure: PR #5287.

**Comment by pmp-p** [comment]
Great, it works on arm7. And anyway MACHDEP won't help for load android abi flavor of modules.

**Comment by vstinner** [comment]
> And anyway MACHDEP won't help for load android abi flavor of modules.

Note: While checking how MACHDEP is used, I found deadcode. I proposed a PR to remove it: PR #5289.

I don't know well the "multiarch" thing and I'm not confortable with autotools, so I chose to write this minimalist and self-contained change which only impacts sys.platform.

**Comment by pmp-p** [comment]
good effects, now instead of tring to load _sysconfigdata_dm/m_linux_.py it seeks for_sysconfigdata_dm/m_android_.py which allow the two flavors to coexist nicely.

**Comment by yan12125** [comment]
Most likely at least MACHDEP should be modified, too.
```
>>> sysconfig.get_config_var('CFLAGS')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/local/tmp/python3/usr/lib/python3.7/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/data/local/tmp/python3/usr/lib/python3.7/sysconfig.py", line 544, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/data/local/tmp/python3/usr/lib/python3.7/sysconfig.py", line 415, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_android_'
```
In my build tree, there's ```build/target/python/usr/lib/python3.7/_sysconfigdata_m_linux_.py``` but no ```build/target/python/usr/lib/python3.7/_sysconfigdata_m_android_.py```. If I understand the build process correctly, _sysconfigdata file is generated via ```$(PYTHON_FOR_BUILD) -S -m sysconfig --generate-posix-vars``` call in ```Makefile.pre.in```, and ```PYTHON_FOR_BUILD``` uses ```MACHDEP``` via ```_PYTHON_SYSCONFIGDATA_NAME```:

https://github.com/python/cpython/blob/58dc03c737a71de93edef7723c9f6186116288ef/configure.ac#L78

Note that this is tested with my building scripts at https://github.com/yan12125/python3-android/ using NDK r16b, not xdegaye's scripts. I tested ARM64, android-21 API on my ASUS ZE500KL phone.

**Comment by pmp-p** [comment]
@yan12125 i suggest to build _sysconfigdata_m_android_.py from a template as most of collected data in that file is only efficient for pip and setuptools when referencing a native compiler. If you look at the  generated_sysconfigdata_m_linux_.py when cross compiled :  it is full of reference to $HOST not $TARGET.

**Pull request closed without merging**
