### PR TITLE
bpo-44645: Check for interrupts on any potentially backwards edge

### PR DESCRIPTION
**Pull request by markshannon**
Second attempt using lists instead of nonlocals. 

https://bugs.python.org/issue44645

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]
Seems that the buildbots are happy with this.

What was the problem @markshannon ?

**Comment by markshannon** [comment]
> What was the problem @markshannon ?

https://bugs.python.org/issue30744 I think

**Comment by markshannon** [comment]
@pablogsal Are you OK with me merging this?

**Review by pablogsal — APPROVED** [review]
Yep! Apologies, I forgot to approve :(

**Pull request merged**
