### PR TITLE
gh-119770: Make termios ioctl() constants positive

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-119770

### CODE REVIEW

**Comment by vstinner** [comment]
@Eclips4 or @sobolevn: Would you mind to try this fix on macOS?

**Review by Eclips4 — APPROVED** [review]
I've tested it locally and everything worked as expected. Thank you Victor!

**Comment by vstinner** [comment]
> @Eclips4 added needs backport to 3.12 needs backport to 3.13 labels

Oh no, I disagree. That's a backward incompatible change. I don't think that we should backport it. It's not a bugfix. In Python 3.13, "it just works".

This change was needed because I changed ioctl() request parameter type from C `unsigned int` to C `unsigned long` in Python 3.14.

**Comment by Eclips4** [comment]
> This change was needed because I changed ioctl() request parameter type from C `unsigned int` to C `unsigned long` in Python 3.14.

But this change was backported to 3.12 and 3.13. Isn't then this should be backported since this fixes at least failing test?

**Comment by Eclips4** [comment]
Or another option: reverting this change for 3.12 && 3.13 branches since this break backwards compatibility

**Comment by vstinner** [comment]
> Or another option: reverting this change for 3.12 && 3.13 branches since this break backwards compatibility

Right, I created two revert changes:

* https://github.com/python/cpython/pull/119905
* https://github.com/python/cpython/pull/119906

**Pull request merged**
