### PR TITLE
bpo-40340 Separate examples within the same sentence clearly.

### PR DESCRIPTION
**Pull request by caje731**
https://bugs.python.org/issue40340

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@caje731

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by remilapeyre — APPROVED** [review]

**Review by aeros — CHANGES_REQUESTED** [review]
Thanks for the PR @caje731. The change itself mostly LGTM, but it should be adjusted slightly to fit within the [80 char line width maximum for reST](https://devguide.python.org/documenting/#use-of-whitespace). 

Once you've fixed that, let me know, and then I can proceed with merging the PR.

**Comment by caje731** [comment]
@aeros thanks for reviewing. I have made the requested changes; please review again.

**Review by aeros — APPROVED** [review]

**Comment by aeros** [comment]
Thanks @caje731

**Pull request merged**
