### PR TITLE
bpo-46018: Ensure that math.expm1 does not raise on underflow

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue46018

### CODE REVIEW

**Comment by mdickinson** [comment]
Just to be clear, was the bogus `OverflowError` witnessed on an actual system, or is this purely a hypothetical possibility. I'm assuming the former, but it wasn't totally clear from the description.

I'd propose a simpler fix: replace the line https://github.com/python/cpython/blob/dc4a212bd305831cb4b187a2e0cc82666fcb15ca/Modules/mathmodule.c#L990
with
```C
        if (fabs(x) < 2.0)
```

It's arguably more dangerous in that the change potentially affects all functions using `is_error` instead of just changing the behaviour of `expm1`, but I think it's safe in practice: we only need to distinguish underflow from overflow, and `2.0` is just as good a threshold as `1.0` for that.

Please could you also add a testcase that would exercise the problematic case, if there isn't one already?

**Comment by zooba** [comment]
> Just to be clear, was the bogus `OverflowError` witnessed on an actual system, or is this purely a hypothetical possibility?

It was an actual prerelease system, and it's entirely possible that the library will be fixed before it ever sees real use. But logically there's no way for expm1 to underflow to 0.0 anyway - it will always go to -1.0, because that's the spec (`expm1(x) == exp(x) - 1.0`).

I expanded the range to 1.5, as there's really no need to go any further. Quite likely making it `<= 1.0` would be sufficient, but why risk it.

**Comment by mdickinson** [comment]
> Please could you also add a testcase that would exercise the problematic case, if there isn't one already?

Update: no need - it's already covered. (See discussion on the b.p.o. issue.)

**Review by mdickinson — APPROVED** [review]
LGTM!

**Comment by mdickinson** [comment]
I guess it's worth running the buildbots on this one, just in case.

**Comment by mdickinson** [comment]
The buildbots seem happy so far, apart from the slow ones ... I don't think we need to wait for the rest of the buildbot results before merging - I'm happy to keep an eye on the remaining ones and raise an alert in the unlikely event that any of them fails for reasons related to this PR.

**Comment by mdickinson** [comment]
If we're regarding this as a kinda/sorta bugfix, should it be backported to 3.10 and 3.9?

**Comment by zooba** [comment]
Yes, I think it should be backported. I'll keep an eye on buildbots as well, but I expect this one to be pretty innocuous.

**Pull request merged**
