### PR TITLE
[DOC] Snippet code to str methods

### PR DESCRIPTION
**Pull request by adorilson**
This PR improvements the str method documentation, adding snippet code in the follows methods and other minor improvements:

- capitalize
- casefold
- center
- count
- encode
- endswith
- expandtabs
- find
- index
- isalnum
- isalpha
- isascii
- isdecimal
- isdigit
- isidentifier
- islower
- isnumeric
- isprintable
- isspace
- istitle
- join
- ljust
- lower
- lstrip
- maketrans
- partition
- replace
- rindex
- rjust
- rpartition
- rsplit
- rstrip
- startswith
- swapcase
- translate
- upper

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@orf

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by adorilson** [comment]
Why the CLA was removed?

**Comment by adorilson** [comment]
The CLA was removed by this PR: https://github.com/python/cpython/pull/24496

**Comment by adorilson** [comment]
The docs build failed, but I did not get the error. In my PC this build works properly.

**Comment by adorilson** [comment]
> Docs wont build with your changes/setup. I can compile the Docs from the current main. The error I get is: omplex.rst:49:Error in declarator or parameters Error in declarator or parameters Invalid C declaration: Expected identifier, got user-defined keyword: complex. Remove it from c_extra_keywords to allow it as identifier. Currently c_extra_keywords is ['alignas', 'alignof', 'bool', 'complex', 'imaginary', 'noreturn', 'static_assert', 'thread_local']. [error at 39] Py_complex _Py_c_neg(Py_complex complex) ---------------------------------------^ make: *** [Makefile:51: build] Error 2
> 

I just building in my PC and this works perfectly. I have synchronized with upstream before.

> NB I see the first change in Doc/library/array.rst does not exist in current Python 3 docs. Hence you will need to see if this is still relevant.

I doesn't touched in this file. Only Doc/library/stdtypes.rst.

**Comment by slateny** [comment]
Can you rebase the branch / cherry-pick the commits so it doesn't grab all the 1k+ commits from main? I'm also not too sure about adding so many examples as it would make the page a bit bloated, but I'll let someone else comment on them.

**Comment by adorilson** [comment]
I have made the requested changes; please review again

**Comment by adorilson** [comment]
In fact, the change was in a new branch/PR #105670

**Comment by AlexWaygood** [comment]
closing in favour of https://github.com/python/cpython/pull/105670

**Pull request closed without merging**
