### PR TITLE
gh-115267: Improve performance for temporary containers modification

### PR DESCRIPTION
**Pull request by pvlkhn**
* Issue: gh-115267

### CODE REVIEW

**Comment by Eclips4** [comment]
Do you have any benchmarks?

**Comment by ronaldoussoren** [comment]
It is not clear to me that this code is correct, in particular (error handling omitted for clarity):

```c
PyObject* list1 = PyList_New(0);
PyObject* list2 = PyList_New(0);

PyList_Append(list2, Py_True);

PyObject* list3 = PySequence_Concat(list1, list2);
```

Currently `list3` will be a new list and `list1` is not changed.  Your PR appears to change this.

**Comment by pvlkhn** [comment]
> It is not clear to me that this code is correct, in particular (error handling omitted for clarity):
> Currently `list3` will be a new list and `list1` is not changed. Your PR appears to change this.

That's true, we are changing behavior of PySequence_Concat/PySequence_Repeat. I see it's breaking the Stable ABI part of Sequence Protocol, so will add test to check creation of a new object in Concat and Repeat.

In the code 
```python 
l1 = [1, 2, 3]
l2 = [1 , 2, 3]
l1 + l2
print(l1)
```
`l1` remains unchanged, cause on line `l1 + l2` there are two references on l1. Does incrementing and decrementing ref count inside PySequence_Concat/PySequence_Repeat sounds as good enough fix? It will simulate python behaviour

Are there other problems for sequences?  Are there same contract for sets?

**Comment by pvlkhn** [comment]
> Do you have any benchmarks?

Sure, I have a benchmark for a specific synthetic case, executed on my system

Timings before commit:
Screenshot 2024-02-12 at 12 32 45

Timings after commit:
Screenshot 2024-02-12 at 12 32 06


Is there any standard way to test performance? I think would be great to check performance on some general benchmark

**Comment by pvlkhn** [comment]
There is one unit tests failing. What do you think, do we need `[0] * 10` working equally to `list([0] * 10)`? On one hand currently we reducing memory usage, on the other hand we are making an unnecessary copy

I am fine with both as such multiplication is not a typical case for list creation incrementally and usually just happens one time

**Comment by mdboom** [comment]
> Is there any standard way to test performance? I think would be great to check performance on some general benchmark

Yes, [pyperformance](https://github.com/python/pyperformance) is that thing.  The Faster CPython team also has a set of standard machines we use and I've kicked off a run of this PR there now (results ready in a couple of hours).

**Comment by mdboom** [comment]
This seems to have no statistically significant impact over the pyperformance suite: "HPT 99th percentile: 1.00x slower"

https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20240211-3.13.0a3%2B-3213e3a/bm-20240211-linux-x86_64-pvlkhn-gh_115267-3.13.0a3%2B-3213e3a-vs-base.md

This does not mean I'm advocating for not merging this.  If it provably improves things in narrow cases, it may still be acceptable if the pain of the added complexity is worth it.  But I'm not personally in a position to evaluate that, so I leave that up to the other reviewers.

**Comment by ericvsmith** [comment]
I don't think we should accept this. It complicates things for essentially no real-world gain.

**Comment by ronaldoussoren** [comment]
> I don't think we should accept this. It complicates things for essentially no real-world gain.

I agree. The current implementation strategy is also inherently broken (see my previous message).

**Comment by ronaldoussoren** [comment]
I'm closing this PR because as mentioned there appears to be no performance improvement on pyperformance and because this PR is the wrong approach even if there were clear performance improvements.

**Pull request closed without merging**
