### PR TITLE
gh-117557: Improve error message for 'C' format if given string is not 1 char long

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-117557

### CODE REVIEW

**Review by ronaldoussoren — APPROVED** [review]
LGTM

**Review by serhiy-storchaka — COMMENTED** [review]
Is it really better than the current error message?

In any case, you cannot just change the error message in Argument Clinic. It should match the error message in PyArg_Parse.

There are other variants of the error message for the same error in `ord`, `str.center`, str and bytes formatting `%c`. If we change the error messages, it is better to consider all options and make them as consistent as possible.

**Comment by erlend-aasland** [comment]
> Is it really better than the current error message?

Yes; it is clearer and more accurate.

> There are other variants of the error message for the same error in `ord`, `str.center`, str and bytes formatting `%c`. If we change the error messages, it is better to consider all options and make them as consistent as possible.

They represent different APIs and require different error messages. Aligning them with this error message does not make sense to me.

**Comment by erlend-aasland** [comment]
> In any case, you cannot just change the error message in Argument Clinic. It should match the error message in PyArg_Parse.

Yes, I think there is value in synchronising these.

**Comment by erlend-aasland** [comment]
I tried to address your concerns in fe02eddf96e9b03d4b16a2da67883fe312eb43f1, Serhiy.

**Review by serhiy-storchaka — COMMENTED** [review]
Thank you, it is better now. But note that other error message (few lines above) requires "a unicode character", not "a string containing exactly one unicode character". The latter looks as a more clumsy formulation of the former.

Ideally, the error message should contain the length of the string if it is not 1. But the `PyArg_Parse` code has limited facilities, so it needs more work.

Please look at more general image. Look how the affected functions are documented. Should the documentation be updated?

Look also at the `'c'` format unit (bytes objects with length 1). Does it need changes?

**Pull request closed without merging**
