### PR TITLE
Fix minor mistake in argparse tutorial 

### PR DESCRIPTION
**Pull request by gitenxx**
I've checked parser.add_argument() (with example code from tutorial) with different types of values and description provided in tutorial is misleading, because this function accepts arbitrary string values, not just integers.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@gitenxx

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by eamanu — CHANGES_REQUESTED** [review]
Good catch @gitenxx. 

IMO the PR is correct. But you should make the PR to master branch not to 3.8 branch.

**Comment by tirkarthi** [comment]
The PR proposes a lot of file changes and I guess there is a mistake in the branch. I would recommend closing this to open a new PR with the suggestion alone as change.

**Comment by csabella** [comment]
@gitenxx, when this was changed to the master branch, it made a diff with a lot more changes than just a simple documentation fix.  As @tirkarthi suggested, I'm going to close this PR.  Please open a new PR with just the relevant change against the master branch.  Thank you!

**Pull request closed without merging**
