### PR TITLE
bpo-43901: Fix refleaks in test_module

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue43901

### CODE REVIEW

**Comment by pablogsal** [comment]
I'm still missing another leak:

```
𓋹 ./python.exe -m test test_module -R :
0:00:00 load avg: 2.89 Run tests sequentially
0:00:00 load avg: 2.89 [1/1] test_module
beginning 9 repetitions
123456789
.........
test_module leaked [1, 1, 1, 1] references, sum=4
test_module failed

== Tests result: FAILURE ==

1 test failed:
    test_module

Total duration: 2.0 sec
Tests result: FAILURE
```

**Comment by pablogsal** [comment]
> I'm still missing another leak:

Gotcha! I have it fixed in 3640843

**Review by larryhastings — APPROVED** [review]

**Comment by larryhastings** [comment]
I was about to make my PR ;-)

**Comment by pablogsal** [comment]
> I was about to make my PR ;-)

Sorry, I was doing this patch and missed your comments on BPO :(

**Comment by larryhastings** [comment]
It's hard to see how that code could ever have passed a refleak check!  It seems like would always have leaked that dict.  Yet I swear I ran one!

**Comment by larryhastings** [comment]
I don't mind the parallel effort, as long as it gets fixed one way or another.  I've caused enough headaches and gnashing of teeth this week--let's try and keep this incident to a minimum!

**Comment by larryhastings** [comment]
Let's go with yours, the PR is already up and checks are running.

**Comment by pablogsal** [comment]
> I've caused enough headaches and gnashing of teeth this week--let's try and keep this incident to a minimum!

No problem Larry! This happens quite a lot for everyone, and the important thing is that we have your patch for 3.10 :)

**Comment by larryhastings** [comment]
> No problem Larry! This happens quite a lot for everyone, 

What rot!  This never happened during the release process for 3.4 and 3.5!  Nobody ever broke the build, ever.  I'm clearly a tiresome outlier.

**Pull request merged**
