### PR TITLE
gh-121407: faster `tp_iternext` for `bltinmodule:sum`

### PR DESCRIPTION
**Pull request by dg-pb**
Small performance improvement.

* Issue: gh-121407

### CODE REVIEW

**Comment by gaogaotiantian** [comment]
Hmm, I'm not super convinced by this optimization. Basically you saved a few pointer dereferences and a call into `PyIter_Next` by moving the code inside the function to the caller - that may not be the direction we want to go. You can do this to any calls to `PyIter_Next` when you use the same iterator. Or to generalize it, you can always save a function call by moving the content inside the function to the caller - but we abstracted code for a reason. You patch will create redundant code (to check for `StopIteration`) all over the place and I think that reduces the readability.

I'm -1 for this change. I don't think the benefit is enough for the cost.

**Comment by dg-pb** [comment]
> I'm -1 for this change. I don't think the benefit is enough for the cost.

It kinda is a standard approach by now.
See other `iter` functions in:
1. bltinmodule.c
2. _collectionsmodule.c
3. itertoolsmodule.c

`PyIter_Next` is the same as `next(iterator)`, but one doesn't use it to loop over iterator.

While `tp_iternext` direct call with handlers in the end is more like `for item in iterable`.

E.g.
```
it = iter(iterable)
while True:
    try:
        item = next(it)
        ...
    except StopIteration:
        break

# vs
for item in iterable:
    ...
```

One uses `next` where appropriate, but for standard iteration `next` is not used.

**Comment by gaogaotiantian** [comment]
Hmm, okay. I did not realize that was already four pieces of same code. My opposition for this is that it inserts plenty of duplicated code all over the function. In `_collectionsmodule.c` it has a `finalize_iterator` to deal with this work, which makes the code look better.

Behind the curtain your approach does the exact same thing as `PyIter_Next` - the logic is almost identical. Even our C API gives an [example](https://docs.python.org/3/c-api/iter.html#c.PyIter_Next) to loop over the iterator using `PyIter_Next`:

```c
while ((item = PyIter_Next(iterator))) {
    /* do something with item */
    ...
    /* release reference when done */
    Py_DECREF(item);
}
```

As we already had some precedences, I'm -0 on this. However, for this specific case, as we will never break early, I think we can do something like

```c
                assert(PyErr_Occurred());
                if (!PyErr_ExceptionMatches(PyExc_StopIteration)) {
                    return NULL;
                }
                return PyLong_FromSsize_t(i_result);
```

**Review by vstinner — COMMENTED** [review]
I would prefer a static inline flavor of PyIter_Next() in the internal C API, rather than inlining directly the code in sum().

**Comment by dg-pb** [comment]
> Behind the curtain your approach does the exact same thing as `PyIter_Next`

Yup, this is purely to avoid unnecessary operations to be done on every iteration.

I wish simply using `PyIter_Next` was optimal, but ~5% gain for such a minimal change is not so bad IMO.

> However, for this specific case, as we will never break early, I think we can do something like

I don't know the reason, but what you propose results in:
```
SystemError: <built-in function sum> returned NULL without setting an exception
```

I don't think some repetition at this point is a big deal given the whole function has a lot of repetitions already and is subject to more general refactoring.

All numeric case loops are the same with repetitive code at the start and at the end.

I think squashing into a single loop could be an option:
E.g.:
```python
result_type = type(init)
while next(it, None) is not None:
    match result_type:
        case int
        case float
        case complex
        case default
            break
```
There would be a slight overhead of conditional statements within a loop, but it would be trivial (e.g. a small fraction of the improvement this PR offers (which is up to 5%)), and could be a reasonable cost for simplification.

Or defining some macros might be another one.

Having that said, for now I think it is still ok, but if any more loops of the same quality are introduced, simplification might be worthwhile.

**Comment by vstinner** [comment]
See also https://github.com/capi-workgroup/decisions/issues/21.

**Comment by rhettinger** [comment]
Thanks for the suggestion, but I'm going to decline.   

This code is already large full of interesting code paths and has a high cyclomatic complexity.  I don't want to make it harder to maintain.   Mostly, I only want to do this optimization in simpler code where the loop overhead is a higher fraction of the total work.

This is just a judgment call and we're not consistent about it.  Different people at different times have different tolerances for code bloat from inlining.

**Pull request closed without merging**
