### PR TITLE
Solved description problem

### PR DESCRIPTION
**Pull request by Harsh-Govil**
----
📚 Documentation preview 📚: https://cpython-previews--117600.org.readthedocs.build/

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Harsh-Govil** [comment]
I  am sending a new PR pls check

**Comment by Harsh-Govil** [comment]
> What is the motivation for this change? It doesn't look necessary.

I had to contribute to 1 open source project for my college assignment. I saw this problem and did the changes based on my understanding of the problem statement. If you want me to do some other changes pls clarify. I would be very happy to contribute

**Comment by Harsh-Govil** [comment]
> This PR is not linked to any issue, so I don't know what the problem is that you are trying to solve.

In documentation explanation to command date.replace() is not clear enough.
I'm not that experienced, so it's maybe look from junior perspective, but since documentation quite needed for beginers i think my opinion might be valuable.

In documentation description to this function says "Return a date with the same value, except for those parameters given new values by whichever keyword arguments are specified." and gives an examle:

--- from datetime import date
--- d = date(2002, 12, 31)
--- d.replace(day=26)
datetime.date(2002, 12, 26)
But it confused me, since it looks like you can change datetime object and as documentation says - datetime objects are immutable, so i had to check and of course you can't change variable like that, the only way that works if you create a new variable (for example: d2 = d.replace(day=26))

So i propose to make this part that there won't be any confusion for anyone by rephrasing it.
For example:

Return a new date object with the same value as initial, except for those parameters given new values by whichever keyword arguments are specified.

--- from datetime import date
--- d = date(2002, 12, 31)
--- d2 = d.replace(day=26)
--- d2
datetime.date(2002, 12, 26)
I haven't seen any tickets issued about this one, but i apologise if there is and i've missed it, or if i miss something in documentation itself.

**Comment by encukou** [comment]
First, [report an issue](https://devguide.python.org/triage/issue-tracker/#reporting-an-issue) describing the problem. That helps keep related and backported pull requests together.

You'll find the same wording in `time.replace` and `datetime.replace`. Change them all, or none of them.

Try to keep source lines below 80 characters, as in (most of) the rest of the document.

Avoid adding unnecessary blank lines, or removing existing ones. (Unless you're intentionally improving the source's readability, of course.)

When rewording something in the reference docs, try to be as concise, correct and complete as you can.

**Comment by hauntsaninja** [comment]
Closing, since OP hasn't replied / signed the CLA

**Pull request closed without merging**
