### PR TITLE
bpo2771: test issue linking from the title

### PR DESCRIPTION
**Pull request by brettcannon**
## CPython Mirror

https://github.com/python/cpython is a cpython mirror repository. Pull requests
are not accepted on this repo and will be automatically closed.

### Submit patches at https://bugs.python.org

For additional information about contributing to CPython, see the
[developer's guide](https://docs.python.org/devguide/#contributing).

### CODE REVIEW

**Comment by brettcannon** [comment]
This will succeed once https://bugs.python.org/issue2771 links to this PR automatically.

**Comment by brettcannon** [comment]
Testing if this comes through as a PR review comment or issue comment.

**Comment by brettcannon** [comment]
Trying another comment to try and trigger the webhook.

**Comment by soltysh** [comment]
Another comment for test.

**Comment by brettcannon** [comment]
Just verified `bpo` in the title works!

**Pull request closed without merging**
