### PR TITLE
gh-107938: Synchonise the signature of of sqlite3.connect and sqlite3.Connection.__init__

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-107938

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Suggesting to backport this, in order to easier backport docstring updates.

**Comment by erlend-aasland** [comment]
cc. @serhiy-storchaka, if you want to look this over; it is a trivial change

**Review by serhiy-storchaka — APPROVED** [review]
This is an interesting trick, but in future they can divergent.

`Connection.__init__` and `__init__` in its subclasses currently require the `factory` parameter to be supported, even if it is ignored. This is both a wart and an artifact of implementation. It may be removed in the future, and from then on the `connect` and `Connection.__init__` signatures will be different.

It is a long way, and I think that it can only happen in distant future, but you should be aware of consequences.

**Comment by erlend-aasland** [comment]
Yes, that is true, but as you say, it is a long way into the future. For now, it makes it simpler for us to do stuff like deprecating positional use of parameters.

**Comment by serhiy-storchaka** [comment]
BTW, after making all optional arguments keyword-only, why not implement `connect()` in Python?
```python
def connect(database, *, factory=Connection, **kwargs):
    return factory(database, **kwargs)
```

**Comment by erlend-aasland** [comment]
> BTW, after making all optional arguments keyword-only, why not implement `connect()` in Python?
> 
> ```python
> def connect(database, *, factory=Connection, **kwargs):
>     return factory(database, **kwargs)
> ```

That is a very good idea.

BTW, I've toyed the idea of with turning `_sqlite3` into a small extension module that simply exposes the relevant SQLite APIs, and then implement `Lib/sqlite3.py` using `_sqlite3`. It would probably have a performance impact, but it would make maintenance easier.

**Comment by erlend-aasland** [comment]
Ah, of course, we cannot backport this because the clone `__init__` feature in Argument Clinic is only present in `main`. Well, backporting is not very important; the spec of `sqlite3.connect` and `sqlite3.Connection.__init__` should not change in 3.12 and 3.11.

**Pull request merged**
