### PR TITLE
gh-121735: Fix module-adjacent references in zip files

### PR DESCRIPTION
**Pull request by jaraco**
~~Merge after #123028.~~

- **gh-121735: Ensure module-adjacent resources are loadable from a zipfile.**
- **gh-121735: Allow all modules to be processed by the ZipReader.**
- **Add blurb**

### CODE REVIEW

**Comment by jaraco** [comment]
I'm a little apprehensive about the prospect of backporting this to Python 3.12, given the amount of refactoring that had to happen in the tests to make them viable. I may opt to backport the fix but limit the amount of changes backported to the tests, depending on how complicated it turns out to be.

**Review by FFY00 — APPROVED** [review]
This looks okay to me.

I don't really have any strong opinion regarding backporting the changes to 3.12. I agree it would be nicer to backport without the large test suite refactoring, but that isn't unreasonable to me if the changes don't end up applying cleanly. Not backporting the test suite changes also increases the possibility for test suite bugs to sneak into the 3.12 branch, as that won't be maintained as closely as the main branch. Additionally, it can also cause conflicts when backporting other fixes, so, eh, I guess I am +0.5 on backporting this PR as a whole.

**Comment by Gatsik** [comment]
Oh, I was going to open a PR that potentially fixes this issues, but noticed that there's already a PR for that
The one thing that it misses is that it doesn't fix the issue when the `importlib` library itself is compiled -- in that case inferring caller doesn't work correctly (my attempt to fix it: https://github.com/Gatsik/cpython/commit/50c15967a6f3b74c5ec5db72d8e9367016f45295)

**Comment by jaraco** [comment]
@gatsik - the implementation provided herein has already been reviewed and released as [`importlib_resources` 6.4.1](https://importlib-resources.readthedocs.io/en/latest/history.html#v6-4-1). It proves the fix and is available.



> The one thing that it misses is that it doesn't fix the issue when the `importlib` library itself is compiled -- in that case inferring caller doesn't work correctly (my attempt to fix it: [Gatsik@50c1596](https://github.com/Gatsik/cpython/commit/50c15967a6f3b74c5ec5db72d8e9367016f45295))

It's not obvious to me from this fix what the failure mode is. I think I see it now - if the `_common` module is available as bytecode but has no source, then `__file__` may not be valid. I think that issue would affect both zip files and direct disk files. Would you be willing to write up a separate issue, either in this repo or in python/importlib_resources that describes the missed expectation and why it's an important use-case to support? It's certainly something worthy of consideration, but it's also something that can be considered independent of this PR.

**Comment by Gatsik** [comment]
@jaraco sure! i created an issue https://github.com/python/cpython/issues/123085

**Comment by jaraco** [comment]
In jaraco/cpython@17dc9667ab2, I've started work on a backport, but it's really broken. I got stuck when `MultiplexedPath` doesn't have support for zip files. That was added to Python 3.13 only in https://github.com/python/cpython/issues/106531. Since that wasn't backported (and shouldn't have been), it won't be possible to backport these tests.

**Comment by vstinner** [comment]
@jaraco: Tests fail on Big Endian machines, look at previous buildbot messages.

cc @encukou

**Comment by jaraco** [comment]
> @jaraco: Tests fail on Big Endian machines, look at previous buildbot messages.

See #123994

**Pull request merged**
