### PR TITLE
bpo-23722: Raise RuntimeError for absent __classcell__.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
A DeprecationWarning was emitted in Python 3.6-3.7.

https://bugs.python.org/issue23722

### CODE REVIEW

**Review by ncoghlan — APPROVED** [review]
LGTM!

**Comment by ncoghlan** [comment]
The Appveyor failure doesn't look related, so I restarted it.

**Comment by serhiy-storchaka** [comment]
So it should be **RuntimeError**, not **RuntimeWarning** (#6933)?

**Comment by ncoghlan** [comment]
Yeah, RuntimeError is correct - I completely missed that I'd mistakenly mentioned RuntimeWarning instead in the docs (I added a comment to the BPO issue about that as well)

**Pull request merged**
