### PR TITLE
gh-107954: Fix configuration type for the perf profiler

### PR DESCRIPTION
**Pull request by pablogsal**
* Issue: gh-107954

### CODE REVIEW

**Comment by diegorusso** [comment]
@pablogsal thanks! I confirm that this PR fixes https://github.com/python/cpython/issues/124613

**Comment by diegorusso** [comment]
Tests are failing, I think they need to be updated as well.

```
======================================================================
FAIL: test_config_get (test.test_capi.test_config.CAPITests.test_config_get) (name='perf_profiling', option_type=<class 'bool'>, sys_attr=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/admin/actions-runner/_work/cpython/cpython/Lib/test/test_capi/test_config.py", line 130, in test_config_get
    self.assertIsInstance(value, option_type)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
AssertionError: 0 is not an instance of <class 'bool'>
```

**Comment by vstinner** [comment]
@pablogsal: I pushed a change in your PR to update tests.

**Comment by vstinner** [comment]
I didn't know that perf_profiling can have two values, 1 or 2. It's not documented.

@pablogsal: I also pushed a change to complete the doc and add more tests. Would you mind to review my change?

**Comment by diegorusso** [comment]
Thanks folks, I've tested the PR in our internal CI and all the tests are passing. LGTM.

**Pull request merged**
