### PR TITLE
gh-116915: Make `_thread._ThreadHandle` support GC

### PR DESCRIPTION
**Pull request by mpage**
Even though it has no internal references to Python objects it still has a reference to its type by virtue of being a heap type. We need to provide a traverse function that visits the type, but we do not need to provide a clear function.

* Issue: gh-116915

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Would a fix that only decrefs the type in dealloc be sufficient, without supporting GC?

https://docs.python.org/3/c-api/typeobj.html#c.Py_TPFLAGS_HEAPTYPE

**Comment by mpage** [comment]
> Would a fix that only decrefs the type in dealloc be sufficient, without supporting GC?

Unfortunately, no. That decref was already present.

**Comment by mpage** [comment]
The `CIFuzz (memory)` failure is unrelated to this PR (gh-116886)

**Comment by Fidget-Spinner** [comment]
> > Would a fix that only decrefs the type in dealloc be sufficient, without supporting GC?
> 
> Unfortunately, no. That decref was already present.

Huh that's really strange. Usually cycles between types and the object itself are special. Will think about this.

**Comment by Fidget-Spinner** [comment]
Ah right I forgot that heap types need to support GC as well. This can be seen in previous work. In this case, this LGTM. 

E.g.
https://github.com/python/cpython/pull/23136/files

**Review by pitrou — APPROVED** [review]
+1. Let's wait for the refleaks builders to be become green again and then merge this.

**Review by Fidget-Spinner — APPROVED** [review]
It seems there is indeed a reference cycle between heap types and the module object itself https://github.com/python/cpython/blob/2982bdb936f76518b29cf7de356eb5fafd22d112/Objects/typeobject.c#L4557.

**Comment by colesbury** [comment]
Windows 11:

https://buildbot.python.org/all/#/builders/1214/builds/304/steps/4/logs/stdio

```
======================================================================
FAIL: test_finalize_running_thread (test.test_threading.ThreadTests.test_finalize_running_thread)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "b:\uildarea\pull_request.ware-win11.refleak\build\Lib\test\test_threading.py", line 459, in test_finalize_running_thread
    self.assertEqual(rc, 42)
    ~~~~~~~~~~~~~~~~^^^^^^^^
AssertionError: 3221225477 != 42
----------------------------------------------------------------------
Ran 207 tests in 34.247s
```

`3221225477` is `0xC0000005` or `STATUS_ACCESS_VIOLATION`

https://github.com/python/cpython/blob/2982bdb936f76518b29cf7de356eb5fafd22d112/Lib/test/test_threading.py#L424-L459

**Review by vstinner — APPROVED** [review]
LGTM. I looked at my checkbox: https://pythondev.readthedocs.io/subinterpreters.html#convert-static-type-to-heap-type

**Comment by vstinner** [comment]
Nice fix @mpage. I confirm that it does fix the leak: https://github.com/python/cpython/issues/116915#issuecomment-2003214682

**Comment by vstinner** [comment]
If anyone see the test_threading.test_finalize_running_thread() crash again, please open a new issue.

**Pull request merged**
