### PR TITLE
bpo-45759: Re: Better error messages for non-matching 'elif'/'else' statements

### PR DESCRIPTION
**Pull request by thatbirdguythatuknownot**
Repeated pull request with a different branch of the fork. Original pull request link -> <https://github.com/python/cpython/pull/29513>

https://bugs.python.org/issue45759

### CODE REVIEW

**Comment by thatbirdguythatuknownot** [comment]
This pull request was made as a workaround to the conflict in `Parser/parser.c` without `git`.

**Comment by MaxwellDupre** [comment]
You have make 67284 changes to parser.c, can you say why its like this rather than usual additions, deletions?

**Comment by AlexWaygood** [comment]
> You have make 67284 changes to parser.c, can you say why its like this rather than usual additions, deletions?

`parser.c` is an autogenerated file. The number of lines changed in `parser.c` is not relevant to anything.

**Comment by AlexWaygood** [comment]
> You have make 67284 changes to parser.c, can you say why its like this rather than usual additions, deletions?

`parser.c` is an autogenerated file. The number of lines changed in `parser.c` is not relevant to anything.

**Comment by thatbirdguythatuknownot** [comment]
> You have make 67284 changes to parser.c, can you say why its like this rather than usual additions, deletions?

@MaxwellDupre It's an autogenerated file, you can also see this in other minor grammar changes.

**Comment by MaxwellDupre** [comment]
Ah, right of course, VS code showed me a confusing view of differences, but Git showed the correct one.

I have tried to compile and got:
Traceback (most recent call last):
  File "/home/me/Documents/GitHub/cpython/./Tools/scripts/deepfreeze.py", line 1, in <module>
    import argparse
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/argparse.py", line 89, in <module>
    import re as _re
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 125, in <module>
    from . import _compiler, _parser
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/_compiler.py", line 18, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch
...
make: *** [Makefile:1106: Python/deepfreeze/site.c] Error 1
make: *** [Makefile:1079: Python/deepfreeze/abc.c] Error 1
make: *** [Makefile:1100: Python/deepfreeze/posixpath.c] Error 1
make: *** [Makefile:1085: Python/deepfreeze/io.c] Error 1
make: *** [Makefile:1097: Python/deepfreeze/ntpath.c] Error 1
make: *** [Makefile:1112: Python/deepfreeze/__hello__.c] Error 1
make: *** [Makefile:1115: Python/deepfreeze/__phello__.c] Error 1
...
AssertionError: SRE module mismatch
make: *** [Makefile:1121: Python/deepfreeze/__phello__.ham.eggs.c] Error 1
make: *** [Makefile:1118: Python/deepfreeze/__phello__.ham.c] Error 1
make: *** [Makefile:1124: Python/deepfreeze/__phello__.spam.c] Error 1
Traceback (most recent call last):
  File "/home/me/Documents/GitHub/cpython/./Tools/scripts/deepfreeze.py", line 1, in <module>
    import argparse
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/argparse.py", line 89, in <module>
    import re as _re
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 125, in <module>
    from . import _compiler, _parser
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/_compiler.py", line 18, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch
make: *** [Makefile:1127: Python/deepfreeze/frozen_only.c] Error 1
___
**Then tried:**
 !  ~/D/G/cpython   patch-10 $  make regen-pegen
PYTHONPATH=./Tools/peg_generator python3.11 -m pegen -q c \
	./Grammar/python.gram \
	./Grammar/Tokens \
	-o ./Parser/parser.new.c
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/me/Documents/GitHub/cpython/Tools/peg_generator/pegen/__main__.py", line 8, in <module>
    import argparse
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/argparse.py", line 89, in <module>
    import re as _re
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 125, in <module>
    from . import _compiler, _parser
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/_compiler.py", line 18, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch
make: *** [Makefile:1353: regen-pegen] Error 1
___

I note that none of the build bots have run.
___
I am using Fedora 5.18.5-200.fc36.x86_64 and 
./configure --with-pydebug
make -s -j

**Comment by thatbirdguythatuknownot** [comment]
Other PR got merged.

**Pull request closed without merging**
