### PR TITLE
gh-110964: clinic: pass clinic argument to bad_argument()

### PR DESCRIPTION
**Pull request by vstinner**
Don't rely on the global 'clinic' argument: pass explicitly a 'clinic' argument.

* Issue: gh-110964

### CODE REVIEW

**Comment by vstinner** [comment]
cc @AlexWaygood

**Comment by AlexWaygood** [comment]
Please give me time to look at this! :-)

**Comment by vstinner** [comment]
"Check if generated files are up to date (pull_request)" failure looks unrelated:

```
./configure --config-cache --with-pydebug --enable-shared
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.6/x64/lib/pkgconfig

configure: loading cache config.cache
configure: error: `PKG_CONFIG_PATH' has changed since the previous run:
configure:   former value:  `/opt/hostedtoolcache/Python/3.11.5/x64/lib/pkgconfig'
configure:   current value: `/opt/hostedtoolcache/Python/3.11.6/x64/lib/pkgconfig'
```

**Comment by vstinner** [comment]
> Please give me some time to look at this! :-)

Mmmmh, so do you need more time to review?

**Comment by vstinner** [comment]
Well, since @AlexWaygood is not available for review, i think that i will just merge my change next days.

**Comment by AlexWaygood** [comment]
Thanks for waiting, sorry for the slow response from me! I wanted to take the time to think about this properly, but haven't had a chance recently due to being busy at work, and it's unlikely that I'll have the time in the next week either.

My instinct is that there should be q simpler solution here that involves fewer changes, but if you feel like there's a rush to get this merged for whatever reason, then please go ahead. I agree I've kept you waiting for a while :-)

**Comment by vstinner** [comment]
me:
> The only purpose of this change is to avoid using clinic global variable in def bad_argument() method. Just for that, I had to modify many lines :-(

@AlexWaygood:
> My instinct is that there should be q simpler solution here that involves fewer changes,

Yeah, there should be a way to redesign the code to have to pass less arguments. I dislike the current API :-( Moreover, passing limited_capi and clinic is kind of redundant, since using `clinic.limited_capi` is the same as passing `limited_capi`.

I close my PR for now. We can revisit this code later when we will try to give rid of the global `clinic` variable.

**Pull request closed without merging**
