### PR TITLE
[doc] Fix dis markup

### PR DESCRIPTION
**Pull request by andresdelfino**

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]

**Review by gpshead — APPROVED** [review]

**Comment by gpshead** [comment]
thanks!

**Comment by rhettinger** [comment]
Does this have any visual effect for the reader?

**Comment by serhiy-storchaka** [comment]
Good catch! And it is common error. Perhaps we can add a check in `Doc/tools/rstlint.py` which checks that the text following a directive does not have excessive indentation.

**Comment by mdickinson** [comment]
> which checks that the text following a directive does not have excessive indentation

I think the issue wasn't excessive indentation, but instead inconsistent indentation within the block for the directive. The text was indented four spaces while the `.. versionadded` directive that was also part of the same block was indented three spaces. Indenting the `.. versionadded` directive one extra space would also have fixed the issue.

**Comment by andresdelfino** [comment]
> Does this have any visual effect for the reader?

Yes.

**Pull request merged**
