### PR TITLE
gh-104799: Default missing lists in AST to the empty list

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Motivated by #104799: avoid breaking backward compatibility with the manual creation of `ast.FunctionDef` nodes. Now, if a list-type field is missing, we simply default to the empty list.

This affects all AST nodes though, not just the new ones.

* Issue: gh-104799

----
:books: Documentation preview :books:: https://cpython-previews--104834.org.readthedocs.build/

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
(This PR is on top of the changes from #104828.)

**Comment by JelleZijlstra** [comment]
Ideally I'd like this to go into 3.12 to fix the BC issues in #104799, but maybe it's too late.

**Comment by markshannon** [comment]
So I understand correctly, this changes the representation of a missing list from `NULL` to `PyList_New(0)`. Correct?

I am a little concerned (just a little) about the performance implications.
Which nodes will this affect in practice?

**Comment by JelleZijlstra** [comment]
> So I understand correctly, this changes the representation of a missing list from `NULL` to `PyList_New(0)`. Correct?

No, it changes from raising a TypeError to PyList_New(0). This is easier to see in the generated code than in the code generator:

```diff
@@ -9306,10 +9404,12 @@ obj2ast_expr(struct ast_state *state, PyObject* obj, expr_ty* out, PyArena*
             return 1;
         }
         if (tmp == NULL) {
-            PyErr_SetString(PyExc_TypeError, "required field \"generators\" missing from DictComp");
-            return 1;
+            tmp = PyList_New(0);
+            if (tmp == NULL) {
+                return 1;
+            }
         }
-        else {
+        {
             int res;
             Py_ssize_t len;
             Py_ssize_t i;
```

So this shouldn't affect performance for code that was already working.

**Pull request merged**
