### PR TITLE
bpo-46347: Fix PyEval_EvalCodeEx to correctly cleanup in error paths

### PR DESCRIPTION
**Pull request by 1st1**
https://bugs.python.org/issue46347

### CODE REVIEW

**Comment by larryhastings** [comment]
Yup, that's how it's done!

**Review by larryhastings — APPROVED** [review]

**Comment by 1st1** [comment]
I don't think this needs to go in 3.10, so I'll just merge it into the main branch.

**Comment by eirnym** [comment]
@1st1 Why do you think it doesn't need to go to 3.10 as well?

**Comment by 1st1** [comment]
> @1st1 Why do you think it doesn't need to go to 3.10 as well?

Because any remaining leaks can only happen when the interpreter is about to shutdown anyways so leaking a bit of memory isn't critical. IMO it's not worth it to push more changes to 3.10, but that will ultimately be up to @pablogsal

**Review by gpshead — COMMENTED** [review]
post-merge LGTM

**Comment by gpshead** [comment]
https://github.com/python/cpython/pull/30553 was the manual backport of this and https://github.com/python/cpython/pull/30554 to 3.10.

**Pull request merged**
