### PR TITLE
bpo-36052: Disallow assigning to __debug__ in named expressions

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue36052

### CODE REVIEW

**Comment by matrixise** [comment]
@pablogsal I was working on this issue :/

**Comment by pablogsal** [comment]
@matrixise  Sorry, when I started to work on this I did not notice the comments in the bpo :(

Do you want me to close the PR and do one yourself?

**Comment by matrixise** [comment]
@pablogsal I have pushed my PR, you are in the blurb entry. Maybe I should add you in the description of the PR with "Co-author-by"

**Comment by matrixise** [comment]
@pablogsal https://github.com/python/cpython/pull/11958 Please, could review it?

**Pull request closed without merging**
