### PR TITLE
bpo-36309  pydoc.py: line 1533 - updated mktemp to mkstemp

### PR DESCRIPTION
**Pull request by fuzzygwalchmei**
line 1533 - updated mktemp to mkstemp

https://bugs.python.org/issue36309

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by tirkarthi** [comment]
Since there is no decision reached on the issue and mailing list I am not sure if this needs a separate PR. Perhaps this could be done as part of the PR where warning is raised and all the relevant call sites are also changed with several places where this function is used.

**Comment by tonybaloney** [comment]
@tirkarthi this pr is regarding an individual use of the `mktemp()` call, not to suppress it completely. The recommendation in the stdlib is to replace calls to `mktemp()` with one of the alternatives
The pydoc module uses `mktemp()` for some local caching. This was the only occurrence in the stdlib.

**Comment by tonybaloney** [comment]
The linked BPO is incorrect, this should probably have it's own bpo

**Comment by csabella** [comment]
@fuzzygwalchmei, please sign the CLA as per the above message.  Also, I agree with @tonybaloney that this should have its own bug tracker issue.  Thank you!

**Comment by csabella** [comment]
@fuzzygwalchmei, thank you for signing the CLA.  Were you able to create a new bug tracker issue for this?  If so, please update the title to reflect the new ticket number.

**Comment by csabella** [comment]
I'm going to close this PR as inactive.

**Pull request closed without merging**
