### PR TITLE
bpo-1635741: port pickle to multi-phase init (PEP 489)

### PR DESCRIPTION
**Pull request by koubaa**
https://bugs.python.org/issue1635741

### CODE REVIEW

**Comment by koubaa** [comment]
@vstinner tests pass but I think this one should be staged in multiple PR.  I'm wondering how you think I should go about dividing it.

**Comment by iritkatriel** [comment]
https://bugs.python.org/issue1635741 is closed. What is the status of this PR?

**Comment by vstinner** [comment]
The change is still relevant, but should use a new issue number.

Moreover, the SC asked to put the conversion of static types to heap types on hold. @encukou and @erlend-aasland wrote https://peps.python.org/pep-0687/ which may unblock the situation but it's still a draft.

**Comment by erlend-aasland** [comment]
@koubaa, PEP 687 was accepted. Are you going to follow up this PR?

**Comment by koubaa** [comment]
@erlend-aasland I'd love to - but I doubt I will get time in the near term.  Others could use my PRs as a reference in case they find it useful towards doing pep 687

**Comment by erlend-aasland** [comment]
> @erlend-aasland I'd love to - but I doubt I will get time in the near term.  Others could use my PRs as a reference in case they find it useful towards doing pep 687

All right, I'll pick it up.

Thanks for all your work on isolating extension modules.

**Comment by erlend-aasland** [comment]
I'm closing this in order to split it up into multiple PRs.

**Pull request closed without merging**
