### PR TITLE
gh-119786:: move 'repo structure' and 'additional resources' from devguide to InternalDocs

### PR DESCRIPTION
**Pull request by iritkatriel**
Original: It's this doc, split in two: https://devguide.python.org/internals/exploring/

* Issue: gh-119786

### CODE REVIEW

**Comment by iritkatriel** [comment]
It's this doc, split in two: https://devguide.python.org/internals/exploring/

**Comment by nedbat** [comment]
Let's discuss this on https://github.com/python/devguide/pull/1456 before doing anything.

**Review by willingc — APPROVED** [review]
I am fine with this content in the InternalsDocs as long as it also remains in the devguide in the short term. Thanks @iritkatriel

**Comment by iritkatriel** [comment]
TBH, if this stays in the devguide then I think it's not necessary here as well.

We can let the internal docs be the deep dive, and assume people have gone through the dev guide too.

**Pull request closed without merging**
