### PR TITLE
bpo-36030: Remove _PyStack_AsTuple() and _PyStack_AsTupleSlice()

### PR DESCRIPTION
**Pull request by sir-sigurd**
Follow up to 234531b4462b20d668762bd78406fd2ebab129c9

https://bugs.python.org/issue36030

### CODE REVIEW

**Comment by vstinner** [comment]
I'm concerned by the removal of this hack

```
/* Issue #29234: Inlining _PyStack_AsTuple() into callers increases their
   stack consumption, Disable inlining to optimize the stack consumption. */
_Py_NO_INLINE PyObject *
(...)
```

Can you please compile Python in release mode (not in debug mode) with and without your change, and run  stack_overflow-3.py script attached to https://bugs.python.org/issue30866 and copy results here? I would like to measure if your PR has an impact on the usage of the stack memory.

**Comment by sir-sigurd** [comment]
> Can you please compile Python in release mode (not in debug mode) with and without your change, and run stack_overflow-3.py script attached to https://bugs.python.org/issue30866 and copy results here? I would like to measure if your PR has an impact on the usage of the stack memory.

Before:
```
test_python_call: 8728 calls before crash, stack: 960 bytes/call
test_python_getitem: 9189 calls before crash, stack: 912 bytes/call
test_python_iterator: 8313 calls before crash, stack: 1008 bytes/call

=> total: 26230 calls, 2880 bytes
```

After:
```
test_python_call: 8729 calls before crash, stack: 960 bytes/call
test_python_getitem: 9189 calls before crash, stack: 912 bytes/call
test_python_iterator: 8312 calls before crash, stack: 1008 bytes/call

=> total: 26230 calls, 2880 bytes
```

**Comment by vstinner** [comment]
"=> total: 26230 calls, 2880 bytes" with and without the patch: oh good, the _Py_NO_INLINE micro-optimization is no more useful. At least, your change has no negative effect ;-)

**Comment by vstinner** [comment]
> Follow up to 234531b4462b20d668762bd78406fd2ebab129c9

I removed that from the commit message, since it's obvious from the bpo number and the git log ;-)

**Comment by vstinner** [comment]
Thanks for the cleanup @sir-sigurd, I merged your PR ;-)

**Pull request merged**
