### PR TITLE
bpo-31630: Skip tests for tan() near pi/2 on OpenBSD and NetBSD.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue31630

### CODE REVIEW

**Review by taleinat — COMMENTED** [review]
LGTM

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

**Comment by csabella** [comment]
I'm going to remove the `backport to 2.7` label and add a label for 3.8.

**Comment by taleinat** [comment]
@serhiy-storchaka, ping?

**Comment by taleinat** [comment]
Ping, @serhiy-storchaka?

**Review by rhettinger — APPROVED** [review]

**Review by iritkatriel — CHANGES_REQUESTED** [review]
This has merge conflicts now.

**Comment by encukou** [comment]
I'll close, see my comment in the issue. Feel free to reopen if you disagree.

**Pull request closed without merging**
