### PR TITLE
gh-74895: getaddrinfo no longer raises OverflowError

### PR DESCRIPTION
**Pull request by smejkar**
http://bugs.python.org/issue30710

Depends on http://bugs.python.org/issue30711 to pass test_getaddrinfo_overflow.

* Issue: gh-74895

### CODE REVIEW

**Comment by smejkar** [comment]
@serhiy-storchaka to pass checks, should I (a) wait till #2436 is merged, (b) relax test_getaddrinfo_overflow, or (c) rebase this onto #2436?

**Review by MaxwellDupre — CHANGES_REQUESTED** [review]
Test output:
`FAIL: test_getaddrinfo_overflow (test.test_socket.GeneralModuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/me/Documents/cpython/Lib/test/test_socket.py", line 1370, in test_getaddrinfo_overflow
    socket.getaddrinfo(None, _testcapi.LONG_MAX + 1)
AssertionError: gaierror not raised
`
Please fix.

**Comment by arhadthedev** [comment]
@giampaolo, @gpshead (as network experts)

**Comment by gpshead** [comment]
> @serhiy-storchaka to pass checks, should I (a) wait till #2436 is merged, (b) relax test_getaddrinfo_overflow, or (c) rebase this onto #2436?

I effectively reworked the test, we don't actually want an error behavior on specific numeric values as we had in the past, we just want to report and error if the underlying platform's getaddrinfo() call reports an error. Not all of them do, or at least not all at the same values.

for all practical purposes I doubt it matters much. it'd be nice for values outside of 16-bit unsigned to be rejected, but that only makes strict sense for IPv4 and IPv6. Other protocols are free to treat numeric service names (aka port) differently.

**Review by gpshead — APPROVED** [review]

**Pull request merged**
