### PR TITLE
[2.7] bpo-30236: Backport regrtest options -m and -G.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**

### CODE REVIEW

**Comment by vstinner** [comment]
Hum, if you want to backport other features from master, I would suggest to first write an unit test in master, and then also backport the unit test.

**Comment by serhiy-storchaka** [comment]
No, I don't plan backporting other features. Writing tests requires much larger rewriting the code than this patch.

**Review by vstinner — APPROVED** [review]
LGTM. I tested --match with a method name and a filename, both work. I also tested --failfast, it worked too.

**Comment by vstinner** [comment]
> No, I don't plan backporting other features. Writing tests requires much larger rewriting the code than this patch.

It's fine, go ahead ;-)

**Pull request merged**
