### PR TITLE
bpo-32116: Add csv2list() and list2csv() to csv module

### PR DESCRIPTION
**Pull request by paullongnet**
Added two subroutines.  One function to read a csv file to a list (csv2list) and another procedure to write list to a csv file.

https://bugs.python.org/issue32116

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by berkerpeksag** [comment]
Thank you for the PR, but this needs to be discussed on bugs.python.org first. The "skip issue" label is only for trivial issues like typo fixes.

**Comment by Mariatta** [comment]
Thanks for the PR, however I must close it, since it was decided in the bug tracker that we won't add it to the standard library.

**Comment by paullongnet** [comment]
How can just one person make that sort of decision?  There was only one person who replied.

**Pull request closed without merging**
