### PR TITLE
gh-111965: Use critical sections to make io.BufferedIOBase and its related classes thread safe

### PR DESCRIPTION
**Pull request by Mayuresh16**
cc: @colesbury @corona10 

* Issue: gh-111965

### CODE REVIEW

**Comment by Mayuresh16** [comment]
@colesbury  Can you please review this draft PR once to help me to understand the issue if any exists in my work?

**Review by colesbury — COMMENTED** [review]
This looks generally like a reasonable approach.

* ~~You will need to sign the CLA~~
* You should make sure the build passes.

EDIT: Sorry - I see that you've already signed the CLA.

**Comment by Mayuresh16** [comment]
> * You should make sure the build passes.

Yeah, contributing for the first time so had a struggle bit but it was fun to begin and understand build checks too ;)

**Review by colesbury — APPROVED** [review]
Thanks @Mayuresh16, this LGTM.

**Review by corona10 — APPROVED** [review]
LGTM, In the end, we should support getter/setter from AC.

**Pull request merged**
