### PR TITLE
gh-87347: Add parenthesis around macro arguments

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by vstinner** [comment]
My PR #92815 was just the starter.

@serhiy-storchaka @erlend-aasland: Here is the main plate :-D Would you mind to review it?

**Review by erlend-aasland — APPROVED** [review]
This looks ok to me.

**Comment by vstinner** [comment]
``./configure --enable-pystats`` was broken: I reverted some pycore_code.h changes.

Py_MEMBER_SIZE() was also broken: I added an unit test and I reverted my change.

**Comment by vstinner** [comment]
Oh no, this change added a regression in PyObject_NEW(): issue #94185.

**Pull request merged**
