### PR TITLE
bpo-35784: Include optional kwargs in hashlib.new() documentation

### PR DESCRIPTION
**Pull request by ta1hia**
Updating documentation for hashlib.new(), including Doc/library/hashlib.rst and the docstring in Lib/hashlib.py. 

https://bugs.python.org/issue35784

https://bugs.python.org/issue35784

### CODE REVIEW

**Review by gpshead — APPROVED** [review]
A news entry isn't really necessary for a documentation update, but is harmless regardless. :)

**Comment by rhettinger** [comment]
> additional keyword arguments that are specific to the selected hashing algorithm

This is going to raise the question of which keywords are available for each algorithm and what they do.  It would be nice if we had a summary table (like that at the top of the *itertools()* documentation).

**Comment by gpshead** [comment]
> This is going to raise the question of which keywords are available for each algorithm and what they do. It would be nice if we had a summary table (like that at the top of the itertools() documentation).

Lets not make such a table.  People shouldn't use `hashlib.new()` in _most_ code.  It is a conveinence function for the use case where someone needs to choose a hash algorithm at runtime.  I don't want to duplicate documentation for the same thing in two places in hashlib.rst.

The one true canonical place for arguments for any given hash function to be defined is in the documentation for the `hashlib.$algorithmname()` constructor. Or individual documentation specific to each algorithm should we wind up in a situation where a `$algorithmname` constructor no longer makes sense (as some of the plethora of suffixed blake$mumble variants might do).  Not as part of `hashlib.new()`.

**Comment by tahia-khan** [comment]
@tiran should this PR be closed then, since the semantic might change anyway after you finish integrating OpenSSL?

**Comment by tiran** [comment]
> @tiran should this PR be closed then, since the semantic might change anyway after you finish integrating OpenSSL?

Makes sense, let's close it. Thanks for your contribution. :+1:

**Pull request closed without merging**
