### PR TITLE
Fix typo in SourceLoader.path_stats docstring

### PR DESCRIPTION
**Pull request by kwentine**

### CODE REVIEW

**Comment by qagren** [comment]
First corrects a typo and then tries to phrase parameter type hints consistently in docstrings of `SourceLoader` methods.

**Review by vstinner — APPROVED** [review]
LGTM.

But you have to regenerate importlib genereated files. Use "make regen-importlib" on Linux for example.

**Comment by qagren** [comment]
Ran `./configure && make regen-importlib` (no pretending to understand more than roughly what it does ^^)

**Comment by vstinner** [comment]
I attempted to automatically backport this change to 3.6 and 3.7 but there are conflict. I don't think that it's worth it to backport it manually, so I close the PR. Thanks @qagren for your fix!

**Pull request merged**
