### PR TITLE
bpo-33370: Add .mypy_cache to .gitignore

### PR DESCRIPTION
**Pull request by cypher-naman**
Added `.mypy_cache` to `.gitignore`

Mentored by @CuriousLearner 

https://bugs.python.org/issue33370

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Comment by matrixise** [comment]
I am sorry, but I don't see why we need to have .mypy_cache in the .gitignore file...

As @brettcannon has said, you have to modify your global .gitignore and not the .gitignore of this project.

Have a nice day,

**Comment by sharma-naman** [comment]
My account is ready.

**Comment by ethanhs** [comment]
There is already an open PR here that passes CI https://github.com/python/cpython/pull/6614. I also don't understand why this is needed?

**Comment by brettcannon** [comment]
Closing this as a duplicate of #6614.

**Pull request closed without merging**
