### PR TITLE
bpo-34764: improve docs example of iter() with sentinel value

### PR DESCRIPTION
**Pull request by chris-rands**
https://bugs.python.org/issue34764

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by chris-rands** [comment]
Actually is it necessary to set `random.seed()` in such documentation example code snippets to ensure that the output is reproducible?

**Review by rhettinger — CHANGES_REQUESTED** [review]
I would like to keep something closer to the original.   The random() example is not a motivating use case.  Instead, consider a block-reader example or some other non-toy use case:

    # Read data in chunks
    for block in iter(partial(f.read, 128), ''):
        ...

This *partial()* can be replaced with ``lambda: f.read(128)`` or with a *def* statement.

**Comment by tirkarthi** [comment]
Doctest fails on Travis since `mydata.db` is not present during execution. You can convert it back to a normal example code or wrap it inside a function and not calling it.

**Review by rhettinger — CHANGES_REQUESTED** [review]
Fixed-length block reads would be more typical for binary data.

**Comment by chris-rands** [comment]
Thanks @rhettinger for your patience! I have made the requested changes (and fixed the indentation); please review again

**Review by rhettinger — APPROVED** [review]

**Pull request merged**
