### PR TITLE
minor: fix typo in test doc, fix flake8 issues

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by tirkarthi** [comment]
Typo fix LGTM. I am not sure the whitespace changes are needed. There are other parts in stdlib that are also not flake8 compliant.

**Comment by blueyed** [comment]
ok, reverted - I've just thought it could be also fixed while at it.

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Comment by tirkarthi** [comment]
Thanks @blueyed :)

**Pull request merged**
