### PR TITLE
gh-85283: Build termios extension with the limited C API

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-85283

----
📚 Documentation preview 📚: https://cpython-previews--116928.org.readthedocs.build/

### CODE REVIEW

**Comment by kulikjak** [comment]
Hi! After this commit, I am seeing the following errors when building main on Solaris:
```
/..../cpython/Modules/termios.c:430:20: error: 'errno' undeclared (first use in this function)
  430 |     if (r == -1 && errno == EINVAL) {
      |                    ^~~~~
/..../cpython/Modules/termios.c:56:1: note: 'errno' is defined in header '<errno.h>'; did you forget to '#include <errno.h>'?
   55 | #include "clinic/termios.c.h"
  +++ |+#include <errno.h>
```
AFAICT, this is because of the newly added `#define Py_LIMITED_API 0x030d0000`, which "hides" the `errno.h` include in `Python.h` (same as the newly added `string.h` include). When I add the missing include, it compiles again.

Should I create a PR with a fix?

**Comment by vstinner** [comment]
```
/..../cpython/Modules/termios.c:430:20: error: 'errno' undeclared (first use in this function)
  430 |     if (r == -1 && errno == EINVAL) {
```

That's strange. I cannot find this line in the main branch.

Do you have a patch on top of the main branch? If yes, you should consider to propose it upstream?

In main, I have:

```c
    if (r == -1) {
        return PyErr_SetFromErrno(state->TermiosError);  // LINE 430
    }
```

**Comment by kulikjak** [comment]
Oh, I am very sorry. This is indeed from an internal patch and not in the `termios.c` sources...

It's a patch that workarounded an issue with the `TIOCGWINSZ` `ioctl` on Solaris, which I forgot to remove before (and since it was just a temporary workaround, I didn't upstream it).

**Comment by vstinner** [comment]
> It's a patch that workarounded an issue with the TIOCGWINSZ ioctl on Solaris, which I forgot to remove before (and since it was just a temporary workaround, I didn't upstream it).

Well, either remove it, or propose it upstream. If you keep it, just add <errno.h> include ;-)

**Pull request merged**
