### PR TITLE
gh-115618: Remove improper Py_XDECREFs in property methods

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-115618

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
It has no effect in main, but in 3.11 the test crashes without the fix.

**Review by Eclips4 — APPROVED** [review]

**Comment by eltoder** [comment]
@serhiy-storchaka Currently your test passes on 3.12 and main without the fix, because None is immortal. AFAICT it is not possible to write a test to catch refcount bugs for immortal objects. What do you think if we change the debug versions of `Py_INCREF`/`Py_DECREF` to update the stats even for immortal objects? Then your test will catch this bug even on 3.12+.

**Comment by Eclips4** [comment]
> @serhiy-storchaka Currently your test passes on 3.12 and main without the fix, because None is immortal. AFAICT it is not possible to write a test to catch refcount bugs for immortal objects. What do you think if we change the debug versions of `Py_INCREF`/`Py_DECREF` to update the stats even for immortal objects? Then your test will catch this bug even on 3.12+.

Personally I do not think that this is worth the effort.

**Comment by eltoder** [comment]
@Eclips4 no, that test doesn't do anything with the total refcount, it only checks that decrefing an immortal object doesn't change its refcount. So it will be fine. We can improve the test by checking incref as well, which will also make it balanced. The test also hard-codes the boundaries of the smallint cache instead of using the macros, which can also be improved.

**Comment by serhiy-storchaka** [comment]
> What do you think if we change the debug versions of `Py_INCREF`/`Py_DECREF` to update the stats even for immortal objects?

I afraid that it is too late, and many tests will show unbalanced refcounts.

**Pull request merged**
