### PR TITLE
bpo-1635741: Fix reference cycle by calling explicit gc collection in main interpreter

### PR DESCRIPTION
**Pull request by shihai1991**
Authored-by: Victor Stinner <vstinner@python.org>

https://bugs.python.org/issue1635741

### CODE REVIEW

**Comment by shihai1991** [comment]
Before this PR:
sys.gettotalrefcount: 14288
sys.gettotalrefcount: 18042
sys.gettotalrefcount: 21796
sys.gettotalrefcount: 25550
sys.gettotalrefcount: 29304
sys.gettotalrefcount: 33058
sys.gettotalrefcount: 36812
sys.gettotalrefcount: 40566
sys.gettotalrefcount: 44320
sys.gettotalrefcount: 48074

After this PR:
sys.gettotalrefcount: 10537
sys.gettotalrefcount: 10540
sys.gettotalrefcount: 10543
sys.gettotalrefcount: 10546
sys.gettotalrefcount: 10549
sys.gettotalrefcount: 10552
sys.gettotalrefcount: 10555
sys.gettotalrefcount: 10558
sys.gettotalrefcount: 10561
sys.gettotalrefcount: 10564

**Comment by vstinner** [comment]
Merged since it seems to fix multiple issues: https://github.com/python/cpython/pull/21902#issuecomment-674926066

Does it fix your issue with encoding names and encodings._aliases?

**Comment by vstinner** [comment]
cc @ncoghlan @ericsnowcurrently: Python finalization is getting better ;-) Yet another GC collection at exit!

**Comment by shihai1991** [comment]
> Merged since it seems to fix multiple issues: [#21902 (comment)](https://github.com/python/cpython/pull/21902#issuecomment-674926066)
> 
> Does it fix your issue with encoding names and encodings._aliases?

Yes, this PR have fix my issue. there have no remaining encodings.aliases in refdumps.
Thanks a million, victor. I have learned much in this issue.

**Comment by vstinner** [comment]
I'm not sure that the GC is still fully functionnal after PyInterpreterState is cleared, but at least, it seems like there were a bunch of reference cycles.

cc @pablogsal

**Comment by animalize** [comment]
Just curious, what are the three leaks.

**Comment by shihai1991** [comment]
> Just curious, what are the three leaks.

You found this detail. I checked that some `str` object own the changed refcount in each iteration(not check the details).

**Pull request merged**
