### PR TITLE
gh-111488: Changed error message in case of no 'in' keyword after 'for' in cmp

### LINKED ISSUE #111488: Confusing `SyntaxError` message for `x for x if range(1)`
# Bug report

Today I made a typo: instead of `in` I wrote `if`.
I was quite interested to see the error message:

```python
>>> [x for x if range(1)]
  File "<stdin>", line 1
    [x for x if range(1)]
           ^^^^^^^^^^^^^
SyntaxError: expected 'else' after 'if' expression
```

I don't think that this error message is correct. Why? Because even if we follow the rabbit hole and use `else`, we won't be ever correct:

```python
>>> [x for (x if range(1) else y) in range(1)]
  File "<stdin>", line 1
    [x for (x if range(1) else y) in range(1)]
            ^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot assign to conditional expression
```

So, maybe we should change it to be something like:

```python
>>> [x for x if range(1)]
  File "<stdin>", line 1
    [x for x if range(1)]
             ^^
SyntaxError: expected 'in', got 'if'
```

Suggestions about wording are welcome :)

If others agree, I would like to work on this.

### Linked PRs
* gh-113656

### PR DESCRIPTION
**Pull request by grigoriev-semyon**
Fixes #111488 

* Issue: gh-111488

### CODE REVIEW

**Comment by pablogsal** [comment]
This approach doesn't work. Please read the discussion on the issue, particularly this comment:

https://github.com/python/cpython/issues/111488#issuecomment-1787205459

For example, this PR breaks this case:

```
>>> [x for a, b, (c + 1, d()) in y]
  File "<stdin>", line 1
    [x for a, b, (c + 1, d()) in y]
                  ^^^^^
SyntaxError: cannot assign to expressio
```

as it now shows:

```
>>> [x for a, b, (c + 1, d()) in y]
  File "<stdin>", line 1
    [x for a, b, (c + 1, d()) in y]
                              ^^
SyntaxError: 'in' expected after for-loop variables
```

**Review by pablogsal — CHANGES_REQUESTED** [review]
Please check the discussion on the issue

**Comment by grigoriev-semyon** [comment]
@pablogsal 
As I understand `| 'async'? 'for' a=star_targets+ !'in'` match only string with star_targets(1+) after `for` and no `in` keyword

and it works when i pass smth like `[x for x() in c]`
but it doesn't work in your testcase
can you help me to understand the difference between cases?
as i understand `a, b, (c + 1, d())` wouldn't match with star_targets
but it matches and existing of 'in' kw doesn't help

**Comment by grigoriev-semyon** [comment]
I understood why this doesn't work: because star_targets crashes on the first incorrect "character" and then `!in` works, which is successful because the next token is really not `in`

But I don't know how to accurately describe the expression(maybe incorrect by star_targets view) between `for` and `in`. Can I get some hint?

**Comment by grigoriev-semyon** [comment]
fixed

```
➜  ~ python3.13
Python 3.13.0a2+ (heads/main-dirty:7b74e4141b, Jan  4 2024, 01:39:25) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> [x for a, b, (c + 1, d()) in y]
  File "<stdin>", line 1
    [x for a, b, (c + 1, d()) in y]
                  ^^^^^
SyntaxError: cannot assign to expression
>>> [x for a, b, (c + 1, d()) if y]
  File "<stdin>", line 1
    [x for a, b, (c + 1, d()) if y]
                              ^^
SyntaxError: 'in' expected after for-loop variables
>>> 
```

**Comment by grigoriev-semyon** [comment]
I have made the requested changes; please review again

**Comment by grigoriev-semyon** [comment]
Hello, I have made the requested changes; please review again :)

**Comment by pablogsal** [comment]
This is better but note lowering the grammar to not include expressions will still change existing errors. For example:

```
>>> [x for a>b if z else 42 in x]
  File "<stdin>", line 1
    [x for a>b if z else 42 in x]
SyntaxError: cannot assign to conditional expression
```

changes to

```
>>> [x for a>b if z else 42 in x]
  File "<stdin>", line 1
    [x for a>b if z else 42 in x]
            ^
SyntaxError: 'in' expected after for-loop variables
```

I think is not too bad because the error is still correct but this may affect other constructs, although I think the error will more or less be correct (maybe it will show AFTER some other real error, though). @lysnikolaou what do you think?

**Comment by pablogsal** [comment]
An example of what I mean:

```
>>> [x for (yield z) with y]
  File "<stdin>", line 1
    [x for (yield z) with y]
            ^^^^^^^
SyntaxError: cannot assign to yield expression
```

will change to

```
>>> [x for (yield z) with y]
  File "<stdin>", line 1
    [x for (yield z) with y]
                     ^^^^
SyntaxError: 'in' expected after for-loop variables
```

here are two errors and now we show the one that's further from the start of the comprehension. So after fixing that there is another error reported BEFORE it.

I am not sure if we should care about that, but this is a difference.

**Comment by pablogsal** [comment]
(@grigoriev-semyon don't change anything yet, let's check what @lysnikolaou thinks)

**Comment by lysnikolaou** [comment]
I'm okay with both, although I'm incline to say let's fix this one and accept that there might be cases that become suboptimal because of it.

Either way we have to accept that there are error messages that are very hard to get right, and this might be one of them. I'm also kind of inclined to try and have a more sophisticated approach to this and other error messages, where you have a priority system where you can try more than one `invalid_` rules and the error with the highest priority wins. Don't know how much effort that would take though.

**Comment by grigoriev-semyon** [comment]
@pablogsal I tried to improve the result, but it seems difficult.

If you agree, I suggest merging this PR and creating a task to further improve the error in this place. 
I am also ready to work on a future task.

**Comment by pablogsal** [comment]
Yeah I think we will merge this and check how it goes. Thanks for the patience @grigoriev-semyon and the good work!

**Review by pablogsal — APPROVED** [review]

**Comment by sobolevn** [comment]
Congrats @grigoriev-semyon! Thanks everyone :)

**Pull request merged**
