### PR TITLE
bpo-35814: More updates to the annotated assignments docs

### PR DESCRIPTION
**Pull request by ilevkivskyi**
A documentation update for https://github.com/python/cpython/pull/13760

cc @pablogsal @gvanrossum 

https://bugs.python.org/issue35814

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by ilevkivskyi** [comment]
This is purely a doc fix, so I think this can be merged now.

**Comment by pablogsal** [comment]
Thanks, @ilevkivskyi for finishing the docs! One question, should we add these changes also to "What's new in 3.8?

**Comment by ilevkivskyi** [comment]
I don't know TBH, on one hand it is really minor, on the other hand it is a change to the syntax. Maybe somewhere in the "Other Language Changes" section?

**Comment by gvanrossum** [comment]
These together definitely deserve to be mentioned in What's New and also a versionadded comment in the section describing the syntax.

**Pull request merged**
