### PR TITLE
bpo-27585: Cancelled lock waiter wakes up the next one

### PR DESCRIPTION
**Pull request by msornay**
Avoid a deadlock when the waiter who is about to take the lock is cancelled

Issue #27585: http://bugs.python.org/issue27585
Original PR on asyncio repository: https://github.com/python/asyncio/pull/467

### CODE REVIEW

**Comment by popravich** [comment]
Guys! @1st1, @asvetlov, @serhiy-storchaka,
Can anyone take a look at this patch, the issue is real PITA.

@msornay, probably, the same fix should be applied to `asyncio.Condition.wait()` method
as it uses the same logic as `asyncio.Lock.acquire()`:
if `await cond.wait()` is resolved but owning task is cancelled -- other waiters could end up in a deadlock

**Comment by asvetlov** [comment]
lgtm

**Comment by popravich** [comment]
Any news?

**Comment by jettify** [comment]
ping

**Comment by 1st1** [comment]
I'll take a look tomorrow/the day after.

**Review by 1st1 — APPROVED** [review]

**Comment by Mariatta** [comment]
Does this still need backport? If not please remove the label.

**Pull request merged**
