### PR TITLE
bpo-40956: Convert _sqlite3.Connection to Argument Clinic

### PR DESCRIPTION
**Pull request by erlend-aasland**
Part 2 of 5, @corona10

https://bugs.python.org/issue40956

### CODE REVIEW

**Comment by erlend-aasland** [comment]
FYI, @corona10, this is the largest part of bpo-40956, and I see that it might be too much for one review. Let me know if I should break this PR up in multiple parts.

**Comment by corona10** [comment]
@vstinner cc @erlend-aasland 
I am quite busy until next week, Can you please take a look instead of me? ;)

**Comment by erlend-aasland** [comment]
> @vstinner cc @erlend-aasland
> I am quite busy until next week, Can you please take a look instead of me? ;)

Let me know if I should split this up; excluding the clinic code, the short stat is `3 files changed, 292 insertions(+), 210 deletions(-)`. I'll be happy to split it up, if that can help.

**Comment by erlend-aasland** [comment]
All right, how about this: I'll split this up in two parts:
1) All the straightforward methods
2) `Connection.execute*()` and `Connection.backup()`, which require small modifications in addition to AC

The former, with the larger line count, should be the easiest to review. The latter may end up with adjustments; I may not have chosen the best way to resolve the issues encountered.

**Pull request closed without merging**
