### PR TITLE
bpo-40421: Cleanup PyFrame C API

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue40421

### CODE REVIEW

**Comment by vstinner** [comment]
@markshannon: I started to review https://github.com/python/cpython/pull/32413 before seeing that it was already merged 3 hours ago, aaaah :-) So I created a PR instead.

I don't think that it's useful to mention that the function argument must not be NULL. We don't do that in the doc of other C API functions. It's implicit.

**Comment by vstinner** [comment]
In terms of API, PyFrame_GetLasti() returns an ``int``. Would it make sense to return ``Py_ssize_t``?

The code constructor makes sure that co_code cannot be larger than INT_MAX:

```
    /* Make sure that code is indexable with an int, this is
       a long running assumption in ceval.c and many parts of
       the interpreter. */
    if (PyBytes_GET_SIZE(con->code) > INT_MAX) {
        PyErr_SetString(PyExc_OverflowError,
                        "code: co_code larger than INT_MAX");
        return -1;
    }
```

**Comment by iritkatriel** [comment]
https://bugs.python.org/issue40421 is closed. What is the status of this PR?

**Comment by markshannon** [comment]
Thanks @vstinner 
Looks good to me.

@iritkatriel  This is just a minor tidy up, https://bugs.python.org/issue40421 can remain closed.

**Comment by markshannon** [comment]
> Would it make sense to return Py_ssize_t?

I don't think so.

**Comment by vstinner** [comment]
Merged, thanks for the review @markshannon

**Pull request merged**
