### PR TITLE
bpo-37973: Improve the docstrings of sys.float_info

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Taken from https://docs.python.org/3/library/sys.html#sys.float_info

https://bugs.python.org/issue37973

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
I don't think this needs a news entry.

**Comment by ammaraskar** [comment]
Maybe the definition of `DBL_MANT_DIG` should be pulled in as well?

**Review by mdickinson — APPROVED** [review]
Changes look good to me, as far as they go.

**Comment by mdickinson** [comment]
Merging. There are other possible improvements here, but they can come in later PRs, and shouldn't block the merge of this on.

**Pull request merged**
