### PR TITLE
Revert "bpo-36802: Drop awrite()/aclose(), support await write() and await close() instead (#13099)"

### PR DESCRIPTION
**Pull request by vstinner**
This reverts commit a076e4f5e42b85664693191d04cfb33e2f9acfa5.

https://bugs.python.org/issue36802

### CODE REVIEW

**Comment by vstinner** [comment]
This revert is an attempt to fix https://bugs.python.org/issue36870 regression.

**Comment by vstinner** [comment]
Without this change, python -m test test_asyncio -m test_drain_raises -v pass but logs a warning on my Windows VM:

```

test_drain_raises (test.test_asyncio.test_streams.StreamTests) ... Task exception was never retrieved
future: <Task finished name='Task-2' coro=<StreamWriter.drain() done, defined at C:\vstinner\python\master\lib\asyncio\streams.py:417> exception=ConnectionAbor
tedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)>
Traceback (most recent call last):
  File "C:\vstinner\python\master\lib\asyncio\streams.py", line 434, in drain
    await fut
  File "C:\vstinner\python\master\lib\asyncio\proactor_events.py", line 370, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\vstinner\python\master\lib\asyncio\windows_events.py", line 488, in send
    ov.WSASend(conn.fileno(), buf, flags)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```

With this PR, it pass but doesn't log any warning.

**Comment by asvetlov** [comment]
Please take a look on https://github.com/python/cpython/pull/13313
I believe it has a proper fix for messages generated by `test_drain_raises()`

**Comment by vstinner** [comment]
I merged PR #13313 instead.

**Pull request closed without merging**
