### PR TITLE
bpo-30593: Document that sqlite3.Cursor.executescript disregards isolation_level

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue30593

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@pablogsal I'm adding _skip news_ to this.

**Comment by pablogsal** [comment]
> @pablogsal I'm adding _skip news_ to this. Can be backported to 3.10 and 3.9 (3.8 doesn't even get doc updates anymore, right?).

Yep, docs changes can almost always be backported!

**Review by pablogsal — APPROVED** [review]

**Comment by erlend-aasland** [comment]
> Yep, docs changes can almost always be backported!

All right :) Thanks.

**Comment by erlend-aasland** [comment]
But I note that Berker chose only to apply backport labels for 3.10 and 3.9 to GH-26027. Maybe do likewise here?

**Comment by pablogsal** [comment]
> But I note that Berker chose only to apply backport labels for 3.10 and 3.9 to GH-26027. Maybe do likewise here?

I don't see personally any problem of improving the docs of all versions even if they are in sec fixes only, bit maybe I am missing some context...

**Review by berkerpeksag — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for reviewing, Berker & Pablo!

**Comment by berkerpeksag** [comment]
> I don't see personally any problem of improving the docs of all versions even if they are in sec fixes only, bit maybe I am missing some context...

It's because historically online documentation of security-fix-only branches weren't updated daily.

**Pull request merged**
