### PR TITLE
Link sys constants in pkgutil.rst

### PR DESCRIPTION
**Pull request by verhovsky**

### CODE REVIEW

**Comment by verhovsky** [comment]
@merwok can you merge this please?

**Review by JelleZijlstra — APPROVED** [review]
Thank you!

**Comment by JelleZijlstra** [comment]
Actually, I noticed this PR is against the 3.9 branch. Could you make it against main instead? We'll backport to 3.9 after merging.

**Comment by verhovsky** [comment]
Oh my god, I am very sorry everyone. I clicked the "Edit" button on GitHub and changed the "merge into" branch from `3.9` to `main`. I assumed it would just do the right thing, I didn't know that it would make thousands of commits and request a review from everyone.

I'm going to close this and open a new PR to avoid spamming everyone. Sorry.

**Comment by terryjreedy** [comment]
One cannot just change the target branch to main when the pr is branched from a maintenance branch.  You are effectively merging 3.9 into main.  You likely have to close this and start over with a branch off of main.

**Pull request closed without merging**
