### PR TITLE
GH-90208: Suppress OSError exceptions from `pathlib.Path.glob()`

### PR DESCRIPTION
**Pull request by barneygale**
`pathlib.Path.glob()` now suppresses all OSError exceptions, except those raised from calling `is_dir()` on the top-level path.

Previously, `glob()` suppressed ENOENT, ENOTDIR, EBADF and ELOOP errors and their Windows equivalents. PermissionError was also suppressed unless it occurred when calling `is_dir()` on the top-level path. However, the selector would abort prematurely if a PermissionError was raised, and so `glob()` could return incomplete results.

# Rationale

Globbing is a shell feature, per the `glob` module docs:

> The [`glob`](https://docs.python.org/3/library/glob.html#module-glob) module finds all the pathnames matching a specified pattern according to the rules used by the Unix shell

When implemented by shells, globbing matches as much as possible without aborting.

In fact, other Python functions that walk a directory tree usually suppress errors, e.g.:

- `glob.glob()`
- `os.walk()` and `os.fwalk()` (configurable)
- `pathlib.Path.walk()` (configurable)

The rationale is the same: an error from one file/directory isn't fatal for the walk, and we can continue walking elsewhere.

Finally, as noted above, `pathlib.Path.glob()` already ignores the most common kinds of `OSError`. This shows some recognition of the above rationale, though incomplete.

* Issue: gh-90208

### CODE REVIEW

**Comment by barneygale** [comment]
FAO @AlexWaygood, who pointed out the messy exception handling and poor test coverage in #104103

**Comment by AlexWaygood** [comment]
(I'm not 100% confident I understand all the subtleties here, so I'd rather leave this for Eryk or Steve to review, if that's okay!)

**Comment by barneygale** [comment]
Marking as a draft because it would be good to land #104292 first.

**Comment by barneygale** [comment]
@JelleZijlstra would you be interested in reviewing this? Thank you!

**Review by JelleZijlstra — APPROVED** [review]
The rationale looks solid, but this is enough of a behavior change that I'd probably not backport.

Your description made me ask why we ignore only that specific set of exceptions (ENOENT, ENOTDIR, EBADF, ELOOP). It looks like that set is used throughout pathlib in places where it makes more sense than here, so there may not have been a strong intent to ignore only those specific errors for globs.

**Comment by barneygale** [comment]
Thanks! I agree on not backporting.

**Pull request merged**
