### PR TITLE
bpo-40275: Use new test.support helper submodules in tests

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by vstinner** [comment]
Strange. "Tests / Check for source changes (pull_request)" failed with "fatal: origin/master...HEAD: no merge base".

```
  shell: /bin/bash -e {0}
Run if [ -z "GITHUB_BASE_REF" ]; then
  if [ -z "GITHUB_BASE_REF" ]; then
    echo '::set-output name=run_tests::true'
  else
    git fetch origin $GITHUB_BASE_REF --depth=1
    git diff --name-only origin/$GITHUB_BASE_REF... | grep -qvE '(\.rst$|^Doc|^Misc)' && echo '::set-output name=run_tests::true' || true
  fi
  shell: /bin/bash -e {0}
From https://github.com/python/cpython
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
fatal: origin/master...HEAD: no merge base
```

https://github.com/python/cpython/pull/21764/checks?check_run_id=958183690

**Comment by shihai1991** [comment]
> Strange. "Tests / Check for source changes (pull_request)" failed with "fatal: origin/master...HEAD: no merge base".
> 
> ```
>   shell: /bin/bash -e {0}
> Run if [ -z "GITHUB_BASE_REF" ]; then
>   if [ -z "GITHUB_BASE_REF" ]; then
>     echo '::set-output name=run_tests::true'
>   else
>     git fetch origin $GITHUB_BASE_REF --depth=1
>     git diff --name-only origin/$GITHUB_BASE_REF... | grep -qvE '(\.rst$|^Doc|^Misc)' && echo '::set-output name=run_tests::true' || true
>   fi
>   shell: /bin/bash -e {0}
> From https://github.com/python/cpython
>  * branch            master     -> FETCH_HEAD
>  * [new branch]      master     -> origin/master
> fatal: origin/master...HEAD: no merge base
> ```
> 
> https://github.com/python/cpython/pull/21764/checks?check_run_id=958183690

Oh, meet this problem again. I already open an thread in: https://discuss.python.org/t/why-the-ci-gate-in-fork-repo-has-been-disabled/4909.
Looks like nobody know the reason.

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
It failed on Windows:

```
ERROR: setUpClass (test.test_asyncio.test_proactor_events.ProactorEventLoopUnixSockSendfileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\a\1\s\lib\test\test_asyncio\test_proactor_events.py", line 937, in setUpClass
    with open(os_helper.TESTFN, 'wb') as fp:
NameError: name 'os_helper' is not defined
```

**Comment by shihai1991** [comment]
> It failed on Windows:
> 
> ```
> ERROR: setUpClass (test.test_asyncio.test_proactor_events.ProactorEventLoopUnixSockSendfileTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "d:\a\1\s\lib\test\test_asyncio\test_proactor_events.py", line 937, in setUpClass
>     with open(os_helper.TESTFN, 'wb') as fp:
> NameError: name 'os_helper' is not defined
> ```

updated.

**Comment by vstinner** [comment]
> updated

Ah, maybe the GitHub UI pointed me to the wrong build. Now I see that Azure Pipelines is running again.

**Comment by shihai1991** [comment]
> > updated
> 
> Ah, maybe the GitHub UI pointed me to the wrong build. Now I see that Azure Pipelines is running again.

Your are right. I have push a commit again: )

**Comment by shihai1991** [comment]
> Strange. "Tests / Check for source changes (pull_request)" failed with "fatal: origin/master...HEAD: no merge base".
> 
> ```
>   shell: /bin/bash -e {0}
> Run if [ -z "GITHUB_BASE_REF" ]; then
>   if [ -z "GITHUB_BASE_REF" ]; then
>     echo '::set-output name=run_tests::true'
>   else
>     git fetch origin $GITHUB_BASE_REF --depth=1
>     git diff --name-only origin/$GITHUB_BASE_REF... | grep -qvE '(\.rst$|^Doc|^Misc)' && echo '::set-output name=run_tests::true' || true
>   fi
>   shell: /bin/bash -e {0}
> From https://github.com/python/cpython
>  * branch            master     -> FETCH_HEAD
>  * [new branch]      master     -> origin/master
> fatal: origin/master...HEAD: no merge base
> ```
> 
> https://github.com/python/cpython/pull/21764/checks?check_run_id=958183690

Looks like `...` in `git diff --name-only origin/$GITHUB_BASE_REF... ' is redundant(I am not sure about it).
But It is worked actually after I removed it: https://github.com/shihai1991/cpython/pull/28/files

**Pull request merged**
