### PR TITLE
bpo-42064: Add module backref to `sqlite3` callback context

### PR DESCRIPTION
**Pull request by erlend-aasland**
Make sure that the module state will always outlive the callback context
by holding a strong reference to the module object in the callback 
context.

https://bugs.python.org/issue42064

### CODE REVIEW

**Comment by erlend-aasland** [comment]
FYI, first attempt is in a2d3eae2dabb03239d9a3bd5f8837287735e469e

**Comment by erlend-aasland** [comment]
The `AMD64 Arch Linux Asan Debug PR` buildbot failure is unrelated to this PR.

**Comment by erlend-aasland** [comment]
FYI, the windows CI failure is unrelated (`test_multiprocessing_spawn`).

**Comment by erlend-aasland** [comment]
> Whoa, that's certainly a big PR.

Did you filter out the auto-generated clinic changes?

```
$ git diff main  --stat Modules/_sqlite/*.[ch]
 Modules/_sqlite/connection.c | 55 ++++++++++++++++++++++++++++++++++++++-----------------
 Modules/_sqlite/connection.h |  1 +
 2 files changed, 39 insertions(+), 17 deletions(-)
```

**Review by encukou — APPROVED** [review]
This looks good, thanks!
One nitpick: it might not be not immediately clear that `create_callback_context` needs the defining class (i.e. exactly the `Connection` class, not a subclass which could have a different module). Do you want to add a comment on that?

**Pull request merged**
