### PR TITLE
Fix stderr bug in json.tool test

### PR DESCRIPTION
**Pull request by dhimmel**
See https://github.com/python/cpython/pull/201#discussion_r103229425.

Tagging @berkerpeksag

### CODE REVIEW

**Review by berkerpeksag — COMMENTED** [review]
I just did a quick review and it looks good to me in general. I still need to test it locally.

**Comment by dhimmel** [comment]
@berkerpeksag just wanted to check in on this PR. Would love to have it merged, since the two linked pull requests are dependent on it.

**Comment by dhimmel** [comment]
@mention-bot can you mention some relevant maintainers for this PR? I don't want progress to stall.

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
Thanks! :)

**Comment by dhimmel** [comment]
3.6 backport pull request is https://github.com/python/cpython/pull/676 (I guess GitHub doesn't automatically cross-reference issues in pull request titles).

**Pull request merged**
