### PR TITLE
bpo-34573: Simplify __reduce__() of set and dict iterators.

### PR DESCRIPTION
**Pull request by sir-sigurd**
https://bugs.python.org/issue34573

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]
LGTM!

**Comment by pablogsal** [comment]
@sir-sigurd The `odict` iterator cannot be simplified like this. If you include a test in the `OrderedDict` test suite that pickles the iterator and unpickles it (as now there is not any test that does this) and you run the test suite with `-R :` you will find that there are memory corruption/invalid reference counts. This is because the way the `tp_next` method on the iterator works is differently.

**Comment by vstinner** [comment]
@pablogsal: You showed me an awful corner case on a similar change for OrderedDict. So now I'm scared to approve such change for other types... Would it mind to approve it? (and maybe also merge it)

**Review by pablogsal — APPROVED** [review]
That corner case is a derivative of what is being handled in #9051. I think this is fine :)

**Pull request merged**
