### PR TITLE
gh-128317: Document `calendar.TextCalendar.formatweek`

### PR DESCRIPTION
**Pull request by hugovk**
Split from https://github.com/python/cpython/pull/128318/files#r1899194979 for backporting.

* Issue: gh-128317

----
📚 Documentation preview 📚: https://cpython-previews--128353.org.readthedocs.build/

### CODE REVIEW

**Review by erlend-aasland — APPROVED** [review]
Thanks!

**Comment by erlend-aasland** [comment]
See also #108202.

**Comment by StanFromIreland** [comment]
Hello, this was already in my PR #108202 what should I do?

**Comment by hugovk** [comment]
PR https://github.com/python/cpython/pull/127608? Let's continue over there.

**Pull request merged**
