### PR TITLE
bpo-40275: Fix a calling bug in threading_helper

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by shihai1991** [comment]
TODO: test tools should have unittest too.

**Comment by shihai1991** [comment]
@vstinner Hi, victor. Pls take a look if you have free time. Sorry, I introduced a potential bug in threading_helper :(

**Comment by vstinner** [comment]
Oh right, there are a few more:

```
$ pyflakes Lib/test/support/threading_helper.py 
Lib/test/support/threading_helper.py:50:9 undefined name 'gc_collect'
Lib/test/support/threading_helper.py:101:13 undefined name 'gc_collect'
Lib/test/support/threading_helper.py:127:16 undefined name 'verbose'
Lib/test/support/threading_helper.py:136:23 local variable 'starttime' is assigned to but never used
Lib/test/support/threading_helper.py:144:20 undefined name 'verbose'
Lib/test/support/threading_helper.py:150:45 undefined name 'sys'
```

**Comment by vstinner** [comment]
These bugs caused multiple buildbots failures: https://github.com/python/cpython/pull/20448

I created PR #20488 to fix all pyflakes warning.

**Comment by vstinner** [comment]
> @vstinner Hi, victor. Pls take a look if you have free time. Sorry, I introduced a potential bug in threading_helper :(

That's ok. I didn't spot these issues neither, and test_support passed.

**Comment by vstinner** [comment]
I merged my https://github.com/python/cpython/pull/20488 instead.

**Comment by shihai1991** [comment]
> I merged my #20488 instead.

Got it, thanks.

**Pull request closed without merging**
