### PR TITLE
docs: in venv table use executable name

### PR DESCRIPTION
**Pull request by musvaage**
<s>changes PowerShell to pwsh and pwsh.exe</s>
changes POSIX PowerShell to pwsh

----
📚 Documentation preview 📚: https://cpython-previews--124315.org.readthedocs.build/

### CODE REVIEW

**Comment by vsajip** [comment]
On my computer, there's no `pwsh.exe` - Powershell is `powershell.exe`. So I'm not sure if your change should be applied as is - perhaps have `powershell.exe` or `pwsh.exe` replace `PowerShell`?

**Comment by AA-Turner** [comment]
> On my Windows computer, there's no `pwsh.exe` - PowerShell is `powershell.exe`. So I'm not sure if your change should be applied as is - perhaps have `powershell.exe` or `pwsh.exe` replace `PowerShell`?

I have both -- `pwsh.exe` is PowerShell 7 and `powershell.exe` is PowerShell 5 (Windows PowerShell). [This appears to be official](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.4#renamed-powershellexe-to-pwshexe).

A

**Review by AA-Turner — CHANGES_REQUESTED** [review]
The change for POSIX seems fine but per Vinay's note the Windows entry should read either "PowerShell" or indicate that both `powershell.exe` and `pwsh.exe` are supported.

A

**Comment by musvaage** [comment]
> Windows entry

unless something like the following is workable, I'll revert to the string PowerShell, and perform a soft reset

please clarify Member preference

Doc/library/venv.rst

```diff
  .. versionadded:: 3.8
     PowerShell activation scripts installed under POSIX for PowerShell Core
-    support.
+    support (users of PowerShell 5.1 replace pwsh.exe with powershell.exe in
+    the table).
```

**Comment by musvaage** [comment]
@AA-Turner

if neither the herein nor last comment's ideas are workable, I'll revert to the string PowerShell and perform a soft reset

in the last comment it was suggested the text in `.. versionadded:: 3.8` could be supplemented

a different approach might be adding a **Note:** directly after the text of `.. versionadded:: 3.8`.

```diff
     support.
  
+ .. note::
  
+     Users of PowerShell 5.1 replace pwsh.exe with powershell.exe in
+     the table.
+    
  You don't specifically *need* to activate a virtual environment,
```

**Comment by musvaage** [comment]
> `pwsh.exe`
> `powershell.exe`

I was disinclined to widen the table's second column.

<hr>

Lib/venv/scripts/activate

CPython and PyPI packages' docs would be simpler if the bash/zsh script was named `activate.sh`.

`python -m venv venv`

Then it could be coded that resultant of the above command venv/bin/activate.sh was copied to venv/bin/activate.

That could remain in the code for some years until a notification was made on file copying deprecation.

regarding documentation simplification

At minimum then is a packager notice to the user to run the appropriate script for their preferred command-line shell.

**Review by vsajip — APPROVED** [review]

**Pull request merged**
