### PR TITLE
Replaced some instances of ClassName.method with super().method.

### PR DESCRIPTION
**Pull request by atombrella**
I replaced this pattern in `SSLSocket`. It's all over the place in the codebase. I don't know if it merits a single ticket for each area, or just the whole code-base.

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
Please open an issue on the [bug tracker](https://bugs.python.org/) for discussion. Or even two issues, because different modules have different maintainers, and the changes should be reviewed and merged separately.

**Comment by methane** [comment]
This PR is linked from [bpo-31853](https://bugs.python.org/issue31853).

**Review by tiran — CHANGES_REQUESTED** [review]
Don't recycle an unrelated and already closed ticket

**Comment by rhettinger** [comment]
Atombrella, I think you're proceeding under that false assumption that using super() if always or often better than direct parent class references.  Python's super() is complicated (and not very fast). It would be easy to accidentally introduce behavior changes.  

Another consideration is that the effects of such changes are hard-to-test because the MRO is controlled by subclasses.  That means that in general we cannot know for sure where super() is going to forward it call (because it was designed to support cooperative multiple inheritance).

In general, changes from direct parent class references to super() should only be done if there is a known use case and if the current maintainer of a module agrees to the change.

**Comment by atombrella** [comment]
OK. Since the ticket has been marked as "not as a bug", I'll close my close my pull request. Thanks for the detailed descriptions.

**Pull request closed without merging**
