### PR TITLE
Improvements to typing documentation

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Documents a few omitted classes and adds NamedTuple methods.

@ilevkivskyi would you mind reviewing this?

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
The Travis failure appears to be a Sphinx bug. Reported as sphinx-doc/sphinx#3600.

**Comment by DimitrisJim** [comment]
Indeed, it was already reported at https://github.com/sphinx-doc/sphinx/issues/3597, waiting for https://github.com/sphinx-doc/sphinx/issues/3598 to be resolved.

**Review by ilevkivskyi — APPROVED** [review]
Thank you for PR! This looks good to me.

(I have noticed inconsistent formatting (number of leading spaces), but I think there should be a _separate_ PR fixing it in the whole file.)

**Comment by rhettinger** [comment]
LGTM

**Review by berkerpeksag — APPROVED** [review]

**Pull request merged**
