### PR TITLE
bpo-38252: use 8-byte step to detect ASCII sequence in 64bit Windows build

### PR DESCRIPTION
**Pull request by ghost**
In 64-bit Windows builds, C type `unsigned long` is 4-byte integer.
Now use `size_t`, it's 8-byte integer in 64-bit Windows builds.

https://bugs.python.org/issue38252

### CODE REVIEW

**Review by eamanu — APPROVED** [review]
Good improve! LGTM

**Comment by csabella** [comment]
@animalize please resolve the merge conflicts.  Thank you!

**Comment by animalize** [comment]
> @animalize please resolve the merge conflicts. Thank you!

Solved conflicts.

**Comment by animalize** [comment]
I have made the requested changes; please review again

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. Please add a NEWS entry.

**Comment by animalize** [comment]
Close and reopen this PR to trigger build bots.

**Comment by animalize** [comment]
Thanks for your review.

**Pull request merged**
