### PR TITLE
bpo-43350: Don't reset active statements twice in _pysqlite_query_execute()

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue43350

### CODE REVIEW

**Comment by erlend-aasland** [comment]
_skip news_

**Comment by erlend-aasland** [comment]
CI seems stuck. Re-opening to trigger it again.

**Comment by gstein** [comment]
I would suggest this be closed, in favor of #26015, which adds a `(void)` to the remaining reset() invocation.

**Comment by erlend-aasland** [comment]
Closing this in favour of #27844.

**Pull request closed without merging**
