### PR TITLE
bpo-36624: Add platform constants in Lib/test/support (support.MS_WINDOWS, support.AIX, etc)

### PR DESCRIPTION
**Pull request by aixtools**
This is just the first phase - an example of what could be - although I have added other constants as discussed during #7800.

During the previous discussion, backport was discussed, and if manual work is needed for the backport(s) I'll do that as well.

https://bugs.python.org/issue36624

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
Please rebase.

**Review by ned-deily — COMMENTED** [review]
In general, I am not in favor of a change like this.  The benefits seem to me to be marginal and mostly a matter of taste.  The downsides are that the change proposes to change 93(!) files with the potential introduction of logic errors in the translation and, more importantly, will likely prevent the auto backport of various future PRs until 3.7 is no longer maintained.  BTW, a change of this type and scope cannot be backported to 3.7.  I'm not going to insist on rejecting it for 3.8 but I'd rather we didn't.  As I've mentioned when reviewing previous similar attempts, people reviewing the code base are *still* going to need to lean the existing idioms for platform checking (i.e. sys.platform checks) because they will still exist in the non-test modules.  So with this change people would have to learn and recognize *two* different ways of doing something and know when to use each where today we only have one for the most part (and I would support cleaning up the small number of outliers).

**Comment by aixtools** [comment]
> 
> 
> Please rebase.

I assume this is needed because of the conflicts. Unfortunately, I have never used rebase before and I fear breaking anything. It is probably misplaced fear, but I'll prefer to save resolving this conflict after more comments re: the intent, before I risk breaking anything.

Thanks for making me aware!

**Comment by auvipy** [comment]
> > Please rebase.
> 
> I assume this is needed because of the conflicts. Unfortunately, I have never used rebase before and I fear breaking anything. It is probably misplaced fear, but I'll prefer to save resolving this conflict after more comments re: the intent, before I risk breaking anything.
> 
> Thanks for making me aware!

Would you mind allowing PR on your branch for rebasing help from me?

**Comment by aixtools** [comment]
> 
> 
> > > Please rebase.
> > 
> > 
> > I assume this is needed because of the conflicts. Unfortunately, I have never used rebase before and I fear breaking anything. It is probably misplaced fear, but I'll prefer to save resolving this conflict after more comments re: the intent, before I risk breaking anything.
> > Thanks for making me aware!
> 
> Would you mind allowing PR on your branch for rebasing help from me?

Not at all. Again, "new" action for me. Is that something I need to change on my github branch.
p.s. I have been exercising using rebase, cleaning up when things go wrong, etc.. so I think I may manage it okay. If not done in a week, I'll get back to you.

**Comment by aixtools** [comment]
> 
> 
> In general, I am not in favor of a change like this. The benefits seem to me to be marginal and mostly a matter of taste. The downsides are that the change proposes to change 93(!) files with the potential introduction of logic errors in the translation and, more importantly, will likely prevent the auto backport of various future PRs until 3.7 is no longer maintained. BTW, a change of this type and scope cannot be backported to 3.7. I'm not going to insist on rejecting it for 3.8 but I'd rather we didn't. As I've mentioned when reviewing previous similar attempts, people reviewing the code base are _still_ going to need to lean the existing idioms for platform checking (i.e. sys.platform checks) because they will still exist in the non-test modules. So with this change people would have to learn and recognize _two_ different ways of doing something and know when to use each where today we only have one for the most part (and I would support cleaning up the small number of outliers).

My frustration with Python is that it seems reluctant to change, yet can also force changes, just because it is new. So, I am prepared to accept that this change does not go through. - that is the personal touch.

As someone who wishes to remain a Python "consumer", not a language developer - I have had learning issues trying to understand why sometimes sys.platform in different forms ( == 'xyz' ...:3 == 'xyz', ....startswith('xyz'). There seems to be neither rhyme nor reason. I read your argument as - this is they we have done it and I am hesitant to change.

Again, as a consumer, I look to things like Lib/test/*.py as "best-practice" - and imho, after reading many of the discussion (I dare not say all, there is that much history) I am still uncertain what is "better" from a language perspective. I frequently wonder ith sys.platform predated platform.system(). Or was sys.platform added later to assist with cross-builds.

Also, let me make clear - I have no personal preference if the constants are based on sys.platform or platform.system(). If there had been a performance argument "way back when" because sys.platform was much more efficient than platform.system() having them as a constant as much as possible is clearly better performance wise (my 'consumer' assumption. This is the core of why I was willing to dig into this - on a request.

And, just to be clear - if the change will not backport easily to 3.7 - I stated before I will do that manually, if need be. And as to the "core" where this approach is not (yet) taken - I am also willing to do that for 3.8 and 3.7. Again, my goal is not to develop new aspects of the language - but I do want it to be what I needed (and need) - a clear example of how things should be done.

I am trying to contribute - in ways that I can contribute now. Not in ways I first have to study and learn for 6 months or more.

Many thanks for your review!

**Comment by aixtools** [comment]
well, going to try to roll this back. Did not work the way it is suppossed to... Bah "rebase" :)

**Comment by aixtools** [comment]
OK - will need some help - I would rather NOT close this PR , throw away the current branch, and then submit the changes again in a new PR.

I have all the changes in a patch file - and I can apply all of those to 'master'. I should have done 'rebase' differently - learning curve...

Is there a clean way to do this - keeping this same PR - or is it just easier to close here, and start over - in a new PR?

**Comment by terryjreedy** [comment]
Closing the PR will remove the noise and undo the spurious review requests.  It will not delete the current bpo-36624-support branch of your aixtools/cpython fork.  If that branch was branched off of the master branch, you should be able update it by pull or fetch/merge upstream/master on your working machine and push to the fork.  Then make a new PR, checking to make sure that the only commits that show on the comparison page *before* making the PR are your commits.

**Comment by brettcannon** [comment]
Closing due to all the spurious review requests and the existing merge conflicts.

**Comment by taleinat** [comment]
I agree with @terryjreedy, this PR should be closed, and a new clean PR should be created.

**Pull request closed without merging**
