### PR TITLE
gh-124928: Emscripten node support: Clean up old node <= 16 flags

### PR DESCRIPTION
**Pull request by hoodmane**
These flags are only needed for node <= 16. Node 16 has been end of life since
October of 2023.

* Issue: gh-124928

### CODE REVIEW

**Review by corona10 — COMMENTED** [review]
Hmm, can we add some assertion to check that user is using Node > 16?

**Comment by hoodmane** [comment]
Yeah that makes sense I will do that.

**Comment by hoodmane** [comment]
Okay now it prints the following complaint to standard error and exits with code 1 on old node versions.
```
Node version must be >= 18, got version v16.20.2
```

**Review by corona10 — CHANGES_REQUESTED** [review]
Please also add NEWS.d that now CPython requires Node >= 18 for Emscripten build :)

**Review by willingc — APPROVED** [review]
Thanks @hoodmane for cleaning up the old node stuff. Much appreciated.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Code changes look good; as noted elsewhere, a news entry is definitely required ([the devguide](https://devguide.python.org/core-developers/committing/#how-to-add-a-news-entry) has details on how to generate one).

I'll also hold off merging until python/steering-council#256 is resolved.

**Review by corona10 — APPROVED** [review]
lgtm!

**Comment by hoodmane** [comment]
@freakboy3742 can we merge now that https://github.com/python/steering-council/issues/256 is approved?

**Review by freakboy3742 — APPROVED** [review]
LGTM!

**Pull request merged**
