### PR TITLE
gh-91962: Fix `hstrerror` detection issues on Solaris

### PR DESCRIPTION
**Pull request by kulikjak**
Configure only checks whether `inet_aton` needs `-lresolv` but it also needs to check `hstrerror` (because on Solaris, `inet_aton` no longer needs `-lresolv`, but `hstrerror` does).

Issue #91962 has more detailed explanation.

* Issue: gh-91962

### CODE REVIEW

**Review by encukou — DISMISSED** [review]
LGTM!
Let's merge after alpha 4 is cut, so if something's wrong we don't block the release process.

**Comment by erlend-aasland** [comment]
I'm not sure if this is the correct fix; please hold on merging it.

**Comment by kulikjak** [comment]
I tested it on Solaris and it seems to work as expected, but I won't pretend that I am an autotools expert and it's perfectly possible that I overlooked something.

**Comment by erlend-aasland** [comment]
> I tested it on Solaris and it seems to work as expected, but I won't pretend that I am an autotools expert and it's perfectly possible that I overlooked something.

There is an existing `hstrerror` check. If it is incorrect, should we not fix that instead of adding a new check?

**Comment by kulikjak** [comment]
I presume you mean the `PY_CHECK_NETDB_FUNC([hstrerror])` line? That one seems to check whether `hstrerror` is available, not whether it needs additional libraries to link. I guess I can shuffle the code a little and move the `-lresolv` check near the corresponding `PY_CHECK_NETDB_FUNC` but that would mean more extensive changes.

That said, there was indeed a slight issue with the detection - it wouldn't work correctly on a system where `hstrerror` needs `-lresolv` and `inet_aton` doesn't exist (although I don't think that is the case anywhere...)

**Comment by encukou** [comment]
@erlend-aasland, does this look good?

**Comment by kulikjak** [comment]
I just finished working on an updated version of the check - the old one stopped working at some point, because extensions are no longer using `LIBS` it seems. 

This one keeps `AC_CHECK_LIB` and just adds another check for `hstrerror`.

**Comment by encukou** [comment]
I plan to merge this tomorrow if there are no objections.

**Review by erlend-aasland — APPROVED** [review]
> I plan to merge this tomorrow if there are no objections.

With this PR, `HAVE_LIBRESOLV` will never be defined in `pyconfig.h` anymore. I don't think that will be a problem; just a heads-up. We don't use `HAVE_LIBRESOLV` in our code base.

**Comment by encukou** [comment]
My gut feeling is that the general idea is OK: `HAVE_LIBRESOLV` means that we have `-lresolv` in the flags, so if we drop `-lresolv` for CPython itself, `HAVE_LIBRESOLV` should go too.

Alas, if you link `socket` statically, you get `-lresolv` but not `HAVE_LIBRESOLV`. I don't think we can handle that well with current tooling?

**Comment by erlend-aasland** [comment]
> Alas, if you link `socket` statically, you get `-lresolv` but not `HAVE_LIBRESOLV`. I don't think we can handle that well with current tooling?

You can just modify the action-if-true block to explicitly define `HAVE_LIBRESOLV` (it was implicitly defined before, since the action-if-true block was empty).

**Comment by kulikjak** [comment]
I can do so, but is it really necessary considering that `HAVE_LIBRESOLV` is currently not used anywhere? It can always be easily added later once it becomes necessary.

**Comment by erlend-aasland** [comment]
> I can do so, but is it really necessary considering that `HAVE_LIBRESOLV` is currently not used anywhere? It can always be easily added later once it becomes necessary.

It is also exported in `Python.h` via `pyconfig.h`, _but_ IMHO it is not needed; I'm fine with the patch as it is (which is also why I approved it).

**Comment by kulikjak** [comment]
Thank you both very much!

**Pull request merged**
