### PR TITLE
gh-102491: Remove IronPython version check in sys_version

### PR DESCRIPTION
**Pull request by eendebakpt**
The platform module contains various version checks for systems such as cpython and ironpython. The file also contains a specfic case for ironpython  which can be removed (see https://github.com/IronLanguages/ironpython3/issues/1667)

Removing the check improves the import speed as it avoids the compilation of a two regular expressions.

```
%timeit _ironpython26_sys_version_parser = re.compile(r'([\d.]+)\s*'   r'\(IronPython\s*'    r'[\d.]+\s*'    r'\(([\d.]+)\) on ([\w.]+ [\d.]+(?: \(\d+-bit\))?)\)' )
383 ns ± 1.66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

Note: most of the compiled regular expressions in `platform.py` can be moved into the methods using them, as most results are cached. This would reduce the importtime for `platform`  even further:
```
Main: The speed of "import platform" is: 8.231517 +- 0.499458 [ms]
Regular expressions adapted: The speed of "import platform" is: 7.182120 +- 0.726896 [ms]

```

* Issue: gh-102491

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks, this looks good. Would you mind adding the news entry?

**Review by hauntsaninja — COMMENTED** [review]
Hm, not an issue with this PR, but I was curious what IronPython is doing. It looks like their platform.py has https://github.com/IronLanguages/ironpython3/blob/f41afc44534786721b89e1efb8e50c4232ee1224/Src/StdLib/Lib/platform.py#L1141 and https://github.com/IronLanguages/ironpython3/blob/f41afc44534786721b89e1efb8e50c4232ee1224/Src/StdLib/Lib/platform.py#L1187

Weirdly, IronPython's [docs](https://github.com/IronLanguages/ironpython3/blob/master/Documentation/installing.md#scripted) indicates that its sys.version would not match the regex we have or the regex they have in their platform.py.

**Comment by eendebakpt** [comment]
> Hm, not an issue with this PR, but I was curious what IronPython is doing. It looks like their platform.py has https://github.com/IronLanguages/ironpython3/blob/f41afc44534786721b89e1efb8e50c4232ee1224/Src/StdLib/Lib/platform.py#L1141 and https://github.com/IronLanguages/ironpython3/blob/f41afc44534786721b89e1efb8e50c4232ee1224/Src/StdLib/Lib/platform.py#L1187
> 
> Weirdly, IronPython's [docs](https://github.com/IronLanguages/ironpython3/blob/master/Documentation/installing.md#scripted) indicates that its sys.version would not match the regex we have or the regex they have in their platform.py.

@hauntsaninja Good point. I created an issue https://github.com/IronLanguages/ironpython3/issues/1667. Based on the decision there, can you (as core dev) make a decision on the other ironpython regular expression.

**Review by hauntsaninja — APPROVED** [review]
Thank you!

**Pull request merged**
