### PR TITLE
GH-108614: Remove `TIER_ONE` and `TIER_TWO` from `_PUSH_FRAME`

### PR DESCRIPTION
**Pull request by markshannon**
Not newsworthy

* Issue: gh-108614

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
LGTM. I like how you managed to remove the HAS_ERROR flag from three uops!

**Comment by gvanrossum** [comment]
Running the tests while forcing -Xuops shows a leak: https://github.com/python/cpython/actions/runs/6042493339/job/16397717979?pr=107820

Though this might be due to another recent PR too.

**Comment by markshannon** [comment]
Have you tested for leaks on main?
I don't see any obvious places where this would introduce a leak.

**Comment by gvanrossum** [comment]
Good call, it looks on main too with -Xuops. So go ahead and merge.

**Pull request merged**
