### PR TITLE
GH-104554: Add RTSPS support to `urllib/parse.py`

### PR DESCRIPTION
**Pull request by zentarim**
RTSPS is the permanent scheme defined in
https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
alongside RTSP and RTSPU schemes.

* Issue: gh-104554

----
:books: Documentation preview :books:: https://cpython-previews--104605.org.readthedocs.build/

### CODE REVIEW

**Comment by orsenthil** [comment]
Could you please add a news entry, and CLA sign requirement?

**Comment by terryjreedy** [comment]
@orsenthil Ignore currently 'normal' failure of experimental hypothesis tests.

**Comment by zentarim** [comment]
Hello, @orsenthil , @terryjreedy !

I've fixed the issues. Is there something else?

**Comment by arhadthedev** [comment]
@orsenthil Should it be backported or reclassified as https://github.com/python/cpython/labels/type-feature?

**Comment by orsenthil** [comment]
@zentarim- Nothing. we are good here. Thank you.

**Review by Hoseinmj — COMMENTED** [review]
Y

**Pull request merged**
