### PR TITLE
gh-106948: Docs: Disable links for C standard library functions, OS utility functions and system calls

### PR DESCRIPTION
**Pull request by erlend-aasland**
----
:books: Documentation preview :books:: https://cpython-previews--107062.org.readthedocs.build/

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
`malloc`, `realloc` and `free` are referred in many different files. Maybe add them in `nitpick_ignore`? And `calloc` for complete.

**Comment by erlend-aasland** [comment]
> `malloc`, `realloc` and `free` are referred in many different files. Maybe add them in `nitpick_ignore`? And `calloc` for complete.

Yes, I noticed. I'll add them, and I'll remove the `_weakref` since it does not belong to this PR really.

**Comment by serhiy-storchaka** [comment]
The most referred functions:
```
      3 :c:func:`!addstr`
      3 :c:func:`calloc`
      3 :c:func:`exec`
      3 :c:func:`function__entry`
      3 :c:func:`printf`
      3 :c:func:`sigaction`
      3 :c:func:`signal`
      3 :c:func:`sprintf`
      3 :c:func:`strerror`
      4 :c:func:`devpoll`
      4 :c:func:`lockf`
      4 :c:func:`main`
      4 :c:func:`snprintf`
      4 :c:func:`stat`
      4 :c:func:`system`
      4 :c:func:`vsnprintf`
      5 :c:func:`dlopen`
      5 :c:func:`fcntl`
      5 :c:func:`flock`
      5 :c:func:`!getopt`
      5 :c:func:`!scanf`
      6 :c:func:`realloc`
      8 :c:func:`select`
      9 :c:func:`poll`
     11 :c:func:`gmtime`
     11 :c:func:`localtime`
     18 :c:func:`fork`
     21 :c:func:`free`
     34 :c:func:`malloc`
```

Some of them, like `getopt` are only referred in one file.

**Comment by serhiy-storchaka** [comment]
1. I am not sure that all functions referred at least 3 times should be added in `nitpick_ignore`. Many of them are only referred in one file (excluding NEWS entries). Memory management functions `malloc`, `realloc` and `free` are obvious candidates for inclusion. `calloc` can also be included besides it is only referred 3 times. `gmtime` and `localtime` are referred several times in two related modules, they also can be included. `fork` is referred in multiple files. `poll` is only referred in select.rst, but multiple times, it is questionable. Etc, etc. On other side, `addstr` is only mentioned in curses.rst, and in all three cases already with `!`. To me, it is an obvious candidate for not inclusion. `function__entry` is a strange thing, is it even a standard name?

2. I did not differentiate between C, Posix and Windows types, Posix and Windows environment variables. It is tiresome to find where exactly the name is defined (and some are defined on multiple platforms), and it does not really matter. I only grouped by the role.

It is my thoughts. If you disagree, go ahead, but may be some of them can be useful to you.

**Comment by erlend-aasland** [comment]
Thanks for you input. I think it makes sense to remove functions which are only mentioned a few times, and instead use `!` to mark them up. I'll return to this later today.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for the review and insight, Serhiy. Highly appreciated!

**Pull request merged**
