### PR TITLE
bpo-36690: Fix typing error in demo rpython.py

### PR DESCRIPTION
**Pull request by BriFuture**
Fixed typing error in File `Tools/demo/rpython.py` at Line 22 where `port[i+1:]` should be `host[i+1:]`

https://bugs.python.org/issue36690

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Review by berkerpeksag — APPROVED** [review]
I won't wait for the CLA since this is a pretty trivial patch. However, please sign the CLA form if you're planning to continue contributing to Python.

Thank you!

**Comment by BriFuture** [comment]
@berkerpeksag Hi, I've signed CLA and confirmed my email address, but it seems my github accout cant pass the check on 
https://check-python-cla.herokuapp.com. 
What's the problem and how to do?

**Comment by berkerpeksag** [comment]
A PSF staff needs to process your signed form and it usually takes a few US business days.

**Pull request merged**
