### PR TITLE
bpo-32030: Add _PyCoreConfig.module_search_paths

### PR DESCRIPTION
**Pull request by vstinner**
_PyCoreConfig_Read() is now responsible to compute sys.path.
So sys.path is now computed before calling _Py_InitializeCore().

Changes:

* Add nmodule_search_path, module_search_paths, executable, prefix,
  base_prefix, exec_prefix and base_exec_prefix to _PyCoreConfig
* _PyMainInterpreterConfig_Read() now only converts wchar_t** lists
  into a Python list, it doesn't compute sys.path anymore.

https://bugs.python.org/issue32030

### CODE REVIEW

**Comment by vstinner** [comment]
Oh. Calling _PyPathConfig_Init() before _PyMem_SetupAllocators() doesn't work.

_PyPathConfig_Init() -> _Py_wreadlink -> Py_EncodeLocale -> PyMem_Raw -> pymalloc_alloc

pymalloc_alloc() calls PyMem_RawRealloc() to allocate the arenas array.

But if _PyMem_SetupAllocators() change the RAW allocator, pymalloc_alloc() will crash when resizing arenas...

In short, PyMem_Malloc() must be called before _PyMem_SetupAllocators().

_PyPathConfig_Init() must be modified to only use the RAW memory allocator.

**Comment by vstinner** [comment]
In other pull requests (now merged), I modified _PyPathConfig_Calculate() to not use the Python API internally, but only regular C functions. I rebased this PR on top of it.

But I'm not sure that @ncoghlan likes this change. I will wait his feedback before merging this PR.

**Comment by vstinner** [comment]
test_site fails on AppVeyor.

**Comment by ncoghlan** [comment]
While I initially thought this might conflict with some future plans I had
for refactoring how we configure the import system at startup, an off-list
discussion with Victor convinced me that was not the case.

So while I haven't reviewed the details of the PR (still on vacation!), I'm
OK with the idea in principle.

**Comment by vstinner** [comment]
I rebased my PR.

**Comment by vstinner** [comment]
@ncoghlan: Oh, this patch adds another layer of uglyness in main.c: global configuration flags should be set before calling _PyPathConfig_Init(), and then get again to get updated values... Maybe _PyPathConfig_Init() shouldn't read nor write these global variables...

**Pull request merged**
