### PR TITLE
[3.9] gh-87604: Avoid publishing list of active per-interpreter audit hooks via the gc module (GH-99373)

### PR DESCRIPTION
**Pull request by zooba**
* Issue: gh-87604

### CODE REVIEW

**Comment by zooba** [comment]
@pablogsal We agreed (on the original PR) that this is a minor, but harmless change. I'm intending to backport it into my patchset for 3.8 and 3.9 builds at work, so figured that means it's worth backporting for everyone.

**Comment by pablogsal** [comment]
I am +1 backporting this but maybe you want to check with @ambv instead for 3.9 and 3.8?

**Comment by pablogsal** [comment]
I am assuming 3.10 has the fix already no?

**Comment by ambv** [comment]
I'm +1 to backport to 3.9 and 3.8.

**Pull request merged**
