### PR TITLE
gh-108303: Move `.whl` test files to `Lib/test/whldata/`

### PR DESCRIPTION
**Pull request by sobolevn**
* Issue: gh-108303

### CODE REVIEW

**Review by AA-Turner — APPROVED** [review]

**Comment by vstinner** [comment]
`whldata` can you rename it to `wheeldata`? Technically, it's seems like these 2 files are venv dependencies. Maybe `venvdata`? I don't know.

**Comment by sobolevn** [comment]
I think that `wheeldata` sounds correct to hold `.whl` files 👍 
While `venvdata` might be confusing.

**Review by vstinner — COMMENTED** [review]
Usually, when you add a new test directory, "Installed" buildbot fails :-) It seems like you didn't add the directory to the Makefile...

**Comment by sobolevn** [comment]
Yes, I will! Thanks for the catch.

**Comment by sobolevn** [comment]
There should be no 3.11 backport, since these changes were only made for 3.12+
See https://github.com/python/cpython/pull/103316

**Comment by vstinner** [comment]
> There should be no 3.11 backport, since these changes were only made for 3.12+

Ok, fine. Thanks for checking.

**Pull request merged**
