### PR TITLE
bpo-38122: minor fixes to AsyncMock spec handling

### PR DESCRIPTION
**Pull request by voidspace**
Simplification of the spec handling for AsyncMock and correction for how spec_set is handled.

https://bugs.python.org/issue38122

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@voidspace

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by lisroach — APPROVED** [review]
Thanks for the fix!

**Comment by matrixise** [comment]
@voidspace Could you work on the backport for 3.8? Thanks

**Comment by matrixise** [comment]
@voidspace I have created a PR with the backport, but I would like to get your approval.

**Comment by cjw296** [comment]
@voidspace: curious as to why these ended up having no tests committed as part of this PR. It's unclear whether https://bugs.python.org/issue38122 is just refactoring or a change in behaviour. If it's the latter, I'd have hoped for some additional tests to verify this...

**Pull request merged**
