### PR TITLE
link to legacy doc on the non-legacy website

### PR DESCRIPTION
**Pull request by benjaminp**

### CODE REVIEW

**Comment by Mariatta** [comment]
I want to try backporting this using cherry-picker bot.

**Review by Mariatta — APPROVED** [review]

**Comment by benjaminp** [comment]
Alright, will you merge this when Travis finishes, or should I?

**Comment by Mariatta** [comment]
You can merge it. I'll be watching the log :)

**Comment by Mariatta** [comment]
Sorry. It failed 😞

**Pull request merged**
