### PR TITLE
bpo-31673: Fixed typo in the name of Tkinter's method adderrorinfo().

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue31673

### CODE REVIEW

**Comment by Mariatta** [comment]
One sec, I will retry the backport

**Comment by serhiy-storchaka** [comment]
Thanks @Mariatta!

**Comment by Mariatta** [comment]
Thanks for the patience @serhiy-storchaka , seems like this will require a manual backport after all :)

**Comment by serhiy-storchaka** [comment]
@miss-islington is not able to resolve conflicts in generated files. The right way of resolving them -- remove the generated file and regenerate it.

**Pull request merged**
