### PR TITLE
bpo-46541: Replace _Py_IDENTIFIER with _Py_ID in sqlite3

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue46541

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Assuming we skip news, since this is an internal change only.

**Comment by erlend-aasland** [comment]
> The main reason I didn't do this earlier is because our (non-builtin) extension modules probably shouldn't be relying on internal API.

It's fully possible to build any stdlib extension as a built-in, even sqlite3.

> How bad would it be to replace uses of `_Py_IDENTIFIER()` with `PyUnicode_InternFromString()`?

Most users will call `execute` and friend on a _cursor_ object, not on a _connection_ object, so most users will not notice neither performance improvements nor regressions. I'm not sure about the adapter case though; I don't know how widely used they actually are.

**Comment by ericsnowcurrently** [comment]
BTW, thanks for working on this!

**Comment by erlend-aasland** [comment]
> BTW, thanks for working on this!

Likewise :)

**Comment by erlend-aasland** [comment]
PTAL. This should result in a small speedup compared to `main`.

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by erlend-aasland** [comment]
Thanks for your review and thoughts, @corona10 & @ericsnowcurrently

**Pull request merged**
