### PR TITLE
gh-108617: Extend interactive session tests for sqlite3

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-108617

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Are you ok with landing #108551 first? Either way, one of the PRs will have to resolve conflicts.

**Comment by serhiy-storchaka** [comment]
If it is compatible with #108551. But since it only calls `communicate()` once per session, there should not be issues.

**Comment by serhiy-storchaka** [comment]
On other hand, if the CLI outputs some farewell message, there will be conflicts. Also, #108551 does not test that all output is not hold until the program ends. In case of some issues I will need to partially revert your changes and simulate a subprocess with a thread.

**Comment by erlend-aasland** [comment]
Good use of the `count()` sequence API. It is a good improvement.

**Review by erlend-aasland — APPROVED** [review]

**Pull request merged**
