### PR TITLE
gh-114552: Update `__dir__` method docs: it allows returning an iterable

### PR DESCRIPTION
**Pull request by sobolevn**
* Issue: gh-114552

----
📚 Documentation preview 📚: https://cpython-previews--114662.org.readthedocs.build/

### CODE REVIEW

**Review by AlexWaygood — COMMENTED** [review]
Could you update line 2012 as well? As I noted in https://github.com/python/cpython/issues/114552#issuecomment-1910115332, it seems also to be incorrect

**Comment by sobolevn** [comment]
It was a good year :)
Updated.

**Comment by AlexWaygood** [comment]
Do we have any tests that assert that non-sequence iterables are okay to be returned from `__dir__` methods? If not, could you add some? :)

**Review by hauntsaninja — APPROVED** [review]

**Review by AlexWaygood — APPROVED** [review]
LGTM, but I'd like for us to wait a little bit before merging, in case anybody else has objections (changing the language spec shouldn't be done lightly, in my opinion)

**Review by terryjreedy — APPROVED** [review]
I added the backport labels because I consider this a doc bugfix.  The `__dir__` doc should have always matched the `__dir__` behavior, and indeed they do as long as 'sequence' is properly interpreded.  Since the new iterator protocol added the new term 'iterable', an iterable is the obvious requirement.  The sloppiness of using 'sequence' when 'iterable' is meant is partly a holdover from the old protocol when only objects with a sequence `__getitem__` could be iterated.  We are still cleaning up this confusion in the docs. 

My perspective is likely colored from having started with 1.3, just before 1.4.

I since read Alex's comment.  To me, we are clarifying, not changing, the language spec.  I am sure we have made other /sequence/interable/ changes but I cannot remember if they were backported.

**Pull request merged**
