### PR TITLE
bpo-31709: Update importlib magic

### PR DESCRIPTION
**Pull request by 1st1**
https://bugs.python.org/issue31709

### CODE REVIEW

**Comment by 1st1** [comment]
NEWS entry was provided as part of https://github.com/python/cpython/pull/3903. This is a simple follow up to that PR.

**Comment by ncoghlan** [comment]
Ah, right, I missed that - you need this to force the removal of the no-longer-needed `await` logic.

**Review by ncoghlan — APPROVED** [review]

**Review by ncoghlan — CHANGES_REQUESTED** [review]
On second thoughts, could you also add a `.. versionchanged: 3.7` note for the opcode docs in the `dis` module?

**Comment by 1st1** [comment]
I didn't expect the Spanish Inquisition!

**Comment by 1st1** [comment]
> On second thoughts, could you also add a .. versionchanged: 3.7 note for the opcode docs in the dis module?

Good catch!

**Review by ncoghlan — APPROVED** [review]

**Comment by ncoghlan** [comment]
@1st1 This one LGTM now as well :)

**Comment by 1st1** [comment]
Thanks again, Nick!

**Pull request merged**
