### PR TITLE
gh-118179: Added implementation for nwise to itertools

### PR DESCRIPTION
**Pull request by lsproule**
* Issue: gh-118179

### CODE REVIEW

**Comment by eendebakpt** [comment]
@lsproule Thanks contributing! You can find more information about the cpython procedures in the developers guide: https://devguide.python.org/. In particular, for this PR you need to create an issue this PR can link to. And in general for additions to cpython a good place to discuss new ideas is https://discuss.python.org/c/ideas/6

**Comment by eendebakpt** [comment]
From the docstring in your PR it looks like the `nwise` is (roughly) equivelent to the `sliding_window` method from more-itertools (see https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.sliding_window)

Is that correct?

**Comment by lsproule** [comment]
@eendebakpt  sliding_window doesn't exist. In the docs, they show you how to implement it using the itertools module.  However, since they added pairwise. I thought having a C version of nwise or yes a sliding window, would make some sense.

**Comment by lsproule** [comment]
so for this clinic input should it be Py_ssize_t? Actually how am I supposed to go about generating the clinic stuff appropriately 

https://github.com/lsproule/cpython/blob/874d06821711fe99d8e765d78eca4702ced41c80/Modules/itertoolsmodule.c#L398C1-L409C2

also, can we check my allocations and de-allocations  because I want to do this well.

https://github.com/lsproule/cpython/blob/874d06821711fe99d8e765d78eca4702ced41c80/Modules/itertoolsmodule.c#L452C1-L516C2

**Comment by rhettinger** [comment]
We haven't decided to add *sliding_window()* to itertools, so it is premature to submit a PR to add it.

I've published it as a recipe and have been looking at how people use it to determine whether it was a good idea.

**Comment by lsproule** [comment]
Well, I would like to revisit that. I think more-itertools is great, but I personally would like to have this in the itertools toolbelt especially because we do have pairwise, and it would be nice to revisit. I changed it to a draft instead of a pull request while we discuss it. I want this to be a quality addition. I personally have used it for analyzing data. I think itertools is an amazing module, so not having to reach for a library like more-iterools is nice for me. I like to try to stick to the standard library as much as possible.

**Comment by rhettinger** [comment]
> I think itertools is an amazing module

Thank for the accolades.

> not having to reach for a library like more-iterools is nice for me

Personally, I do like using that package.  The norm for Python development for a few years is to have fewer tools in the standard library and to encourage use of third-party libraries.  The latter are easy to install and typically have a lively, active group of contributors.

**Comment by lsproule** [comment]
I love more-itertools as well. I kind of implemented nwise in C then. I was like wait a second, so I implemented for CPython in the itertools C. I personally think a sliding_window/nwise implementation in C that is fully fleshed out and optimized would be really cool. I personally would like some help optimizing it and benchmarking it. I personally think it makes sense since it's just a generic pairwise.

**Comment by lsproule** [comment]
I personally don't think my implementation was fully fleshed out. I 100% know there was room for improvement, and I would 100% be willing to take advice from the community on optimization/benchmarking. However, I couldn't imagine how we couldn't have improvements over the pure python implementation that's in more-itertools.

**Pull request closed without merging**
