### PR TITLE
bpo-36035: fix rglob for broken links

### PR DESCRIPTION
**Pull request by jstucke**
https://bugs.python.org/issue36035

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by eamanu — COMMENTED** [review]
https://github.com/python/cpython/pull/11964 duplicated

**Review by pitrou — APPROVED** [review]
Nice! Thank you for doing this!

**Comment by pitrou** [comment]
Ok, I won't bother about 3.6 personally (is it still open for regular bug fixes?).

**Pull request merged**
