### PR TITLE
gh-89240: Limit multiprocessing.Pool to 61 workers on Windows

### PR DESCRIPTION
**Pull request by aisk**
* Issue: gh-89240

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Looks reasonable to me, compare to https://github.com/python/cpython/pull/13132/files. Although that PR complains 63 is the max and the overhead is 2 objects.

**Comment by aisk** [comment]
It looks like #107873 can totally resolve the original issue if it has been merged, rather than pointing out the limitations in document and error messages like this PR.
So I think it's better to wait until #107873 is merged and close the current PR, or if it's not, then we can restart the review process.

**Comment by zooba** [comment]
My PR is waiting on reviews and/or testing. If a couple of people want to confirm that it works, then we can merge it.

Otherwise, this PR looks fine to me.

**Comment by aisk** [comment]
Since #107873 has been merged, this issue can be closed now. Still, thank you to everyone who reviewed this!

**Pull request closed without merging**
