### PR TITLE
Add developer guide link to README.rst

### PR DESCRIPTION
**Pull request by ncoghlan**

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Review by Mariatta — APPROVED** [review]
LGtM. Thanks, @ncoghlan  :)

**Comment by Mariatta** [comment]
Does this need backported?

**Comment by zware** [comment]
The devguide is also linked in the Documentation section below; should it be removed from there since it's added at the top?

**Review by vstinner — CHANGES_REQUESTED** [review]
I suggest to remove the now redundant link to the devguide in the Documentation section.

**Comment by ncoghlan** [comment]
The online conflict resolution failed miserably, so I'll just close this and make a new PR

**Comment by ncoghlan** [comment]
Replacement PR: https://github.com/python/cpython/pull/145

**Pull request closed without merging**
