### PR TITLE
bpo-36635: Add _testinternalcapi module

### PR DESCRIPTION
**Pull request by vstinner**
Add a new _testinternalcapi module to test the internal C API.

Move _Py_GetConfigsAsDict() function to the internal C API:
_testembed now uses _testinternalcapi to access the function.

https://bugs.python.org/issue36635

### CODE REVIEW

**Comment by vstinner** [comment]
I chose to name the C file _testinternalcapi.c rather _testinternalcapimodule.c, just because "_testinternalcapimodule.c" is too long :-)

**Comment by vstinner** [comment]
I'm not sure about the module name. Maybe "_testinternal" is better? (shorter, contains enough info?)

**Comment by vstinner** [comment]
I copied the _testcapi project of PCbuild/ and I tried to adapt it, but it seems like I made a mistake. Importing _testinternalcapi fails with:

```
ImportError: dynamic module does not define module export function (PyInit__testinternalcapi)
```

**Comment by vstinner** [comment]
> I copied the _testcapi project of PCbuild/ and I tried to adapt it, but it seems like I made a mistake. Importing _testinternalcapi fails with: ...

@zooba @zware: I did something wrong for the Windows project. Any idea? Should I use the GUI to create the project instead?

**Comment by serhiy-storchaka** [comment]
Perhaps you need to generate new unique identifiers.

**Comment by vstinner** [comment]
> Perhaps you need to generate new unique identifiers.

Now done in the 2 project files.

**Comment by zooba** [comment]
The GUIDs shouldn't matter outside of Visual Studio, and the only one that has to change is the ProjectGuid (which was updated initially, I believe). The ones in the filters file are referring to known values for the category, so they were fine.

(There is an update missing from `Tools/msi/test/test_files.wxs`, but that won't be the cause of this issue.)

Based on not seeing the following line in the build logs, I think it's decided not to produce a DLL for some reason:

```
Creating library C:\projects\cpython\PCbuild\amd64\_testinternalcapi.lib and object C:\projects\cpython\PCbuild\amd64\_testinternalcapi.exp
```

Possibly the `Py_BUILD_CORE_BUILTIN` directive is causing one of the `dllexport` macros to change? I'd have to dig into the headers more closely to figure it out, so perhaps you'll get it first.

**Comment by vstinner** [comment]
Hum. The problem should be that PyMODINIT_FUNC is defined differently if Py_BUILD_CORE_BUILTIN is defined:

```
#define PyMODINIT_FUNC PyObject*
```

instead of:

```
#define PyMODINIT_FUNC __declspec(dllexport) PyObject*
```

The following change works around the issue on Windows:

```
diff --git a/Modules/_testinternalcapi.c b/Modules/_testinternalcapi.c
index c326d5c97d..13acf377fa 100644
--- a/Modules/_testinternalcapi.c
+++ b/Modules/_testinternalcapi.c
@@ -35,7 +35,7 @@ static struct PyModuleDef _testcapimodule = {
 };


-PyMODINIT_FUNC
+__declspec(dllexport) PyMODINIT_FUNC
 PyInit__testinternalcapi(void)
 {
     PyObject *m;
```

**Comment by zooba** [comment]
Yeah, that sounds like it. The "BUILTIN" part of the macro implies that it's going to be merged into the CPython shared library and loading using inittab rather than dynamically.

Perhaps there's another macro you could use for this module? Or else just hack around it as you showed.

**Comment by vstinner** [comment]
> Yeah, that sounds like it. The "BUILTIN" part of the macro  implies that it's going to be merged into the CPython shared library and  loading using inittab rather than dynamically. Perhaps there's another macro you could use for this module? Or else just hack around it as you showed.

There is already a Py_BUILD_CORE_MODULE define which is defined in the Visual Studio project when a C extension is built as a .pyd file (DLL):

```
PCbuild/pyproject.props:26:    <_PydPreprocessorDefinition Condition="$(TargetExt) == '.pyd'">Py_BUILD_CORE_MODULE;</_PydPreprocessorDefinition>
```

This define is only used at once place:

```
PC/pyconfig.h:146:#if defined(Py_BUILD_CORE) || defined(Py_BUILD_CORE_BUILTIN) || defined(Py_BUILD_CORE_MODULE)
```

I wrote PR #12853 to change PyAPI_FUNC(type), PyAPI_DATA(type) and PyMODINIT_FUNC macros
of pyport.h when Py_BUILD_CORE_MODULE is defined. I should fix this issue.

**Comment by vstinner** [comment]
The PR #12853 fix this change: I tested manually, it works.

**Review by zooba — APPROVED** [review]
If the fix for dllexport works here (and it sounds like it will), I'm happy with this change.

**Comment by vstinner** [comment]
> The PR #12853 fix this change: I tested manually, it works.

I merged PR #12853. I rebased this PR on top of it, I squashed commits and I made minor changes (I fixed Modules/Setup).

Modules/_testinternalcapi.c now requires that a define is set explicitly:

```
#if !defined(Py_BUILD_CORE_BUILTIN) && !defined(Py_BUILD_CORE_MODULE)
#  error "Py_BUILD_CORE_BUILTIN or Py_BUILD_CORE_MODULE must be defined"
#endif
```

**Comment by vstinner** [comment]
Thanks for the review @zooba, and thanks @serhiy-storchaka and @zware for hints to debug the compilation issue on Windows :-)

**Pull request merged**
