### PR TITLE
[3.11, 3.12] docs: typing.Self, fix typo

### PR DESCRIPTION
**Pull request by maxzhenzhera**
- fix double spelled word 'use'

> You should **use use** [Self](https://docs.python.org/3.11/library/typing.html?highlight=typing#typing.Self) as calls to ...

- change methods names in the code blocks to the infinitive form

> return**s**_self > return_self

Simple typo fixes, no issue was created.

### CODE REVIEW

**Comment by maxzhenzhera** [comment]
@Fidget-Spinner Am I correct this time?) Sorry, it's just my first contribution.

**Comment by kumaraditya303** [comment]
Please create a PR from the latest main branch.

**Comment by kumaraditya303** [comment]
Checkout the latest main branch, make your changes, commit it and then create a PR.

**Comment by arhadthedev** [comment]
> Firstly, I made a PR from 3.11 to 3.11

@maxzhenzhera Is your fix for all Python versions supported or just for 3.11? @kumaraditya303 suggests the former so proposes to create a PR from **main** to **main**; backporting to older versions will be done automatically by bots.

If your fix cannot be applied to the currently developed 3.12, please specify this explicitly because everybody seems confused.

**Comment by maxzhenzhera** [comment]
@arhadthedev thank you for your explanation.
It's just my first contribution and I easily got confused)

**Comment by terryjreedy** [comment]
With rare exceptions, all contributed PRs should be created from a *branch* of current main pushed to your fork from your local repository.  If one directly patches local main and hence fork main, one's local repository gets ahead of cpython main and this becomes a nuisance.  After deleting the branch on the fork, one should usually delete the local branch.  The devguide says a lot more.

**Pull request closed without merging**
