### PR TITLE
Update CI files to account for the master -> main rename

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Review by gpshead — APPROVED** [review]

**Review by isidentical — APPROVED** [review]

**Comment by ammaraskar** [comment]
`.azure-pipelines` needs an update too or is @zooba taking care of that?

**Comment by isidentical** [comment]
Do we need to update `Doc/tools/templates/customsourcelink.html:7` for the docs as well?

**Comment by vstinner** [comment]
You forgot:

```
.azure-pipelines/ci.yml:4:trigger: ['master', '3.9', '3.8', '3.7']
.azure-pipelines/pr.yml:4:pr: ['master', '3.9', '3.8', '3.7']

.github/CONTRIBUTING.rst:7:- master
.github/PULL_REQUEST_TEMPLATE.md:19:If this is a backport PR (PR made against branches other than `master`),
.github/PULL_REQUEST_TEMPLATE.md:28:GH-NNNN refers to the PR number from `master`.

.travis.yml:24:    - master
```

**Comment by vstinner** [comment]
> Do we need to update Doc/tools/templates/customsourcelink.html:7 for the docs as well?

I suggest to restrict this PR to CI files, to be able to merge it quickly. But yeah, it sounds like this file should be updated as well.

**Review by ammaraskar — APPROVED** [review]

**Review by gpshead — APPROVED** [review]

**Review by vstinner — APPROVED** [review]
🤖 Victor happy  🤖

**Comment by vstinner** [comment]
Windows (x64) Failing:

```

**Comment by vstinner** [comment]
Windows (x64) Failing:

```
LINK : fatal error LNK1104: cannot open file 'python310.lib' [D:\a\cpython\cpython\PCbuild\_ctypes_test.vcxproj]
```

**Comment by vstinner** [comment]
" bedevere/maintenance-branch-pr — Not a valid maintenance branch PR title. "

Oh oh, maybe this bot is going to hold the PR... I created https://github.com/python/bedevere/issues/337

**Pull request merged**
