### PR TITLE
gh-57531 add BufferedReader.read() return value check for non-blocking stream mode

### PR DESCRIPTION
**Pull request by z764969689**
gh-57531 add `BufferedReader.read()` return value check for non-blocking stream mode, simply opt the `TextIOWrapper` error raising.

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Please resolve conflicts and add tests. Also capitalize the first letter of a sentence in a NEWS entry.

**Comment by z764969689** [comment]
@serhiy-storchaka Conflicts solved & NEWS entry edited. I'm wondering if I need to open another PR for the tests or just edit them in this one.

**Comment by serhiy-storchaka** [comment]
It is better to add new tests in the same PR. It makes easier to check that they fail without this change and pass with it.

**Comment by z764969689** [comment]
I've added a simple test case and I found that the test case would fail the C implementation. Since I'm unfamiliar with the C code, might need some help from others to modify the C code.
BTW, not pretty clear on the implementation differences, is it okay that the error-raising logic varies between them?

**Comment by serhiy-storchaka** [comment]
It is more complex issue than covered in this PR. If change the behavior of text file read() for non-blocking buffered readers, the same change should be done for non-blocking raw files. If change the behavior for "read-until-end", the same change should be done for partial read.

And of course the behavior of both C and Python implementation should be consistent.

Thank you for reviving this issue, I will look what can I do with this.

**Pull request closed without merging**
