### PR TITLE
Fix typos in Objects/odictobject.c documentation

### PR DESCRIPTION
**Pull request by robertzk**
This fixes two tpyos in comments in the file implementing OrderedDict.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by robertzk** [comment]
See CLA:

[Contributor Agreement - signed.pdf](https://github.com/python/cpython/files/2153168/Contributor.Agreement.-.signed.pdf)

**Review by taleinat — APPROVED** [review]

**Comment by taleinat** [comment]
@robertzk, we're only waiting for approval of your signed contributor agreement.

**Comment by robertzk** [comment]
@taleinat thank you! I just received this email:

> Hi Robert,

All of the CLA bits are taken care of now. A committer needed to remove the `CLA not signed` label so that the verification bot could add the `CLA signed` label. So you're all set now except for final review of the changes.

Cheers,

Betsy

**Pull request merged**
