### PR TITLE
bpo-36077: Update handling of defaulted fields

### PR DESCRIPTION
**Pull request by EpicWink**
When a non-defaulted dataclass field follows a defaulted field, the behaviour has changed from raising a `TypeError` to making all arguments in `__init__` following the defaulted field keyword-only.

I'm not sold on the prettiness of the `versionchanged` area in the docs change: please comment.

https://bugs.python.org/issue36077

### CODE REVIEW

**Comment by jdlourenco** [comment]
Looking forward for this!

**Comment by EpicWink** [comment]
This is waiting on [PEP 557](https://www.python.org/dev/peps/pep-0557/#id7) to be changed to allow this in the first place. I've submitted [a feature-request in Discourse](https://discuss.python.org/t/make-succeeding-non-default-init-parameters-keyword-only-in-dataclasses-instead-of-raising/2952) but there's been no discussion.

**Comment by ericvsmith** [comment]
We don't typically update PEPs when new features are added.

**Comment by EpicWink** [comment]
Other way around: this pull-request is in direct contradiction with the PEP (it says that non-defaulted fields following defaulted fields cause a TypeError)

**Comment by ericvsmith** [comment]
It doesn't matter: PEPs are not meant to describe current behavior.

**Comment by EpicWink** [comment]
For those wanting a patch: https://gist.github.com/EpicWink/195f43286e47c26eef7d5eb3263fee75

**Comment by NeilGirdhar** [comment]
This is so useful!  Thanks for the patch.

**Comment by randallpittman** [comment]
Thank you for the patch. Any way to know if this will get into 3.10?

**Comment by EpicWink** [comment]
There hasn't been much discussion in the [mailing list entry I posted](https://mail.python.org/archives/list/python-ideas@python.org/message/2V2SCUFMK7PK3DVA7D77AVXWIXNTSQDK/) or the [Discourse post](https://discuss.python.org/t/make-succeeding-non-default-init-parameters-keyword-only-in-dataclasses-instead-of-raising/2952), so it seems the core devs aren't interested.

[This suggestion from 2018](https://mail.python.org/archives/list/python-ideas@python.org/message/YOK5DRIPJJ4TXIVI2F7VYJZ3LBE35DCG/) suggests allowing it in a backwards-compatible way by introducing a `keyword_only` parameter, which enables the behaviour in this PR.

There is [an existing solution in the mailing list](https://mail.python.org/archives/list/python-ideas@python.org/message/YWNSGIEVFY623U6O5YYSVV6UI37VNNXB/): pass `init=False` to the `dataclass` decorator. I don't like this as then you need to write a custom `__init__` and `__repr__` for subclasses.

**Comment by ericvsmith** [comment]
I've posted a different proposal in python-ideas at https://mail.python.org/archives/list/python-ideas@python.org/message/FI6KS4O67XDEIDYOFWCXMDLDOSCNSEYG/

I'd be interested in any opinions on it. Please comment on python-ideas for a wider audience.

Thanks!

**Comment by EpicWink** [comment]
This has been superseded by the more explicit solution to be included in Python 3.10 #24909

**Pull request closed without merging**
