### PR TITLE
gh-126992: Change pickle code to base 10 for load_long and load_int

### PR DESCRIPTION
**Pull request by Legoclones**
To be in line with the documentation and sync behavior across all 3 pickle implementations, `load_int()` and `load_long()` are changed to have the base explicitly set to 10 (like in `pickletools.py`). 

* Issue: gh-126992

### CODE REVIEW

**Review by skirpichev — APPROVED** [review]
LGTM

But see the issue thread.  The discrepancy could be easily solved without backward-incompatible changes.

**Review by vstinner — COMMENTED** [review]
Please add a NEWS entry: see https://devguide.python.org/ HOWTO (use blurb-it or blurb).

**Comment by Legoclones** [comment]
Just added a NEWS entry - I hope I did it right

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
@serhiy-storchaka: Would you mind to double check this change?

**Comment by serhiy-storchaka** [comment]
I am not sure that this is an issue. Non-decimal integers was accepted always. It was not documented, but user code may depend on it. We may even make it an official feature in future.

**Comment by skirpichev** [comment]
> I am not sure that this is an issue.

There is still an inconsistency wrt pickle and pickletools.

> It was not documented, but user code may depend on it.

What do you think on changing pickletools instead, as it was suggested in the issue thread?

**Comment by serhiy-storchaka** [comment]
If consider pickletools as a debugging tool, making it more lenient is safer.

**Comment by Legoclones** [comment]
Yeah the problem right now is that pickletools is LESS lenient because it ONLY accepts base 10, so if we want to keep the any-base feature in pickle, we should change `pickletools` to accept more bases than 10. I can make another pull request

**Comment by Legoclones** [comment]
@serhiy-storchaka Would you like me to change my pull request to update pickletools.py to accept any base?

**Comment by serhiy-storchaka** [comment]
Take your time. In the end, the solution proposed in this PR may be the right solution.

**Review by serhiy-storchaka — COMMENTED** [review]
After research and discussion I am inclined to accept this change. But please add tests. Test that prefixes `0x`, `0o` and `0b` are rejected, but leading `0`s are accepted and interpreted as decimals. Add also pickletools tests.

**Comment by serhiy-storchaka** [comment]
There are already many similar tests. They try to unpickle the manually prepared data.

I added tests. They fail without changes in this PR.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
@Legoclones, it seems you are new with Git and made a common error (don't be ashamed, it happened with me too) -- you added changes to your `main` branch and created a PR from it. It makes impossible to you to create new PRs -- they will include changes from this PR. The right way -- create a separate branch for every PR (see the [devguide](https://devguide.python.org/getting-started/git-boot-camp/) for details).

Now your fork is broken. To fix it, delete the `main` branch in your fork on GitHub and your local copy and checkout the main branch from the upstream. Read the devguide about configuring an upstream remote repository. Do this only after this PR have been merged.

**Comment by vstinner** [comment]
@serhiy-storchaka:
> I added tests. They fail without changes in this PR.

Oh nice, I like your tests :-) I expected something way more complicated.

**Comment by Legoclones** [comment]
@serhiy-storchaka I've had a busy week at school, so I haven't had time to write the tests yet. Thanks for doing that and getting it done. Also yeah, I realized I had committed my changes to main and not a separate branch, I'll have to recreate it. 

The tests look good, thanks for working with me on it!

**Pull request merged**
