### PR TITLE
bpo-40077: Convert _operator to use PyType_FromSpec

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue40077

### CODE REVIEW

**Comment by corona10** [comment]
@shihai1991 Can you please take a look also?

**Review by shihai1991 — APPROVED** [review]
Thanks, LGTM.

**Review by vstinner — APPROVED** [review]
LGTM, well done :-) It's easy to forget small things in such refactoring.

**Comment by vstinner** [comment]
Thanks @corona10.

**Pull request merged**
