### PR TITLE
bpo-45898: Remove duplicate symbols from _ctypes/cfield.c (GH-29791)

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <christian@python.org>

https://bugs.python.org/issue45898

### CODE REVIEW

**Comment by brettcannon** [comment]
Looks like Windows still wants those symbols exported.

https://github.com/python/cpython/runs/4332435157?check_suite_focus=true#step:4:724

**Comment by arhadthedev** [comment]
@brettcannon Is there libffi-8.dll in `$(ExternalsDir)libffi-3.4.2` runner directory when a GitHub action fails (as declared in `libffi.props`)? I cannot say "the library is present because other imports are resolved" since `ffi_type_*` look like the only ffi exports. At least there is no other declaration with `FFI_EXTERN` in [headers before generation](https://github.com/libffi/libffi/tree/cd44289/include).

**Comment by brettcannon** [comment]
> @brettcannon Is there libffi-8.dll in `$(ExternalsDir)libffi-3.4.2` runner directory when a GitHub action fails (as declared in `libffi.props`)?

No idea.

**Comment by tiran** [comment]
Steve explained the issue on BPO. Windows cannot statically reference values from a DLL.

**Comment by tiran** [comment]
ARM64 buildbot is failing with ``LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt``, https://buildbot.python.org/all/#/builders/739/builds/265

**Pull request merged**
