### PR TITLE
 gh-111178: Avoid calling functions from incompatible pointer types in `longobject.c`

### PR DESCRIPTION
**Pull request by picnixz**
* Issue: python/cpython#111178

### CODE REVIEW

**Comment by picnixz** [comment]
I'll need a core dev to check whether this would fix the AMD64 Arch Linux Usan PR build bot. I think it should at least fix this compilation error but I'm not sure if there won't be more compilations errors.

**Comment by encukou** [comment]
!buildbot Usan

**Comment by encukou** [comment]
Thank you for the fix! It looks good to merge if the buildbot passes.

No NEWS required; I agree with your triage.

**Comment by picnixz** [comment]
So, the fix fixed it but since the compiler early exits, there are more errors appearing:

```text
Objects/object.c:2892:5: runtime error: call to function MemoryError_dealloc through pointer to incorrect function type 'void (*)(struct _object *)'
/buildbot/buildarea/pull_request.pablogsal-arch-x86_64.clang-ubsan/build/Objects/exceptions.c:3391: note: MemoryError_dealloc defined here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Objects/object.c:2892:5 in 
```

Should I try to fix the build bot in one go, or do we just merge this one, then fix compilation errors one by one? (this would affect the title of the PR as well btw and I don't think I'm able to run a build bot myself to check)

**Comment by encukou** [comment]
> Should I try to fix the build bot in one go, or do we just merge this one, then fix compilation errors one by one? 

Let's go for something between that. After a PR is merged, or in a few days, open a new one with however many fixes you have.

Even if it's just one.
I'll merge this PR; it's an improvement.

> I don't think I'm able to run a build bot myself to check

Are you able to run USAN on your machine? There are [instructions in the devguide](https://devguide.python.org/development-tools/clang/) (for *nix, though the installation looks very outdated, it should be easier now); also the buildbot logs have the commands to run (but not to install clang).
For this particular issue you can use `-fsanitize=function` rather than the full `-fsanitize=undefined`.

**Pull request merged**
