### PR TITLE
bpo-36763: Use PyConfig_Clear()

### PR DESCRIPTION
**Pull request by vstinner**
Stop using "static PyConfig", PyConfig must now always use
dynamically allocated strings: use PyConfig_SetString(),
PyConfig_SetArgv() and PyConfig_Clear().

https://bugs.python.org/issue36763

### CODE REVIEW

**Comment by vstinner** [comment]
This PR depends on PR #14444 to add PyConfig_SetWideStringList().

**Comment by brettcannon** [comment]
The title says this is about `PyConfig_Clear()` but most of the changes in the PR revolve around `PyConfig_SetWideStringList()`. Is the title accurate?

**Comment by vstinner** [comment]
> The title says this is about PyConfig_Clear() but most of the changes in the PR revolve around PyConfig_SetWideStringList(). Is the title accurate?

To be able to use PyConfig_Clear(), as "required" by the PEP 587, you have to use dynamically allocated memory, and so the code has to be modified to use PyConfig_SetWideStringList() instead of static strings.

This change depends on PR #14444: we need a PyConfig_SetWideStringList() function, otherwise, it's harder to use set warnoptions and xoptions fields of PyConfig.

**Comment by vstinner** [comment]
This change should be backported to 3.8 once PR #14523 is merged.

**Pull request merged**
