### PR TITLE
gh-93279: Small improvement in large integer addition/subtraction

### PR DESCRIPTION
**Pull request by ghost**
Issue #93279.

An alternative to using function-like macros would be to use `goto`s with 2 labels that we can jump to.

Given that these changes are not visible to users, I think the skip news label is warranted?

### CODE REVIEW

**Comment by mdickinson** [comment]
Thanks for the PR. The goal here is presumably performance improvement. Please could you show profiling results?

**Comment by oda-gitso** [comment]
@mdickinson As stated in the issue, removing those two swap operations likely won't make a significant difference. However, after expansion of the macros, it is clear that either the same statements are executed as before or fewer.

As a sanity check, here are a few benchmarks using `repeat` from the `timeit` module. The statements are chosen such that every single path possible in `x_add` and `x_sub` are taken. This was done on Ubuntu 20.04.4 LTS (x86-64). 

In all cases, the minimum and mean of the timings are lower after the change.

```
Table 1: ./configure && make -j3
----------------------------------------------------------------------------------------

Parameters
==========
number = 1_000_000
repeat = 30
timer  = time.perf_counter_ns
units  = nanoseconds

Statements                      Before                          After 
=========================== ||  ============================||==========================
                            ||  min      mean     stdev     ||  min      mean     stddev
=========================== ||  ========================================================
(1 << 30) + 5               ||  5019780, 5201643, 122149    ||  4638075, 4830536, 146937
5 + (1 << 30)               ||  5277725, 5424422, 69798     ||  4867679, 5006738, 79334
(1 << 30) - 5               ||  5374897, 5527616, 65028     ||  4987948, 5107252, 64247
5 - (1 << 30)               ||  5397568, 5529733, 86341     ||  5013793, 5125125, 59836
(1 << 30) - ((1 << 30) + 5) ||  5399164, 5554048, 93981     ||  4977032, 5135688, 78707
((1 << 30) + 5) - (1 << 30) ||  5555539, 5686508, 94400     ||  5012947, 5120253, 71766
(1 << 30) - (1 << 30)       ||  5384972, 5548893, 80268     ||  5013126, 5103014, 68235
========================================================================================

Table 2: ./configure --enable-optimizations --with-lto && make -j3
----------------------------------------------------------------------------------------

Parameters
==========
number = 1_000_000
repeat = 30
timer  = time.perf_counter_ns
units  = nanoseconds

Statements                      Before                          After 
=========================== ||  ============================||==========================
                            ||  min      mean     stdev     ||  min      mean     stddev
=========================== ||  ========================================================
(1 << 30) + 5               ||  4740106, 4990630, 135952    ||  4622757, 4920805, 145109
5 + (1 << 30)               ||  5014933, 5294768, 608651    ||  5013003, 5121956, 75617
(1 << 30) - 5               ||  5129470, 5204597, 74539     ||  5106871, 5200499, 56701
5 - (1 << 30)               ||  5133240, 5253893, 60297     ||  5079341, 5190666, 61793
(1 << 30) - ((1 << 30) + 5) ||  5160753, 5290531, 60350     ||  5129571, 5180099, 55235
((1 << 30) + 5) - (1 << 30) ||  5145835, 5290267, 60745     ||  5129745, 5218765, 91353
(1 << 30) - (1 << 30)       ||  5130790, 5280351, 58741     ||  5129465, 5190674, 58065
========================================================================================

```

**Comment by mdickinson** [comment]
> As stated in the issue, removing those two swap operations likely won't make a significant difference. However, after expansion of the macros, it is clear that either the same statements are executed as before or fewer.

Okay, thanks. Thank you for the thought, but I don't think this is sufficient motivation to make this change. There's a net loss in readability and maintainability as a result of the introduction of these macros, and I think we'd want to see a substantial benefit to offset that cost.

**Comment by oda-gitso** [comment]
@mdickinson 

Would you be open to reviewing a version without macros? Rather than using the macros, we could use two goto labels with a comment by the labels stating that both set of statements are identical, except that the roles of `a` and `b` are reversed. IMHO, while this makes the code a little longer, it does not make it any less readable, especially after one realizes (e.g. via the comment) that both set of statements are really the same.

I feel strongly about removing the two swapping operations:
1.  `5 + (1 << 30)` versus `(1 << 30) + 5` should not internally differ by 6 statements;
2. these 6 statements should never be executed because they do not have to be.

Integer addition/subtraction is such a fundamental/common operation. I think a little microoptimizing is warranted.

**Comment by mdickinson** [comment]
@oda-gitso Thank you for your comments. I understand your concerns, but there are lots of trade-offs here. Stability, reliability and maintainability are also important, and any change, however small, carries associated risks and costs. In general, there needs to be a strong reason _to_ make any given change, especially to something this fundamental. I'm afraid I'm not seeing that strong reason here.

**Comment by oda-gitso** [comment]
@mdickinson 

I respectfully disagree that stability, reliability and maintainability will be sacrificed here. Anyone thinking about touching this code will double-check everything (plus reviewers) and the core `x_add`, `x_sub` algorithms are not that difficult. The `goto` version would have the same code as it is now in `main`, but with the core algorithms duplicated (with roles of `a` and `b` reversed). There would only be two labels that we "go to". Yes, this means more code. However, one comment stating that the two set of statements are identical except that the roles of the variables `a` and `b` are reversed would cancel that out, IMO. To me, it would not make it any less readable. Compared to the current state (in terms of stability, reliability, maintainability, and so on), the differences are minuscule. 

Anyways, it appears you are not willing to review the `goto` version, given your decision to close this. 

As an advance, I may choose to open a discussion regarding this to get some input from others. 

Thanks anyways for your consideration!

**Pull request closed without merging**
