### PR TITLE
DOC: mathmodule.c: fix typo in math.log docstring

### PR DESCRIPTION
**Pull request by westurner**
```rst
Fix a typo in docstring in :py:func:`math.log` ``mathmodule.c`` 
```

### CODE REVIEW

**Review by mblahay — APPROVED** [review]
Good catch.

**Comment by mblahay** [comment]
@ambv This is just a modification to fix a missing "is" in the documentation. Is this a candidate for skipping the issue number and news?

**Review by hauntsaninja — APPROVED** [review]
Thank you!

**Comment by westurner** [comment]
Thanks!

**Pull request merged**
