### PR TITLE
gh-94512: Fix forced arg format in AC-processed overlapped

### PR DESCRIPTION
**Pull request by arhadthedev**
Please note that this PR redefines a local hierarchy of converters by inserting a universal pointer converter as a common root.

* Issue: gh-94512

### CODE REVIEW

**Comment by arhadthedev** [comment]
`HANDLE_converter` must choose between `int` on POSIX and `void *` on Windows; draft this PR until I'll sort out how to properly implement it.

**Comment by arhadthedev** [comment]
False alarm, an underlying pointer processing already does this.

**Comment by gvanrossum** [comment]
Did this cause some GitHub warnings? E.g. at the end of https://github.com/python/cpython/pull/95253/files there are some warnings like
```
 Modules/clinic/overlapped.c.h#L40
'=': 'ULONG_PTR' differs in levels of indirection from 'void *' [D:\a\cpython\cpython\PCbuild\_overlapped.vcxproj]
```

**Comment by arhadthedev** [comment]
@gvanrossum A two-step fix is ready:

- gh-95446 (deciding first whether `PyLong_*Uintptr_t` should be a macro/inline function or exported from python3.dll/.so)
- gh-95518

**Comment by zooba** [comment]
Can we quick fix it by making AC generate casts for `uintptr_t`?

**Comment by arhadthedev** [comment]
@zooba I agree with a quick fix here and now. Here it is:

- https://github.com/python/cpython/pull/95538

**Pull request merged**
