### PR TITLE
bpo-31106: Fix handling of erros in posix_fallocate() (#3000)

### PR DESCRIPTION
**Pull request by socketpair**
https://bugs.python.org/issue31106

### CODE REVIEW

**Comment by socketpair** [comment]
@nirs I confused. Should I fix anything in code ? Seems everything is right according to our conversation.

**Comment by socketpair** [comment]
@Mariatta @larryhastings 
Please review

**Comment by socketpair** [comment]
ping

**Review by larryhastings — CHANGES_REQUESTED** [review]
Thanks for the patch!  I'd like just a few small changes.

I understand why you just assign to errno the way you did, but I think we can do a little better.  Instead, please change the "errno == EINTR" to "result == EINTR" in both functions, and only assign to errno immediately before calling posix_error().  (It's reasonable to assign to errno there because of how posix_error() works.)

Note that we can safely assign to errno outside ALLOW_THREADS, because errno is per-thread (using amazing magic).

I wish I knew why these functions don't assign to errno...!

**Review by larryhastings — APPROVED** [review]

**Comment by larryhastings** [comment]
That's a big improvement.  Thanks for the patch, and the cleanup!

**Pull request merged**
