### PR TITLE
gh-126782: Support qualified referencing for `ntpath.abspath()`

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-126782

### CODE REVIEW

**Comment by nineteendo** [comment]
cc @zooba

**Comment by nineteendo** [comment]
Yeah, I'm getting a segmentation fault when running `make regen-all`. I hope it works now.

**Comment by erlend-aasland** [comment]
Please do not force-push PRs, because if the Git rebasing is done incorrectly (as here), it will frustratingly create review chaos. Instead, do `git merge --no-ff main` (from within your PR branch). **Please see the devguide for how to follow our development workflow.**

**Comment by nineteendo** [comment]
I never rebase, when I force push it's to redo a merge commit which failed here.

**Comment by nineteendo** [comment]
I'll fix the drive relative paths in a separate PR.

**Comment by ZeroIntensity** [comment]
Two notes:

- Please don't change the target issue after the PR has been opened, it makes it harder to track discussion.
- I'd really prefer that this PR get closed and reopened as a fresh PR under the new issue. Incorrectly rebasing triggers a review from all the codeowners, and they don't get unsubscribed even after their review request is removed.

**Comment by nineteendo** [comment]
It wasn't a rebase, I made a merge commit locally, but I realised I forgot to add the generated code. So I reset my head and committed without restarting the merge, causing the reviews to be requested. I force pushed afterwards to revert this commit in the hope it would remove the reviews (it didn't) with the intention of trying again.

**Pull request closed without merging**
