### PR TITLE
GH-126789: fix some sysconfig data on late site initializations

### PR DESCRIPTION
**Pull request by FFY00**
* Issue: gh-126789

### CODE REVIEW

**Comment by FFY00** [comment]
@hugovk could you maybe have a look at this PR when you have time, as I am currently the only active maintainer?

**Comment by FFY00** [comment]
There's an address sanitizer failure, but seems unrelated. Might be worth investigating still.

https://github.com/python/cpython/actions/runs/11827914917/job/32957010967?pr=126812

**Comment by freakboy3742** [comment]
@FFY00 This PR (and the 3.13 backport) appears to have broken the iOS and Android buildbots. venv tests are also impractical on those platforms due to the lack of subprocesses. I'm working on a fix now.

**Comment by FFY00** [comment]
@freakboy3742 sorry about that! I probably should have triggered the buildbot tests before merging.

I hadn't run into issues caused by the unavailability of subprocesses, so I forgot about that. This was an oversight on my part :face_with_diagonal_mouth:

**Comment by freakboy3742** [comment]
@FFY00 I'm not sure it's worth a major rewrite. Virtual environments aren't really useful in the iOS/Android/Emscripten context, because those platforms are already sandboxed and isolated by the app/webpage bundle that they're delivered in. Its similar to the question of whether you need venv inside a Docker container - except that in this case, there's no ability to call subprocess, which makes using a venv near impractical, rather than just an arguable design choice.

**Comment by terryjreedy** [comment]
Backport PRs #126918 and #126919 are merged.

**Pull request merged**
