### PR TITLE
remove pointless variable initialization in socketmodule

### PR DESCRIPTION
**Pull request by wrongnull**
This value is never read, so this assignment is meaningless and will be optimized away at compile time. The issue was not created and the new entry was skipped because the changes are not visible to the user.

### CODE REVIEW

**Review by Eclips4 — APPROVED** [review]

**Comment by erlend-aasland** [comment]
> This value is never read, so this assignment is meaningless and will be optimized away at compile time.

Is it really so? ;)

https://github.com/python/cpython/blob/bb66600558cb8d5dd9a56f562bd9531eb1e1685f/Modules/socketmodule.c#L1735-L1739

In general, we try to not encourage PRs like this. As you already pointed out, the compiler will optimise it away anyway, so the CI, review, and Git history churn is (in most cases) not worth it.

I'm sure you can find a lot of interesting bugs to work on in the issue tracker :)

**Comment by erlend-aasland** [comment]
Moreover, we try really hard to avoid the `skip issue` label. See the devguide for more details :)

**Comment by wrongnull** [comment]
> Is it really so? ;)

It is. I just ran clang static analyzer on that file.

**Comment by erlend-aasland** [comment]
Before tearing down Chesterton's Fence, take a look and try to find out why a specific line of code was introduced in the first place. I find `git log -L:funcname:filename` to be a useful tool for this.

**Pull request closed without merging**
