### PR TITLE
bpo-39166: Fix trace of last iteration of async for loops

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue39166

### CODE REVIEW

**Comment by pablogsal** [comment]
@markshannon Could you take a look at this when you have time? I am not happy about this solution as is just adding more shrinkwrap but solving the general case is not immediate.

@nedbat Could you check if this breaks anything else in your test suite?

**Comment by nedbat** [comment]
All my tests pass with this change, thanks!

**Comment by pablogsal** [comment]
> s/incorrent/incorrect/

Thanks for the catch, will correct the other one in a separate PR!

**Comment by markshannon** [comment]
Unless I am misunderstanding the code, this seems rather fragile as it relies on the compiler emitting the `async for` exception handler non-aligned with a line and all other exception handlers aligned with a new line.
That seems an unreasonable restraint on the compiler and is not documented anywhere.

Again, it seems like we need a way to signal that instructions are artificial and should be ignored by tracing.

**Comment by pablogsal** [comment]
> That seems an unreasonable restraint on the compiler and is not documented anywhere.

Yup, that is why I said:

>  I am not happy about this solution as is just adding more shrinkwrap but solving the general case is not immediate

> Again, it seems like we need a way to signal that instructions are artificial and should be ignored by tracing.

Yup, I fully agree, but os not going to be that immediate, because we need to manage also pushing and poping blocks in the frame in the eval loop. 

How do you want to proceed? Do you want to close this and wait until we have a more resilient solution or you want to merge this (and the tests) meanwhile?

**Comment by markshannon** [comment]
I'm going to merge this.
It isn't perfect , but it is an improvement and it doesn't prevent further improvements.
@nedbat, @pablogsal Any final comments before I merge?

**Comment by nedbat** [comment]
None from my side.  I'm still wondering if there's a lowish-cost way to transfer some of the coverage.py tests to the CPython test suite, to shrink the feedback loop.

**Comment by pablogsal** [comment]
> I'm still wondering if there's a lowish-cost way to transfer some of the coverage.py tests to the CPython test suite, to shrink the feedback loop.

I have plans to work on this soonish, I will let you know once I have some free cycles. :)

**Comment by pablogsal** [comment]
> Any final comments before I merge?

Nop, thanks for the review! Let's sync in the future to try to work on a more resilient solution :)

**Pull request merged**
