### PR TITLE
added a more strict version of defaultdict

### PR DESCRIPTION
**Pull request by ravi140222**
should I create an issue first for this?
was discussing this at https://discuss.python.org/t/disabling-use-of-certain-keywords-with-defaultdict/14790/7

### CODE REVIEW

**Comment by sweeneyde** [comment]
Thanks for your curiosity. Yes, this sort of change requires an issue.

Some thoughts though:

* It's unclear why this is modifying importlib. The defaultdict implementation lives at `Modules/_collectionsmodule.c`
* It doesn't make much sense to me to have an incomplete list of "all the things you're not supposed to do". There is an infinity of things that wouldn't make sense to do.
* Python typically has an "Easier-to-Ask-Forgiveness-than-Permission" exception handling convention, rather than a "Look-Before-You-Leap" one. See, e.g., https://docs.python.org/3/glossary.html#term-EAFP and the `duck-typing` entry above it.
* It's possible to construct many other objects that don't make much sense, e.g., `map(1, "ABC")`. They'll notify you that something is wrong when something actually goes wrong. Namely, `1` raises a `TypeError` if someone tries to call it.

So unless something changes, I'd be opposed to this change.

A note about the particular implementation: Querying `something in some_dict.values()` is a linear time that could be turned into a constant-time test of `something in some_set`. It's also unclear why strings are being used at all, as opposed to, say, just the set of callables.

**Comment by ravi140222** [comment]
I was confused where to put it, as the defaultdict implementation is in a `c` file.
I made the changes that you suggested.
Should this PR be closed if it does not appear to be something that could be changed?
Or keep it open, in case it could have some purpose at a later time.

**Comment by sweeneyde** [comment]
For the reasons listed before, I'll go ahead and close this, but thanks for the effort.

**Comment by ravi140222** [comment]
but could you tell me what happens in the case of `functools.reduce`, why is the check being done immediately here.
should it not be changed to not throw an error, when used like `functools.reduce(1, ['a', 'b']).

**Pull request closed without merging**
