### PR TITLE
Remove the test for xc in _pydecimal

### PR DESCRIPTION
**Pull request by donno2048**

### CODE REVIEW

**Comment by ambv** [comment]
How is it obvious that `xc` is never 1?

**Comment by donno2048** [comment]
If `xc == 1` then the function will return in line `2140`

**Comment by donno2048** [comment]
@ambv any response?

**Comment by ambv** [comment]
Sorry, it's still unclear to me that this is certain. On lines 2190, 2200, and 2217 there might be cases in which `xc` becomes 1. Since the code is very math-heavy there, I don't feel confident about dropping those checks.

**Comment by donno2048** [comment]
> Sorry, it's still unclear to me that this is certain. On lines 2190, 2200, and 2217 there might be cases in which `xc` becomes 1. Since the code is very math-heavy there, I don't feel confident about dropping those checks.

But everyone of this lines is inside the `y.sign == 1` condition which means they'll return in line `2224` (or before) and won't get to this part any way.

**Comment by donno2048** [comment]
@ambv

**Comment by ambv** [comment]
Do you have a tool with which you found the issue in this pull request and your other pull requests? Or did you do this manually?

For me, there's too many paths through this function for us to be able to reliably tell.

**Comment by donno2048** [comment]
Found it by hand, any code analysis tool will give probably thousands of errors and warning, I won't go through it all

**Comment by donno2048** [comment]
> For me, there's too many paths through this function for us to be able to reliably tell.

It's obviously either going to get into the condition or not, if not then `xc` won't change and we don't need to check for it since we know it wasn't `1` if it does enters the condition then it'll return before reaching this part in the code and we can surely just not check for `xc`

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨

**Pull request merged**
