### PR TITLE
gh-101955: Fix SystemError in possesive quantifier with alternative and group

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-101955

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
@animalize Could you please make a review of this PR?

**Comment by wjssz** [comment]
How about this patch? It's simpler.
```diff
 Modules/_sre/sre_lib.h | 20 ++++++++++++++++++++
 1 file changed, 20 insertions(+)

diff --git a/Modules/_sre/sre_lib.h b/Modules/_sre/sre_lib.h
--- a/Modules/_sre/sre_lib.h
+++ b/Modules/_sre/sre_lib.h
@@ -1257,6 +1257,18 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                pointer */
             state->ptr = ptr;
 
+            /* Set state->repeat to non-NULL */
+            ctx->u.rep = (SRE_REPEAT*) PyObject_Malloc(sizeof(*ctx->u.rep));
+            if (!ctx->u.rep) {
+                PyErr_NoMemory();
+                RETURN_ERROR(SRE_ERROR_MEMORY);
+            }
+            ctx->u.rep->count = -1;
+            ctx->u.rep->pattern = NULL;
+            ctx->u.rep->last_ptr = NULL;
+            ctx->u.rep->prev = state->repeat;
+            state->repeat = ctx->u.rep;
+
             /* Initialize Count to 0 */
             ctx->count = 0;
 
@@ -1271,6 +1283,10 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                 }
                 else {
                     state->ptr = ptr;
+                    /* Restore state->repeat */
+                    state->repeat = ctx->u.rep->prev;
+                    PyObject_Free(ctx->u.rep);
+
                     RETURN_FAILURE;
                 }
             }
@@ -1343,6 +1359,10 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                 }
             }
 
+            /* Restore state->repeat */
+            state->repeat = ctx->u.rep->prev;
+            PyObject_Free(ctx->u.rep);
+
             /* Evaluate Tail */
             /* Jump to end of pattern indicated by skip, and then skip
                the SUCCESS op code that follows it. */
```

**Comment by wjssz** [comment]
How about this patch? It's simpler:
```diff
 Modules/_sre/sre_lib.h | 20 ++++++++++++++++++++
 1 file changed, 20 insertions(+)

diff --git a/Modules/_sre/sre_lib.h b/Modules/_sre/sre_lib.h
index 97fbb0a75e5..2d124ab5ac3 100644
--- a/Modules/_sre/sre_lib.h
+++ b/Modules/_sre/sre_lib.h
@@ -1294,6 +1294,18 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                pointer */
             state->ptr = ptr;
 
+            /* Set state->repeat to non-NULL */
+            ctx->u.rep = (SRE_REPEAT*) PyObject_Malloc(sizeof(*ctx->u.rep));
+            if (!ctx->u.rep) {
+                PyErr_NoMemory();
+                RETURN_ERROR(SRE_ERROR_MEMORY);
+            }
+            ctx->u.rep->count = -1;
+            ctx->u.rep->pattern = NULL;
+            ctx->u.rep->last_ptr = NULL;
+            ctx->u.rep->prev = state->repeat;
+            state->repeat = ctx->u.rep;
+
             /* Initialize Count to 0 */
             ctx->count = 0;
 
@@ -1308,6 +1320,10 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                 }
                 else {
                     state->ptr = ptr;
+                    /* Restore state->repeat */
+                    state->repeat = ctx->u.rep->prev;
+                    PyObject_Free(ctx->u.rep);
+
                     RETURN_FAILURE;
                 }
             }
@@ -1380,6 +1396,10 @@ SRE(match)(SRE_STATE* state, const SRE_CODE* pattern, int toplevel)
                 }
             }
 
+            /* Restore state->repeat */
+            state->repeat = ctx->u.rep->prev;
+            PyObject_Free(ctx->u.rep);
+
             /* Evaluate Tail */
             /* Jump to end of pattern indicated by skip, and then skip
                the SUCCESS op code that follows it. */
```

**Comment by serhiy-storchaka** [comment]
@wjssz, would not it leak memory in case of error (when user interrupted evaluation by pressing Ctrl-C)?

There are two differences of this PR from your patch:
* It tries to avoid a memory leak in case of error.
* It tries to not allocate a new SRE_REPEAT block if not needed.

But I have suspect that it does not work. It is difficult to test the former case, and the latter case may work incorrectly in case of nested possessive repetitions. So it may be safer to use your simpler patch and fix memory leaks later. Do you mind to create a PR @wjssz?

**Comment by wjssz** [comment]
I'm @animalize, this is my new GitHub account.

> would not it leak memory in case of error (when user interrupted evaluation by pressing Ctrl-C)?

You are right. Maybe `RETURN_FAILURE;` is better than `RETURN_ERROR(SRE_ERROR_MEMORY)` for this reason.

> So it may be safer to use your simpler patch and fix memory leaks later. Do you mind to create a PR @wjssz?

Sorry. I'm not going to sign CLA.
Don't forget to change from `PyObject_Malloc/Free()` to `PyMem_Malloc/Free()`.

> fix memory leaks later

I have a patch for this. I'll post it after.

**Comment by serhiy-storchaka** [comment]
You are welcome @wjssz/@animalize. It was pleasure to work with you last time.

Right now I'm writing a code which would help to test user interruption and catch memory leaks.

**Comment by serhiy-storchaka** [comment]
Now, after fixing leaks and using memory pool for SRE_REPEAT, the simpler patch https://github.com/python/cpython/pull/111362#issuecomment-2415712607 can be used. Thanks @wjssz.

**Pull request merged**
