### PR TITLE
gh-82378: fix sys.tracebacklimit in pyrepl

### PR DESCRIPTION
**Pull request by cfbolz**
make sure that pyrepl uses the same logic for `sys.tracebacklimit` as both the basic repl and the standard `sys.excepthook`. as discussed on #82378, `sys.tracebacklimit` has two different meanings, and this pr makes sure that it's consistent in the two repls.

* Issue: gh-82378

### CODE REVIEW

**Comment by cfbolz** [comment]
@serhiy-storchaka would you maybe have time to look at this one as well? it's vaguely related to the `excepthook` PR: also a cornercase behaviour-change in pyrepl compared to the classic repl.

**Comment by serhiy-storchaka** [comment]
I first want to merge #122528. It performs refactoring, so it will conflict with this PR, but at the end it can make it simpler.

I wonder how it affects this issue.

**Comment by cfbolz** [comment]
> I first want to merge #122528. It performs refactoring, so it will conflict with this PR, but at the end it can make it simpler.
> 
> I wonder how it affects this issue.

Thanks for the heads up, makes sense! I'm happy to rebase this pr once you're done.

**Comment by serhiy-storchaka** [comment]
Please rebase.

**Comment by cfbolz** [comment]
@serhiy-storchaka I'm traveling for a bit, sorry, will do it end next week.

**Comment by cfbolz** [comment]
@serhiy-storchaka I've merged main into the PR. you could look again.

I've also opened a variant of this PR, #123062 , with a more radical change. please pick whichever is more appropriate, I'm fine with either outcome.

**Comment by serhiy-storchaka** [comment]
#123062 looks better in long run. I propose to modify it (it can be considered a third variant).

**Comment by cfbolz** [comment]
I'm closing this PR, #123062 looks much better now.

**Pull request closed without merging**
