### PR TITLE
bpo-22831: Use "with" to avoid possible fd leaks in distutils.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue22831

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM.

FYI I rebased the PR on master and used "git diff master.. -w" to hide indentation changes.

**Comment by vstinner** [comment]
Oh, it's also possible to ignore whitespaces by adding ?w=1 to the URL!
https://github.com/python/cpython/pull/10921/files?w=1

**Comment by tirkarthi** [comment]
I think this might help in having a review from @merwok given that there is similar open issue with changes to distutils and some comments on the other issue's PR changes https://bugs.python.org/issue35416#msg331114

**Comment by merwok** [comment]
This looks OK.  Does it replace the other PR?

**Comment by serhiy-storchaka** [comment]
It intersects with the other PR. It is an extraction from a larger patch which changed all code that calls `close()` explicitly. Seems the other PR contains also other changes.

**Pull request merged**
