### PR TITLE
bpo-30723: Enhancement to IDLE parenmatch extension

### PR DESCRIPTION
**Pull request by wohlganger**
flash-delay now independent of style.
added 'parens' style: highlights left and right parens.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by mlouielu** [comment]
@wohlganger, what is the different between this PR and #2306 ? Are they the same? thanks.

**Comment by wohlganger** [comment]
Sorry, I'm new. I thought this was rejected by the bot. #2306 also makes the FLASH_DELAY work with ctrl-0 activated parens highlighting. I didn't know IDLE  had that, and it was a simple fix in the same file. I also added my name to the acks file. This commit should be rejected while I try to get #2306 accepted.

**Comment by terryjreedy** [comment]
Closed as duplicate of #2306

**Pull request closed without merging**
