### PR TITLE
gh-123657: Fix crash and refleak in `decimal.getcontext()`

### PR DESCRIPTION
**Pull request by neonene**
* Issue: gh-123657

### CODE REVIEW

**Comment by neonene** [comment]
@ZeroIntensity Could you verify this fix?

cc @kumaraditya303 @erlend-aasland

**Comment by ZeroIntensity** [comment]
I can take a look in an hour or so.

**Review by ZeroIntensity — APPROVED** [review]
Confirmed that this fixes the assertion failure, as well as the memory leak:

```
./python -Xshowrefcount -c "import decimal; decimal.getcontext()"
[0 refs, 0 blocks]
```

**Comment by ZeroIntensity** [comment]
@encukou, this needs the 3.13 backport label.

**Comment by encukou** [comment]
This makes `setcontext` leak in the `--with-decimal-contextvar=no` build:
```
$ ./python -Xshowrefcount -c "import decimal; decimal.getcontext(); decimal.setcontext(decimal.Context())"
[7122 refs, 4233 blocks]
```

Since `cached_context` is now an owned reference, `PyDec_SetCurrentContext` needs a Py_CLEAR instead of just setting to NULL.
Please also adjust `cached_context`'s comment in the `decimal_state` struct: explicity mention it's a strong reference.

**Comment by neonene** [comment]
Done.

**Review by encukou — APPROVED** [review]

**Comment by encukou** [comment]
Thanks!
(FWIW, A big reason why I wanted “owned reference” mentioned is that it's not immediately clear that this is a `PyObject` subclass and so it even *can* have strong reference. It didn't need to be emphasized this much. But, that's a minor point.)

**Comment by vstinner** [comment]
Thanks for this nice fix. It does fix this leak.

Before:

```
$ ./python -X showrefcount -c 'import decimal; decimal.getcontext()'
[207 refs, 138 blocks]
```

After (with this fix):

```
$ ./python -X showrefcount -c 'import decimal; decimal.getcontext()'
[0 refs, 0 blocks]
```

cc @picnixz

**Pull request merged**
