### PR TITLE
Removed dangling `since Python` at the end of library/xml.rst

### PR DESCRIPTION
**Pull request by Seluj78**

### CODE REVIEW

**Review by Mariatta — APPROVED** [review]

**Comment by Seluj78** [comment]
@tiran Was the `since Python` at the end supposed to be for something ? I just looked at the blame and you were the last one to change those lines 👍

**Comment by serhiy-storchaka** [comment]
I do not know what would be better: to remove the trailing "since Python" or to remove the leading "since Python" and fix the trailing one. What looks better English?

In any case, I think it is better to replace `3.8.0` with `3.8` and add the corresponding `versionchanged` directive.

**Comment by Seluj78** [comment]
I think leaving the first `since Python` looks better 👍 

As for the `versionchanged` directive, I'll see what I can do 👌

**Comment by Seluj78** [comment]
@serhiy-storchaka Is this what you wanted? 👌

**Comment by serhiy-storchaka** [comment]
The `versionchanged` directives were added in proper places (in `xml.dom.pulldom.rst` and `xml.sax.rst`), so it is not needed here. Sorry.

**Comment by serhiy-storchaka** [comment]
Just restore your initial change please.

**Comment by Seluj78** [comment]
@serhiy-storchaka Done 👌

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
