### PR TITLE
bpo-24209: In http.server script, rely on getaddrinfo to bind to preferred address based on the bind parameter.

### PR DESCRIPTION
**Pull request by jaraco**
https://bugs.python.org/issue24209

### CODE REVIEW

**Comment by jaraco** [comment]
With this patch, I see this behavior:

```
cpython feature/http-server-bind-ipv6 $ ./python.exe -m http.server --bind localhost                                                                                                     
Serving HTTP on ::1 port 8000 (http://::1:8000/) ...
^C
Keyboard interrupt received, exiting.
cpython feature/http-server-bind-ipv6 $ ./python.exe -m http.server                                                                                                                      
Serving HTTP on :: port 8000 (http://:::8000/) ...
^C
Keyboard interrupt received, exiting.
```

**Comment by jaraco** [comment]
@lisroach Since you reviewed and submitted the last PR on this issue, would you care to comment on or review this also?

**Comment by jaraco** [comment]
I'm inclined to proceed with the merge, but happy to iterate further as needed.

**Comment by rathann** [comment]
Will this be backported to 3.7?

**Pull request merged**
