### PR TITLE
bpo-40684: Fix make install for platlibdir=lib64

### PR DESCRIPTION
**Pull request by vstinner**
"make install" now uses the PLATLIBDIR variable for the destination
lib-dynload/ directory when ./configure --with-platlibdir is used.

Update --with-platlibdir comment in configure.

https://bugs.python.org/issue40684

### CODE REVIEW

**Comment by vstinner** [comment]
Currently, --libdir=/usr/lib64 updates BINLIBDEST and DESTSHARED.

With this change, BINLIBDEST and DESTSHARED no longer depend on LIBDIR but always use ``$exec_prefix/$PLATLIBDIR/`` path.

@hroncok @mcepl @ned-deily @zware: Would you mind to review this change? I'm not comfortable with changing the build system :-/

See https://bugs.python.org/issue40684 for the context and the bug.

**Comment by vstinner** [comment]
To reduce the risk of regression, one option would be to continue to use `BINLIBDEST=	$(LIBDIR)/python$(VERSION)` by default, but use `BINLIBDEST=	${exec_prefix}/${PLATLIBDIR}/python$(VERSION)` with ``--with-platlibdir=`` option is used.

**Comment by vstinner** [comment]
> To reduce the risk of regression, one option would be to continue to use BINLIBDEST= $(LIBDIR)/python$(VERSION) by default, but use BINLIBDEST= ${exec_prefix}/${PLATLIBDIR}/python$(VERSION) with --with-platlibdir= option is used.

Done. This PR has no more effect by default. Now it only changes BINLIBDEST when --with-platlibdir is used.

**Comment by mcepl** [comment]
+1 from me

**Pull request merged**
