### PR TITLE
gh-123843: change _datetimemodule.c & datetimetest.py zope refs to archive

### PR DESCRIPTION
**Pull request by otkd**
Resolves the issue by replacing broken references with archived versions of the canonical zope pages

* Issue: gh-123843

### CODE REVIEW

**Comment by Eclips4** [comment]
Please remove the `NEWS` entry, it's not needed here.

**Comment by otkd** [comment]
> Please remove the `NEWS` entry, it's not needed here.

@Eclips4 done, thank you

**Review by Eclips4 — APPROVED** [review]
Thanks!

**Review by AA-Turner — COMMENTED** [review]
Having looked at the two links, I'm not sure that they add anything valuable beyond historic interest from 20 years ago -- I've opened #123846 as a sketch of a different approach to remove the links. I tried to add them as review suggestions but GH's interface made it too confusing, sorry.

A

**Comment by terryjreedy** [comment]
I add DO-NOT-MERGE because I am perhaps 90% sure that Turner's alternative PR should be merged instead.  But I am not quite sure enough to just do it.

**Comment by otkd** [comment]
@AA-Turner @terryjreedy Tbh I agree removing the links is better, I would even propose that links be removed from comments in general.

Closing in favor of https://github.com/python/cpython/pull/123846

**Pull request closed without merging**
