### PR TITLE
bpo-37170: Fix the cast on error in PyLong_AsUnsignedLongLongMask()

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue37170

### CODE REVIEW

**Review by mangrisano — APPROVED** [review]

**Review by vstinner — COMMENTED** [review]
While we are on it, can you also update the doc?
https://docs.python.org/dev/c-api/long.html#c.PyLong_AsUnsignedLongLongMask

replace -1 with ``(unsigned long long) -1`` in the doc.

Since it's a bug fix, can you also add a NEWS entry?

**Comment by ZackerySpytz** [comment]
Thank you, @vstinner, for the review. I have made the requested changes.

3.6 only takes security fixes at this point, so I think the "needs backport to 3.6" label should be removed, no?

**Review by jdemeyer — CHANGES_REQUESTED** [review]
Shouldn't there be a test added for this?

**Comment by vstinner** [comment]
> 3.6 only takes security fixes at this point, so I think the "needs backport to 3.6" label should be removed, no?

Oops, I'm not used to Python 3.8 branch yet :-) I wanted to add "needs backport to 3.8" ;-) (fixed)

> Shouldn't there be a test added for this?

Yes, a test would be good.

**Review by mdickinson — APPROVED** [review]
LGTM. Would it be feasible to write a regression test?

**Comment by mdickinson** [comment]
> Would it be feasible to write a regression test?

Ah, sorry; I should have read the other comments first.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by vstinner** [comment]
> Ah, sorry; I should have read the other comments first.

A test should be added.

**Review by mdickinson — APPROVED** [review]
LEGTM! (Looks even gooder to me, now that it has a test.)

**Comment by vstinner** [comment]
@ZackerySpytz: oh, so backport failed. Would you mind to attempt to backport the change manually to 3.8 first? Once 3.8 fix will land, we can consider other backports.

**Comment by ZackerySpytz** [comment]
@vstinner, I have created a backport to 3.8.

**Comment by vstinner** [comment]
> @vstinner, I have created a backport to 3.8.

Merged, thanks. Can you try to backport to 3.7 and 2.7? You might reuse the 3.8 or not, it's up to you.

**Pull request merged**
