### PR TITLE
bpo-38519: Internal include files missing on Windows

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue38519

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
@zooba Do you think we need a news entry for this?

**Review by eamanu — APPROVED** [review]
LGTM. IMO we need NEWs

**Comment by zooba** [comment]
Agreed. A NEWS entry reading `Restores the internal C headers that were missing from the nuget.org and Microsoft Store packages` would be fine.

**Review by zooba — APPROVED** [review]
Approved with NEWS entry

**Comment by ZackerySpytz** [comment]
I have added a news entry.

**Pull request merged**
