### PR TITLE
bpo-31371: Remove Tix

### PR DESCRIPTION
**Pull request by zware**
https://bugs.python.org/issue31371

### CODE REVIEW

**Review by ned-deily — APPROVED** [review]
LGTM

**Review by zooba — APPROVED** [review]
Is there a source/bin-deps PR to review as well?

**Comment by zware** [comment]
@zooba No; the bin-deps change will be up to you and source-deps won't change (we have to keep it around there for older versions).

**Comment by zware** [comment]
PEP 4 says we can't remove it yet, so bpo-31371 has been closed.

**Pull request closed without merging**
