### PR TITLE
bpo-38636: Fix IDLE tab toggle and file indent width

### PR DESCRIPTION
**Pull request by terryjreedy**
These format menu functions (default shortcuts Alt-T and Alt-U)
were mistakenly disabled in 3.7.5 and 3.8.0.

https://bugs.python.org/issue38636

### CODE REVIEW

**Comment by terryjreedy** [comment]
I might eventually fix this a different way, but this is simple enough to apply by hand to existing 3.7.5 and 3.8.0 installations  -- add a line and edit or replace the two that follow.

I intend to add new tests before merging.

**Comment by taleinat** [comment]
This is such an obvious fix, I suggest just merging it.

I'm not sure we should be automatically testing that all of our menu options work, anyways.

**Review by taleinat — APPROVED** [review]
LGTM

**Comment by terryjreedy** [comment]
The bug being fixed is a faulty binding, so I would one day like to test  them automatically as well as manually (which I forgot here), but another time.  I did want to finish the format module tests.  Just waiting for CI.

**Pull request merged**
