### PR TITLE
bpo-34160: Add the sort attribute to the xml.dom.minidom.Node.writexml method

### PR DESCRIPTION
**Pull request by matrixise**
https://bugs.python.org/issue34160

### CODE REVIEW

**Comment by matrixise** [comment]
I closed/reopen the PR there was an issue with appveyor

**Comment by matrixise** [comment]
in fact, there was some issues in my code :/ not detected locally but fortunately AppVeyor was there ;-)

**Comment by tirkarthi** [comment]
I think this is the same as https://github.com/python/cpython/pull/10452 that has a discussion about adding a new sort parameter.

**Comment by matrixise** [comment]
I close this PR

**Pull request closed without merging**
