### PR TITLE
bpo-42103: Improve validation of Plist files.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Prevent some possible DoS attacks via providing invalid Plist files
with extremally large number of objects or collection sizes.

https://bugs.python.org/issue42103

### CODE REVIEW

**Review by ronaldoussoren — APPROVED** [review]
LGTM

**Comment by serhiy-storchaka** [comment]
Please make review of new changes.

* Added NEWS entries.
* Added more tests.
* Raise InvalidFileException for too large bytes and string size instead of returning garbage.
* Raise InvalidFileException instead of ValueError for specific invalid datetime (NaN).
* Raise InvalidFileException instead of TypeError for non-hashable dict keys.

Not all errors in Plist file are checked, loading broken Plist file can produce a garbage. But if an error is detected you get InvalidFileException instead of ValueError, IndexError, etc. Of course you can still get MemoryError (if read too large file) or RecursionError.

**Comment by serhiy-storchaka** [comment]
@ronaldoussoren, please take a look again.

**Review by ronaldoussoren — APPROVED** [review]
LGTM.

**Pull request merged**
