### PR TITLE
[Feature request (Do not merge)] Give better error message

### PR DESCRIPTION
**Pull request by masterneko**
The problem with python is that the warnings/errors are not that useful. Take this for example

```
  File "game.py", line 85
    if gameOver == True
                      ^
SyntaxError: invalid syntax
```
Here I have forgotten the colon, this error message is not very useful.
It would be helpful if it said `Expected ":" at line [line]`

P.S: Can python please enable issues on github?

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@caelwithcats

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by caelwithcats** [comment]
@the-knights-who-say-ni What is this and why do I need to sign a "PSF" agreement, it's free and open source software. I haven't heard of any such thing in FOSS software !??!

**Comment by methane** [comment]
@caelwithcats Thank you for your contributing.

The license agreement is needed to keep FOSS.
Please read our contributors guide. https://devguide.python.org/pullrequest/#cla

**Comment by terryjreedy** [comment]
To expand, in past decades there have been major software copyright lawsuits involving years of court actions and millions of dollars in lawyer fees.  The CA was in response to try to keep PSF from being a target of such and lessen damage if it is.

**Comment by caelwithcats** [comment]
Fix python
```
if gameOver == 0
{
     print "Game over, back to python2"
}

**Pull request closed without merging**
