### PR TITLE
bpo-37177: make IDLE's search dialogs transient

### PR DESCRIPTION
**Pull request by taleinat**
https://bugs.python.org/issue37177

### CODE REVIEW

**Comment by taleinat** [comment]
@IrvKalb, your review would be appreciated!

**Comment by terryjreedy** [comment]
Even if this does not fix all hiding issues, it should be merged, with a blurb added, as a fix for bpo-24139.
Possible text:  "Properly 'attach' search dialogs to their edit windows so that they work like other dialogs and do not get hidden beneath."

**Comment by taleinat** [comment]
> as a fix for bpo-24139

That appears to be the wrong issue.

**Comment by terryjreedy** [comment]
Sorry, bpo-24039.

**Pull request merged**
