### PR TITLE
gh-62090: Simplify argparse usage formatting

### LINKED ISSUE #62090: argparse: mutually exclusive groups full of help-suppressed args can cause AssertionErrors
BPO | [17890](https://bugs.python.org/issue17890)
--- | :---
Nosy | @terryjreedy, @bitdancer, @vadmium, @iritkatriel
Files | <li>[argparse-assertfail.py](https://bugs.python.org/file30102/argparse-assertfail.py "Uploaded as text/plain at 2013-05-02.00:43:01 by gholms"): Test case</li><li>[7691d1d4b955.diff](https://bugs.python.org/file30108/7691d1d4b955.diff "Uploaded as text/plain at 2013-05-02.13:53:44 by Yogesh.Chaudhari"): gholms repo</li><li>[Issue17890-27.patch](https://bugs.python.org/file30110/Issue17890-27.patch "Uploaded as text/plain at 2013-05-02.16:22:44 by Yogesh.Chaudhari"): Resolution for Python 2.7 issue17890</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-05-02.00:43:02.387>
labels = ['type-bug', 'library']
title = 'argparse: mutually exclusive groups full of help-suppressed args can cause AssertionErrors'
updated_at = <Date 2021-12-10.16:06:27.619>
user = 'https://bugs.python.org/gholms'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.16:06:27.619>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-05-02.00:43:02.387>
creator = 'gholms'
dependencies = []
files = ['30102', '30108', '30110']
hgrepos = ['187']
issue_num = 17890
keywords = ['patch']
message_count = 17.0
messages = ['188250', '188253', '188278', '188291', '188295', '188306', '188337', '188379', '188413', '188984', '189054', '189064', '189065', '189355', '193191', '259189', '408217']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'bethard', 'r.david.murray', 'martin.panter', 'paul.j3', 'Yogesh.Chaudhari', 'gholms', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'patch review'
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue17890'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

### Linked PRs
* gh-105039

### LINKED ISSUE #62549: argparse usage should preserve () in metavars such as range(20)
BPO | [18349](https://bugs.python.org/issue18349)
--- | :---
Nosy | @iritkatriel
Files | <li>[metaparen.patch](https://bugs.python.org/file30754/metaparen.patch "Uploaded as text/plain at 2013-07-03.06:16:49 by paul.j3")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-07-03.06:16:51.100>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'argparse usage should preserve () in metavars such as range(20)'
updated_at = <Date 2021-12-10.15:48:45.716>
user = 'https://bugs.python.org/paulj3'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.15:48:45.716>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-07-03.06:16:51.100>
creator = 'paul.j3'
dependencies = []
files = ['30754']
hgrepos = []
issue_num = 18349
keywords = ['patch']
message_count = 5.0
messages = ['192222', '192717', '193077', '193188', '408214']
nosy_count = 2.0
nosy_names = ['paul.j3', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue18349'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### LINKED ISSUE #77048: argparse assertion failure with multiline metavars
BPO | [32867](https://bugs.python.org/issue32867)
--- | :---
Nosy | @terryjreedy, @vadmium, @MaT1g3R, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-18.05:06:42.980>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'argparse assertion failure with multiline metavars'
updated_at = <Date 2021-12-15.19:58:48.287>
user = 'https://github.com/MaT1g3R'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-15.19:58:48.287>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-02-18.05:06:42.980>
creator = 'MaT1g3R'
dependencies = []
files = []
hgrepos = []
issue_num = 32867
keywords = []
message_count = 7.0
messages = ['312299', '312674', '312680', '312683', '312693', '314063', '408641']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'bethard', 'martin.panter', 'paul.j3', 'MaT1g3R', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'test needed'
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32867'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### LINKED ISSUE #82091: argparse wrapping fails with metavar="" (no metavar)
BPO | [37910](https://bugs.python.org/issue37910)
--- | :---
Nosy | @rhettinger, @shihai1991, @sjfranklin, @iritkatriel
PRs | <li>python/cpython#15372</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-21.22:08:19.919>
labels = ['type-bug', 'library', '3.10', '3.11']
title = 'argparse wrapping fails with metavar="" (no metavar)'
updated_at = <Date 2021-10-19.09:28:30.797>
user = 'https://github.com/sjfranklin'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-19.09:28:30.797>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-08-21.22:08:19.919>
creator = 'sjfranklin'
dependencies = []
files = []
hgrepos = []
issue_num = 37910
keywords = ['patch']
message_count = 6.0
messages = ['350117', '350169', '354647', '371415', '371446', '404280']
nosy_count = 5.0
nosy_names = ['rhettinger', 'paul.j3', 'shihai1991', 'sjfranklin', 'iritkatriel']
pr_nums = ['15372']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37910'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

### LINKED ISSUE #89743: argparse.ArgumentParser.add_mutually_exclusive_group : metavar create parenthesis undefined behavior
BPO | [45580](https://bugs.python.org/issue45580)
--- | :---
Nosy | @lysnikolaou, @pablogsal, @sobolevn, @AbcSxyZ

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-22.19:31:30.976>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'argparse.ArgumentParser.add_mutually_exclusive_group : metavar create parenthesis undefined behavior'
updated_at = <Date 2021-10-25.16:32:34.545>
user = 'https://github.com/AbcSxyZ'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-25.16:32:34.545>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-10-22.19:31:30.976>
creator = 'AbcSxyZ'
dependencies = []
files = []
hgrepos = []
issue_num = 45580
keywords = []
message_count = 4.0
messages = ['404815', '404891', '404893', '404981']
nosy_count = 5.0
nosy_names = ['paul.j3', 'lys.nikolaou', 'pablogsal', 'sobolevn', 'AbcSxyZ']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45580'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### LINKED ISSUE #96310: argparse sometimes tracebacks when all options in a mutually exclusive group are suppressed
# Bug report

When a subparser contains a mutually exclusive group and the all options in the group are suppressed,
it sometimes errors out with a traceback. The crash depends on other options (their ordering and length) and terminal size.

Reproducer:
```
#!/usr/bin/python3

import argparse

parser = argparse.ArgumentParser()
commands = parser.add_subparsers(title="commands", dest="command")
cmd_foo = commands.add_parser("foo")
group = cmd_foo.add_mutually_exclusive_group()
group.add_argument('--verbose', action='store_true', help=argparse.SUPPRESS)
group.add_argument('--quiet', action='store_true', help=argparse.SUPPRESS)
cmd_foo.add_argument("--longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong")

parser.parse_args()
```

```
$ python3.11 reproducer.py foo --help
Traceback (most recent call last):
  File ".../reproducer.py", line 13, in <module>
    parser.parse_args()
  File "/usr/lib64/python3.11/argparse.py", line 1862, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 1895, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 2085, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 2062, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.11/argparse.py", line 1971, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.11/argparse.py", line 1234, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 1895, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 2103, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 2043, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.11/argparse.py", line 1971, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.11/argparse.py", line 1112, in __call__
    parser.print_help()
  File "/usr/lib64/python3.11/argparse.py", line 2590, in print_help
    self._print_message(self.format_help(), file)
                        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 2574, in format_help
    return formatter.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 286, in format_help
    help = self._root_section.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 217, in format_help
    item_help = join([func(*args) for func, args in self.items])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 217, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
                      ^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 341, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError
```

Please note that setting `COLUMNS` to a high number doesn't trigger the traceback:
```
COLUMNS=1000 python3.11 reproducer.py foo --help
usage: reproducer.py foo [-h]  [--longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong LONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONG]

options:
  -h, --help            show this help message and exit
  --longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong LONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONG

```

# Your environment

- CPython versions tested on: 3.8.13, 3.10.6, 3.11.0b5
- openSUSE Tumbleweed 20220823

### Linked PRs
* gh-96311
* gh-115767
* gh-115768

### LINKED ISSUE #98666: mutually exclusive group w/ all parameters argparse.SUPPRESS'd causes an assert
# Bug report

```python
state_group = parser.add_mutually_exclusive_group()
state_group.add_argument('--param1', nargs='?', const='default', metavar='NAME',
                         help=SUPPRESS)
state_group.add_argument('--param2', nargs='?', const='default', metavar='NAME',
                         help=SUPPRESS)
```

will cause an assert in 
  `assert ' '.join(opt_parts) == opt_usage`
of argparse.py

because the empty group [] is converted into two spaces
e.g.
[group1] [] [group 2]
gets converted to this by the `opt_usage = format(optionals, groups)` code above the assert:
[group1]  [group 2]
and the two spaces don't match the single space of the assert

# Your environment

- CPython versions tested on: 3.10.4
- Operating system and architecture: OSX, arm64

### PR DESCRIPTION
**Pull request by hamdanal**
## Rationale

argparse performs a complex formatting of the usage for argument grouping and for line wrapping to fit the terminal width. This formatting has been a constant source of bugs for at least 10 years (see linked issues below) where defensive assertion errors are triggered or brackets and paranthesis are not properly handeled.

## Problem

The current implementation of argparse usage formatting relies on regular expressions to group arguments usage only to separate them again later with another set of regular expressions. This is a complex and error prone approach that caused all the issues linked below. Special casing certain argument formats has not solved the problem. The following are some of the most common issues:
- empty `metavar`
- mutually exclusive groups with `SUPPRESS`ed arguments
- metavars with whitespace
- metavars with brackets or paranthesis

## Solution

The following two comments summarize the solution:
- https://github.com/python/cpython/issues/82091#issuecomment-1093832187
- https://github.com/python/cpython/issues/77048#issuecomment-1093776995

Mainly, the solution is to rewrite the usage formatting to avoid the group-then-separate approach. Instead, the usage parts are kept separate and only joined together at the end. This allows for a much simpler implementation that is easier to understand and maintain. It avoids the regular expressions approach and fixes the corresponding issues.

This closes the following issues:
-  #62090
-  #62549
-  #77048
-  #82091
-  #89743
-  #96310
-  #98666

These PRs become obsolete:
-  #15372
-  #96311

* Issue: gh-62090

### CODE REVIEW

**Comment by hamdanal** [comment]
@rhettinger @hpaulj I’d like to get your opinion on this change if you don’t mind.

P.S: the failure on Windows doesn’t seem to be related.

**Comment by hpaulj** [comment]
I agree that the existing usage formatter is too brittle.  9 years ago I tried to write an alternative as part of a project to generalize the concept of mutually-exclusive-groups, allowing other relations (and/or/any etc), and nesting.  https://bugs.python.org/issue11588.  I can't offhand find my best usage patch, but agree with the idea of building usage groups, and combining them at the end. 

But currently I'm not as involved with github and argparse.  I'm commenting on some issues, but have not contributed (or tested) a patch (in the old style) or  github push in a long time.

**Comment by encukou** [comment]
A simplification sounds good to me. I'll start reading up on argparse so I can review this in detail.

**Comment by encukou** [comment]
This does not handle nested exclusive groups correctly. Nested exclusive groups are deprecated, but still supported for now. For example:
```
import argparse
parser = argparse.ArgumentParser()
g=parser.add_mutually_exclusive_group()
g.add_argument('--spam')
gg=g.add_mutually_exclusive_group()
gg.add_argument('--hax')
gg.add_argument('--hex')
g.add_argument('--eggs')
parser.add_argument('--num')
print(parser.format_usage())
```
Without this change, the output is not ideal, but technically correct:
```plain
/tmp/repro.py:5: DeprecationWarning: Nesting mutually exclusive groups is deprecated.
  gg=g.add_mutually_exclusive_group()
usage: repro.py [-h] [--spam SPAM | [--hax HAX | --hex HEX |] --eggs EGGS] [--num NUM]
```
But with this change, the argument added at the end (`--num`) joins the group:
```plain
/tmp/repro.py:5: DeprecationWarning: Nesting mutually exclusive groups is deprecated.
  gg=g.add_mutually_exclusive_group()
usage: repro.py [-h] [--spam SPAM | [--hax HAX | --hex HEX] | --eggs EGGS | [--num NUM]]
```

One fix would be to pad the new sequence with `None` to keep the original length when replacing `parts[start:end]` at the end. That way the meaning of indices wouldn't change

**Comment by hpaulj** [comment]
We need to be very careful when nesting groups.  What's the intent, and
what's the actual parsing action?  Carefully consider all the discussion
dealing with the deprecation. It isn't just because the usage formatting is
broken.

**Comment by hamdanal** [comment]
Thank you both for the valuable feedback, I've addressed the case of nested groups and tested several variations with/without suppressed actions locally and they all produce the correct usage text now.

**Review by encukou — APPROVED** [review]

**Comment by encukou** [comment]
Thank you for the fix!

**Pull request merged**
