### PR TITLE
bpo-32159: Remove tools for CVS and Subversion

### PR DESCRIPTION
**Pull request by vstinner**
CPython migrated from CVS to Subversion, to Mercurial, and then to
Git. CVS and Subversion are not more used to develop CPython.

* platform module: drop support for sys.subversion. The
  sys.subversion attribute has been removed in Python 3.3.
* Remove Misc/svnmap.txt
* Remove Tools/scripts/svneol.py
* Remove Tools/scripts/treesync.py

https://bugs.python.org/issue32159

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]

**Comment by Mariatta** [comment]
I think there should be a news entry under "Tools" section that cvs and svn have been removed.

**Review by ned-deily — APPROVED** [review]

**Comment by vstinner** [comment]
> I think there should be a news entry under "Tools" section that cvs and svn have been removed.

Sure! Done.

**Comment by Mariatta** [comment]
Thanks @vstinner :) I hope it's ok that I changed the wording in the news entry a bit, from `not more used` to `no longer used`.

**Review by Mariatta — APPROVED** [review]

**Comment by vstinner** [comment]
> Thanks @vstinner :) I hope it's ok that I changed the wording in the news entry a bit, from not more used to no longer used.

Sure, thank you for doing that.

**Pull request merged**
