### PR TITLE
bpo-40528: Improve AST generation script to do builds simultaneously

### PR DESCRIPTION
**Pull request by isidentical**
- getopt => argparse switch (for extendability in the future)
- no old-style globals, used arguments to pass over data
- Removed limitation of not being able to produce both C and H simultaneously.
  this will make it run faster since it parses asdl once and uses that tree to
  generate both header and c source (and in the future maybe python file)

https://bugs.python.org/issue40528

### CODE REVIEW

**Comment by pablogsal** [comment]
You need to update the windows regen files (`PCbuild/regen.vcxproj`)

**Comment by pablogsal** [comment]
@tonybaloney Can you give us a hand with the `PCbuild/regen.vcxproj` shenanigans? :wink:

**Comment by tonybaloney** [comment]
@isidentical tested it on VS2019, builds well with the changes :+1:

**Comment by isidentical** [comment]
Thanks @tonybaloney!

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Great work @isidentical! 

And thanks @tonybaloney for the help :)

**Pull request merged**
