### PR TITLE
bpo-44345: Fix comment in parser.c

### PR DESCRIPTION
**Pull request by anonaka**
Fix the first line comment in parser.c

https://bugs.python.org/issue44345

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@anonaka

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by anonaka** [comment]
I have just signed the CLA.

**Review by nanjekyejoannah — COMMENTED** [review]
Its not showing yet that you signed CLA but I think it will with time.

**Review by nanjekyejoannah — COMMENTED** [review]
I will let @lysnikolaou merge this one.

**Review by lysnikolaou — APPROVED** [review]
Looks good. Congrats @anonaka on your first contribution!

**Comment by lysnikolaou** [comment]
I'm gonna go ahead and merge this without the CLA label change, since it's a small change.

**Pull request merged**
