### PR TITLE
gh-113841: fix possible undefined division by 0 in _Py_c_pow()

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-113841

### CODE REVIEW

**Comment by skirpichev** [comment]
CC @gpshead

**Review by gpshead — APPROVED** [review]
cute math trick & thanks for the detailed analysis on the issue.

**Comment by skirpichev** [comment]
Sorry, @gpshead, your description is slightly wrong;)

Of course, ``x**-y != x**y`` in general (for floating-point numbers), even for real.  E.g.:
```pycon
>>> f = 0.992856470905735
>>> math.exp(f)
2.6989328952459926
>>> 1/math.exp(-f)
2.698932895245993
```
Perhaps, I should mention that in the pr description.  It was assumed as an ordinary truth:(

Though, the difference should be ~1ULP for good libm implementations (like in above example).  So, I don't expect regressions in accuracy.  My tests seems to confirm this.

But rigor error analysis is hard.  In fact, I'm not sure why division was used from beginning.  Closest algorithm I've found (no error checks, of course;)) - it's Algorithm 190 from ACM: https://dl.acm.org/doi/10.1145/366663.366679.  It uses subtraction in the exponent.

**Comment by gpshead** [comment]
LOL I can fix the commit description in the backport. :)

**Comment by skirpichev** [comment]
Oh, yes, please.  Next time I'll try not forgot to fill pr description.

**Pull request merged**
