### PR TITLE
gh-109706: Fix multiprocessing test_nested_startmethod()

### PR DESCRIPTION
**Pull request by vstinner**
Don't check order, queue items can be written in any order.

* Issue: gh-109706

### CODE REVIEW

**Comment by vstinner** [comment]
cc @pitrou

**Review by pitrou — APPROVED** [review]
LGTM, thanks. This behavior is arguably non-intuitive...

**Comment by vstinner** [comment]
> LGTM, thanks. This behavior is arguably non-intuitive...

Well... I'm no longer surprised by surprising multiprocessing behavior :-D

**Comment by vstinner** [comment]
Merged. Thanks for the review @pitrou. I wasn't sure about that one!

**Pull request merged**
