### PR TITLE
[3.7] bpo-35983: skip trashcan for subclasses (GH-11841)

### PR DESCRIPTION
**Pull request by jdemeyer**
https://bugs.python.org/issue35983

### CODE REVIEW

**Comment by jdemeyer** [comment]
CC @pitrou

**Comment by pitrou** [comment]
This is backporting a new API, which is not something we usually do. @ned-deily

**Comment by jdemeyer** [comment]
This PR isn't so much about creating a new API, it's more about using that new API internally.

But I don't want to argue, feel free to close if it's not good for backporting.

**Comment by pitrou** [comment]
I'll let Ned decide.

**Comment by ned-deily** [comment]
Sorry but I do not think we should be making this kind of change in a maintenance release.  Let's stick to releasing in 3.8.

**Pull request closed without merging**
