### PR TITLE
 Fix 'deecorator' typo in test/test_dataclasses

### PR DESCRIPTION
**Pull request by terryjreedy**

### CODE REVIEW

**Review by ericvsmith — APPROVED** [review]
Looks good to me. Thanks!

**Comment by terryjreedy** [comment]
Do you or do you not want this backported?

**Comment by ericvsmith** [comment]
I do!

**Comment by terryjreedy** [comment]
I presume not to 3.6 because original not bugfix.

**Comment by ericvsmith** [comment]
This code is new in 3.7, so no backport to 3.6. Thanks!

**Pull request merged**
