### PR TITLE
bpo-31905

### PR DESCRIPTION
**Pull request by Gerardwx**
Add check for None

https://bugs.python.org/issue31905

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Gerardwx** [comment]
CLA signed.

**Comment by pablogsal** [comment]
IMHO this doesn't seem a bug (as is already suggested in [the issue](https://bugs.python.org/issue31905)). Notice that any object (not only `None`) that doesn't implement `_version` will raise `AttributeError`. Checking for `None` only will be very confusing because it will return `False` but other things will not.

**Comment by vstinner** [comment]
Please elaborate the PR title.

**Comment by Mariatta** [comment]
Since the issue has been closed, and determined as not a bug, I'm closing this PR.
Thanks!

**Pull request closed without merging**
