### PR TITLE
bpo-30742 Enabling compiling with VS2015

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by zooba — CHANGES_REQUESTED** [review]
These changes are insufficient to make Python work properly when built with MSVC 14.0 or later. I've rejected the bug on BPO - please continue the discussion there if you feel strongly about this.

**Comment by jcfr** [comment]
@zooba  Thanks for the feedback.

> These changes are insufficient to make Python work properly when built with MSVC 14.0 or later.

Would you have some additional hints allowing to implement a proper patch ?

**Comment by zooba** [comment]
Find the issue on bugs.python.org for the port I made for Python 3.5 and see the associated patches.

**Comment by terryjreedy** [comment]
Issue has been closed rejecting the patch for cpython

**Comment by jcfr** [comment]
For future reference, here are the related python 3.5 issues mentioned in @zooba  review :

* http://bugs.python.org/issue24643
* http://bugs.python.org/issue22919

and some of the related patches I could find:

* python/cpython@401f9f3 : Fix #13210. Port the Windows build from VS2008 to VS2010
* python/cpython@65e4cb1 : Issue #22919: Windows build updated to support VC 14.0 (Visual Studio 2015), which will be used for the official 3.5 release.
* python/cpython@d81431f : Issue #23524: Replace _PyVerify_fd function with calling _set_thread_local_invalid_parameter_handler on every thread. 

For future reference, to allow building of Python 2.7.13 using VS2015:
* these patches have been backported and are now maintained in [this fork](https://github.com/python-cmake-buildsystem/cpython) 
* these patches do **NOT** backport changes related to the CPython visual studio build system 
* instead they are automatically applied by [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem)  (Note: this will happen only after https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/188 is merged)

**Comment by terryjreedy** [comment]
The references from me are actually from the miss-islinton bot.  They are an accident because when copying the current title line when merging PR 24469, I omitted the 9, so when miss-islington was processing the backports, it had the wrong original number.

**Comment by jcfr** [comment]
@terryjreedy  Makes sense. Thanks for the clarification.

**Pull request closed without merging**
