### PR TITLE
bpo-31533: fix broken link to OpenSSL docs

### PR DESCRIPTION
**Pull request by felipeochoa**
https://bugs.python.org/issue31533

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by tiran — APPROVED** [review]
Thanks, LGTM. The wiki is more up to date than https://linux.die.net/man/1/ciphers

You have not yet to sign the contributor agreement.

**Comment by felipeochoa** [comment]
I've signed the CLA now and linked up my bpo and github accounts. I've also fixed the other occurrence of the dead link

**Comment by tiran** [comment]
Now let the magic if Miss Islington begin!

**Pull request merged**
