### PR TITLE
gh-103053: Skip the whole `test_freeze` module in tests on `s390x` with `PGO`

### PR DESCRIPTION
**Pull request by sobolevn**
Now, let's try the buildbot test with these changes.

* Issue: gh-103053

### CODE REVIEW

**Comment by sobolevn** [comment]
@zware can you please take a look when you have the time?

**Review by vstinner — CHANGES_REQUESTED** [review]
Please don't do that. It's ok to have a red buildbot, it doesn't prevent to release Python: it's only part of [PEP 11 Tier 3](https://peps.python.org/pep-0011/#tier-3).

> Failures on these platforms do not block a release.

If you skip the failing test, as the maintainer of this platform, I will no be able to notice it :-(

**Comment by sobolevn** [comment]
So, other options are:
1. Increase the test timeout for this platform (maybe only for pgo builds)
2. Try optimizing `freeze` process (can be very complex and error prone)
3. Create another form of testing 🤔 

Any ideas are welcome!

**Comment by ambv** [comment]
We can try with a greatly increased timeout for this particular platform and see if that's indeed the problem.

**Comment by encukou** [comment]
> Any ideas are welcome!

Use a subdirectory in the build area, instead of `os_helper.temp_dir()`, and guard against it being copied into itself recursively?

**Comment by vstinner** [comment]
> Create another form of testing thinking

Honestly, I'm not convinced by the value of this test. If freeze is badly broken, everybody will notice since Python itself is also frozen, no? Or did I misunderstood the purpose of the test, or what's frozen exactly? Don't all core devs already indirectly test frozen Python?

**Comment by vstinner** [comment]
> Please don't do that. It's ok to have a red buildbot, it doesn't prevent to release Python: it's only part of [PEP 11 Tier 3](https://peps.python.org/pep-0011/#tier-3).
> If you skip the failing test, as the maintainer of this platform, I will no be able to notice it :-(

I wrote PR #109591 to not skip the test on s390x, but only if Python is built with PGO, which is differerent.

**Pull request closed without merging**
