### PR TITLE
bpo-36739: Update controlflow.rst

### PR DESCRIPTION
**Pull request by pbhd**
in addition to global-statement also mention nonlocal-statement
(in the paragraph describing access to variables which are non local to a function

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
Please sign the CLA when you get a chance.

**Comment by pbhd** [comment]
CLA is on the way...

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
I removed the news file, because it is not needed for this situation.

Thanks and congrats on your first contribution to CPython :tada:

**Pull request merged**
