### PR TITLE
gh-58032: Docs: Sort argparse alphabetically

### PR DESCRIPTION
**Pull request by hugovk**
Follow on from https://github.com/python/cpython/pull/124664, let's keep the modules sorted alphabetically.

* Issue: gh-58032

----
📚 Documentation preview 📚: https://cpython-previews--125871.org.readthedocs.build/

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
I intentionally moved builtins at the beginning of the list.

**Review by savannahostrowski — APPROVED** [review]
Thanks Hugo!

**Review by willingc — APPROVED** [review]
:ship:

**Comment by willingc** [comment]
> I intentionally moved builtins at the beginning of the list.

@serhiy-storchaka What prompted you to move to the beginning? Perhaps we need a sentence or section break between them @hugovk

**Comment by serhiy-storchaka** [comment]
Builtins look special to me, and in some other places we list them separately from other modules. I thought that even if we list them in the common list with other modules, it is worth to move the builtins module to the beginning. But I may be wrong here -- in few last What's New files (3.13, 3.14) they are listed alphabetically in the list of modules.

**Comment by willingc** [comment]
Thanks for clarifying @serhiy-storchaka. @hugovk, do you want to offset built-ins from the rest of standard library modules?

**Comment by hugovk** [comment]
In a way it's just another module in the docs, and I'd prefer alphabetical, but I don't mind too much.

If we're browsing a long list, it's easier to find alphabetically, and it'll be less likely for new edits to be added in arbitrary order if it begins with A instead of B. 

cc @AA-Turner who edited the last two versions, any opinion?

**Comment by willingc** [comment]
I'm going to go ahead and merge this to unblock the PR. We can always create future iterations to improve the difference between builtins and the other libraries.

**Pull request merged**
