### PR TITLE
gh-75552: Remove deprecated tkinter.tix module

### PR DESCRIPTION
**Pull request by zware**
* Issue: gh-75552

----
:books: Documentation preview :books:: https://cpython-previews--104902.org.readthedocs.build/

### CODE REVIEW

**Comment by zooba** [comment]
If you haven't rebuilt the MSI yourself, might be worth touching something in the tools/msi directory so that the PR tests run. I don't think there are any Tix-specific dependencies in it though, so it ought to be fine.

**Comment by zware** [comment]
Ah, hmm.  Because of the way Tcl/Tk/Tix is packaged in `cpython-bin-deps`, should we create a `tcltk-8.6.13.1` without tix?

**Comment by zware** [comment]
I suppose at worst the `tix` libraries just become dead weight in the `tcltk` installation, and the next time we build a new Tcl/Tk bundle for a new version, the dead weight will be removed.

Interestingly, the `TestsMSI` workflows "passed", but each one with 4 warnings and 2 errors.  This is not new to this PR, though so I won't hold this up based on that.  I would like a positive review from someone before I click the button, though :)

**Comment by zooba** [comment]
Yeah, there'll be updates needed to https://github.com/python/release-tools/blob/master/windows-release/tcltk-build.yml, which is where the "real" build happens. I can do that.

We probably need to tag builds separately for "without Tix" unless we've got a major version update coming (i.e. one that won't be used for 3.12)?

**Comment by zooba** [comment]
> Interestingly, the `TestsMSI` workflows "passed", but each one with 4 warnings and 2 errors.

The warnings are all expected... the errors are because we don't build the docs first in that job. I've just filed #104929 to fix that, so if you want to wait and merge it before merging this, that ought to give you clean results?

**Comment by hugovk** [comment]
Nice branch name! :)

Can some of this stuff be removed?
```
Modules/tkappinit.c
63:#ifdef WITH_TIX
65:        extern int Tix_Init(Tcl_Interp *interp);
66:        extern int Tix_SafeInit(Tcl_Interp *interp);
67:        Tcl_StaticPackage(NULL, "Tix", Tix_Init, Tix_SafeInit);

Lib/idlelib/help.html
30:    <link rel="prev" title="tkinter.tix — Extension widgets for Tk" href="tkinter.tix.html" />
126:    <p class="topless"><a href="tkinter.tix.html"
127:                          title="previous chapter"><code class="xref py py-mod docutils literal notranslate"><span class="pre">tkinter.tix</span></code> — Extension widgets for Tk</a></p>
163:          <a href="tkinter.tix.html" title="tkinter.tix — Extension widgets for Tk"
1080:    <p class="topless"><a href="tkinter.tix.html"
1081:                          title="previous chapter"><code class="xref py py-mod docutils literal notranslate"><span class="pre">tkinter.tix</span></code> — Extension widgets for Tk</a></p>
1120:          <a href="tkinter.tix.html" title="tkinter.tix — Extension widgets for Tk"

Modules/Setup
225:# specific extension (e.g. Tix or BLT), leave the corresponding line
242:# *** Uncomment and edit for Tix extension only:
243:# -DWITH_TIX -ltix8.1.8.2 \
```

**Comment by zooba** [comment]
See also https://github.com/python/release-tools/pull/47 where I'm making the Tix build step optional for the cpython-bin-deps build.

The package from my test run is at https://dev.azure.com/Python/cpython/_build/results?buildId=128771&view=artifacts&pathAsName=false&type=publishedArtifacts (for about 30 days I expect) if you want to check that it works.

**Comment by jneb** [comment]
There still is no alternative for the tix module. The Select and Balloon classes are nowhere to be found, no Python replacement, and ttk doesn't even look like tix. What are the poor users to do?

**Comment by zware** [comment]
Tix has been unmaintained for 10 years now, has open security vulnerabilities, and every update of anything in our toolchain risks breaking it.  If you still need it, it's open source and can be vendored into your project or maintained separately, but we will no longer provide it out of the box as of Python 3.13.

**Pull request merged**
