### PR TITLE
gh-101766: Fix refleak for _BlockingOnManager resources from test suite level

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-101766

### CODE REVIEW

**Comment by corona10** [comment]
@exarkun @gvanrossum @sobolevn 

* I revert the 775f8819e319127f9bfb046773b74bcc62c68b6a since @exarkun pointed out that the change will cause the regression which was already resolved.
* Rather than I tried to clean up the global dictionary at the test suite level. It will reduce the possibility of leakage at the test level.

**Review by sobolevn — APPROVED** [review]
Wow, this turned out way more complex than I initially thought! 👍

**Review by gvanrossum — APPROVED** [review]
This works too. Many tests do something like this. Is there standard infrastructure for clearing caches?

**Comment by corona10** [comment]
> This works too. Many tests do something like this. Is there standard infrastructure for clearing caches?

I am not sure, let's create a issue for that. We will need it.

**Pull request merged**
