### PR TITLE
travis: Use -O3 option

### PR DESCRIPTION
**Pull request by methane**
We don't use debugger on Travis.

### CODE REVIEW

**Comment by methane** [comment]
clang test is faster (about 18min -> 11min).
But no change on gcc+coverage test.  It's surprising to me.

**Comment by JulienPalard** [comment]
> But no change on gcc+coverage test. It's surprising to me.

As travis has a cache and you did not changed any C file, make had nothing to do so it make sense the time didn't changed.

**Review by JulienPalard — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Do you mind to create backports to 3.6 and 2.7 @methane?

**Comment by methane** [comment]
There were no trouble for long time caused by this.
I'm +1 to backport this.

**Pull request merged**
