### PR TITLE
gh-126139: Improve error message location for future statement with unknown feature

### LINKED ISSUE #126139: Improve error message locations for future statements with unknown future features
# Feature or enhancement

### Proposal:

Currently, attempting to use a future statement with an unknown future feature produces a syntax error with the error location set to the start of the line:
```none
$ python3 example.py
  File "../example.py", line 1
    from __future__ import does_not_exist
    ^
SyntaxError: future feature does_not_exist is not defined
```
This has some unfortunate UX in the new 3.13 REPL, where it results in only the `f` character at the start of the line being highlighted:

image

The UX is also suboptimal for future statements with multiple future features, since the error location doesn't show which feature is causing the error:
```none
$ python3 example.py
  File "../example.py", line 1
    from __future__ import division, with_statement, pirnt_function
    ^
SyntaxError: future feature pirnt_function is not defined
```
It would be nice if the error location instead highlighted the specific future feature that isn't defined. Something like:
```none
$ python3 example.py
  File "../example.py", line 1
    from __future__ import division, with_statement, pirnt_function
                                                     ^^^^^^^^^^^^^^
SyntaxError: future feature pirnt_function is not defined
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

_No response_

### Linked PRs
* gh-126140
* gh-126155
* gh-126160

### PR DESCRIPTION
**Pull request by brianschubert**
Fixes #126139

The error location is now set to the location of the undefined feature name:

```python
>>> from __future__ import division, with_statement, pirnt_function
  File "<python-input-0>", line 1
    from __future__ import division, with_statement, pirnt_function
                                                     ^^^^^^^^^^^^^^
SyntaxError: future feature pirnt_function is not defined
```

I wasn't sure if this is noteworthy enough for a What's New entry. Let me know if I should add one.

* Issue: gh-126139

### CODE REVIEW

**Review by iritkatriel — APPROVED** [review]

**Comment by iritkatriel** [comment]
@pablogsal Would you backdoort this?

**Comment by pablogsal** [comment]
To 3.11? Unfortunately as much as I want we are past bug fix period and I don't think this qualifies as a security fix :(

**Comment by pablogsal** [comment]
> @pablogsal Would you backdoort this?

To other branches yes: I think this easily qualifies as a bug fix

**Comment by iritkatriel** [comment]
> Sorry, @brianschubert and @iritkatriel, I could not cleanly backport this to `3.12` due to a conflict. Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
> 
> ```
> cherry_picker 224c370a3680132997f1e43d20a3b4ca95a060ab 3.12
> ```

This will require a manual backport to 3.12.

**Pull request merged**
