### PR TITLE
[3.12] gh-118507 : Fix `ntpath.isfile` for pipes.

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-118507

### CODE REVIEW

**Comment by nineteendo** [comment]
I think I didn't include unrelated changes. Is it fine to use the C version for `ntpath.isjunction()` and `ntpath.lexists()`?

**Comment by zooba** [comment]
> Is it fine to use the C version for `ntpath.isjunction()` and `ntpath.lexists()`?

Let's revert those, just to minimise the risk of changed behaviour. We can consider backporting them later once we're more confident.

**Comment by nineteendo** [comment]
Done, I also removed the C implementation for these functions to not give anyone ideas...

**Comment by zooba** [comment]
A draft pull request is a good idea.

**Pull request merged**
