### PR TITLE
bpo-41528 Use math module in turtle

### PR DESCRIPTION
**Pull request by TrangOul**
Use angle-related functions from math module instead of reinventing the wheel.

https://bugs.python.org/issue41528

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@TrangOul

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by rhettinger — APPROVED** [review]

**Review by terryjreedy — APPROVED** [review]

**Comment by terryjreedy** [comment]
Travis timed out, restarted with close/open.  Will merge when possible.

**Comment by terryjreedy** [comment]
@vstinner   Travis failed again, 3rd time, but this time only Travis.
Does PR need to be redone?
```
$ xvfb-run make -C Doc/ PYTHON=../python SPHINXOPTS="-q -W -j4" doctest
make: Entering directory '/home/travis/build/python/cpython/Doc'
make[1]: Entering directory '/home/travis/build/python/cpython/Doc'
mkdir -p build
Missing the required blurb or sphinx-build tools.
Please run 'make venv' to install local copies.
Makefile:49: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/travis/build/python/cpython/Doc'
Testing of doctests in the sources finished, look at the results in build/doctest/output.txt
Makefile:127: recipe for target 'doctest' failed
make: *** [doctest] Error 1
make: Leaving directory '/home/travis/build/python/cpython/Doc'
```

**Comment by vstinner** [comment]
> @vstinner Travis failed again, 3rd time, but this time only Travis.

You are a victim of https://bugs.python.org/issue41685 You  can try to rebase your PR on top of master to retrieve https://github.com/python/cpython/commit/a4c4e17f959621ab00a98086af1704fb0c896466 fix.

**Pull request merged**
