### PR TITLE
bpo-34605: childs => children

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue34605

### CODE REVIEW

**Comment by ericvsmith** [comment]
Looks good to me!

**Comment by ericvsmith** [comment]
Forgot: I don't know what they're trying to say with `pliant`, so I suggest leaving it alone.

**Comment by vstinner** [comment]
> Forgot: I don't know what they're trying to say with pliant, so I suggest leaving it alone.

works for me :-)

**Comment by perfide** [comment]
> Forgot: I don't know what they're trying to say with `pliant`, so I suggest leaving it alone.

"pliant children" makes no sense.
It made sense as "pliant slave", a bad joke though.
I think "and its helper functions, like" is easier to understand.

**Pull request merged**
