### PR TITLE
bpo-38506: Fix the Windows launcher's mishandling of 3.10

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue38506

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
This may not be the proper fix.

If this approach is accepted, this PR would still need a news entry.

**Comment by zooba** [comment]
@ZackerySpytz Using the API is the best choice, IMHO, but rather than using the "clever" subtraction approach, let's just use direct comparisons and return -1, 0 or 1. This isn't a tight loop, so readability wins over number of steps.

**Comment by zooba** [comment]
Oh, we probably also want an invariant or neutral locale rather than the current user locale, as we're sorting our own values rather than user-specified values. I don't remember which constant that would be though.

**Comment by csabella** [comment]
@ZackerySpytz and @zooba , should this one move ahead now that we're on 3.10?

**Comment by csabella** [comment]
cc @pablogsal

**Comment by pablogsal** [comment]
I think there are still some unresolved aspects raised by @zooba

**Comment by ZackerySpytz** [comment]
I have updated the PR.

Unfortunately, `Py_UNREACHABLE()` cannot be used in `PC\launcher.c`.

**Review by gvanrossum — APPROVED** [review]
Go for it!

**Pull request merged**
