### PR TITLE
gh-118207: Rename the COMMON_FIELDS macro in funcobject.h and undef it after use

### PR DESCRIPTION
**Pull request by itamaro**
* Issue: gh-118207

### CODE REVIEW

**Comment by encukou** [comment]
Did you consider renaming it to `_Py_COMMON_FIELDS`, so that we also avoid a clash if someone defines it before including `Python.h`?

**Comment by encukou** [comment]
Yeah, undef is good -- with it, other Python header files can use the same name :)

**Comment by itamaro** [comment]
done!

**Review by erlend-aasland — APPROVED** [review]

**Comment by encukou** [comment]
Thank you!

**Pull request merged**
