### PR TITLE
gh-103092: isolate _lsprof

### PR DESCRIPTION
**Pull request by aisk**
The main change is moving the static variables `random_value` and `random_stream` in `rotatingtree.c` to a struct and storing it in the module's state.

Other changes are to pass the struct from the module's state.

* Issue: gh-103092

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Thanks; can you split out the Argument Clinic adaption and contribute that as a separate PR?

**Comment by aisk** [comment]
Sure, see #103092 .

**Comment by aisk** [comment]
Hi @erlend-aasland, I have a new thought. This change is just to isolate these two static variables: https://github.com/python/cpython/blob/1a6e2138773b94fdae449b658a9983cd1fc0f08a/Modules/rotatingtree.c#L11-L12

But as they are the state of a pseudo-random generator, they can be shared between interpreters under a lock. For single interpreter usage, there is no noticeable performance decrease. And this work can be done easily.

I have no idea if this approach is acceptable, or whether we should continue with the previous work. If it does, I can do some benchmarking to see if there is a performance decrease in multiple isolated interpreters usage.

**Comment by erlend-aasland** [comment]
Sounds reasonable. Go ahead!

**Comment by erlend-aasland** [comment]
Superseded by #115301

**Pull request closed without merging**
