### PR TITLE
bpo-30158: Fix deprecation warnings in test_importlib introduced by …

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
…bpo-29576.

### CODE REVIEW

**Comment by vstinner** [comment]
While ignoring the warning on find_module() and find_loader() tests make sense, I'm not sure about tests *using* find_module/find_loader. Should these tests be updated to use find_spec()?

**Comment by serhiy-storchaka** [comment]
I don't know.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
It looks like the whole module is a bit lacking on the `find_spec()` tests and could stand an upgrade. I opened https://bugs.python.org/issue30202 to track that.

**Comment by vstinner** [comment]
"I opened https://bugs.python.org/issue30202 to track that."

Thanks Brett for that ;-)

**Pull request merged**
