### PR TITLE
Cosmetic smtplib changes

### PR DESCRIPTION
**Pull request by scop**
Some cosmetic smtplib changes here. Let me know if you'd like a bpo/news entry or splitting this PR into two.

Automerge-Triggered-By: @maxking

Automerge-Triggered-By: @csabella

### CODE REVIEW

**Comment by maxking** [comment]
I think the changes make sense, I am going to merge these.

Thanks @scop for your contribution!

**Review by maxking — APPROVED** [review]

**Comment by maxking** [comment]
It looks to me like Azure Pipelines PR is stuck :(

**Comment by bitdancer** [comment]
We didn't used to accept cosmetic changes like this unless there were other bugs being fixed in the same area.  Well, the doc change is fine.  The other seems safe as well, so I don't object to merging it, I just want to note that the CPython culture at least used to be "don't make code changes unless you are fixing a bug nearby". :)

**Comment by maxking** [comment]
@bitdancer  I thought that the conversion from 0/1 to False/True would be useful too so I ended up approving the changes :)

**Comment by csabella** [comment]
Added automerge as @maxking had approved this and was just waiting for the CI to pass.

**Pull request merged**
