### PR TITLE
bpo-34855: Correct Windows-native variables

### PR DESCRIPTION
**Pull request by antektek**
Adding an extra S to "EXTERNAL_DIR" (line 27).

https://bugs.python.org/issue34855

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by Mariatta** [comment]
I don't think we should make this change.

**Comment by antektek** [comment]
Hello,

I saw this [issue](https://bugs.python.org/issue34855) concerning the following file : [find_python.bat](https://github.com/python/cpython/blob/master/PCbuild/find_python.bat).
I think it is just a spelling mistake but it is possible that I misunderstand the issue.

**Comment by Mariatta** [comment]
In that case, please include the issue number in the PR title, so this PR is linked to the issue correctly. I.e. the PR title should have started with "bpo-34855: ..."
I'll let @python/windows-team to take it from here.

**Comment by forskning** [comment]
https://github.com/python/cpython/commit/68d663cf85d1ac5eaf83482eed39c0a6f8093601
committed Jul 17, 2017

a Member added to https://bugs.python.org/issue34855

versions: + Python 3.6, Python 3.7
nosy: + paul.moore, tim.golden, zach.ware, steve.dower

seems like someone on the Nosy List should attend to the changes where indicated

by the way, as "Report Tracker Problem" from the python bug tracker webpage is now hyperlinked to a GitHub address, someone might identify if any of the non-highlighted fields on the python bug tracker registration page are factually required (in order to receive the confirmation e-mail), and, if so, change those fields to highlighted

**Comment by forskning** [comment]
no clarification has been presented on the correctness on line 11 from

https://github.com/python/cpython/blob/master/.azure-pipelines/windows-steps.yml

**Comment by forskning** [comment]
I believe https://github.com/python/cpython/commit/0cd6391fd890368ea1743dac50c366b42f2fd126 created windows-appx-test.yml

Which commit created windows-steps.yml?

@zooba

**Comment by forskning** [comment]
in the extracted download cpython-3.6.8.zip

EXTERNAL_DIR appears in the .vsts directory

**Comment by forskning** [comment]
if modification of the additional two files

windows-appx-test.yml
windows-steps.yml
 
is pursued, maybe the issue should be renamed to

bpo-34855: Correct Windows-native variables

S.D. labeled issue34855 "easy" on the Python bug tracker

its not urgent, and can be postponed until the 1st quarter of 2019

I'd wait for a clarification from S.D. on the cited .yml files' content

**Comment by antektek** [comment]
I changed the title of the merge request just in case of.

**Comment by forskning** [comment]
@antektek

bedevere-bot seems to be without manners, adding hyperlinks invariably to any bugs python org issues

**Comment by zooba** [comment]
Yes, updating those two YAML files would be correct. (Though not really necessary for correct functionality, it'll help avoid the confusion of using incorrect variables.)

**Comment by zooba** [comment]
Marking this as un-NEWSworthy, since it doesn't have any impact on end-users (even those who are building from source 99% of the time).

**Comment by forskning** [comment]
I believe https://github.com/python/cpython/commit/0d8f83f59c8f4cc7fe125434ca4ecdcac111810f created the following.

.vsts\windows-buildbot.yml
.vsts\windows-pr.yml

I'd wait for a clarification from S.D. on the cited .yml files' content.

**Comment by forskning** [comment]
The OS-windows label could be added.

**Comment by zooba** [comment]
Looks great to me. It might be time to try updating the build output location in the Pipelines builds to outside the source tree, as I think we can successfully run tests there now. But I'll give that a go.

**Comment by forskning** [comment]
in 3.6.x is PCbuild/find_python.bat going to be corrected

in >=3.6.7 are .azure-pipeline files to be corrected

https://github.com/python/cpython/pull/11177#issuecomment-452179793

in 3.6.6. are the .vsts files to be modified

https://bugs.python.org/issue34855 has been closed

**Comment by forskning** [comment]
https://bugs.python.org/issue34855

mentions 3.6 but has been closed

absent any backport to that branch

is a backport needed for 3.6

**Comment by forskning** [comment]
bpo-34855: lists 3.6

the needs backport to 3.6 label should be added

**Comment by forskning** [comment]
@zooba if no one is intending to pursue the backport to 3.6 I suppose this issue could be closed

**Comment by zooba** [comment]
Let's see if the tag works.

**Comment by zooba** [comment]
No, guess not. I'll close it then :)

**Comment by zooba** [comment]
It's already closed. Please try and avoid commenting on resolved issues, and particularly on pull requests - it just creates noise that distracts us from helping actual contributinos.

**Pull request merged**
