### PR TITLE
gh-102795: Fix use of poll in test_epoll's test_control_and_wait

### LINKED ISSUE #102795: test_epoll.test_control_and_wait flakes from improper poll() usage
# Bug report

test_epoll.test_control_and_wait can flake. In the test we wait for events on two file descriptors. This is done in a single call to select.epoll's poll() function. However, it is valid for the OS to return only one event via poll() and the next via a subsequent call to poll(). This rarely happens, but it can cause the test to fail despite properly functioning polling.

# Your environment

- CPython versions tested on: 3.10.2
- Operating system and architecture: Linux 5.19.11 and gVisor

### Linked PRs
* gh-102796
* gh-104173

### PR DESCRIPTION
**Pull request by kevinGC**
This test can fail unnecessarily. In the test we wait for events on two file descriptors. This is done in a single call to select.epoll's poll() function. However, it is valid for the OS to return only one event via poll() and the next via a subsequent call to poll(). This rarely happens, but it can cause the test to fail despite properly functioning polling.

Instead, we poll a second time when necessary.

Fixes #102795.

* Issue: gh-102795

### CODE REVIEW

**Comment by arhadthedev** [comment]
@vstinner (as a committer into `Modules/selectmodule.c` the changed test belongs to)

**Comment by vstinner** [comment]
Hum, maybe loop on calling this function until it returns even events? Maybe loop on ``test.support.busy_retry(test.support.SHORT_TIMEOUT)`` to fail if it takes too long.

**Comment by kevinGC** [comment]
Updated, PTAL.

**Comment by kevinGC** [comment]
Hey, anything I can do to help move this?

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
I didn't backport the fix since Python 3.11 doesn't have busy_wait().

**Pull request merged**
