### PR TITLE
gh-93649: Split memory and docstring tests from _testcapimodule.c

### PR DESCRIPTION
**Pull request by erlend-aasland**
- gh-93649: Split docstring from _testcapimodule.c
- gh-93649: Splic memory tests from _testcapimodule.c

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Should we add tracemalloc tests to `Modules/_testcapi/mem.c`?

**Review by vstinner — APPROVED** [review]
LGTM.

I suggest to rename "mem.c" to "pymem.c", since most tests are about the "PyMem" API: https://docs.python.org/dev/c-api/memory.html

But I'm also fine with "mem" name, it's up to you.

**Comment by erlend-aasland** [comment]
I think I prefer the "mem" name, but I'm not sure it matters much really. What do you think about including the tracemalloc tests?

**Comment by erlend-aasland** [comment]
> I think I prefer the "mem" name, but I'm not sure it matters much really. What do you think about including the tracemalloc tests?

We can add the tracemalloc tests later if we find out they should live in `Modules/_testcapi/mem.c`

**Comment by sobolevn** [comment]
@erlend-aasland can you please review my fix of this failure? It happens for each PR right now :(

Link: https://github.com/python/cpython/pull/99519

**Pull request merged**
