### PR TITLE
bpo-40419: timeit CLI docs now mention 1,2,5,10,... trials instead of powers of 10

### PR DESCRIPTION
**Pull request by sjvrijn**
Docs updated both in the `Lib/timeit.py` and `Doc/library/timeit.rst` files

https://bugs.python.org/issue40419

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@sjvrijn

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by remilapeyre — APPROVED** [review]
Hi @sjvrijn, thanks for fixing the docs. Please sign the CLA, it may not be necessary for this change but you will need it if you want to contribute more significant changes in the future :)

**Comment by sjvrijn** [comment]
Hi @remilapeyre, the CLA has been signed. Is there anything else I forgot?

**Comment by remilapeyre** [comment]
Hi @sjvrijn, everything's good then 👍 . 

Now a core developer will make a second round of review and will either merge your PR or ask for some changes. There is a lot of PRs to review so it may take some time thought.

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
:+1: Thank you for your report and PR Sander!

**Pull request merged**
