### PR TITLE
gh-109575: Don't export -fsanitize compiler options

### PR DESCRIPTION
**Pull request by vstinner**
When Python is configured to use ASAN, MSAN or UBSAN sanitizer, with "./configure --with-address-sanitizer" for example, compiler and linker flags for sanitizers are no longer exported to third party C extensions. Add flags to CFLAGS_NODIST and LDFLAGS_NODIST, instead of BASECFLAGS and LDFLAGS.

Makefile.pre.in: PY_LDFLAGS_NOLTO now uses PY_LDFLAGS_NODIST, instead of LDFLAGS_NODIST, and add CONFIGURE_LDFLAGS_NOLTO after PY_LDFLAGS_NODIST.

* Issue: gh-109575

### CODE REVIEW

**Comment by vstinner** [comment]
On the main branch, with the bug:

```
$ ./configure --with-pydebug --with-address-sanitizer CC=clang 
$ grep fsanitize Makefile
BASECFLAGS=	-fsanitize=address -fno-omit-frame-pointer  -fno-strict-overflow -Wsign-compare -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer
CONFIGURE_LDFLAGS=	-fsanitize=address 
```

With the fix, the flags are not longer exported:

```
$ ./configure --with-pydebug --with-address-sanitizer CC=clang 
$ grep fsanitize Makefile
CONFIGURE_CFLAGS_NODIST= -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -fsanitize=address -fno-omit-frame-pointer
CONFIGURE_LDFLAGS_NODIST= -fsanitize=address
```

**Comment by vstinner** [comment]
cc @gpshead @erlend-aasland

**Comment by vstinner** [comment]
Test PY_LDFLAGS_NOLTO on building ``_bootstrap_python``:

```
./configure --with-address-sanitizer --with-lto
make
```

Logs:

```
gcc   -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -fsanitize=address  -fno-lto -o _bootstrap_python (...)
```

``-fno-lto`` option is passed as expected.

**Comment by gpshead** [comment]
this change makes sense _if_ we want to do this.  it wasn't clear what "right" behavior was to me for this, see my comment on the Issue.  (i'm happy either way myself)

**Comment by vstinner** [comment]
I thought that it was a mistake, but apparently, some people actually want this behavior. I'm mostly using ASAN, but for ASAN, it seems to be the expected behavior. So I just close my PR :-)

If someone wants to adjust the code for other sanitizers, please go ahead!

**Pull request closed without merging**
