### PR TITLE
gh-118527: Intern code name and filename on default build

### PR DESCRIPTION
**Pull request by colesbury**
Interned and non-interned strings are treated differently by `marshal`, so be consistent between the default and free-threaded build.

* Issue: gh-118527

### CODE REVIEW

**Review by brandtbucher — APPROVED** [review]

**Comment by brandtbucher** [comment]
So to clarify, the risk here is that the default build will "leak" a bunch of names if code is created dynamically (by using `exec` or whatever), each time using a different name, then freed?

How significant is the scaling improvement on the free-threading build?

**Comment by brandtbucher** [comment]
Honestly, I'm not too worried since we already intern names and constants and stuff.

**Comment by markshannon** [comment]
Do you have any numbers on how many extra strings this will intern?

**Comment by colesbury** [comment]
> How significant is the scaling improvement on the free-threading build?

It's critical for some common patterns, although it's not the only critical bottleneck (there are other remaining bottlenecks too).

For example:

```python
def run_in_parallel():
    def foo():
        pass
    return foo
```

If `run_in_parallel()` is run from multiple threads concurrently, then the construction of different `foo` functions would be a bottleneck due to the functions taking their names from the code object. (The names are refcounted). 

>  Do you have any numbers on how many extra strings this will intern?

Running `test_threading` (chosen arbitrarily) I see the number of interned unicode strings change:

before this PR: 19419
after this PR: 19721

(in the default build)

**Comment by markshannon** [comment]
> Running `test_threading` (chosen arbitrarily) I see the number of interned unicode strings change:
> 
> before this PR: 19419 after this PR: 19721
> 
> (in the default build, as reported by `sys.getunicodeinternedsize()`)

The increase from 19419 to 19721 doesn't seem so bad, but it depends on the baseline.
As an extreme example, if 19418 of those are interned by `python -c "pass"` then it is an increase from 1 to 300 which is bad.

Can you get numbers for something like the mypy benchmark or a similar "realistic" program?

**Comment by colesbury** [comment]
`./python -m mypy --config-file Lib/test/libregrtest/mypy.ini`
before: 25643
after: 25789

**Comment by colesbury** [comment]
And `./python -c "pass"`
before: 3926
after: 4070

**Pull request merged**
