### PR TITLE
gh: [Lib/idlelib] use $XDG_CONFIG_HOME or ~/.config for idle use configurations

### PR DESCRIPTION
**Pull request by aryalaadi**
better to follow XDG standards, I also dont want a messy home directory.

### CODE REVIEW

**Comment by aisk** [comment]
I think this is not a trivial change, so it requires an issue as the [devguide requires](https://devguide.python.org/getting-started/pull-request-lifecycle/#quick-guide).

**Comment by aryalaadi** [comment]
> I think this is not a trivial change, so it requires an issue as the [devguide requires](https://devguide.python.org/getting-started/pull-request-lifecycle/#quick-guide).

ok, ill look into later when im free

**Comment by aisk** [comment]
And I found there is already an existing issue which has discussed changing the configuration location: #51424. Maybe this can provide some help.

**Comment by terryjreedy** [comment]
Sorry, but I am rejecting this.  I have no `XDG_CONFIG_HOME` so this is obviously not standard even on Windows.   I do have a `.config/git` in my personal account with git installed, but no .config in other user directories, so it also not standard, also at least not on Windows.  I presume git made the .config directory.  Not a bad idea is Microsoft had such, but MS has other ideas.   Quite aside from this, putting .idlerc *anywhere* but where it has been for 24 years, without real issue, breaks compatibility with all previous releases of all versions.  There was also a Windows-specific IDLE issue, I believe closed, to move .idlerc on Windows under the normally hidden $APPDATA% directory.  This had the same back-compatibility issue, as well as a visibility issue for a file users need to be able to access.

**Pull request closed without merging**
