### PR TITLE
gh-113317: Argument Clinic: Add libclinic.function

### PR DESCRIPTION
**Pull request by vstinner**
* Move Module, Class, and Function ~~and Parameter~~ classes to a new libclinic.function module.
* Move VersionTuple and Sentinels to libclinic.utils.

* Issue: gh-113317

### CODE REVIEW

**Comment by erlend-aasland** [comment]
> Move Module, Class, Function and Parameter classes to a new libclinic.function module.

This naming does not make sense to me. Why would *class*, *module* and *parameter* live in a file called `function.py`?

**Comment by vstinner** [comment]
> This naming does not make sense to me. Why would class, module and parameter live in a file called function.py?

Do you want to propose a different name? Or have one class per file?

**Comment by erlend-aasland** [comment]
The commit message says:

> Move Module, Class, Function and Parameter classes to a new libclinic.function module.

But this is not true; `Parameter` was not moved; it was left out of the PR.

**Comment by vstinner** [comment]
> But this is not true; Parameter was not moved; it was left out of the PR.

Parameter was moved to libclinic.function in the merged commit, no? Search for `class Parameter:` in https://github.com/python/cpython/commit/b1236a44101410e28a69ec6df5f29e7a5f2eb0b2. Well, I can be wrong.

**Comment by erlend-aasland** [comment]
No, you're right; I misread it in-between all the changes. Sorry!

**Pull request merged**
