### PR TITLE
bpo-17188: DOC: Document 'from None' in raise statement

### PR DESCRIPTION
**Pull request by csabella**
Prepare PR for patch by thomir to document 'from None' in raise statement.

### CODE REVIEW

**Comment by terryjreedy** [comment]
The patch was written by Dennis Mårtensson (and Nick Coughlin in message) with edits by Nitika Agarwal and Thomi Richards. All have signed the CLA.  Dennis should be credited as the 'original author' and added to Misc/ACKS.

**Review by terryjreedy — APPROVED** [review]
I verified the 1/0 message change, new example, and 3.3 notes (the last from Nick's message) and then rebuilt docs with patch.  Web page looks good.

**Comment by terryjreedy** [comment]
Nick, I requested review because my rst is rusty.  But I decided to check by download and build.  I think this is ready to merge when travis is done.

**Review by ncoghlan — APPROVED** [review]
Looks good to me. Adding the label for a 3.6 backport so the default online docs get updated.

**Comment by terryjreedy** [comment]
Nick, I cannot do backports yet so I leave that to you.

**Comment by Mariatta** [comment]
@csabella Can you do the backport? Thanks :)
The commit hash is 763557eac06ba60d7c5133e4f80df8870d8f917e

**Pull request merged**
