### PR TITLE
bpo-11191: skip the distutils test 'test_search_cpp' when AIX and not gcc as compiler, etc.

### PR DESCRIPTION
**Pull request by aixtools**
skip the distutils test 'test_search_cpp' when AIX and not gcc as compiler
    as xlc et al do not support -o (as output). 'cpp' output is ALWAYS to stdout
also add additional logic Lib/test/__init__.py for when
    sysconfig.customize_compiler returns [] rather than None
add the additional argument '-C' for AIX xlc cpp processing so comments are
    included in the cpp output rather than replaced by a single ' ' (space) char.

https://bugs.python.org/issue11191

### CODE REVIEW

**Comment by aixtools** [comment]
A) This 'fixes' the distutils test 'test_search_cpp' by skipping it when the compiler is not gcc. When the argument -E is used, the argument -o is not accepted.
B) Even though the test is skipped, the processing of the 'pp_args' is corrected (-o is not added, -C is added so that comments are included in the output)
C) There was an additional error that caused 6 tests to fail (when sysconfig.customize_compiler returned [] rather than None). This is also corrected.

I am not claiming that this is the best solution. However, it does show where work needs to be done. Improvements are welcomed.

**Comment by aixtools** [comment]
Closing the PR - as the merge with current master creates a lot of noise. Will resubmit in a cleaner form.

**Comment by trudeaun** [comment]
IBM has just released a new [XL C/C++ for AIX compiler, V16.1](https://www.ibm.com/developerworks/community/blogs/572f1638-121d-4788-8bbb-c4529577ba7d/entry/New_XL_C_C_and_Fortran_for_AIX_compilers_available_today_V16_1?lang=en). The `-E` option has been updated so that the combination of `-E -o` stores the preprocessed result in the file specified by `-o`. See more details on [Knowledge Center](https://www.ibm.com/support/knowledgecenter/SSGH3R_16.1.0/com.ibm.xlcpp161.aix.doc/compiler_ref/opt_e_upper.html).

**Comment by aixtools** [comment]
Nice. That will make it go away for anyone with the latest compiler - so now the patch would need to be even more specific - like many macos ones, where the version of the os is important.
However, as a private person (hobbyist) it will never work for me. I am, it seems, many versions behind (or did they finally sync the Fortran and XLC version numbers?

Sigh. Mustard after the meal has been eaten.

**Comment by trudeaun** [comment]
Starting in V16.1, the Fortran and XLC version numbers are finally synched up, so V16.1's predecessor is V13.1.3. Which version are you on currently? If you have an active license for an older version, you should be able to upgrade to the latest version without charge.

**Pull request closed without merging**
