### PR TITLE
Redundant expression

### PR DESCRIPTION
**Pull request by gaurav1086**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@gaurav1086

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by eamanu — APPROVED** [review]
LGTM. I think this don't change the functionality of the functions. 

But I would like to hear a core dev :)

**Comment by eamanu** [comment]
@gaurav1086 please, sign CLA.

**Comment by gaurav1086** [comment]
Hi @eamanu, thanks for the review. I have signed the CLA and also received the copy of it. Not sure why its showing as 'not signed'.

**Comment by eamanu** [comment]
@gaurav1086 Oh ok. we just need wait :)

**Comment by tiran** [comment]
The files are taken from the [blake2 reference implementation](https://github.com/BLAKE2/BLAKE2/tree/20160619/ref). I don't want to deviate from upstream. Any good compiler will know how to optimize this line anyway.

**Pull request closed without merging**
