### PR TITLE
Remove ')'

### PR DESCRIPTION
**Pull request by marethyu**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Marethyu12

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by eamanu — APPROVED** [review]
The NEWS can be skipped

**Review by aeros — APPROVED** [review]
Thanks for the PR and welcome @Marethyu12! LGTM.

Since this PR involves a simple change that could arguably be fixed with auto-correct, I think we can omit the CLA. But if you do sign it, the amount of time it takes for the PR to me merged will likely be reduced. In order to update the status, check the [CLA assistant](https://check-python-cla.herokuapp.com/) 24-48 hours after submitting the signed CLA to the PSF.

**Comment by aeros** [comment]
I'll close and re-open the PR to restart the tests. The Ubuntu failure is definitely unrelated, as it failed in the "Install Dependencies" stage.

**Review by remilapeyre — APPROVED** [review]

**Comment by terryjreedy** [comment]
I will merge trivial patches that do not contain any creative composition and which therefore could not be copyrighted.  Otherwise, I will not.

**Comment by terryjreedy** [comment]
Tests for 3.8 backport failed in Sphinx and ctypes.  Rerunning with new backport.

**Pull request merged**
