### PR TITLE
bpo-46712: share more global strings in deepfreeze

### PR DESCRIPTION
**Pull request by kumaraditya303**
https://bugs.python.org/issue46712

(#90868)

```console
@kumaraditya303 ➜ /workspaces/cpython (more-strings) $ cat Python/deepfreeze/deepfreeze.c | grep _Py_STR | wc -l
159
```

### CODE REVIEW

**Review by gvanrossum — COMMENTED** [review]
deepfreeze.py changes are okay, but I need @ericsnowcurrently to review the rest.

**Comment by kumaraditya303** [comment]
@gvanrossum Any update on this? Is this in Eric's review queue?

**Comment by gvanrossum** [comment]
@ericsnowcurrently Please review.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Comment by ericsnowcurrently** [comment]
Thanks, @kumaraditya303!  Sorry for the delay.

**Pull request merged**
