### PR TITLE
gh-123596: Fixed return None when getattr the sys.tracebacklimit.

### PR DESCRIPTION
**Pull request by rruuaanng**
* Issue: gh-123596

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
Please add tests for this change.

**Comment by rruuaanng** [comment]
Please let me finish the work at hand. I'm about to add everything ：）

**Comment by vstinner** [comment]
> Please let me finish the work at hand. I'm about to add everything ：）

Please don't create a pull request until it's ready according to you. Otherwise people might want to review it without knowing that it's incomplete.

**Comment by rruuaanng** [comment]
I see. Maybe I should respond to your request quickly. So I created a draft pull. I hope no one will misunderstand. I'm working this.

**Comment by rruuaanng** [comment]
I'm not sure it's worth adding the test. It seems like
https://github.com/python/cpython/blob/7d88140d5299bd086434840db66ede8ccd01a688/Lib/test/test_traceback.py#L3006-L3015
already exists. And his handling of tracebacklimit is really only 1000 when it's undefined.

**Comment by rruuaanng** [comment]
And this change passes the existing test for `tracebacklimit`. To ensure accuracy, I verified that frame_gen is empty by inserting a `print` into `_extract_from_extended_frame_gen`, and it actually behaves in accordance with the original logic of the program.

test code:
```
def f():
    f()

f()
```
changed diff:
```
--- a/Lib/traceback.py
+++ b/Lib/traceback.py
@@ -455,7 +455,7 @@ def _extract_from_extended_frame_gen(klass, frame_gen, *, limit=None,
         # information is not available.
         builtin_limit = limit is BUILTIN_EXCEPTION_LIMIT
         if limit is None or builtin_limit:
-            limit = getattr(sys, 'tracebacklimit', None)
+            limit = getattr(sys, 'tracebacklimit', 1_000)
             if limit is not None and limit < 0:
                 limit = 0
         if limit is not None:
@@ -466,7 +466,8 @@ def _extract_from_extended_frame_gen(klass, frame_gen, *, limit=None,
                 frame_gen = itertools.islice(frame_gen, limit)
             else:
                 frame_gen = collections.deque(frame_gen, maxlen=-limit)
-
+        for frame in frame_gen:
+            print(frame)
         result = klass()
         fnames = set()
```
changed output:
```
(<frame at 0x000001D8F6E1AF00, file 'E:\\code\\github\\cpython\\alpha\\cpython-main\\Users\\test.py', line 4, code f>, (4, 4, 4, 7))
Traceback (most recent call last):
  File "E:\code\github\cpython\alpha\cpython-main\Users\test.py", line 6, in <module>
    f()
    ~^^
  File "E:\code\github\cpython\alpha\cpython-main\Users\test.py", line 4, in f
    f()
    ~^^
  File "E:\code\github\cpython\alpha\cpython-main\Users\test.py", line 4, in f
    f()
    ~^^
  File "E:\code\github\cpython\alpha\cpython-main\Users\test.py", line 4, in f
    f()
    ~^^
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```
When I remove `1_000`
```
index 0fe7187..1b5f4eb 100644
--- a/Lib/traceback.py
+++ b/Lib/traceback.py
@@ -466,7 +466,8 @@ def _extract_from_extended_frame_gen(klass, frame_gen, *, limit=None,
                 frame_gen = itertools.islice(frame_gen, limit)
             else:
                 frame_gen = collections.deque(frame_gen, maxlen=-limit)
-
+        for frame in frame_gen:
+            print(frame)
         result = klass()
         fnames = set()
         for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
```
For the above test code
```
(<frame at 0x000001B713E3B270, file 'E:\\code\\github\\cpython\\alpha\\cpython-main\\Users\\test.py', line 4, code f>, (4, 4, 4, 7))
(<frame at 0x000001B713E3B1C0, file 'E:\\code\\github\\cpython\\alpha\\cpython-main\\Users\\test.py', line 4, code f>, (4, 4, 4, 7))
(<frame at 0x000001B713E3B110, file 'E:\\code\\github\\cpython\\alpha\\cpython-main\\Users\\test.py', line 4, code f>, (4, 4, 4, 7))
(<frame at 0x000001B713E3B060, file 'E:\\code\\github\\cpython\\alpha\\cpython-main\\Users\\test.py', line 4, code f>, (4, 4, 4, 7))
(<frame at 0x000001B713E3AFB0, file 'E:\\code\\github\\cpython\\alpha\\cpython-main\\Users\\test.py', line 4, code f>, (4, 4, 4, 7))
(<frame at 0x000001B713E3AF00, file 'E:\\code\\github\\cpython\\alpha\\cpython-main\\Users\\test.py', line 4, code f>, (4, 4, 4, 7))
RecursionError: maximum recursion depth exceeded
```

**Comment by rruuaanng** [comment]
I actually feel like this change could probably be merged with the PR that adds `tracebacklimit`, since it seems like changing `traceback.py` separately is a bit abrupt (mainly because I'm confused about the test, I'm not sure if I need to add a duplicate test, because changing it to 1000 doesn't seem to have any effect on the test, because when `tracebacklimit` doesn't exist in the test code, its value will be 1000).

**Comment by rruuaanng** [comment]
I have added a test that checks if the call stack is 1000. Can it skip NEWS? It seems that this change is implicit.

**Comment by rruuaanng** [comment]
I'll close this PR and hand the change over to the original author for fix.

**Pull request closed without merging**
