### PR TITLE
bpo-38704: Prevent installation on unsupported Windows versions

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue38704

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
I guess `Py_WINVER` et al. should be updated as well.

There was also some discussion on https://bugs.python.org/issue32592 w.r.t. dropping Windows < 8.1.

**Comment by zooba** [comment]
@ZackerySpytz I think you're missing some changes to `msi\bundle\Default.wxl` for the updated string references.

Have you been able to build the MSI? It should pull down any dependencies automatically and be fairly straightforward if you run the tools/msi/build.bat script.

**Comment by csabella** [comment]
@ZackerySpytz, please address the code review.  Thanks!

**Comment by zooba** [comment]
Closed/reopened to run the MSI checks, which I added after this PR was created.

**Comment by zooba** [comment]
We still need the string added to `Tools\msi\bundle\Default.wxl`. It will compile fine because it's a runtime reference to the string - we'll only see a failure when run on a Win<=8 system.

**Comment by ZackerySpytz** [comment]
I have updated `Tools\msi\bundle\Default.wxl`.

**Comment by ambv** [comment]
This missed the boat for inclusion in Python 3.9 which accepts security fixes only as of today.

**Comment by zooba** [comment]
Looks like after I resolved the conflicts, it was because we already had a good fix for this 😆 Oh well, no harm done. I won't backport

**Pull request merged**
