### PR TITLE
gh-125008: Fix `tokenize.untokenize` roundtrip for `\n{{`

### PR DESCRIPTION
**Pull request by tomasr8**
I'm not sure if this is the best way to fix this issue so I'm open to alternatives :)

* Issue: gh-125008

### CODE REVIEW

**Comment by wyattscarpenter** [comment]
Might as well add test cases for `\` alone, while you're at it. Hope this is helpful, if you do decide to do that:

```py3
        self.check_roundtrip(r"rf'\t{{foo}}'")
        self.check_roundtrip(r"f'\\t{{foo}}'")
        self.check_roundtrip(r"rf'\\\t{{foo}}'")
        self.check_roundtrip(r"f'\\\\t{{foo}}'")
```
(some of them are raw to avoid `SyntaxWarning: invalid escape sequence '\{'`.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
The changes LGTM. Thanks a lot for the catch and the fix @tomasr8!

I will wait if you want to address @wyattscarpenter suggestion and we can land afterwards

**Comment by pablogsal** [comment]
This will need backport to 3.12 and 3.13

**Comment by tomasr8** [comment]
Thanks for the suggestion @wyattscarpenter ! I added more tests with raw strings :)

**Comment by wyattscarpenter** [comment]
Sorry, I bungled the code example I was trying to give you. I actually meant
```py3
        self.check_roundtrip(r"rf'\{{foo}}'")
        self.check_roundtrip(r"f'\\{{foo}}'")
        self.check_roundtrip(r"rf'\\\{{foo}}'")
        self.check_roundtrip(r"f'\\\\{{foo}}'")
```
\\ currently suffers from the same defect of the disappearing {, like \\, but since they're sort of a special case they might be worth testing for explicitly. Or not; they aren't that special of the case so maybe it doesn't matter that much.

**Comment by tomasr8** [comment]
Added more tests :) f-string are tricky so I think it's better to have more tests anyway

**Comment by pablogsal** [comment]
Landing! Great job

**Pull request merged**
