### PR TITLE
bpo-43669: Drop the internal _sha3 module per PEP 644

### PR DESCRIPTION
**Pull request by illia-v**
https://www.python.org/dev/peps/pep-0644/#sha-3

Closes https://github.com/python/cpython/pull/24601

https://bugs.python.org/issue43669

### CODE REVIEW

**Review by tiran — CHANGES_REQUESTED** [review]
This changeset needs a new, dedicated BPO and a thorough discussion.

**Comment by tiran** [comment]
I haven't removed the _sha3 and _blake2 modules yet on purpose. I recommend that we wait two releases and drop them in 3.12.

**Comment by illia-v** [comment]
> I haven't removed the _sha3 and _blake2 modules yet on purpose. I recommend that we wait two releases and drop them in 3.12.

It may be prudent enough, but it's worth documenting this somewhere :)
Based on https://github.com/python/cpython/pull/24601#issuecomment-830770550 I thought that you didn't have any arguments against dropping `_sha3` in 3.10.

**Comment by tiran** [comment]
Greg and I came to the conclusion that the hashlib module must provide sha3 even when Python is built without OpenSSL. In bpo-47098 GH-32060 I replaced the large KCP with a tiny implementation.

**Pull request closed without merging**
