### PR TITLE
bpo-42955: Remove sub-packages from sys.stdlib_module_names

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue42955

### CODE REVIEW

**Comment by vstinner** [comment]
> Tests / Ubuntu (pull_request) Failing 

This is unrelated to my PR, `FAIL: test_identify (tkinter.test.test_ttk.test_widgets.ComboboxTest)`.
https://bugs.python.org/issue42507

**Comment by vstinner** [comment]
cc @stevendaprano @pablogsal

**Comment by vstinner** [comment]
@gaborbernat @warsaw @gpshead: What do you think of this change?

**Comment by gpshead** [comment]
To me, this makes sense. The use case we've had at work for an official list of what modules are in the standard library has been in code health tooling.  Sorting stdlib imports before others, etc.  Only the top level package names are important there.

**Review by gpshead — APPROVED** [review]

**Comment by vstinner** [comment]
Merged, thanks @gpshead.

Well, I wasn't fully comfortable with the half-baken trade-off: include sub-packages but not sub-modules. IMO the new API is now more consistent: only list main packages.

**Pull request merged**
