### PR TITLE
[3.11] GH-96636: Remove all uses of NOTRACE_DISPATCH (GH-96643)

### PR DESCRIPTION
**Pull request by markshannon**
Co-authored-by: Brandt Bucher <brandtbucher@gmail.com>
(cherry picked from commit aa3b4cf779b3dddb84e094879b91703354910d8c)

* Issue: gh-96636

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Whoops this probably should wait for @pablogsal before it gets merged.

**Comment by markshannon** [comment]
@pablogsal?

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
It would be great if we can quickly check that the coverage test suite passes or doesn't fail more with this PR before landing.

Otherwise, LGTM, land when ready 👍

**Comment by markshannon** [comment]
This shouldn't impact coverage.py. This is for weird code that turns on tracing in finalizers, weakrefs or asynchronously.

I'm fairly sure coverage.py doesn't do any of those things. @nedbat?

**Comment by nedbat** [comment]
Coverage.py doesn't do any of those weird things :)  Also, I now have nightly build testing every day, so we'll hear soon if this broke something.

**Comment by pablogsal** [comment]
Ok, let's merge it then 👍

**Comment by neonene** [comment]
An extra `DISPATCH()` macro has been added accidentally, which has no harm.
https://github.com/python/cpython/blob/46f791d2633d496df0d866206493a6936d64905e/Python/ceval.c#L3582-L3586

**Comment by brandtbucher** [comment]
Nice catch. I'll open a PR to fix.

**Pull request merged**
