### PR TITLE
[3.9] gh-122905: Sanitize names in zipfile.Path. (GH-122906)

### PR DESCRIPTION
**Pull request by jaraco**
* Issue: gh-122905

### CODE REVIEW

**Comment by ajayk** [comment]
Can this be merged based on https://github.com/python/cpython/pull/123160#issuecomment-2305908867

**Comment by jaraco** [comment]
Yes, I think so. @ambv any objections?

**Comment by jaraco** [comment]
This change is superseded by another in the works (#123354). It needs to be merged so the backports of that fix can supersede this one.

**Comment by jaraco** [comment]
On second thought, it can be superseded without being merged.

**Pull request closed without merging**
