### PR TITLE
bpo-41515: prevent get_type_hints from raising KeyError

### PR DESCRIPTION
**Pull request by efahl**
https://bugs.python.org/issue41515

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@efahl

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by gvanrossum — APPROVED** [review]
Sorry for sitting on this so long. Can you prepare a short blurb too?

**Comment by gvanrossum** [comment]
Also please rebase, it might fix the macOS test failure.

**Comment by tirkarthi** [comment]
I have created https://github.com/python/cpython/pull/25352 with attribution to author since I don't have permission to update the PR. Thanks.

**Comment by gvanrossum** [comment]
Closed in favor of GH-25352.

**Pull request closed without merging**
