### PR TITLE
asyncio.streams.open_connection remove loop from docstring

### PR DESCRIPTION
**Pull request by tgbugs**
asyncio.streams.open_connection no longer accepts loop as a keyword argument and providing it causes:
TypeError: BaseEventLoop.create_connection() got an unexpectedkeyword argument 'loop' therefore remove it from the docstring.

### CODE REVIEW

**Comment by tgbugs** [comment]
This is a trivial change so if someone who has signed the CLA wants to submit it I don't mind.

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
@tgbugs: Could you please sign the CLA? It would really be much easier that way -- I can't merge without it.

**Comment by tgbugs** [comment]
@gvanrossum CLA signed.

**Comment by gvanrossum** [comment]
@tgbugs I just realized (seconds after merging :-) that a similar change needs to be applied to open_connection(). Are you interested in taking that on, now that you've got the CLA signed and all?

**Comment by tgbugs** [comment]
Happy to, but won't be able to get to it until late next week of that
matters.

**Comment by gvanrossum** [comment]
@tgbugs No problem, take your time.

**Pull request merged**
