### PR TITLE
[3.11] Fix v3.11.0 release merge problems

### PR DESCRIPTION
**Pull request by pablogsal**
When merging the v3.11.0 tag into 3.11, some files were incorrectly updated and some others were not properly deleted.

Automerge-Triggered-By: GH:pablogsal

### CODE REVIEW

**Review by ned-deily — APPROVED** [review]

**Comment by CAM-Gerlach** [comment]
The docs build is failing because during the same merge, the ref target labels at the top of two of the sections got doubled up, which I noticed and had already prepped a PR, #98625 , before I saw this one. You can merge it first, or feel free to cherry-pick or directly make the change here if you prefer and close that one.

**Comment by pablogsal** [comment]
> #98625

Thanks, i think I prefer to fix it here

**Comment by CAM-Gerlach** [comment]
@pablogsal FYI, not sure if you saw, but there's another set that commit missed above the pending removal section (looks like the GitHub checks do highlight it)

**Comment by ned-deily** [comment]
Another issue: the blurb items for the PR's cherry-picked into v3.11.0 from the post-rc2 3.11 branch need to be manually deleted as they show up twice, both under v3.11.0 and under "Python next" (see PEP 101 for details).

**Comment by pablogsal** [comment]
> Another issue: the blurb items for the PR's cherry-picked into v3.11.0 from the post-rc2 3.11 branch need to be manually deleted as they show up twice, both under v3.11.0 and under "Python next" (see PEP 101 for details).

These are the ones we need to eliminate:

```
>>> import pathlib
>>> x = open("./Misc/NEWS.d/3.11.0.rst")
>>> p = pathlib.Path("./Misc/NEWS.d/next")
>>> files = list(p.glob("**/*.rst")
>>> [file for file in files if file.read_text() in text]
[PosixPath('Misc/NEWS.d/next/Core and Builtins/2022-09-18-08-47-40.gh-issue-96821.Co2iOq.rst'),
 PosixPath('Misc/NEWS.d/next/Core and Builtins/2020-11-15-02-08-43.bpo-42316.LqdkWK.rst'),
 PosixPath('Misc/NEWS.d/next/Core and Builtins/2022-10-06-02-11-34.gh-issue-97002.Zvsk71.rst'),
 PosixPath('Misc/NEWS.d/next/Core and Builtins/2022-09-05-19-20-44.gh-issue-96587.bVxhX2.rst'),
 PosixPath('Misc/NEWS.d/next/Core and Builtins/2022-09-21-16-06-37.gh-issue-96975.BmE0XY.rst'),
 PosixPath('Misc/NEWS.d/next/Core and Builtins/2022-09-21-14-38-31.gh-issue-96848.WuoLzU.rst'),
 PosixPath('Misc/NEWS.d/next/Core and Builtins/2022-10-03-13-35-48.gh-issue-97752.0xTjJY.rst'),
 PosixPath('Misc/NEWS.d/next/Documentation/2022-05-20-18-42-10.gh-issue-93031.c2RdJe.rst'),
 PosixPath('Misc/NEWS.d/next/Documentation/2022-10-02-10-58-52.gh-issue-97741.39l023.rst'),
 PosixPath('Misc/NEWS.d/next/Security/2022-09-28-17-09-37.gh-issue-97616.K1e3Xs.rst'),
 PosixPath('Misc/NEWS.d/next/Tests/2022-10-20-17-49-50.gh-issue-95027.viRpJB.rst'),
 PosixPath('Misc/NEWS.d/next/Library/2022-05-25-15-57-39.gh-issue-90155.YMstB5.rst'),
 PosixPath('Misc/NEWS.d/next/Library/2022-09-25-23-24-52.gh-issue-97545.HZLSNt.rst'),
 PosixPath('Misc/NEWS.d/next/Build/2022-09-11-14-23-49.gh-issue-96729.W4uBWL.rst'),
 PosixPath('Misc/NEWS.d/next/Windows/2022-10-19-20-00-28.gh-issue-98360.O2m6YG.rst'),
 PosixPath('Misc/NEWS.d/next/Windows/2022-09-29-23-08-49.gh-issue-90989.no89Q2.rst'),
 PosixPath('Misc/NEWS.d/next/Windows/2022-10-19-19-35-37.gh-issue-98414.FbHZuS.rst')]
```

**Comment by CAM-Gerlach** [comment]
### RecursionError: Maximum fixup depth exceeded!

**Pull request merged**
