### PR TITLE
Move change detection to separate workflow in CI

### PR DESCRIPTION
**Pull request by webknjaz**
This is a continuation of the CI refactoring PR series I've been doing.

### CODE REVIEW

**Comment by hugovk** [comment]
It was already in its own job:

image


This PR:

image

Would it be more accurate to say this moves the job to its own workflow + file? 

Benefits:

* Makes the top-level `build.yml` shorter.
* Helps make each bit more modular, separating config.
* Are there other benefits of this change?

Costs:

* This PR does add a net 46 lines of config, mainly passing the outputs from the new job out through the new workflow, though it's not too complex.
* We get another "dummy" reusable workflow showing in the [left menu](https://github.com/python/cpython/actions), with no workflows shown when clicking (although the pinning does help find the important ones, thanks for letting me know about pinning):

image

**Comment by webknjaz** [comment]
> Would it be more accurate to say this moves the job to its own workflow + file?

Yes, you're right. I must've phrased it better.


> Benefits:
> 
>     * Makes the top-level `build.yml` shorter.
> 
>     * Helps make each bit more modular, separating config.
> 
>     * Are there other benefits of this change?

I think these benefits have a significant impact on their own. This also contributes to the separation of the structure / triggers vs. implementation details. In the future, it makes it cleaner to add more jobs (or separate what's in there already) if the need be. I feel like it currently computes several things that aren't necessarily related enough to be in the same job.
My idea is that the top-level workflow structure should be in the main configuration file, and the components would be separate, only interfacing through their inputs/outputs.
It's basically an abstraction layer separation exercise.
Having such predictable structure will also enable us to introduce linting that would keep it consistent and easy to reason about.


> Costs:
> 
>     * This PR does add a net 46 lines of config, mainly passing the outputs from the new job out through the new workflow, though it's not too complex.
> 
>     * We get another "dummy" reusable workflow showing in the [left menu](https://github.com/python/cpython/actions), with no workflows shown when clicking (although the pinning does help find the important ones, thanks for letting me know about pinning):

Yes, you're right. I suppose, we could add names to those reusable workflows with something along the lines of “Don't click”. Combined with pinning the entry-point workflows, that would make it look nicer. Personally, I'm not too worried about these, but I see how some of the points may annoy people.

Additionally, it may make sense to hit GitHub support with a request to hide workflows that only have a `workflow_call` trigger, since it's known that those are never going to have any runs listed.

**Comment by webknjaz** [comment]
@picnixz this also needs backport labels FYI

**Comment by hugovk** [comment]
Yes, I agree on balance this makes it things a bit clearer. Thanks!

**Pull request merged**
