### PR TITLE
Check this

### PR DESCRIPTION
**Pull request by fochoao**
# CPython Latest with some libraries.

It should be in the following format:

CPython Windows Make Alpha 3

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@fochoao

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by tiran** [comment]
We do not include precompiled files and binaries in our source repository.

**Comment by skeeto** [comment]
Could we somehow delete or force-push away the branch associated with this pull request as well as #23752? I maintain a mirror of this repository (`git clone --mirror https://github.com/python/cpython`) and I noticed that my mirror recently more than quadrupled in size. The culprits are #23910 and #23752 since they each introduce large binary files (the biggest being a `.vs/` directory). These are retained as refs `refs/pull/23910/head` and `refs/pull/23752/head`, and so these end up in my mirror. That's a lot of waste for a couple of irrelevant pull requests.

**Comment by fochoao** [comment]
> We do not include precompiled files and binaries in our source repository.

Thanks for saying so.



> Could we somehow delete or force-push away the branch associated with this pull request as well as #23752? I maintain a mirror of this repository (`git clone --mirror https://github.com/python/cpython`) and I noticed that my mirror recently more than quadrupled in size. The culprits are #23910 and #23752 since they each introduce large binary files (the biggest being a `.vs/` directory). These are retained as refs `refs/pull/23910/head` and `refs/pull/23752/head`, and so these end up in my mirror. That's a lot of waste for a couple of irrelevant pull requests.

Yes I noticed the molase of said directory until late, I will keep updating anyway, I am going for CPython 3.10.0a7+, I could keep a project with built binaries, but I prefer to leave the whole tree so it works as it should. Anyways since I see cannot contribute with pre-compiled binaries, it is ok, thanks anyways.

**Pull request closed without merging**
