### PR TITLE
Spelling/Grammar Improvements.

### PR DESCRIPTION
**Pull request by Rimjhim-Dey**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Rimjhim-Dey

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by JulienPalard** [comment]
Is this hacktoberfest spam again?

**Comment by Rimjhim-Dey** [comment]
No! It's not a spam...

**Comment by terryjreedy** [comment]
@Rimjhim-Dey This PR is wrong and violates our error message standard.  It is clearly invalid.  It is one of at least 7 invalid or spam PRs submitted to python/cpython in the last 24 hours.  (I checked them all.)  I suspect that you did not read our devguide.  There have been others on other python repositories.   Python is one of multiple projects attacked this way, draining resources away from real work.  See 'Hacktoverfest spam' https://blog.domenic.me/hacktoberfest/

@JulienPalard Thank you for adding the spam labels.

**Comment by Rimjhim-Dey** [comment]
I understand what you are saying but as you know we have given this task. And Thanks  for spamming because now I understand what is the real issue.
And a question, does spam label will disqualify me from the Hacktoberfest contest?

**Comment by Mariatta** [comment]
When a PR is marked either as "spam" or "invalid" the PR does not count towards Hactoberfest. https://hacktoberfest.digitalocean.com/faq/

**Comment by Rimjhim-Dey** [comment]
Thank You for sharing these things. And Sorry for spamming without knowing this. I hope I can really contribute something in future which will originally help you people.

**Comment by Mariatta** [comment]
Review Hacktoberfest's quality standard before making additional pull requests:  https://hacktoberfest.digitalocean.com/details#quality

**Pull request closed without merging**
