### PR TITLE
gh-110964: clinic: refactor output_templates()

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-110964

### CODE REVIEW

**Comment by vstinner** [comment]
cc @AlexWaygood

**Review by erlend-aasland — APPROVED** [review]
Are you fine with this, @AlexWaygood?

**Comment by AlexWaygood** [comment]
> Are you fine with this, @AlexWaygood?

Haven't had a chance to review in depth, but this looks fine to me -- feel free to merge if you're happy!

**Comment by vstinner** [comment]
Merged, thanks for reviews.

**Pull request merged**
