### PR TITLE
gh-94732: Fix KeyboardInterrupt race in asyncio run_forever()

### PR DESCRIPTION
**Pull request by hetmankp**
This addresses issue #94732, ensuring that the event loop's _thread_id
attribute and the asyncgen hooks set by sys.set_asyncgen_hooks() are
always restored no matter where a KeyboardInterrupt exception is raised.

* Issue: gh-94732

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
I am okay with skipping news,  it please do sign the CLA.

**Comment by hetmankp** [comment]
> I am okay with skipping news, it please do sign the CLA.

I have attempted to sign the CLA (i.e. enable the app) but I have the "Keep my email addresses private" option selected on Github, and the CLA app doesn't seem to accept my Github noreply email address. (My Github account is old enough, the noreply address shouldn't need the ID number).

Is this form of signing the agreement not supported at all or did I do something wrong?

**Comment by ambv** [comment]
> the CLA app doesn't seem to accept my Github noreply email address

@hetmankp, can you say what exactly seems to be happening? We do have handling for the old-style noreply addresses, too, maybe there's a bug in there.

**Comment by hetmankp** [comment]
> @hetmankp, can you say what exactly seems to be happening? We do have handling for the old-style noreply addresses, too, maybe there's a bug in there.

Sorry @ambv , I should have been more specific. When I click the "SIGN IN WITH GITHUB TO AGREE" button on the _The PSF Individual Contributor Agreement_ page, I get taken to a white page with one line of text which reads:

`Thank you for authorizing our application, but the CLA must be signed by the users who contributed to the PR. Authors emails are: hetmankp@users.noreply.github.com.`

**Comment by gvanrossum** [comment]
How's the CLA signing going? Still no resolution?

**Comment by gvanrossum** [comment]
@hetmankp I cannot merge this without a signed CLA, alas. @ambv What can we do?

**Comment by hetmankp** [comment]
> @hetmankp I cannot merge this without a signed CLA, alas. @ambv What can we do?

@gvanrossum @ambv , more than happy to work with whoever is available to provide further debugging information from my end.

Obviously this commit is simple enough we can probably find an alternative way forward if it comes to that, but if at all possible I'd rather we address the licencing system bug since it could affect other committers as well (plus it is the second time it has caused an issue for me attempting to submit a merge request into CPython).

**Comment by gvanrossum** [comment]
I don't know what's going on in the CLA bot, but presumably it would be avoidable if you linked a proper email address to your GitHub account and created a new PR using that email? (IIRC you can set the email address when committing with a git flag, or you can change your git config to set it.)

**Pull request closed without merging**
