### PR TITLE
gh-91877: Fix "Write Transports" table in asyncio docs

### LINKED ISSUE #91877: Invalid method name in asyncio low-level API index
**Documentation**

In the ["Write Transports" table in the Transports section of asyncio low-level API index page](https://docs.python.org/3.10/library/asyncio-llapi-index.html#transports), invalid method name is listed. In that table, the second row from the bottom currently refers [transport.get_write_buffer_size()](https://docs.python.org/3.10/library/asyncio-protocol.html#asyncio.WriteTransport.get_write_buffer_size). However, I think the method name here should be [transport.get_write_buffer_limits()](https://docs.python.org/3.10/library/asyncio-protocol.html#asyncio.WriteTransport.get_write_buffer_limits) because (1) corresponding short description is the one for `transport.get_write_buffer_limits()` and (2) its counterpart, `transport.set_write_buffer_limits()` is listed just below.

### PR DESCRIPTION
**Pull request by TechieBoy**
Fixes gh-91877

### CODE REVIEW

**Review by carljm — APPROVED** [review]
Change looks correct.

**Review by erlend-aasland — APPROVED** [review]

**Review by kumaraditya303 — APPROVED** [review]

**Comment by kumaraditya303** [comment]
@erlend-aasland: You can merge this :)

**Comment by erlend-aasland** [comment]
Argh, I mixed up the two attrs in the commit message 😦

**Comment by erlend-aasland** [comment]
Would you mind creating the backport PR's, Kumar? I'm afraid Miss Islington is having a bad day.

**Comment by kumaraditya303** [comment]
> Would you mind creating the backport PR's, Kumar? I'm afraid Miss Islington is having a bad day.

Yes, I'll create it.

**Pull request merged**
