### PR TITLE
Clarify amount of dots between package and subpackage

### PR DESCRIPTION
**Pull request by susan-shu-c**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@susan-shu-c

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by brandtbucher — APPROVED** [review]
Thanks @susan-shu-c!

**Comment by brandtbucher** [comment]
CC @willingc

**Review by willingc — APPROVED** [review]
Thanks for the correction.

**Comment by brandtbucher** [comment]
Congrats on your first CPython contribution @susan-shu-c! :champagne:

Looking forward to seeing more from you in the future.

**Comment by susan-shu-c** [comment]
Thanks for the fast response brandtbucher and willingc! Super excited and thanks for the welcome! 🐍

**Pull request merged**
