### PR TITLE
gh-102110: Updated cpython/Tools/README

### PR DESCRIPTION
**Pull request by jojo-jupiter**
gh-102110: Updated current cpython/Tools subdirectories and descriptions in README.

Added all cpython/Tools subdirectories to the README and included descriptions for the following subdirectories:
- c-analyzer
- cases_generator
- importbench
- nuget
- wasm

### CODE REVIEW

**Comment by arhadthedev** [comment]
According to `...`s in the changes, the PR is in progress. Probably you should convert it into a draft to not confuse reviewers.

**Comment by arhadthedev** [comment]
Or just delete these lines since `Several modules still require descriptions` in the news entry covers it.

**Comment by TylerBurgee** [comment]
> According to `...`s in the changes, the PR is in progress. Probably you should convert it into a draft to not confuse reviewers.
> Or just delete these lines since `Several modules still require descriptions` in the news entry covers it.

Thank you for your feedback! I will convert this PR to a draft and make the changes you suggested.

**Comment by TylerBurgee** [comment]
gh-102110: Updated cpython/Tools/README to include descriptions for all current modules in cpython/Tools.

Added descriptions for the folllowing cpython/Tools modules to cpython/Tools/README:

-------------------
- build
- clinic
- patchcheck
- ssl
- tz
- c-analyzer
- cases_generator
- importbench
- nuget
- wasm
-------------------

Removed parser from README, as this module no longer exists in cypthon/Tools.

**Comment by arhadthedev** [comment]
@TylerBurgee Please ping me if nobody reviews this PR until next Friday so I could ping all active developers affected for review:

> - ericsnowcurrently (build and c-analyzer)
> - gvanrossum (cases-generator)
> - erlend-aasland (clinic)
> - zooba (nuget)
> - zware (patchcheck)
> - vstinner (wasm)

**Comment by TylerBurgee** [comment]
@arhadthedev Okay, will do!

**Comment by hugovk** [comment]
Thank you for the PR, however there were already two open PRs for this listed on the [issue](https://github.com/python/cpython/issues/102110):

* https://github.com/python/cpython/pull/102550: no response to reviews, about to be closed
* https://github.com/python/cpython/pull/102625: ready after reviews, about to be merged

Sorry for any mixup, I suggest next time picking something that doesn't already have open PRs.

**Pull request closed without merging**
