### PR TITLE
gh-99905: Fix output of misses in summarize_stats.py execution counts

### PR DESCRIPTION
**Pull request by mdboom**
This was an indentation error introduced in 2844aa6a

* Issue: gh-99905

### CODE REVIEW

**Comment by markshannon** [comment]
LGTM.
This would imply that any instruction with misses would have been absent from the execution counts table, and that seems to be case.

**Comment by markshannon** [comment]
Curious to see the updated stats.

**Comment by brandtbucher** [comment]
Fun fact: there is a `%` formatting option that scales by 100 and adds the "%" for you!

**Comment by mdboom** [comment]
> Curious to see the updated stats.

I see you figured out how to kick one off manually.

I deleted the earlier (broken) results from earlier this week since they could be misleading.

**Pull request merged**
