### PR TITLE
bpo-11176: give more meaningful argument names in argparse documentation

### PR DESCRIPTION
**Pull request by Bonifacio2**
https://bugs.python.org/issue11176

### CODE REVIEW

**Review by nanjekyejoannah — COMMENTED** [review]
Can you give the original authors some credit too on the PR, if you built on their work, please?

We usually do it by putting `co-author: <author email>` in the PR comment.

**Comment by Bonifacio2** [comment]
Hello, @nanjekyejoannah. I only downloaded and tried to apply the original patch. I didn't look into its content (partially because I was afraid I would be influenced by what they had done and unable to give proper attribution).

**Review by MaxwellDupre — APPROVED** [review]
The new stuff looks ok.

**Comment by rhettinger** [comment]
I prefer the current form.  We have an introductory section and tutorial with well motivated use cases.  For the details docs the emphasis shifts to the mechanics of the operation, so the *foo* and *bar* style work better.

Thanks for the suggestion, but I think we should pass on this one.  It changes the style of the docs in a way that I think makes the less useful as a reference.

**Pull request closed without merging**
