### PR TITLE
bpo-20183: Convert _locale to the Argument Clinic

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue20183

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]
:+1:

**Comment by serhiy-storchaka** [comment]
Please merge with master and regenerate generated files.

**Comment by ZackerySpytz** [comment]
Thank you, Serhiy, for reviewing Argument Clinic patches.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution.

**Pull request merged**
