### PR TITLE
bpo-43258: Fix sqlite3 UDF callback scoping

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue43258

### CODE REVIEW

**Comment by erlend-aasland** [comment]
As promised in #24569, @berkerpeksag

**Review by berkerpeksag — APPROVED** [review]

**Comment by erlend-aasland** [comment]
FYI, the `test_asyncio` failure is unrelated to this PR.

**Comment by berkerpeksag** [comment]
Thank you!

**Comment by erlend-aasland** [comment]
Thanks again, @berkerpeksag 🙏🏻

**Pull request merged**
