### PR TITLE
gh-104108: Add the Py_mod_multiple_interpreters Module Def Slot

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
I'll be adding a value to indicate support for per-interpreter GIL in gh-99114.

* Issue: gh-104108

### CODE REVIEW

**Comment by ericsnowcurrently** [comment]
FYI, I plan on adding a test for this.

**Comment by ericsnowcurrently** [comment]
Any objections to this PR?  It's blocking the per-interpreter GIL PR, so I'd like to merge it as soon as possible.

**Review by erlend-aasland — COMMENTED** [review]
Apart from docs missing, this looks good to me.

**Comment by ericsnowcurrently** [comment]
I'm going to circle back to the docs after feature freeze.

**Pull request merged**
