### PR TITLE
gh-87092: create a 'jump target label' abstraction so that the compiler's codegen stage does not work directly with basic blocks

### PR DESCRIPTION
**Pull request by iritkatriel**
This does two things:

(1) prepares the code for moving codegen from basicblock to proper labels (which are replaced by basicblock refs before the optimization stage).
(2) reduces boilerplate and tightens error checking in a few places.

* Issue: gh-87092

### CODE REVIEW

**Review by markshannon — CHANGES_REQUESTED** [review]
Nice.

Could you rename `SET_LABEL` to something a bit more meaningful?

Logically we are emitting labels in the same way as we are emitting instructions.
However, we aren't really doing that physically.

I'd be happy with `EMIT_LABEL` or `EMIT_LABEL_HERE`, assuming the implementation will match the concept soon enough.
Or we could use `USE` as the old code was `compiler_use_next_block`.
Either `USE_LABEL` or `USE_LABEL_HERE`?

It's your call, but "set" has so many meanings as to be meaningless.

**Comment by iritkatriel** [comment]
I have made the requested changes; please review again.

I also made a few more changes that make this refactor more complete - we now have both a target_label and a target (block) on the instruction. The label is set by the frontend and the block is calculated before optimisations. They have different types to make sure we know which one we are using when.

Eventually the i_target can move off the instruction to the basicblock (there is only one per BB). Once the label becomes an int we can use the oparg field for it, so the instruction won't need either of these two fields.

**Comment by iritkatriel** [comment]
Buildbots are happy with this.

**Comment by iritkatriel** [comment]
With the last change the front end's labels are int rather than basicblock*.

**Comment by iritkatriel** [comment]
I found the bug that caused the reverted commit to fail, but I think we should merge this PR as is and continue in another one. 

This PR currently touches a lot of the code, but the changes are simple. The next step is a bit more sensitive so it's better to have it in a smaller PR.

**Review by markshannon — APPROVED** [review]
OK, let's merge this.

**Pull request merged**
