### PR TITLE
GH-117224: Move the body of a few large-ish micro-ops into helper functions

### PR DESCRIPTION
**Pull request by markshannon**
Moves the bodies of `_LOAD_GLOBAL`, `GET_ANEXT`, `GET_AWAITABLE` and `LOAD_NAME` into helper functions.

* Issue: gh-117224

### CODE REVIEW

**Comment by mdboom** [comment]
How does this differ from https://github.com/python/cpython/issues/117224, which ended being unhelpful / inconclusive?

**Comment by markshannon** [comment]
I'd forgotten about that issue.

**Review by iritkatriel — APPROVED** [review]

**Comment by markshannon** [comment]
Failures are due to network issues on embedded platforms

**Comment by mdboom** [comment]
Out of curiosity, I ran benchmarking on this PR.  While for most configurations, the difference is within the noise, for the [JIT on Windows, it's around 9% faster](https://github.com/faster-cpython/benchmarking-public/tree/main/results/bm-20240802-3.14.0a0-7aca84e-JIT).  nbody alone is like 92% faster, and nbody is also notably the benchmark that spends the most time percentage-wise in the JIT.  So, somehow this was a magic unlock for JIT performance on Windows-only -- if we can better understand why, maybe this will help elsewhere.

Cc: @brandtbucher

**Pull request merged**
