### PR TITLE
Remove several unused imports in `_pyrepl`

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Review by Eclips4 — APPROVED** [review]
LGTM!
Also, if we can do a little bit of _refactoring_ (Not in this PR), can we replace ``if False: ...`` with a ``if TYPE_CHECKING: ...``? This ``if False: ...`` entries looks weird for me.

**Comment by sobolevn** [comment]
`TYPE_CHECKING` needs `typing` import which is slow. Import time is critical for REPLs :(

**Comment by Eclips4** [comment]
> `TYPE_CHECKING` needs `typing` import which is slow. Import time is critical for REPLs :(

Oh, I forgot about that. Then let's leave it as it is.

**Comment by denballakh** [comment]
There is a way to do `if TYPE_CHECKING` check without importing `typing`:
```py
MYPY = False
if MYPY: # False at runtime, but mypy thinks that it is True
  ... # do expensive stuff
```
```sh
> mypy -h
...
  --always-true NAME        Additional variable to be considered True (may be
                            repeated)
  --always-false NAME       Additional variable to be considered False (may be
                            repeated)
...
```

**Review by lysnikolaou — APPROVED** [review]
LGTM!

**Pull request merged**
