### PR TITLE
bpo-23984: Improve descriptor documentation

### PR DESCRIPTION
**Pull request by shubh3794**
https://bugs.python.org/issue23984

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by shubh3794** [comment]
Signed the CLA

**Comment by MSeifert04** [comment]
That doesn't seem correct. This will raise an `IndentationError: expected an indented block` exception.

**Review by DimitrisJim — COMMENTED** [review]
Hi @shubh3794 and thanks for the patch. Did you just remove the print call? This doesn't really improve the example (it makes it worse, actually)

**Comment by DimitrisJim** [comment]
Also, if you can, please edit the title of the issue to include the b.p.o id by using:

bpo-23984: "title of this issue"

**Comment by shubh3794** [comment]
@DimitrisJim You're right, I was hasty while pushing it. Review now

**Comment by MSeifert04** [comment]
`return` is not a function, so generally you don't need the `()`. 

However [one issue on the issue tracker](https://bugs.python.org/msg241458) was "that [the example] gives no hint of why one might want to use a staticmethod". And I don't see how this change improves that. Could you elaborate on that point?

**Comment by shubh3794** [comment]
@MSeifert04 I thought about that, and I can explain the usage as well, but the usage can be thoroughly explained a paragraph, would that suffice or should I add a complete OO example(which I think is not required). Correct me if I'm wrong.

**Comment by MSeifert04** [comment]
I don't think it needs to be a "complete OO example" but just something "better" than returning the argument. Actually `staticmethod` is rarely used, because Python (unlike Java, ...) doesn't enforce classes-only. So an example should at least *hint* at possible use-cases in Python. At least that's my interpretation of the comment 

FWIW: I'm just a new contributor like you, so please don't assume I know what should be documented there.

**Comment by shubh3794** [comment]
@MSeifert04 I think the usage of static method is more theoretical since practically people usually avoid static methods, And the purpose I think is clear from the method, that it can be called via a class or an object of that class. Use cases are just that it might fit into a context of a class which is already specified in the doc.

**Comment by shubh3794** [comment]
@DimitrisJim Requesting your input over here.

**Comment by DimitrisJim** [comment]
Using `return x` looks like the _safest_ option for the time being (mirroring the `classmethod` example later in the documentation). A little sentence under the example explaining why/where this is useful would probably be needed too.

I'd suggest you stick with `return x` for now and wait until @rhettinger, the author of this HOWTO, finds some time to come and offer his input on the matter. He'll judge the degree and nature of the change that's required here.

**Review by serhiy-storchaka — APPROVED** [review]

**Review by rhettinger — CHANGES_REQUESTED** [review]
I would rather leave the print() in the method call and instead remove the two print() calls on lines 365 and 367.

**Comment by shubh3794** [comment]
@rhettinger I have made the changes as you proposed. Kindly let me know if you want me to change anything else.

**Comment by shubh3794** [comment]
@rhettinger Is the PR okay to be merged now?

**Comment by shubh3794** [comment]
@serhiy-storchaka @rhettinger Is the PR okay to be merged now, please let me know if I can make it better somehow

**Comment by serhiy-storchaka** [comment]
It is LGTM.

**Review by louisom — APPROVED** [review]
It LGTM, as rhettinger says, the only problem is this isn't a good example to explain the static method usage. (try to explain that static method won't access the attribute of the instance.

**Comment by shubh3794** [comment]
@rhettinger Please suggest a course of action.

**Comment by brettcannon** [comment]
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

**Comment by vstinner** [comment]
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

**Comment by shubh3794** [comment]
@brettcannon Hey I had already made changes, I am awaiting review from @rhettinger. He suggested a few changes which I made, only his approval is pending.

**Comment by shubh3794** [comment]
I have made the requested changes; please review again

**Review by rhettinger — APPROVED** [review]

**Comment by vstinner** [comment]
AppVeyor CI was stuck. I closed/reopened the PR to workaround that.

**Pull request merged**
