### PR TITLE
bpo-29086: Add stableabi option to Documentation

### PR DESCRIPTION
**Pull request by WillAyd**
Starting as a draft for now, as there are quite a few ways to go about this. I figured this first approach, while verbose, has the upside of leveraging functionality that has already been built into the documentation. Happy to expand to other functions if we think this is in the right direction

https://bugs.python.org/issue29086

### CODE REVIEW

**Comment by WillAyd** [comment]
This is how it renders:

image

**Review by Fidget-Spinner — COMMENTED** [review]
This LGTM, the only problem is that nearly all the `:stableabi:` markup has trailing whitespace and tabs, this is causing both the Travis CI checks and Azure pipelines to fail.

Usually I'd advise running [make patcheck](https://devguide.python.org/pullrequest/?highlight=patchcheck#patchcheck). However, you might want to do this using your own IDE/manually since it occasionally re-indents/de-indents unrelated parts of the documentation (from personal experience).

**Review by Fidget-Spinner — APPROVED** [review]

**Comment by WillAyd** [comment]
Not stale just awaiting core review

**Review by Mariatta — APPROVED** [review]
Looks great to me. Thanks!

**Comment by Mariatta** [comment]
Does this need backport?

**Comment by WillAyd** [comment]
Not sure what your backport policy is. It could be since it has been this way for a while, though at the same time the change is relatively minor

**Comment by encukou** [comment]
Hi,
Can we please hold off on this PR for a few weeks? I am writing a PEP about the stable ABI.

**Comment by Mariatta** [comment]
No prob, @encukou .I've added the do-not-merge label for now.

**Comment by encukou** [comment]
I've just put up a first draft of the PEP at: https://github.com/encukou/abi3/blob/main/PEP.rst
and kicked off a discussion at: https://mail.python.org/archives/list/capi-sig@python.org/thread/PMM5QG4IAL6LOMNFXNHW72INSCN4JC5H/

**Comment by encukou** [comment]
The PEP is almost ready: https://discuss.python.org/t/pre-pep-maintaining-the-stable-abi/6986

@WillAyd, do you mind if I close this PR and take over the effort?

**Comment by WillAyd** [comment]
Not a problem at all - great work on the PEP

**Comment by encukou** [comment]
GH-25668 proposes to add the notes, along with when a particular API was added.

**Pull request closed without merging**
