### PR TITLE
Prevent TypeError if multiple waiters

### PR DESCRIPTION
**Pull request by earonesty**
Minor error that can occur if someone wait_closes and then someone else closes a server.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by earonesty** [comment]
Signing up nets me zero confirmation emails.   Not sure why.  No errors.

**Comment by serhiy-storchaka** [comment]
Please open an issue on the [bug tracker](https://bugs.python.org/), add tests and  news entry.

**Comment by csabella** [comment]
As this issue has been waiting for additional information for a long time, I am going to close it.  Feel free to re-open it if @serhiy-storchaka 's concerns are addressed.  If you do re-open, please also resolve the merge conflict.

**Pull request closed without merging**
