### PR TITLE
bpo-40275: Use new test.support helper submodules in tests

### PR DESCRIPTION
**Pull request by shihai1991**
Use test helpers in the following test cases:
* test_asyncio
* test_getopt
* test_tcl
* test_xmlrpc

https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by shihai1991** [comment]
@vstinner Hi, victor. Pls take a look if you have free time.

**Comment by vstinner** [comment]
@serhiy-storchaka: Hi. Would you be available next week to have a look at what has been done recently in `test/support/__init__.py` in https://bugs.python.org/issue40275 before we start to convert the whole Python test suite to newer support submodules like support.os_helper? The final goal is remove aliases from support to be able to remove imports, and also to make `test/support/__init__.py` smaller.

**Comment by serhiy-storchaka** [comment]
I do not see a value in getting rid of the os module import. It is one of base modules, and it is used in the test launcher and in most tests, so you actually cannot get rid of importing it. It just disturbs the files history and makes the software archeology harder. Please stop.

**Comment by shihai1991** [comment]
> I do not see a value in getting rid of the os module import. It is one of base modules, and it is used in the test launcher and in most tests, so you actually cannot get rid of importing it. It just disturbs the files history and makes the software archeology harder. Please stop.

Thanks for your comment, serhiy. IMHO, it's not try to getting rid of the os module import but to control what exact modules we want import in ut.

**Comment by serhiy-storchaka** [comment]
They were always imported from the `test.support` module. And I do not see reasons to change this. It will just clutter the history and break automatic backporting.

**Comment by shihai1991** [comment]
> They were always imported from the `test.support` module. And I do not see reasons to change this. It will just clutter the history and break automatic backporting.

some testcases like test_unix_events.py have not use `test.support` directly, the others need keep import `test.support`(MAYBE we need to split `test.support` continuously.

**Comment by vstinner** [comment]
@serhiy-storchaka:
> I do not see a value in getting rid of the os module import. It is one of base modules, and it is used in the test launcher and in most tests, so you actually cannot get rid of importing it. It just disturbs the files history and makes the software archeology harder. Please stop.
> They were always imported from the test.support module. And I do not see reasons to change this. It will just clutter the history and break automatic backporting.

Hi Serhiy,

The creation of the support.os_helper submodule is not directly related the "test.support has way too many imports" https://bugs.python.org/issue40275 issue, but more about the old bpo-15494 "Move test/support.py into a test.support subpackage", commit fb15aa1e0873043548df782ace51fe1340ea559a:

```
commit fb15aa1e0873043548df782ace51fe1340ea559a
Author: Nick Coghlan <ncoghlan@gmail.com>
Date:   Sun Jul 28 20:56:19 2013 +1000

    Close #15494: test.support is now a package rather than a module
    
    Initial patch by Indra Talip
```

Between Python 2.7 and Python 3.10, support became 2x larger:

```
$ wc -l 2.7/Lib/test/support/*.py
 2177 2.7/Lib/test/support/__init__.py
  170 2.7/Lib/test/support/script_helper.py
 2347 total

$ wc -l master/Lib/test/support/*.py
    41 master/Lib/test/support/bytecode_helper.py
    38 master/Lib/test/support/hashlib_helper.py
   238 master/Lib/test/support/import_helper.py
  1960 master/Lib/test/support/__init__.py
   183 master/Lib/test/support/interpreters.py
    29 master/Lib/test/support/logging_helper.py
   611 master/Lib/test/support/os_helper.py
   262 master/Lib/test/support/script_helper.py
   269 master/Lib/test/support/socket_helper.py
   204 master/Lib/test/support/testresult.py
   209 master/Lib/test/support/threading_helper.py
   180 master/Lib/test/support/warnings_helper.py
  4224 total
```

But this PR is not only about os_helper. There are also support.import_helper and support.warning_helper.

Removing `from .import_helper import from `support/__init__.py` removes 9 imports from `import test.support`:

```
- 'importlib',
- 'importlib._bootstrap',
- 'importlib._bootstrap_external',
- 'importlib.abc',
- 'importlib.machinery',
- 'importlib.util',
- 'typing',
- 'typing.io',
- 'typing.re',
```

If we remove `from .warnings_helper import ...` from ``support/__init__.py`` and top-level `import warnings` in unittest, it becomes possible to completely avoid importing `warnings` on `import test.support`.

> They were always imported from the test.support module. And I do not see reasons to change this. It will just clutter the history and break automatic backporting.

If these changes create too many merge conflicts, we can backport https://bugs.python.org/issue40275 changes to 3.8 and 3.9 branches.

**Comment by vstinner** [comment]
@shihai1991: Can you please solve the merge conflict?

**Comment by shihai1991** [comment]
> @shihai1991: Can you please solve the merge conflict?

sure, I rebase it now ;)

**Comment by shihai1991** [comment]
thanks, victor :)

**Pull request merged**
