### PR TITLE
Fix typo in Lib/socketserver.py docstring

### PR DESCRIPTION
**Pull request by YesmynameisPerry**
Changed:

> 'This is bad class design, but save some typing'

Into:

> 'This is bad class design, but saves some typing'

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@YesmynameisPerry

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by brandtbucher** [comment]
Thanks for your time @YesmynameisPerry, and welcome to CPython! :sunglasses:

**Review by brandtbucher — APPROVED** [review]
Nice catch!

**Review by eamanu — APPROVED** [review]
Good Catch

**Review by corona10 — APPROVED** [review]
LGTM

@vstinner Can you take a look at this PR as the core developers?
It looks like just a typo so it can be easily merged.

**Comment by brandtbucher** [comment]
Congrats on your first CPython contribution @YesmynameisPerry! :champagne:

Looking forward to seeing more from you in the future.

**Comment by corona10** [comment]
Congrat @YesmynameisPerry :)

**Pull request merged**
