### PR TITLE
Fix a couple of compiler warnings.

### PR DESCRIPTION
**Pull request by markshannon**

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]
Looks safe to me. An overflow just means we deoptimize if I understand correctly.

**Comment by JulienPalard** [comment]
Using gcc 10.3.0 I had no warning here, out of curiosity what warning is this fixing?

**Comment by markshannon** [comment]
> Using gcc 10.3.0 I had no warning here, out of curiosity what warning is this fixing?

On windows: https://github.com/python/cpython/pull/28520/files#diff-c22186367cbe20233e843261998dc027ae5f1f8c0d2e778abfa454ae74cc59deR3669

**Comment by markshannon** [comment]
> Looks safe to me. An overflow just means we deoptimize if I understand correctly.

No possibility of an overflow. Although the type of `dk_entries` is signed, it can never be negative.

**Comment by JulienPalard** [comment]
> On windows: https://github.com/python/cpython/pull/28520/files#diff-c22186367cbe20233e843261998dc027ae5f1f8c0d2e778abfa454ae74cc59deR3669

Ohh ok.

Looks good to me too.

**Pull request merged**
