### PR TITLE
warning: unused variable

### PR DESCRIPTION
**Pull request by chouetz**
vi is unused in this code block according to my ide

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Thanks for your interest in improving CPython!

Unfortunately, cosmetic changes are usually not accepted for the CPython repo. We have a large number of open bug reports, and prefer to spend our time fixing those.

**Comment by chouetz** [comment]
@AlexWaygood thanks for your comment, I wanted to do a separated pull-request from the modification I intend to do on bug gh-42811
Then I will do this cosmetic change embedded with this other PR

**Comment by AlexWaygood** [comment]
@chouetz, we'd prefer it if you didn't do the cosmetic change at all, if that's okay :) including the change as part of a substantive PR will create a confusing diff and distract from the PR's main purpose

**Comment by chouetz** [comment]
@AlexWaygood ok then we don't "fix" this kind of stuff, or only when noticed within a development that targets a precise block of code? Would it be ok if it's on a specific commit within a PR? Especially here because it's really trivial (I completely understand we don't want to bring confusion during a code review)
Sorry to ask such questions, just trying to do things right
Thanks in advance

**Comment by AlexWaygood** [comment]
> Sorry to ask such questions, just trying to do things right

Of course, no worries!

Yeah, in general, we don't "fix" this kind of stuff:

- Lots of the CPython codebase is really old and predates these kinds of style guides being written. If we encouraged PRs like this, there's unfortunately a risk that we'd get deluged with PRs "cleaning up" the CPython codebase, which isn't something we really want.
- People have different opinions about what constitutes "good style", so encouraging PRs like this leads to annoying back-and-forths (E.g. I don't find the proposed change here significantly more readable, personally 🙂)
- Cosmetic PRs lead to code churn and confusing `git blame`.

Every repo has their own policy on PRs like this; some are much more receptive than others; this is just the stance CPython has chosen to take here 🙂

FYI, there's lots more information to new contributors that you might find useful in the devguide: https://devguide.python.org

**Pull request closed without merging**
