### PR TITLE
Upgrade bundled pip and setuptools

### PR DESCRIPTION
**Pull request by pradyunsg**
See https://github.com/pypa/pip/issues/10488#issuecomment-949777565 and [PEP 453](https://python.github.io/peps/pep-0453/). :)

### CODE REVIEW

**Comment by IRDonch** [comment]
@pradyunsg Are you going to update this?

**Comment by pradyunsg** [comment]
I've been meaning to, but haven't come around to it yet.

**Comment by pradyunsg** [comment]
Closing this for now -- I'll file a new PR with the current release cycle.

**Comment by pradyunsg** [comment]
x-ref: https://github.com/pypa/pip/issues/10726

**Pull request closed without merging**
