### PR TITLE
gh-102498 Clean up unused variables and imports in the email module 

### PR DESCRIPTION
**Pull request by JosephSBoyle**
Found some unused vars using the following pyflakes command `$  python3.12 -m pyflakes Lib/email/`. Inspired by @AlexWaygood 's use of the tool to find issues in the `test_typing.py` file (can't seem to find the exact issue).

Cleanup some unused variables and imports in the email module.

In `text.py` I replaced a pagebreak character (U+000C) with a newline. The latter doesn't seem to be rendered by GH. VScode shows it, as will most editors I imagine.

GH Issue: #102498

* Issue: gh-102498

### CODE REVIEW

**Comment by warsaw** [comment]
Thanks for the cleanup.  I can review it in more detail after a few housekeeping updates have been made (updating the branch to current HEAD, creating an issue, and adding an issue number).

You can just delete the page feed line (see PEP 8, two blank lines only between top level constructs).  The page feeds are a historical holdover for when this library was developed independently.

**Comment by hugovk** [comment]
To appease Bedevere about the issue number, please prefix the PR title as "gh-XXXXX:"

**Comment by JosephSBoyle** [comment]
Hi @warsaw, thanks for the quick response. I've added an issue, rebased to the current HEAD and removed that extra line as you requested. Should be good for a review now.

@hugovk cheers for the headsup r.e the issue number.

**Comment by JosephSBoyle** [comment]
There are 45 pagebreaks remaining in the entire cpython repo, 34 of which are in `email`. I'm happy to replace them with newlines / delete them as appropriate per pep-8 if people want them gone. Might be something for another issue though:)

**Comment by JosephSBoyle** [comment]
I appear to have duplicated the commits during the merge somehow. I would rebase them but that seems to be discouraged. If we merge this PR they'll all be squashed anyways as I understand it.. Let me know if dropping the duplicated commits is preferable and I can do that:)

**Comment by hugovk** [comment]
Correct, all PRs are squashed and merged, so don't worry about the individual commits too much. 👍

**Comment by JosephSBoyle** [comment]
Hi @warsaw. Could you please take a look at this when you get a chance?

**Review by warsaw — APPROVED** [review]

**Pull request merged**
