### PR TITLE
bpo-44659: Replace @ilevkivskyi with @Fidget-Spinner as typing code owner

### PR DESCRIPTION
**Pull request by ambv**
https://bugs.python.org/issue44659

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]
LGTM. Though it feels weird seeing my handle there ;). We need to backport this to 3.10 and 3.9 too right? Otherwise backport PRs will ping Ivan.

**Comment by ambv** [comment]
Yes, this will indeed need backports.

**Comment by ambv** [comment]
Sorry, Ivan, address sanitizer refuses to let you go.

**Comment by Fidget-Spinner** [comment]
Wow we managed to break ASAN 😉.

Thanks again for handling this Łukasz!

**Comment by ambv** [comment]
Naturally, it's literally my job.

**Comment by Fidget-Spinner** [comment]
Haha, congrats on the position :).

**Comment by isidentical** [comment]
Ah, I think this might not work for triagers :/ 

> The people you choose as code owners must have write permissions for the repository.

**Comment by ambv** [comment]
There's a few ways we can fix this 😎

**Pull request merged**
