### PR TITLE
Fix typo in __mul__ docstring

### PR DESCRIPTION
**Pull request by grantjenks**
Fix typo in `__mul__` docstring.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Comment by grantjenks** [comment]
I seem to be blocked on "CLA not signed". The CPython devguide says:

"""
After signing the CLA, please wait at least one US business day and then check “Your Details” on b.p.o to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA). Once you have verified that your b.p.o account reflects your signing of the CLA, you can either ask for the CLA check to be run again or wait for it to be run automatically the next time you push changes to your PR.
"""

I've signed and submitted the CLA and waited 3 business days but still "Contributor Form Received" on https://bugs.python.org/user27001 is blank. You can view the signed contributor form at http://www.grantjenks.com/docs/Python-Contributor-Agreement-Form-Signed.pdf

Please let me know if there's anything that needs correcting.

**Review by serhiy-storchaka — APPROVED** [review]

**Review by serhiy-storchaka — COMMENTED** [review]
While we are here, it is worth to fix a docsting for `__rmul__` below. Currently it is `"Return self*value."`, but should be `"Return value*self."`.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @grantjenks! Your signing of the CLA will be accepted manually, it takes a time. But I think that signing the CLA for such trivial fix is not required and going to merge it not waiting the acceptance.

Though it would be good if you will fix other error two line below in this PR.

**Comment by grantjenks** [comment]
Hi @serhiy-storchaka! I've seen your name occasionally on the python mailing lists. Nice to meet you this way too :)

I fixed the other typo two lines below the original patch. Good catch!

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
