### PR TITLE
bpo-38431: fix dataclasses.InitVar.__repr__

### PR DESCRIPTION
**Pull request by samuelcolvin**
new version of #16700 based off master.

See original bug https://github.com/samuelcolvin/pydantic/issues/886

https://bugs.python.org/issue38431

### CODE REVIEW

**Comment by brandtbucher** [comment]
Thanks for your time @samuelcolvin, and welcome to CPython!

**Review by brandtbucher — APPROVED** [review]
This looks like a good change to me!

**Comment by brandtbucher** [comment]
CC @ericvsmith

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by brandtbucher** [comment]
Congrats on your first CPython contribution @samuelcolvin! :champagne:

Looking forward to seeing more from you in the future.

**Pull request merged**
