### PR TITLE
gh-81548: Deprecate octal sequences with value larger than 0o377

### LINKED ISSUE #81548: octal escapes applied inconsistently throughout the interpreter and lib
BPO | [37367](https://bugs.python.org/issue37367)
--- | :---
Nosy | @gvanrossum, @terryjreedy, @taleinat, @ezio-melotti, @serhiy-storchaka, @mr-nfamous, @websurfer5
PRs | <li>python/cpython#14654</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-21.19:46:08.946>
labels = ['expert-regex', 'easy', '3.9']
title = 'octal escapes applied inconsistently throughout the interpreter and lib'
updated_at = <Date 2019-11-20.09:14:13.360>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-20.09:14:13.360>
actor = 'taleinat'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2019-06-21.19:46:08.946>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 37367
keywords = ['patch', 'easy', 'easy (C)']
message_count = 9.0
messages = ['346246', '346865', '347261', '347411', '347516', '356817', '357026', '357031', '357041']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'terry.reedy', 'taleinat', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'bup', 'Jeffrey.Kintscher']
pr_nums = ['14654']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37367'
versions = ['Python 3.9']
```

</p></details>

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Closes #81548.

### CODE REVIEW

**Comment by gvanrossum** [comment]
I'm glad you're doing this!

**Comment by serhiy-storchaka** [comment]
Interesting, you posted your comment just between two commits which I have pushed with one `git push`.

**Comment by slateny** [comment]
I think [this line](https://github.com/python/cpython/pull/91668/files#diff-78f24041d66ab8ed2ae1aee94bcd42396d27af833cb96a3c506294c6d6dce82dR808) should be `:gh:` instead of `:issue:` - got a failed CI [here](https://github.com/python/cpython/runs/6241319316?check_suite_focus=true)

**Comment by disconnect3d** [comment]
If possible, I would suggest extending the information about this deprecation warning as it is not obvious for people reading this why is this made and when does the deprecation warning fires off.

1. The former could be something like:
> This is done because higher values may give unexpected results. For example the b'\407' literal is b'\x07' as the 0o407 (263) value is treated as a single byte and 263 % 256 = 7.

2. The latter issue, when the deprecation warning fires off, can be seen here:
```sh
$ python3.11 a.py
ć b'\x07'
$ python3.11 -W default a.py
//a.py:1: DeprecationWarning: invalid octal escape sequence '\407'
  print("\407", b"\407")
//a.py:1: DeprecationWarning: invalid octal escape sequence '\407'
  print("\407", b"\407")
ć b'\x07'
```
I believe this comes from the [default warning filter](https://docs.python.org/3/library/warnings.html#default-warning-filter). Idk if we really want it described there, but imho it never hurts to provide more information.


cc: @serhiy-storchaka

**Comment by pablogsal** [comment]
> If possible, I would suggest extending the information about this deprecation warning as it is not obvious for people reading this why is this made and when does the deprecation warning fires off.
> 
> 1. The former could be something like:
> 
> > This is done because high octal escape values may give unexpected results. For example the b'\407' literal is b'\x07' as the 0o407 (263) value is treated as a single byte and 263 % 256 = 7.
> 
> 2. The latter issue, when the deprecation warning fires off, can be seen here:
> 
> ```shell
> $ cat a.py
> print("\407", b"\407")
> 
> $ python3.11 a.py
> ć b'\x07'
> 
> $ python3.11 -W default a.py
> //a.py:1: DeprecationWarning: invalid octal escape sequence '\407'
>   print("\407", b"\407")
> //a.py:1: DeprecationWarning: invalid octal escape sequence '\407'
>   print("\407", b"\407")
> ć b'\x07'
> ```
> 
> I believe this comes from the [default warning filter](https://docs.python.org/3/library/warnings.html#default-warning-filter). Idk if we really want it described there, but imho it never hurts to provide more information.
> 
> cc: @serhiy-storchaka

Will give this a go soon 👍

**Comment by arhadthedev** [comment]
> Will give this a go soon 👍

@pablogsal

**Pull request merged**
