### PR TITLE
Move misplaced blurb entries

### PR DESCRIPTION
**Pull request by Yhg1s**
Move misplaced blurb entries from "C_API" to "C API", and from "Core_and_Builtins" to "Core and Builtins".

### CODE REVIEW

**Comment by ambv** [comment]
Shouldn't this rename go the other way?

**Review by hugovk — APPROVED** [review]
Blurb <= 1.1.0 wants the old names with spaces.

* https://github.com/python/release-tools currently uses 1.1.0

Blurb >= 1.2.0 can read directories both with spaces and with underscores.

* https://github.com/python/release-tools/pull/143 upgrades to use 1.2.0

If we merge that PR, we can close (or merge!) this PR.

If @Yhg1s  wants to do it the old way for this release, let's merge this one.

**Comment by ambv** [comment]
I merged the release-tools PR.

**Comment by Yhg1s** [comment]
I already fixed this for 3.13.0b4 in a separate PR. I sent this PR to Hugo because this is his bailiwick now :)

**Pull request closed without merging**
