### PR TITLE
gh-75128: Ignore EADDRNOTAVAIL error in asyncio.BaseEventLoop.create_server()

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-75128

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
It is actually a 6.5 years old patch by @pitrou which was not yet merged perhaps due to oversight.

**Comment by serhiy-storchaka** [comment]
!builtbot "AMD64 Arch Linux Asan"

**Comment by serhiy-storchaka** [comment]
!builtbot AMD64 Arch Linux

**Comment by serhiy-storchaka** [comment]
!buildbot AMD64 Arch Linux

**Comment by pitrou** [comment]
Well I lost track of this and I haven't done any network programming in a long time, so I don't qualified to review this anymore, sorry :-(

**Comment by serhiy-storchaka** [comment]
The change looks reasonable to me, it got positive feedback in the issue, and it fixes the remaining failures on buildbots. So I'm going to merge it.

**Review by gvanrossum — APPROVED** [review]
LGTM, thanks! Make sure to add Antoine in a Co-Authored-By header.

**Comment by serhiy-storchaka** [comment]
> LGTM, thanks! Make sure to add Antoine in a Co-Authored-By header.

Yes, of course, it is Antoine's patch. I only added one line (log warning only in debugging, as in other cases) and a NEWS entry. The patch was good from the start and did not need a correction.

**Pull request merged**
