### PR TITLE
gh-118119: Re-use `sep` in `posixpath.expanduser()`

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-118119

### CODE REVIEW

**Comment by nineteendo** [comment]
Could someone add the skip-news label? Thank you.

**Comment by birkenfeld** [comment]
Whatever the motivation back then, this being posixpath `sep` is guaranteed to be `"/"` so I don't see a problem with the change.

**Comment by nineteendo** [comment]
@birkenfeld, could you approve this then?

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by nineteendo** [comment]
Thanks @encukou.

**Pull request merged**
