### PR TITLE
[3.7] bpo-36307: Travis: upgrade to Xenial environment (GH-12356)

### PR DESCRIPTION
**Pull request by methane**
(cherry picked from commit 74ae50e53e59bbe39d6287b902757f0cd01327dc)

Co-authored-by: CAM Gerlach <CAM.Gerlach@Gerlach.CAM>

https://bugs.python.org/issue36307

### CODE REVIEW

**Comment by tirkarthi** [comment]
Not sure if it helps but this seems to be a related issue : https://github.com/travis-ci/travis-ci/issues/8363 . I can see more users with the workaround `- pyenv global system 3.5` (Replacing 3.5 with 3.7?) in `before_install` (https://github.com/pre-commit/pre-commit/commit/e3ab8902692e896da9ded42bd4d76ea4e1de359d)

**Comment by tirkarthi** [comment]
Seems to work with the workaround (https://github.com/tirkarthi/cpython/commit/95a193ccd6dfde98d0ae757155e583b2fd9d5fe3)

```
before_install:
  - pyenv global system 3.7
```

Ref : https://travis-ci.org/tirkarthi/cpython/jobs/507972151

Fails without workaround

Ref : https://travis-ci.org/tirkarthi/cpython/jobs/507981710

**Comment by methane** [comment]
pyenv is great, but I hate pyenv shims.  It slows down python startup more than 5x.  It adds many garbage commands in PATH.  It's crazy.

**Comment by tirkarthi** [comment]
Agreed. I searched for any fixes but I couldn't get any other solution other than the workaround.

**Pull request merged**
