### PR TITLE
gh-123089: avoid _IterationGuard for WeakSet, make it thread safe 

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-123089

### CODE REVIEW

**Review by colesbury — COMMENTED** [review]
The change looks good to me, but I think this deserves a NEWS entry.

**Comment by kumaraditya303** [comment]
> The change looks good to me, but I think this deserves a NEWS entry.

Added news entry, thanks for your review!

**Comment by picnixz** [comment]
Does it need to be backported to 3.13? (or at least to have a PR pending for it)?

**Comment by kumaraditya303** [comment]
No, this change is for Python 3.14+

**Pull request merged**
