### PR TITLE
Fix doc SubprocessTransport.get_pipe_transport

### PR DESCRIPTION
**Pull request by stepheny**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by stepheny** [comment]
Since this is such a minor fix, I won't hire a lawyer  to review an agreement, so I do not agree the CLA.
This patch is provided AS IS.
If you insist an additional agreement on an open souce project, then consider this as a bug report and just close the pull request.

**Comment by asvetlov** [comment]
Your patch is correct but I afraid the CLA is required, sorry.

**Comment by csabella** [comment]
Closing this since the CLA won't be signed.

**Pull request closed without merging**
