### PR TITLE
GH-105848: Get rid of `KW_NAMES` (again)

### PR DESCRIPTION
**Pull request by brandtbucher**
This is an updated version of #105849.

* Issue: gh-105848

----
:books: Documentation preview :books:: https://cpython-previews--108496.org.readthedocs.build/

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
Looks great!

**Comment by brandtbucher** [comment]
I might have messed something up. Benchmarking came back 2% slower with wonky stats.

**Comment by markshannon** [comment]
I see a few ways to make this faster.

1. Leave the code much as it is now, but store `kwnames` on the threadstate instead of in a C local variable. We would need to take extra care to ensure that no Python code could be called between `KW_NAMES` and the start of the following call *and* move `kwnames` from the threadstate to a local at the start of every `CALL` instruction.
2. Use a borrowed reference to `kwnames`. We would need to make sure that error handling doesn't decref the `kwnames`. (If we get deferred references, we could make `kwnames` a deferred reference and it wouldn't need any special casing for error handling)

Option 2 sounds a lot simpler, if a bit slower.

Unless we go with option 1, we are going to see a lot more `PUSH_NULL` instructions. It might be worth adding `LOAD_FAST_PUSH_NULL` and `LOAD_CONST_PUSH_NULL` superinstructions.

My guess is that with option 2, and the the superinstructions, there won't be much of a slowdown.

**Comment by markshannon** [comment]
(And please add a link to the stats)

**Comment by brandtbucher** [comment]
(The stats issue I observed was in the comparison vs main, and is unrelated.)

So, here's the current situation. This branch adds over 7 billion new `PUSH_NULL` instructions to the benchmark run, which is a significant (~5%) increase in the number of instructions executed. This makes the benchmarks [2% slower](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230810-3.13.0a0-3276185/bm-20230810-linux-x86_64-brandtbucher-kwnames_again-3.13.0a0-3276185-vs-base.png) ([stats](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230810-3.13.0a0-3276185/bm-20230810-azure-x86_64-brandtbucher-kwnames_again-3.13.0a0-3276185-pystats.md)).

I tried the "easy" route of [adding a new `LOAD_FAST_PUSH_NULL` superinstruction](https://github.com/brandtbucher/cpython/compare/brandtbucher:cpython:kwnames-again...brandtbucher:cpython:kwnames-again-super), since the stats suggest that this is by far the most common `PUSH_NULL` pairing. However, that made it *an additional 2% slower* (for a total of [4% slower than `main`](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230810-3.13.0a0-77a6830/bm-20230810-linux-x86_64-brandtbucher-kwnames_again_super-3.13.0a0-77a6830-vs-base.png)), which is incredibly surprising, even though a handful of the slowest benchmarks from this branch got way faster on that branch ([stats](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230810-3.13.0a0-77a6830/bm-20230810-azure-x86_64-brandtbucher-kwnames_again_super-3.13.0a0-77a6830-pystats.md)).

So, it seems that clearly something needs to be done, but superinstructions aren't going to help. I'll try some of the other suggested ideas tomorrow, but in general this is getting to be a pretty annoying problem.

**Comment by gvanrossum** [comment]
That's disappointing; it would seem that moving kwnames to the tstate makes most sense to try next?

**Comment by brandtbucher** [comment]
Moving keyword names to the `frame` is a little less than [1% slower](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230811-3.13.0a0-7f16231/bm-20230811-linux-x86_64-brandtbucher-kwnames_frame-3.13.0a0-7f16231-vs-base.png). I was getting crashes with moving it to the `tstate` (which is trickier), but I think I resolved those and I'm benchmarking that approach now.

**Comment by brandtbucher** [comment]
Sticking it on the `tstate` is [a little more than 1% slower](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230811-3.13.0a0-70d0242/bm-20230811-linux-x86_64-brandtbucher-kwnames_tstate-3.13.0a0-70d0242-vs-base.png).

**Comment by gvanrossum** [comment]
Off-line we decided to at least look at splitting CALL into two separate opcode families, CALL and CALL_KW. Looking at the specializations, most of them seem to either insist on no keywords (the majority), or insist on keywords. There are only a few specializations that need to handle either case. So we would not be adding many new opcodes, and the split makes the specialization more efficiently. Using uops we could avoid having more code. Of course, we (Brandt :-) still have to code this and benchmark it before we can be sure of those predictions -- this has been a surprising adventure so far.

**Comment by brandtbucher** [comment]
Closing in favor of the `CALL`/`CALL_KW` split (PR up soon).

**Pull request closed without merging**
