### PR TITLE
gh-92417: `socket` docs: remove references to Python <3.3

### PR DESCRIPTION
**Pull request by AlexWaygood**
#92417

### CODE REVIEW

**Comment by rhettinger** [comment]
Please don't backport any of these.  Only actual bug fixes should be back ported.

**Comment by JelleZijlstra** [comment]
The devguide (https://devguide.python.org/gh-labels/?highlight=backport) says "Generally, backports to the maintenance branches are primarily bugfixes and documentation clarifications." This is a documentation clarification, so it seems fine to backport it.

**Review by serhiy-storchaka — COMMENTED** [review]
I am not sure about this. We still keep `versionchanged` directives for versions >= 3.0 in docs. Even if nobody currently uses Python 3.2, the old (and still working) code can have references to IOError.

**Comment by AlexWaygood** [comment]
> I am not sure about this. We still keep `versionchanged` directives for versions >= 3.0 in docs. Even if nobody currently uses Python 3.2, the old (and still working) code can have references to IOError.

That's a good point. `IOError` isn't mentioned anywhere else in the `chunk` docs, so I'll revert those changes. (`chunk` is also now deprecated, so probably not worth worrying about.)

`socket.error` is documented elsewhere in the module, though, so I think it makes sense to remove the note in the `socket` docs. Do you agree?

**Comment by AlexWaygood** [comment]
Thanks @ambv!

**Pull request merged**
