### PR TITLE
Doc: Simplify Copyright line in README

### PR DESCRIPTION
**Pull request by davidak**
This also makes it consistent with other places like:

- https://docs.python.org/dev/copyright.html
- https://www.python.org/ footer
- https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Python/getcopyright.c#L7

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by matrixise** [comment]
For me, it's ok, we have some references where the copyright by the PSF is from 2001-2018. We could merge it after the review of @VanL .

**Comment by VanL** [comment]
This is fine with me.

**Review by VanL — APPROVED** [review]

**Comment by Mariatta** [comment]
I beleieve there is an issue in bpo about the copyright. I'll have to look it up and link it here.

**Review by Mariatta — APPROVED** [review]

**Comment by ned-deily** [comment]
@Mariatta, Are you thinking of https://bugs.python.org/issue29555 ?  That also covers copyright dates in a number of modules.

**Comment by Mariatta** [comment]
Ah yeah that's the issue I was thinking.

**Review by gvanrossum — APPROVED** [review]
LGTM.

**Review by matrixise — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks @davidak and congrats on your first contribution to CPython :taco:

**Pull request merged**
