### PR TITLE
[3.10] gh-123693: Use platform-agnostic semantics when processing zipfile.Path.name.

### LINKED ISSUE #123693: zipfile.Path.name uses inappropriate Windows semantics
# Bug report

### Bug description:

In https://github.com/python/cpython/pull/123426#issuecomment-2324839726, we learned that Python 3.10 (only) ended up with a version of `zipfile.Path` that uses [`pathlib.Path` (platform-variable) behavior](https://github.com/python/cpython/blob/d3f39cefe721db643957d48316ac98c5e279f0c3/Lib/zipfile.py#L2441-L2443) for parsing the name. As a result, zipfiles with names like `V: foo` or `foo\bar` get incorrect names and are thus broken.

This issue was revealed by applying additional tests for GH-123270.

The issue was corrected incidentally in zipp 3.16.2 and Python 3.11. The issue does not affect Python 3.9.

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

### Linked PRs
* gh-123694

### PR DESCRIPTION
**Pull request by jaraco**
Depends on, merge after GH-123426.

- **[3.10] gh-123693: When computing the zipfile.Path.name, use PurePosixPath for platform-agnostic behavior.**

Closes #123693.

### CODE REVIEW

**Comment by jaraco** [comment]
Until this PR is rebased onto main after merging the dependent PR, here is the [diff for this PR](https://github.com/python/cpython/compare/refs/pull/123426/head...refs/pull/123694/head).

**Review by zooba — APPROVED** [review]
LGTM

**Comment by ambv** [comment]
You can rebase now.

**Comment by jaraco** [comment]
I've merged and the diff is now good. The macOS failure is unrelated. I did not rebase, as the squash merge will handle that. Please merge whenever.

**Pull request merged**
