### PR TITLE
bpo-44865: Missing translations in `argparse`

### PR DESCRIPTION
**Pull request by jdetrey**
A couple of other missing translations are addressed by #12711.

Incidentally, this also fixes a bug with the "(default: …)" help string of the `BooleanOptionalAction` class: when used with the `ArgumentDefaultsHelpFormatter`, a second "(default: …)" string would be added to the help text. This was due to the fact that the `default` value was immediately expanded in the help string, and thus wasn't detected as a "(default: …)" string by the `ArgumentDefaultsHelpFormatter._get_help_string()` method (which relies on finding a named format argument `%(default)` inside the help string).

https://bugs.python.org/issue44865

### CODE REVIEW

**Review by MaxwellDupre — APPROVED** [review]
All argparse tests ok.

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
It looks reasonable. Please resolve conflicts with the main branch.

If this fixes a bug, there should be tests.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution. For this PR and #12711. I apologize that it took a long time to review it.

**Comment by Tuahm** [comment]
Oke

Pada Sel, 27 Feb 2024 00.31, Serhiy Storchaka ***@***.***>
menulis:

**Comment by jdetrey** [comment]
No worries at all, @serhiy-storchaka! Thanks a lot for reviewing it and for the merge! :)

**Pull request merged**
