### PR TITLE
gh-84459: Make wording more specific for Path.replace

### PR DESCRIPTION
**Pull request by slateny**
#84459

Automerge-Triggered-By: GH:brettcannon

### CODE REVIEW

**Review by barneygale — CHANGES_REQUESTED** [review]
Could you also correct the docs for `os.replace()`? They're wrong in a slightly different way. Otherwise LGTM.

**Comment by slateny** [comment]
Used `non-empty` over `nonempty` as it seemed more common

**Review by barneygale — APPROVED** [review]

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
Thanks!

**Pull request merged**
