### PR TITLE
bpo-36236: Set a fatal error if the current path cannot be obtained

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue36236

### CODE REVIEW

**Comment by tirkarthi** [comment]
This might have a news entry since this crashes the interpreter on Mac OS while executing `python -m module_name` from a deleted directory.

**Comment by pablogsal** [comment]
@vstinner Not sure what is the best way to use `_Py_INIT_USER_ERR` here as this function (`_PyPathConfig_ComputeArgv0`) returns a `Pyobject*`.

**Comment by vstinner** [comment]
I don't think that the fix is correct: https://bugs.python.org/issue36236#msg337767

**Comment by pablogsal** [comment]
Superseded by #12424

**Pull request closed without merging**
