### PR TITLE
Mention build.bat counterpart in GH workflows error message

### PR DESCRIPTION
**Pull request by Fidget-Spinner**

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
@terryjreedy would you like me to create an issue for this as well (and add news) or do you feel that isn't necessary?

**Comment by terryjreedy** [comment]
@zooba  Just to make sure, is "build.bat --regen" the proper equivalent of "make regen-all"?

**Comment by ammaraskar** [comment]
> @zooba Just to make sure, is "build.bat --regen" the proper equivalent of "make regen-all"?

Not Steve but just wanted to say that it is indeed the correct command, see the PR it was added in for reference: https://github.com/python/cpython/pull/12654

> Adds an additional project to the PCbuild.sln that runs the equivalent commands that are in the `regen-all` stage in the Makefile.

**Review by ammaraskar — APPROVED** [review]

**Comment by terryjreedy** [comment]
Thank you. That confirms -regen is part of 3.9, so can backport this.

**Comment by terryjreedy** [comment]
Both backports merged.

**Pull request merged**
