### PR TITLE
Converted pyclbr.py to use f-string

### PR DESCRIPTION
**Pull request by l0r3m1psum**
There were two use of the old '%' string formatting and I changed
them to the modern f-string version.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@l0r3m1psum

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by brandtbucher** [comment]
Thanks for your time @l0r3m1psum, and welcome to CPython! :sunglasses:

**Review by brandtbucher — APPROVED** [review]
Technically, this looks fine. However, we typically don't accept many formatting or f-string changes without a good reason for doing so, since it just creates code churn without really improving anything except (arguably) readability.

I'll go ahead and approve this, and a core dev can make the call to accept this or not!

**Comment by l0r3m1psum** [comment]
Hey @brandtbucher thank you very much for approving my PR 😄. Ok I get the point, so even if I was working on a tool (that I will probably never finish) to convert all old string formatting to f-strings, a change like that would probably not be accepted right?

**Comment by brandtbucher** [comment]
Almost certainly not; while the tool seems useful enough on it's own (and interesting to build), I would discourage you from spending the time on it *just* to run it on CPython!

It would probably affect thousands of lines in hundreds of modules, making a lot of noise that's almost impossible to review.

**Comment by tirkarthi** [comment]
I agree with @brandtbucher . Similar changes like f-strings, pep8 style changes have been rejected in the past. Discussion about similar scenario in the past : https://bugs.python.org/issue38351

**Comment by csabella** [comment]
Hi @l0r3m1psum, thank you for your contribution and for your interest in improving CPython.  Based on the reasons already given, I'm going to close this without merging it.  Please take a look at bug tracker for other issues you might be interested in working on.  Thank you!

**Pull request closed without merging**
