### PR TITLE
bpo-37289: Remove 'if False' handling in the peephole optimizer

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue37289

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
What if `PyObject_IsTrue()` returns `-1`?

**Comment by pablogsal** [comment]
@serhiy-storchaka It goes to the break and skips to the next bytecode, right? I am missing something?

**Comment by serhiy-storchaka** [comment]
It should be handled as an error.

**Comment by pablogsal** [comment]
@serhiy-storchaka Done in 455cbc7

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
