### PR TITLE
gh-59795: distinct python-config from pkg-config python

### PR DESCRIPTION
**Pull request by haubi**
Fix output of 'python-config' for creating loadable Python modules.
Fix output of 'pkg-config python' for linking against the interpreter.

* Issue: gh-59795

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
could you please re base this or want new taker for this?

**Comment by ned-deily** [comment]
See more recent [bpo-36721](https://bugs.python.org/issue36721) which also addresses this area.

**Comment by vstinner** [comment]
> See more recent bpo-36721 which also addresses this area.

I'm not sure that bpo-36721 is related. Misc/python-config.sh.in still uses SYSLIBS, whereas Misc/python.pc.in doesn't.

**Review by iritkatriel — CHANGES_REQUESTED** [review]
This has merge conflicts now.

**Comment by haubi** [comment]
Unfortunately, meanwhile I have moved on to completely different tasks, and have neither the environment nor the time any more to look into that again: Feel free to pick up!

**Comment by erlend-aasland** [comment]
Meta: added GitHub links to OP and comments for easier navigation.

**Comment by erlend-aasland** [comment]
> Unfortunately, meanwhile I have moved on to completely different tasks, and have neither the environment nor the time any more to look into that again: Feel free to pick up!

In that case, I propose to close this PR. If anybody wants to pick this up, they'll be better off by starting from scratch; the build system has seen huge changes the recent years.

We should also consider closing the linked issue; I'm unsure if this is a real problem anymore.

**Pull request closed without merging**
