### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by Amanjot726**

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Hello! Thanks for taking the time to make this PR. You might want to read the [python devguide](https://devguide.python.org/) if you're just starting out. 

According to the devguide, [using either one or two spaces after a period is valid](https://devguide.python.org/documenting/#style-guide). So the current documentation is valid.

I hope you're not discouraged by this, and I'm looking forward to your contributions :).

**Review by MYavuzYAGIS — COMMENTED** [review]
It would be nicer if you write a script to automate this. Thx!

**Comment by Fidget-Spinner** [comment]
@MYavuzYAGIS no it wouldn't be nice to write a script to automate this. Please don't automate this as two spaces after a period is correct in reStructuredText documentation.

**Comment by MYavuzYAGIS** [comment]
> @MYavuzYAGIS no it wouldn't be nice to write a script to automate this. Please don't automate this as two spaces after a period is correct in reStructuredText documentation.

@Fidget-Spinner hey thx for clarification, my bad on bad advice on that end.
But I hope you got my point there. Peace🤞

**Pull request closed without merging**
