### PR TITLE
Example docs had missing values

### PR DESCRIPTION
**Pull request by alfiedotwtf**

### CODE REVIEW

**Comment by alfiedotwtf** [comment]
Can't seem to find how to add the "skip issue" tag.

**Comment by tinomist** [comment]
im a dumb ass idk what u guys do

**Comment by tinomist** [comment]
i mean that u guys  no your stuff help

**Comment by tinomist** [comment]
u the good guys or bad i hope good

**Comment by asvetlov** [comment]
The PR is wrong: `{'spam', 'bacon'} & {'eggs', 'bacon', 'salad'} == {'bacon'}`

**Comment by alfiedotwtf** [comment]
Gah! Sorry, my brain skipped the del() in the proceeding lines!

**Comment by Mariatta** [comment]
I deleted a few inappropriate comments in this PR. Please consider this a warning.

**Pull request closed without merging**
