### PR TITLE
bpo-44291: Fix reconnection in logging.handlers.SysLogHandler (GH-26490)

### PR DESCRIPTION
**Pull request by cybergrind**
https://bugs.python.org/issue44291

`./python -m test test_logging  -m SysLogHandlerTest`

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@cybergrind

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by cybergrind** [comment]
Hi, @vsajip Not sure where is better to remind about PR. It would be great if you could look into it

**Comment by vsajip** [comment]
Hi Kirill, sorry I haven't been able to get to it thus far. I hope to be able to review this soon - say by the middle of next week; this week I am very busy on other stuff that is more urgent. Thanks for your patience.

**Comment by vsajip** [comment]
Closing and reopening to re-run stalled checks.

**Comment by sahilsangani98** [comment]
Is this issue resolved with Python version 3.9 as well? 

If no, how to resolve this error with Python version 3.9 as I can't upgrade my services with Python 3.11.

It will be really appreciated if someone can guide me on this.

@cybergrind cybergrind
@vsajip 
@alex

**Comment by vsajip** [comment]
Simplest: Why not copy the handler from 3.11 to your own code and use that?

**Pull request merged**
