### PR TITLE
bpo-36064: Clarify allowed data types for urllib.request.Request.

### PR DESCRIPTION
**Pull request by JulienPalard**
https://bugs.python.org/issue36064

### CODE REVIEW

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Review by eamanu — APPROVED** [review]
lgtm

**Review by willingc — APPROVED** [review]
Thanks!

**Comment by willingc** [comment]
Thanks @JulienPalard for the PR and @tirkarthi and @eamanu for the reviews. :cookie:

**Comment by tirkarthi** [comment]
I hope this can be backported to 3.7 ?

**Pull request merged**
