### PR TITLE
Remove unused internal _PyImport_GetModuleId() function

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by ericsnowcurrently** [comment]
FTR, here's Victor's PyPI search:  https://github.com/python/cpython/pull/107213#issuecomment-1648840363

**Review by ericsnowcurrently — APPROVED** [review]
Assuming no external modules (or embedders) are using this, LGTM.

**Comment by vstinner** [comment]
Hum, the CLA Signing job was blocked. So I closed/reopened my PR and also rebased it on the main branch. Let's see if this time, the job starts.

**Comment by vstinner** [comment]
> [docs/readthedocs.org:cpython-previews — Read the Docs build failed!](https://readthedocs.org/projects/cpython-previews/builds/21404205/)

Strange. Python ``.readthedocs.yaml`` uses ``exit 183`` if the Python Documentation was not changed and so it's not needed to build the documentation, and this exit code is [documented by ReadTheDocs](https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition) as "skip the build"

**Comment by vstinner** [comment]
> Strange. Python .readthedocs.yaml uses exit 183 if the Python Documentation was not changed and so it's not needed to build the documentation, and this exit code is documented by ReadTheDocs as "skip the build"

I reported the issue to ReadTheDocs bug tracker: https://github.com/readthedocs/readthedocs.org/issues/10567

**Comment by vstinner** [comment]
> Assuming no external modules (or embedders) are using this, LGTM.

I checked again: I found no user in PyPI top 5,000 projects (2023-07-04):

```
$ ./search_pypi_top.py PYPI-2023-07-04/ '_PyImport_GetModuleId' -q
PYPI-2023-07-04/fastobo-0.12.2.tar.gz: fastobo-0.12.2/crates/pyo3-ffi/src/cpython/import.rs: // skipped _PyImport_GetModuleId
PYPI-2023-07-04/orjson-3.9.1.tar.gz: orjson-3.9.1/include/cargo/pyo3-ffi-0.19.0/src/cpython/import.rs: // skipped _PyImport_GetModuleId

Time: 0:00:39.023925
Found 2 matching lines in 2 projects
```

The 2 results are only **comments** to say that PyO3-ffi has no binding for _PyImport_GetModuleId().

**Comment by vstinner** [comment]
I closed/reopened again the PR to trigger a new ReadTheDocs job. Right now, [the job](https://readthedocs.org/projects/cpython-previews/builds/21404472/) is failing with:

> Concurrency limit reached (2), retrying in 5 minutes.

**Pull request merged**
