### PR TITLE
[3.11] gh-124651: Quote template strings in `venv` activation scripts (GH-124712) (GH-126185)

### PR DESCRIPTION
**Pull request by vstinner**
(cherry picked from commit d48cc82ed25e26b02eb97c6263d95dcaa1e9111b) (cherry picked from commit 8450b2482586857d689b6658f08de9c8179af7db)

* Issue: gh-124651

### CODE REVIEW

**Comment by vstinner** [comment]
@vsajip: Would you mind to review this backport to 3.11?

Again, I had conflicts in `Lib/venv/scripts/common/activate`. I had to fix manually the conflicts.

**Review by vsajip — APPROVED** [review]

**Comment by vstinner** [comment]
@pablogsal: Would you mind to merge/review this security fix?

**Comment by pablogsal** [comment]
Yup

**Review by Harry-gill — COMMENTED** [review]
hh

**Pull request merged**
