### PR TITLE
bpo-33764: Appveyor fixes

### PR DESCRIPTION
**Pull request by zware**
https://bugs.python.org/issue33764

### CODE REVIEW

**Comment by zware** [comment]
It appears that AppVeyor is not accepting builds from us at the moment; I'm not sure why.  I've tested this on my own clone (zware/cpython#8), though, and from a sample size of one it appears to both speed up the build and prevent the crash.

@terryjreedy if this comes unblocked and I haven't already done it, please feel free to merge.

**Comment by vstinner** [comment]
I closed my PR #7368 as a duplicate of this one.

**Comment by vstinner** [comment]
And now we cannot merge this PR because of https://bugs.python.org/issue33765 ? AppVeyor, you are not funny with us :-( Is a Python release manager allowed to merge such change? @ned-deily?

**Comment by vstinner** [comment]
It would be nice to see a new AppVeyor build with this new configuration, before merging backports.

**Pull request merged**
