### PR TITLE
gh-108303: Move all XML-related test files to `test_xml`

### PR DESCRIPTION
**Pull request by sobolevn**
There should be a lot of changed files, but history should be clean.

* Issue: gh-108303

----
📚 Documentation preview 📚: https://cpython-previews--114344.org.readthedocs.build/

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
test_xmlrpc and test_docxmlrpc are not XML tests.

**Comment by serhiy-storchaka** [comment]
I do not think that it is worth to do. Unlike to `asyncio` or `email`, `xml` is not a single package. It is a set of unrelated packages in a common parent namespace.

**Comment by sobolevn** [comment]
@serhiy-storchaka sorry, I don't agree. They might have any implementation details, but they are still sharing the same namespace and they use the same fixture files. It is logical for test to have the same namespaces as regular code does.

**Comment by sobolevn** [comment]
@vstinner I tried to remove `xmltestdata/` directory, but I didn't go too well.
Since it relies on some exotic line-ending rules and possibly other magic stuff, I would say that keeping it as-is the same simplest and the safest thing we can do.

**Review by vstinner — CHANGES_REQUESTED** [review]
I suggest to close this issue.

There are different aspects:

* Is it possible to run individual tests separately? Like `test_xml.test_test_minidom`. Yes, it's possible.
* Does the change increase parallelism of tests, or make it worse? Same, since regrtest splits `test_xml` into sub-tests to run them in parallel.
* Are these sub-tests related? How? Well, there are related to "XML". Their _implementations_ are unrelated. `xml.minidom` *implementation* has nothing to do with `xml.etree`.

@sobolevn:
> they are still sharing the same namespace and they use the same fixture files. It is logical for test to have the same namespaces as regular code does.

We have many "os-like" and "socket-like" tests in separated tests, and that's why we have helpers such as `support.os_helper` and `support.socket_helper`. I don't buy the argument "putting everything at the same place is better".

While it's very tempting to put "everything related to XML" in a test package, for this change, I prefer to stick to the status quo: "flat namespace is better than nested" (PEP 20) :-)

Not changing tests keeps the Git history linear (no custom command line option needed) and avoids developers to change their habits. I don't think that the benefits are way higher than drawbacks (moving code).

Test files are already in the `xmltestdata` directory.

**Comment by sobolevn** [comment]
Ok, sounds convincing 👍

**Pull request closed without merging**
