### PR TITLE
Revert "bpo-46329: Split calls into precall and call instructions."

### PR DESCRIPTION
**Pull request by pablogsal**
Reverts python/cpython#30855

https://bugs.python.org/issue46329

### CODE REVIEW

**Comment by pablogsal** [comment]
CC: @markshannon @brandtbucher

**Comment by brandtbucher** [comment]
#31005 probably needs to be reverted with this as well.

**Comment by brandtbucher** [comment]
#31005 probably needs to be reverted with this as well.

**Comment by pablogsal** [comment]
> #31005 probably needs to be reverted with this as well.

Yep, I just pushed the commit :)

**Comment by pablogsal** [comment]
> #31005 probably needs to be reverted with this as well.

👍  Yep, I just pushed the commit.

**Pull request closed without merging**
