### PR TITLE
bpo-33722: Add documentation to unittest.mock.mock_open

### PR DESCRIPTION
**Pull request by jcrotts**
https://bugs.python.org/issue33722

### CODE REVIEW

**Comment by tirkarthi** [comment]
This PR contains changes from https://github.com/python/cpython/pull/5179 though it was merged to master. The examples looks like a reasonable addition to me. Can you please try rebasing with latest master?

**Comment by gvanrossum** [comment]
Don’t request reviews from the whole world.

**Comment by jcrotts** [comment]
My Mistake, Not sure where I even requested a review?

**Comment by gvanrossum** [comment]
I recommend you open a new PR with just the changes you want.  Probably need to update your fork somehow.

**Pull request closed without merging**
