### PR TITLE
gh-91276: Make JUMP_IF_TRUE_OR_POP/JUMP_IF_FALSE_OR_POP relative

### PR DESCRIPTION
**Pull request by iritkatriel**
https://bugs.python.org/issue47120

### CODE REVIEW

**Comment by markshannon** [comment]
We could handle this in the assembler, I guess.
```
JUMP_IF_TRUE_OR_POP back
```
Would become
```
COPY 1
POP_JUMP_IF_FALSE back
POP_TOP
```
As long as backward jumps are rare (and they will be), then this wouldn't add any real overhead.

**Comment by iritkatriel** [comment]
> Are you completely sure it is impossible for the compiler to generate a backwards branch for these instructions?

I put an assertion and all tests passed. But yeah, we can make it more rubust as you suggest.

**Comment by iritkatriel** [comment]
Closing and reopening to kick the bots.

**Comment by iritkatriel** [comment]
Buildbots are happy.

**Pull request merged**
