### PR TITLE
bpo-33654: Support BufferedProtocol in set_protocol() and start_tls()

### PR DESCRIPTION
**Pull request by 1st1**
https://bugs.python.org/issue33654

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]
looks good

**Comment by asvetlov** [comment]
hmm, windows tests are failing

**Comment by 1st1** [comment]
Yes, i'll be looking into win issues before merging.

**Comment by 1st1** [comment]
@asvetlov please take a look at the 0238da4 -- I think I fixed the windows issue

**Comment by asvetlov** [comment]
Wow, nice.
Waiting for merge.

**Pull request merged**
