### PR TITLE
bpo-39684: Combine two if/thens

### PR DESCRIPTION
**Pull request by petdance**
These two code if/thens can be combined

    if (ready) {
        kind = PyUnicode_KIND(self);
        data = PyUnicode_DATA(self);
    }
    else {
        wstr = _PyUnicode_WSTR(self);
    }

    Py_UCS4 ch;
    if (ready) {
        ch = PyUnicode_READ(kind, data, 0);
    }
    else {
        ch = wstr[0];
    }

https://bugs.python.org/issue39684

### CODE REVIEW

**Comment by ericvsmith** [comment]
This  change looks good to me.

**Comment by petdance** [comment]
Unfortunately it fails the macOS tests.  I've been able to recreate it, and I'm investigating why it happens.

**Comment by petdance** [comment]
The macOS failures were because of https://bugs.python.org/issue38691

They're now passing once I merged the reverted changes to the branch.

**Comment by gvanrossum** [comment]
Something went wrong with git. You should probably fetch from upstream and rebase.

**Comment by petdance** [comment]
> Something went wrong with git. You should probably fetch from upstream and rebase.

That's exactly what I did, and then pushed it.

**Comment by petdance** [comment]
I can go make a new branch+PR if that would be better.

**Comment by gvanrossum** [comment]
Then can you ask for git help somewhere? The PR definitely doesn’t look
right (click on Changes to see for yourself — it should *only* show your
changes, but it shows other things) and all I have here is a phone.
-- 
--Guido (mobile)

**Comment by petdance** [comment]
New branch coming soon.

**Pull request closed without merging**
