### PR TITLE
bpo-37129: Add os.RWF_APPEND flag for os.pwritev

### PR DESCRIPTION
**Pull request by YoSTEALTH**
Recreated https://github.com/python/cpython/pull/13735

https://bugs.python.org/issue37129

### CODE REVIEW

**Review by gpshead — APPROVED** [review]

**Comment by YoSTEALTH** [comment]
I am not sure what the error is anymore...

**Comment by vstinner** [comment]
> I am not sure what the error is anymore...

Please run `./python Tools/clinic/clinic.py -f Modules/posixmodule.c` and then commit updated generated files.

**Comment by vstinner** [comment]
Thanks @YoSTEALTH, I merged your PR. It's nice to see new features for these cool functions ;-)

**Comment by YoSTEALTH** [comment]
@vstinner thanks for merging :)

**Pull request merged**
