### PR TITLE
bpo-39041: Add GitHub Actions support

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue39041

### CODE REVIEW

**Review by brettcannon — APPROVED** [review]
Should make sure to add doc-building workflow. I would also build against `-latest` for the OSs. And I think you might be able to use `${runs-on}` as the title so it states the OS that way.

**Comment by zooba** [comment]
I changed the VM images to "latest", but it still seems best to have static labels. I also added the coverage test run after we know the Ubuntu tests have passed, but I don't know that we'll want the extra delay.

Maybe if I split it into a separate check we can make the coverage run optional? We'll have to merge this one first though. Once I get the docs workflow in then we can do that and iterate on the coverage run.

**Comment by brettcannon** [comment]
Yeah, I would split the coverage run out as a separate thing as we don't rely on it to prevent coverage slippage.

**Comment by zooba** [comment]
From my other PR (where I've enabled the builds), it looks like this:
image

**Pull request merged**
