### PR TITLE
bpo-33746: Fix test_unittest in verbose mode

### PR DESCRIPTION
**Pull request by vstinner**
Skip TestBreak.testRegisterResult() when run in verbose mode.

support._run_suite() uses TextTestRunner in verbose mode, but
TextTestRunner.run() calls registerResult(result) which makes the
test fail with "odd object in result set".

https://bugs.python.org/issue33746

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
I'm not sure about the purpose of this test.

Wouldn't be better to save the content of `unittest.signals._results` before calling `unittest.registerResult()` and check that `unittest.registerResult(result)` adds `result` and only it to this set?

**Comment by serhiy-storchaka** [comment]
@voidspace

**Comment by vstinner** [comment]
I merged master into my PR to reschedule CI jobs.

**Comment by vstinner** [comment]
> Wouldn't be better to save the content of unittest.signals._results before calling unittest.registerResult() and check that unittest.registerResult(result) adds result and only it to this set?

I created an alternative fix: PR #7389.

**Comment by vstinner** [comment]
Abandonned, I will merge PR #7799 instead.

**Pull request closed without merging**
