### PR TITLE
Optimized Images in repo

### PR DESCRIPTION
**Pull request by manishprivet**
# Optimized Images

Optimized .png and .svg images in repo by 11.69% using IMGBot.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@manishprivet, @ImgBotApp

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by merwok** [comment]
@methane you ran optipng before, maybe you’re interested in reviewing this :slightly_smiling_face:

**Comment by methane** [comment]
Thank you for proposing it.  I have not known IMGbot.

Before merging this pull request, I made a suggestion about installing IMGBot app on this repository.
See https://discuss.python.org/t/optimize-images-by-imgbot/4672

**Comment by manishprivet** [comment]
I guess there's some problem on the b.p.o site, as after registration, when I clicked on the link in confirmation email, it only showed <br> **Invalid URL scheme in homepage URL**,<br>and my email isn't registered yet.

bpo error

**Comment by csabella** [comment]
@manishprivet, please sign the CLA.  Thank you!

**Comment by manishprivet** [comment]
> @manishprivet, please sign the CLA. Thank you!

Done. My B.P.O. username is `user35899` and Login name is `manishprivet1`, but it's still showing CLA Not Signed [here](https://check-python-cla.herokuapp.com/)

**Comment by terryjreedy** [comment]
When did you sign?  (It can take up to a week to get recorded.) You are 'User35899', but your *username* is your login name, and I am pretty sure that the latter is what you need to put on the form.

Since you have never used the older 'manishprivet', it might be possible to delete it, except I don't know who to ask.

**Comment by manishprivet** [comment]
I signed it today itself.
image

**Comment by manishprivet** [comment]
I don't understand, why's the bot automatically adding the label

**Comment by zware** [comment]
The CLA check is failing because one of the commits is from `ImgBotApp`, not `manishprivet`.  The CLA must be signed by all authors/committers represented in the commits, not just the user who opened the pull request.

**Comment by terryjreedy** [comment]
I verified that manishprivet's CLA is now registered.  The Knight's comment is misleading at it removed the label after the enquiry and then re-added it because of ImgBotApp.   After reading the ImgBot User Agreement and Doc, I believe we could legitimately merge this without formally adding it to CPython repository.  (See  https://discuss.python.org/t/optimize-images-by-imgbot/4672.)  But I would prefer one of the Python administrators to clear this.  I don't know who they are.

 I will close and reopen to try to get clearance from Travis.  The Travis config was redone in Sept.

I think we can skip issue and news.

**Review by hugovk — APPROVED** [review]
I visually inspected and the images are still the same.

**Comment by hugovk** [comment]
Closing/re-opening to poke the CI.

**Comment by hugovk** [comment]
✅ CI now green. 

If we don't want commits from @ImgBotApp (but https://discuss.python.org/t/optimize-images-by-imgbot/4672 would be nice, I use it on other repos), we can easily make a new PR after running something like:

```
find . -type f -iname "*.png" -exec optipng -o7 -zm1-9 {} \;
```

Saves about 17.5%.

**Pull request merged**
