### PR TITLE
gh-97669: Remove abitype.py and pep384_macrocheck.py

### PR DESCRIPTION
**Pull request by vstinner**
Remove abitype.py and pep384_macrocheck.py scripts of Tools/scripts/.

* Issue: gh-97669

### CODE REVIEW

**Comment by vstinner** [comment]
> Remove abitype.py and pep384_macrocheck.py scripts of Tools/scripts/.

@encukou @erlend-aasland @corona10: Did one of you ever use one of these scripts? If not, I don't think that they are still relevant.

I didn't know these scripts but I ported many C extensions to heap types, module state and multi-phase init API. I was fine to do a few changes manually.

**Comment by erlend-aasland** [comment]
> Did one of you ever use one of these scripts?

I know about their existence, and I've had a look at them, but I've never used them. Porting C extension modules to module state is not straight-forward.

**Comment by encukou** [comment]
I've never used them. They seem untested and unused. Let's remove them and if anyone complains, improve them or add the check to CI.

**Review by erlend-aasland — APPROVED** [review]

**Comment by vstinner** [comment]
Ok, I removed them. As written in the doc, a copy can be found in the https://github.com/gvanrossum/old-demos project.

Doc: https://docs.python.org/dev/whatsnew/3.12.html#demos-and-tools

> I've never used them. They seem untested and unused. Let's remove them and if anyone complains, improve them or add the check to CI.

Right, no doc, no test.

**Comment by corona10** [comment]
Oh, I am late, but I never used them. I even don't know their existence.

**Pull request merged**
