### PR TITLE
bpo-38219: Optimize dict creating and updating by a dict.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue38219

### CODE REVIEW

**Review by eamanu — APPROVED** [review]
Lgtm. I test it in a Debian 9 I can see the reduction of time on creating and updating dicts

**Review by methane — APPROVED** [review]
LGTM

**Comment by ammaraskar** [comment]
Hmm, not sure if I'm missing it but it seems like there's no direct test for a dict constructed from another dict. i.e `dict({'a': 1})` or similar in `test_dict.py`.

`test_missing` and the fact that this code is shared with `dict.update` seems to be in-directly exercising the path. Might be useful to introduce one while you're performing just to avoid future breakage.

**Comment by serhiy-storchaka** [comment]
There are many tests for a dict constructed from another dict:
```
Lib/test/test_dict.py:18:
  for invalid in {1 : 2}, Custom({1 : 2}):
Lib/test/test_dict.py:692:
  d = D({1: 2, 3: 4})
Lib/test/test_dict.py:1193:
  d.update(self.__dict__)
Lib/test/test_dict.py:886:
  dd.update(d)
Lib/test/test_dict.py:891:
  dd.update(d)
Lib/test/test_dict.py:141:
  d.update({1:100})
Lib/test/test_dict.py:142:
  d.update({2:20})
Lib/test/test_dict.py:143:
  d.update({1:1, 2:2, 3:3})
Lib/test/mapping_tests.py:46:
  p1 = dict(p) #workaround for singleton objects
Lib/test/mapping_tests.py:176:
  d.update(self.other)
Lib/test/mapping_tests.py:103:
  p.update(self.reference)
Lib/test/mapping_tests.py:104:
  self.assertEqual(dict(p), self.reference)
Lib/test/mapping_tests.py:108:
  self.assertEqual(dict(p), self.reference)
```

**Comment by ammaraskar** [comment]
Sorry, I should have been more clear: I meant a dict constructed from the base dict object on the right since the check in this code is a `PyDict_CheckExact`. It does seem like `test_invalid_keyword_arguments` and `mapping_tests.py` should provide adequate coverage.

**Comment by serhiy-storchaka** [comment]
All lines above are lines where the dict is directly created or updated from the base dict object in test_dict. So there is enough coverage.

**Pull request merged**
