### PR TITLE
CI: Make macOS Intel required to succeed

### PR DESCRIPTION
**Pull request by hugovk**
Intel-based macOS aka `build_macos` aka `x86_64-apple-darwin` is [Tier 1 in PEP 11](https://peps.python.org/pep-0011/#tier-1), which means:

- CI failures block releases.
- Changes which would break the `main` branch are not allowed to be merged; any breakage should be fixed or reverted immediately.
- All core developers are responsible to keep `main`, and thus these platforms, working.
- Failures on these platforms block a release.

Let's remove it from the "allowed to fail" list so that it is "required to succeed".

(Windows x86 (32-bit) aka `build_win32` aka `x86_64-pc-windows-msvc` is also Tier 1, but I'm not making it required in this PR because some tests are still flaky.)

---

Also remove EOL Python 3.7 from the list of branches. (Or we probably only need bugfix and newer, 3.11+.)

### CODE REVIEW

**Comment by vstinner** [comment]
Be careful: there is known bug on macOS: https://github.com/python/cpython/issues/110083

**Comment by vstinner** [comment]
In terms of performance, the GHA macOS now seem to have good performance, between Linux and Windows:

* Ubuntu: 13 min (tests: ``Total duration: 11 min 11 sec``)
* macOS: **17 min** (tests: ``Total duration: 13 min 28 sec``)
* Windows x64: 27 min (tests: `Total duration: 22 min 59 sec`)

**Comment by hugovk** [comment]
> Be careful: there is known bug on macOS: #110083

Shall we wait until it's fixed?

**Comment by vstinner** [comment]
> Shall we wait until it's fixed?

I didn't check the failure rate. So far, the job was non-voting (didn't block a PR if it failed). I'm tracking too many tests: https://github.com/python/cpython/issues/vstinner :-)

**Comment by vstinner** [comment]
cc @sobolevn

**Pull request merged**
