### PR TITLE
bpo-32636: Fix @asyncio.coroutine debug mode bug exposed by #5250

### PR DESCRIPTION
**Pull request by njsmith**
None

https://bugs.python.org/issue32636

### CODE REVIEW

**Review by 1st1 — APPROVED** [review]

**Comment by 1st1** [comment]
@Mariatta Sorry for bothering you, but what to do when Bedevere bot is stuck? :)

**Comment by Mariatta** [comment]
I'll try closing and reopening again 😛  Sorry for the noise.

**Comment by Mariatta** [comment]
Hmm not sure. I'll have to read code, once I have the chance a little later.

**Comment by 1st1** [comment]
@Mariatta should we re-submit this patch?

**Comment by Mariatta** [comment]
Hold on before re-submitting a patch. I wanna debug bedevere and find out the issue. Thanks. Will keep you updated.

**Comment by Mariatta** [comment]
There's 500 error with the webhook for this particular PR. I will take a further look.

**Comment by Mariatta** [comment]
I found the issue. The error arised in this specific situation of title edited and the PR does not contain any description (`body` is None). Bedevere assumed that there would be a `body` in the PR.
Fixed in https://github.com/python/bedevere/pull/79

**Comment by 1st1** [comment]
Thanks so much, @Mariatta!

**Comment by Mariatta** [comment]
@1st1 @njsmith All checks passed!

**Comment by 1st1** [comment]
Thanks @Mariatta!

**Pull request merged**
