### PR TITLE
gh-114965: Updated bundled pip to 24.0

### PR DESCRIPTION
**Pull request by sbidoul**
* Issue: gh-114965

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
SBOM updates LGTM, hope the experience was straightforward :)

**Review by pfmoore — APPROVED** [review]

**Comment by pfmoore** [comment]
@sethmlarson I thought the idea of the new SBOM stuff was that we *didn't* have to change the SBOM data for a pip release?

I'm going to assume you've reviewed that as I don't know what I'd check. Also, won't the SBOM data impact the automatic backports? I'll add the "needs backport" labels once this is merged, but if backports are going to neeed manual intervention on an ongoing basis, that's a bit awkward 🙁

**Comment by sbidoul** [comment]
@sethmlarson the SBOM procedure went well, although the CI had to remind me to do it, of course :) That's a small additional burden in the pip release process, especially the manual entry of the checksums. Any chance to automate that further?

Regarding the backport, I'm stuck because cherry_picker says I'm not in a cpython repo. I do have the `upstream` remote pointing to the right place, it's the same cpython local clone I used before. Any idea what where I could look to resolve this?

**Comment by sbidoul** [comment]
> Regarding the backport, I'm stuck because cherry_picker says I'm not in a cpython repo

I could make it work with an older version of cherry_picker.

**Comment by hugovk** [comment]
> Regarding the backport, I'm stuck because cherry_picker says I'm not in a cpython repo. I do have the `upstream` remote pointing to the right place, it's the same cpython local clone I used before. Any idea what where I could look to resolve this?

Sounds like this bug, Cherry Picker is swallowing warnings and issuing a misleading one:

https://github.com/python/cherry-picker/issues/99

**Comment by pfmoore** [comment]
@sethmlarson gentle ping on the SBOM question

**Comment by sethmlarson** [comment]
@pfmoore @sbidoul I've [opened an issue](https://github.com/python/release-tools/issues/91) that would move pip's automated discovery into the CPython release process, rather than the source repository, since pip is a special case as I noted above. Let me know if this proposal makes sense to you. Apologies to you both for the extra burden the past two releases have been. I've tried to optimize for as little manual work as possible, in many cases a bit is unavoidable but for pip it should be.

**Pull request merged**
