### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by tirkarthi**

### CODE REVIEW

**Comment by tirkarthi** [comment]
I am not a native English speaker I think it should be "Apple's guidelines" instead of "Apple guidelines" in idlelib.

**Comment by matrixise** [comment]
Do we need a back port to 3.7?

**Comment by tirkarthi** [comment]
Except for "guidlines" in idlelib the other two are 3.8 only.

**Comment by csabella** [comment]
@terryjreedy usually likes to make the IDLE doc fixes into their own separate PR, so you may want to wait for him to comment.

**Comment by terryjreedy** [comment]
My typo, thanks for catching.  Nouns can be used as adjectives, so 'Apple guidelines' is OK, with a slightly different sense from 'Apple's guidelines'.  But I will consider opinions on which seems better, especially for beginners.

Changes to idle.rst should not only be backported, but need to be propagated to idlelib/help.html, which change also should be backported.  It is easier to do it in a separate PR, which I will do.

**Comment by tirkarthi** [comment]
> Changes to idle.rst should not only be backported, but need to be propagated to idlelib/help.html, which change also should be backported. It is easier to do it in a separate PR, which I will do.

Do you want me to revert idlelib changes from this PR? The other two typos are 3.8 only. Hence backport might require manual work.

**Comment by terryjreedy** [comment]
Follow-up is #13354.

**Comment by tirkarthi** [comment]
Thanks @terryjreedy

**Pull request merged**
