### PR TITLE
bpo-24234: fix bytes.__bytes__ to not truncate at a zero byte

### PR DESCRIPTION
**Pull request by mdickinson**
Fixes buildbot failures introduced in GH-27901.

https://bugs.python.org/issue24234

### CODE REVIEW

**Review by corona10 — APPROVED** [review]
@mdickinson Thank you for quick fix 👍 
LGTM

**Comment by mdickinson** [comment]
The s390x buildbot is reporting:

> test_typing leaked [1, 1, 1] memory blocks, sum=3

**Comment by corona10** [comment]
@mdickinson Other Refleak tests doesn't report the issue :(

**Comment by mdickinson** [comment]
I'll merge anyway - this change is obviously needed. The Arch Linux buildbot failure looks unrelated, and has been happening for a while. We can keep an eye on the s390x buildbot for a while to see if the test_typing refleak is persistent.

**Pull request merged**
