### PR TITLE
gh-104773: PEP 594: Remove the aifc module

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-104773

----
:books: Documentation preview :books:: https://cpython-previews--104933.org.readthedocs.build/

### CODE REVIEW

**Comment by hugovk** [comment]
Can we remove these test files as well?

```
./Lib/test/audiodata/pluck-ulaw.aifc
./Lib/test/audiodata/pluck-alaw.aifc
./Lib/test/Sine-1000Hz-300ms.aif
```

**Comment by vstinner** [comment]
Someone else wrote a less complete PR: PR #104927.

**Comment by vstinner** [comment]
> Can we remove these test files as well?

Right. I remove these test files and a few more.

**Comment by vstinner** [comment]
With this change, test_wave becomes the last user of ``Lib/test/audiotests.py``. I don't think that it's worth it to move the code into Lib/test/test_wave.py. I prefer to leave it as it is for now.

The two remaining AIFC test files are used by test_email:

```
Lib/test/test_email/data/sndhdr.aifc
Lib/test/test_email/data/sndhdr.aiff
```

**Review by hugovk — APPROVED** [review]

**Comment by vstinner** [comment]
The ``chunk`` module is related to AIFF: I wrote PR #104868 to remove it.

**Comment by vstinner** [comment]
I added a What's New in Python 3.13 and Changelog entry.

**Comment by vstinner** [comment]
See also issue #105096:  wave: Deprecate getmark(), setmark() and getmarkers() methods.

**Pull request merged**
