### PR TITLE
gh-107262: update Tkinter tests for 8.6.14

### PR DESCRIPTION
**Pull request by DBJim**
Update test assertions to pass with the changed behavior in Tk 8.6.14.

These two assertions are now only tested when the fixed Tk version is used, and it now tests for the correct result.

The tests are now passing locally on windows 64 bit when built with 8.6.14, which I hope should allow #116145 to progress for Windows.

Since it only changes the tests, I think news can be skipped.

* Issue: gh-107262

### CODE REVIEW

**Comment by DBJim** [comment]
Hi @serhiy-storchaka, Would you mind taking a look? Let me know if you prefer to approach differently

**Review by serhiy-storchaka — COMMENTED** [review]
Thank you for your PR. I will look at this closer after I build Tcl/Tk 8.6.14.

I think that it is worth to keep tests for older Tk versions, which can still be in use. For example:
```py
            self.checkParam(widget, 'padding', (5, 6, 7),
                            expected=(5, 6, 7) if patchlevel >= (8, 6, 14) else ('5', '6', '7'))
```
You should also run the tests after manually changing `wantobjects = 1` to `wantobjects = 0` in `Lib/tkinter/__init__.py` (unfortunately there is not option to do this without manual modification of the sources) and ensure that they are still passed.

So the final code could look rather like:
```py
            self.checkParam(widget, 'padding', (5, 6, 7),
                            expected=('5', '6', '7') if self.wantobject or patchlevel < (8, 6, 14) else (5, 6, 7))
```

**Review by serhiy-storchaka — APPROVED** [review]
I updated tests, so they now pass with older Tcl/Tk.

**Comment by serhiy-storchaka** [comment]
@DBJim, thank you for your contribution.

Maybe you're new to Git? I noticed that you made these changes in the `main` branch. This makes it difficult for you to generate other PRs. You should create a new branch from the `main` branch, commit all changes to that branch, and create a PR from that branch. This allows you to work on several PRs at the same time and preserves your `main` branch.

**Pull request merged**
