### PR TITLE
[3.9] bpo-40854: Allow overriding sys.platlibdir via PYTHONPLATLIBDIR env-var (GH-20605)

### PR DESCRIPTION
**Pull request by vstinner**
(cherry picked from commit 8f023a2f664f902a3d0b7a6f64d63afc0d1c15ae)

https://bugs.python.org/issue40854

### CODE REVIEW

**Comment by vstinner** [comment]
bpo-1294959 added sys.platlibdir and configure --with-platlibdir to use /usr/lib64 on Fedora and SuSE to Python 3.9.  The problem is that https://bugs.python.org/issue40854#msg370655 use case seems to be a regression compared to Python 3.9.

I now consider to backport the commit 8f023a2f664f902a3d0b7a6f64d63afc0d1c15ae to 3.9 since it looks like a fix part of bpo-1294959 rather than a bug fix.

I created this PR to backport PyConfig.platlibdir and PYTHONPLATLIBDIR env var to Python 3.9.

@ambv: Are you ok to include this change in Python 3.9 final?

cc @hroncok @mcepl @stratakis

**Comment by vstinner** [comment]
If this PR is merged, the documentation must be updated in the master branch to replace "3.9" with "3.10" (as I did in this backport).

**Comment by ambv** [comment]
I'm fine with this landing in 3.9.0 but unless it lands within the next hour or so it will miss Beta 2.

**Comment by mcepl** [comment]
LGTM, but, boy, this is getting really complicated! Originally, it was just a simple few lines hack …

**Comment by vstinner** [comment]
> LGTM, but, boy, this is getting really complicated! Originally, it was just a simple few lines hack …

A hack is acceptable for a downstream patch. But upstream, we usually write things differently and it requires more work. Also, when a feature is made upstream, new corner cases are discovered :-)

See also https://bugs.python.org/issue40684 "make install doesn't respect configure --with-platlibdir=lib64".

**Comment by vstinner** [comment]
> I'm fine with this landing in 3.9.0 but unless it lands within the next hour or so it will miss Beta 2.

Ok, I merged my PR. Thanks @ambv ;-)

**Comment by vstinner** [comment]
> If this PR is merged, the documentation must be updated in the master branch to replace "3.9" with "3.10" (as I did in this backport).

I created PR #20735.

**Pull request merged**
