### PR TITLE
bpo-19417: Add test_bdb.py

### PR DESCRIPTION
**Pull request by xdegaye**
https://bugs.python.org/issue19417

### CODE REVIEW

**Comment by xdegaye** [comment]
Close and re-open the PR to trigger a new Appveyor build that failed because of a failure fetching openssl during the Python build process.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks!

**Comment by Mariatta** [comment]
@xdegaye can you backport to 3.6 and 2.7? Thanks.

**Comment by xdegaye** [comment]
Thanks @Mariatta. I will do the backport to 3.6 and 2.7.

**Pull request merged**
