### PR TITLE
bpo-39573: Use Py_SIZE() in s_set() of cfield.c

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue39573

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
This change is unrelated to https://bugs.python.org/issue39573 If you consider that s_set() behavior is a bug, please open a separated issue.

Your change is backward incompatible. Example:

```
import ctypes

class MyStruct(ctypes.Structure):
    _fields_ = (
        ('char', ctypes.c_char * 5),
    )

s = MyStruct()
print(ascii(s.char), bytes(s))
s.char = b'a\0b\0'
print(ascii(s.char), bytes(s))
```

Current behavior:

```
b'' b'\x00\x00\x00\x00\x00'
b'a' b'a\x00\x00\x00\x00'
```

=> only b'a\0' (2 bytes) are copied

With your PR:

```
b'' b'\x00\x00\x00\x00\x00'
b'a' b'a\x00b\x00\x00'
```

=> only b'a\0b\0' (4 bytes) are copied

**Comment by vstinner** [comment]
cc @corona10

**Comment by shihai1991** [comment]
> This change is unrelated to https://bugs.python.org/issue39573 If you consider that s_set() behavior is a bug, please open a separated issue.
> 
> Your change is backward incompatible. Example:
> 
> ```
> import ctypes
> 
> class MyStruct(ctypes.Structure):
>     _fields_ = (
>         ('char', ctypes.c_char * 5),
>     )
> 
> s = MyStruct()
> print(ascii(s.char), bytes(s))
> s.char = b'a\0b\0'
> print(ascii(s.char), bytes(s))
> ```
> 
> Current behavior:
> 
> ```
> b'' b'\x00\x00\x00\x00\x00'
> b'a' b'a\x00\x00\x00\x00'
> ```
> 
> => only b'a\0' (2 bytes) are copied
> 
> With your PR:
> 
> ```
> b'' b'\x00\x00\x00\x00\x00'
> b'a' b'a\x00b\x00\x00'
> ```
> 
> => only b'a\0b\0' (4 bytes) are copied

Thanks for your quick feedback, victor.
> This change is unrelated to https://bugs.python.org/issue39573
I found you do some macro porting operations, so I thought this macro porting operation relate to 39573 is fine(not the cause of a bug).

> Your change is backward incompatible.
Great example, current tests not help me found this backward incompatible and your example have answer this question(`/* XXX Why not Py_SIZE(value)? */`). 

Sorry for this noisy PR, guys!

**Comment by shihai1991** [comment]
To prevent other developers break this backward incompatible again, i add victor's example in https://github.com/python/cpython/pull/18424

**Pull request closed without merging**
