### PR TITLE
bpo-39349: Add cancel_futures to Executor.shutdown base class

### PR DESCRIPTION
**Pull request by hauntsaninja**
https://bugs.python.org/issue39349

### CODE REVIEW

**Comment by hauntsaninja** [comment]
cc @aeros 

Seems like we can skip news, since the addition is new in 3.9. We should also backport to 3.9.

**Review by aeros — APPROVED** [review]
Thanks for the PR @hauntsaninja! I've edited the title slightly to reflect that it's adding *cancel_futures* to the base class so that the title is more distinct original PR that added the feature. Other than that, it looks good to me. I'll restart the CI by reopening and closing since the failures look to be entirely unrelated (I opened a [separate issue](https://bugs.python.org/issue41682) for the test_asyncio failure in the Windows CI).

**Comment by hauntsaninja** [comment]
Thanks! It looks like the only CI failures currently are the doctest ones, which there's a python-dev thread about: https://mail.python.org/archives/list/python-dev@python.org/thread/KMXK6BQWQZRR2TGVRLECMR7CUVIVTUMQ/

**Comment by aeros** [comment]
> Thanks! It looks like the only CI failures currently are the doctest ones, which there's a python-dev thread about: 

@hauntsaninja No problem. I just read that thread recently, and was about to give an update. I believe the travis failure is also due to it, seeing as its specifically the documentation test failing in the build stage. So I would try pushing a non-functional commit (add some whitespace to between words in the docstring, or between the last word and the period of a sentence) to cause travis to use the older version of setuptools for the doctest. We can also just wait on the fix for setuptools, and then close/re-open the PR later; I'll leave it up to you to.

**Comment by aeros** [comment]
Thanks! I'll proceed with merging.

**Review by aeros — APPROVED** [review]

**Comment by aeros** [comment]
@hauntsaninja If you'd like to manually work on backporting to 3.9 with cherry_picker, feel free to @ mention me in the PR. If you're unfamiliar with this process, it's described in a section of the [devguide](https://devguide.python.org/committing/?highlight=backport#backporting-changes-to-an-older-version).

**Comment by hauntsaninja** [comment]
Sure, opened https://github.com/python/cpython/pull/22048

**Pull request merged**
