### PR TITLE
Update timeit.rst

### PR DESCRIPTION
**Pull request by alex-martelli**
Clarifying that Tim's introduction to "Algorithms" is only in the *second* edition of "Python Cookbook" (since, alas, it's not in the current, third edition).

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@alex-martelli

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by tirkarthi** [comment]
Patches go to master branch to be backported back to the relevant branches. Please see https://devguide.python.org/pullrequest/

**Comment by iritkatriel** [comment]
Sorry, it looked like a good idea at the time.

**Comment by ned-deily** [comment]
Since the PR was originally (incorrectly) against the 3.8 branch, it's probably easier and safer to just cherry-pick the change to a new PR against main and auto back port to 3.10 and 3.9 now.

**Comment by iritkatriel** [comment]
There's still the CLA not signed issue as well.

**Comment by iritkatriel** [comment]
And I haven't checked the book myself to verify this change.

**Comment by gvanrossum** [comment]
Someone should at least ask Alex if this is him. Anybody can create a
GitHub account named Alex Martelli and add a photo of Alex to it... (And
IIRC GitHub frowns upon people having multiple accounts.)

**Comment by terryjreedy** [comment]
18. Algorithms with Tim's intro is now 1. Data Structures and Algorithms, without.  Half of Tim's 4 1/2 pages discussed classic algorithm references; the other half timeit, with bits dated.  I looked through the doc chapter to see if there was anything really essential missing and decided not. #26301 replaces this.

Irit, thank you for trolling through 'stale' PRs like this so we can try to dispose of them one way or another.  In the future, you can ask me to help without the accidental mass review request ;-).

**Pull request closed without merging**
