### PR TITLE
bpo-31873: Change 12 instances of 'unicode' to 'Unicode'

### PR DESCRIPTION
**Pull request by toonarmycaptain**
Update 'unicode' capitalization. 'Unicode' is a proper noun, and as such should be capitalized, currently the capitalization is inconsistent throughout the document. 
Changed 12 instances.

https://bugs.python.org/issue31873

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
This doesn't look doubtless to me. Please open an issue on the tracker for discussion.

**Comment by toonarmycaptain** [comment]
@serhiy-storchaka I fixed a dozen cases to make the capitalization uniform throughout the document, but can do.

**Comment by toonarmycaptain** [comment]
Opened [Issue 31873](https://bugs.python.org/issue31873).

**Review by JulienPalard — APPROVED** [review]
There's 1233 `Unicode` for 265 `unicode` in the doc. 89 `Unicode obj` for only 8 `unicode obj`, so for consistency I'm OK with this.
Also from a spellchecking point of view, I prefer Unicode over unicode (yes we use one in the french translation and we capitalized all Unicode occurrences to avoid spellcheck errors).

**Pull request merged**
