### PR TITLE
bpo-41338: Fix warnings in test_decimal

### PR DESCRIPTION
**Pull request by methane**
https://bugs.python.org/issue41338

### CODE REVIEW

**Comment by methane** [comment]
@serhiy-storchaka What do you think about suppress DeprecationWarning in `requires_legacy_unicode_capi` decorator?

**Comment by serhiy-storchaka** [comment]
> @serhiy-storchaka What do you think about suppress DeprecationWarning in `requires_legacy_unicode_capi` decorator?

I think it is a good idea. Actually I have wrote a PR #21543 that implements it simultaneously with you. :wink:

**Review by serhiy-storchaka — APPROVED** [review]
:+1:

It is up to you, mark with `ignore_warnings` individual tests or change `requires_legacy_unicode_capi`.

**Review by skrah — APPROVED** [review]

**Comment by skrah** [comment]
Actually, we could delete this test if it's too much trouble. It has run for several years and the code won't change.

**Pull request merged**
