### PR TITLE
Doc: Disable smartquotes for zh-tw and fr translations.

### PR DESCRIPTION
**Pull request by JulienPalard**
See: https://mail.python.org/pipermail/doc-sig/2018-August/004079.html
and: https://github.com/python/cpython/pull/4006

### CODE REVIEW

**Comment by JulienPalard** [comment]
@adrianliaw can you please test a build with this patch and validate it fixes zh-tw quote issues?

**Comment by adrianliaw** [comment]
It works perfectly for our build. Thank you @JulienPalard for the PR!

As a side note, previously the issue occurred in the translation of tutorial/venv.rst where:

```
pip has a number of subcommands: “search”, “install”, “uninstall”, “freeze”, etc.
```

was translated into:

```
pip 有好幾個子指令："search"、"install"、"uninstall"、"freeze" 等等。
```

but output as

```
pip 有好幾個子指令：」search」、」install」、」uninstall」、」freeze」 等等。
```

Now by applying this PR, this issue doesn't raise again.

**Review by willingc — APPROVED** [review]
Looks good. Thanks @JulienPalard. I'll leave this for you to merge.

**Comment by JulienPalard** [comment]
I prefer the https://github.com/python/cpython/pull/9423 version, so I clone mine.

**Pull request closed without merging**
