### PR TITLE
bpo-31452: fix asyncio.gather does not cancel tasks if one fails

### PR DESCRIPTION
**Pull request by kwarunek**
Currently if one task fail `asyncio.gather` (without `return_exception`) leaves the rest of tasks pending instead of cancel them.

https://bugs.python.org/issue31452

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by asvetlov — CHANGES_REQUESTED** [review]
@kwarunek your PR looks good but please do formal requirements: sign CLA and add news entry.

https://github.com/python/cpython/pull/3597/files#diff-33471390d839efb818436e087da26388L2224 covers the problem pretty well.

**Comment by kwarunek** [comment]
I didn't expect the Spanish Inquisition!

**Review by asvetlov — APPROVED** [review]
LGTM

**Comment by asvetlov** [comment]
@1st1 I'll merge the PR if you have no objections

**Comment by 1st1** [comment]
Will review it today

**Review by 1st1 — CHANGES_REQUESTED** [review]
Want to confirm this with Guido first.

**Comment by 1st1** [comment]
Closing this PR because the corresponding issue was rejected.

**Pull request closed without merging**
