### PR TITLE
gh-94199: Remove ssl.match_hostname() function

### PR DESCRIPTION
**Pull request by vstinner**
Remove the ssl.match_hostname() function. The ssl.match_hostname()
was deprecated in Python 3.7. OpenSSL performs hostname matching
since Python 3.7, Python no longer uses the ssl.match_hostname()
function.

* Issue: gh-94199

### CODE REVIEW

**Comment by vstinner** [comment]
Hum, it seems like this function deprecated since Python 3.7 is still widely used :-(

According to a code search on ``ssl.match_hostname``, 37 projects of PyPI top 5000 projects use the deprecated function:

* aliyun-python-sdk-core-2.13.36
* ansible-core-2.13.1
* backports.ssl_match_hostname-3.7.0.1
* cassandra-driver-3.25.0
* clvm_tools_rs-0.1.14
* docker-5.0.3
* docker-compose-1.29.2
* docker-py-1.10.6
* eth_abi-3.0.0
* eth-account-0.6.1
* eth-hash-0.3.2
* eth-rlp-0.3.0
* eth-utils-2.0.0
* geventhttpclient-1.5.4
* hexbytes-0.2.2
* jedi-0.18.1
* ldap3-2.9.1
* newrelic-7.12.0.176
* oci-2.72.0
* pex-2.1.93
* pip-22.1.2
* pipenv-2022.6.7
* pipreqs-0.4.11
* pymongo-4.1.1
* python-telegram-bot-13.12
* pytype-2022.6.23
* raven-6.10.0
* rethinkdb-2.4.9
* salt-3004.2
* snowflake-connector-python-2.7.8
* suds-1.1.1
* suds-community-1.1.1
* thrift-0.16.0
* types-backports-0.1.3
* types-urllib3-1.26.15
* urllib3-1.26.9
* xdis-6.0.4

I didn't check if the function is used on any Python version, or only on old Python versions, or maybe only on recent Python versions. The [backports.ssl_match_hostname](https://pypi.org/project/backports.ssl_match_hostname/) project is a backport of the ssl.match_hostname() function for Python 3.6 and older.

Searching for ``match_hostname`` finds 65 projects. For example, (distlib/compat.py)[https://github.com/pypa/distlib/blob/9b535c342eb7d11bed584e32e53f5d1c9303b034/distlib/compat.py#L92-L189] uses ``from ssl import match_hostname`` but has a fallback implementation for Python 3.6 and older.

The urllib3 module has its own implementation: [urllib3/util/ssl_match_hostname.py](https://github.com/urllib3/urllib3/blob/06b97c50d72869a3d955e13f3032a93589ae1675/src/urllib3/util/ssl_match_hostname.py#L93).

cc @hugovk

**Comment by vstinner** [comment]
> Hum, it seems like this function deprecated since Python 3.7 is still widely used :-(

For now, I mark the PR as a draft.

**Comment by vstinner** [comment]
@tiran: I understand that you're fine with removing the function right now in Python 3.12, so I mark my PR as reviewable again :-)

**Review by tiran — APPROVED** [review]

**Comment by AdamWill** [comment]
FWIW, FreeIPA uses it in a few places. It has a method that wraps it - `ipalib.x509.IPACertificate.match_hostname()` - and three uses of that method. I don't think they can simply be dropped under the assumption that openssl is "handling it", because it actually seems to be dealing with certificate data directly itself, not intermediated by openssl. See:

* [wrapper method](https://github.com/freeipa/freeipa/blob/4a3e3efb84cee9e3784246f3bc47f1f56b266bc0/ipalib/x509.py#L387)
* [use in certdb.py](https://github.com/freeipa/freeipa/blob/4a3e3efb84cee9e3784246f3bc47f1f56b266bc0/ipapython/certdb.py#L962)
* [use in cainstance.py](https://github.com/freeipa/freeipa/blob/4a3e3efb84cee9e3784246f3bc47f1f56b266bc0/ipaserver/install/cainstance.py#L2380)
* [use in upgrade.py](https://github.com/freeipa/freeipa/blob/4a3e3efb84cee9e3784246f3bc47f1f56b266bc0/ipaserver/install/server/upgrade.py#L719)

I'll see if it can be switched to use the urllib3 version, maybe. Tagging @abbra for info.

**Comment by vstinner** [comment]
Ser maybe with @tiran who works on FreeIPA and deprecated ssl.match_hostname().

**Comment by hroncok** [comment]
I've opened https://pagure.io/freeipa/issue/9409

**Comment by vstinner** [comment]
> FWIW, FreeIPA uses it in a few places. It has a method that wraps it

Well. You can just copy/paste code from Python 3.11:

<details>

```py
import socket as _socket
import warnings
from _ssl import SSLCertVerificationError

CertificateError = SSLCertVerificationError


def _dnsname_match(dn, hostname):
    """Matching according to RFC 6125, section 6.4.3

    - Hostnames are compared lower-case.
    - For IDNA, both dn and hostname must be encoded as IDN A-label (ACE).
    - Partial wildcards like 'www*.example.org', multiple wildcards, sole
      wildcard or wildcards in labels other then the left-most label are not
      supported and a CertificateError is raised.
    - A wildcard must match at least one character.
    """
    if not dn:
        return False

    wildcards = dn.count('*')
    # speed up common case w/o wildcards
    if not wildcards:
        return dn.lower() == hostname.lower()

    if wildcards > 1:
        raise CertificateError(
            "too many wildcards in certificate DNS name: {!r}.".format(dn))

    dn_leftmost, sep, dn_remainder = dn.partition('.')

    if '*' in dn_remainder:
        # Only match wildcard in leftmost segment.
        raise CertificateError(
            "wildcard can only be present in the leftmost label: "
            "{!r}.".format(dn))

    if not sep:
        # no right side
        raise CertificateError(
            "sole wildcard without additional labels are not support: "
            "{!r}.".format(dn))

    if dn_leftmost != '*':
        # no partial wildcard matching
        raise CertificateError(
            "partial wildcards in leftmost label are not supported: "
            "{!r}.".format(dn))

    hostname_leftmost, sep, hostname_remainder = hostname.partition('.')
    if not hostname_leftmost or not sep:
        # wildcard must match at least one char
        return False
    return dn_remainder.lower() == hostname_remainder.lower()


def _inet_paton(ipname):
    """Try to convert an IP address to packed binary form

    Supports IPv4 addresses on all platforms and IPv6 on platforms with IPv6
    support.
    """
    # inet_aton() also accepts strings like '1', '127.1', some also trailing
    # data like '127.0.0.1 whatever'.
    try:
        addr = _socket.inet_aton(ipname)
    except OSError:
        # not an IPv4 address
        pass
    else:
        if _socket.inet_ntoa(addr) == ipname:
            # only accept injective ipnames
            return addr
        else:
            # refuse for short IPv4 notation and additional trailing data
            raise ValueError(
                "{!r} is not a quad-dotted IPv4 address.".format(ipname)
            )

    try:
        return _socket.inet_pton(_socket.AF_INET6, ipname)
    except OSError:
        raise ValueError("{!r} is neither an IPv4 nor an IP6 "
                         "address.".format(ipname))
    except AttributeError:
        # AF_INET6 not available
        pass

    raise ValueError("{!r} is not an IPv4 address.".format(ipname))


def _ipaddress_match(cert_ipaddress, host_ip):
    """Exact matching of IP addresses.

    RFC 6125 explicitly doesn't define an algorithm for this
    (section 1.7.2 - "Out of Scope").
    """
    # OpenSSL may add a trailing newline to a subjectAltName's IP address,
    # commonly with IPv6 addresses. Strip off trailing \n.
    ip = _inet_paton(cert_ipaddress.rstrip())
    return ip == host_ip


def match_hostname(cert, hostname):
    """Verify that *cert* (in decoded format as returned by
    SSLSocket.getpeercert()) matches the *hostname*.  RFC 2818 and RFC 6125
    rules are followed.

    The function matches IP addresses rather than dNSNames if hostname is a
    valid ipaddress string. IPv4 addresses are supported on all platforms.
    IPv6 addresses are supported on platforms with IPv6 support (AF_INET6
    and inet_pton).

    CertificateError is raised on failure. On success, the function
    returns nothing.
    """
    warnings.warn(
        "ssl.match_hostname() is deprecated",
        category=DeprecationWarning,
        stacklevel=2
    )
    if not cert:
        raise ValueError("empty or no certificate, match_hostname needs a "
                         "SSL socket or SSL context with either "
                         "CERT_OPTIONAL or CERT_REQUIRED")
    try:
        host_ip = _inet_paton(hostname)
    except ValueError:
        # Not an IP address (common case)
        host_ip = None
    dnsnames = []
    san = cert.get('subjectAltName', ())
    for key, value in san:
        if key == 'DNS':
            if host_ip is None and _dnsname_match(value, hostname):
                return
            dnsnames.append(value)
        elif key == 'IP Address':
            if host_ip is not None and _ipaddress_match(value, host_ip):
                return
            dnsnames.append(value)
    if not dnsnames:
        # The subject is only checked when there is no dNSName entry
        # in subjectAltName
        for sub in cert.get('subject', ()):
            for key, value in sub:
                # XXX according to RFC 2818, the most specific Common Name
                # must be used.
                if key == 'commonName':
                    if _dnsname_match(value, hostname):
                        return
                    dnsnames.append(value)
    if len(dnsnames) > 1:
        raise CertificateError("hostname %r "
            "doesn't match either of %s"
            % (hostname, ', '.join(map(repr, dnsnames))))
    elif len(dnsnames) == 1:
        raise CertificateError("hostname %r "
            "doesn't match %r"
            % (hostname, dnsnames[0]))
    else:
        raise CertificateError("no appropriate commonName or "
            "subjectAltName fields were found")
```

</details>

> I'll see if it can be switched to use the urllib3 version, maybe. Tagging @abbra for info, also @hroncok .

I'm not sure that this closed issue is the best way to discuss solutions for FreeIPA. Maybe https://pagure.io/freeipa/issue/9409 is a better place :-)

**Pull request merged**
