### PR TITLE
gh-121035: Update logging flow chart to include lastResort

### PR DESCRIPTION
**Pull request by bessman**
* Issue: gh-121035

----
📚 Documentation preview 📚: https://cpython-previews--121036.org.readthedocs.build/

### CODE REVIEW

**Comment by vsajip** [comment]
Thanks for this, but what process have you used? I've been thinking about replacing (or perhaps augmenting) this PNG file with something that's more easily modifiable, such as an SVG.

**Comment by bessman** [comment]
I edited it in GIMP. Not the most convenient workflow, indeed.

If you prefer, I could look into recreating the flowchart as SVG in Inkscape or Dia. It won't look exactly the same, of course, but I'm sure I can get it reasonably close.

**Comment by vsajip** [comment]
> I could look into recreating the flowchart as SVG

That would be great. I think it needs to be a bit "nicer", style-wise, than the current iteration, which looks pretty old-fashioned and out of step with the overall documentation that surrounds it. If you think that's too much work, I'll understand!

**Comment by bessman** [comment]
> I think it needs to be a bit "nicer", style-wise

I'm not much of a graphic designer, so I can't really execute on this without further guidance. Do you have an example of an image in the style you would like?

For now, I have replaced the PNG with an SVG in the same style. I'll experiment a bit with font size and background to make sure it's readable.

**Comment by bessman** [comment]
I'm working on embedding the SVG in the page HTML properly, so that the font is the same as the surrounding page text.

**Comment by vsajip** [comment]
Quick work, it's coming along nicely. Things that occurred to me:

* I would change "lastResort" to "handler of last resort"
* The overall size of the SVG might need to be tweaked, too - at least from what I can see from the documentation preview.
* Maybe keep your updated PNG in the repository (for now), in case we find that some browsers can't display the SVG (unlikely, I know). We can link the SVG from the documentation as you've done, but keep the PNG around in case we need to add an additional link to that.

**Comment by bessman** [comment]
> I would change "lastResort" to "handler of last resort"

How about "lastResort handler"? My thinking is that for someone unfamiliar with the `logging` module, it is immediately obvious that "lastResort" is the name of an actual Python object, and a quick ctrl+f on the same page will bring the user to an explanation of what it is. Whereas "handler of last resort" is less obvious what it is, at least to me.

**Comment by bessman** [comment]
One problem: The sphinx `:class: invert-in-dark-mode` command does not work with raw html. I've added a bit of CSS to the SVG which makes it aware of the browser's dark mode setting, but I haven't been able to figure out a way to make it respond to the theme selector drop down. I.e. if someone with their browser set to dark mode selects light mode from the theme selector, the diagram will look bad. Same for light mode browser + dark mode theme selector.

An alternative is to load the SVG with `.. image::` instead of `.. raw:: html`, but them the text in the diagram won't be copyable or accessible to screen readers.

**Comment by vsajip** [comment]
> One problem: The sphinx :class: invert-in-dark-mode

Maybe leave that for a later refinement? Accessibility is probably more important than a light/dark mismatch.

**Comment by bessman** [comment]
Then I think this is ready.

**Review by vsajip — APPROVED** [review]

**Comment by vsajip** [comment]
Thank you very much for this!

**Comment by vsajip** [comment]
@bessman I made some changes to the SVG to tweak elements positions and styles. I want to export the changed version to PNG, but the PNG I export from Inkscape has a transparent background. What tool did you end up using to create the SVG and PNG (including precise versions, and on which OS)? I modified the SVG by hand as I couldn't find a suitable tool that would make minimal changes to the SVG you created.

**Comment by vsajip** [comment]
There's still a pending issue of syncing with the theme selector, but I think that will require changes in the pydoc theme to e.g. add a class to the `body` element indicating the mode in use.

**Comment by bessman** [comment]
> What tool

I made it in Dia (v0.97+git from Ubuntu 20.04). Perhaps the .dia file should also be added to the repo?

To create the PNG, I used Dia's export feature. However, after some experimentation I've found a way to do the conversion with imagemagick (6.9.10-23 Q16 x86_64 20190101) which achieves better compression:

`convert logging_flow.svg -background none -define png:compression-filter=1 -define png:compression-level=9 -define png:compression-strategy=0 logging_flow.png`

**Comment by bessman** [comment]
> is the `.dia` file text? 

It's gzip'd XML.

**Comment by vsajip** [comment]
Sadly, I've noticed that following my changes (mostly to remove inline styles from the elements in favour of CSS), Dia won't import the SVG correctly any more. See this screenshot:

dia

**Comment by bessman** [comment]
Well, in case it's helpful, here is the .dia file: [logging_flow.xml.gz](https://github.com/user-attachments/files/16073563/logging_flow.xml.gz)

I had to change the suffix to .xml.gz for github to accept it.

**Comment by vsajip** [comment]
Thanks very much.

**Pull request merged**
