### PR TITLE
fix docstring typo in bdb.py

### PR DESCRIPTION
**Pull request by flizzywine**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@flizzywine

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by aeros — APPROVED** [review]
Thanks for the PR @flizzywine, and welcome!

LGTM. I think this is small enough to merge without CLA signed, but it's preferred to sign it if you're willing/able to do so (especially if there's some interest in future contributions).

**Review by iritkatriel — APPROVED** [review]

**Comment by iritkatriel** [comment]
You need to sign the CLA before your changes can be merged. See https://devguide.python.org/pullrequest/?highlight=cla#licensing

**Comment by aeros** [comment]
@iritkatriel The general policy is to allow minor, non-creative fixes (such as typo fixes) without CLA, but it's at the discretion of the core developer merging the change. I'm currently waiting on a response from the author (there are some legitimate cases where people can't sign the CLA due to employer contracts or similar issues).

**Pull request merged**
