### PR TITLE
bpo-30179: Update Copyright to 2017

### PR DESCRIPTION
**Pull request by csabella**

### CODE REVIEW

**Comment by Mariatta** [comment]
We have an open issue about this http://bugs.python.org/issue29555, and this PR is duplicate of #4.

**Comment by csabella** [comment]
Sorry, I searched but didn't find it.  Thank you.

**Comment by Mariatta** [comment]
No problem :) Thanks.

**Comment by csabella** [comment]
Is there a dev list somewhere of "do's and dont's"?  I feel like I keep making novice mistakes and would love to have a FAQ to reference for things that have been discussed and decided (like this issue or the ... in the code snippets).  I hate causing people to have to clean up after me.  :-(

**Comment by Mariatta** [comment]
No worries (I made these mistakes too 😅 )
I don't think there is a list of do and don'ts other than what's been documented in the [Dev Guide](http://cpython-devguide.readthedocs.io/).
If you think some things are missing, perhaps open an [issue](https://github.com/python/devguide).

The [core-mentorship](https://mail.python.org/mailman/listinfo/core-mentorship) mailing list is also good place to ask questions  :)

**Pull request closed without merging**
