### PR TITLE
Add workflow for automatic issue headers

### PR DESCRIPTION
**Pull request by AA-Turner**
xref: https://github.com/python/cpython/pull/108033#issuecomment-1680996433

As per Alex, please feel free to test at https://github.com/AA-Turner/cpython/issues/new/choose

A

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
Javascript isn't my strong suit, but this approach makes sense to me, as far as I can tell! And it seems to work pretty well :)

Will wait for another review before merging, though

**Comment by AA-Turner** [comment]
For reference, the ocktokit docs:

* https://octokit.github.io/rest.js/v20#issues-get
* https://octokit.github.io/rest.js/v20#issues-update

And the GitHub docs for the return object schemas:

* https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue

A

**Comment by hugovk** [comment]
This can cause conflicts if you click to edit right after posting, and in the meantime the action adds the header. When you try and save it shows:

image

It would be nicer to avoid this if possible, but I guess we'd need some of the workarounds from https://github.com/python/cpython/pull/108033#issuecomment-1681030685 onward, like having a somehow textbox near the top.

And, well, we can also get conflicts with the RTD link addition, but that's docs only PRs and this is for most issues.

**Comment by AlexWaygood** [comment]
> This can cause conflicts if you click to edit right after posting, and in the meantime the action adds the header.

In the spirit of EAFP, we could try this out, and see if we get any complaints?

**Review by hugovk — APPROVED** [review]
Sure :)

**Pull request merged**
