### PR TITLE
gh-97670: Remove sys.getdxp() and analyze_dxp.py script

### PR DESCRIPTION
**Pull request by vstinner**
Remove the sys.getdxp() function and the Tools/scripts/analyze_dxp.py script. DXP stands for "dynamic execution pairs". They were related to DYNAMIC_EXECUTION_PROFILE and DXPAIRS macros which have been removed in Python 3.11. Python can now be built with "./configure --enable-pystats" to gather statistics on Python opcodes.

* Issue: gh-97670

### CODE REVIEW

**Comment by vstinner** [comment]
@markshannon: Would you mind to review this PR?

**Comment by vstinner** [comment]
@brandtbucher: Would you mind to review this PR?

**Comment by markshannon** [comment]
Removing the script seems fine.
Do we know for sure that no one is using `sys.getdxp()`?

**Comment by vstinner** [comment]
> Do we know for sure that no one is using sys.getdxp()?

I just searched in the PyPI top 5000 projects: I found 0 projects using ``getdxp()``. I cannot be 100% sure. But if a project uses getdxp(), it can be updated to use the new way to gather stats, no? Also, we can add back the function if someone comes with a use case for it. For me, it's mostly a tool to develop and optimize Python. So if no Python core dev uses it, I don't think that we should worry about removing this function.

**Comment by vstinner** [comment]
@smontanaro: I found a script using ``sys.getdxp()`` in "BitTorrent-master" . Are you still using it?

```py
# Copyright (c) 2001-2004 Twisted Matrix Laboratories.
# See LICENSE for details.
(...)
def report(email, appname):
    """
    Send an RLE encoded version of sys.getdxp() off to our Top Men (tm)
    for analysis.
    """
    if hasattr(sys, 'getdxp') and appname:
        dxp = xmlrpclib.ServerProxy("http://manatee.mojam.com:7304")
        dxp.add_dx_info(appname, email, sys.version_info[:3], rle(sys.getdxp()))
```

See [twisted/python/dxprofile.py](https://www.programcreek.com/python/?code=kenorb-contrib%2FBitTorrent%2FBitTorrent-master%2Ftwisted%2Fpython%2Fdxprofile.py) for the full source with the ``rle()`` function.

This script was part of Twisted and [was removed in Twisted Core 8.0.0](https://github.com/twisted/twisted/blob/022659ca88dca6361288cd26486942cba0ed77c4/docs/historic/NEWS.rst) (2008-03-17) because [it no longer worked (issue #2908)](https://github.com/twisted/twisted/issues/2908).

**Comment by vstinner** [comment]
I found references to getdxp() by @smontanaro on python-dev mailing list in 2001-2003:

* [Instruction count frequency server](https://mail.python.org/archives/list/python-dev@python.org/message/Y6VPH447CC5SV42VNIZXQFPQ4GLVBW7C/)
* [Python optmizations](https://mail.python.org/archives/list/python-dev@python.org/message/CRCGWFUJIFPRQC6VURXN5VJQOIZVJRY4/)
* [automated testing system](https://mail.python.org/archives/list/python-dev@python.org/message/PHFJNWCWSLNCT6Z45I4CBN3ZAGRGEDFY/)
* [Dynamic bytecode analysis](https://mail.python.org/archives/list/python-dev@python.org/message/MGKBJCHSXYJISH4XODILMWKEWJ3XP6PM/)

**Comment by vstinner** [comment]
Ah by the way, as you can see in this PR, ``sys.getdxp()`` is not documented and not tested at all. There is just a test on the script.

**Comment by smontanaro** [comment]
@vstinner As you might have expected, I'm no longer using the dxp stuff, but thanks for checking. :-)

**Comment by vstinner** [comment]
Thanks for reviews. It's now removed.

**Pull request merged**
