### PR TITLE
Fix typos in docs, error messages and comments

### PR DESCRIPTION
**Pull request by jianghuyiyuan**
----
📚 Documentation preview 📚: https://cpython-previews--122502.org.readthedocs.build/

### CODE REVIEW

**Review by picnixz — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks, but I think we can manage with these minor inconsistencies in the comments.

**Comment by AlexWaygood** [comment]
This PR touches six files. Of the six files touched, three of the files are docs files, in which the PR fixes grammatical errors in the docs, and in a fourth file the PR fixes a spelling error in a message that could be shown to a user.

I agree with @erlend-aasland that we don't want to encourage PRs that only fix typos in comments, but — despite its current title — that's not what this PR does. I think overall the changes this PR makes are valuable.

**Review by AlexWaygood — APPROVED** [review]

**Comment by erlend-aasland** [comment]
> and in a fourth file the PR fixes a spelling error in a message that could be shown to a user

More specific a user who builds a debug build of CPython; the error message is guarded by the debug flag.

**Comment by picnixz** [comment]
Actually, we had a bunch of similar PRs that were accepted those past weeks (even when touching the C code) so I think we should have allowed this one as well: https://github.com/python/cpython/pulls?q=is%3Apr+author%3Axyb+sort%3Aupdated-desc (most of them are by xyb)

**Pull request merged**
