### PR TITLE
bpo-32117: Updated Simpsons names in docs

### PR DESCRIPTION
**Pull request by kingbuzzman**
`sally` is not a Simpsons character 

https://bugs.python.org/issue32117

Automerge-Triggered-By: @gvanrossum

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@kingbuzzman

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by kingbuzzman** [comment]
How do i add a "skip news" label?

**Comment by gvanrossum** [comment]
Only triagers and core devs can add that label, so I will add it for you. But we are still waiting for your CLA.

**Comment by kingbuzzman** [comment]
*Googling what that means*

**Comment by kingbuzzman** [comment]
Understood. Email sent. Thank you Guido.

**Comment by kingbuzzman** [comment]
Any other steps needed to get this merged?

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Thanks! All set now.

**Pull request merged**
