### PR TITLE
bpo-43916: Use Py_TPFLAGS_DISABLE_NEW flag in hashlib

### PR DESCRIPTION
**Pull request by tiran**
https://bugs.python.org/issue43916

### CODE REVIEW

**Comment by vstinner** [comment]
I merged my PR #25721 and the flag was renamed. Can you please rebase your PR?

**Review by vstinner — APPROVED** [review]
LGTM. If you rebase your PR and rename Py_TPFLAGS_DISABLE_NEW flag to Py_TPFLAGS_DISALLOW_INSTANTIATION.

I only reviewed Lib/test/test_hashlib.py and Modules/_hashopenssl.c changes.

**Comment by vstinner** [comment]
I created PR #25745 which also updates the posix module.

**Comment by tiran** [comment]
Thanks Victor!

**Pull request closed without merging**
