### PR TITLE
[3.12] gh-118263: Add additional arguments to path_t (Argument Clinic type) in posixmodule (GH-118355)

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-118263

### CODE REVIEW

**Comment by nineteendo** [comment]
@zooba does this also need "DO-NOT-MERGE"? In theory this just removes the Python wrapper.

**Comment by zooba** [comment]
As long as it's a draft, it can't be merged.

**Comment by nineteendo** [comment]
I marked it as ready for review.

**Comment by zooba** [comment]
Let's have it. It looks clean enough, and it'll make backports easier if we change anything around here later on.

**Pull request merged**
