### PR TITLE
Fix asyncio policy docs about per interpreter semantics

### PR DESCRIPTION
**Pull request by kumaraditya303**

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by CAM-Gerlach** [comment]
It would seem to still be useful to qualify "global" _somehow_, though, in terms of what actual scope it is global in—per process? Per machine? Something else? Otherwise, it is not very meaningful and potentially even confusing on its own, as a non-expert reader might plausibly think it means anywhere from thread-global to machine-global, given "global" can mean different things in different contexts (Python keyword, C concept, and various others).

**Comment by CAM-Gerlach** [comment]
Also, meta sidenote—it looks like on the CPython repo, the default squash merge commit message is set to be the first commit in the PR, rather than the PR title, which leads to the commit message being the rather uninformative "Fixup policy docs" rather than the far more useful "Fix asycio policy docs about per interpreter semantics" PR title. Someone should probably change that...

**Comment by gvanrossum** [comment]
That's my fault, normally I edit the commit title when I merge it, but I was in a hurry (too many meetings today).

**Comment by CAM-Gerlach** [comment]
No worries, its easy to miss, and it should be fixed for the future to use the PR title by default now that Ezio set the appropriate repo settings

**Pull request merged**
