### PR TITLE
gh-99202: Fix extension type from documentation for compiling in C++20 mode 

### PR DESCRIPTION
**Pull request by jpn--**
As noted in #99202, C++20 added support for designated initializers and fails to compile if you mix named and unnamed initializers.

The documentation currently includes a section "[Defining Extension Types: Tutorial](https://docs.python.org/3/extending/newtypes_tutorial.html)" that mixed named and unnamed initializers, so it will not compile as shown. 

This PR adds names on the header macros, so they do now compile in C++20 mode.  The change is only made in the demo documentation, not any "real" code.

* Issue: gh-99202

### CODE REVIEW

**Comment by arhadthedev** [comment]
@vstinner @encukou @erlend-aasland @bruno-at-bareos as participants of the parent issue.

**Review by vstinner — APPROVED** [review]
LGTM. IMO it's fine to use this syntax in the documentation for new extensions.

@encukou: What do you think?

Python 3.11 itself now targets C11: https://peps.python.org/pep-0007/#c-dialect Python still supports building extensions with older C standards and various C++ standards.

**Comment by encukou** [comment]
This actually looks great! I'm surprised that there aren't any obvious downsides!

IMO it would be nice to introduce `PyVarObject_HEAD_BASE` macros, named to match the field name, which wouldn't include the comma. But that's a separate issue: it would still make sense to use that with `.ob_base =`

Victor, do you want to merge? (I can't commit to watching/fixing buildbots this week.)

**Comment by vstinner** [comment]
Merged, thanks!

**Pull request merged**
