### PR TITLE
bpo-20408: Fix memoryview() signature in docs.

### PR DESCRIPTION
**Pull request by felixxm**
https://bugs.python.org/issue20408

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]
LGTM

**Comment by felixxm** [comment]
This is not stale, I'm waiting for review.

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
Thank you!

**Comment by felixxm** [comment]
Thanks for checking :rocket:

**Pull request merged**
