### PR TITLE
bpo-30754

### PR DESCRIPTION
**Pull request by tmblweed**
Added changes clarifying dedent behavior with regards to whitespace

https://bugs.python.org/issue30754

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by tmblweed** [comment]
@gpshead - this is my first commit to the repo - so do I need to do anything? I did sign the CLA a few hours ago, but not sure what your comment meant. Thanks!

**Comment by gpshead** [comment]
Nope, nothing else to do for this PR on your end.  This looks good, thanks!

It was being held up by some trialing whitespace in both files making it fail the continuous integration checks.  I believe I've fixed those now.

In the future, look into configuring your editor(s) to always remove trailing whitespace from lines when saving files.  A `make patchcheck` beforehand might have caught this before seeing it in the CI systems.

**Comment by tmblweed** [comment]
sounds good, thanks for that!

**Pull request merged**
