### PR TITLE
Simple typo

### PR DESCRIPTION
**Pull request by sondrelg**
Hi!

I could be wrong, but I believe "they were run" is the correct use of `run` in this case 😊

Thanks!

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@sondrelg

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by sondrelg** [comment]
I tried creating an account with the bug tracker, but it looks like it doesn't support nordic letters (like ø):
```
'ascii' codec can't encode character u'\xf8' in position 13: ordinal not in range(128)

**Review by nanjekyejoannah — COMMENTED** [review]
Please open your PR against the `main` branch.

**Review by gpshead — APPROVED** [review]

**Review by gpshead — CHANGES_REQUESTED** [review]
please move/redo the PR to be against the main branch - we automate backports from there.

**Comment by sondrelg** [comment]
I'll reopen

**Pull request closed without merging**
