### PR TITLE
bpo-47243: Duplicate entry in 'Objects/unicodetype_db.h'

### PR DESCRIPTION
**Pull request by LiarPrincess**
Fix for duplicate 1st entry in 'Objects/unicodetype_db.h':

```c
/* a list of unique character type descriptors */
const _PyUnicode_TypeRecord _PyUnicode_TypeRecords[] = {
    {0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0}, <--- HERE
    {0, 0, 0, 0, 0, 32},
    {0, 0, 0, 0, 0, 48},
    …
```

https://bugs.python.org/issue47243

https://bugs.python.org/issue47243

Automerge-Triggered-By: GH:isidentical

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@LiarPrincess

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by LiarPrincess** [comment]
CLA is signed, but there is this 'at least one business day before our records are updated'.

**Comment by LiarPrincess** [comment]
NEWS entry added.

Issue after migration #91399.

**Comment by cfbolz** [comment]
FWIW, this change looks correct to me (the original problem was a small miss-thought, I think).

**Comment by isidentical** [comment]
@LiarPrincess can you regenerate the unicodedata (and then I think we can merge it in). Thanks @cfbolz for the review!

**Review by isidentical — APPROVED** [review]

**Comment by isidentical** [comment]
Thanks for the PR @LiarPrincess!

**Comment by LiarPrincess** [comment]
Thanks for review.
Updated with main & regenerated 'unicodetype_db.h' with Unicode 15.0.

**Pull request merged**
