### PR TITLE
bpo-35616: Change references to '4.0'.

### PR DESCRIPTION
**Pull request by eamanu**
https://bugs.python.org/issue35616

### CODE REVIEW

**Comment by terryjreedy** [comment]
I am not sure if '3.9' is the right replacement, so I want other opinions.

**Comment by eamanu** [comment]
Maybe 3.10?

**Comment by vstinner** [comment]
Removing an API requires more discussions on python-dev.

cc @serhiy-storshaka

**Comment by eamanu** [comment]
@vstinner Do I open a thread on python-dev mailing list?

**Comment by terryjreedy** [comment]
@vstinner This proposal does not remove any APIs.  Do you mean that each change from 'deprecated' to 'removed' will need individual discussion?  (Some have had that already.)
@eamanu I will open a pydev thread if/when I think appropriate.

**Review by terryjreedy — CHANGES_REQUESTED** [review]
Some change is needed, but it is not yet clear exactly what.

**Comment by eamanu** [comment]
> @eamanu I will open a pydev thread if/when I think appropriate.

Roger that

**Comment by terryjreedy** [comment]
I am withdrawing the proposal.  See issue.

**Pull request closed without merging**
