### PR TITLE
Small text fixes for enum.rst

### PR DESCRIPTION
**Pull request by elliotwaite**
Some suggestions I thought of while reading over this helpful HOWTO.

If any of these changes are incorrect or unwanted, feel free to edit this PR or cherry-pick only the changes you want to keep.

### CODE REVIEW

**Review by ethanfurman — APPROVED** [review]
I made a couple changes to your changes, but overall it looks good!  Thank you!

**Comment by elliotwaite** [comment]
Thanks for the review. Your changes look good.

That "whitespace or comma separated string" sentence is a tricky one because the value can be a whitespace-separated, comma-separated, or comma-and-whitespace-separated string. Listing all those options might be the clearest, but might be overly verbose given that the code example shown right after that sentence clears up the ambiguity. I see now how what I suggested actually made it worse, since it suggested that the value could be a whitespace string or a comma-separated string. From looking at [some Google search results](https://www.google.com/search?q=%22whitespace+or+comma+separated+string%22), it looks like how you have it now or how you had it before are two popular ways to write that sentence if just adding hyphens.

**Comment by ambv** [comment]
At least as a non-native speaker, I prefer "whitespace- and comma-separated" because it clearly builds the sentence structure, making it easier to parse. Listing the whitespace+commas option feels a little verbose to me in this context. I think the current state is clear and reads well.

**Comment by elliotwaite** [comment]
@ambv, got it, sounds good. Thanks for the merge.

**Pull request merged**
