### PR TITLE
gh-111765: move old PyFloat_* tests to Lib/test/test_capi/test_float.py 

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-111765

### CODE REVIEW

**Comment by skirpichev** [comment]
@AlexWaygood, probably this also can skip news?

**Comment by skirpichev** [comment]
CC @serhiy-storchaka

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

I was going to suggest you make these changes, but it was obvious, so you already made them.

**Comment by skirpichev** [comment]
> I was going to suggest you make these changes

That was actually [suggested](https://github.com/python/cpython/pull/111624#issuecomment-1789978007) in https://github.com/python/cpython/pull/111624.

**Pull request merged**
