### PR TITLE
bpo-35551: encodings update

### PR DESCRIPTION
**Pull request by epicfaace**
https://bugs.python.org/issue35551

### CODE REVIEW

**Review by eamanu — APPROVED** [review]
LGTM. news?

**Comment by eamanu** [comment]
@epicfaace Please sign the CLA

**Comment by epicfaace** [comment]
@eamanu I signed it yesterday, do you know how long it should take to update?

**Comment by vstinner** [comment]
> @eamanu I signed it yesterday, do you know how long it should take to update?

It can take a few days. Check the status in your bugs.python.org profile.

**Comment by epicfaace** [comment]
@eamanu it's been updated as signed now.

**Comment by csabella** [comment]
Requesting review from @malemburg based on question from @methane on the bug tracker.

**Review by malemburg — APPROVED** [review]

**Comment by csabella** [comment]
@epicfaace, thank you for the pull request and @malemburg, thank you for the approval.

**Pull request merged**
