### PR TITLE
bpo-35081: add NEWS entry for new Include/internal/pycore_*.h files

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue35081

### CODE REVIEW

**Comment by vstinner** [comment]
@ncoghlan: Would you mind to review this NEWS entry? Is it what you expected?

**Comment by vstinner** [comment]
See also https://bugs.python.org/issue35296 and PR #10665.

**Comment by vstinner** [comment]
I created a NEWS entry. You can modify it if you want to elaborate :-)

**Comment by ncoghlan** [comment]
That's exactly what I had in mind, thanks - just a heads up to say "Yes, we moved some stuff around" if folks see weird build errors when they switch from building 3.7 to building 3.8 :)

**Pull request merged**
