### PR TITLE
gh-52186: the makesetup script now respects macro define arguments of…

### PR DESCRIPTION
**Pull request by michaelgrahamevans**
… the form '-Dname=definition'

Previously adding a macro define argument in the Modules/Setup file such as '-Dname=value' was recognised by the makesetup script as a Make variable definition due to the '=' character. This change uses sed to find lines with only one token to the left of the first '=' which it treats as a Make variable definition. Lines not matching this criteria are matched as module definitions. Moreover, this change respects Make variable definitions with '=', ':=', '::=', '+=' and '?=' syntax.

https://bugs.python.org/issue7938

* Issue: gh-52186

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by michaelgrahamevans** [comment]
I have signed the CLA.

**Comment by benjaminp** [comment]
I wonder if we can simplify this by assuming the make variables are of the form `^SOME_VAR=`? (i.e., one word at the beginning of a line).

**Comment by MaxwellDupre** [comment]
Is this still relevant?

**Comment by arhadthedev** [comment]
Oh... It seriously slipped through the cracks.

**Pull request closed without merging**
