### PR TITLE
bpo-37830: Revert "bpo-32489: Allow 'continue' in 'finally' clause. (GH-5822)"

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
This reverts commit fe2bbb1869b42222a3f331a3dfb8b304a19a5819.

https://bugs.python.org/issue37830

### CODE REVIEW

**Comment by isidentical** [comment]
Then i am closing #15221

**Review by isidentical — APPROVED** [review]

**Comment by pablogsal** [comment]
We should also inform @ambv so it removes this from the main announcement of future releases.

**Comment by dpgeorge** [comment]
FWIW I think that `continue` should never be allowed in a `finally` clause because it's tricky to implement, and simply should not be used in scripts (I feel the same about `break` and `return` in a `finally`, but that's not really possible to ban at this point).  We had similar VM seg-faults in MicroPython for all these "unwinding jumps", see https://github.com/micropython/micropython/commit/b735208403a54774f9fd3d966f7c1a194c41870f and https://github.com/micropython/micropython/commit/e1fb03f3e2d1e99d0f745e9e17a963a036d34476 for the fixes (for return and break respectively).  Banning this syntax at the compile level would make things simpler.

@ncoghlan FYI we did discuss this topic at PyCon AU 2018

**Comment by serhiy-storchaka** [comment]
Actually this reversion does not solve the issue completely: https://bugs.python.org/issue37830#msg349513. So it does not make sense to do it.

**Review by ncoghlan — APPROVED** [review]

**Comment by ncoghlan** [comment]
The rationale of making life easier for interpreter implementors still applies though - the fact that try/finally can be used to *suppress* an exception is genuinely weird.

**Review by vstinner — APPROVED** [review]
LGTM. I'm ok to revert the change in Python 3.8 to get more time to find maybe a different approach in Python 3.9. Right now, we have to focus on stabilizing Python 3.8.

**Comment by serhiy-storchaka** [comment]
I have closed this issue because I do not see any sense in reverting changes for `continue` if there is the same issue with `break`. At least `continue` is not used in existing code, so it will not crash any program.

**Comment by ncoghlan** [comment]
@serhiy-storchaka The request from MicroPython was to reconsider allowing this construct at all. The fact that break is broken in the same way is a solid argument that we should stop digging the hole deeper (and perhaps consider disallowing break as well). We're making work for other implementations for no good reason.

**Comment by dpgeorge** [comment]
> The request from MicroPython was to reconsider allowing this construct at all.

Probably here is not the right place to have such a discussion, but my aim was to raise the point that we also had issues with return/break/continue in a finally, and that I would support changing the language to disallow this combination of constructs.

return/break/continue in a finally suite will (silently) cancel any raised exception, which is unexpected behaviour and probably not what the writer of the Python code intended.  At least there are other ways to write such code (without having return/break/continue in the finally) which has more explicit behaviour.  I did a survey of the Python standard library and this pattern is rarely used.  And where it is used it's easy to change it.

I would consider writing a PEP to disallow this construct, if there's interest.

**Comment by isidentical** [comment]
+1 from me but i proposed that on python-ideas and no reply so far. I want
to be part of PEP process (as a inital bug reporter) if you allow.

**Comment by ncoghlan** [comment]
@isidentical @dpgeorge A draft PEP for that would be a good next step. I'd be happy to take on the PEP sponsor role.

For continue, the proposal would be to *not* add support in Python 3.8, while for return and break, the proposal would be to deprecate in 3.9, emit a compilation warning in 3.10, and then disallow after that.

**Comment by dpgeorge** [comment]
Ok, I'll draft a PEP.

**Comment by serhiy-storchaka** [comment]
[PEP 601](https://www.python.org/dev/peps/pep-0601/) was rejected (although I think it contains a reasonable seed).

**Pull request closed without merging**
