### PR TITLE
gh-127897: fix HACL* build on macOS/Catalina

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
* Issue: gh-127897

### CODE REVIEW

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Looks like I must update folder using `./refresh` script instead. Also, I'm waiting for [that PR](https://github.com/FStarLang/karamel/pull/505) to be reviewed.

**Comment by picnixz** [comment]
FTR: we don't change the contents of `_hacl` except via the `refresh.sh` script so you do need to first update that one. In addition, do not forget to update `Misc/sbom.spdx.json`.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
The [hacl-star repository](https://github.com/hacl-star/hacl-star/blob/8dca31ef8e6329a53c21584b8401b386bc94020d/dist/karamel/include/krml/internal/target.h) does not contain the updated KaRaMeL headers, as it too is manually synchronized. 🤷‍♂️

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
The updates have been successfully collected: https://github.com/hacl-star/hacl-star/pull/1010

**Comment by msprotz** [comment]
As you noticed, the refresh is automated via CI -- I've approved the PR and the updated file is now in main. Thanks again!

**Review by gpshead — APPROVED** [review]

**Comment by gpshead** [comment]
github appears stuck. i'm going to close and reopen the PR to retrigger it.

**Pull request merged**
