### PR TITLE
gh-94215: Reproducer for segfault in frame_setlineno()

### PR DESCRIPTION
**Pull request by tiran**
* Issue: gh-94215

### CODE REVIEW

**Comment by tiran** [comment]
I can't promise that the change is correct. The test reproducer no longer crashes with a segfault and refleak tests do not report any reference leaks either.

**Comment by tiran** [comment]
My fix is incorrect. It introduces a reference leak.

**Comment by kumaraditya303** [comment]
> My fix is incorrect. It introduces a reference leak.

Where is the refleak ? Can you provide a link to failing buildbot?

**Comment by tiran** [comment]
As I said my attempt to solve the segfault introduces a refleak. You can easily reproduce the refleak by running ``test_pdb`` with test runner option ``-R``.

**Comment by tiran** [comment]
I have removed the invalid fix and cleaned up the test. I'm going to add and backport the new tests so we have a reproducer for possible ref leak and crashes available.

**Pull request merged**
