### PR TITLE
bpo-39896: Const args and remove unused args in Python/compile.c

### PR DESCRIPTION
**Pull request by petdance**
Remove unused args from:
* binop
* compiler_next_instr
* inplace_binop

Const arguments for:
* assemble_jump_offsets
* blocksize
* check_caller
* check_compare
* check_index
* check_is_arg
* check_subscripter
* compiler_error
* compiler_new_block
* compiler_pop_fblock
* compiler_push_fblock
* compiler_warn
* compute_code_flags
* dfs
* find_ann
* get_ref_type
* merge_const_tuple
* stackdepth

https://bugs.python.org/issue39896

### CODE REVIEW

**Comment by petdance** [comment]
I forgot the bpo in the title.  Is there a way to get @bedevere-bot to re-examine my PR?

**Comment by Mariatta** [comment]
We got webhook timeout error when you edited the title. I've re-delivered the payload.

**Comment by benjaminp** [comment]
I'm not sure if making `compiler *` arguments const is a good idea. That object represents the state of the compiler, so it's expected any part of the compiler may want to mutate it.

**Comment by petdance** [comment]
> That object represents the state of the compiler, so it's expected any part of the compiler may want to mutate it.

Understood, and that's why I suggested consting it, because it's an indicator to whoever's reading the code that the function does not change the state.

Functions like `check_caller` and `check_subscripter` and `get_ref_type` that are read-only seem the most appropriate for constness on the compiler.  

Then I changed the other worker functions like `compiler_new_block` because I figured that in all the cases of the functions I changed, since they're all static, if something needed to change that it wouldn't take much to un-const them.

OTOH, if that's too broad of a brush, I can make a new PR that's more selective.

**Comment by benjaminp** [comment]
I'd prefer not to change constness of `compiler *` arguments.

**Comment by petdance** [comment]
I'll whip up a new PR that addresses the others.

**Pull request closed without merging**
