### PR TITLE
gh-101732: Modules/_ssl.c: use Y2038 compatible openssl function when available

### PR DESCRIPTION
**Pull request by kanavin**
* Issue: gh-101732

### CODE REVIEW

**Comment by encukou** [comment]
Thanks. I see that [the function was added in OpenSSL 3.3](https://www.openssl.org/docs/man3.3/man3/SSL_SESSION_get_time.html), released April 10. (It's not in Arch You'll probably know: is there a distro/container with OpenSSL 3.3, test this?)

It returns `time_t`. Could you use `_PyLong_FromTime_t` rather than `PyLong_FromLongLong`? (This function is currently not public, but that's another issue.)

I see that Arch Linux now has OpenSSL 3.3, so I should be able to test this in an Arch VM. Before I do that, please run *your* tests with `_PyLong_FromTime_t`.

**Comment by kanavin** [comment]
> Thanks. I see that [the function was added in OpenSSL 3.3](https://www.openssl.org/docs/man3.3/man3/SSL_SESSION_get_time.html), released April 10. (It's not in Arch You'll probably know: is there a distro/container with OpenSSL 3.3, test this?)
> 
> It returns `time_t`. Could you use `_PyLong_FromTime_t` rather than `PyLong_FromLongLong`? (This function is currently not public, but that's another issue.)
> 
> I see that Arch Linux now has OpenSSL 3.3, so I should be able to test this in an Arch VM. Before I do that, please run _your_ tests with `_PyLong_FromTime_t`.

I've done that with both original and fixed (as you requested) version. The tests are run on a 32 bit system running in qemu with time set to 2050, certificates regenerated to not be expired (discussed elsewhere :), and openssl 3.3.0. 

test_ssl fails without the patch and succeeds with it.

**Comment by kanavin** [comment]
Thread-sanitizer fail doesn't seem to be related? Hard for me to tell for sure.

**Comment by encukou** [comment]
Yes, doesn't seem related.

Please don't force-push to CPython PRs; the brand new commits need to be reviewed all over again. In a bigger PR it would be an issue :)
You don't need to worry about the branch being up to date.

**Review by encukou — APPROVED** [review]
Turns out I can't easily get a 32-bit system with system clock set past 2038 :)
But on a 64-bit one, this passes, and I can't see anything wrong with the PR. So I'll merge.

**Pull request merged**
