### PR TITLE
gh-122544: Change OS image in Azure Pipelines to ubuntu-24.04

### PR DESCRIPTION
**Pull request by Damien-Chen**
Change base OS image in Azure pipeline from `ubuntu-22.04` to `ubuntu-24.04`

* Issue: gh-122544

### CODE REVIEW

**Comment by hugovk** [comment]
Please could you also add 3.13 to the triggers on line 1 of these files, and remove EOL 3.7?

**Comment by hugovk** [comment]
Or can we use `3.*` like in GitHub Actions? 

https://github.com/python/cpython/blob/d57f8a9f76e75384ec997686c2a826b1dc3c69c4/.github/workflows/build.yml#L8

**Comment by Damien-Chen** [comment]
> Or can we use `3.*` like in GitHub Actions?
> 
> https://github.com/python/cpython/blob/d57f8a9f76e75384ec997686c2a826b1dc3c69c4/.github/workflows/build.yml#L8

It seems that Azure Pipelines doesnt support patterns like  `3.*`

**Comment by hugovk** [comment]
Is `ubuntu-24.04` available for Azure Pipelines yet? 

`ubuntu-22.04` is the latest at https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

**Comment by Damien-Chen** [comment]
> Azure Pipelines

I think `ubuntu-24.04` is available based on 
https://github.com/actions/runner-images/issues/9848

> pool:
>    name: 'Azure Pipelines'
>    vmImage: 'ubuntu-24.04'

**Comment by hugovk** [comment]
I have Azure Pipelines set up on my fork, but it errored with `ubuntu-24.04`:

```
##[error]No config name or imagelabel provided in request
,##[error]The remote provider was unable to process the request.
```

https://dev.azure.com/hugovk/CPython/_build/results?buildId=5151&view=logs&j=341b3d8e-0d13-57d4-859b-65d31dcbc29e

**Comment by Damien-Chen** [comment]
> ##[error]No config name or imagelabel provided in request
> ,##[error]The remote provider was unable to process the request

It looks like strange, let me check with this

**Comment by Damien-Chen** [comment]
It seems that Azure Pipeline currently does not support `ubuntu-24.04`. Maybe we can pend this until they release it ?

**Comment by hugovk** [comment]
Sure, do you want to mark this as a draft or close it and re-open later?

**Comment by Damien-Chen** [comment]
I prefered closed it. BTW, should I send another PR that only adding 3.13 to the trigger and remove EOL 3.7 based on previous suggestion ?

**Comment by hugovk** [comment]
Yes please! No issue needed for that.

**Pull request closed without merging**
