### PR TITLE
gh-113317: Pass clinic to AC parse_arg() methods

### PR DESCRIPTION
**Pull request by vstinner**
Add 'clinic' parameter to Argument Clinic parse_arg() and bad_argument() methods. Remove usage of the 'clinic' global variable in these methods.

* Issue: gh-113317

### CODE REVIEW

**Comment by vstinner** [comment]
Currently, it is possible to get *limited_capi* from `clinic.limited_capi`. But I'm not sure how the code is going to be refactored later, so I prefer to keep the two parameters for now: *limited_capi* and *clinic*.

**Comment by erlend-aasland** [comment]
Sorry, I disagree with this approach 🙂 It would be better to teach `CConverter.add_include` to handle multiple includes per converter, and then in `output_templates()` fetch all includes from all the converters and add them via `clinic.add_include()`. If we teach `CConverter.add_include` that trick, we won't need `clinic` in `bad_argument`. Also, that will result in a much smaller diff! What do you think?

**Comment by vstinner** [comment]
> It would be better to teach CConverter.add_include to handle multiple includes per converter, and then in output_templates() fetch all includes from all the converters and add them via clinic.add_include().

Hum, that's strange: I already wrote an `add_include()` method in `CConverter`. In fact, `bad_argument()` can just reuse it.

I wrote PR #114324 which is way shorter.

**Comment by vstinner** [comment]
> I wrote PR https://github.com/python/cpython/pull/114324 which is way shorter.

Let's focus on this approach instead. I close this PR.

**Pull request closed without merging**
