### PR TITLE
gh-93421: Fix sqlite3 cursor `.rowcount` for UPDATE ... RETURNING queries

### LINKED ISSUE #93421: SQLite rowcount is corrupted when combining UPDATE RETURNING w/ table that is dropped and recreated
version info:

```
$ python
Python 3.10.0 (default, Nov  5 2021, 17:23:47) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.36.0'
```

we have a test suite that creates a table, runs some SQL, then drops it.   if multiple tests run that each perform this task, if the same SQLite connection is used, rowcount starts returning "0".   Seems to also require RETURNING to be used.   Full demonstration:

```py
import os
import sqlite3



def go():
    """function creates a new table, runs INSERT/UPDATE, drops table,
    commits connection.

    """

    # create table
    cursor = conn.cursor()
    cursor.execute(
        """CREATE TABLE some_table (
        id INTEGER NOT NULL,
        value VARCHAR(40) NOT NULL,
        PRIMARY KEY (id)
    )
    """
    )
    cursor.close()
    conn.commit()

    # run operation
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO some_table (id, value) VALUES (1, 'v1')"
    )
    ident = 1

    cursor.execute(
        "UPDATE some_table SET value='v2' "
        "WHERE id=? RETURNING id",
        (ident,),
    )
    new_ident = cursor.fetchone()[0]
    assert ident == new_ident
    assert cursor.rowcount == 1, cursor.rowcount
    cursor.close()

    # drop table
    cursor = conn.cursor()
    cursor.execute("DROP TABLE some_table")
    cursor.close()

    conn.commit()

if os.path.exists("file.db"):
    os.unlink("file.db")

# passes
conn = sqlite3.connect("file.db")
go()

# run again w/ new connection (same DB), passes
conn = sqlite3.connect("file.db")
go()

print("FAILURE NOW OCCURS")
# run again w/ same connection, fails
go()
```

on the third run, where we ran the "test" on the same connection twice, it fails:

```
$  python test3.py 
FAILURE NOW OCCURS
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 62, in <module>
    go()
  File "/home/classic/dev/sqlalchemy/test3.py", line 39, in go
    assert cursor.rowcount == 1, cursor.rowcount
AssertionError: 0
```

it would appear there's some internal caching of table state that needs to be cleared.

### PR DESCRIPTION
**Pull request by erlend-aasland**
Resolves #93421

### CODE REVIEW

**Comment by erlend-aasland** [comment]
This PR also resolves #79579

**Comment by erlend-aasland** [comment]
FYI, the failing buildbot are also failing on `main`; they are unrelated to this PR.

**Comment by animalize** [comment]
Haven't checked this method for problems.
Please consider using `sqlite3_total_changes64()`, I'm afraid `sqlite3_total_changes()` will be easier to get wrong result.

total_changes [doc](https://www.sqlite.org/c3ref/total_changes.html):
> The two functions are identical except for the type of the return value and that if the number of rows modified by the connection exceeds the maximum value supported by type "int", then the return value of sqlite3_total_changes() is undefined.

**Comment by erlend-aasland** [comment]
> Haven't checked this method for problems.

Please do; I appreciate your review.

> Please consider using `sqlite3_total_changes64()`, I'm afraid `sqlite3_total_changes()` will be easier to get wrong result.

Yes, I will make sure the 64-bit version is used, when available. Thanks for the heads-up!

**Comment by erlend-aasland** [comment]
FTR, I will revert the DML check change in this PR; that is cleaner.

**Comment by animalize** [comment]
Just found `sqlite3_total_changes64()` is a very new function,  added in 3.37.0 (2021-11-27)

If change one row per second, it will overflow after 68 years:
```python
>>> (2**31-1)/3600/24/365
68.09625973490614
```
Not afraid of you laughing, I hope a program can run 1000 years without errors, in theory we can achieve this goal.

**Comment by erlend-aasland** [comment]
> Just found `sqlite3_total_changes64()` is a very new function, added in 3.37.0 (2021-11-27)

Yes, both of the 64-bit changes APIs were added in 3.37.0.

> Not afraid of you laughing, I hope a program can run 1000 years (or forever) without errors, in theory we can achieve this goal.

Absolutely. But I also like to keep in mind that perfect is the enemy of good. IMO, a some of the sqlite3 issues have fallen to this; the proposed solution is not perfect, so we're stuck with API pains and bugs. A pragmatic view may, in some cases, be beneficial.

For the record: for now, I think my alternative PR is the better solution for this issue.

**Comment by erlend-aasland** [comment]
Closing in favour of gh-93526

**Pull request closed without merging**
