### PR TITLE
gh-81488: Add recursive wording for issubclass

### PR DESCRIPTION
**Pull request by slateny**
#81488

### CODE REVIEW

**Comment by AlexWaygood** [comment]
This probably can't be cleanly backported to 3.9 due to the reference to Union types. Are you interested in doing a manual backport to 3.9 (if it's merged), or shall we leave 3.9?

**Review by AlexWaygood — APPROVED** [review]
I've no idea what's going on with the CI failures, but this LGTM

**Comment by slateny** [comment]
Sure, I can do a manual backport, and not too sure about the CI error either

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
@slateny leaving the 3.9 backport to you. Thanks for your many docs improvements!

**Pull request merged**
