### PR TITLE
gh-101619: Improve performance of `list_repeat`

### LINKED ISSUE #101619: Improve `list_repeat`
[Current implementation](https://github.com/python/cpython/blob/main/Objects/listobject.c#L552) of `list_repeat` doesn't took into consideretion case when `n` is equals to 1.
(Implementation of `list_inplace_repeat` has this check)
We can add this block of code to function
```c

    const Py_ssize_t input_size = Py_SIZE(a);
    if (n == 1 && input_size != 0){
        PyListObject *np = (PyListObject *) list_new_prealloc(input_size);
        PyObject **src = a->ob_item;
        PyObject **src_end = src + input_size;
        PyObject **dest = np->ob_item;
        while (src < src_end) {
            _Py_RefcntAdd(*src, n);
            *dest++ = *src++;
        }
        Py_SET_SIZE(np, input_size);
        return (PyObject *) np;
    }
```
This prevent us from calculating output size (because output size is equals to input size) and other checks.

### Linked PRs
* gh-101695

### PR DESCRIPTION
**Pull request by Eclips4**
Resolves #101619 
Thanks @peendebak for advices.

* Issue: gh-101619

### CODE REVIEW

**Comment by carljm** [comment]
Code looks fine to me. It would be good to get a run of the full `pyperformance` benchmark suite, to see if this moves the needle at all. I suspect that it won't; repeating a list `* 1` is likely uncommon, and a 9% improvement in a rare case likely won't translate to any visible improvement in real code.

**Comment by carljm** [comment]
Those pyperformance results are definitely impressive, and a bit suspicious (unless `list_repeat` is used more places than I thought.) Maybe someone from faster-cpython team will be able to trigger a run on their standardized pyperformance measurement infra to confirm. If those results are confirmed, this definitely seems worth adding.

**Comment by Eclips4** [comment]
I checked it again, and got same results. Interesting. I didn't expect such results.

**Comment by eendebakpt** [comment]
@Eclips4 I cannot run the pyperformance benchmark itself, but I can run individual tests. I did not see improvements for the benchmarks I tested (deepcopy_memo, coroutines).

**Comment by Eclips4** [comment]
> @Eclips4 I cannot run the pyperformance benchmark itself, but I can run individual tests. I did not see improvements for the benchmarks I tested (deepcopy_memo, coroutines).

How did you benchmark it? I will try this on another machine

**Comment by eendebakpt** [comment]
> > @Eclips4 I cannot run the pyperformance benchmark itself, but I can run individual tests. I did not see improvements for the benchmarks I tested (deepcopy_memo, coroutines).
> 
> How did you benchmark it? I will try this on another machine

Download the pyperformance code from GitHub, go to the folder https://github.com/python/pyperformance/tree/main/pyperformance/data-files/benchmarks/bm_deepcopy and run
```
python run_benchmark.py
```

**Comment by Eclips4** [comment]
I got such results:
deepcopy
old:
```
.....................
deepcopy: Mean +- std dev: 323 us +- 3 us
.....................
deepcopy_reduce: Mean +- std dev: 2.91 us +- 0.04 us
.....................
deepcopy_memo: Mean +- std dev: 32.8 us +- 0.3 us
```
new:
```
.....................
deepcopy: Mean +- std dev: 319 us +- 2 us
.....................
deepcopy_reduce: Mean +- std dev: 2.90 us +- 0.05 us
.....................
deepcopy_memo: Mean +- std dev: 29.7 us +- 0.2 us
```

coroutines:
old:
```
.....................
coroutines: Mean +- std dev: 22.8 ms +- 0.2 ms
```
new:
```
.....................
coroutines: Mean +- std dev: 21.8 ms +- 0.2 ms
```
The results really don't differ much.
I'll probably close PR and Issue.

**Comment by eendebakpt** [comment]
Thanks for making the effort!

**Pull request closed without merging**
