### PR TITLE
bpo-43232: Prohibit previously deprecated operations on TransportSocket

### PR DESCRIPTION
**Pull request by illia-v**
Probably the warning should be updated in Python 3.8 and Python 3.9 to avoid confusion ("will be prohibited in asyncio 3.9" -> "will be prohibited in Python 3.10").

https://bugs.python.org/issue43232

### CODE REVIEW

**Comment by illia-v** [comment]
BTW, I didn't document the change in What's New, because it looks like the class is pretty low-level. If it should be documented there, please let me know in what section: neither "Deprecated" nor "Removed" seem to suite.

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
Instead of explicitly raising RuntimeError, just remove the corresponding methods.

**Comment by illia-v** [comment]
I have made the requested changes; please review again

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
The warning was added in 3.8 (see #81208), 4 years ago. This PR was merged 2 years ago. Please open a new issue for your use case.

**Pull request merged**
