### PR TITLE
gh-127282: fix concurrent/future/thread.py: _python_exit

### PR DESCRIPTION
**Pull request by SekaiArendelle**
relate to https://github.com/python/cpython/issues/127282

* Issue: gh-127282

### CODE REVIEW

**Review by ZeroIntensity — COMMENTED** [review]
Thanks for contributing! This needs a NEWS entry and a simple test (you'll probably need to add one to [test_thread_pool](https://github.com/python/cpython/blob/main/Lib/test/test_concurrent_futures/test_thread_pool.py)).

I'm a little on the fence about this change, the `timeout=2` feels a bit arbitrary, and I don't know how stable it is (this doesn't do anything for Linux, FWIW).

**Comment by GoodenoughPhysicsLab** [comment]
should we use `platforms.system()`, and even fix `join` further

**Comment by GoodenoughPhysicsLab** [comment]
it seems that there is no need to add a new dependence of `platforms`, I will have a try to add one to test.

**Comment by GoodenoughPhysicsLab** [comment]
it's hard for me to add a test, because the program can't know that he is blocked.

**Comment by GoodenoughPhysicsLab** [comment]
The problem of `Thread.join` have been fixed somewhere. Therefore, I'll close this issue.

**Pull request closed without merging**
