### PR TITLE
gh-123811: test that round() can return signed zero

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-123811

### CODE REVIEW

**Comment by skirpichev** [comment]
Probably could skip news.

**Review by vstinner — APPROVED** [review]
LGTM

**Review by Eclips4 — APPROVED** [review]

**Comment by vstinner** [comment]
Merged, thanks @skirpichev.

**Comment by serhiy-storchaka** [comment]
Is this tested for Decimal?

**Pull request merged**
