### PR TITLE
[3.9] bpo-40246: Fix test_fstring when run with the old parser

### PR DESCRIPTION
**Pull request by lysnikolaou**
https://bugs.python.org/issue40246

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
@lysnikolaou This does not affect 3.10?

**Comment by lysnikolaou** [comment]
It currently does, but I don't think we need to fix that, since the old parser will be removed some time before the 3.10 release.

**Comment by pablogsal** [comment]
> It currently does, but I don't think we need to fix that, since the old parser will be removed some time before the 3.10 release.

:boom: I am waiting to unleash the destruction PR :wink:

**Comment by lysnikolaou** [comment]
Looking forward to that.

**Pull request merged**
