### PR TITLE
docs: add a more precise example

### PR DESCRIPTION
**Pull request by Ret2Me**
Previous example used manual integer value assignment in class based declaration but in functional syntax has been used auto value assignment what could be confusing for the new users.
Additionally documentation doesn't show how to declare new enum via functional syntax with usage of the manual value assignment.

----
📚 Documentation preview 📚: https://cpython-previews--121015.org.readthedocs.build/

### CODE REVIEW

**Review by ethanfurman — CHANGES_REQUESTED** [review]
Most of the changes are not necessary.  I would accept a second example, similar to your proposed example, of `...[('RED', 1), ('GREEN', 2), ...`.

**Comment by Ret2Me** [comment]
I have made the requested changes; please review again

**Comment by willingc** [comment]
@ethanfurman I'm triaging open doc PRs. Do you want to review this one again? Thanks!

**Review by willingc — APPROVED** [review]

**Review by ethanfurman — APPROVED** [review]

**Review by willingc — APPROVED** [review]
Thanks @ethanfurman for the new review and @Ret2Me for the contribution.

**Pull request merged**
