### PR TITLE
bpo-28340: backport io.TextIOWrapper.tell() improvements to py2.7

### PR DESCRIPTION
**Pull request by rmalouf**
io.TextIOWrapper.tell() is unusably slow in Python 2.7.  This same problem was introduced in Python 3 and fixed in Python 3.3, and this is my attempt at backporting the fix to 2.7.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by rmalouf** [comment]
Anyone?

**Comment by Mariatta** [comment]
I'll be closing and re-opening this PR to trigger the bots.

**Comment by Mariatta** [comment]
The issue has been closed as won't fix, so I'll close this PR. Thanks!

**Pull request closed without merging**
