### PR TITLE
Buildbot testing PR - DO NOT MERGE

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by pablogsal** [comment]
GG

**Comment by pablogsal** [comment]
sdfsdf

**Comment by pablogsal** [comment]
fdgfg

**Comment by pablogsal** [comment]
sdfsdfsd

**Comment by pablogsal** [comment]
sdfsdfsd

**Comment by pablogsal** [comment]
dsffsdfsd

**Comment by pablogsal** [comment]
sdfsdfsdf

**Comment by pablogsal** [comment]
dsdfsdf

**Comment by pablogsal** [comment]
sadfsdfsda

**Comment by pablogsal** [comment]
dfgdfg

**Comment by pablogsal** [comment]
sdfgdfsgsdfgsdf

**Comment by pablogsal** [comment]
sdfsdf

**Comment by pablogsal** [comment]
!buildbot lelelele

**Comment by pablogsal** [comment]
!buildbot lelelele

**Comment by pablogsal** [comment]
!buildbot lelelele

**Comment by pablogsal** [comment]
!buildbot lelelele

**Comment by pablogsal** [comment]
!buildbot lelelele

**Comment by pablogsal** [comment]
!buildbot aarch64

**Comment by pablogsal** [comment]
!buildbot AMD64

**Comment by pablogsal** [comment]
!buildbot aarch64

**Comment by pablogsal** [comment]
!buildbot aarch64

**Comment by pablogsal** [comment]
!buildbot Arch Linux Asan

**Comment by pablogsal** [comment]
!buildbot Arch\sLinux

**Comment by pablogsal** [comment]
!buildbot Arch

**Comment by pablogsal** [comment]
!buildbot Linux

**Comment by pablogsal** [comment]
!buildbot .*Asan.*

**Comment by pablogsal** [comment]
!buildbot .*Usan.*

**Comment by pablogsal** [comment]
!buildbot .*Usan.*

**Comment by gpshead** [comment]
Where does the code implementing !buildbot live?

**Comment by pablogsal** [comment]
> Where does the code implementing !buildbot live?

here: https://github.com/python/buildmaster-config/blob/e528a03acad215b790236627408863e3ea6f4284/master/custom/pr_testing.py#L183-L276

**Pull request closed without merging**
