### PR TITLE
[3.12] Sync location of `mypy` pin with the `main` branch

### PR DESCRIPTION
**Pull request by art3xa**
Move `mypy` pin from `Tools/clinic/requirements-dev.txt` to `Tools/requirements-dev.txt`

(https://github.com/python/cpython/pull/111313#issuecomment-1779088740)

### CODE REVIEW

**Review by AlexWaygood — CHANGES_REQUESTED** [review]
Thanks! You'll also need to change this line to reflect the new location:

https://github.com/python/cpython/blob/5c4f9a1c7ed9fddd8c3ce4c1793af07f66f36a6b/.github/workflows/mypy.yml#L38

**Review by AlexWaygood — APPROVED** [review]
Thanks!

**Comment by hugovk** [comment]
There's also some docs ones at https://github.com/python/cpython/issues/110383

And “easy”, “good first issue” and “help wanted” issues in other Python core repos:

* https://github.com/search?q=org%3Apython+-repo%3Apython%2Fcpython+is%3Aissue+is%3Aopen+label%3Aeasy%2C%22good+first+issue%22%2C%22help+wanted%22&type=issues&ref=advsearch

**Comment by art3xa** [comment]
Thank you so much!)

**Pull request merged**
