### PR TITLE
gh-114812: Allow distributions to modify ModuleNotFoundError messages

### PR DESCRIPTION
**Pull request by hoodmane**
* Issue: gh-114812

### CODE REVIEW

**Comment by hoodmane** [comment]
Do I need to run some regenrate frozen libs make script?

**Comment by terryjreedy** [comment]
Main question is whether this needs PEP approval first, or whether it should be removed from PEP.  That discussion should be on issue.

Implementation (patch) look ok to me, but I won't apply.  Regeneration should be automatic, I think.  In any case, code tests pass.  This should have both news and What's New entry; I think this can wait until main question resolved.  Anyway, whoever commits might want to write those, or at least the What's New patch.

**Comment by encukou** [comment]
With this, distributors can modify the message by patching a private function.
But I don't see much difference between patching `_find_and_load_unlocked` rather than `_find_and_load_unlocked`.
As is, the PR doesn't really do anything to make this a supported feature.

**Comment by hoodmane** [comment]
Well `_find_and_load_unlocked` is a much longer function to patch and we'd have to put in something like an assertion that `inspect.get_source` on the function returns the expected original value to make sure that the patch isn't causing a nonobvious breakage. Applying this patch is a much better solution since if the patch context changes it will fail and we'll have to rebase the patch. But what would be even better is if we could upstream the patch. If a later change to Python breaks it we'll find out from our tests failing and we could go back to patching, but in the meantime it will save on rebasing patches.

My hope was that this is a more or less trivial code change that would be easy to accept, and that discussion about whether or not to standardize something that's formally supported could happen separately.

**Comment by hoodmane** [comment]
Okay I'm going to close this since I am convinced by the feedback in the issue to use a different approach.

**Pull request closed without merging**
