### PR TITLE
gh-126914: Use an atomic field for determining if the initial thread can be used

### PR DESCRIPTION
**Pull request by ZeroIntensity**
* Issue: gh-126914

### CODE REVIEW

**Comment by ZeroIntensity** [comment]
QSBR seems to be breaking on free-threading for whatever reason :(

**Comment by ZeroIntensity** [comment]
Looks like the new fix works. Yay!

**Comment by ericsnowcurrently** [comment]
While this solution makes sense, I have some thoughts on an alternate approach that will be better for us long-term.  See gh-126989.

**Comment by ZeroIntensity** [comment]
Closing in favor of GH-126989

**Pull request closed without merging**
