### PR TITLE
bpo-32280: Store `_PyRuntime` in a named section

### PR DESCRIPTION
**Pull request by maxbelanger**
This patch stores the `_PyRuntime` structure in a section of the same name (on Windows, macOS or Linux; otherwise untested in our configurations). This allows a debugging or crash reporting tool to quickly locate this structure at runtime without requiring the symbol table.

https://bugs.python.org/issue32280

### CODE REVIEW

**Review by Rezduan83 — APPROVED** [review]

**Comment by ericsnowcurrently** [comment]
@zooba, I figure you'd know about "named sections" well enough to have some insight here.  The point of the PR may be moot (see the BPO issue), but let's assume we want to accommodate the use case described in the issue.  Is a named section the right way to go?  Is the proposed change the approach we'd want in CPython?

Note that the question of the fate of the `_Py_Runtime` static global is discussed separately in the BPO issue. :)

**Comment by ericsnowcurrently** [comment]
ping, @zooba

**Comment by vstinner** [comment]
> csabella requested a review from vstinner 2 days ago 

I don't know anything about the Windows and macOS specific pagma. So I have no opinion on this PR.

**Comment by pablogsal** [comment]
This can be very useful to debuggers so I think this is a good idea but I think we should just have it as non-stable detail that could change if we need to so I am removing the NEWS item. People implementing debuggers and runtime state tools will already read the source to reverse engineer the information needed so they will find this in any case.

I have also updated the patch to include this on Linux for gcc/clang

**Comment by pablogsal** [comment]
Example usage:

```
✦ ❯ readelf -t ./python | grep PyRuntime -A 2
  [27] .PyRuntime
       PROGBITS         00000000005a0cd0  000000000059fcd0  0
       00000000000002a0 0000000000000000  0                 8

✦ ❯ ./python
Python 3.11.0a0 (heads/impl-runtime-section-dirty:7f48393536, Jun  3 2021, 23:39:39) [Clang 11.1.0 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
[2]  + 107638 suspended  ./python

✦2 ❯ head /proc/107638/maps
56268ebed000-56268ec48000 r--p 00000000 08:12 5247400                    /home/pablogsal/github/python/master/python

❯ sudo gdb -p 107638
gdb) x/b (0x56268ebed000+0x00000000005a0cd0)
0x56268f18dcd0 <_PyRuntime>:    0
```

**Pull request merged**
