### PR TITLE
bpo-39324: Add markdown mimetype mapping

### PR DESCRIPTION
**Pull request by rdbatch**
Adding markdown mapping (.md <-> text/markdown) to mimetypes as registered here https://www.iana.org/assignments/media-types/text/markdown.

https://bugs.python.org/issue39324

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@rdbatch02

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by eamanu — COMMENTED** [review]
Hi, @rdbatch02 thanks for the PR. IMHO this should be discuss, I recommend you write to python-ideas mailing list, but the opened the issue it's ok. 

This will need  a NEWS. And don't forget sign the CLA

**Comment by rdbatch02** [comment]
> Hi, @rdbatch02 thanks for the PR. IMHO this should be discuss, I recommend you write to python-ideas mailing list, but the opened the issue it's ok.
> 
> This will need a NEWS. And don't forget sign the CLA

Hi @eamanu, I've added a NEWS and it looks like the CLA went through. Should I plan to submit this to the mailing list as well in addition to the issue that I opened? Or can discussion be solicited on the open issue?

**Comment by tirkarthi** [comment]
The RFC also includes `.markdown` as an extension though I have seen `.md` to be more common

Relevant part : "File extension(s): .md, .markdown"

**Comment by rdbatch02** [comment]
Thanks for the heads up on that @tirkarthi, I haven't seen the `.markdown` extension myself but it's worth adding since it's in the RFC. Updated this PR.

**Comment by legendofa** [comment]
Hi, is there something in the way of merging this? Which of the checks are not completed yet?

**Comment by jaraco** [comment]
@Yhg1s Would you agree this is a bugfix? It seems a shame to leave this missing important content type to be missing for years to come.

**Review by jaraco — APPROVED** [review]

**Comment by vstinner** [comment]
What's the status of the 3.12 backport? https://github.com/python/cpython/pull/118594

**Pull request merged**
