### PR TITLE
bpo-37083: Add TYPE_COMMENT for updated grammar

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue37083

### CODE REVIEW

**Comment by gvanrossum** [comment]
Surely there are more places where TYPE_COMMENT is allowed? Check the Grammar file.

**Comment by corona10** [comment]
@gvanrossum 
Thanks for the review.
I read https://github.com/python/cpython/blob/master/Grammar/Grammar file and I found that `funcdef` was missed on compound_stmts.rst.
I am going the wrong way?

**Comment by gvanrossum** [comment]
I'll comment on the bpo issue. TLDR: Don't merge this.

**Comment by corona10** [comment]
> I'll comment on the bpo issue. TLDR: Don't merge this.

Got it. Thanks for letting me know.

**Pull request closed without merging**
