### PR TITLE
Typo fix in file Python/getopt.c

### PR DESCRIPTION
**Pull request by hansrajdas**
Typo fix in file Python/getopt.c
* improvment should be improvement
* Extra whitespece removed

### CODE REVIEW

**Review by mangrisano — APPROVED** [review]
Thank you.

**Comment by benjaminp** [comment]
We should probably just delete this paragraph. It seems unlikely that David Gottner would want to hear about Python's hacked-up copy of his code.

**Comment by hansrajdas** [comment]
@benjaminp and @mangrisano - thanks for your time, so shall i delete these 3 lines?

**Comment by hansrajdas** [comment]
> We should probably just delete this paragraph. It seems unlikely that David Gottner would want to hear about Python's hacked-up copy of his code.

@benjaminp I have deleted the requested paragraph. Please take a look. Thank you!

**Pull request merged**
