### PR TITLE
bpo-45510: Specialize BINARY_SUBTRACT

### PR DESCRIPTION
**Pull request by corona10**
https://github.com/faster-cpython/ideas/issues/100

https://bugs.python.org/issue45510

### CODE REVIEW

**Comment by corona10** [comment]
> Sorry about the conflicts. I wanted to get both the CALL_FUNCTION specializations PRs merged.

i can do this all day

**Comment by corona10** [comment]
@markshannon cc @pablogsal @Fidget-Spinner 

> My concern with this change is that it will slow down any subtraction on anything other than pairs of ints and floats.

I definitely agree with your concern. So do I, At first, I thought that it's okayish since we already have the issue with `BINARY_ADD`. So if this change is not worth to applied, let's stale the PR until the issue is solved.

> I'd like to see some microbenchmarks for int - float, float - int, and decimal - decimal.

Whether merge this PR or not, it's worth measuring such benchmarks, we can get some data from this experiment.
I will share the result after writing some scripts.

**Comment by markshannon** [comment]
Will need reworking once #29482 is merged. Sorry to make you redo this, yet again :slightly_frowning_face:

I think the end result will be better though, as we won't need yet another `ADAPTIVE` instruction.

**Comment by corona10** [comment]
@markshannon 
#29482 looks great approach, I will newly create the PR once the PR is merged.
Thanks for letting me know.

**Comment by brandtbucher** [comment]
Should this PR be closed (in favor of #29523)?

**Pull request closed without merging**
