### PR TITLE
Docs: Fix Makefile syntax

### PR DESCRIPTION
**Pull request by AA-Turner**
xref: #123113.

A

----
📚 Documentation preview 📚: https://cpython-previews--123287.org.readthedocs.build/

### CODE REVIEW

**Comment by AA-Turner** [comment]
This was the smallest resolution, we could alternatively use the approach Hugo suggested:

> I think we can define this near the top:
>
>```make
>NUM_CPUS := $(shell nproc)
>JOBS := $(shell echo $$(($(NUM_CPUS) + 1)))
>```
>
>And then change the commands to use `--jobs=$(JOBS)`

**Review by JulienPalard — APPROVED** [review]

**Review by hugovk — APPROVED** [review]
Let's hold off merging the backports until after we've verified `main`/3.14 is now building. I'll keep an eye on the server logs.

**Comment by hugovk** [comment]
> Let's hold off merging the backports until after we've verified `main`/3.14 is now building. I'll keep an eye on the server logs.

On second thoughts, let's merge backports now to get faster feedback.

It's currently doing zh-cn/3.14 with commit 5ff638f1b53587b9f912a18fc776a2a141fd7bed, which is the one just before this PR was merged:


```console
❯ rg "cpython reset --hard" docsbuild.log
36:2024-08-24 00:03:15,339 DEBUG pl/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
91:2024-08-24 00:09:01,324 DEBUG ko/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
146:2024-08-24 00:18:58,541 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
201:2024-08-24 00:31:13,907 DEBUG it/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
256:2024-08-24 00:37:02,575 DEBUG id/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
312:2024-08-24 00:47:34,482 DEBUG fr/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
367:2024-08-24 00:56:48,811 DEBUG es/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
424:2024-08-24 01:08:22,284 DEBUG en/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard 935b8b422b801f8c6a6ac35f5f2493f05279ae9e --'
473:2024-08-24 01:13:44,563 DEBUG zh-tw/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
530:2024-08-24 02:28:31,925 DEBUG zh-cn/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
586:2024-08-24 03:27:11,430 DEBUG uk/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
3961:2024-08-24 03:31:51,789 DEBUG tr/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4014:2024-08-24 03:38:28,717 DEBUG pt-br/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4068:2024-08-24 03:48:23,932 DEBUG pl/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4122:2024-08-24 03:53:59,419 DEBUG ko/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4177:2024-08-24 04:03:51,403 DEBUG ja/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4233:2024-08-24 04:15:33,154 DEBUG it/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4288:2024-08-24 04:21:35,323 DEBUG id/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4344:2024-08-24 04:31:49,370 DEBUG fr/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4399:2024-08-24 04:41:07,989 DEBUG es/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4455:2024-08-24 04:52:46,512 DEBUG en/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 58fdb169c8a93925541fecc74ba73c566147f2ca --'
4648:2024-08-24 05:07:02,698 DEBUG zh-tw/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
4701:2024-08-24 06:16:16,789 DEBUG zh-cn/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
4757:2024-08-24 07:09:34,118 DEBUG uk/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8209:2024-08-24 07:13:42,824 DEBUG tr/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8262:2024-08-24 07:20:26,121 DEBUG pt-br/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8317:2024-08-24 07:28:32,781 DEBUG pl/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8371:2024-08-24 07:34:23,989 DEBUG ko/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8426:2024-08-24 07:42:43,401 DEBUG ja/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8481:2024-08-24 07:52:59,192 DEBUG it/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8536:2024-08-24 07:58:38,048 DEBUG id/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8592:2024-08-24 08:08:16,705 DEBUG fr/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8647:2024-08-24 08:16:11,245 DEBUG es/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8702:2024-08-24 08:25:43,708 DEBUG en/3.12: Run: 'git -C /srv/docsbuild/cpython reset --hard 7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a --'
8751:2024-08-24 08:30:46,106 DEBUG zh-tw/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
8807:2024-08-24 09:40:18,717 DEBUG zh-cn/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
8863:2024-08-24 10:33:33,379 DEBUG uk/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10563:2024-08-24 10:37:42,071 DEBUG tr/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10616:2024-08-24 10:44:20,871 DEBUG pt-br/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10670:2024-08-24 10:53:59,354 DEBUG pl/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10724:2024-08-24 10:59:35,915 DEBUG ko/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10780:2024-08-24 11:09:20,225 DEBUG ja/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10835:2024-08-24 11:21:27,970 DEBUG it/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10893:2024-08-24 11:27:13,182 DEBUG id/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
10948:2024-08-24 11:37:23,290 DEBUG fr/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
11003:2024-08-24 11:46:46,219 DEBUG es/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
11059:2024-08-24 11:58:09,579 DEBUG en/3.13: Run: 'git -C /srv/docsbuild/cpython reset --hard a65fe07db4aa57b4e67f2f9e914db7ea281f127f --'
11108:2024-08-24 12:03:50,259 DEBUG zh-tw/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 5ff638f1b53587b9f912a18fc776a2a141fd7bed --'
11166:2024-08-24 13:13:15,847 DEBUG zh-cn/3.14: Run: 'git -C /srv/docsbuild/cpython reset --hard 5ff638f1b53587b9f912a18fc776a2a141fd7bed --'
```

Looks like it'll do the rest of the 3.14 loop with this old 5ff638f1b53587b9f912a18fc776a2a141fd7bed commit.

(By the way, this seems room for improvement: each language/version could fetch the latest commit when it begins, rather than when the batch begins, so each builds with the newest checkout right now, instead of one potentially many hours old.)

Then it'll move to 3.12 and 3.13, and it'll be about 11 hours until it gets to 3.14 again. However, it'll start on 3.12 in about 2.5 hours.

**Comment by hugovk** [comment]
This is working now, thanks!

It actually started with 3.14 again, and so far has built these:

|      Start       | Language/version |  Build |
| :--------------: | :--------------: |------: |
| 2024-08-24 16:07 |    zh-tw/3.14    | 1h 36m |
| 2024-08-24 17:44 |    zh-cn/3.14    | 1h 22m |
| 2024-08-24 19:08 |     uk/3.14      |     3m |
| 2024-08-24 19:13 |     tr/3.14      | 1h 34m |

Comparison with their previous builds:


|      Start       | Language/version |  Build |
| :--------------: | :--------------: |------: |
| 2024-08-18 21:33 |    zh-tw/3.14    | 1h 59m |
| 2024-08-18 23:33 |    zh-cn/3.14    | 1h 48m |
| 2024-08-19 01:24 |     uk/3.14      |     4m |
| 2024-08-19 01:30 |     tr/3.14      | 2h 25m |

Which is a nice improvement of 20-40 mins each!

(uk/3.14 is HTML only.)

I'll post comparisons back in the main thread after we've had more builds :)

**Comment by hugovk** [comment]
> (By the way, this seems room for improvement: each language/version could fetch the latest commit when it begins, rather than when the batch begins, so each builds with the newest checkout right now, instead of one potentially many hours old.)

I've opened https://github.com/python/docsbuild-scripts/issues/190 for this.


> I'll post comparisons back in the main issue after we've had more builds :)

Build times about 1.5 as fast! https://github.com/python/docsbuild-scripts/issues/169#issuecomment-2308783834

**Pull request merged**
