### PR TITLE
gh-111863: Rename `Py_NOGIL` to `Py_GIL_DISABLED`

### PR DESCRIPTION
**Pull request by hugovk**
A suggestion for gh-111863, following the pattern of the `--disable-gil` flag.

cc @colesbury

### CODE REVIEW

**Comment by pitrou** [comment]
Then I would suggest `Py_GIL_DISABLED` (using a noun + adjective, rather than a verb, for a constant).

**Comment by colesbury** [comment]
Thanks @hugovk. I would like some comment first from the Python steering council about the preferred name so that:

1) We don't need to change it again in the future.
2) We don't spend too much time bikeshedding the name.

Beyond that, we'll also need to change [`pypa/packaging`](https://github.com/search?q=org%3Apypa+Py_NOGIL&type=code) as it uses `sysconfig.get_config_var("Py_NOGIL")`, which comes from the macro defined in `configure`.

**Comment by gpshead** [comment]
The SC threw our xkcd-randomized dart at the dartboard of bikeshed names: it landed on `Py_GIL_DISABLED`.

**Review by colesbury — APPROVED** [review]

**Comment by Yhg1s** [comment]
This created a file in Misc/NEWS.d/next/C_API, presumably by accident. The actual directory should be Misc/NEWS.d/next/"C API" (a space instead of an underscore). Was the blurb file created by hand, or is this a bug in blurb or blurb-it?

**Pull request merged**
