### PR TITLE
gh-101907: Removes use of non-standard C++ extension from Include/cpython/code.h

### PR DESCRIPTION
**Pull request by zooba**
Updates all references to use the macros, so that changes are localised to the header file.

* Issue: gh-101907

### CODE REVIEW

**Comment by zooba** [comment]
Another possible fix (that I haven't tested yet) would be to move this struct into a private header. I don't have any strong preference, but I'm also not familiar with its background and intended use.

**Comment by markshannon** [comment]
This is C11, not C++.

What problem is this causing?

**Comment by markshannon** [comment]
Anonymous unions are quite useful, especially for inserting unions into a struct and retaining API compatibility. It's a shame we can't use them.

**Comment by zooba** [comment]
I agree they're useful, but I don't need to be convinced. We have to win over the C++ committee 😄 And then wait a decade for it to be generally available in all the compilers we support.

Incidentally, I noticed the `SET` macro, so I fixed it and am switching the assignments to use that.

**Comment by zooba** [comment]
#101912 is an alternate PR to this one

**Comment by zooba** [comment]
We prefer #101912

**Pull request closed without merging**
