### PR TITLE
bpo-39374: Updated sorting documentation with better key function description

### PR DESCRIPTION
**Pull request by juhanakristian**
https://bugs.python.org/issue39374

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@brandfilt

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by terryjreedy — APPROVED** [review]
I approve either as is, with (...) added twice, or with it added only once.  Raymond, do you have a preference?  I will merge if you want.

**Comment by terryjreedy** [comment]
@brandfilt Please sign CLA if you have not.  It is really easy.  I believe we can merge this without, but 'with' is easier, and we would be set for your next PR.

**Comment by brandfilt** [comment]
@terryjreedy I added my GitHub name to bugs.python.org details and signed the CLA after creating the pull request

**Comment by terryjreedy** [comment]
Thanks.  It takes a working day for it to get recorded properly.

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
The Azure Pipeline seems to be stuck.  Closing and reopening this PR in an attempt to restart it.

**Pull request merged**
