### PR TITLE
Remove `ifdef` check for an OpenSSL version (0.9.6) we don't support

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Review by tiran — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Compiler warning:
```
/home/serhiy/py/cpython/Modules/_ssl.c: In function ‘newPySSLSocket’:
/home/serhiy/py/cpython/Modules/_ssl.c:885:10: warning: unused variable ‘mode’ [-Wunused-variable]
     long mode;
          ^~~~
```

**Comment by alex** [comment]
@serhiy-storchaka Good catch thanks -- should we be using `-Werror` or something in CI?

**Comment by serhiy-storchaka** [comment]
There are several compiler warnings produced on different platforms, especially on non-master branches.

**Comment by Mariatta** [comment]
I'm a little confused here. Has the backport to 3.7 been done? Where is the PR for it so I can remove the needs backport to 3.7 label.

**Pull request merged**
