### PR TITLE
gh-110262: Handle `PyList_SetSlice` error in `object.c`

### PR DESCRIPTION
**Pull request by sobolevn**
Sorry for the PRs spam, @JelleZijlstra!

* Issue: gh-110262

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
Even if `PyList_SetSlice()` fails, I do not see how the change makes difference. Bot `break` and `goto finally` lead to the same code.

This code was not changed since 1998 when it was added by @gvanrossum in 8661036cb807dbb55badfeeaa9723c11118bd5c7.

**Comment by sobolevn** [comment]
Yeap, this is the change I was not quite sure about as I said in https://github.com/python/cpython/issues/110262

**Comment by serhiy-storchaka** [comment]
Let's not fix what isn't broken.

**Comment by sobolevn** [comment]
@serhiy-storchaka thank you for all the review! They are really helpful! 👍

**Comment by serhiy-storchaka** [comment]
I apologize for having to reject some of your suggestions, but sometimes knowing what not to do is just as important as knowing what to do.

**Comment by sobolevn** [comment]
This what I learn from you!

**Pull request closed without merging**
