### PR TITLE
gh-111544: Fix mimalloc build on AIX

### PR DESCRIPTION
**Pull request by ayappanec**
This PR is to fix the problem mentioned in the issue #111544 

* Issue: gh-111544

### CODE REVIEW

**Comment by erlend-aasland** [comment]
ISTM this change can be upstreamed. What do you think?

**Comment by vstinner** [comment]
It LGTM, but can you please remove the Changlog (NEWS) entry? It's not useful for the next Python release.

**Comment by vstinner** [comment]
cc @DinoV

**Comment by ayappanec** [comment]
> It LGTM, but can you please remove the Changlog (NEWS) entry? It's not useful for the next Python release.

I just removed the NEWS entry.

**Comment by vstinner** [comment]
Merged, thanks.

**Comment by ayappanec** [comment]
> Merged, thanks.

Thank you very much for the support.

**Pull request merged**
