### PR TITLE
bpo-36388: fix Pdb.do_debug to not trace itself

### PR DESCRIPTION
**Pull request by blueyed**
https://bugs.python.org/issue36388

### CODE REVIEW

**Comment by blueyed** [comment]
This is still legit, but only missing review and a test.
It's used in pdp++, where it has a test that could be adopted: https://github.com/pdbpp/pdbpp/commit/dd633bb551ecfcf9b2afb67fd6f0eb43fe96990c#diff-b95fdb555737b59555993f2928802c507ba6b466dd9de0f8bafa256c1cce52d2R5992-R6013

**Review by asvetlov — CHANGES_REQUESTED** [review]
The patch looks good.
NEWS entry and tests are needed.

**Comment by AlexWaygood** [comment]
Ping, @blueyed -- is this still something you're interested in working on?

**Comment by kumaraditya303** [comment]
Closing as it is stale, if you want to work on this, the PR can be re-opened or a new PR can be created.

**Pull request closed without merging**
