### PR TITLE
missing multiply symbol in the documentation

### PR DESCRIPTION
**Pull request by sekomer**
I added the missing symbol to the documentation, thanks in advance.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Sekomer

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Sekomer** [comment]
I don't know how to add "skipnews" and "skipissue" labels, how can i add them ?

**Comment by Sekomer** [comment]
Could you please handle "skipnews" and "skipissue" problems...

**Review by JulienPalard — APPROVED** [review]
LGTM

**Comment by Sekomer** [comment]
Oh you are very kind 😊 thank you.  I will do my best and try to make more contributions :)) Kimden: Julien PalardGönderilme: 3 Mart 2021 Çarşamba 12:13Kime: python/cpythonBilgi: Alperen Serkan Aksöz; MentionKonu: Re: [python/cpython] missing multiply symbol in the documentation (#24686) @JulienPalard approved this pull request.LGTM—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
