### PR TITLE
bpo-35308: Fix regression where BROWSER env var is not respected

### PR DESCRIPTION
**Pull request by zmwangx**
https://bugs.python.org/issue35308

### CODE REVIEW

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
I think the default value for `preferred` should be negated as well. And perhaps tests need to be updated.

**Comment by zmwangx** [comment]
Wait, are you saying the default value in `_synthesize()` should be `False`? Since `_synthesize()` appears to only be used in situations where the browser is user-supplied, default False seems counterintuitive.

**Comment by serhiy-storchaka** [comment]
Before e3ce69522ffd7c0354d6e70d18f42bce325ed97e both `register()` and `_synthesize()` had an undocumented parameter `update_tryorder` with the default value 1 which meant "add as least preferred". In e3ce69522ffd7c0354d6e70d18f42bce325ed97e `update_tryorder=1` in `register()` was replaced with `preferred=False`, and in 25b804a9c21c735ce322877f105ebab2539ccfc1 `update_tryorder=1` in `_synthesize()` was incorrectly replaced with `preferred=True`. It is my mistake.

**Comment by zmwangx** [comment]
Sorry for the delay here. Default value of `preferred` to `_synthesize()` has been flipped, and a test has been added to make sure `BROWSER` always takes precedence.

To bot: I have made the requested changes; please review again.

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
