### PR TITLE
bpo-32592: Set Windows 8 as the minimum required version for API support

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue32592

### CODE REVIEW

**Comment by zware** [comment]
This is going to require a change to the buildbot config to turn off the 3.x builder on the Windows 7 bot(s).  I'd rather wait on this until that change is in than to have to make the change to fix the breakage.

**Comment by zooba** [comment]
It shouldn't, as the minimum API isn't actually enforced anywhere except at compile time, and all the Win10 SDKs have the Win8 APIs available.

**Comment by zware** [comment]
I've started a buildbot-custom build to check that.

**Comment by zooba** [comment]
Don't merge this before #15949 or it'll break the other one. (That PR is being backported, and then I'll have to rebase this one...)

**Comment by zware** [comment]
The [Win7 SP1 buildbot](https://buildbot.python.org/all/#/builders/42/builds/58) is happy, so I'll merge this after #15949.

**Review by zware — APPROVED** [review]

**Comment by vstinner** [comment]
Thanks!

**Pull request merged**
