### PR TITLE
bpo-42994: Add MIME types for opus, AAC, 3gpp and 3gpp2

### PR DESCRIPTION
**Pull request by ndbeals**
Add MIME types for opus, AAC, 3gpp and 3gpp2. Some types have multiple extensions, the IANA preferred extension comes first.

These are officially recognized MIME types by IANA: https://www.iana.org/assignments/media-types/media-types.xhtml#audio

- Opus: `.opus: audio/opus` (https://www.iana.org/assignments/media-types/audio/opus and https://tools.ietf.org/html/rfc7845 for recommended file extension)
- AAC: `.aac: audio/aac` (https://www.iana.org/assignments/media-types/audio/aac)
- 3GPP: `.3gp: audio/3gpp` (https://www.iana.org/assignments/media-types/audio/3gpp)
- 3GPP2: `.3g2: audio/3gpp2` (https://www.iana.org/assignments/media-types/audio/3gpp2)

https://bugs.python.org/issue42994

### CODE REVIEW

**Comment by ndbeals** [comment]
I've pinged the issue on the python bug tracker.

**Review by ypankovych — APPROVED** [review]

**Comment by ypankovych** [comment]
LGTM

**Review by FFY00 — APPROVED** [review]

**Review by orsenthil — APPROVED** [review]
LGTM.

**Comment by ndbeals** [comment]
Thanks for reviewing and merging this.

**Pull request merged**
