### PR TITLE
gh-66624: Add a name to re._constants.MAXGROUPS constant

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-66624

### CODE REVIEW

**Comment by vstinner** [comment]
cc @serhiy-storchaka

**Comment by vstinner** [comment]
Before:

```
$ ./python
>>> import re._constants; re._constants.MAXGROUPS
1073741823
```

After:

```
$ ./python
>>> import re._constants; re._constants.MAXGROUPS
MAXGROUPS
```

**Comment by serhiy-storchaka** [comment]
Why do you need this?

Named constants were used for constants which appear in the intermediate wordcode. This helps in debugging the RE compiler.  But AFAIK MAXGROUPS is not used in this way.

**Comment by vstinner** [comment]
> Why do you need this?

For consistency, it looks weird when I looked at the code that most constants are decorated with names, but not this one.

**Comment by serhiy-storchaka** [comment]
This is not by omission. Reasons for making other named constants are not applicable here.

**Comment by vstinner** [comment]
> This is not by omission. Reasons for making other named constants are not applicable here.

Ok. Thanks for the review, I close my PR.

**Pull request closed without merging**
