### PR TITLE
gh-68395: Avoid naming conflicts by mangling variable names in Argument Clinic

### LINKED ISSUE #68395: Argument Clinic doesn't mangle conflicting names
BPO | [24207](https://bugs.python.org/issue24207)
--- | :---
Nosy | @larryhastings, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-05-16.10:21:03.935>
labels = ['type-bug', 'expert-argument-clinic']
title = "Argument Clinic doesn't mangle conflicting names"
updated_at = <Date 2015-05-16.10:21:03.935>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2015-05-16.10:21:03.935>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Argument Clinic']
creation = <Date 2015-05-16.10:21:03.935>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 24207
keywords = []
message_count = 1.0
messages = ['243304']
nosy_count = 2.0
nosy_names = ['larry', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24207'
versions = ['Python 3.5']
```

</p></details>

### Linked PRs
* gh-104065

### LINKED ISSUE #83922: Argument Clinic name conflict
BPO | [39741](https://bugs.python.org/issue39741)
--- | :---
Nosy | @larryhastings, @pablogsal, @isidentical

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-24.17:30:10.453>
labels = ['type-feature', 'expert-argument-clinic', '3.9']
title = 'Argument Clinic name conflict'
updated_at = <Date 2020-02-24.20:07:45.911>
user = 'https://github.com/isidentical'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-24.20:07:45.911>
actor = 'BTaskaya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Argument Clinic']
creation = <Date 2020-02-24.17:30:10.453>
creator = 'BTaskaya'
dependencies = []
files = []
hgrepos = []
issue_num = 39741
keywords = []
message_count = 2.0
messages = ['362599', '362602']
nosy_count = 3.0
nosy_names = ['larry', 'pablogsal', 'BTaskaya']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39741'
versions = ['Python 3.9']
```

</p></details>

### PR DESCRIPTION
**Pull request by erlend-aasland**
Add all internally used variable names to CLINIC_PREFIXED_ARGS.

* Issue: gh-68395

### CODE REVIEW

**Comment by erlend-aasland** [comment]
We can skip NEWS here; this is an implementation detail of the internal tooling.

**Review by hauntsaninja — APPROVED** [review]

**Comment by erlend-aasland** [comment]
I'll wait a few days to give Serhiy a chance to chime in, before merging this.

**Comment by erlend-aasland** [comment]
@serhiy-storchaka, I aim on landing this by tomorrow evening (CET).

**Review by kumaraditya303 — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Two green lights, no complaints; I'm landing this. Thanks for the reviews!

**Pull request merged**
