### PR TITLE
gh-77171 Support WAVE_FORMAT_EXTENSIBLE in the wave module

### PR DESCRIPTION
**Pull request by ykadowak**
I took over the original PR https://github.com/python/cpython/pull/9515 and created this new PR since the original one seems abandoned.

I rebased @ZackerySpytz's work on the current `main` and resolved some conflicts. Then changed some code to meet the reviewer's request which made for the original PR.

* Issue: gh-77171

### CODE REVIEW

**Comment by yusuke-kadowaki** [comment]
@zooba 
Could you take a look at this please? Since you are the reviewer of the original PR.

**Comment by zooba** [comment]
LGTM, thanks!

**Comment by yusuke-kadowaki** [comment]
Thank you for reviewing and merging this!

Maybe we can backport this?

**Comment by zooba** [comment]
I'm unsure whether to backport, so I [started a thread](https://discuss.python.org/t/backporting-support-for-wave-formats/19305?u=steve.dower) to get other opinions.

**Comment by zooba** [comment]
I've decided not to backport, as the variation between micro releases may be surprising and make it harder to predict whether a file will open.

[pedalboard](https://pypi.org/project/pedalboard/) is a good alternative for reading/writing files on earlier versions.

**Comment by yusuke-kadowaki** [comment]
Thank you for considering, updating the doc and the bugfix!

**Pull request merged**
