### PR TITLE
[3.6] bpo-29607: Fix stack_effect computation for CALL_FUNCTION_EX

### PR DESCRIPTION
**Pull request by methane**
original pull request: GH-202
(cherry picked from commit 3a9ac827c7c87dffc60c4200323948551bcb6662)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by methane** [comment]
Waiting CLA sign is confirmed.

**Comment by Mariatta** [comment]
@methane CLA has been signed :) see GH-202

**Comment by methane** [comment]
Thanks to notice.

**Pull request merged**
