### PR TITLE
bpo-26506: hex() documentation: mention %x % int

### PR DESCRIPTION
**Pull request by manvi77**
bpo-26506: hex() documentation: mention %x % int

### CODE REVIEW

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks @manvi77 and congrats on your first contribution to CPython 🎉 

Can you please backport this to the 3.6 branch? 
You can use [cherry_picker](https://pypi.org/project/cherry-picker/).

Thanks.

**Comment by manvi77** [comment]
Thanks @Mariatta, I will check to backport this to 3.6 branch on this weekend.

**Comment by manvi77** [comment]
@Mariatta ,  While I am trying backport to 3.6 using cherry_picker ((venv) ~/mypython/cpython @ (Manvisha) | =>cherry_picker 67ba4fa467ffff825d6a0c0a21cc54ff1df2ed1b 3.6), got following error

Now backporting '67ba4fa467ffff825d6a0c0a21cc54ff1df2ed1b' into '3.6'
Switched to a new branch 'backport-67ba4fa-3.6'
Branch backport-67ba4fa-3.6 set up to track remote branch 3.6 from upstream.

[backport-67ba4fa-3.6 99eec92c12] bpo-26506: hex() documentation: mention %x % int (GH-2525)
 Date: Thu Jul 6 22:30:58 2017 +0300
 1 file changed, 52 insertions(+), 10 deletions(-)

Failed to push to origin ☹
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

Deleted branch backport-67ba4fa-3.6 (was 5679e670a6).

branch backport-67ba4fa-3.6 has been deleted.

**Comment by Mariatta** [comment]
@manvi77 Is `origin` set up to your own fork of CPython?

Can you tell me the result of this command when run from ~/mpython/cpython ?
Thanks

`git remote -v`

**Comment by manvi77** [comment]
@Mariatta, the result is 

origin	https://github.com/python/cpython.git (fetch)
origin	https://github.com/python/cpython.git (push)
upstream	https://github.com/python/cpython.git (fetch)
upstream	https://github.com/python/cpython.git (push)

**Comment by Mariatta** [comment]
@manvi77 cherry_picker assumes that `origin` is set to track own fork of cpython.

In your case `origin` is set to python/cpython, which you don't have a permission to push to, so it failed.

You can use the `--pr-remote` option with cherry_picker: 
The following should work for you:

```
$ git remote add pr https://github.com/manvi77/cpython.git
$ cherry_picker --pr-remote pr 67ba4fa467ffff825d6a0c0a21cc54ff1df2ed1b 3.6 
```

**Comment by manvi77** [comment]
@Mariatta , thank you and it worked :) . Is it all done?

**Comment by Mariatta** [comment]
Thanks @manvi77 
After pushing the backport branch, we need to create the backport PR.
I created GH-2870 from your branch.

**Pull request merged**
