### PR TITLE
gh-126595: fix a crash when calling `itertools.count(sys.maxsize)`

### PR DESCRIPTION
**Pull request by picnixz**
* Issue: gh-126595

### CODE REVIEW

**Review by skirpichev — DISMISSED** [review]
LGTM

But I doubt this should be backported.

**Comment by picnixz** [comment]
> But I doubt this should be backported.

Considering it's a bug that makes the interpreter crash, I think this should.

**Comment by skirpichev** [comment]
> Considering it's a bug that makes the interpreter crash

Only for debug builds.

**Comment by picnixz** [comment]
Yes, but I still think it's better to backport it since it can be used by third-party libraries (let's discuss it on the issue instead).

**Comment by picnixz** [comment]
Ok, maybe it's better to have a separate PR actually.

**Comment by picnixz** [comment]
I'm reverting the `__repr__` check and delegate it to https://github.com/python/cpython/pull/126620. The rationale is that there are some free-threaded update to do and I want to ease backports.

**Review by skirpichev — APPROVED** [review]
Yep, this seems correct.

Edit: One nitpick (a slightly smaller diff):
```diff
diff --git a/Modules/itertoolsmodule.c b/Modules/itertoolsmodule.c
index 1201fa0949..78fbdcdf77 100644
--- a/Modules/itertoolsmodule.c
+++ b/Modules/itertoolsmodule.c
@@ -3291,6 +3291,9 @@ itertools_count_impl(PyTypeObject *type, PyObject *long_cnt,
                 PyErr_Clear();
                 fast_mode = 0;
             }
+            else if (cnt == PY_SSIZE_T_MAX) {
+                fast_mode = 0;
+            }
         }
     } else {
         cnt = 0;
```

**Comment by picnixz** [comment]
Ah actually your suggestion is better because I forgot to clear the exception!! I'll commit in a few moments (just waking up)

**Comment by picnixz** [comment]
I think it will be more likely to have cnt equal to maxsize rather than having an error. Which is why I put that test first.

**Comment by skirpichev** [comment]
> I think it will be more likely to have cnt equal to maxsize rather than having an error.

Well, in terms of probability - it's more likely to have an error (this happens on countable subset of integers), rather having cnt equal to some fixed value ;)

**Comment by picnixz** [comment]
Actually I was wrong. I thought that the error only happened in bad situations but the overflow exception happens when you put something >= maxsize so *your* fix is better!

**Review by vstinner — APPROVED** [review]
LGTM

**Review by ruidazeng — APPROVED** [review]

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
+1 for backporting

**Comment by vstinner** [comment]
I don't know what is going on with the 3.12 backport, it seems to be stuck.

**Pull request merged**
