### PR TITLE
Allow up to a 0.01% drop in coverage

### PR DESCRIPTION
**Pull request by zware**
I'm not sure that this is correct, but we'll see what codecov thinks.  It does pass the validator, but I couldn't get the validator to fail at all with well-formed YAML...

### CODE REVIEW

**Review by dstufft — APPROVED** [review]

**Comment by nedbat** [comment]
I'm curious what the reasoning for this is?

**Comment by terryjreedy** [comment]
Several pull request threads, such as this one, have gotten noisy but irrelevant 'coverage decreased by .01 %' warnings.  I am puzzled that this patch to the .yml driver should change code coverage at all.  If the change shrinks the message somehow, I am in favor of it.

**Comment by zware** [comment]
In my rush to get this submitted this morning, I failed to reference python/core-workflow#21, which inspired this.

@nedbat, the object here is to avoid having Codecov "fail" its check due to random noise in the coverage results.  This is obviously not the ideal solution; ideally, we should find and squash the noise.  This is a good way to make the coverage check more useful in the short term, though.

@terryjreedy, I don't think this will affect the messages left by codecov, but will affect the status in the 'merge' box at the bottom of the PR (note the difference between this one and #20).

**Review by vstinner — APPROVED** [review]
I saw the coverage complaining on multiple PR whereas the change couldn't have any effect of the coverage, so I'm +1 on this change ;-)

**Pull request merged**
