### PR TITLE
  gh-99352: Ensure HTTPSConnection is available before exercising https tests.

### PR DESCRIPTION
**Pull request by orsenthil**
gh-99352: Ensure HTTPSConnection is available before exercising https tests.

This will fix the buildbot issue mentioned in

https://github.com/python/cpython/pull/99353

### CODE REVIEW

**Comment by arhadthedev** [comment]
!buildbot AMD64 RHEL7 3.x

**Comment by arhadthedev** [comment]
!buildbot AMD64 RHEL7 3\.x

**Comment by arhadthedev** [comment]
I tried `AMD64 RHEL7 3.x` and `AMD64 RHEL7 3\.x`

**Comment by orsenthil** [comment]
!buildbot AMD64 RHEL7 3.x

**Comment by orsenthil** [comment]
!buildbot AMD64 RHEL7 3.x

**Comment by orsenthil** [comment]
Looks all good with the build-bots. Merging this.

**Pull request merged**
