### PR TITLE
Fix trivial typo in test_interpreters

### PR DESCRIPTION
**Pull request by jeff5**
Just one letter, but it was making test_interpreters fail to compile.

### CODE REVIEW

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Comment by jeff5** [comment]
Thanks @ericsnowcurrently . It needs a couple of labels to satisfy Sir Bedevere, which I don't think I can add. The Windows failure appears to be an unrelated fault in a specific helper script on Win32, which isn't an obstacle for me.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Note that `./python -m test.test_interpreters` does nothing in 3.11 and 3.12. It would be nice to fix this.

**Comment by jeff5** [comment]
> Note that `./python -m test.test_interpreters` does nothing in 3.11 and 3.12. It would be nice to fix this.

Is this asking me to add anything to the present PR? IIUC that command works in 3.13a+ thanks to @ericsnowcurrently's repackaging of `test_interpreters`, with this typo fixed, which seems a different PR.

Is the continuing failure of the [Windows build](https://github.com/python/cpython/actions/runs/7293094216/job/19890198819?pr=113381) an obstacle to merging?

**Comment by serhiy-storchaka** [comment]
Nothing to add to this PR. It will be merged when all checks be passed (the failure of Windows build is a matter of luck).

Since this PR does not have an associated issue, and the issue that turned `test_inerpreters` into package is already closed, I mentioned it here. It would be nice to make `test_inerpreters` executable in 3.11 and 3.12 by adding the `unittest.main()` call. It is also a trivial change. If anybody of you, @jeff5 and @ericsnowcurrently, do this, nice. Otherwise I will do it.

**Comment by jeff5** [comment]
I'd be happy to save you a task. I understand this as:
* Two PRs, one targeting each maintenance tip.
* Just PRs (not an issue) because you wrote "trivial".
* I should use the "backport" style of title for each PR (guidance in the PR template).
* GitHub will summon @ericsnowcurrently because of the code owners thing and he'll put me right if I'm not.

I see the Windows test has magically gone right just when it was needed. :)

**Pull request merged**
