### PR TITLE
[Skip Issue] Replace dead code with an assertion in winreg.c

### PR DESCRIPTION
**Pull request by ZackerySpytz**

### CODE REVIEW

**Review by serhiy-storchaka — DISMISSED** [review]

**Comment by serhiy-storchaka** [comment]
Actually `PyUnicode_AsUnicodeAndSize()` shouldn't fail here. It could fail at the first iteration.

**Comment by serhiy-storchaka** [comment]
I would rather replace the check with an assert.

**Comment by ZackerySpytz** [comment]
It seems fragile to rely wholly on the previous `PyUnicode_AsUnicodeAndSize()` calls. It would be safest to keep the `NULL` check.

**Comment by serhiy-storchaka** [comment]
We already rely on the previous `PyUnicode_AsUnicodeAndSize()` calls. If the second call can return a different pointer, it can return also a different size. And it that case we will get a buffer overwriting.

I suggest to add two asserts, for pointer and for length.

**Comment by ZackerySpytz** [comment]
@serhiy-storchaka Thank you for your remarks, Serhiy. I've replaced the check with an assertion.

**Comment by Carole1** [comment]
with these code problems, I'm not ready yet.

**Pull request merged**
