### PR TITLE
[3.11] gh-108303: Fix and move `badsyntax_pep3120.py` (GH-109513)

### PR DESCRIPTION
**Pull request by sobolevn**
(cherry picked from commit 4dd47c63a97b3c39cd964ad12431fcdaf76dc823)

* Issue: gh-108303

### CODE REVIEW

**Comment by vstinner** [comment]
Tests fail:

```
ERROR: test_find_module_encoding (test.test_imp.ImportTests.test_find_module_encoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/test/test_imp.py", line 83, in test_find_module_encoding
    imp.find_module('badsyntax_pep3120', path)
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'badsyntax_pep3120'
```

**Comment by sobolevn** [comment]
`test_imp` is missing in 3.12 and 3.13, fixed 👍

**Comment by ambv** [comment]
There's still three failures that survive re-runs:
```
ERROR: test_inline_table_recursion_limit (test.test_tomllib.test_misc.TestMiscellaneous.test_inline_table_recursion_limit) (limit=137, available=99, nest_count=32)
FAIL: test_get_recursion_depth (test.test_support.TestSupport.test_get_recursion_depth)
 ERROR: test_recursion (test.test_support.TestSupport.test_recursion)
 ```

All are about exceeded recursion limits.

**Comment by AlexWaygood** [comment]
> ERROR: test_inline_table_recursion_limit (test.test_tomllib.test_misc.TestMiscellaneous.test_inline_table_recursion_limit) (limit=137, available=99, nest_count=32)

That one's been failing on the 3.11 branch for a while now, I think, FWIW. Don't know about the others.

**Comment by vstinner** [comment]
> ERROR: test_inline_table_recursion_limit (test.test_tomllib.test_misc.TestMiscellaneous.test_inline_table_recursion_limit) (limit=137, available=99, nest_count=32)
> FAIL: test_get_recursion_depth (test.test_support.TestSupport.test_get_recursion_depth)
> ERROR: test_recursion (test.test_support.TestSupport.test_recursion)

Sadly, these ones are regressions when I **fixed** a RecursionError :-( See issue GH-108851.

**Pull request merged**
