### PR TITLE
bpo-43204: Fix LibTomCrypt URL in md5module.c and sha*module.c comments

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue43204

Automerge-Triggered-By: GH:tiran

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I guess this can pass as _skip news_ and _skip issue_

**Review by tiran — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks, @tiran 🙏🏻

BTW, do we need _skip issue_ for _automerge_ to function properly?

**Comment by tiran** [comment]
Thanks for the fix!

**Comment by erlend-aasland** [comment]
Thanks for reviewing, @tiran !

**Pull request merged**
