### PR TITLE
gh-101476: Use _PyType_GetModuleState where applicable

### LINKED ISSUE #101476: Add internal API for fast module access from heap type methods
See [topic on Discourse](https://discuss.python.org/t/a-fast-variant-of-pytype-getmodule/23377?u=erlendaasland).

For CPython internal usage, we've got `_PyModule_GetState`, which is a fast variant of `PyModule_GetState`, the module check in the latter is simply an assert in the former.

For `PyType_GetModuleState`, there are three `if`s (two of them implicitly in `PyType_GetModule`):

1. check that the given type is a heap type
2. check that the given type has an associated module
3. check that the result of `PyType_GetModule` is not `NULL`

For stdlib core extension modules, all of these conditions are always true (AFAIK). With a fast static inlined variant, for example `_PyType_GetModuleState`, with a fast variant of `PyType_GetModule` inlined, where all three conditions are `assert()`ed, we can speed up a heap type methods that need to access module state.

### Linked PRs
* gh-101477
* gh-102188

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-101476

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I consider this a trivial and non-controversial PR; I intend to merge it as soon as the CI is green. If this turns out to be bad judgement from my side, I'm happy to revert it.

**Comment by corona10** [comment]
>  If this turns out to be bad judgement from my side, I'm happy to revert it.

I though that there were some kinds discussion to use public API as possible.
I will let you know once I find it.

**Comment by corona10** [comment]
Might be one piece of discussion I remember: https://github.com/python/cpython/issues/90699#issuecomment-1302279260

**Comment by ericsnowcurrently** [comment]
At least with _xxsubinterpreters, I purposefully did not use any internal API.  Ideally, non-builtin extensions would avoid internal API, generally.

**Comment by erlend-aasland** [comment]
@ericsnowcurrently, @corona10: As the PR title says, I've only applied this where applicable. This implies extension modules that define `Py_BUILD_CORE_BUILTIN 1`. For extension modules without this define, no change has been made.

**Comment by erlend-aasland** [comment]
I've reverted the change in _testmultiphase.

**Review by kumaraditya303 — APPROVED** [review]

**Comment by ericsnowcurrently** [comment]
BTW, thanks for working on this, @erlend-aasland!

**Comment by erlend-aasland** [comment]
Thanks for comments and reviews, everyone!

**Pull request merged**
