### PR TITLE
bpo-43522: Fix SSLContext.hostname_checks_common_name (GH-24899)

### PR DESCRIPTION
**Pull request by tiran**
Fix problem with ssl.SSLContext.hostname_checks_common_name. OpenSSL does not
copy hostflags from *struct SSL_CTX* to *struct SSL*.

Signed-off-by: Christian Heimes <christian@python.org>

https://bugs.python.org/issue43522

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thank you, both the reproducer and the urllib3 test suite run fine with this change!

**Comment by tiran** [comment]
The fix has landed in OpenSSL 3.0.0 and is flagged for backport to 1.1.1.

**Comment by pquentin** [comment]
Thanks! Should we mention in the docs that the flag had no effect until now?

**Comment by tiran** [comment]
> Thanks! Should we mention in the docs that the flag had no effect until now?

Something like this? I'll adjust the versionchanged to 3.8.9 and 3.9.3 in backports.

```
  .. versionchanged:: 3.10

     The flag had no effect with OpenSSL 1.1.1k and older.
```

**Comment by pquentin** [comment]
Yes, that would be perfect. That way we'll know for what Python and OpenSSL combinations this flag will be safe to use.

There's one thing I don't understand: is it enough to have either the CPython and OpenSSL fixes, or do we need both?

**Comment by tiran** [comment]
The workaround in this PR is only necessary for OpenSSL 1.1.1k and older. 1.1.1l and 3.0.0 are going to copy the flag correctly without the workaround. 

``#if ... OPENSSL_VERSION < 0x101010cf``

```
>>> chr(0xc + ord('a') - 1)
'l'
```

**Pull request merged**
