### PR TITLE
[3.4][Security] bpo-29572: Update Windows build to OpenSSL 1.0.2k (GH-443)

### PR DESCRIPTION
**Pull request by vstinner**
(cherry picked from commit dd2000cbe475da48fdc94e8f05618e9f460077fd)

https://bugs.python.org/issue29572

### CODE REVIEW

**Comment by vstinner** [comment]
Please review carefully this cherry-pick since I had conflicts on the backport. Original change: commit dd2000cbe475da48fdc94e8f05618e9f460077fd.

**Review by tiran — APPROVED** [review]

**Review by zware — APPROVED** [review]
Approved, as long as AppVeyor also approves :)

**Comment by vstinner** [comment]
Similar change for macOS: PR #3447.

**Comment by larryhastings** [comment]
I don't understand how this branch is out-of-date with 3.4...?  I haven't accepted any patches into the 3.4 branch in a while.

Anyway, please update the PR so that I get a nice green accept button instead of an angry red "Squash And Merge" button.  I don't like pressing red buttons.

**Comment by vstinner** [comment]
I rebased my PR on top of the current 3.4 branch.

**Comment by vstinner** [comment]
@larryhastings: Is it better now?

**Pull request merged**
