### PR TITLE
gh-116741: Upgrade libexpat to 2.6.2

### PR DESCRIPTION
**Pull request by sethmlarson**
cc @hartwork 

* Issue: gh-116741

### CODE REVIEW

**Review by hartwork — APPROVED** [review]
@sethmlarson looks good, my verification script likes it. Thank you! :+1: 

```Dockerfile
# Copyright (c) 2022-2024 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the Apache License version 2.0

FROM alpine
RUN apk add --update \
            diffutils \
            git \
            sed \
        && \
    git clone --depth 1 https://github.com/python/cpython cpython-main \
        && \
    ( cd cpython-main && git rev-parse HEAD ) \
        && \
    git clone --depth 1 --branch libexpat-2.6.2 https://github.com/sethmlarson/cpython cpython-pr \
        && \
    ( cd cpython-pr && git rev-parse HEAD ) \
        && \
    git config --global advice.detachedHead false \
        && \
    git clone --depth 1 --branch R_2_6_0 https://github.com/libexpat/libexpat libexpat_2_6_0 \
        && \
    git clone --depth 1 --branch R_2_6_2 https://github.com/libexpat/libexpat libexpat_2_6_2 \
        && \
    diff -r -u libexpat_2_6_0/expat/lib/ cpython-main/Modules/expat/ | tee 2-6-0.diff \
        && \
    diff -r -u libexpat_2_6_2/expat/lib/ cpython-pr/Modules/expat/ | tee 2-6-2.diff \
        && \
    sed -e '/^Only in /d' -e '/^\(+++\|---\) /d' -e '/^diff /d' -i 2-6-0.diff 2-6-2.diff \
        && \
    diff -u 2-6-0.diff 2-6-2.diff \
        && \
    echo 'Diff is good.'
```

**Comment by hartwork** [comment]
@sethmlarson ready to merge?

**Comment by hartwork** [comment]
@sethmlarson any news?

**Comment by sethmlarson** [comment]
@hartwork I can't merge PRs on my own, I'll find a core developer to merge.

**Review by gpshead — APPROVED** [review]
These changes appear to match https://github.com/libexpat/libexpat/compare/R_2_6_0...R_2_6_2.

We should probably script updating this.

**Comment by sethmlarson** [comment]
Created the backports:

* https://github.com/python/cpython/pull/118185
* https://github.com/python/cpython/pull/118186
* https://github.com/python/cpython/pull/118187
* https://github.com/python/cpython/pull/118188

**Comment by hartwork** [comment]
@sethmlarson thanks a lot! :+1:

**Pull request merged**
