### PR TITLE
bpo-46345: add a test case for implicit `Optional` class attribute

### PR DESCRIPTION
**Pull request by sobolevn**
Related https://github.com/python/cpython/pull/30304

CC @corona10 as my mentor

https://bugs.python.org/issue46345

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]
LGTM. Do you suggest we backport this?

**Review by JelleZijlstra — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks for the review! 👍 

I think it is safe to backport to 3.10 and 3.9

**Review by gvanrossum — APPROVED** [review]

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Looks like the issue-number bot is stuck. Closing and reopening to restart it (sigh).

**Comment by sobolevn** [comment]
Thanks everyone!

**Pull request merged**
