### PR TITLE
bpo-30644: Mention how to disable signal fd wakeup

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@njsmith

**Comment by njsmith** [comment]
Yeah, good idea and lgtm

If you want to get really fancy, I guess you could also mention that on unixes it's an arbitrary FD, but on Windows it should be a socket handle (not an FD at all).

**Comment by pitrou** [comment]
If I'm reading `signalmodule.c` correctly (especially the functions `signal_set_wakeup_fd` and `trip_signal`), we support both regular file descriptors and sockets on Windows (but not native Windows handles).

**Comment by njsmith** [comment]
> we support both regular file descriptors and sockets on Windows (but not native Windows handles).

Ah, looks like you're right. In practice though I don't think there are any uses for passing in a regular file descriptor, because only sockets can be set in non-blocking mode, and python sockets are always represented as socket handles and not wrapped into an fd.

**Pull request merged**
