### PR TITLE
Fix markup for xml.sax in 3.8 notes

### PR DESCRIPTION
**Pull request by andresdelfino**

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
What does this do in the "What's New" document? If this is a bugfix, it shouldn't be added here. If this is a new feature, it should not be backported.

**Comment by andresdelfino** [comment]
> 
> 
> What does this do in the "What's New" document? If this is a bugfix, it shouldn't be added here. If this is a new feature, it should not be backported.

Perhaps it was meant for 3.8 at first but then it was decided to be backported? Maybe we should just remove the mention about this altogether in 3.8?

**Comment by tiran** [comment]
It's a possibly breaking change and therefore has to be documented in whatsnew. Two core devs wanted to have the changed documented in whatsnews. I agreed with their wish, too.

**Comment by andresdelfino** [comment]
@tiran Is it custom to add a What's new entry in an upcoming major version when the change will be provided before in a maintenance release of a stable version? This fix was already made available in 3.7.1 and we are announcing it again in 3.8, like the bug was still there in 3.7.X. Also note that the documentation changes of this fix for 3.8 say the change was made in 3.8, but, again, the fix was made in 3.7.1. Seems confusing.

IMHO, What's new in X should be a delta against the What's new in X-1 where X-1 is the latest sable release.

If this sounds reasonable I can make a PR with the required changes.

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
