### PR TITLE
gh-98852: Add extra type check to avoid a bug with parameterizing gen…

### PR DESCRIPTION
**Pull request by Eclips4**
* Issue: gh-98852

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
You would need to:
1. Add `NEWS`, consider using `blurb` CLI or online services. See `news` CI job logs
2. Add tests: at least the example from the original bug report. But, I like when there are lots of tests :)

**Comment by Eclips4** [comment]
I find only one way how write test for it:

```python3
class BaseCallableTests:
    ...
    def test_determine_new_args(self):
        Callable = self.Callable
        T = TypeVar("T")
        P = TypeVar("P")

        class C(Generic[T]): ...

        S = Callable[[C], P]
        U = S[T]
        if self.Callable is collections.abc.Callable:
            self.assertEqual(U, Callable[[C[T]], T])
        else:
            self.assertEqual(U, Callable[[C], T])
    ...
```
What u think about this?
And i have one question,
```python3
from typing import TypeVar, Generic
from collections.abc import Callable
from typing import Callable as TypingCallable


T = TypeVar("T")
P = TypeVar("P")
Z = TypeVar("Z")

class C(Generic[Z]): ...

S = Callable[[C], P]
U = S[T]
U
> collections.abc.Callable[[__main__.C[~Z]], ~T]
S_T = TypingCallable[[C], P]
U_T = S_T[T]
U_T
> typing.Callable[[__main__.C], ~T]
```
Is it okay?

**Comment by sobolevn** [comment]
It does not look right that two callables have different results.

**Comment by Eclips4** [comment]
I think, problem was solved in this PR: https://github.com/python/cpython/pull/98952
But, question about `collections.abc.Callable` and `typing.Callable` still relevant.

**Comment by JelleZijlstra** [comment]
Closing in favor of #98952. I can't reproduce the `Callable` difference on current main:

```
Python 3.12.0a1+ (heads/pep688v2-dirty:007fdc1153, Nov  7 2022, 06:50:30) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import TypeVar, Generic
>>> from collections.abc import Callable
>>> from typing import Callable as TypingCallable
>>> 
>>> 
>>> T = TypeVar("T")
>>> P = TypeVar("P")
>>> Z = TypeVar("Z")
>>> 
>>> class C(Generic[Z]): ...
... 
>>> S = Callable[[C], P]
>>> U = S[T]
>>> U
collections.abc.Callable[[__main__.C], ~T]
>>> S_T = TypingCallable[[C], P]
>>> U_T = S_T[T]
>>> U_T
typing.Callable[[__main__.C], ~T]
```

**Pull request closed without merging**
