### PR TITLE
Doc: Fix typos

### PR DESCRIPTION
**Pull request by ember91**
See https://github.com/python/cpython/pull/125569

----
📚 Documentation preview 📚: https://cpython-previews--125728.org.readthedocs.build/

### CODE REVIEW

**Comment by skirpichev** [comment]
This affects also C sources.

**Comment by AA-Turner** [comment]
@ember91 please revert all changes to `Modules/`

**Review by AA-Turner — DISMISSED** [review]
Please revert all changes to Modules/

**Comment by ember91** [comment]
> This affects also C sources.

Fixed, by reverting changes to Modules/

**Review by skirpichev — APPROVED** [review]

**Review by willingc — APPROVED** [review]
Thank you for correcting this PR. @AA-Turner this PR now addresses changes to `.rst` files.

@ember91 I encourage you to choose an open issue for a future PR and expanding beyond typo fixes. Thanks!

**Review by erlend-aasland — APPROVED** [review]

**Pull request merged**
