### PR TITLE
bpo-35024: Remove redundant and possibly incorrect verbose message after writing '.pyc'

### PR DESCRIPTION
**Pull request by kwentine**
Since `SourceFileLoader.set_data()` catches exceptions raised by `_write_atomic()` and logs an informative message consequently, always logging successful outcome in 'SourceLoader.get_code()' seems redundant.  

https://bugs.python.org/issue35024

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by ncoghlan** [comment]
The commit needs a "make regen-importlib" before the tests will pass.
While it's a relatively minor change, I think it's worth adding a NEWS entry for, just in case someone is in the habit of trawling the debug messages to find out which pyc files are getting written.

**Comment by qagren** [comment]
I've just learnt about `make regen-importlib` for another minor fix today, will do sorry.
Another question (please let me know if it's not the place to seek for such advice I don't want to waste your time): do I rebase this branch on top of master and do a `push --force` (to avoid merge conflicts with recently regenerated `importlib_external.h` ? Or will it be taken care of "behind the scenes"?

**Comment by ncoghlan** [comment]
For review purposes, merging master into the PR branch is better (since GitHub does a better job of figuring out the appropriate diff with earlier versions of the review PR).

There's then a final squash & merge at commit time that avoids complicating the development history with those additional merges.

**Comment by qagren** [comment]
Thanks. Merged master, ran `make regen-importlib` and added news entry (although I was not really sure about how much details to put in the latter)

**Comment by brettcannon** [comment]
Just for reference, the main logging call is handled by:

https://github.com/python/cpython/blob/4e3a53bceefe4803c08a025523d8658862cb31c0/Lib/importlib/_bootstrap_external.py#L1033-L1039

I've left comments on the issue to discuss a potential alternative solution.

**Comment by brettcannon** [comment]
Actually, my alternative is unnecessarily complex. 😄 I tweaked the news entry, so once CI goes green this can be merged.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
@qagren honestly, code removal is more important than adding. Less code (typically) means less maintenance. When we started Python 3.0 we had an informal competition over who could remove the most amount of code from the stdlib. 😄

**Pull request merged**
