### PR TITLE
bpo-43993: Update vendored pip to 21.1.1

### PR DESCRIPTION
**Pull request by sbidoul**
https://bugs.python.org/issue43993

### CODE REVIEW

**Comment by pfmoore** [comment]
@ambv @pablogsal Is this OK to go into 3.8/3.9/3.10b1? I'm aware it's pretty close to the release, but typically ensurepip changes are low-impact, and 21.1 contained some rather annoying warnings that we'd like to suppress in the version that gets released with CPython.

**Comment by pablogsal** [comment]
> @ambv @pablogsal Is this OK to go into 3.8/3.9/3.10b1?

LGTM for 3.10b1 but it needs to be merged before Monday to be included

**Comment by pfmoore** [comment]
Thanks @pablogsal I'll merge now. I won't trigger backports until I have the OK from @ambv though.

**Comment by ambv** [comment]
OK for both 3.8 and 3.9, please merge ASAP.

**Comment by pfmoore** [comment]
Thanks @ambv both merges done.

**Pull request merged**
