### PR TITLE
Remove redundant checks in posixmodule.c

### PR DESCRIPTION
**Pull request by berkerpeksag**

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Sorry, I don't understand why they are redundant.

**Comment by berkerpeksag** [comment]
I was basically following your review comment in https://github.com/python/cpython/pull/8740#discussion_r209866334.

**Comment by serhiy-storchaka** [comment]
The comment in #8740 was about the code that didn't have any effect:
```c
    if (!return_value) {
        goto exit;
    }
exit:
```
The code removed in this PR is needed for returning NULL on error.

**Comment by berkerpeksag** [comment]
Ah, now I understand your original comment. Thanks!

**Pull request closed without merging**
