### PR TITLE
gh-125875: Fix docs typo FORMAT_SPEC to FORMAT_WITH_SPEC

### PR DESCRIPTION
**Pull request by rimi0108**
* Issue: gh-125875

----
📚 Documentation preview 📚: https://cpython-previews--126319.org.readthedocs.build/

### CODE REVIEW

**Comment by rimi0108** [comment]
@corona10

**Review by corona10 — APPROVED** [review]
According to changelog
```
[gh-33092](https://github.com/python/cpython/issues/33092): Simplify and speed up interpreter for f-strings. Removes FORMAT_VALUE opcode. Add CONVERT_VALUE, FORMAT_SIMPLE and FORMAT_WITH_SPEC opcode. Compiler emits more efficient sequence for each format expression.
```

**Comment by corona10** [comment]
But I would like to leave a chance to review from @willingc , @Mariatta or @hugovk

**Review by willingc — APPROVED** [review]
Looks great. Thanks @rimi0108 and congrats on your contribution. @corona10 feel free to merge and celebrate :tada:

**Pull request merged**
