### PR TITLE
bpo-40690: Check that testcase.__module__ != 'unittest.case'

### PR DESCRIPTION
**Pull request by abetkin**
https://bugs.python.org/issue40690

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@abetkin

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by csabella** [comment]
@abetkin, please sign the CLA as per the previous comment.  Thanks!

**Comment by remilapeyre** [comment]
Hi @abetkin, thanks for the PR! Like I said on BPO, this only fix one loader, the other have the same issue. To be accepted the change will need some tests and a [NEWS entry](https://devguide.python.org/committing/#what-s-new-and-news-entries), you can add one by using https://blurb-it.herokuapp.com/.

**Comment by csabella** [comment]
@abetkin, as mentioned before, we can't accept a PR without a signed CLA.  If you are unable to sign the CLA, then this PR will be closed.

**Comment by csabella** [comment]
I'm going to close this as the CLA has not been signed.  Once the CLA is signed, it can be reopened.  Thanks!

**Pull request closed without merging**
