### PR TITLE
bpo-35984: _xxsubinterpreters: Fix memory leak in _channel_send()

### PR DESCRIPTION
**Pull request by izbyshev**
https://bugs.python.org/issue35984

### CODE REVIEW

**Comment by vstinner** [comment]
No NEWS entry needed since the fixed module is private.

**Comment by vstinner** [comment]
I tested manually the change: it works as expected.

Without this change, "./python -m test -R 3:3 test__xxsubinterpreters" fails ("leaked [3, 4, 3] memory blocks, sum=10"). With this change, the test doesn't leak anymore.

**Review by vstinner — APPROVED** [review]
LGTM.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Pull request merged**
