### PR TITLE
gh-101819: Prepare _io._IOBase for module state

### PR DESCRIPTION
**Pull request by erlend-aasland**
- Add PyIOBase_Type to _io module state
- Pass defining class to _io._IOBase.fileno

* Issue: gh-101819

### CODE REVIEW

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by erlend-aasland** [comment]
Thanks for the review, Dong-hee! Let's run the bots, since we're touching the visit and free funcs.

**Comment by erlend-aasland** [comment]
I wonder why the s390x refleak bots are failing. Is there an issue on main?

**Comment by kumaraditya303** [comment]
> I wonder why the s390x refleak bots are failing. Is there an issue on main?

https://github.com/python/cpython/issues/104413

**Review by kumaraditya303 — APPROVED** [review]

**Pull request merged**
