### PR TITLE
gh-124008: Fix calculation of the number of written bytes for the Windows console

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Since MultiByteToWideChar()/WideCharToMultiByte() is not reversible if the data contains invalid UTF-8 sequences, use binary search to calculate the number of written bytes from the number of written characters.

Also fix handling of memory allocation failures.

* Issue: gh-124008

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
@zooba, @vstinner, do you mind to take a look at this PR?

**Comment by zooba** [comment]
I keep trying to review and I keep getting confused 😆 

Perhaps we should revise this entire piece of functionality, do one big conversion (and hope that anyone writing more than 32KB to the console in one go has enough RAM), and loop over that? Then we're only dealing with UTF-16 pairs, which ought to be simpler.

**Comment by cmaloney** [comment]
The RAM constraint should be gone with Windows 8+ (gh-121940), just the "interactivity" / Ctrl-C interruptability (if can get to `WaitForMultipleObjectsEx` would solve that and is where I've been trying to aim recently, but also lots of steps to get there).

**Comment by zooba** [comment]
> The RAM constraint should be gone with Windows 8+

I was referring to the memory we have to allocate to store a UTF-16 version of the string. If someone decides to write 2GB worth of ASCII in one go, we'll need another 4GB to store the UTF-16 encoded version, even before we get to passing it to the console APIs.

**Comment by serhiy-storchaka** [comment]
This PR consists of three parts:

* fixed `_find_last_utf8_boundary()`;
* `_wchar_to_utf8_count()` to calculate the number of partially written bytes;
* numerous other fixes, mainly missed `PyErr_NoMemory()`.

Even if the 32KiB limit is gone, there is still the 2GiB or 4GiB limit, so the code will stay almost the same. It cannot help. Unless we get rid of `MultiByteToWideChar()` and use double conversion with Python UTF-8 and UTF-16 codecs, but this would be a much larger change, and the code may be less efficient.

**Comment by zooba** [comment]
I think it's the binary search to find the converted length that upsets me the most.

Does it get any simpler if we arbitrarily cut at 32K bytes, count back to a complete UTF-8 character, and then write from there? Rather than trying to fit within 32KB worth of UTF-16, which is no longer a real limit on supported platforms.

**Comment by serhiy-storchaka** [comment]
No, it will not get much simpler.

Note that the code to find the initial length was already here. I only fixed some corner cases in it.

We still need binary search to map the number of actually written wchars to the number of UTF-8 bytes. Even if we do as you suggested, this will only save ~10 lines of code (relatively simple in comparison of the rest of this PR). We can do this in the following PR. For now, keeping this code means less changes.

**Comment by zooba** [comment]
Yeah, that's annoying... but you're right.

Okay, I have no further objections.

**Comment by vstinner** [comment]
> test_truediv - test.test_complex.ComplexTest.test_truediv

It's unrelated and I cannot reproduce the issue on the buildbot (nor on my laptop). I don't know what's going on.

**Pull request merged**
