### PR TITLE
Doc: Bump Sphinx version.

### PR DESCRIPTION
**Pull request by JulienPalard**
To reflect the one we're using in production.

### CODE REVIEW

**Comment by vstinner** [comment]
Can this change wait after beta1 release?

**Review by ned-deily — APPROVED** [review]
LGTM

**Comment by JulienPalard** [comment]
@vstinner you mean after the 3.8 cutoff? Yes we can wait.

**Comment by JulienPalard** [comment]
@bedevere-bot I'm not proud of this one :]

**Comment by vstinner** [comment]
@JulienPalard: you know that you are talking to a bot, right ;-)

**Pull request merged**
