### PR TITLE
bpo-29243: Fix Makefile with respect to --enable-optimizations

### PR DESCRIPTION
**Pull request by torsava**
When using the Profile Guided Optimization (./configure --enable-optimizations)
Python is built not only during `make` but rebuilt again during `make test` and
`make install`. This patch fixes the issue.

Note that this fix produces no change at all in the Makefile if configure is
run witout --enable-optimizations.

### CODE REVIEW

**Review by vstinner — DISMISSED** [review]
I still see "all" in testall, testuniversal, quicktest, smelly, patchcheck. Please update these ones as well.

But thank you for working on this very annoying bug!

**Comment by torsava** [comment]
> I still see "all" in testall, testuniversal, quicktest, smelly, patchcheck. Please update these ones as well.

Ah, you're right, thanks for the help! I've amended the commit accordingly.

**Comment by vstinner** [comment]
I ran the following test and I only see Python compiled twice, as expected:

* build with generate profile
* run the profile task
* build with the collected data

Command:

```
./configure --with-pydebug --prefix=/home/haypo/pgo --enable-optimizations
vim Makefile   # write "PROFILE_TASK=-c pass", just to get a quick test
make
make install
make quicktest
```

**Comment by vstinner** [comment]
Can you please document the change in the Build section in Misc/NEWS? With a NEWS entry, the change will be ready to be merged.

**Comment by torsava** [comment]
Amended the commit with a NEWS entry!

**Comment by louisom** [comment]
@torsava you don't need to rebase or squash the commit, at the end of the merge it will do it so :)

**Comment by vstinner** [comment]
Oh, I'm sorry, I missed the "First-time contributor" notice on GitHub. Would you mind to add your name in Misc/ACKS as well?

**Comment by torsava** [comment]
> @torsava you don't need to rebase or squash the commit, at the end of the merge it will do it so :)

Ah, thank you! I wasn't sure what the merging policy was here, and I dislike simple changes drawn out over multiple commits. (I now realise it's addressed in the contributor guide, sorry for missing that.)

> Oh, I'm sorry, I missed the "First-time contributor" notice on GitHub. Would you mind to add your name in Misc/ACKS as well?

Done, thanks!

**Comment by louisom** [comment]
@torsava yes, I did this before, I also like to squash to make it clean. But that is not good for others to reviewing on GitHub when doing squashing. 

And there is a discussion (I dont' remember on python-dev or python-committers) about this, the final answer is: don't squash and leave to the end, you can see here for more information: [devguide-pullrequest](http://cpython-devguide.readthedocs.io/pullrequest.html#submitting)

**Comment by vstinner** [comment]
Thank you for your contrib Tomáš Orsava! This bug annoyed me, I opened a duplicate issue: http://bugs.python.org/issue29641

@torsava: Do you want to do the backports? https://docs.python.org/devguide/committing.html#backporting-changes-to-an-older-version

**Comment by torsava** [comment]
> Thank you for your contrib Tomáš Orsava! This bug annoyed me, I opened a duplicate issue: http://bugs.python.org/issue29641

Glad to have helped!

> @torsava: Do you want to do the backports?

I'm having some trouble with `cherry_picker` and I need to be going now. However, if it can wait a few days, I _would_ like to do the backports!

**Comment by vstinner** [comment]
> I'm having some trouble with cherry_picker and I need to be going now. However, if it can wait a few days, I would like to do the backports!

Take your time, there is no urgency ;-) You can ping me directly, we are colleagues ;-)

**Comment by gpshead** [comment]
thank you! :)

**Pull request merged**
