### PR TITLE
bpo 33217:  add deprecation warnings for Enum

### PR DESCRIPTION
**Pull request by ethanfurman**
deprecate non-Enum containment checks on Enum members

### CODE REVIEW

**Comment by terryjreedy** [comment]
This is drastically wrong.  I suspect you started from a stale, out-of-date branch.

**Comment by ethanfurman** [comment]
On 04/05/2018 11:36 AM, Terry Jan Reedy wrote:

> This is drastically wrong. I suspect you started from a stale, out-of-date branch.

Thanks for catching that, Terry.  I tried updating my repo before working on the patch, but obviously I failed.

--
~Ethan~

**Comment by terryjreedy** [comment]
Or, you tried to merge a 3.7 derived branch into master instead of into 3.7.  (I just saw the workflow thread.)  Do you really want to patch 3.7 without patching master?

**Comment by ethanfurman** [comment]
On 04/05/2018 12:15 PM, Terry Jan Reedy wrote:

> Or, you tried to merge a 3.7 derived branch into master instead of into 3.7. (I just saw the workflow thread.) Do you
> really want to patch 3.7 without patching master?

In this case, yes.  I need to add some DeprecationWarnings to 3.7, and then raise TypeError in 3.8.  So different 
patches those two branches.

--
~Ethan~

**Comment by terryjreedy** [comment]
Looking at the workflow list thread, the patch branch was derived from 3.7.  You should have merged into python:3.7 instead of python:master.  There is a drop-down list of branches to merge into on the upper-left (I believe) of the create-PR page.  I don't know if '[3.7]' should be added at the beginning of the title if it is not a backport, but I suspect so.

Questions about using the current workflow, as opposed to improving it, can go to core-mentorship list.  I have gotten several questions answered there.

**Comment by ethanfurman** [comment]
On 04/05/2018 12:30 PM, Terry Jan Reedy wrote:

> Looking at the workflow list thread, the patch branch was derived from 3.7. You should have merged into python:3.7
> instead of python:master. There is a drop-down list of branches to merge into on the upper-left (I believe) of the
> create-PR page. I don't know if '[3.7]' should be added at the beginning of the title if it is not a backport, but I
> suspect so.
>
> Questions about using the current workflow, as opposed to improving it, can go to core-mentorship list. I have gotten
> several questions answered there.

Thank you.

--
~Ethan~

**Pull request closed without merging**
