### PR TITLE
bpo-11998: Patch smtplib.py

### PR DESCRIPTION
**Pull request by prrvchr**
This update was made to meet 2 needs:

- Bug Fix: https://github.com/python/cpython/pull/11998
- Allow backward compatibility with Python 2.7.9 or higher.

https://bugs.python.org/issue36094

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@prrvchr

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by corona10** [comment]
Python2 is EOL. We does not support Python 2.7.x

**Comment by prrvchr** [comment]
@corona10 
Python 2 EOL: We will have to work with python 2.7.x for many more years ...
Why refuse to have only one version of smtplib.py to maintain ...

**Comment by jstasiak** [comment]
I believe this should be split into two pull requests – one fixing a bug and another improving backward compatibility. Right now I can barely see what the actual fix is here.

But on the backward compatibility front:

> Why refuse to have only one version of smtplib.py to maintain ...

I'd say because it may add a maintenance burden (arguably not in this case) or affect the code negatively (like `initial_response_ok` losing its keyword-only designation in this patch).

**Comment by prrvchr** [comment]
Ok, I drop the backward compatibility...
I corrected the bug link: https://bugs.python.org/issue36094
I create 2 files, one for python 2 and one for python 3, available on the following links:
https://github.com/prrvchr/cpython/blob/2.7/Lib/smtplib.py
https://github.com/prrvchr/cpython/blob/3.9/Lib/smtplib.py
You are free to take care to merge these changes, that in me I use these modified versions ...

**Comment by asvetlov** [comment]
In general, a pull request should be created against the master branch and manually backported if the automatic backpot fails.

This is the project policy.

2.7 branch is frozen and doesn't accept any change, sorry.

I'm closing this PR; it removes all audit calls which is not acceptable.

**Pull request closed without merging**
