### PR TITLE
bpo-30157: Fix csv.Sniffer.sniff() regex pattern

### PR DESCRIPTION
**Pull request by jake-jake-jake**
Looks like there is an extra > in the regex pattern for this sort of csv line: `# ,".*?"`

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by vstinner** [comment]
Please open a bug report to describe the bug and link it to this PR: then add "bpo-xxx" the PR title.

**Comment by jake-jake-jake** [comment]
@haypo Let me know if anything else needs adjusting.

**Comment by louisom** [comment]
Change title to something like `bpo-30157: Fix csv sniffer regex patter`  would be more descriptive.

**Comment by serhiy-storchaka** [comment]
I'm surprized that such bug was not caught by tests. This means the lack of tests. Needed a new test for that case.

**Review by serhiy-storchaka — APPROVED** [review]

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
Needed a test and a Misc/NEWS entry.

**Comment by jake-jake-jake** [comment]
I added some tests for the regex patterns that should ensure that Sniffer._guess_quote_and_delimiter() matches patterns as expected.

**Comment by jake-jake-jake** [comment]
@serhiy-storchaka Let me know if I need to make any more amendments to the tests or news entry; the tests should properly identify when the patterns fail to match.

**Comment by serhiy-storchaka** [comment]
`Sniffer._guess_quote_and_delimiter()` is an implementation detail. Is it possible to write tests for these cases using only public API (`Sniffer.sniff()`)?

**Comment by serhiy-storchaka** [comment]
Recreated as #5601.

**Pull request closed without merging**
