### PR TITLE
[2.7] bpo-32616: Disable computed gotos by default for clang < 5

### PR DESCRIPTION
**Pull request by methane**
https://bugs.python.org/issue32616

### CODE REVIEW

**Comment by benjaminp** [comment]
We should probably put this check in `configure.ac`, so that configure doesn't claim we're going to use computed use gotos while we silently don't. (You could just stick the `ifdef` into the `AC_RUN_IFELSE`.)

**Comment by methane** [comment]
I'm sorry, I'm not familiar with configure.ac.
As my understanding, configure just define `HAVE_COMPUTED_GOTOS` automatically.
`USE_COMPUTED_GOTOS` is never defined automatically, unless `--with(out)-computed-gotos`
is specified.

This pull request is just change behavior when `USE_COMPUTED_GOTOS` is not defined.

**Comment by methane** [comment]
This is output of configure script:
```
checking for socklen_t... yes
checking for build directories... checking for --with-computed-gotos... no value specified
checking whether gcc -pthread supports computed gotos... yes
done
```

**Review by benjaminp — APPROVED** [review]

**Comment by ilovezfs** [comment]
@methane @benjaminp unfortunately this issue still affects Python 2.7.15rc1 because in Xcode 9.x, the value of `__clang_major__` is 9.

**Comment by methane** [comment]
@ilovezfs We know, but there is no easy fix for it.  See https://bugs.python.org/issue32616 for continued discussion.

**Comment by p0six** [comment]
So is this now considered resolved for High Sierra users via 2.7.15rc1?

**Comment by ilovezfs** [comment]
@p0six no. You still must manually pass `--without-computed-gotos` to configure if you're building from source.

**Comment by ilovezfs** [comment]
@p0six however, Xcode >= 9.3 is apparently unaffected.

**Pull request merged**
