### PR TITLE
GH-92123: Pass _elementtree state as parameter

### PR DESCRIPTION
**Pull request by erlend-aasland**
Complement to #101190

* Issue: gh-92123

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Passing the state around as a parameter is one way to get rid of `ET_STATE_GLOBAL`. It results in a larger diff (more churn), but IMO it is an ok approach. Alternatively, we can store state as a member in the type contexts, which will result in a smaller diff.

**Comment by erlend-aasland** [comment]
(I will **rebase** this onto `main` after #101187 has landed.)

**Comment by erlend-aasland** [comment]
cc. @arhadthedev

**Comment by erlend-aasland** [comment]
After this, the remaining parts are:

- use `PyModule_GetState` where possible (1 small PR)
- use `PyType_GetModuleState` where possible (1 slightly larger PR w/clinic changes)
- use `PyType_GetModuleByDef`+`PyModule_GetState` where possible
- adapt to multi-phase init

**Comment by kumaraditya303** [comment]
> After this, the remaining parts are:

Up to you but I can review of all this in one go, they are relatively small changes.

**Comment by kumaraditya303** [comment]
Side thought: `sizeof(ElementObject)` is `56` which rounds off to `64` for alignment so we can add a state pointer and the memory usage will be same.

**Review by kumaraditya303 — APPROVED** [review]

**Comment by erlend-aasland** [comment]
> Side thought: `sizeof(ElementObject)` is `56` which rounds off to `64` for alignment so we can add a state pointer and the memory usage will be same.

Yes; well observed.

**Pull request merged**
