### PR TITLE
bpo-47053: Reduce deoptimization in BINARY_OP_INPLACE_ADD_UNICODE

### PR DESCRIPTION
**Pull request by sweeneyde**
Hopefully "left-hand side is the same as assignment target" is more stable and less miss-prone than `Py_REFCNT == 2`.

Note that PyUnicode_Append already has lots of overhead, and it checks if it's safe to work in place.

See https://github.com/faster-cpython/ideas/discussions/269

https://bugs.python.org/issue47053

### CODE REVIEW

**Comment by sweeneyde** [comment]
A benchmark:

```python
from pyperf import Runner, perf_counter
import sys

LENGTHS = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9]
DATA = [('a',) * x for x in LENGTHS]

def bench(loops):
    data = DATA * loops
    t0 = perf_counter()
    for s in data:
        res = ''
        for c in s:
            res += c
    return perf_counter() - t0

runner = Runner()
runner.bench_time_func("inplace add str", bench)
```

```
Mean +- std dev: [main_concat] 4.84 us +- 0.06 us -> [nomiss] 4.24 us +- 0.04 us: 1.14x faster
```

**Comment by markshannon** [comment]
Looks good for the microbenchmark, do you have numbers for the full suite?

[This](https://github.com/faster-cpython/ideas/discussions/269#discussioncomment-2169711) is the stats for this PR?

**Comment by sweeneyde** [comment]
> Looks good for the microbenchmark, do you have numbers for the full suite?

On my not-that-stable laptop with GCC on WSL, using --enable-optimizations --with-lto, I get a 1.02x faster geometric mean: https://gist.github.com/sweeneyde/7fb779d28c55ba4b5e8d40f0bf8f596f

> [This](https://github.com/faster-cpython/ideas/discussions/269#discussioncomment-2169711) is the stats for this PR?

Yes, that's correct.

**Comment by sweeneyde** [comment]
The previous microbenchmark was with MSCV, I got some different results with related benchmarks on GCC:

```python
from pyperf import Runner, perf_counter
import sys

LENGTHS = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9]
DATA = [('a',) * x for x in LENGTHS]

def bench1(loops):
    data = DATA * loops
    t0 = perf_counter()
    for s in data:
        res = ''
        for c in s:
            res += c
    return perf_counter() - t0


def bench2(loops):
    data = []
    n = 10_000
    for i in range(loops):
        data.append(("a" * n, "a"))
        data.append(("", "a"))
    t0 = perf_counter()
    for s, c in data:
        s += c
        s += c
        s += c
    return perf_counter() - t0

runner = Runner()
runner.bench_time_func("bench1", bench1)
runner.bench_time_func("bench2", bench2)
```

```
bench1: Mean +- std dev: [bench_concat_main] 2.48 us +- 0.11 us -> [bench_concat_nomiss] 2.66 us +- 0.15 us: 1.07x slower
bench2: Mean +- std dev: [bench_concat_main] 976 ns +- 24 ns -> [bench_concat_nomiss] 866 ns +- 18 ns: 1.13x faster

Geometric mean: 1.02x faster
```

It could be just a random result of how the PGO decides to shuffle things around?

**Comment by markshannon** [comment]
~0% misses is a very clear improvement on 96.6%. 

I'm not worried that the benchmarks numbers are a bit noisy, given this is a clear improvement.

**Pull request merged**
