### PR TITLE
bpo-46449: add more assertions to verify that deepfreeze modules are finalized properly

### PR DESCRIPTION
**Pull request by kumaraditya303**
https://bugs.python.org/issue46449

### CODE REVIEW

**Comment by kumaraditya303** [comment]
cc @vstinner

**Review by vstinner — CHANGES_REQUESTED** [review]
`assert(Py_REFCNT(code) == 1000000000);` is very specific to deepfreeze currently implementation, whereas this code is a generic implementation of frozen modules which exists in Python 3.10 and older. I prefer to not leak too many deepfreeze implementation details here.

**Comment by kumaraditya303** [comment]
> `assert(Py_REFCNT(code) == 1000000000);` is very specific to deepfreeze currently implementation, whereas this code is a generic implementation of frozen modules which exists in Python 3.10 and older. I prefer to not leak too many deepfreeze implementation details here.

Sure this code is generic implementation of frozen modules but if `info->get_code` is not null then the block is about deepfreeze implementation as get_code is present only on deepfrozen modules not on just frozen modules.

**Comment by vstinner** [comment]
Sorry, I don't think that these assertions are correct.

**Comment by vstinner** [comment]
Tomorrow, a 3rd party code can decide to implement get_code() but use regular code objects, not use immortal code object. This code should remain generic.

**Pull request closed without merging**
