### PR TITLE
GH-115776: Static object are immortal, so mark them as such.

### PR DESCRIPTION
**Pull request by markshannon**
* Issue: gh-115776

### CODE REVIEW

**Comment by mdboom** [comment]
Should this be backported to 3.12?  Is it an actual bug / would we expect any impact on third-party extensions because of this?

**Comment by markshannon** [comment]
It only surfaced as a result of https://github.com/python/cpython/pull/116115, so maybe not.

**Comment by markshannon** [comment]
@eduardo-elizondo do you recall why the refcount was set to 1 for extension code?

**Comment by scoder** [comment]
Fixes the issue with the latest CPython master.

There's a comment above the definitions that also needs adapting.

**Review by ericsnowcurrently — APPROVED** [review]
This seems reasonable.  An initial refcount of 1 makes the object effectively immortal without any of the benefits.

The only potential problem is if an extension is expecting their static type/object to have a normal refcount (starting at 1).  However, that probably isn't worth worrying about.

The only thing I'd recommend is that you update the comment at line 118 to reflect the change.  If you know of any other similar comments elsewhere in the code it would be worth updating those too.

**Comment by mdboom** [comment]
> The only potential problem is if an extension is expecting their static type/object to have a normal refcount (starting at 1). However, that probably isn't worth worrying about.

My gut tells me a changelog entry should suffice there.  Extension authors (especially ones who care about this detail) are used to this sort of thing.

**Comment by eduardo-elizondo** [comment]
@markshannon This change is totally valid - the reason it was not done in the first place is to avoid incompatibility with extension code.

There could be asserts/tests on exact refcount values and this change would have broken those builds/tests. You can even see it in the immoral objects PR where I had to change _testembed.c to modify the `Py_REFCNT(str1) == 1` check to `_Py_IsImmortal(str1)`

There's an argument on whether or not having any exact refcounts checks are correct, but I didn't want to challenge it at the time. Thus, to avoid any problems with extension code and reduce the surface area of impact, I localized it to just affect the CPython build.

That said, happy to see that you are now cleaning this up!

**Comment by ngoldbaum** [comment]
For what it's worth, this change did break one numpy test, see the PR linked above. That said, I think this is a good change and it was trivial to update the test by adding a python version check.

**Comment by puremourning** [comment]
It broke vim tests too https://github.com/vim/vim/issues/15838#issuecomment-2403480614

**Pull request merged**
