### PR TITLE
gh-110383: Changed the doc for str.rsplit from 'starting from the left' to 'starting from the right' 

### PR DESCRIPTION
**Pull request by Unique-Usman**
Changed the doc for str.rsplit to be from 'starting from the left' to 'starting from the right' as str.rsplit start from the right

### CODE REVIEW

**Comment by erlend-aasland** [comment]
You need to change the clinic input code in `Objects/unicodeobject.c`. Directly manipulating the clinic output (anything that lives inside a `clinic/` directory) will never work; future updates to the clinic input would overwrite such a change, _but_ you'd never be able to check in such a change because we've got CI checks to prevent changes to generated code (see the "Check if generated files are up to date" CI check).

There's an [Argument Clinic How-to in the devguide](https://devguide.python.org/development-tools/clinic/). I suggest you start with that, and then retarget this PR to change `Objects/unicodeobject.c` instead.

**Comment by Unique-Usman** [comment]
Yeah @erlend-aasland thanks for the suggestion.

**Comment by sparrowt** [comment]
Looks like it's [this line](https://github.com/python/cpython/blob/4b90b5d857ba88c7d85483e188a73323df9ba05c/Objects/unicodeobject.c#L12689) specifically the ` = str.split` on the end that is "[cloning](https://devguide.python.org/development-tools/clinic/#how-to-clone-existing-functions)" the per-parameter docstrings from `split` onto `rsplit`.

Given the docs say:
> Sorry, there’s no syntax for partially cloning a function, or cloning a function then modifying it. Cloning is an all-or nothing proposition.

it seems like the only option is to stop cloning and then copy-paste the parameter docstrings from `split` [here](https://github.com/python/cpython/blob/4b90b5d857ba88c7d85483e188a73323df9ba05c/Objects/unicodeobject.c#L12500-L12508) into `rsplit` [here](https://github.com/python/cpython/blob/4b90b5d857ba88c7d85483e188a73323df9ba05c/Objects/unicodeobject.c#L12692C1-L12692C1).

**Comment by sparrowt** [comment]
I've opened https://github.com/python/cpython/pull/113353 which hopefully does the right thing

**Comment by erlend-aasland** [comment]
I propose a different approach in #113355.

**Pull request closed without merging**
