### PR TITLE
bpo-45654: freeze runpy module

### PR DESCRIPTION
**Pull request by kumaraditya303**
https://bugs.python.org/issue45654

### CODE REVIEW

**Comment by kumaraditya303** [comment]
cc @gvanrossum

**Comment by gvanrossum** [comment]
Did you regen all?

**Comment by kumaraditya303** [comment]
> Did you regen all?

Done

**Comment by kumaraditya303** [comment]
@gvanrossum Added news also, anything else left ?

**Review by gvanrossum — COMMENTED** [review]
Do you know by how much the binary size increased?

**Comment by kumaraditya303** [comment]
> Do you know by how much the binary size increased?

Around 250~ KB on windows 11 64 bit

**Comment by gvanrossum** [comment]
Okay, that's acceptable. I'll approve and merge then -- the Azure Pipelines PR failure seems a flake.

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Thanks for your contribution!

**Pull request merged**
