### PR TITLE
gh-105107: Remove PyEval_CallFunction() function

### PR DESCRIPTION
**Pull request by vstinner**
Remove 4 functions from the C API, deprecated in Python 3.9:

* PyEval_CallObjectWithKeywords()
* PyEval_CallObject()
* PyEval_CallFunction()
* PyEval_CallMethod()

Keep 3 functions in the stable ABI:

* PyEval_CallObjectWithKeywords()
* PyEval_CallFunction()
* PyEval_CallMethod()

* Issue: gh-105107

----
:books: Documentation preview :books:: https://cpython-previews--105108.org.readthedocs.build/

### CODE REVIEW

**Comment by vstinner** [comment]
cc @methane

**Comment by vstinner** [comment]
The "Tests / Check for source changes (pull_request)" CI job failed because the added NEWS entry filename contains a space in ``C API/`` sub-directory name.

**Review by methane — APPROVED** [review]

**Comment by hugovk** [comment]
I've merged https://github.com/python/cpython/pull/105110 to workaround the CI error, let's update this branch.

**Comment by vstinner** [comment]
I completed the documentation how to port existing code after reading comments of the long issue #73734.

**Comment by vstinner** [comment]
> I've merged https://github.com/python/cpython/pull/105110 to workaround the CI error, let's update this branch.

Thanks. To complete the doc, I rebased my PR on the main branch.

**Pull request merged**
