### PR TITLE
[3.5] bpo-36742: Corrects fix to handle decomposition in usernames (GH-13812) (GH-13814)

### PR DESCRIPTION
**Pull request by vstinner**
(cherry picked from commit 8d0ef0b5edeae52960c7ed05ae8a12388324f87e)

Co-authored-by: Steve Dower <steve.dower@python.org>
(cherry picked from commit fd1771dbdd28709716bd531580c40ae5ed814468)

https://bugs.python.org/issue36742

### CODE REVIEW

**Comment by vstinner** [comment]
https://bugs.python.org/issue36742 is not fully fixed in the 3.5 branch: commit 4655d576141ee56a69d2052431c636858fcb916a wasn't enough. We also need this second fix which is a backport from Python 3.6.

**Comment by larryhastings** [comment]
Just to confirm: this PR doesn't change any code in the standard library.  It only changes tests.  That's what you wanted?

**Comment by vstinner** [comment]
It changes the urllib module. I backported the change, I didn't make any change.

**Comment by larryhastings** [comment]
Thanks for the 3.5 backport love!

**Pull request merged**
