### PR TITLE
gh-125741: Update `build.yml` for the new check_autoconf_regen job

### PR DESCRIPTION
**Pull request by AA-Turner**
Follows on from #125744.

cc: @corona10 @webknjaz 

A

* Issue: gh-125741

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]
LGTM

**Comment by webknjaz** [comment]
@AA-Turner this will also need backport labels, I believe.

**Comment by AA-Turner** [comment]
Erlend hasn't merged the last set of back-ports yet so I'll hold off on merging this PR.

**Comment by erlend-aasland** [comment]
> Erlend hasn't merged the last set of back-ports yet so I'll hold off on merging this PR.

Merged!

**Review by erlend-aasland — APPROVED** [review]

**Pull request merged**
