### PR TITLE
define __abs__ to get an absolute path like in abs(Path("./"))

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by KOLANICH** [comment]
BTW, since you have a separate bug tracker and email is required, I'm not going to register on it.

**Comment by bitdancer** [comment]
We'll just close this, then, since it isn't likely to get accepted anyway, and the bug tracker and/or the python-ideals mailing list is where discussion would take place.  Thanks for wanting to contribute, though.

**Comment by KOLANICH** [comment]
@bitdancer, feel free to create an own PR and a bug on the bug tracker about adding __abs__ to this class. You can consider my contribution as public domain.

I'm not going to register to the bug tracker or sign any CLAs as IMHO it has too restrictive rules.

**Pull request closed without merging**
