### PR TITLE
[3.10] bpo-43760: Ensure that older Cython generated code compiles under 3.10.

### PR DESCRIPTION
**Pull request by markshannon**
Not sure what sort of NEWS entry this needs, if any.

https://bugs.python.org/issue43760

### CODE REVIEW

**Comment by markshannon** [comment]
Why does the ABI checker claim this breaks the ABI?
The size of the `PyThreadState`struct is not part of the ABI. It is never passed by value, only be pointer.

**Comment by pablogsal** [comment]
> The size of the `PyThreadState`struct is not part of the ABI. It is never passed by value, only be pointer.

Because code can dereference the pointer

**Comment by pablogsal** [comment]
> full definition the compiler needs the offsets to optimize member access.

For instance, this is this particular case:

```
  [C]'function void _PyErr_Clear(PyThreadState*)' at errors.c:453:1 has some indirect sub-type changes:
    parameter 1 of type 'PyThreadState*' has sub-type changes:
      in pointed to type 'typedef PyThreadState' at pystate.h:20:1:
        underlying type 'struct _ts' at pystate.h:62:1 changed:
          type size changed from 2240 to 2304 (in bits)
          1 data member insertion:
            'int _ts::use_tracing', at offset 384 (in bits) at pystate.h:79:1
          6 data member changes (22 filtered):
           'unsigned long int _ts::thread_id' offset changed from 1408 to 1472 (in bits) (by +64 bits)
           'int _ts::trash_delete_nesting' offset changed from 1472 to 1536 (in bits) (by +64 bits)
           'PyObject* _ts::trash_delete_later' offset changed from 1536 to 1600 (in bits) (by +64 bits)
           'void (void*)* _ts::on_delete' offset changed from 1600 to 1664 (in bits) (by +64 bits)
           'void* _ts::on_delete_data' offset changed from 1664 to 1728 (in bits) (by +64 bits)
           'CFrame _ts::root_cframe' offset changed from 2112 to 2176 (in bits) (by +64 bits)
```

**Comment by pablogsal** [comment]
Don't worry too much, as the fields are not public we can just regenerate the ABI. The check is there so you don't change it unadvertedly.

**Comment by pablogsal** [comment]
lel

**Comment by pablogsal** [comment]
Doesn't matter, I have created https://github.com/python/cpython/pull/28498

**Pull request closed without merging**
