### PR TITLE
bpo-36347: Renaming the constants for the .flags of PyMemberDef

### PR DESCRIPTION
**Pull request by matrixise**
https://bugs.python.org/issue36347

### CODE REVIEW

**Comment by remilapeyre** [comment]
This is nice, it makes the field far less opaque and improve readability. Do you think we could change those who are set to `0` to replace them by `READWRITE` in the same PR?

**Comment by matrixise** [comment]
@remilapeyre we could do it, but I prefer to avoid because it's a big change. This is the same thing with the f-string, you can use the f-string for the new development, not for the existing, excepted if you refactor the code.

**Comment by matrixise** [comment]
just for `Modules`, `Objects` we have ~69 definitions of members. I prefer to wait for the feedback of the core-dev and after create a new PR with this change (if they agree with this change).

**Comment by remilapeyre** [comment]
Ok, I think it's a bit less intrusive than for f-string because there still is some places where it's more readable to use other format strings but your patch would improve readability everywhere. You are right that it can be done in another PR and that it's better to wait for the feedback of a core dev anyway.

**Review by remilapeyre — APPROVED** [review]

**Comment by matrixise** [comment]
restart the build...

**Comment by matrixise** [comment]
I close this PR, I think it's a bad practice to create a big PR with a lot of modifications.

**Pull request closed without merging**
