### PR TITLE
Deleting duplicates in itertoolsmodule.c

### PR DESCRIPTION
**Pull request by AlphaHot**
If I am wrong, please explain to me why the code is duplicated?

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@AlphaHot

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by rhettinger — APPROVED** [review]

**Comment by brandtbucher** [comment]
Thanks for your time @AlphaHot, and welcome to CPython! :sunglasses:

I assume that you've seen the bot's message about the CLA?

**Review by brandtbucher — APPROVED** [review]
Nice catch!

**Comment by AlphaHot** [comment]
@brandtbucher @rhettinger CLA done

**Comment by AlphaHot** [comment]
[Contributor Agreement - signed.pdf](https://github.com/python/cpython/files/4364272/Contributor.Agreement.-.signed.pdf)

**Comment by brandtbucher** [comment]
Thanks for signing! Unfortunately, the CLA is manually processed by someone at the PSF, so it can take a couple of business days to update.

**Comment by rhettinger** [comment]
Thanks for attaching the CLA PDF.  That will suffice.

**Comment by ned-deily** [comment]
(FYI, the CLA has been processed, as the "check youself" link shows, but this PR doesn't have a bpo issue associated with it so the bot will not process it.)

**Pull request merged**
