### PR TITLE
bpo-43950: Implement fine grained error locations for interactive mode

### PR DESCRIPTION
**Pull request by thatbirdguythatuknownot**
Original issue number: #88116
Most of the implementation comes from #27117. Changes include new fields in the `compiler` struct (`.c_source`) and the `PyCodeObject` object (`.co_source`) to overcome the problem in the old PR by storing the source locally instead of globally. A new `source` argument was also added to `_PyAST_Compile()` to pass the source from the parser to the compiler.

### CODE REVIEW

**Comment by pablogsal** [comment]
I'm confused. The original PR #27117 is still open, even if it is a draft and the original design questions already remain. Why have you opened another PR? Have you contacted @isidentical first to take his code/approach? 

We still need to decide if this is a good idea because this has drawbacks, which is one of the reasons we didn't pursue this originally.

**Comment by thatbirdguythatuknownot** [comment]
> I'm confused. The original PR #27117 is still open, even if it is a draft and the original design questions already remain. Why have you opened another PR? Have you contacted @isidentical first to take his code/approach?
> 
> We still need to decide if this is a good idea because this has drawbacks, which is one of the reasons we didn't pursue this originally.

Alright, so I have to close this one first?

**Comment by pablogsal** [comment]
> Alright, so I have to close this one?

Well, you don't *have to* but the aspects and questions I have mentioned still stand. Particularly and most importantly, if you have taken code directly from https://github.com/python/cpython/pull/27117 then you need first to have the author's permission, otherwise, we won't be able to merge this even if we wanted.

**Comment by pablogsal** [comment]
After thinking about this I am -1 as the complexity introduced by this is quite high to just cover interactive mode. Unless @isidentical think otherwise, we should close this PR.

Thanks @thatbirdguythatuknownot for the prototype and for persuing the idea. Unfortunately this is one of the cases where the complexity introduced unfortunately doesn't balance well with the feature.

I think we could probably do it better in the future implementing interactive mode over temporary files

**Comment by thatbirdguythatuknownot** [comment]
Alright, I'll close this PR.

**Pull request closed without merging**
