### PR TITLE
gh-122835: Fix module name in ``test_typing``

### PR DESCRIPTION
**Pull request by Eclips4**
* Issue: gh-122835

### CODE REVIEW

**Comment by Eclips4** [comment]
Previously:
```python
eclips4@nixos ~/p/p/cpython (main)> ./python Lib/test/test_typing.py
...................................................................................................................................................................................................................................................................s.........................................................................................................................................................................................................................................................................................................................................F............................................................................................
======================================================================
FAIL: test_annotations (__main__.TypedDictTests.test_annotations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eclips4/programming/programming-languages/cpython/Lib/test/test_typing.py", line 8832, in test_annotations
    self.assertEqual(Y.__annotations__, {'a': type(None), 'b': fwdref})
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'a': <class 'NoneType'>, 'b': ForwardRef('int', module='__main__')} != {'a': <class 'NoneType'>, 'b': ForwardRef('int', module='test.test_typing')}
- {'a': <class 'NoneType'>, 'b': ForwardRef('int', module='__main__')}
?                                                           ^^^  ^^

+ {'a': <class 'NoneType'>, 'b': ForwardRef('int', module='test.test_typing')}
?                                                          +++++++++ ^^^  ^


----------------------------------------------------------------------
Ran 682 tests in 0.506s

FAILED (failures=1, skipped=1)
```

Now:
```python
eclips4@nixos ~/p/p/cpython (main) [1]> ./python Lib/test/test_typing.py
...................................................................................................................................................................................................................................................................s......................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 682 tests in 0.529s

OK (skipped=1)
```

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Does this need backporting, or is this one of the new tests added in 3.14?

**Comment by Eclips4** [comment]
> Does this need backporting, or is this one of the new tests added in 3.14?

This is a new test, backports aren't need.

**Comment by AlexWaygood** [comment]
Great, thanks!

**Pull request merged**
