### PR TITLE
 gh-93649: Split heaptype tests from _testcapimodule.c 

### PR DESCRIPTION
**Pull request by encukou**
I'll need to add a test related to heap types, so I'm splitting these out before that to make the test module more manageable.

* Issue: gh-93649

### CODE REVIEW

**Comment by encukou** [comment]
That failure looks unrelated.

**Comment by encukou** [comment]
The buildbot's next job passed: https://buildbot.python.org/all/#/builders/540/builds/3380

**Comment by ezio-melotti** [comment]
@encukou, it seems that this PR introduced two unused vars:
https://github.com/python/cpython/blob/7da4937748eb588bb0e977839061ce76cab1b252/Modules/_testcapi/heaptype.c#L279-L280

I'm seeing warnings about it in https://github.com/python/cpython/pull/95874/files:
image

**Comment by encukou** [comment]
Thanks for the catch! The warnings will be fixed in #95992

**Pull request merged**
