### PR TITLE
bpo-30266: support "= None" pattern in AbstractContextManager

### PR DESCRIPTION
**Pull request by JelleZijlstra**

### CODE REVIEW

**Review by ilevkivskyi — APPROVED** [review]

**Review by berkerpeksag — CHANGES_REQUESTED** [review]
Could you please add a note to `Misc/NEWS`?

**Comment by JelleZijlstra** [comment]
Done, thanks for the review.

**Comment by ilevkivskyi** [comment]
It looks like a fourth merge is required...

**Comment by gvanrossum** [comment]
Pinging @berkerpeksag -- is this now to your satisfaction? Could we get it in 3.6.3? (I.e. before Monday June 12.)

**Comment by gvanrossum** [comment]
This seems simple enough, I'm merging it.

**Comment by gvanrossum** [comment]
@Mariatta Can you help backporting this to 3.6?

**Pull request merged**
