### PR TITLE
gh-92546: Fix _perfcheck in pprint.py

### LINKED ISSUE #92546: Minor bug in pprint module
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
> pprint.py
Traceback (most recent call last):
  File "C:\Python\Python310\Lib\pprint.py", line 670, in <module>
    _perfcheck()
  File "C:\Python\Python310\Lib\pprint.py", line 645, in _perfcheck
    p._safe_repr(object, {}, None, 0, True)
TypeError: PrettyPrinter._safe_repr() takes 5 positional arguments but 6 were given

### PR DESCRIPTION
**Pull request by kj7rrv**
Closes #92546

* Issue: gh-92546

### CODE REVIEW

**Comment by kj7rrv** [comment]
I don't think this needs a NEWS entry because it's just a minor bug fix?

**Comment by arhadthedev** [comment]
I tried to do the same fix in gh-92560. Currently it stuck on determination whether developer-only tools should be tested, so I'm porting this function to [python/pyperformance](https://github.com/python/pyperformance) ([`pprint` branch of my fork](https://github.com/arhadthedev/pyperformance/tree/pprint) - I can't create a PR until I fix some bugs).

**Comment by kj7rrv** [comment]
@arhadthedev should I close this?

**Comment by arhadthedev** [comment]
@kj7rrv I would wait until a triager or a core developer walks by. Maybe your PR will be accepted so I'll close mine.

**Comment by kj7rrv** [comment]
@arhadthedev Oh, okay. I'll leave it.

**Comment by kj7rrv** [comment]
How long do the tests generally take?

**Comment by arhadthedev** [comment]
The port is done: https://github.com/python/pyperformance/pull/222. You can track it to close your PR after/if it's merged.

**Comment by kj7rrv** [comment]
So I should change this PR to remove _perfcheck instead of fixing the bug? @arhadthedev

**Comment by kj7rrv** [comment]
Superseded by gh-94613

**Pull request closed without merging**
