### PR TITLE
gh-101100: Fix sphinx warnings of removed opcodes

### PR DESCRIPTION
**Pull request by ghost**
Fixed sphinx warnings:
```
whatsnew/3.11.rst:1674: WARNING: 'opcode' reference target not found: BEFORE_WITH [ref.opcode]
whatsnew/3.4.rst:1982: WARNING: 'opcode' reference target not found: LOAD_CLASSDEREF [ref.opcode]
whatsnew/3.6.rst:2369: WARNING: 'opcode' reference target not found: FORMAT_VALUE [ref.opcode]
whatsnew/3.6.rst:2374: WARNING: 'opcode' reference target not found: BUILD_CONST_KEY_MAP [ref.opcode]
whatsnew/3.6.rst:2378: WARNING: 'opcode' reference target not found: CALL_FUNCTION [ref.opcode]
whatsnew/3.6.rst:2378: WARNING: 'opcode' reference target not found: CALL_FUNCTION_KW [ref.opcode]
whatsnew/3.6.rst:2378: WARNING: 'opcode' reference target not found: BUILD_MAP_UNPACK_WITH_CALL [ref.opcode]
whatsnew/3.6.rst:2378: WARNING: 'opcode' reference target not found: BUILD_TUPLE_UNPACK_WITH_CALL [ref.opcode]
whatsnew/3.6.rst:2389: WARNING: 'opcode' reference target not found: STORE_ANNOTATION [ref.opcode]
whatsnew/3.7.rst:2479: WARNING: 'opcode' reference target not found: CALL_METHOD [ref.opcode]
whatsnew/3.7.rst:2482: WARNING: 'opcode' reference target not found: STORE_ANNOTATION [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: BREAK_LOOP [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: CONTINUE_LOOP [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: SETUP_LOOP [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: SETUP_EXCEPT [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: ROT_FOUR [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: BEGIN_FINALLY [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: CALL_FINALLY [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: POP_FINALLY [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: END_FINALLY [ref.opcode]
whatsnew/3.8.rst:2155: WARNING: 'opcode' reference target not found: WITH_CLEANUP_START [ref.opcode]
whatsnew/3.9.rst:1206: WARNING: 'opcode' reference target not found: LOAD_ASSERTION_ERROR [ref.opcode]
```

* Issue: gh-101100

----
📚 Documentation preview 📚: https://cpython-previews--127222.org.readthedocs.build/

### CODE REVIEW

**Review by hugovk — APPROVED** [review]
Thanks!

**Comment by hugovk** [comment]
Please could you open backports for the 3.13 and 3.12 branches?

We should be careful, because some of these were removed in 3.14, so shouldn't be removed from 3.13 and 3.12 docs.

Likewise, any removed in 3.13 shouldn't be removed from 3.12 docs.

**Comment by koyuki7w** [comment]
@hugovk Thanks for reviewing. Opened PRs for 3.13 and 3.12 backports.

**Comment by hugovk** [comment]
Thank you!

**Pull request merged**
