### PR TITLE
bpo-35950: Raise OSError in io.BufferedReader.truncate()

### PR DESCRIPTION
**Pull request by berkerpeksag**
The truncate() method of io.BufferedReader() should raise OSError
when it is called on a read-only io.BufferedReader() instance.

https://bugs.python.org/issue35950

### CODE REVIEW

**Comment by methane** [comment]
Please try to read source code more widely, and make new code consistent with existing code.  For example:

https://github.com/python/cpython/blob/4e221577cb569e706980f02ceb50873e59cded75/Lib/_pyio.py#L1619-L1621

Same error type and error message is preferred.

**Comment by berkerpeksag** [comment]
Have you read the issue and documentation?

```
writable()
Return True if the stream supports writing. If False, write() and truncate() will
raise OSError.
```

https://docs.python.org/3/library/io.html#io.IOBase.writable

If I understand it correctly, `truncate()` should raise `OSerror` if the underlying stream's `writable()` returns `False`.

It seems to me that the implementation is in sync with the documentation here. Could you clarify your comment a bit?

**Comment by methane** [comment]
I read, of course.

"raise OSError" means "raise an instance of OSError or it's subclass."

UnsupportedOperation is subclass of OSError.  It is used in similar cases, like write() is called for non writable file.

**Comment by berkerpeksag** [comment]
Ah, now I understand what you mean. Yes, I'll update the PR.

**Comment by serhiy-storchaka** [comment]
Could you please update the PR, @berkerpeksag?

**Comment by berkerpeksag** [comment]
I'm going to update it this weekend.

**Comment by berkerpeksag** [comment]
Superseded by https://github.com/python/cpython/pull/18586.

**Pull request closed without merging**
