### PR TITLE
More actionable error message when spawn is incorrectly used.

### PR DESCRIPTION
**Pull request by ppwwyyxx**
Users of my library report this as an issue to my project when they encounter this error. The error message can be made more actionable - pointing them to a more detailed documentation that explains the fix.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Can I get a reviewer? Thanks

**Comment by arhadthedev** [comment]
@pitrou, @gpshead (as active multiprocessing experts)

**Comment by ppwwyyxx** [comment]
Hi, multiprocessing experts @pitrou and @gpshead, can you take a moment to look at this change in error message?

**Comment by pitrou** [comment]
@serhiy-storchaka What do you think?

**Comment by serhiy-storchaka** [comment]
Sorry, I am not an expert in this field and there are no code changes that I can quickly understand and review.

I can only point out that including web links in an error message is unusual, but this multi-line error message is already unusual. The code was added by @roudkerk in bpo-8713.

**Review by gpshead — APPROVED** [review]

**Comment by gpshead** [comment]
This is effectively a documentation change. It's an error message that should not be seen often, but is intended to tell people how to fix their code so they don't hit the error. Expanding on it and linking back to the multiprocessing docs seems fine to me, even if unusual.

**Pull request merged**
