### PR TITLE
Move around example in to_bytes() to avoid confusion

### PR DESCRIPTION
**Pull request by skirpichev**

### CODE REVIEW

**Comment by arhadthedev** [comment]
Can confirm that a paragraph `don't try to convert a value greater than 255 or you'll get an OverflowError` incorrectly has a non-throwing example.

**Comment by mdickinson** [comment]
I suspect the intent of the example was to support the "The default values can be used to conveniently turn an integer into a single byte object." statement rather than the "... don't try to convert a value greater than 255 ..." statement. 

Maybe @warsaw can confirm or deny?

**Comment by skirpichev** [comment]
Anyway, across the docs a pattern "don't do this and that or you'll get XYZ:" usually coming with a doctest, where you actually get XYZ...

Maybe we should just drop this example?  The text is clear enough.

**Comment by mdickinson** [comment]
I don't think the example should be changed here. If we want to reduce confusion, how about just moving things around so that the example immediately follows the "The default values can be used to conveniently turn an integer into a single byte object." statement?

**Comment by skirpichev** [comment]
> If we want to reduce confusion

That was the point.

> how about just moving things around

Does make sense for me.  See an attempt.

**Review by mdickinson — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
