### PR TITLE
gh-98831: register instructions have 0 pushes and pops

### PR DESCRIPTION
**Pull request by iritkatriel**
* Issue: gh-98831

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
Good call!

Maybe it's time to add some tests for the generated opcode metadata (but I'm not asking for that now).

**Comment by iritkatriel** [comment]
It failed very quickly when I tried to use it (the sanity check we added in the compiler flipped).

**Comment by gvanrossum** [comment]
Is it ready to merge? (Note: there are other things in the generator that probably don't work, e.g. there are some commented-out `out.emit(f"JUMPBY(OPSIZE(...` calls. But those might be not needed if we go ahead with the variable-length scheme.

**Comment by iritkatriel** [comment]
> Is it ready to merge?

I think so.

 
> Note: there are other things in the generator that probably don't work, e.g. there are some commented-out `out.emit(f"JUMPBY(OPSIZE(...` calls. But those might be not needed if we go ahead with the variable-length scheme.

I'm not doing variable length instructions now. I'm adding the plumbing in the compiler, and for now supporting only 1 oparg (so I can do RETURN_VALUE from a tmp register). There's plenty there to keep me busy for now.

**Pull request merged**
