### PR TITLE
Fix typo in help.html

### PR DESCRIPTION
**Pull request by KonstHardy**
Fix typo:

intially -> initially

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@KonstHardy

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by nanjekyejoannah — APPROVED** [review]

**Review by nanjekyejoannah — COMMENTED** [review]
LGTM, thanks for the fix @KonstHardy. This is simple enough to merge without signing the CLA but please sign it for future PRs. You can also sign for this one if you want before we merge it.

**Comment by terryjreedy** [comment]
Will explain later

**Comment by nanjekyejoannah** [comment]
I approved on basis of its a simple typo fixed, I will leave to you @terryjreedy

**Comment by terryjreedy** [comment]
I understand.  What neither of you knew is that idlelib/help.html is a near-copy of the idle.html generated from idle.rst by sphinx. This is done with a function in help.py that removes trailing whitespace and maybe some other stuff.  So this file should not be directly edited.  idle.rst got this fix two weeks ago in #27903.  I ran the update script and will commit the change in #28191.

**Pull request closed without merging**
