### PR TITLE
removal of duplicated text paragraph

### PR DESCRIPTION
**Pull request by taras-sereda**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@taras-sereda

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by akulakov** [comment]
I think we can merge this without CLA because it's only removal of duplicate paragraph? (the remaining copy is below the code example)

**Comment by taras-sereda** [comment]
CLA is already signed, but still "non-signed" label is there.
image

**Comment by arhadthedev** [comment]
Caches are evil. Here it's updated, there it isn't yet. So everything is OK. The only thing left is to wait someone from the team (keeping in mind time zones and work hours, of course).

> I think we can merge this without CLA because it's only removal of duplicate paragraph?

Without the CLA some contributor can sue Python Software Foundation on copyright grounds (any change of code is an intellectual property and so on). So the foundation keeps it safe.

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
