### PR TITLE
bpo-36541: lib2to3: Support named assignment expressions

### PR DESCRIPTION
**Pull request by thatch**
There are two copies of the grammar -- the one used by Python itself as
Grammar/Grammar, and the one used by lib2to3 which has necessarily diverged at
Lib/lib2to3/Grammar.txt because it needs to support older syntax an we want it
to be reasonable stable to avoid requiring fixer rewrites.

This brings suport for syntax like `if x:= foo():` to match what the live
Python grammar does.

https://bugs.python.org/issue36541

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by lisroach** [comment]
@thatch please add a NEWS entry (you can use the `blurb add` tool).

**Comment by gpshead** [comment]
I've clicked the buttons to land the parsing fix for https://bugs.python.org/issue33348 first (https://github.com/python/cpython/pull/6586).  you'll likely need to merge and update this PR after that merges.  Otherwise this looks good to go in.

**Comment by csabella** [comment]
@thatch, please take a look at the last review about rebasing this change.  Thanks!

**Comment by isidentical** [comment]
Any update regarding this patch?

**Comment by thatch** [comment]
I force-pushed a rebase on Feb 24, I think this is waiting on @gpshead review

**Review by gpshead — APPROVED** [review]

**Comment by thatch** [comment]
cherry_pick for 3.7 is https://github.com/python/cpython/pull/19317 (I had to manually push as the tool didn't understand my style of origin being read-only and having a separate remote for pushing)

**Pull request merged**
