### PR TITLE
Enhance PyConfig documentation

### PR DESCRIPTION
**Pull request by vstinner**
Mention more command line options.

### CODE REVIEW

**Comment by vstinner** [comment]
PR rebased to get the Docs CI fix: https://github.com/python/cpython/pull/92395

**Review by ezio-melotti — COMMENTED** [review]
For consistency, all the `0`s and `1`s should be wrapped within ` ``...`` `.

**Comment by vstinner** [comment]
> For consistency, all the 0s and 1s should be wrapped within ``...``.

As you want: done.

**Review by ezio-melotti — APPROVED** [review]
I meant all the ones you added, but that works too :)

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
