### PR TITLE
bpo-28556: Routine updates to typing

### PR DESCRIPTION
**Pull request by ilevkivskyi**
``typing`` module was last updated 2 months ago. Here are few more updates:
* Add ``NoReturn`` type
* Use ``WrapperDescriptorType`` (original PR by Jim Fasarakis-Hilliard)
* Minor bug-fixes

This needs to be backported to 3.5 and 3.6

Attn: @gvanrossum

### CODE REVIEW

**Comment by Mariatta** [comment]
Maybe update Misc/NEWS too?

**Comment by ilevkivskyi** [comment]
> Maybe update Misc/NEWS too?

Thank you @Mariatta, good point! Fixed this.

**Comment by Mariatta** [comment]
And of course there is a conflict now :(
@ilevkivskyi Do you mind resolving it first? Otherwise I think it looks good.

**Comment by ilevkivskyi** [comment]
@Mariatta 
> Do you mind resolving it first?

Resolved.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks :) I'll merge after the build is finished.

**Pull request merged**
