### PR TITLE
Add Pycharm's .idea directory to gitignore

### PR DESCRIPTION
**Pull request by rajathagasthya**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in "Your Details" at b.p.o
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least a day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by Carreau** [comment]
note you can also set that globally on your system : 

```
$ cat ~/.gitconfig
# This is Git's per-user configuration file.
[core]
	excludesfile = $HOME/.gitignore  
```
Which allow you to not patch every project you contribute to.

**Comment by vstinner** [comment]
Compared to the old .hgignore, .gitignore lacks more files:

```
BuildLog.htm
.DS_Store
Include/pydtrace_probes.h
lcov-report/
Misc/*.wpu
Tools/unicode/build/
Tools/unicode/MAPPINGS/
```

I don't know these files, so I don't know if it's ok to add them as well.

For .DS_Store (used by macOS): it seems like Git ignores it by default, which is a good idea ;-)

**Comment by zware** [comment]
We just rejected a patch to add Eclipse's project dir (bpo-29510), so I'm closing this as well.

Thanks for contributing, though!

**Comment by zware** [comment]
We do probably need to update .gitignore, though.

**Pull request closed without merging**
