### PR TITLE
bpo-42037: Corrected request dependencies in CookieJar functions

### PR DESCRIPTION
**Pull request by markus-sus**
https://bugs.python.org/issue42037

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@markus-sus

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by markus-sus** [comment]
I signed the agreement now and setup my bug tracker account properly.
Hopefully this will be resolved automatically then in a day or two.

**Review by Fidget-Spinner — APPROVED** [review]
LGTM.  The entries changed from `:meth:` to `:attr:` do seem to corroborate with the docs for [Request Objects](https://docs.python.org/3/library/urllib.request.html#request-objects).

**Review by ZackerySpytz — APPROVED** [review]

**Comment by markus-sus** [comment]
Is there anything I should do for this? I assume not

**Comment by markus-sus** [comment]
I see that the news item is required. Is it really needed for this relatively small change?

**Comment by Fidget-Spinner** [comment]
> I see that the news item is required. Is it really needed for this relatively small change?

Usually not. However only triagers and core devs can apply the skip news label (Zackery and I cant).

Since Eric is on the bpo, gentle ping to @merwok . Sorry to disturb.

**Comment by furkanonder** [comment]
@Fidget-Spinner Issue seems to be resolved. We can close the issue.

**Pull request merged**
