### PR TITLE
bpo-46340: fix DeprecationWarning when running asyncio tests

### PR DESCRIPTION
**Pull request by kumaraditya303**
https://bugs.python.org/issue46340

### CODE REVIEW

**Comment by kumaraditya303** [comment]
cc @asvetlov

**Comment by erlend-aasland** [comment]
Following the [devguide strictly](https://devguide.python.org/triaging/?highlight=skip%20issue#github-labels-for-prs), this PR needs an issue. _Skip issue_ is for misspellings in docs/comments, and perhaps for updating broken links.

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
I would consider rewording the PR title to more accurately reflect the actual change.

**Comment by kumaraditya303** [comment]
cc @asvetlov

**Review by asvetlov — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
