### PR TITLE
gh-123610: Added missing windows handle types to wintypes.py

### PR DESCRIPTION
**Pull request by rruuaanng**
* Issue: gh-123610

I fixed the issue with missing handles that was mentioned in https://github.com/python/cpython/issues/123610 and added the missing handle types.

My wrong commit made it difficult to reset. This is my last branch: https://github.com/python/cpython/pull/123721

### CODE REVIEW

**Comment by rruuaanng** [comment]
Hey @savannahostrowski, I’ve got a question I’d like to ask.
Based on the discussion in the PR #123721, That PR was last week, what should I do now?

**Comment by savannahostrowski** [comment]
@rruuaanng Thanks for the PR. We'll need to wait for a core developer to review it. Sometimes, PRs can take a while to be reviewed since many do this on a volunteer basis.  Let's leave this PR open and give folks time to review.

**Comment by picnixz** [comment]
I'm the one who reviewed it last week. Since nothing seemed to have changed, I think this is fine. I had one interrogation namely, whether this warrants a NEWS entry and what granularity of details should be used.

I suggested NOT to add a NEWS entry since we didn't even bother adding a NEWS entry for the previous handle types which are not even documented. However, a core dev will need to confirm this and to agree on merging this PR. We could, in a follow-up PR, add some doc indicating which handles are available and which are not. 

In the meantime, except waiting for such core dev, nothing more is needed. However, to spare CI resources, it would be preferrable not to merge the `main` branch into your branch unless you have merge conflicts to resolve.

**Comment by rruuaanng** [comment]
> I'm the one who reviewed it last week. Since nothing seemed to have changed, I think this is fine. I had one interrogation namely, whether this warrants a NEWS entry and what granularity of details should be used.
> 
> I suggested NOT to add a NEWS entry since we didn't even bother adding a NEWS entry for the previous handle types which are not even documented. However, a core dev will need to confirm this and to agree on merging this PR. We could, in a follow-up PR, add some doc indicating which handles are available and which are not.
> 
> In the meantime, except waiting for such core dev, nothing more is needed. However, to spare CI resources, it would be preferrable not to merge the `main` branch into your branch unless you have merge conflicts to resolve.
> 
> EDIT: I'll add the `skip news` label just so that the PR appears "green" on the PR page.

Thank you for your reminder.

**Comment by rruuaanng** [comment]
> @rruuaanng Thanks for the PR. We'll need to wait for a core developer to review it. Sometimes, PRs can take a while to be reviewed since many do this on a volunteer basis. Let's leave this PR open and give folks time to review.

Okay, thanks for the reminder, I think that's good.

**Comment by rruuaanng** [comment]
It's been two weeks since this PR was submitted. Maybe there are just too many PR, and it looks like no core developers have caught sight of it.
cc @vstinner

**Comment by zooba** [comment]
Agreed we don't really need NEWS for this, on the basis that anyone already using these types must have worked around it in some way, and the workarounds won't be broken by us adding the types here. It can be a secret little easter egg for someone to find (hopefully we aren't encouraging people to use the deprecated APIs that used these types...)

**Comment by rruuaanng** [comment]
Thanks to the reviewers for their efforts! Thanks for the merger of zooba! Maybe users will not use the above-mentioned abandoned API (to tell you quietly, Hmmmmm，they all actually used Linux).

**Comment by erlend-aasland** [comment]
> (hopefully we aren't encouraging people to use the deprecated APIs that used these types...)

I'm puzzled why we're adding (apparently) very seldom used and deprecated APIs.

**Pull request merged**
