### PR TITLE
Fix spelling errors of 'initial' in enum.py

### PR DESCRIPTION
**Pull request by hongweipeng**

### CODE REVIEW

**Review by eamanu — APPROVED** [review]

**Comment by eamanu** [comment]
Good catch @hongweipeng  This issue is a fix typo. News and bpo could be ignore here

**Review by aeros — APPROVED** [review]
Thanks for the PR @hongweipeng, LGTM.

**Comment by aeros167** [comment]
Categorizing this as a documentation change since it exclusively involves a docstring.

**Review by matrixise — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
