### PR TITLE
gh-119819: Update test to skip if _multiprocessing is unavailable.

### PR DESCRIPTION
**Pull request by vsajip**
* Issue: gh-119819

### CODE REVIEW

**Comment by mhsmith** [comment]
@vsajip: It looks like this PR didn't completely fix the issue. The [iOS builder](https://buildbot.python.org/all/#/builders/1380) has been failing for the last few hours because of some iOS version issue – hopefully @rkm can fix that when he has a chance. But before that, it was failing for the previous 9 days because a logging test was trying to use `multiprocessing`.

**Comment by mhsmith** [comment]
@freakboy3742: I initially got your username wrong above, so here's another mention in case the edit didn't notify you.

**Comment by freakboy3742** [comment]
@mhsmith That error looks like Xcode has auto-updated itself, but hasn't installed an updated simulator. I've just logged into the machine and completed the install process. 

What's weird is that the buildbot interface isn't raising alerts, and (at least for me), the link you've provided (which has previously worked for me), is showing *no* builds...

**Comment by vsajip** [comment]
Do you know _why_ the previous fix (`import_helper.import_module('_multiprocessing')`) didn't work? Especially as the original error on iOS referred to the inability to import `_multiprocessing`.

**Comment by freakboy3742** [comment]
It does work (although `requires_subprocess` is a slightly more common way to capture the requirement in the rest of the code base). The test failure we're currently seeing is a completely separate test to the one this PR is modifying. That test is currently only guarded on needing threads, but has an implicit dependency on the subprocess capabilities of multiprocessing.

**Comment by vsajip** [comment]
OK, but `requires_subprocess` basically just relies on `sys.platform` values, right? Conceivably `_multiprocessing` could be unavailable in other scenarios?

**Comment by freakboy3742** [comment]
Yes, `requires_subprocess` is based entirely on sys.platform.

I guess it's possible you might be on a platform where the platform supports subprocesses, but `_multiprocessing` hasn't been compiled; but given multiprocessing's only real dependency is subprocesses, it's seems highly unlikely. And, in this case, the problematic test doesn't use `_multiprocessing` at all - it's failing because the pure Python parts of `multiprocessing`.

**Pull request merged**
