### PR TITLE
gh-74606: Add fromfile_parent_relative parameter to argparse.ArgumentParser

### PR DESCRIPTION
**Pull request by bob1de**
This is an enhanced version of patch file on http://bugs.python.org/issue30421.

It maintains backwards compatibility and docs have been updated as well.
See that or gh issue below for description.

* Issue: gh-74606

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by bob1de** [comment]
Ok, CLA is signed now and I'm ready for feedback.

Best regards
Robert

**Comment by bob1de** [comment]
I wanted to ask for some progress on this issue. Is there somebody willing to review it? It still merges without conflicts.

Best regards
Robert

**Comment by terryjreedy** [comment]
Adding a new parameter is an enhancement that has not been mentioned on the issue, let alone approved.

**Comment by bob1de** [comment]
Sorry, but what did you mean by "let alone approved"?

Just for reference, here is a quote of the docs for the new parameter of ``argparse.ArgumentParser()`` I suggest:

* ``fromfile_parent_relative`` - Whether to treat paths of argument
  files as relative to the location of the file they are specified in
  (``True``) or to the current working directory (``False``) (default:
  ``False``)

Best regards
Robert

**Comment by terryjreedy** [comment]
My comment (which constituted my review) was in response to that.  You propose to add a new feature with a specific name.  AFAIK, neither Bethard nor any other core developer has approved of either the new feature as a concept or the specific name.

To seek such approval, you could post to python-ideas list.  (I think most proposals other than for tkinter and IDLE should start there.) Briefly describe the idea and rationale and reference the issue and this PR.  If you get a positive response, expect discussion of the option (parameter) name.

**Comment by bob1de** [comment]
Thank you for your explanation. This is my first contribution to cpython, hence thinks went a bit wrong somehow.

**Comment by bob1de** [comment]
@terryjreedy Ah! I didn't get your response at python-dev. That's why your comment here seemed out-of-context to me. Now I read it and things are clear. Thanks again!

**Comment by arhadthedev** [comment]
> You propose to add a new feature with a specific name. AFAIK, neither Bethard nor any other core developer has approved of either the new feature as a concept or the specific name.

@terryjreedy Was the approval achieved? If not, should the PR and issue be closed then?

/cc @bob1de

**Comment by bob1de** [comment]
@arhadthedev No, this wasn't pursued any further from my side. It started as the sharing of a little code I used in a project and thought could also be beneficial to stdlib, but the process turned out more complex than expected. Had not much of an idea of the cpython contribution guidelines back then.

So I guess I'm better closing this right away and maybe start a fresh python-dev discussion on the issue eventually, correct?

**Comment by terryjreedy** [comment]
When this was submitted, the then expert listed in the expert's index was added as nosy, but he had become inactive.  Another core dev worked on argparse a bit a year or two ago, and is doing other things now.  I believe someone else has touched argparse recently, but not listed himself as an expert responsible for the module.  Robert, if you are withdrawing the suggestion, perhaps close this and the issue.  But if you still think it a good idea, I would leave at least the issue, for the next person who looks as the Argparse issues list https://github.com/orgs/python/projects/5.

**Comment by bob1de** [comment]
@terryjreedy Thanks, then I'll close this PR and leave the issue open; I still think the way nested inclusion behaves right now can be irritating at least. Maybe someone picks up the idea later on or has an even better way to improve on this.

**Pull request closed without merging**
