### PR TITLE
Typo in math.prod example

### PR DESCRIPTION
**Pull request by ashwinvis**
Trivial change in whatsnew document for 3.8.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks for catching this. cc: @rhettinger

**Review by eamanu — APPROVED** [review]
LGM

**Comment by eamanu** [comment]
Hi @ashwinvis Thanks for the contribution. Please don't forget the CLA  :-)

**Comment by ashwinvis** [comment]
Done

**Review by aeros — APPROVED** [review]
Thanks for the PR @ashwinvis.

The changes look good to me. Since this is a typo correction, we can skip the bpo issue and news entry (particularly since it's correcting "what's new"). Also, this should be backported 3.8.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks @ashwinvis for your contribution!

**Pull request merged**
