### PR TITLE
Fix `test.support.Py_C_RECURSION_LIMIT` to reflect `Include/cpython/pystate.h` more accurately

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by vstinner** [comment]
The `_testcapi` extension should always be available when running the Python test suite. I suppose that the ImportError code path is for Python implementation others than CPython, no?

**Comment by brettcannon** [comment]
> The `_testcapi` extension should always be available when running the Python test suite. I suppose that the ImportError code path is for Python implementation others than CPython, no?

I have no idea since I didn't add that code.

**Comment by vstinner** [comment]
@markshannon: Do you have an opinion on this change?

@brettcannon: If you want to sync the Python support code with the C header file, you may also add the Py_DEBUG case. (But I'm asking if it's worth it, since you can expect the `_testcapi` extension to be available in CPython.)

**Comment by brettcannon** [comment]
If we end up not bothering with this PR then I will update the comment to drop the `pystate.h` comment as it's misleading if it doesn't have to be kept in sync.

**Pull request merged**
