### PR TITLE
gh-125196: Use PyUnicodeWriter in symtable.c

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-125196

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by vstinner** [comment]
Merged, thanks for the review @JelleZijlstra.

**Comment by encukou** [comment]
Due to either this change or #124865, the *AMD64 Arch Linux TraceRefs 3.x* buildbot is failing: https://buildbot.python.org/#/builders/484/builds/6022/steps/6/logs/stdio

**Comment by vstinner** [comment]
> Due to either this change or https://github.com/python/cpython/pull/124865, the AMD64 Arch Linux TraceRefs 3.x buildbot is failing: https://buildbot.python.org/#/builders/484/builds/6022/steps/6/logs/stdio

I checked with git bisect and the regression was introduced by commit f2cb39947093feda3ff85b8dc820922cc5e5f954:

```
commit f2cb39947093feda3ff85b8dc820922cc5e5f954
Author: Eric Snow <ericsnowcurrently@gmail.com>
Date:   Wed Oct 9 11:32:16 2024 -0600

    gh-116510: Fix a Crash Due to Shared Immortal Interned Strings (gh-124865)
    
    Fix a crash caused by immortal interned strings being shared between
    sub-interpreters that use basic single-phase init. In that case, the string
    can be used by an interpreter that outlives the interpreter that created and
    interned it. For interpreters that share obmalloc state, also share the
    interned dict with the main interpreter.
    
    This is an un-revert of gh-124646 that then addresses the Py_TRACE_REFS
    failures identified by gh-124785.
```

**Comment by nascheme** [comment]
I created a bug for this crash: gh-125286

**Pull request merged**
