### PR TITLE
[3.6] bpo-30290: IDLE - pep8 names and tests for help-about 

### PR DESCRIPTION
**Pull request by terryjreedy**
054e09147aaa6f61aca6cd40c7bf7ce6dc54a04b (GH 1697)
5a346d5dbc1f0f70eca706a8ba19f7645bf17837 (GH 1714)
eca7da0f13c78013b924fe7306f3e2e59c0af40b (GH 1838)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Mariatta** [comment]
I think you need to change the base branch to `3.6` instead of `master`

**Comment by Mariatta** [comment]
@terryjreedy I re-opened your PR, and changed the base branch to `3.6` instead of `master`.

**Comment by terryjreedy** [comment]
This attempt to cherry pick the 3 PRs for bpo-30290 somehow went horribly wrong.  So is the failure to find my CLA ;-).  The conflicts are artifacts, as is the number of files changed.  I have no idea how to make the conflicts disappear.  When I click on files changed, the actual diff for two idlelib files looks correct.  I am going to try again in my 3.6 worktree with only git commands.

**Comment by terryjreedy** [comment]
https://github.com/python/cpython/pull/2070 is a clean PR with the same diff.
This time I selected 3.6 as the base.

**Pull request closed without merging**
