### PR TITLE
bpo-44185: Added close() to mock_open __exit__

### LINKED ISSUE #88351: mock_open file handle __exit__ does not call close
BPO | [44185](https://bugs.python.org/issue44185)
--- | :---
Nosy | @voidspace, @tirkarthi, @CendioOssman, @williamsjoblom, @samety
PRs | <li>python/cpython#26902</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-20.08:17:05.886>
labels = ['type-feature', 'library', '3.9', '3.10', '3.11']
title = 'mock_open file handle __exit__ does not call close'
updated_at = <Date 2021-06-26.15:05:02.423>
user = 'https://github.com/williamsjoblom'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-26.15:05:02.423>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-20.08:17:05.886>
creator = 'williamsjoblom'
dependencies = []
files = []
hgrepos = []
issue_num = 44185
keywords = ['patch']
message_count = 1.0
messages = ['394005']
nosy_count = 5.0
nosy_names = ['michael.foord', 'xtreak', 'CendioOssman', 'williamsjoblom', 'sametyaslan']
pr_nums = ['26902']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44185'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by samety**
https://bugs.python.org/issue44185

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@samety

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by MaxwellDupre — APPROVED** [review]
Looks ok for me.

**Comment by cjw296** [comment]
Let's discuss more on https://github.com/python/cpython/issues/88351.

**Review by cjw296 — APPROVED** [review]

**Review by cjw296 — CHANGES_REQUESTED** [review]
Please can you fix the docs failure coming from bad ReST in the NEWS entry.

**Comment by samety** [comment]
I have made the requested changes; please review again

**Review by cjw296 — APPROVED** [review]

**Pull request merged**
