### PR TITLE
bpo-43044: [2.7] Doc: Stop linking to non-existent pages.

### PR DESCRIPTION
**Pull request by verhovsky**
Currently, visiting https://docs.python.org/2/library/stringio.html and clicking the "You should upgrade and read the Python documentation for the current stable release." link in the header sends you to https://docs.python.org/3/library/stringio.html which is a 404 Error page. This pull requests changes that link to https://docs.python.org/3/library/io.html#io.StringIO

Pages that have been completely removed in Python 3 now link to https://docs.python.org/3/index.html

I also added a few alternatives in comments if someone has any thoughts. (See https://github.com/python/pythondotorg/issues/1719 for details)

https://bugs.python.org/issue43044

### CODE REVIEW

**Comment by tirkarthi** [comment]
Adding @benjaminp since this is changes for 2.7 and has reached EoL.

**Comment by verhovsky** [comment]
Here's a clickable list of the redirects I've added:

| Python 2                                                                                  | Python 3                                                                                                                                                   |
|-------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [`library/fpformat`](https://docs.python.org/2/library/fpformat.html)                     |                                                                                                                                                            |
| [`library/mutex`](https://docs.python.org/2/library/mutex.html)                           |                                                                                                                                                            |
| [`library/new`](https://docs.python.org/2/library/new.html)                               |                                                                                                                                                            |
| [`library/statvfs`](https://docs.python.org/2/library/statvfs.html)                       |                                                                                                                                                            |
| [`library/dircache`](https://docs.python.org/2/library/dircache.html)                     |                                                                                                                                                            |
| [`library/macpath`](https://docs.python.org/2/library/macpath.html)                       |                                                                                                                                                            |
| [`library/dbhash`](https://docs.python.org/2/library/dbhash.html)                         |                                                                                                                                                            |
| [`library/bsddb`](https://docs.python.org/2/library/bsddb.html)                           |                                                                                                                                                            |
| [`library/someos`](https://docs.python.org/2/library/someos.html)                         |                                                                                                                                                            |
| [`library/popen2`](https://docs.python.org/2/library/popen2.html)                         |                                                                                                                                                            |
| [`library/mhlib`](https://docs.python.org/2/library/mhlib.html)                           |                                                                                                                                                            |
| [`library/mimetools`](https://docs.python.org/2/library/mimetools.html)                   |                                                                                                                                                            |
| [`library/mimewriter`](https://docs.python.org/2/library/mimewriter.html)                 |                                                                                                                                                            |
| [`library/mimify`](https://docs.python.org/2/library/mimify.html)                         |                                                                                                                                                            |
| [`library/multifile`](https://docs.python.org/2/library/multifile.html)                   |                                                                                                                                                            |
| [`library/sgmllib`](https://docs.python.org/2/library/sgmllib.html)                       |                                                                                                                                                            |
| [`library/imageop`](https://docs.python.org/2/library/imageop.html)                       |                                                                                                                                                            |
| [`library/hotshot`](https://docs.python.org/2/library/hotshot.html)                       |                                                                                                                                                            |
| [`library/future_builtins`](https://docs.python.org/2/library/future_builtins.html)       |                                                                                                                                                            |
| [`library/user`](https://docs.python.org/2/library/user.html)                             |                                                                                                                                                            |
| [`library/fpectl`](https://docs.python.org/2/library/fpectl.html)                         |                                                                                                                                                            |
| [`library/restricted`](https://docs.python.org/2/library/restricted.html)                 |                                                                                                                                                            |
| [`library/rexec`](https://docs.python.org/2/library/rexec.html)                           |                                                                                                                                                            |
| [`library/bastion`](https://docs.python.org/2/library/bastion.html)                       |                                                                                                                                                            |
| [`library/imputil`](https://docs.python.org/2/library/imputil.html)                       |                                                                                                                                                            |
| [`library/compiler`](https://docs.python.org/2/library/compiler.html)                     |                                                                                                                                                            |
| [`library/dl`](https://docs.python.org/2/library/dl.html)                                 |                                                                                                                                                            |
| [`library/posixfile`](https://docs.python.org/2/library/posixfile.html)                   |                                                                                                                                                            |
| [`library/commands`](https://docs.python.org/2/library/commands.html)                     |                                                                                                                                                            |
| [`library/mac`](https://docs.python.org/2/library/mac.html)                               |                                                                                                                                                            |
| [`library/ic`](https://docs.python.org/2/library/ic.html)                                 |                                                                                                                                                            |
| [`library/macos`](https://docs.python.org/2/library/macos.html)                           |                                                                                                                                                            |
| [`library/macostools`](https://docs.python.org/2/library/macostools.html)                 |                                                                                                                                                            |
| [`library/easydialogs`](https://docs.python.org/2/library/easydialogs.html)               |                                                                                                                                                            |
| [`library/framework`](https://docs.python.org/2/library/framework.html)                   |                                                                                                                                                            |
| [`library/autogil`](https://docs.python.org/2/library/autogil.html)                       |                                                                                                                                                            |
| [`library/carbon`](https://docs.python.org/2/library/carbon.html)                         |                                                                                                                                                            |
| [`library/colorpicker`](https://docs.python.org/2/library/colorpicker.html)               |                                                                                                                                                            |
| [`library/macosa`](https://docs.python.org/2/library/macosa.html)                         |                                                                                                                                                            |
| [`library/gensuitemodule`](https://docs.python.org/2/library/gensuitemodule.html)         |                                                                                                                                                            |
| [`library/aetools`](https://docs.python.org/2/library/aetools.html)                       |                                                                                                                                                            |
| [`library/aepack`](https://docs.python.org/2/library/aepack.html)                         |                                                                                                                                                            |
| [`library/aetypes`](https://docs.python.org/2/library/aetypes.html)                       |                                                                                                                                                            |
| [`library/miniaeframe`](https://docs.python.org/2/library/miniaeframe.html)               |                                                                                                                                                            |
| [`library/sgi`](https://docs.python.org/2/library/sgi.html)                               |                                                                                                                                                            |
| [`library/al`](https://docs.python.org/2/library/al.html)                                 |                                                                                                                                                            |
| [`library/cd`](https://docs.python.org/2/library/cd.html)                                 |                                                                                                                                                            |
| [`library/fl`](https://docs.python.org/2/library/fl.html)                                 |                                                                                                                                                            |
| [`library/fm`](https://docs.python.org/2/library/fm.html)                                 |                                                                                                                                                            |
| [`library/gl`](https://docs.python.org/2/library/gl.html)                                 |                                                                                                                                                            |
| [`library/imgfile`](https://docs.python.org/2/library/imgfile.html)                       |                                                                                                                                                            |
| [`library/jpeg`](https://docs.python.org/2/library/jpeg.html)                             |                                                                                                                                                            |
| [`library/sun`](https://docs.python.org/2/library/sun.html)                               |                                                                                                                                                            |
| [`library/sunaudio`](https://docs.python.org/2/library/sunaudio.html)                     |                                                                                                                                                            |
| [`c-api/int`](https://docs.python.org/2/c-api/int.html)                                   |                                                                                                                                                            |
| [`c-api/string`](https://docs.python.org/2/c-api/string.html)                             |                                                                                                                                                            |
| [`c-api/class`](https://docs.python.org/2/c-api/class.html)                               |                                                                                                                                                            |
| [`c-api/cobject`](https://docs.python.org/2/c-api/cobject.html)                           |                                                                                                                                                            |
| [`howto/doanddont`](https://docs.python.org/2/howto/doanddont.html)                       |                                                                                                                                                            |
| [`howto/webservers`](https://docs.python.org/2/howto/webservers.html)                     |                                                                                                                                                            |
| [`library/strings`](https://docs.python.org/2/library/strings.html)                       | [`library/text.html`](https://docs.python.org/3/library/text.html)                                                                                         |
| [`library/stringio`](https://docs.python.org/2/library/stringio.html)                     | [`library/io.html#io.StringIO`](https://docs.python.org/3/library/io.html#io.StringIO)                                                                     |
| [`library/sets`](https://docs.python.org/2/library/sets.html)                             |                                                                                                                                                            |
| [`library/userdict`](https://docs.python.org/2/library/userdict.html)                     | [`library/collections.html#userdict-objects`](https://docs.python.org/3/library/collections.html#userdict-objects)                                         |
| [`library/repr`](https://docs.python.org/2/library/repr.html)                             | [`library/reprlib.html`](https://docs.python.org/3/library/reprlib.html)                                                                                   |
| [`library/copy_reg`](https://docs.python.org/2/library/copy_reg.html)                     | [`library/copyreg.html`](https://docs.python.org/3/library/copyreg.html)                                                                                   |
| [`library/anydbm`](https://docs.python.org/2/library/anydbm.html)                         | [`library/dbm.html`](https://docs.python.org/3/library/dbm.html)                                                                                           |
| [`library/whichdb`](https://docs.python.org/2/library/whichdb.html)                       | [`library/dbm.html#dbm.whichdb`](https://docs.python.org/3/library/dbm.html#dbm.whichdb)                                                                   |
| [`library/dumbdbm`](https://docs.python.org/2/library/dumbdbm.html)                       | [`library/dbm.html#module-dbm.dumb`](https://docs.python.org/3/library/dbm.html#module-dbm.dumb)                                                           |
| [`library/dbm`](https://docs.python.org/2/library/dbm.html)                               | [`library/dbm.html#module-dbm.ndbm`](https://docs.python.org/3/library/dbm.html#module-dbm.ndbm)                                                           |
| [`library/gdbm`](https://docs.python.org/2/library/gdbm.html)                             | [`library/dbm.html#module-dbm.gnu`](https://docs.python.org/3/library/dbm.html#module-dbm.gnu)                                                             |
| [`library/robotparser`](https://docs.python.org/2/library/robotparser.html)               | [`library/urllib.robotparser.html`](https://docs.python.org/3/library/urllib.robotparser.html)                                                             |
| [`library/md5`](https://docs.python.org/2/library/md5.html)                               |                                                                                                                                                            |
| [`library/sha`](https://docs.python.org/2/library/sha.html)                               |                                                                                                                                                            |
| [`library/thread`](https://docs.python.org/2/library/thread.html)                         | [`library/_thread.html`](https://docs.python.org/3/library/_thread.html)                                                                                   |
| [`library/dummy_thread`](https://docs.python.org/2/library/dummy_thread.html)             |                                                                                                                                                            |
| [`library/email-examples`](https://docs.python.org/2/library/email-examples.html)         | [`library/email.examples.html`](https://docs.python.org/3/library/email.examples.html)                                                                     |
| [`library/rfc822`](https://docs.python.org/2/library/rfc822.html)                         |                                                                                                                                                            |
| [`library/htmlparser`](https://docs.python.org/2/library/htmlparser.html)                 | [`library/html.parser.html`](https://docs.python.org/3/library/html.parser.html)                                                                           |
| [`library/htmllib`](https://docs.python.org/2/library/htmllib.html)                       |                                                                                                                                                            |
| [`library/urllib2`](https://docs.python.org/2/library/urllib2.html)                       | [`library/urllib.request.html`](https://docs.python.org/3/library/urllib.request.html)                                                                     |
| [`library/httplib`](https://docs.python.org/2/library/httplib.html)                       | [`library/http.client.html`](https://docs.python.org/3/library/http.client.html)                                                                           |
| [`library/urlparse`](https://docs.python.org/2/library/urlparse.html)                     | [`library/urllib.parse.html`](https://docs.python.org/3/library/urllib.parse.html)                                                                         |
| [`library/basehttpserver`](https://docs.python.org/2/library/basehttpserver.html)         | [`library/http.server.html`](https://docs.python.org/3/library/http.server.html)                                                                           |
| [`library/simplehttpserver`](https://docs.python.org/2/library/simplehttpserver.html)     | [`library/http.server.html#http.server.SimpleHTTPRequestHandler`](https://docs.python.org/3/library/http.server.html#http.server.SimpleHTTPRequestHandler) |
| [`library/cgihttpserver`](https://docs.python.org/2/library/cgihttpserver.html)           | [`library/http.server.html#http.server.CGIHTTPRequestHandler`](https://docs.python.org/3/library/http.server.html#http.server.CGIHTTPRequestHandler)       |
| [`library/cookielib`](https://docs.python.org/2/library/cookielib.html)                   | [`library/http.cookiejar.html`](https://docs.python.org/3/library/http.cookiejar.html)                                                                     |
| [`library/cookie`](https://docs.python.org/2/library/cookie.html)                         | [`library/http.cookies.html`](https://docs.python.org/3/library/http.cookies.html)                                                                         |
| [`library/xmlrpclib`](https://docs.python.org/2/library/xmlrpclib.html)                   | [`library/xmlrpc.client.html`](https://docs.python.org/3/library/xmlrpc.client.html)                                                                       |
| [`library/simplexmlrpcserver`](https://docs.python.org/2/library/simplexmlrpcserver.html) | [`library/xmlrpc.server.html`](https://docs.python.org/3/library/xmlrpc.server.html)                                                                       |
| [`library/docxmlrpcserver`](https://docs.python.org/2/library/docxmlrpcserver.html)       | [`library/xmlrpc.server.html#documenting-xmlrpc-server`](https://docs.python.org/3/library/xmlrpc.server.html#documenting-xmlrpc-server)                   |
| [`library/ttk`](https://docs.python.org/2/library/ttk.html)                               | [`library/tkinter.ttk.html`](https://docs.python.org/3/library/tkinter.ttk.html)                                                                           |
| [`library/tix`](https://docs.python.org/2/library/tix.html)                               | [`library/tkinter.tix.html`](https://docs.python.org/3/library/tkinter.tix.html)                                                                           |
| [`library/scrolledtext`](https://docs.python.org/2/library/scrolledtext.html)             | [`library/tkinter.scrolledtext.html`](https://docs.python.org/3/library/tkinter.scrolledtext.html)                                                         |
| [`library/__builtin__`](https://docs.python.org/2/library/__builtin__.html)               | [`library/builtins.html`](https://docs.python.org/3/library/builtins.html)                                                                                 |
| [`library/_winreg`](https://docs.python.org/2/library/_winreg.html)                       | [`library/winreg.html`](https://docs.python.org/3/library/winreg.html)                                                                                     |


And the code to generate it:

```py
moved_files = {
    "library/fpformat": None,
    "library/mutex": None,
    "library/new": None,
    "library/statvfs": None,
    "library/dircache": None,
    "library/macpath": None,
    "library/dbhash": None,
    "library/bsddb": None,
    # 'library/someos': 'library/index',
    "library/someos": None,
    # 'library/popen2': 'library/subprocess',
    "library/popen2": None,
    # 'library/mhlib': 'library/mailbox',
    "library/mhlib": None,
    # 'library/mimetools': 'library/email',
    "library/mimetools": None,
    # 'library/mimewriter': 'library/email',
    "library/mimewriter": None,
    # 'library/mimify': 'library/email',
    "library/mimify": None,
    # 'library/multifile': 'library/email',
    "library/multifile": None,
    "library/sgmllib": None,
    "library/imageop": None,
    # 'library/hotshot': 'library/profile',
    "library/hotshot": None,
    "library/future_builtins": None,
    "library/user": None,
    "library/fpectl": None,
    "library/restricted": None,
    "library/rexec": None,
    "library/bastion": None,
    "library/imputil": None,
    "library/compiler": None,
    # 'library/dl': 'library/ctypes',
    "library/dl": None,
    "library/posixfile": None,
    # 'library/commands': 'library/subprocess',
    "library/commands": None,
    "library/mac": None,
    "library/ic": None,
    "library/macos": None,
    "library/macostools": None,
    "library/easydialogs": None,
    "library/framework": None,
    "library/autogil": None,
    "library/carbon": None,
    "library/colorpicker": None,
    "library/macosa": None,
    "library/gensuitemodule": None,
    "library/aetools": None,
    "library/aepack": None,
    "library/aetypes": None,
    "library/miniaeframe": None,
    "library/sgi": None,
    "library/al": None,
    "library/cd": None,
    "library/fl": None,
    "library/fm": None,
    "library/gl": None,
    "library/imgfile": None,
    "library/jpeg": None,
    "library/sun": None,
    "library/sunaudio": None,
    # 'c-api/int': 'c-api/long',
    "c-api/int": None,
    # 'c-api/string': 'c-api/bytes',
    "c-api/string": None,
    "c-api/class": None,
    # 'c-api/cobject': 'c-api/capsule',
    "c-api/cobject": None,
    "howto/doanddont": None,
    "howto/webservers": None,
    "library/strings": "library/text",
    "library/stringio": ("library/io", "io.StringIO"),
    # 'library/sets': ('library/stdtypes', 'set'),
    # 'library/sets': ('library/stdtypes', 'set-types-set-frozenset'),
    "library/sets": None,
    "library/userdict": ("library/collections", "userdict-objects"),
    "library/repr": "library/reprlib",
    "library/copy_reg": "library/copyreg",
    "library/anydbm": "library/dbm",
    "library/whichdb": ("library/dbm", "dbm.whichdb"),
    "library/dumbdbm": ("library/dbm", "module-dbm.dumb"),
    "library/dbm": ("library/dbm", "module-dbm.ndbm"),
    "library/gdbm": ("library/dbm", "module-dbm.gnu"),
    "library/robotparser": "library/urllib.robotparser",
    # 'library/md5': 'library/hashlib',
    "library/md5": None,
    # 'library/sha': 'library/hashlib',
    "library/sha": None,
    "library/thread": "library/_thread",
    # Renamed to _dummy_thread but has since been removed completely
    # 'library/dummy_thread': 'library/_dummy_thread',
    "library/dummy_thread": None,
    "library/email-examples": "library/email.examples",
    # 'library/rfc822': 'library/email',
    "library/rfc822": None,
    "library/htmlparser": "library/html.parser",
    "library/htmllib": None,
    # 'library/urllib2': 'library/urllib',
    "library/urllib2": "library/urllib.request",
    "library/httplib": "library/http.client",
    "library/urlparse": "library/urllib.parse",
    "library/basehttpserver": "library/http.server",
    "library/simplehttpserver": ("library/http.server", "http.server.SimpleHTTPRequestHandler"),
    "library/cgihttpserver": ("library/http.server", "http.server.CGIHTTPRequestHandler"),
    "library/cookielib": "library/http.cookiejar",
    "library/cookie": "library/http.cookies",
    "library/xmlrpclib": "library/xmlrpc.client",
    "library/simplexmlrpcserver": "library/xmlrpc.server",
    "library/docxmlrpcserver": ("library/xmlrpc.server", "documenting-xmlrpc-server"),
    "library/ttk": "library/tkinter.ttk",
    "library/tix": "library/tkinter.tix",
    "library/scrolledtext": "library/tkinter.scrolledtext",
    "library/__builtin__": "library/builtins",
    "library/_winreg": "library/winreg",
}

from tabulate import tabulate

rows = []
for old, new in moved_files.items():
    if new is None:
        new = ""
    elif isinstance(new, str):
        new = f"[`{new}.html`](https://docs.python.org/3/{new}.html)"
    else:
        new = f"[`{new[0]}.html#{new[1]}`](https://docs.python.org/3/{new[0]}.html#{new[1]})"
    rows.append([f"[`{old}`](https://docs.python.org/2/{old}.html)", new])

print(
    tabulate(
        rows,
        headers=["Python 2", "Python 3"],
        tablefmt="github",
    )
)
```

You can find a list of all the files that are missing between Python 2.7 and Python 3.8 by downloading a copy of the documentation, then using `comm` against the output of `find` in the two directories. This misses any files that are completely different but still named the same but I don't think that happened.

```sh
wget https://docs.python.org/2/archives/python-2.7.18-docs-html.zip
unzip python-2.7.18-docs-html.zip

wget https://docs.python.org/3/archives/python-3.9.1-docs-html.zip  # new link at https://docs.python.org/3/download.html
unzip python-3.9.1-docs-html.zip

comm -23 <(find python-2.7.18-docs-html/ | cut -d'/' -f2- | sort) <(find python-3.9.1-docs-html/ | cut -d'/' -f2- | sort)
```

**Comment by ned-deily** [comment]
Sorry, the PR was closed automatically when the 2.7 branch was recently deleted, not through explicit action. The behavior you describe is certainly not ideal.  Perhaps there is another way to solve the problem: create redirects or some such in the 3 doc tree or server config rather than modifying the now-frozen 2.7 source?  Pinging @JulienPalard.  And, to pursue this further, please open an issue on the Python bug tracker: https://bugs.python.org.

**Comment by JulienPalard** [comment]
Yes I'd prefer doing this on the nginx config instead on the non-existing 2.7 branch, as I previously did a few times here:  https://github.com/python/psf-salt/blob/3f0c2941fe7df2dad29fe669811291b991eb677a/salt/docs/config/nginx.docs-backend.conf#L38

@verhovsky would you mind converting your PR to nginx syntax, on https://github.com/python/psf-salt/?

**Pull request closed without merging**
