### PR TITLE
bpo-31270: Simplify documentation of itertools.zip_longest

### PR DESCRIPTION
**Pull request by raphaelm**
https://bugs.python.org/issue31270

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by raphaelm** [comment]
CLA is signed and submitted. Do I need to write a NEWS entry for this? I think it's rather "skip news", right?

**Comment by Mariatta** [comment]
Thanks @raphaelm, I think news can be skipped for this one :)

**Comment by raphaelm** [comment]
Hi @Mariatta, thanks for the quick answer! :)

**Comment by rhettinger** [comment]
I prefer code that is closer to the actual implementation:

```
    def zip_longest(*args, **kwds):
        # zip_longest('ABCD', 'xy', fillvalue='-') --> Ax By C- D-
        fillvalue = kwds.get('fillvalue')
        iterators = [iter(it) for it in args]
        num_active = len(iterators)
        while True:
            values = []
            for i, it in enumerate(iterators):
                if it is None:
                    value = fillvalue
                else:
                    try:
                        value = next(it)
                    except StopIteration:
                        num_active -= 1
                        value = fillvalue
                        iterators[i] = None
                values.append(value)
            if not num_active:
                return
            yield tuple(values)
```

Also, please keep the leading whitespace the same as the original.  Likewise, don't introduce blank lines into the code equivalents.

**Review by rhettinger — CHANGES_REQUESTED** [review]
See alternate implementation in the comments.

**Comment by rhettinger** [comment]
Moving this to an alternate pull request #3427

**Pull request closed without merging**
