### PR TITLE
Fix error in argparse documentation example

### PR DESCRIPTION
**Pull request by SarahPythonista**
Automerge-Triggered-By: @rhettinger

Automerge-Triggered-By: @aeros

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@SarahPythonista

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by rhettinger — APPROVED** [review]

**Review by aeros — APPROVED** [review]
Thanks for the PR @SarahPythonista and welcome!

I tested the suggested changes in the REPL using Python 3.8 and received the following output:

```py
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo', required=True)
_StoreAction(option_strings=['--foo'], dest='foo', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
>>> parser.parse_args(['--foo', 'BAR'])
Namespace(foo='BAR')
>>> parser.parse_args([])
usage: [-h] --foo FOO
: error: the following arguments are required: --foo
```

The suggested changes look correct to me, good catch.

**Comment by aeros** [comment]
Also, if you're having issues with the CLA status not updating after 24 hours, I would recommend manually refreshing the status on GitHub through https://check-python-cla.herokuapp.com/.

**Comment by csabella** [comment]
@SarahPythonista, thank you for the PR.  Your PR will be merged automatically once the CLA is signed.  Please take a look at the comment from @aeros and leave a comment if you're having issues with the CLA.  Thank you!

**Comment by aeros** [comment]
Going to close the 3.7 backport PR (since we typically only do backports for the current version on docs.python.org and later).

**Comment by aeros** [comment]
Thanks for the reminder to take care of this PR @tirkarthi and to @SarahPythonista for the documentation example fix. :-)

**Pull request merged**
