### PR TITLE
gh-100540: Remove obsolete Modules/_ctypes/darwin/ dlfcn shim

### PR DESCRIPTION
**Pull request by zware**
As far as I can tell, this hasn't been actually used since Mac OS X 10.2.

* Issue: gh-100540

### CODE REVIEW

**Comment by zware** [comment]
!buildbot macOS

**Comment by zware** [comment]
!buildbot .*mac

**Comment by arhadthedev** [comment]
Probably, this should be removed too:

https://github.com/python/cpython/blob/199507b81a302ea19f93593965b1e5088195a6c5/Tools/c-analyzer/cpython/_parser.py#L54

**Comment by zware** [comment]
> Probably, this should be removed too:

Ah, thanks; I missed that one here, though I got the neighboring one in GH-100543.

**Review by ronaldoussoren — APPROVED** [review]
Patch looks good to me.

**Pull request merged**
