### PR TITLE
future-proof .travis.yml for python 3.10

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Review by aeros — APPROVED** [review]
@asottile Thanks for the contribution and good catch! The `skip news` and `skip issue` labels would likely be appropriate for this PR.

**Comment by ammaraskar** [comment]
LGTM, looks like 3.10 is confirmed too:

> 3.9 will receive bugfix updates approximately every month for approximately 12 months. After the release of 3.10.0 final, a final 3.9 bugfix update will be released.

https://discuss.python.org/t/pep-596-python-3-9-release-schedule-doubling-the-release-cadence/1828

**Comment by zware** [comment]
Thanks for the patch @asottile, and thanks for the reviews @aeros167 and @ammaraskar!

**Comment by aeros167** [comment]
> Thanks for the patch @asottile, and thanks for the reviews @aeros167 and @ammaraskar!

No problem, and thanks for merging the PR @zware. (:

**Pull request merged**
