### PR TITLE
gh-93183: Adjust wording in socket docs

### LINKED ISSUE #93183: [docs] socket documentation: "packages" -> "packets"
**Documentation**

In the example of the [socket.rst](https://github.com/python/cpython/blob/main/Doc/library/socket.rst),  the comment ```# receive all packages``` should be changed to ```# receive all packets``` and the comment  ```receive a package``` should be changed to  ```receive a packet```.

```
import socket

# the public network interface
HOST = socket.gethostbyname(socket.gethostname())

# create a raw socket and bind it to the public interface
s = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_IP)
s.bind((HOST, 0))

# Include IP headers
s.setsockopt(socket.IPPROTO_IP, socket.IP_HDRINCL, 1)

# receive all packages
s.ioctl(socket.SIO_RCVALL, socket.RCVALL_ON)

# receive a package
print(s.recvfrom(65565))

# disabled promiscuous mode
s.ioctl(socket.SIO_RCVALL, socket.RCVALL_OFF)
```

### PR DESCRIPTION
**Pull request by VictorNorman**
Replace "package" and "packages" with "packet" and "packets" in comments in sample code.

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@VictorNorman, please sign the CLA.

**Review by ezio-melotti — APPROVED** [review]

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
> @VictorNorman, please sign the CLA.

Quoting https://devguide.python.org/committing/#assessing-a-pull-request:

> Make sure that the contributor has signed a [Contributor Licensing Agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA), unless their change has no possible intellectual property associated with it (e.g. fixing a spelling mistake in documentation)

AFAICS, this PR can land without the CLA being signed.

**Comment by erlend-aasland** [comment]
> Quoting https://devguide.python.org/committing/#assessing-a-pull-request:
> 
> > Make sure that the contributor has signed a [Contributor Licensing Agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA), unless their change has no possible intellectual property associated with it (e.g. fixing a spelling mistake in documentation)
> 
> AFAICS, this PR can land without the CLA being signed.

Darn, that does not help; I'm unable to merge since the CI does not pass. So, @VictorNorman, please sign the CLA, or I cannot merge this.

**Comment by AA-Turner** [comment]
> I'm unable to merge since the CI does not pass

This seems to be a regression with the new CLA system - was it intended? @VictorNorman has an institutional email address, so may need to go through the corporate signing process with his university, rather than the individual process.

A

**Comment by erlend-aasland** [comment]
I'm not sure what to do with this PR. Should we just close it? As long as Victor Norman does not respond, there is not much I can do, at least.

**Comment by AA-Turner** [comment]
@erlend-aasland it isn't a copyrightable change, so I would close and you could just push the changes as a core dev (I would open a PR myself but I'm plagued by CLA issues!)

A

**Comment by erlend-aasland** [comment]
Ok, thanks, I'll do that tomorrow.

**Pull request closed without merging**
