### PR TITLE
gh-111495: add stub files for C API test modules

### PR DESCRIPTION
**Pull request by skirpichev**
This is to reduce merge conflicts (Modules/Setup.stdlib.in) for subsequent pull requests for the issue.

* Issue: gh-111495

### CODE REVIEW

**Comment by skirpichev** [comment]
So far there is only files from https://github.com/python/cpython/pull/111496, https://github.com/python/cpython/pull/111562 and #109647.  More is coming.

CC @serhiy-storchaka

**Comment by skirpichev** [comment]
Ok, all test modules for #111495 were added.  @serhiy-storchaka, this is ready for review.

BTW, perhaps this should be labeled "tests" automatically?

**Review by serhiy-storchaka — APPROVED** [review]
I prefer to remove parameter names in declarations, but LGTM.

**Comment by serhiy-storchaka** [comment]
It could be an opportunity to re-order all lists in alphabetic order, but it would make more difficult to see what items were added.

**Comment by serhiy-storchaka** [comment]
I guess some changes were not backported to 3.12. @skirpichev could you please manually create a backport?

**Comment by skirpichev** [comment]
On Tue, Oct 31, 2023 at 10:46:46PM -0700, Serhiy Storchaka wrote:
>    I guess some changes were not backported to 3.12. ***@***.*** could you
>    please manually create a backport?

Sure, I'll try.

**Pull request merged**
