### PR TITLE
gh-117201: Handle leading `//` for `posixpath.commonpath`

### PR DESCRIPTION
**Pull request by nineteendo**
Tracked further here:

- #117361

### CODE REVIEW

**Comment by nineteendo** [comment]
Hmm, looks like `None` should raise a `TypeError`...

**Review by barneygale — CHANGES_REQUESTED** [review]
Very tidy implementation! I'm particularly pleased you removed this head-scratcher:

```python
isabs, = set(p[:1] == sep for p in paths)
```

Could you add a news blurb?

**Comment by nineteendo** [comment]
Barneygale, I have made the requested changes; please review again.

**Comment by nineteendo** [comment]
Eh, there seems to be a bug with @bedevere-app:

- I converted this issue to a draft & back
- bedevere-app added "awaiting review" & removed "awaiting change review".

Not entirely sure where to report that...

**Comment by nineteendo** [comment]
@zooba, what do you think of these changes?

**Comment by barneygale** [comment]
Don't worry about making `commonpath()` a little slower if you're fixing a bug, that's no problem. You don't need to compensate for it by speeding up other methods! Those speed-ups look nice, but I think they might be easier to review in their own PR, if that's no trouble? Thanks!

**Comment by nineteendo** [comment]
I was simply refactoring the other functions to make them more readable, while waiting for suggestions.
But, must I put the bug fixes for `ntpath.commonpath` & `posixpath.realpath` (coming up) in separate pull requests?

**Comment by barneygale** [comment]
Yes please, separate PRs for separate changes makes each one easier to review.

Note that we don't accept changes that _only_ improve readability. It causes too much churn and too many arguments. But you're welcome to improve readability as part of another change, e.g. a bugfix, enhancement or speed-up, as long as you're not introducing too much risk by tinkering with delicate code. Hope that makes sense?

**Comment by nineteendo** [comment]
Eh...

**Comment by nineteendo** [comment]
I've renamed the branch causing this pull request to be closed. Follow up in #117334.

**Pull request closed without merging**
