### PR TITLE
bpo-39541: Remove distutils bdist_wininst command

### PR DESCRIPTION
**Pull request by vstinner**
Remove distutils bdist_wininst command, it was deprecated in Python
3.8: use bdist_wheel command instead.

https://bugs.python.org/issue39541

### CODE REVIEW

**Comment by vstinner** [comment]
Oh, this change breaks setuptools:

```
(...)
File "/home/runner/work/cpython/cpython/Doc/venv/lib/python3.9/site-packages/setuptools/command/install_scripts.py", line 35, in run
  bw_cmd = self.get_finalized_command("bdist_wininst")
(...)
ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'
```

**Comment by vstinner** [comment]
> Oh, this change breaks setuptools: (...)

I reported the issue to setuptools: https://github.com/pypa/setuptools/issues/1985

**Comment by zooba** [comment]
@vstinner The easiest way is probably to replace it with the contents of https://github.com/python/cpython/blob/master/PC/layout/support/distutils.command.bdist_wininst.py (which is currently what I drop in for the distros that don't include this). It keeps setuptools happy right up to the point where you try and use the command, and then it fails nicely. We can also point to the discussions or at least the bugs about why we removed it.

**Comment by vstinner** [comment]
> @vstinner The easiest way is probably to replace it with the contents of https://github.com/python/cpython/blob/master/PC/layout/support/distutils.command.bdist_wininst.py (which is currently what I drop in for the distros that don't include this). It keeps setuptools happy right up to the point where you try and use the command, and then it fails nicely. We can also point to the discussions or at least the bugs about why we removed it.

Done. I tested manually that "make venv PYTHON=../python" works in the Doc/ directory. It fails without the Lib/distutils/command/bdist_wininst.py stub.

**Comment by vstinner** [comment]
@zooba: Should we keep PC/layout/support/distutils.command.bdist_wininst.py and Tools/msi/distutils.command.bdist_wininst.py? I don't know how these files are used.

**Comment by vstinner** [comment]
@pganssle: my setuptools fix has been merged into setuptools. Does it change something to do you decision on this PR? Should it go into Python 3.9 or not?

**Comment by vstinner** [comment]
There is no clear consensus towards removing distutils bdist_wininst command. I close this PR for now, it's too late for Python 3.9 (feature freeze is coming soon). We can reconsider removing it once setuptools will be more ready for this removal.

**Pull request closed without merging**
