### PR TITLE
bpo-42064: Optimise `sqlite3` state access, part 1

### PR DESCRIPTION
**Pull request by erlend-aasland**
Prepare for module state:

- Add "get state by defining class" and "get state by module def" stubs
- Add AC defining class when needed
- Add state pointer to connection context
- Pass state as argument to utility functions

https://bugs.python.org/issue42064

Automerge-Triggered-By: GH:encukou

### CODE REVIEW

**Comment by encukou** [comment]
Have you thought about caching the state on Connection objects? That way you could get the state from a cursor by following two pointers. (And similarly for other cases where you have a Connection, which is most of pysqlite).
Connections are already quite heavy, so adding one more pointer might be a good trade-off.

`pysqlite_get_state_by_cls` looks like it'll eventually use `_PyType_GetModuleByDef`, which isn't as fast as following two pointers.

**Comment by erlend-aasland** [comment]
> Have you thought about caching the state on Connection objects? That way you could get the state from a cursor by following two pointers. (And similarly for other cases where you have a Connection, which is most of pysqlite).
> Connections are already quite heavy, so adding one more pointer might be a good trade-off.

Yes, I have though about it, but I don't remember why I didn't follow that idea :) As you say, it's probably a very good trade-off. I'll have a go at it.

> `pysqlite_get_state_by_cls` looks like it'll eventually use `_PyType_GetModuleByDef`, which isn't as fast as following two pointers.

Both true.

**Comment by erlend-aasland** [comment]
PTAL!

**Review by encukou — APPROVED** [review]

**Comment by encukou** [comment]
Looks good, I just did a trivial merge to resolve a conflict.

**Comment by erlend-aasland** [comment]
> Looks good, I just did a trivial merge to resolve a conflict.

Great, thanks and thank you for reviewing.

**Pull request merged**
