### PR TITLE
[3.6] bpo-39545: document that await does not work in f-strings

### PR DESCRIPTION
**Pull request by elenaoat**
https://bugs.python.org/issue39545

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
I'm here at the PyCascades 2020 sprint sitting next to Elena.

**Comment by gvanrossum** [comment]
This is waiting for @larryhastings to merge. This piece of documentation is *only* relevant for 3.6, since in 3.7 this actually works (see the issue, bpo-39545).

**Comment by zware** [comment]
@ned-deily for 3.6 :)

**Comment by ned-deily** [comment]
(Don't blame @larryhastings for 3.6! :) )

**Comment by gvanrossum** [comment]
Sorry Larry and thanks Ned!

**Pull request merged**
