### PR TITLE
gh-92106: Forbid specialization of TypedDict types

### LINKED ISSUE #92106: Forbid specialization of TypedDict types
`typing.TypedDict` creates a `dict` subclass. `dict` is a generic class, and can be specialized, e.g. `dict[int, str]`. But TypedDict creates a specialized dictionary class, with different types for values for different keys (and the type of the key is always `str`). It is not a generic class. It does not make sense to specialize it the same way as TypedDict.
```python
class Point2D(TypedDict):
    x: int
    y: int
    label: str

Point2D[int, str]
```
The last line should be error at run time.

Generic TypedDict (#89026) is a different story.

This change can be made as a side effect of #27663, but I prefer to have a separate discussion for this.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Closes #92106.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Cc. @davidfstr

**Review by AlexWaygood — APPROVED** [review]
Seems nice and simple, and it does indeed make no sense from a typing perspective to try to parameterise a non-generic `TypedDict`

**Comment by JelleZijlstra** [comment]
This could break users who want to use generic TypedDicts compatible with pre-3.11:

```python
if TYPE_CHECKING:
    class TD(TypedDict, Generic[T]):
        a: T
else:
    class TD(TypedDict):
        a: T

d: TD[int] = {"a": 1}
```

I think it's safer to keep things unchanged here.

**Comment by davidfstr** [comment]
> I think it's safer to keep things unchanged here.

Agreed.

Also, this PR appears to conflict with https://github.com/python/cpython/pull/27663/ , which seems likely to be merged soon.

**Comment by serhiy-storchaka** [comment]
Forbidding parametrization of non-generic TypedDict types is a side effect of #27663. I created a separate issue to make it clear.

If we agree that it should forbidden, we should merge this PR (which also includes tests). If we agree that it should be allowed, we should add other tests, explicitly document this behavior, and change #27663 to keep non-generic TypedDict types parametrizable.

**Comment by serhiy-storchaka** [comment]
> This could break users who want to use generic TypedDicts compatible with pre-3.11:

Why not write `if TYPE_CHECKING or sys.version_info >= (3, 11):`?

**Comment by JelleZijlstra** [comment]
> > This could break users who want to use generic TypedDicts compatible with pre-3.11:
> 
> Why not write `if TYPE_CHECKING or sys.version_info >= (3, 11):`?

That would work, but it would be a backward compatibility break. We should let code work on 3.11 unchanged if possible.

**Review by JelleZijlstra — CHANGES_REQUESTED** [review]
Let's instead test that subscription works on arbitrary TypedDicts.

**Comment by JelleZijlstra** [comment]
Closing in favor of #92176.

**Pull request closed without merging**
