### PR TITLE
GH-105879: Note exec/eval keyword change in What's New

### PR DESCRIPTION
**Pull request by ncoghlan**
* Issue: gh-105879

----
📚 Documentation preview 📚: https://cpython-previews--121831.org.readthedocs.build/

### CODE REVIEW

**Comment by hugovk** [comment]
Rebased to check if https://github.com/python/cpython/pull/121848 fixes the CI.

**Comment by webknjaz** [comment]
:crossed_fingers:

**Comment by ambv** [comment]
At least the name of the skipped Windows job is still borked.

"Tests / Windows ${{ ((fromJSON(matrix.free-threading) && '(free-threading)') || '') }} (pull_requ"

**Comment by webknjaz** [comment]
@ambv a workaround would be to use a static `name:` entry and embed the variable bits into the reusable workflow job names one level below. I personally don't really care, but if that annoys you enough, we could go for it.

**Comment by webknjaz** [comment]
Though, there might be other limitations with this (some sort of a `${{ '' }}` expression, even empty, is usually needed for nicer display in the sidebar when the jobs are actually run).

**Comment by webknjaz** [comment]
@ambv if you still want the job names to be rendered differently — let me know, and I can come up with alternative options.

**Comment by ambv** [comment]
OK, thanks! Let's see how it looks for a while and we'll decide if it's still bothering me later.

**Pull request merged**
