### PR TITLE
bpo-44396: Update multi-line-start location when reallocating tokenizer buffers

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue44396

Automerge-Triggered-By: GH:pablogsal

### CODE REVIEW

**Comment by isidentical** [comment]
Should we also check whether `multiline_start` is `NULL` in https://github.com/python/cpython/blob/4cb6ba14325cff98589c2660d1d2c65f4aacfee4/Parser/tokenizer.c#L1885

**Comment by pablogsal** [comment]
> Should we also check whether `multiline_start` is `NULL` in

Hummm...why you think that is necessary? How can that happen?

**Comment by isidentical** [comment]
If I am not missing anything, according to this (on your branch) when the `tok->multi_line_start - tok->buf < 0`, then `multi_line_start` becomes `NULL`. 
https://github.com/python/cpython/blob/304ca6ddb0591405ca422b5442306b59b157e2ca/Parser/tokenizer.c#L388

**Review by isidentical — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
