### PR TITLE
Minor typo fix in Default.wxl

### PR DESCRIPTION
**Pull request by Ditzy3076**
Issue: Not created

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by orsenthil** [comment]
Hi @JamesPavek , there is no typo in that sentence. It's a grammatically correct, meaningful sentence. Prefer not to change it. So -1 from me.

**Comment by DimitrisJim** [comment]
Definitely not a typo but I actually like the change, it reads better this way.

**Comment by Mariatta** [comment]
Thank you for the PR, @JamesPavek. 
I agree with @orsenthil, the sentence is fine as is.

**Pull request closed without merging**
