### PR TITLE
bpo-33012: Fix invalid function cast warnings with gcc 8

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
for method conventions different from METH_NOARGS, METH_O and
METH_VARARGS in Argument Clinic generated code.

https://bugs.python.org/issue33012

### CODE REVIEW

**Review by methane — APPROVED** [review]

**Comment by xdegaye** [comment]
Shouldn't these changes be made in the generator instead, i.e. in ./Tools/clinic/clinic.py ?

**Comment by xdegaye** [comment]
Followed by the command:
```
make regen-all
```

**Comment by methane** [comment]
@xdegaye I think that's @serhiy-storchaka did. See
https://github.com/python/cpython/pull/6748/files#diff-5e15637e15d50f49f6cb1d7f69fcab4b

**Comment by xdegaye** [comment]
@methane you are right, sorry for the noise.

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by vstinner** [comment]
@serhiy-storchaka: Can you please update/rebase your change?

**Comment by vstinner** [comment]
See also PR #6008 and https://bugs.python.org/issue33015

**Pull request merged**
