### PR TITLE
gh-99952: [ctypes] fix refcount issues in from_param() result.

### PR DESCRIPTION
**Pull request by ynkdir**
Fixes a reference counting issue with `ctypes.Structure` when a `from_param()` method call is used and the structure size is larger than a C pointer `sizeof(void*)`.

This problem existed for a very long time, but became more apparent in 3.8+ by change likely due to garbage collection cleanup timing changes.

* Issue: gh-99952

### CODE REVIEW

**Comment by ynkdir** [comment]
related changelog
bpo-35947: Update windows to the current version of libffi #11797
bpo-37140: Fix StructUnionType_paramfunc() #15612

**Comment by junkmd** [comment]
🚀

**Comment by FFY00** [comment]
I am not comfortable enough judging if this is the best/correct fix, but it seems like something that @vstinner might enjoy having a look at.

**Comment by junkmd** [comment]
🎄 🎁 🧑‍🎄 🤶 
Just remind.

**Comment by dpy013** [comment]
hello all
Is there an update on the current pr?

**Comment by junkmd** [comment]
The absence of updates may be because the [`expert-ctypes` label](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Aopen+label%3Aexpert-ctypes+) is not attached to this PR, even though it is attached to issue #99952.

Looking at the PRs with the `expert-ctypes` label that have been merged, I think the other core developers involved to `ctypes` are @zware, @AA-Turner and @gpshead.

Triage and labeling to PRs seems to be done by @AlexWaygood.

I hope that they are aware of this ping and will respond.

**Comment by zware** [comment]
This looks reasonable as far as I can tell, but unfortunately my expertise with `ctypes` only extends as far as removing ancient copies of `libffi` from the repository :)

**Review by gpshead — APPROVED** [review]

**Comment by gpshead** [comment]
Thanks everyone, this kind of bug can be particularly challenging to diagnose!

**Comment by ynkdir** [comment]
Thank you.

**Pull request merged**
