### PR TITLE
Remove more stray backticks from NEWS files

### PR DESCRIPTION
**Pull request by ezio-melotti**
Follow-up of #115356 which removes more stray backticks.

### CODE REVIEW

**Review by erlend-aasland — APPROVED** [review]

**Comment by ezio-melotti** [comment]
Are these files generated by blurb?  Is it ok to edit them directly?

**Review by hugovk — APPROVED** [review]

**Comment by ezio-melotti** [comment]
Does someone want to try to backport these?
I tried using cherry picker but ran into errors and I didn't have time yet to investigate and fix them.

**Comment by hugovk** [comment]
Done! There were no changes to apply to the 3.11 branch.

**Comment by ezio-melotti** [comment]
Thanks!

**Pull request merged**
