### PR TITLE
gh-127341: Argument Clinic: fix compiler warnings for getters with docstrings

### LINKED ISSUE #127341: Clinic causes compiler warnings when using a getter and setter with a docstring
# Bug report

### Bug description:

I noticed this while working on GH-126890, as some odd macro redefinition warnings came up from the generated clinic file. As it turns out, clinic has a bug where using *both* `@getter` and `@setter` where the getter has a docstring doesn't work correctly. Quick reproducer:
```c
/*[clinic input]
@getter
Test.test

My silly docstring
[clinic start generated code]*/

/*[clinic input]
@setter
Test.test
[clinic start generated code]*/
```

This results in generated code that looks like this:

```c
PyDoc_STRVAR(Test_test__doc__,
"My silly docstring");
#define Test_test_HAS_DOCSTR

#if defined(Test_test_HAS_DOCSTR)
#  define Test_test_DOCSTR Test_test__doc__
#else
#  define Test_test_DOCSTR NULL
#endif
#if defined(TEST_TEST_GETSETDEF)
#  undef TEST_TEST_GETSETDEF
#  define TEST_TEST_GETSETDEF {"test", (getter)Test_test_get, (setter)Test_test_set, Test_test_DOCSTR},
#else
#  define TEST_TEST_GETSETDEF {"test", (getter)Test_test_get, NULL, Test_test_DOCSTR},
#endif

static PyObject *
Test_test_get_impl(TestObj *self);

static PyObject *
Test_test_get(TestObj *self, void *Py_UNUSED(context))
{
    return Test_test_get_impl(self);
}

#if defined(TEST_TEST_HAS_DOCSTR)
#  define Test_test_DOCSTR Test_test__doc__
#else
#  define Test_test_DOCSTR NULL
#endif
#if defined(TEST_TEST_GETSETDEF)
#  undef TEST_TEST_GETSETDEF
#  define TEST_TEST_GETSETDEF {"test", (getter)Test_test_get, (setter)Test_test_set, Test_test_DOCSTR},
#else
#  define TEST_TEST_GETSETDEF {"test", NULL, (setter)Test_test_set, NULL},
#endif
```

There's two bugs here:

- The setter uses the wrong name for the `HAS_DOCSTR` part; it uses `TEST_TEST_HAS_DOCSTR` while `Test_test_HAS_DOCSTR`, so the resulting docstring ends up being redefined to NULL.
- Even with that fixed, the docstring macro would get redefined anyway.

The simplest fix is to just drop the `HAS_DOCSTR` entirely, and just check whether the actual `DOCSTR` macro is defined or not, and then set it to `NULL` in that case (thanks @erlend-aasland for this suggestion).

I've created GH-127310 as a fix.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-127310
* gh-127431

### PR DESCRIPTION
**Pull request by ZeroIntensity**
Finally got enough connection to submit a PR :smile:

Co-authored-by: Erlend E. Aasland <erlend.aasland@protonmail.com>

* Issue: gh-127341

### CODE REVIEW

**Comment by skirpichev** [comment]
It seems you forgot ``make clinic``, or it was intentional, to reduce patch size?  Change looks fine.

**Comment by ZeroIntensity** [comment]
> It seems you forgot `make clinic`, or it was intentional, to reduce patch size? Change looks fine.

Yeah, that would be it. Fixed!

**Comment by erlend-aasland** [comment]
I don't like the original approach that was taken when the `GETSET_` clinic templates were added. How about we simplify it to this:

```diff
diff --git a/Tools/clinic/libclinic/parse_args.py b/Tools/clinic/libclinic/parse_args.py
index fc2d9fe9870..a57d729bec5 100644
--- a/Tools/clinic/libclinic/parse_args.py
+++ b/Tools/clinic/libclinic/parse_args.py
@@ -146,7 +146,7 @@ def declare_parser(
 GETSET_DOCSTRING_PROTOTYPE_STRVAR: Final[str] = libclinic.normalize_snippet("""
     PyDoc_STRVAR({getset_basename}__doc__,
     {docstring});
-    #define {getset_basename}_HAS_DOCSTR
+    #define {getset_basename}_DOCSTR {getset_basename}__doc__
 """)
 IMPL_DEFINITION_PROTOTYPE: Final[str] = libclinic.normalize_snippet("""
     static {impl_return_type}
@@ -157,9 +157,7 @@ def declare_parser(
         {{"{name}", {methoddef_cast}{c_basename}{methoddef_cast_end}, {methoddef_flags}, {c_basename}__doc__}},
 """)
 GETTERDEF_PROTOTYPE_DEFINE: Final[str] = libclinic.normalize_snippet(r"""
-    #if defined({getset_basename}_HAS_DOCSTR)
-    #  define {getset_basename}_DOCSTR {getset_basename}__doc__
-    #else
+    #if !defined({getset_basename}_DOCSTR)
     #  define {getset_basename}_DOCSTR NULL
     #endif
     #if defined({getset_name}_GETSETDEF)
@@ -170,9 +168,7 @@ def declare_parser(
     #endif
 """)
 SETTERDEF_PROTOTYPE_DEFINE: Final[str] = libclinic.normalize_snippet(r"""
-    #if defined({getset_name}_HAS_DOCSTR)
-    #  define {getset_basename}_DOCSTR {getset_basename}__doc__
-    #else
+    #if !defined({getset_basename}_DOCSTR)
     #  define {getset_basename}_DOCSTR NULL
     #endif
     #if defined({getset_name}_GETSETDEF)
```

**Comment by erlend-aasland** [comment]
BTW, I think we should record why this was a bug in an issue, and then link this PR to that issue.

**Review by skirpichev — APPROVED** [review]

**Review by erlend-aasland — APPROVED** [review]
Thanks for identifying and fixing this!

**Comment by ZeroIntensity** [comment]
I'll deal with backporting.

**Pull request merged**
