### PR TITLE
[3.6] bpo-29532: Altering a kwarg dictionary passed to functools.partial() no longer affects a partial object after creation.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**

### CODE REVIEW

**Comment by mdickinson** [comment]
There's something odd going on here: the diff shown by GitHub looks unrelated to [bpo-29532](https://bugs.python.org/issue29532), and instead looks related to [bpo-29602](https://bugs.python.org/issue29602).

**Comment by methane** [comment]
@serhiy-storchaka This pull request seems broken.
Would you close this PR and create new one?  Right step to cherry pick may be like this:

```
# Assuming upstream is python/cpython and origin is fork
git fetch --prune upstream
git checkout -b bpo29532-py36 upstream/3.6
git cherry-pick 29532
git push origin bpo29532
```

**Comment by serhiy-storchaka** [comment]
Sorry. Thank you @methane, I'll try to use your commands.

**Comment by berkerpeksag** [comment]
Using `git cherry-pick -x` would even be better.

**Pull request closed without merging**
