### PR TITLE
bpo-45900: Add limited type annotations to ipaddress module

### PR DESCRIPTION
**Pull request by wrgeorge1983**
https://bugs.python.org/issue45900

https://bugs.python.org/issue45900

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@wrgeorge1983

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by asvetlov** [comment]
Typing for stdlib is provided by https://github.com/python/typeshed
CPython policy discourages embedded typing declarations.

**Comment by asvetlov** [comment]
Thanks for the PR anyway!

**Comment by AlexWaygood** [comment]
Just to further what @asvetlov  said — IDEs and linters nearly all use the stubs in typeshed for typechecking, so that's the place where PRs relating to type hints should go. The stub for the `ipaddress` module is [here](https://github.com/python/typeshed/blob/master/stdlib/ipaddress.pyi), and (from my experience), typeshed is very open to PRs if you think the stubs can be improved in any way 🙂

**Pull request closed without merging**
