### PR TITLE
bpo-40077: Convert mmap to use heap types

### PR DESCRIPTION
**Pull request by erlend-aasland**
@corona10 or @vstinner, would you mind reviewing this?

https://bugs.python.org/issue40077

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM! This change looks really clean and valid. But I would appreciate another review, just to double check if I missed something.

**Comment by vstinner** [comment]
cc @shihai1991

**Review by corona10 — APPROVED** [review]
lgtm to me also ;)

**Review by shihai1991 — APPROVED** [review]
Thanks for your PR. I have no other comments in here.

**Comment by erlend-aasland** [comment]
Thanks for reviewing, all of you! 🙏🏻

**Comment by vstinner** [comment]
One less static type! Thanks @erlend-aasland.

**Pull request merged**
