### PR TITLE
gh-117657: Fix data races report by TSAN unicode-hash

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-117657

### CODE REVIEW

**Comment by corona10** [comment]
@colesbury @mpage 
From my local clang-18 and GHA do not report race condition issues for unicode-hash, so IMO, we can remove the function from the list until it is detected in the future.

**Comment by colesbury** [comment]
I think there is still a data race, even if it's only reported occasionally. We read and write to `_PyUnicode_HASH(self)` without atomics -- I think we should use relaxed atomic load/stores.

https://github.com/python/cpython/blob/90ec19fd33e2452902b9788d4821f1fbf6542304/Objects/unicodeobject.c#L11391-L11396

**Comment by corona10** [comment]
> I think there is still a data race, even if it's only reported occasionally. We read and write to _PyUnicode_HASH(self) without atomics -- I think we should use relaxed atomic load/stores.

Thank you for the feedback, I will take a look.

**Review by colesbury — APPROVED** [review]
LGTM

**Pull request merged**
