### PR TITLE
bpo-35674: Expose posix_spawnp

### PR DESCRIPTION
**Pull request by saraharkam**
https://bugs.python.org/issue35674

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
Please do the following changes:

* Your change contains an obvious bug... you have to exchange the true/false blocks of:

```

    err_code = posix_spawn(&pid, path->narrow,
    if(use_posixspawnp){
                           file_actionsp, attrp, argvlist, envlist);
        err_code = posix_spawn(&pid, path->narrow,
                               file_actionsp, attrp, argvlist, envlist);
    }
    else {
        err_code = posix_spawnp(&pid, path->narrow,
                                file_actionsp, attrp, argvlist, envlist);
    }
```

* Include also Modules/clinic/posixmodule.c.h generated change in your PR: run "make "clinic".
* Replace true/false with 1/0 your posixmodule.c changes: we don't use stdbool.h in CPython code base and true/false caused me compilation error.
* Add the unit test that I wrote below, add it to TestPosixSpawn of Lib/test/test_posix.py:

```
     @support.skip_unless_symlink
    def test_posix_spawnp(self):
        # Use a symlink to create a program in its own temporary directory
        temp_dir = tempfile.mkdtemp()
        self.addCleanup(support.rmtree, temp_dir)

        program = 'posix_spawnp_test_program.exe'
        program_fullpath = os.path.join(temp_dir, program)
        os.symlink(sys.executable, program_fullpath)

        path = os.environ.get('PATH', '')
        path = os.pathsep.join((temp_dir, path))
        env = dict(os.environ, PATH=path)

        spawn_args = (program, '-I', '-S', '-c', 'pass')
        code = textwrap.dedent("""
            import os
            args = %a
            env = %a
            pid = os.posix_spawnp(args[0], args, env)
            pid2, status = os.waitpid(pid, 0)
            if pid2 != pid:
                raise Exception(f"pid {pid2} != {pid}")
            if status != 0:
                raise Exception(f"status = {status}")
        """ % (spawn_args, env))

        # Use a subprocess to test os.posix_spawnp() with a modified PATH
        # environment variable: posix_spawnp() uses the current environment
        # to locate the program, not its environment argument.
        args = ('-c', code)
        assert_python_ok(*args, PATH=path)
```

**Comment by vstinner** [comment]
Hi @saraharkam, @nanjekyejoannah assigned the issue to herself last Thursday (January 10): https://bugs.python.org/issue35674#msg333375

Would you be ok to let Joannah implement the feature? 

Note: I'm mentoring Joannah.

**Comment by vstinner** [comment]
I don't like to do that, but I close the issue because @nanjekyejoannah assigned the issue to her. She just wrote PR #11554.

@saraharkam: Don't hesitate to propose other PRs, I may have a look and welcome in Python!

**Comment by saraharkam** [comment]
Sorry :disappointed: 

I will search another issue that I can contribute.

**Comment by vstinner** [comment]
No need to be sorry. I am sorry of closing your PR. You can follow discussions PR #11554 and maybe help joannah.

**Pull request closed without merging**
