### PR TITLE
gh-120343: Fix column offsets of multiline tokens in tokenize

### PR DESCRIPTION
**Pull request by lysnikolaou**
* Issue: gh-120343

### CODE REVIEW

**Comment by pablogsal** [comment]
Hummm, seems that this doesn't work as we still have some broken tests :(

**Comment by lysnikolaou** [comment]
Oops. Fixed now.

**Review by pablogsal — APPROVED** [review]
LGTM! Thanks for the fix @lysnikolaou 

We want a NEWS entry probably, no?

**Comment by lysnikolaou** [comment]
The news entry in https://github.com/python/cpython/pull/120352 is probably good enough. What do you think?

**Comment by pablogsal** [comment]
> The news entry in #120352 is probably good enough. What do you think?

Agreed 👍

**Pull request merged**
