### PR TITLE
bpo-33346: Allow async comprehensions inside implicit async comprehensions.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue33346

### CODE REVIEW

**Review by gvanrossum — COMMENTED** [review]
Don't merge this yet. I think we need more discussion about the desired behavior. And we need docs to match.

**Comment by pablogsal** [comment]
Can we include this in beta1?

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
I have updated the PR to match the main branch and I am landing this as the discussion in bpo has been quiet for several years and everyone seems to be on the same page.

@serhiy-storchaka, Дякую за чудову роботу! :smiley:

**Comment by serhiy-storchaka** [comment]
Wow!

**Comment by iritkatriel** [comment]
I noticed that no tests fail if I comment out this line: 
https://github.com/python/cpython/blob/089835469d5efbea4793cd611b43cb8387f2e7e5/Python/compile.c#L5785
and I bisected it to this PR. 

(1) Does this make sense?
(2) Is there another tests that will show where this line is needed, or can we remove it?

**Comment by iritkatriel** [comment]
> I noticed that no tests fail if I comment out this line:
> 
> https://github.com/python/cpython/blob/089835469d5efbea4793cd611b43cb8387f2e7e5/Python/compile.c#L5785
> 
> 
> and I bisected it to this PR.
> (1) Does this make sense? (2) Is there another tests that will show where this line is needed, or can we remove it?

I think it's fine because this PR added in symtable.c code that propagates the value of ``ste_coroutine`` from a comprehension to the enclosing scope (unless it's a generator, which the compile.c code excludes as well). So this is now happening already during symtable construction (as it should be), and we don't need the assignment in the compiler anymore.

**Pull request merged**
