### PR TITLE
bpo-46005: add note about setuptools to Doc/extending/building.rst

### PR DESCRIPTION
**Pull request by sobolevn**
https://bugs.python.org/issue46005

### CODE REVIEW

**Review by merwok — COMMENTED** [review]
LGTM, but I would remove the news snippet.  It will not really provide value when collected in a NEWS document (unless I’ve missed recent conventions, NEWS does not duplicate the full git changelog).

**Review by merwok — APPROVED** [review]

**Comment by merwok** [comment]
Wasn’t there a python.github.io site configured to show docs built from pull requests?

**Comment by AlexWaygood** [comment]
> Wasn’t there a python.github.io site configured to show docs built from pull requests?

The artifact is [uploaded here](https://github.com/python/cpython/actions/runs/1646966435) 🙂

**Comment by AlexWaygood** [comment]
BTW, @merwok, should this be backported to 3.9? I think `distutils` was only deprecated in 3.10.

**Comment by merwok** [comment]
Yes, that’s the artifact, it needs to be downloaded and extracted.  I was referring to a website that’s easier to look at 🙂 

I checked the 3.9 branch and the _setuptools_disclaimer.rst is there, so we can backport.
The formal deprecation may be in 3.10, but the package was minimally maintained before and setuptools was recommended.

**Comment by AlexWaygood** [comment]
> Yes, that’s the artifact, it needs to be downloaded and extracted. I was referring to a website that’s easier to look at 🙂

I don't know of such a website (but then, I'm fairly new to CPython! If there is one, I'd be very interested to know about it...)

Having downloaded and extracted it myself, this is what it looks like, anyhow!
image

**Comment by sobolevn** [comment]
@AlexWaygood probably @merwok is asking about https://github.com/python/cpython/pull/30272 and https://github.com/python/cpython/pull/19025

Right now the automation does not work 😞

**Review by merwok — APPROVED** [review]

**Comment by taleinat** [comment]
Thanks for the PR, @sobolevn!

I'm not sold on this change though. I'm marking this PR as "do not merge" for now, until the discussion on the b.p.o. issue reaches a conclusion.

**Comment by AA-Turner** [comment]
Trigger CLA

**Comment by sobolevn** [comment]
I am closing this PR, because `distutils` module was completely removed.
There will be major changes to its documentation.

**Pull request closed without merging**
