### PR TITLE
bpo-32098: Fix hardcoded value in test_os.py

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue32098

### CODE REVIEW

**Comment by merwok** [comment]
I think this PR has the wrong bug number.

**Comment by pablogsal** [comment]
Indeed, the correct one is 32098. My bad.

**Comment by pablogsal** [comment]
@merwok Thanks for the catch!

**Comment by vstinner** [comment]
Thank you for your contribution ;-)

**Comment by vstinner** [comment]
Oops, I missed the fact that the bpo number was missing in the commit message. It's still surprised that the Pull Request title and descript are different than the "generated" commit message when I press [Merge]. Sometimes I forget to check, like for this PR. It doesn't matter, it's a trivial fix.

**Pull request merged**
