### PR TITLE
gh-94673: Ensure subtypes are readied only once in math.trunc()

### PR DESCRIPTION
**Pull request by neonene**
Fixes a typo in d2e2e53f733f8c8098035bbbc452bd1892796cb3.
cc: @ericsnowcurrently

* Issue: gh-94673

### CODE REVIEW

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

(good catch!)

**Comment by ericsnowcurrently** [comment]
Hmm, I have a guess.  That code was added in 2007 (commit 15d3d045) as a builtin (bltinsmodule.c).  In 2008 the function was moved to the math module.  So that's probably the difference.

**Comment by mdickinson** [comment]
@ericsnowcurrently Nice find; that would make sense. (Well, maybe; I still can't quite figure out why the `PyType_Ready` would have been necessary, but it's a little more plausible that built-in functions could be being executed before some types are fully initialised.)

Do you see any reason not to just get rid of this code in `mathmodule.c`?

**Comment by ericsnowcurrently** [comment]
I suspect that code is an artifact of a time when folks were inconsistent about calling `PyType_Ready()`.  However, I'm not sure what the actual status quo is at this point.  This might be a good thing to ask about on python-dev.

**Pull request merged**
