### PR TITLE
bpo-38205: Py_UNREACHABLE() calls Py_FatalError()

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue38205

### CODE REVIEW

**Comment by vstinner** [comment]
Example from:
https://github.com/python/cpython/pull/16280#issuecomment-533049748

```
vstinner@apu$ ./python bug.py
Fatal Python error: We've reached an unreachable state. Anything is possible.
The limits were in our heads all along. Follow your dreams.
https://xkcd.com/2200
Python runtime state: initialized

Current thread 0x00007f5dc4f6d740 (most recent call first):
  File "/home/vstinner/python/master/bug.py", line 8 in func
  File "/home/vstinner/python/master/bug.py", line 11 in main
  File "/home/vstinner/python/master/bug.py", line 13 in <module>
Aborted (core dumped)
```

With RANDALL_WAS_HERE macro defined:

```
$ ./python bug.py
Fatal Python error: If you're seeing this, the code is in what I thought was
an unreachable state.

I could give you advice for what to do, but honestly, why
should you trust me?  I clearly screwed this up.  I'm writing
a message that should never appear, yet I know it will
probably appear someday.

On a deep level, I know I'm not up to this task.
I'm so sorry.
https://xkcd.com/2200
Python runtime state: initialized

Current thread 0x00007f7a71348740 (most recent call first):
  File "/home/vstinner/python/master/bug.py", line 8 in func
  File "/home/vstinner/python/master/bug.py", line 11 in main
  File "/home/vstinner/python/master/bug.py", line 13 in <module>
Aborted (core dumped)
```

**Review by zware — APPROVED** [review]

**Comment by vstinner** [comment]
I will wait for @serhiy-storchaka approval, since he was the one to disagree with my first attempt:
https://bugs.python.org/issue38205#msg352782

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thank you.

**Review by gpshead — APPROVED** [review]

**Comment by animalize** [comment]
The code generated by PR will push the string OFFSET at the call sites.
If you have performance cleanliness, you can use a macro points to a non-inline function.

**Comment by vstinner** [comment]
"The assembly code generated by this PR will push the string OFFSET at the call sites, the assembly code will longer a bit. If you care about this, you can use a macro points to a non-inline function."

**I** don't care about emitted machine code :-)

**Pull request merged**
