### PR TITLE
Minor tweaks to typing union objects doc

### PR DESCRIPTION
**Pull request by andresdelfino**
Automerge-Triggered-By: @merwok

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]
LGTM. I had originally used 'Union Object' but changed it to 'union object' to keep it consistent with `typing.Union`'s docs in #22517. Which I then proceeded to forget to apply in some places. Thanks for the catch!

**Comment by merwok** [comment]
does this need backports?

**Comment by Fidget-Spinner** [comment]
@merwok  No, the union object only exists in 3.10.

**Review by merwok — APPROVED** [review]

**Comment by merwok** [comment]
Thanks to you both!

**Pull request merged**
