### PR TITLE
bpo-29750: support non-ASCII passwords in smtplib

### PR DESCRIPTION
**Pull request by Windsooon**
issue: https://bugs.python.org/issue29750

I updated the PR based on the review from https://github.com/python/cpython/pull/8938

https://bugs.python.org/issue29750

### CODE REVIEW

**Comment by Windsooon** [comment]
Please review this PR when you have time @taleinat  :D

**Comment by ZackerySpytz** [comment]
You don't need to create a new PR in order to address review comments. Just update the original PR.

**Comment by Windsooon** [comment]
Hello, @ZackerySpytz , I use a wrong branch name at the very beginning then deleted it locally by mistake. That is why I use a new PR here.

**Comment by seblu** [comment]
Python 3.8.0 is still impacted by this.

Patched version 3.8.0 accept passwords with utf8 chars.

**Comment by Leon-001** [comment]
Hi,
I just wanted to give some motivation: I had a special character in my password and it took some time until I have figured out, what was going on. It would be great, if this patch could be reviewed!
Thank you all!

**Comment by max-toepfer** [comment]
Hello, lovely Python dev folks,
as another affected individual I wanted to ask, if this topic is still alive?
Thank you so much for the contributions!

**Comment by MaxwellDupre** [comment]
`Let smtplib support non-ASCII passwords`, better
`smtplib support for UTF-8 passwords`

**Review by Jourdelune — APPROVED** [review]

**Comment by arhadthedev** [comment]
Closing in favor of SASLprep-based gh-103611.

**Pull request closed without merging**
