### PR TITLE
bpo-46150: ensure `fakename` does not exist in `PosixPathTest.test_expanduser`

### PR DESCRIPTION
**Pull request by sobolevn**
https://bugs.python.org/issue46150

### CODE REVIEW

**Review by kumaraditya303 — APPROVED** [review]
LGTM

**Comment by sobolevn** [comment]
CC @twouters

**Comment by kumaraditya303** [comment]
https://github.com/python/cpython/pull/30244 is already merged and fixed this issue.

**Comment by gpshead** [comment]
never the less, i like yours better. :)  I didn't imagine anyone else would've run into this before so I didn't even search for a related issue or PR for my trivial "fix".

Plus someone pointed out that the number I added to the name in my merged PR can be interpreted poorly... I'll go with this one.

**Review by gpshead — APPROVED** [review]

**Pull request merged**
