### PR TITLE
Use f-strings in asyncio-task code examples

### PR DESCRIPTION
**Pull request by Mariatta**
Replace str.format with f-strings in the code examples of asyncio-task documentation.

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Does this make the code simpler?

I would rather replace
```python
print('The coroutine raised an exception: {!r}'.format(exc))
```
with
```python
print('The coroutine raised an exception:', repr(exc))
```

**Comment by serhiy-storchaka** [comment]
Does this make the code simpler?

I would rather replace
```python
print('The coroutine raised an exception: {!r}'.format(exc))
```
with
```python
print('The coroutine raised an exception:', repr(exc))
```

**Review by asvetlov — APPROVED** [review]
Let's use f-strings for sake of uniformness.

**Comment by vstinner** [comment]
> Does this make the code simpler?

IMHO the change makes the code easier to read (str.format => f-string).

About f-string vs str % args... Well, that's a matter of taste. I'm not sure that there is a strong argument for one style or the other. I tend to prefer f-string. IMHO it's simpler to read.

**Pull request merged**
