### PR TITLE
bpo-38021: Provide a PEP425 platform tag with sufficient detail for pypa packaging

### PR DESCRIPTION
**Pull request by aixtools**
https://bugs.python.org/issue38021

Think tools such as pypa/pip, pypa/wheel, and in the future pypa/packaging

### CODE REVIEW

**Comment by aixtools** [comment]
Another bit I am adding - so it is central, rather than being repeated in everything that needs it makes the following simple program possible.

from sysconfig import get_platform as get_platform

from _aix_support import aix_buildtag as get_btag

print("running:{!s}".format(get_platform()))
print("builtas:{!s}".format(get_btag()))

On system it was built on:

root@x066:[/data/prj/python/python3-3.9]./python ../git/aix_build_tag.py
running:AIX.6107.1415.32
builtas:AIX.6107.1415.32

On AIX 6.1 TL9 system

michael@x071:[/data/prj/python/python3-3.9]./python ../git/aix_build_tag.py
running:AIX.6109.1837.32
builtas:AIX.6107.1415.32

On AIX 7.1 TL4 system

root@x064:[/data/prj/python/python3-3.9]./python ../git/aix_build_tag.py
running:AIX.7104.1806.32
builtas:AIX.6107.1415.32

**Comment by aixtools** [comment]
https://bugs.python.org/issue38021  msg351332 for details on the last change

**Comment by terryjreedy** [comment]
Something is drastically wrong here.

**Comment by terryjreedy** [comment]
I am not sure what you did today or before, but this includes all idlelib changes since early September (about when this was opened).  Perhaps the root problem is that your aixtools/cpython fork master branch is also '3 months' out of date.
https://github.com/aixtools/cpython/branches
Your local and fork master should be kept up to date, as described in the devguide.

My suggestion: delete aixtools:bpo-38021-pep425 from your github fork, *but not locally*.  Update local master from python/cpython and push updated master to your fork. Checkout local aixtools:bpo-38021-pep425 branch (assuming that it was properly created from master).  Do an update merge: 'git merge origin/master.  Push the branch to your fork.  Hit the compare button to create a new PR.  *Stop and check the diff to make sure it only contains your changes or other changes that belong to the PR.*  Only make new PR if this is true.  If it contains extraneous diffs from already merged PR, figure out fix or ask on core-mentorship.

**Comment by aixtools** [comment]
I tried to rebase. Sigh.

**Pull request closed without merging**
