### PR TITLE
Feature: Added __len__ method to _BaseNetwork class in ipaddress module.

### PR DESCRIPTION
**Pull request by mfabryz**
This enables a call such as:

`In [41]: random.choice(ipaddress.ip_network("192.169.0.0/16"))                                                                              
Out[41]: IPv4Address('192.169.242.248')
`

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@mfabryz

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by csabella** [comment]
Hi @mfabryz, thank you for your interest in improving CPython.  Any feature request would require an issue to be opened on out bug tracker.  Please take a look at [this page from the devguide for more info](https://devguide.python.org/tracker/).  Thanks!

**Comment by csabella** [comment]
@mfabryz, please create an issue on the bug tracker for this.  Thank you.

**Comment by iritkatriel** [comment]
This PR add a new function without a new test.

**Comment by iritkatriel** [comment]
@mfabryz  I am closing this because you did not respond to the request to open a bpo issue for over a year. If you want to pursue this, please open one and explain why this enhancement is beneficial and safe (note that adding len can impact the truthiness of an object).

**Pull request closed without merging**
