### PR TITLE
bpo-39764: Make Task.get_stack accept ag_frame

### PR DESCRIPTION
**Pull request by lidizheng**
The title will be updated after the issue's creation.

https://bugs.python.org/issue39764

Automerge-Triggered-By: @asvetlov

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@lidizheng

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by lidizheng** [comment]
The test failure seems due to flake:

```
Timeout (0:20:00)!
Thread 0x00007f73c2100080 (most recent call first):
  File "/home/runner/work/cpython/cpython/Lib/tkinter/__init__.py", line 697 in wait_visibility
  File "/home/runner/work/cpython/cpython/Lib/tkinter/test/test_ttk/test_extensions.py", line 190 in test_resize
  File "/home/runner/work/cpython/cpython/Lib/unittest/case.py", line 616 in _callTestMethod
  File "/home/runner/work/cpython/cpython/Lib/unittest/case.py", line 659 in run
  File "/home/runner/work/cpython/cpython/Lib/unittest/case.py", line 719 in __call__
  File "/home/runner/work/cpython/cpython/Lib/unittest/suite.py", line 122 in run
  File "/home/runner/work/cpython/cpython/Lib/unittest/suite.py", line 84 in __call__
  File "/home/runner/work/cpython/cpython/Lib/unittest/suite.py", line 122 in run
  File "/home/runner/work/cpython/cpython/Lib/unittest/suite.py", line 84 in __call__
  File "/home/runner/work/cpython/cpython/Lib/unittest/runner.py", line 176 in run
  File "/home/runner/work/cpython/cpython/Lib/test/support/__init__.py", line 2079 in _run_suite
  File "/home/runner/work/cpython/cpython/Lib/test/support/__init__.py", line 2201 in run_unittest
  File "/home/runner/work/cpython/cpython/Lib/test/test_ttk_guionly.py", line 30 in test_main
  File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/runtest.py", line 234 in _runtest_inner2
File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/runtest.py", line 270 in _runtest_inner
  File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/runtest.py", line 140 in _runtest
  File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/runtest.py", line 193 in runtest
  File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/runtest_mp.py", line 80 in run_tests_worker
  File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/main.py", line 654 in _main
  File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/main.py", line 634 in main
  File "/home/runner/work/cpython/cpython/Lib/test/libregrtest/main.py", line 712 in main
  File "/home/runner/work/cpython/cpython/Lib/test/regrtest.py", line 43 in _main
  File "/home/runner/work/cpython/cpython/Lib/test/regrtest.py", line 47 in <module>
  File "/home/runner/work/cpython/cpython/Lib/runpy.py", line 86 in _run_code
  File "/home/runner/work/cpython/cpython/Lib/runpy.py", line 193 in _run_module_as_main

== Tests result: FAILURE ==

**Review by 1st1 — APPROVED** [review]

**Comment by 1st1** [comment]
I'll close/reopen the PR to rerun the CI

**Comment by 1st1** [comment]
Please add a NEWS entry with blurb and update what's new

**Comment by lidizheng** [comment]
@1st1 Thanks for the quick review. I have updated the blurb (first time using this tool).

**Review by asvetlov — APPROVED** [review]
lgtm

**Comment by lidizheng** [comment]
@asvetlov Is there any additional work I need to do to get this PR merged?

**Comment by asvetlov** [comment]
No, everything is perfect!
Merging.

**Pull request merged**
