### PR TITLE
gh-126742: avoid checking for library filename in `dlerror()` error messages

### PR DESCRIPTION
**Pull request by picnixz**
I will run this one with all buildbots.

* Issue: gh-126742

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
Do we need this check at all?

**Comment by picnixz** [comment]
> Do we need this check at all?

I wanted to at least check that the filename would be present but considering that the maintenance could be annoying, I'm ok with dropping it. Technically, catching the exception should be sufficient (namely, not catching UnicodeDecodeError) right?

**Review by vstinner — COMMENTED** [review]
I agree, just remove the filename check.

**Comment by serhiy-storchaka** [comment]
Agree.

**Review by serhiy-storchaka — APPROVED** [review]

**Review by vstinner — APPROVED** [review]

**Comment by vstinner** [comment]
Two buildbot workers failed:

> buildbot/ARM64 MacOS M1 NoGIL PR — Build done.
> buildbot/ARM64 MacOS M1 Refleaks NoGIL PR — Build done.

multiprocessing tests failed: it's unrelated.

**Pull request merged**
