### PR TITLE
bpo-43689: improve documentation for Differ

### PR DESCRIPTION
**Pull request by jugmac00**
Lines beginning with ``?`` try to help understanding the given diff.

The output can be hard to understand when it contains whitespace characters, such as spaces, tabs or line breaks.

While previously only tabs were mentioned, now all are listed.

https://bugs.python.org/issue43689

Automerge-Triggered-By: GH:rhettinger

### CODE REVIEW

**Review by obestwalter — APPROVED** [review]
Good clarification about what can hide above the question mark.

**Review by lastthyme — APPROVED** [review]

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
Closing and reopening to trigger the bots.

**Comment by jugmac00** [comment]
> Closing and reopening to trigger the bots.

I would have preferred "Merging and celebrating" though @rhettinger :-)

**Comment by jugmac00** [comment]
Thank you, @rhettinger 

Could you please close https://github.com/python/cpython/issues/87855 ? I created it over at bpo and cannot close it here (mannequin).

**Comment by slateny** [comment]
Closed, thanks for your contribution :+1:

**Pull request merged**
