### PR TITLE
gh-96696: Fix ResourceWarning in test.test_frame

### PR DESCRIPTION
**Pull request by sweeneyde**
* Issue: gh-96696

### CODE REVIEW

**Comment by sweeneyde** [comment]
I checked that this fails before 1b46d118e6e72daa64b98cafddb406c68b419efa and passes after.

**Comment by sweeneyde** [comment]
For example, https://buildbot.python.org/all/#/builders/474 is green for the first time in months.

**Comment by markshannon** [comment]
It was a bit tricky to get a test to fail on older versions.
Can you confirm that the test still fails prior to https://github.com/python/cpython/pull/95886? Thanks.

**Comment by sweeneyde** [comment]
Yep, this test case would fail before https://github.com/python/cpython/pull/95886:
```
PS C:\Users\sween\Source\Repos\cpython2\cpython> .\python.bat -m test test_frame
Running Debug|x64 interpreter...
0:00:00 Run tests sequentially
0:00:00 [1/1] test_frame
test test_frame failed -- Traceback (most recent call last):
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\test_frame.py", line 262, in test_issue95818
    assert_python_ok("-c", code)
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\support\script_helper.py", line 166, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\support\script_helper.py", line 151, in _assert_python
    res.fail(cmd_line)
  File "C:\Users\sween\Source\Repos\cpython2\cpython\Lib\test\support\script_helper.py", line 76, in fail
    raise AssertionError("Process return code is %d\n"
AssertionError: Process return code is 3
command line: ['C:\\Users\\sween\\Source\\Repos\\cpython2\\cpython\\PCbuild\\amd64\\python_d.exe', '-X', 'faulthandler', '-c', '\nimport gc\ngc.set_threshold(1,1,1)\nclass GCHello:\n    def __del__(self):\n        print("Destroyed from gc")\ndef gen():\n    yield\nfd = open(\'C:\\\\Users\\\\sween\\\\Source\\\\Repos\\\\cpython2\\\\cpython\\\\Lib\\\\test\\\\test_frame.py\')\nl = [fd, GCHello()]\nl.append(l)\ndel fd\ndel l\ngen()\n']

stdout:
---

---

stderr:
---
A s s e r t i o n   f a i l e d :   ! _ P y F r a m e _ I s I n c o m p l e t e ( f r a m e ) ,   f i l e   C : \ U s e r s \ s w e e n \ S o u r c e \ R e p o s \ c p y t h o n 2 \ c p y t h o n \ I n c l u d e \ i n t e r n a l \ p y c o r e _ f r a m e . h ,   l i n e   1 6 4
 Fatal Python error: Aborted

Current thread 0x00002384 (most recent call first):
  Garbage-collecting
  File "<string>", line 7 in gen
  File "<string>", line 14 in <module>
---

test_frame failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_frame

Total duration: 1.9 sec
Tests result: FAILURE
```

**Comment by markshannon** [comment]
Thanks for checking.

**Pull request merged**
