### PR TITLE
bpo-21302: Add nanosleep() implementation for time.sleep() in Unix

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue21302

### CODE REVIEW

**Comment by vstinner** [comment]
I created this PR based on @Livius90's PR #28526 to propose a "Refactor" commit.

**Comment by vstinner** [comment]
The PR #28526 LGTM, but I propose to write the `#ifdef` dance differently and rename `secs` to `timeout` to make the code more readable. So I created this PR based on PR #28526. For the main code in Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS, I merged the 3 code paths to put if `#ifdef` in the Py_BEGIN_ALLOW_THREADS block.

@Livius90: Is it better? What do you think?

**Comment by Livius90** [comment]
I can not say that the new Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS `#ifdef` section is better and more readable. I lost to see easily these have different `err` variables passing/checking. Any other new naming style is better, sure.

https://github.com/python/cpython/blob/d7a6cdd1711c5e55e81c37cf4acc173d9093d83e/Modules/timemodule.c#L2092

**Comment by vstinner** [comment]
> I lost to see easily these have different err variables passing/checking.

Ok, I moved err closer to the function call.

**Comment by Livius90** [comment]
I think, It is much better, thanks.

**Comment by vstinner** [comment]
Thanks @Livius90! I merged the PR based on your PR :-) I also updated the documentation.

**Pull request merged**
