### PR TITLE
gh-92906: Enable test_cppext on Windows

### PR DESCRIPTION
**Pull request by jkloth**
With source build virtual environments sorted out, this test also runs just fine on Windows.  Requires #92897.

Adding @vstinner due to recent work on this test.

### CODE REVIEW

**Comment by jkloth** [comment]
The Windows test failures are to be expected until #92897 is resolved.

**Comment by serhiy-storchaka** [comment]
There are merge conflicts now. It may be easier to recreate this change from scratch than try to resolve them.

**Comment by vstinner** [comment]
I tried to add the following code to setup.py, but setup.py stil fails to find `python313_d.lib`, it looks for `python313.lib` :-(

```py
    include_dirs = []
    library_dirs = []
    if support.MS_WINDOWS:
        # pyconfig.h is created in PCbuild\amd64\
        # python313.lib is created in  PCbuild\amd64\
        src_dir = dirname(dirname(dirname(os.getcwd())))
        build_dir = os.path.join(src_dir, 'PCbuild', 'amd64')
        include_dirs.append(build_dir)
        library_dirs.append(build_dir)
```

**Comment by vstinner** [comment]
I wrote a new PR from scratch: https://github.com/python/cpython/pull/117000

PR are now run on Windows, but only on release build.

**Pull request closed without merging**
