### PR TITLE
bpo-42064: Remove stale extern declarations in `sqlite3` headers

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue42064

### CODE REVIEW

**Review by corona10 — COMMENTED** [review]
IMHO, we may need to update `Tools/c-analyzer/cpython/ignored.tsv`

See: https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Tools/c-analyzer/cpython/ignored.tsv#L58

**Comment by erlend-aasland** [comment]
> IMHO, we may need to update `Tools/c-analyzer/cpython/ignored.tsv`
> 
> 
> 
> See: https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Tools/c-analyzer/cpython/ignored.tsv#L58

I didn't know about this; thanks for the heads up! I'll update the PR.

**Comment by erlend-aasland** [comment]
@corona10 I'll have an extra look at this later today; there's a lot more that can be removed from the c-analyzer ignore list.

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by erlend-aasland** [comment]
Thanks, @corona10 !

**Pull request merged**
