### PR TITLE
bpo-34461: Availability of parsers in etree initializer of xml package

### PR DESCRIPTION
**Pull request by nealpy**
Please refer to the PR - https://github.com/python/cpython/pull/8857

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by nealpy** [comment]
@Mariatta : Please check as i have opened the new PR as described in https://github.com/python/cpython/pull/8857

**Comment by scoder** [comment]
Please answer the question that I asked in the ticket.

**Comment by nealpy** [comment]
@scoder : Replied over the ticket - please check

**Comment by matrixise** [comment]
Hi @nealpy 

Thank you for your contributions but we need that you sign the CLA for your code. Please could you go to https://www.python.org/psf/contrib/contrib-form/ and sign the document?

Thank you,

**Comment by ned-deily** [comment]
Since there has been no consensus that this change is desirable, I'm closing the issue and the PRs.

**Pull request closed without merging**
