### PR TITLE
doc: PyUnicode_AsUTF8String() fails if string contains surrogates

### PR DESCRIPTION
**Pull request by vstinner**
----
📚 Documentation preview 📚: https://cpython-previews--124605.org.readthedocs.build/

### CODE REVIEW

**Comment by vstinner** [comment]
cc @pitrou @serhiy-storchaka 

I prefer to say "surrogate characters" rather than "lone surrogates", since surrogate pairs are also disallowed.

```
>>> "\uDC80".encode('utf8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 0: surrogates not allowed

>>> "\uDBFF\uDFFF".encode('utf8')
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed
```

**Comment by vstinner** [comment]
See related discussion: https://discuss.python.org/t/pep-756-c-api-add-pyunicode-export-and-pyunicode-import-c-functions/63891/43

**Review by serhiy-storchaka — COMMENTED** [review]
See the surrogatepass error handler documentation:
```rst
+===================+========================+===========================================+
|``'surrogatepass'``| utf-8, utf-16, utf-32, | Allow encoding and decoding surrogate code|
|                   | utf-16-be, utf-16-le,  | point (``U+D800`` - ``U+DFFF``) as normal |
|                   | utf-32-be, utf-32-le   | code point. Otherwise these codecs treat  |
|                   |                        | the presence of surrogate code point in   |
|                   |                        | :class:`str` as an error.                 |
+-------------------+------------------------+-------------------------------------------+
```
I suggest to use term "surrogate code points" and specify the range.

**Comment by vstinner** [comment]
> I suggest to use term "surrogate code points" and specify the range.

Done. Please review my updated PR.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Pull request merged**
