### PR TITLE
bpo-32413: Add documentation that at the module level, locals(), globals() are the  same dictionary

### PR DESCRIPTION
**Pull request by srinivasreddy**
https://bugs.python.org/issue32413

### CODE REVIEW

**Comment by srinivasreddy** [comment]
back port needed for 2.7, 3.4, 3.5, 3.6, 3.7

**Comment by srinivasreddy** [comment]
@rhettinger  Could you please take a look?

**Comment by srinivasreddy** [comment]
@merwok  Could you please review?

**Comment by srinivasreddy** [comment]
@methane  Could you please review?

**Comment by srinivasreddy** [comment]
@terryjreedy  Could you please take a look.

**Review by Carreau — APPROVED** [review]

**Comment by brettcannon** [comment]
Once CI clears this will get merged. Thanks everyone!

@srinivasreddy in the future, please refrain @ mentioning so many people to try and get a review. The appropriate way to request a review is to email python-dev if no one has reviewed your PR in a month.

**Review by brettcannon — APPROVED** [review]

**Pull request merged**
