### PR TITLE
bpo-31299: Implementation of ignore_modules argument for traceback functions

### PR DESCRIPTION
**Pull request by vaultah**
https://bugs.python.org/issue31299

### CODE REVIEW

**Comment by vaultah** [comment]
I noticed that `MiscTest.test_all` in _test_traceback.py_ can be implemented using the new `test.support.check__all__`. Would it be okay to change it in this pull request?

**Comment by mscuthbert** [comment]
should ignore_modules go after chain for backwards compatibility?  Possibly making it a keyword-only option?

**Comment by vaultah** [comment]
While placing optional boolean arguments after non-boolean ones feels more natural to me, I didn't think about backwards compatibility, so that was an oversight.

That being said, considering the current number of positional arguments that the `traceback` functions accept, I feel that users *should* pass optional arguments by their names anyway...  Addition of yet another optional argument to several `traceback` functions seems a good justification for breaking backwards compatibility and making the *majority* of optional arguments in that module keyword-only. What do you think?

**Comment by mscuthbert** [comment]
Yes I think that most of them should become keyword only would be the best, then order doesn't matter. 

(In the throes of porting some Python code to JavaScript and not having keyword arguments is killing me. :-) so anything to encourage them I like )

**Pull request closed without merging**
