### PR TITLE
gh-101879: docs - italicize argument in smtplib.SMPT() description

### LINKED ISSUE #101879: Documentation for smtplib Missing Italics
The input parameter `source_address` for `class smtplib.SMTP` is missing _italics_. I was scanning the text looking for the documentation for this input and couldn't find it because I am used to scanning for _italics_ according to the conventions of Python docs. Here is a highlight of the location of the parameter that needs italics.

https://docs.python.org/3/library/smtplib.html#smtplib.SMTP:~:text=raised.%20The%20optional-,source_address,-parameter%20allows%20binding

### Linked PRs
* gh-101886
* gh-103888

### PR DESCRIPTION
**Pull request by OTheDev**
Closes #101879 

* Issue: gh-101879

### CODE REVIEW

**Review by terryjreedy — CHANGES_REQUESTED** [review]
On line 28, 'host' and 'port' should also be italicized.

**Review by hugovk — APPROVED** [review]
Thanks.

I also removed the 3.10 backport label because it now only accepts security fixes.

**Review by hauntsaninja — APPROVED** [review]
Thank you!

**Comment by erlend-aasland** [comment]
AFAICS, @terryjreedy's remarks have been addressed.

**Review by erlend-aasland — APPROVED** [review]

**Pull request merged**
