### PR TITLE
bpo-35726: Add test for QueueHandler with multiple handlers

### PR DESCRIPTION
**Pull request by tirkarthi**
Add a test case for [bpo-35726](https://bugs.python.org/issue35726)

https://bugs.python.org/issue35726

### CODE REVIEW

**Comment by tirkarthi** [comment]
@vsajip @Zheaoli I have created a test based on my understanding of PR https://github.com/python/cpython/pull/11537 . Feedback welcome if there are any changes to be made.

**Review by eamanu — APPROVED** [review]
LGTM.

**Comment by Zheaoli** [comment]
@tirkarthi Nice job bro, It's seem good

**Comment by tirkarthi** [comment]
Ping @vsajip

**Pull request merged**
