### PR TITLE
gh-118613: Fix error handling of `_PyEval_GetFrameLocals` in `ceval.c`

### PR DESCRIPTION
**Pull request by sobolevn**
Refs https://github.com/python/cpython/pull/115153

* Issue: gh-118613

### CODE REVIEW

**Comment by gaogaotiantian** [comment]
While you are on this matter, could you change the `else if` part to an assertion? The locals should either be a `FrameLocalsProxy` or a mapping at least. Just remove the `else if` case and change that to an assertion. Then you can always return `locals` at the end of the function.

Otherwise, logically, you need to handle the else case which should not ever exist.

**Review by gaogaotiantian — APPROVED** [review]

**Review by gvanrossum — APPROVED** [review]
Good to go!

**Comment by sobolevn** [comment]
Since https://github.com/python/cpython/pull/115153 was not backported, I also don't backport.

Thanks everyone! 👍

**Comment by gaogaotiantian** [comment]
This piece of code has only been in main for like 2 days so there's no need to backport :)

**Pull request merged**
