### PR TITLE
gh-110543: Fix CodeType.replace in presence of comprehensions

### PR DESCRIPTION
**Pull request by JelleZijlstra**
* Issue: gh-110543

### CODE REVIEW

**Comment by CyberQin** [comment]
is it planned at 3.12.1?  the only problem for pyinstaller + scipy user

**Comment by JelleZijlstra** [comment]
I would like it to be but someone has to review it.

**Comment by carljm** [comment]
Thanks @JelleZijlstra! I am back from vacation and looking at this issue/PR.

**Comment by JelleZijlstra** [comment]
Thanks! This solution works but I'm not really happy with it; if you have a better idea, that'd be great.

**Comment by carljm** [comment]
I think the solution that would be most in-line with the current design of code objects would be to add a `co_fasthidden` accessor on code objects, and corresponding new argument to both `code_new` and `code_replace`. This is what I would have done in the first place, if I'd realized the issue with `code.replace()`.

I think this is better because it places full control into the hands of callers of `code.replace()` (and creators of new synthetic code objects), rather than implicitly tying `CO_FAST_HIDDEN` to `LOAD_FAST_AND_CLEAR` in the bytecode. This allows creation of broken code objects, of course, but there are already many ways to create broken code objects.

The main unpleasant consequence here would be the need to add a new `PyUnstable_Code_NewWithFastHidden` API (maybe technically we are allowed to modify the signature of an existing `PyUnstable_*`, but adding a new function seems much nicer than breaking users of the existing function, especially in a bugfix release).

But adding to the signature of `code_new` and `code_replace` in a bugfix release is not great either, since it means that users of those APIs who use the new argument would need to check for Python version >= 3.12.1.

So maybe we should take my suggested approach only for 3.13, and use your PR for 3.12? What do you think?

**Comment by JelleZijlstra** [comment]
That does seem like a better long-term solution, but I'm also hesitant to make that sort of change in the 3.12 branch at this point. So I agree with your suggestion to apply this PR's solution to 3.12 and add new arguments to the constructor for 3.13.

**Review by carljm — APPROVED** [review]
I think the most straightforward way to implement the plan discussed above is to go ahead and land this PR in main, backport it to 3.12, and then I will prepare a separate PR for main to switch to a new constructor/replace argument.

Thank you for putting together this fix!

**Pull request merged**
