### PR TITLE
bpo-12067: Add tests to test_compare

### PR DESCRIPTION
**Pull request by humbdrag**
Finishing up https://bugs.python.org/issue12067 (original PR - #3199) https://bugs.python.org/issue12067

https://bugs.python.org/issue12067

### CODE REVIEW

**Comment by humbdrag** [comment]
This is not visible to users so I think "skip news" is applicable to this.

**Comment by terryjreedy** [comment]
The changelog has a section Tests, so I see no reason to not mention extensive changes like this.

This seems nearly identical to #60625 and #30651 so the first should have been left open to get the revised CLA tag.  But we can go with this one.

**Comment by humbdrag** [comment]
> The changelog has a section Tests, so I see no reason to not mention extensive changes like this.
> 
> This seems nearly identical to #60625 and #30651 so the first should have been left open to get the revised CLA tag. But we can go with this one.

Thanks for the reply. Good point, added news file.

**Comment by humbdrag** [comment]
@terryjreedy Sorry for tagging but any further thoughts?

**Comment by terryjreedy** [comment]
This appears more or less identical to the original PR, #3199, with original attributions and merge conflicts removed.  Our workflow is to credit original authors and, when possible, to fix merge conflicts on the PR.   I did so fairly easily, leaving this as redundant.  If you have any comments or suggestions, please make them there.

**Pull request closed without merging**
