### PR TITLE
bpo-34690: DO NOT MERGE - Experimental "frozen modules".

### PR DESCRIPTION
**Pull request by larryhastings**
Published as a PR just to give people the Github review interface.  See [bpo-34690](https://www.bugs.python.org/issue34690).

https://bugs.python.org/issue34690

### CODE REVIEW

**Comment by gvanrossum** [comment]
Where's the code to generate frozenmodules.c?

I'd prefer the generated tables to be separated from the interesting (hand-written) code in frozenmodules.c -- GitHub flat-out refuses to display it, which makes reviewing the hand-written code there impossible.

PS. IIRC making this possible is the reason we made code objects immutable. Glad there's finally a practical use for that.

**Comment by larryhastings** [comment]
I've updated the PR to include the original tarball.  The code that generates frozenmodules.c is split across frozen_module.py and _serializer.c.  If we move forward with this approach, I think I'd want to rewrite the serializer in pure Python--I don't see the need to split the implementation across C and Python.

**Comment by brettcannon** [comment]
Removing the import team from reviewing as this is still a WIP. We can be added back when it's ready to go.

**Comment by erlend-aasland** [comment]
Closed, as this feature has been implemented by the Faster CPython team.

**Pull request closed without merging**
