### PR TITLE
bpo-89886: Clean up MACHDEP and _PYTHON_HOST_PLATFORM checks

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue45723

### CODE REVIEW

**Comment by erlend-aasland** [comment]
If the basic CI passes, I'll send it to the bots.

**Comment by tiran** [comment]
There is no CI for cross building yet.

**Comment by erlend-aasland** [comment]
> There is no CI for cross building yet.

Let's run it on the Emscripten container then; that's a cross-build, AFAIU.

**Comment by erlend-aasland** [comment]
Accidentally, I've got some ARM toolchains installed. I'll throw it at them and see how it fares.

**Comment by arhadthedev** [comment]
Just out of curiosity: what distributions still don't have Autoconf so we need pregenerated `configure` under version control? Won't it be better to let a user or a package manager to generate it on their system instead?

**Comment by tiran** [comment]
Package managers are not our concern. We keep configure and other scripts in git to lower the barrier for contributors.

Our ``configure.ac`` more than just autotools. It also requires automake, a recent version of autoconf-archive and pkg-config's M4 macros. Not every distro has a recent enough autoconf archive package. Some distros have the pkg-config M4 files in a separate package. Until a couple of weeks ago our ``configure.ac`` did not work with autoconf 2.71.

**Comment by arhadthedev** [comment]
Well, if this file cannot be removed because of specific requirements for its generation, maybe it can be marked as generated akin to outputs of Argument Clinic, Freeze, and Parser/asdl_c.py? It will allow GitHub to collapse it. By the way, I created #30031 to address this.

**Comment by erlend-aasland** [comment]
BTW, this is a case where the `configure` diff matters at little bit more than normal: we have no CI for changes like this, so being able to see that the refactored code actually produces the same result is crucial. Luckily, this diff is pretty short 🙂

**Comment by erlend-aasland** [comment]
> Accidentally, I've got some ARM toolchains installed. I'll throw it at them and see how it fares.

Works for me.

**Review by MaxwellDupre — APPROVED** [review]
From the number of tests passed on my machine (420) I would say this looks ok to me.
But I cant test for all the supported architectures.
Also, I saw 61 `fatal error` in the `config.log`.
Is this ok?
BTW how do you check the results on configure? A part from running full test suite and checking the log.

**Comment by erlend-aasland** [comment]
> From the number of tests passed on my machine (420) I would say this looks ok to me.
> But I cant test for all the supported architectures.
> Also, I saw 61 `fatal error` in the `config.log`.
> Is this ok?
> BTW how do you check the results on configure? A part from running full test suite and checking the log.

Hi, Maxwell, and thank you for your interest in making CPython better by reviewing pull requests :)

In order to be able to review this, you'll need to have a fairly good (IMO) understanding of how `autoconf` works. Based on your comment, I'd recommend you to check out the `autoconf` docs[^1], and also to run through some `autoconf` tutorials. That should help you understand how to interpret the contents of `config.log`, it should help you to decide which factors to apply when deciding if you should approve this PR or not, and it should help you answer your last question.

Personally, I'd say that this PR is pretty simple to review; there should be no changes to how `configure` works and the diff is pretty small. Reading through the generated code took me a couple of minutes (_most_ of the changes are just auto-formatting changes).

[^1]: https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.71/html_node/index.html

**Pull request closed without merging**
