### PR TITLE
bpo-33716: test_concurrent_futures: increase timeout

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue33716

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
The commit message can be enhanced:

* Try to write a shorter title (first line)
* I'm not sure that 5' unit is commonly known, I suggest to use the more common "5 min".

Example of commit message:

```
bpo-33716, test_concurrent_futures: increase timeout

Increase the timeout from 1 min to 5 min.

Replace also time.time() with time.monotonic() for timeouts.
```

You can use git push --force here to rewrite the commit message.

**Comment by pablogsal** [comment]
@vstinner Thanks! I was under the assumption that all the commits will be squashed when the PR is merged and the final merged commit message will be rewritten there. 

I have made the requested changes; please review again

**Review by vstinner — DISMISSED** [review]
LGTM.

"bpo-33716: test_concurrent_futures: increase timeout"

nitpick: I use "bpo-33716, test_concurrent_futures: increase timeout" (comma, not colon), but it's really up to you. There is no written guidelines for commit messages.

**Comment by vstinner** [comment]
@pitrou: I proposed to increase the timeout from 1 min to 5 min to repair buildbots, but does the check still make sense with a maximum duration of 5 minutes? https://bugs.python.org/issue33716#msg320126

**Comment by vstinner** [comment]
@pablogsal: I added the "skip news" label. I don't think that a NEWS entry is needed for such simple test change. I only add a NEWS entry for major changes in tests.

**Review by vstinner — APPROVED** [review]
LGTM.

@pitrou wrote that he doesn't recall why I added the sanity test with a limit of 60 seconds  and that "It's probably ok to increase the timeout, though.".

**Pull request merged**
