### PR TITLE
gh-106774: Update bundled pip version to 23.2.1

### LINKED ISSUE #106774: Upgrade the bundled version of pip to 23.2.1
# Feature or enhancement

This is the latest pip release.

# Pitch

This ensures that users who install newest release of Python get the newest version of pip.

### Linked PRs
* gh-106775
* gh-107222
* gh-107223

### PR DESCRIPTION
**Pull request by pfmoore**
closes: #106774
xref: https://github.com/pypa/pip/pull/12145

* Issue: gh-106774

### CODE REVIEW

**Comment by pfmoore** [comment]
@Yhg1s This is the regular update of the bundled pip. Assuming there are no issues with the release, I expect to backport it to 3.12 - can I confirm you don't have any objections to this? If we do have issues with the release, we'll follow up with a bugfix release, which I will also backport. I will ensure that any bugfixing is completed before 31st July, so we don't have any outstanding problems when RC1 is cut. Is this acceptable to you?

**Comment by Yhg1s** [comment]
Yes, if this can get into RC1, that's acceptable.

**Comment by pfmoore** [comment]
@Yhg1s This is ready to merge now - we've released pip 23.2.1 with a single fix for an issue that was identified, and I've updated the PR to include that.

If you can approve (subject to the tests passing, and me not getting any more "this branch is out of date with main" errors!) I'll merge and do the backports to 3.12 and 3.11.

**Comment by pfmoore** [comment]
OK, merging this on the assumption that the comment above from @Yhg1s counts as sufficient approval.

**Pull request merged**
