### PR TITLE
gh-65169: Clarify prog behavior in argparse

### PR DESCRIPTION
**Pull request by slateny**
For the latter part of the PR, my understanding is that we have this originally:

```
... match how the program was invoked on the command line
```

which implies that if the program is called like

```
./some-dir/run.py
```

then the help message will match it, but that's inaccurate. And while symlinks were mentioned in the bpo I'm not too sure how the original would read wrong, but nonetheless the suggested rewording fits well to me so I've used it with some very minor changes.

Co-authored-by: Kinga Farkas

https://bugs.python.org/issue20970

* Issue: gh-65169

### CODE REVIEW

**Review by DanielNoord — CHANGES_REQUESTED** [review]
We should probably add the co-author in the commit message so they actually get credited for it.

Also, we can now link to the github issue so it gets closed when this gets merged.

**Comment by slateny** [comment]
I believe that on merge, Github will automatically pull the co-author from the description so no need to put it in the commit message. Good point on the gh issue, I'll change them over for convenience.

**Comment by mehrdadmoradii** [comment]
@DanielNoord I have created a new PR #96983. I also mentioned both @slateny and @lilbludot on that.

**Comment by slateny** [comment]
What's the reason for making a new PR?

**Comment by slateny** [comment]
@asvetlov It looks like the section being updated here was written by you some 10 years ago, could you take a peek at it?

**Review by savannahostrowski — APPROVED** [review]
It looks like this may have gotten lost in the fold but after reading through the issue thread, this looks good to me.

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
