### PR TITLE
gh-106446: Fix failed doctest in stdtypes

### PR DESCRIPTION
**Pull request by CharlieZhao95**
Fix failed doctest in stdtypes.

* Issue: gh-106446

----
:books: Documentation preview :books:: https://cpython-previews--106447.org.readthedocs.build/

### CODE REVIEW

**Review by terryjreedy — CHANGES_REQUESTED** [review]
More of the doctests definitely need changes, regardless of CI issues.  See issue comment.

**Comment by CharlieZhao95** [comment]
> More of the doctests definitely need changes, regardless of CI issues. See issue comment.

Should I put all fixes in one PR? These changes may need to be backported to different Python versions :)

**Comment by terryjreedy** [comment]
That is why I checked the output back to 3.11.  I believe everything was same back to 3.11.  So 'yes'.

**Review by terryjreedy — APPROVED** [review]
Thank you for the additions.  They look good.  I am not going to touch the address issue now.  
I added "Note that all byte lengths may depend on the operating system." so that readers will not be puzzled if they run those examples, or doctest them, on Windows.  I am ready to merge once you approve the new sentence.

**Comment by CharlieZhao95** [comment]
Should I backport this to 3.11 manually?

**Pull request merged**
