### PR TITLE
gh-104773: PEP 594: Remove the pipes module

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-104773

----
:books: Documentation preview :books:: https://cpython-previews--104848.org.readthedocs.build/

### CODE REVIEW

**Comment by hugovk** [comment]
The doctest failure is unrelated, here's a PR to fix it: https://github.com/python/cpython/pull/104852

**Review by hugovk — APPROVED** [review]

**Comment by vstinner** [comment]
@AlexWaygood: Why did you merged the branch 'main' into remove_pipes? I created this PR 49 minutes ago. Do you expect regressions since main changed in the meanwhile? I was awaiting CI tests to complete, and with this merge I have to wait 30 minutes again :-(

**Comment by hugovk** [comment]
I expect it's to include the doctest fix https://github.com/python/cpython/pull/104852 from `main`, so we can get a nice clean (green) slate here.

**Comment by hugovk** [comment]
By the way, we've now made available GitHub's "Enable auto-merge" feature for this repo, so this could be a good opportunity to give it a spin:

https://devguide.python.org/getting-started/git-boot-camp/#accepting-and-merging-a-pull-request

**Comment by vstinner** [comment]
> The doctest CI check was failing on this PR

Oh, I didn't see. In that case, thank you :-) I was just surprised to see a merge without any explanation.

**Comment by AlexWaygood** [comment]
> I was just surprised to see a merge without any explanation.

Apologies — I'll explain my actions next time 😄

**Pull request merged**
