### PR TITLE
[3.8] Update interpreter.rst (GH-17059)

### PR DESCRIPTION
**Pull request by Seluj78**
Fixed what seemed to be a weird phrasing..
(cherry picked from commit 5e01a6542a1beb552a17e16b71dc0ba9fc6adcfb)

Co-authored-by: Jules Lasne (jlasne) <jules.lasne@gmail.com>

### CODE REVIEW

**Comment by Seluj78** [comment]
This is a backport of #17059 for 3.8. I had to move around the lines to respect the 80 chars per line but I am unsure if that was necessary

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
@Seluj78 sadly the backport to 3.7 failed again :-(

**Comment by Seluj78** [comment]
Done for the 3.7 backport

**Pull request merged**
