### PR TITLE
bpo-40882: Fix a memory leak in SharedMemory on Windows

### PR DESCRIPTION
**Pull request by ZackerySpytz**
In multiprocessing.shared_memory.SharedMemory(), the temporary view
returned by MapViewOfFile() should be unmapped when it is no longer
needed.

https://bugs.python.org/issue40882

### CODE REVIEW

**Review by zooba — APPROVED** [review]

**Comment by csabella** [comment]
@zooba, should this be merged?  Thanks!

**Comment by iritkatriel** [comment]
@ZackerySpytz This has merge conflicts now.

**Comment by kumaraditya303** [comment]
I fixed the merge conflicts.

**Comment by zooba** [comment]
Any volunteers to do the backport? I've got too many other things checked out right now to do it

**Comment by lukegarland** [comment]
Here it is for Python 3.10 https://github.com/python/cpython/pull/99911

**Comment by lukegarland** [comment]
Backport for 3.11 is here: https://github.com/python/cpython/pull/99973

**Pull request merged**
