### PR TITLE
gh-93963: Remove deprecated names from importlib.abc.

### LINKED ISSUE #93963: Officially deprecate and remove abcs in importlib.abc moved to importlib.resources.
In #90276, I grouped the functionality related to `importlib.resources` into its own package (creating clearer separation of responsibility from `importlib.*`). That included moving some abstract base classes from `importlib.abc` to `importlib.resources.abc`. We need to officially deprecate the presence in `importlib.abc` and then remove them in a future release.

- [x] deprecation: https://github.com/python/cpython/pull/93965
- [x] documentation: #94546 
- [x] cleanup: #95217, #96598
- [ ] ~removal: https://github.com/python/cpython/pull/94528~
- [x] removal: https://github.com/python/cpython/pull/119720

_Originally posted by @jaraco in https://github.com/python/cpython/issues/93610#issuecomment-1157848163_

### Linked PRs
* gh-119720

### PR DESCRIPTION
**Pull request by jaraco**
- gh-93963: Remove deprecated names from importlib.abc

### CODE REVIEW

**Comment by jaraco** [comment]
I see now in 691a82a, Github did the wrong thing. Apparently, because this repo uses squash merge, thereby rewriting history, Git can't tell that the lines removed in 96f14c2f3d3fe9fcd063c8075cdfb2bbd58d855a were to be removed, and instead of complaining that there's a conflict, it just undid that change.

**Comment by jaraco** [comment]
I've filed [a Github support ticket](https://support.github.com/ticket/personal/0/1717562) to report the issue to Github and get their opinion on it. In the meantime, 17f614e should work around the issue.

**Comment by warsaw** [comment]
> I've filed [a Github support ticket](https://support.github.com/ticket/personal/0/1717562)

Looks like probably only you @jaraco can see that ticket.

**Comment by warsaw** [comment]
@jaraco I'm trying to reboot myself on this discussion.  @jaraco was the deprecation of access to these ABCs ever documented as deprecated in the library docs?  I can't find that.  That's not to say that it should hold up removal of these, since the deprecation warnings happened in the code.  If we go ahead and remove the b/c hack now, I do think that any documentation update to `importlib.resources.abc` should explicitly mention the deprecation and removal history of access through `importlib.abc`.

**Comment by jaraco** [comment]
> Looks like probably only you @jaraco can see that ticket.

Yeah, that's true. That's how Github does thinks. I linked it here to be transparent about what I'm doing and to associate a reference. Still no response, BTW.

> was the deprecation of access to these ABCs ever documented as deprecated in the library docs? 

I did not previously include that effort as part of this change because Hugo and others were working on docs updates. The deprecations were subsequently documented in https://github.com/python/cpython/pull/94546.

**Comment by CAM-Gerlach** [comment]
Just FYI, following what was discussed in python/core-workflow#475 , this is the only personal feature branch remaining on the upstream `cpython` repo, which blocks the full implementation of the branch protection rule approved in python/steering-council#144 that would avoid the issue where it is easy to push personal feature branches to the upstream by accident, either through the Git CLI or via GitHub's web Edit feature.

**Comment by jaraco** [comment]
Let's close this and delete the branch and hope someone can find the changes when the time comes to submit it.

**Comment by hugovk** [comment]
Re-done as https://github.com/python/cpython/pull/119720.

**Pull request closed without merging**
