### PR TITLE
Fix bpo-36041: fix folding of quoted string in display_name violates RFC

### PR DESCRIPTION
**Pull request by ghost**
Fix bug 36041: don't unquote quoted strings during email header folding

The refolding process is unable to determine if it is folding an unstructured header (where unquoting and
unescaping the string would be allowed) or a structured header where the quotes are required. Therefore, do the safe thing and keep the quotes and escapes.

https://bugs.python.org/issue36041

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by nanjekyejoannah** [comment]
@SwampWalker put "Fix bug 36041: don't unquote quoted strings during email header folding" in the PR title.

**Comment by bitdancer** [comment]
I haven't tested it, but it seems to me the problem with this is that if you have something like `"this is an example of a very long quoted string" <foo@example.com>`, then what you will get is `"this" "is" "an"....` which isn't what we want.  I think you almost have to implement something like the EW algorithm, where you try to glue back together adjacent quoted strings.  It's been long enough since I wrote this code that I'm not sure I'm correct, though :)  And like I said I didn't actually test your fix to see what happens in this case, at least not yet.

**Comment by SwampWalker** [comment]
I was just following the instructions in the PR prefill [nanjekyejoannah](/nanjekyejoannah), you might want to see those instructions updated. I've updated the title.

**Comment by SwampWalker** [comment]
Bitdancer, you have misunderstood what the fix does. It does not quote the children, it adds a DQUOTE terminal as the first and last child and escapes the intermediate children. The test I added shows that each individual child is not separately quoted. I had considered refactoring the quote_string() function to extract a separate escape_string() function so I wouldn't have to call quote_string()[1:-1] with the followup slicing to remove the quotes. The reason I did not is because that escaping is somewhat specific to quoted strings and making a escape_string_for_quoted_string() method seemed to add more boilerplate than what I thought the function would deserve.

**Comment by bitdancer** [comment]
Ah, I see.  You are right, I did not spend enough time understanding the code (I was trying to give you quick feedback and obviously I was too quick :)

I will try to review this completely soon.

**Comment by mlda065** [comment]
Does this pull request also happen to fix [40359](https://bugs.python.org/issue40359?@ok_message=msg%20366966%20created%0Aissue%2040359%20message_count%2C%20messages%20edited%20ok&@template=item)? 

(Which is a ticket I created earlier today, about parsing long attachment file names.)

**Comment by wbolster** [comment]
> I will try to review this completely soon. but that sounds like the right solution.

@bitdancer is there any chance you can can be bothered do another review round on these changes? :upside_down_face: if so, that would be great! 🙏

**Pull request closed without merging**
