### PR TITLE
bpo-37681: no_sanitize_thread supported from gcc 5.1

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue37681

### CODE REVIEW

**Comment by shihai1991** [comment]
cc @izbyshev

**Comment by shihai1991** [comment]
@vstinner Looks Ronald too busy, bothering you again.

**Comment by ronaldoussoren** [comment]
The patch looks sane. My current plan is to spend tonight (CEST) on some CPython work including this PR.

**Comment by ronaldoussoren** [comment]
One thing you could do is create a news entry (see the "Details" link at the failing pre-merge checks).

**Comment by shihai1991** [comment]
> The patch looks sane. My current plan is to spend tonight (CEST) on some CPython work including this PR.

copy that. Thanks, guys:)

**Comment by vstinner** [comment]
@ronaldoussoren: "The patch looks sane. My current plan is to spend tonight (CEST) on some CPython work including this PR."

Oh sorry, I missed your comment and went ahead: I merged the PR.


@ronaldoussoren: "One thing you could do is create a news entry (see the "Details" link at the failing pre-merge checks)."

I consider that changes which only fix compiler warnings don't deserve a NEWS entry, so I added "skip news" label.

**Pull request merged**
