### PR TITLE
bpo-41119: Output correct error message for list/tuple followed by colon

### PR DESCRIPTION
**Pull request by lysnikolaou**
https://bugs.python.org/issue41119

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by pablogsal** [comment]
> Sorry, @lysnikolaou and @pablogsal, I could not cleanly backport this to `3.9` due to a conflict.

The era of automatic backports is over :(

**Comment by pablogsal** [comment]
@lysnikolaou Could you made the backport using `cherry_picker`?

**Comment by lysnikolaou** [comment]
> @lysnikolaou Could you make the backport using `cherry_picker`?

Yup, I'll do it a bit later today.

**Comment by lysnikolaou** [comment]
> > Sorry, @lysnikolaou and @pablogsal, I could not cleanly backport this to `3.9` due to a conflict.
> 
> The era of automatic backports is over :(

I guess that's because of the different filenames?

**Comment by pablogsal** [comment]
> I guess that's because of the different filenames?

Not really, my git was smart enough to do the remapping in previous backports

**Comment by lysnikolaou** [comment]
> > I guess that's because of the different filenames?
> 
> Not really, my git was smart enough to do the remapping in previous backports

Yes, but Parser/parser.c existed in previous versions as well, right?

**Comment by pablogsal** [comment]
> > > I guess that's because of the different filenames?
> > 
> > Not really, my git was smart enough to do the remapping in previous backports
> 
> Yes, but Parser/parser.c existed in previous versions as well, right? 

Yep, but git knows the story of that file, the same way it will do if you do `git log FILE --follow`: it will only show you the story of FILE across renames even if it substituted some other file that had the same name before (there is an heuristic that you can tune for when git thinks you delete + create Vs when it thinks you modified).

**Comment by lysnikolaou** [comment]
Oh okay, didn't know that.

**Pull request merged**
