### PR TITLE
gh-91869: Fix tracing of specialized instructions with extended args

### PR DESCRIPTION
**Pull request by sweeneyde**
https://github.com/python/cpython/issues/91869

### CODE REVIEW

**Comment by markshannon** [comment]
I'm worried about keeping the adaptive form of the `EXTENDED_ARG` and its following opcode in sync. Adding instrumentation is likely to make this even more complex.

I think we should go back to the old approach of simply not quickening any opcode that is preceded by an `EXTENDED_ARG`.

According to the [latest stats](https://github.com/faster-cpython/ideas/blob/main/stats.md), `EXTENDED_ARG` is only 0.4% of the opcodes executed and only a few of those are candidates for specialization.

The new test looks good.

**Comment by markshannon** [comment]
My concern was that we might optimize (or deoptimize) the `EXTENDED_ARG`, but not the following instruction (or vice versa).

But, from what you are saying that should be OK as `EXTENDED_ARG` is really the special form, only needed when tracing and `EXTENDED_ARG_QUICK` is the normal form. Is that correct?

Would it better to never quicken `EXTENDED_ARG`, but have the compiler emit `EXTENDED_ARG_QUICK` directly (so `EXTENDED_ARG` only exists for tracing).

**Comment by sweeneyde** [comment]
> My concern was that we might optimize (or deoptimize) the `EXTENDED_ARG`, but not the following instruction (or vice versa).
> 
> But, from what you are saying that should be OK as `EXTENDED_ARG` is really the special form, only needed when tracing and `EXTENDED_ARG_QUICK` is the normal form. Is that correct?

Yes, the current PR's `EXTENDED_ARG` primarily exists for tracing. It should always be safe to switch from `EXTENDED_ARG_QUICK` to `EXTENDED_ARG` because it's always safe (right?) to do as tracing does and execute `_PyOpcode_Deopt[opcode]` instead of `opcode`.

> Would it better to never quicken `EXTENDED_ARG`, but have the compiler emit `EXTENDED_ARG_QUICK` directly (so `EXTENDED_ARG` only exists for tracing).

That would make sense -- I'll see how hard it is to implement `EXTENDED_ARG/EXTENDED_ARG_FOR_TRACING` instead, such that `_PyOpcode_Deopt[EXTENDED_ARG] == EXTENDED_ARG_FOR_TRACING`.

**Comment by sweeneyde** [comment]
https://github.com/python/cpython/pull/91974 implements that idea. It slightly complicates the meaning of `_PyOpcode_Deopt[]` and which opcodes are included in `dis.opmap` and such, but it does make it so that `EXTENDED_ARG_TRACE` is only ever executed if tracing is happening.

I think I'd lean toward this PR (91945), but either is fine by me.

**Comment by markshannon** [comment]
You can leave `EXTENDED_ARG` and `EXTENDED_ARG_QUICK`; no need for `EXTENDED_ARG_FOR_TRACING` or to change `_PyOpcode_Deopt`

I tried removing the case for `EXTENDED_ARG` from `_PyCode_Quicken` and  emitting `EXTENDED_ARG_QUICK` instead of `EXTENDED_ARG` in `write_instr` and all the test pass.

**Comment by markshannon** [comment]
@sweeneyde Thanks for the fix.

**Pull request merged**
