### PR TITLE
bpo-26543: fix `imaplib.noop()` failing when debug > 3

### PR DESCRIPTION
**Pull request by ankostis**
+ Add a failing TC for the problem.

https://bugs.python.org/issue26543

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
Just to be explicit: this PR doesn't fix the bug, it just adds a test to trigger the bug:

vstinner@apu$ ./python -bb -m test test_imaplib -v -m '*noop*'

```
======================================================================
ERROR: test_noop_with_debug (test.test_imaplib.ThreadedNetworkedTestsSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vstinner/prog/python/master/Lib/test/support/__init__.py", line 2105, in decorator
    return func(*args)
  File "/home/vstinner/prog/python/master/Lib/test/test_imaplib.py", line 871, in test_noop_with_debug
    imap.noop()
  File "/home/vstinner/prog/python/master/Lib/imaplib.py", line 668, in noop
    return self._simple_command('NOOP')
  File "/home/vstinner/prog/python/master/Lib/imaplib.py", line 1191, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/home/vstinner/prog/python/master/Lib/imaplib.py", line 1022, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: NOOP command error: BAD [b'NOOP unknown']
```

**Comment by ankostis** [comment]
> Just to be explicit: this PR doesn't fix the bug,

Correct.

> Once you have made the requested changes, 

Will notify you when i do it - cut it would be next week the soonest since i'm on the road at the moment.

**Comment by CuriousLearner** [comment]
Hi @ankostis !

Do you have time to write a patch for this?

**Comment by ankostis** [comment]
I took some time and extracted here the patch i had used to make it work (in 2b99cec)

**Comment by CuriousLearner** [comment]
@ankostis 

Thank you for your work. I've tried to fix this in cases where a call to simple command is made, as well as when a call to `_dump_ur` is made.

But I have some more observations, and I'll wait for someone's input to gracefully handle the crash.

It is in PR #15206 . You may close this PR and let me know if you've any thoughts on the patch in the new PR.

Thanks again!

**Comment by ankostis** [comment]
Sorry, is don't have any time for feedback.
Thanks for telling over, I'm glad i help.

**Pull request closed without merging**
