### PR TITLE
Delete DOS-only PC/testpy.py

### PR DESCRIPTION
**Pull request by arhadthedev**
1. On Windows, `python PC\testpy.py` prints the following error:

    ```text
    Could not import the standard "symbol" module.  If this is
      a PC, you should add the dos_8x3 directory to your PYTHONPATH.
    ```

2. According to the script source code, it would then call `test.libregrtest.main`. However, we have a dedicated `python -m test` runner with lots of parameters for such a purpose.

### CODE REVIEW

**Comment by ambv** [comment]
arm and win32 report
```
D:\a\1\s\Modules\_hashopenssl.c(33,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory
```

which doesn't seem related but it would still be better to have everything green to check in a file deletion. Let me update the branch.

**Comment by zooba** [comment]
This is fine, but are there any other files to be removed from the PC directory? No point doing a single PR for each one if they're this uncontroversial.

**Comment by arhadthedev** [comment]
> are there any other files to be removed from the PC directory

There are files mentioned nowhere in python/cpython (`git grep filename.ext` gives empty output). However, I don't know which ones are high-quality sources, or used by outside scripts and release managers, and which ones are abandoned and can be removed.

- PC/classicAppCompat.can.xml
- PC/classicAppCompat.cat
- PC/icons/launcher.icns
- PC/icons/launcher.svg
- PC/icons/logo.svg
- PC/icons/py.icns
- PC/icons/pyc.icns
- PC/icons/pyc.svg
- PC/icons/pyd.icns
- PC/icons/pyd.svg
- PC/icons/python.icns
- PC/icons/python.svg
- PC/icons/pythonw.icns
- PC/icons/pythonw.svg
- PC/icons/setup.icns
- PC/icons/setup.svg
- PC/layout/support/appxmanifest.py
- PC/layout/support/catalog.py
- PC/layout/support/filesets.py
- PC/layout/support/nuspec.py
- PC/layout/support/props.py
- PC/store_info.txt

JFYI, the list is generated with `..\python.bat ..\find_unused.py > 1.txt` where find_unused.py is the following:

```py
from os.path import basename
from subprocess import run
from sys import stderr

lstree = ('git', 'ls-tree', '-r', '--name-only', 'HEAD')
lstree_result = run(lstree, capture_output=True, check=True, text=True)
tracked_files = lstree_result.stdout.splitlines()

for file_path in tracked_files:
    print(file_path, file=stderr)
    file_name = basename(file_path)
    grep_result = run(['git', 'grep', '-q', file_name, '--', ':/'])
    found_no_usage = grep_result.returncode != 0
    if found_no_usage:
        print(f'- {file_path}')

```

**Comment by arhadthedev** [comment]
@pablogsal Are `PC/icons/*.icns` and `PC/classicAppCompat.*` used to build Python 3.12 installers? If no, can they be safely deleted?

**Comment by zooba** [comment]
You need to fix that script, because those files are definitely used ;-)

The *.icns ones are the macOS versions of those icons, which we kept for the day that the icons are aligned between releases. They're probably genuinely not referenced anywhere.

All the rest are part of the PC/layout script, and are essential. So this tells me there's nothing left to clean up and I can merge this PR, thanks!

**Pull request merged**
