### PR TITLE
WIP: bpo-36347: Renaming the constants for the PyMemberDef.flags

### PR DESCRIPTION
**Pull request by matrixise**
* Declaration of new constants for the PyMemberDef.flags with an
enumeration and with the PY_ prefix (convention of the C-API for the
public names). The redeclaration is for the backward compatibility.
* Use __attribute__(deprecate) for the deprecation of the former
constants.
* Update the documentation about the new constants.

https://bugs.python.org/issue36347

### CODE REVIEW

**Comment by matrixise** [comment]
This PR is a WIP PR and it's used for the associated issue.

At this moment, there is some issues

- [ ] Add a blurb entry
- [ ] Fix the compilation step on AppVeyor for the Windows support
- [ ] Fix the warnings when compiling on Linux

**Review by jdemeyer — CHANGES_REQUESTED** [review]
The whole "restricted mode" thing is long obsolete and support has been removed in Python 3. So really, the flags related to restricted mode should just be deprecated *without* offering a replacement. And I would propose to remove all mentions of restricted mode from the docs.

**Comment by matrixise** [comment]
On 03/27, Jeroen Demeyer wrote:
>jdemeyer requested changes on this pull request.
>
>The whole "restricted mode" thing is long obsolete and support has been
>removed in Python 3. So really, the flags related to restricted mode
>should just be deprecated *without* offering a replacement. And I would
>propose to remove all mentions of restricted mode from the docs.

Hi Jeroen,

Sorry, I didn't see your previous email.

About this point, I have to send an email to python-dev@python.org and
ask for the next step for this issue.

Thank you for your suggestion.

Have a nice day

**Comment by jdemeyer** [comment]
See also #12684 for no longer using these constants in CPython internally. That PR should be completely uncontroversial.

**Comment by matrixise** [comment]
I close my PR.

**Pull request closed without merging**
