### PR TITLE
bpo-30764: Windows support.SuppressCrashReport

### PR DESCRIPTION
**Pull request by vstinner**
* Add Windows support to test.support.SuppressCrashReport: call
  SetErrorMode() and CrtSetReportMode().
* _testcapi: add CrtSetReportMode() and CrtSetReportFile() functions
  and CRT_xxx and CRTDBG_xxx constants needed by SuppressCrashReport.

### CODE REVIEW

**Comment by vstinner** [comment]
I tried to implement a pure ctypes version but failed: see http://bugs.python.org/issue30764#msg296965

IMHO this PR is more reliable.

**Comment by vstinner** [comment]
cc @eryksun

**Comment by vstinner** [comment]
This PR will allow to fix http://bugs.python.org/issue30705

**Comment by zooba** [comment]
Don't we already have these functions in `PC/msvcrtmodule.c`?

**Comment by vstinner** [comment]
> Don't we already have these functions in PC/msvcrtmodule.c?

None of the added functions or constants is already available in msvcrt. Otherwise, I would just use them ;-)

Reminder: Python 2.7 was released 7 years ago. A lot of things evolved in Python 3 in the meanwhile ;-)

**Pull request merged**
