### PR TITLE
bpo-37228: Add whatsnew for removal of loop.create_datagram_endpoint()'s *reuse_address* parameter

### PR DESCRIPTION
**Pull request by aeros**
https://bugs.python.org/issue37228

### CODE REVIEW

**Review by ned-deily — COMMENTED** [review]
LGTM, thanks!

**Comment by aeros** [comment]
@1st1 and/or @asvetlov, would you mind giving this a final look-over before we add these whatsnews entries? Since it's a backwards incompatible change to asyncio affecting multiple versions (for anyone passing `reuse_address=True` to `loop.create_datagram_endpoint()`), I want to make sure we communicate it as well as possible. 

Is the current iteration adequate or should it be more specific? My goal was to avoid adding too many details in the whatsnew entry and explain most of the details in the documentation.

**Comment by 1st1** [comment]
Thank you, Kyle! Apologies for the wait!

**Comment by 1st1** [comment]
@aeros Kyle, could you please manually backport the PR?

**Comment by aeros** [comment]
@1st1 
> Thank you, Kyle! Apologies for the wait!

No problem. (:

> Kyle, could you please manually backport the PR?

Yep, and I'll add you as a reviewer for the backports.

**Pull request merged**
