### PR TITLE
Make all instructions macros internally.

### PR DESCRIPTION
**Pull request by markshannon**
Adds a de-sugaring pass that converts:
```C
inst(LOAD_FAST, (-- value)) {
    value = GETLOCAL(oparg);
    assert(value != NULL);
    Py_INCREF(value);
}
```
into
```C
op(_LOAD_FAST, (-- value)) {
    value = GETLOCAL(oparg);
    assert(value != NULL);
    Py_INCREF(value);
}
macro(LOAD_FAST) = _SAVE_CURRENT_IP + _LOAD_FAST
```
and converts occurrences of `_SAVE_CURRENT_IP` to `SAVE_IP offset` for the tier 2.

### CODE REVIEW

**Comment by markshannon** [comment]
Fails with the error: `AssertionError: Push or pop above current stack level: stack_pointer[0]` when generating the code for `LOAD_FAST_CHECK`.

**Comment by gvanrossum** [comment]
What problem are you trying to solve here? It would seem to be purely a problem of the structure of the code generator, because the "translation table" (`_PyOpcode_opcode_metadata` in pycore_opcode_metadata.h) already treats everything as a macro.

I don't quite follow what you're trying to do with `_SAVE_CURRENT_IP`.

**Comment by markshannon** [comment]
I'm trying to make the semantics and behavior of each instruction completely explicit in the IR.

It keeps the back ends simpler, which is an overall improvement, as we have only one front-end, but many back ends.

We already have the following back-ends and we may get more:

* Tier 1 interpreter generator
* Ancillary table generator 
* Tier 2 interpreter generator
* Abstract interpreter generator
* Copy-and-patch stencil generator.

Each of these tools needs to understand the implicit conventions.
If nothing is implicit, they become much simpler.

**Comment by gvanrossum** [comment]
Let me take this and make it work, without including the `SAVE_CURRENT_IP` at the start of the generated macros.

**Pull request closed without merging**
