### PR TITLE
bpo-30206: restore *data* parameter of binascii.b2a_base64 to positional-only

### PR DESCRIPTION
**Pull request by zhangyangyu**

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Review by vstinner — COMMENTED** [review]
Can you try to write an unit test to prevent regression in the future?

Should we change the doc to specify that data is a positional only argument?

**Comment by zhangyangyu** [comment]
Of course I could add a test. I don't think we need a doc. It's never mentioned in the current doc and actually I think nobody notice the unintentional change.

**Comment by serhiy-storchaka** [comment]
I'm not sure about tests. Other implementation can support passing `data` as keyword, this isn't a bug. It is hard to implement positional-only parameter in pure Python.

**Comment by zhangyangyu** [comment]
Honestly speaking I support adding a test in this case. There are already some tests for positional-only arguments in other tests. I am not sure we should take care of other implementation here or this needs a cpython-only test.

**Comment by serhiy-storchaka** [comment]
What are other tests for positional-only arguments?

**Comment by zhangyangyu** [comment]
Like test_builtin.TestSorted.test_bad_arguments.

**Comment by serhiy-storchaka** [comment]
test_builtin.TestSorted.test_bad_arguments tests a concrete bug caused a crash when pass the first argument by keyword. This is an exceptional case.

**Comment by vadmium** [comment]
The change looks like it does what is intended, although I don’t think it is worthwhile. The damage (if any) as already been done.

**Comment by zhangyangyu** [comment]
Okay. Remove the test. Thanks all :-)

**Pull request merged**
