### PR TITLE
gh-106368: Argument Clinic: Add tests for cloned functions with custom C base names

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-106368

### CODE REVIEW

**Review by AlexWaygood — COMMENTED** [review]
There is still one case in this block that is untested:

https://github.com/python/cpython/blob/e28b0dc86dd1d058788b9e1eaa825cdfc2d97067/Tools/clinic/clinic.py#L4888-L4890

What if `is_legal_py_identifier(full_name)` evaluates to `True`, `not c_basename` evaluates to `False`, `is_legal_c_identifier(c_basename)` evaluates to `False` and `is_legal_py_identifier(existing)` evaluates to `True`?

I.e., if I apply this diff to your PR branch, the assertion is never triggered:

```diff
-            if (is_legal_py_identifier(full_name) and
-                (not c_basename or is_legal_c_identifier(c_basename)) and
-                is_legal_py_identifier(existing)):
+            if is_legal_py_identifier(full_name) and is_legal_py_identifier(existing):
+                if c_basename:
+                    assert is_legal_c_identifier(c_basename)
```

...Could you also add a test with a cloned function with a custom C base name where the custom C base name is not a legal C identifier?

**Comment by AlexWaygood** [comment]
I'm getting warnings about the execution environment when I'm running `python -m test test_clinic -v` with this PR branch locally, btw:

```pytb
Ran 243 tests in 0.620s

OK
Warning -- files was modified by test_clinic
Warning --   Before: []
Warning --   After:  ['clinic/']
Warning -- files was modified by test_clinic
Warning --   Before: []
Warning --   After:  ['clinic/']
test_clinic failed (env changed)

== Tests result: SUCCESS ==

1 test altered the execution environment:
    test_clinic

Total duration: 1.2 sec
Tests result: SUCCESS
```

**Comment by AlexWaygood** [comment]
> I'm getting warnings about the execution environment when I'm running `python -m test test_clinic -v` with this PR branch locally, btw:

Ah, and it looks like the CI is complaining about the same thing: https://github.com/python/cpython/actions/runs/5868181574/job/15910445072

**Comment by erlend-aasland** [comment]
> > I'm getting warnings about the execution environment when I'm running `python -m test test_clinic -v` with this PR branch locally, btw:
> 
> Ah, and it looks like the CI is complaining about the same thing: https://github.com/python/cpython/actions/runs/5868181574/job/15910445072

Ah, yeah, I noticed earlier today, but got sidetracked. Since we're running a "expect success" test, we will actually generate clinic output in the added test (hence the sudden `clinic/` directory). A workaround is to register a `cleanUp()` method, another is to just suppress all output, and yet another, is to run a `destination file clear` at the end of the clinic input.

**Comment by erlend-aasland** [comment]
I wonder why we're not seeing complaints about `clinic/` directories for the other `self.clinic.parse` tests...

**Comment by erlend-aasland** [comment]
> I wonder why we're not seeing complaints about `clinic/` directories for the other `self.clinic.parse` tests...

... because they don't create output; either they're dumping to block or buffer, or they're testing some weird directive, or they're run with precomputed checksums in the input (hence no regenerated output).

**Comment by erlend-aasland** [comment]
> ...Could you also add a test with a cloned function with a custom C base name where the custom C base name is not a legal C identifier?

Ah, good call. On it!

**Review by AlexWaygood — APPROVED** [review]
Looks great, thank you!

**Comment by erlend-aasland** [comment]
> thank you!

Likewise!

**Pull request merged**
