### PR TITLE
gh-85864: Mark no keyword arg for seek()

### PR DESCRIPTION
**Pull request by slateny**
#85864

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Actually, while we're here, could you confirm whether any other methods mentioned here need the same change? I checked and at least `readline` and `readlines` also take only positional arguments. Haven't looked at the others.

**Comment by slateny** [comment]
@JelleZijlstra Hmm, where is the position-only function parameters specified for these functions? I've tried looking at [_pyio.py](https://github.com/python/cpython/blob/main/Lib/_pyio.py#L372) but there's no `/` there, and while [_io/clinic/textio.c.h](https://github.com/python/cpython/blob/main/Modules/_io/clinic/textio.c.h#L473) does have the `/`, [this](https://docs.python.org/3/c-api/intro.html#c.PyDoc_STRVAR) says that `PyDoc_STRVAR` is just for docstrings so it doesn't seem that it would have impact on the implementation

**Comment by JelleZijlstra** [comment]
Here: https://github.com/python/cpython/blob/ac4ffd3be2049591701fee9f054191cce5ab9762/Modules/_io/iobase.c#L516. The Argument Clinic input blocks marks the parameter as pos-only, and this does affect the runtime. `_pyio.py` doesn't ever actually get used as far as I can tell.

**Comment by slateny** [comment]
It seems that [IOBase](https://github.com/python/cpython/blob/main/Modules/_io/clinic/iobase.c.h) doesn't have `seek()` defined, while the [docs](https://docs.python.org/3/library/io.html#io.IOBase.seek) do have it. Then, [BytesIO's seek](https://github.com/python/cpython/blob/main/Modules/_io/clinic/bytesio.c.h#L378) states that it has position-only arguments, yet in the docs, [BytesIO](https://docs.python.org/3/library/io.html#io.BytesIO) inherits [BufferedIOBase](https://docs.python.org/3/library/io.html#io.BufferedIOBase) which inherits [IOBase](https://docs.python.org/3/library/io.html#io.IOBase), and only `IOBase` has `seek()` in the docs. In this case, should the position-only marker be put onto IOBase's seek, or should the subclasses have `seek` written in the doc?

**Review by JelleZijlstra — APPROVED** [review]
Thank you!

**Comment by JelleZijlstra** [comment]
Sorry for missing that! I think we should just mark it as positional-only in the IOBase docs.

**Pull request merged**
