### PR TITLE
gh-103604: Fix incorrect paths in `netlify.toml`

### PR DESCRIPTION
**Pull request by arhadthedev**
Addresses both errors mentioned in the issue:

```plain
7:24:55 PM: Different build dir detected, going to use the one specified in the Netlify configuration file: 'Doc' versus 'Doc/' in the Netlify UI
7:24:55 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'Doc/build/html' versus 'build/html' in the Netlify UI
```

* Issue: gh-103604

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
It works now https://deploy-preview-103605--python-cpython-preview.netlify.app/

**Comment by arhadthedev** [comment]
Seems the configuration in the Netlify UI was changed.

**Comment by arhadthedev** [comment]
See the issue.

**Comment by arhadthedev** [comment]
Superseded by gh-103843 (see https://github.com/python/cpython/issues/103604#issuecomment-1528847407).

**Pull request closed without merging**
