### PR TITLE
GH-89886: Bump autoconf to version 2.71

### PR DESCRIPTION
**Pull request by erlend-aasland**
Based on gh-29756

* Issue: gh-89886

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Changes must be communicated; we need a NEWS entry and a bullet in What's New.

**Comment by arhadthedev** [comment]
image
😕

**Comment by erlend-aasland** [comment]
> image
> 😕

Yes. It is not surprising that the generated output changes considerably when you switch from one generator to another.

**Review by brettcannon — APPROVED** [review]
It looks fine to me, but I am far from an autoconf expert.

**Review by gpshead — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for the reviews! I'll have another look myself, before landing. Also, I'll add NEWS/What's New items.

**Comment by erlend-aasland** [comment]
IIUC, Autoconf macros are now pickier wrt. quoting than before; let's keep that in mind if we might get syntax errors for some untested `configure` options. Also with that in mind, it _may_ make sense to do a macro audit and simply add proper quoting to all arguments.

**Comment by erlend-aasland** [comment]
Running `autoupdate` (2.71) on `configure.ac` asks us to fix sys/time.h dependency:

```
$ autoupdate configure.ac
configure.ac:5246: warning: Update your code to rely only on HAVE_SYS_TIME_H,
then remove this warning and the obsolete code below it.
All current systems provide time.h; it need not be checked for.
Not all systems provide sys/time.h, but those that do, all allow
you to include it and time.h simultaneously.
```

It's an easy fix, and I suggest we apply it in a follow-up PR.

**Comment by erlend-aasland** [comment]
FTR, I'm landing this later today.

**Comment by erlend-aasland** [comment]
FTR, I'm investigating the buildbot errors.

**Pull request merged**
