### PR TITLE
bpo-29352: document s[i:j] with negative slices < -len(s)

### PR DESCRIPTION
**Pull request by 4kir4**

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
If be meticulous, missed the case of `-len(s) < i < 0` or `-len(s) < j < 0`. This is covered by note (3), but if read note (4) in the context of note (3) the mentioning of `len(s) + i` (where i still is not normalized) look strange.

Maybe remove the sentence `If *i* or *j* is greater than ``len(s)``, use ``len(s)``.` and add more general wording that only valid indices are taken into account? Sorry, I don't know how to formulate it in English.

**Comment by 4kir4** [comment]
If you think there is a better way to document the behavior; suggest your variant.  See http://bugs.python.org/msg289780

**Comment by Syeberman** [comment]
What if we break out each case separately?

> When an index in a slice is outside of range(-len(s),len(s)), it gets clamped to the bounds of the sequence.  Specifically:
> - if i>=len(s) and k>0, or i<-len(s) and k<0, the slice is empty
> - if i>=len(s) and k<0, the (reversed) slice starts with the last element
> - if i<-len(s) and k>0, the slice starts with the first element
> - if j>=len(s) and k<0, or j<-len(s) and k>0, the slice is empty
> - if j>=len(s) and k>0, the slice ends after the last element
> - if j<-len(s) and k<0, the (reversed) slice ends after the first element

**Comment by flavianh** [comment]
User @4kir4  has been unactive. I'll recreate a PR with @Syeberman's suggestion

**Comment by 4kir4** [comment]
@flavianh  [As I said earlier](https://github.com/python/cpython/pull/702#issuecomment-291927047) 

> I prefer the wording in the current patch. Though I don't have strong feelings one way or the other as long as the behavior is specified explicitly.

I don't think this PR will ever be merged. Please, go ahead and create a PR with a different wording.

**Comment by JulienPalard** [comment]
Closing as linked issue has been closed (out of date) by @rhettinger. Don't hesitate to comment in the issue if needed.

**Pull request closed without merging**
