### PR TITLE
gh-115556: Remove quotes from command-line arguments in test.bat and rt.bat

### PR DESCRIPTION
**Pull request by ambv**
This change essentially replaces usage of `%1` with `%~1`, which removes quotes, if any. Without this change, the if statements fail due to the quotes mangling the syntax.

Additionally, this change works around comma being treated as a parameter delimiter in `test.bat` by escaping commas at time of parsing. Tested combinations of rt and regrtest arguments, all seems to work as before but now you can specify commas in arguments like `"-uall,extralargefile"`.

* Issue: gh-115556

### CODE REVIEW

**Comment by ambv** [comment]
!buildbot Windows11 Bigmem

**Comment by ambv** [comment]
!buildbot Windows11 Bigmem

**Comment by zware** [comment]
I have no objections to this, but do please run the full set of Windows buildbots before merge.

**Comment by ambv** [comment]
!buildbot Windows

**Pull request merged**
