### PR TITLE
gh-121456: fixed complex as string throws error when string contains whitespace

### PR DESCRIPTION
**Pull request by LimaBD**
# Fixed complex as string throws error when string contains whitespace and added tests for this

issue: gh-121456

Before:
```python
print(complex("12 - 98j"))
```
```
Traceback (most recent call last):
  File "/home/angrygingy/Desktop/temporal/./to_run.py", line 1, in <module>
    print(complex("12 - 98j"))
          ~~~~~~~^^^^^^^^^^^^
ValueError: complex() arg is a malformed string
```

With this changes
```python
print(complex("12 - 98j"))
```
```
(12-98j)
```

I had to add a extra-step to store the sign and later multiply `y`
```c
char sign = *s;
...
if (sign == '-') {
    y = -y;
}
```

My concern was that this affects performance, but I did tests and it doesn't seem to happen.
```python
import cProfile

def example():
    for _ in range(10000000):
        complex("12-98.123456789j")

cProfile.run('example()')
```

Before
```
         4 function calls in 1.648 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    1.648    1.648 <string>:1(<module>)
        1    1.648    1.648    1.648    1.648 show_timings.py:3(example)
        1    0.000    0.000    1.648    1.648 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

With this changes
```
         4 function calls in 1.655 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    1.655    1.655 <string>:1(<module>)
        1    1.655    1.655    1.655    1.655 show_timings.py:3(example)
        1    0.000    0.000    1.655    1.655 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

### CODE REVIEW

**Review by ZeroIntensity — CHANGES_REQUESTED** [review]
`if` statements should follow the format defined in [PEP 7](https://peps.python.org/pep-0007/#code-lay-out)

**Comment by Eclips4** [comment]
> `if` statements should follow the format defined in [PEP 7](https://peps.python.org/pep-0007/#code-lay-out)

As well as `while` statements.

**Comment by LimaBD** [comment]
Thanks @ZeroIntensity @Eclips4 for the suggestions, I just finished making the changes.

**Comment by LimaBD** [comment]
I had added a check to ensure that the float is not signed twice

```python
print(complex("12 - -98j"))
```
```
Traceback (most recent call last):
  File "/home/angrygingy/Desktop/temporal/./to_run.py", line 1, in <module>
    print(complex("12 - -98j"))
          ~~~~~~~^^^^^^^^^^^^^
ValueError: complex() arg is a malformed string
```

**Review by ZeroIntensity — COMMENTED** [review]
Still missing PEP 7 compliance! Otherwise, LGTM.

**Review by ZeroIntensity — APPROVED** [review]

**Comment by LimaBD** [comment]
I added more tests for twice signed numbers to ensure that ValueError is raised By the way,

why docs tests is not passing ?

```
Error: new NEWS nits:

/home/runner/work/cpython/cpython/build/NEWS:87: WARNING: py:func reference target not found: warnings.filterswarnings
```

**Comment by devdanzin** [comment]
> By the way, why docs tests is not passing ?

Seems unrelated to your change, it's something added in https://github.com/python/cpython/commit/1a84bdc2371ada60c01c72493caba62c9860007b#diff-3b2105d4c1e6b38172c53e4abe1bcafdce9bb864981c319f6fe15056f6b69d3d

**Review by ZeroIntensity — CHANGES_REQUESTED** [review]
Typo in the NEWS.d entry. It should be `warnings.filterwarnings`, not `warnings.filterswarnings` (you have an extra `s` after filter!), which is what's causing CI to fail.

Edit: oh wait, that looks unrelated to this issue.

**Comment by ZeroIntensity** [comment]
> > By the way, why docs tests is not passing ?
> 
> Seems unrelated to your change, it's something added in [1a84bdc#diff-3b2105d4c1e6b38172c53e4abe1bcafdce9bb864981c319f6fe15056f6b69d3d](https://github.com/python/cpython/commit/1a84bdc2371ada60c01c72493caba62c9860007b#diff-3b2105d4c1e6b38172c53e4abe1bcafdce9bb864981c319f6fe15056f6b69d3d)

Right, I didn't see this. This PR looks fine to me otherwise.

**Review by ZeroIntensity — APPROVED** [review]

**Comment by ZeroIntensity** [comment]
FWIW, pulling from upstream should fix this.

**Review by skirpichev — CHANGES_REQUESTED** [review]
You should adjust docs to match new behaviour.

**Comment by ZeroIntensity** [comment]
Do bugfixes need documentation changes?

**Comment by ZeroIntensity** [comment]
Oh, nevermind, I saw your comment on the original issue.

**Comment by LimaBD** [comment]
as discussed before here #53783 and here #121456, i am going to close this PR

**Pull request closed without merging**
