### PR TITLE
bpo-40937: Do not expose abstract collection classes in the collections module

### PR DESCRIPTION
**Pull request by remilapeyre**
Original patch in ef092fe9905f61ca27889092ca1248a11aa74498 by Serhiy Storchaka

https://bugs.python.org/issue40937

### CODE REVIEW

**Comment by rhettinger** [comment]
Have Serhiy take a look this.  He's up to date on how long this has been deferred and where the essential downstream packages have been updated yet.

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
Add a What's New entry.

**Comment by remilapeyre** [comment]
Thanks, I have made the requested changes; please review again

**Comment by tirkarthi** [comment]
FWIW, I created 100 issues across 3500 top PyPI packages about this. There were also several reports from Fedora about this when they updated to Python 3.9. https://github.com/search?q=is%3Aissue+author%3Atirkarthi+archived%3Afalse+collections

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
See also #23754.

@rhettinger, merge please one of these PRs.

**Comment by rhettinger** [comment]
That isn't up to me. Try @pablogsal

**Comment by hugovk** [comment]
This removal has been merged via https://github.com/python/cpython/pull/23754.

Thanks for the PR!

**Pull request closed without merging**
