### PR TITLE
bpo-37342: Fix the incorrect nb_index's type in typeobj documentation

### PR DESCRIPTION
**Pull request by shihai1991**
It was listed as `binaryfunc`. It should be `unaryfunc`.

### CODE REVIEW

**Review by tirkarthi — APPROVED** [review]
LGTM. It's listed as unaryfunc ".. c:member:: unaryfunc PyNumberMethods.nb_index" in https://github.com/python/cpython/blob/master/Doc/c-api/typeobj.rst line 2069.

**Comment by tirkarthi** [comment]
Please fix the CI error. I think the last column with "__index__" at https://travis-ci.org/python/cpython/jobs/547863960#L399 needs a space so that it's aligned with the rest of columns in the table as shown in the CI error log.

**Comment by shihai1991** [comment]
> Please fix the CI error. I think the last column with "**index**" at https://travis-ci.org/python/cpython/jobs/547863960#L399 needs a space so that it's aligned with the rest of columns in the table as shown in the CI error log.
> 
> Edit: I think NEWS entry is not needed for this doc change

Good catch. Let us try it ;)

**Review by Mariatta — APPROVED** [review]
Thanks. I confirmed it is `unaryfunc` in https://github.com/python/cpython/blob/af41c567af81de7c4408e2e2617f1d3747408434/Include/cpython/object.h#L136. News file is not needed.

**Comment by tirkarthi** [comment]
Thank you @shihai1991

**Pull request merged**
