### PR TITLE
bpo-39033: Fix NameError in zipimport during hash validation

### PR DESCRIPTION
**Pull request by tirkarthi**
Fix `NameError` in `zipimport` during hash validation and add a regression test.

https://bugs.python.org/issue39033

### CODE REVIEW

**Review by corona10 — APPROVED** [review]
Nice catch from the issuer :)

Looks good to me!

**Review by ncoghlan — APPROVED** [review]
Nice catch! At some point we should probably just search the entire code base for references to "boostrap"...

**Comment by tirkarthi** [comment]
Thanks Nick. I think this can be backported to 3.8 too. This changes the importlib header file and I guess it's allowed to change between bug fix versions.

**Comment by brettcannon** [comment]
@tirkarthi yes, the header files can change in bugfix releases. But it does mean backporting will have to be done in manual PRs to get the right bytecode.

**Comment by tirkarthi** [comment]
Ah yes, thanks Brett I will make a manual backport with the generated header file.

**Pull request merged**
