### PR TITLE
bpo-27923: Minor API improvements for binary sequences (PEP 467)

### PR DESCRIPTION
**Pull request by elias6**
This is basically my original attempt to implement PEP 467, with some minor changes to make it work with Python 3.7.

https://bugs.python.org/issue27923

### CODE REVIEW

**Comment by mikez302** [comment]
Does anyone know why the Travis build is failing? I can't figure it out.

**Comment by mscuthbert** [comment]
Do we generally put in a PendingDeprecationWarning when the alternative syntax is not available in still supported versions of Python or is going all the way to DeprecationWarning immediately the normal way of doing things?  The new syntax is great, but I'd prefer not to need to do a version test/fork as long as <= Py3.6 is still supported by my modules and while PendingDeprecationWarnings are fine, I try not to have DeprecationWarnings in code I release.

**Comment by mikez302** [comment]
So... what else needs to be done for this change to be approved? Does someone need to merge it?

**Comment by erlend-aasland** [comment]
Closing this, as the linked issue has been closed.

**Pull request closed without merging**
