### PR TITLE
[2.7] bpo-39084: Construct string.letters in the correct order when resetting locale

### PR DESCRIPTION
**Pull request by Manishearth**
https://bugs.python.org/issue39084

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Manishearth

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Manishearth** [comment]
(I've already signed the CLA online, but it hasn't been updated)

**Comment by zware** [comment]
Sorry, but I'm closing this for the same reasons as the [issue](https://bugs.python.org/issue39079):
- this is a 2.x-only issue
- it's been this way for 22 years apparently without causing issues until now (I can find no other reports on bugs.python.org)
- it's actually [documented](https://docs.python.org/2/library/locale.html#background-details-hints-tips-and-caveats) that this happens
- there's probably some code somewhere that would be broken by "fixing" this, and there would be no opportunity to fix it back because
- Python 2.7 only has 2 weeks to live

You've followed our PR guidelines very well, though; thanks for that and I hope your next contribution has a better end than this one!

**Comment by Manishearth** [comment]
> it's actually [documented](https://docs.python.org/2/library/locale.html#background-details-hints-tips-and-caveats) that this happens

It's not documented that `string.letters` will reverse, only that it will be recalculated



> there's probably some code somewhere that would be broken by "fixing" this, and there would be no opportunity to fix it back because

I'd be very surprised if this happened given that this is kinda unpredictable, setlocale() can be called at weird times.



> Python 2.7 only has 2 weeks to live

That's fair. My view is that it's not dead yet and we should get any fixes possible in before that so that the final version has them -- after all, even if it's EOL it's going to take a while for it to completely go away. But I get that that makes fixes like these very low priority.

**Pull request closed without merging**
