### PR TITLE
[3.12] gh-108447: Detect platform triplets for x86_64 GNU/Hurd (GH-108045)

### PR DESCRIPTION
**Pull request by sthibaul**
(cherry picked from commit edb569e8e1f469ac5ce629cc647ab169d895de41)

* Issue: gh-108447

### CODE REVIEW

**Review by erlend-aasland — DISMISSED** [review]
Are you fine with this, Dong-hee?

**Comment by erlend-aasland** [comment]
I changed my mind; I'm not sure it is a good idea to alter the platform triplets in 3.12 and 3.11.

**Comment by sthibaul** [comment]
> I changed my mind; I'm not sure it is a good idea to alter the platform triplets in 3.12 and 3.11.

? It's not altering it, it's adding it

**Comment by erlend-aasland** [comment]
IMO, it's a feature; we don't backport features. What do you think, @corona10?

**Comment by corona10** [comment]
Agree

**Pull request closed without merging**
