### PR TITLE
gh-96761: Fix build process of the clang compiler for _bootstrap_python

### PR DESCRIPTION
**Pull request by corona10**
Co-authored-by: Matthias Goergens <matthias.goergens@gmail.com>

* Issue: gh-96761

### CODE REVIEW

**Comment by corona10** [comment]
cc @matthiasgoergens

**Comment by matthiasgoergens** [comment]
Awesome, thanks for picking this up!

**Comment by corona10** [comment]
@pablogsal Can you please take a look?

**Comment by corona10** [comment]
FYI, we already use this approach while selecting the default LTO policy for CPython building
https://github.com/python/cpython/pull/96766

**Pull request merged**
