### PR TITLE
GH-95289: Always call uncancel() when required

### PR DESCRIPTION
**Pull request by gvanrossum**
In `__aexit__()` we should always call `self._parent_task.uncancel()` when we called `self._parent_task.cancel()` -- even if the exception being received by `__aexit__()` is not `CancelledError` (since it may have been suppressed or replaced by another exception).

The logic is a bit contorted since we must propagate a cancellation error in two separate situations:
- if uncancel() is called and it returns a value greater than zero
- if we don't call uncancel() at all

* Issue: gh-95289

### CODE REVIEW

**Comment by YvesDup** [comment]
Hi, 
I ran this code with your changes, for the required test in the 'externally cancel' case.
Here a `CancelledError` is raised, the `_parent_cancel_requested`  is `False`, so `uncancel()` is never called. Is the expected behavior ?

```py
import asyncio

class MyException(Exception):
    pass

async def async_fn2():
    try:
        await asyncio.sleep(0.0)
        raise MyException
    finally:
        print("raise done")

async def main():
    task = asyncio.current_task()
    try:
        async with asyncio.TaskGroup() as tg:
            tg.create_task(async_fn2())
            await asyncio.sleep(1)

    except* (MyException, asyncio.CancelledError) as e:
        # How to check a private `_parent_cancel_requested` attr here, outside the class ?
        print(f"{e.exceptions} -> {task.cancelling()=}, {tg._parent_cancel_requested=}")

async def supermain():
    t = asyncio.create_task(main())
    await asyncio.sleep(0)

    t.cancel()
    print("cancel main task")
    await asyncio.sleep(1)

    print(f"{t.cancelling()=} must be 1, confirm ?")

asyncio.run(supermain())
```

**Comment by YvesDup** [comment]
I wonder whether it is important to check if parent task is not `cancelling` when starts the `async with` ? 
In that case, should we raise a `RuntimeError` in the `__aenter__` ?

**Comment by gvanrossum** [comment]
> I wonder whether it is important to check if parent task is not `cancelling` when starts the `async with` ? In that case, should we raise a `RuntimeError` in the `__aenter__` ?

What problem would that solve?

**Comment by YvesDup** [comment]
>>    I wonder whether it is important to check if parent task is not cancelling when starts the async with ? In that case, should we raise a RuntimeError in the __aenter__ ?
>
> What problem would that solve?

Problem is already solved with the 'externally cancel' case. 
Sorry for waste your time.

**Comment by kumaraditya303** [comment]
Superseded by https://github.com/python/cpython/pull/95602 which includes tests.

**Pull request closed without merging**
