### PR TITLE
gh-109182: Fix and improve tests for gh-108654

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-109182

* Issue: gh-108654

### CODE REVIEW

**Review by carljm — APPROVED** [review]
I prefer to keep the use of `with self.subTest(...)` when a test case is checking two related cases. It's not a huge deal, but it keeps the two cases independent, so that if the first one fails, the second one still runs instead of being silently skipped, so that a single run of the tests can give a fuller picture of the state of the system under test.

Otherwise, these changes look like clear improvements to the comprehensiveness (and readability) of the tests. Thank you!

**Comment by serhiy-storchaka** [comment]
`_check_in_scopes()` uses `subTest()` internally. So 2 subsequent `_check_in_scopes()`s can give you up to 6 failure reports (3 reports each).

**Comment by serhiy-storchaka** [comment]
Thank you for your review @carljm.

**Comment by carljm** [comment]
> `_check_in_scopes()` uses `subTest()` internally. So 2 subsequent `_check_in_scopes()`s can give you up to 6 failure reports (3 reports each).

Oh, good point! So we already will get independent failures for all six cases. The only thing we lose by eliminating the outer `subTest` is the extra `raises` context value -- but by eliminating the loop, we no longer need that, since it is effectively provided by the line number.

Ok, then I am happy with these changes as is!

**Pull request merged**
