### PR TITLE
[doc] Document VIRTUAL_ENV environment variable (GH-21970)

### PR DESCRIPTION
**Pull request by andresdelfino**
Automerge-Triggered-By: @vsajip

### CODE REVIEW

**Review by vsajip — APPROVED** [review]

**Comment by vsajip** [comment]
> I therefore recommend that this commit be reverted.

Rather than doing that, I would propose to change the paragraph as follows:

> When a virtual environment has been activated using one of the activation scripts, the :envvar:`VIRTUAL_ENV` environment
variable is set to the path of the virtual environment. Although it might seem that this could  be used to check if one is running inside a virtual environment, it is not always present: for example, a script installed in a virtual environment can be run using its absolute path, and the correct environment would then be in effect; however, there would be no ``VIRTUAL_ENV`` variable in the environment. It's always safer to use ``sys.base_prefix != sys.prefix``, which will be ``True`` when running in a virtual environment.

**Comment by pelson** [comment]
> When a virtual environment has been activated using one of the activation scripts, the :envvar:`VIRTUAL_ENV` environment
> variable is set to the path of the virtual environment. Although it might seem that this could be used to check if one is running inside a virtual environment, it is not always present: for example, a script installed in a virtual environment can be run using its absolute path, and the correct environment would then be in effect; however, there would be no `VIRTUAL_ENV` variable in the environment. It's always safer to use `sys.base_prefix != sys.prefix`, which will be `True` when running in a virtual environment. See the note below.

I take your lead on this, but to me that sounds like quite a lot of words for not a lot of new detail. I definitely think the page in question could be reshuffled a bit to make this concise and easier to find the information quickly. Would you like me to submit a proposal?

**Comment by andresdelfino** [comment]
I think we shouldn't remove the mention to VIRTUAL_ENV (reverting this commit would have that effect), as it is helpful.

Of course, I'm all for improving the correctness of the docs.

**Comment by vsajip** [comment]
Well, I made my suggestion in the way that I did because it 

* Informs users about the environment variable (it could be useful to know in some scenarios)
* Warns against relying on it for determining whether code is running in a virtual environment

and it may be wordier than it needs to be, but I was thinking of spelling things out for any inexperienced users / users new to virtual environments.

**Pull request merged**
