### PR TITLE
venv (shorthand for home)

### PR DESCRIPTION
**Pull request by ghost**
Sometimes it's indicated to explicitly state the obvious, unless of course the author of the below inferred the possibility of the use of a UN*X style hidden directory in another location than $HOME.

```
$ ed -s venv-create.inc <<<'6,15p'
Running this command creates the target directory (creating any parent
directories that don't exist already) and places a ``pyvenv.cfg`` file in it
with a ``home`` key pointing to the Python installation from which the command
was run (a common name for the target directory is ``.venv``).  It also creates
a ``bin`` (or ``Scripts`` on Windows) subdirectory containing a copy/symlink
of the Python binary/binaries (as appropriate for the platform or arguments
used at environment creation time). It also creates an (initially empty)
``lib/pythonX.Y/site-packages`` subdirectory (on Windows, this is
``Lib\site-packages``). If an existing directory is specified, it will be
re-used.
$ 
```

Noting Windows doesn't allocate for UN*X style hidden directories, what might be a "common name for the target directory" on that OS?

### CODE REVIEW

**Comment by vsajip** [comment]
The suggested change doesn't seem right to me. The `.venv` directory referred to is not _necessarily_ meant to be in the user's home directory. Quite often there are multiple `.venv` directories  for a user, each relating to a specific project in the user's  area of the filesystem hierarchy.

**Comment by fluesvamp** [comment]
@vsajip 

then we should close

> Quite often there are multiple .venv directories for a user, each relating to a specific project in the user's area of the filesystem hierarchy.

Is that irrespective of platform?

**Comment by vsajip** [comment]
> Is that irrespective of platform?

Yes.

**Comment by fluesvamp** [comment]
@vsajip 

The venv-create.inc excerpt brings to mind the Filesystem Hierarchy Standard (FHS)* not per se Python conventions. Shell output of `tree` using `-ad` and `-L` <ins>level</ins> options run within a user's area of the filesystem hierarchy showing multiple `.venv` directories might provide a clarification.

\* files hidden from `ls`

Factually the Windows console has a `TREE` builtin which might emphasize that the `.venv` convention is likewise used on that Operating System.

<hr>

```diff
- was run (a common name for the target directory is ``.venv``).  It also creates
+ was run (a common name irrespective of platform for the target directory is ``.venv``).  It also creates
```

**Pull request closed without merging**
