### PR TITLE
gh-118189: Revert accidentally added incl.tar

### PR DESCRIPTION
**Pull request by arhadthedev**
This is a follow-up to gh-118159.

`Include/incl.tar` is a full copy of `Include`. It seems to be added by accident so this PR deletes it back.

No NEWS entry because the file was added yesterday with no backports.

*/cc @gvanrossum as an author of the parent PR.*

* Issue: gh-118189

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Looks unrelated

**Comment by gvanrossum** [comment]
Sorry! git rookie mistake. :-( Thanks for cleaning up my mess.

**Comment by mhsmith** [comment]
> ```
>     self.assertEqual(len(posix.confstr("CS_PATH")) > 0, True)
>                          ~~~~~~~~~~~~~^^^^^^^^^^^
> ValueError: unrecognized configuration name
> ```

@freakboy3742: This seems to be happening at random in about 1 in 10 of the iOS buildbot runs.

**Comment by freakboy3742** [comment]
I've opened #118201 to track the intermittent iOS build failure.

**Pull request merged**
