### PR TITLE
Correct typo in configparser.rst

### PR DESCRIPTION
**Pull request by strugee**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by strugee** [comment]
CLA is now signed (pending confirmation) but this feels unnecessary? This change is so trivial I probably don't hold _any_ copyright at all in this file. I think @the-knights-who-say-ni should probably be adjusted.

**Comment by freddrake** [comment]
+1

**Comment by freddrake** [comment]
This is seriously trivial; I don't thnik the CLA is an issue.

**Comment by strugee** [comment]
:thumbsup: thanks @freddrake!

**Pull request merged**
