### PR TITLE
bpo-39895: Move `pathlib.Path.touch()` implementation into the path accessor

### PR DESCRIPTION
**Pull request by barneygale**
`Path.touch()` does a lot of os-specific /stuff/ that should probably live in the accessor. Perhaps most importantly, is calls `os.close()` on whatever `accessor.open()` returns, which is problematic for those wishing to write their own accessor that doesn't work on a file descriptor level.

This PR:

- Routes `Path.touch()` via the path's accessor, in conformity with most other `Path` methods.
- Adds an `_NormalAccessor.touch()` method
- Removes `_NormalAccessor.utime()` (which was only used by `touch()`)
- Removes `Path._raw_open()` (which was only used by `touch()`)

https://bugs.python.org/issue39895

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@barneygale

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by barneygale** [comment]
I think this doesn't require a NEWS entry as it's an internal refactor

**Review by pitrou — APPROVED** [review]
LGTM. Could you please merge/rebase from master and fix the conflicts?

**Comment by barneygale** [comment]
Rebased

**Comment by barneygale** [comment]
@pitrou can this be merged? Thanks

**Pull request merged**
