### PR TITLE
bpo-41277: Mapping correct values in the os.setxattr() documentation

### PR DESCRIPTION
**Pull request by shreyneil**
https://bugs.python.org/issue41277

Automerge-Triggered-By: GH:ericvsmith

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@shreyneil

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by shreyneil** [comment]
Happy and excited to open my first PR towards the goal of contributing to this project.
@rhettinger have signed the CLA and mailed to contributors mailing list, it would be great if you can add the skip news label and review the PR

**Comment by shreyneil** [comment]
@ericvsmith can you review this one ?

**Review by ericvsmith — APPROVED** [review]
This looks correct to me. It's the tested behavior in ExtendedAttributeTests.

**Pull request merged**
