### PR TITLE
bpo-45508: Specialize INPLACE_ADD

### PR DESCRIPTION
**Pull request by sweeneyde**
Pyperformance/Specialization results: https://gist.github.com/sweeneyde/41a76356e875e2a98d16ce5410ab41c0

https://bugs.python.org/issue45508

### CODE REVIEW

**Comment by markshannon** [comment]
You can remove `unicode_concatenate`

**Comment by markshannon** [comment]
Maybe I should read the first comment :slightly_smiling_face:

**Comment by markshannon** [comment]
Once #29482 is merged this will need to reworked for the Nth (and hopefully last) time. Sorry about that.
On the bright side, it should save some boilerplate.

**Comment by sweeneyde** [comment]
I think PR 29482 will just make this obsolete -- it manages to re-use `*_ADD` opcodes for `INPLACE_ADD` opcodes (nice!):

```
(In specialize.c)
        case NB_ADD:
        case NB_INPLACE_ADD:
            if (PyUnicode_CheckExact(lhs)) {
                if (_Py_OPCODE(instr[1]) == STORE_FAST && Py_REFCNT(lhs) == 2) {
                    *instr = _Py_MAKECODEUNIT(BINARY_OP_INPLACE_ADD_UNICODE,
                                              _Py_OPARG(*instr));
                    goto success;
                }
                *instr = _Py_MAKECODEUNIT(BINARY_OP_ADD_UNICODE,
                                          _Py_OPARG(*instr));
                goto success;
            }
```

**Pull request closed without merging**
