### PR TITLE
bpo-40741: Update Windows installer to use SQLite 3.32.2

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue40741

### CODE REVIEW

**Review by ned-deily — APPROVED** [review]
The macOS installer changes look fine, though I won't take the time to actually test them right now.  Thanks, @erlend-aasland!

@zooba, What are your thoughts on backports?  In principle, I'm fine with 3.9, 3.8, and 3.7.

**Comment by erlend-aasland** [comment]
@ned-deily, @zooba: SQLite 3.32.2 was released a couple of days ago. I've created a PR for `cpython-source-deps`. When that one goes through (and gets tagged), do you want me to update this PR, or is it cleaner to close this and create a new PR?

**Comment by ned-deily** [comment]
@erlend-aasland, Thanks for the 3.32.2 heads-up. I think either updating or a new pr is fine.  Be aware, though, that I am pushing the macOS installer update in a separate PR as I'd like this to be in 390b2. So when you update this PR, please remove the Mac installer blurb entry; the build-installer change shouldn't conflict if you don't remove it :)

**Comment by erlend-aasland** [comment]
Great that you got it in before 3.9-beta2, @ned-deily, thanks :) I've removed the macOS parts (both the blurb and the installer script) from this PR. Waiting for https://github.com/python/cpython-source-deps/pull/20 to be merged and tagged.

**Comment by erlend-aasland** [comment]
Thanks for merging https://github.com/python/cpython-source-deps/pull/20, @zooba. I'll push a dummy commit just to kick off the CI on this PR, if you don't mind.

**Comment by erlend-aasland** [comment]
Closing this and reopening separate PR's for SQLite 3.32.3 for macOS and Windows.

**Pull request closed without merging**
