### PR TITLE
gh-113978: Ignore warnings on text completion inside REPL

### PR DESCRIPTION
**Pull request by WolframAlph**
gh-113978

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
Maybe instead we should do this?

```diff
» git patch
diff --git Lib/rlcompleter.py Lib/rlcompleter.py
index 206d6fb511c..62fd2c7fdec 100644
--- Lib/rlcompleter.py
+++ Lib/rlcompleter.py
@@ -176,8 +176,9 @@ def attr_matches(self, text):
                 if (word[:n] == attr and
                     not (noprefix and word[:n+1] == noprefix)):
                     match = "%s.%s" % (expr, word)
+                    import types
                     if isinstance(getattr(type(thisobject), word, None),
-                                  property):
+                                  (property, types.GetSetDescriptorType)):
                         # bpo-44752: thisobject.word is a method decorated by
                         # `@property`. What follows applies a postfix if
                         # thisobject.word is callable, but know we know that
                        
```

It also solves the issue: 
Снимок экрана 2024-01-12 в 14 35 59

**Comment by WolframAlph** [comment]
Not really sure. My intention was to eliminate all possible warnings during completion (now and in future) no matter where they come from. Maybe it's the only possible path where it can happen but I am not sure since I never dealt with such things. Your solution looks cleaner to me and I believe you have broader context so I leave it up to you to decide.

**Comment by sobolevn** [comment]
My thoughs: properties should not evaluate when auto-complete works, so I think that adding an ignore just hides this problem.

So, we should really address the root of this problem: do not execute `.co_lnotab` property on code objects (and similar types as well).

**Comment by WolframAlph** [comment]
> properties should not evaluate when auto-complete works

I agree. But is this true only for built-in objects and their properties or user defined as well?
Consider following piece of code:
```python
class D:
    def __get__(self, _, __):
        print(“evaluated")

class C:
    prop = D()
```
trying to get suggestions for `C.` evaluates `prop` and prints the message.

**Comment by sobolevn** [comment]
We can also try to replace `getattr` with `inspect.getattr_static`

**Comment by WolframAlph** [comment]
Some things depend on being evaluated. Using `inspect.getattr_static` instead of `getattr` breaks tests. 

https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Lib/test/test_rlcompleter.py#L51-L85

Things like `__init_subclass__`, `__class__`, `mro`, etc...

**Pull request merged**
