### PR TITLE
gh-110276: No longer ignore PROFILE_TASK failure silently

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-110276

----
:books: Documentation preview :books:: https://cpython-previews--110295.org.readthedocs.build/

### CODE REVIEW

**Review by AlexWaygood — COMMENTED** [review]
This PR only touches the Makefile but, as I said in https://github.com/python/cpython/issues/110276#issuecomment-1745207314, the problem also exists on Windows: I found locally that the test would fail but the build would still succeed. Windows builds don't use the Makefile.

**Comment by vstinner** [comment]
!buildbot PGO

**Comment by vstinner** [comment]
AMD64 RHEL8 LTO + PGO PR failed: https://buildbot.python.org/all/#/builders/378/builds/1199

```
FAIL: test_selflink (test.test_glob.SymlinkLoopGlobTests.test_selflink)
```

It's an unrelated failure: https://github.com/python/cpython/issues/109959

**Comment by mdboom** [comment]
This seems like it may have broken PGO on macOS: https://github.com/python/cpython/issues/110313

**Comment by vstinner** [comment]
> This seems like it may have broken PGO on macOS: https://github.com/python/cpython/issues/110313

Aha, interesting bug.

**Comment by JacobHenner** [comment]
Now that test failures are no longer ignored, Python 3.13 builds on Rocky Linux 8 are now failing: https://github.com/python/cpython/issues/125067

**Pull request merged**
