### PR TITLE
bpo-33663: Convert content length to string before putting to header

### PR DESCRIPTION
**Pull request by ValeriyaSinevich**
https://bugs.python.org/issue33663

https://bugs.python.org/issue33663

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by ValeriyaSinevich** [comment]
CLA agreement is signed.

**Comment by zooba** [comment]
Looks goo, thanks!

**Comment by rayluo** [comment]
PR looks good! Off topic: why that bot duplicated the url in the PR description? :-)

**Pull request merged**
