### PR TITLE
bpo-40275: Use new test.support helper submodules in tests

### PR DESCRIPTION
**Pull request by shihai1991**
Use test helpers in the following test cases:
* tests of distutils
* test_dbm_gnu
* test_eof
* test_hashlib
* test_idle
* test_imaplib
* test_marshal
* test_py_compile
* test_set
* test_socket
* test_sysconfig
* test_traceback
* test_unicode
* test_xml_etree
* test_zipfile

https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by shihai1991** [comment]
@vstinner pls take a look if you have free time, thanks.

**Review by vstinner — APPROVED** [review]
LGTM. I cannot merge your PR, there is a merge conflict. Please fix the conflict, and ping me when it's done.

**Comment by shihai1991** [comment]
@vstinner ping : )

**Comment by shihai1991** [comment]
thanks, victor.

**Pull request merged**
