### PR TITLE
General faq update

### PR DESCRIPTION
**Pull request by E-Paine**
This is a very trivial set of changes that updates a few pieces of information on the "general" FAQ page. I did not deem it worth an issue, so I hope this is noticed by someone.

### CODE REVIEW

**Review by aeros — CHANGES_REQUESTED** [review]
Thanks for the PR @E-Paine. While I'm on-board with the change to the release schedule and rough estimated users part, I don't think the changes for `comp.lang.python` and `com.lang.python.announce` are particularly useful or maintainable. The idea of the numbers on postings are to give an incredibly rough estimate, and it adds an unnecessary maintenance burden to continuously lower or increase it based on the most recent activity. So I think those parts are fine as they are.

**Comment by E-Paine** [comment]
Very good point. I have reverted those changes

**Comment by aeros** [comment]
Thanks for making the recommended changes! It looks good to me now, I'll proceed with merging (with a slight adjustment to the title in the commit message to make the changes more clear).

**Review by aeros — APPROVED** [review]

**Comment by aeros** [comment]
Also, back porting to 3.9 and 3.8 so it's in the latest versions of the documentation on docs.python.org.

**Pull request merged**
