### PR TITLE
gh-108303: Move all math files to `Lib/test/mathdata/`

### PR DESCRIPTION
**Pull request by sobolevn**
This one is pretty straight-forward. All math data now lives in a specialized place.

* Issue: gh-108303

### CODE REVIEW

**Review by lizzydavis695 — APPROVED** [review]
Command

**Review by serhiy-storchaka — APPROVED** [review]

**Review by vstinner — COMMENTED** [review]
I dislike "data" directories.

It seems like test_math uses 3 data files which are only used by test_math.

test_float uses 2 data files which are only used by test_float.

For me, "data" directories are nice when data files are shared by different tests. It doesn't seem to be the case here.

What do you think of creating test_float/ and test_math/ directories instead?

**Comment by sobolevn** [comment]
> What do you think of creating test_float/ and test_math/ directories instead?

I don't have any strong opinions here, for me `mathdata/` seems like a more simple way of organizing tests. But, I can change it to be `test_math/` (with possibly `test_cmath.py` inside) and `test_float/` 

Why do I prefer the first option? Because later some other file can be added there: possibly from `test_int.py` or `test_decimal.py` or whatever. Or some test from `test_math.py` can reuse float test data. This is why I went with the approach in this PR.

**Comment by serhiy-storchaka** [comment]
"cmath_testcases.txt" is shared with `test_cmath`.

**Comment by vstinner** [comment]
@serhiy-storchaka approved the change, I'm not *strongly* against ``Lib/test/mathdata/`` approach.

I'm just surprised that 2 test files are added there whereas they are only used by test_float. I don't see the point of "sharing" these two files. Maybe make a test_float/ directory for them?

@serhiy-storchaka: If you're fine with mathdata/ approach,go ahead and merge the PR :-)

> Because later some other file can be added there: possibly from test_int.py or test_decimal.py or whatever. Or some test from test_math.py can reuse float test data.

That sounds to be be an hypothetical use case. I would prefer to stick to current test data files usage to decide how to organize them.

**Comment by serhiy-storchaka** [comment]
It also imports the path to the test data file and the parsing function from `test_math`, and runs tests without skipping complex numbers.

**Comment by serhiy-storchaka** [comment]
> I'm just surprised that 2 test files are added there whereas they are only used by test_float. I don't see the point of "sharing" these two files. Maybe make a test_float/ directory for them?

They could be used in tests for `decimal` and `fractions`. I am not even sure that they are not yet used there.

**Comment by serhiy-storchaka** [comment]
> If tomorrow other tests start using test_float data files, we can re-consider the organization of these data files, no?

#109548

**Comment by vstinner** [comment]
Oh, @serhiy-storchaka made https://github.com/python/cpython/pull/109548 which makes mathdata/ directory more relevant :-)

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
Oh, this PR was outdated since PR #109548 got merged! I wrote PR #109686 to fix it.

**Pull request merged**
