### PR TITLE
bpo-1635741: Port _codecs extension module to multiphase initialization (PEP 489)

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue1635741

Automerge-Triggered-By: @encukou

### CODE REVIEW

**Review by ncoghlan — APPROVED** [review]
LGTM (given the relative simplicity of the module), but until I've reviewed a few more of these, I'd like to get a +1 from @encukou as well.

**Comment by encukou** [comment]
The catch it that the simple module exposes complex API, and multiphase init asserts that the module is [expected to support sub-interpreters](https://docs.python.org/3/c-api/module.html?highlight=pymodule_fromdefandspec#multi-phase-initialization). Any module that manipulates some registry should get some extra attention :)
All looks OK here, since the`PyCodec_*` functions all use interpreter-specific state.
@Dormouse759, do you want to take a look?

**Comment by shihai1991** [comment]
Thanks, guys.

**Comment by encukou** [comment]
Thank *you*!

**Pull request merged**
