### PR TITLE
Remove macOS tests from Travis.

### PR DESCRIPTION
**Pull request by benjaminp**
Azure runs macOS, so we don't need Travis to do it.

### CODE REVIEW

**Comment by ammaraskar** [comment]
Is overlap the only motivation for removal here? I don't think overlap is necessarily bad, after all we run Linux on both Travis and Azure as well. Windows is run on Azure and AppVeyor. The redundancy helps to figure out flaky tests/race conditions and provides some actionable information in case a particular provider goes down.

**Comment by benjaminp** [comment]
On Mon, Sep 9, 2019, at 18:11, Ammar Askar wrote:
> Is overlap the only motivation for removal here? I don't think overlap 
> is necessarily bad, after all we run Linux on both Travis and Azure as 
> well.

The overlap isn't free, though. Duplicated work takes up finite CI resources. It's also true that the more things we run the more likely we are to see flakes.

**Comment by zooba** [comment]
I agree with this particular one, since the Travis resources are limited.

I'd prefer to keep as many parallel builds as we can though, especially cross-CI system, as that gives us better representation of different user environments.

**Review by ned-deily — COMMENTED** [review]
I think that running the tests under macOS on Travis has not proved to be very effective at finding real problems so I support making this change.  Thanks!

**Pull request merged**
