### PR TITLE
[3.12] gh-116145: Updated bundled Tcl/Tk on Windows to 8.6.14 (GH-117030)

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
(cherry picked from commit 0e8d35b931f41210483cc51c4169e9a943c7f166)

* Issue: gh-116145

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
https://github.com/python/cpython-source-deps/archive/refs/tags/tix-8.4.3.6.tar.gz does not exist. But this reference is not changed in this PR!

**Comment by serhiy-storchaka** [comment]
> https://github.com/python/cpython-source-deps/archive/refs/tags/tix-8.4.3.6.tar.gz does not exist. But this reference is not changed in this PR!

It exists. The problem must be anywhere else.

**Comment by zware** [comment]
It looks to me like Tix compatibility finally broke in Tcl/Tk 8.6.14.  I don't think it's worthwhile to try to fix Tix (which is removed from Python 3.13+ and deprecated in 3.6-3.12); I'll leave it up to your judgement whether to disable the test or skip the Tcl/Tk update on 3.12.

**Comment by zware** [comment]
I'm somewhat out of the loop here; how impactful is the update to Tcl/Tk 8.6.14 on Windows?  Is it worth @zooba's time creating a `+tix` binary package just for 3.12?  I'm afraid we can't get away with dropping Tix at this point in the 3.12 cycle.

**Comment by serhiy-storchaka** [comment]
There are plentiful of changes in 8.6.14 in comparison with previous bugfixes.

**Comment by zooba** [comment]
Do we need to create it or can we just copy it into the latest branch (and update the tag)?

**Comment by zooba** [comment]
Tix has no dependencies, so it should be fine with the last built one. I can copy it into our 8.6.14 build and tag a new .1 version, or would you prefer 8.6.15?

**Pull request closed without merging**
