### PR TITLE
Spelling fixes to docs, docstrings, and comments 

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Review by ilevkivskyi — APPROVED** [review]
Thanks!

**Review by gvanrossum — COMMENTED** [review]
I am against this. Spelling fixes just cause noise in the git history without much benefit. Also, they are often used by people with no interest in contributing further as a way to get their name in some project (though I don't know if the OP here thinks that way).

**Review by gvanrossum — CHANGES_REQUESTED** [review]
To be clear I don't want this merged at all.

**Comment by serhiy-storchaka** [comment]
@scop already contributed two doc fixes.

* 49b2734bf12dc1cda80fd73d3ec8896ae3e362f2 Spelling fixes (#2902)
* 297fd876aad8ef443d8992618de22c46dbda258b bpo-28393: Update encoding lookup docs wrt bpo-27938 (#4871)

Should we reject any typo fixes in future?

**Comment by scop** [comment]
On Wed, Apr 4, 2018 at 8:37 PM, Guido van Rossum
<notifications@github.com> wrote:
>
> Also, they are often used by people with no interest in contributing further as a way to get their name in some project (though I don't know if the OP here thinks that way).

I certainly don't, and it never was. And if you don't take my word for
it, there's already a bunch of accepted changes with my name on them
in cpython, so that ship (getting my name in the project) has already
sailed quite a while ago. Granted, most of those are related to
spelling etc fixes, but I don't think that's relevant with regards to
the suspicion about my current intent.

**Comment by gvanrossum** [comment]
OK, @scop is exonerated, but in general I still think that fixing a bunch of unrelated typos in one diff is just causing noise. It's better to fix typos only when more substantial things in the same file are changed.

I know that some other large projects have a strict policy against typo (and style) fixes on account of the noise and work it generates, though I can't quickly find a reference (maybe PHP or Rails?)

**Review by gvanrossum — APPROVED** [review]

**Comment by scop** [comment]
> @scop <https://github.com/scop> already contributed two doc fixes.
>
FWIW also at least
10a7dbd, d2a584b, 0be894b, 09c22ad, 8890bb2, 15f44ab, eb99570,
f157982, 732ba82, cebfdac, 315e104, 2a8baed.

**Comment by scop** [comment]
On Wed, Apr 4, 2018 at 10:22 PM, Guido van Rossum <notifications@github.com>
wrote:

> I hope @scop can expand his contributions to improving the text of the docs
> through clarifications, which are more important than spelling.


To be fair, I think I've contributed a few of those already, ditto some
other non-doc related fixes. But this is about enough on this topic, let's
move on, and thanks :)

**Comment by gvanrossum** [comment]
Yes, thanks for your contributions, and sorry for not knowing about them!

**Comment by terryjreedy** [comment]
I must find misspellings much more annoying than Guido, and am a bit embarrassed that I have added a few.  There have been hundreds of fixes in the past few years; they grow like weeds.

A PR spell check of (ascii) words in docs and code comments, and strings would be great.  Ville ('scop'), would you be interested in helping with this?  The main problem would be minimizing false 'errors'.  Other people (such as Mariatta) know how to write bots.

Ville, I suspect that an auto-backport to 3.7 will fail and expect that the 2.7 backport should (as the IDLE news entry is not in 2.7).  Are you willing to do the backports manually?  If so, I am willing to merge this and review and merge backports.

**Comment by scop** [comment]
I took a look at backporting to 2.7, but turns out none of the misspellings here are present there.

I would be interested in learning about writing GitHub bots, and might have some time to help out with creating one for this purpose. So sure, let me know how to get started or help out with that.

**Comment by terryjreedy** [comment]
I opened https://github.com/python/core-workflow/issues/237 - Spellcheck PRs.

All the changes merged back to 3.7.  3 to 3.6.

**Pull request merged**
