### PR TITLE
bpo-23975: Correct conversion of Rational’s to float

### PR DESCRIPTION
**Pull request by skirpichev**
Also document that numerator/denominator properties are instances of the Integral.

This solution was [suggested](https://bugs.python.org/issue23975#msg241638) by Paul Moore.

https://bugs.python.org/issue23975

### CODE REVIEW

**Comment by skirpichev** [comment]
@mdickinson, you are listed as an expert for the fractions module, could you review this little PR?  (This, probably, lacks a test.)

**Comment by mdickinson** [comment]
@skirpichev Seems like a reasonable approach to me. But as you say, it needs a test before it can go in. (There should be at least _something_ in the test suite that fails if those `int` conversions are removed.)

**Comment by skirpichev** [comment]
> But as you say, it needs a test before it can go in.

Ok, lets see how it looks.

**Comment by skirpichev** [comment]
Hmm, unfortunately, there is a silent type-cast.  I can adjust the test, but may be it does make sense to add
```diff
diff --git a/Lib/fractions.py b/Lib/fractions.py
index f9ac882ec0..4a153ee8e3 100644
--- a/Lib/fractions.py
+++ b/Lib/fractions.py
@@ -143,6 +143,10 @@ def __new__(cls, numerator=0, denominator=None, *, _normalize=True):
         elif type(numerator) is int is type(denominator):
             pass # *very* normal case
 
+        elif (isinstance(numerator, numbers.Integral) and
+            isinstance(denominator, numbers.Integral)):
+            pass
+
         elif (isinstance(numerator, numbers.Rational) and
             isinstance(denominator, numbers.Rational)):
             numerator, denominator = (
```

**Comment by skirpichev** [comment]
@mdickinson, let me know if you have some objections for added tests (maybe Lib/test/test_abstract_numbers.py is the right place to this?).  I've realized that there almost no tests for default methods of the numbers.py (#32022 address this issue, partially).

**Comment by MaxwellDupre** [comment]
The fix looks simple but where does the current implementation fail? Can you provide a test case such that the current fails but the after the fix the test succeeds?

**Comment by skirpichev** [comment]
@MaxwellDupre, the added test should be such one.  At least it was a failing test for the old main branch (~Apr 2021).

**Review by MaxwellDupre — APPROVED** [review]
LGTM

**Review by mdickinson — APPROVED** [review]
LGTM

**Pull request merged**
