### PR TITLE
bpo-22021: shutil.make_archive() root_dir do not work

### PR DESCRIPTION
**Pull request by nanjekyejoannah**
This PR fixes issue : https://bugs.python.org/issue22021.
Signed-off-by: nanjekyejoannah <nanjekyejoannah@gmail.com

https://bugs.python.org/issue22021

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by vstinner** [comment]
@nanjekyejoannah: Hum, it seems like test_shutil is failing. Can you try to investigate why it fails? (tell me if you need help)

**Comment by vstinner** [comment]
Can you please amend your commit message to mention the original author? Example:

```
Initial patch by Weinan Li.
```

About your commit message:

```
This PR fixes issue : https://bugs.python.org/issue22021.
Signed-off-by: nanjekyejoannah <nanjekyejoannah@gmail.com
```

The first line is useless: the bpo number is already part of the commit title. On the second line, ``>`` is missing, no? By the way, I don't use such Git tag usually. What is its purpose?

**Comment by nanjekyejoannah** [comment]
@vstinner I sign the commits just incase it is a requirement as most projects I have opened PRs on require. I think am too used also :) 

Review noted. I will revert with fixes for the same.

**Comment by serhiy-storchaka** [comment]
The current behavior looks correct to me. It is consistent with the behavior of the `tar` command. This change breaks tests and I think it will break user code.

Read the discussion on bpo-22021.

**Pull request closed without merging**
