### PR TITLE
Add JOBS parameter to docs Makefile

### PR DESCRIPTION
**Pull request by christopheNan**
separate parameter JOBS in order to be able to specify it in command line (used by translators who build documentation in their language)

related to https://git.afpy.org/AFPy/python-docs-fr/pulls/23

### CODE REVIEW

**Comment by christopheNan** [comment]
Would be nice to backport to 3.11

**Comment by hugovk** [comment]
Sounds reasonable. Do translators want to set it to some higher or lower value? Does `auto` not work for them?

Please could you move it in between `BLURB` and `PAPER`?

**Comment by christopheNan** [comment]
> Sounds reasonable. Do translators want to set it to some higher or lower value? Does `auto` not work for them?

'auto' is good as a default value. As far as I am concerned, it happens that I lower the value (to 1). I ask for this modification as it is transparent for default usage of the Makefile.

**Review by hugovk — APPROVED** [review]
Thank you!

**Pull request merged**
