### PR TITLE
WIP: bpo-36021: WindowsDefault does not execute os.startfile() for a local file

### PR DESCRIPTION
**Pull request by matrixise**
https://bugs.python.org/issue36021

### CODE REVIEW

**Comment by JulienPalard** [comment]
Have you tried to implement three cases instead of two:
- file://
- whitelisted schemes
- other cases

It may make the intention more readable, by removing `- set(['file', ''])` and `if parsed_url.scheme == 'file'`.

?

Also I'm not sure about the behavior of `os.access(path, os.X_OK)` in windows. Do `os.startfile` executes a `.exe` file that is not marked `X_OK`? (Not a Windows user here).

**Comment by matrixise** [comment]
@JulienPalard 
`file://` is already tested with `file:///tmp/test.txt`
for the whitelisted schemes, you have an example with `https://`

about `os.access(path, os.X_OK)`, after a small check on a Windows VM, it's not portable :/ I use an other solution in my last commit (I read the binary file and read the two first bytes `== b'MZ'`)

**Comment by matrixise** [comment]
ok, I have a whitelist and I allow the HTML files with WebBrowser.WindowsDefault()

**Review by vstinner — CHANGES_REQUESTED** [review]
I'm not sure that it's a proper fix. I propose to discuss at https://bugs.python.org/issue36021

**Comment by JulienPalard** [comment]
LGTM

**Comment by matrixise** [comment]
@JulienPalard yep, still WIP because we have a discussion about the solution on the bug tracker.

**Comment by matrixise** [comment]
There is a discussion on https://bugs.python.org/issue36021 but no real solution. I prefer to close this PR and wait for a consensus. Thank you for the review.

**Pull request closed without merging**
