### PR TITLE
gh-128058: Fix test_builtin ImmortalTests

### PR DESCRIPTION
**Pull request by vstinner**
On 32-bit systems with Free Threading, _Py_IMMORTAL_INITIAL_REFCNT is defined as 5 << 28, not 7 << 28.

* Issue: gh-128058

### CODE REVIEW

**Review by ZeroIntensity — DISMISSED** [review]
LGTM, but I'm curious about why none of our buildbots caught this. Are none of them 32 bit?

**Comment by ZeroIntensity** [comment]
So it's not a typo. It's probably what I said in the issue then:

> I think this is probably because there's a different reference count for heap immortals and static immortals now

**Comment by colesbury** [comment]
This is getting very confusing. In `Py_REFCNT()` (and `sys.getrefcount()`) we tried to make immortal objects in the free threading build appear to have the same refcount as in the default build:

https://github.com/python/cpython/blob/8a433b683fecafe1cb04469a301df2b4618167d0/Include/refcount.h#L104-L106

I'm not so sure this is a good strategy anymore now that there are so many different immortal refcounts in the default build.

**Comment by ZeroIntensity** [comment]
I'm not convinced we need a different reference count for static immortals, that's going to especially complicate things.

**Comment by vstinner** [comment]
> Tests / macOS / build and test (macos-13) (pull_request)Failing after 34s 

That's the issue gh-128069.

**Comment by vstinner** [comment]
> That's the issue https://github.com/python/cpython/issues/128069.

I updated the branch to retrieve the macOS fix.

**Review by colesbury — APPROVED** [review]

**Comment by ZeroIntensity** [comment]
Doing my best to understand the issue here. Why do we have a different immortal reference count for free threading?

**Comment by vstinner** [comment]
Merged, thanks for reviews.

**Pull request merged**
