### PR TITLE
gh-90606: Add ability to get signature of TypedDict

### PR DESCRIPTION
**Pull request by uriyyo**
#90606

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This will also need a unit test.

I'm not too convinced this is useful to add, since an `*args, **kwargs` signature doesn't really give any information. I guess we need to fix the regression though.

**Comment by gvanrossum** [comment]
Since `inspect.signature(dict)` also fails I don't see why it should be made to pass for `TypedDict` specifically.

**Comment by uriyyo** [comment]
@JelleZijlstra Maybe it makes sense to generate custom signature for `TypedDict`:
```py
import inspect
from typing import TypedDict


class TD(TypedDict):
    a: int
    b: int


inspect.signature(TD)
```
```py
<Signature (mp=None, /, *, a=None, b=None, **kwargs) -> __main__.TD>
```

I am not sure that this will be super useful. Just an idea)

**Comment by AlexWaygood** [comment]
Looks like this also causes a slowdown, though it's probably only noticeable if you're instantiating a _lot_ of `TypedDict`s:

On my machine, running on main:

```python
C:\Users\alexw\coding\cpython>python
Running Debug|x64 interpreter...
Python 3.11.0a7+ (main, Apr 14 2022, 10:41:31) [MSC v.1931 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import TypedDict
>>> T = TypedDict('T', {'foo': int})
>>> import timeit
>>> timeit.timeit(T, number=10000000)
4.352623799990397
```

With this patch applied:

```python
C:\Users\alexw\coding\cpython>python
Running Debug|x64 interpreter...
Python 3.11.0a7+ (main, Apr 14 2022, 10:41:31) [MSC v.1931 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import TypedDict
>>> T = TypedDict('T', {'foo': int})
>>> import timeit
>>> timeit.timeit(T, number=10000000)
10.428143600001931
```

**Comment by gvanrossum** [comment]
I suspect nobody feels like being the bad guy and rejecting this, so let me be it. Sorry.

**Pull request closed without merging**
