### PR TITLE
gh-101659: Isolate "obmalloc" State to Each Interpreter

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
This is strictly about moving the "obmalloc" runtime state from `_PyRuntimeState` to `PyInterpreterState`.  Doing so improves isolation between interpreters, specifically most of the memory (incl. objects) allocated for each interpreter's use.  This is important for a per-interpreter GIL, but such isolation is valuable even without it.

FWIW, a per-interpreter obmalloc is the proverbial canary-in-the-coalmine when it comes to the isolation of objects between interpreters.  Any object that leaks (unintentionally) to another interpreter is highly likely to cause a crash (on debug builds at least).  That's a useful thing to know, relative to interpreter isolation.

Benchmarking indicates the performance impact is negligible.  (I'll re-run soon to double-check.)

* Issue: gh-101659

### CODE REVIEW

**Review by erlend-aasland — DISMISSED** [review]

**Comment by ericsnowcurrently** [comment]
FYI, the current CI failures are due to existing code.  Basically, that code (in `_PyImport_FixupExtensionObject()`) tries to delete a [currently] global object that was created by a different interpreter than the "current" one.  (There *may* be a few other similarly problematic global objects.  I'll have to check.)  As to why only some of the jobs are failing: the failure is a check by the debug allocator, which is only used in `Py_DEBUG` builds.

FWIW, the failure is exactly what we should expect to happen when per-interpreter data breaks isolation.  I actually spent a while trying to figure out what I was doing wrong in my branch before realizing that everything was working as it should. 😄

**Comment by ericsnowcurrently** [comment]
I'm tabling this until we've isolated all non-static objects.

**Comment by ericsnowcurrently** [comment]
This PR is currently blocked by:

* https://github.com/python/cpython/pull/102657
* https://github.com/python/cpython/pull/102658
* https://github.com/python/cpython/pull/102659
* https://github.com/python/cpython/pull/102663
* https://github.com/python/cpython/pull/102661
* https://github.com/python/cpython/pull/102339 (or the fixes to keep it global)

**Comment by ericsnowcurrently** [comment]
FYI, as with the [per-interpreter ref total](https://github.com/python/cpython/pull/102545#issuecomment-1468208281), I'm probably going to add some code to preserve the per-interpreter allocated blocks when each subinterpreter is destroyed, so any leaks may be handled appropriately when the runtime is finalized.  I may also report the per-interpreter count at interpreter finalization.  We'll see.

**Comment by ericsnowcurrently** [comment]
FYI, I plan on looking into the failing tests on WIndows:

### Windows x64

https://github.com/python/cpython/actions/runs/4613172260/jobs/8154898824?pr=101660#step:6:773

failed:  test__xxinterpchannels

<details>
<summary>test output</summary>

initial:
```
0:17:16 load avg: 12.24 [381/433/3] test__xxinterpchannels crashed (Exit code 3221225477) -- running: test_asyncio (6 min 14 sec)
Debug memory block at address p=000002943D304900: API '�'
    18302063728033398269 bytes originally requested
    The 7 pad bytes at p-7 are not all FORBIDDENBYTE (0xfd):
        at p-7: 0xdd *** OUCH
        at p-6: 0xdd *** OUCH
        at p-5: 0xdd *** OUCH
        at p-4: 0xdd *** OUCH
        at p-3: 0xdd *** OUCH
        at p-2: 0xdd *** OUCH
        at p-1: 0xdd *** OUCH
    Because memory is corrupted at the start, the count of bytes requested
       may be bogus, and checking the trailing pad bytes may segfault.
    The 8 pad bytes at tail=FDFE00923B2E46FD are Windows fatal exception: access violation

Current thread 0x00001b18 (most recent call first):
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 589 in _callTestMethod
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 634 in run
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 690 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\runner.py", line 240 in run
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1106 in _run_suite
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1232 in run_unittest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 281 in _test_module
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 317 in _runtest_inner2
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 360 in _runtest_inner
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 219 in _runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 265 in runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest_mp.py", line 98 in run_tests_worker
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 732 in _main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 711 in main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line [775](https://github.com/python/cpython/actions/runs/4613172260/jobs/8154898824?pr=101660#step:6:776) in main
  File "D:\a\cpython\cpython\Lib\test\regrtest.py", line 43 in _main
  File "D:\a\cpython\cpython\Lib\test\regrtest.py", line 47 in <module>
  File "D:\a\cpython\cpython\Lib\runpy.py", line 88 in _run_code
  File "D:\a\cpython\cpython\Lib\runpy.py", line 198 in _run_module_as_main
```

re-run:
```
0:19:23 Re-running test__xxinterpchannels in verbose mode

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

</details


### Windows x86 (32-bit)

https://github.com/python/cpython/actions/runs/4613172260/jobs/8154897789#step:5:731

failed:  test__xxinterpchannels

<details>
<summary>test output</summary>

initial:
```
0:16:07 load avg: 9.09 [377/433/2] test__xxinterpchannels crashed (Exit code 322122[547](https://github.com/python/cpython/actions/runs/4613172260/jobs/8154897789#step:5:548)7) -- running: test_threading (41.2 sec), test_asyncio (2 min 47 sec)
Debug memory block at address p=04D0A1D8: API '�'
    4261281277 bytes originally requested
    The 3 pad bytes at p-3 are not all FORBIDDENBYTE (0xfd):
        at p-3: 0xdd *** OUCH
        at p-2: 0xdd *** OUCH
        at p-1: 0x00 *** OUCH
    Because memory is corrupted at the start, the count of bytes requested
       may be bogus, and checking the trailing pad bytes may segfault.
    The 4 pad bytes at tail=02CE9FD5 are Windows fatal exception: access violation

Current thread 0x00000508 (most recent call first):
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 589 in _callTestMethod
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 634 in run
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 690 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\runner.py", line 240 in run
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1106 in _run_suite
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1232 in run_unittest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 281 in _test_module
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 317 in _runtest_inner2
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 360 in _runtest_inner
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 219 in _runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 265 in runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest_mp.py", line 98 in run_tests_worker
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 732 in _main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 711 in main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 775 in main
  File "D:\a\cpython\cpython\Lib\test\regrtest.py", line 43 in _main
  File "D:\a\cpython\cpython\Lib\test\regrtest.py", line 47 in <module>
  File "D:\a\cpython\cpython\Lib\runpy.py", line 88 in _run_code
  File "D:\a\cpython\cpython\Lib\runpy.py", line 198 in _run_module_as_main
```

re-run:
```
test_with_kwargs (test.test__xxinterpchannels.ChannelIDTests.test_with_kwargs) ... ok
Debug memory block at address p=0218A390: API '�'
    4261281277 bytes originally requested
    The 3 pad bytes at p-3 are not all FORBIDDENBYTE (0xfd):
        at p-3: 0xdd *** OUCH
        at p-2: 0xdd *** OUCH
        at p-1: 0x00 *** OUCH
    Because memory is corrupted at the start, the count of bytes requested
       may be bogus, and checking the trailing pad bytes may segfault.
    The 4 pad bytes at tail=0016A18D are Windows fatal exception: access violation

Current thread 0x000013bc (most recent call first):
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 589 in _callTestMethod
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 634 in run
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 690 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\runner.py", line 240 in run
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1106 in _run_suite
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1232 in run_unittest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 281 in _test_module
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 317 in _runtest_inner2
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 360 in _runtest_inner
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 235 in _runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 265 in runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 353 in rerun_failed_tests
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line [756](https://github.com/python/cpython/actions/runs/4613172260/jobs/8154897789#step:5:757) in _main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 711 in main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 775 in main
  File "D:\a\cpython\cpython\Lib\test\__main__.py", line 2 in <module>
  File "D:\a\cpython\cpython\Lib\runpy.py", line 88 in _run_code
  File "D:\a\cpython\cpython\Lib\runpy.py", line 198 in _run_module_as_main
test_by_unassociated_interp (test.test__xxinterpchannels.ChannelReleaseTests.test_by_unassociated_interp) ...
```

failures in test__xxsubinterpreters are probably unrelated (I've seen them [elsewhere](https://github.com/python/cpython/actions/runs/4613103828/jobs/8154753698#step:6:960)):

```
0:10:11 load avg: 11.74 [230/433/1] test__xxsubinterpreters crashed (Exit code 3221225477)
Windows fatal exception: access violation

Thread 0x00000de4 (most recent call first):
  File "D:\a\cpython\cpython\Lib\test\test__xxsubinterpreters.py", line 80 in clean_up_interpreters
  File "D:\a\cpython\cpython\Lib\test\test__xxsubinterpreters.py", line 88 in tearDown
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 594 in _callTearDown
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 637 in run
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 690 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 122 in run
  File "D:\a\cpython\cpython\Lib\unittest\suite.py", line 84 in __call__
  File "D:\a\cpython\cpython\Lib\unittest\runner.py", line 240 in run
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1106 in _run_suite
  File "D:\a\cpython\cpython\Lib\test\support\__init__.py", line 1232 in run_unittest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 281 in _test_module
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line [317](https://github.com/python/cpython/actions/runs/4613172260/jobs/8154897789#step:5:318) in _runtest_inner2
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 360 in _runtest_inner
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 219 in _runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest.py", line 265 in runtest
  File "D:\a\cpython\cpython\Lib\test\libregrtest\runtest_mp.py", line 98 in run_tests_worker
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 732 in _main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 711 in main
  File "D:\a\cpython\cpython\Lib\test\libregrtest\main.py", line 775 in main
  File "D:\a\cpython\cpython\Lib\test\regrtest.py", line 43 in _main
  File "D:\a\cpython\cpython\Lib\test\regrtest.py", line 47 in <module>
  File "D:\a\cpython\cpython\Lib\runpy.py", line 88 in _run_code
  File "D:\a\cpython\cpython\Lib\runpy.py", line 198 in _run_module_as_main
```

</details

**Comment by ericsnowcurrently** [comment]
FYI, benchmarking results roughly indicate a 1% regression.

**Pull request merged**
