### PR TITLE
Remove reference to address from the docs, as it only causes confusion

### PR DESCRIPTION
**Pull request by Rosuav**
Docs-only change, removing a bit of phrasing that's caused endless confusion. If this is deemed non-trivial, I can take it to BPO for discussion.

### CODE REVIEW

**Comment by elazarg** [comment]
Social security number is not a universally familiar term.

**Comment by Rosuav** [comment]
True, which is why I also mentioned license numbers - many locations have those, eg driver licensing etc. The idea is that it should resonate as something assigned to someone, rather than where someone can be found.

**Comment by elazarg** [comment]
When I saw the term license the first thing I thought was "something that allows me to use this object". And even though this might be true in some sense (though probably not what you meant), it is not less confusing. Maybe these are helpful in addition to "memory location".
The most precise explanation is something along the lines of "the thing that defines whether to object are one" but I can see the problems in this description too. 

Sorry for not being constructive here. I just wanted to say that reading this as a 15 year old developer (which I am not) from Israel, I would probably be more confused than with the original description.

**Comment by Rosuav** [comment]
Oh, it's definitely constructive, and I have no problem with it! But the problem - as can be seen frequently on python-list - is that talking about memory addresses causes people to think that they ARE addresses, which (a) isn't true except on CPython, and (b) doesn't actually help anyway, as you can't use the id as a pointer. Hence trying to explain it differently.

**Comment by serhiy-storchaka** [comment]
It should be discussed on the bug tracker or on the Python-Dev mailing list.

The term "address in memory" is common. I have no idea what "license number" or "social security number" of object are. Does it have relation to permissions control?

**Comment by merwok** [comment]
I think comments show that this requires a bpo ticket, and/or a mailing list discussion, to show how the current text causes confusion and make sure new text is better.

**Comment by matrixise** [comment]
@Rosuav I have just opened a discussion on `python-dev` here is the link https://mail.python.org/pipermail/python-dev/2018-November/155649.html
I propose to discuss about your PR and if there is no comments, I suggest to close your PR. Wait&See and thank you for your contribution.

**Comment by methane** [comment]
"license number" or "social security number" are reused soon after it's invalidated?

`id(f()) is id(f())` can be True even if `f() is f()` is False.  It's because id is reused very quickly.

I feel "address of memory" is more understandable...

**Comment by Rosuav** [comment]
The trouble is that saying that it's a memory address leads to people asking questions like "How do I get an object, given its id?". If you have an object's address, it does make sense to dereference that (which you can happily do with C pointers, incl with the ctypes module). Python objects have identities, not addresses. In a lot of systems, identity numbers aren't reused too soon, to avoid confusion; but many of them do permit eventual reuse. Does anyone know how player numbers are assigned in various sports?

**Comment by Rosuav** [comment]
I'm just imagining a young child whining "But whyyyyyyyyyyyyy?"... :) Yeah, that might work, I guess. But I still don't like having any reference to memory at all. It might be helpful to people who understand lower level languages like C, but for them it'll also be a false analogy. For people who don't know how memory works, is it truly helpful?

**Comment by matham** [comment]
How about just `"a number assigned to it when it is created"`.

**Comment by elazarg** [comment]
And does not belong to any other object as long as it's alive.

**Comment by serhiy-storchaka** [comment]
Young children know that that there are many things that they do not understand. And you can get the same "But whyyyyyyyyyyyyy?" about "license number" and "social security number" which may be more false analogies.

**Comment by Rosuav** [comment]
You know what? I don't care any more. Put whatever you want in the docs; I'm done fighting for this.

**Comment by csabella** [comment]
Looking for direction on this issue as it is languishing in its current state.  Based on the thread on python-dev, it seems that a change to the wording is desirable and perhaps removing any analogy is the best way forward.  Should an issue be opened on the bug tracker for further discussion?  Should this PR be closed pending that discussion?  Thanks!

**Comment by merwok** [comment]
I think opening and ticket to keep track of the problem (and link to previous discussions of it) and closing this specific PR sounds good.

**Comment by JulienPalard** [comment]
In some countries the licence plates are bound to a person, on some other countries they are bound to a vehicule. I'd definitly avoid using this analogy.

As you proposed initially @Rosuav, please open a b.p.o issue around it.

Proposed wording while I'm here is to replace `address in memory` by `address (in memory)`.

**Comment by Rosuav** [comment]
I never said "licence plate", and never suggested that as an analogy. And no, I'm not going to open a bpo issue, because apparently nobody can agree on good wording.

**Comment by matrixise** [comment]
Thank you for your contribution, but because there is no bpo issue and because this PR could be ambiguous depending on the country, I prefer to close it.

**Comment by JulienPalard** [comment]
> I never said "licence plate", and never suggested that as an analogy. And no, I'm not going to open a bpo issue, because apparently nobody can agree on good wording.

Sorry about it! So I don't know what's a "license number" is (I'm french), maybe I'm not alone not understanding this analogy and maybe address is easier.

I agree with closing this PR, address works for most people and it's hard to find a better analogy. If one find a better one, don't hesitate to comment though.

**Comment by Rosuav** [comment]
The trouble is, "address" is straight-up wrong, but all the people who have the power to make the decisions find that "address" fits their brains, so it's absolutely fine for them. Every other analogy is flawed too. But like I said, I'm done fighting this, so whatever, PR closed.

**Comment by elazarg** [comment]
On the contrary; "address" is _technically_ precise, at least in the sense of formal language semantics. Of course you are right that it might be confusing for some (mostly to people with understanding of low-level implementation detail).

**Comment by Rosuav** [comment]
@elazarg I don't understand. Do you mean that an object's id actually IS its address in some way, as defined by Python's formal language semantics?

**Comment by merwok** [comment]
Well, `memory address` is only a CPython implementation detail, and with some issues (ID reuse!), so it is definitely not part of the language reference!

This is why a ticket is needed, and rewording that line would be a good thing.
(I seem to recall other parts of the doc already mention that it’s only an implementation detail, will search later)

**Comment by elazarg** [comment]
@Rosuav exactly. 
@merwok do you mean that two different objects might have the same ID at the same time?

**Comment by merwok** [comment]
Not at the same time!

**Comment by merwok** [comment]
> exactly

No, the format Python language definition defines `id` as returning something opaque.  Using memory address is a CPython implementation detail.

**Comment by elazarg** [comment]
Then it is a memory address - in the "abstract" (or virtual) machine, defined by the language. It need not correspond to a memory address in the underlying machine, but it might.

**Comment by merwok** [comment]
I find your wording confusing.  The docs are clear: https://docs.python.org/3/library/functions.html#id

> Return the “identity” of an object. This is an integer which is guaranteed to be unique and constant for this object during its lifetime. Two objects with non-overlapping lifetimes may have the same id() value.

**Comment by elazarg** [comment]
This is precisely what void pointer in C, or an object reference in Java, are. This is what people call "address".

Whether the language gives any way to dereference or cast it is a different matter. And whether it correspond to virtual addresses in the machine (or not), is indeed implementation details.

The word "identity" is fine, but "address" is precisely identity minus lifetime information.

**Pull request closed without merging**
