### PR TITLE
gh-93040 Wrap unused parameters in Objects/obmalloc.c with Py_UNUSED

### PR DESCRIPTION
**Pull request by ghost**
Issue #93040. 

This PR wraps unused parameters with `Py_UNUSED()` in the following functions from `obmalloc.c`:
 - `_PyMem_RawMalloc`
 - `_PyMem_RawCalloc`
 - `_PyMem_RawRealloc`
 - `_PyMem_RawFree`
 - `_PyObject_ArenaVirtualAlloc`
 - `_PyObject_ArenaVirtualFree`
 - `_PyObject_ArenaMmap`
 - `_PyObject_ArenaMunmap`
 - `_PyObject_ArenaMalloc`
 - `_PyObject_ArenaFree`
 - `address_in_range`
 - `pymalloc_alloc`
 - `pymalloc_free`

`address_in_range()` is a special one out of this list as there are different versions of this function depending on the value of a macro. I have only added `Py_UNUSED()` for the version that does not use the `pool` parameter.

### CODE REVIEW

**Comment by oda-gitso** [comment]
cc @erlend-aasland @vstinner for your involvement in the issue.

**Review by erlend-aasland — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
Merged, thanks. I don't think that this change should be backported, unless some C compilers emit many warnings when building Python 3.10 and 3.11.

**Comment by oda-gitso** [comment]
Thanks @vstinner @erlend-aasland!

**Pull request merged**
