### PR TITLE
bpo-36329: Remove 'make -C Doc serve' in favour of 'make -C Doc htmlview'

### PR DESCRIPTION
**Pull request by hugovk**
Matching Devguide PR: https://github.com/python/devguide/pull/826.

Also updated `make -C htmlview` so it used a full path with `file://`, because the original didn't open the page (macOS).

For example:
```sh
cd Doc

# Doesn't open anything:
python3 -c "import webbrowser; webbrowser.open('build/html/index.html')"

# Opens the docs page e.g. file:///Users/hugo/github/cpython/Doc/build/html/index.html :
python3 -c "import os, webbrowser; webbrowser.open('file://' + os.path.realpath('build/html/index.html'))"
```

https://bugs.python.org/issue36329

### CODE REVIEW

**Comment by encukou** [comment]
Could you make `serve` echo `The serve target was removed, use htmlview instead (see bpo-36329)`, to help anyone still using it?
Also, could you keep the example in `wsgiref` docs? It has a purpose there. (Maybe it could be simplified to focus on serving, better commented, and moved to Doc/, of course. But it shouldn't be removed.)

**Comment by hugovk** [comment]
Updated! How does this look?

**Review by encukou — APPROVED** [review]
Looks great, thank you!

Sorry for the delay, this fell off my list :(

**Comment by hugovk** [comment]
Thanks for the review/merge! Any chance of checking the devguide one? https://github.com/python/devguide/pull/826

**Pull request merged**
