### PR TITLE
bpo-39421: Fix posible crash in heapq with custom comparison operators

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue39421

### CODE REVIEW

**Review by corona10 — CHANGES_REQUESTED** [review]
```python
import heapq

class h(int):
    def __lt__(self, o):
        list2.clear()
        return NotImplemented

class g(int):
    def __lt__(self, o):
        list1.clear()
        return NotImplemented

list1, list2 = [], []

heapq.heappush(list1, h(0))
heapq.heappush(list2, g(0))

print(list1)
print(list2)

heapq.heappush(list1, g(1))
heapq.heappush(list2, h(1))
print(list1)
print(list2)
```

This PR does not fix this case. Please take a look

**Comment by pablogsal** [comment]
> This PR does not fix this case. Please take a look

Thanks! I added a test in 9718f66

**Review by corona10 — APPROVED** [review]
LGTM

Just comment:
In some time, if we can pass objects as a variadic argument.
The code might be cleaner. (I don't deeply think about the possibility)

e.g. Py_INCREF(a, b, c...); Py_DECREF(a, b, c...);

**Comment by pablogsal** [comment]
> e.g. Py_INCREF(a, b, c...); Py_DECREF(a, b, c...);

We would need a different function as C99 does not allow overloads for `va_list` and I don't think is that common

**Comment by pablogsal** [comment]
I would like to wait to see if @vstinner and @methane would prefer to add the check into `PyObject_RichCompareBool` instead although I think it would be too costly.

**Review by methane — APPROVED** [review]

**Comment by alex** [comment]
This should be backported to all branches that are still doing security releases.

**Pull request merged**
