### PR TITLE
[3.9] bpo-40204: Allow pre-Sphinx 3 syntax in the doc (GH-21844)

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue40204

### CODE REVIEW

**Comment by vstinner** [comment]
cc @hroncok ;-)

**Comment by hroncok** [comment]
Thank you. Shall I test it in Fedora?

**Comment by vstinner** [comment]
> Thank you. Shall I test it in Fedora?

It's not needed.

Before backporting changes, I checked in the master branch that the documentation is still rendered properly with Sphinx 2 at https://docs.python.org/dev/ I tested manually in a virtual environment that the documentation builds without warnings in 3.9 (this PR) and master branches: the documentation is built with -W (treat warnings as errors).

**Comment by vstinner** [comment]
@ambv @pablogsal: This change is not a bug fix, but more like a feature: support Sphinx 3. I would like to merge it into the 3.9 branch, but it can wait after 3.9.0 final. Can I merge it now? I never know if changes after RC1 after cherry-picked in a release branch, or if you use directly the 3.9 branch for releases between RC1 and the final release.

**Comment by vstinner** [comment]
cc @doko42

**Comment by ambv** [comment]
If there isn't a flurry of commits into 3.9 I'd rather avoid cherry-picking because it makes it harder to merge back post-release. In this particular case, since this is documentation, I think this is allowed.

**Review by ambv — APPROVED** [review]

**Comment by vstinner** [comment]
> In this particular case, since this is documentation, I think this is allowed.

Thanos, I merged ou PR.

**Pull request merged**
