### PR TITLE
gh-101135: Windows launcher: Add backwards compatibility for older 32-bit versions

### LINKED ISSUE #101135: Windows py launcher: older 32-bit versions not supported in some cases
# Bug report

On 64-bit Windows, if both Python 2.7 32-bit and Python 2.7 64-bit are installed, these two installs are considered equivalent and only the 64-bit version is considered, both when running `py -2-32` (which fails) and `py -0` (which only displays the 64-bit version).

This is also the case for Python 3.4 and lower, as the "-32" suffix is only part of the tag in the registry in 3.5+.

Under `C:\`:
image

`py -0p` output:
image

While these versions are no longer officially supported since 2020, [PEP-514](https://peps.python.org/pep-0514/) does have a section on backwards compatibility, mentioning:
> To ensure backwards compatibility, applications should treat environments listed under the following two registry keys as distinct, even when the Tag matches:
> ```
> HKEY_LOCAL_MACHINE\Software\Python\PythonCore\<Tag>
> HKEY_LOCAL_MACHINE\Software\Wow6432Node\Python\PythonCore\<Tag>
> ```

# Your environment

- CPython versions tested on: 3.11.1
- Operating system and architecture: Windows 10 x64

### Linked PRs
* gh-101138
* gh-101290

### PR DESCRIPTION
**Pull request by boimart1**
`py -0p` output, with this fix:

image

For 32-bit installs, these versions did not contain the "-32" in their registry name, so the 32 and 64-bit installs were treated equal.

Additionally, there were a few related bugs in the code to add nodes to the EnvironmentInfo tree:
* All nodes' `parent`s were always `NULL`
* If two nodes compared equal, the one one was "chosen" (the sort key condition was reversed). However, due to the NULL parent problem, nodes were never actually replaced in the tree.
* Even when a node was meant to be replaced, there was no `freeEnvironmentInfo()` on the removed node.

Finally, `_listAllEnvironments` now displays `-32` in the tag for PythonCore 32-bit versions which don't have the suffix already.

An alternative fix would have been to add `-32` to the tag name for PythonCore 32-bit versions which don't have it in the name. I can go back and implement it that way instead if this approach seems too complicated -- however, that would involve adding a few functions to properly update the tag without leaking.

* Issue: gh-101135

### CODE REVIEW

**Comment by zooba** [comment]
> An alternative fix would have been to add -32 to the tag name for PythonCore 32-bit versions which don't have it in the name. I can go back and implement it that way instead if this approach seems too complicated -- however, that would involve adding a few functions to properly update the tag without leaking.

I'd prefer this fix. Ideally this would be easy to remove when we decide that we _actually_ don't care about end-of-life versions, since apparently it's too soon for that. Use the `allocSearchInfoBuffer` function to allocate a new buffer - these get attached to the `SearchInfo` structure and won't leak.

**Comment by zooba** [comment]
The `parent` fixes are good though, thanks! I thought I had tests that would ensure it was handling duplicated nodes properly, but I guess not.

**Comment by boimart1** [comment]
> env.architecture isn't actually a good enough check if you care about EOL'd versions, you need to add GetBinaryType calls for when searching the HKCU registry key and assume 64-bit/32-bit based on the WOW6432Node selection for HKLM keys

For the HKLM entries, I believe this is already covered by the `fallbackArch` argument, which sets `env.architecture` to the correct value based on which registry section was searched.
https://github.com/python/cpython/blob/e9d5bb902fe72106c56204d0f7ec2fb238fda67d/PC/launcher2.c#L1489-L1491

Good point on the HKCU entries though. I'll see where I can fit that in.

So, to recap:
* add detection of 32bit vs 64bit to HKCU entries,
* add "-32" to the tag name of the 32-bit entries which don't have it,
* constrain these two checks to PythonCore 2.X and 3.5 and lower,
* remove `_compareArch`, since architecture comparison it will be implicit with the "-32" suffix always being present in the tag name,
* also remove the new code in `_listAllEnvironments` which appended "-32".

**Comment by zooba** [comment]
That sounds good.

Also verify that a command like `py -2.7` will select `2.7-32` if that's the only option. It _should_, but my confidence in all my contributions over the last few months has been pretty well shattered, so check my work :)

**Comment by boimart1** [comment]
Did a bunch of manual testing with 3.4 (fully pre-PEP 514) and 3.5 (includes executablePath and the "-32" in the tag for 32bit installations, but not full PEP 514), plus a few tests with 3.6 (follows PEP 514). I made sure to have the following behavior, as written in [PEP 397](https://peps.python.org/pep-0397/):
* `py -X.Y` uses the 64-bit installation if there is one, 32-bit otherwise
* `py -X.Y-64` uses the 64-bit installation, fails if there is none
* `py -X.Y-32` uses the 32-bit installation, fails if there is none
In all cases, if the same version+architecture exists in both HKCU and HKLM, the HKCU entry is preferred.

**Pull request merged**
