### PR TITLE
bpo-29643: Fix check for --enable-optimizations

### PR DESCRIPTION
**Pull request by ts826848**
The presence of the --enable-optimizations flag is indicated by the
value of $enableval, but the configure script was checking $withval,
resulting in the --enable-optimizations flag being effectively ignored.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/22867185/d3aedcf8-f137-11e6-8469-d5f7861a1073.png)
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by ts826848** [comment]
I have signed the CLA.

**Comment by zhangyangyu** [comment]
It would be nice to open an issue on http://bugs.python.org/ to track this problem. And don't forget to nosy @brettcannon .

**Comment by brettcannon** [comment]
My Makefile knowledge is fairly limited so I'm adding @gpshead to see if he is up for reviewing. If not then I can handle it.

And can you open an issue on bugs.python.org for this, @aw1621107 ?

**Comment by ts826848** [comment]
Oops, forgot about that. Submitted [issue 29643](https://bugs.python.org/issue29643). Sorry about the delay.

**Comment by gpshead** [comment]
thanks, this change looks good.

**Comment by gpshead** [comment]
When checking it in, we need to check in regenerated configure files along with it.  but that could make easy backporting/merging a pain.  do we have a process preference for configure.ac & configure changes?  or just leave it up to whomever is merging?

**Comment by brettcannon** [comment]
@gpshead I think we have a version requirement specified in configure.ac, but otherwise the committer just runs autoconf and commits both configure.ac and configure.

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by methane** [comment]
I'm sorry.  I failed to merge master and I used `push --force` to solve it.
If curious notify sent to you, please ignore it.

**Comment by methane** [comment]
When I ran autoreconf, unrelated changes (pkg-config 0.29 -> 0.29.2) happens.
Should I remove the change?

**Comment by ned-deily** [comment]
@methane: The change to aclocal.m4 should not matter one way or another.  You can leave it in or not.

**Pull request merged**
