### PR TITLE
bpo-46249: Move set `lastrowid` out of the `sqlite3` query loop

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue46249

### CODE REVIEW

**Comment by erlend-aasland** [comment]
(GitHub would not let me resurrect GH-30371 because I deleted the original branch.)

**Comment by erlend-aasland** [comment]
Skipping news as it is an internal change only. No user visible effects.

**Comment by felixxm** [comment]
I confirmed this doesn't break anything in Django tests :heavy_check_mark:

**Review by corona10 — APPROVED** [review]
I've looked closely at the change, but it doesn't seem like a regression will happen. 
LGTM

**Comment by erlend-aasland** [comment]
Thanks for reviewing, Dong-hee!

**Pull request merged**
