### PR TITLE
bpo-30964: Mention ensurepip in package installation docs

### PR DESCRIPTION
**Pull request by NicholasKobald**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by NicholasKobald** [comment]
I have signed the CLA.

**Review by ncoghlan — APPROVED** [review]

**Comment by ncoghlan** [comment]
Thanks! As a first-time contributor, would you mind also adding yourself to the appropriate location in the Misc/ACKS file before I merge the PR?

**Comment by ncoghlan** [comment]
Thanks once again :)

This update should also be backported to the 2.7 & 3.6 maintenance branches as covered in https://docs.python.org/devguide/gitbootcamp.html#backporting-merged-changes

If you're willing & able to create those backport PRs yourself (and request a review from me), that would be greatly appreciated, otherwise I'll create them at some point :)

**Comment by NicholasKobald** [comment]
Thanks for the link, I'll give it a shot.

**Comment by ncoghlan** [comment]
@NicholasKobald Since it's now clear the backporting instructions are incomplete, I'd be interested in your feedback on whether or not https://github.com/python/devguide/issues/238#issuecomment-316909188 would help clarify the required additional steps.

**Pull request merged**
