### PR TITLE
bpo-31245: asyncio: Fix typo, isistance => isinstance

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue31245

### CODE REVIEW

**Comment by vstinner** [comment]
Typo spotted while using pyflakes on the stdlib.

**Review by 1st1 — APPROVED** [review]

**Comment by vstinner** [comment]
cc  @ovv

**Comment by 1st1** [comment]
Ideally need a regression test to trigger a NameError in current master branch.

**Comment by vstinner** [comment]
> Ideally need a regression test to trigger a NameError in current master branch.

Sorry, I'm too lazy to do that. I only wanted to fix an obvious typo fixed in a recent commit ;-)

**Comment by ovv** [comment]
My bad, I should have catch that. Thanks @vstinner

**Comment by vstinner** [comment]
> My bad, I should have catch that. Thanks @vstinner

No problem. If you want, you may write an unit test which tests also this code path. Since the bug was not catched by the tests, it seems like we miss some tests. Sorry, I didn't look at https://bugs.python.org/issue31245

**Pull request merged**
