### PR TITLE
bpo-32650: Add native coroutine support to bdb when stepping over line

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue32650

CC: @asvetlov

### CODE REVIEW

**Comment by asvetlov** [comment]
Thank you for patch but tests are needed.
You can take a look on tests from initial commit 8820c239f77 which had introduced generator based coroutines.
Copying generator tests but replacement generators with async defs would be easiest way I believe.

**Comment by pablogsal** [comment]
@asvetlov  I think is more complicated as coroutines are not iterable objects. Take for example `test_pdb_next_command_for_generator`. Replacing `def` for `async def` in `test_gen` will raise `TypeError` on next(it).

**Comment by asvetlov** [comment]
I did mean not literal replacement but pointing on bdb tests style and required functionality.

**Comment by pablogsal** [comment]
@asvetlov My bad, I did not understood your comment correctly. I will try to generate the required tests. Thanks for the comments :)

**Comment by asvetlov** [comment]
No problem.

**Comment by pablogsal** [comment]
This is the output without this patch for comparison:

```
> /home/pablogsal/github/cpython/cosa.py(10)test_f()
-> await test_gen()
(Pdb) s
--Call--
> /home/pablogsal/github/cpython/cosa.py(3)test_gen()
-> async def test_gen():
(Pdb) s
> /home/pablogsal/github/cpython/cosa.py(4)test_gen()
-> await asyncio.sleep(0)
(Pdb) n
--Return--
> /home/pablogsal/github/cpython/cosa.py(4)test_gen()->None
-> await asyncio.sleep(0)
(Pdb)
--Return--
> /home/pablogsal/github/cpython/cosa.py(10)test_f()->None
-> await test_gen()
(Pdb)
--Call--
> /usr/lib/python3.6/asyncio/base_events.py(564)call_soon()
-> def call_soon(self, callback, *args):
(Pdb) s
> /usr/lib/python3.6/asyncio/base_events.py(574)call_soon()
-> self._check_closed()
(Pdb) s
--Call--
> /usr/lib/python3.6/asyncio/base_events.py(355)_check_closed()
-> def _check_closed(self):
(Pdb) c
```

**Comment by asvetlov** [comment]
Looks perfect, please go ahead

**Comment by asvetlov** [comment]
@1st1 @njsmith you may be interesting in the PR

**Comment by 1st1** [comment]
Andrew, I don't use pdb myself, so if you think the change is ok please feel free to merge it.

**Comment by 1st1** [comment]
Keep in mind that it's better to be merged now in order for it to make it to beta1.

**Comment by pablogsal** [comment]
We can merge it now without closing the issue and implement more tests later if you are Ok with that.

@1st1 Do you think there is a better way to test this behaviour without invoking the coroutines though the event loop?

**Comment by asvetlov** [comment]
Sounds like a plan

**Review by asvetlov — APPROVED** [review]

**Comment by 1st1** [comment]
You can just manually advance a coroutine a with coro.send() method.

**Comment by asvetlov** [comment]
@pablogsal I'm going to sleep.
Please make a next PR with missing tests

**Comment by asvetlov** [comment]
Thanks for contribution!

**Comment by 1st1** [comment]
Maybe you should also handle CO_ASYNC_GENERATOR flag.

**Comment by pablogsal** [comment]
@1st1 I am adding this in #5403

**Pull request merged**
