### PR TITLE
bpo-40275: Adding filesystem_helper submodule in test.support

### PR DESCRIPTION
**Pull request by shihai1991**
Add a new test.support.filesystem_helper submodule and move TESTFN to filesystem_helper.

https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by shihai1991** [comment]
@vstinner Hi, victor. Pls take a look if you have free time, thanks.

**Review by vstinner — CHANGES_REQUESTED** [review]
Sorry, I cannot review a PR modifying 100+ files. You may try to add a new submodule which first adds aliases to support symbols, create small PRs to update tests (ex: PR for 20 tests), and then really move symbols from support to the new submodule.

I mean something like that for support/filesystem_helper.py:

```
from test.support import TESTFN
```

I expect the first PR to only modify 3 files: `support/__init__.py`, the new submodule and test.rst.

**Comment by shihai1991** [comment]
> Sorry, I cannot review a PR modifying 100+ files. You may try to add a new submodule which first adds aliases to support symbols, create small PRs to update tests (ex: PR for 20 tests), and then really move symbols from support to the new submodule.
> 
> I mean something like that for support/filesystem_helper.py:
> 
> ```
> from test.support import TESTFN
> ```
> 
> I expect the first PR to only modify 3 files: `support/__init__.py`, the new submodule and test.rst.

Thanks for your suggestion, victor.  I will update this PR.

**Comment by vstinner** [comment]
> Thanks for your suggestion, victor. I will update this PR.

I close this PR which has way too many reviewers.

**Pull request closed without merging**
