### PR TITLE
Typo - Update util.py

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
I don't think this one requires CLA, it's my first (tiny) contribution, just fixing two typos (otherwise I will likely not do more, I mostly help JuliaLang). Commits in public domain, feel free to merge even without giving me credit.

**Comment by sobolevn** [comment]
All contrinutions require CLA signing :(

**Comment by AA-Turner** [comment]
> All contributions require CLA signing :(

It used to be possible to override the CLA checks for minor contributions such as this, but the new CLA assistant tool doesn't let you.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Review by brettcannon — APPROVED** [review]

**Comment by hauntsaninja** [comment]
Closing since OP hasn't signed CLA, PR is trivial and now has merge conflicts

**Comment by PallHaraldsson** [comment]
It's fixed now, but note though same typo here:
https://github.com/python/cpython/blob/cb1bf89c4066f30c80f7d1193b586a2ff8c40579/Lib/importlib/util.py#L135

**Pull request closed without merging**
