### PR TITLE
[3.6] bpo-34563: Fix for invalid assert on big output of multiprocessing.Process (GH-9027)

### PR DESCRIPTION
**Pull request by ahcub**
https://bugs.python.org/issue34563

### CODE REVIEW

**Comment by tirkarthi** [comment]
Just as an update Appveyor build failure is tracked here : https://bugs.python.org/issue34575

Thanks

**Comment by tirkarthi** [comment]
There is a REST API to clear the cache manually. I have added this at https://bugs.python.org/msg324613 . Maybe someone with credentials can try to see if it helps.

Ref : https://github.com/appveyor/ci/issues/985

Thanks

**Comment by vstinner** [comment]
AppVeyor hits https://bugs.python.org/issue34575 bug

**Comment by vstinner** [comment]
The AppVeyor is currently not mandatory. I'm quite sure that the fix is good, and we have post-commit tests using buildbots on 3.6, so I merged your PR.

**Comment by ahcub** [comment]
awesome, thank you!

**Pull request merged**
