### PR TITLE
bpo-28533: Remove asyncore, asynchat, smtpd modules

### PR DESCRIPTION
**Pull request by vstinner**
Remove the asyncore and asynchat modules, deprecated in Python
3.6: use the asyncio module instead.

Remove the smtpd module, deprecated in Python 3.6: the aiosmtpd
module can be used instead, it is based on asyncio.

* Remove asyncore, asynchat and smtpd documentation
* Remove test_asyncore, test_asynchat and test_smtpd
* Rename Lib/asynchat.py to Lib/test/support/_asynchat.py
* Rename Lib/asyncore.py to Lib/test/support/_asyncore.py
* Rename Lib/smtpd.py to Lib/test/support/_smtpd.py
* Remove DeprecationWarning from private _asyncore, _asynchat and
  _smtpd modules
* _smtpd: remove deprecated properties

https://bugs.python.org/issue28533

### CODE REVIEW

**Comment by vstinner** [comment]
A year ago @aeros worked on a patch: https://github.com/aeros/cpython/tree/remove-asycore-asynchat-smtpd

Kyle mentioned the PEP 594. I prefer to not mention it since this PEP is still a draft. IMO the deprecation and linked to bpo issues is enough to justify the removals.

cc @tiran

**Review by warsaw — APPROVED** [review]

**Review by orsenthil — APPROVED** [review]
LGTM. Thank you, @vstinner  :)

**Review by tiran — APPROVED** [review]

**Review by gvanrossum — APPROVED** [review]
It's time for these long-deprecated packages to leave.

**Review by vsajip — APPROVED** [review]

**Comment by vstinner** [comment]
I looked at buildbot failures:

* AMD64 Windows10: unrelated, test_importlib failed. It looks like a Git clone issue. Not sure why it occurs on "PR" builds.
* AMD64 Arch Linux Asan PR: unrelated, https://bugs.python.org/issue45797

**Comment by vstinner** [comment]
Merged. I prefer to merge such change early in the 3.11 devcycle, so we can revert it if it breaks too many projects.

Thanks for the reviews and approvals!

**Comment by Karlson2k** [comment]
In the meantime the [suggested replacement](https://github.com/aio-libs/aiosmtpd) supports [Python versions up to 3.9](https://github.com/aio-libs/aiosmtpd#supported-testenvs). Python 3.10 and later is not supported.
There is [no single commit in the past 14 months in the repo](https://github.com/aio-libs/aiosmtpd/commits/master). 
Python 3.11 will be released without working replacement. The suggested replacement is not compatible with 3.11.

**Pull request merged**
