### PR TITLE
gh-92223: Remove pre-Python 3.7 alternative

### PR DESCRIPTION
**Pull request by srittau**
#92223

### CODE REVIEW

**Comment by srittau** [comment]
Do docs-only changes like this need a NEWS entry?

**Comment by srittau** [comment]
Also, we could keep the example, but without the `ensure_future()` alternative, but I'm not sure it's worth it for the remaining, rather trivial part.

**Comment by AlexWaygood** [comment]
We could probably also get rid of the "(requires 3.7+)" note at Line 23.

**Comment by srittau** [comment]
> We could probably also get rid of the "(requires 3.7+)" note at Line 23.

Good catch, done.

**Comment by AlexWaygood** [comment]
> Also, we could keep the example, but without the `ensure_future()` alternative, but I'm not sure it's worth it for the remaining, rather trivial part.

There are lots of examples elsewhere in this document of how to use `create_task`, so personally I think it's fine to just ditch the example.

**Review by AlexWaygood — APPROVED** [review]

**Review by JelleZijlstra — APPROVED** [review]

**Review by kumaraditya303 — APPROVED** [review]

**Pull request merged**
