### PR TITLE
gh-119517: Fixes for pasting in pyrepl

### PR DESCRIPTION
**Pull request by godlygeek**
Drastically improve the performance of pyrepl when pasting large amounts of text.

CC: @pablogsal

* Issue: gh-119517

Do-over of https://github.com/python/cpython/pull/120251 which I made a mess of 😓.

### CODE REVIEW

**Comment by pablogsal** [comment]
@treyhunner can you give this PR a test? This PR doesn't do lazy refresh approach and in my testing, makes pasting as fast as the old REPL

**Comment by treyhunner** [comment]
@pablogsal This works great for me! 👍

I was able to paste the entire text of Frankenstein in under 4 seconds! (was ~20 seconds before this change)

I can see the full output of the pasted text. This is particularly helpful when pasting just a few hundred lines of text.

This will be a **very big improvement** for my use case. 👏

---

The only (very slight) odd thing I noticed is the `(paste)` prompt and `...` prompt are both used (with `...` just at the end) in different parts of the pasted text. That leads to a slight misalignment due to `(paste)` being 4 characters longer than `...`.

Example snippet:

```
Python 3.14.0a0 (main, Jun 10 2024, 09:49:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(paste) us_states = [
   [removed states]
(paste)     "Montana",
(paste)     "Nebraska",
(paste)     "Nevada",
...     "New Hampshire",
...     "New Jersey",
...     "New Mexico",
    [removed states]
>>>
```

As @pablogsal noted in #120234, IPython only shows the last terminal-sized chunk of output when scrolling up through history so this is a **fairly minor issue**.

However, I do anticipate that the current behavior will occasionally raise eyebrows from new Python users and may require a bit of hand-waving to explain it away.

Personally, I'd love to see `...` used in paste mode (for consistency with the old REPL) because I plan to only ever use paste mode via bracketed paste. If lacking a distinct prompt for pastse mode might confuse some folks, maybe using `(p)` as the prompt (since it's 3 characters) might make sense.

Again though, this issue is minor and I doubt it would cause frequent confusion for new users.

Thank you for the big improvement @godlygeek.

**Comment by pablogsal** [comment]
I think there is an easy fix for the prompt issue: just use the paste prompt on non-bracketed-paste mode (which is the original reason we added it, so a user typing manually can know that's in paste mode). WDYT @godlygeek ?

**Comment by godlygeek** [comment]
I think that only showing the indicator when the user explicitly toggled on paste mode is a good idea. I also think that showing the indicator on every line is surprising. Even in manual paste mode, I'd only do a pasting indicator either on the line currently being edited, or (preferably) on the message line (where messages like "[ not unique ]" show up during tab completion).

**Comment by pablogsal** [comment]
I'm happy to do either, so let's change it

**Comment by pablogsal** [comment]
@godlygeek I have made some small changes like encapsulating the cached data into a class and deactivated the prompt for paste in bracketed paste mode. I will land after the tests pass

**Comment by hugovk** [comment]
This needs a NEWS file or skip-news label to auto-merge.

**Review by pablogsal — APPROVED** [review]

**Comment by lysnikolaou** [comment]
FWIW it still takes about 20 seconds to paste in the entire text of Frankenstein for me.

**Comment by godlygeek** [comment]
> FWIW it still takes about 20 seconds to paste in the entire text of Frankenstein for me.

Did you check how long it takes in 3.13b1? Is this PR faster, or no improvement whatsoever?

**Comment by pablogsal** [comment]
> FWIW it still takes about 20 seconds to paste in the entire text of Frankenstein for me.

Maybe you are testing a debug version? Also I noticed that different terminals paste at different rates, so always check against `PYTHON_BASIC_REPL=1`

**Comment by godlygeek** [comment]
> I have made some small changes like encapsulating the cached data into a class

Thanks - I was waffling between keeping the changes localized vs doing that refactoring.

> and deactivated the prompt for paste in bracketed paste mode

👍 I looked at what it would take to get the paste mode indicator to show up the message line, as I had proposed. It doesn't work as nicely as I would have hoped: the Console class may decide not to show that line, if you're scrolled up, or if the cursor line is the bottom line of the screen. I may send another PR tweaking some things there to improve it, but ultimately it won't work as nicely as I had hoped, so just disabling it for bracketed pastes is definitely the quick fix.

**Comment by lysnikolaou** [comment]
> Did you check how long it takes in 3.13b1? Is this PR faster, or no improvement whatsoever?

Oh yeah, this is a *significant* improvement over 3.13b1. The old REPL is still faster and only takes ~6 seconds.

**Comment by pablogsal** [comment]
> he old REPL is still faster and only takes ~6 seconds.

Are you comparing using the same compiled version and setting `PYTHON_BASIC_REPL` on and off?

**Comment by godlygeek** [comment]
> The old REPL is still faster and only takes ~6 seconds.

What terminal are you using? Does it supported bracketed pastes? One of the optimizations here only applies when bracketed paste mode is enabled.

**Comment by lysnikolaou** [comment]
> Are you comparing using the same compiled version and setting `PYTHON_BASIC_REPL` on and off?

Yes.

> What terminal are you using? Does it supported bracketed pastes? One of the optimizations here only applies when bracketed paste mode is enabled.

I'm using iTerm2, which supports bracketed paste mode AFAIK.

**Comment by pablogsal** [comment]
Wow, in my Mac, using Iterm2 and a non-debug build, it takes exactly the same to paste the entire text. I wonder what's going on here....

**Comment by pablogsal** [comment]
@lysnikolaou If you go to Iterm > Edit > Paste special > Paste faster. What value you get?

Screenshot 2024-06-11 at 18 28 41

**Comment by lysnikolaou** [comment]
> If you go to Iterm > Edit > Paste special > Paste faster. What value you get?

I'm getting 173 kB/sec.

I tested with a non-debug `--enable-optimizations` build and it now takes about the same, ~7 seconds with both the old and the new REPL. So false alarm.

Thanks again @godlygeek!

**Pull request merged**
