### PR TITLE
gh-118508: Clarify which characters are matched by `\s`

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-118508

----
📚 Documentation preview 📚: https://cpython-previews--119155.org.readthedocs.build/

### CODE REVIEW

**Review by blaisep — APPROVED** [review]
Nice additional clarification, thank you

**Comment by nineteendo** [comment]
@kumaraditya303, you merged a recent regex clarification. Would you like to merge this one as well?

**Comment by nineteendo** [comment]
Do we close the issue or do we backport the change?

**Comment by encukou** [comment]
Docs fixes are generally backported.

**Pull request merged**
