### PR TITLE
gh-123492: Remove unnecessary `:func:` parentheses

### PR DESCRIPTION
**Pull request by mattwang44**
Remove unnecessary `:func:` parentheses from reST content

* Issue: gh-123492

----
📚 Documentation preview 📚: https://cpython-previews--123493.org.readthedocs.build/

### CODE REVIEW

**Comment by picnixz** [comment]
That's a lot of files to check. @AA-Turner do you think we can quickly make something with sphinx-lint for this? I'm currently busy on fixing exception errors (and cleaning up my office...)

**Comment by mattwang44** [comment]
Please note that sphinx-lint CI only checks the `Doc` part. I can revert the changes in `Lib` and `Misc` (which reduce the number of updated files from 79 to 46) if you think they are unnecessary here.

**Comment by hugovk** [comment]
> That's a lot of files to check. @AA-Turner do you think we can quickly make something with sphinx-lint for this? I'm currently busy on fixing exception errors (and cleaning up my office...)

This PR is a result of adding it to Sphinx Lint :)

https://github.com/sphinx-contrib/sphinx-lint/pull/115

> Please note that sphinx-lint CI only checks the `Doc` part. I can revert the changes in `Lib` and `Misc` (which reduce the number of updated files from 79 to 46) if you think they are unnecessary here.

Let's keep `Misc` but revert the single `Lib` file: we can backport this PR to 3.13 and 3.12 but let's be extra cautious with 3.13 because it's in the release candidate phase.

**Review by hugovk — APPROVED** [review]
Thanks!

**Comment by hugovk** [comment]
@mattwang44 Would you like to make the backport PRs?

**Comment by mattwang44** [comment]
> @mattwang44 Would you like to make the backport PRs?

ok let me handle this!

**Pull request merged**
