### PR TITLE
gh-105983: add incognito mode to webbrowser module

### PR DESCRIPTION
**Pull request by AmirNakhaeii**
Add incognito / private mode to webbrowser module
--
open browser in incognito mode when in open() function **new** parameter is equal _3_

* Issue: gh-105983

### CODE REVIEW

**Comment by Eclips4** [comment]
Duplicate of #105984

**Comment by AmirNakhaeii** [comment]
@Eclips4
Well, what's the problem? I also tried to add this feature.

**Comment by kr-g** [comment]
good day,

just received your message via email.
and saw the message from @Eclips4

when you would please have a look at the history of the initial pull request and the code given there you will see that i already did the development before i have created the issue regarding the new feature. it is a bit confusing sometimes how github organize the flow of information. 

anyway i saw that you added also support for edge. 

thats great because i dont have microsoft windows. 
i do development on linux only.
thank you.

probably best would be that you wait until my pull request is merged, and then you create an own issue regarding the enhancement and support for edge. and an extra pull request for that.

myself would prefer this approach since i can not spent time for taking part in a development where i dont have the proper OS and cant not even test it.

thanks for your contribution, and understanding.

ps. do close your pull request, also because you followed the naming convention and gave it the same name as mine - thats might be confusing to others -

**Comment by kr-g** [comment]
just corrected the different pull requests numbers in my former reply. sorry for the confusion.

**Comment by kr-g** [comment]
> probably best would be that you wait until my pull request is merged, and then you create an own issue regarding the enhancement and support for edge. and an extra pull request for that.

i dont know if it is possible to created "depening" issues in github. 

but probably it might be also an idea to clone my git repo and checkout the branch https://github.com/kr-g/cpython/tree/kr-g-browser-incognito and create from this HEAD ref a new branch where you put your code for edge browser.

**Comment by kr-g** [comment]
@AmirNakhaeii 

please have also a look here https://github.com/python/cpython/pull/105984/files at the test cases -> Lib/test/test_webbrowser.py

you need to create also one for Edge. 
Thanks

**Comment by AmirNakhaeii** [comment]
@kr-g
Thank you for your guidance. I will definitely fulfill your request. Good luck.

**Comment by AmirNakhaeii** [comment]
@kr-g 
I rarely visit my Gmail. That's why I didn't see your message.

**Comment by kr-g** [comment]
@AmirNakhaeii 
> I rarely visit my Gmail. That's why I didn't see your message.

ok fine, i try to keep that in mind

**Pull request closed without merging**
