### PR TITLE
bpo-44336: Prevent hanging on child process handles

### PR DESCRIPTION
**Pull request by jkloth**
Replace the child process `typeperf.exe` with a daemon thread
that reads the performance counters directly.  This prevents
the issues that arise from inherited handles in grandchild processes
(see https://bugs.python.org/issue37531#msg350191).

https://bugs.python.org/issue44336

### CODE REVIEW

**Comment by jkloth** [comment]
Please add the test-with-buildbots label to ensure this actually fixes the buildbots!

**Comment by isidentical** [comment]
CC: @pablogsal

**Comment by zware** [comment]
Do note that it's currently failing on Windows CI, but I went ahead and added the label.

**Comment by jkloth** [comment]
It seems that buildbot runs were not sheduled for the Windows buildbots. :(  Is it because they are paused (due to excessive exceptions?) or that the CI failed?

**Comment by zware** [comment]
I think it's just backlog, though I notice that your worker is currently "paused" (though I don't know why).

**Comment by jkloth** [comment]
Woohoo!  The PR allows the buildbot test stage to finish successfully!  Well, in this case, with an error, but it no longer hangs waiting for the buildbot controller process to kill it.

**Comment by jkloth** [comment]
Follow up for those not watching the buildbots.  Before this PR:
    https://buildbot.python.org/all/#/builders/593/builds/58
and after:
    https://buildbot.python.org/all/#/builders/593/builds/59

**Comment by jkloth** [comment]
Likewise for the other Windows 10 buildbot (bolen-windows10), before:
https://buildbot.python.org/all/#/builders/577/builds/54
and after:
https://buildbot.python.org/all/#/builders/577/builds/55

**Comment by pablogsal** [comment]
Seems that there are some test failures in the CI in Windows? @jkloth could you rebase this PR against master, rerun the CI and maybe take a look? Thanks!

Also it would be great if someone with Windows experience could take a quick look at this. Ideally @zooba if is available :)

**Comment by jkloth** [comment]
> Seems that there are some test failures in the CI in Windows?

Yes, this is expected due to the current goings on with bpo-11105.   The tests are aborting, if you scroll back to their initial test.  The whole point of this PR is to see these failures from the buildbots instead of being masked by timeout exceptions from the builder process.

Note that I cannot reproduce any aborts locally when using a release build, however I am running Windows build 19043 (21H1) vs 17763 on the CI.  The OS version differences have been known to influence test results.

**Comment by jkloth** [comment]
There is one problem with the approach in the PR, test__xxsubinterpreters (specifically the is_running() function) cannot be run sequentially, that is, in the same process as the test runner.  It fails when more than one thread state is active.  It would be possible to skip this particular test case when not run in sub-process mode (-jN) with some additional plumbing.

If that approach is deemed worthy, I'll update the PR to include that as well.  I **really** would like to see the failures on the Windows buildbots show prominently again, instead of being masked behind builder timeout exceptions.

**Comment by jkloth** [comment]
I've addressed the conflicts with test__xxsubinterpreters in the latest commit.  In short, only use load for multiprocess test runs.

**Comment by jkloth** [comment]
See also [regrtest fails to start on missing performance counter names](https://bugs.python.org/issue46788)

**Comment by eryksun** [comment]
This would be less fragile and more useful in general if support were added to `_winapi` for `PdhOpenQueryW()`, `PdhAddEnglishCounterW()`, `PdhCollectQueryData()`, `PdhCollectQueryDataEx()`, `PdhGetFormattedCounterValue()`, and `PdhCloseQuery()`. The English counter name is "\\System\\Processor Queue Length" -- no need to worry about localized names, hard-coded values, or hard-coded struct sizes and offsets.

**Pull request merged**
