### PR TITLE
gh-114271: Make `PyInterpreterState.threads.count` thread-safe in free-threaded builds

### PR DESCRIPTION
**Pull request by mpage**
Use atomics to mutate `PyInterpreterState.threads.count`

* Issue: gh-114271

### CODE REVIEW

**Comment by mpage** [comment]
@colesbury - Can you add the "skip news" label to this?

**Comment by mpage** [comment]
@colesbury - Would you take a look at this, please?

**Review by colesbury — APPROVED** [review]
LGTM

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Pull request merged**
