### PR TITLE
gh-117941: Reject option names starting with "--no-" in argparse.BooleanOptionalAction

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
They never worked correctly.

* Issue: gh-117941

### CODE REVIEW

**Review by savannahostrowski — CHANGES_REQUESTED** [review]
LGTM, but I think we should also update the documentation to reflect that `--no-foo` is no longer supported, right? The blurb from the docs:

> You may also specify an arbitrary action by passing an Action subclass or other object that implements the same interface. The BooleanOptionalAction is available in argparse and adds support for boolean actions such as --foo and --no-foo:

**Comment by serhiy-storchaka** [comment]
It never was supported. Just now you will get an error instead of wrong result when you use BooleanOptionalAction in the way it was not supposed to be used.

**Comment by savannahostrowski** [comment]
Right, but isn't the text I mentioned above suggesting that `--no-foo` can be used with `BooleanOptionalAction`? After this PR is merged, this is no longer recommended, as you'll get an error, so shouldn't we remove this as an example in the paragraph?

**Comment by serhiy-storchaka** [comment]
> but isn't the text I mentioned above suggesting that `--no-foo` can be used with `BooleanOptionalAction`?

Read it in the context. The following example shows that it creates action for `--no-foo` when `'--foo'` is passed to `add_argument()`.

**Comment by savannahostrowski** [comment]
Yeah, I see the example. It just sort of reads a bit unclear to me and implies that I should be able to create a parser with:
`parser.add_argument('--no-foo', action=argparse.BooleanOptionalAction)`, which is no longer the case.

**Comment by serhiy-storchaka** [comment]
I do not see anything that implies that '--no-foo' works. And it never worked.

**Review by savannahostrowski — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thank you for your review @savannahostrowski.

**Pull request merged**
