### PR TITLE
gh-115145: Update documentation about ``PyThreadState_DeleteCurrent``

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-115145

----
📚 Documentation preview 📚: https://cpython-previews--124920.org.readthedocs.build/

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
The GIL must be held, it's checked by:

```
void
_PyThreadState_DeleteCurrent(PyThreadState *tstate)
{
    _Py_EnsureTstateNotNULL(tstate);
    ...
}
```

**Comment by da-woods** [comment]
Can we have another look at this?

> Like [PyThreadState_Delete()](https://docs.python.org/3/c-api/init.html#c.PyThreadState_Delete), the global interpreter lock must be held.

To me this implies that the GIL _must_ be held for `PyThreadState_Delete`, which contradicts the documentation for `PyThreadState_Delete`. I suspect you just want to remove the words "Like PyThreadState_Delete()" but I'm not sure I understand it well enough to be absolutely confident.

**Comment by vstinner** [comment]
I agree that "Like PyThreadState_Delete()" is wrong and should be removed.

@corona10: Do you want to propose a patch for this?

**Comment by corona10** [comment]
Yeah I will send the patch

**Pull request merged**
