### PR TITLE
bpo-44991: Normalise `sqlite3` function and collation callback naming

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue44991

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I forgot these two in GH-28088.

**Comment by erlend-aasland** [comment]
cc. @encukou

**Comment by erlend-aasland** [comment]
Reopening to trigger asan test again.

**Review by shihai1991 — APPROVED** [review]
Keeping consistent code style is fine to me.

**Comment by erlend-aasland** [comment]
> Keeping consistent code style is fine to me.

Thanks for reviewing!

**Review by encukou — COMMENTED** [review]
I don't care that strongly about the pysqlite prefix, so I didn't point this out in the earlier review.
But sure, let's make them consistent!

**Pull request merged**
