### PR TITLE
gh-116646: Add limited C API support to AC fildes converter

### PR DESCRIPTION
**Pull request by vstinner**
Add tests on the "fildes" converter to _testclinic_limited.

* Issue: gh-116646

### CODE REVIEW

**Comment by vstinner** [comment]
@serhiy-storchaka @erlend-aasland: Ok, this approach should be the least intrusive and the least controversial. It only adds support for the limited C API, but keep the code for the internal C API using converter.

In the worst case, it generates internal C API code for the limited C API, but we can revisit this corner case later.

**Review by serhiy-storchaka — COMMENTED** [review]
Why bother with limited_capi? It is okay to use `PyObject_AsFileDescriptor` unconditionally.

**Comment by serhiy-storchaka** [comment]
The fallback is still here if you do not remove `converter = '_PyLong_FileDescriptor_Converter'`.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
I prefer to not add an indentation and the limited_capi check. The fallback is still used in a number of modules.

**Comment by vstinner** [comment]
> The fallback is still here if you do not remove converter = '_PyLong_FileDescriptor_Converter'.

Ok, let me elaborate. I tried to move code to converter_init(). The problem is that the logic to decide if an `#include` must be added or not doesn't work well. It's because `converter_init()` is always added: calling `add_include()` means that the include is always added, even if it's not used. I plan to write a follow-up PR to adjust this.

**Comment by vstinner** [comment]
Merged, thanks for the review @serhiy-storchaka.

**Comment by erlend-aasland** [comment]
LGTM; thanks.

**Comment by erlend-aasland** [comment]
> [...] when touching Argument Clinic which is fragile and has a small test suite.

You keep repeating this, but the latter part is not true. Please keep to the facts, and don't invent FUD about the Argument Clinic test suite.

**Comment by vstinner** [comment]
Your right, AC has a large test suite today, and mypy is a great help. Sorry.

**Pull request merged**
