### PR TITLE
bpo-40976: Clarify motivation for `chain.from_iterable`

### PR DESCRIPTION
**Pull request by cool-RR**
https://bugs.python.org/issue40976

### CODE REVIEW

**Comment by cool-RR** [comment]
If anyone can put the "skip news" label here, that'll be helpful.

**Comment by vedgar** [comment]
"Huge" is an understatement. Iterable might be infinite, with a well-defined chain.

**Comment by cool-RR** [comment]
Good point, I missed that. I'll update the PR soon.

**Comment by rhettinger** [comment]
I disagree with the premise of this edit which reflects a personal viewpoint about why people would use *chain.from_iterable()*.  In practice, it is commonly used for small inputs — the "huge" or "infinite case" is not common.  Users can want or need lazy input consumption for reasons other than size, for example, flattening a single nested input iterator.

It isn't clear to me what problem are you trying to solve with this edit. AFAICT, the current docs are accurate and have been clearly understood for years.   The primary motivation for *chain.from_iterable()* was to give a better fit for when the input was an iterable (i.e. use *chain()* with a fixed number of input sources and *chain.from_iterable()*  for a variable number of sources).  While star-args can often be used for the latter, it is awkward and non-obvious.

**Comment by rhettinger** [comment]
One other thought: In the Python world, the term "optimization" is often taken as a pejorative, as in "pre-mature optimization".  This tool was not in fact designed as an optimization; rather, it just to provide a better fit for a variable number of inputs.

**Comment by ericvsmith** [comment]
I agree with @rhettinger that the proposed change is not an improvement. More words don't always make things clearer.

**Comment by cool-RR** [comment]
I understand. Thanks for your time and attention.

**Comment by alvations** [comment]
For the sake of documentation, I've ran some benchmark on unpacking rather huge no. of iterable and both run-time seem equivalent: https://stackoverflow.com/a/62513808/610569

I hope I didn't get the benchmarking idea/code wrong ;P

**Pull request closed without merging**
