### PR TITLE
Add Erlend as CODEOWNER for Argument Clinic docs

### PR DESCRIPTION
**Pull request by erlend-aasland**

### CODE REVIEW

**Review by AlexWaygood — COMMENTED** [review]
Hrm, not sure. I'm increasingly familiar with the Python code in `Tools/clinic/`, and I have a broad understanding of how it all works... but I wouldn't necessarily call myself an expert in _using_ AC just yet 😆

(I'm obviously always happy to review docs PRs whenever you'd like me to :)

**Review by ezio-melotti — COMMENTED** [review]
Technically you don't need to be an expert to be added to `CODEOWNERS`, since its main function is to request your review and ping you when someone makes a PR that touches the listed files.

If you *don't* want to be pinged, then it's ok  not to be listed, whether you are an expert or not.

**Comment by AlexWaygood** [comment]
> Technically you don't need to be an expert to be added to `CODEOWNERS`, since its main function is to request your review and ping you when someone makes a PR that touches the listed files.

I know. But I already get a lot of pings on a lot of things, and I guess I'd prefer not to have _automated_ review on things where I don't feel like I'm an expert yet :)

**Comment by erlend-aasland** [comment]
> I know. But I already get a lot of pings on a lot of things, and I guess I'd prefer not to have _automated_ review on things where I don't feel like I'm an expert yet :)

No stress, I'll ping you manually for these PRs 😆

**Comment by erlend-aasland** [comment]
More seriously: no sweat; I've removed you :) I promise I'll only ping you if needed.

**Review by AlexWaygood — APPROVED** [review]
✍️🚀

**Review by ezio-melotti — APPROVED** [review]

**Pull request merged**
