### PR TITLE
bpo-28867: Warn when NamedTemporaryFile is not explicitly closed

### PR DESCRIPTION
**Pull request by jdufresne**
https://bugs.python.org/issue28867

### CODE REVIEW

**Comment by jdufresne** [comment]
Any interest in this fix? Anything I can do to move this along?

**Comment by jdufresne** [comment]
Added the news entry.

**Review by berkerpeksag — CHANGES_REQUESTED** [review]
I don't think the following pattern is acceptable:

```py
try:
    ...
except urllib.error.HTTPError as exc:
    exc.close()
```

Dealing with `HTTPError`'s `fp` attribute shouldn't be the responsibility of the user. It would be better to deal with it in `addbase`:

https://github.com/python/cpython/blob/99e6c260d60655f3d2885af545cbc220b808d492/Lib/urllib/response.py#L14

**Comment by jdufresne** [comment]
@berkerpeksag Thanks for the review. I'm happy to adjust the PR to meet the request, but I could use a bit of guidance and more detail.

The reason I took this approach is due to the comment here:

https://github.com/python/cpython/blob/65ecc390c1fa5acdd6348ae3f9843bbdcd8870d1/Lib/urllib/request.py#L742-L745

```
        # Don't close the fp until we are sure that we won't use it
        # with HTTPError.
```

Are you suggesting that the error handler should eagerly close the file? Would doing so be acceptable?

**Comment by berkerpeksag** [comment]
Ah, good point, thanks. I need to think about it more carefully. While I don't have objections on the idea discussed in the issue, I think we need to find a solution for `exc.close()` before merging this PR.

**Pull request closed without merging**
