### PR TITLE
[3.13] gh-122656: dataclass freeze specific fields

### PR DESCRIPTION
**Pull request by dsal3389**
* Issue: gh-122656

----
📚 Documentation preview 📚: https://cpython-previews--122657.org.readthedocs.build/

### CODE REVIEW

**Comment by ZeroIntensity** [comment]
3.13 is feature-frozen. See [the release schedule](https://peps.python.org/pep-0719/#schedule).

**Comment by dsal3389** [comment]
ahhh I see, to which branch should I push it then?

**Comment by ZeroIntensity** [comment]
`main`, but again this needs to be approved on [discourse](https://discuss.python.org).

**Comment by sobolevn** [comment]
I will close the PR, because:
- it should be targeting `main`, not `3.13`
- it is too early for the implementation. But, you can use it as a reference

Thanks!

**Pull request closed without merging**
