### PR TITLE
bpo-41482: Fix error in ipaddress.IPv4Network docstring

### PR DESCRIPTION
**Pull request by ericfrederich**
I think I did this right.

https://bugs.python.org/issue41482

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@ericfrederich

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by rougeth — APPROVED** [review]

**Review by ericvsmith — COMMENTED** [review]
Thanks for catching this! As soon as the CLA is signed, I'll merge it.

**Comment by ericfrederich** [comment]
I signed one of those on 2015/7/22, I think it was for a contribution I
made to Jython.

https://secure.echosign.com/public/viewAgreement?tsid=2AAABLblqZhCG5ON_GnB9N3pKGKQ32GfLmTCR1iGIlLOZHnHvN5O9DuEhpjurvcGHDSbJLVX6aLw*&

**Comment by ericvsmith** [comment]
I don't know what it takes to get this rectified. Can you check https://check-python-cla.herokuapp.com/ ? Or look at https://devguide.python.org/pullrequest/#licensing ?

On the other hand, this change is trivial. But I think it would be good to get it cleared up. Your next contribution might not be so simple.

**Comment by ericfrederich** [comment]
Okay, I think it may be fixed now.

**Comment by ericvsmith** [comment]
Thanks, @ericfrederich!

**Pull request merged**
