### PR TITLE
bpo-44263: Better explain the GC contract for PyType_FromSpecWithBases

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue44263

### CODE REVIEW

**Comment by pablogsal** [comment]
CC: @erlend-aasland

**Review by Fidget-Spinner — APPROVED** [review]
Thanks for the clarifications. I was pretty confused with your fix at https://github.com/python/cpython/commit/8b4312b909abff3100c1f18fb3efa5c25617fee3. So I'm glad the reason is in the docs now!

If I'm understanding correctly, in that specific case, you want ``_ssl.SSLError`` to inherit its ``tp_traverse`` etc. fields from the parent ``PyExc_OSError`` (which implements the GC), so you didn't set ``Py_TPFLAGS_HAVE_GC`` in ``_ssl.SSLError``?

**Comment by pablogsal** [comment]
> If I'm understanding correctly, in that specific case, you want `_ssl.SSLError` to inherit its `tp_traverse` etc. fields from the parent `PyExc_OSError` (which implements the GC), so you didn't set `Py_TPFLAGS_HAVE_GC` in `_ssl.SSLError`?

Correct, this is because SSLError doesn't add any extra fields: is just `PyOSErrorObject`.

**Comment by encukou** [comment]
Thank you for the clarification!

**Comment by vstinner** [comment]
> Thank you for the clarification!

Yeah, thanks Pablo! This part wasn't obvious to me at all, especially the type inheritance part.

FYI Pablo and me hit this issue the hard way while debugging a random crash involving the _ssl.SSLError exception: https://bugs.python.org/issue44252 Two unit tests only crashed on Windows, and only if you ran the unit test in a very specific way. GC collections are not really "determistic" from my human debugger pointer of view :-) I made the crash more likely by running `import gc; gc.set_threshold(5)` at Python startup.

**Pull request merged**
