### PR TITLE
bpo-31870: Add a timeout parameter to ssl.get_server_certificate()

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue31870

Automerge-Triggered-By: GH:tiran

### CODE REVIEW

**Review by tiran — CHANGES_REQUESTED** [review]
There is a merge conflict in what's new.

**Review by tiran — CHANGES_REQUESTED** [review]
@ZackerySpytz This PR is also conflicting. Please resolve the conflict and then instruct Bedevere to ping me again.

**Comment by ZackerySpytz** [comment]
I have made the requested changes; please review again.

**Review by tiran — APPROVED** [review]
Thanks for your patience!

**Comment by tiran** [comment]
@ZackerySpytz Windows doesn't like your tests. I have created https://github.com/python/cpython/pull/25570 to address the test issue.

**Pull request merged**
