### PR TITLE
gh-84852: Add basic font MIME types

### PR DESCRIPTION
**Pull request by MasterInQuestion**
Namely:
    |&#x2A;| ".ttf": "font/ttf"
    |&#x2A;| ".otf", ".otc", ".ttc": "font/otf"
    |&#x2A;| ".woff": "font/woff"
    |&#x2A;| ".woff2": "font/woff2"

    References:
    https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#font_mime_types
    https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src#font_formats
    https://en.wikipedia.org/wiki/OpenType
    https://en.wikipedia.org/wiki/TrueType

* Issue: gh-84852

### CODE REVIEW

**Review by serhiy-storchaka — CHANGES_REQUESTED** [review]
I think that it is a good idea. But this change needs a NEWS file and tests. Please open an issue for reference.

**Comment by MasterInQuestion** [comment]
How shall I write the [NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS.d) file..? Linking to this post?
    The tests... It won't break anything, semantically verified.

**Comment by serhiy-storchaka** [comment]
> Most changes to Python [require a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python). Add one using the [blurb_it](https://blurb-it.herokuapp.com) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

As for the tests, you should add cases related to your changes in `Lib/test/test_mimetypes.py`. No need to add cases for all changes, but I think that it would be interesting to add checks for `guess_all_extensions('font/otf')` and `guess_extension('font/otf')`. Make your changes consistent with other similar checks.

**Comment by serhiy-storchaka** [comment]
There is already open issue for adding fonts to mimetypes: #84852.

**Comment by MasterInQuestion** [comment]
Finding issue for no issue...

    I did read.
    But the message... would the link plus "Add basic font MIME types" suffice?

    I believe the "test" files don't affect the eventual execution?
    If so... why bother?

**Comment by serhiy-storchaka** [comment]
The link is not needed, but add the list of added MIME types or file extensions.

Tests are needed to check that the change makes sense and that the following changes will not unintentionally cancel them. For example, there is an alternate patch for #84852, conflicting with this PR.

**Comment by MasterInQuestion** [comment]
Is not the whole change most clear simply tracing the link..?

    Rather than spending time on tests that might not work, or might be outright malapropos...
    Wouldn't it be more appropriate, to focus on the actual coding itself?

**Comment by serhiy-storchaka** [comment]
That's not how it works in software development. "Coding" without tests is meaningless.

**Comment by MasterInQuestion** [comment]
So shall be testing without "Coding".

**Pull request closed without merging**
