### PR TITLE
bpo-40528: Implement a metadata system for ASDL Generator

### PR DESCRIPTION
**Pull request by isidentical**
ASDL Generator was lack of proper annotation related to the generated
module. This patch implements a MetadataVisitor that produces a
metadata object to pass to other visitors that are visiting that
same module. For the initial patch, it dynamically retrieves int
sequences (like cmpop), that was previously hardcoded. It offers
an interface that is easy to extend.

https://bugs.python.org/issue40528

### CODE REVIEW

**Comment by pablogsal** [comment]
Re-triggering CI

**Comment by isidentical** [comment]
Thanks @pablogsal, it looks like everything is passing now.

**Comment by pablogsal** [comment]
@isidentical Can you rebase?

**Comment by isidentical** [comment]
> @isidentical Can you rebase?

Sure, rebased!

**Pull request merged**
