### PR TITLE
gh-122546: use same filename for different exceptions in new repl

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-122546

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks for the PR @skirpichev 👌

**Comment by skirpichev** [comment]
> Could you prepare the back port following these instructions?

I'll try.

**Comment by cfbolz** [comment]
@skirpichev hold off for a moment. there are various missing other backports which cause the automated backport failures, this one: https://github.com/python/cpython/pull/122817 and this one: https://github.com/python/cpython/pull/123062

**Comment by skirpichev** [comment]
Opened as a draft, just in case it may block other backports.

**Pull request merged**
