### PR TITLE
gh-95656: Enable the sqlite3 load extension API in Windows build

### LINKED ISSUE #95656: Enable sqlite extensions in the Windows build
# Feature or enhancement

Enable SQLite extension loading in the Windows build (in the sqlite DLL shipped with Python, and in the stdlib sqlite3 module).

# Pitch

At the moment, sqlite extensions are disabled at compile time - see the note in [the docs](https://docs.python.org/3.11/library/sqlite3.html#sqlite3.Connection.enable_load_extension). On Windows, though:

1. We supply our own sqlite DLL, so we control the build options, and
2. Users rarely build their own copy of Python.

So the reasons for not enabling extension loading don't really apply there, and conversely, people who want to use extensions cannot do so without limiting themselves to custom Python builds.

# Previous discussion

See https://discuss.python.org/t/should-we-audit-enabling-loading-of-sqlite3-extensions-shared-libraries/8124/9

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-95656

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I'm not sure about backporting this. What do you say, Steve?

**Comment by erlend-aasland** [comment]
This API is not tested. Let's add a test while we're there.

**Comment by zooba** [comment]
Does this have a Python API to go with it? Is that currently unusable on every release? If so, let's backport.

**Comment by erlend-aasland** [comment]
> Does this have a Python API to go with it?

Yes, it enables this API:

https://github.com/python/cpython/blob/bdbadb905ae638b67a6c9a6767be396e18839dd6/Modules/_sqlite/connection.c#L1490-L1525

> Is that currently unusable on every release? If so, let's backport.

Yes; ok.

**Comment by zooba** [comment]
Haha, yeah, good point. Backport for sure

**Review by zooba — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks, Steve!

**Comment by erlend-aasland** [comment]
Aha... no backport to 3.10 is needed. I changed the `#ifdef` guard in 3.11, while Christian and I were updating `configure.ac`. So... this means I broke this for Windows builds in 3.11.

**Comment by erlend-aasland** [comment]
FTR, broken in gh-29434.

**Pull request merged**
