### PR TITLE
Change WriterObj.writeline to WriterObj.write

### PR DESCRIPTION
**Pull request by remilapeyre**
This cleans the csv module a bit, I don't think it requires a bpo issue or a news entry.

### CODE REVIEW

**Comment by csabella** [comment]
@remilapeyre, this isn't a trivial issue, so it would require a bpo issue.  Thanks!

**Comment by asvetlov** [comment]
Usually, we discourage PRs like this: it just renames the internal name without providing any extra functionality or bug fixing.

**Comment by csabella** [comment]
@remilapeyre, thank you for the suggestion, but I'l close this based on @asvetlov's comment.

**Comment by remilapeyre** [comment]
Hi @asvetlov, @csabella ! It was asked by @vstinner in https://github.com/python/cpython/pull/12306#discussion_r265668156 as the previous naming was misleading.

**Comment by asvetlov** [comment]
Ok, I'm fine then.
Sorry, without the context your motivation was not very clear.

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks, @remilapeyre

**Pull request merged**
