### PR TITLE
bpo-42090: zipfile.Path.joinpath now accepts multiple arguments

### PR DESCRIPTION
**Pull request by jaraco**
https://bugs.python.org/issue42090

Automerge-Triggered-By: GH:jaraco

### CODE REVIEW

**Comment by jaraco** [comment]
Hi Tal. Good to meet you this week. Github suggests you might be a good reviewer for this change. Please take a look, or let me know if you'd rather not receive requests like these.

**Comment by taleinat** [comment]
Hey @jaraco! I'm happy to receive such requests :)

This seems like a straightforward improvement. I think this should be mentioned in the docs, though. Strange that this method is undocumented; is that intentional? Seems like a good opportunity to fix this?

**Comment by jaraco** [comment]
> This seems like a straightforward improvement. I think this should be mentioned in the docs, though. Strange that this method is undocumented; is that intentional? Seems like a good opportunity to fix this?

I had the same instinct, but didn't feel motivated enough to include it in this change. I'll add it.

**Comment by jaraco** [comment]
Hi Tal. The latest commit includes docs. Please have a new look.

**Review by Mariatta — APPROVED** [review]
Looks good from my perspective. Thanks for updating the documentation.

**Pull request merged**
