### PR TITLE
bpo-36625: Remove obsolete comments from docstrings in fractions module

### PR DESCRIPTION
**Pull request by jmolinski**
Updated 3 docstrings in `fractions.Fraction` containing comments referring to python 3.0.

New docstrings are consistent with other docstrings in the fractions module.

https://bugs.python.org/issue36625

### CODE REVIEW

**Review by mdickinson — APPROVED** [review]
LGTM. Does this need a Misc/NEWS entry?

**Comment by scoder** [comment]
LGTM, too. I don't think this merits bothering users with a "What's new" entry.

**Comment by mdickinson** [comment]
Agreed that it doesn't need a what's new entry, but it should still have a Misc/NEWS entry, on general principles. (Specfically, *these* general principles: https://devguide.python.org/committing/#what-s-new-and-news-entries.) @jmolinski Please could you use the `blurb` tool to add an entry?

**Comment by jmolinski** [comment]
@mdickinson of course, I added the Misc/NEWS entry.

**Review by mdickinson — APPROVED** [review]
LGTM

**Comment by mdickinson** [comment]
All done. @jmolinski Thank you very much for the contribution!

**Pull request merged**
