### PR TITLE
3.4 rtrt \lib\logging\__init__.py", line 190, in _checkLevel e TypeError("Level not an integer or a valid string: %r" % level) r: Level not an integer or a valid string: <function error at 0x00000000 >

### PR DESCRIPTION
**Pull request by stargame25**
When i start my script this:

```
rt YD_v4.py
C:\PythonFiles\YD (youtube_dl)\YD_v4\YD_v4.py", line 8, in <module>
ing.basicConfig(filename='logfile '+data+'.log', level=logging.error)
C:\Python34\lib\logging\__init__.py", line 1757, in basicConfig
.setLevel(level)
C:\Python34\lib\logging\__init__.py", line 1250, in setLevel
.level = _checkLevel(level)
C:\Python34\lib\logging\__init__.py", line 190, in _checkLevel
e TypeError("Level not an integer or a valid string: %r" % level)
r: Level not an integer or a valid string: <function error at 0x00000000
```
>
[my script](https://www.dropbox.com/s/f870t76l6assls1/YD_v4.rar?dl=0)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by stargame25** [comment]
I'm beginner in programming

**Comment by Mariatta** [comment]
Hello, if you have questions about using python or learning to use Python, you can try asking in mailing lists such as [python-list](https://mail.python.org/mailman/listinfo/python-list), [tutor](https://mail.python.org/mailman/listinfo/tutor) or even [StackOverflow](http://stackoverflow.com/).

**Comment by stargame25** [comment]
No no i have problem i wrote above, and i mean i don't know how to resolve it by myself.
Problem in python files itself

**Pull request closed without merging**
