### PR TITLE
bpo-28791: Update OS X installer to use SQLite 3.21.0.

### PR DESCRIPTION
**Pull request by Mariatta**
https://bugs.python.org/issue28791

### CODE REVIEW

**Review by mlouielu — APPROVED** [review]
version, url and checksum looks good.

**Review by ned-deily — COMMENTED** [review]
Thanks for the PR.  I would prefer that this not be applied yet until I've had a chance to review and test the SQLite updates in the installer build context prior to the next alpha.

**Comment by Mariatta** [comment]
Thanks @ned-deily. Should I mark this as `wip`? 
BTW I made the corresponding PR for the windows build in https://github.com/python/cpython/pull/4246.

**Comment by ned-deily** [comment]
It’s fine as is. I just won’t be able to get to it immediately.

**Comment by Mariatta** [comment]
@ned-deily Will it be possible to include this in 3.7.0a3? Thanks.

**Comment by ned-deily** [comment]
I'm working on it now :)

**Comment by ned-deily** [comment]
LGTM, thanks!

**Pull request merged**
