### PR TITLE
gh-117142: ctypes: Migrate global closure freelist to thunk-type state

### PR DESCRIPTION
**Pull request by neonene**
This introduces `PyCThunkType_Type`, a metaclass of `PyCThunk_Type`, to bypass the module check during a finish.

* Issue: gh-117142

### CODE REVIEW

**Comment by neonene** [comment]
#117875

**Comment by encukou** [comment]
What problem is this solving, and why can't it be solved in a simpler way?

I think the closure freelist can stay process-global. The free-threaded build will need some locking (not just for multiple interpreters), but I think closure alloc/dealloc happens rarely enough that a global mutex should be enough. (This is unlike most of Python's freelists, which exist *because* allocation/deallocation is too common.)

We don't free the allocated pages at interpreter shutdown. I don't think that's a big concern, though -- while we don't munmap the pages, we do recycle them.

Is there something I'm missing?

**Comment by neonene** [comment]
I'm trying to reduce global variables as much as possible first, then asking for a decision.  If you think the closure (de)allocation is not frequent, the freelist can be removed in the future?  Leaving an experment without the global variable. The CI appears to be OK.

**Comment by encukou** [comment]
It would be nice if libffi (`ffi_closure_alloc`/_free) always did all this for us (on all platforms) so we could drop this code. Not sure what's the status there; I don't know that much about libffi.

**Pull request closed without merging**
