### PR TITLE
Exclude myself from mention-bot

### PR DESCRIPTION
**Pull request by vstinner**
I made changes in almost all CPython files last 5 years, so
mention-bot asks me to review basically all pull requests. I simply
don't have the bandwidth to review everything, sorry! I prefer to
select myself which PR I want to follow.

### CODE REVIEW

**Comment by vstinner** [comment]
I'm not sure if I should put my name in userBlacklist or userBlacklistForPR.

**Comment by vstinner** [comment]
> I'm not sure if I should put my name in userBlacklist or userBlacklistForPR.

I will follow Stefan Krah's example: put my GitHub login in both lists ;-)

**Comment by Carreau** [comment]
While you are at it can you add `.mentionbot` to the list of ignored files ?

**Comment by dstufft** [comment]
@haypo You want to add yourself to ``userBlacklist``.

**Comment by dstufft** [comment]
``userBlacklistForPR`` will stop the mention bot from mentioning anyone on *your* PRs.

**Comment by vstinner** [comment]
@Carreau: "While you are at it can you add .mentionbot to the list of ignored files ?"

I don't see .mentionbot in "git status". What is your OS? What is the issue? :-)

**Comment by vstinner** [comment]
@dstufft : "You want to add yourself to userBlacklist."

Oh ok, done :-)

**Comment by dstufft** [comment]
@haypo he means to add ``.mention-bot`` to the list of blacklisted files inside of the ``.mention-bot`` file. I wouldn't do that though, I think it's useful ¯\\_(ツ)\_/¯

**Review by dstufft — APPROVED** [review]

**Comment by vstinner** [comment]
"@haypo he means to add .mention-bot to the list of blacklisted files inside of the .mention-bot file. I wouldn't do that though, I think it's useful ¯\_(ツ)_/¯"

Ah, please propose a PR for that @Carreau. At least, *I* will no more be be impacted once this change will be merged :-D

**Comment by Carreau** [comment]
> Ah, please propose a PR for that @Carreau. At least, I will no more be be impacted once this change will be merged :-D

Understood, I'll make a PR and ping you manually everywhere, just to be sure you don't miss anything.

**Comment by AraHaan** [comment]
heh, nice way to pick on him. :stuck_out_tongue:

**Comment by vstinner** [comment]
"Understood, I'll make a PR and ping you manually everywhere, just to be sure you don't miss anything."

Thanks! :-)

**Pull request merged**
