### PR TITLE
Backport master's README.rst to 3.6

### PR DESCRIPTION
**Pull request by zware**
Includes GH-2, GH-70, GH-73, and GH-21.

### CODE REVIEW

**Comment by Mariatta** [comment]
GH-73 has already been cherry-picked in GH-79 :)

**Review by brettcannon — APPROVED** [review]
Quick glance of the rendered output LGTM.

**Comment by brettcannon** [comment]
So should this be merged in spite of GH-79?

**Comment by zware** [comment]
This change contains GH-79, and git recorded this change as a delete `README` and add `README.rst`, so there's no conflict.  I'll go ahead and merge.

**Pull request merged**
