### PR TITLE
bpo-42625: Using Py_XINCREF() in _PyState_AddModule to avoid segmentation fault.

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue42625

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
Don't add new calls to Py_FatalError(), this function must be avoided whenever possible.

It's really bad when Python is embedded in an application, and really bad in general.

Make sure that it's well documented that the first argument must not be NULL and add an assertion if you really care.

**Comment by shihai1991** [comment]
> Don't add new calls to Py_FatalError(), this function must be avoided whenever possible.
> 
> It's really bad when Python is embedded in an application, and really bad in general.
> 
> Make sure that it's well documented that the first argument must not be NULL and add an assertion if you really care.

Thanks, get it. I will update it soon.

**Review by vstinner — CHANGES_REQUESTED** [review]
I don't see the purpose of this PR. Not accepting NULL is not a new feature, it was never accepted.

I suggest to just close the PR. If you consider that the assert is useles, just keep the added assert, but remove all added documentation which is wrong.

**Comment by shihai1991** [comment]
> I don't see the purpose of this PR. Not accepting NULL is not a new feature, it was never accepted. 
> I suggest to just close the PR. If you consider that the assert is useles, just keep the added assert, but remove all added documentation which is wrong.

It just not make sure the module is not illegals. the reason is this line(not check the module and using `Py_INCREF()`): https://github.com/python/cpython/blob/master/Python/pystate.c#L728
So I prefer to keep this PR~

**Review by vstinner — CHANGES_REQUESTED** [review]
This PR is wrong.

**Pull request closed without merging**
