### PR TITLE
bpo-37589: Fixed 138 missing dependencies in Makefile.pre.in

### PR DESCRIPTION
**Pull request by vemakereporter**
Hi, I've fixed 138 dependences missing reported.
Those issues can cause incorrect results when cpython is incrementally built.

For example, any changes in "Include/typeslots.h" will not cause "Modules/atexitmodule.o" to be rebuilt, which is incorrect.

I've tested it on my computer, the fixed version worked as expected.

Thanks
Vemake

https://bugs.python.org/issue37589

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by aeros — COMMENTED** [review]
@vemakereporter Welcome and thanks for the contribution! 

Since this is a rather large change and occurring in the makefile, I would strongly advise opening an issue over on the [issue tracker](bugs.python.org). Smaller PRs such as typo fixes can often be submitted with an issue, but for any significant changes it's typically required. For more information on the PR process, see the [devguide](https://devguide.python.org/pullrequest). Let me know if you have any further questions.

**Comment by vemakereporter** [comment]
> @vemakereporter Welcome and thanks for the contribution!
> 
> Since this is a rather large change and occurring in the makefile, I would strongly advise opening an issue over on the [issue tracker](bugs.python.org). Smaller PRs such as typo fixes can often be submitted with an issue, but for any significant changes it's typically required. For more information on the PR process, see the [devguide](https://devguide.python.org/pullrequest). Let me know if you have any further questions.

Hi @aeros167 , I've signed the CLA and created an issue on the issue tracker as you requested. 
Here is the issue's link: 
https://bugs.python.org/issue37589


Thanks
Vemake

**Comment by vemakereporter** [comment]
@aeros167 Please take a look at this fix. If no problem, do these minor changes need to be included in the news?

**Comment by aeros167** [comment]
@vemakereporter Yes, I would definitely recommend adding a news entry for these changes, it certainly wouldn't hurt. Currently I'm just waiting on others (particularly core devs) to submit feedback to the issue page and the PR to make sure everything looks good. I added the makefile expert to the nosy list on the issue tracker page, and I'll mention him here as well. cc @Yhg1s

**Comment by aeros167** [comment]
@vemakereporter You should also make sure you get the CLA signed as well, frequently the core devs won't submit their review until it's signed (since it can't be merged before the CLA is signed). If you've submitted it and it's been over 24 hours, try refreshing the status of it manually on GitHub with the [check yourself](https://check-python-cla.herokuapp.com/) link that the @the-knights-who-say-ni bot posted.

After that, the average wait time for most PRs is around 1-2 weeks, but it can take longer if the core devs are busy and are unable to adequately review your submission.

**Comment by vemakereporter** [comment]
> @vemakereporter You should also make sure you get the CLA signed as well, frequently the core devs won't submit their review until it's signed (since it can't be merged before the CLA is signed). If you've submitted it and it's been over 24 hours, try refreshing the status of it manually on GitHub with the [check yourself](https://check-python-cla.herokuapp.com/) link that the @the-knights-who-say-ni bot posted.
> 
> After that, the average wait time for most PRs is around 1-2 weeks, but it can take longer if the core devs are busy and are unable to adequately review your submission.

Hi @aeros167 , I've signed the CLA, please have a look.

**Comment by vemakereporter** [comment]
@Yhg1s

**Comment by aeros167** [comment]
@vemakereporter I'm personally not an expert on makefile changes, so there's no further review that I can do. If there's no response from @Yhg1s or any other core devs within the next week or so, I'll bring this PR up on the python-dev mailing list. @me to remind me to do so in case I get caught up in something else and forget.

**Comment by Yhg1s** [comment]
Thanks for the patch, but this introduced a lot of manual work, and we'll forget to keep track of these dependencies. Also, none of the rest of the Makefile tracks dependencies to this granularity; instead, we have a few separate lists of headers. PR #15757 fixes this by just adding the missing headers to the right lists.

**Pull request closed without merging**
