### PR TITLE
bpo-17942: Improve IDLE debugger user interface

### PR DESCRIPTION
**Pull request by roseman**
Previous versions were dependent on a parallel 'ui' library that handled some of the 8.4/8.5 differences in Tk, as well as provided some utilities. In terms of functionality, this version omits the tooltips found in the original one (code left but commented out to indicate where they'd go), but otherwise is the same. Some pieces, e.g. context menu bindings, windowing system calls, etc. should probably still be pulled into a separate ui module.

https://bugs.python.org/issue17942

### CODE REVIEW

**Comment by terryjreedy** [comment]
Turn Debugger on, Run file, and
Traceback (most recent call last):
  File "F:\Python\mypy\tem2.py", line 1, in <module>
    import Tkinter as tk
  File "F:\Python\mypy\tem2.py", line 1, in <module>
    import Tkinter as tk
  File "f:\dev\3x\lib\bdb.py", line 86, in trace_dispatch
    return self.dispatch_line(frame)
  File "f:\dev\3x\lib\bdb.py", line 110, in dispatch_line
    self.user_line(frame)
  File "f:\dev\3x\lib\idlelib\debugger.py", line 32, in user_line
    self.gui.interaction(message, frame)
AttributeError: 'PyShellFileList' object has no attribute 'already_open'

**Review by terryjreedy — CHANGES_REQUESTED** [review]
See posted error

**Comment by roseman** [comment]
Thanks Terry. I've added the missing routine to filelist.py in my branch. It looks like this is automatically added to this pull request...? (excuse the newbie question)

**Comment by terryjreedy** [comment]
Yes, when one pushes a commit to a branch on a github repository that is the basis for a pull request, then the commit appears on the pull request.  You probably pushed to 'origin'.  If I created a local pr_2454 branch and made some commits, and did 'git push https://github.com/roseman pr_2454:debugger-ui-17942', those commits would become part of this.  Please ask questions.  The devguide is both helpful and confusing.

**Comment by brettcannon** [comment]
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

**Comment by terryjreedy** [comment]
From AppVeyor
```
C:\projects\cpython\lib\idlelib\debugger.py:316: DeprecationWarning: invalid escape sequence \.
  match = re.match('^<(?:.*)\.([^\.]*) object at 0x[0-9a-f]+>$'
```
Add 'r' prefix to regex
```
ERROR: test_init (idlelib.idle_test.test_debugger.NameSpaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\idlelib\idle_test\test_debugger.py", line 25, in test_init
    debugger.NamespaceViewer(self.root, 'Test')
AttributeError: module 'idlelib.debugger' has no attribute 'NamespaceViewer'
```

**Comment by roseman** [comment]
replaced by newer PR

**Pull request closed without merging**
