### PR TITLE
bpo-25461: Update os.walk() docstring to match the online docs

### PR DESCRIPTION
**Pull request by codeape2**
https://bugs.python.org/issue25461

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by codeape2** [comment]
> 
> Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.
> 

I completed the CLA process just now.

**Review by eamanu — CHANGES_REQUESTED** [review]
hmm sorry, but I don't notice an improve here. The idea is the same with different words.

Sometime docstring and docs differ on words.

But it would be great listen other opinions. :-)

**Comment by codeape2** [comment]
> hmm sorry, but I don't notice an improve here. The idea is the same with different words.
> 
> Sometime docstring and docs differ on words.
> 
> But it would be great listen other opinions. :-)

This change has been discussed on bpo (https://bugs.python.org/issue25461#msg253377):

> If you want to avoid ineffective because its meaning is subtle (a reasonable request), the correct replacement would be "modifying dirnames has no effect on the behavior of the walk", which is wordier but clearer.

The wording change in the online docs were done from a patch on that issue. For os.walk() the online docs and docstring were more or less equal, so it makes little sense to change the wording of one of them and not the other.

IIRC, the patch for os.py was added to the issue after the changes to os.rst had been merged.

**Comment by codeape2** [comment]
Could someone add the 'skip news' label, please?

**Pull request merged**
