### PR TITLE
gh-91288: Move `set.test_c_api` to `_testcapimodule.test_set`

### LINKED ISSUE #91288: Move tests from setobject.c to _testcapimodule
BPO | [47132](https://bugs.python.org/issue47132)
--- | :---
Nosy | @rhettinger, @arhadthedev
PRs | <li>python/cpython#32133</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-26.19:16:33.510>
labels = ['expert-C-API', 'type-feature', 'tests', '3.11']
title = 'Move tests from setobject.c to _testcapimodule'
updated_at = <Date 2022-03-27.04:32:59.942>
user = 'https://github.com/arhadthedev'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-27.04:32:59.942>
actor = 'Dennis Sweeney'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests', 'C API']
creation = <Date 2022-03-26.19:16:33.510>
creator = 'arhadthedev'
dependencies = []
files = []
hgrepos = []
issue_num = 47132
keywords = ['patch']
message_count = 1.0
messages = ['416083']
nosy_count = 2.0
nosy_names = ['rhettinger', 'arhadthedev']
pr_nums = ['32133']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47132'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by arhadthedev**
Currently, tests for PySet/PyFrozenSet C API are defined in [Objects/setobject.c](https://github.com/python/cpython/blob/master/Objects/setobject.c) and available via `set.test_c_api()`.

Moving them to, for example, `_testcapi` gives the following advantanges:

- an internal, CPython-specific method stops being available in a public interface of the set class

- CPython already has tests grouped into dedicated packages

- the target package undefines NDEBUG thus making asserts available in release builds

- a user may choose to omit the tests from a build not carrying them around

- a file of 2.5k lines of codes becomes 152 lines smaller.

Closes gh-91288.

### CODE REVIEW

**Comment by arhadthedev** [comment]
`Tests / Check if generated files are up to date` fails with:

> ./_bootstrap_python ./Programs/_freeze_module.py abc ./Lib/abc.py Python/frozen_modules/abc.h
> make[1]: execvp: ./_bootstrap_python: Permission denied
> ./_bootstrap_python ./Programs/_freeze_module.py codecs ./Lib/codecs.py Python/frozen_modules/codecs.h
> make[1]: execvp: ./_bootstrap_python: Permission denied

**Comment by rhettinger** [comment]
I don't see the point of this.  It seem like unnecessary code churn that just moves related pieces of code farther apart.   The method is only visible in debug builds which is the entire point of the having the test method.

> an internal, CPython-specific method stops being available in a public interface of the set class

If it isn't in a release build and isn't [documented as public](https://docs.python.org/3/c-api/set.html) , then it isn't public.

**Comment by arhadthedev** [comment]
@rhettinger There is no sense to keep some test cases separately from the rest of the C API tests after their dependency on private functions is eliminated.

**Comment by rhettinger** [comment]
Thank for the suggestion but I'm going to decline.  AFAICT no real user problem is being solved here.  Also, as the maintainer of the code, it is a bit easier for me to have it all in one place.

**Comment by arhadthedev** [comment]
> it is a bit easier for me to have it all in one place.

Actually, I don't object. I agree that unnavigable ~8k lines of `_testcapimodule.c` is hardly a solution. I've just got an impression that all tests gravitate torwards `Lib/test` so decided to move the piece to its kins without second thought.

**Pull request closed without merging**
