### PR TITLE
Bump test deps: `ruff` and `mypy`

### PR DESCRIPTION
**Pull request by art3xa**
Release post: https://mypy-lang.blogspot.com/2023/10/mypy-16-released.html

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
mypy 1.6.0 has some major bugs, 1.6.1 is great to have!

**Comment by hugovk** [comment]
@art3xa Please could you take care of the backports?

**Comment by art3xa** [comment]
> @art3xa Please could you take care of the backports?

Yes, I can

**Comment by sobolevn** [comment]
Congrats on your first CPython contribution, @art3xa! Please, feel free to ask for help during the backport process if something is not right :)

**Pull request merged**
