### PR TITLE
Revert "GH-96145: Add AttrDict to JSON module for use with object_hook (#96146)"

### PR DESCRIPTION
**Pull request by ambv**
This reverts commit 1f0eafa844bf5a380603d55e8d4b42d8c2a3439d.

More discussion on the issue.

* Issue: gh-96145

----
:books: Documentation preview :books:: https://cpython-previews--105948.org.readthedocs.build/

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Review by CAM-Gerlach — APPROVED** [review]

**Review by AlexWaygood — APPROVED** [review]

**Review by brettcannon — APPROVED** [review]

**Review by vstinner — APPROVED** [review]
I'm not against the concept, it sounds appealing. But it seems like the implementation has some issues and deserves to be discussed. Maybe it was too early to put it in Python 3.12.

**Review by corona10 — APPROVED** [review]

**Review by erlend-aasland — APPROVED** [review]
+1 for this revert.

**Comment by rhettinger** [comment]
>  the implementation has some issues 

Please elaborate. This is the simplest possible implementation that meets the spec of being fully substitutable for a regular dict while allowing optional attribute access for all valid identifiers that aren't keywords or dict methods.  The implementation is pretty much unchanged since introduced by Martelli twenty years ago and is the usual recipe that people have been using in practice.

While it is possible to contrive a funky case like Jelle's `pop` example, this seems to *never* arise in practice. People who wrangle data for living will benefit by having this option for JSON's object hook. It greatly improves the readability of data access code in much the same way as dataclasses, namedtuple, Enum, Panda's dataframes, and SimpleNamespace. 

I would support marking this as "provisional" to leave wiggle room for dealing with "pop" example, but I think it should not be reverted.  The code is immediately usable and will be of great service to the data wranglers who deal with heavily next JSON.  If you all decide to take this code out, I predict that it will never get done and will be gone forever.

We've already has two decades of people reinventing this for the own projects, so it is not doing to mature much from here.  Also, the people like CAM Gerlack who fundamentally oppose this programming practice data will likely never change their minds despite the successes of dataclasses, SimpleNamespace, and argparse.Namespace. I can't know for sure what it is in their minds, but I suspect they haven't personally felt the pain of using chains of square brackets and quotes for lookups into known schemas.

**Comment by rhettinger** [comment]
@JelleZijlstra Would this minor edit satisfy your concern about the `ad.pop = 3` corner case?

```
    def __setattr__(self, attr, value):
        if hasattr(dict, attr):
            raise AttributeError(f'Cannot set attribute {attr!r}.  Try d[{attr!r}] instead.')
        self[attr] = value

    def __delattr__(self, attr):
        if hasattr(dict, attr):
            raise AttributeError(f'Cannot delete attribute {attr!r}.  Try d[{attr!r}] instead.')
        try:
            del self[attr]
        except KeyError:
            raise AttributeError(attr) from None
```

**Comment by Yhg1s** [comment]
As RM, can I please ask that we not iterate on design right before the final beta release? We'd have one chance to get it exactly right, and regardless of my own opinion on the suitability of the feature, I don't want to deal with the fallout of getting this wrong.

**Review by gpshead — APPROVED** [review]

**Pull request merged**
