### PR TITLE
bpo-19569: Add a macro to suppress deprecation warnings (counterpart of Py_DEPRECATED())

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Co-Authored-By: Arfrever Frehtes Taifersar Arahesis <arfrever.fta@gmail.com>

https://bugs.python.org/issue19569

### CODE REVIEW

**Review by jdemeyer — COMMENTED** [review]
I think you should explain more clearly why this is needed.

**Comment by ZackerySpytz** [comment]
These macros can be used to locally suppress deprecation warnings if a deprecated C API function needs to be used. There was some relevant discussion on the BPO issue.

**Comment by jdemeyer** [comment]
> There was some relevant discussion on the BPO issue.

Could you give a more concrete pointers? I didn't find the justification for this PR.

**Comment by methane** [comment]
> Could you give a more concrete pointers? I didn't find the justification for this PR.

When I uncomment `Py_DEPRECATED` macros in Include/cpython/unicodeobject.h,
I see some warning in `_testcapimodule.c`.

**Comment by methane** [comment]
It seems these macros are too much.
I just want a `Py_SUPRESS_DEPRECATED_DECLS` macro.

**Comment by methane** [comment]
@ZackerySpytz Would you make these macros private? (e.g. adding _ prefix).
I want to use it in Python 3.9, but I don't want to add public API to 3.9.

**Pull request merged**
