### PR TITLE
bpo-24538: Fix bug in shutil involving the copying of xattrs to read-only files.

### PR DESCRIPTION
**Pull request by obilaniu**
Implements solution recommend in https://bugs.python.org/issue24538#msg301493

https://bugs.python.org/issue24538

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by giampaolo — APPROVED** [review]
LGTM. This also needs a backport for 3.7 and 2.7. Also se my comment at https://bugs.python.org/issue24538#msg342051

**Comment by obilaniu** [comment]
May I call for a backport to 3.5 & 3.6 as well? They are often used in my field as well.

The backport to 3.7 “failed” (#13234), but only [because of a flaky test](https://github.com/python/cpython/pull/13234#issuecomment-491154867). Can we ignore it?

**Comment by giampaolo** [comment]
@obilaniu 3.6 and 3.5 branches accept security patches only:
https://devguide.python.org/#status-of-python-branches

**Comment by giampaolo** [comment]
@obilaniu could you please create a PR for 2.7 branch as well? 
https://github.com/python/cpython/pull/13212#issuecomment-491381681

**Comment by obilaniu** [comment]
@giampaolo Oh ok, then I think 3.7 is plenty good enough.

I looked at Python 2.7 and it looks unaffected by the problem. The failing codepaths related to copying xattrs are absent in Python 2, and indeed things like `pip install .` do work in Python 2 and not on Python 3. Perhaps you might choose to withdraw the `needs backport to 2.7` tag.

**Pull request merged**
