### PR TITLE
GH-109408: Move the Python file whitespace check from patchcheck to pre-commit

### PR DESCRIPTION
**Pull request by AA-Turner**
* Issue: gh-109408

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]

**Review by hugovk — APPROVED** [review]

**Comment by hugovk** [comment]
Thanks!

**Comment by hugovk** [comment]
@AA-Turner Please could you take care of the backports in https://github.com/python/cpython/pull/109890 and here?

**Comment by hugovk** [comment]
I've found a problem with this (and the C one) when running on macOS, pre-commit cannot find an executable called `python`:

```console
❯ pre-commit run --all-files
Run Ruff on Lib/test/....................................................Passed
Run Ruff on Argument Clinic..............................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
Check Python file whitespace.............................................Failed
- hook id: python-file-whitespace
- exit code: 1

Executable `python` not found

Check C file whitespace..................................................Failed
- hook id: c-file-whitespace
- exit code: 1

Executable `python` not found

Sphinx lint..............................................................Passed
Check hooks apply to the repository......................................Passed
Check for useless excludes...............................................Passed
```

It works with `python3`, but that's not going to work with Windows.

Is there a portable solution?

One option could be like https://github.com/pre-commit/pre-commit-hooks/blob/main/.pre-commit-hooks.yaml which has entries such as:

```yaml
-   id: check-added-large-files
    name: check for added large files
    description: prevents giant files from being committed.
    entry: check-added-large-files
    language: python
    stages: [commit, push, manual]
```

Which uses a file like https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/check_added_large_files.py

**Comment by hugovk** [comment]
(So let's hold off on the backports until this is fixed.)

**Comment by AA-Turner** [comment]
The `pre-commit` website [(implicitly) suggested](https://pre-commit.com/#arguments-pattern-in-hooks) using ``python`` for ``system`` languages, I hadn't realised it wouldn't work on Macs.

The drawback with [``language: python``](https://pre-commit.com/#python) is that it seems there's no option to run outwith a venv, so we'd suffer an unnecessary slowdown.

A

**Pull request merged**
