### PR TITLE
gh-90667: fix incompatible pointer type warnings

### PR DESCRIPTION
**Pull request by erlend-aasland**

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Alternatively, we can fix the callers.

**Comment by sweeneyde** [comment]
Out of curiosity, what does the compiler warning say?

**Comment by erlend-aasland** [comment]
> Out of curiosity, what does the compiler warning say?

It's the GitHub CI that complains about incompatible pointer type `-Wincompatible-pointer-types`.

<details>
<summary>Screenshot</summary>

bilde

</details>

**Review by sweeneyde — APPROVED** [review]
The change looks fine, I'm just confused why I'm not seeing the compiler warnings anywhere on other PRs.

**Comment by erlend-aasland** [comment]
> The change looks fine, I'm just confused why I'm not seeing the compiler warnings anywhere on other PRs.

I accidentally noticed it in GH-30872. I haven't checked other PRs yet, but I suspect it will only appear on PRs that either touch longobject.c or ceval.c. I'll have a look, FWIW.

**Comment by sweeneyde** [comment]
Could it be that some of these have been fixed by https://github.com/python/cpython/pull/91711?

**Comment by erlend-aasland** [comment]
> Could it be that some of these have been fixed by #91711?

Ah, that passed me by; sorry for the noise. I'll close this, then.

**Pull request closed without merging**
