### PR TITLE
Regenerate the PEG parser to pick up latest changes

### PR DESCRIPTION
**Pull request by pablogsal**
Automerge-Triggered-By: @pablogsal

### CODE REVIEW

**Comment by ambv** [comment]
Should I wait for this before cutting beta1? 🧐

**Comment by pablogsal** [comment]
> Should I wait for this before cutting beta1? 🧐

Yes, please! I was just going to ping you now :)

**Comment by pablogsal** [comment]
This was caused by merging a PR that had an old version of the automatically-generated files in which the CI passed but it was not up-to-date.

**Comment by ambv** [comment]
Not urgent but try figuring out if we can ensure that those are never out-of-date for future releases. This sounds like a nasty thing to overlook.

**Comment by pablogsal** [comment]
> Not urgent but try figuring out if we can ensure that those are never out-of-date for future releases. This sounds like a nasty thing to overlook.

Will try to think about that but sadly, other automatically-regenerated files have the same problem, is just that the PEG parser is being updated more often. IIRC there was some discussion about trying to ensure that all PRs are updated against `master` and the conclusion was that is not possible to do in an easy way :(

**Pull request merged**
