### PR TITLE
bpo-35913: asyncore: allow handling of half closed connections

### PR DESCRIPTION
**Pull request by iboukris**
See issue-35913.

https://bugs.python.org/issue35913

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by eamanu — CHANGES_REQUESTED** [review]
Please sign CLA. And add and news entry

**Comment by iboukris** [comment]
@eamanu, will do asap, just wanted get CI meanwhile, thanks.

**Comment by eamanu** [comment]
Could you add some tests?

**Comment by iboukris** [comment]
I'll work on a test, to better demonstrate as well.

**Comment by iboukris** [comment]
I've added a test which demonstrate proper handling of half closed socket using the new handle_eof() method. Strangely, it fails on macOS when using poll(), but I think it's a macOS bug so I just skip it for now on this platform (can't debug it in depth right now, but it wouldn't be their first but in this area).

**Comment by iritkatriel** [comment]
Closed under bpo-45552.

**Pull request closed without merging**
