### PR TITLE
gh-117398: Add multiphase support to _datetime

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-117398

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@ericsnowcurrently: this works nice for a single test run, but obviously fails if we're running ref-leak tests (the reload reinitializes the singletons in the global state).

**Comment by erlend-aasland** [comment]
One way to fix reloading is to use an initialization guard.

**Comment by tonybaloney** [comment]
thank you for doing this!

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Comment by ncoghlan** [comment]
@ericsnowcurrently @erlend-aasland Are we sure this won't segfault in the case I described in https://github.com/python/cpython/issues/117398#issuecomment-2106112547 ? (acquire a capsule reference, reload the module, use the capsule with the reloaded module)

The addition of the `no_rerun` guard on the C API test case makes me more concerned about that risk than I already was.

**Comment by erlend-aasland** [comment]
This is an incomplete first step of a series of multiple PRs. Eric and I propose to handle the encapsulated C API last. The scenario you describe will probably segfault.

**Comment by erlend-aasland** [comment]
FTR, the test guard was added because running with `test -R : ` leaks.

**Comment by erlend-aasland** [comment]
Actually, the scenario you are describing _is_ what happens when you do a ref-leak run of the C API test: the `_testcapimodule` reuses the pointer to the encapsulted C API, but the `_datetime` module is reloaded (and its exec function is run) every time. I didn't check coverage (yet), but so far this only causes leaks.

**Comment by vstinner** [comment]
This change introduced a reference leak: see issue gh-119655.

**Pull request merged**
