### PR TITLE
bpo-29808: Do not fail in SysLogHandler constructor if syslog isn't available.

### PR DESCRIPTION
**Pull request by vsajip**

### CODE REVIEW

**Comment by Mariatta** [comment]
Although the diff looks correct, this seems to include a whole bunch of unrelated changes.

**Comment by vsajip** [comment]
That's just the messages from empty merge commits in my 3.5 branch. I would expect the spurious messages to all go away when the squash+merge is done.

**Comment by Mariatta** [comment]
Thanks @vsajip :)
For the future we shouldn't cherry-pick directly in the maintenance branch, but rather in a separate branch.
The devguide has new [recommendation](http://cpython-devguide.readthedocs.io/gitbootcamp.html#backporting-merged-changes) on how to backport using [cherry_picker.py](https://github.com/python/core-workflow/tree/master/cherry_picker) which takes care of the rebase, branching, and opening up the PR page.

**Comment by vsajip** [comment]
Does that mean that we shouldn't have our own copies of maintenance branches? I use git worktree and have separate working directories for 3.5, 3.6 and master. I switch to the relevant directory, apply the cherry-pick, run tests and push ... then create a PR using the GitHub UI.

**Pull request merged**
