### PR TITLE
Add @maxking to CODEOWNERS file

### PR DESCRIPTION
**Pull request by maxking**

### CODE REVIEW

**Review by eamanu — APPROVED** [review]

**Comment by Mariatta** [comment]
Hmm we've never tried adding non core developers into `CODEOWNERS` yet, so I'm not sure if this will work. The effect of `codeowners` file is that you will be automatically requested review for the matched PR, and I don't know if we can request review from people outside of Python org.

But anyway, let's try this, and we can always revert the change.

**Review by Mariatta — APPROVED** [review]

**Comment by maxking** [comment]
Thanks @Mariatta ! Now all I need to do is open a PR and see if it works ;-)

**Comment by tirkarthi** [comment]
https://help.github.com/en/articles/about-code-owners

> People with admin or owner permissions can set up a CODEOWNERS file in a repository. The people you choose as code owners must have write permissions for the repository.

**Comment by brettcannon** [comment]
I opened #13660 to revert this since @tirkarthi found that reference saying @maxking would need to have write access to get notifications.

Maybe once the new "triage" access is launched that will work with CODEOWNERS and then we can give @maxking that level of access.

**Pull request merged**
