### PR TITLE
bpo-31722: Update codecs.IncrementalDecoder to use __subclasshook__

### PR DESCRIPTION
**Pull request by corona10**
I 've updated to codecs.IncrementalDecoder to be able to get True from below code snippets.

```python
>>> issubclass(_pyio.IncrementalNewlineDecoder, codecs.IncrementalDecoder)
True
>>> issubclass(_io.IncrementalNewlineDecoder, codecs.IncrementalDecoder)
True
>>> issubclass(io.IncrementalNewlineDecoder, codecs.IncrementalDecoder)
True
>>> class A(_io.IncrementalNewlineDecoder):
...     pass
...
>>> class B(_pyio.IncrementalNewlineDecoder):
...     pass
...
>>> issubclass(A, codecs.IncrementalDecoder)
True
>>> issubclass(B, codecs.IncrementalDecoder)
True
```

https://bugs.python.org/issue31722

### CODE REVIEW

**Comment by corona10** [comment]
@serhiy-storchaka @vstinner 

For reviewers,
IMHO, The more straightforward way to solve this issue is set tp_base of `_io.IncrementalNewlineDecoder `to `codecs.IncrementalDecoder`.
But I can't find a way to this on C API level to work with pure python object type.

So my choice is to use ABC.abc.
Please let me know if I am going in the wrong way.

Thanks always!

**Comment by corona10** [comment]
Or How about switching `IncrementalDecoder` into the C implementation and then
inherit it on the `_pyio.IncrementalDecoder` and `_io.IncrementalDecoder`?

**Comment by serhiy-storchaka** [comment]
The problem is not that `issubclass()` returns False, but that two classes are not truly compatible.

**Comment by serhiy-storchaka** [comment]
Implementing `IncrementalDecoder` in C could work, but it would add more complexity. I do not know what is the best solution of this issue.

**Comment by corona10** [comment]
@serhiy-storchaka 

Yes, I tried it today and I found that it is a complex issue better than I expected.
Since this class is used in the below pattern.

```python
class IncrementalDecoder(mbc.MultibyteIncrementalDecoder,
                                              codecs.IncrementalDecoder):
```

We should implement it to be able to avoid lay-out conflict.

**Pull request closed without merging**
