### PR TITLE
gh-109413: Add more type hints to `libregrtest`

### PR DESCRIPTION
**Pull request by sobolevn**
While working on https://github.com/python/cpython/issues/126237 I've noticed that there are quite a lot of simple and uncontroversial type hints that I can add to `libregrtest`.

I also bumped mypy to the recent version (it is the same as 1.12, but faster).

* Issue: gh-109413

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by sobolevn** [comment]
Thank you! I think that we backport such changes (based on experience of https://github.com/python/cpython/issues/109413), so I will add labels!

**Comment by AlexWaygood** [comment]
Thanks! If you're interested in working in more improvements here, the mypy config we use for `libregrtest` is extremely lenient at the moment; ideally we'd make it stricter. In particular, we still have `strict_optional = false` for several submodules of `libregrtest` 😱 <https://github.com/python/cpython/blob/main/Lib/test/libregrtest/mypy.ini>

> I will try to create a manual backport to 3.12, but it is not easy: #125597

I wouldn't worry about it _too_ much if it's hard. I wouldn't say that these changes are important to backport in and of themselves. The main reason to backport them is to reduce the risk of merge conflicts when backporting future bugfixes (which _are_ important to backport) to `libregrtest`. If we run into such merge conflicts in the future, I think it shouldn't be too hard to just remove the type hints from certain functions in order to solve the conflicts with the 3.12 branch.

**Comment by sobolevn** [comment]
Yes, I am working on some further fixes :)
But before I fix fixes here, I have to fix fixes in mypy first 😆 
https://github.com/python/mypy/pull/18103

**Pull request merged**
