### PR TITLE
Use _PyLong_GetOne() in long_pow()

### PR DESCRIPTION
**Pull request by hikariyo**
Just another place like what #125044 did. It makes code clearer.

### CODE REVIEW

**Comment by rruuaanng** [comment]
Please add title label, like this
```
gh-<issue_id>: xxx
```

**Comment by hikariyo** [comment]
> Please add title label, like this
> 
> ```
> gh-<issue_id>: xxx
> ```

This is a trivial change which might skip issue 😊

**Comment by rruuaanng** [comment]
And, this has been rejected by the core-dev, I don't think this modification is meaningful.

**Comment by hikariyo** [comment]
> And, this has been rejected by the core-dev, I don't think this modification is meaningful.

But similar change has been merged as I mentioned, and I think the last PR has been rejected because it changed so many places which makes code ugly, different from this PR.

**Comment by rruuaanng** [comment]
My suggestion is to open an issue and listen to other people's opinions.

**Comment by rruuaanng** [comment]
You might be talking about this
https://github.com/python/cpython/pull/125044/files

In fact, changing the code style alone isn't allowed. You should also modify other functions to pass.

**Comment by hikariyo** [comment]
Okay, sorry to trouble you 🙏.

**Comment by erlend-aasland** [comment]
> And, this has been rejected by the core-dev, I don't think this modification is meaningful.

@rruuaanng, please try and keep a polite tone.

@hikariyo: Thanks for the PR, but as has been noted, pretty much all code changes, including refactorings[^1], need issues. Please see the [devguide for more info](https://devguide.python.org/getting-started/pull-request-lifecycle/) :)

[^1]: this PR counts as refactoring

**Comment by rruuaanng** [comment]
> > And, this has been rejected by the core-dev, I don't think this modification is meaningful.
> 
> 
> 
> @rruuaanng, please try and keep a polite tone.
> 
> 
> 
> @hikariyo: Thanks for the PR, but as has been noted, pretty much all code changes, including refactorings[^1], need issues. Please see the [devguide for more info](https://devguide.python.org/getting-started/pull-request-lifecycle/) :)
> 
> 
> 
> [^1]: this PR counts as refactoring

I'm sorry, I'm not hostile. Maybe I should bring a smile🙂

**Comment by erlend-aasland** [comment]
> I'm sorry, I'm not hostile. Maybe I should bring a smile

It often helps to use more friendly words. Instead of _"I don't think this modification is meaningful"_, try instead to _ask_ what the author intends to achieve with the change. @rruuaanng, see also https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution.

**Pull request closed without merging**
