### PR TITLE
fix in docs: import auto in enum chapter

### PR DESCRIPTION
**Pull request by JulianKahnert**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by JulianKahnert** [comment]
CLA should be signed now

**Review by Mariatta — CHANGES_REQUESTED** [review]
The change is good, but please make sure Travis CI passes. I couldn't view the log. My guess is maybe there's trailing whitespace.
Also, the [3.6] should be removed from PR title.
This change is targeting the master branch. `[3.6]` in PR title are meant for PRs targeting the 3.6 branch. Thanks.

**Comment by JulianKahnert** [comment]
TravisCI failed because of a github timeout error ... try to trigger the build process [again](https://stackoverflow.com/a/17624403).

**Pull request closed without merging**
