### PR TITLE
gh-126433: Fix compiler warning on 32-bit Windows

### PR DESCRIPTION
**Pull request by vstinner**
* Issue: gh-126433

### CODE REVIEW

**Comment by vstinner** [comment]
Fix the following warning:

> C:\victor\python\main\Modules_hacl\Lib_Memzero0.c(39,27): warning C4244: 'function': conversion from 'uint64_t' to 'SIZE_T', possible loss of data [C:\victor\python\main\PCbuild\pythoncore.vcxproj]

@msprotz: Should I fix the issue in HACL upstream first? Or do you want to fix it upstream?

**Comment by vstinner** [comment]
SecureZeroMemory() second parameter type is SIZE_T: https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366877(v=vs.85)

**Comment by msprotz** [comment]
If you could fix upstream that would be optimal. The file is in `hacl-star/lib/c/` I believe. Thanks!!

**Comment by vstinner** [comment]
> If you could fix upstream that would be optimal. The file is in hacl-star/lib/c/ I believe. Thanks!!

@msprotz: I created https://github.com/hacl-star/hacl-star/pull/1004.

**Comment by vstinner** [comment]
> @msprotz: I created https://github.com/hacl-star/hacl-star/pull/1004.

It has been merged. Can I run `make regen-sbom` or should I updated hacl-star in Python somehow?

**Comment by msprotz** [comment]
You need to:
- go into Modules/_hacl, edit refresh.sh to point to the new hash, and run refresh.sh
- `git grep` for the old hash in the root directory, replaces all occurrences of the old hash with the new hash (they appear in various json files)
- make regen-sbom

And then you should be good! Cheers.

**Comment by vstinner** [comment]
> And then you should be good! Cheers.

I updated `lib/c/Lib_Memzero0.c` in hacl-start upstream, but I didn't see the different copies:

```
$ find -name "Lib_Mem*c"
./dist/gcc-compatible/Lib_Memzero0.c
./dist/mozilla/Lib_Memzero0.c
./dist/msvc-compatible/Lib_Memzero0.c
./dist/portable-gcc-compatible/Lib_Memzero0.c
./lib/c/Lib_Memzero0.c
```

On my upstream PR, the bot said "dist is not automatically re-generated, be sure to do it manually." Oops, I didn't do that!

Should I modify manually the 5 files?

**Comment by msprotz** [comment]
https://github.com/hacl-star/hacl-star/pull/1005#issuecomment-2465394901

**Comment by vstinner** [comment]
I created PR gh-126791 to update hacl-star and retrieve the change fixing the warning. I close this PR.

**Pull request closed without merging**
