### PR TITLE
bpo-39474: Fix AST pos for expressions like (a)(b), (a)[b] and (a).b.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue39474

### CODE REVIEW

**Review by lysnikolaou — APPROVED** [review]
LGTM!

**Review by isidentical — APPROVED** [review]

**Review by gvanrossum — APPROVED** [review]
From a quick glance LG.

Would it make sense to add a test for e.g. `((a)).b`?

**Comment by serhiy-storchaka** [comment]
We can add complex examples like `((((a+b).c)[d])(e))().f`, but it would not cover anything that was not already covered by the minimal example `(a).b`.

**Comment by gvanrossum** [comment]
I don't need complex example, but I'd like a single example showing `((a)).b`, since IIRC there's some special code involved in removing redundant parentheses, and I feel that that special case was involved in the bug in the first place.

**Comment by gvanrossum** [comment]
Honestly I take it back, you can land.

**Pull request merged**
