### PR TITLE
gh-100238: Use setuptools in peg-generator and reenable tests

### PR DESCRIPTION
**Pull request by lysnikolaou**
* Issue: gh-100238

### CODE REVIEW

**Comment by pablogsal** [comment]
@lysnikolaou you need to probably rebase the changes in the PR that removes the endings from lines (also two windows tests are failing).

**Comment by pablogsal** [comment]
We still have the failing windows tests. This may be something regarding the name of the binary perhaps?

**Comment by lysnikolaou** [comment]
It appears so and I'm not sure why. The only other test that uses this (`test_cppext`) is skipped on Windows, so we don't really have something to compare.

**Comment by pablogsal** [comment]
> It appears so and I'm not sure why

Do you know if `python_d.exe` is correct on Windows? I think that otherwise this line is kind of wrong:

> Run: D:\a\cpython\cpython\PCbuild\win32\python_d.exe -X dev -m venv venv

**Review by pablogsal — APPROVED** [review]
Great job @lysnikolaou :heart:

**Comment by lysnikolaou** [comment]
Probabaly no backport for this, right?

**Comment by pablogsal** [comment]
> Probabaly no backport for this, right?

I don't think so, but I also don't think it would hurt

**Comment by hroncok** [comment]
@pablogsal I built https://github.com/python/cpython/pull/105056 on top. I think it would be reasonable to backport this to 3.12, so I can backport mine as is. WDYT?

**Comment by hroncok** [comment]
I've asked Petr to label this with the 3.12 label so we know the CI results before a decision is made.

**Comment by encukou** [comment]
(I pushed the button to open the 3.12 PR for Miro; I'm not implying it should be merged.)

**Comment by pablogsal** [comment]
> I'm okay with backporting, since this is just re-enabling a test, so it really wouldn't hurt. I'll leave it up to @pablogsal though.

The problem with the back port is that we have ref leaks with this PR on `main` no? If we back port without fixing them we are going to have them also on 3.12

**Comment by lysnikolaou** [comment]
> > I'm okay with backporting, since this is just re-enabling a test, so it really wouldn't hurt. I'll leave it up to @pablogsal though.
> 
> The problem with the back port is that we have ref leaks with this PR on `main` no? If we back port without fixing them we are going to have them also on 3.12

That's right, I meant after fixing the refleaks.

**Comment by pablogsal** [comment]
> > > I'm okay with backporting, since this is just re-enabling a test, so it really wouldn't hurt. I'll leave it up to @pablogsal though.
> > 
> > 
> > The problem with the back port is that we have ref leaks with this PR on `main` no? If we back port without fixing them we are going to have them also on 3.12
> 
> That's right, I meant after fixing the refleaks.

In that case I am ok back porting 👍

**Pull request merged**
