### PR TITLE
bpo-44807: Forbid to define __init__ method in Protocol classes

### PR DESCRIPTION
**Pull request by uriyyo**
https://bugs.python.org/issue44807

### CODE REVIEW

**Comment by uriyyo** [comment]
@Fidget-Spinner Could you please review this PR?

**Comment by ambv** [comment]
Looks related to BPO-44806 as well.

**Comment by uriyyo** [comment]
@ambv I am not sure about that.

This issue more about that `__init__` method of `Protocol` is simply replaced with another implementation without any warnings or errors. It's seems not related to BPO-44806

**Comment by ambv** [comment]
Apart from this conflicting with current `typing.py` and tests, I'm honestly not sure what to do with this PR. Discussion on the issue.

**Comment by ambv** [comment]
Per issue resolution, we're leaving this for now as it's unclear if `__init__()` shouldn't be instead treated as part of a protocol definition.

**Pull request closed without merging**
