### PR TITLE
gh-71052: Use `raise_signal` rather than `kill` in `ThreadSignals.test_signals`

### PR DESCRIPTION
**Pull request by mhsmith**
On Android, we run the test suite embedded in a standard app, in order to be representative of the environment where Python is most likely to be used. This means there's a native thread that uses `sigwait` to listen for SIGUSR1 in a loop, and responds by triggering the Java garbage collector and logging a message. This is only used for debugging purposes, and in most cases it doesn't matter because any signal handler will take priority over it.

However, in `ThreadSignals.test_signals` there's a background thread which sends both SIGUSR1 and SIGUSR2, and then immediately exits. So if the background thread is unavailable because it’s exited, and the main thread is unavailable because it’s already processing one of the signals (see `complete_signal` in [kernel/signal.c](https://github.com/torvalds/linux/blob/master/kernel/signal.c)), then the other signal may be delivered to Android’s `sigwait` loop instead of the test's own handler. This happens about 1 time out of 4.

This PR fixes that by sending the signals using `raise_signal` (which is directed at the current thread) rather than `os.kill` (which is directed at the whole process). Not only does this avoid the above scenario, it also strengthens the test by verifying that a signal which is *delivered* to a background thread, and not merely *sent* by it, still runs the Python-level handler on the main thread.

Since `raise` ["shall not return until after the signal handler does"](https://pubs.opengroup.org/onlinepubs/9699919799/functions/raise.html), this also allows for the removal of a whole block of code which waits for the signal to arrive.

* Issue: gh-71052

### CODE REVIEW

**Comment by mhsmith** [comment]
This is a minor change to a test, so no news entry is required.

**Comment by mhsmith** [comment]
@vstinner: There's no CODEOWNERS entry for signals, but you've done some work in this area recently. Are you able to review this PR?

**Review by vstinner — APPROVED** [review]
LGTM.

The change works as expected. I stressed the test with `./python -m test test_threadsignals -m test_signals -j250 -F` . The system load was around 225.00 on a laptop with 12 logicial CPUs (6 cores), the test ran successfully 1676 times in 2 minutes.

**Comment by vstinner** [comment]
Merged, thanks!

**Pull request merged**
