### PR TITLE
gh-101100: Docs: Check Sphinx warnings and fail if improved

### PR DESCRIPTION
**Pull request by hugovk**
Recently I improved some colour contrast for [Pygments](https://github.com/pygments/pygments/pull/2448), and they have a file of current contrast ratios. If they're improved by a PR, the CI will [fail to make sure the ratio constants are updated](https://github.com/pygments/pygments/blob/14cff613a681d2c95bf2c56f81833f645353bbe0/tests/contrast/test_contrasts.py#L97-L100), to ensure continual improvement with no regressions.

This is a good idea!

Let's add it here, to check if any files in `.nitignore` (which may have Sphinx warnings) switch to having no warnings. Then we can remove them from `.nitignore` to make sure they remain free of warnings.

I was going to add another Sphinx build, a fourth, to touch the relevant files, so only those would be rebuilt. But four builds is far too many!

Instead, let's build only once and save the warnings to a file. Then we can process the file and do the three phases:

* Annotate PRs with Sphinx nitpicks (as before)
* Ensure some files always pass Sphinx nit-picky mode (as before)
* Check for improved files that can be removed from `.nitignore` (new!)

----
:books: Documentation preview :books:: https://cpython-previews--106460.org.readthedocs.build/

* Issue: gh-101100

### CODE REVIEW

**Comment by hugovk** [comment]
Marked as draft to make some temporary commits to demonstrate errors.

First, the new check finds five files that no longer contain warnings!

```
Congratulations! You improved:

Doc/c-api/dict.rst
Doc/c-api/weakref.rst
Doc/library/cgi.rst
Doc/library/cmath.rst
Doc/library/curses.ascii.rst

Please remove from Doc/tools/.nitignore
```

https://github.com/python/cpython/actions/runs/5468129112/jobs/9955353278?pr=106460

Some of these files were deleted along with [PEP 594's dead batteries](https://peps.python.org/pep-0594/). Others have been "accidentally" fixed since `.nitignore` was first compiled.

**Comment by hugovk** [comment]
Adding a (temporary) warning to `3.12.rst`, which is not allowed warning, gives:

```
Error: must not contain warnings:

Doc/whatsnew/3.12.rst
Warning: /home/runner/work/cpython/cpython/Doc/whatsnew/3.12.rst:9: WARNING: c:func reference target not found: PyFrame_BlockSetup
```

Plus the file is annotated.

**Comment by hugovk** [comment]
Updating from main finds a new file that's been fixed! 🎉 

```
Congratulations! You improved:

Doc/library/getopt.rst

Please remove from Doc/tools/.nitignore
```

**Comment by hugovk** [comment]
3.12 doesn't yet have the refactored `.github/workflows/reusable-docs.yml` workflow, so let's leave this backport for that 👍

**Comment by CAM-Gerlach** [comment]
Looks like that was landed and this is required to backport #108065 , so retrying the backport.

**Comment by CAM-Gerlach** [comment]
Had to manually backport it due to conflicts in .nitignore, and might need to resolve a few additional discrepancies there once it builds.

**Pull request merged**
