### PR TITLE
gh-109120: Fix handle of incorrect star expressions

### LINKED ISSUE #109120: incorrect SyntaxError
# Bug report

### Bug description:

The following input will cause a `SyntaxError`.  That's all well and good, but the message for the `SyntaxError` is incorrect.
```python
f(A,*)
```
```python
SyntaxError: iterable argument unpacking follows keyword argument unpacking
```
This is not correct.  That error message is intended for cases like this `f(**kwargs, *args)`.
This bug is present on `3.9`, `3.10`, and `3.11`.  I haven't tested `3.12`, but I suspect that it is present there as well.  The bug is not present on `3.8`.

### CPython versions tested on:

3.8 3.9, 3.10, 3.11

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-117444
* gh-117464
* gh-117465

### PR DESCRIPTION
**Pull request by grigoriev-semyon**
Fixes: #109120 

* Issue: gh-109120

### CODE REVIEW

**Comment by pablogsal** [comment]
LGTM

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
@grigoriev-semyon Thanks for the PR! Can you work in the backports using `cherry_picker` as per https://github.com/python/cpython/pull/117444#issuecomment-2031666248?

**Comment by grigoriev-semyon** [comment]
> @grigoriev-semyon Thanks for the PR! Can you work in the backports using `cherry_picker` as per https://github.com/python/cpython/pull/117444#issuecomment-2031666248?

ofc :)

**Comment by grigoriev-semyon** [comment]
> @grigoriev-semyon Thanks for the PR! Can you work in the backports using `cherry_picker` as per [#117444 (comment)](https://github.com/python/cpython/pull/117444#issuecomment-2031666248)?

is it ok if I make regen-pegen in backport PR? There is some conflicts

**Pull request merged**
