### PR TITLE
[3.10] gh-91118: Fix docstrings that do not honor --without-doc-strings (GH-31769)

### PR DESCRIPTION
**Pull request by arhadthedev**
Co-authored-by: Éric <merwok@netwok.org>
Co-authored-by: Jelle Zijlstra <jelle.zijlstra@gmail.com>
(cherry picked from commit a573cb2fec664c645ab744658d7e941d72e1a398)

Co-authored-by: Oleg Iarygin <oleg@arhadthedev.net>

### CODE REVIEW

**Comment by arhadthedev** [comment]
A failed test has no relation with changed docstrings:

```plain
== Tests result: ENV CHANGED ==

417 tests OK.

10 slowest tests:
- test_concurrent_futures: 2 min 41 sec
- test_multiprocessing_spawn: 2 min 39 sec
- test_gdb: 2 min 1 sec
- test_multiprocessing_forkserver: 1 min 38 sec
- test_asyncio: 1 min 29 sec
- test_multiprocessing_fork: 1 min 21 sec
- test_peg_generator: 1 min 13 sec
- test_signal: 51.0 sec
- test_subprocess: 43.9 sec
- test_venv: 35.7 sec

1 test altered the execution environment:
    test_asyncio

9 tests skipped:
    test_devpoll test_ioctl test_kqueue test_msilib test_startfile
    test_winconsoleio test_winreg test_winsound test_zipfile64

Total duration: 9 min 15 sec
Tests result: ENV CHANGED
make: *** [Makefile:1255: buildbottest] Error 3
Error: Process completed with exit code 2.
```

**Comment by AlexWaygood** [comment]
> A failed test has no relation with changed docstrings:

The test is known to be flaky on the backport branches (I think @JelleZijlstra was having trouble with it recently).

**Comment by AlexWaygood** [comment]
> > A failed test has no relation with changed docstrings:
> 
> The test is known to be flaky on the backport branches, for some reason (I think @JelleZijlstra was having trouble with it recently). Not sure that anybody's worked out what the problem is, though.

https://github.com/python/cpython/pull/91667 looks like it should fix `test_asyncio` on 3.10.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by arhadthedev** [comment]
@AlexWaygood #91680 is merged so I've updated this PR.

**Pull request merged**
