### PR TITLE
gh-97588: Failing tests to demonstrate the issue

### PR DESCRIPTION
**Pull request by matthiasgoergens**
The tests are expected to fail, and are marked as such.

* Issue: gh-97588

### CODE REVIEW

**Comment by matthiasgoergens** [comment]
@mdickinson I marked the tests as failing, so we cant potentially get them into `main` as a basis for further work.

**Review by nanjekyejoannah — COMMENTED** [review]
Shouldn't we be patching a fix instead? Unless we are accepting this as desired behaviour.

**Comment by matthiasgoergens** [comment]
@nanjekyejoannah See https://github.com/python/cpython/pull/97702 for the fix.

**Review by nanjekyejoannah — COMMENTED** [review]
Then we close this to merge the fix instead, no?

**Comment by matthiasgoergens** [comment]
@nanjekyejoannah I'm not completely confident in the fix, yet. But I am confident that these test cases are good.

Not sure we have a general policy against contributing failing test cases?

**Comment by nanjekyejoannah** [comment]
The tests test the failing caes. But with the fix, these tests will change i.e not failing, I would prefer reviewing a PR with a fix and updated tests, since there is a fix. What do you think?

**Review by nanjekyejoannah — COMMENTED** [review]
The tests test the failing caes. But with the fix, these tests will change i.e not failing, I would prefer reviewing a PR with a fix and updated tests, since there is a fix. What do you think?

**Comment by matthiasgoergens** [comment]
@nanjekyejoannah Feel free to review https://github.com/python/cpython/pull/97702

**Comment by encukou** [comment]
These were merged with #97702. Thank you!

**Pull request closed without merging**
