### PR TITLE
bpo-43155: Add PyCMethod_New to PC/python3dll.c

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue43155

### CODE REVIEW

**Review by encukou — APPROVED** [review]
I don't have Windows to test with, but I agree that PyCMethod_New should be part of the limited ABI.

**Comment by vstinner** [comment]
> I don't have Windows to test with, but I agree that PyCMethod_New should be part of the limited ABI.

I concur with @encukou. I merged the fix, thanks.

**Comment by vstinner** [comment]
@ZackerySpytz: can you please try to backport it manually to 3.9?

**Comment by ZackerySpytz** [comment]
Okay, I will create a backport for 3.9.

**Pull request merged**
