### PR TITLE
gh-96678: Avoid undefined behaviour in test

### PR DESCRIPTION
**Pull request by matthiasgoergens**
Signed integer overflow is undefined behaviour.

* Issue: gh-96678

### CODE REVIEW

**Comment by matthiasgoergens** [comment]
@pablogsal Would you like to have a look, please?  Thanks!

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Could you do the backports using cherry_picker @matthiasgoergens ?

**Comment by matthiasgoergens** [comment]
Ok.  I'll use cherry_picker later. I'm not on my PC right now.

**Comment by matthiasgoergens** [comment]
@pablogsal Sorry, I was a bit late.  Does this still need the backport?

**Comment by pablogsal** [comment]
I think we are still missing the 3.10 backport

**Comment by matthiasgoergens** [comment]
Oh, I was confused about 3.11 vs 3.10 backport. Yes, I see know that the 3.10 one is still missing.

**Comment by matthiasgoergens** [comment]
@pablogsal Actually, since we are not going to drop `-fwrapv` for anything below 3.12, we don't need to backport this fix.

**Pull request merged**
