### PR TITLE
readme: fix displaying issue of command

### PR DESCRIPTION
**Pull request by mara004**
Avoid line break in command as this causes displaying issues (at least on GH).

Before:
image

After:
image

### CODE REVIEW

**Comment by Rowlando13** [comment]
The PR looks good. Looks like the original writer accidentally broken the line in the middle of the back ticks.  Also first review for this repo, so let me know if it is not helpful.

**Comment by mara004** [comment]
@Rowlando13 I guess it's sufficient to leave review to a CPython dev with subsequent merge rights.
+1's from external reviewers probably aren't necessary for minor changes like this.

**Comment by Rowlando13** [comment]
@mara004 Thanks for the feedback.

**Review by willingc — APPROVED** [review]
Looks good. Thanks @mara004

**Pull request merged**
