### PR TITLE
bpo-38089: Move Azure Pipelines to latest VM versions and make macOS tests optional

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue38089

### CODE REVIEW

**Comment by zooba** [comment]
Note that this will fail until #15850  and #15849  are merged.

**Comment by zware** [comment]
I'm a bit concerned about this one; this leaves us open to being broken by any image update.  With Azure being required, that means any update that breaks us forces us to manually intervene in any PR opened before the breakage is fixed.  We've had a few instances of that otherwise; I didn't like them :)

**Comment by zooba** [comment]
I guess given I found two other bugs by doing this, I can't really argue with the possibility :)

I'll see if I can figure out the current names of the images and use them explicitly.

**Comment by zooba** [comment]
@zware Waiting on your approval

**Review by zware — APPROVED** [review]
LGTM

**Pull request merged**
