### PR TITLE
bpo-33648: remove PY_WARN_ON_C_LOCALE

### PR DESCRIPTION
**Pull request by grimreaper**
This code does not appear to be used anywhere in the python code base. The
use was removed in eb81795d7d3a8c898fa89.

https://bugs.python.org/issue33648

### CODE REVIEW

**Comment by ncoghlan** [comment]
This seems to have lost quite a few `PKG-CONFIG` related settings as well.

Tagging @benjaminp since those settings appear to come from https://github.com/python/cpython/commit/03c0d2e1f272c7c6df5f6066a6abc222ff61073a#diff-9ceb48203b3fd0a963276aeb22265658 after mostly being removed in https://github.com/python/cpython/commit/540162260c09cf58c7477d4b94941e6908283970#diff-9ceb48203b3fd0a963276aeb22265658

**Comment by methane** [comment]
@grimreaper Would you minimize changes?

**Comment by grimreaper** [comment]
done. Not sure why they got lost in the first place.

**Comment by grimreaper** [comment]
hrm... a regen results in new unexpected changes. It seems someone ran a regen with a different set o tools than I do ?

**Comment by grimreaper** [comment]
Ah, I see
```
-[m4_define([PKG_MACROS_VERSION], [0.29.2])
+[m4_define([PKG_MACROS_VERSION], [0.29.1])
```

I'll try and fix this

**Pull request merged**
