### PR TITLE
bpo-42415: Add PyObject_CallNoArgs to PC\python3dll.c

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue42415

### CODE REVIEW

**Comment by davidhewitt** [comment]
Thanks! I'm curious if this will get backported to 3.9.x series on Windows (3.9.1?), or de-facto we're accepting that this function is actually not fully in the limited api until Python 3.10 (because users building from Windows can't link against this symbol right now on 3.9).

**Review by alex — APPROVED** [review]

**Comment by alex** [comment]
I've marked this for backporting to the 3.9 branch. There's obviously no putting the toothpaste back into the tube though, it'll never work on 3.9.0 for Windows :-(

**Comment by alex** [comment]
@python/windows-team -- FYI, not merging until one of y'all looks :-)

**Comment by vstinner** [comment]
I merged PR #23598 instead which adds more symbols. Thanks anyway for your PR!

**Pull request closed without merging**
