### PR TITLE
[3.13] gh-120782: Update internal type cache when reloading datetime (GH-120829)

### PR DESCRIPTION
**Pull request by neonene**
When reloading `_datetime` module, the single-phase version did not invoke the `PyInit__datetime` function, whereas the current multi-phase version updates the static types through the module init. The outdated static type cache in the interpreter state needs to be invalidated at the end of reloading the multi-phase module.

This PR is a manual backport of a81d434c06335b0989ba83666ec7076b9d9d4e1e, adding `assert` statements to the test case.
This also backports e6076d1e1303c3cc14bc02baf607535af2cf1501 (gh-120180) manually.

* Issue: gh-120782

### CODE REVIEW

**Comment by neonene** [comment]
cc @JelleZijlstra @ericsnowcurrently @kumaraditya303

**Review by JelleZijlstra — APPROVED** [review]

**Comment by neonene** [comment]
@ericsnowcurrently Backported e6076d1e1303c3cc14bc02baf607535af2cf1501 as well. (I can take back the change)

**Review by kumaraditya303 — APPROVED** [review]

**Comment by neonene** [comment]
Thanks.

**Comment by freakboy3742** [comment]
This backport appears to have broken the iOS buildbot. I’m AFK for the next week; I’ll take a look when I’m back at my desk.

**Comment by neonene** [comment]
> This backport appears to have broken the iOS buildbot. 

#121561 should be effective for fixing it.

**Pull request merged**
