### PR TITLE
[2.7] bpo-30310: tkFont now supports unicode options (e.g. font family).

### PR DESCRIPTION
**Pull request by serhiy-storchaka**

### CODE REVIEW

**Review by terryjreedy — CHANGES_REQUESTED** [review]
Needs currently failing test fixed by patch.  See issue for suggestion.

**Comment by serhiy-storchaka** [comment]
Is this good to you @terryjreedy?

**Review by terryjreedy — APPROVED** [review]

**Comment by terryjreedy** [comment]
I seem to have fixed the News merge conflict (until there is another one ;-). If you are happy with this, push before there is another conflict, and the need for another round of tests ;-).

**Comment by terryjreedy** [comment]
Sorry for delay.  Had unavoidable family business to attend to.

**Comment by serhiy-storchaka** [comment]
Thank you for your review.

**Pull request merged**
