### PR TITLE
the termios man page is in section 3

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
@EdwardBetts good catch, thank you! Could you please sign the CLA? While your patch may be trivial, it would be nice to sign it for your future contributions.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by EdwardBetts** [comment]
@berkerpeksag I've signed the CLA.

**Comment by berkerpeksag** [comment]
@EdwardBetts thank you! :)

**Pull request merged**
