### PR TITLE
Mock 100% coverage

### PR DESCRIPTION
**Pull request by cjw296**
Get Mock to 100% coverage and clean up a few things along the way.

### CODE REVIEW

**Comment by cjw296** [comment]
@mariocj89 / @tirkarthi - I'm unsure about whether this should be backported to the 3.7 branch:

- on the one hand, there's not "bugfix" code here, so it should be fine to not backport.
- on the other, without being backported, it may be more difficult to backport future bugfixes.
- the pypi.py mock package is hopefully going to be released "real soon now"

Thoughts?

**Comment by ZackerySpytz** [comment]
FWIW, I believe a BPO issue should have been created for this sizeable patch (as prescribed by the  [developer's guide](https://devguide.python.org/#quick-reference)).

**Comment by cjw296** [comment]
My apologies, would you like me to retrospectively open one?

**Comment by tirkarthi** [comment]
Please don't backport this to 3.7 . I feel this could have waited a bit since some of the internals of mock don't have tests and one refactoring that seemed harmless had produced regression (https://bugs.python.org/issue36593). I agree with Zackery that this could have had a bpo and possibly a review from @voidspace but it's little late since this is merged. But then we have beta period for bug fixing if any and can revert chunks of it if needed :)

**Comment by cjw296** [comment]
Well, actually, as of this PR, the internals of mock *do* have tests. Everything is covered, some of it was challenging ;-)

My intention was to get his into the backport so we could get some real world experience of it.
Interestingly, that has stalled on a weird and annoying failure on pypy:
https://travis-ci.org/testing-cabal/mock/jobs/527082522#L455

This is super weird, the first call to `mock.__sizeof__` fails, but subsequent ones succeed. Any ideas on that very gratefully received.

@voidspace / @mfoord is at PyCon and said he'd have time to sprint on Mock, so hopefully he can give this a good going over. I've got the backporting process to the standalone mock package working again, so whatever we find we can get quickly released onto pypi for more testing.

**Comment by tirkarthi** [comment]
> This is super weird, the first call to mock.__sizeof__ fails, but subsequent ones succeed. Any ideas on that very gratefully received.

Are you seeing this after the PR or before the PR itself? Please add the code and error. I could give it a try.

**Comment by cjw296** [comment]
Code is here:
https://github.com/testing-cabal/mock/tree/0459be22861214bef07c6a707d09ad22fec5af35

Failure is here:
https://travis-ci.org/testing-cabal/mock/jobs/527082522#L455

This is only on pypy...

**Comment by cjw296** [comment]
Oh. and here's the "fix": https://github.com/testing-cabal/mock/commit/252c749d7ea2e18f67618335f715b825d92fd5db

Now, why would pypy need that for magic mocks to work?!

**Pull request merged**
