### PR TITLE
gh-107507: Replace 'The goals of Argument Clinic' with a summary

### LINKED ISSUE #107507: Replace the "goals of Argument Clinic" with a link to PEP 436
The [Argument Clinic howto](https://docs.python.org/3/howto/clinic.html) starts with six paragraphs about the goals of Argument Clinic, mostly repeating the motivation and rationale of PEP-436. Here's a quick run-through of the paragraphs:

1. AC should take over arg parsing in CPython.
2. Hand-written arg parsing code is a chore; AC must be easy to use.
3. AC must generate correct and hopefully fast code; also an outdated section about the possibility of generating tailor made code for various cases.
4. AC should support all of CPython's "strange parsing behaviours".
5. AC should provide introspection signatures for builtins.
6. The last paragraph repeats information present in the tutorial.

Suggesting to remove the whole "The goals of Argument Clinic", and instead provide a short summary (one or two sentences) and link to PEP-436.

### Linked PRs
* gh-107508
* gh-107516
* gh-107517

### PR DESCRIPTION
**Pull request by erlend-aasland**
Instead of repeating the rationale and motivation of PEP-436,
reword the Abstract to provide a summary of the goals of AC.

* Issue: gh-107507

----
:books: Documentation preview :books:: https://cpython-previews--107508.org.readthedocs.build/

### CODE REVIEW

**Comment by erlend-aasland** [comment]
(Oh my, I can't believe I didn't create a feature branch for this PR 😅)

**Review by ezio-melotti — APPROVED** [review]

**Review by AlexWaygood — COMMENTED** [review]
Hmm, I thought the current policy was that PEPs were meant to be historical documents rather than living documentation, and that we should ideally have all relevant documentation in the CPython repo rather than referring people to PEPs. For the typing docs, we're trying to move _away_ from constant references to the typing PEPs (though progress has been slow on achieving that)

**Comment by erlend-aasland** [comment]
> Hmm, I thought the current policy was that PEPs were meant to be historical documents rather than living documentation, and that we should ideally have all relevant documentation in the CPython repo rather than referring people to PEPs. For the typing docs, we're trying to move _away_ from constant references to the typing PEPs (though progress has been slow on achieving that)

For this change, I think the existing text is way to elaborate; the goals of Argument Clinic can be summarised in a single sentence.

Also, we don't refer to the PEP as such, we only point out that Argument Clinic was introduced with a PEP.

**Review by AlexWaygood — APPROVED** [review]
Thanks, I think my initial reaction to this PR was overly coloured by the title you gave to the linked issue. Reading it over again, you're right that none of this information is relevant to users of argument clinic. This definitely improves things!

**Comment by erlend-aasland** [comment]
Thanks for the review, Ezio and Alex!

**Pull request merged**
