### PR TITLE
gh-84522: Add for-loop to apply-method-to-sequence FAQ

### LINKED ISSUE #84522: Programming FAQ about "How do I apply a method to a sequence of objects?" should include the option of an explicit for-loop
BPO | [40342](https://bugs.python.org/issue40342)
--- | :---
Nosy | @rhettinger, @mdickinson, @vedgar, @Dominik1123

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-20.21:06:38.162>
labels = ['type-feature', '3.8', '3.9', 'docs']
title = 'Programming FAQ about "How do I apply a method to a sequence of objects?" should include the option of an explicit for-loop'
updated_at = <Date 2020-04-22.07:11:11.110>
user = 'https://github.com/Dominik1123'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-22.07:11:11.110>
actor = 'veky'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-04-20.21:06:38.162>
creator = 'Dominik V.'
dependencies = []
files = []
hgrepos = []
issue_num = 40342
keywords = []
message_count = 6.0
messages = ['366880', '366885', '366901', '366979', '366980', '366982']
nosy_count = 5.0
nosy_names = ['rhettinger', 'mark.dickinson', 'docs@python', 'veky', 'Dominik V.']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40342'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

* PR: gh-94660

* PR: gh-99362

### PR DESCRIPTION
**Pull request by kj7rrv**
Closes gh-84522

Issue gh-84522

### CODE REVIEW

**Comment by arhadthedev** [comment]
@bedevere-bot No, small doc changes don't.

**Comment by rhettinger** [comment]
It would be better to leave this as talking about methods only.  Just add the for-loop example.

Changing the title of the entry risks breaking external links to the FAQ (for example, from code comments, blog posts, and answers on StackOverflow).

**Comment by kj7rrv** [comment]
@rhettinger is there a way to change the title without changing the link?

**Comment by kj7rrv** [comment]
The problematic code seems to be `Escape('\x1b[?25l\x1b[?7l')`

**Pull request merged**
