### PR TITLE
[3.12] gh-110525: Add CAPI tests for set and frozenset objects (GH-110526).

### PR DESCRIPTION
**Pull request by sobolevn**
(cherry picked from commit c49edd7d9c5395a6a6696a4846f56bc8b2b22792)

* Issue: gh-110525

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Good luck! It is not easy because some changes in C API tests structure (#93649)  were not backported to 3.11. Now there is a great barrier between 3.12 and 3.11.

**Comment by vstinner** [comment]
Yeah, we should try to backport these changes to 3.11.

**Comment by serhiy-storchaka** [comment]
Who is the Hercules to cherry-pick 107 commits?

**Comment by vstinner** [comment]
> Who is the Hercules to cherry-pick 107 commits?

I created PR #110835: Backport test_capi enhancements from Python 3.12 to Python 3.11.

**Pull request merged**
