### PR TITLE
gh-105736: Sync pure python version of OrderedDict with the C version

### PR DESCRIPTION
**Pull request by rhettinger**
This solves a problem noticed in the referenced issue.  When `__init__` is overridden, the C version is still usable but the pure Python version fails.   The solution is to have the internal invariants sets up in `__new__` rather than `__init__`.

The original copy/pickle issue still remains.

* Issue: gh-105736

### CODE REVIEW

**Comment by ambv** [comment]
I can confirm the new tests fail without the fix 👍🏻

One thing I'm trying to find is why we needed the `AttributeError` check for `self.__root` before. Since this is an double-underscore attribute, intuition tells me the only case when this can happen is unpickling. But when we provide `self.__class__` as an "empty object factory" in the result of `self.reduce`, that will call `__init__()` first before setting the state, so `self.__root` won't exist at pickling and unpickling time either. And in fact, I can reproduce that it isn't ever present in those times, for protocols 3 - 5. 

So I guess skipping the `try:except:` is harmless. But I wonder if I'm missing something.

**Comment by rhettinger** [comment]
> One thing I'm trying to find is why we needed the AttributeError check for self.__root before. 

The `__init__` method can be called more than once for an instance and it must add on to existing state rather than reset it from scratch.  Here's an example with both regular dictionaries and OrderedDicts:

```
>>> d = dict(a=1, b=2)
>>> d.__init__(b=3, c=4)
>>> d
{'a': 1, 'b': 3, 'c': 4}

>>> d = OrderedDict(a=1, b=2)
>>> d.__init__(b=3, c=4)
>>> d
OrderedDict({'a': 1, 'b': 3, 'c': 4})
```

In contrast, the `__new__` method can only be called once because it creates the actual instance.  Hence, the `try/except` is no longer needed — the attribute cannot already exist.

**Comment by ambv** [comment]
By whom can it be called multiple times? I mean, yes, theoretically you can explicitly grab `__init__()` from an existing instance and call it again but is this a pattern in actual use anywhere? I haven't seen this before.

(yes, I agree that `__new__()` can skip the `try:except:`.)

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. And the resulting code looks clearer.

Moving the code from `__init__` to `__new__` can break pickling, but OrderedDict uses full constructor instead of `__new__` in pickling, so it is safe from this side.

**Comment by serhiy-storchaka** [comment]
Side note. "gh-" in the title should be in lower case, and the issue number should be separated by a colon from the rest of the text. I think this is the reason why other Raymond's PRs were not automatically linked from the corresponding issue.

**Pull request merged**
