### PR TITLE
bpo-1635741: Enhance get_binascii_state()

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue1635741

### CODE REVIEW

**Review by corona10 — COMMENTED** [review]
Looks good to me.

**Comment by corona10** [comment]
Looks like _Pickle_GetState needs same change..

https://github.com/python/cpython/blob/dffe4c07095e0c693e094d3c140e85a68bd8128e/Modules/_pickle.c#L183

**Comment by shihai1991** [comment]
> Looks like _Pickle_GetState needs same change on sperate PR..
> https://github.com/python/cpython/blob/dffe4c07095e0c693e094d3c140e85a68bd8128e/Modules/_pickle.c#L183

I create this sperate change due to binascii extension module have been ported to `pep-489`.
IMO, other extension modules' `get_xxx_state()` can be done with porting operation.

**Comment by shihai1991** [comment]
cc @vstinner Hi, victor. It's a enhancement operation of binascii's `get_module_state()`

**Comment by vstinner** [comment]
I don't think that this change is worth it. In practice, I don't see why the state would be NULL. If it's the case, the code should crash anyway :-) Existing code which checks that the state is not NULL with an assertion is fine. But I don't think that this change is worth it.

**Comment by shihai1991** [comment]
got it, thanks, victor :)

**Pull request closed without merging**
