### PR TITLE
[3.9] bpo-43930: Update bundled pip to 21.1 and setuptools to 56.0.0

### PR DESCRIPTION
**Pull request by sbidoul**
Update bundled pip to 21.1 and setuptools to 56.0.0.

(cherry picked from commit 196983563d05e32d2dcf217e955a919f9e0c25e1)

https://bugs.python.org/issue43930

### CODE REVIEW

**Review by pradyunsg — COMMENTED** [review]
The pip wheel's py2.py3 needs to be updated to py3, I think?

**Review by pfmoore — APPROVED** [review]

**Comment by sbidoul** [comment]
Should I worry about the buildbot failure ? It seems unrelated but...

**Comment by pfmoore** [comment]
It looks unrelated, so I don't intend to worry about it 🤷

**Comment by pradyunsg** [comment]
> OSError: [Errno 24] Too many open files

Seems unrelated to me too!

**Pull request merged**
