### PR TITLE
gh-84805: Autogenerate signature for METH_NOARGS and METH_O extension functions

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* Issue: gh-84805

### CODE REVIEW

**Review by erlend-aasland — APPROVED** [review]
Nice feature!

**Comment by serhiy-storchaka** [comment]
@erlend-aasland, do you have any opinion about the name of the single positional parameter in METH_O functions? I use `object`, but maybe there are better ideas? It does not affect execution, it only affects the `help()` output.

**Comment by erlend-aasland** [comment]
> @erlend-aasland, do you have any opinion about the name of the single positional parameter in METH_O functions? I use `object`, but maybe there are better ideas? It does not affect execution, it only affects the `help()` output.

I thought about it while reviewing, and I think `object` is fine. In any way, it is better than the current `(...)`.

**Comment by ambv** [comment]
Closing and re-opening to retrigger CLA checks. Sorry for the noise.

**Pull request merged**
