### PR TITLE
bpo-38780: Avoid errors in SyslogHandler when socket is not set up.

### PR DESCRIPTION
**Pull request by jaraco**
https://bugs.python.org/issue38780

### CODE REVIEW

**Comment by vsajip** [comment]
Why is it better to have a `NullSocket` rather than `None`? It seems like `None` would catch more error cases than a `NullSocket` which accepts an erroneously made method call which then just does nothing.

**Comment by jaraco** [comment]
> Why is it better to have a `NullSocket` rather than `None`? It seems like `None` would catch more error cases than a `NullSocket` which accepts an erroneously made method call which then just does nothing.

I guess my thinking was that because the `None` required an `if None` around each invocation of it, it would be better to embed that Noneness into the underlying object.  The point of the PR is to suppress errors when the handler is not fully configured. I was tempted for the `NullSocket` to be even less fitting to the implementation, and using something like a MagicMock or an object that accepts any interface with a trivial response, but ultimately settled on this narrow fit to cover the known needed cases.

**Comment by jaraco** [comment]
After some analysis and attempting to write tests, I determined that [this approach is inadequate](https://bugs.python.org/issue38780?@ok_message=issue%2038780%20stage%20edited%20ok&@template=item#msg384128), so I'm closing this PR, although I'll leave the branch and test branch around.

**Comment by jaraco** [comment]
I've moved the branch to `/refs/archive/bugfix/bpo-38780` in jaraco/cpython.

**Pull request closed without merging**
