### PR TITLE
bpo-32015: Asyncio looping during simultaneously socket read/write an…

### PR DESCRIPTION
**Pull request by andr-04**
https://bugs.python.org/issue32015

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by 1st1** [comment]
Looks good to me, but we need a unit test. A functional one, ideally.

**Review by asvetlov — CHANGES_REQUESTED** [review]
I like to stress @1st1 note: a new test is required.

Otherwise we could break the proposed feature easy by future refactoring at least.

**Comment by andr-04** [comment]
I have made the requested changes; please review again

**Review by asvetlov — APPROVED** [review]

**Comment by andr-04** [comment]
@asvetlov, What about [Python 3.5](https://github.com/python/cpython/blob/3.5/Lib/asyncio/selector_events.py#L378)?

**Comment by asvetlov** [comment]
Python 3.5 is in security mode, the current policy for bugfix backporting is applied to 3.6 only.

**Comment by 1st1** [comment]
I actually asked for a functional test, not a mocked one. @andr-04 can you add one in a separate PR?

**Comment by andr-04** [comment]
I'll try. The reproducing script is [there](https://bugs.python.org/file47262/raise.py) if you are interested in.

**Pull request merged**
