### PR TITLE
gh-103053: Run tools test_freeze on buildbot

### PR DESCRIPTION
**Pull request by vstinner**
No longer skip test_tools.test_freeze on buildbots.

* Issue: gh-103053

### CODE REVIEW

**Comment by vstinner** [comment]
I fixed test_freeze on FreeBSD in PR #110451.

**Comment by vstinner** [comment]
> buildbot/ARM Raspbian PR — Build done.

test_tools failed with with a 40 min timeout and a system load of 6.28.

```
0:42:03 load avg: 6.28 [260/467/1] test_tools worker non-zero exit code (Exit code 1) -- running (2): test_zipfile (2 min 43 sec), test.test_concurrent_futures.test_deadlock (8 min 23 sec)
test_freeze_simple_script (test.test_tools.test_freeze.TestFreeze.test_freeze_simple_script) ... Timeout (0:40:00)!
Thread 0xf7ded040 (most recent call first):
  File "/var/lib/buildbot/workers/pull_request.gps-raspbian.nondebug/build/Lib/selectors.py", line 398 in select
  File "/var/lib/buildbot/workers/pull_request.gps-raspbian.nondebug/build/Lib/subprocess.py", line 2108 in _communicate
  File "/var/lib/buildbot/workers/pull_request.gps-raspbian.nondebug/build/Lib/subprocess.py", line 1209 in communicate
  File "/var/lib/buildbot/workers/pull_request.gps-raspbian.nondebug/build/Lib/subprocess.py", line 550 in run
  File "/var/lib/buildbot/workers/pull_request.gps-raspbian.nondebug/build/Tools/freeze/test/freeze.py", line 35 in _run_quiet
  File "/var/lib/buildbot/workers/pull_request.gps-raspbian.nondebug/build/Tools/freeze/test/freeze.py", line 170 in freeze
  File "/var/lib/buildbot/workers/pull_request.gps-raspbian.nondebug/build/Lib/test/test_tools/test_freeze.py", line 32 in test_freeze_simple_script
```

The test pass when re-run, but it took **36 min**!

```
1:48:58 load avg: 3.00 running (1): test_tools (35 min 18 sec)
1:49:28 load avg: 3.55 running (1): test_tools (35 min 48 sec)
1:49:45 load avg: 3.26 [2/2] test_tools passed (36 min 4 sec)
Re-running test_tools in verbose mode
(...)
Ran 36 tests in 2163.293s
```

build: https://buildbot.python.org/all/#/builders/1062/builds/415

**Comment by vstinner** [comment]
s390x Fedora Clang PR failed with ``FAIL: test_pipesize_default (test.test_subprocess.ProcessTestCaseNoPoll.test_pipesize_default)``: unrelated issue gh-110184.

**Comment by vstinner** [comment]
@gpshead: Apparently, test_tools only fails on your ARM Raspbian PR buildbot. I see different options:

* Disable ``cpu`` resources on this buildbot to skip slowest tests like `test_tools`
* Increaes timeout from 40 min to 1 hour or even more
* Another option to only skip test_tools on this buildbot

What do you prefer? I prefer to disable the `cpu` resources. I would prefer a fast CI quick runs most tests, than a slow CI which fail time to time with timeout.

**Comment by vstinner** [comment]
I'm not sure that it's really worth it to run test_freeze on more CIs. The test is slow and I don't really understand why this tool is maintained in Python itself (which is not even installed by `make install`). Well, I just close my PR.

**Comment by gpshead** [comment]
https://github.com/python/buildmaster-config/pull/441 to add `-u-cpu` for whomever can approve it.

the bot will become 3x faster whenever I can get my hand on a shiny new RaspberryPi 5.

**Pull request closed without merging**
