### PR TITLE
[3.7] [3.8] Update interpreter.rst (GH-17059) (GH-17060)

### PR DESCRIPTION
**Pull request by Seluj78**
Fixed what seemed to be a weird phrasing.

(cherry picked from commit 5e01a6542a1beb552a17e16b71dc0ba9fc6adcfb)

Co-authored-by: Jules Lasne (jlasne) <jules.lasne@gmail.com>.
(cherry picked from commit 1eac437e8da106a626efffe9fce1cb47dbf5be35)

Co-authored-by: Jules Lasne (jlasne) <jules.lasne@gmail.com>

Automerge-Triggered-By: @vstinner

### CODE REVIEW

**Comment by Seluj78** [comment]
ping @vstinner

**Comment by Seluj78** [comment]
Also ping @Mariatta, is seems like Miss Illington isn't coping really well with one word changes in the doc :/

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
> Also ping @Mariatta, is seems like Miss Illington isn't coping really well with one word changes in the doc :/

It's better to report issues to https://github.com/python/miss-islington/issues rather than ping only Mariatta ;-)

**Pull request merged**
