### PR TITLE
[backport to 3.6] bpo-29529: Add .travis.yml to 3.6 branch

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Comment by berkerpeksag** [comment]
I think the plan is to make sure everything works fine on master first and then backport `.travis.yml` to maintenance branches.

**Comment by methane** [comment]
I'm sorry.  What remains?

**Comment by methane** [comment]
Should I close this PR for now?

**Comment by berkerpeksag** [comment]
No need to close, but I'd wait for a couple days before merging these backports. See also http://bugs.python.org/issue29529.

**Comment by brettcannon** [comment]
So @berkerpeksag is right that I didn't backport any of this on purpose because I knew things like python/core-workflow#19 would come up when people more experienced than me in Travis usage would make suggestions. (I was also waiting for the IRC encryption stuff to land but I believe 4538ddcacc8e8f00d5d36d7bc84e551a56ce6da2 covers that specific issue.)

**Comment by brettcannon** [comment]
GH-74 has proposed changes to `.travis.yml`.

**Comment by methane** [comment]
while GH-74 looks nice, I feel inconvenience for lack of travis check for 3.6 branch...

**Comment by berkerpeksag** [comment]
#74 has been merged. Please give me a couple days so I can make sure that I didn't cause any regression in our Travis configuration.

**Comment by methane** [comment]
I did cherry pick changes in master.
Feel free to push merge button when you feels good.

**Comment by berkerpeksag** [comment]
Here's another one to be cherry-picked @methane :) https://github.com/python/cpython/commit/c33ee85b6fbed7f9c68e9fd39cd0582af9237ef1

**Comment by jaouich** [comment]
!!!!

**Review by ncoghlan — APPROVED** [review]

**Comment by ncoghlan** [comment]
Going ahead and merging this so we actually get CI on the maintenance branches :)

**Pull request merged**
