### PR TITLE
gh-91578: error message updated for abstract class

### PR DESCRIPTION
**Pull request by ravi140222**

### CODE REVIEW

**Comment by ravi140222** [comment]
done

**Comment by vainaijr** [comment]
did I do the entry correctly, is there something else to be done?

**Review by rhettinger — APPROVED** [review]

**Comment by vainaixr** [comment]
it gives some assertion errors.
Will have to make the same change for them also.
Will do it in a couple of days.

**Comment by ravi140222** [comment]
hopefully it passes this time.

**Review by ericvsmith — APPROVED** [review]

**Pull request merged**
