### PR TITLE
Unmark files as executable that can't actually be executed.

### PR DESCRIPTION
**Pull request by gnprice**
There are plenty of legitimate scripts in the tree that begin with a
`#!`, but also a few that seem to be marked executable by mistake.

Found them with this command -- it gets executable files known to Git,
filters to the ones that don't start with a `#!`, and then unmarks
them as executable:

    $ git ls-files --stage \
      | perl -lane 'print $F[3] if (!/^100644/)' \
      | while read f; do
          head -c2 "$f" | grep -qxF '#!' \
          || chmod a-x "$f"; \
        done

Looking at the list by hand confirms that we didn't sweep up any
files that should have the executable bit after all.  In particular

 * The `.psd` files are images from Photoshop.

 * The `.bat` files sure look like things that can be run.
   But we have lots of other `.bat` files, and they don't have
   this bit set, so it must not be needed for them.

Automerge-Triggered-By: @benjaminp

### CODE REVIEW

**Comment by gnprice** [comment]
@benjaminp ^ -- I noticed this after your d33e46d17 fixed another such file.

**Review by benjaminp — APPROVED** [review]

**Comment by gnprice** [comment]
@benjaminp Thanks! Just sent the converse too, as #15354 .

**Comment by terryjreedy** [comment]
On Windows, a file is 'executable' if is has the right registry entries for the extension.  I don't think that Windows pays any more attention to the execute bit that is does to #! lines.  So I don't care about it either way for idle.bat, and don't care whether you backport the change.

**Comment by gnprice** [comment]
@terryjreedy , thanks for that confirmation!

Meanwhile, this failed one of the test builds -- specifically "Ubuntu PR Tests" in [the Azure pipelines](https://dev.azure.com/Python/cpython/_build/results?buildId=48904&view=logs&j=256d7e09-002a-52d7-8661-29ee3960640e). Here's the log:
```
Starting: Install dependencies
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
sudo ./.azure-pipelines/posix-deps-apt.sh 1.1.1c
========================== Starting Command Output ===========================
in/bash --noprofile --norc /home/vsts/work/_temp/ba52b7c9-dcd5-438a-a36c-de38a96384aa.sh
sudo: ./.azure-pipelines/posix-deps-apt.sh: command not found
##[error]Bash exited with code '1'.
```

I... am puzzled that that's been working with no `#!` line. Easy to fix, though. To avoid confusion I'll add such a line, while also marking it executable again.

**Review by skrah — COMMENTED** [review]
Surely `runall.bat` is executable.  Please revert.

**Comment by gnprice** [comment]
> Surely `runall.bat` is executable.

Yes. As I mentioned in the commit message / PR description:

> * The `.bat` files sure look like things that can be run.
>   But we have lots of other `.bat` files, and they don't have
>   this bit set, so it must not be needed for them.

Specifically, these (after the change):
```
$ git ls-files --stage | perl -lane 'print "$F[0] $F[3]" if (/\.bat$/)'
100644 Doc/make.bat
100644 Lib/ctypes/macholib/fetch_macholib.bat
100644 Lib/idlelib/idle.bat
100644 Lib/venv/scripts/nt/activate.bat
100644 Lib/venv/scripts/nt/deactivate.bat
100644 Modules/_decimal/tests/runall.bat
100644 PC/bdist_wininst/build.bat
100644 PCbuild/build.bat
100644 PCbuild/build_env.bat
100644 PCbuild/clean.bat
100644 PCbuild/env.bat
100644 PCbuild/find_msbuild.bat
100644 PCbuild/find_python.bat
100644 PCbuild/get_externals.bat
100644 PCbuild/idle.bat
100644 PCbuild/prepare_libffi.bat
100644 PCbuild/prepare_ssl.bat
100644 PCbuild/prepare_tcltk.bat
100644 PCbuild/rt.bat
100644 Tools/buildbot/build.bat
100644 Tools/buildbot/buildmsi.bat
100644 Tools/buildbot/clean.bat
100644 Tools/buildbot/remoteDeploy.bat
100644 Tools/buildbot/remotePythonInfo.bat
100644 Tools/buildbot/test.bat
100644 Tools/msi/build.bat
100644 Tools/msi/buildrelease.bat
100644 Tools/msi/get_externals.bat
100644 Tools/msi/testrelease.bat
100644 Tools/msi/uploadrelease.bat
100644 Tools/nuget/build.bat
100644 Tools/unicode/genwincodecs.bat
```

Many if not most of those are intended to be directly executed too. Yet before this change just two of them had the executable bit set in Git -- on the rest, our practice has been to leave it unset. Terry explained above why the executable bit doesn't matter for batch files. On those two, this change just brought them in line with our practice on the rest.

If you'd like to change that practice, I think that would be best as a separate change -- adding the executable bit to all the batch files that are meant to be directly executed.

(Though I think the current practice is the cleaner one: given that it doesn't affect actually executing the files, setting it seems like it would just be misleading.)

**Comment by skrah** [comment]
"Our practice"?  I''m the author of `Modules/_decimal/*`, and *my* practice is to set the executable bit if there's a `.sh` file with an exact `.bat` counterpart.  :)

I'm developing on Linux and I want to see the same color in directory listings when two files are, Windows practices notwithstanding, meant to be executed directly and do the same thing..


> If you'd like to change that practice [...]

There doesn't need to be an overarching policy for that kind of unimportant matters.  You are the one trying to establish such a practice.

**Comment by gnprice** [comment]
Well, if you have a strong preference for the executable bit to be set on that file, then please go ahead and set it back. What to do with batch files in this respect isn't a thing I feel strongly about.

I'd encourage you if so to look at the other batch files in the tree (listed above) at the same time, and see if you think the same should apply to some of them.

I should perhaps clarify my meaning on this point, though:

> > If you'd like to change that practice [...]
> 
> There doesn't need to be an overarching policy for that kind of unimportant matters.

Policy != practice. Practice is just whatever is actually done; there is always a practice. In referring to "our practice on the rest" of the batch files, I'm not imagining any policy; I'm just summarizing the facts of what we actually do in the case of the other batch files.

Generally in a shared codebase I think it's helpful for practices to be consistent across the codebase. But, as you say, this one is just not that important. If you prefer a different practice which you don't care to try to apply to `PCbuild/` and `Tools/msi/` and the rest, then I don't expect anyone will care enough to object.

**Comment by skrah** [comment]
On Wed, Aug 21, 2019 at 02:05:43PM -0700, Greg Price wrote:
> Well, if you have a strong preference for the executable bit to be set on that file, then please go ahead and set it back. What to do with batch files in this respect isn't a thing I feel strongly about.
> 
> I'd encourage you if so to look at the other batch files in the tree (listed above) at the same time, and see if you think the same should apply to some of them.

Sigh, we have another manager.

**Comment by terryjreedy** [comment]
Greg, if you prepare a PR to revert that one file and request my review, I will merge in when CI passes.   Multi-owner patches usually sit around at least a few days, giving people time to object.  This one was handled, it appears, super efficiently, within a couple of hours.  You, Benjamin, and I all lacked the imagination to think of why someone might object, and that the merging should wait a couple of days.

idle.bat was added by David Scherer in 2000, and scarcely touched since.  I suspect David set it, but have no idea why.  A typical Windows developer would never notice that setting.

**Comment by skrah** [comment]
Thank you Terry, I've already reverted it in the meantime, so there's no need for further action.

**Comment by gnprice** [comment]
> [Terry] Multi-owner patches usually sit around at least a few days, giving people time to object. This one was handled, it appears, super efficiently, within a couple of hours. You, Benjamin, and I all lacked the imagination to think of why someone might object, and that the merging should wait a couple of days.

Thanks for that context. Yeah, I saw the "code owners" line up [at the top](https://github.com/python/cpython/pull/15353#event-2571690654) of the thread with a medium-long list of people, but don't yet have a firm sense of how that's interpreted in this project.

I will certainly take this thread as data to predict a greater probability of there being an objection I didn't have the imagination to think of, even on a patch as minor as this one. Benjamin has quite a lot more past data here than I do :slightly_smiling_face:, but perhaps his predictions will shift a bit too.


> [Stefan] I've already reverted it in the meantime, so there's no need for further action.

Cool, and thanks for leaving the rest of the patch in place. Glad we're all set.

(For convenient reference for anyone else reading the thread: it looks like that commit is bcc446f52 .)

**Comment by terryjreedy** [comment]
idlelib is another special directory in that nearly all PRs get backported unchanged to current 3.x versions (PEP 434).   Github's code owner mechanism sends me an email about any patch, like this one, touching it.   When people could patch it without me noticing, it was occasionally a nuisance.

**Pull request merged**
