### PR TITLE
bpo-44864: Do not translate user-provided strings in `ArgumentParser.add_subparsers()`

### PR DESCRIPTION
**Pull request by jdetrey**
Call `_()` on `argparse`-provided strings only.

https://bugs.python.org/issue44864

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@jdetrey

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by MaxwellDupre — APPROVED** [review]
Ran 1670 tests in 8.544s
OK
Looks ok.

**Review by iritkatriel — CHANGES_REQUESTED** [review]
This is a behaviour change and, as such, requires a unit test to cover it.

If there are no tests for translations in argparse, those should be added and possibly we need to go over what does and what doesn't need to be translated. 

CC @terryjreedy

**Comment by encukou** [comment]
I agree that this needs tests -- at least very specific ones for the changed cases.

The change itself is correct: argparse-provided strings should be translated, user-provided ones should not. The translation function (`_`) should only be used on string literals.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

There are no currently any tests for gettext in argparse, and adding them requires a lot of effort. I do not think that this should be a blocker for this bugfix. You can open a new issue for adding tests for gettext in argparse.

**Comment by serhiy-storchaka** [comment]
@iritkatriel, @encukou, are you fine with merging this PR without tests and creating a separate issue for adding tests for argparse+gettext?

**Comment by iritkatriel** [comment]
Sure.

**Comment by serhiy-storchaka** [comment]
Opened #124432.

**Comment by serhiy-storchaka** [comment]
BTW, `Tools/i18n/pygettext.py` fails with the current code and passes with the fixed one.

**Pull request merged**
