### PR TITLE
bpo-47250: Fix refleak from object.__getstate__()

### PR DESCRIPTION
**Pull request by corona10**
Co-authored-by: Brandt Bucher <brandt@python.org>

https://bugs.python.org/issue47250

### CODE REVIEW

**Comment by corona10** [comment]
`````

➜  cpython git:(bpo-47250) ✗ ./python.exe -m test -R 3:3 test_descr -m test_issue24097
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 4.63 Run tests sequentially
0:00:00 load avg: 4.63 [1/1] test_descr
beginning 6 repetitions
123456
......

== Tests result: SUCCESS ==

1 test OK.

Total duration: 107 ms
Tests result: SUCCESS
`````

**Review by brandtbucher — APPROVED** [review]
Thanks. Do you wanna feed it to the buildbots, just in case?

**Comment by corona10** [comment]
> Thanks. Do you wanna feed it to the buildbots, just in case?

Yeah, let's run the bots

**Review by vstinner — APPROVED** [review]
LGTM.

**Pull request merged**
