### PR TITLE
gh-99087: Add missing newline for prompts in docs

### PR DESCRIPTION
**Pull request by slateny**
https://github.com/python/cpython/issues/99087

* Issue: gh-99087

### CODE REVIEW

**Comment by erlend-aasland** [comment]
This is against the recommendations by the dev guide: https://devguide.python.org/documentation/style-guide/#code-examples

Suggesting to close this PR.

**Comment by slateny** [comment]
I would argue that it does aid copy-pasting: for example, in the [enum howto](https://docs.python.org/dev/library/enum.html), we have this:
image

which (when the `>>>` is clicked on the top-right of the code box) corresponds to the prompt
```
class Perm(IntFlag):
    R = 4
    W = 2
    X = 1
    RWX = 7
Perm.RWX

~Perm.RWX

Perm(7)

```

but this causes a error when pasted:
```
>>> class Perm(IntFlag):
...     R = 4
...     W = 2
...     X = 1
...     RWX = 7
... Perm.RWX
  File "<stdin>", line 6
    Perm.RWX
    ^^^^
SyntaxError: invalid syntax
```

This happens if the previous line is a part of something function, class, etc. when there's indentation, so the new line's needed to clear it out. I should have also put my justification in the description instead of leaving it empty - my bad on that.

**Comment by erlend-aasland** [comment]
> I should have also put my justification in the description instead of leaving it empty - my bad on that.

Yeah, either that, or creating an issue describing the problem. Perhaps an issue would have been appropriate here, since it is clearly not a trivial change.

**Comment by slateny** [comment]
> The problem here is that the edit looks gross and makes the examples slightly longer, noisier, and less readable without adding anything substantive.

Preventing errors from copy-pasting prompts, especially from howto pages, would quality as substantive to me, and since the edit is just extending the existing `...` it doesn't appear that much visually intrusive. However, if the consensus is that prompts are to be left as-is intentionally, then I have no problem with closing this PR and pointing future PRs with similar changes to this one for justification.

**Review by JelleZijlstra — APPROVED** [review]
I think this change is helpful, though I must admit I'd never even noticed the button to remove the prompts from code samples. I won't merge it though until there's consensus on the issue.

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
FTR; the sqlite3 change is no longer relevant.

**Review by ethanfurman — APPROVED** [review]

**Pull request merged**
