### PR TITLE
bpo-38605: bump the magic number for 'annotations' future

### PR DESCRIPTION
**Pull request by isidentical**
https://bugs.python.org/issue38605

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thank you @isidentical!

**Comment by isidentical** [comment]
Thanks for noticing this @serhiy-storchaka!

**Review by gvanrossum — APPROVED** [review]
LGTM

**Comment by isidentical** [comment]
@gvanrossum can you merge?

**Pull request merged**
