### PR TITLE
[3.4] bpo-34791: xml package obeys ignore env flags (GH-9544)

### PR DESCRIPTION
**Pull request by vstinner**
The xml.sax and xml.dom.domreg modules now obey
sys.flags.ignore_environment.

Signed-off-by: Christian Heimes <christian@python.org>

(cherry picked from commit 223e501fb9c2b6ae21b96054e20c4c31d94a5d96)

https://bugs.python.org/issue34791

### CODE REVIEW

**Comment by matrixise** [comment]
@vstinner LGTM

**Review by gpshead — APPROVED** [review]

**Comment by larryhastings** [comment]
Appveyor claims the build failed... but AFAICT everything was fine.  There are no reported build errors, and no test failures.  Did it simply time out?

**Comment by vstinner** [comment]
> Appveyor claims the build failed... but AFAICT everything was fine. There are no reported build errors, and no test failures. Did it simply time out?

I clicked on "Re-Build PR" to test again this PR. (@larryhastings you should get the button as well if you log in appveyor.com, it's connected to GitHub and so you get the permission from the Python group.)

The log ends with "[389/391] test_urllib2net" as if the job has been cancelled or stopped. The job says " Failed 5 minutes ago in 13 min 35 sec". Another recent successful job took 17 min.

Stop stressing AppVeyor, you make it grumpy :-(

**Comment by larryhastings** [comment]
I would send Appveyor chocolates and love letters if it would help!

**Comment by larryhastings** [comment]
Thanks for the backport!  3.4 salutes you, as it rides off into the sunset.

**Pull request merged**
