### PR TITLE
Fix link to bpo issue in Changelog

### PR DESCRIPTION
**Pull request by cs-shadow**
I think this is rather trivial so didn't create an issue for it. But, please let me know if I am missing something. Thanks!

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@cs-shadow

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by cs-shadow** [comment]
Sorry I missed the CLA before, I have signed it now.

**Review by tirkarthi — APPROVED** [review]
Thanks for the catch. LGTM.

**Review by aeros — COMMENTED** [review]
Thanks for the PR @cs-shadow and welcome!

LGTM. Based on the description of the change log entry and bpo issues, https://bugs.python.org/issue38688 is definitely the correct issue to link to rather than https://bugs.python.org/issue38668.

**Review by aeros — APPROVED** [review]

**Review by csabella — APPROVED** [review]
LGTM

@tirkarthi, I'll leave this for you to merge.  :-)

**Comment by tirkarthi** [comment]
Thanks @cs-shadow. Thanks @csabella , hope I followed the correct process with my first merge commit :)

**Pull request merged**
