### PR TITLE
gh-98948: Remove obsolete readelf dependency

### PR DESCRIPTION
**Pull request by serge-sans-paille**
This got introduced in commit 5884449539510313c826d69835829c7957c7154a to determine if readline is already linked against curses or tinfo in the setup.py, which is no longer present.

* Issue: gh-98948

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @vstinner , because I know he's in love with autoconf. I didn't run a local autoreconf because my local version is different from the one used to generate previous version. Instead, I manually edited the `configure` script, feel free to regenerate it on your side.

**Comment by vstinner** [comment]
Can you try to add a NEWS entry in the Build category to document your change? See https://devguide.python.org/ about blurb.

**Comment by vstinner** [comment]
I added a commit to your branch: I ran "make regen-configure" which uses a container to get always the same version.

**Comment by serge-sans-paille** [comment]
@vstinner : entry added & commits squashed. Thanks for the review!

**Comment by vstinner** [comment]
Merged, thanks!

**Pull request merged**
