### PR TITLE
Fix #19404: Change context managers to have appropriate docstrings

### PR DESCRIPTION
**Pull request by plokmijnuhby**
Changed functionality so that contextmanager and asyccontextmanager return classes rather than functions. The classes have appropriate docstrings and names. (This made one of the internal classes redundant, so I removed it.)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by 1st1 — COMMENTED** [review]
I'm really not sure about this one.  While I understand the idea and "why", I don't think that the increased complexity of the new code is worth it.

**Comment by ncoghlan** [comment]
Hi, thanks for this attempt, but as discussed on the tracker issue, I don't think changing the way contextlib works to cope with a limitation in pydoc is the right answer here - instead, we need to make pydoc smarter so that contextlib can tell it to return instance-specific documentation, and ignore the documentation for the type.

**Pull request closed without merging**
