### PR TITLE
bpo-39481: Make functools.cached_property, partial, ...

### PR DESCRIPTION
**Pull request by emmatyping**
... partialmethod, _lru_cache_wrapper generic.

I noticed that `_lru_cache_wrapper`'s Python implementation is a function, what should be done about that? I feel like it would be weird to have code that runs without the compiled functools to break on a subscripted lru_cache. Perhaps it should be a class instead?

https://bugs.python.org/issue39481

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
The conflicts are really annoying. I think we should merge these one at a time and then resolve conflicts in one following PR and land that before merging the next one. That will take a lot of time, because each time we must wait for the tests... :-(

**Comment by gvanrossum** [comment]
> I noticed that `_lru_cache_wrapper`'s Python implementation is a function, what should be done about that? I feel like it would be weird to have code that runs without the compiled functools to break on a subscripted lru_cache. Perhaps it should be a class instead?

Based on this I withdraw my approval. @rhettinger what do you think?

@ethanhs If you want to make progress, remove `_lru_cache_wrapper` from this PR?

**Review by gvanrossum — CHANGES_REQUESTED** [review]
`_lru_cache_wrapper` issue.

**Comment by rhettinger** [comment]
I suggest omitting the lru_cache() for now.

Also, it would be nice to have a few tests.

**Comment by ethanhs** [comment]
@rhettinger Okay, sounds good, I will remove the lru_cache change, that can be done in a follow up. As for tests, I added the modified types to the GenericAlias tests that check they are subscriptable here: https://github.com/python/cpython/pull/19427/files#diff-f3accc4cfc3724113e786a2ba3548f35R27

Did you have other tests in mind?

**Comment by ethanhs** [comment]
I have made the requested changes; please review again

**Review by gvanrossum — APPROVED** [review]
I think Raymond should be happy, so I'll merge now.

**Pull request merged**
