### PR TITLE
[3.12] gh-119311: Fix name mangling with PEP 695 generic classes (#119464)

### LINKED ISSUE #119311: Unexpected name mangling behavior with generics
# Bug report

### Bug description:

Name mangling behaves inconsistently when used with generics. Here’s the code to reproduce the issue:
```python
class __Foo(type):
    pass


class Bar[T](metaclass=__Foo):
    pass
```

This raises `NameError: name '_Bar__Foo' is not defined`. However, removing the `[T]` results in the error disappearing. This suggests that the name mangling behavior is inconsistent when generics are involved. This behavior seems to be a bug, as it would be expected for the name mangling to either always occur or never occur, regardless of whether generics are used.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-119464
* gh-119643
* gh-119644
* gh-125771

### LINKED ISSUE #119395: PEP 695: Name mangling leaks to surrounding scope
# Bug report

```
% cat leak.py 
def f():
    __foo = 1
    class X[T]: ...
    return __foo
f()
% python3.12 leak.py
Traceback (most recent call last):
  File "/Users/jelle/py/cpython/leak.py", line 5, in <module>
    f()
  File "/Users/jelle/py/cpython/leak.py", line 4, in f
    return __foo
           ^^^^^
NameError: name '_X__foo' is not defined. Did you mean: '__foo'?
```

The PEP 695 implementation of generic classes turns on name mangling for the type parameter scope, but never turns it off afterwards. As a result, all code that appears syntactically after the PEP 695 scope also gets mangling applied to it.

I have a fix for this, but I believe applying it requires updating the magic number, and I'm not sure we can afford to to do that on the 3.12 branch.

### Linked PRs
* gh-119399

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #119311. Fixes #119395.

(cherry picked from commit a9a74da4a0ca0645f049e67b6434a95e30592c32)

* Issue: gh-119311

### CODE REVIEW

**Review by carljm — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
"Check if the ABI has changed" is failing, this is what I was worried about. I'll try to think of a solution that doesn't involve new entries on the struct.

**Comment by carljm** [comment]
My recollection (admittedly vague) is that the ABI dumpy doesn't really try to distinguish internal ABI, so an ABI check failure isn't a definitive no-go, it just meshes means RM should take a look. 

If we are concerned that someone might be building with `Py_BUILD_CORE` and depending on offsets into internal symtable entry structs, an easy change that would eliminate that concern would be to move the new field to the end of the struct in the 3.12 version.

**Comment by JelleZijlstra** [comment]
@Yhg1s what do you think of merging this into 3.12? It fixes two bugs with name mangling around PEP 695 (#119311, #119395), but makes some changes to the internal C API to do so.

**Comment by Yhg1s** [comment]
Yes, I think it makes sense to backport this to 3.12. The ABI breakage doesn't matter because the structs aren't visible as Carl said, and the new function is fine because it's private _and_ not used by extension modules, just the core itself.

You do need to regen the ABI dump as part of the PR.

**Comment by JelleZijlstra** [comment]
I couldn't get the abi regen tool to run locally (I tried the instructions in https://devguide.python.org/getting-started/setup-building/#regenerate-the-abi-dump but got errors related to mpdecimal). But I was able to edit the dump file manually and the check succeeds now.

**Pull request merged**
