### PR TITLE
gh-101570: Update bundled pip version to 23.0

### PR DESCRIPTION
**Pull request by pradyunsg**
This updates the bundled wheel.

* Issue: gh-101570

### CODE REVIEW

**Comment by pradyunsg** [comment]
/cc @warsaw, as requested in https://discuss.python.org/t/announcement-pip-23-0-release/23342/9?u=pradyunsg

I haven't double-checked if this unblocks the imp removal -- given that https://github.com/pypa/pip/pull/11689 didn't get landed, I think it doesn't?

**Review by FFY00 — APPROVED** [review]

**Comment by FFY00** [comment]
I couldn't reproduce the fedora builbot failure locally via docker, so I triggered a rebuild.

**Comment by pradyunsg** [comment]
Indeed, it was flakiness! That’s for digging into that @FFY00!

**Comment by pradyunsg** [comment]
Actually, I goofed up -- I intended to be backporting #101997 instead.

**Pull request merged**
