### PR TITLE
bpo-46764: Fix wrapping bound method with @classmethod

### PR DESCRIPTION
**Pull request by msullivan**
Since #8405, @classmethod now has special case behavior to call its
argument's tp_descr_get if it exists. This breaks wrapping a bound
method with it, since bound method's have a do-nothing tp_descr_get.

Drop that do-nothing tp_descr_get.

https://bugs.python.org/issue46764

### CODE REVIEW

**Comment by msullivan** [comment]
Looking at the history, it looks like `method_descr_get` used to handle unbound methods. This became dead in python 3, and that logic was cleaned up in #12169, but I think it should basically be sound to just drop it.

(Of course, things that directly check for the presence of `__get__`, like classmethod, will be affected)

**Review by JelleZijlstra — APPROVED** [review]
@rhettinger do you still want to look at this? Would be good to get it in before the feature freeze (this Friday).

**Comment by rhettinger** [comment]
@JelleZijlstra I'm holding off on this one for a bit.  As a bug fix, it can be committed after the feature freeze.  The contending issue is that I'm working on deprecating the behavior — it is hard to use, it broke too many things, the fixed are making it worse, and since 3.10 we have a viable clean alternate path using ``__wrapped``.

**Comment by JelleZijlstra** [comment]
Right, the descriptor behavior of classmethod has been problematic (https://github.com/python/cpython/issues/89519#issuecomment-1093931550 for reference). I'll leave this to you.

**Review by rhettinger — APPROVED** [review]

**Pull request merged**
