### PR TITLE
[3.6] bpo-29615: SimpleXMLRPCDispatcher no longer chains KeyError (or any other exception) to exception(s) raised in the dispatched methods.

### PR DESCRIPTION
**Pull request by petr-motejlek**

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by petr-motejlek** [comment]
@serhiy-storchaka , I tried to add the proper cherry pick label myself, but could not find a place to do that. What am I missing, please? :)

**Comment by Mariatta** [comment]
@petr-motejlek only those with write permission can apply labels :)
Also this PR doesn't appear to be done via `git cherry-pick` command?

**Comment by petr-motejlek** [comment]
@Mariatta , cherry pick seemed to pick up some unrelated changes (from 3.7) and to get rid of them I had to manually edit some of the commits. So, I cleaned up the diff and squashed all changes into one simple commit

**Comment by serhiy-storchaka** [comment]
@Mariatta, I'm not well experienced with Git and GitHub. Is there something wrong with this PR?

**Comment by Mariatta** [comment]
@serhiy-storchaka I think it's fine :) You can merge it. Thanks.

**Review by Mariatta — APPROVED** [review]

**Comment by petr-motejlek** [comment]
Thanks, guys :)

**Comment by serhiy-storchaka** [comment]
Thanks @Mariatta.

**Pull request merged**
