### PR TITLE
[3.8] bpo-42822: Revert "[3.8] [doc] Fix erroneous backslashes in signatures and names (GH-23658)"

### PR DESCRIPTION
**Pull request by JulienPalard**
Reverts python/cpython#23828 due to https://github.com/python/python-docs-theme/issues/63

https://bugs.python.org/issue42822

### CODE REVIEW

**Comment by JulienPalard** [comment]
Hum no, a full revert is not needed, only some bits has to be reverted, let me check this in details.

**Comment by JulienPalard** [comment]
@andresdelfino Same here, I kept only backslashes involved in strings, so in one hand we keep the difference as small as possible between versions (easing backports), while keeping the doc right.

I hope I picked the right ones, I still did not took the time to build it locally to visually check every change (I'm at $DAYJOB lunch break ;p).

**Review by andresdelfino — APPROVED** [review]
LGTM

**Comment by andresdelfino** [comment]
@JulienPalard I compared your changes with the ones introduced and found all of the problematic ones fixed :)

**Pull request merged**
