### PR TITLE
Suggestion: Spaces before and after ---

### PR DESCRIPTION
**Pull request by Seluj78**

### CODE REVIEW

**Comment by Seluj78** [comment]
@ncoghlan you seem to be one of the last editors of that file, what are your thoughts ? Should I continue doing that for the whole file ? Is it not necessary ? 

When translating that file to French, one of our new translator left it like this but they need to be spaced out

**Comment by Seluj78** [comment]
@birkenfeld you seem to be the one who wrote those lines, 12 years ago 😱 What are your thoughts ?

**Comment by birkenfeld** [comment]
I'll show up as the original author of all docs files that are old enough, since I committed the conversion from TeX to rst/Sphinx. But most of the content is much older still :)

I'm neutral in whether this is a good idea; historically we have frowned upon such wholesale minor style changes.

**Comment by taleinat** [comment]
> I'm neutral in whether this is a good idea; historically we have frowned upon such wholesale minor style changes.

That's true. However, the [Helping with Documentation section in the Developer's Guide](https://devguide.python.org/docquality/) currently seems to support making such doc fixes and minor improvements. Selected quotes:

> Issues vary from typos to unclear documentation and items lacking documentation."

> Simple typos don’t require issues of their own, but, instead, submit a pull request directly.

**Comment by taleinat** [comment]
In this specific case, this change will be rejected for two reasons:

1. The em-dashes used here should indeed *not* be surrounded by spaces. The current form is correct!
2. These distutils docs are considered legacy, so to my understanding they should only be changed to address major issues.

**Pull request closed without merging**
