### PR TITLE
gh-89683: add tests for `deepcopy` on frozen dataclasses

### PR DESCRIPTION
**Pull request by picnixz**
Note that I did not change the existing behaviour. Should we, in the case the user defines their own slot, automatically add `__{get,set}state__` methods if they are not provided?

* Issue: gh-89683

### CODE REVIEW

**Review by ericvsmith — APPROVED** [review]

**Comment by picnixz** [comment]
Erf, backports failed. I'll take care of them now.

**Comment by ericvsmith** [comment]
@picnixz : Thanks!

**Comment by picnixz** [comment]
Backports are ready (I really hate making backports manually because `cherry_picker` tells me I'm outside a CPython  repository).

**Comment by ericvsmith** [comment]
You're better than me: I tried using `cherry_picker` and failed. Thanks for the backports.

**Pull request merged**
