### PR TITLE
gh-93726: addition of __match_args__ to Fraction

### PR DESCRIPTION
**Pull request by ravi140222**

### CODE REVIEW

**Comment by rhettinger** [comment]
From the *discuss* thread:

This seems like bug bait because fractions should compare with value equality instead of component equality — fractions get reduced when created:

 match Fraction(2, 6):
      case Fraction(2, 6):
             print('This can never match')
      case Fraction(1, 3):
             print('This would match instead')

**Comment by mdickinson** [comment]
> This seems like bug bait because fractions should compare with value equality instead of component equality — fractions get reduced when created:

I don't really see that as an issue; I'd expect it to be somewhat rare to deliberately express Fractions not in lowest terms.

**Comment by mdickinson** [comment]
As far as the PR content goes, it's a fine start, but it should have tests.

**Comment by brandtbucher** [comment]
I’m not sure if this is a good idea, for the same reason why we decided not to add `complex.__match_args__`.

As I see it, problem is that you can’t specify a minimum number of args, which can lead to unexpected behavior for those familiar with the one-argument form of the constructor. For example, `case Fraction(4)` would match `Fraction(4, 5)`, and `case Fraction(4.2)` would never match anything. `case Fraction(f)` would only ever capture an integer numerator. Are we okay with that, from a usability standpoint?

Note that early draft PEPs for pattern matching *did* include specification for a `__match_args_required__` attribute that could be set to `2` in the case of `Fraction` or `complex`, but we ended up dropping it to simplify the proposal (and because use-cases are relatively rare). Maybe it would be best to find enough cases like this and propose it as a new part of the protocol instead.

**Comment by brandtbucher** [comment]
At least in the case of `complex` though, the attribute names are short and sweet. `Fraction` is a bit trickier... the attribute names are longer, so using them in a pattern may often involve breaking it across several lines.

**Comment by rhettinger** [comment]
Are there any known use cases for this?  I haven't seen anyone matching like this with if-elif-else chains, so the motivation for this is almost zero.

>  I'd expect it to be somewhat rare to deliberately express Fractions not in lowest terms

With case logic, it would be a natural and easy mistake to make:

```
     match Fraction(n, 143):
        ...
        case Fraction(37, 143):
            print('possible match')
        case Fraction(38, 143):
            print('possible match')
       case Fraction(39, 143):
           print('this can never match')
       ...
```

Even just matching on either numerator or denominator is hazardous:  ``case Fraction(n, 6)`` or ``case Fraction(6, d)``.  Neither of these would pass a quality code review but could easily pass a cursory review.

We should reject this:

* No real, known valid use cases
* Antipattern to use match/case when ``match cls(a, b):`` won't always match ``case cls(a,b)`` where *a* and *b* are literals.
* If someone really needs the class pattern, they can explicitly write `` Fraction(denominator=6)`` or ``Fraction(numerator=6)`` which is clearer than ``Fraction(_, 6)`` or ``Fraction(6, _)``.
*  In general, we shouldn't provide short-cuts for writing bad code with surprising behavior.  Instead, we should focus on providing support for things that people are known to need and that are known to improve their code.

Side note:  We're already in an awkward position with floats and complex because exactly equality tests are usually an anti-pattern for the types:  ``match 1.1 + 2.2:  case 3.3: "never match" ``.  I'm currently working a wrapper so that we can support approximate matching with something like ``match almost_eq_wrapper(area / radius**2):   case math.pi: ...``.

**Comment by mdickinson** [comment]
> Are there any known use cases for this?

I'd use this for general destructuring with numeric input of unknown type: if/elif chains that are testing: "if it's an int, then do this, else if it's a float, do this, else if it's a Fraction with numerator n and denominator d, do this ...". So I'd expect it to be used with cases of the form `Fraction(n, d)` rather than of the form `Fraction(13, 143)`. So it wouldn't be any more than a convenience to save the manual `n, d = value.numerator, value.denominator` destructuring. But that sort of destructuring seems like exactly what the match statement should be good at.

I accept Brandt's argument that it's awkward because `Fraction` takes a variable number of arguments.

**Comment by rhettinger** [comment]
> So it wouldn't be any more than a convenience to save the manual n, d = value.numerator, value.denominator destructuring. But that sort of destructuring seems like exactly what the match statement should be good at.

If I was picking a faction apart, I would do it in the match-clause rather than the case-clause:

```
match f.as_integer_ratio():
     case (n, 2):  print(n, 'halves')
     case (n, 4):  print(n, 'fourths')
     case (n, 8): print(n, 'eigths')
     case (n, d): print(n, 'of', d)
```

> I accept Brandt's argument that it's awkward because Fraction takes a variable number of arguments.

Well, it's okay if we all dislike the proposition for different reasons — the outcome is the same.  Brandt also noted that use cases were rare (and I concur).  

For me, I object because the constructor transforms the inputs, possibly unexpectedly.  This would also be a problem for *Decimal()*.  Which case would match, ``Decimal(value=10)``, ``Decimal(value='10')``, or ``Decimal(value=10.0)`` (all of which are valid constructor inputs)?

**Comment by mdickinson** [comment]
> If I was picking a faction apart, I would do it in the match-clause rather than the case-clause:

I think you misunderstand. That's not my use-case: my use-case is getting a number of unknown type, and then matching by type. The `Fraction` is one of the cases inside the match statement; the other cases match types other than Fraction.

> if we all dislike the proposition for different reasons

I don't dislike the proposal: I like the proposal, but am sad that it can't be implemented because of the ambiguity that @brandtbucher points out. If we had a way to specify a minimum number of args, I think this would be a perfectly fine proposal.

**Comment by mdickinson** [comment]
Closing for the reasons discussed.

**Comment by mdickinson** [comment]
> This would also be a problem for _Decimal()_. Which case would match, `Decimal(value=10)`, `Decimal(value='10')`, or `Decimal(value=10.0)` (all of which are valid constructor inputs)?

If you consider this a problem (I don't), then isn't it already a problem with `int`, too?

```
>>> x = 10
>>> match x:
...     case int("10"):
...         print("Match!")
... 
>>> # no match
```

**Pull request closed without merging**
