### PR TITLE
Fix uninitialized struct member

### PR DESCRIPTION
**Pull request by rhettinger**

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
It is already initialized by `memset` in `PyType_GenericAlloc`.

**Comment by rhettinger** [comment]
I don't think we should rely on that.  It is a bug waiting to happen.  For reference, the similar code for function objects explicitly sets the dict to NULL.

**Comment by serhiy-storchaka** [comment]
But we rely on this in all other places. AFAIK, when you create an ordinary Python object, its `__dict__` is not initialized explicitly. The object is filled with zeros by `memset()`, and the dict is created on demand in `PyObject_GenericGetDict()`.

You can try to replace `memset(obj, '\0', size)` with `memset(obj, '\xab', size)` and see how hard the interpreter will fail.

I would rather remove redundant explicit initializations by zero.

**Comment by rhettinger** [comment]
You and I have profoundly different programming sensibilities.  Personally, I think what you're proposing is dangerous.  

The C code for the *lru_cache()* took a number of short-cuts that made the code difficult to verify. I found errors and still don't know if the code is completely correct.

This patch is part of what I need to be able to reason about the code without having to take into account actions at a distance.

I'm going to apply this patch because this isn't a question about whether it is correct.  This only question is whether explicitly initializing all the fields is a good idea.  For me, it improves my ability to reason about the code, and that is sufficient reason.

**Comment by vstinner** [comment]
Commit message " Fix uninitialized struct member" of commit bba760e9b6c7da3586ed9c8e3d5a0ce2909a97bb is wrong: as @serhiy-storchaka explained to you, `obj->dict` is already initialized to 0 by `PyType_GenericAlloc()`.

By the way, when Python is built in debug mode, the debug hooks on memory allocators initializes allocated memory with PYMEM_CLEANBYTE (`0xCD`). If PyType_GenericAlloc() would not initialize memory to zero, `obj->dict` would be inititialized to `0xCDCD...CD` pointer.

Hopefully, the commit was not backported to stable branches: it doesn't fix anything.


@rhettinger:
> I'm going to apply this patch because this isn't a question about whether it is correct. This only question is whether explicitly initializing all the fields is a good idea. For me, it improves my ability to reason about the code, and that is sufficient reason."

I concur that it's non obvious to understand that fields are initialized to 0 just by reading `lru_cache_new()`. But initialize `obj->dict` to 0 is inefficient and useless.

You could have add a comment to remind that the type allocator (`PyType_GenericAlloc()`) initializes all fields to 0 by default.

**Pull request merged**
