### PR TITLE
Check this please.

### PR DESCRIPTION
**Pull request by fochoao**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@fochoao

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by zware** [comment]
I'm not sure what your goal is here, but your approach is the wrong one. If you're trying to report a bug, open an issue on bugs.python.org. If you're trying to suggest a change, send an email to python-ideas@python.org. If you're looking for help, try python-list@python.org.

I notice that you've been banned from pyca for opening similarly un-useful PRs. The approach you seem to be taking is not the way to actually help anyone; PRs like this only waste people's time. Please do not open another pull request in this organization until you have gone through one of the channels I mentioned above, and have a small change with some agreement from others that such a change should be made.

**Comment by fochoao** [comment]
Cross compilation works on Windows x86-x64, macOS and Ubuntu, that was my goal.

**Comment by eamanu** [comment]
@fochoao I'm not sure about what do you want show, sorry, but maybe this can be interest for you https://buildbot.python.org/all/#/ if you're interest on python build for different platforms.

**Comment by fochoao** [comment]
Thanks for pointing me in the right direction!!

**Pull request closed without merging**
