### PR TITLE
[3.8] gh-80254: Disallow recursive usage of cursors in sqlite3 converters

### PR DESCRIPTION
**Pull request by erlend-aasland**
(cherry picked from commit c908dc5b4798c311981bd7e1f7d92fb623ee448b)

Co-authored-by: Sergey Fedoseev <fedoseev.sergey@gmail.com>
Co-authored-by: Jelle Zijlstra <jelle.zijlstra@gmail.com>

### CODE REVIEW

**Review by Tony-Frank-ML — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Buildbot comments (updating this post as they complete):

- AMD64 FreeBSD Shared PR: compile failures; seems unrelated to this PR
- ARM64 Windows PR: build tools missing; unrelated
- ARM64 Windows Non-Debug PR: build tools missing; unrelated

**Comment by JelleZijlstra** [comment]
The remaining failures (Gentoo, Fedora, Asan, Usan) are also on tests unrelated to SQLite. I don't have permissions to merge to this branch though.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by erlend-aasland** [comment]
FTR, the buildbot failures all seem unrelated. Some are failed builds (missing build tools), others are unrelated test failures.

**Comment by vstinner** [comment]
The 3.8 no longer accept bugfixes, only security fixes: https://devguide.python.org/#status-of-python-branches

Do you consider that this change fix a security issue?

**Comment by JelleZijlstra** [comment]
> The 3.8 branch no longer accept bugfixes, only security fixes: https://devguide.python.org/#status-of-python-branches
> 
> Do you consider that this change fix a security issue?

Yes, because it fixes a segfault. https://github.com/python/cpython/pull/29054#issuecomment-1117964876

**Comment by vstinner** [comment]
Ok, thanks.

**Pull request merged**
