### PR TITLE
bpo-n/a: Updated ccbench.py used to assess multithreading

### PR DESCRIPTION
**Pull request by Sophist-UK**
As used in https://github.com/faster-cpython/ideas/discussions/328.

Guido asked me to submit my changes as a PR so that the enhancements would be available to others.

Because this is not a PR on Python product code - but rather an update of an incidental performance measurement script - an issue number is not relevant.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Sophist-UK

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Sophist-UK** [comment]
I would have commented sooner had I known that this was about to happen. It would have been helpful if someone had commented in this PR that this was being considered so that I would have been notified and might have had a chance to comment before it happened.

I believe it was clear from the https://github.com/faster-cpython/ideas/discussions/328 that the ccbench script is still useful - because it clearly identifies an ongoing performance issue when multithreading with one or more CPU-heavy threads, and indeed it was @gvanrossum Guido himself who requested this PR.

That said, I do understand that performance scripts do not really have a place in the cpython source code repo, but unfortunately I do not have the time to rework the updated ccbench script for the pyperformance suite, so I guess it is going to just disappear.

**Comment by ericsnowcurrently** [comment]
@hugovk ^^^

**Comment by hugovk** [comment]
Thanks for the ping. Let's continue in the issue, I already replied to the identical comment there: https://github.com/python/cpython/issues/97680#issuecomment-1951363437

(And for completeness, there's also an identical comment at [d.p.o.](https://discuss.python.org/t/do-we-still-need-tools-io-cc-string-bench/22557/6))

**Pull request closed without merging**
