### PR TITLE
gh-113664: Improve style of Big O notation

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Use cursive to make it looking like mathematical formulas.

* Issue: gh-113664

----
📚 Documentation preview 📚: https://cpython-previews--113695.org.readthedocs.build/

### CODE REVIEW

**Review by hugovk — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Nice. Could we use the Sphinx `:math:` role for this?

**Comment by Rowlando13** [comment]
It was discussed in gh-11364. It looks like it was decided against because it is rendered in a different font.

**Comment by erlend-aasland** [comment]
@Rowlando13, thanks for the heads-up; I missed that discussion. I'm fine with the consensus of using italics for such notations[^1].

[^1]: though, I would personally prefer the `:math:` rendering

**Comment by serhiy-storchaka** [comment]
I tried also with :math: in  #113724.

**Comment by hugovk** [comment]
This PR with EPUB (in macOS Books):

image

image

image

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Digression: I don't think _O(highest file descriptor)_ and _O(number of file descriptors)_ is valid Big O notation. We can change that in a follow-up PR.

**Comment by encukou** [comment]
IMO, *O*(*highest file descriptor*) is fine. It would be more complicated if we did use `:math:`, where the term would need to be marked up as a single multi-letter variable (rather than a product of single-letter ones). But with simple italics, or `<var>` in HTML, you can get away with this.
Only change it if you can find a *clearer* way to express it. After all, math notation is all about being clear (to people used to reading math papers).

**Comment by hugovk** [comment]
I've created https://github.com/python/devguide/pull/1261 to document this style in the devguide.

**Pull request merged**
