### PR TITLE
bpo-44490: Add 'Whats New' docs regarding types.Union changes

### PR DESCRIPTION
**Pull request by uriyyo**
https://bugs.python.org/issue44490

### CODE REVIEW

**Comment by uriyyo** [comment]
@Fidget-Spinner Could you please review `What's new`? I believe you can improve what I wrote)

And also, could you please add `skip-news` label?

**Comment by Fidget-Spinner** [comment]
I'm really sorry, but Serhiy may be backporting this change to 3.10. In which case we won't need to add a ``whats new`` for 3.11.

If his backport lands, please add your name to the whats new in 3.10 https://docs.python.org/3.10/whatsnew/3.10.html#pep-604-new-type-union-operator. (the part mentioning Maggie and Phillipe). I think you've done enough for it :).

**Comment by uriyyo** [comment]
Okay, thats makes sense. Let's wait for Serhiy changes.

**Comment by Fidget-Spinner** [comment]
Ok, Serhiy has landed his 3.10 backports so we don't need the what's new in 3.11 anymore. Please credit him and yourself in the 3.10 whats new. Maybe ``(Contributed by Maggie Moss and Philippe Prados in :issue:`41428`, with additions by Yurii Karabas and Serhiy Storchaka in :issue:`44490`.)``?

**Review by Fidget-Spinner — APPROVED** [review]

**Pull request merged**
