### PR TITLE
Update What's New in Python 3.9

### PR DESCRIPTION
**Pull request by vstinner**
* Mention bpo of PyImport_Cleanup removal
* Fix bpo number of PyByteArray_Init removal

### CODE REVIEW

**Comment by vstinner** [comment]
My previous attempt which the wrong bpo number: PR #14239.

This change should be backported manually to 3.8 to backport PR #14239.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks!

**Comment by vstinner** [comment]
Come on @miss-islington, you can do it!

**Comment by vstinner** [comment]
@miss-islington: I believe in you.

**Comment by Mariatta** [comment]
I'm looking into this.

**Comment by vstinner** [comment]
Oh. The backport creates a conflict: the change modify Doc/whatsnew/3.9.rst which doesn't exist in 3.8. I will do the backport manually.

**Comment by vstinner** [comment]
I created PR #14294 backport to 3.8.

**Pull request merged**
