### PR TITLE
Remove commented out code

### PR DESCRIPTION
**Pull request by bradengroom**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by davidak — APPROVED** [review]

**Comment by matrixise** [comment]
Thank you for your contribution but we can close this PR because the commented code has already been removed with 02277482ea765335e497ecd9661d4bde9b5ddc67. I am really sorry but thank you again for your contrib.

**Comment by matrixise** [comment]
@zooba or @pablogsal 

You can close this PR, unfortunately for @bradengroom @pablogsal has already removed the commented code.

**Comment by pablogsal** [comment]
@bradengroom Thank your very much for the PR. Apparently, I removed this commented code while I was fixing another issue. Sorry about that!

**Pull request closed without merging**
