### PR TITLE
Docs: replace 'currying' by 'partial function'.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
Currying is not mentioned in the text so the reference is a little pointless.

> Currying is related to, but not the same as, partial application.

From https://en.wikipedia.org/wiki/Currying.

It is better to replace this with link to https://en.wikipedia.org/wiki/Partial_application as that is used in https://docs.python.org/3.8/howto/functional.html#the-functools-module

### CODE REVIEW

**Review by rhettinger — CHANGES_REQUESTED** [review]
Instead of replacing the current entry, just add a new entry.  The concept of "currying" is in the realm of functional programming and is more well known than partial function application. There is some value in mentioning both. 

Also, the distinction between them can be viewed as "splitting hairs".

**Comment by clemens-tolboom** [comment]
New commit follows @rhettinger review: keeping both.

FWIW the docs is not mentioning curry-ing anywhere so that was my reason to replace it.

```
grep curry -i Doc/howto/functional.rst | wc -l
       1
```
which is the link to wikipedia :-O

**Review by rhettinger — CHANGES_REQUESTED** [review]
Please leave the current entry as-is and add a new entry for partial function application.

Even if the word isn't used elsewhere in the docs, having the word "curry" present will give search engines a target.

**Comment by clemens-tolboom** [comment]
I forgot to push before/after comment of may 11 :-/ https://github.com/python/cpython/pull/91814#issuecomment-1123622424

**Pull request merged**
