### PR TITLE
bpo-34366: fix FreeBSD with both system lib and libuuid present

### PR DESCRIPTION
**Pull request by mgorny**
It is entirely possible for a FreeBSD (or another) system to have both
system uuid.h + -lc and external uuid/uuid.h + -luuid libraries
installed simultaneously.  If that is the case, prefer the system
library (to avoid unnecessary dependencies) and make sure that the code
does not attempt to combine both.

https://bugs.python.org/issue34366

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
`setup.py` no longer used in CPython since 3.12. Could you please update your PR @mgorny?

It is an old issue, how was it solved in existing distributions? Or your configuration is too uncommon? Do we need to backport this change or only change the main branch?

**Comment by mgorny** [comment]
To be honest, I don't remember if it affects regular FreeBSD (which I haven't used for quite a while already) or if it was specific to Gentoo/FreeBSD (discontinued in ~2019). In either case, I don't really have an environment handy and I don't really have the energy to set one up to check if it is still useful.

**Comment by serhiy-storchaka** [comment]
Then I am closing this PR. In any case thank you for it.

**Comment by serhiy-storchaka** [comment]
On other hand, there is a similar issue #85077 with alternative solution #20693.

**Pull request closed without merging**
