### PR TITLE
bpo-40077: Fix potential refleaks of _json

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue40077

### CODE REVIEW

**Comment by shihai1991** [comment]
@corona10 `self.memo` of `PyScannerObject` should be traversed too, right?

**Comment by shihai1991** [comment]
@corona10 `self.memo` of `PyScannerObject` should be traversed too, right?

**Comment by vstinner** [comment]
@pablogsal: Oh, that's an intersting bug. I consider that it should be backported to 3.7 and 3.8.

**Review by vstinner — APPROVED** [review]
LGTM.

@pablogsal: Do you think that a NEWS entry is required for such fix?

**Review by corona10 — APPROVED** [review]
> self.memo of PyScannerObject should be traversed too, right?

Nice catch it should be LGTM

**Comment by vstinner** [comment]
@shihai1991: @miss-islington failed to backport automatically the change, there is merge conflict. You can please backport the fix 3.7 and 3.8? You can use cherry_picker or `git cherry-pick -x b709302f3125622986bd458dfb2954fda5e8366d`. Tell me if you need help for the backport.

**Pull request merged**
