### PR TITLE
bpo-36891: Enhancement in site.py

### PR DESCRIPTION
**Pull request by vx1920**
Following Anaconda problem is addressed here: "python.exe -m conda update --all" gives error somewhere in SSL communication code. Real problem is that no proper PATH to folder with some DLLs and Anaconda does not provide it without calling to Home\Scripts\activate.bat. It would be better when Anaconda provides it automatically and end-user (like me) just start python.exe using full path to python.exe without any changes in system PATH and other environment variables.  

Proposed modification in site.py allows "sitevendor" customization plugin in addition to "sitecustomize" and "usercustomuze". More info displayed when "python.exe -m site" typed from command line.

I propose Anaconda to be shipped with proper startup/init code in PythonHome\sitevendor.py instead of using PythonHome\Scripts\activate.bat.  Old sitecustomize and usercustomize plugins continue to work as before (if already used by end-user).
New "sitevendor.py" can be placed near python.exe and contain something sitevendor.txt file attached. I am going to discuss adding this "sitevendor.py" with Anaconda developers, but Lib\site.py changes going to be taken from your CPython\Lib\site.py  (as I assume) 

[sitevendor.txt](https://github.com/python/cpython/files/3169197/sitevendor.txt)

https://bugs.python.org/issue36891

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by csabella** [comment]
This isn't a trivial issue, so please open an issue on bugs.python.org and include the bpo issue number in the title of this pull request.  Thanks!

**Comment by vx1920** [comment]
_csabella wrote: add new issue in bugs.python.org_

I am not talking about bugs in Python/Lib/Site.py. I propose relatively simple enhancement of it:
modification in site.py allows "sitevendor" customization plugin in addition to existed "sitecustomize" and "usercustomuze". More info displayed when "python.exe -m site" typed from command line.

Should it go into 'bugs' or should it go to another place ?

**Comment by csabella** [comment]
Other changes to `site.py` in the past have originated with an issue on the bug tracker.  If you take a look at the git history for this file, the commits all start with `bpo-xxxxx`.  You'll also need a bug tracker account to sign the CLA.

**Comment by vx1920** [comment]
BPO-36891  enhancement issue created in bugs.python.org by vx1920

**Comment by csabella** [comment]
Please take a look at the failing CI tests.  `test_site` is failing on all the builds.

**Comment by vx1920** [comment]
This is my first contribution attempt and I did miss something.
I did modify site.py and now it produces more useful info in output when requested.
Mentioned "test_site" may may request above info and compare output with some "master".
It looks like in addition to changes in site.py I have to update above "master".
How can I install above "test_site" automated test in my PC and run it ?
Where do we have repository for above "tests" and "masters" ?
Was it OK that new output is more detailed and more "human readable" ? 

Original and modified info output presented below (for my PC), "py" in CMD.EXE command line means full path to python.exe, it is simple py.bat, available on request.

************************  ORIGINAL *******************************
d:\my>py -m site_ORIG
Run: d:\InstSoft\Python\Conda3x64\Python.exe
Arg: -m site_ORIG
sys.path = [
    'd:\\my',
    'd:\\InstSoft\\Python\\Conda3x64\\python37.zip',
    'd:\\InstSoft\\Python\\Conda3x64\\DLLs',
    'd:\\InstSoft\\Python\\Conda3x64\\lib',
    'd:\\InstSoft\\Python\\Conda3x64',
    'd:\\InstSoft\\Python\\Conda3x64\\lib\\site-packages',
    'd:\\InstSoft\\Python\\Conda3x64\\lib\\site-packages\\win32',
    'd:\\InstSoft\\Python\\Conda3x64\\lib\\site-packages\\win32\\lib',
    'd:\\InstSoft\\Python\\Conda3x64\\lib\\site-packages\\Pythonwin',
]
USER_BASE: 'C:\\Users\\myname\\AppData\\Roaming\\Python' (doesn't exist)
USER_SITE: 'C:\\Users\\myname\\AppData\\Roaming\\Python\\Python37\\site-packages' (doesn't exist)
ENABLE_USER_SITE: True




****************** MODIFIED **************************
d:\my>py -m site
Run: d:\InstSoft\Python\Conda3x64\Python.exe
Arg: -m site
sys.path = [
  d:\my
  d:\InstSoft\Python\Conda3x64\python37.zip
  d:\InstSoft\Python\Conda3x64\DLLs
  d:\InstSoft\Python\Conda3x64\lib
  d:\InstSoft\Python\Conda3x64
  d:\InstSoft\Python\Conda3x64\lib\site-packages
  d:\InstSoft\Python\Conda3x64\lib\site-packages\win32
  d:\InstSoft\Python\Conda3x64\lib\site-packages\win32\lib
  d:\InstSoft\Python\Conda3x64\lib\site-packages\Pythonwin
]
env[PATH] = [
  C:\Windows\system32
  C:\Windows
  C:\Windows\System32\Wbem
  C:\Windows\System32\WindowsPowerShell\v1.0\
  c:\Progs\Bin
  C:\Program Files\dotnet
]
USER_BASE: 'C:\\Users\\myname\\AppData\\Roaming\\Python' (doesn't exist)
USER_SITE: 'C:\\Users\\myname\\AppData\\Roaming\\Python\\Python37\\site-packages' (doesn't exist)
ENABLE_USER_SITE: True
sitevendor ON: d:\InstSoft\Python\Conda3x64\sitevendor.py
sitecustomize OFF
usercustomize OFF
d:\my>

**Comment by vx1920** [comment]
More details:
I did use Anaconda installation, there was no test_site there
I did install Python and I am looking there

**Comment by csabella** [comment]
@vx1920, please read the Quick Reference section of the [devguide](https://devguide.python.org/) and the README for the repository for information on running the test suite.  Also, please respond to the questions on the bug issue that you opened on the bug tracker.

**Comment by vx1920** [comment]
Fixed problem with test_site automated test: test detect that 'types' was loaded
Reason was in 'import importlib' has such side effect. I did change code to use __import__() function instead of using importlib.import_module()

**Comment by msarahan** [comment]
For perpsective, see https://github.com/ContinuumIO/anaconda-issues/issues/3292

From Anaconda's point of view, this is not the right way to do things.  Anything that modifies PATH such that the Python interpreter's notion of PATH differs from the actual system value of PATH is likely to cause problems.

There are two better ways to solve this:

1. change DLL search paths at a lower level.  We patch python on Windows to achieve this.  This is described in the issue above.  @vx1920 seems to not like this because it requires setting an environment variable to activate this functionality.
2. Use DLL stubs and delayed loading such that we have more control over which DLLs get loaded.  This takes a lot more effort, but should be viable.  We are working on this, but it will take time.  We have no estimated timeline.

Even if CPython includes this change, Anaconda will probably not use it.

**Comment by vx1920** [comment]
_msarahan wrote: @vx1920 seems to not like this because it requires setting an environment variable to activate this functionality._

All what I like is: I  run "python.exe -m conda update --all" and I don't have any problems with SSL , even I did not run any actvate.bat and I did not set any CONDA_xxx environment variables.

For now I can achieve it with python-startup modification as of:
_import os
import sys
prefix = os.path.split(os.path.abspath(sys.executable))[0]
env = os.environ
env['CONDA_DLL_SEARCH_MODIFICATION_ENABLE'] = '1'
env['CONDA_DEFAULT_ENV'] = 'base'
env['CONDA_PREFIX'] = prefix
env['CONDA_SHLVL'] = '1'_

Why Anaconda don't ship something like this and most of AnacondaHome\Scripts and cwp.py going to be obsolete. Actually Anaconda is changing os.environ['PATH'] there, while prohiboting others to do it.

1. I am not very familiar with GitHub UI. Can somebody tell me how to generate ZIP with all Anaconda's patched C code from "recipes" with diff files (just sources for Python.exe+py*dll, especially main.c with CONDA_xxx handling). Maybe I can understand better what you really did change it and why it is really better to change especially C instead of Python.

2. I am not against changing C, I am against having many different versions of Python interpreters. Theoretically regular Python.exe may mai implement option to provide way to attach C plugin DLLs for activation control or other purposes (other than C extensions for Python libraries). If anaconda need something special in C - they do it in C or Python plugin.
If something is better to do using C, it can be C/C++, something else can be done other way.

**Comment by mingwandroid** [comment]
> P.P.S.
What about following:
There is module sys in Python, It has 'path' member variable inside. It controls how to search Python modules and site.py modifies it on startup. What about adding there additional variable dllpath to control loading of DLLs. Anaconda may extend this sys.dllpath in this variable without touching environ[PATH]. For further control Anaconda can implement it inside special startup-plugin DLL with special handling of DLL loading, but maybe all what is needed that Anconda extends sys.dllpath using sitevendor.py and that is all: Python.exe will load DLLs from right places, no need to patch main.c in Python.exe and os.environ['PATH'] is untouched...

We will happily review any PRs.

**Comment by vx1920** [comment]
_>>> We will happily review any PRs._

What about review-approve-merge this PR and after that I submit next PR for new file to ship it with Anaconda in the root folder (where we have python.exe). I have no any idea about all these variables, but I have suspicions that everything can be changed at any moment after updates in Python.exe. You perform corresponding change in sitevendor.py which also is updated and I can run Python.exe from command line again without problems in OpenSSL DLL loading.  If you like to control python.exe with environment variables - you can continue do it. Nobody need to know about it.

_# ------- sitevendor.py, shipped/updated with Anaconda ----
import os
import sys
prefix = os.path.split(os.path.abspath(sys.executable))[0]
env = os.environ
env['CONDA_DLL_SEARCH_MODIFICATION_ENABLE'] = '1'
env['CONDA_DEFAULT_ENV'] = 'base'
env['CONDA_PREFIX'] = prefix
env['CONDA_SHLVL'] = '1'
# eof_

**Comment by mingwandroid** [comment]
I think this should be closed. The reported issue has nothing to do with CPython, it's purely to do with `Anaconda Distribution`'s CPython build on Windows. Sorry for the noise.

@vx1920, if you want to continue this (though I believe it will be fruitless as I've stated our position *and* the reasoning behind them) then please discuss it at https://github.com/ContinuumIO/anaconda-issues/issues/3292 instead of here.

**Pull request closed without merging**
