### PR TITLE
gh-99108: Followup fix for Modules/Setup

### PR DESCRIPTION
**Pull request by msprotz**
* Issue: gh-99108

Automerge-Triggered-By: GH:erlend-aasland

### CODE REVIEW

**Review by asottile — APPROVED** [review]
no idea why the cpython suite doesn't fail -- my guess is it doesn't use this file

**Comment by msprotz** [comment]
thanks -- do you mind adding a skip-news label, too?

**Comment by erlend-aasland** [comment]
Can you please fix `Modules/Setup.stdlib.in` also?

**Comment by asottile** [comment]
> Can you please fix `Modules/Setup.stdlib.in` also?

afaict that file is correct (and validated because it gets used by the testsuite)

**Review by erlend-aasland — APPROVED** [review]

**Comment by gpshead** [comment]
I personally don't know why Modules/Setup even exists anymore, I thought the .in file template replaced it.

**Comment by erlend-aasland** [comment]
> I personally don't know why Modules/Setup even exists anymore, I thought the .in file template replaced it.

Yes, true. I'm not sure if `Modules/Setup` is actually usable. If it is unusable, we should just tear it out.

**Pull request merged**
