### PR TITLE
GH-94808: Cover `PyOS_mystrnicmp` and `PyOS_mystricmp`

### PR DESCRIPTION
**Pull request by artemmukhin**
* Issue: gh-94808

### CODE REVIEW

**Comment by ortem** [comment]
I'm not sure who is best positioned to review this, but maybe @corona10 could take a look?

**Comment by corona10** [comment]
> I'm not sure who is best positioned to review this, but maybe @corona10 could take a look?

Okay, I will take a look by this weekend :)

**Comment by ortem** [comment]
@corona10 Thank you!

**Review by corona10 — CHANGES_REQUESTED** [review]
Would you like to separate the file into Modules/_testcapi/pyos.c
likewise https://github.com/python/cpython/blob/main/Modules/_testcapi/float.c ?

The test itself looks good.

**Comment by ortem** [comment]
I have made the requested changes; please review again.

@corona10 Thank you for the review! I've separated the tests.

Although I haven't managed to run the tests from `Modules/_testcapi` on my machine. Before separating, I ran my tests via `./python -m test -v test_capi`, but now they are note executed as I see. I found the [C API Tests](https://devguide.python.org/developer-workflow/c-api/#c-api-tests) paragraph in the devguide, but I didn't find how to run these tests. Could you please clarify?

**Comment by ortem** [comment]
I've found out that the tests were not executed because of the wrong naming.

`Test_testcapi` only executes the test method if its built-in name starts with `test_` and doesn't end with `_code`:

https://github.com/python/cpython/blob/ced13c96a4eb9391a9d27e3e13218f70c579670f/Lib/test/test_capi/test_misc.py#L1422-L1425

It is mentioned in the [C API Tests](https://devguide.python.org/developer-workflow/c-api/#c-api-tests) paragraph to some extent:
> Functions named `test_*` are used as tests directly

But at first reading, I got confused because in `_testcapi/float.c` file, the `test_` prefix is only used in the C function name:

https://github.com/python/cpython/blob/534660f1680955c7a6a47d5c6bd9649704b74a87/Modules/_testcapi/float.c#L84-L88

However, in contrast to my tests, these test methods are actually executed through `test_float.py`:

https://github.com/python/cpython/blob/534660f1680955c7a6a47d5c6bd9649704b74a87/Lib/test/test_float.py#L1516-L1519

I hope this investigation might help other first-time contributors.

@corona10 If you think it would be helpful to clarify this point in the devguide, please let me know, and I'll be happy to open a corresponding PR.

**Comment by corona10** [comment]
> I've found out that the tests were not executed because of the wrong naming.
> Test_testcapi only executes the test method if its built-in name starts with test_ and doesn't end with _code:
> But at first reading, I got confused because in _testcapi/float.c file, the test_ prefix is only used in the C function name:
> However, in contrast to my tests, these test methods are actually executed through test_float.py:

AFAIK, those things are intended.

**Review by corona10 — APPROVED** [review]
LGTM

But I want to listen to the opinion of @erlend-aasland  for this testing structure.

**Comment by ortem** [comment]
@erlend-aasland could you please take a look?

**Review by erlend-aasland — APPROVED** [review]

**Comment by ortem** [comment]
Thank you!

Cc @corona10

**Pull request merged**
