### PR TITLE
bpo-31948: Broken MSDN links in msilib docs

### PR DESCRIPTION
**Pull request by Jesse-Bakker**
bpo-31948: Fix broken MSDN links in msilib docs

https://bugs.python.org/issue31948

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by Mariatta — APPROVED** [review]

**Review by Mariatta — CHANGES_REQUESTED** [review]
Thanks! The NEWS entry is not needed. Please remove it. Otherwise, everything else looks great!

**Comment by Jesse-Bakker** [comment]
I have made the requested changes; please review again.

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks @Jesse-Bakker and congrats on your first contribution to CPython 🌮

**Comment by Mariatta** [comment]
@Jesse-Bakker could you prepare the backport PR against 3.6 branch?
Thanks.

**Comment by Jesse-Bakker** [comment]
@Mariatta Will do!

**Pull request merged**
