### PR TITLE
__mro__ attribute change with getmro function in inspect module

### PR DESCRIPTION
**Pull request by hakancelikdev**

### CODE REVIEW

**Comment by hakancelik96** [comment]
I request "skip issue" and "skip news".

**Review by hadialqattan — APPROVED** [review]
A good catch!

Tested manually using the Python REPL on Ubuntu 20.04.1 LTS (Focal Fossa).

**Comment by iritkatriel** [comment]
@hakancelik96 can you explain why you are proposing this change?

**Comment by hakancelik96** [comment]
> @hakancelik96 can you explain why you are proposing this change?

I wanted to make this change to improve readability, it seemed like a better idea to use an already existing method, but now I think that there should be a lot of code in CPython like this, and updating each one like this might be unnecessary.

In addition, I wanted to practice myself by contributing to CPython the times when I made this change and move towards better contributions.

**Comment by iritkatriel** [comment]
@hakancelik96 I understand, and I am glad that you are interested in contributing to Python.

Readability is a matter of opinion, and this is why the [dev guide](https://devguide.python.org/) advises against cosmetic-only changes. There is also a cost to code-churn in terms of long commit histories, potential for errors slipping in, etc.

Have a look at [this blog post](https://realpython.com/start-contributing-python/ ) for some suggestions on contributing to Python. See you soon on another PR!

**Pull request closed without merging**
