### PR TITLE
Fix typo in configure

### PR DESCRIPTION
**Pull request by eltociear**
hte -> the

### CODE REVIEW

**Comment by NAPADAI** [comment]
configure

**Comment by NAPADAI** [comment]
> configure

**Review by UriyaHarpeness — APPROVED** [review]

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by ned-deily** [comment]
@corona10, FYI, this PR Is incomplete. `configure` is a file generated from `configure.ac` using `autoreconf`.  When making changes, you need to change `configure.ac` first, then run `autoreconf`, then checkin the changes to both files.  We maintain `configure` as a check-in file for convenience so people don't have to run `autoreconf` themselves when changes to `configure.ac` are made.  If you don't change `configure.ac`, the change made just to `configure` will likely be lost the next time a change to `configure.ac` (and thus `configure`) is made.  The Dev Guide has more info: https://devguide.python.org/setup/#regenerate-configure

**Comment by corona10** [comment]
@ned-deily 
Thank you, I got the email from you and I noticed that what I missed. 
It's definitely my mistake. sorry about this.
I create the revert PR for this.

**Pull request merged**
