### PR TITLE
bpo-30934: IDLE: Add Linux/MacOS coverage usage

### PR DESCRIPTION
**Pull request by mlouielu**

### CODE REVIEW

**Comment by terryjreedy** [comment]
What you wrote is what I would *like* to do, but how does `python -m coverage` work when coverage is not installed for the repository?  I just get 'No module named coverage'.   I also tried python <path to 3.6 site-lib/coverage> and coverage ran but its internal inports failed.

**Comment by mlouielu** [comment]
@terryjreedy @csabella Add on how to prepare coverage on Linux and MacOS. I didn't put this on first because I thought that you will prepare it via `5. Test Coverage` top says.

**Comment by terryjreedy** [comment]
Now that I know what is in common, I think I will rewrite a bit to eliminate duplication within and with the devguide.  I probably will have a question.

**Comment by JulienPalard** [comment]
@terryjreedy, ping

**Comment by terryjreedy** [comment]
Closed for reasons noted on issue.

**Pull request closed without merging**
