### PR TITLE
bpo-40024: Update _elementtree to use PyModule_AddType

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue40024

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
Would you mind to revert _decimal changes and move them into a separated PR?

**Comment by skrah** [comment]
`_decimal` deliberately calls `PyType_Ready()` at the top of `PyInit__decimal()`, so I don't see the need for the new function here. I'm not going to restructure the whole init.

So please just remove these changes, no need for a separate PR.

**Comment by corona10** [comment]
@vstinner @skrah 
Thanks for the review :)
I 've reverted decimal. Please take a look.

**Review by vstinner — APPROVED** [review]
LGTM.

**Pull request merged**
