### PR TITLE
bpo-36623: Clean parser headers and include files

### PR DESCRIPTION
**Pull request by pablogsal**
All of these functions are not used/defined anymore.

https://bugs.python.org/issue36623

### CODE REVIEW

**Comment by vstinner** [comment]
Sorry, I don't have bandwidth right now to review your PR. Maybe come back to me in 2 weeks. Your PR is scary because it's very long and it changes a lot of public headers at once.

**Comment by zooba** [comment]
I think this should have a NEWS entry and What's New section, as it's removing headers that were publicly available (even if they should not have been).

On the off chance that it breaks somebody, that will give them an issue to come and post on, or at least read the rationale. It can be the same issue as the original change.

**Comment by methane** [comment]
It seems simple removal.  LGTM if CI can compile them without any warnings.

**Comment by pablogsal** [comment]
Resolved merge conflicts regarding the WhatsNew entries.

**Review by methane — APPROVED** [review]

**Pull request merged**
