### PR TITLE
bpo-33679: IDLE: Re-enable color configuration for code context

### PR DESCRIPTION
**Pull request by csabella**
The difference from before is that the settings are now on the
Highlights tab instead of the Extensions tab and only change one theme
at a time instead of all themes.  The default for light themes is black
on light gray, as before.  The default for the IDLE Dark theme is white
on dark gray, which better fits the dark theme.

When one starts IDLE from a console and loads a custom theme without
definitions for 'context', one will see a warning message on the console.
To stop the warning, go to Options => Configure IDLE => Highlights,
select the custom theme if not selected already, select 'Code Context',
and select foreground and background colors.

https://bugs.python.org/issue33679

### CODE REVIEW

**Review by terryjreedy — COMMENTED** [review]
Your initial context background is cute, but a bit too 'cute'.  I think something more neutral, black #000000, dark gray, such as #606060, or dark bluish-gray, such as #505090 is better for a default.  I changed to the latter.

I want to re-test colors with variable contexts, as it was background color flipping that annoyed me previously.  I think this is otherwise ready to merge.

In a separate issue, we should eliminate the config loop.  The new reload method, called when Settings closes, should reset existing code context widgets.

In a separate issue, perhaps after 3.6 is frozen, we can and should change the use of theme_elements in configdialog.py to not need the order field.

**Comment by terryjreedy** [comment]
I merged #7333 first, and will try to fix the conflicts with the web editor before trying to make a branch for further testing.

**Comment by csabella** [comment]
The new color looks like a dark periwinkle to me, meaning it looks purple-ish (maybe it's my monitor).  This one looks a little more in the dark bluish-gray range - #56647e (86, 100, 126 with the sliders).

**Comment by terryjreedy** [comment]
Given the differences between monitors and eyes, I think we should make the default a neutral gray that is the inverse of the light gray for light themes.  I just pulled 'variable lines' to retest this patch.

**Comment by terryjreedy** [comment]
Test failure: Travis does not run GUI tests, so it did not run code context tests, so its pass do not mean that the merge is OK.  Appveyor does run GUI tests, but fixing the merge conflicts did not merge in all the changes in the the variable lines patch.  In particular, the test was run without the config-main changes that the merged tests assume.  There is supposed to be an 'update PR' button, but I don't see one.  I will do it and retest on my system.

**Comment by terryjreedy** [comment]
The problem was mis-selecting one line in codecontext.py.  There was no update button because it was done as part of the merge resolution.

**Pull request merged**
