### PR TITLE
bpo-28453: Document missing SSLObject methods

### PR DESCRIPTION
**Pull request by stevenwinfield**
https://bugs.python.org/issue28453

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by brettcannon** [comment]
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

**Comment by stevenwinfield** [comment]
Hi,
I signed the CLA at the same time as I submitted the pull request, received email confirmation, and specified my github username on bpo, but the checker web app still says I haven’t signed. 
Who am I supposed to contact about this?
Thanks.

**Comment by brettcannon** [comment]
@stevenwinfield I can see that your GitHub name is properly associated, but the CLA signing hasn't been recorded yet. You can email contributors@python.org to see if they received the CLA.

**Pull request closed without merging**
