### PR TITLE
[3.7] bpo-34977: Add Windows App Store package (GH-11027)

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue34977

### CODE REVIEW

**Review by vstinner — DISMISSED** [review]
I would prefer to see the change land on master first, wait until buildbots run, and only later merge into 3.7.

By the way, I prefer "git cherry-pick -x" (from commit in master) to track that it's a backport, but that's just not a requirement :-)

**Comment by zooba** [comment]
The backport is slightly different already, so it can't be a direct cherry-pick.

I'll wait for master, but I'm also going to ask @ned-deily  to hold 3.7.2rc1 for this change, so please help that one land.

**Comment by vstinner** [comment]
> The backport is slightly different already, so it can't be a direct cherry-pick.

Oh ok, I didn't notice.

**Comment by ned-deily** [comment]
Since we still have another couple of open issues and this is so close, I am holding 3.7.2rc1 for another day or so in the hopes we can get this in.

**Comment by zooba** [comment]
I have made the requested changes; please review again

**Pull request merged**
