### PR TITLE
gh-101137: Add `text/x-rst` to `mimetypes`

### PR DESCRIPTION
**Pull request by sobolevn**
* Issue: gh-101137

### CODE REVIEW

**Comment by sobolevn** [comment]
Ok, I found https://github.com/python/cpython/pull/17995
Removing the `md` part from this PR.

**Comment by jaraco** [comment]
Thanks for getting this done before I committed and proposed the same change :)

**Review by jaraco — APPROVED** [review]

**Comment by sobolevn** [comment]
Do we want a backport?

**Comment by jaraco** [comment]
> Do we want a backport?

I'm unsure. For #17995, I contend that it definitely deserves a backport, since `text/markdown` is unequivocally in the standards list (so it's a bug that it's missing from the behavior). `text/x-rst`, however, is less formally recognized, so is less obviously a bug, so I'm slightly inclined not to back port it and treat it like a feature. On the other hand, `text/x-rst` is also standardized in the Python packaging ecosystem, so also seems like an obvious shortcoming. I'll flag this one for backport too, but without prejudice (and give the release manager some time to review after `text/markdown`).

**Comment by jaraco** [comment]
@sobolevn Would you reconcile the backport? Thanks.

**Pull request merged**
