### PR TITLE
Use Py_TYPE to access ob_type

### PR DESCRIPTION
**Pull request by pdox**
We have a macro, so let's use it!

### CODE REVIEW

**Comment by pdox** [comment]
I believe this is trivial enough of a change (just search & replace), that it makes sense to skip news and issue.

**Review by asvetlov — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
I'm -1. This is just a code churn. Using `ob_type` is legitimate. `Py_TYPE()` is helpful when the pointer has a type different from `PyObject *`. We usually don't do such kind of changes.

**Comment by pdox** [comment]
@serhiy-storchaka 
This is about increasing the flexibility of the code. By having all accesses to ob_type go through the macro, it becomes easier to instrument cPython for debugging or customized behavior. If someone wants to add extra logic on every access to ob_type (e.g. for debugging), that person would have to repeat the work of this PR.

Since I already did this for my own purpose (I needed a way of detecting ob_type accesses), I was hoping I could save other people the trouble by sending the change upstream.

**Comment by serhiy-storchaka** [comment]
Open an issue on the tracker for the discussion. This is not a trivial change. It changes too much code, and it should be reviewed and approved by several core developers.

**Comment by rhettinger** [comment]
FWIW, I concur with this rejection for all the reasons mentioned by Serhiy.

**Pull request closed without merging**
