### PR TITLE
bpo-44959: Added fallback to extension modules with '.sl' suffix on HP-UX

### PR DESCRIPTION
**Pull request by florinspatar**
https://bugs.python.org/issue44959

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@florinspatar

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by vstinner** [comment]
I closed/reopened the PR to re-run the failed  CI job: Address sanitizer (pull_request):

```
2 tests failed: test__xxsubinterpreters test_multiprocessing_fork
```

Please ping me once tests pass, I will merge your PR ;-)

**Review by vstinner — APPROVED** [review]
LGTM.

The NEWS entry should be in the "Core" category, but I don't care much. Change it it you want (remove the old file, re-run blurb to add a new entry).

**Comment by florinspatar** [comment]
Did the requested NEWS change. `test_multiprocessing_fork` seem to fail randomly

**Comment by vstinner** [comment]
Merged, thanks for your contribution @florinspatar!

**Pull request merged**
