### PR TITLE
bpo-33792: Add selector and proactor windows policies

### PR DESCRIPTION
**Pull request by 1st1**
https://bugs.python.org/issue33792

### CODE REVIEW

**Comment by 1st1** [comment]
There's no adequate documentation on asyncio policies that lists all of them.  I'll try to work on that in a separate PR.

**Review by vstinner — APPROVED** [review]
LGTM.

The new classes should be documented around https://docs.python.org/dev/library/asyncio-eventloops.html#event-loop-policies-and-the-default-policy

But it can be done later, right now event DefaultEventLoopPolicy is not properly documented... It's just *mentionned* one.

Please backport the change to 3.7 :-)

**Comment by vstinner** [comment]
Oh wow, AppVeyor failed with a weird error!?

```
FAIL: test_env_var_debug (test.test_asyncio.test_base_events.BaseEventLoopTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\test\test_asyncio\test_base_events.py", line 771, in test_env_var_debug
    sts, stdout, stderr = assert_python_ok('-E', '-c', code)
  File "C:\projects\cpython\lib\test\support\script_helper.py", line 157, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "C:\projects\cpython\lib\test\support\script_helper.py", line 143, in _assert_python
    res.fail(cmd_line)
  File "C:\projects\cpython\lib\test\support\script_helper.py", line 84, in fail
    err))
AssertionError: Process return code is 3221225477
command line: ['C:\\projects\\cpython\\PCbuild\\win32\\python.exe', '-X', 'faulthandler', '-I', '-E', '-c', 'import asyncio\nloop = asyncio.get_event_loop()\nprint(loop.get_debug())']
stdout:
---
---
stderr:
---
Windows fatal exception: access violation
Current thread 0x00000184 (most recent call first):
  File "C:\projects\cpython\lib\asyncio\events.py", line 41 in __init__
  File "C:\projects\cpython\lib\asyncio\selector_events.py", line 260 in _add_reader
  File "C:\projects\cpython\lib\asyncio\selector_events.py", line 117 in _make_self_pipe
  File "C:\projects\cpython\lib\asyncio\selector_events.py", line 66 in __init__
  File "C:\projects\cpython\lib\asyncio\events.py", line 660 in new_event_loop
  File "C:\projects\cpython\lib\asyncio\events.py", line 640 in get_event_loop
  File "<string>", line 2 in <module>
---
```

**Comment by vstinner** [comment]
> There's no adequate documentation on asyncio policies that lists all of them. I'll try to work on that in a separate PR.

Ok, works for me.

**Comment by 1st1** [comment]
> Oh wow, AppVeyor failed with a weird error!?

Not sure if it's related; restarted the CI.

**Comment by 1st1** [comment]
@ned-deily @vstinner The CI crash on Windows buildbots is real and I have no idea what's going on. It seems to be completely unrelated to asyncio.

Here's a screenshot from my Win VM:
screen shot 2018-06-07 at 6 28 08 pm

**Comment by ned-deily** [comment]
Would it help to pull in some of the Windows experts?  (I’ll be off line for the next few hours.)

**Comment by 1st1** [comment]
Victor was also able to reproduce the bug. But the CI is green now...

The crash is specific to 32bit builds and seems to be originating from

```python
class Handle:
    """Object returned by callback registration methods."""

    __slots__ = ('_callback', '_args', '_cancelled', '_loop',
                 '_source_traceback', '_repr', '__weakref__',
                 '_context')

    def __init__(self, callback, args, loop, context=None):
        if context is None:
            context = contextvars.Context()   # << this line
```

If we add a simple `dict()` before "# << this line" the crash disappears :)

**Comment by vstinner** [comment]
The crash is https://bugs.python.org/issue33803 and it's unrelated to this change. It's just that the change made the bug more likely.

**Pull request merged**
