### PR TITLE
bpo-27580: Add support of null characters in csv

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
https://bugs.python.org/issue27580

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
@smontanaro, please take a look. For unknown reasons I cannot add you to reviewers.

**Comment by ammaraskar** [comment]
You don't have to necessarily do it here, but just a note to myself that we should update the `csv` fuzzer:

https://github.com/python/cpython/blob/0219017df7ec41839fd0d56a3076b5f09c58d313/Modules/_xxtestfuzz/fuzzer.c#L356-L360

to generate inputs with nulls, such as in the json fuzzer here:

https://github.com/python/cpython/blob/0219017df7ec41839fd0d56a3076b5f09c58d313/Modules/_xxtestfuzz/fuzzer.c#L166-L169

in this or a follow up PR.

**Review by iritkatriel — APPROVED** [review]

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by serhiy-storchaka** [comment]
> I assume `Doc/library/csv.rst` will be updated at some point to make it clear that ASCII NUL is now a valid.

I have not found a good place for this. It was not documented that ASCII NUL is special. Perhaps a NEWS entry will be enough.

**Comment by merwok** [comment]
#97503 is requesting a backport to 3.10

**Pull request merged**
