### PR TITLE
trivial: use $(MAKE) instead of literal "make"

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Review by matrixise — APPROVED** [review]

**Comment by matrixise** [comment]
Hi @grimreaper,

thank you for your pull request.

**Comment by matrixise** [comment]
There is an issue with the multiprocessing module but we don't change that module :/ and I can't run again TravisCI :/

**Comment by grimreaper** [comment]
I rebased which should re-run the tests.

**Comment by matrixise** [comment]
Hi @grimreaper thank you for your rebase, and now the CI is green...

**Comment by methane** [comment]
I don't think this change is worth enough.  `$(MAKE)` is good for executing, but it may not be good for printing in some time.  For example, when you type `make`, but `$(MAKE)` can be full path of the make program.

**Comment by grimreaper** [comment]
Note that it is possible if not likely that `make` is wrong. Perhaps we should print the basename of `$(make)`?

**Comment by methane** [comment]
I don't think pay attention for this is not worth enough.
If `make` is wrong, the user knows right command.

**Pull request closed without merging**
