### PR TITLE
bpo-40443: Remove unused imports in idlelib

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue40443

### CODE REVIEW

**Comment by vstinner** [comment]
@terryjreedy @csabella: Would you mind to review this PR?

**Review by terryjreedy — APPROVED** [review]
Non-use verified.

**Comment by terryjreedy** [comment]
Don't understand macOS failure, and the abrupt stop.  Treating as unrelated intermittent failure.
```
clang: warning: -framework Tk: 'linker' input unused [-Wunused-command-line-argument]
In file included from /Users/runner/runners/2.169.1/work/cpython/cpython/Modules/_tkinter.c:46:
/Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/tk.h:86:11: fatal error: 'X11/Xlib.h' file not found
#       include <X11/Xlib.h>
                ^~~~~~~~~~~~
1 error generated.

Python build finished successfully!

...
The following modules found by detect_modules() in setup.py, have been
```
...

**Comment by vstinner** [comment]
Terry: yeah sadly the macOS CI looks sick :-(

**Pull request merged**
