### PR TITLE
Fix typos in unittest.mock documentation

### PR DESCRIPTION
**Pull request by anirudh-chhangani**
assert, not assret

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by anirudh-chhangani** [comment]
I have signed the CLA, please rerun the check once approved. Thanks

**Comment by dianaclarke** [comment]
While strange at first glance, the use of "assret" was intentional in this context. These docs are illustrating what would happen if you accidentally typed "assret" rather than "assert" (a common typo).

Some history and additional context can be found here:

- Patch: [Closes Issue 21238: New keyword argument `unsafe` to Mock.](https://github.com/python/cpython/commit/8c14534df6c7bd561fac31985fba60306e181265)

- Bug #21238: [unittest.mock.Mock should not allow you to use non-existent assert methods](http://bugs.python.org/issue21238)

This is apparently such a common typo, that it's even special-cased here:

 - https://github.com/python/cpython/blob/97e1b1c81458d2109b2ffed32ffa1eb643a6c3b9/Lib/unittest/mock.py#L582

Now we know :)

**Review by dianaclarke — CHANGES_REQUESTED** [review]
Review: -1, do not merge

----------

See my earlier comment about "assret" being correct in this context.

**Comment by anirudh-chhangani** [comment]
@dianaclarke you are correct, I should have read the whole context before making the change. Thanks for the clarification.

**Pull request closed without merging**
