### PR TITLE
gh-92626: Correct JavaScript MIME types + extensions per RFC 9239

### PR DESCRIPTION
**Pull request by mathiasbynens**
This patch updates the MIME type configuration per RFC 9239.
https://www.rfc-editor.org/rfc/rfc9239

First, the recommended MIME type is now `text/javascript`:

> The most widely supported media type in use is `text/javascript`; all
> others are considered historical and obsolete aliases of `text/javascript`.

Second, the `.mjs` extension is now explicitly registered:

> The `.mjs` file extension signals that the file represents a JavaScript
> module. Execution environments that rely on file extensions to
> determine how to process inputs parse `.mjs` files using the Module
> grammar of [ECMA-262].

cpython already had an entry for `.mjs` (great!), but it was using the obsolete
MIME type.

IANA template: https://www.iana.org/assignments/media-types/text/javascript

Issue: #92626

### CODE REVIEW

**Comment by arhadthedev** [comment]
> RFC: 9239
> Published: May 2022
>
> 6.1.Common JavaScript Media Types
> 6.1.1. text/javascript

🎉🎉🎉 Finally encoding-aware human-readable text is treated as such (`text/*`) instead of binary blobs (`application/*`).

> `text`
>
> Text-only data including any human-readable content, source code, or textual data such as comma-separated value (CSV) formatted data.
>
> `application`
>
> Any kind of binary data that doesn't fall explicitly into one of the other types; either data that will be executed or interpreted in some way or binary data that requires a specific application or category of application to use. Generic binary data (or binary data whose true type is unknown) is application/octet-stream. Other common examples include application/pdf, application/pkcs8, and application/zip.
>
> -- https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

**Comment by AA-Turner** [comment]
Lib/test/mime.types should maybe be updated, although it seems that file hasn't been substantively updated since 2011:

https://github.com/python/cpython/blob/cb04a09d2dfd197436a11de504b92773569e19fb/Lib/test/mime.types#L1217

Also:

https://github.com/python/cpython/blob/1f134e96ba994bea3aaea533d4a558df3c5cc3c0/Tools/wasm/README.md?plain=1#L213-L217

A

**Comment by AA-Turner** [comment]
@warsaw would we backport something like this? I'm unsure if it would count as a bugfix.

A

**Comment by arhadthedev** [comment]
It would be great to have this PR merged since it brings stuff to the latest RFC.

**Comment by encukou** [comment]
This was changed in #97934. Apologies for forgetting this PR.

**Pull request closed without merging**
