### PR TITLE
Simplify wording in logging.debug reference

### PR DESCRIPTION
**Pull request by andresdelfino**

### CODE REVIEW

**Comment by pablogsal** [comment]
Personally, I prefer `if it does evaluate to True` or `if its boolean value is true` or similar wording. The rationale is that IMHO `if true` can be confused to "it has to bee the object `True`". 

I like to resolve the double negative, though.

**Comment by andresdelfino** [comment]
I can change the PR, but please consider that "if true/false" is all over the place in the documentation. I think it's something you should have learned by the time you are using the logging module.

**Comment by andresdelfino** [comment]
>     1. There is another area on the same page with similar wording of `if it does not evaluate as false`, so if one is changed, then the other should be as well.

Agreed! Fixed.

>     2. This page has areas which state `if evaluates to True/False` and some that have `if True/False`.  

Please note the casing: text says "true"/"false", not "True"/"False", which are actual reserved words. Lots of things evaluate to true/false that are not actually True/False objects, so referencing the constants would be wrong.

On a related comment, I'd also replace occurrences of "if X evaluates to Y" to "if Y" (as in "if X evaluates to true" -> "if true").

**Comment by vsajip** [comment]
There's a specific reason I used "does not evaluate to false" - in this particular case, you can pass for `exc_info` one of:

* An exception tuple - adds exception info to the logging event
* An exception instance - adds exception info to the logging event
* Any truthy value - adds exception info to the logging event using `sys.exc_info()`
* Any non-truthy value ("does evaluate to false" - but not necessary `False`) - no exception info added to the logging event

So, the "does not evaluate to false" is a concise way of identifying the first three cases (which have in common that exception info is added to the event, which is stated immediately following that phrase).

I feel that the suggested wording ("is true") might have more potential for confusing with "is `True`" and so I don't see the need to make this change. Propose to close.

**Comment by andresdelfino** [comment]
Closing per module's author proposal.

**Pull request closed without merging**
