### PR TITLE
gh-91325: Skip Stable ABI checks with Py_TRACE_REFS special build

### PR DESCRIPTION
**Pull request by encukou**
Py_TRACE_REFS is not compatible with Py_LIMITED_API nor with the stable ABI.

* Issue: gh-91325

### CODE REVIEW

**Review by kumaraditya303 — DISMISSED** [review]
There are merge conflicts.

**Comment by encukou** [comment]
... where are my soft cushions, @bedevere-bot ?

**Comment by encukou** [comment]
No soft cushions, so I've resolved the conflict.

**Comment by encukou** [comment]
I have made the requested changes; please review again

**Pull request merged**
