### PR TITLE
gh-101981: Consolidate macOS configure steps in CI

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-101981

Automerge-Triggered-By: GH:erlend-aasland

### CODE REVIEW

**Review by ned-deily — APPROVED** [review]
LGTM, thanks! Let's see if it works :)

**Comment by erlend-aasland** [comment]
> LGTM, thanks! Let's see if it works :)

Thanks for the heads-up, I had forgotten about this :)

Now, I also adjusted the `PKG_CONFIG_PATH` variable to adhere to the recommendations of the devguide. We'll see how that fares.

**Comment by erlend-aasland** [comment]
I'll have to look at the CI failure tomorrow; over and out from Scandinavia.

**Comment by corona10** [comment]
It doesn't works, it seems like `test_tools`reference the `GITHUB_ENV`, so if we want to make this pass.
IMHO, we should make `test_tools` to reference the `configure`  scope variable.

**Comment by erlend-aasland** [comment]
See fix in #102152

**Pull request merged**
