### PR TITLE
gh-113692: skip a test if multiprocessing isn't available.

### PR DESCRIPTION
**Pull request by vsajip**
* Issue: gh-113692

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Looks good!

(should we set `required_on` to at least one platform as typo protection?)

**Comment by vsajip** [comment]
> Looks good!
> (should we set required_on to at least one platform as typo protection?)

Thanks. Do you think that's needed for this specific issue? It seems a simple enough change. Not sure what you mean by typo protection.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
> Not sure what you mean by typo protection.

I think @hauntsaninja is suggesting we require this pass on some platform to avoid a typo in the name of the module being imported since there's no error checking the module name is legitimate (although could that check be added thanks to `sys.stdlib_module_names`?).

@vsajip I added the backport label as I think this needs to land in 3.12 as well.

**Comment by hauntsaninja** [comment]
Yup, that's what I meant :-) Looks like sys.stdlib_module_names won't do the trick, it doesn't include things like `_xxsubinterpreters` or `_wmi`

**Comment by vsajip** [comment]
Perhaps `import_helper.import_module` could be enhanced to do these checks? Wouldn't that be the best place for such?

**Comment by hauntsaninja** [comment]
Yeah, I took Brett's suggestion to mean we add a check against `sys.stdlib_module_names` in `import_helper.import_module`. The naive thing doesn't work for the reasons I mention, and not sure this is important enough to make an allowlist for it.

**Pull request merged**
