### PR TITLE
bpo-40956: Convert _sqlite3.Cache to Argument Clinic

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue40956

### CODE REVIEW

**Comment by erlend-aasland** [comment]
skip news

**Comment by erlend-aasland** [comment]
FYI, rebased onto master bco. #20828

**Comment by erlend-aasland** [comment]
@berkerpeksag What about ditching the whole Cache/Node stuff and just use `functools.lru_cache`? Pro: It would get rid of a lot of code. Con: It might be a little bit slower. Worth pursuing?

**Comment by erlend-aasland** [comment]
@serhiy-storchaka Would you mind reviewing this?

**Comment by berkerpeksag** [comment]
> @berkerpeksag What about ditching the whole Cache/Node stuff and just use `functools.lru_cache`?

I'm usually not a fan of changing code that has been working fine for more than a decade, but let me think about it a bit.

I'm going to review this PR this week.

**Comment by erlend-aasland** [comment]
> I'm usually not a fan of changing code that has been working fine for more than a decade, but let me think about it a bit.

That's a valid argument, but take a look at my arguments at bpo-42862.

> I'm going to review this PR this week.

Great, thanks.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks, @serhiy-storchaka 🙏🏻

**Comment by erlend-aasland** [comment]
Closing this, as it has been made obsolete by #24203.

**Pull request closed without merging**
