### PR TITLE
bpo-32797: linecache should search for sources if loader doesn't find them

### PR DESCRIPTION
**Pull request by jdemeyer**
https://bugs.python.org/issue32797

### CODE REVIEW

**Comment by jdemeyer** [comment]
@embray 
@pfmoore

**Comment by pfmoore** [comment]
Looks good to me in relation to my comments [on python-list](https://mail.python.org/pipermail/python-ideas/2018-April/050151.html), that this is what the docs say. But I haven't reviewed [bpo-32797](https://bugs.python.org/issue32797), so I'm not going to approve this without @embray's feedback.

Further discussion should really be on the issue tracker, so I'll add any other comments I have there.

**Comment by jdemeyer** [comment]
@pfmoore: Erik Bray commented positively on this PR, so can this be approved then?

**Comment by encukou** [comment]
This was auto-closed by merging #9540. @jdemeyer, please re-open if that wasn't intentional.

**Pull request closed without merging**
