### PR TITLE
gh-100176: Remove outdated Tools/{io,cc,string}bench

### LINKED ISSUE #100176: Meta issue: clean up redundant compat code
# Bug report

There's several places that have compatibility code for EOL and unsupported Python versions.

We can modernise the code by removing the obsolete bits.

I'll open separate PRs to keep the changes focused by area, and intend to use this meta issue for them all (but can also open separate issues if preferred).

### Linked PRs
* gh-100177
* gh-100190
* gh-100197
* gh-100297
* gh-101853

### PR DESCRIPTION
**Pull request by hugovk**
Closes https://github.com/python/cpython/pull/32135.
Closes https://github.com/python/cpython/pull/100176.
Closes https://github.com/python/cpython/pull/100197.

See:

* https://github.com/python/cpython/issues/100176#issuecomment-1374752981
* https://discuss.python.org/t/do-we-still-need-tools-io-cc-string-bench/22557

Replaces and:
* closes https://github.com/python/cpython/pull/32135.
* closes https://github.com/python/cpython/pull/100197.

* Issue: gh-100176

### CODE REVIEW

**Comment by arhadthedev** [comment]
BTW, it allows to close gh-32135 as outdated.

**Comment by sobolevn** [comment]
@rhettinger had some opinion on this as well.

**Comment by erlend-aasland** [comment]
Sad to see Håvamål go 😢👁️

https://github.com/python/cpython/blob/81e3aa835c32363f4547b6566edf1125386f1f6d/Tools/iobench/iobench.py#L482-L548

**Comment by hugovk** [comment]
(Resolved conflict)

**Comment by Sophist-UK** [comment]
I would have commented sooner had I known that this was about to happen. It would have been helpful if someone had commented in [my PR to `ccbench.py`](https://github.com/python/cpython/pull/32135) that this was being considered so that I would have been notified and might have had a chance to comment before it happened.

I believe it was clear from the [extensive discussion about the shortcomings of the current GIL in faster-cpython](https://github.com/faster-cpython/ideas/discussions/328) that the `ccbench` script is still useful - because it clearly identifies an ongoing performance issue when multithreading with one or more CPU-heavy threads.

That said, I do understand that performance scripts do not really have a place in the cpython source code repo, but unfortunately I do not have the time to rework the updated `ccbench` script for the pyperformance suite, so I guess it is going to just disappear.

**Comment by hugovk** [comment]
> I would have commented sooner had I known that this was about to happen. It would have been helpful if someone had commented in [my PR to `ccbench.py`](https://github.com/python/cpython/pull/32135) that this was being considered so that I would have been notified and might have had a chance to comment before it happened.

Apologies, I'll ping next time this sort of thing comes up. (btw we wouldn't be allowed to merge your PR because it looks like the CLA isn't signed.)


> That said, I do understand that performance scripts do not really have a place in the cpython source code repo, but unfortunately I do not have the time to rework the updated `ccbench` script for the pyperformance suite, so I guess it is going to just disappear.

Yep, in general, benchmarks are much more useful in pyperformace, because they're run often and people pay attention to their results.

The code hasn't disappeared, it's still in the 3.12 and older branches, and in Git history.

And of course, if there's consensus we can easily revert/re-add bits of this.

**Comment by Sophist-UK** [comment]
> btw we wouldn't be allowed to merge your PR because it looks like the CLA isn't signed.

Go look at the PR history - I signed the CLA and the relevant label was added. Later the label was removed for some reason unknown to me..

**Pull request merged**
