### PR TITLE
GH-89812: Clean up pathlib tests.

### PR DESCRIPTION
**Pull request by barneygale**
Merge `PurePathTest` into `_BasePurePathTest`, and `PathTest` into `_BasePathTest`. No change of coverage.

* Issue: gh-89812

### CODE REVIEW

**Comment by barneygale** [comment]
Note that the `_BasePurePathTest` and `_BasePathTest` classes reflect a time long ago when pathlib had `pathlib._BasePurePath` and `pathlib._BasePath` classes. These haven't existed since pathlib was an independent package. We may re-introduce them in future (see #104810), but they will look rather different!

**Comment by ambv** [comment]
This depends on GH-105744.

**Comment by ambv** [comment]
I currently don't have a Windows box to test the coverage with, but I tested on macOS and Linux and this looks good to me. Let's go for it! Thanks for the cleanup, Barney! ✨ 🍰 ✨

**Comment by ambv** [comment]
(If you're curious to check on Windows, the guide is good: https://devguide.python.org/testing/coverage/)

**Comment by barneygale** [comment]
Thank you for the review, Łukasz!

**Pull request merged**
