### PR TITLE
socket documentation fix - rename triple to 3-tuple

### PR DESCRIPTION
**Pull request by OriHoch**
was a bit confusing to me looking at this doc, wasn't sure what a triple meant, also, I believe it has other meanings in different contexts..

Searching the docs I see a lot of usages of 3-tuple, so I assume it's more standard.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@OriHoch

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by ammaraskar** [comment]
Closing and re-opening to trigger CI.

**Comment by MaxwellDupre** [comment]
Cant build, cant review:
 ~/D/G/cpython   socket-doc-rename-triple-to-3-tuple $…  make -C Doc/ html
make: Entering directory '/home/me/Documents/GitHub/cpython/Doc'
mkdir -p build
Building NEWS from Misc/NEWS.d with blurb
PATH=./venv/bin:$PATH sphinx-build -b html -d build/doctrees   -W . build/html 
Running Sphinx v4.5.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 491 source files that are out of date
updating environment: [config changed ('version')] 485 added, 0 changed, 9 removed
reading sources... [100%] whatsnew/index                                                                                       

Warning, treated as error:
/home/me/Documents/GitHub/cpython/Doc/c-api/complex.rst:49:Error in declarator or parameters
Error in declarator or parameters
Invalid C declaration: Expected identifier, got user-defined keyword: complex. Remove it from c_extra_keywords to allow it as identifier.
Currently c_extra_keywords is ['alignas', 'alignof', 'bool', 'complex', 'imaginary', 'noreturn', 'static_assert', 'thread_local']. [error at 39]
  Py_complex _Py_c_neg(Py_complex complex)
  ---------------------------------------^
make: *** [Makefile:51: build] Error 2

**Comment by AA-Turner** [comment]
> wasn't sure what a triple meant

In mathematics, a triple is a [common name](https://en.wikipedia.org/wiki/Tuple#Etymology) for a tuple of three elements.

I'm +0 on this change.

A

**Comment by AA-Turner** [comment]
Closing & re-opening to re-trigger CLA.

**Comment by slateny** [comment]
I think that one could deduce that triple = 3-tuple just by context, but since `socket` isn't a math-related module I'd be +1 for changing it to avoid confusion (and to be a bit more consistent).

**Review by EmberCraze — APPROVED** [review]
LGTM

**Review by kumaraditya303 — APPROVED** [review]

**Review by hugovk — APPROVED** [review]

**Pull request merged**
