### PR TITLE
GH-46412: More efficient bool() for ndbm/_gdbmmodule

### PR DESCRIPTION
**Pull request by gvanrossum**
Based on patches uploaded to BPO by BPO user eolson (Eric Olson).
No known email or GitHub username for attribution.

(The bug was opened in 2008, not quite a record but still impressive.)

* Issue: gh-46412

### CODE REVIEW

**Review by corona10 — APPROVED** [review]
Nice! 
LGTM

**Comment by gvanrossum** [comment]
There was a subtle indentation error that caused 'make patchcheck' to fail.

Also, 'test_int' is now flaky due to the int-conversion security check -- it checks the time it takes to do conversions and the Azure VM was too slow. We may need to discuss this on Discord.

**Comment by corona10** [comment]
> There was a subtle indentation error that caused 'make patchcheck' to fail.

Ooops, I didn't notice that.

**Comment by gvanrossum** [comment]
Neither did I -- it took me forever (firing up various tools) to notice.

**Pull request merged**
