### PR TITLE
[3.7] gh-80254: Disallow recursive usage of cursors in sqlite3 converters

### PR DESCRIPTION
**Pull request by erlend-aasland**
(cherry picked from commit c908dc5b4798c311981bd7e1f7d92fb623ee448b)

Co-authored-by: Sergey Fedoseev <fedoseev.sergey@gmail.com>
Co-authored-by: Jelle Zijlstra <jelle.zijlstra@gmail.com>

### CODE REVIEW

**Comment by erlend-aasland** [comment]
CI cannot find merge base, and decides that this is not worthy running the tests. Buildbots seem to ignore this fact though, so I guess that it's fine if they are green.

**Comment by erlend-aasland** [comment]
This buildbot run does not look good. Do you experience this often on the 3.7 branch, @ambv?

**Review by JelleZijlstra — APPROVED** [review]
We're not allowed to merge until regular CI passes (the check is required). Code looks good to me but we'll have to figure out what's up with CI.

**Comment by erlend-aasland** [comment]
I think it is related to 4ac923f2756f835f512339ee181348cc535ab07f

**Comment by erlend-aasland** [comment]
I think backporting both GH-24004 and GH-21806 will fix it. Maybe not both are required, but I think both should be backported.

**Comment by vstinner** [comment]
The 3.7 branch no longer accept bugfixes, only security fixes: https://devguide.python.org/#status-of-python-branches

Do you consider that this change fix a security issue?

**Comment by ned-deily** [comment]
> Do you consider that this change fix a security issue?

Yes, see discussion [here](https://github.com/python/cpython/pull/29054#issuecomment-1117964876).

**Pull request merged**
