### PR TITLE
bpo-46794: Bump up the libexpat version into 2.4.6

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue46794

### CODE REVIEW

**Comment by corona10** [comment]
@hartwork Please take a look

**Comment by hroncok** [comment]
For the record, the Fedora update of standalone expat to 2.4.6 broke some tests. I am not seeing such failures here, so it might be something Fedora specific, but I recommend caution.

```
======================================================================
ERROR: testEncodings (test.test_minidom.MinidomTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.8.12/Lib/test/test_minidom.py", line 1150, in testEncodings
    self.assertRaises(UnicodeDecodeError, parseString,
  File "/builddir/build/BUILD/Python-3.8.12/Lib/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/builddir/build/BUILD/Python-3.8.12/Lib/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
  File "/builddir/build/BUILD/Python-3.8.12/Lib/xml/dom/minidom.py", line 1969, in parseString
    return expatbuilder.parseString(string)
  File "/builddir/build/BUILD/Python-3.8.12/Lib/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/builddir/build/BUILD/Python-3.8.12/Lib/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 5

======================================================================
ERROR: testExceptionOnSpacesInXMLNSValue (test.test_minidom.MinidomTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.8.12/Lib/test/test_minidom.py", line 1597, in testExceptionOnSpacesInXMLNSValue
    parseString('<element xmlns:abc=["http:abc.com/de f g/hi/j k"](http://abc.com/defg/hi/jk)><abc:foo /></element>')
  File "/builddir/build/BUILD/Python-3.8.12/Lib/xml/dom/minidom.py", line 1969, in parseString
    return expatbuilder.parseString(string)
  File "/builddir/build/BUILD/Python-3.8.12/Lib/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/builddir/build/BUILD/Python-3.8.12/Lib/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
----------------------------------------------------------------------

======================================================================
ERROR: test_issue3151 (test.test_xml_etree.BugsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.8.12/Lib/test/test_xml_etree.py", line 1972, in test_issue3151
    e = ET.XML('<prefix:localname xmlns:prefix="${stuff}"/>')
  File "/builddir/build/BUILD/Python-3.8.12/Lib/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
----------------------------------------------------------------------
```

Happens with all Python versions including 3.11.

**Comment by hroncok** [comment]
OK, that is 2cae93832f46b245847bdc252456ddf7742ef45e -- never mind me.

**Comment by corona10** [comment]
@hroncok Thanks for double-checking. 
I created the PR when I notice that @hartwork fix the issue :)

**Review by gpshead — APPROVED** [review]

**Review by hartwork — COMMENTED** [review]
> @hartwork Please take a look

Hi @corona10, I had a look at it now.  I used an approach similar to https://github.com/python/cpython/pull/31022#issuecomment-1033994084 except with Docker automation, details below.

Technically, the first commit `bpo-46794: Bump up the libexpat version into 2.4.6` drops the `pyexpatns.h` integration, so it does more than advertized (and would fail in `git bisect` context), and then that "regression" is reverted in a new commit. While that's likely considered picky, I would suggest to either

- a) squash the two commits together to resolve the semantic mismatch and bisect failure situation or
- b) turn it into a 3-commit sandwich where first `pyexpatns.h` integration is dropped to yield vanilla Expat 2.4.4, then an update to 2.4.6, and then bringing `pyexpatns.h` integration back.

Just my 2 cents. For my `Dockerfile`, it's this:

```Dockerfile
# Copyright (c) 2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the Apache license version 2.0

FROM alpine
RUN apk add --update \
            diffutils \
            git \
            sed \
        && \
    git clone --depth 1 https://github.com/python/cpython cpython-main \
        && \
    ( cd cpython-main && git rev-parse HEAD ) \
        && \
    git clone --depth 1 --branch bpo-46794 https://github.com/corona10/cpython corona10-bpo-46794 \
        && \
    ( cd corona10-bpo-46794 && git rev-parse HEAD ) \
        && \
    git config --global advice.detachedHead false \
        && \
    git clone --depth 1 --branch R_2_4_4 https://github.com/libexpat/libexpat libexpat_2_4_4 \
        && \
    git clone --depth 1 --branch R_2_4_6 https://github.com/libexpat/libexpat libexpat_2_4_6 \
        && \
    diff -r -u libexpat_2_4_4/expat/lib/ cpython-main/Modules/expat/ | tee 2-4-4.diff \
        && \
    diff -r -u libexpat_2_4_6/expat/lib/ corona10-bpo-46794/Modules/expat/ | tee 2-4-6.diff \
        && \
    sed -e '/^Only in /d' -e '/^\(+++\|---\) /d' -e '/^diff /d' -i 2-4-4.diff 2-4-6.diff \
        && \
    diff -u 2-4-4.diff 2-4-6.diff \
        && \
    echo 'Diff is good.'
```

Best, Sebastian

**Comment by hroncok** [comment]
Note that CPython PRs are squashed when merged.

**Comment by hartwork** [comment]
> Note that CPython PRs are squashed when merged.

@hroncok I assume that's an "always" then. Excellent point :+1:

**Review by hartwork — APPROVED** [review]

**Pull request merged**
