### PR TITLE
Conditionals Improvment

### PR DESCRIPTION
**Pull request by machinexa2**
I have modified conditionals of different files, I have changed `var is not None` to bool(var), and bool() isnt required in if cases
* is not is deprecated and gives warning
```python
>>> 1 is not None
<stdin>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
True
```
* is not None is lengthy and doesn't look nice
* is not None takes more opcode to perform the same task
```python
>>> x = lambda n: n if n is not None else ''
>>> y = lambda n: n if n else ''
>>> from dis import dis
>>> dis(x)
  1           0 LOAD_FAST                0 (n)
              2 LOAD_CONST               0 (None)
              4 IS_OP                    1
              6 POP_JUMP_IF_FALSE       12
              8 LOAD_FAST                0 (n)
             10 RETURN_VALUE
        >>   12 LOAD_CONST               1 ('')
             14 RETURN_VALUE
>>> dis(y)
  1           0 LOAD_FAST                0 (n)
              2 POP_JUMP_IF_FALSE        8
              4 LOAD_FAST                0 (n)
              6 RETURN_VALUE
        >>    8 LOAD_CONST               1 ('')
             10 RETURN_VALUE
>>>
```
Although replacing is not None doesn't break anything in 99% cases. In
1% cases, where variable either contains 0, or empty string can cause
error. So, you may review my edits. Also, I have seen some weird code
style like
```python
if var is not None and len(var) > 0:
```
To check whether a string, list, tuple or dictionary is empty or not by this way doesnt seem nice both visually and performance wise. I have changed them. `bool(var)` or `if var:` can check whether they are empty or not. bool() does the work and there's no need of that function in if statement.
Note, I havent touched unittest files and some other specific cases of `is not None` Also for `is None` I did quite similaar

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@machinexa2

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by machinexa2** [comment]
I have received signed document saying `You signed: "Contributor Agreement 2020-09-23` however doesnt show CLA `https://check-python-cla.herokuapp.com/` when my username `machinexa2` is given

**Comment by machinexa2** [comment]
Hmm I need to send that pdf

**Comment by tiran** [comment]
-1

``bool(v)`` has a different semantic than ``v is not None``. It's also four times slower and not considered good practice.

```
$ python3 -m timeit -s "v = None" "bool(v)"
5000000 loops, best of 5: 56.2 nsec per loop
$ python3 -m timeit -s "v = None" "v is not None"
20000000 loops, best of 5: 13.9 nsec per loop
```

**Comment by machinexa2** [comment]
Screenshot_2020-12-22_16_59_28

**Comment by machinexa2** [comment]
You are correct, bool() seems to be slow, I will revert it. However I added bool() less, while removing is not None. Here's my code
```py
from perfplot import show
from string import ascii_lowercase
from random import choice

def gen_ran(r):
    return ''.join([choice(ascii_lowercase) for i in range(r)])

def isnotnone(string):
    if string is not None:
        str(string)
    else:
        pass

def isnormal(string):
    if string:
        str(string)
    else:
        pass
def isboolnormal(string):
    if bool(string):
        str(string)
    else:
        pass
show(
        setup=lambda n: gen_ran(n),
        kernels=[
            isnormal,
            isnotnone,
            isboolnormal,
        ],
        n_range=[int(k ** 1.5) for k in range(5)],
        equality_check=None
)
```

**Comment by tiran** [comment]
I just noticed that your PR modified over 300 files. We do not accept large scale code changes because they are impossible to review and verify in a sensible amount of time. We are conservative and careful because any change can lead to a bug or change in behavior.

``if foo`` and ``if foo is not None`` have different semantic. You'd have to make a compelling case for **every** change and explain why a) the change improves the code, b) the change cannot cause a regression.

**Comment by machinexa2** [comment]
Ok I will slowly add pull requests

**Pull request closed without merging**
