### PR TITLE
bpo-37511: mmap module add OpenBSD madvise flag.

### PR DESCRIPTION
**Pull request by ghost**
Similar role as MADV_NOCORE.

https://bugs.python.org/issue37511

### CODE REVIEW

**Comment by jdemeyer** [comment]
What does `MADV_CONCEAL` do? I googled it and the only hits came from the Python bug and PR.

**Comment by jdemeyer** [comment]
And it's not listed on https://man.openbsd.org/madvise.2 so there is something fishy with this PR.

**Comment by dcarlier-afilias** [comment]
Ah I made a typo (and out of place too). Going to fix it.

**Review by jdemeyer — APPROVED** [review]
Looks good to me, but maybe add it to #14513 instead?

**Comment by dcarlier-afilias** [comment]
Ok if preferred I ll move it there.

**Pull request closed without merging**
