### PR TITLE
gh-104057: Fix direct invocation of test_module

### LINKED ISSUE #104057: Some test modules fail when run as a script
```python
 C:\Users\KIRILL-1\CLionProjects\cpython> ./python Lib/test/test_module.py
Running Debug|x64 interpreter...
.....................F..............
======================================================================
FAIL: test_module_repr_with_full_loader (__main__.ModuleTests.test_module_repr_with_full_loader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\test\test_module.py", line 238, in test_module_repr_with_full_loader
    self.assertEqual(
AssertionError: "<module 'foo' (<class '__main__.FullLoader'>)>" != "<module 'foo' (<class 'test.test_module.FullLoader'>)>"      
- <module 'foo' (<class '__main__.FullLoader'>)>
?                        ^  ^^^^^
+ <module 'foo' (<class 'test.test_module.FullLoader'>)>
?                        ^^^^^^^^^  ^^^^^


----------------------------------------------------------------------
Ran 36 tests in 0.217s

FAILED (failures=1)
```
I'll soon send a PR to fix it.

### Linked PRs
* gh-104059
* gh-104064
* gh-104069

### PR DESCRIPTION
**Pull request by Eclips4**
Fix #104057 

* Issue: gh-104057

### CODE REVIEW

**Comment by Eclips4** [comment]
cc @AlexWaygood

**Review by zware — APPROVED** [review]

**Comment by Eclips4** [comment]
Hello @zware!
Should it be backported to 3.11 branch?

**Comment by Eclips4** [comment]
Also, I found an few similiar issues in tests. 
Should I create an new issue for each of them?
I would create a one issue and just mention it in PR's.

**Comment by AlexWaygood** [comment]
Using one issue and linking multiple PRs to it would be best.

**Comment by Eclips4** [comment]
> Using one issue and linking multiple PRs to it would be best.

Thanks for your answer, Alex!
Should I create new issue, or just rename #104057 ?

**Comment by zware** [comment]
> > Using one issue and linking multiple PRs to it would be best.
> 
> Thanks for your answer, Alex! Should I create new issue, or just rename #104057 ?

I'll reopen and rename #104057.

**Comment by zware** [comment]
> Hello @zware! Should it be backported to 3.11 branch?

Apparently not :).  That line doesn't exist in 3.11; if there's a similar issue in that branch, we should just create a clean PR against 3.11.

**Pull request merged**
