### PR TITLE
gh-102628: Fix sqlite3 CLI promt text on Windows

### LINKED ISSUE #102628: Prompt text in sqlite3 CLI (new in 3.12) is Linux oriented and doesn't apply to Windows
# Bug report
The command line command `python3.12 -m sqlite3` gives a prompt stating "[...]Type ".help" for more information; type ".quit" or CTRL-D to quit."
But on Windows, the Unixism `CTRL-D` doesn't work (instead, and after adding ";" and "ENTER", it reports: "OperationalError (SQLITE_ERROR): unrecognized token: "♦"" ); `CTRL-Z` _does_ work on Windows (but not on Linux, I guess).

Request to clarify the prompt.

# Environment
- CPython: Python 3.12.0a6 (tags/v3.12.0a6:f9774e5, Mar  7 2023, 23:52:43) [MSC v.1934 64 bit (AMD64)]
- Operating system: MS Windows 3.11 Pro
- Architecture: Intel i5

### Linked PRs
* gh-103898
* gh-103945

### PR DESCRIPTION
**Pull request by erlend-aasland**
CTRL-Z is the Windows equivalent of CTRL-D.

* Issue: gh-102628

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@terryjreedy, will this work on IDLE on Windows, or does that only support CTRL-D?

**Comment by terryjreedy** [comment]
First, note that ^Z by itself does not work, which is confusing to *nix users who just learn 'Use ^Z instead of ^D".  So maybe it should say "^Z + <return>" or perhaps "^Z in a Windows console".  But experienced Windows users 'should' know about <return> -- although I managed to forget occasionally from disuse.  What do you think?

Currently, IDLE only supports ^D, which is why I have not done this yet.  About a decade ago, someone decided that IDLE should work same across platforms.  Because of this issue, I was thinking maybe ^Z<return> should have been left if possible.  I don't know if we can make ^D work in CommandPrompt. I suspect not.

The current PR is an improvement, so merge if you want, or with either alternative.

**Comment by erlend-aasland** [comment]
Is there a stable way to detect if we are running in IDLE? I've seen people check if `idlelib.run` is in `sys.modules`, but I have no idea if that is too hacky or not.

**Comment by erlend-aasland** [comment]
I landing this, as it is an improvement over the current prompt. I'm slightly reluctant to expanding the prompt as hinted, since I think it is preferable to keep it as succinct as possible.

I still think we should try to fix the IDLE-on-Windows case, though.

**Comment by erlend-aasland** [comment]
Thanks for the insight, @terryjreedy. Thanks for the report, @dutcho

**Comment by terryjreedy** [comment]
You merged after I decided to make the 'hack' official and wrote the following.  Please do the followup or ask me to.
-------------
Good question.  At least some people are checking `idlelib.run' in sys.modules` because I have recommend that  probably on python list and certainly on stackoverflow.  IDLE starts the user code execution subprocess with `python -c "__import__('idlelib.run')..." as it is the idlelib module that actually runs user code.

But what about when one starts IDLE with '-n' (no subprocess).  This is 'deprecated' and not actively maintained and tested.  (However, it has no removal date and I might reverse this.)  It happens that other modules currently import common items from run, but these should be moved to util.  To avoid breaking what I have suggested, I added a note to my draft issue for populating util that if run imports are removed, 'idlelib.run' must still be added to sys.modules.  I should say something in the IDLE doc too.

**Comment by erlend-aasland** [comment]
I merged, since you said:

> The current PR is an improvement, so merge if you want, or with either alternative.

Sorry if I misunderstood. Also, I do plan to follow up this; I'll request your review.

If the `idlelib.run` trick works in most cases, I think we should use that. The deprecated no-subprocess variant you mention seems too much of a corner case to support, in my opinion.

**Comment by erlend-aasland** [comment]
For the record, the follow-up PR is here:

- #103945

**Comment by terryjreedy** [comment]
No misunderstanding.  Your question really was a good one.  It is one thing to say on SO "Here's a hack that works now" and another to use it in the stdlib.  So I reviewed the code to make sure I understood why it works.  It turned out that the answer is completely different for the 2 different execution modes. Having it always work is trivial.  pyshell already manipulates sys.modules for another back-compatibility issue.

**Pull request merged**
