### PR TITLE
bpo-39107: Update Tcl/Tk on macOS AND Windows

### PR DESCRIPTION
**Pull request by szb512**
Updates Tcl/Tk to 3.8.10. Check issue 39107. I don't know if I have done it right, let me know if I need to make changes.

https://bugs.python.org/issue39107

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@szb512

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by terryjreedy** [comment]
The patch is trivial.  What testing have you done with what macOS version(s)?

**Comment by szb512** [comment]
Stability testing and performance testing

**Comment by ned-deily** [comment]
Thanks for the PR but we are not ready yet to move to 8.6.10 for the python.org macOS installers, the only thing this code affects.

**Comment by szb512** [comment]
Ok.

**Comment by szb512** [comment]
Do you want me to update anything else?

**Comment by ned-deily** [comment]
No need for you to do anything more on this, thanks. I will deal with it conjunction with some other necessary changes.

**Comment by szb512** [comment]
Ok.

**Comment by szb512** [comment]
Updated PR for the windows side.

**Comment by ned-deily** [comment]
Please make the Windows changes a separate PR. Which Tk versions are used on Windows and macOS are independent issues.

**Comment by szb512** [comment]
I actually don’t know how to…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by zware** [comment]
@szb512 Thanks for your interest in contributing here, but unfortunately this is not a change that can really be contributed by anyone other than @ned-deily on the Mac side and @zooba on the Windows side: the changes to the Mac installer have to be hand-tested by @ned-deily as the macOS installer producer, and Tcl and Tk have to be built, signed and checked into a separate repository by @zooba as the Windows installer producer.  As such, I think it's best that we just close this PR.

You could argue that we ought to have a more automated process here, but we currently don't :)

Thanks for trying, though, and I hope your next contribution goes more smoothly!

**Pull request closed without merging**
