### PR TITLE
gh-105431: Remove unused stuff from `test_typing.NewTypeTests`

### PR DESCRIPTION
**Pull request by sobolevn**
* Issue: gh-105431

### CODE REVIEW

**Comment by AlexWaygood** [comment]
The refleak buildbots haven't run for some reason, and I would like to make sure we get a refleak buildbot run before merging this, since it's basically a revert of #27305, which was a PR to fix refleaks in `test_typing`.

**Comment by sobolevn** [comment]
Local result:

```
~/Desktop/cpython  issue-105431 ✔                                                      2 ⚠️
» ./python.exe -m test -R 5:5 -v test_typing > /dev/null
beginning 10 repetitions
1234567890
..........
                                                                                           
~/Desktop/cpython  issue-105431 ✔                                                         
» echo $?                                               
0
```

**Comment by AlexWaygood** [comment]
> Local result:

I believe you, but I'd still like to make sure that we get the same results in CI before merging :)

**Review by JelleZijlstra — APPROVED** [review]
Looks good assuming the buildbots eventually wake up

**Review by AlexWaygood — APPROVED** [review]
The refleak buildbot results are finally in, and they look good. There's no failures in `test_typing`, just pre-existing refleaks in `test_capi`.

Thanks!

**Pull request merged**
