### PR TITLE
Replace `numbers.Real` with `Real` in numbers.rst

### PR DESCRIPTION
**Pull request by geryogam**

### CODE REVIEW

**Comment by sweeneyde** [comment]
I believe that since we're in the numbers module docs, we can assume that `Real` means `numbers.Real`, and `Complex` means `numbers.Complex`. In other words, you can assume that `from numbers import Real, Complex` has already happened.

It's similar to how the itertools recipes docs will write `chain` instead of `itertools.chain`: https://docs.python.org/3/library/itertools.html#itertools-recipes

If you'd like to discuss this more, please open an issue on bugs.python.org. Thanks!

**Comment by maggyero** [comment]
> I believe that since we're in the numbers module docs, we can assume that `Real` means `numbers.Real`, and `Complex` means `numbers.Complex`. In other words, you can assume that `from numbers import Real, Complex` has already happened.

Yes we can assume it, that is precisely why I opened this pull request, since this is the only part of the code snippet which does not make that assumption.

**Comment by sweeneyde** [comment]
Ah, sorry I misunderstood.

**Comment by JelleZijlstra** [comment]
Not sure about this, since it's supposed to be an example of how to use `numbers`, and the real code it's based on does use `numbers.Real`, not `Real`.

**Comment by maggyero** [comment]
> Not sure about this, since it's supposed to be an example of how to use `numbers`, and the real code it's based on does use `numbers.Real`, not `Real`.

The real code does not use `if isinstance(a, Rational):` but `if isinstance(a, numbers.Rational):` so the current `numbers` documentation is not even consistent with the real code:

https://github.com/python/cpython/blob/v3.10.4/Lib/fractions.py#L368-L377

**Review by MaxwellDupre — APPROVED** [review]
Looks better.

**Review by rhettinger — APPROVED** [review]

**Comment by rhettinger** [comment]
Closing and reopening to trigger the bots.

**Comment by maggyero** [comment]
Thanks for the review!

**Pull request merged**
