### PR TITLE
importlib doc: Fix required Python version of an example

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Review by aixtools — CHANGES_REQUESTED** [review]
Maybe this is self-explanatory, but it reads asif this function did not exist in Python-3.4. If it did not exist, clearly a documentation bug that needs correcting.

However, IHMO, if this is a change only because Python3-3.5 is "newer" this should not be modified without a issue number explaining why "pretending" older versions did not support this is wise.

**Comment by e-kwsm** [comment]
> Maybe this is self-explanatory, but it reads asif this function did not exist in Python-3.4

Actually `module_from_spec` is new in 3.5.

**Comment by vstinner** [comment]
@e-kwsm first created PR #10030 but there was a blocker issue on CIs. I asked him to create a new PR instead.

**Comment by matrixise** [comment]
@aixtools I suppose @e-kwsm has updated to 3.5 because 3.4 will be in EOL in 4 months.

**Comment by vstinner** [comment]
> Actually module_from_spec is new in 3.5.

Reference: https://docs.python.org/dev/library/importlib.html#importlib.util.module_from_spec

**Comment by vstinner** [comment]
> @aixtools I suppose @e-kwsm has updated to 3.5 because 3.4 will be in EOL in 4 months.

Read again the PR, the doc is just wrong. The PR fix it.

**Pull request merged**
