### PR TITLE
bpo-27679: Remove set_bitfields()

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue27679

### CODE REVIEW

**Comment by shihai1991** [comment]
Looks like nobody need this `set_bitfields()` function.
If I was wrong , pls help me close this PR, thanks.

**Review by eamanu — APPROVED** [review]
LGTM

**Comment by aeros167** [comment]
> Looks like nobody need this `set_bitfields()` function.
> If I was wrong , pls help me close this PR, thanks.

In order to close a PR, simply enter in a final comment such as "Closing PR because ..." and instead of selecting the `Comment` option, choose the option to the left, `Close and comment`.

**Comment by shihai1991** [comment]
> > Looks like nobody need this `set_bitfields()` function.
> > If I was wrong , pls help me close this PR, thanks.
> 
> In order to close a PR, simply enter in a final comment such as "Closing PR because ..." and instead of selecting the `Comment` option, choose the option to the left, `Close and comment`.

Thanks, got it;)

**Review by aeros — COMMENTED** [review]
In a search of the cpython repository for `set_bitfields`, this is the only occurrence. This is the initial message in the commit which first created the function 12 years ago: "Make _ctypes_test.c compile on Windows" without any further details or documentation. 

If the integrations tests are still fully passing without it and it is not used in any other location, as far as I can tell, it can be safely removed. However, since this is not at all my area of expertise, I don't want to explicitly approve this PR, in case this function is still useful in some way that I'm unaware of. @vstinner would probably have a more definitive answer.

**Comment by vstinner** [comment]
As soon as tests still pass, the change LGTM :-) Thanks.

**Pull request merged**
