### PR TITLE
gh-99908 Update 'odds and ends' `class` documentation

### PR DESCRIPTION
**Pull request by JosephSBoyle**
Note: Closed the last PR due to issues with the CLA bot and modified commit authorship (incorrect email was used for my commit).

Modernizes an example in the 'odds and ends'  section of the documentation about classes.

* Issue: gh-99908

### CODE REVIEW

**Comment by JosephSBoyle** [comment]
image

I don't understand why the CLA bot thinks that 'joe.boyle@blackcowtech.uk' needs to sign; I can't see that email in the git history! 

Can we ignore it?

**Comment by AlexWaygood** [comment]
Unfortunately, the CLA check is "required" in our CI, meaning that we are physically incapable of merging if the check fails. You can see that the "squash and merge" button just isn't available to me on this PR:

8FA85DBB-D79B-4EED-B66D-29B347CF8502

**Comment by JosephSBoyle** [comment]
@AlexWaygood Okay, understood, I'll make a figure it out and let you know when it's sorted!

:vulcan_salute:

**Comment by AlexWaygood** [comment]
> image
> 
> I don't understand why the CLA bot thinks that '[joe.boyle@blackcowtech.uk](mailto:joe.boyle@blackcowtech.uk)' needs to sign; I can't see that email in the git history!
> 
> Can we ignore it?

Perhaps @ambv can help with this, as one of the authors of the CLA bot :)

**Comment by AlexWaygood** [comment]
Closing in favour of #100499

**Comment by CAM-Gerlach** [comment]
Just to note, if I pull this branch and use `git log` or `git show -q de102b1`, I get the `joe.boyle@blackcowtech.uk` address as the author, and the same if I [check it via the GitHub API](https://api.github.com/repos/python/cpython/pulls/100498/commits) (which is what the bot uses). Therefore, the bot operating exactly as it should, as the actual commit pushed to the PR branch has the author set as `joe.boyle@blackcowtech.uk`.

image

If we look at your screenshot, we can see what is going on—the commit in question is marked `replaced`, which means the commit being shown locally is not the actual original commit de102b1 , but rather a modified version only visible to you locally. This means either you or a tool you used performed a `git replace` operation on the commit, and that presumably changed the author email. However, that is not visible external to your local repo, at least without special steps. If you run `git --no-replace-objects log`, you'll see the actual original commit that was pushed here. For an in depth look at how `git replace` works, [see this SO answer](https://stackoverflow.com/a/70118599).

Presumably, in your revised PR, you amended/squashed the original commit(s), which created an actual new commit that could then be pushed here.

**Pull request closed without merging**
