### PR TITLE
bpo-42238: [doc]: Hide false positive in make suspicious.

### PR DESCRIPTION
**Pull request by JulienPalard**
https://bugs.python.org/issue42238

### CODE REVIEW

**Comment by JulienPalard** [comment]
Original PR (https://github.com/python/cpython/pull/29389) has been backported to 3.9 and 3.10 so I'll backport this to 3.9 and 3.10 too.

**Comment by AlexWaygood** [comment]
> Original PR (#29389) has been backported to 3.9 and 3.10 so I'll backport this to 3.9 and 3.10 too.

I think @ambv already applied this to 3.9/3.10:
- https://github.com/python/cpython/pull/29619/commits/dc23aed922bd79c32b948cb9b1f60d6d909d9fa7
- https://github.com/python/cpython/pull/29620/commits/0111c5af9aa67edd5b885afe139572ebb57f3da9

(Sorry for the bother — thanks for fixing!)

**Comment by ambv** [comment]
@JulienPalard, since we're no longer running `make suspicious` in CI for `main` per your own change (GH-26575), should we just stop caring about `make suspicious` at all?

**Comment by JulienPalard** [comment]
> @JulienPalard, since we're no longer running `make suspicious` in CI for `main` per your own change ([GH-26575](https://github.com/python/cpython/pull/26575)), should we just stop caring about `make suspicious` at all?

Soon, yes. The idea is I'm tracking closely `make suspicious` in bpo-42238 to see if there's true positives that I can implement in `rstlint.py`. It allowed me to add a few new things in rstlint:

- bda69abe849b37467350d3750ae24d356230c940
- fbf10080bb369cfef1f230c2cd5135a558b242d5
- 01331f1a3cf86fd308e9a134bb867bf01fb191f5
- b9735420aa8ecd2555fe3dc000863bc50487334b

and we do ensure rstlint in the CI as it make no false positives.

So « soon » rstlint should catch all the true positives of make suspicious, leaving only false positives for `make suspicious`.

This day I'll just drop it, and really stop caring about it.

Up to this day I prefer having an up-to-date `susp-ignored.csv`, so I can easily monitor new alerts.

**Comment by JulienPalard** [comment]
(But I only watch master so backporting can be ignored, yes)

**Comment by AlexWaygood** [comment]
> and we do ensure rstlint in the CI as it make no false positives.

Arguably rstlint [did have a few false positives in this PR ](https://github.com/python/cpython/pull/29389#issuecomment-964294948) 🙂 (but maybe I'm just too backtick-happy!)

**Comment by JulienPalard** [comment]
> Arguably rstlint [did have a few false positives in this PR ](https://github.com/python/cpython/pull/29389#issuecomment-964294948) slightly_smiling_face (but maybe I'm just too backtick-happy!)

This is a really interesting information, TIL, thanks! I'll have to look at it :D

**Pull request merged**
