### PR TITLE
bpo-39481: Generic alias to os.DirEntry

### PR DESCRIPTION
**Pull request by isidentical**
Add generic alias to DirEntry

https://bugs.python.org/issue39481

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
LG, but I don't know why the tests are failing.

**Comment by isidentical** [comment]
This is a [known failure](https://bugs.python.org/issue40188)

**Comment by gvanrossum** [comment]
Dang. Azure does not seem to be a happy place. I guess you could try closing and reopening the PR to retry the tests, hopefully then they'll work so we can merge.

**Comment by isidentical** [comment]
@gvanrossum ready to go

**Comment by gvanrossum** [comment]
Here you go! If you want to do more, please coordinate with @ethanhs.

**Pull request merged**
