### PR TITLE
bpo-40334: Allow to run make regen-pegen without distutils

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue40334

### CODE REVIEW

**Comment by pablogsal** [comment]
CC: @lysnikolaou

**Comment by pablogsal** [comment]
Sadly, we cannot support < Python3.8 because the walrus operator is used in the generated parser :(

**Comment by pablogsal** [comment]
Sadly, we cannot support < Python3.8 because the walrus operator is used in the generated meta-parser :(

@serhiy-storchaka Would you like to skip the pegen regeneration if PYTHON_FOR_REGEN is not at least 3.8? Or maybe crash with a better error message?

**Review by lysnikolaou — APPROVED** [review]

**Comment by lysnikolaou** [comment]
LG.

**Comment by pablogsal** [comment]
There isn't much that we can do without a considerable redesign to allow running this with something lower than Python3.8 as the generated parser for Python heavily uses the `:=` operator so I will land this so the rest of the reported problems are fixed and a clear error message is emitted in case you run with something lower than 3.8.

**Pull request merged**
