### PR TITLE
bpo-33164: blake2: Fix Coverity scan

### PR DESCRIPTION
**Pull request by methane**
https://bugs.python.org/issue33164

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by stratakis** [comment]
Thanks for the fix. Should also the 3.8 backport label be added, as the blake2 module was updated on 3.8?

**Comment by methane** [comment]
> Thanks for the fix. Should also the 3.8 backport label be added, as the blake2 module was updated on 3.8?

You are right. I thought Python 3.8 become security-fix only mode, but it was wrong. There is one more bugfix release for 3.8.

**Comment by tiran** [comment]
Please respect code owner responsibility and give me at least a change to review and comment on PRs that affect my area of expertise. I'm not happy that you pushed the PR given me the opportunity to very it.

**Comment by methane** [comment]
I'm sorry about that.

This pull request is just resurrecting your change that I lost by mistake. That's why I merge this without waiting you.

**Pull request merged**
