### PR TITLE
bpo-23578: Show which offset raise error when using struct.pack

### PR DESCRIPTION
**Pull request by louisom**
Adding PyErr_SetString and PyErr_Format wrapper, with a global offset
variable to handle this.

```
struct.pack('!h', 0x8FFFF)
Traceback (most recent call last):
  File "tests.py", line 5, in <module>
    struct.pack('!h', 0x8FFFF)
struct.error: Raise at offset 1, 'h' format requires -32768 <= number <= 32767
```

### CODE REVIEW

**Comment by rhettinger** [comment]
This looks like a reasonable improvement.

**Comment by louisom** [comment]
@rhettinger I'm not sure about the global variable. Is there any way to test if global variable has the defect when using threads?

**Comment by louisom** [comment]
@serhiy-storchaka I removed the global offset variable, and add a new parameter `pos` to corresponding function. Not sure this kind of big change is better than global variable or not.

Could you help me review this? Thanks.

**Review by auvipy — CHANGES_REQUESTED** [review]
plz re base

**Comment by csabella** [comment]
This change is from an unknown repository and this GitHub account is no longer active.  I'm going to close this PR so that another one could be opened to replace it.

**Pull request closed without merging**
