### PR TITLE
Update README file extensions to .rst

### PR DESCRIPTION
**Pull request by taycaldwell**
Updated the file extensions of the README files in the repo to have the .rst file extension so they are rendered properly on GitHub.

### CODE REVIEW

**Comment by ghost** [comment]
Not all of them should be a simple rename, see if you can bring .rst formatting in the mix.

**Comment by refi64** [comment]
If you want, you can also use some of the stuff I did in #5

**Comment by taycaldwell** [comment]
@rogersachan Files have now been fixed and updated with proper .rst formatting with respect to how GitHub renders them. A lot of the existing files used proper syntax and looked fine. For those files I just added the file extension so they could be rendered properly.

The biggest formatting changes were applied to the PCBuild README.

**Comment by brettcannon** [comment]
Would it be possible to break this PR up into separate ones per file? I know that might be a pain but it would make it easier to review since e.g. I don't know if @zooba and @zware actually want to the READMEs related to Windows builds to change (plus you stripped out Windows line endings in those files).

**Comment by brettcannon** [comment]
GH-104 renames Doc/README.rst as well.

**Comment by taycaldwell** [comment]
@brettcannon I'm fine with breaking it down into multiple PRs.

**Comment by zooba** [comment]
I'm not concerned about this one (though the other readme "fix" broke our release builds...). Ideally we'd have a `.txt` version there too so that it's easy to read the file from a clone/tarball, but if the GitHub masses would prefer .rst then I'd rather only have one copy. It's hard enough to keep it up to date already...

**Comment by brettcannon** [comment]
OK, then let's do this file-by-file as there's so many PRs flying by that are grabbing this sort of low-hanging fruit it's probably best to do this slowly and methodically so that @taycaldwell doesn't have to constantly rebase because someone did another README.

**Pull request closed without merging**
