### PR TITLE
bpo-40773: Fix rendering for 'retval' on the pdb page

### PR DESCRIPTION
**Pull request by arisaka97**
https://bugs.python.org/issue40773

Automerge-Triggered-By: @merwok

### CODE REVIEW

**Comment by remilapeyre** [comment]
Hi @arisaka97, it looks like you are having issues with GitHub PRs, is something wrong?

**Review by remilapeyre — APPROVED** [review]

**Comment by arisaka97** [comment]
I am sorry that I confused the title of PR with the content of commit. When I found that the commit could not be modified, I  deleted the previous PR.

**Comment by arisaka97** [comment]
I am very sorry for the inconvenience.

**Comment by remilapeyre** [comment]
> I am very sorry for the inconvenience.

It's not an issue at all, I just wanted to let you know that when merging, all the commits will get squashed and the code developer will have the possibility to change the commit message then. So it's not really an issue if you made a typo or an error :)

**Comment by arisaka97** [comment]
> > I am very sorry for the inconvenience.
> 
> 
> 
> It's not an issue at all, I just wanted to let you know that when merging, all the commits will get squashed and the code developer will have the possibility to change the commit message then. So it's not really an issue if you made a typo or an error :)


Thank you for your patience :)

**Comment by merwok** [comment]
Is the problem also present in 3.7 and 3.8 docs?

**Review by merwok — APPROVED** [review]

**Pull request merged**
