### PR TITLE
bpo-33609: Add document for dict order

### PR DESCRIPTION
**Pull request by methane**
https://bugs.python.org/issue33609

### CODE REVIEW

**Review by 1st1 — COMMENTED** [review]
What about deletion? Does it scramble the order or does it preserve it? What are the guarantees?

**Comment by methane** [comment]
"Preserves insertion order" is guaranteed for deletion too.

**Comment by 1st1** [comment]
Can you clarify that in the docs? ideally with a 3-4 lines example.

**Comment by methane** [comment]
"Scramble on deletion" was implementation detail of original Raymond's compact dict.
So adding sentence like "Insertion order is preserved after deletion" may confuse readers.

Instead, I added one sentence about "insert after deletion" case.  It had example already.
With this example, reader will understand "preserve insertion order after deletion" clearly.

**Comment by ned-deily** [comment]
@1st1 Are you OK with the revised wording?

**Comment by 1st1** [comment]
Yes, I think the updated text is great. Thanks, @methane!

**Pull request merged**
