### PR TITLE
bpo-20180: Use argument clinic for dict.pop() and dict.popitem()

### PR DESCRIPTION
**Pull request by methane**
https://bugs.python.org/issue20180

### CODE REVIEW

**Comment by tirkarthi** [comment]
Does this provide performance improvement for `dict.pop` ? I am using a non-PGO build for benchmarking.

```
➜  cpython git:(master) ./python.exe -m timeit -s 'd = {"a": 1}' 'd.pop("a", None)'
2000000 loops, best of 5: 125 nsec per loop
➜  cpython git:(master) ./python.exe -m timeit -s 'd = {"a": 1}' 'd.pop("a", None)'
2000000 loops, best of 5: 127 nsec per loop
➜  cpython git:(master) ./python.exe -m timeit -s 'd = {"a": 1}' 'd.pop("a", None)'
2000000 loops, best of 5: 127 nsec per loop
```

```
➜  cpython git:(pr_12792) ./python.exe -m timeit -s 'd = {"a": 1}' 'd.pop("a", None)'
5000000 loops, best of 5: 82.7 nsec per loop
➜  cpython git:(pr_12792) ./python.exe -m timeit -s 'd = {"a": 1}' 'd.pop("a", None)'
5000000 loops, best of 5: 80.3 nsec per loop
➜  cpython git:(pr_12792) ./python.exe -m timeit -s 'd = {"a": 1}' 'd.pop("a", None)'
5000000 loops, best of 5: 74.5 nsec per loop
```

**Comment by methane** [comment]
Yes.  Calling convention is changed from METH_VARARGS to METH_FASTCALL.

**Comment by tirkarthi** [comment]
Is it worth adding a NEWS entry for such speedups since this is a considerable one reducing 120ns to 80ns.

**Comment by methane** [comment]
I am not sure about it.

Some methods changed from METH_VARARGS to METH_FASTCALL without NEWS entry.
For example, #9560.

**Comment by tirkarthi** [comment]
My rationale towards adding them is that unless someones follows CPython commits these optimizations are hard to find. Adding them to changelog might encourage users and give better outlook on how CPython is getting faster, given that it's `dict.pop` which is slightly more common. But it's your call on adding a NEWS entry.

**Pull request merged**
