### PR TITLE
gh-93991: Use boolean instead of 0/1 for condition check

### PR DESCRIPTION
**Pull request by leikdga**
# gh-93991: Use boolean instead of 0/1 for condition check

Automerge-Triggered-By: GH:alex

### CODE REVIEW

**Review by teddyoweh — APPROVED** [review]

**Review by teddyoweh — APPROVED** [review]

**Review by corona10 — APPROVED** [review]
Nice clean-up, please remove NEWS.d 
It will be not needed.

**Comment by leizhanghello** [comment]
> Nice clean-up, please remove NEWS.d It will be not needed.

Removed NEWS.d. Thanks!

**Review by ghost — APPROVED** [review]
The disassembly is identical
```
>>> stmt_true = "if True: pass"
>>> stmt_1 = "if 1: pass"
>>> from dis import dis
>>> dis(stmt_true)
              0 RESUME                   0

  1           2 LOAD_CONST               1 (None)
              4 RETURN_VALUE
>>> dis(stmt_1)
              0 RESUME                   0

  1           2 LOAD_CONST               1 (None)
              4 RETURN_VALUE
```
IMO, it does improve readability though.

**Review by rhettinger — APPROVED** [review]

**Comment by leizhanghello** [comment]
> The disassembly is identical
> 
> ```
> >>> stmt_true = "if True: pass"
> >>> stmt_1 = "if 1: pass"
> >>> from dis import dis
> >>> dis(stmt_true)
>               0 RESUME                   0
> 
>   1           2 LOAD_CONST               1 (None)
>               4 RETURN_VALUE
> >>> dis(stmt_1)
>               0 RESUME                   0
> 
>   1           2 LOAD_CONST               1 (None)
>               4 RETURN_VALUE
> ```
> 
> IMO, it does improve readability though.


Thanks @oda-gitso for replying. I would like to clarify a little more about speed difference I mentioned in the [gh-93991](https://github.com/python/cpython/issues/93991#issue-1275843092) .

First, here you showed that the bytecode is the same for `if 1` and `if True`. But this is because Python interpreter does some optimization over constant expressions and statements. It is similar to [constant folding](https://en.wikipedia.org/wiki/Constant_folding) in compiler.

One more example to show this:

```python3
>>> import dis

>>> stmt_true = "if 231 - 50: print(70)"
>>> dis.dis(stmt_true)
  1           0 LOAD_NAME                0 (print)
              2 LOAD_CONST               1 (70)
              4 CALL_FUNCTION            1
              6 POP_TOP
              8 LOAD_CONST               2 (None)
             10 RETURN_VALUE

>>> stmt_false = "if 231 - 50 - 181: print(71)"
>>> dis.dis(stmt_false)
  1           0 LOAD_CONST               2 (None)
              2 RETURN_VALUE
``` 

One caveat is, Python's constant folding is not very powerful. Here is an example:

```python3
>>> import dis

>>> stmt = "a = 1\nif a - 1: print(72)"
>>> dis.dis(stmt)
  1           0 LOAD_CONST               0 (1)
              2 STORE_NAME               0 (a)

  2           4 LOAD_NAME                0 (a)
              6 LOAD_CONST               0 (1)
              8 BINARY_SUBTRACT
             10 POP_JUMP_IF_FALSE       12 (to 24)
             12 LOAD_NAME                1 (print)
             14 LOAD_CONST               1 (72)
             16 CALL_FUNCTION            1
             18 POP_TOP
             20 LOAD_CONST               2 (None)
             22 RETURN_VALUE
        >>   24 LOAD_CONST               2 (None)
             26 RETURN_VALUE
```

In our code, the value of the `ok` variable cannot be determined until execution time, so constant fold can not be applied. 


This is part of the bytecode of [filecmp.py](https://github.com/python/cpython/blob/8e0897814109765a9e463676413fff016875217b/Lib/filecmp.py) file (line 172):
```python3
172     >>  140 LOAD_FAST                4 (ok)
            142 POP_JUMP_IF_FALSE      126 (to 252)
```

Python will evaluate the `POP_JUMP_IF_FALSE` operator on `ok` variable to get a `True` or `False`.

The implementation is [here](https://github.com/python/cpython/blob/8e0897814109765a9e463676413fff016875217b/Python/compile.c#L8988). it calls `PyObject_IsTrue` to check whether a value (e.g., `True`, `5`, `'hello'`) should be treated as boolean `True` or `False`.

And if we go to check the [definition](https://github.com/python/cpython/blob/8e0897814109765a9e463676413fff016875217b/Objects/object.c#L1485) of `PyObject_IsTrue`, we can see that, if first check whether the value is strictly equal to `True` (line 1489). For value `1`, we need to convert it to boolean first (line 1496). This is why I say that `a = True; if a: pass` is faster than `a = 1; if a: pass`. (And of course, the difference is very very small.)

Thanks for your comment again! If there is any question, please let me know.

**Comment by oda-gitso** [comment]
Thanks for the comment @leizhanghello. 

> But this is because Python interpreter does some optimization over constant expressions and statements. 

Yes, I assumed as much.

-----

The only claim I was making is that the disassembly of `if 1: pass` versus `if True: pass` is identical. It is also true that the disassembly of `if a: pass` where `a` either refers to `True` or `1` is also identical (ignoring the assignment to `a`), which I probably should have made more explicit, though I chose not to pollute the comment.  

I was not making any claims about the underlying differences of `POP_JUMP_IF_FALSE` or friends. I was just trying to emit potentially relevant information should one wish to explore further.

I agree with all of your changes and am impressed by your level of detail.

**Comment by leizhanghello** [comment]
Got it. Thanks @oda-gitso so much for your nice and patient explanation! This is my first time contributing to such a great repository. I tried to explain as much as I can (although this may pollute the comment a little 😄) to avoid any possible mistakes.

**Pull request merged**
