### PR TITLE
bpo-45843: Optimize constant comparisons/contains

### PR DESCRIPTION
**Pull request by thatbirdguythatuknownot**
https://bugs.python.org/issue45843

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Thanks for the really impressive compiler work.

I hope I understand the code correctly. It's effectively doing constant folding for comparison expressions where both sides are consts right? So `1<2` goes from
```
LOAD_CONST 1
LOAD_CONST 2
COMPARE_OP 0
```
to
```
LOAD_CONST 0 (True)
```
My question is how common do people write things like `1<2` in production code? Constant folding for things like `10*64` make sense for readability, but I don't see how `1<2` is useful.

**Comment by markshannon** [comment]
I was surprised that this isn't handled by the AST optimizer.
In fact there is "to do" for precisely this: 
https://github.com/python/cpython/blob/main/Python/ast_opt.c#L621

@thatbirdguythatuknownot could you implement this in the AST optimizer?

**Comment by markshannon** [comment]
I suspect that no one would write `if 1 < 2:`, but there is an expectation that Python will fold constants and that the body of
```Python
if 0:
     sensitive_internal_debugging_code
```
is removed from the bytecode. 

So this is probably worth doing from a consistency point of view, even if it makes no difference in terms of performance.

**Comment by thatbirdguythatuknownot** [comment]
> I was surprised that this isn't handled by the AST optimizer. In fact there is "to do" for precisely this: https://github.com/python/cpython/blob/main/Python/ast_opt.c#L621
> 
> @thatbirdguythatuknownot could you implement this in the AST optimizer?
@markshannon should I keep the changes made in `Python/compile.c`?

**Comment by thatbirdguythatuknownot** [comment]
> I suspect that no one would write `if 1 < 2:`, but there is an expectation that Python will fold constants and that the body of
> 
> ```python
> if 0:
>      sensitive_internal_debugging_code
> ```
> 
> is removed from the bytecode.
> 
> So this is probably worth doing from a consistency point of view, even if it makes no difference in terms of performance.

@markshannon Should I revert the changes made to `Python/compiler.c`?

**Comment by markshannon** [comment]
I don't understand why you need all the extra code.

All you need to do in `fold_compare` is check that both sides of the comparisons are constants and perform the comparison.
See `fold_subscr` for an example.

**Comment by thatbirdguythatuknownot** [comment]
> I don't understand why you need all the extra code.
> 
> All you need to do in `fold_compare` is check that both sides of the comparisons are constants and perform the comparison. See `fold_subscr` for an example.

@markshannon Do I `return` if there is a comparison that does not have a constant?

**Comment by isidentical** [comment]
Closing since this issue got rejected on the bug tracker.

**Pull request closed without merging**
