### PR TITLE
bpo-39191: Fix RuntimeWarning in asyncio test

### PR DESCRIPTION
**Pull request by asvetlov**
https://bugs.python.org/issue39191

Automerge-Triggered-By: @asvetlov

### CODE REVIEW

**Review by tirkarthi — COMMENTED** [review]
Slightly offtopic, the last patch that caused this warning had a typo `_check_runnung` which is trivial and can be fixed with this PR.

**Comment by asvetlov** [comment]
You are right. I've fixed the typo.

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Comment by asvetlov** [comment]
Thanks for the review, @tirkarthi

**Pull request merged**
