### PR TITLE
bpo-39994: Removed redundant code.

### PR DESCRIPTION
**Pull request by ghost**
Since ```self._dispatch``` has ```dict.__repr__: self._pprint_dict``` the ```elif``` block is not needed.

https://bugs.python.org/issue39994

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@palakjha

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by aeros — COMMENTED** [review]
Thanks for the PR @palakjha and welcome! 

This PR will require a signed CLA prior to merging, since it involves a code change (even if it's just removing 6 lines). After 24-48 hours of signing the CLA, you can check the status via the [CLA assistant](https://check-python-cla.herokuapp.com/). If it detects that your CLA has been signed, the label will update from `CLA not signed` to `CLA signed`.

Let me know if you have any questions. :)

**Comment by iritkatriel** [comment]
This change makes a difference in semantics (perhaps a good one) in this case:

```
import pprint

class MyDict(dict):
    def __repr__(self):
        return 'I do my own thing'*50


if __name__ == '__main__':
    d=MyDict()
    for i in range(50):
        d['a%s'%i] = i

    pprint.pprint(d)
```

Before the change MyDict.__repr__ is ignored and the dict contents are printed. After the change it prints "I do my own thing" 50 times.

**Review by iritkatriel — CHANGES_REQUESTED** [review]
Since this causes a change in behavior it needs to be submitted with an appropriate title/commit message, test and documentation update.

**Comment by ericvsmith** [comment]
Since the original author has vanished, I'm going to close this and note that I did so on the bpo.

**Pull request closed without merging**
