### PR TITLE
bpo-43869: Improve epoch docs

### PR DESCRIPTION
**Pull request by miguendes**
https://bugs.python.org/issue43869

### CODE REVIEW

**Review by hugovk — APPROVED** [review]
Looks good, as @vstinner wrote in https://bugs.python.org/issue43869#msg391216:

> time.time doc says "On Windows and most Unix systems, the epoch is January 1, 1970, 00:00:00 (UTC)" 
> 
> The epoch doc says "For Unix, the epoch is January 1, 1970, 00:00:00 (UTC)".
> 
> At least, the epoch doc can be completed to also mention that it's the same on Windows.

**Review by ofek — APPROVED** [review]

**Comment by vstinner** [comment]
Right, it's consistent with: https://docs.python.org/dev/library/time.html#time.time

"On Windows and most Unix systems, the epoch is January 1, 1970, 00:00:00 (UTC) and leap seconds are not counted towards the time in seconds since the epoch."

**Comment by vstinner** [comment]
The CI failed. I closed/reopend the CI to trigger new CI jobs. Well, it's an old PR, maybe it contains outside CI config. We will see how it goes ;-)

**Comment by vstinner** [comment]
Please have a look at my follow-up PR #30664.

**Pull request merged**
