### PR TITLE
gh-93172: Remove unnecessary if in binascii_a2b_qp_impl() from Modules/binascii.c

### PR DESCRIPTION
**Pull request by ghost**
Issue #93172.

Removed an unnecessary ``if`` in ``binascii_a2b_qp_impl()`` from ``Modules/binascii.c``.

### CODE REVIEW

**Comment by sweeneyde** [comment]
It looks like there's a second occurrence of this elsewhere in the file. Would you mind changing that as well in this PR?

**Comment by methane** [comment]
NEWS file is not needed for small changes that is invisible to users.

**Comment by oda-gitso** [comment]
> It looks like there's a second occurrence of this elsewhere in the file. Would you mind changing that as well in this PR?

@sweeneyde Sure! 

> NEWS file is not needed for small changes that is invisible to users.

@methane Apologies. I have deleted the news entry.

**Review by methane — APPROVED** [review]

**Comment by oda-gitso** [comment]
Thanks @sweeneyde @methane!

**Pull request merged**
