### PR TITLE
bpo-29704: Fix asyncio.SubprocessStreamProtocol closing

### PR DESCRIPTION
**Pull request by sethmlarson**
Was told by @1st1 to open this PR here from python/asyncio. See the original Pull Request for discussion and review: https://github.com/python/asyncio/pull/485

### CODE REVIEW

**Comment by 1st1** [comment]
LGTM. @asvetlov @fafhrd91 want to take a look too?

**Comment by SethMichaelLarson** [comment]
One moment, adding the test as well.

**Comment by 1st1** [comment]
@SethMichaelLarson Do we have an open issue for this on bugs.python.org? If not can you create one?

**Comment by sethmlarson** [comment]
We do not, I will create one now.

**Comment by sethmlarson** [comment]
I created an issue with @BotoX comments and links to issue on python/asyncio http://bugs.python.org/issue29704

**Comment by 1st1** [comment]
Please add a `Misc/NEWS` entry (to the top of Library section for 3.7.0 alpha)

**Comment by sethmlarson** [comment]
@1st1 Done, is that entry acceptable?

**Comment by 1st1** [comment]
Yep. Looking good now.

**Comment by 1st1** [comment]
This PR is merged, however, I didn't see that it had some trailing whitespace. Please make sure that your editor strips trailing whitespace.

**Comment by 1st1** [comment]
Note: tested this PR with all uvloop functional subprocess tests, everything looks alright.

**Comment by sethmlarson** [comment]
@1st1 Sorry about that! My fault for not noticing. GitHub's web editor doesn't strip whitespace like PyCharm does. :) I'm glad it also works in uvloop, I should probably test asyncio changes with uvloop as well first before submitting.

**Comment by 1st1** [comment]
> I'm glad it also works in uvloop, I should probably test asyncio changes with uvloop as well first before submitting.

It's not so much about uvloop as it is about some unittests there that test both uvloop & vanilla asyncio. I plan to port some of those tests to CPython to increase coverage.

**Comment by 1st1** [comment]
Anyways, thanks for the contribution!

**Comment by sethmlarson** [comment]
@1st1 Would be a good idea to port them, I've got some tests for selectors2 that don't occur in Python's stdlib selectors that might be considered good as well for unique situations.

**Comment by 1st1** [comment]
>  I've got some tests for selectors2 that don't occur in Python's stdlib selectors that might be considered good as well for unique situations.

Please open a PR with those tests, selectors module is very important. For an extra benefit, you'll see your tests running on the full CPython buildbots matrix.

**Comment by sethmlarson** [comment]
Will do, might have to experiment with different Python versions, PEP 475 really split the behavior for anything syscall-related in Python.

**Comment by sethmlarson** [comment]
What is the protocol for tests that behave differently (skip?) on different Python versions? Would they only be put in the version where they should be or is it normal to have tests that only run on Python 3.5+, for example.

**Comment by vstinner** [comment]
> Will do, might have to experiment with different Python versions, PEP 475
really split the behavior for anything syscall-related in Python.

I lost track of asyncio. PEP 475 was implemented in Python 3.5. Python 3.4
doesn't accept bugfixes anymore. Why do you want to test different Python
versions? Is asyncio on Python 3.3 or 3.4 still a thing?

**Comment by sethmlarson** [comment]
@haypo Ah 3.4 is off bug-fix. Makes that a lot easier! :) Disregard my above comment then.
The tests would have to do with selectors.

**Comment by vstinner** [comment]
We try to keep this table up to date:
https://docs.python.org/devguide/#status-of-python-branches

**Comment by fafhrd91** [comment]
@haypo some rasberypi dev still on 3.4.2
https://home-assistant.io this is still on 3.4.2
I had to ship backported cookies module with aiohttp.

**Comment by vstinner** [comment]
> @haypo some rasberypi dev still on 3.4.2
> https://home-assistant.io this is still on 3.4.2
> I had to ship backported cookies module with aiohttp.

You are on the CPython project. There is also a
http://github.com/python/asyncio project because there is no more
release on http://pypi.python.org/pypi/asyncio/ since 2 years. I
understand that asyncio doesn't evolve anymore on Python 3.4. Upgrade
or backport yourself, no?

**Pull request merged**
