### PR TITLE
gh-103247: add `tearDown` to `test_loader` and clear module cache

### PR DESCRIPTION
**Pull request by sunmy2019**
* Issue: gh-103247

### CODE REVIEW

**Comment by itamaro** [comment]
I was able to repro the reported failure on main, and confirmed this PR fixes it.

I'm not sure adding the `tearDown` is helpful though.
the `uncache` context manager uncaches the names both on enter and exit, and perform some checks on the names - two things that the `tearDown` doesn't perform.
while having the `tearDown` may prevent some failures (like this one), its existence might indicate that the `uncache` context manager is not really needed, which is not necessarily true (I don't know if it matters in practice, just noting the behavior differences).

in any case, I also confirmed that just adding the context manager to `test_try_registration` without the `tearDown` fixes the issue.

**Comment by sunmy2019** [comment]
> I'm not sure adding the `tearDown` is helpful though.

Adding this is proposed by @FFY00. And I am neutral about it.

**Comment by sunmy2019** [comment]
> I'm not sure adding the `tearDown` is helpful though.

I think you are correct, adding both is unnecessary.

`tearDown` method and `util.uncache` provides duplicate function. And `util.uncache(name)` provides more flexibility than the `tearDown` method.

`tearDown` here is a safety net.

**Review by itamaro — APPROVED** [review]
LGTM!

**Review by brettcannon — APPROVED** [review]

**Pull request merged**
