### PR TITLE
gh-108777: Split _PyTime tests from _testinternalcapi.c

### PR DESCRIPTION
**Pull request by colesbury**
This moves the 12 `_PyTime` related tests to their own file in `Modules/_testinternalcapi/`.

* Issue: gh-108777

### CODE REVIEW

**Review by erlend-aasland — APPROVED** [review]

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by vstinner** [comment]
Nice change.

**Comment by sobolevn** [comment]
Do you have any objections on backporting this PR? Because next PRs like https://github.com/python/cpython/pull/110630 are impossible to backport :(

**Comment by vstinner** [comment]
Sure, the change can be backported. Do you want to backport it to 3.12 and 3.11?

**Comment by sobolevn** [comment]
I am not sure about the CAPI semantics, but the test structure would be nice to have in both 3.11 and 3.12

**Pull request merged**
