### PR TITLE
GH-96458: Statically initialize utf8 representation of static strings

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-96458

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
`_PyUnicode_LATIN1_INIT` is wrong name. You can statically initialize utf8 representation only in ASCII strings.

**Review by gvanrossum — APPROVED** [review]
I'd like @ericsnowcurrently to review this too.

**Comment by markshannon** [comment]
Are you generating utf8 strings separately from the ascii string, or do they share the same data?

**Comment by gvanrossum** [comment]
> Are you generating utf8 strings separately from the ascii string, or do they share the same data?

The utf8 cache strings are only ever created and used for non-ASCII strings (i.e. at least one character is 128 or larger). The unicode string object is smart enough to know that for pure ASCII strings the utf8 is identical so it doesn't bother creating or using the utf8 cache value.

This PR only generates utf8 data for exactly 6 strings in deepfreeze.c. I'm sure those are the ones with at least non-ASCII character.

In order to see a leak one would have to request the utf8 encoding of at least one of those 6 strings.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Comment by ericsnowcurrently** [comment]
> `_PyUnicode_LATIN1_INIT` is wrong name. You can statically initialize utf8 representation only in ASCII strings.

What do you mean?  Keep in mind that the macro is used exclusively to statically initialize latin-1 strings.

**Comment by gvanrossum** [comment]
> > `_PyUnicode_LATIN1_INIT` is wrong name. You can statically initialize utf8 representation only in ASCII strings.
> 
> What do you mean? Keep in mind that the macro is used exclusively to statically initialize latin-1 strings.

Indeed -- in fact the macro is only used in pycore_runtime_init_generated.h (a generated file :-) to initialize the `_latin1` field of unicode objects. So the name seems eminently reasonable.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Sorry, now I see that `_PyUnicode_LATIN1_INIT` takes a new argument.

**Pull request merged**
