### PR TITLE
bpo-31440: Changed default module search path for windows

### PR DESCRIPTION
**Pull request by ghost**
https://bugs.python.org/issue31440

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by zhangyangyu** [comment]
Thanks for your contribution @gaurav6696. But to complete the patch we need you to sign the CLA and for this issue a NEWS entry is also needed. And please watch the discussion in bpo. :-)

**Comment by vstinner** [comment]
I added the "skip news" label since I don't consider that it's worth it to document such minor fix in the documentation (python3 --help).

**Comment by ghost** [comment]
Thanks

**Review by tiran — APPROVED** [review]
LGTM

**Pull request merged**
