### PR TITLE
[2.7] Docs: fix some wrong words (GH-6987)

### PR DESCRIPTION
**Pull request by Mariatta**
Fix typos in code comments: bdb.py and configure.ac..
(cherry picked from commit b5c246f833d95991fed728c3845176dd661cd5ea)

Co-authored-by: Eitan Adler <grimreaper@users.noreply.github.com>

### CODE REVIEW

**Comment by Mariatta** [comment]
@ned-deily I ran autoconf here. Can you check if this is right? It has more changes than I expect..

**Review by ned-deily — COMMENTED** [review]
The giveaway is that all the diffs are in configure.ac, not in configure.  The latter is generated by the autoconf  not the former.   Looks like the issue is that the 2.7 configure.ac has a lot of trailing spaces cruft that has been there forever and now is probably not the time to change it.  Recommend that you revert the edit to configure.ac and just make the changes manually then rerun autoconf.

**Comment by matrixise** [comment]
@Mariatta @ned-deily 
You will find my backport of this PR here https://github.com/python/cpython/pull/10315

**Comment by ned-deily** [comment]
Thanks for the PR.  It has been superseded by #10315.

**Pull request closed without merging**
