### PR TITLE
gh-113199: Make `read1` and `readline` of `HTTPResponse` close IO after reading all data

### PR DESCRIPTION
**Pull request by illia-v**
The added code is very similar to what already exists in `read`:
https://github.com/python/cpython/blob/73222213787d86d900d4dfab2c2cf9cb41b9bf77/Lib/http/client.py#L484-L487

* Issue: gh-113199

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
There is a similar case in `readline()`. Do you mind to add autodisconnect there too?

**Comment by illia-v** [comment]
> There is a similar case in `readline()`. Do you mind to add autodisconnect there too?

Added, thanks for the suggestion!

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Comment by kristjanvalur** [comment]
Yes, this is how it should be, I guess :)

**Pull request merged**
