### PR TITLE
GH-102126: fix deadlock at shutdown when clearing thread states

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-102126

### CODE REVIEW

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

There's one case that could be problematic but (ISTM) is highly unlikely:  some other thread might call `PyThreadState_Delete*()` on one of the existing thread states, which would modify the linked list while we're walking it here.  We could mitigate that (very small) risk by checking in those functions if the interpreter is finalizing and returning immediately (or blocking) if it is.  FWIW, the status quo is already deficient in that case, and this PR only slightly adds to the problem.  Regardless, the risk is fairly minimal so we can address that separately.

(Before merging, would you mind just double-checking that the risk actually is minimal? 😄)

----

One observation: the lock isn't strictly necessary here.  It's needed for one of the following:

* in case a new thread state gets created for the interpreter
* in the case described above (`PyThreadState_Delete*()` was called in another thread)

At this point in interpreter finalization, neither of those things should be happening.  So it may make sense to disallow them (or ignore/block, in the case of the second one).  Alternately we could give each interpreter it's own lock (e.g. `PyInterpreterState.threads.mutex`) to use when managing its thread states, as opposed to reusing the global "HEAD" lock like we currently do.

**Comment by kumaraditya303** [comment]
> There's one case that could be problematic but (ISTM) is highly unlikely: some other thread might call PyThreadState_Delete*() on one of the existing thread states, which would modify the linked list while we're walking it here. We could mitigate that (very small) risk by checking in those functions if the interpreter is finalizing and returning immediately (or blocking) if it is. FWIW, the status quo is already deficient in that case, and this PR only slightly adds to the problem. Regardless, the risk is fairly minimal so we can address that separately.

Yeah, I too noticed that but I am not concerned about that as at runtime shutdown such code is already unsafe and can crash or result in hang etc. Regardless I'll address that separately in a new issue and get this fixed first. 

Thanks for the review.

**Comment by kumaraditya303** [comment]
The buildbots failures are unrelated so merging. https://buildbot.python.org/all/#/builders/259/builds/681/steps/5/logs/stdio

**Comment by kumaraditya303** [comment]
> Regardless I'll address that separately in a new issue

https://github.com/python/cpython/issues/102233

**Pull request merged**
