### PR TITLE
[2.7] bpo-30694: Upgrade Modules/expat/ to libexpat 2.2.1 (#2300)

### PR DESCRIPTION
**Pull request by vstinner**
New file: Modules/expat/siphash.h.
(cherry picked from commit 5ff7132313eb651107b179d20218dfe5d4e47f13)

### CODE REVIEW

**Comment by vstinner** [comment]
I tested manually the change on Linux, test_pyexpat pass:

```
git clean -fdx  # remove all untracked files
./configure -C --with-pydebug CFLAGS=-O0 --enable-unicode=ucs4 && make && ./python -m test -v test_pyexpat 
```

**Comment by vstinner** [comment]
Oh, the compilation of expat 2.2.1 on Windows using Visual Studio 2008 fails because of missing stdint.h header :-(

```
c:\projects\cpython\modules\expat\siphash.h(79): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory [C:\projects\cpython\PCbuild\_elementtree.vcxproj]
```

https://ci.appveyor.com/project/python/cpython/build/2.7.13+.3582

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by vstinner** [comment]
> Oh, the compilation of expat 2.2.1 on Windows using Visual Studio 2008 fails because of missing stdint.h header :-(

So, I wrote a patch, and added it for my PR. Then I wanted to send it upstream, but... upstream, they already fixed the issue in master! https://github.com/libexpat/libexpat/commit/c74d380b8f0b5215153d840d2af9455d9c53b960

New try: I cherry-picked this commit on top of expat 2.2.1.

**Comment by vstinner** [comment]
I tested the latest version of this PR on Windows with VS 2008 on a fresh Git repository (I ran "git clean -fdx" to remove all untracked files): the compilation succeed and test_pyexpat pass!

**Comment by vstinner** [comment]
@the-knights-who-say-ni: "Unfortunately we couldn't find an account corresponding to your GitHub username on bugs.python.org (b.p.o) to verify you have signed the CLA (...)"

Oh, I kept the original author of the commit in my cherry-pick: "Sebastian Pipping <sebastian@pipping.org>", but as expected, this libexpat contributor isn't related to Python :-/ I took the ownership of this commit, sorry Sebastian! Anyway, I already replaced the Git ownership of all files in Modules/expat/ :-)

**Pull request merged**
