### PR TITLE
Minor clean up.

### PR DESCRIPTION
**Pull request by 10maurycy10**
Not much to say here.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@10maurycy10

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by pablogsal** [comment]
Hi @10maurycy10 and thanks for the PR. A couple of things:

* You need to make sure to sign the CLA before contributing to Python. Check the previous comment.
* I don't understand what this PR is cleaning. Normally we don't refactor code for formatting or similar purposes unfortunately.

**Comment by 10maurycy10** [comment]
It fixes some missing brackets that looks out of place.

**Comment by pablogsal** [comment]
> It fixes some missing brackets that looks out of place.

Unfortunately we normally don't take PRs that are formatting only to avoid risking  introducing subtle bugs. I am going to close this PR but I am sure you will find something interesting to work on! :)

P.S. Make sure to sign up the CLA so we can review your future work !

**Pull request closed without merging**
