### PR TITLE
bpo-43908: Make heap types converted during 3.10 alpha immutable

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue43908

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I'll add tests in a separate PR.

**Comment by pablogsal** [comment]
@vstinner could you take a look?

**Review by Ely68 — APPROVED** [review]

**Comment by erlend-aasland** [comment]
@vstinner Do you want me to break this up in multiple PR's? The number of files changed is high, but the actual diff is pretty short (`+61 −38`).

**Comment by pablogsal** [comment]
@vstinner Can you review this by Thursday, as this is a release blocker for beta 3?

**Review by pablogsal — APPROVED** [review]

**Pull request merged**
