### PR TITLE
gh-97556: Raise null bytes syntax error upon null in multiline string

### PR DESCRIPTION
**Pull request by lysnikolaou**
* Issue: gh-97556

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]
LGTM

Maybe we should add sone asserts here and there that tok->done is not error to prevent this issue from happening in other places

**Comment by lysnikolaou** [comment]
> Maybe we should add sone asserts here and there that tok->done is not error to prevent this issue from happening in other places

That's a good idea. Where would you add these `assert`s though, since most of the time we shouldn't be asserting, but rather check for it.

One of the items I have in my to-do list is to add comments and assert in various places in the tokenizer to make the logic a bit easier to follow. Would it be okay to merge this as-is and then do that in a separate PR?

**Comment by vstinner** [comment]
@lysnikolaou: Do you consider backporting your change to Python 3.11?

**Comment by bskinn** [comment]
See discussion linked in the associated issue, there was a decision made _not_ to backport the initial change that worked for single quoted strings, due to avoiding breaking compatibility in a patch version release.

**Comment by bskinn** [comment]
See https://github.com/python/cpython/issues/96670#issuecomment-1260161574

**Comment by lysnikolaou** [comment]
GH-104195 includes a backport of this commit to 3.11.

**Pull request merged**
