### PR TITLE
bpo-38488: Upgrade bundled versions of pip & setuptools

### PR DESCRIPTION
**Pull request by xavfernandez**
https://bugs.python.org/issue38488

### CODE REVIEW

**Comment by vstinner** [comment]
For core devs reviewing this change: before merging a new setuptoos + pip upgrade, please run buildbots on the PR to ensure that it doesn't break FreeBSD and Install buildbots again. See https://bugs.python.org/issue38488 for the previous issues.

**Review by vstinner — CHANGES_REQUESTED** [review]
This PR doesn't seem to fix the 2 regressions that I listed in https://bugs.python.org/issue38488

**Comment by vstinner** [comment]
> This PR doesn't seem to fix the 2 regressions that I listed in https://bugs.python.org/issue38488

Ah, the permission issue should be fixed: @xavfernandez wrote in https://github.com/python/cpython/pull/16782#issuecomment-635401640:

> The permission issue is likely due to pypa/pip#8164 that was fixed in 20.1.1.
> Sorry I did not keep this PR up-to-date with the latest pip, #20491 should hopefully fix this.

But what about the https://bugs.python.org/issue40808 issue?

**Comment by pradyunsg** [comment]
That looks like a fragile test that using re.sub to ignore that specific error message, but it changed in the newer release.

**Comment by xavfernandez** [comment]
> But what about the https://bugs.python.org/issue40808 issue?

@vstinner , like Pradyun, this is due to https://github.com/pypa/pip/commit/1ee270a8d485ab4deafd2f7d7b950ce31d474807 that slightly changed the wording.

**Comment by vstinner** [comment]
Let's see how buildbots like this upgrade :-)

**Comment by xavfernandez** [comment]
Buildbot seems happy ?

**Review by vstinner — APPROVED** [review]
LGTM. But I will not merge this PR since I don't know how to validate the content of binary wheel files.

Is there a GPG signature somewhere to verify the files? Or an automated way to validate its content?

**Comment by xavfernandez** [comment]
> Is there a GPG signature somewhere to verify the files? Or an automated way to validate its content?

No GPG signature but I'd suggest checking that the hashes of the bundled files match those advertised by https://pypi.org/project/pip/#files & https://pypi.org/project/setuptools/47.1.0/#files

**Comment by vstinner** [comment]
> I'd suggest checking that the hashes of the bundled files match those advertised by https://pypi.org/project/pip/#files & https://pypi.org/project/setuptools/47.1.0/#files

Would it be possible to add a tool somewhere in Tools/ to validate hashes of wheel binaries?

**Comment by ned-deily** [comment]
I'd like to see this get into the next round of releases including 3.7.8 so I'm merging it now. I manually verified the hashes of the pip and setuptools wheels.  Having a tool to manually check would be nice; even better, I think would be a tool that allows us to build the two wheels ourselves from source so that we are not dependent on non-source files from elsewhere.

**Pull request merged**
