### PR TITLE
Update links in the documentation

### PR DESCRIPTION
**Pull request by jamesfe**
I noticed some of the links in the documentation return 404 errors (via some automated documentation checking I have been doing) and I wanted to submit this as a PR for you.  It seems fairly trivial so I haven't created an issue for it.  Let me know if you want me to do that.

Also, some of the domains for the links are no longer active, so I found alternatives that seemed plausible and reasonable.  Please let me know if these are not acceptable.

Cheers,
Jimmy

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by jamesfe** [comment]
Have just signed and submitted the CLA.

**Comment by brettcannon** [comment]
@jamesfe You have not associated your bugs.python.org account with your GitHub account. Please see the CLA comment from earlier about how to rectify the situation.

**Comment by jamesfe** [comment]
@brettcannon how embarrassing that even as I submit a change to the docs, I myself failed to read that comment completely.  I have added the relevant info to my BPO account.  Thanks!

**Comment by brettcannon** [comment]
@jamesfe 😄 it happens. It's all good now.

Do note, though, that your PR didn't pass our CI check of the docs, so that will need to be fixed before anyone probably looks at your suggested changes.

**Comment by jamesfe** [comment]
@brettcannon editing previous comment: Everything is fixed.  Those slightly frustrating documentation checks are actually pretty smart and caught some links I'd missed in my original pass.

**Review by marco-buttu — CHANGES_REQUESTED** [review]
Thanks, your changes are OK :)  However, I found other broken links that you can fix in this pull request.  For instance, in `Doc/library/functools.rst` there is a link to [https://en.wikipedia.org/wiki/Cache_algorithms#Examples](https://en.wikipedia.org/wiki/Cache_algorithms#Examples) that gives the error message *Anchor 'Examples' not found*.  You can fix changing the URL to [https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_Recently_Used_.28LRU.29](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_Recently_Used_.28LRU.29).  To find all broken URLs please execute `make linkcheck` from the *Doc* directory.  Thank you very much for you time.

**Comment by jamesfe** [comment]
@marco-buttu Great suggestion - I'll probably do this tomorrow morning (paris time).  Thanks for the info regarding `make linkcheck`!

**Comment by jamesfe** [comment]
Here are some more fixed up link sections - one area I am a little nervous about modifying is the change release documents.  

These seem quasi-historical in nature and refer to things like old Python module listing pages which are no longer in existence as well as Zope Corporation (see license.rst) which may now be Zope Community - are these files off limits?  

If not my best course of action is probably to just delete the link references and leave the text in place since some things haven't migrated, they are simply gone

**Comment by marco-buttu** [comment]
@jamesfe both *Doc/license.rst* and *LICENSE* should be changed according to @gvanrossum wording in [bpo-25910](http://bugs.python.org/issue25910#msg295200).  Just wait a bit because I want to be sure #1933 aims to fix only redirections and not also broken links.  I will review your changes as soon as I get an answer.  Thanks :-)

**Comment by jamesfe** [comment]
Great no problem - I am not waiting by the phone for this PR, it is unlikely it is blocking anything ;-)

**Comment by marco-buttu** [comment]
@jamesfe the @CuriousLearner [comment](https://github.com/python/cpython/pull/1933#issuecomment-318975231) in #2765 makes me think that this PR is a duplicate.

**Comment by jamesfe** [comment]
@marco-buttu yes - there are some links I fix here that are not fixed in #1933.  @CuriousLearner can cherry-pick this commit onto their branch for an easy way to integrate my changes, but I am not particular one way or the other.

**Comment by CuriousLearner** [comment]
Hey @jamesfe I would be happy to cherry-pick your commits into the patch. But I haven't got a review till now.

**Comment by jamesfe** [comment]
Is anyone available to add the `skip news` label to this?

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks!

**Comment by jamesfe** [comment]
Thanks so much for merging this!

**Comment by asvetlov** [comment]
You are welcome!

**Pull request merged**
