### PR TITLE
Fix a bug about wrong order of function arguments

### PR DESCRIPTION
**Pull request by LostBenjamin**
Hi,

This pull request is a fix to a potential bug about wrong order of function arguments at `Lib/test/test_descr.py`. Please check the changes.

Best,
Jingxuan

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
No, it is the correct order.

**Comment by LostBenjamin** [comment]
Why?

The [documentation](https://docs.python.org/3/library/functions.html#isinstance) says that the first argument of `isinstance` is the object and the second argument is the class.

**Comment by serhiy-storchaka** [comment]
The first argument is the object (its value does not matter, it is ignored in this test in any case). The second argument can be not only a class, but also a tuple or an arbitrary object with the `__instancecheck__()` method. The test checks that `isinstance(x, y)` calls `y.__instancecheck__()`.

**Comment by LostBenjamin** [comment]
Thank you for the explanation!

**Pull request closed without merging**
