### PR TITLE
bpo-30587: Adds signature checking for mock autospec object method calls

### PR DESCRIPTION
**Pull request by claudiubelu**
Mock can accept an spec object / class as argument, making sure that accessing attributes that do not exist in the spec will cause an AttributeError to be raised, but there is no guarantee that the spec's methods signatures are respected in any way. This creates the possibility to have faulty code with passing unit tests and assertions.

Example:

```
import mock

class Something(object):
    def foo(self, a, b, c, d):
        pass

m = mock.Mock(spec=Something)
m.foo()
```

Adds the ``autospec`` argument to Mock, and its ``mock_add_spec`` method.

Passes the ``spec``'s attribute with the same name to the child mock (spec-ing the child), if the mock's ``autospec`` is ``True``.

Sets ``_mock_check_sig`` if the given spec is callable.

Adds unit tests to validate the fact that the autospec method signatures are respected.

https://bugs.python.org/issue30587

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Mariatta** [comment]
Thanks for the PR. This doesn't seem to be a trivial change. Can you please open an issue at https://bugs.python.org, and then reference the issue number in the PR title.

**Comment by claudiubelu** [comment]
Hello. I actually reported a bug for this, but I didn't reference it in the commit message. Will do.

**Comment by claudiubelu** [comment]
@Mariatta Hi, can you take a look again? :)

**Comment by AraHaan** [comment]
@bclau on your https://github.com/python/cpython/pull/4476 PR it seems you accidentally included the commit for this PR.

**Comment by voidspace** [comment]
I'm taking a look at this.

**Comment by voidspace** [comment]
I'd like spec to have signature validation. I don't think the use case for "attribute validation only" (current spec behaviour) is very strong and I'd rather not add new keywords. The mock API is already too complex.

I'll take the existing PR and modify it to use spec instead of adding the new autospec.

**Comment by ben-reilly** [comment]
@voidspace Any status update on this change?

**Comment by MaxwellDupre** [comment]
I have a small issue with _get_class method. It doesn't seem to be part of any module/standard lib.
Also, _get_class does not seem to appear in mock.py for 3.10.02 or 3.11.
Lastly, would it be possible to bring your patch up to latest 3.11?

**Comment by arhadthedev** [comment]
@voidspace, would you mind to return to this PR? It would be great to have it finally merged in a worthy state after these three tumbly years. :)

**Comment by arhadthedev** [comment]
(though, it broke tests)

**Comment by arhadthedev** [comment]
@sobolevn (as a committer into `mock.py` who is still active)

**Comment by cjw296** [comment]
> I'd like spec to have signature validation. I don't think the use case for "attribute validation only" (current spec behaviour) is very strong and I'd rather not add new keywords. The mock API is already too complex.
> 
> I'll take the existing PR and modify it to use spec instead of adding the new autospec.

@arhadthedev - I don't see that this feedback was addressed, and a few others appear to have raised issues in follow up. 
It doesn't appear that @claudiubelu is still working on this patch so I'm going to close the PR.

It sounds like there's a good idea lurking here, but more discussion needs to happen on https://github.com/python/cpython/issues/74772 before a new PR is opened.

**Comment by claudiubelu** [comment]
> I'd like spec to have signature validation. I don't think the use case for "attribute validation only" (current spec behaviour) is very strong and I'd rather not add new keywords. The mock API is already too complex.
> 
> I'll take the existing PR and modify it to use spec instead of adding the new autospec.

Hello,

I haven't followed this in quite a while, and I've remembered this recently when I hit this issue again.

I technically agree with you, adding a new keyword may be a bit undesirable since it's already quite complex, but I'd have to say that changing the ``spec`` behaviour to the ``autospec`` one would be more confusing. That is because ``spec`` meaning is already well-established at this point and what it does, and there is already ``autospec``  in a few scenarios (``mock.patch``). Having ``mock.Mock`` ``spec`` behave like ``mock.patch`` ``autospec`` would be inconsistent and confusing.

So, it's not really a new keyword, this PR would just make the API more uniform, bringing the ``autospec`` capability to ``mock.Mock``. Simplifying the API by reducing ``spec`` and ``autospec`` is another discussion, and a bit outside the scope of this PR, IMO.

I think we can reopen the PR. I can rebase it (though, I think it might be easier to cherry-pick the commit onto the current ``HEAD``, though I'm not sure how to credit other contributors on this PR in that case), fix any failing test / linting issue if it appears (there is a new failing test, missing argument).

> I have a small issue with _get_class method. It doesn't seem to be part of any module/standard lib. Also, _get_class does not seem to appear in mock.py for 3.10.02 or 3.11. Lastly, would it be possible to bring your patch up to latest 3.11?

``_get_class`` was not touched / used in the original commit, and since then this issue has been addressed, ``_spec_class = type(spec)`` is now used instead.

**Pull request closed without merging**
