### PR TITLE
[3.9] bpo-45520: Backport __getstate__, __setstate__ methods for `dataclasses` from 3.10 into 3.9 (GH-25786)

### PR DESCRIPTION
**Pull request by sobolevn**
Refs https://github.com/python/cpython/commit/823fbf4e0eb66cbef0eacb7e8dbfb5dc8ea83b40

https://bugs.python.org/issue45520

### CODE REVIEW

**Comment by sobolevn** [comment]
CC @ericvsmith @Fidget-Spinner

**Comment by merwok** [comment]
Please mention dataclasses in the PR title

**Comment by Fidget-Spinner** [comment]
@sobolevn sorry for the really long delay (I dropped the ball on this notification for a month). Unfortunately I have to admit I'm clueless at pickle so I can't review this.

**Comment by sobolevn** [comment]
@Fidget-Spinner no worries, thanks for your review! 

This is a backport of a bugfix from `3.10` to `3.9`
For some reason it was not done in https://github.com/python/cpython/pull/25786

CC @JelleZijlstra as the original reviewer 🙂

**Comment by JelleZijlstra** [comment]
Since dataclasses only gained native slot support in 3.10, it doesn't seem important to apply this fix to 3.9. (It affects people who set `__slots__` manually, but if you do that it doesn't seem too bad to also manually provide pickle support.) Also, unconditionally setting these methods is risky; it may overwrite a user-provided method.

I'll leave the decision to @ericvsmith though.

**Review by MaxwellDupre — APPROVED** [review]
Ran 175 tests in 1.202s
OK
Looks reasonable.

**Comment by ambv** [comment]
We're releasing the last bugfix release of 3.9 today and this PR's been stale for a while. Sadly it's a *wontfix* now.

**Pull request closed without merging**
