### PR TITLE
Fix typo for configure.ac

### PR DESCRIPTION
**Pull request by corona10**
From https://github.com/python/cpython/pull/26078

### CODE REVIEW

**Review by ned-deily — CHANGES_REQUESTED** [review]
It looks like there is a difference between the autoconf version you are using and the one last used to merge.  As noted in configure.ac, we are using 2.69 but there are newer versions out there.  Since this is truly a one-line change, I suggest you forget about trying autoreconf for this and just make that change manually :)

**Comment by corona10** [comment]
>  I suggest you forget about trying autoreconf for this and just make that change manually :)

Got it

**Comment by corona10** [comment]
I have made the requested changes; please review again

**Review by ned-deily — APPROVED** [review]
LGTM. Sorry about all the churn.

**Comment by corona10** [comment]
Thank you @ned-deily 
And sorry about my uncareful mistake.

**Review by willingc — APPROVED** [review]

**Pull request merged**
