### PR TITLE
Minor ReST formatting fixes in subprocess docs

### PR DESCRIPTION
**Pull request by timhoffm**
Formatted some code segments as literal or code block.

### CODE REVIEW

**Comment by timhoffm** [comment]
Not quite following why CI fails. Travis says:

> [distutils/examples:267] "`" found in "This is the description of the ``foobar`` package."

But that seems unrelated to this PR.

**Comment by tirkarthi** [comment]
The error seems to have been fixed. Updating your branch with latest master might help https://bugs.python.org/issue37644.

**Comment by timhoffm** [comment]
Rebased.

**Comment by matrixise** [comment]
Thank you for your contribution, your PR has been merged into master and will be backported to 3.8.

**Pull request merged**
