### PR TITLE
bpo-29612 : Fix hard link creation in tar extraction when it points to themselves

### PR DESCRIPTION
**Pull request by j0ack**
When creating a link from a tarball, if the link target and the file has the same path it raised an exception.

We simply ignore this case at the beginning of the method.

https://bugs.python.org/issue29612

### CODE REVIEW

**Comment by j0ack** [comment]
As @JulienPalard said in #5753, this is an attempt to fix this issue in master to backport in 2.7 later

**Review by BoboTiG — COMMENTED** [review]
Thank you for the patch :)
Do you mind adding a test case?

**Comment by j0ack** [comment]
@BoboTiG sure I'll push a commit with a test case

**Comment by BoboTiG** [comment]
Also, add your name in the NEWs entry:
```
Skip link creation from a tar file during extraction if the target path is
equal to the link target. Patch by Joachim Trouverie.
```

**Comment by j0ack** [comment]
@BoboTiG I had a unit test to be sure hard link are correctly extracted from a tar archive but I'm not really sure how to check that hard link that points to themselves are skipped. If anyone has a hint ?

**Comment by j0ack** [comment]
Not sure if this issue is still opened.

If it is could someone give me a hint for the unit test ?

**Comment by BoboTiG** [comment]
I could help the next week.

**Comment by BoboTiG** [comment]
Hm I am confused. I reproduced the error on Python 2.7.16 but **not** on Python 3.6.8, 3.6.9, 3.7.3 or 3.7.4, nor master.

As master is the branch for Python 3.9, perhaps this issue is not *mergeable*.

2 things:
- Do you reproduce the issue on your OS from the **master** branch? Perhaps did I miss something (I tested on GNU/Linux).
- If it is a specific Python 2.7 fix, finally, then you original PR was good :)

**Comment by BoboTiG** [comment]
Also, do you have a testable tar file? The one from that PR contains special files and I got `PermissionError`:
```python
python tartest.py skip testtar.tar /tmp/tardata-python-3.6.9  
ustar/conttype
ustar/regtype
ustar/dirtype
ustar/dirtype-with-size
ustar/lnktype
ustar/symtype
ustar/blktype
Traceback (most recent call last):
  File "tartest.py", line 17, in <module>
    unarchive(skip, archive, dest)
  File "tartest.py", line 12, in unarchive
    tar_fd.extract(info, dest)
  File "/.../tarfile.py", line 2052, in extract
    numeric_owner=numeric_owner)
 File "/.../tarfile.py", line 2128, in _extract_member
    self.makedev(tarinfo, targetpath)
  File "/.../tarfile.py", line 2202, in makedev
    os.makedev(tarinfo.devmajor, tarinfo.devminor))
PermissionError: [Errno 1] Operation not permitted
```

**Comment by j0ack** [comment]
> Hm I am confused. I reproduced the error on Python 2.7.16 but **not** on Python 3.6.8, 3.6.9, 3.7.3 or 3.7.4, nor master.
> 
> As master is the branch for Python 3.9, perhaps this issue is not _mergeable_.
> 
> 2 things:
> 
>     * Do you reproduce the issue on your OS from the **master** branch? Perhaps did I miss something (I tested on GNU/Linux).
> 
>     * If it is a specific Python 2.7 fix, finally, then you original PR was good :)

Well after tests it seems that this issue has been fixed on Python 3. 
I'll reopen the original PR

Thanks

**Comment by j0ack** [comment]
> Also, do you have a testable tar file? The one from that PR contains special files and I got `PermissionError`:
> 
> ```python
> python tartest.py skip testtar.tar /tmp/tardata-python-3.6.9  
> ustar/conttype
> ustar/regtype
> ustar/dirtype
> ustar/dirtype-with-size
> ustar/lnktype
> ustar/symtype
> ustar/blktype
> Traceback (most recent call last):
>   File "tartest.py", line 17, in <module>
>     unarchive(skip, archive, dest)
>   File "tartest.py", line 12, in unarchive
>     tar_fd.extract(info, dest)
>   File "/.../tarfile.py", line 2052, in extract
>     numeric_owner=numeric_owner)
>  File "/.../tarfile.py", line 2128, in _extract_member
>     self.makedev(tarinfo, targetpath)
>   File "/.../tarfile.py", line 2202, in makedev
>     os.makedev(tarinfo.devmajor, tarinfo.devminor))
> PermissionError: [Errno 1] Operation not permitted
> ```

There is the same issue with the test tar file on master

Anyway thanks for your review

**Comment by BoboTiG** [comment]
FTR I used this one, manually creafted following the commands found on the BPO, if it helps you. You will have to unzip it first (GitHub does not allow to attacj `.tar` files). You could  add it into your other branch to test the behabior on Python 2.7.
[tardata.zip](https://github.com/python/cpython/files/3723660/tardata.zip)

**Comment by j0ack** [comment]
Could you please reopen https://github.com/python/cpython/pull/5753 @BoboTiG or should I create a new MR ?

**Comment by BoboTiG** [comment]
I do not have enough rights to reopen a PR. Create a new one ;)

**Pull request closed without merging**
