### PR TITLE
gh-104469 : Convert _testcapi/vectorcall_limited.c to use AC

### PR DESCRIPTION
**Pull request by nahyeon-an**
* Issue: gh-104469

### CODE REVIEW

**Comment by nahyeon-an** [comment]
@corona10

**Review by corona10 — APPROVED** [review]
lgtm!

**Comment by ambv** [comment]
Closing and re-opening to retrigger CLA checks. Sorry for the noise.

**Comment by corona10** [comment]
> @corona10 FYI this caused a few of the WebAssembly buildbots to fail, e.g., https://buildbot.python.org/all/#/builders/1046/builds/2731 .

I will take a look, it can be easily fixed if the implicit function declarations is a real issue.

> In file included from ../../Modules/_testcapi/clinic/vectorcall_limited.c.h:6:
../../Include/internal/pycore_gc.h:48:10: error: call to undeclared function 'PyObject_IS_GC'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    if (!PyObject_IS_GC(obj)) {

**Comment by corona10** [comment]
````
#define Py_LIMITED_API 0x030c0000 // 3.12
#include "parts.h"
#include "clinic/vectorcall_limited.c.h"

#ifdef LIMITED_API_AVAILABLE
````

the code line of #ifdef LIMITED_API_AVAILABLE was issue, I will send a hot fix for it.

**Comment by corona10** [comment]
Okay, this is an issue between AC and limited C APIs. We should revert it first.
cc @erlend-aasland @vstinner @nahyeon-an

Thank you @vstinner for investigation :)

**Comment by vstinner** [comment]
> Okay, this is an issue between AC and limited C APIs

Right, see:

* issue #85283
* https://discuss.python.org/t/propose-that-argument-clinic-only-uses-public-python-apis-to-make-it-easier-to-use-outside-cpython/16557

**Comment by erlend-aasland** [comment]
Sounds good, go ahead with any needed reverts. It is not important that the _test* extension modules use clinic :)

**Comment by vstinner** [comment]
New attempt since Argument Clinic now supports the limited C API: PR #109691.

**Pull request merged**
