### PR TITLE
bpo-33125: Enables building traditional installer for Windows ARM64

### PR DESCRIPTION
**Pull request by zooba**
Also skips building web-based installers completely

https://bugs.python.org/issue33125

### CODE REVIEW

**Comment by nsait-linaro** [comment]
Great ! Thanks @zooba

**Comment by zooba** [comment]
Still not ready - the py.exe launcher needs quite a few updates to work, so I'm going to omit it from the installer for now. We can add it back later.

**Comment by zooba** [comment]
Made and tested a release build and it all looks good. I'll leave this open in case anyone has a read and spots anything, but otherwise I'll merge (hopefully before the next release, if I remember)

**Comment by nsait-linaro** [comment]
@zooba Do we expect to see a windows/arm64 installer with the next alpha release of Python 3.11 ?

**Comment by zooba** [comment]
@nsait-linaro That's my plan, though it's missing some "standard" components. So unless we manage to get the py.exe launcher updated and Tcl/Tk supported on ARM64, we might not ship it as the final release. (The Store and Nuget packages will continue to ship, because I'm not concerned about people being as surprised by the missing components there.)

**Comment by nsait-linaro** [comment]
Thanks, @zooba. That makes sense. Yes, it will be nice to sort out the launcher and tcl interface. I haven't looked into those bits yet but happy to dig if you need any help.

**Comment by zooba** [comment]
@nsait-linaro I think Tcl/Tk need updates to their build system to be able to handle the cross compilation (and yes, we'll be cross compiling them). Right now they don't seem to handle platforms other than x64 and x86 at all.

The launcher is more complex and will have a much bigger impact on how everyone uses it, regardless of platform. If you have time to dig into either, start with Tcl/Tk I think.. (In fact, I'm betting all the GUI toolkits will need work, and I haven't looked at any of them yet. But they probably won't want to move until there's CI available... at least with Tcl/Tk we do our own builds.)

**Pull request merged**
