### PR TITLE
GH-103224: Use the realpath of the Python executable in `test_venv`

### PR DESCRIPTION
**Pull request by artemmukhin**
Now running tests through a Python symlink no longer causes `test_upgrade_dependencies` and `test_zippath_from_non_installed_posix` to fail.

* Issue: gh-103224

### CODE REVIEW

**Comment by artemmukhin** [comment]
@vsajip Could you please take a look? This PR only involves a small change in the test

**Comment by vsajip** [comment]
In some buildbots `test_venv` is failing, but I haven't had time to look into why.

**Comment by arhadthedev** [comment]
```plain
== Tests result: FAILURE ==
411 tests OK.
1 test failed:
    test_venv
18 tests skipped:
    test_asdl_parser test_clinic test_devpoll test_gdb test_ioctl
    test_kqueue test_launcher test_msilib test_peg_generator
    test_startfile test_tix test_tkinter test_ttk test_winconsoleio
    test_winreg test_winsound test_wmi test_zipfile64
0:06:57 load avg: 0.91
0:06:57 load avg: 0.91 Re-running failed tests in verbose mode
0:06:57 load avg: 0.91 Re-running test_venv in verbose mode (matching: test_zippath_from_non_installed_posix, test_upgrade_dependencies)
test_upgrade_dependencies (test.test_venv.BasicTest.test_upgrade_dependencies) ... FAIL
test_zippath_from_non_installed_posix (test.test_venv.BasicTest.test_zippath_from_non_installed_posix)
Test that when create venv from non-installed python, the zip path ... ERROR
======================================================================
ERROR: test_zippath_from_non_installed_posix (test.test_venv.BasicTest.test_zippath_from_non_installed_posix)
Test that when create venv from non-installed python, the zip path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/test/test_venv.py", line 606, in test_zippath_from_non_installed_posix
    subprocess.check_call(cmd,
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4fiiqaq7/bin/python3'
======================================================================
FAIL: test_upgrade_dependencies (test.test_venv.BasicTest.test_upgrade_dependencies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/test/test_venv.py", line 237, in test_upgrade_dependencies
    builder.upgrade_dependencies(fake_context)
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/venv/__init__.py", line 459, in upgrade_dependencies
    self._call_new_python(context, '-m', 'pip', 'install', '--upgrade',
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/venv/__init__.py", line 355, in _call_new_python
    subprocess.check_output(args, **kwargs)
  File "/home/buildbot/buildarea/pull_request.cstratak-fedora-stable-x86_64.clang-installed/build/target/lib/python3.12/test/test_venv.py", line 222, in pip_cmd_checker
    self.assertEqual(
AssertionError: Lists differ: ['/tm[20 chars]thon3', '-m', 'pip', 'install', '--upgrade', '[14 chars]ols'] != ['/tm[20 chars]thon3.12', '-m', 'pip', 'install', '--upgrade'[17 chars]ols']
First differing element 0:
'/tmp/tmpbr5t_vk3/bin/python3'
'/tmp/tmpbr5t_vk3/bin/python3.12'
- ['/tmp/tmpbr5t_vk3/bin/python3',
+ ['/tmp/tmpbr5t_vk3/bin/python3.12',
?                               +++
   '-m',
   'pip',
   'install',
   '--upgrade',
   'pip',
   'setuptools']
----------------------------------------------------------------------
Ran 2 tests in 1.068s
FAILED (failures=1, errors=1)
test test_venv failed
1 test failed again:
    test_venv
== Tests result: FAILURE then FAILURE ==
411 tests OK.
1 test failed:
    test_venv
18 tests skipped:
    test_asdl_parser test_clinic test_devpoll test_gdb test_ioctl
    test_kqueue test_launcher test_msilib test_peg_generator
    test_startfile test_tix test_tkinter test_ttk test_winconsoleio
    test_winreg test_winsound test_wmi test_zipfile64
1 re-run test:
    test_venv
Total duration: 6 min 59 sec
Tests result: FAILURE then FAILURE
program finished with exit code 2
elapsedTime=419.107087
```

**Comment by artemmukhin** [comment]
@arhadthedev Thank you for clarifying! I tried to fix that in the second commit. Could you please rerun the tests?

**Comment by arhadthedev** [comment]
Retriggered the build because the last logs seem to be expired:

image

**Pull request merged**
