### PR TITLE
Add .idea and .iml to .gitignore

### PR DESCRIPTION
**Pull request by gfyoung**
These arose when working with the repository in IntelliJ IDE.  This is a trivial PR.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by gfyoung** [comment]
> Unfortunately our records indicate you have not signed the CLA.

I signed the CLA two days ago.  How long does it take to propagate?  Or should I forward the confirmation email to somebody?

**Comment by zooba** [comment]
Thanks!

**Comment by berkerpeksag** [comment]
Note that a nearly identical PR (see https://github.com/python/cpython/pull/6) was rejected before because users can use a global .gitignore file (see also bpo-29510 for Eclipse.)

**Comment by gfyoung** [comment]
Fair enough, though I think this comment at the end of the PR <a href="https://github.com/python/cpython/pull/6#issuecomment-279109972">here</a> suggests that perhaps that that suggestion should be reconsidered.  I see no reason to assume that users have a global `.gitignore` file configured.  That's seem to be just asking for accidental file commits.

**Comment by berkerpeksag** [comment]
Using a global .gitignore file is a best practice. That last comment was about syncing .gitignore with .hgignore.

**Comment by gfyoung** [comment]
Best practice but not required.  Call me cynical, but I don't expect users to do this (in my case, I was working on a machine other than my own and accidentally committed these changes in another PR).

**Pull request merged**
