### PR TITLE
bpo-43220: Accept explicit default args in required groups

### PR DESCRIPTION
**Pull request by keith**
Previously if you had a default argument on a required mutually
exclusive group and the default was explicitly passed, it was treated
as if no value was passed. Now it accepts that value.

https://bugs.python.org/issue43220

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@keith

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by rhettinger** [comment]
Please add a NEWS entry using Blurb.

**Comment by keith** [comment]
Updated!

**Comment by keith** [comment]
Any idea who I can get to review?

**Comment by keith** [comment]
@rhettinger friendly bump!

**Review by furkanonder — APPROVED** [review]
LGTM.

**Comment by keith** [comment]
I merged main into this to resolve the conflict. @furkanonder should I do anything else here or is the process to wait for further review?

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution. It was fixed in other way by #124307.

**Pull request closed without merging**
