### PR TITLE
bpo-46104: [typing docs]: Fix example broken by PR #30148

### PR DESCRIPTION
**Pull request by AlexWaygood**
This PR addresses a review by @gvanrossum, which can be found in the discussion in GH-30179.

https://bugs.python.org/issue46104

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Thanks Alex, there may also be line 1786 to revert, if we *really* want to stick with the original intent.

https://github.com/python/cpython/pull/30179/files#diff-8a0f115fde6769c122b771b6d0eca184c4580f7b5fabe2f0b0579c679424364fL1786

**Comment by AlexWaygood** [comment]
> Thanks Alex, there may also be line 1786 to revert, if we _really_ want to stick with the original intent.
> 
> https://github.com/python/cpython/pull/30179/files#diff-8a0f115fde6769c122b771b6d0eca184c4580f7b5fabe2f0b0579c679424364fL1786

Sure -- though I don't think the same argument applies for those lines? But, I'm happy to change that bit as well, if there's a reason to do so! 🙂 I'll mark this PR as "draft" for now.

**Review by gvanrossum — APPROVED** [review]
Thanks.

**Comment by AlexWaygood** [comment]
> Thanks.

No problem — sorry for the bother.

**Review by Fidget-Spinner — APPROVED** [review]
> > Thanks Alex, there may also be line 1786 to revert, if we _really_ want to stick with the original intent.
> > https://github.com/python/cpython/pull/30179/files#diff-8a0f115fde6769c122b771b6d0eca184c4580f7b5fabe2f0b0579c679424364fL1786
> 
> Sure — though I don't think the same argument applies for those lines? But, I'm happy to change that bit as well, if there's a reason to do so! 🙂 I'll mark this PR as "draft" for now.

Yeah, on second look, you're right, I think the new version improves on that example.

**Pull request merged**
