### PR TITLE
gh-97669: Remove outdated example scripts (#97675)

### PR DESCRIPTION
**Pull request by vstinner**
Remove outdated example scripts of the Tools/scripts/ directory:

* gprof2html.py
* md5sum.py
* nm2def.py
* pathfix.py
* win_add2path.py

Remove test_gprof2html, test_md5sum and test_pathfix of test_tools.

* Issue: gh-97669

### CODE REVIEW

**Comment by vstinner** [comment]
> gprof2html.py

Created in 2002 by @gvanrossum. Following changes are mostly coding styles changes, no feature or bugfix.

I didn't use gprof format for a long time. There are now many tools to profile programs with nice UI. I don't think that maintaining such tool in Python with a HTML output is still relevant today.

> md5sum.py

If someone wants such feature as part of Python, I would suggest to add a command line interface (CLI) to the hashlib module instead.

The script doesn't support multithreading, whereas Python releases the GIL in hashlib. The script uses the old ``getopt`` module.

@gvanrossum wrote in 2001:

> This is a trivial command line utility to print MD5 checksums.
> I published it on the web as http://www.python.org/2.1/md5sum.py
> so I thought I might as well check it in.

Well, I don't think that it's still relevant in 2022. There are now many ways to easily distribute Python scripts (pip, GitHub, whatever works).

> nm2def.py

```
Helpers to extract symbols from Unix libs and auto-generate
Windows definition files from them. Depends on nm(1). Tested
on Linux and Solaris only (-p option to nm is for Solaris only).
```

@malemburg: if you still use this script, it should be maintained outside Python. Python doesn't use it.

> pathfix.py

@hroncok: Script used by Fedora, see: https://discuss.python.org/t/remove-outdated-tools-scripts-scripts/19571/35

It can be maintained somewhere else.

> win_add2path.py

Not used by the Windows installer: https://discuss.python.org/t/remove-outdated-tools-scripts-scripts/19571/20

**Review by gvanrossum — APPROVED** [review]
Kill 'em with fire!

**Comment by learnwithsomya** [comment]
Hi @vstinner ,
Is there any alternate ways to use the `pathfix.py` or patch updates for consuming the file? Refer: https://gitlab.com/redhat/centos-stream/rpms/python3.14/-/blob/c10s/python3.14.spec?ref_type=heads#L1325

**Comment by gvanrossum** [comment]
> Is there any alternate ways to use the `pathfix.py` or patch updates for consuming the file?

Yes, by copying the script out of an old branch into your repo.

**Comment by vstinner** [comment]
>  Is there any alternate ways to use the pathfix.py or patch updates for consuming the file? Refer: https://gitlab.com/redhat/centos-stream/rpms/python3.14/-/blob/c10s/python3.14.spec?ref_type=heads#L1325

The python3.14.spec that you linked refers to `%{_rpmconfigdir}/redhat/pathfix.py` which gets `pathfix.py` from `/usr/lib/rpm/redhat/pathfix.py`. The file is installed by `python-rpm-macros` on my Fedora. So `pathfix.py` is now maintained by the [python-rpm-macros project](https://src.fedoraproject.org/rpms/python-rpm-macros/tree/rawhide).

The CentOS Stream package doesn't get `pathfix.py` from Python but from `python-rpm-macros`.

**Comment by vstinner** [comment]
Update: Ah, in fact `pathfix.py` is maintained in the [fedora-python/pathfix](https://github.com/fedora-python/pathfix) repository.

**Pull request merged**
