### PR TITLE
bpo-32773: added --option to allow changing the preserve_mode for copy_file()

### PR DESCRIPTION
**Pull request by jayyyin**
Original PR: https://github.com/python/cpython/pull/5584

I recreated the PR with a branch other than master since it was causing issues with my other attempts at pulling

https://bugs.python.org/issue32773

### CODE REVIEW

**Comment by jdemeyer** [comment]
My opinion maybe doesn't count much, but I would like to repeat what I said on [bpo-32773](https://bugs.python.org/issue32773):

I consider the current behaviour of preserving timestamps a *bug*. So I think that this should simply be fixed instead of adding an option. (And if you really do add an option, the default should be to *not* preserve timestamps.)

**Comment by jdemeyer** [comment]
Why does this patch only change `bdist_rpm`? There are many more places where `copy_file()` is called.

**Comment by jayyyin** [comment]
@jdemeyer could you point out where? I've been having trouble determining where...

**Comment by iritkatriel** [comment]
Closing the PR following the closure of its b.p.o issue (https://bugs.python.org/issue32773)

**Pull request closed without merging**
