### PR TITLE
bpo-40434: Update the reason why CPython doesn't have switch statements

### PR DESCRIPTION
**Pull request by amaajemyfren**
https://bugs.python.org/issue40434

### CODE REVIEW

**Review by remilapeyre — APPROVED** [review]

**Comment by amaajemyfren** [comment]
Thanks @remilapeyre for the approval. Kindly add the _skip news_ label and advise on the next steps please.

Thank you.

**Comment by remilapeyre** [comment]
> Kindly add the _skip news_ label and advise on the next steps please.
 The _skip news_ label will be added by a core developer that will make a second review of your PR and either ask for some changes or merge it :)

**Review by nanjekyejoannah — COMMENTED** [review]
@amaajemyfren , I commented on bpo but decided to put the same thought here. I understand the change but curious what is your reasoning on referencing just  one of the PEPs and not both of them?

**Comment by amaajemyfren** [comment]
Hi @nanjekyejoanna,

the statement initially said that there was _no consensus yet on how to do range tests_. This is not true because there is now a decision to not do range tests - that decision is _only_ in [PEP 3103](https://www.python.org/dev/peps/pep-3103/#abstract) and not in PEP 275 ([PEP 275](https://www.python.org/dev/peps/pep-0275/#rejection-notice) actually links to PEP 3103 to explain why it is rejected). My feeling is that putting two references complicates the goal of explaining it.

(This next part was added just to make the bot respond so please bear with me)

I was not expecting the Spanish Inquisition when I put up this PR.

**Comment by amaajemyfren** [comment]
I was not expecting the Spanish Inquisition.

**Review by nanjekyejoannah — COMMENTED** [review]
> PEP 275 actually links to PEP 3103 to explain why it is rejected

Well, am not very convinced if consensus was reached on range tests so I will refrain for someone else's opinion as it is not as apparent to me yet.

**Comment by CAM-Gerlach** [comment]
@iritkatriel Was this an accident? Seems like the section has been substantially updated, with these sentences eliminated and replaced with information about the new `match` statement.

**Comment by iritkatriel** [comment]
Thanks for checking and closing.

**Comment by CAM-Gerlach** [comment]
(N.B., Victor closed it 2 years ago, not me :)

**Comment by iritkatriel** [comment]
Ah, I thought this was the issue - I guess we can close that now: https://github.com/python/cpython/issues/84614

**Comment by CAM-Gerlach** [comment]
Ah, gotcha—didn't see the linked issue. Thanks!

**Pull request closed without merging**
