### PR TITLE
gh-93649: Split watcher API tests from _testcapimodule.c

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-93649

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
I think we can also move `class TestDictWatchers(unittest.TestCase):` from `test_capi/test_misc.py` to its own python file: `test_capi/test_dict_watchers.py`

**Comment by erlend-aasland** [comment]
> I think we can also move `class TestDictWatchers(unittest.TestCase):` from `test_capi/test_misc.py` to its own python file: `test_capi/test_dict_watchers.py`

That's a good idea.

**Review by vstinner — COMMENTED** [review]
First, I hesitated to suggest "dict" instead of "watchers", but it seems like there are *many* tests on dict watchers, so it's worth it to have separated files.

Can you rename watchers.c/py to dict_watchers.c/py?

I'm fine to leave the 4 other "dict" functions in _testcapi for now:

```
    {"test_dict_iteration",     test_dict_iteration,             METH_NOARGS},
    {"dict_getitem_knownhash",  dict_getitem_knownhash,          METH_VARARGS},
    {"dict_get_version", dict_get_version, METH_VARARGS},
    {"clear_managed_dict", clear_managed_dict, METH_O, NULL},
```

**Comment by erlend-aasland** [comment]
But there are also type watchers, and soon also function watchers. I figured all of these watcher APIs could live in the same place. Perhaps it will be too scattered with a new pair of files for each of these.

**Comment by vstinner** [comment]
Oh. I didn't notice that watchers are on different things. I was only aware of dict watchers.

**Comment by vstinner** [comment]
In this case, "watchers" is a perfect name.

**Comment by sobolevn** [comment]
I've opened https://github.com/python/cpython/issues/99544 about this crash.

**Pull request merged**
