### PR TITLE
gh-125684: Add `ARMv7` floating-point coprocessor support to `pymath.c`

### PR DESCRIPTION
**Pull request by rruuaanng**
For more to see: https://developer.arm.com/documentation/ddi0406/cb/System-Level-Architecture/System-Control-Registers-in-a-VMSA-implementation/VMSA-System-control-registers-descriptions--in-register-order/FPSCR--Floating-point-Status-and-Control-Register--VMSA?lang=en

* Issue: gh-125684

### CODE REVIEW

**Comment by rruuaanng** [comment]
Sorry. Please allow me to check the compatibility of the instruction again.

**Comment by skirpichev** [comment]
This pr doesn't solve any real issue (yet?), or did I miss something?  If this is a work in progress, please mark it as a draft.

**Comment by rruuaanng** [comment]
> This pr doesn't solve any real issue (yet?), or did I miss something?  If this is a work in progress, please mark it as a draft.

I found that there are actually many such fpu-supported functions in the code base, but in fact they are not used. I think I can add other relevant instruction support for this.

**Comment by skirpichev** [comment]
> I found that there are actually many such fpu-supported functions in the code base, but in fact they are not used.

Could you point to examples?

> I think I can add other relevant instruction support for this.

Which user problem this will solve?

**Comment by rruuaanng** [comment]
> Could you point to examples?

E.g. `_Py_get_387controlword`

> Which user problem will this solve?

On the arm platform, you can use this function to set FPU rounding error, Na value and so on.

**Comment by rruuaanng** [comment]
I'll close this PR. It seems that by ARMv7, 53-bit floating point support is already the default behavior. I apologize for the rudeness of opening this PR. Thanks for the review.

**Comment by skirpichev** [comment]
> E.g. _Py_get_387controlword

No, it's used in Python/pystrtod.c

**Pull request closed without merging**
