### PR TITLE
bpo-31670: Associate .wasm with application/wasm

### PR DESCRIPTION
**Pull request by flagxor**
https://bugs.python.org/issue31670

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by 92161898515** [comment]
👍

**Comment by flagxor** [comment]
Signed CLA.

**Comment by flagxor** [comment]
Advice appreciated on what to do with NEWS?
Seems like a minor change. Ideally would get picked to 2.7

**Comment by scotchka** [comment]
I think this qualifies for NEWS.

**Comment by brettcannon** [comment]
There is a CLA issue with this PR as @bradn123 is the author of the change and they have not signed the CLA due to not having a bugs.python.org account. If they can sign the CLA then we can let this PR in, otherwise we will need to close it for legal reasons.

**Comment by flagxor** [comment]
Ah, done with my other account, but no worries, it looks like someone else has fixed this:
https://github.com/python/cpython/commit/199a280af540e3194405eb250ca1a8d487f6a4f7

Closing.

**Pull request closed without merging**
