### PR TITLE
bpo-36168: Lowercase the word "subsequent" in get_value doc

### PR DESCRIPTION
**Pull request by kmoza**
Subsequent -> subsequent

https://bugs.python.org/issue36168

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by kmoza** [comment]
@Mariatta I have submitted my signed CLA today and tried to check the status of my CLA at https://check-python-cla.herokuapp.com/. However, the response from https://check-python-cla.herokuapp.com/ is "has not signed CLA" for my Github username. Could you help whether I am missing something or the status will be updated after a day.

**Comment by Mariatta** [comment]
CLA tales one business day to process. Please check again tomorrow. Thanks.

**Review by Mariatta — APPROVED** [review]
Thanks!

**Comment by Mariatta** [comment]
Thanks and congrats for your first contribution to CPython :taco:
This will be automatically merged once we receive the CLA. Please re-check the CLA in a day.

**Comment by CuriousLearner** [comment]
Hey @Mariatta 

This also needs a backport to 3.8 labels as per the issue.

**Pull request merged**
