### PR TITLE
bpo-46016: GHA Doc job now also runs "make check"

### PR DESCRIPTION
**Pull request by vstinner**
The GitHub Action documentation job now also runs "make check" to
check the documentation.

https://bugs.python.org/issue46016

### CODE REVIEW

**Comment by vstinner** [comment]
The second commit should be removed, it's just to trigger the Docs CI job.

**Comment by vstinner** [comment]
cc @tiran

**Comment by vstinner** [comment]
cc @JulienPalard

**Comment by vstinner** [comment]
Oh, the job failed when the `xvfb-run` command was run twice:

```
xvfb-run make -C Doc/ PYTHON=../python SPHINXOPTS="-q -W --keep-going -j4" check
xvfb-run make -C Doc/ PYTHON=../python SPHINXOPTS="-q -W --keep-going -j4" doctest
```

The second run failed with:

```
xvfb-run: error: Xvfb failed to start
```

I modified the config to only use `xvfb-run` to run `doctest`.

**Comment by vstinner** [comment]
> Docs / Docs (pull_request) Successful

Good. The 3 doc tests passed!

**Comment by vstinner** [comment]
I reverted `bpo-46016: Fix rest syntax of GH-29993 (GH-30006)` fix on purpose to make sure that GHA Doc job now catchs the bug.

**Comment by vstinner** [comment]
> I reverted [bpo-46016](https://bugs.python.org/issue46016): Fix rest syntax of GH-29993 (GH-30006) fix on purpose to make sure that GHA Doc job now catchs the bug.

Good! The new check catches the bug:

> Docs / Docs (pull_request) Failing

```
Run make -C Doc/ PYTHON=../python SPHINXOPTS="-q -W --keep-going -j4" check
make: Entering directory '/home/runner/work/cpython/cpython/Doc'
../python tools/rstlint.py -i tools -i ./venv -i README.rst
Error: [2] whatsnew/3.11.rst:335: default role used
```

**Comment by vstinner** [comment]
@tiran @JulienPalard: the PR works as expected, it's now awaiting for your review :-)

**Review by erlend-aasland — APPROVED** [review]

**Pull request merged**
