### PR TITLE
[3.5] bpo-34656: Avoid relying on signed overflow in _pickle memos (GH-9261)

### PR DESCRIPTION
**Pull request by vstinner**
(cherry picked from commit a4ae828ee416a66d8c7bf5ee71d653c2cc6a26dd)

https://bugs.python.org/issue34656

### CODE REVIEW

**Comment by vstinner** [comment]
Oh, FTP tests are failing on Travis CI :-( I should backport this fix:

```
commit c11b3b19a5b022c6c229043d37f9a9fd06f22500
Author: Victor Stinner <vstinner@redhat.com>
Date:   Wed Dec 5 01:58:31 2018 +0100

    bpo-35411: Skip test_urllib2net FTP tests on Travis CI (GH-10907)
    
    On Travis CI, FTP tests of test_urllib2net randomly fail with "425
    Security: Bad IP connecting".
    
    test.pythoninfo now also logs TRAVIS environment variable.
```

**Comment by vstinner** [comment]
> Oh, FTP tests are failing on Travis CI :-( I should backport this fix:

Done: I created PR #11874.

**Review by gpshead — APPROVED** [review]

**Comment by vstinner** [comment]
@larryhastings "ftplib.error_temp: 425 Security: Bad IP connecting." bites again, you need a new merge to get my FTP fix.

**Comment by larryhastings** [comment]
Thanks for the backported fix!  It does my heart good to see pickle avoiding integer overflows.

**Pull request merged**
