### PR TITLE
bpo-39184: Add audit events to command execution functions in os and pty modules

### PR DESCRIPTION
**Pull request by gousaiyang**
Add audit events to the following functions:

- os.exec*
- os.spawn*
- os.posix_spawn*
- os.startfile
- pty.spawn

https://bugs.python.org/issue39184

https://bugs.python.org/issue39184

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@gousaiyang

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by terryjreedy** [comment]
I was about to close this and tell you to start over with a new PR, but you seem to have corrected it.  In the future, do not hit the green [Make Pull Request] button unless the list of commits only has your commits and not those of others.  Also, fix the list of suggested reviewers when needed.

**Comment by gousaiyang** [comment]
Sorry about this, the review request was automatically triggered by the system. I messed up with this branch (should not fetch changes by others) and fixed it by force push.

**Comment by zooba** [comment]
Thanks! These look great!

**Pull request merged**
