### PR TITLE
bpo-31638: Add compression support to zipapp

### PR DESCRIPTION
**Pull request by zmwangx**
Add optional argument `compressed` to `zipapp.create_archive`, and add option `--compress` to the command line interface of `zipapp`.

https://bugs.python.org/issue31638

### CODE REVIEW

**Comment by pfmoore** [comment]
Looks good to me. I'm actually tempted to consider defaulting to uncompressed as a bug, and simply switch to compressing by default. (When I implemented this, I never even considered that uncompressed was the default for `ZipFile`).

@brettcannon what's your view on this? The only compatibility issue I can see would be for Pythons built without zlib support. Is that something we'd need to consider? And if so, would having an `--uncompressed` flag to request the old behaviour be sufficient?

**Comment by brettcannon** [comment]
The module needs to work with zlib not existing and it should default to uncompressed. I don't view adding a single boolean argument to a call burdensome if it makes people think about the trade-offs of compatibility and decompression overhead versus download/disk size.

**Comment by pfmoore** [comment]
OK, cool. Thanks for the clarification.

**Comment by pfmoore** [comment]
Thanks for the contribution, @zmwangx!

**Comment by zmwangx** [comment]
Thanks for the quick turnaround!

**Pull request merged**
