### PR TITLE
GH-117108: Set the "old space bit" to "visited" for all young objects 

### PR DESCRIPTION
**Pull request by markshannon**
When handling weakrefs, it is possible for objects to get moved from the young generation or pending old space in the visited old space.

By setting the "old space bit" (bit 0 of `_gc_next`) to matched the visited space, any young objects moved to the old generation without passing through the increment will have the old space bit set correctly.

The `handle_weakrefs` function can also move objects from the pending into the visited space, so we need to explicitly set the bit in that case.

This PR also adds more checks (in debug builds) that the old space bit is set correctly throughout cycle GC.

* Issue: gh-117108

### CODE REVIEW

**Comment by gvanrossum** [comment]
According to Mark, this should also fix the occasional [buildbot failures](https://github.com/python/cpython/issues/108362#issuecomment-2016583997).

**Comment by vstinner** [comment]
I confirm that this change fix the multiprocessing regression. I tested the change manually.

Moreover, buildbots didn't fail on this PR (triggered by `test-with-buildbots`).

> According to Mark, this should also fix the occasional https://github.com/python/cpython/issues/108362#issuecomment-2016583997.

I created PR gh-117252 to track the multiprocessing test_processes.test_thread_safety() failures. In fact, the test is skipped on GitHub CI because the "cpu" resource is disabled by `--fast-ci`, whereas it's enabled on buildbots with ``--slow-ci``.

I can easily reproduce the issue locally:

```
$ ./python -m test test_multiprocessing_spawn.test_processes -m test_thread_safety -v -u all -F
(...)
== resources: all
(...)
0:00:00 load avg: 1.44 Run tests sequentially
0:00:00 load avg: 1.44 [  1] test_multiprocessing_spawn.test_processes
test_thread_safety (test.test_multiprocessing_spawn.test_processes.WithProcessesTestFinalize.test_thread_safety) ...

python: Python/gc.c:321: gc_list_merge: Assertion `gc_list_is_empty(to) || gc_old_space(to_tail) == gc_old_space(from_tail)' failed.
Fatal Python error: Aborted

Current thread 0x00007fc41be006c0 (most recent call first):
  Garbage-collecting
  File "/home/vstinner/python/main/Lib/test/_test_multiprocessing.py", line 4631 in __init__
  File "__init__", line ??? in __init__
  File "/home/vstinner/python/main/Lib/test/_test_multiprocessing.py", line 4657 in make_finalizers
  File "/home/vstinner/python/main/Lib/threading.py", line 990 in run
  File "/home/vstinner/python/main/Lib/threading.py", line 1039 in _bootstrap_inner
  File "/home/vstinner/python/main/Lib/threading.py", line 1010 in _bootstrap
(...)
```

**With this change, the test no longer fails** with an assertion error:

```
$ ./python -m test test_multiprocessing_spawn.test_processes -m test_thread_safety -v -u all -F
(...)
== resources: all
(...)
0:00:54 load avg: 1.96 [ 13] test_multiprocessing_spawn.test_processes
test_thread_safety (test.test_multiprocessing_spawn.test_processes.WithProcessesTestFinalize.test_thread_safety) ... ok

----------------------------------------------------------------------
Ran 1 test in 4.243s

OK
(...)
```

**Review by vstinner — APPROVED** [review]
LGTM. While I don't fully understand all internals, the overall change LGTM. Also, I trust Mark to do the right thing.

If something goes wrong, we can still rework the code later. I prefer to merge the code right now to repair buildbots.

**Comment by vstinner** [comment]
@markshannon: Oh, this PR has a merge conflict. Maybe a conflict with the change commit 23e4f80ce2a2bac50acd1785e791316d5b578b8d. Would you mind to solve the merge conflict? I don't think that I can push changes to faster-cpython.

**Comment by markshannon** [comment]
Thanks @vstinner for reviewing this.

**Pull request merged**
