### PR TITLE
bpo-43322: Use consistent '#include' syntax in extn. tutorial

### PR DESCRIPTION
**Pull request by matthewhughes934**
Use the same format for Python header files

https://bugs.python.org/issue43322

### CODE REVIEW

**Comment by Blackpower1972** [comment]
https://github.com/python/cpython/pull/24820vstinner:urllib_basic_auth_regexLib/urllib/request the192.168.1.1/32https://github.com/python/cpython/pull/18284#issue-369132952[export http_proxy=http://alice.example.com:8080](https://github.com/python/cpython/pull/24838)

**Comment by Blackpower1972** [comment]
vstinner:urllib_basic_auth_regexLib/urllib/request.pyvstinner:urllib_basic_auth_regexexport http_proxy=http://alice.example.com:8080JunyiXie:fix/pymalloc_subinterpretervstinner:urllib_basic_auth_regexexport http_proxy=http://alice.example.com:8080

**Comment by iritkatriel** [comment]
There is a difference in C between these two formats. Are you suggesting this just for consistency or because you think the example is currently incorrect?

**Comment by matthewhughes934** [comment]
> There is a difference in C between these two formats. Are you suggesting this just for consistency or because you think the example is currently incorrect?

Purely for consistency. From what I understand the quotes will perform an implementation defined search then fallback to the (implementation defined) search method used by `<>`.

**Pull request closed without merging**
