### PR TITLE
move Codecov configuration under .github

### LINKED ISSUE #80: Move Codecov configuration under .github
Codecov says the [file can live anywhere](https://docs.codecov.io/docs/codecov-yaml#section-can-i-name-the-file-codecov-yml-), so we might as well move it out of the way.

### PR DESCRIPTION
**Pull request by morrme**
closes: https://github.com/python/core-workflow/issues/80

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by brettcannon** [comment]
Could you also drop the leading `.` from the name? That way it matches `appveyor.yml`.

**Comment by brettcannon** [comment]
While this doesn't really require signing the CLA, @morrme , it would be great if you could for future contributions. 😄

**Comment by morrme** [comment]
@brettcannon will do! waiting for that process to complete shouldn't delay this PR, right?

**Comment by brettcannon** [comment]
@morrme nope, the hold-up is on me just simply being busy with the run-up to PyCon US.

**Comment by morrme** [comment]
@brettcannon oh, cool..... just wanted to make sure i wasn't delaying things.  enjoy PyCon! I wish I could be there!

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
Thanks for the PR, @morrme !

**Pull request merged**
