### PR TITLE
bpo-39712: Cross reference env. vars and -X command line options

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue39712

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Updated with NEWS entry.

**Comment by erlend-aasland** [comment]
@pitrou, would you mind reviewing this?

**Comment by erlend-aasland** [comment]
It was closed because I did not have the bandwidth to follow it up. I do not plan to re-open it, as I have other CPython priorities nowadays. I do think it would be nice to fix this, so feel free to pick it up.

**Comment by erlend-aasland** [comment]
BTW, my fork is still there; I use it daily.

**Comment by furkanonder** [comment]
> BTW, my fork is still there; I use it daily.

Ahh, my mistake, I couldn't reach the [branch](https://github.com/erlend-aasland/cpython/tree/fix-issue-39712) when I clicked, I thought you deleted the repo instead of the branch.

**Pull request closed without merging**
