### PR TITLE
bpo-35240: Travis CI runs doctest without XVFB_RUN

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue35240

### CODE REVIEW

**Comment by vstinner** [comment]
I don't see the point of running "make doctest" with xvfb-run.

I guess that it was copied/pasted when "make doctest" has been added to Travis CI by @matrixise in .travis.yml: commit 859c068e52a31e13e2b9bb6a3f861fa8c290cb0e.

To run the Python test suite, xvfb-run makes sense since multiple tests run a GUI.

**Comment by vstinner** [comment]
Oh, doctest failed on Travis CI :-(

```
Warning, treated as error:
**********************************************************************
Line 12, in default (setup code)
Failed example:
    from turtle import *
    turtle = Turtle()
Exception raised:
    Traceback (most recent call last):
```

**Comment by JulienPalard** [comment]
The current `make doctest` needs an X server to test turtle so this PR is currently failing with:

        _tkinter.TclError: no display name and no $DISPLAY environment variable

But this can be gracefully muted, like we're currently disabling those same tests when we can't import tkinter, in Docs/config.py check for:

```
doctest_global_setup = '''
try:
    import _tkinter
except ImportError:
    _tkinter = None
'''
```

**Comment by vstinner** [comment]
I was wrong. PR #10753 seems to be a better option.

**Pull request closed without merging**
