### PR TITLE
bpo-40600: Disallow loading extension modules load more than once in per interpreter.

### PR DESCRIPTION
**Pull request by shihai1991**
* Add _PyState_AddSingleModule() and _PyState_FindSingleModule() in pystate.c.
* Add `Py_MODFLAGS_SINGLE` of module flags

Co-authored-by: Dong-hee Na <donghee.na92@gmail.com>

https://bugs.python.org/issue40600

### CODE REVIEW

**Comment by shihai1991** [comment]
@corona10 Hi, Dong-hee Na. Do you mind I copied your testcase `test_multiple_loading_on_subinterpreter` in here?(ps: I added you as a co-author in here ;))

**Comment by corona10** [comment]
@shihai1991 Thanks!

**Review by vstinner — CHANGES_REQUESTED** [review]
I'm not 100% sure that we really need this feature: see https://bugs.python.org/issue40600 discussion.

**Comment by encukou** [comment]
This is solved in a different way in bpo-42639.
Thank you for working on this issue, even though this PR didn't make it in!

**Pull request closed without merging**
