### PR TITLE
bpo-45754: Use correct SQLite limit when checking statement length

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue45754

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @serhiy-storchaka

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by erlend-aasland** [comment]
FYI: The `AMD64 FreeBSD Shared PR` buildbot failed `test_gdb`. It has been doing so for a while, so it is probably unrelated.

**Comment by pablogsal** [comment]
> FYI: The `AMD64 FreeBSD Shared PR` buildbot failed `test_gdb`. It has been doing so for a while, so it is probably unrelated.

I fixed that today

**Comment by erlend-aasland** [comment]
> I fixed that today :)

Yay :) Thanks for merging.

**Pull request merged**
