### PR TITLE
bpo-33421: Add AsyncContextManager to typing module documentation.

### PR DESCRIPTION
**Pull request by twavv**
https://bugs.python.org/issue33421

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Review by ilevkivskyi — APPROVED** [review]
LGTM. Thank you for adding this!

**Comment by ilevkivskyi** [comment]
Oh, wait. why are you making the PR to the 3.6 branch? It looks like this also needs to be added to 3.7 and master. Could you please close this one and re-open w.r.t. master branch? I will then merge and backport to other relevant branches (this is how things are normally done here).

**Comment by travigd** [comment]
Okay, I'll mention you in the new pull request.

**Comment by travigd** [comment]
Actually, 3.7+ has `contextlib.AbstractAsyncContextManager` but  3.6 has no such equivalent. Should the documentation for 3.6 and 3.7 be different? The rest of the documentation tends to be along the lines of 
```rst
   A generic version of ...
```
so for 3.7 we could say
```rst
A generic version of :class:`contextlib.AbstractAsyncContextManager`.
```
but not for 3.6.

In fact, seems 3.6 has [some weird dodging around the absence of `contextlib.AbstractAsyncContextManager`](https://github.com/python/cpython/blob/3.6/Lib/typing.py#L1972).

**Pull request closed without merging**
