### PR TITLE
gh-128201: Fix ``DeprecationWarning`` in ``Lib/test/test_pdb.py``

### PR DESCRIPTION
**Pull request by Eclips4**
* Issue: gh-128201

### CODE REVIEW

**Comment by hugovk** [comment]
If `asyncio.set_event_loop_policy` is deprecated, what should end users call instead? Presumably not `asyncio._set_event_loop_policy`?

Can we also call the replacement?

**Comment by Eclips4** [comment]
Initially I was thinking about a "default way" to fix that `DeprecationWarning` by rewriting code to avoid using deprecated things.
But after looking at https://github.com/python/cpython/pull/128024 I changed my mind. 

This one was accidentally omitted in https://github.com/python/cpython/pull/128024:
* Line 2135
* Line 2256
* Line 2356

**Comment by gaogaotiantian** [comment]
Okay I think the fix is okay at this point. However, is there an asyncio expert that can take a look at the testing code and see if this line is even needed? As there's no explicit code to change the policy. The testing code is pretty trivial, will a `new_event_loop` change the policy? Why do we need to set it back to default in the first place?

**Comment by kumaraditya303** [comment]
> Okay I think the fix is okay at this point. However, is there an asyncio expert that can take a look at the testing code and see if this line is even needed? As there's no explicit code to change the policy. The testing code is pretty trivial, will a new_event_loop change the policy? Why do we need to set it back to default in the first place?

For pdb tests, `asyncio.run` could be used instead of `asyncio.new_event_loop` as that would take care of policy stuff internally. 
AFAICS pdb doesn't mess around the policy stuff so migrating of all tests to use newer `asyncio.run` or `asyncio.Runner` seems worthwhile.

**Review by kumaraditya303 — APPROVED** [review]

**Comment by graingert** [comment]
This isn't correct, it should be `asyncio.run(main(), loop_factory=asyncio.EventLoop)` otherwise run will set the policy which will leak into other threads

**Comment by kumaraditya303** [comment]
> This isn't correct, it should be asyncio.run(main(), loop_factory=asyncio.EventLoop) otherwise run will set the policy which will leak into other tests

This isn't so much about correctness, the point is that our test infra doesn't check for policy in pdb tests so omitting loop_factory doesn't makes any difference.

**Comment by graingert** [comment]
ah then pdb tests need an extra test isolation check, that checks that the policy has been restored to None

**Pull request merged**
