### PR TITLE
GH-77609: Support following symlinks in `pathlib.Path.glob()`

### PR DESCRIPTION
**Pull request by barneygale**
Add support for `***` wildcard in `pathlib.Path.glob()` and `rglob()`. This wildcard works like `**`, except that it also recurses into symlinks.

See *Recursive Globbing* in the [zshexpn manpage](https://linux.die.net/man/1/zshexpn) for prior art.

Alternative to #102616

* Issue: gh-77609

### CODE REVIEW

**Comment by barneygale** [comment]
Marking as a draft because it would be good to land #104292 and #104141 first.

**Comment by barneygale** [comment]
I don't think the current behaviour is _wrong_, just difficult to optimize. With this PR, users would be able to recursively walk symlinks, and we'd be able to optimize `***/*.py` later on (but not `**/*.py`). Still, I'm not convinced this is the right way forward.

**Comment by zooba** [comment]
> Still, I'm not convinced this is the right way forward.

I'm surprised, because you closed the other PR saying you _were_ convinced this was the way forward.

Personally, I preferred the other way. It's a bit more work, but in ~5 years time we'll have forgotten about it and will just have sensible defaults. Adding this way and leaving the other one leaves us with two warts (okay, maybe 1.5, if people _like_ this, but I feel like special patterns specifically for symlinks is too much).

**Comment by barneygale** [comment]
> > Still, I'm not convinced this is the right way forward.
> 
> I'm surprised, because you closed the other PR saying you _were_ convinced this was the way forward.

I know. I literally changed my mind again last night while playing around with the `glob()` implementation! :P

> Personally, I preferred the other way. It's a bit more work, but in ~5 years time we'll have forgotten about it and will just have sensible defaults. Adding this way and leaving the other one leaves us with two warts (okay, maybe 1.5, if people _like_ this, but I feel like special patterns specifically for symlinks is too much).

:+1: fair point, thanks for the advice.

**Comment by barneygale** [comment]
Closing in favour of #102616

**Pull request closed without merging**
