### PR TITLE
Fix typo in Lib/concurrent/futures/thread.py

### PR DESCRIPTION
**Pull request by ubordignon**
Changed "an" to "a".

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by tirkarthi — COMMENTED** [review]
Similar wording in `ProcessPoolExecutor` docstring : https://github.com/python/cpython/blob/408a2ef1aceff1f4270c44552fa39ef93d9283e3/Lib/concurrent/futures/process.py#L508

**Comment by ubordignon** [comment]
> cpython/Lib/concurrent/futures/process.py

I added the correction to a new commit.
I signed di CLA referencing my GitHub account. Should I also register on bpo? I hear you're moving over to GitHub.

**Review by tirkarthi — APPROVED** [review]
LGTM. I would prefer a review from a native English speaker too. Fixing typos don't require CLA signing but I will leave it to core dev merging this. Thanks for the PR.

**Comment by csabella** [comment]
@ubordignon, welcome to CPython and thank you for your contribution.    :tada:

**Comment by ubordignon** [comment]
Thanks a lot!

**Pull request merged**
