### PR TITLE
bpo-37148: Fix asyncio test that check for warning when running the test suite with huntleaks

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue37148

### CODE REVIEW

**Comment by pablogsal** [comment]
Tested locally:

```
❯ ./python.exe -m test test_asyncio -m test_stream_writer_create_warning -R :
Run tests sequentially
0:00:00 load avg: 1.96 [1/1] test_asyncio
beginning 9 repetitions
123456789
.........

== Tests result: SUCCESS ==

1 test OK.

Total duration: 1 sec 975 ms
Tests result: SUCCESS
```

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
@pablogsal there is another PR for improving streams tests stability: https://github.com/python/cpython/pull/13790
I'd like to merge it but waiting for review

**Comment by pablogsal** [comment]
Thanks, @asvetlov, I will try to review it as soon as I merge this and unblock the refleaks buildbots to allow beta1 release (they are still red as of now).

**Comment by ambv** [comment]
@pablogsal: https://buildbot.python.org/all/#/builders/168/builds/1150

**Comment by vstinner** [comment]
> @pablogsal: https://buildbot.python.org/all/#/builders/168/builds/1150

This failure is unrelated to this fix. It will be fixed by https://github.com/python/cpython/pull/13790 which has just been merged ;-) (but not part of this build)

**Comment by tirkarthi** [comment]
There is a `test__xxsubinterpreters` in the build for #13790 : https://buildbot.python.org/all/#/builders/168/builds/1151/steps/5/logs/stdio

```
======================================================================
FAIL: test_still_running (test.test__xxsubinterpreters.DestroyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test__xxsubinterpreters.py", line 765, in test_still_running
    interpreters.destroy(interp)
AssertionError: RuntimeError not raised
----------------------------------------------------------------------
Ran 112 tests in 30.951s
FAILED (failures=1, skipped=5)
test test__xxsubinterpreters failed
```

**Comment by vstinner** [comment]
@tirkarthi: Please open a new issue on bugs.python.org, this issue is unrelated.

**Pull request merged**
