### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by xyb**

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Review by sobolevn — APPROVED** [review]
Thanks!

**Review by sobolevn — CHANGES_REQUESTED** [review]
Looks like `help.html` file is generated from:

```
Help => IDLE Help: Display help.html with proper formatting.
Doc/library/idle.rst (Sphinx)=> Doc/build/html/library/idle.html
(help.copy_strip)=> Lib/idlelib/help.html
```

**Review by sobolevn — APPROVED** [review]

**Comment by xyb** [comment]
> @xyb would you please create manual backport PRs?

Sure, I'll be working on it soon.

**Comment by terryjreedy** [comment]
Sorry, my networking was down for a week.  Thanks for doing the backports.  I am looking at the help.html issue.

**Review by SamyDgz — APPROVED** [review]

**Pull request merged**
