### PR TITLE
bpo-23544: Disable IDLE Stack Viewer when running user code

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Starting stack viewer when user code is running hangs IDLE.

https://bugs.python.org/issue23544

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
An alternative fix would be to use a method like `EditorWindow.right_menu_event()`, where individual methods are specified via `verify_state` for submenu items.

**Comment by taleinat** [comment]
I like this approach!

I suggest also moving the check for the existence of `sys.last_traceback` from `open_stack_viewer()` to the postcommand, which would allow removing a nice chunk of error handling code there.

**Comment by taleinat** [comment]
Currently, selecting "Debug -> Stack Viewer" also fails if a successful command was last run, or even just an empty statement. If fails after a small delay and just sounds the bell rather than displaying an error box. Ideally, we would recognize that case as well and have the menu option disabled in such cases.

**Review by terryjreedy — APPROVED** [review]
I changed index patterns to not care about trivial changes, such as 'Stack Viewer' to 'Stack viewer' and to fail given inconsistent menu and pattern changes.  I manually tested that everything works.

I will merge this when CI passes to fix hangs (user code executing) and crashes (Debugger active).   I would test and likely merge a new patch to allow a stack viewer anytime.  If either of you decide to do it, open and issue and say so.

**Comment by terryjreedy** [comment]
splat from unrelated 3 tests failed:
test_gdb test_subprocess test_venv

**Pull request merged**
