### PR TITLE
bpo-46906: Mention native endian in PyFloat_Pack8() doc

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue46906

### CODE REVIEW

**Comment by vstinner** [comment]
@JelleZijlstra @mdickinson: It seems like PR #31832 wording was confusing, so here is a different wording. Is it **less** confusing?

**Review by mdickinson — APPROVED** [review]
This looks fine to me. @JelleZijlstra?

**Review by JelleZijlstra — APPROVED** [review]
Thanks!

**Comment by vstinner** [comment]
I hesitated to add a new dedicated documentation for the PY_BIG_ENDIAN macro, but I didn't find any good place for it. So I documented it where it's mentioned, in the float docs.

Thanks for the review.

IMO the magic macro is less surprising with the documentation about its value.

**Pull request merged**
