### PR TITLE
[2.7] bpo-34836: fix test_default_ecdh_curve, needs no tlsv1.3.

### PR DESCRIPTION
**Pull request by xnox**
https://bugs.python.org/issue34836

https://bugs.python.org/issue34836

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by tiran** [comment]
The patch looks good to me. Please include a news entry.

**Comment by xnox** [comment]
@tiran added a NEWS entry, hopefully correctly.

**Comment by xnox** [comment]
What can I do to get this reviewed / merged? I do not understand the current state of this PR.

**Comment by encukou** [comment]
I changed the title to make the bot happy.
But an SSL expert (like @tiran) should merge this. I'm not brave enough to do it.

**Review by ncoghlan — APPROVED** [review]
@tiran already reviewed the test change above, it was just pending the NEWS entry.

**Pull request merged**
