### PR TITLE
bpo-40328: Add tool for generating cjk mapping headers

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue40328

### CODE REVIEW

**Comment by corona10** [comment]
@vstinner
If this repository would not be a proper place to store files under tool/data
Is it okay to create a new repository for this? 
The file can be broken and loose when the times are passed.

**Review by vstinner — COMMENTED** [review]
I would prefer to put this script in Tools/unicode/ and don't store Unicode files in Modules/cjkcodecs/tools/data/CP932.TXT, but always download them: as done by Tools/unicode/makeunicodedata.py or some unit tests.

**Review by corona10 — COMMENTED** [review]
@vstinner Please take a look :)

**Comment by corona10** [comment]
@methane @serhiy-storchaka  
Also, Can you please take look at this PR?

**Comment by methane** [comment]
I don't have time to understand the script.  I only confirmed that this pull request doesn't change the mapping header files.

**Comment by corona10** [comment]
@methane 
Thank you Naoki San!
The main objective of this PR is generating the same mapping header files :)
For example, we can make some change with this script when
something needs to change about supporting Japanese.
(I don't know the practical case)

**Comment by corona10** [comment]
@vstinner Can we merge this PR?

**Review by vstinner — COMMENTED** [review]
Should we run this script in "make regen-all"? Or do you expect that these generated files will never ever change?

Currently, "make regen-all" has no 3rd party dependencies, whereas this script requires to download files from the Internet. In my experience, any additional external dependency makes Python CIs less stable :-(

Other "unicode scripts" are no run by "make regen-all", so I think that it's fine.

**Comment by vstinner** [comment]
@corona10: I let you decide if you are confident enough to merge this PR with no review.

Since this script is not run by any CI and only run manually, I don't see any risk of regression.

It seems like "Unicode experts" (including me) don't have the bandwidth to review your change.

**Pull request merged**
