### PR TITLE
bpo-24746: Avoid stripping trailing whitespace in doctest fancy diff

### PR DESCRIPTION
**Pull request by CuriousLearner**
https://bugs.python.org/issue24746

### CODE REVIEW

**Comment by CuriousLearner** [comment]
Hello @bitdancer @tim-one 

Can you please have a look at this patch?

**Review by orsenthil — APPROVED** [review]
This looks good to me. I followed the patch, and discussion in https://bugs.python.org/issue24746

**Comment by orsenthil** [comment]
Thank you, @CuriousLearner !

**Comment by orsenthil** [comment]
@CuriousLearner  - Will you be willing to create the backport? If you get to it before me, please ping me on that PR.

**Comment by CuriousLearner** [comment]
Hey @orsenthil 

Yes, I'm on it.

I started with `cherry_picker cbb16459934eaf29c7c7d362939cd05550b2f21f 2.7`
resolved the conflict, committed it, and now on the final step `cherry_picker --continue`, but it is taking really long, and it seems like it hung up.

I'll keep you posted!

If the last `cherry_picker --continue` succeeds, I'll tag you in another PR.

**Pull request merged**
