### PR TITLE
gh-116145: Updated bundled Tcl/Tk on Windows to 8.6.14

### PR DESCRIPTION
**Pull request by zooba**
* Issue: gh-116145

### CODE REVIEW

**Comment by terryjreedy** [comment]
@chrstphrchvz knows about tcl/tk changes.
@serhiy-storchaka is tkinter/ttk code and test maintainer.

Windows x86 test https://github.com/python/cpython/actions/runs/8349119889/job/22852588108?pr=117030

test tkinter 2 failures:

======================================================================
FAIL: test_itemconfigure (test.test_tkinter.test_widgets.ListboxTest.test_itemconfigure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_tkinter\test_widgets.py", line 1002, in test_itemconfigure
    self.assertEqual(widget.itemconfigure(0, 'background'),
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     ('background', 'background', 'Background', '', 'red'))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Tuples differ: ('background', '', '', '', 'red') != ('background', 'background', 'Background', '', 'red')

First differing element 1:
''
'background'

- ('background', '', '', '', 'red')
+ ('background', 'background', 'Background', '', 'red')

======================================================================
FAIL: test_configure_tabs (test.test_tkinter.test_widgets.TextTest.test_configure_tabs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_tkinter\test_widgets.py", line 662, in test_configure_tabs
    self.checkParam(widget, 'tabs', '10.2 20.7 1i 2i',
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    expected=('10.2', '20.7', '1i', '2i'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\test\test_tkinter\widget_tests.py", line 50, in checkParam
    self.assertEqual2(widget[name], expected, eq=eq)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\test\test_tkinter\widget_tests.py", line 34, in assertEqual2
    self.assertEqual(actual, expected, msg)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Tuples differ: (10.2, 20.7, <string object: '1i'>, <string object: '2i'>) != ('10.2', '20.7', '1i', '2i')


*** test audit 1 failure, lines 980-1070: Broken pipe error
I know nothing about this.  It passed on rerun, same fail, OK on x64, no failure on free-threading builds.
Perhaps ignore for now.

*** test_ttk failed (8 failures) lines 1384-1905
All are same quoting issue: actual `(0,)` expected as `('0',)`.

**Review by zware — APPROVED** [review]

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by zooba** [comment]
The macOS change was not backported to 3.12. I don't remember whether we'd consider this a bugfix or a suitable-for-post-beta-pre-RC change, but I'm happy enough to leave it to 3.13 only.

**Comment by serhiy-storchaka** [comment]
8.6.14 is a bugfix release. Is there a way for Windows users to update the Tcl/Tk version independently?

**Comment by zooba** [comment]
Better discuss on the issue, since the macOS maintainers are almost certainly not watching this PR.

**Pull request merged**
