### PR TITLE
bpo-37250: define tp_print for backwards compatibility

### PR DESCRIPTION
**Pull request by jdemeyer**
bugfix for 3.8, so needs backport.

https://bugs.python.org/issue37250

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
Cython cannot be fixed instead? I am not sure that I like reintroducing tp_print, it is unused for 10 years...

**Comment by jdemeyer** [comment]
> Cython cannot be fixed instead?

This is being discussed at bpo-37221, please discuss there.

**Comment by vstinner** [comment]
Please open a separated issue, https://bugs.python.org/issue37221 is about PyCode_New

**Comment by vstinner** [comment]
I created https://bugs.python.org/issue37250

**Comment by jdemeyer** [comment]
Rejected on bpo-37250

**Pull request closed without merging**
