### PR TITLE
bpo-35321: Set the spec origin to frozen in frozen modules

### PR DESCRIPTION
**Pull request by nnja**
This fix correctly sets the spec origin to
"frozen" for the _frozen_importlib module. Note that the
origin was already correctly set in _frozen_importlib_external.

https://bugs.python.org/issue35321

### CODE REVIEW

**Comment by vstinner** [comment]
Are you sure that this PR is related to https://bugs.python.org/issue35537?

**Comment by nnja** [comment]
@vstinner drat, copied and pasted the wrong issue number. It's actually https://bugs.python.org/issue35321. I updated the commit message, GitHub issue title & message.

**Comment by maggyero** [comment]
@nnja Thank you for this PR!

**Review by warsaw — APPROVED** [review]
Thanks for the PR @nnja - LGTM.

**Comment by warsaw** [comment]
I added the backport tags for 3.7 and 3.6, but I'd like to get @ned-deily 's take on that.

**Comment by ned-deily** [comment]
AFAICT this is not a 3.6 regression: the behavior has been around for a long time. Even though it is minor and the risk of breakage is small, the benefit seems to be also small.  My take is that this doesn't meet the criteria for a security-fix-only branch so it should not go into 3.6 or earlier.  Sorry!

**Comment by warsaw** [comment]
Thank you @ned-deily - we'll just back port this to 3.7.

**Comment by nnja** [comment]
I have a question about how to backport this into 3.7. 

I used the `cherry_picker` tool to try to apply this commit to 3.7. When I looked at the merge conflict
I realized it's in `Python/importlib.h` which is the generated header file for this frozen module. 

As expected, this file has irresolvable conflicts. 

What's the process for this type of backport?

**Comment by warsaw** [comment]
I'm not sure this is the right way to do it (does the devguide provide any help?).  What I generally do is to use the tool to do the merge in the older branch, then revert `Python/importlib.h`, then `make regen-importlib` to get a proper `importlib.h`.  Then that's the branch I propose for merging.

I wonder if @Mariatta has any thoughts on adding this to @miss-islington by default?

**Comment by Mariatta** [comment]
you can resolve the conflict manually (regenerate the files) and the do `cherry_picker --continue`.

Currently miss-islington can't do this automatically. There is open ticket here: https://github.com/python/miss-islington/issues/41.

**Comment by nnja** [comment]
I'll try this approach and follow up if I run into any issues. Thank you @Mariatta and @warsaw!

**Pull request merged**
