### PR TITLE
gh-103323: Remove current_fast_get() unused parameter

### PR DESCRIPTION
**Pull request by vstinner**
The current_fast_get() static inline function doesn't use its 'runtime' parameter, so just remove it.

* Issue: gh-103323

### CODE REVIEW

**Comment by vstinner** [comment]
@ericsnowcurrently @colesbury @corona10: Would you mind to review this change?

The change commit f8abfa331421e2c28388c5162f37820495e3c2ee modified current_fast_get(). Before the Python Thread State was retrieved from runtime, but it's no longer the case.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

IIRC, the main reason I left the parameter was to reduce churn.  After that I didn't see any harm in leaving the parameter.  That said, I'm not opposed to dropping it.

**Review by colesbury — APPROVED** [review]
This looks more straightforward to me too

**Review by corona10 — APPROVED** [review]
lgtm

**Pull request merged**
