### PR TITLE
gh-104469 Convert _testcapi/float.c to use AC

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-104469

### CODE REVIEW

**Comment by corona10** [comment]
This is the sample PR but if the https://github.com/python/cpython/issues/104469 is rejected, I will close the PR.

**Review by sobolevn — COMMENTED** [review]
LGTM! From my point of view, this is indeed an improvement 👍

**Comment by corona10** [comment]
> LGTM! From my point of view, this is indeed an improvement 👍

Thank you, let's wait for @erlend-aasland 's opinion too. 
He is AC expert these days, and I also expect feedback which kinds of things are not to be converted.

**Review by erlend-aasland — APPROVED** [review]
This is nice. Less boilerplate code in the tests is a good thing IMO.

**Pull request merged**
