### PR TITLE
gh-115816: Improve internal symbols API in optimizer

### PR DESCRIPTION
**Pull request by gvanrossum**
This isn't ready, but for @Fidget-Spinner and @markshannon to know what I'm working on.

* Issue: gh-115816

### CODE REVIEW

**Comment by gvanrossum** [comment]
@Fidget-Spinner Do you have time to review?

**Comment by gvanrossum** [comment]
FWIW the CI failure seems unrelated, it's homebrew being difficult (see #build channel on Discord).

**Comment by Fidget-Spinner** [comment]
I can review but it seems you messed up the merge.

**Comment by gvanrossum** [comment]
Let me create a new PR.

**Comment by gvanrossum** [comment]
See gh-116028 instead.

**Review by axizqayum686 — APPROVED** [review]
axizqayum686@gmail.com

**Pull request closed without merging**
