### PR TITLE
bpo-27639: slices of UserLists should be instances of UserList

### PR DESCRIPTION
**Pull request by vaultah**
https://bugs.python.org/issue27639

### CODE REVIEW

**Comment by vaultah** [comment]
I noticed that `__init__` creates an unnecessary copy of `initlist.data`:

    self.data[:] = initlist.data[:]

and `__iadd__` converts its second argument to `list` in some cases:

    self.data += list(other)

I removed the slice part from the former, but I'm wondering if `self.data += list(other)` has any advantages over `self.data += other`.

**Comment by methane** [comment]
LGTM.

@vaultah Could you add your name in `Misc/ACKS`, and add "Patch by <Your Name>" in NEWS entry?

@rhettinger Would you review this?

**Comment by vaultah** [comment]
My name is already in `Misc/ACKS`. I'm not interested in updating this patch. If it's possible, you may merge it without a name.

**Comment by mblahay** [comment]
:( I'm sorry, didn't know this was out there since it wasn't attached to the ticket. Will review what you have done as it seems to be more than what Erick Cervantes and I had and will use what is valid. Most of all, I will make sure your name is listed some where as contributing to this, as soon as I find out where that some where is. Thank you for your efforts!

**Comment by mblahay** [comment]
I have reviewed the changes and it in addition to resolving the problem stated in ticket 27639, there are two other changes. One, in __init__, you identify above. My team agrees that this change is a good performance improver. 

The second one involves what appears to be a modification to __setitem_ that corresponds to the modification to __getitem__. The problem is that it is unclear why __setitem__ needs to be modified. It works fine without any changes. Vaultah, I would very much like for you to explain it to me.

**Pull request closed without merging**
