### PR TITLE
gh-78318: Add pathlib.Path.lexists and related

### PR DESCRIPTION
**Pull request by nphilipp**
This adds the `follow_symlink` parameter to `pathlib.Path.exists()`,
and wraps the new functionality in `pathlib.Path.lexists()`, analogous
to `os.stat()` ./. `os.lstat()` and `os.path.exists()` ./.
`os.path.lexists()`.

Signed-off-by: Nils Philippsen <nils@tiptoe.de>

* Issue: gh-78318

### CODE REVIEW

**Comment by barneygale** [comment]
This looks fine to me (note: I'm just some guy, not a core dev)

I'd argue that we're adding two ways to do the same thing (`exists(follow_symlinks=False)` and `lexists()`), where the former is more explicit, and so the addition of `lexists()` is unnecessary.

**Review by kadirselcuk — APPROVED** [review]

**Comment by nphilipp** [comment]
@barneygale You're right that `.lexists()` just wraps `.exists(follow_symlinks=True)`. I put it in to have the same symmetry as with `.chmod()`/`.lchmod()` and `.stat()`/`.lstat()`. If we'd rather have both methods without parameters, I guess the implementation could be moved to a protected method and `.exists()` become a wrapper like `.lexists()` but if it's all the same I'd leave it as it is.

**Comment by nphilipp** [comment]
Resolving conflicts.

**Comment by barneygale** [comment]
The difference is that `lchmod` and `lstat` are bona fide system calls, whereas `lexists` isn't.

**Comment by nphilipp** [comment]
I think you mean that they are standard library calls, neither have been syscalls in a long while (at least on Linux). My motivation, however, wasn't to make people coming from a POSIX-compliant C library "feel at home", but old fogies like me who're used to the `os.path` API. Anyway, some tests are failing, so there's work for me to do.

**Comment by barneygale** [comment]
I'm still -1 on this, per Zen of Python's "There should be one -- and preferably only one -- obvious way to do it."

I'd rather we didn't have `lstat()` or `lchmod()` either, for the record :)

**Comment by AlexWaygood** [comment]
> I'm still -1 on this, per Zen of Python's "There should be one -- and preferably only one -- obvious way to do it."
> 
> I'd rather we didn't have `lstat()` or `lchmod()` either, for the record :)

Ah, I misinterpreted your "This looks fine to me" earlier comment :)

In that case, let's close this. There seems to have been little interest in the issue or the PR in the four-and-a-half years since the issue was opened, and the bar for additions to the stdlib is (quite rightly) high.

Thanks for the PR @nphilipp -- I hope this doesn't discourage you from contributing to CPython in the future!

**Pull request closed without merging**
