### PR TITLE
bpo-42685: Improve placing of simple query windows.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
* If parent is specified and mapped, the query widget is
  centered at the center of parent. Its position and size
  can be corrected so that it fits in the virtual root window.
* Otherwise it is centered at the center of the screen.

https://bugs.python.org/issue42685

### CODE REVIEW

**Comment by terryjreedy** [comment]
When checking code, IDLE changed focus to Shell in case there are warning messages.  (I want to change this, but...)  If there is a syntax error, current code calls messagebox.showerror and tries to put focus on the editor.  The latter raised the editor over Shell but focus remains on the modal messagebox until it is dismissed.  Error box is centered.  After I put the focus line first, nothing changes.  Should it?  Is not a visible focused parent 'mapped'?  idlelib.runscript 206/7.
```
        self.editwin.text.focus_set()
        tkMessageBox.showerror(title, message, parent=self.editwin.text)
```

**Comment by terryjreedy** [comment]
I have read the code but not checked it in detail.  It does center 'Tab width' and I consider this a better default position even if not the best for this particular box.  The 5 types of query.Query boxes are centered and I am satisfied with that and have never considered moving any of them.

**Comment by serhiy-storchaka** [comment]
Dialogs in `commondialog` are implemented in Tk and may use native OS dialogs. They are out of control Tkinter and may be out of control of Tk. Dialogs in `simpledialog` are implemented in Python and try to mimic dialogs in `commondialog` (more or less).

This PR just adds the code used to place native Tk dialogs rewritten to Python.

**Comment by serhiy-storchaka** [comment]
Moved the code to separate function (which corresponds Tk private function `:tk:PlaceWindow`) and resused it in `SimpleDialog`. There was similar code, but the new code better handles corner cases and supports [virtual root window](https://en.wikipedia.org/wiki/Root_window#Virtual_root_window).

It can be reused also in IDLE, but I left this to separate PR.

**Comment by terryjreedy** [comment]
If I decide to use _place_window before 3.8 or 3.9 leave maintenance, I will put a copy in idlelib for those versions.

**Pull request merged**
