### PR TITLE
bpo-36822: Fix minor grammatical error in glossary.rst

### PR DESCRIPTION
**Pull request by CuriousLearner**
https://bugs.python.org/issue36822

### CODE REVIEW

**Comment by CuriousLearner** [comment]
Hey @pablogsal 

Can you please take a look at this?

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by pablogsal** [comment]
Thanks for the fix @CuriousLearner :tada:

**Comment by pablogsal** [comment]
@CuriousLearner  Could yo do the backport manually (if is needed)?

**Comment by CuriousLearner** [comment]
Hey @pablogsal 

Here it is: https://github.com/python/cpython/pull/13260

**Pull request merged**
