### PR TITLE
Issue24773 - PEP 495 implementation

### PR DESCRIPTION
**Pull request by abalkin**

### CODE REVIEW

**Comment by tim-one** [comment]
I suggest replacing `_mktime`'s `fold` logic with this, simply because I think it's more transparent.  Roughly, "if moving a day away in the right direction gives a different UTC offset, try using that instead, and accept it if it converts to the same local timestamp".  It's shorter this way too, and makes it quite clear that whether `fold` is set is a very minor part of the logic:

        if t1 == t:
            # We found one solution, but it may not be the one we need.
            # Look for another later solution (if `fold` is set), or an
            # earlier one (if `fold` is 0).
            u2 = u1 + (max_fold_seconds if self.fold else -max_fold_seconds)
            b = local(u2) - u2
            if a != b:
                u2 = t - b
                if local(u2) == t:
                    return u2
            return u1

**Comment by abalkin** [comment]
Yes, it was easier to get the logic right when it was spread out at first, but once it is written, your variant is easier to read.  I implemented it with a few tweaks in d020cc3cbbd942bc393f88cca71cbe768a09914b.

Note that we now have a block

```
        u2 = t - b
        t2 = local(u2)
        if t2 == t:
            return u2
```

repeated twice.  I wonder if there is a way to rearrange the code to avoid this duplication.

**Comment by brettcannon** [comment]
Thanks for the PR, but https://github.com/python/cpython is a cpython mirror repository; pull requests are not accepted on this repo. Please submit bugs and patches at https://bugs.python.org.

**Comment by abalkin** [comment]
@brettcannon  - what's the problem with having an open PR for the purposes of code review?

Also, what's the status of transitioning CPython development to Github?

**Comment by abalkin** [comment]
BTW, the related bug tracker issue is at <http://bugs.python.org/issue24773>.

**Pull request closed without merging**
