### PR TITLE
bpo-42401: Fix parsing and writing of the date timezone.

### PR DESCRIPTION
**Pull request by jcbertin**
The plistlib library does not write dates correctly due to its timezone naive date management.
You can test it by running this gist: https://gist.github.com/jcbertin/fedc115ea8122bec9953aa11041294eb

This PR fix it for both the writer and the parser. However, for the parser, it keeps the actual behavior for compatibility reason but adds an option to correctly decode timezone aware dates.

https://bugs.python.org/issue42401

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@jcbertin

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by MaxwellDupre — CHANGES_REQUESTED** [review]
Why have you set _MACOS_EPOCH and _MACOS_EPOCH_NAIVE to 2001,1,1?
When I googled it said same as Unix epoch 1970,1,1.
Also, I note that there are failed tests, can you check and fix please?

**Comment by micolous** [comment]
Driving by as I've also hit this same bug...

> Why have you set _MACOS_EPOCH and _MACOS_EPOCH_NAIVE to 2001,1,1? When I googled it said same as Unix epoch 1970,1,1.

I don't know where you saw documentation indicating otherwise, because [CFBinaryPList.c](opensource.apple.com/source/CF/CF-744.18/CFBinaryPList.c)'s implementation of binary `CFDate` calls [CFDateGetAbsoluteTime](https://developer.apple.com/documentation/corefoundation/1542812-cfdategetabsolutetime), which per the documentation:

> Absolute time is measured in seconds relative to the absolute reference date of **Jan 1 2001 00:00:00 GMT.** A positive value represents a date after the reference date, a negative value represents a date before it. For example, the absolute time -32940326 is equivalent to December 16th, 1999 at 17:54:34. 

The existing code **already** set the epoch to 2001-01-01.

It's unclear what the test failures actually are here, though, because the build logs have long-expired as this patch was unreviewed for a while.  A test for this new feature would be useful, though. :)

**Comment by ronaldoussoren** [comment]
#113363 implements an option to read and write timezone aware datetime values and with that this PR is no longer necessary.

**Pull request closed without merging**
