### PR TITLE
bpo-31634: Install wheel in ensurepip

### PR DESCRIPTION
**Pull request by segevfiner**
https://bugs.python.org/issue31634

### CODE REVIEW

**Comment by merwok** [comment]
Can you update the reST docs?

**Comment by segevfiner** [comment]
@merwok I added a clause to `whatsnew/3.7.rst`. [ensurepip.rst](https://github.com/python/cpython/blob/master/Doc/library/ensurepip.rst) seems to explicitly not mention the dependencies it installs for pip (Before this PR, this was only `setuptools`), so I didn't change it.

**Comment by merwok** [comment]
Ok I’ll let @ncoghlan say if these should be implementation details or advertised features.

**Comment by dstufft** [comment]
What packages (other then pip) this installs is an implementation detail. The intent was that once pip is able to automatically install setuptools/etc as part of building a sdist, that ensurepip would no longer ship setuptools by default, and it would only install pip.

**Comment by ncoghlan** [comment]
Thanks for the PR! As @dstufft noted, the fact `ensurepip` installs even `setuptools` as a dependency is currently considered an implementation detail, and is likely to be replaced at some point by having `pip` itself dynamically install it when asked to build from a source archive (at which point `pip` would install both `setuptools` *and* `wheel`).

So I'm going to close this PR without merging it, but I've closed the related issue as "postponed" rather than "rejected", as there other reasons we may end up offering an `ensuresetuptools` module that bundles both `setuptools` and `wheel`: https://bugs.python.org/issue31634#msg303734

**Pull request closed without merging**
