### PR TITLE
[3.9] bpo-40924: Revert "bpo-39791 native hooks for importlib.resources.files (GH-20576)"

### PR DESCRIPTION
**Pull request by ambv**
This reverts commit 9cf1be46e3692d565461afd3afa326d124d743dd due to

https://bugs.python.org/issue40924

The change being reverted broke Certifi and caused root certificates to be unavailable to urllib.

### CODE REVIEW

**Comment by vstinner** [comment]
This PR looks larger than just a revert. It also upgrade to the beta2. Was it done on purpose?

**Comment by ambv** [comment]
No, that's a failed rebase. Fixing right now.

**Comment by vstinner** [comment]
Please add a NEWS entry to mention the revert.

https://github.com/python/cpython/commit/9cf1be46e3692d565461afd3afa326d124d743dd added `Misc/NEWS.d/next/Library/2020-06-02-02-16-02.bpo-39791.StCJlA.rst` which was merged into 3.9.0b2.rst:

```
Built-in loaders (SourceFileLoader and ZipImporter) now supply ``TraversableResources`` implementations for ``ResourceReader``, and the fallback function has been removed.
```

**Review by vstinner — APPROVED** [review]
LGTM if you add a NEWS entry.

**Comment by vstinner** [comment]
IMHO it's better to document the revert than modifying `Misc/NEWS.d/3.9.0b2.rst`.

**Review by ned-deily — APPROVED** [review]
I did a complete macOS installer build and test install with the PR. The test suite ran without errors and I verified that certifi.where() now returns the correct result.  With the addition of a news entry, LGTM.

**Review by ned-deily — COMMENTED** [review]
Perhaps the entry should specifically mention "introduced in 3.9.0b2"?

**Comment by ambv** [comment]
Good idea, Ned.

**Review by ned-deily — APPROVED** [review]

**Pull request merged**
