### PR TITLE
fix URL redirect

### PR DESCRIPTION
**Pull request by partev**
http://www.opensource.org -> https://opensource.org

https://docs.python.org/3.12/license.html already uses https://opensource.org

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Does it really matter? The old URL still auto redirects and upgrades to HTTPS on a modern browser.

**Comment by partev** [comment]
> Does it really matter? The old URL still auto redirects and upgrades to HTTPS on a modern browser.

you are probably right. closing.

**Review by Fidget-Spinner — APPROVED** [review]

**Comment by Fidget-Spinner** [comment]
@partev I've changed my mind. Thank you for the PR, I'll be merging it. 

In general we don't encourage these types of PRs because they can add churn. If the future you can bundle multiple link upgrade PRs into one PR.

**Comment by Fidget-Spinner** [comment]
On second thought, this touches the license, and I'm not comfortable changing that. I'm so sorry!

**Pull request closed without merging**
