### PR TITLE
bpo-23699: Use a macro to reduce boilerplate code in rich comparison functions

### PR DESCRIPTION
**Pull request by stratakis**
Patch from @encukou

More info at: http://bugs.python.org/issue23699

Rebased for the current master branch.

https://bugs.python.org/issue23699

### CODE REVIEW

**Review by ncoghlan — APPROVED** [review]
The change itself looks good to me (reducing the total line count by 250+ lines is a sign of a good pattern extraction), so there's just the Misc/NEWS and Misc/ACKS bookkeeping needed prior to merging.

**Comment by stratakis** [comment]
Thanks for taking a look at it Nick. Will update the PR with the Misc/NEWS and Misc/ACKS files. Do you think it would be possible to backport this change to the 3.6 branch? Should I make a PR for a backport as well?

**Comment by ncoghlan** [comment]
No, it's a new feature, so projects will need to either define it themselves or get it from a compatibility project like Py3C for older releases.

**Comment by stratakis** [comment]
PR has been rebased on top of master and the tests pass. Is there some way I can help moving this forward?

**Review by ncoghlan — APPROVED** [review]

**Comment by ncoghlan** [comment]
Thanks!

**Pull request merged**
