### PR TITLE
gh-102204: Fix endianness issue in AIX

### PR DESCRIPTION
**Pull request by ayappanec**
This PR is to fix the problem mentioned in the issue #102204 

* Issue: gh-102204

### CODE REVIEW

**Comment by ayappanec** [comment]
Can someone review this ? It's a small change which fixes the _hacl module build in AIX.

**Comment by arhadthedev** [comment]
@gpshead (as an active core dev who participated in gh-99109 that introduced the file this PR changes).

**Comment by gpshead** [comment]
This code comes from the upstream [HACL* project](https://github.com/hacl-star/hacl-star), can you also file an issue or PR with them to get AIX-relevant code into https://github.com/hacl-star/hacl-star/blob/main/dist/karamel/include/krml/lowstar_endianness.h?

**Comment by gpshead** [comment]
it looks like this was fixed upstream and we recently pulled in an updated hacl* when the sha3 code was merged.  can you check main today and see if there is still any work to be done?

**Comment by ayappanec** [comment]
> it looks like this was fixed upstream and we recently pulled in an updated hacl* when the sha3 code was merged. can you check main today and see if there is still any work to be done?

It works now. Thanks for the support.

**Pull request closed without merging**
