### PR TITLE
lib/collections: Allow Counter()*integer.

### PR DESCRIPTION
**Pull request by abhijeetbodas2001**
This isn't part of the standard multiset operations, but makes sense to be added nonetheless, I feel!

### CODE REVIEW

**Comment by abhijeetbodas2001** [comment]
IMO, the change is too small to warrant a GH issue, but I am happy to open one if required.

**Comment by picnixz** [comment]
Please read the devguide first: https://devguide.python.org/getting-started/pull-request-lifecycle/. This requires an issue and a prior discussion. Until this feature is accepted, this PR should be closed.

**Comment by rhettinger** [comment]
Thank you for the suggestion, but I will decline.  A counter-to-integer `*` operation does not match the counter-to-counter `+` and `-` operations.  Having unexpectedly different semantics would create unnecessary confusion.  Likely, that is why "this isn't part of the standard multiset operations".

FWIW, here is an easy way to do what you want:

```
>>> c = Counter(a=1, b=2, c=3)
>>> Counter({k : v*2 for k, v in c.items()})
Counter({'c': 6, 'b': 4, 'a': 2})
```

**Comment by abhijeetbodas2001** [comment]
> what are the use cases?

I was (unpleasantly) surprised to find that `Counter` did not support multiplication with integer while solving [a particular puzzle](https://adventofcode.com/2024/day/11).

So the use-case isn't a "real" one, but I made this PR since this felt natural to have.

But thanks for the reviews nonetheless!

**Pull request closed without merging**
