### PR TITLE
Add missed `stream` argument

### PR DESCRIPTION
**Pull request by shadchin**

### CODE REVIEW

**Comment by gaogaotiantian** [comment]
This issue has been there since [day 1](https://github.com/python/cpython/commit/aaa83cdfab6817446285e631232f64b394ac6791#diff-38e729d33180aa9d5769e22475ef893ed3436c4602add44b97db330e7aa8d111) and no one finds it in 2 years. It's not documented and it's not used internally. Is this just dead code @jaraco ?

**Comment by jaraco** [comment]
Thanks @gaogaotiantian for tracking down the origin of the issue. Although that's day 1 for this class, the code is derived from resources.py in that commit.

In the upstream implementation (which probably has better fidelity of the history of this change), [that file is skipped for coverage checks](https://github.com/python/importlib_resources/blob/babc28763cd8e4f6fc4d6d67136ff51fb9182069/.coveragerc#L7). That module was provided as an illustration of the lowest level interfaces required to supply `TraversableResources`. It's entirely conceivable that no one has made use of them. This code was made in response to https://github.com/python/importlib_resources/issues/90.

If we accept this change (and we probably should), we'll want to make sure it gets ported upstream.

**Comment by jaraco** [comment]
I've cherry-picked this change into python/importlib_resources and released it as 6.1.1. This change will make it into CPython in due time. If you want to author a news fragment, I'll merge this change.

**Review by jaraco — DISMISSED** [review]
Please add a news fragment, but otherwise looks good.

**Comment by gaogaotiantian** [comment]
My question is, if no one has used this piece of code for 2 years and it's not documented at all, do we still need it in CPython repo?

**Comment by jaraco** [comment]
> My question is, if no one has used this piece of code for 2 years and it's not documented at all, do we still need it in CPython repo?

Probably not, but to remove it will require a deprecation and we'll want to present that deprecation first in importlib_resources. Feel free to propose that there. In the meantime, it makes sense to merge the bugfix.

**Comment by gaogaotiantian** [comment]
Oh, I thought removing code that we never documented does not require anything. But yeah, the fix itself definitely makes sense.

**Comment by shadchin** [comment]
I have made the requested changes; please review again

**Review by jaraco — APPROVED** [review]

**Comment by shadchin** [comment]
Is something required of me here?

**Comment by shadchin** [comment]
What needs to be done to merge this PR?

**Comment by jaraco** [comment]
Thanks for your patience. I had a rough winter, so missed the notifications. Merging now.

**Pull request merged**
