### PR TITLE
bpo-41004: IPv4Interface, and IPv6Interface hash collisions 

### PR DESCRIPTION
**Pull request by sreev**
Automerge-Triggered-By: @ericvsmith

https://bugs.python.org/issue41004

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@sreev

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by sreev** [comment]
> Hello, and thanks for your contribution!
> 
> I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).
> ## CLA Missing
> 
> Our records indicate the following people have not signed the CLA:
> 
> @sreev
> 
> For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.
> 
> If you have recently signed the CLA, please wait at least one business day
> before our records are updated.
> 
> You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.
> 
> Thanks again for the contribution, we look forward to reviewing it!

Just signed the CLA. Thanks.
/Sree

**Comment by ZackerySpytz** [comment]
bpo-41004

**Comment by amiremohamadi** [comment]
Hi @sreev! 
I think this change will need a NEWS entry.
you can add NEWS using https://blurb-it.herokuapp.com/

**Review by ericvsmith — CHANGES_REQUESTED** [review]
It would be good to add some tests for this. Maybe just something that asserts that two IPv4Interface objects have different hashes. Same for IPv6Interface.

And as noted elsewhere, it needs a NEWS entry.

**Comment by ned-deily** [comment]
It looks like this PR has been superseded by #21033?

**Comment by kirotawa** [comment]
Hi,

Is this issue completely solved already? I'm seeing "resolved" in https://bugs.python.org/issue41004 , but here it's still open. So just would like to be sure.

**Comment by iritkatriel** [comment]
This was indeed fixed already in https://github.com/python/cpython/pull/21033

**Comment by sreev** [comment]
@ned-deily no worries, as long as it's fixed. thanks.
thanks, @iritkatriel .

**Pull request closed without merging**
