### PR TITLE
gh-105084: Tests: Use setuptools+wheel from sysconfig.get_config_var('WHEEL_PKG_DIR') if set

### PR DESCRIPTION
**Pull request by hroncok**
I am currently testing this approach in Fedora.

* Issue: gh-105084

### CODE REVIEW

**Comment by hroncok** [comment]
Open question: Should TEST_HOME_DIR be considered when the wheel is not found in WHEEL_PKG_DIR?

The current implementation assumes that when WHEEL_PKG_DIR is set, it contains wheels for setuptools and wheel, but it does not necessarily need to be so (some distributors might only have pip there).

**Comment by hroncok** [comment]
This approach works for Fedora.

**Review by pradyunsg — APPROVED** [review]

**Review by lysnikolaou — APPROVED** [review]
Looks good! Thanks @hroncok!

**Comment by hroncok** [comment]
Thanks, folks. Could you please add a Python 3.11 label? This is tests-only, so I belive it may still go into 3.11.

**Comment by hroncok** [comment]
I meant 3.12 of course.

**Comment by hroncok** [comment]
Ah, https://github.com/python/cpython/pull/104798 would need to be backported first.

**Comment by hroncok** [comment]
I have a patch in Fedora that applies to 3.11.0b1 and can backport that one, but I guess I'll ask first.

**Pull request merged**
