### PR TITLE
gh-110105: Fix MSVC ARM64 atomic add of 16 and 8-bit values

### PR DESCRIPTION
**Pull request by colesbury**
MSVC versions starting with 19.33 (and fixed in 19.37) do not properly sign extend the value read from the atomic pointer in `_InterlockedExchangeAdd8` and `_InterlockedExchangeAdd16`. Work around this issue by using a compare-exchange loop for all MSVC versions prior to 19.37 on ARM64.

* Issue: gh-110105

### CODE REVIEW

**Comment by colesbury** [comment]
@zooba are you able to test this on your private ARM64 buildbot? I did some minimal testing by making sure the new code paths work on Windows x64, but I don't have access to a Windows arm64 machine. GHA unfortunately doesn't have Windows arm64 runners.

**Comment by colesbury** [comment]
!buildbot ARM

**Comment by zooba** [comment]
I strongly suspect it's going to be all the operations, not just add. Because the test crashes we never find out which other ones fail (it would be better to return an exit code than to `assert` in these tests).

**Comment by encukou** [comment]
Is this still relevant?
I'd prefer not including a workaround for a fixed compiler bug, especially in (currently) unused functions.

**Comment by colesbury** [comment]
Sounds good - I'll close the PR.

**Pull request closed without merging**
