### PR TITLE
gh-106531: Apply changes from importlib_resources 6.3.2

### PR DESCRIPTION
**Pull request by jaraco**
* Issue: gh-106531

### CODE REVIEW

**Comment by jaraco** [comment]
Well shoot. I'd meant for this to land in Python 3.13, but lost track of it. @Yhg1s would you be willing to allow this to land in 3.13b2? It does add a deprecation for a usage that's likely rare.

**Comment by jaraco** [comment]
I was thinking about this overnight and I'm going to take the executive decision to merge it and back-port it, knowing that we might decide to delay the deprecation, especially if there's more than a small impact (which I don't expect).

**Comment by jaraco** [comment]
On further consideration, after re-reading the summary in the blurb and looking at the diff, I'm reminded that this change is about much more than just the introduced deprecation. Still, I want to get this merged and we can discuss the viability of the backport in the backport PR.

**Comment by Yhg1s** [comment]
Given that this is effectively syncing with a newer version of importlib_resources, I'm okay with this going into 3.13 at this point.

**Review by Yhg1s — APPROVED** [review]

**Pull request merged**
