### PR TITLE
bpo-10572: Move test sub-packages to Lib/test

### PR DESCRIPTION
**Pull request by idomic**
https://bugs.python.org/issue10572

### CODE REVIEW

**Review by ned-deily — CHANGES_REQUESTED** [review]
Please make sure that tests still run correctly when running from an installed instance of Python, not just from a development build directory.  The various test directories are installed in the main Makefile (Makefile.pre.in) `libinstall` rule.  I think you'll find that many tests are now broken.  See the `LIBSUBDIRS` variable in the Makefile. (I see that the dev guide does not refer to this topic so I've opened a devguide issue about it: https://github.com/python/devguide/issues/573)

**Comment by idomic** [comment]
Thanks @ned-deily , I've updated the makefile and adding a News file.
I have made the requested changes; please review again

**Comment by idomic** [comment]
Ok I fixed all of the tests expect 1 in lib2to3 in which I'm not really sure what's going on.

**Comment by idomic** [comment]
When looking on the test that's failing:

test_write_filtered_python_package (test.test_zipfile.PyZipFileTests) ...   File "/Users/runner/runners/2.164.0/work/cpython/cpython/Lib/test/lib2to3_tests/data/bom.py", line 2
    print "BOM BOOM!"

It looks like it uses print syntax of python 2.7 which is not relevant anymore, any idea why is it there? I suspect in the master it was just not running and because now it's in the tests folder it's running by default.

I have made the requested changes; please review again

**Comment by brettcannon** [comment]
@idomic it looks like it's a test file for the lib2to3 test to use. There's probably a test that reads that file, runs lib2to3 on it, and checks the results. So that file is very likely there on purpose and meant to be Python 2 syntax.

**Comment by brettcannon** [comment]
@idomic you also have conflicts. It might be easier to do one PR per package so lessen the chances of merge conflicts occurring.

**Review by brettcannon — CHANGES_REQUESTED** [review]
The merge conflicts need to be fixed, and I would strongly suggest breaking this PR up into single PRs per package.

**Comment by idomic** [comment]
> The merge conflicts need to be fixed, and I would strongly suggest breaking this PR up into single PRs per package.

I'll submit a new PR with 1 package and will tag you and Ned

**Pull request closed without merging**
