### PR TITLE
gh-127146: Mark test_bz2 tests with requires_subprocess

### PR DESCRIPTION
**Pull request by hoodmane**
* Issue: gh-127146

### CODE REVIEW

**Comment by freakboy3742** [comment]
This doesn't seem quite right - iOS and Android don't support subprocesses, but have no problem implementing the bz2 tests. How are you seeing this problem manifest?

**Comment by hoodmane** [comment]
```
Traceback (most recent call last):
  File "/home/rchatham/cpython/Lib/test/test_bz2.py", line 252, in testWrite
    self.assertEqual(ext_decompress(f.read()), self.TEXT)
                     ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rchatham/cpython/Lib/test/test_bz2.py", line 34, in ext_decompress
    return subprocess.check_output(['bunzip2'], input=data)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rchatham/cpython/Lib/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/home/rchatham/cpython/Lib/subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rchatham/cpython/Lib/subprocess.py", line 824, in __init__
    raise OSError(
        errno.ENOTSUP, f"{sys.platform} does not support processes."
    )
OSError: [Errno 138] emscripten does not support processes.

```

**Comment by hoodmane** [comment]
Looking at `ext_decompress`:
```py
def ext_decompress(data):
    global has_cmdline_bunzip2
    if has_cmdline_bunzip2 is None:
        has_cmdline_bunzip2 = bool(shutil.which('bunzip2'))
    if has_cmdline_bunzip2:
        return subprocess.check_output(['bunzip2'], input=data)
    else:
        return bz2.decompress(data)
```
Looks like the problem is that `shutil.which('bunzip2')` returns something truthy for some reason.

**Comment by hoodmane** [comment]
```
$ ./python.sh -c "import shutil; print(shutil.which('bunzip2'))"
/usr/bin/bunzip2
```
Okay the problem is that in `node_entry.mjs` I should do one or both of:
1. not propagate the PATH environment variable or
2. not mount the /usr directory.

**Comment by hoodmane** [comment]
Thanks @freakboy3742!

**Review by Asba3488 — APPROVED** [review]

**Pull request closed without merging**
