### PR TITLE
[3.6] bpo-37461: Fix typo (inifite -> infinite)

### PR DESCRIPTION
**Pull request by GeeTransit**
https://bugs.python.org/issue37461

### CODE REVIEW

**Review by epicfaace — APPROVED** [review]

**Comment by jdemeyer** [comment]
We no longer accept bugfixes for 3.6. So this should be closed.

**Comment by jdemeyer** [comment]
Is this a backport? Normally, patches are first merged in master and then backported.

**Comment by GeeTransit** [comment]
Well, it's a typo soo:question:

**Comment by epicfaace** [comment]
Actually, it looks like 3.6 is in security mode (https://devguide.python.org/#branchstatus), so not sure if typo fixes would be accepted in the branch. @ned-deily?

**Comment by ned-deily** [comment]
The typo is the news entry for an as-yet unreleased fix to be released in the next 3.6.x security release so it is appropriate to fix it.  Thanks for noticing, @GeeTransit, and for the other backport of it.

**Pull request merged**
