### PR TITLE
gh-100110: Specialize FOR_ITER for tuples

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Same as FOR_ITER_LIST, but it accounts for 57% of our current failures.

https://github.com/faster-cpython/ideas/blob/main/stats/pystats-python-a87c46e-2022-12-04.md#specialization-attempts-3

* Issue: gh-100110

### CODE REVIEW

**Comment by markshannon** [comment]
I'm not sure that I entirely trust those stats, yet.
They are probably right though, and I guess we can revert this if the stats prove to be wrong.

**Review by markshannon — APPROVED** [review]
Looks good.
Have you attempted to benchmark this?

**Comment by Fidget-Spinner** [comment]
> Looks good. Have you attempted to benchmark this?

No. It's just one specialisation. I doubt anything in pyperformance will change.

**Comment by markshannon** [comment]
I'm running the stats on it.
Partly to see if makes the expected difference, and partly just to see if the stats workflow does what I expect.

**Comment by markshannon** [comment]
The [stats](https://github.com/faster-cpython/ideas/blob/main/stats/pystats-Fidget-Spinner-e3504e7-2022-12-08.md) show what I would expect. No specialization failures for tuples, and an increase of hit rates for `FOR_ITER` from about 66% to 79%.

**Pull request merged**
