### PR TITLE
howto/urllib2: remove link to an outdated French translation

### PR DESCRIPTION
**Pull request by deronnax**
We now have our own translation and it's not outdated.

Ping @JulienPalard

### CODE REVIEW

**Review by JulienPalard — APPROVED** [review]

**Comment by JulienPalard** [comment]
Can you please target your PR to the `main` branch? That's where all PR are merged so they are never lost for future versions, you don't want this paragraph to reappear in 3.12.

To hit 3.11 we backport PRs on main to 3.11 (using a bot reading github labels).

**Comment by JulienPalard** [comment]
(Sorry for the big flood or Github automated reviews! I just tried to base the PR on main from the Github UI, hoping it would work as the commit was simple...).

**Comment by deronnax** [comment]
Sorry, I don't why I targeted 3.11, the habit of the translation workflow I guess. To avoid a big pile of unrelated commit and still use the same PR, I created a branch from an up-to-date main named 3.11 and force-pushed it to my (old) 3.11 remote , but it mysteriously upset'd bedevere bot who close my PR. If you can't reopen it, I will create another.

**Comment by AlexWaygood** [comment]
> If you can't reopen it, I will create another.

Creating another would be the best course of action here! It's basically impossible to change the target branch on a CPython PR without causing a huge flood of reviews for loads of people, unfortunately.

**Pull request closed without merging**
