### PR TITLE
bpo-45047 Rat in a maze 

### PR DESCRIPTION
**Pull request by Ayushparikh-code**
https://bugs.python.org/issue45047

### CODE REVIEW

**Comment by Ayushparikh-code** [comment]
hey @ericvsmith @iritkatriel @terryjreedy can u plz review it so that it can be merged !

**Comment by terryjreedy** [comment]
I ran the file and got no errors and no output.  I was expecting something, but maybe docstring.testmod is intentionally silent, unlike unittest.  Is this the style of other files in the directory?

**Comment by Ayushparikh-code** [comment]
> I ran the file and got no errors and no output. I was expecting something, but maybe docstring.testmod is intentionally silent, unlike unittest. Is this the style of other files in the directory?

yeah

**Comment by iritkatriel** [comment]
Closing as bpo-45047 was rejected.

**Pull request closed without merging**
