### PR TITLE
gh-117977: Amend version changed annotation for os.chmod, os.chown, and os.listdir

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-117977

----
📚 Documentation preview 📚: https://cpython-previews--117978.org.readthedocs.build/

### CODE REVIEW

**Comment by nineteendo** [comment]
cc @hauntsaninja: happened here as well.

**Comment by nineteendo** [comment]
@erlend-aasland, could you merge this?

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
For future reference, try to make sure the PR title describes the actual change ;)

**Comment by nineteendo** [comment]
Thanks, I wasn't sure how to describe this.

**Comment by nineteendo** [comment]
> By the way, there's usually no need to update the PR from `main` unless you have a good reason

A required test randomly failed and you can't merge with failed tests. Is there a way to re-run a single test?

**Comment by nineteendo** [comment]
When the job gets cancelled by a new commit it doesn't seem to get saved. But I have the same problem here: #117855.

**Pull request merged**
