### PR TITLE
gh-88531 Fix dataclass __post_init__/__init__ interplay documentation

### PR DESCRIPTION
**Pull request by Kaniee**
This fixes a misleading and not runable example in the dataclass documentation.

* Issue: gh-88531

----
:books: Documentation preview :books:: https://cpython-previews--107404.org.readthedocs.build/

### CODE REVIEW

**Review by AA-Turner — APPROVED** [review]
This does make the example work, but seems to take away some of the clarity of the said example. Perhaps ``Rectangle`` could be not a dataclass here?

cc: @ericvsmith

A

**Comment by Kaniee** [comment]
I see what you're saying.
On the other hand, if `Rectangle` would be no dataclass, we would need to these three lines to it: 
```python
def __init__(self, height, width):
    self.height = height
    self.width = width
```

I would stick with the example where `Rectangle` is a dataclass, exactly that is the pattern I use `__post_init__` for most of the time.

**Comment by ericvsmith** [comment]
I think making `Rectangle` a non-dataclass is the best approach. Sure, it's a few lines of code, but the base being a dataclass isn't the important thing: it having a `__init__` is. I think that the base being a dataclass is potentially confusing to new users reading the docs to learn about dataclasses: they might think the base being a dataclass is a requirement.

**Comment by Kaniee** [comment]
I updated it accordingly.

**Review by AA-Turner — APPROVED** [review]

**Pull request merged**
