### PR TITLE
bpo-46470: remove unused branch from `typing._remove_dups_flatten`

### PR DESCRIPTION
**Pull request by sobolevn**
CC @corona10 as my mentor.

https://bugs.python.org/issue46470

### CODE REVIEW

**Comment by sobolevn** [comment]
I am lucky today, all my PRs trigger very rare error in `test_asyncio` 😆

**Review by JelleZijlstra — APPROVED** [review]
I think this happened in 3.6:
```
In [22]: typing_inspect.get_args(Union[List[str], Set[str]])
Out[22]: ((typing.List, str), (typing.Set, str))
```

**Comment by sobolevn** [comment]
This test officially won:

```
 ======================================================================
FAIL: test_sendfile_close_peer_in_the_middle_of_receiving (test.test_asyncio.test_sendfile.ProactorEventLoopTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_asyncio\test_sendfile.py", line 461, in test_sendfile_close_peer_in_the_middle_of_receiving
    with self.assertRaises(ConnectionError):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ConnectionError not raised
```

No idea why it happens so often today. I've tried to re-trigger the CI twice, but it still fails.

**Comment by gvanrossum** [comment]
Could it be that bpo-46409 / GH-30633 destabilized that test even more? Is there evidence in other PRs that this is happening more often?

If it's timing related (as sounds likely) it could also have to do with congestion in the fleet of machines where GitHub Actions are run. Possibly someone should open a separate bug. Even if it's not any PR's fault, the asyncio tests are clearly more flaky than most, and are causing a fair amount of CI churn.

**Comment by gvanrossum** [comment]
Trying once more.

**Comment by AlexWaygood** [comment]
> Is there evidence in other PRs that this is happening more often?

Anecdotally, from what I can tell, it does seem to have been occurring *much* more often in the last few weeks.

**Comment by gvanrossum** [comment]
So not Mark's generators PR, but maybe something else.

Any chance of plotting these occurrences? That could make it obvious where
to look. (But getting the data to plot might be complicated.)

**Comment by sobolevn** [comment]
Me-test: 1-1 😆 
https://github.com/python/cpython/pull/30801

Now, it should be fine!

**Comment by AlexWaygood** [comment]
> Me-test: 1-1 😆 #30801
> 
> Now, it should be fine!

The service you have done to my mental health is incalculable

**Review by Fidget-Spinner — APPROVED** [review]
Wow, that's an interesting blast from the past.

**Review by raghavthind2005 — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
That looks unrelated to this PR.

**Pull request merged**
