### PR TITLE
[3.7] bpo-36965: replace include of  crtdbg.h with windows.h, backport 925af1d 3.7 (GH-13421)

### PR DESCRIPTION
**Pull request by erikjanss**
https://bugs.python.org/issue36965

### CODE REVIEW

**Review by eamanu — COMMENTED** [review]
looks good. But I think that will be open a issue an explain a little more 
what are you doing that :-)

**Comment by erikjanss** [comment]
it's a manual backport of GH-13421, this is the first time I went trough the manual cherry picking process ... so I didn't notice the required title format ...

**Comment by vstinner** [comment]
I fixed the commit message and merged your PR, thanks.

**Comment by erikjanss** [comment]
Thank you !

**Pull request merged**
