### PR TITLE
gh-111201: Speed up paste mode in the REPL

### PR DESCRIPTION
**Pull request by pablogsal**
* Issue: gh-111201

### CODE REVIEW

**Comment by pablogsal** [comment]
This depends on https://github.com/python/cpython/pull/119318 landing first

**Comment by lysnikolaou** [comment]
I think that this has completely broken paste. Pasting code shows the last character of the pasted line only. The whole buffer is shown after hitting backspace. If arrows are used between the paste and the backspace, the buffer get completely messed up.

**Comment by pablogsal** [comment]
Hummm, we live tested this several times. I wonder if there is some weird interaction with other PRs we landed

**Comment by pablogsal** [comment]
We should revert meanwhile I think

**Comment by pablogsal** [comment]
@lysnikolaou @ambv WDYT?

**Comment by lysnikolaou** [comment]
+1 for reverting, otherwise it might be hard to do manual testing of PRs at the sprints.

**Comment by lysnikolaou** [comment]
@ 119432 fixes this.

**Pull request merged**
