### PR TITLE
gh-103088: Fix test error message

### PR DESCRIPTION
**Pull request by Zabolekar**
* Issue: gh-103088

### CODE REVIEW

**Comment by arhadthedev** [comment]
Triggering the buildbots to get logs with the new message.

**Comment by arhadthedev** [comment]
The tests are done:

```plain
======================================================================
FAIL: test_activate_shell_script_has_no_dos_newlines (test.test_venv.BasicTest.test_activate_shell_script_has_no_dos_newlines)
Test that the `activate` shell script contains no CR LF.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\buildarea\pull_request.bolen-windows10\build\Lib\test\test_venv.py", line 628, in test_activate_shell_script_has_no_dos_newlines
    self.assertFalse(line.endswith(b'\r\n'), error_message)
AssertionError: True is not false : CR LF found in line 1
----------------------------------------------------------------------
```

**Comment by zooba** [comment]
It only overrides the value of `core.eol` being used as the default, which is not what is happening here. We've explicitly set the line ending for the file, we just need anyone who's checked it out in the past to delete it and check it out again (tested on my own Windows machine, which has `core.autocrlf` set).

If we can't find a way to force the buildbots to do a clean checkout, instead of reusing their existing one, then we probably need to ping all the owners to log in and do it manually.

**Comment by zooba** [comment]
The buildbot results look good (the expected failure), so merging this. Buildbot discussion back to #103088 please.

**Pull request merged**
