### PR TITLE
Specify which square root is returned in the docs.

### PR DESCRIPTION
**Pull request by Frederico-Messa**
By formal definition, the square roots of x are the values of y such that y^2 = x.
For example, -3 and 3 are the square roots of 9, and we say that the PRINCIPAL square root of 9 is 3 (the positive one). This 
 nomenclature is valid even when we are working only with real numbers.
I know, although, that in several countries, to avoid repeatedly saying that √x is the principal square root of x, usually omit the term "principal", particularly in school. But I think it is best to be clear in the docs of this function.
As a reference, please look at https://en.wikipedia.org/wiki/Square_root

### CODE REVIEW

**Comment by AA-Turner** [comment]
-0 on this, personally I'd need to remind myself what the principal root is, as the language deviates from the "default" of assuming the positive square root.

It might be better to leave `mathmodule.c` alone and add some text to the documentation, where we've more space to expand?

A

**Comment by AlexWaygood** [comment]
> -0 on this, personally I'd need to remind myself what the principal root is, as the language deviates from the "default" of assuming the positive square root.
> 
> It might be better to leave `mathmodule.c` alone and add some text to the documentation, where we've more space to expand?
> 
> A

Whatever the case, the vast majority of PRs need to be made against the `main` branch of CPython, and then (if they are accepted and merged) possibly backported to the maintenance branches. This PR has `3.11` as the target branch, and the easiest course of action is to start again with a new PR targeting `main`, so I'm closing this for now. Feel free to open a new PR (but no promises that it will be accepted, and ideally take note of Adam's feedback if you do so).

**Comment by Frederico-Messa** [comment]
> -0 on this, personally I'd need to remind myself what the principal root is, as the language deviates from the "default" of assuming the positive square root.
> 
> It might be better to leave `mathmodule.c` alone and add some text to the documentation, where we've more space to expand?
> 
> A

Hello, @AA-Turner. I don't know much about this GitHub repository, and further, this is my second pull request at all, so I am new to this kind of contribution. Anyway, I think it's enabled to anyone edit my commit for another file or branch, so the problem you mentioned could be easily fixed. Which file should I been looking at? Also, sorry, but I don't know the meaning of "-0 on this", can you explain, please? (I am not a native speaker of english).

**Comment by Frederico-Messa** [comment]
> > -0 on this, personally I'd need to remind myself what the principal root is, as the language deviates from the "default" of assuming the positive square root.
> > It might be better to leave `mathmodule.c` alone and add some text to the documentation, where we've more space to expand?
> > A
> 
> Whatever the case, the vast majority of PRs need to be made against the `main` branch of CPython, and then (if they are accepted and merged) possibly backported to the maintenance branches. This PR has `3.11` as the target branch, and the easiest course of action is to start again with a new PR targeting `main`, so I'm closing this for now. Feel free to open a new PR (but no promises that it will be accepted, and ideally take note of Adam's feedback if you do so).

Oh @AlexWaygood, okay, I didn't know that. Sorry. Can I change the commit, or do I really need to create a new pull request?

**Comment by AlexWaygood** [comment]
> Can I change the commit, or do I really need to create a new pull request?

I'm afraid changing the target branch after the PR has been filed often interacts very badly with the GitHub CODEOWNERS feature — so unless you want to automatically request a review from the entire core dev team, yeah, I recommend creating a new PR. Sorry about that 🙂

**Comment by AA-Turner** [comment]
@AlexWaygood oops, didn't notice the PR targeted 3.11, thanks!

@Frederico-Messa thank you for wanting to contribute! https://devguide.python.org/pullrequest/ might be a good starting point, it describes the CPython workflow, opening an issue, and the review process etc. Alex and I can't edit your PR directly, and even if we could we probably wouldn't -- it is up to you as the proposer of the change to demonstrate the need for it etc, as well as responding to feedback.

`-0` means that I'm not really in favour, but I'm not saying I hate it! [PEP 10](https://peps.python.org/pep-0010/) has some background details here.

In terms of what you should do next, I would open an issue to see if there is support for changing the documentation here -- and then create a new PR against `HEAD`.

A

**Comment by Frederico-Messa** [comment]
Thanks for the answers @AA-Turner and @AlexWaygood. I understand the problems.

About which file I should edit, this is also in the guide you presented, @AA-Turner? I would like to know which file to modify in the next PR, if not the `mathmodule.c`. (I don't know whether you know which one it is. If not, I will try to discover.)

**Comment by AA-Turner** [comment]
https://github.com/python/cpython/blob/5893b5db98b38b17750c0572c7209774a5034898/Doc/library/math.rst?plain=1#L437-L439

**Comment by Frederico-Messa** [comment]
> https://github.com/python/cpython/blob/5893b5db98b38b17750c0572c7209774a5034898/Doc/library/math.rst?plain=1#L437-L439

Thanks!

**Pull request closed without merging**
