### PR TITLE
gh-100519: simplification to `eff_request_host` in cookiejar.py

### PR DESCRIPTION
**Pull request by glyph**
`IPV4_RE` includes a `.`, and the `.find(".") == -1` included here is already testing to make sure there's no dot, so this part of the expression is tautological. Instead use more modern `in` syntax to make it clear what the check is doing here

This change is trivial so I did not open an issue.

I filed #31004 for this same change, and a bot linked linked me to some CLA instructions which tell me a bot will present me with a button in the comment.  So I assume the workflow has changed and I'll get a CLA bot request on this new PR.

* Issue: gh-100519

### CODE REVIEW

**Comment by glyph** [comment]
image

**Comment by glyph** [comment]
Oh hey but I officially did sign it, cool, nevermind, I don't mind the error :)

**Comment by glyph** [comment]
> Oh hey but I officially did sign it, cool, nevermind, I don't mind the error :)

Hmm. I thought I saw a green "CLA signed" but upon reloading the page it's red again, and the CLA check is red. Let me know how I can sort this out and I'd be happy to sign it.

**Comment by glyph** [comment]
Now the page just looks like this:

image

**Comment by hauntsaninja** [comment]
You're good on the CLA front, it seems. I added a skip-issue label, but you'll still need to add a news entry for this PR; you can do this at https://blurb-it.herokuapp.com/

**Review by hauntsaninja — APPROVED** [review]
This looks good to me.

I guess the only concern is whether it's useful for the `IPV4_RE.search` clause to be there even if it currently does nothing. But that regex doesn't seem likely to change and more importantly, the RFC 2965 wording is pretty clear:
```
   The term effective host name is related to host name.  If a host name
   contains no dots, the effective host name is that name with the
   string .local appended to it.  Otherwise the effective host name is
   the same as the host name.  Note that all effective host names
   contain at least one dot.
```

**Review by hauntsaninja — APPROVED** [review]
Thank you! While CPython typically does not encourage trivial changes, this clearly makes the code more readable / idiomatic and matches the RFC 2965 spec better.

Also interestingly blurbit failed for me, but I was able to push manually:
> ❌ Cannot create news file for [GH-99588](https://github.com/python/cpython/pull/99588)! Make sure you have access to that PR!

cc @JelleZijlstra

**Comment by JelleZijlstra** [comment]
Seems OK; I might skip the NEWS entry since there should be no user-visible effect (unless someone monkeypatches IPv4_RE, I guess), but there's no harm in keeping it.

Going to click "update branch" in the hope it will make CI pass.

**Pull request merged**
