### PR TITLE
gh-115490: Make the interpreter.channels and interpreter.queues Modules Handle Reloading Properly

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
The problem manifested when the .py module got reloaded and the corresponding extension module didn't.  The .py module registers types with the extension and the extension was not allowing that to happen more than once.  The solution: let it happen more than once.

* Issue: gh-115490

### CODE REVIEW

**Review by encukou — APPROVED** [review]
This looks good to me, though I'm not too familiar with the details here.

**Comment by encukou** [comment]
I see comments about doing unregistration via weakref or removing the registry altogether, both of which I thought about before noticing the comments:

    // XXX Assign a callback to clear the entry from the registry?

    /* For now we use a global registry of shareable classes.  An
   alternative would be to add a tp_* slot for a class's
   crossinterpdatafunc. It would be simpler and more efficient.  */

Is there a reason for not doing one of these now?
It definitely shouldn't block the PR.

**Comment by Yhg1s** [comment]
This... is a lot of change to fix a test failure caused by the shenanigans our testing framework does. I'd rather not rush this in right before a release, even an alpha release. A change like this needs time to bake so repeated runs and all the different buildbots get a chance to find issues.

I'll make a separate change to just special-case test.support.interpreters in libregrtest's sys.modules cleanup, we can roll it back after this goes in.

**Comment by Yhg1s** [comment]
#115515 is the temporary workaround.

**Comment by ericsnowcurrently** [comment]
FYI, I've cut out the extra cleanup code.

**Comment by gpshead** [comment]
shouldn't we add an explicit test case for this behavior?  (a single test that reloads the modules leading to the problem perhaps?)

**Pull request merged**
