### PR TITLE
[WIP] bpo-33048: Update travis for osx and recent brew change

### PR DESCRIPTION
**Pull request by willingc**
[WIP] Update travis config to test for Python 3 on macOS.

https://bugs.python.org/issue33048

### CODE REVIEW

**Comment by pitrou** [comment]
I think we'd rather a normal test run than a coverage run (especially as the coverage run eschews multiprocessing tests, which is a place where there can be "interesting" platform-specific issues :-)).

**Comment by pitrou** [comment]
FWIW, I think the errors executing `./python` are because you need `./python.exe` on macOS (the filesystem may be case-insensitive). @ned-deily

**Comment by willingc** [comment]
Thanks @pitrou. I'll give that a shot later today or tomorrow. I appreciate the tips.

**Comment by willingc** [comment]
@pitrou Was wondering if we can remove brew as conda-smithy does?

**Comment by pitrou** [comment]
@willingc, well, why not, but we still need to install Python 3 and libxz to get the build process to work...

**Comment by taleinat** [comment]
Ping, @willingc, is this still relevant? If so, I have a macOS machine and would be happy to help get it sorted out.

**Comment by willingc** [comment]
@taleinat I don't think it has been relevant since Brew reversed its original decision re: numbering.

**Comment by willingc** [comment]
I think we can close this.

**Pull request closed without merging**
