### PR TITLE
gh-105626: Change the default return value of `HTTPConnection.get_proxy_response_headers`

### PR DESCRIPTION
**Pull request by sobolevn**
See https://github.com/python/cpython/pull/104248#issuecomment-1585579473
CC @nametkin

* Issue: gh-105626

----
:books: Documentation preview :books:: https://cpython-previews--105628.org.readthedocs.build/

### CODE REVIEW

**Comment by sobolevn** [comment]
This Win fail is not related.

**Comment by sobolevn** [comment]
Friendly ping :)

**Review by JelleZijlstra — APPROVED** [review]
Does seem like `None` makes more sense here, but I'd prefer to get @gpshead's opinion.

As an aside it's amusing this test is still called `test_httplib`, after the Python 2 name of this module.

**Comment by gpshead** [comment]
`None` feels awkward because you are then _forced_ to check the return value before you use it rather than just blindly use a `.get("field")` style API.  Your goal seems to be to keep the type annotation signature simple. Can we instead return an empty `HTTPMessage` class?

**Comment by gpshead** [comment]
I marked this as a release blocker to force us to decide before 3.12rc1 so that we don't wind up with our new API needing to have a deprecation cycle and behavior change in the future (or just live with what is understandably perceived as an API wart).

**Comment by sobolevn** [comment]
@gpshead yes, from this side empty `HTTPMessage` might seem better.

Questions:
1. Is default `policy=compat32` for `HTTPMessage` suitable in all cases here? Or should we use a different one?
2. Can users actually want to check this? As far as I understand `CONNECT` is really optional. So, this new API with `None` also serves as a response to a possible question "Did we have a `CONNECT` call here?"
3. Is `(m.get_proxy_response_headers() or {}).get('whatever')` workaround good enough to not care about `None` here?

**Comment by gpshead** [comment]
> Is (m.get_proxy_response_headers() or {}).get('whatever') workaround good enough to not care about potential None checks here?

honestly... that idiom may be enough, I expect this is going to be a very rarely used API.

**Review by gpshead — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks everyone :)

**Pull request merged**
