### PR TITLE
bpo-36814: ensure os.posix_spawnp handles Py_None

### PR DESCRIPTION
**Pull request by tonybaloney**
https://bugs.python.org/issue36814

### CODE REVIEW

**Comment by tonybaloney** [comment]
Requesting review from @nanjekyejoannah

**Comment by ZackerySpytz** [comment]
I believe this change should have a test.

**Comment by tonybaloney** [comment]
@ZackerySpytz agreed, added tests

**Comment by nanjekyejoannah** [comment]
Looks fine for me. @vstinner any thoughts?

**Review by vstinner — CHANGES_REQUESTED** [review]
You should not add tests to TestPosixSpawnP but _PosixSpawnMixin, otherwise only os.posix_spawnp() is tested, not os.posix_spawn().

Well, honestly, I would go with a PR without tests. We already have plenty of tests for posix_spawn().

If you want to add tests, please avoid setUp() and avoid hardcoding "posix_spawnp" in the test, since the tests should be run on posix_spawn and posix_spawnp.

**Comment by tonybaloney** [comment]
I have made the requested changes; please review again

**Pull request merged**
