### PR TITLE
[3.5] bpo-30458: Disallow control chars in http URLs. (GH-12755)

### PR DESCRIPTION
**Pull request by hroncok**
Disallow control chars in http URLs in urllib.urlopen.  This addresses a potential security problem for applications that do not sanity check their URLs where http request headers could be injected.

Disable https related urllib tests on a build without ssl (GH-13032)
These tests require an SSL enabled build. Skip these tests when python is built without SSL to fix test failures.

Use http.client.InvalidURL instead of ValueError as the new error case's exception. (GH-13044)

Co-Authored-By: Miro Hrončok <miro@hroncok.cz>

https://bugs.python.org/issue30458

### CODE REVIEW

**Comment by vstinner** [comment]
AppVeyor failed with:

**Comment by vstinner** [comment]
> It seems like these failures are related to https://bugs.python.org/issue36816: PR #13200 isn't merged yet.

Travis CI basically has the same failures and so it's likely the same issue.

**Review by vstinner — APPROVED** [review]
LGTM. Straightforward backport (cherry-pick). The patch went fine in all other branches.

**Comment by hroncok** [comment]
Compared to 3.6, I've removed the f-strings.

**Comment by larryhastings** [comment]
Thanks for the 3.5 love!

**Pull request merged**
