### PR TITLE
[doc] Add link to FileHandler in logging (GH-21940)

### PR DESCRIPTION
**Pull request by andresdelfino**
No link exists in the doc

Automerge-Triggered-By: @vsajip

### CODE REVIEW

**Review by vsajip — CHANGES_REQUESTED** [review]
The table contains numerous other references to `FileHandler` and `StreamHandler` - I would suggest changing them all to cross-references, or leaving them all as is.

**Review by vsajip — CHANGES_REQUESTED** [review]
Apparently there are conflicts - please resolve.

**Comment by andresdelfino** [comment]
I have made the requested changes; please review again

**Comment by andresdelfino** [comment]
For some reason, make -C Doc/ PYTHON=../python SPHINXOPTS="-q -W --keep-going -j4" doctest suspicious html is not using the created venv.

make htmlview works correctly locally.

**Comment by vsajip** [comment]
I'll close and reopen the pull request to see if that makes a difference.

**Review by vsajip — APPROVED** [review]

**Pull request merged**
