### PR TITLE
gh-90815: Add mimalloc memory allocator

### PR DESCRIPTION
**Pull request by tiran**
https://bugs.python.org/issue46657

gh-90815

### CODE REVIEW

**Comment by neonene** [comment]
JFYI on Windows,
- `test_fstring.test_many_expressions` reserves 150MB memory which seems never released. The following case holds 500MB:
```
build_fstr = lambda n: "f'" + ('{1}' * n) + "'"
exec(build_fstr(350)*1000)
```
- MSVC fails to build x86 PGO, without generating `python311*.pgc` profiles if `test_embed.EmbeddingTests.test_bpo20891` is used for an exercise. The same goes for x64 PGO when trained with only the test.

**Comment by tiran** [comment]
I still can reproduce the issue with unreleased memory with mimalloc 2.0.6. It appears that mimalloc does not give back huge pages to the OS.

```
>>> sys._debugmallocstats()
mimalloc (version: 206)
heap stats:    peak      total      freed    current       unit      count   
  reserved:   64.0 MiB   64.0 MiB      0       64.0 MiB                        not all freed!
 committed:   64.0 MiB   64.0 MiB      0       64.0 MiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB  128.5 KiB 1000.1 KiB -871.6 KiB                        ok
  segments:      1          1          0          1                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0         25        -25                            ok
-abandoned:      0          0          0          0                            ok
 -extended:      0    
 -noretire:      0    
     mmaps:      0    
   commits:      0    
   threads:      0          0          0          0                            ok
  searches:     0.0 avg
numa nodes:       1
   elapsed:       3.205 s
   process: user: 0.050 s, system: 0.007 s, faults: 0, rss: 11.6 MiB, commit: 64.0 MiB
```

```
>>> build_fstr = lambda n: "f'" + ('{1}' * n) + "'"
>>> exec(build_fstr(350)*1000)
```

```
>>> sys._debugmallocstats()
mimalloc (version: 206)
heap stats:    peak      total      freed    current       unit      count   
  reserved:  704.0 MiB  704.0 MiB  128.0 MiB  576.0 MiB                        not all freed!
 committed:  704.0 MiB  704.0 MiB  120.2 MiB  583.7 MiB                        not all freed!
     reset:      0          0          0          0                            ok
   touched:  128.5 KiB    1.5 MiB  838.7 MiB -837.2 MiB                        ok
  segments:     10         12         10          2                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0        7.4 Ki    -7.4 Ki                         ok
-abandoned:      0          0          0          0                            ok
 -extended:      0    
 -noretire:      0    
     mmaps:      0    
   commits:      0    
   threads:      0          0          0          0                            ok
  searches:     0.0 avg
numa nodes:       1
   elapsed:      13.101 s
   process: user: 1.096 s, system: 0.194 s, faults: 0, rss: 585.5 MiB, commit: 704.0 MiB

```

**Comment by tiran** [comment]
- build Python with debug: ``./configure --with-pydebug``
- print mimalloc stats: ``sys._debugmallocstats()``
- run mi_collect: ``sys._mi_collect(True)``
- devguide: https://devguide.python.org/

**Comment by ericsnowcurrently** [comment]
> * MSVC fails to build x86 PGO, without generating `python311*.pgc` profiles if `test_embed.EmbeddingTests.test_bpo20891` is used for an exercise. The same goes for x64 PGO when trained with only the test.

Thanks for identifying this, @neonene!  @zooba just pointed out to me that PGO with x86 isn't something we release, so we'd want to focus on getting it working on x64.

**Comment by tiran** [comment]
For the record ``MIMALLOC_DECOMMIT_DELAY=0`` env var or ``sys._mi_collect(True)`` (force) give back memory to the OS more aggressively. Daan is looking into the matter.

**Comment by zooba** [comment]
> * MSVC fails to build x86 PGO, without generating `python311*.pgc` profiles if `test_embed.EmbeddingTests.test_bpo20891` is used for an exercise. The same goes for x64 PGO when trained with only the test.

Only just actually noticed this comment.

That test is for a native race condition that shouldn't normally need to touch the memory allocator, so hopefully it's just a weird PGO issue. I doubt anything new is being learned in the profile, so we may just be best to skip this test in the default profile (somewhere in the test suite where we handle the `--pgo` option).

**Comment by ericsnowcurrently** [comment]
The PGO problem was fixed with gh-94790.

**Comment by tiran** [comment]
I have rebased the PR again.

**Comment by ericsnowcurrently** [comment]
Thanks!

**Comment by bobfang1992** [comment]
Hi, just want to check if this is still under development?

**Comment by zooba** [comment]
tiran is currently taking a break, so it's not being actively developed. I think we're still interested in using mimalloc though? Probably @ericsnowcurrently is the best person to sync with.

**Comment by erlend-aasland** [comment]
> Probably @ericsnowcurrently is the best person to sync with.

... or @colesbury.

**Comment by daanx** [comment]
Hi, @daanx here from mimalloc -- let me know if I can help with this PR. Just wanted to add that it would be good to merge the latest version of mimalloc as recently I made many improvements in particular for Valgrind and ASAN (and ETW) tools.

**Comment by erlend-aasland** [comment]
Superseded by #109914.

**Pull request closed without merging**
