### PR TITLE
bpo-36424: Add support for pickling frozen dataclasses with __slots__

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Allow to pickle and unpickle frozen dataclasses that have
``__slots__``.

Co-Authored-By: Claudiu Popa <pcmanticore@gmail.com>

https://bugs.python.org/issue36424

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
Some of the added code does not adhere to PEP 8 w.r.t. line length -- that is for symmetry with the adjacent `_create_fn()` calls (which themselves don't follow PEP 8).

**Review by MojoVampire — APPROVED** [review]

**Comment by Kobzol** [comment]
What's the status of this PR? We want to send frozen dataclasses to multiple processes in Keras multi-GPU training and the inability to (un)pickle them severely limits this use case.

**Comment by akulakov** [comment]
@Kobzol this was fixed (see issue) but hasn't been backported to 3.9; so one option is to wait for 3.10 release.

**Comment by hauntsaninja** [comment]
Thanks, this was fixed in https://github.com/python/cpython/pull/25786

**Pull request closed without merging**
