### PR TITLE
bpo-44771: rename namespacedata01 to namespacedata

### PR DESCRIPTION
**Pull request by FFY00**
This should fix the buildbots, see
https://github.com/python/cpython/pull/27436#issuecomment-889896711

Signed-off-by: Filipe Laíns <lains@riseup.net>

https://bugs.python.org/issue44771

### CODE REVIEW

**Comment by pablogsal** [comment]
You need to regenerate importlib probably:

```
  File "<frozen importlib._bootstrap>", line 1008, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'namespacedata01'
----------------------------------------------------------------------
```

**Comment by FFY00** [comment]
`namespacedata01` is only used in the tests, so it shouldn't affect the frozen importlib. I just forgot the `g` at the end of my sed expression so it only replaced the first `namespace01` in each line :sweat_smile:

**Comment by pablogsal** [comment]
> `namespacedata01` is only used in the tests, so it shouldn't affect the frozen importlib.

Haha, yeah, I noticed but then I updated the comment. Seems that not faster than you checked :sweat_smile:

**Comment by jaraco** [comment]
So is the plan here to just cause the files to be deleted on the buildbots, but not merge this change? Just force the buildbots to lose the files long enough that they start passing on main?

**Comment by FFY00** [comment]
Either that or plainly rename the data, but I just noticed I forgot `.giattributes` :facepalm:

Let's let the buildbots run and after that see if they are still failing on new commits. I don't think they should since the data was removed here and they had to check it out again.

**Comment by jaraco** [comment]
I'd like not to have to rename the data, because that creates additional divergence from both `../data01` and also from the implementation in `importlib_resources`. I'd like to have whatever the permanent solution is not to carry the baggage of this incident.

**Comment by pablogsal** [comment]
The original PR also introduced a file descriptor leak that needs to be addressed: https://buildbot.python.org/all/#/builders/320/builds/107

**Comment by jaraco** [comment]
The refleak is occurring in test_path (removing `test_path` causes the refleak errors to go away). I suspect the issue is in how `CompatibilityFiles` adapts for `path`.

**Comment by jaraco** [comment]
I've isolated it to `test_path.CommonTests.test_useless_loader`:

```
cpython main $ git diff
diff --git a/Lib/test/test_importlib/test_path.py b/Lib/test/test_importlib/test_path.py
index 4436d7f34e..871c6d7a0c 100644
--- a/Lib/test/test_importlib/test_path.py
+++ b/Lib/test/test_importlib/test_path.py
@@ -11,6 +11,10 @@ def execute(self, package, path):
         with resources.path(package, path):
             pass
 
+    def test_useless_loader(self):
+        # Temporarily disable test as it's causing refleaks
+        return
+
 
 class PathTests:
     def test_reading(self):

cpython main $ ./python.exe Lib/test/regrtest.py -R : test_importlib
0:00:00 load avg: 2.18 Run tests sequentially
0:00:00 load avg: 2.18 [1/1] test_importlib
beginning 9 repetitions
123456789
.........
test_importlib passed in 38.5 sec

== Tests result: SUCCESS ==

1 test OK.

Total duration: 38.5 sec
Tests result: SUCCESS
cpython main $ git stash
Saved working directory and index state WIP on main: 48a62559df bpo-44648: Fix error type in inspect.getsource() in interactive session (GH-27171)
cpython main $ ./python.exe Lib/test/regrtest.py -R : test_importlib
0:00:00 load avg: 2.53 Run tests sequentially
0:00:00 load avg: 2.53 [1/1] test_importlib
beginning 9 repetitions
123456789
.........
test_importlib leaked [1, 1, 1, 1] file descriptors, sum=4
test_importlib failed (reference leak) in 38.0 sec

== Tests result: FAILURE ==

1 test failed:
    test_importlib

1 re-run test:
    test_importlib

Total duration: 38.0 sec
Tests result: FAILURE
```

**Comment by jaraco** [comment]
This is done its duty and is no longer needed (see #27497). Thanks Filipe.

**Pull request closed without merging**
