### PR TITLE
gh-122943: Add the varpos parameter in _PyArg_UnpackKeywords

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Remove _PyArg_UnpackKeywordsWithVararg.
Add comments for integer arguments of _PyArg_UnpackKeywords.

This is a follow up of #122945. It was not included in #122945 to minimize the diff.

* Issue: gh-122943

### CODE REVIEW

**Review by skirpichev — APPROVED** [review]

**Review by erlend-aasland — APPROVED** [review]
Neat. Consider this style amendment for IMO slightly more readable generated code:

<details>

<summary>diff</summary>

```diff
diff --git a/Tools/clinic/libclinic/parse_args.py b/Tools/clinic/libclinic/parse_args.py
index 8b7afbcf3e4..8d1714b1ebe 100644
--- a/Tools/clinic/libclinic/parse_args.py
+++ b/Tools/clinic/libclinic/parse_args.py
@@ -695,13 +695,21 @@ def parse_general(self, clang: CLanguage) -> None:
                 if has_optional_kw:
                     self.declarations += "\nPy_ssize_t noptargs = %s + (kwargs ? PyDict_GET_SIZE(kwargs) : 0) - %d;" % (nargs, self.min_pos + self.min_kw_only)
                 unpack_args = '_PyTuple_CAST(args)->ob_item, nargs, kwargs, NULL'
-            parser_code = [libclinic.normalize_snippet(f"""
-                {argsname} = _PyArg_UnpackKeywords({unpack_args}, &_parser,
-                        /*minpos*/ {self.min_pos}, /*maxpos*/ {self.max_pos}, /*minkw*/ {self.min_kw_only}, /*varpos*/ {1 if self.varpos else 0}, argsbuf);
+            snippet = f"""
+                {argsname} = _PyArg_UnpackKeywords(
+                    {unpack_args}, &_parser,
+                    /*minpos*/ {self.min_pos},
+                    /*maxpos*/ {self.max_pos},
+                    /*minkw*/ {self.min_kw_only},
+                    /*varpos*/ {1 if self.varpos else 0},
+                    argsbuf
+                );
                 if (!{argsname}) {{{{
                     goto exit;
                 }}}}
-                """, indent=4)]
+            """
+            snippet = libclinic.normalize_snippet(snippet, indent=4)
+            parser_code = [snippet]
 
         if self.requires_defining_class:
             self.flags = 'METH_METHOD|' + self.flags
```

</details>

**Comment by skirpichev** [comment]
> Consider this style amendment for IMO slightly more readable generated code:

(This is why auto-formatting for clinic output (with indent-like tool) might be not a bad idea.)

But if we are going for multi-line code snippet, lets add also spaces to comments: ``/*minpos*/`` -> ``/* minpos */``.

**Comment by erlend-aasland** [comment]
> (This is why auto-formatting for clinic output (with indent-like tool) might be not a bad idea.)

We already do auto-formatting of clinic output[^1]; see `Tools/clinic/libclinic/formatting.py`. But I don't think coercing Argument Clinic to produce "100% correct PEP-7 code" is good use os anyones time. Time is better spent on resolving real Argument Clinic issues.

[^1]: its just that some parts of the generator is not producing very readable code (yet)

**Comment by serhiy-storchaka** [comment]
> Consider this style amendment for IMO slightly more readable generated code:

It would be less readable to me. I have vision problems so I get lost in very scattered code.

> But if we are going for multi-line code snippet, lets add also spaces to comments: `/*minpos*/` -> `/* minpos */`.

I initially wrote it as `/* min_pos */`, but it was too noisy. It was more difficult to find the code between comments.

**Pull request merged**
