### PR TITLE
add .pytest_cache/ to .gitignore

### PR DESCRIPTION
**Pull request by holymonson**
Doesn't need issue or news.

### CODE REVIEW

**Comment by Mariatta** [comment]
Thanks for the PR, but is there reason for proposing this change?
We don't use pytest within the project.

**Comment by holymonson** [comment]
> Thanks for the PR, but is there reason for proposing this change?
We don't use pytest within the project.

@Mariatta - We don't? Then how can we test specified case in `Lib/`?
I was using below and it seems fine.
```
$ pytest lib2to3/tests/test_parser.py::TestAsyncAwait::test_async_var
============================= test session starts ==============================
platform darwin -- Python 3.7.0, pytest-3.7.2, py-1.5.4, pluggy-0.7.1
rootdir: /Users/monson/Projects/cpython, inifile:
collected 1 item

lib2to3/tests/test_parser.py .                                           [100%]

=========================== 1 passed in 0.08 seconds ===========================
```

**Comment by Mariatta** [comment]
You can use pytest for sure, but that's something you install for yourself right?
Our devguide only mentions doing something like `./python -m unittest -v test.test_abc.TestABC`.

https://devguide.python.org/runtests/#running

I would suggest creating your own global .gitignore for this.

**Comment by holymonson** [comment]
I see, thanks.

**Pull request closed without merging**
