### PR TITLE
bpo-40275: Remove all new modules imported by tests

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by shihai1991** [comment]
@vstinner Hi, victor. I checked the codes of your idea:
```Maybe we need a mechanism to load everything needed to run tests, and restore old sys.modules before loading tests. The risk is to load a module multiple times, but I don't think that it's an issue.``` in #20207

* sequential run tests: you have write the unload mechanism, but your code just try to unload the test (sub)modules, so we enhance to unload all new import modules is good enough, no?
* multiprocess run tests: it's run in subprocess, so it's no necessary to unload the import modules in tests, right?

**Comment by iritkatriel** [comment]
Issue issue40275 is closed. What is the status of this PR?

**Comment by shihai1991** [comment]
> https://bugs.python.org/issue40275 is closed. What is the status of this PR?

Hi, Irit. Thanks for your mention. I forget this PR's details already: ( I close it now.

**Comment by vstinner** [comment]
Ah, it was forgotten in https://bugs.python.org/issue40275 which has tons of PRs. Thanks for cleanup @iritkatriel  ;-)

**Pull request closed without merging**
