### PR TITLE
gh-96678: Fix UB of null pointer arithmetic

### PR DESCRIPTION
**Pull request by matthiasgoergens**
* Issue: gh-96678

Automerge-Triggered-By: GH:pablogsal

### CODE REVIEW

**Review by pablogsal — COMMENTED** [review]
Have the assert ever triggered in the test suite? Do you have the stack trace at that point?

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Also can you add a news entry?

**Comment by matthiasgoergens** [comment]
> Have the assert ever triggered in the test suite? Do you have the stack trace at that point?

Yes, the assert triggers in the test suite. You can see ths when you look at the build bot's test run for that commit. I don't know whether that build bot ein gives so a stack trace, though.

I can try to give you stack trace.

**Comment by pablogsal** [comment]
> > Have the assert ever triggered in the test suite? Do you have the stack trace at that point?
> 
> Yes, the assert triggers in the test suite. You can see ths when you look at the build bot's test run for that commit. I don't know whether that build bot ein gives so a stack trace, though.
> 
> I can try to give you stack trace.

No need, just add the NEWS entry and I can land this. Interestingly this code has been here since the beginning of time :P

**Comment by pablogsal** [comment]
Ah, but this should have been detected by the UB buildbot no?

**Comment by pablogsal** [comment]
Ah, indeed. All failures happen in subprocesses

**Comment by matthiasgoergens** [comment]
> Ah, but this should have been detected by the UB buildbot no? This means that it happens only in a subprocess or there is some shenanigans again that prevent this to surface in release mode

I explained the shenanigans in the last comment on the issue.

Basically, it's only undefined behaviour in standard C.

We are using -fwrapv which makes it defined behaviour. That's why the sanitiser doesn't complain.

My goal here to clean this up anyway, so we can consider running without -fwrapv, and perhaps get a few more C compiler optimisations.thst way.

**Comment by pablogsal** [comment]
> We are using -fwrapv which makes it defined behaviour. That's why the sanitiser doesn't complain.

But for this case we need `-fwrapv-pointer`. I assume that's also passed in release mode?

**Comment by pablogsal** [comment]
In any case, I am landing the PR. Thanks a lot for working on this. Your work really makes a difference ❤️

**Comment by matthiasgoergens** [comment]
My goal is to make it so that we can run with -fstrict-overflow (if we want to.)

**Comment by matthiasgoergens** [comment]
@pablogsal https://github.com/faster-cpython/ideas/issues/458 might be interesting for you in this context.

**Review by kumaraditya303 — APPROVED** [review]

**Comment by kumaraditya303** [comment]
The bot isn't merging this because 'awaiting review' was added mistakenly, I am fixing the labels.

**Pull request merged**
