### PR TITLE
gh-114011: Convert for loops in dataclasses module to comprehensions

### PR DESCRIPTION
**Pull request by keithasaurus**
gh-114011: Convert for loops in dataclasses module to comprehensions

This is a simple porting of `for` loops to list comprehensions for performance and readability. I haven't done benchmarking but can if needed.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Thank you, but CPython typically does not accept patches that are primarily cosmetic. If this is for performance reasons, benchmarking the change would be great!

**Comment by rhettinger** [comment]
Stylistically, I don't think these particular changes should be made.

Usually, we prefer list comprehensions when they are short and sweet. But when the bodies grow larger, it is almost always more readable and maintainable to have a traditional loop.   The particular changes in the PR are too large to mentally consume in one gulp.

**Comment by keithasaurus** [comment]
@rhettinger 

Two of the three changes here deal with the `_asdict_inner` function. Ok if I re-target toward optimizing that function? The second two list comprehensions would be part of that, but neither of are particularly difficult on the eyes -- no `if` or walrus operator. There are several other aspects of that function that I think could be modified to speed it up as well -- for example, not checking if something is an instance of a tuple twice, which it currently does. I'm guessing there's something like a 5% speedup available with modest changes.

**Comment by keithasaurus** [comment]
Will open a separate PR for speeding up dataclasses.asdict

**Pull request closed without merging**
