### PR TITLE
bpo-44092: Don't reset statements/cursors before rollback

### PR DESCRIPTION
**Pull request by erlend-aasland**
In SQLite versions pre 3.7.11, pending statements would block a
rollback.  We now require SQLite 3.7.15, so this workaround can go.

https://bugs.python.org/issue44092

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@corona10 This change means that `InterfaceError` is no longer thrown for fetch across rollbacks. This is clearly a change in behaviour, but I can't see how it would break existing apps other than peoples fault handlers not being called :) I guess this also needs a What's New item.

**Comment by erlend-aasland** [comment]
@serhiy-storchaka, I'm not sure how to proceed in order to land this. I'm pretty sure this is correct; it works across all supported SQLite versions. I've tried to ping Berker about this, but I haven't gotten any response. Proposal: We merge this to `main` now; it is still early in 3.11 development, so we have plenty of time to get feedback from the community. For example, the Django people have an extensive sqlite3 test suite, and the've been very quick to report regressions or inaccuracies earlier. If, for some reason, we conclude this is the wrong fix, it will be easy to revert it, in good time for the beta.

**Comment by erlend-aasland** [comment]
@animalize: would you mind reviewing this?

**Comment by animalize** [comment]
I will try, I'm not a deep user of SQL, but if you can't find a reviewer I'm glad to try, hope I can review this in 2~4 weeks.

**Comment by erlend-aasland** [comment]
> I will try, I'm not a deep user of SQL, but if you can't find a reviewer I'm glad to try, hope I can review this in 2~4 weeks.

Great, thanks. You'll find my reasoning in the bpo.

**Comment by erlend-aasland** [comment]
@ghaering: Would you mind reviewing this? (A 👎🏻 or 👍🏻 reaction would be 👌🏻). Totally understand if you won't.

**Comment by animalize** [comment]
It seems `reset` variable can be removed from `pysqlite_Cursor` struct.
I'm not a core developer, maybe no one listens to my opinion, but I will help you to find problems.

**Comment by erlend-aasland** [comment]
Thanks for helping out, @animalize!

**Comment by erlend-aasland** [comment]
@pablogsal, I would have been nice to get this in to the upcoming alpha :)

**Comment by animalize** [comment]
It seems this PR can be committed. Then to do subsequent improvement.

**Review by pablogsal — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thank you, Pablo! 🙏🏻

**Pull request merged**
