### PR TITLE
Implement the get_resource_reader() API for file system imports

### PR DESCRIPTION
**Pull request by warsaw**

### CODE REVIEW

**Comment by warsaw** [comment]
@brettcannon I've moved the zipimport work to a separate branch, still in progress.

**Review by brettcannon — CHANGES_REQUESTED** [review]
It looks great overall, but we do need docs for this.

**Comment by warsaw** [comment]
@brettcannon Didn't you just land the docs for this in bca42186b69e2e615d29d0d4fdb493c9fe71c48b ?

**Comment by warsaw** [comment]
I have made the requested changes; please review again

**Comment by warsaw** [comment]
@brettcannon Ping.  I'm rebasing my zipimporter branch on top of this one, so I'd like to land it soon.  See my previous comment about the docs.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
I landed the docs for the ABC, but I didn't document anything relating to the changes in this PR. I've gone ahead and approved this so you can get your zipimporter changes in as we can do doc changes in after b1 if necessary.

**Pull request merged**
