### PR TITLE
GH-106485: "Un-materialize" `__dict__`s in  `LOAD_ATTR_WITH_HINT`

### PR DESCRIPTION
**Pull request by brandtbucher**
There's a failure path in the specialized bytecode that is often hit by objects that have a materialized `__dict__`, but *probably* don't need it anymore.

I'm running the benchmarks and gathering stats to see how promising this approach is.

* Issue: gh-106485

### CODE REVIEW

**Comment by markshannon** [comment]
Do you have stats for this PR?

**Comment by markshannon** [comment]
There a few scenarios that we should consider. Here are the two I'm concerned about:
1. One or more objects have their `__dict__`s accessed, then an attribute accessed. Alternately
2. Many objects have their `__dict__`s accessed (e.g. by copy or pickle), then attributes are accessed repeatedly

In case 1, we will repeatedly materialize and dematerialize the `__dict__`. Hopefully this case will be rare, so the performance impact will be acceptable.

It is case 2 that matters, IMO.  We need to keep the relevant `LOAD_ATTR`s specialized to `LOAD_ATTR_INSTANCE_VALUES` and at the same time dematerialize the `__dict__`s when we can.

That suggests to me that dematerialization should occur in the specializer and, more importantly, in the deopt path of `LOAD_ATTR_INSTANCE_VALUES`.

In `LOAD_ATTR_INSTANCE_VALUES`
we could replace 
`DEOPT_IF(!_PyDictOrValues_IsValues(dorv), LOAD_ATTR);`
with 
`DEOPT_IF(!_PyDictOrValues_IsValues(dorv), LOAD_ATTR_DEMATERIALIZE)`
and eliminate `LOAD_ATTR_WITH_HINT` altogether.

**Comment by brandtbucher** [comment]
According to the [stats comparison](https://github.com/faster-cpython/benchmarking/blob/main/results/bm-20230706-3.13.0a0-0ab8274/bm-20230706-azure-x86_64-brandtbucher-un_materialize-3.13.0a0-0ab8274-pystats-vs-base.md), the number of `__dict__` materializations "on request" increased from 3.7 million to 3.9 million, but the number of dict "un-materializations" is 3.7 million.

So this is incredibly effective, but the results do *suggest* that some `__dict__`s are "thrashing" back and forth in the [`mypy` benchmark](https://github.com/faster-cpython/benchmarking/blob/main/results/bm-20230706-3.13.0a0-0ab8274/bm-20230706-linux-x86_64-brandtbucher-un_materialize-3.13.0a0-0ab8274-vs-base.png), which got 17% slower and pulled the (otherwise boring) results down to 0.6% slower.

(Sorry, it looks like there aren't public links for these results.)

**Comment by brandtbucher** [comment]
> In case 1, we will repeatedly materialize and dematerialize the `__dict__`. Hopefully this case will be rare, so the performance impact will be acceptable.

See my comment above: the numbers suggest that the `mypy` benchmark does this.

> It is case 2 that matters, IMO. We need to keep the relevant `LOAD_ATTR`s specialized to `LOAD_ATTR_INSTANCE_VALUES` and at the same time dematerialize the `__dict__`s when we can.
>
> That suggests to me that dematerialization should occur in the specializer and, more importantly, in the deopt path of `LOAD_ATTR_INSTANCE_VALUES`.

I think this should stay out of the specializer, since that runs infrequently and only sees the first instance of a class at a given location. I'll try the `LOAD_ATTR_INSTANCE_VALUE` flavor, though.

**Comment by brandtbucher** [comment]
Something about my merge messed up the diff, I think...

**Comment by brandtbucher** [comment]
#106539 is an alternative to this, using `LOAD_ATTR_INSTANCE_VALUE`.

**Comment by brandtbucher** [comment]
Closing in favor of #106539.

**Pull request closed without merging**
