### PR TITLE
gh-102856: Update "Formatted string literals" docs section after PEP701

### PR DESCRIPTION
**Pull request by lysnikolaou**
* Issue: gh-102856

----
:books: Documentation preview :books:: https://cpython-previews--104861.org.readthedocs.build/

### CODE REVIEW

**Comment by pablogsal** [comment]
I think we need to fix also the "grammar" that is included here and substitute that for the PEG grammar

**Comment by pablogsal** [comment]
image

I mean this one

**Comment by pablogsal** [comment]
Hummmm IIRC that grammar is slightly incorrect or it was missing some details. Check it out and if you are happy with it then let's keep it

**Comment by lysnikolaou** [comment]
I briefly compared it with our version in the PEG and it seems okay to me. If you're also okay with it, we can merge.

**Review by pablogsal — APPROVED** [review]
LGTM 

Great work!

**Pull request merged**
