### PR TITLE
bpo-40448: ensurepip: Do not use cache

### PR DESCRIPTION
**Pull request by ghost**
ensurepip optionally installs or upgrades 'pip' and 'setuptools' using
the version of those modules bundled with Python.  The internal PIP
installation routine by default temporarily uses its cache, if it
exists.  This is undesirable as Python builds and installations may be
independent of the user running the build, whilst PIP cache location
is dependent on the user's environment and outside of the build
environment.

At the same time, there's no value in using the cache while installing
bundled modules.

This change disables PIP caching when used in ensurepip.

https://bugs.python.org/issue40448

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@kkonopko

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by ned-deily** [comment]
@pradyunsg Opinions?

**Comment by kkonopko** [comment]
Is there still I need to do about this PR?  No pressure, just checking :)

Should I do anything about bedevere/news, or is it something that a maintainer would take care of when merging?

**Comment by ned-deily** [comment]
I've also just asked on the bug tracker for a review.

**Review by pfmoore — APPROVED** [review]
Looks good to me, and I agree this change makes sense.

**Comment by pfmoore** [comment]
> Is there still I need to do about this PR?

I believe you'll need to fix the test failures and add a news item.

**Review by pradyunsg — APPROVED** [review]
LGTM too!

**Review by dstufft — APPROVED** [review]

**Comment by ned-deily** [comment]
@kkonopko If you would like to add a news entry, please do so.  You can use the `blurb-it` web interface or the `blurb` program (see [here]( https://devguide.python.org/committing/#what-s-new-and-news-entries)).  The [changelog](https://docs.python.org/dev/whatsnew/changelog.html#changelog) has plenty of examples.

**Pull request merged**
