### PR TITLE
bpo-44131: Test Py_FrozenMain()

### PR DESCRIPTION
**Pull request by vstinner**
* Add test_frozenmain to test_embed
* Add Programs/test_frozenmain.py
* Add Programs/freeze_test_frozenmain.py
* Add Programs/test_frozenmain.h
* Add make regen-test-frozenmain
* Add test_frozenmain command to Programs/_testembed

https://bugs.python.org/issue44131

### CODE REVIEW

**Comment by encukou** [comment]
It seems wasteful to generate another frozencopy of importlib. There's already one in `Python/importlib*.h`; can that be used instead?

**Comment by vstinner** [comment]
@encukou: "It seems wasteful to generate another frozen copy of importlib. There's already one in Python/importlib*.h; can that be used instead?"

Right, I wrote the test differently to retrieve the two frozen importlib modules from PyImport_FrozenModules.

**Comment by vstinner** [comment]
Windows (x64): Failing:

> _testembed.obj : error LNK2001: unresolved external symbol __imp_Py_FrozenMain

Ah, it looks like the https://bugs.python.org/issue44133 bug.

**Comment by vstinner** [comment]
Since Py_FrozenMain is not currently exported on Windows, I modified my PR to skip the test on Windows for now. I will enable the test once https://bugs.python.org/issue44133 will be fixed.

**Pull request merged**
