### PR TITLE
Fix documentation typos

### PR DESCRIPTION
**Pull request by pfusik**

### CODE REVIEW

**Review by kumaraditya303 — APPROVED** [review]
Can you sign the CLA https://www.python.org/psf/contrib/contrib-form/ as it will be required for your future contributions.

**Comment by pfusik** [comment]
@kumaraditya303 Signed it yesterday.

**Review by sobolevn — APPROVED** [review]
Thanks!

- Typo in `Doc/c-api/init_config.rst` only exists on 3.10
- Typon in `Doc/howto/descriptor.rst` exists on both 3.9 and 3.10

So, I will mark it as "needs backport" to both versions.

**Comment by pfusik** [comment]
What's the next step with this PR? I see "First-time contributors need a maintainer to approve running workflows."

**Comment by sobolevn** [comment]
@corona10 can you please help us? 🙂

**Review by corona10 — APPROVED** [review]

**Pull request merged**
