### PR TITLE
bpo-46487: Add `get_write_buffer_limits` to Write and _SSLProtocol transports

### PR DESCRIPTION
**Pull request by mooncell07**
https://bugs.python.org/issue46487

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Should wait until @pablogsal resolve issue with failed buildbots

**Comment by kumaraditya303** [comment]
The buildbots are fixed on main branch now.

**Comment by AlexWaygood** [comment]
Oh god, what did I do

**Comment by mooncell07** [comment]
Um, sorry did I do something wrong

**Comment by ambv** [comment]
Nope, all good, @miss-islington went into an infinite loop applying and removing the `automerge` label. It took me a second to fix it, hence the temporary `DO-NOT-MERGE` label.

**Comment by AlexWaygood** [comment]
> Um, sorry did I do something wrong

I managed to trigger an anxiety attack in the miss-islington bot, because I tried to reapply the "automerge" label, to get her to merge your PR. But I'm only a CPython triager, so I don't have merge privileges, hence the anxiety attack.

Nothing to do with you — just me and the bots having a totally normal morning :) thanks @ambv for the quick fix!!

**Pull request merged**
