### PR TITLE
bpo-40133: Add ` unittest.mock.matchers`  with additional matching classes

### PR DESCRIPTION
**Pull request by Flameeyes**
https://bugs.python.org/issue40133

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Flameeyes

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Flameeyes** [comment]
FTR the code is coming from Google, who already has a signed CLA for it.

I will be able to sign my individual CLA this coming Saturday, for any follow up.

**Comment by csabella** [comment]
As per the comments on the bug tracker issue, I'm going to close this as it would be better suited to a PyPI package.

**Comment by gpshead** [comment]
see the bug.

**Comment by csabella** [comment]
Thanks, @gpshead!  :-)

**Comment by cjw296** [comment]
@gpshead - please don't merge this without further discussion on the bug.

**Comment by gpshead** [comment]
mock's owners don't want these features as is.  We can create a new PR for the subset of things that make sense if any.

**Pull request closed without merging**
