### PR TITLE
bpo-36817: Fix reference leak for expr_text in f-string = parsing

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue36817

### CODE REVIEW

**Comment by pablogsal** [comment]
❯ ./python -m test test_future -m test_annotations -R :
Run tests sequentially
0:00:00 load avg: 0.66 [1/1] test_future
beginning 9 repetitions
123456789
.........
test_future passed

== Tests result: SUCCESS ==

1 test OK.

Total duration: 324 ms
Tests result: SUCCESS

**Review by ilevkivskyi — APPROVED** [review]
Thanks for the fix! LGTM.

**Review by ericvsmith — APPROVED** [review]
Thanks for catching this. I kept thinking "I need to remember to make sure that memory gets freed", and then I forgot to do it.

**Comment by pablogsal** [comment]
I am restarting the CI because appveyor failed with some random asyncio error.

**Pull request merged**
