### PR TITLE
Ordering

### PR DESCRIPTION
**Pull request by ghost**
"This feature" refers to automatic concatenation of string literals, not concatenation of variable and literal.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by Mariatta — CHANGES_REQUESTED** [review]
Thanks! I think your proposed change makes sense. However I noticed you made the PR against the 3.6 branch. We work on the master branch first, and then backport it to the earlier versions.
Can you prepare another PR that targets the master branch?

**Comment by ghost** [comment]
I have made the requested changes; please review again.

**Comment by Mariatta** [comment]
Thanks for this PR. I merged your PR that was against `master`.
I'm closing this one, although it is correct, I prefer the backport PRs #4545 and #4546.
The backport PRs have more complete commit message, and they contain references to the original PR on master and the commit hash.

Thanks!

**Pull request closed without merging**
