### PR TITLE
bpo-44479: Simplified LICENSE.txt regeneration in Windows build

### PR DESCRIPTION
**Pull request by zooba**
https://bugs.python.org/issue44479

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
Unfortunately, that specific failing CI only runs post-commit. Even the ``test-with-buildbots`` label doesn't trigger it. So I'm not sure how to test if this works. Especially when I can't reproduce it :(. Sorry.

**Comment by zooba** [comment]
You can manually check whether the generated file (probably `PCbuild\amd64\LICENSE.txt`, but the path will be in the output now) includes the Tcl/Tk license text. Delete the file and do a regular build should be enough.

**Review by Fidget-Spinner — APPROVED** [review]
Wow thanks for the advice. On main, when I delete the file and rebuild, the LICENSE.txt file is created but empty. With this PR it's populated :).

**Comment by zooba** [comment]
Thanks for the review :)

**Pull request merged**
