### PR TITLE
gh-100445: Improve error message for unterminated strings with escapes

### PR DESCRIPTION
**Pull request by hauntsaninja**
* Issue: gh-100445

### CODE REVIEW

**Comment by pablogsal** [comment]
This is in my queue ;) Will review it as soon as I am back from vacation

**Comment by hauntsaninja** [comment]
(This might conflict with PEP 701 changes, in which case feel free to close it)

**Comment by pablogsal** [comment]
Yeah, let's wait until PEP 701 gets a decision to know what to do here :+1:

**Comment by hauntsaninja** [comment]
Coming back to this, rebased on top of latest main :-)

**Comment by hauntsaninja** [comment]
I've fixed the merge conflicts again!

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by pablogsal** [comment]
Great job @hauntsaninja! Thanks for the patience!

**Pull request merged**
