### PR TITLE
bpo-45191: Fix tb_lineno for multi-line expressions

### PR DESCRIPTION
**Pull request by nahco314**
https://bugs.python.org/issue45191

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@NaHCO314

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by FFY00** [comment]
@markshannon could you have a look when you have a moment? Thanks!

**Comment by markshannon** [comment]
@NaHCO314  Can you add a test for the behavior you claim to fix?

**Comment by brettcannon** [comment]
This PR got messed up and ended up pulling in way more than expected. Please try recreating the PR with only your changes.

**Comment by Fidget-Spinner** [comment]
I suspect you're using GH desktop app to merge changes from main into your work branch. If that's so, please try this guide out https://devguide.python.org/gitbootcamp/#updating-your-cpython-fork.

Copying from the guide relevant parts for you:
```md
Another scenario:
- You created some-branch some time ago.
- Time passes.
- You made some commits to some-branch.
- Meanwhile, there are recent changes from the upstream CPython repository.
- You want to incorporate the recent changes from the upstream CPython repository into some-branch.

Solution:

git checkout some-branch
git fetch upstream
git merge upstream/main
git push origin some-branch
```

**Pull request closed without merging**
