### PR TITLE
gh-117335: Handle non-iterables for `ntpath.commonpath`

### PR DESCRIPTION
**Pull request by nineteendo**
* Issue: gh-117335

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
For reference, `posixpath.commonpath()` was changed in #114709. I forget to check also the `ntpath` implementation. :man_facepalming:

**Review by serhiy-storchaka — COMMENTED** [review]
The large part of this PR looks unrelated to this issue. Should not moving the `if not paths` check be enough?

**Comment by nineteendo** [comment]
Yes, but I also wanted to refactor the code a bit. Though if you have remarks about that let me know.

**Comment by serhiy-storchaka** [comment]
Please leave refactoring for another time. It does not look necessary and even related to this issue.

**Comment by nineteendo** [comment]
Wouldn't that be rejected then?

> Note that we don't accept changes that only improve readability. It causes too much churn and too many arguments. But you're welcome to improve readability as part of another change, e.g. a bugfix, enhancement or speed-up, as long as you're not introducing too much risk by tinkering with delicate code. Hope that makes sense?

If you feel like the changes are overkill, I could leave it at this:

```diff
for i, c in enumerate(s1):
    if c != s2[i]:
-        common = common[:i]
-        break
-else:
-    common = common[:len(s1)]
-return drive + root + sep.join(common)
+        return drive + root + sep.join(common[:i])
+return drive + root + sep.join(common[:len(s1)])
```

**Comment by serhiy-storchaka** [comment]
It depends on how large and justified the changes will be.

**Comment by nineteendo** [comment]
I've reverted the unnecessary changes I made. Now only a few variables have been renamed & some statements combined.

**Comment by serhiy-storchaka** [comment]
It looks interesting, and may be not pure cosmetic, but it is not related to the original issue.

**Comment by nineteendo** [comment]
There you go.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Comment by erlend-aasland** [comment]
@nineteendo, could you please have a look at the devguide before opening further PRs. Having a good grasp on how to create a good PR is helpful both for you and for the reviewers; it reduces review churn, CI churn, and frustration in both ends :)

I suggest starting here:
- https://devguide.python.org/getting-started/pull-request-lifecycle/

**Pull request merged**
