### PR TITLE
Remove redundant line missed in pep-492 commit c28890fb

### PR DESCRIPTION
**Pull request by joernheissler**
Also see https://github.com/python/peps/pull/413

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
Good catch, thanks! Did you sign the CLA? I couldn't see it on bugs.python.org.

**Comment by joernheissler** [comment]
No, I did not. And not going to. Procedure is way too complicated.

**Comment by berkerpeksag** [comment]
Ok, we can't accept your contribution without a signed CLA. I will fix documentation and PEP myself.

**Pull request closed without merging**
