### PR TITLE
Bring Python into the new year.

### PR DESCRIPTION
**Pull request by corona10**
Happy New Year ;)

### CODE REVIEW

**Comment by animalize** [comment]
There is a "2016" in `cpython/PC/python_ver_rc.h`, it could be changed to 2021.

**Comment by vstinner** [comment]
Last year, @benjaminp did the commit: commit 946b29ea0b3b386ed05e87e60b8617c9dc19cd53.

**Review by vstinner — APPROVED** [review]
LGTM.

You modified the same files than last year commit, but you also updated PC/python_ver_rc.h which is a good thing.

**Comment by vstinner** [comment]
This change should not be backported to 3.6 and 3.7, it's not a security fix: https://devguide.python.org/#status-of-python-branches

**Comment by ned-deily** [comment]
@vstinner The copyrights are an exception. They should be updated on still active branches.

**Comment by ned-deily** [comment]
@corona10 If you would care to deal with the merge conflict for 3.6, I'll see that the PR gets merged.  Thanks!

**Comment by vstinner** [comment]
> @vstinner The copyrights are an exception. They should be updated on still active branches.

Oh. I didn't know, good to know.

**Comment by pombredanne** [comment]
Reposting from:
https://github.com/python/cpython/commit/de6f20a6de48d63066b2cf5b317f50629f01d74a#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R87

Could we stop making these constant changes to the license texts juts for a new year? these really not matter much. Constant change in the license texts make the downstream identification more complex and brings zero benefits IMHO

**Pull request merged**
