### PR TITLE
Improved Code 2

### PR DESCRIPTION
**Pull request by machinexa2**
Thats it for day, If any special/weird cases comes out or bug then mention me.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@machinexa2

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by machinexa2** [comment]
I have filled out form, send to contributors@python.org, but still not CLA.

**Comment by Fidget-Spinner** [comment]
I feel that this may cause changes in behavior. This applies to anything changing ```if x is not None:``` to ```if x:```.
Checking for `None` is very different from checking for Falsey. The problem with the change is that it leads to `[]`, `{}`, `""`, `0`, `()`, etc. all fulfilling that check. This may cause unintended behavior because sometimes the code _does_ want to allow `[]` through, but specifically not `None`. However by changing to `if x:`, `[]` is denied too.

It seems that some behavior has already been changed, tests for argparse on all platforms seem to be failing with this PR.

**Comment by Mariatta** [comment]
I agree with @Fidget-Spinner. The change is invasive, and didn't actually fix anything. Generally we don't change what's already working unless there is actual bug.

**Pull request closed without merging**
