### PR TITLE
GH-93728: fix memory leak in deepfrozen code objects

### LINKED ISSUE #93728: Memory leak when reading co_code attribute of deepfrozen code objects
Reproducer:
```py
import os
os.path.join.__code__.co_code
```

Relevant Valgrind Report:
```console
==21416== HEAP SUMMARY:
==21416==     in use at exit: 397 bytes in 1 blocks
==21416==   total heap usage: 19,728 allocs, 19,727 frees, 2,629,532 bytes allocated
==21416== 
==21416== 397 bytes in 1 blocks are still reachable in loss record 1 of 1
==21416==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==21416==    by 0x2FA6DD: _PyMem_RawMalloc (obmalloc.c:101)
==21416==    by 0x2FC5CD: PyObject_Malloc (obmalloc.c:713)
==21416==    by 0x287BDC: _PyBytes_FromSize (bytesobject.c:103)
==21416==    by 0x2881A6: PyBytes_FromStringAndSize (bytesobject.c:136)
==21416==    by 0x29F609: _PyCode_GetCode (codeobject.c:1374)
==21416==    by 0x29F69B: code_getcode (codeobject.c:1728)
==21416==    by 0x2A31B2: getset_get (descrobject.c:202)
==21416==    by 0x2F86E6: _PyObject_GenericGetAttrWithDict (object.c:1269)
==21416==    by 0x2F8F14: PyObject_GenericGetAttr (object.c:1357)
==21416==    by 0x2F9864: PyObject_GetAttr (object.c:912)
==21416==    by 0x3B5B16: _PyEval_EvalFrameDefault (ceval.c:3472)
==21416== 
==21416== LEAK SUMMARY:
==21416==    definitely lost: 0 bytes in 0 blocks
==21416==    indirectly lost: 0 bytes in 0 blocks
==21416==      possibly lost: 0 bytes in 0 blocks
==21416==    still reachable: 397 bytes in 1 blocks
==21416==         suppressed: 0 bytes in 0 blocks
==21416== 

```
 This is a 3.12 only regression caused by #93382.

### PR DESCRIPTION
**Pull request by kumaraditya303**
Closes #93728

### CODE REVIEW

**Comment by kumaraditya303** [comment]
Skipping news as no release is affected.

**Comment by kumaraditya303** [comment]
Valgrind report with fix:
```console
==27367== HEAP SUMMARY:
==27367==     in use at exit: 0 bytes in 0 blocks
==27367==   total heap usage: 19,728 allocs, 19,728 frees, 2,629,532 bytes allocated
==27367== 
==27367== All heap blocks were freed -- no leaks are possible
==27367== 
==27367== Use --track-origins=yes to see where uninitialised values come from
==27367== For lists of detected and suppressed errors, rerun with: -s
==27367== ERROR SUMMARY: 40 errors from 12 contexts (suppressed: 0 from 0)

```

**Comment by Fidget-Spinner** [comment]
I had an inkling that something was off about my PR (things were going too well :), but I'm really glad you caught this before any releases went out. Thanks again Kumar.

**Review by Fidget-Spinner — COMMENTED** [review]
From my very rudimentary understanding of deepfreeze, this LGTM.

**Comment by kumaraditya303** [comment]
> I'm really glad you caught this before any releases went out. Thanks again Kumar.

Yeah, its nice that no release has this leak and I caught this early in 3.12 dev cycle.

**Review by gvanrossum — APPROVED** [review]
LGTM.

The `co_code` field is a cache for the `co_code` attribute, initialized to `NULL` in `init_code()`, set to a bytes object (caching the deoptimized code) in `_PyCode_GetCode()` and decref'ed in `code_dealloc()`. It is also (implicitly) initialized to `NULL` in deepfreeze (since the real bytecode lives in `co_code_adaptive`). So it makes sense that clearing it is the right thing to do when restoring the initial state.

(Using `.replace()` sets `co_code` to the deoptimized code if it wasn't passed in, I think that is due to the way that API works.)

**Pull request merged**
