### PR TITLE
bpo-23835: Enforce that configparser defaults are strings

### PR DESCRIPTION
**Pull request by aragilar**
This is the patch attached to https://bugs.python.org/issue23835, updated to master.

https://bugs.python.org/issue23835

### CODE REVIEW

**Review by ambv — CHANGES_REQUESTED** [review]
Instead of this, reading defaults should be done by calling`self.read_dict()`, then it will behave consistently with doing:

```py3
cp['DEFAULT'] = {1: 2.4}
```

**Comment by aragilar** [comment]
Yeah, that seems more sensible (I originally wrote the patch against 2.7, which is why I didn't use read_dict). Do you want the new version in a new PR, or just replace the current PR with the new code? Also, where should I add a test, I couldn't find where I should add it last time I looked.

**Comment by ambv** [comment]
Replacing the current PR is totally fine. There are tests for configparser in Lib/test/test_configparser.py.

**Comment by aragilar** [comment]
Done.

**Comment by aragilar** [comment]
Ping?

**Comment by ambv** [comment]
I'll add a NEWS.d entry in a separate PR.

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨

**Pull request merged**
