### PR TITLE
bpo-33772: Fix couple of dead code paths

### PR DESCRIPTION
**Pull request by ghost**
https://bugs.python.org/issue33772

### CODE REVIEW

**Review by methane — APPROVED** [review]

**Review by methane — COMMENTED** [review]
In ast.c and compile.c, `break` before next `case` seems worth.
It notes that "this case clause doesn't fallthrough".

Others seems good to me.

**Comment by dcarlier-afilias** [comment]
In ast.c and compile.c they always return before the `break

**Comment by methane** [comment]
> In ast.c and compile.c they always return before the break

I know.  But the case clause is not so simple.  It takes several seconds to read code for knowing it.

**Comment by dcarlier-afilias** [comment]
I hope I m not asking too much :-) but any opinion on this older PR ?

https://github.com/python/cpython/pull/6286

**Comment by csabella** [comment]
Closing and re-opening to retrigger CI checks.

**Comment by csabella** [comment]
@dcarlier-afilias, thank you for the pull request and, @methane, thank you for the code review and approval.

**Pull request merged**
