### PR TITLE
gh-112388: Fix an error that was causing the parser to try to overwrite tokenizer errors

### PR DESCRIPTION
**Pull request by pablogsal**
* Issue: gh-112388

### CODE REVIEW

**Comment by carsonRadtke** [comment]
Maybe scope creep, but is there an opportunity for an improvement here?

`_PyPegen_raise_error` always returns `NULL` - maybe it should be `void`.

**Review by sunmy2019 — APPROVED** [review]
Looks good

**Comment by sunmy2019** [comment]
> `_PyPegen_raise_error` always returns `NULL` - maybe it should be `void`.

We need a placeholder here. If you track the caller, it's like
```c
void *a;
if (all_good)
    a = ...;
else
    a = _PyPegen_raise_error(...);
```

**Review by lysnikolaou — APPROVED** [review]
LGTM!

**Comment by lysnikolaou** [comment]
> `_PyPegen_raise_error` always returns `NULL` - maybe it should be `void`.

Most of the time we assign the return value of `_PyPegen_raise_error` to the variable returned by the rule. This is a "hack" to set a specific error from a grammar action, but still signify to the parser that the rule has failed and it should backtrack all the way.

**Pull request merged**
