### PR TITLE
gh-99108: Add missing md5/sha1 defines to Modules/Setup

### PR DESCRIPTION
**Pull request by asottile**
* Issue: gh-99108

### CODE REVIEW

**Comment by asottile** [comment]
cc @msprotz @erlend-aasland 

looks like these were missed too (copied them from Modules/Setup.stdlib.in)

this fixes the deadsnakes builds -- still not sure why this file doesn't get tested in `cpython` itself or how it differs from Setup.stdlib.in 🤷

**Comment by erlend-aasland** [comment]
As GPS noted on the related PR, this file is really not used anymore. We should tear it out.

**Comment by asottile** [comment]
> As GPS noted on the related PR, this file is really not used anymore. We should tear it out.

debian still uses it -- is there a guide on what to replace it with?

```console
$ wget -q http://deb.debian.org/debian/pool/main/p/python3.11/python3.11_3.11.2-4.debian.tar.xz
$ tar --to-stdout -xf * debian/rules | grep -nC3 Modules/Setup
537-define __post_configure
538-	egrep \
539-	  "^#($$(awk -v ORS='|' '$$2 ~ /^extension$$/ {print $$1}' debian/PVER-minimal.README.Debian.in)XX)" \
540:	  Modules/Setup \
541-	    | sed -e 's/^#//' -e 's/-Wl,-Bdynamic//;s/-Wl,-Bstatic//' \
542:	    >> $(1)/Modules/Setup.local
543-
544-	: # unconditionally run makesetup
545-	cd $(1) && \
546-	  ../Modules/makesetup -c ../Modules/config.c.in -s Modules \
547:	    Modules/Setup.local Modules/Setup.bootstrap Modules/Setup.stdlib ../Modules/Setup
548-	mv $(1)/config.c $(1)/Modules/
549-
550-	: # and fix the timestamps
```

**Comment by erlend-aasland** [comment]
Is there even a guide on how to use `Modules/Setup`? ;) The link you provided is for 3.11; `main` is 3.12.

**Review by erlend-aasland — APPROVED** [review]

**Comment by asottile** [comment]
> Is there even a guide on how to use `Modules/Setup`? ;) The link you provided is for 3.11; `main` is 3.12.

sorry here's the link for 3.12: https://salsa.debian.org/cpython-team/python3/-/blob/db3395e789613c8d01502da8a1be68a976337022/debian/rules#L544

I'm not sure, but it's been using this file for years as far as I know

**Comment by erlend-aasland** [comment]
It seem that Modules/Setup is still tied to the build system, including fairly recent changes by Christian. _IIRC_, he has a long term goal of getting rid of it, but as long as the file is here (and being used in the wild), we should of course keep it up to date.

Thanks for noticing, and thanks for the patch!

**Comment by erlend-aasland** [comment]
> I'm not sure, but it's been using this file for years as far as I know

Correct, Modules/Setup has been in use for many years.

**Pull request merged**
