### PR TITLE
bpo-40275: Use new test.support helper submodules in tests

### PR DESCRIPTION
**Pull request by shihai1991**
Use test helpers in the following test cases:

* test_dbm_gnu
* test_faulthandler
* test_grp
* test_dbm_gnu
* test_faulthandler
* test_grp
* test_http_cookiejar
* test_httpservers
* test_import
* test_ntpath
* test_site
* test_socketserver
* test_statistics
* test_tabnanny
* test_tcl
* test_md5sum
* test_turtle
* test_urllib2net
* test_urllibnet
* test_webbrowser
* test_winsound
* test_tkinter

https://bugs.python.org/issue40275

### CODE REVIEW

**Comment by shihai1991** [comment]
cc @vstinner

**Comment by vstinner** [comment]
@shihai1991: How many remaining tests need to be patched? Do you have an estimation?

**Comment by shihai1991** [comment]
> @shihai1991: How many remaining tests need to be patched? Do you have an estimation?

I have ported all tests what I can test in my centos vm. To some testcases  which runs in windows and macos I depend ci gate to estimate.
I estimate it's between 5 to 8(not too exact)

**Comment by vstinner** [comment]
> I estimate it's between 5 to 8(not too exact)

That's great!

> I have ported all tests what I can test in my centos vm. To some testcases which runs in windows and macos I depend ci gate to estimate.

You can write a test/WIP PR which removes aliases in test.support and see which tests fail.

**Comment by shihai1991** [comment]
> You can write a test/WIP PR which removes aliases in test.support and see which tests fail.

yep. I have already did this ; )

**Pull request merged**
