### PR TITLE
GH-98219: reduce sleep time in `asyncio` subprocess test

### PR DESCRIPTION
**Pull request by kumaraditya303**
Instead of `100000000`, `2` is used so that the test still works but the process completes after 2 sec and hopefully avoid permission errors.

* Issue: gh-98219

### CODE REVIEW

**Comment by kumaraditya303** [comment]
FWIW this seems to only happen on very slow machines like Github Actions and with Windows 10. I have tried to reproduce this on Windows 11 but no luck.

**Comment by kumaraditya303** [comment]
Windows tests passed, triggering bots again to check again that it works. For reference previous run https://github.com/python/cpython/actions/runs/3460146711/jobs/5776365470

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
Should this be backported to 3.11?

**Comment by kumaraditya303** [comment]
> Should this be backported to 3.11?

Yes!

**Comment by gvanrossum** [comment]
Do the buildbot failures look like our fault?

**Pull request merged**
