### PR TITLE
Fix tense build to built

### PR DESCRIPTION
**Pull request by calebmarchent**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Review by pganssle — APPROVED** [review]
This seems like a straightforward fix to the grammar, I'm not sure it needs NEWS (CLA might be legally arguable as well since it may not meet the minimum requirements to be copyrightable, but better safe than sorry on that).

**Comment by calebmarchent** [comment]
I sent the signed CLA through AdobeSign on 4th April; but have not seen a response?

**Comment by tirkarthi** [comment]
https://check-python-cla.herokuapp.com/ indicates it's signed.

**Review by tirkarthi — APPROVED** [review]

**Comment by calebmarchent** [comment]
All we need now is the "skip issue" and "skip news" tags and someone with commit access can merge.

**Comment by pganssle** [comment]
CC: @willingc @merwok as the two people on the "experts list" for documentation whose github names I know 😉.

I think we just need the skip news and skip issue labels, then this can be merged. I'd also say a backport to 3.7, since [this typo is also present in the 3.7 documentation](https://docs.python.org/3.7/extending/building.html#distributing-your-extension-modules).

**Comment by merwok** [comment]
@python/cpython-bots The #/GH thing is still annoying.  Can there be a way to write the desired commit message then use automerge?

**Comment by merwok** [comment]
Thanks for the patch!

**Comment by calebmarchent** [comment]
Thanks for the merge :)

**Pull request merged**
