### PR TITLE
bpo-45510: Specialize BINARY_SUBTRACT

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue45510

### CODE REVIEW

**Comment by corona10** [comment]
Work based on https://github.com/python/cpython/pull/29010

**Comment by sweeneyde** [comment]
Shouldn't CHECK_BINOP be removed from _PyLong_Subtract?

**Comment by corona10** [comment]
@sweeneyde 

>Shouldn't CHECK_BINOP be removed from _PyLong_Subtract?

Thanks :) Updated!

**Comment by Fidget-Spinner** [comment]
LGTM. I'm interested to see what the final benchmark results from the faster-cpython machine gives.

**Comment by markshannon** [comment]
[Performance results](https://gist.github.com/markshannon/ba7dd51a4522ec21aac397be563bfc4b) shows a speedup.

**Pull request merged**
