### PR TITLE
Update ga_new to use _PyArg_CheckPositional and _PyArg_NoKwnames

### PR DESCRIPTION
**Pull request by corona10**

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM.

**Review by gvanrossum — COMMENTED** [review]
Thanks! I hope you’ll try to implement a cache next.

**Comment by corona10** [comment]
> Thanks! I hope you’ll try to implement a cache next.

I will try it! Thanks

**Comment by vstinner** [comment]
@corona10: Oh, I didn't notice that this PR has no bpo associated with. You could reuse https://bugs.python.org/issue40369 since your change was initially proposed here, as part of a larger change. I like to link commits to bpo which provide more context. Sometimes, it's not worth it to create an issue just for a small cleanup change.

Don't worry, it's not a big deal. It's just a minor remark for your future changes ;-)

**Pull request merged**
