### PR TITLE
bpo-43094: Update sqlite3 docs to match implementation

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue43094

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@berkerpeksag Would you mind reviewing this?

skip news, I presume.

**Review by Fidget-Spinner — APPROVED** [review]
I'm not Berker, but this LGTM :).

For convenience:
create_function:
https://github.com/python/cpython/blob/3ccef1ca474592e191a00e131dfbaf777db271e9/Modules/_sqlite/clinic/connection.c.h#L97

create_aggregate:
https://github.com/python/cpython/blob/3ccef1ca474592e191a00e131dfbaf777db271e9/Modules/_sqlite/clinic/connection.c.h#L160

Which seems to match up with the changes in the docs.

**Comment by terryjreedy** [comment]
This is a substantive change, not a typo or grammar fix, so I would not merge without a blurb.

**Comment by Fidget-Spinner** [comment]
Sorry if this isn't related, but I just noticed the docstrings on some other functions don't match either:
Eg create_collation docstring:
https://github.com/python/cpython/blob/3ccef1ca474592e191a00e131dfbaf777db271e9/Modules/_sqlite/clinic/connection.c.h#L623

Ref:
https://github.com/python/cpython/blob/3ccef1ca474592e191a00e131dfbaf777db271e9/Modules/_sqlite/clinic/connection.c.h#L633

Meanwhile the one on python docs is correct
https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_collation

I wonder if this is intentional to avoid callable shadowing the actual builtin callable function?

**Comment by erlend-aasland** [comment]
> Sorry if this isn't related, but I just noticed the docstrings on some other functions don't match either:
> Eg create_collation docstring:
> [...] 

That seems to be a regression from #23341. Good catch! I guess it's fine to include that one in this PR. I'll do an audit of all docstrings/docs/specs in `sqlite3` and add any discrepancies to the PR.

**Comment by erlend-aasland** [comment]
> This is a substantive change, not a typo or grammar fix, so I would not merge without a blurb.

Noted. Thanks!

**Comment by erlend-aasland** [comment]
@Fidget-Spinner: I've done an audit of the module level functions. Should this be backported to 3.9 and 3.8? If so, I will have to split this PR in two: one that contains docstring fixes (regressions from my recent AC change), and one that contains documentation fixes that should be backported.

**Comment by Fidget-Spinner** [comment]
> @Fidget-Spinner: I've done an audit of the module level functions. Should this be backported to 3.9 and 3.8? If so, I will have to split this PR in two: one that contains docstring fixes (regressions from my recent AC change), and one that contains documentation fixes that should be backported.

Thanks for fixing them! My hunch is the regression fixes should go into another PR with the bpo number same as the PR which caused the regression, while the backportable stuff remains in this PR. **However I am not an sqllite3 expert by any means**, so I wouldn't be surprised if this hunch is wrong.

**Comment by erlend-aasland** [comment]
> Thanks for fixing them! My hunch is the regression fixes should go into another PR with the bpo number same as the PR which caused the regression, while the backportable stuff remains in this PR.

Makes sense!

**Comment by terryjreedy** [comment]
Do not merge yet because there is still discussion on pydev, and some disagreement, as to precisely the fix should be.  In particular, can we make the proper names keyword only?  Please make sure you read the thread and wait for consensus.

Regression fixes do not have to be attached to the regressing issue.  It has been done both ways, with a note on the original issue if done on a separate issue.

**Comment by erlend-aasland** [comment]
> Do not merge yet because there is still discussion on pydev, and some disagreement, as to precisely the fix should be.  In particular, can we make the proper names keyword only?  Please make sure you read the thread and wait for consensus.
> 
> 
> 
> Regression fixes do not have to be attached to the regressing issue.  It has been done both ways, with a note on the original issue if done on a separate issue.

Yes, I'm following the thread. I think I'll close this PR bco. noise, and open a new one when there's concensus.

**Pull request closed without merging**
