### PR TITLE
GH-104395: Add a link in 'Meta Information' to the docs download page

### PR DESCRIPTION
**Pull request by AA-Turner**
* Issue: gh-104395

----
:books: Documentation preview :books:: https://cpython-previews--104443.org.readthedocs.build/

### CODE REVIEW

**Comment by terryjreedy** [comment]
I have no opinion at the moment.

**Review by ned-deily — APPROVED** [review]
LGTM, thanks!

**Review by hugovk — APPROVED** [review]

**Comment by adorilson** [comment]
> * Issue: [Add link to Download page on documentation index #104395](https://github.com/python/cpython/issues/104395)
> 
> 
> books Documentation preview books: https://cpython-previews--104443.org.readthedocs.build/

Thanks for your PR, Adam.

I just would like to do a suggestion more.

Download sounds more related to "Reporting bugs" and "Contributing to Docs" items than "History" and "Copyright" ones. By other hand, "About" seems more related to this latest.

So, I suggest:

First column:
- Reporting...
- Contributing...
- Download...

Second column:
- About...
- History...
- Copyright

Maybe this can be a little detail, but it do more sense for me as a user.

**Comment by hugovk** [comment]
So instead of:

image

Flip the last two:

image

Seems okay to me: first column are things to do, second is just information.

**Comment by CAM-Gerlach** [comment]
FWIW, the other items have rather strange, distracting and inconstant case (sentence/title), phrasing (Docs/documentation, "of Python" or not) and ordering (should most logically be About, History, Copyright), but if we're adding this one, may as well at least add it where it makes the most sense.

**Comment by adorilson** [comment]
@CAM-Gerlach I agree with you.

But one point more. Maybe "History and License" is in wrong section, because the others items are about documentation (meta information), but it is about Python itself. So, what if move this item to "Parts of documentation" section?

**Comment by JulienPalard** [comment]
Feel strange that on the top left we have "Download these documents" and at the bottom "Download the documentation", should the wording be unified?

I'm also not a fan to duplicate this link, should it really be duplicated, or just moved out of the sidebar?

While we're at it: should the sidebar be kept at all? The version picker already exists on the top of the page, and maybe other things can be moved.

It would provide more space for the main page, allowing to make it more user friendly. I remember when I started Python I "feared" this page: too many links, eyes were lost looking at it.

**Comment by hugovk** [comment]
Jist today, someone said they wished they could download the Python tutorial as PDF or epub, not realising they're already available. 

Let's merge this, it's an improvement over the current situation. And we can open a new issue or PR if we wish to make further changes.

**Pull request merged**
