### PR TITLE
bpo-41445: Added configure temporary files to gitignore

### PR DESCRIPTION
**Pull request by pokemonish**
https://bugs.python.org/issue41445

https://bugs.python.org/issue41445

### CODE REVIEW

**Comment by methane** [comment]
Don't edit `configure` script directly.
It is generated by `configure.ac`.
See https://devguide.python.org/setup/#regenerate-configure

**Comment by methane** [comment]
On my machine, all files generated by `configure` are ignored. Why do you propose adding these files?

**Comment by wasiher** [comment]
When I was playing with configure script, I noticed that while configure quite a lot `conftest*` files are popped out and removed. Also I read that configure does not try to use /tmp directories and so on, because they are not reliable.
If you just run this in one tab:
`while true; do git add . && git diff; done`
And run this in other one:
`./configure`
Garbage files will pop in the diff.
By this reason I just tracked genereated files, and put them into .gitignore.

**Comment by wasiher** [comment]
Maybe it is important
I used linux

**Comment by ammaraskar** [comment]
If they're created and removed, is there a reason this should be added to the `.gitignore`? Under what situation would you be doing `git add` between the window of running `./configure` and it finishing?

**Comment by wasiher** [comment]
I understand the position that it maybe a kind of overkill to add these files to gitignore.
But on the other side I am not sure that I understand why I can't call `git add` whenever I wish.

I think that it can be a good idea to create a temporary directory to pass all temporary files, so I tried to understand how to do that in autoconf, but my mind was not still so strong to get to the point of understanding how to do that correctly.

Also Inada Naoki told a good idea about running the `./configure` script from other folder to produce a Python build fully there to make it possible not to mix source and build. I like this idea and i will use it, but it is not a forbidden way to call a `./configure` in the folder where it is placed.

So, I am questionin myself this question too. Do we need to pass these a little bit akward, but not harmful lines to .gitignore in the name of freedom of using `git add` or not?

**Comment by methane** [comment]
> I think that it can be a good idea to create a temporary directory to pass all temporary files, so I tried to understand how to do that in autoconf, but my mind was not still so strong to get to the point of understanding how to do that correctly.

As I wrote in bpo, you can use separated build dir and keep source tree clean.

**Comment by methane** [comment]
As far as I Googled, it is not common convention to add these files to gitignore.
See https://github.com/github/gitignore/blob/master/Autotools.gitignore for example.

**Comment by wasiher** [comment]
Closing it as not important on bugtracker :)

**Pull request closed without merging**
