### PR TITLE
[doc] Fix a typo in the graphlib docs

### PR DESCRIPTION
**Pull request by mariosasko**
This PR fixes a typo in the docs of a `TopologicalSorter.is_active`.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@mariosasko

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by tirkarthi — APPROVED** [review]
LGTM. Thanks.

**Comment by tirkarthi** [comment]
Please update your branch with the latest master branch since it has changes that will help docs build error.

**Comment by mariosasko** [comment]
> Please update your branch with the latest master branch since it has changes that will help docs build error.

Did it.

**Comment by pablogsal** [comment]
Thanks @mariosasko for the PR! 🎉

**Pull request merged**
