### PR TITLE
bpo-29617: Remove Python 3.3 support from asyncio

### PR DESCRIPTION
**Pull request by methane**
[[bpo-29617](https://bugs.python.org/issue29617)]

### CODE REVIEW

**Comment by methane** [comment]
tips: https://github.com/python/cpython/pull/232/files?w=1 can be used to ignore indent changes while review.

**Review by deronnax — CHANGES_REQUESTED** [review]
from what I see, the "compat" import isn't used anymore in this file after your patch and can be removed

**Comment by methane** [comment]
@deronnax nice catch!

**Comment by vstinner** [comment]
Oh, I'm very happy to see the removal of the ugly _TracebackLogger class with its giant docstring to justify its design :-) It's also nice to see all conditional code on ``__del__()``.

**Comment by vstinner** [comment]
Before approving, how do Python 3.3 users get asyncio? "python3.3 -m install asyncio" which gets https://pypi.python.org/pypi/asyncio backport? This version is no more maintained, right? (Latest release: 2015-03-10.)

The asyncio documentation (on readthedocs.io) requires 3.5 or higher!
http://asyncio.readthedocs.io/en/latest/getting_started.html#python-3-5-or-higher-only

**Comment by methane** [comment]
If PyPI package for Python 3.3 is needed, we can export code from 3.6 branch.
It means new features of Python 3.7+ are not ported to asyncio for Python 3.3.

And if asyncio on PyPI won't be updated anymore, we can remove `compat` module completely.

**Comment by vstinner** [comment]
> If PyPI package for Python 3.3 is needed, we can export code from 3.6 branch. It means new features of Python 3.7+ are not ported to asyncio for Python 3.3.

Two years ago, the policy was to use exactly the same code base on all CPython branches and on the https://github.com/python/asyncio project.

What is the current policy?

https://github.com/python/asyncio description is "This project is the asyncio module for Python 3.3". Do we still need this project? This project has 76 open issues and 12 pull requests.

**Comment by vstinner** [comment]
> If PyPI package for Python 3.3 is needed, we can export code from 3.6 branch. It means new features of Python 3.7+ are not ported to asyncio for Python 3.3.

Two years ago, the policy was to use exactly the same code base on all CPython branches and on the https://github.com/python/asyncio project.

What is the current policy?

https://github.com/python/asyncio description is "This project is the asyncio module for Python 3.3". Do we still need this project? This project has 76 open issues and 12 pull requests.

**Comment by methane** [comment]
I added @gvanrossum and @1st1 to nosy list of https://bugs.python.org/issue29617 and
waiting future plan of it.

**Comment by 1st1** [comment]
@methane Let's merge this!

**Review by 1st1 — APPROVED** [review]
Looks good. Please rebase it to the latest master.

**Pull request merged**
