### PR TITLE
bpo-46042: Improve SyntaxError locations in the symbol table

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue46042

### CODE REVIEW

**Comment by cfbolz** [comment]
Looks good to me! I like the macros and just having `symtable_add_def` always take a position.

**Comment by cfbolz** [comment]
I think we could be even more general. It seems the other two remaining uses of `ste_lineno` for error locations are also wrong:

```python
[x for x in range(10)
        if (yield) == 5]
```

```python
def f():
    from math import *
```

**Comment by pablogsal** [comment]
These two are a bit more complex because we would need to identify which of the comprehension generators have a 'yield' inside, but that happens downstream from us.

**Comment by pablogsal** [comment]
From the second example I have submitted another commit

**Comment by cfbolz** [comment]
PyPy has the equivalent of an extra `ste_type` in the `_block_type` enum that's used for comprehensions. Then you could produce the error when visiting the yield?

**Comment by pablogsal** [comment]
> PyPy has the equivalent of an extra `ste_type` in the `_block_type` enum that's used for comprehensions. Then you could produce the error when visiting the yield?

We would need to also know the comprehension type to raise properly

**Comment by pablogsal** [comment]
Nevermind, I found a better workaround that is not too inelegant IMHO

**Comment by cfbolz** [comment]
Nice, that's a good approach!

**Pull request merged**
