### PR TITLE
Rename Doc/README.txt to Doc/README.rst

### PR DESCRIPTION
**Pull request by ghost**
I have simply updated the document and its references to README.rst (thanks to whoever formatted it).

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least a day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

**Comment by nedbat** [comment]
This is being handled in #2.

**Comment by ghost** [comment]
I have signed the CLA, so the PR will take a day for approval

**Comment by methane** [comment]
@rogersachan master branch already renamed README.txt -> README.rst
Please rebase your branch.

**Comment by ghost** [comment]
I accidentally merged and destroyed this PR, so I'll close it now.


P.S. The extra option next to the merge button would have let you rebase it but ¯\_(ツ)_/¯

**Comment by willingc** [comment]
Hi @rogersachan,

Thanks for the PR. It's common practice in open source for the contributor to rebase their submission instead of the maintainer doing it. By the contributor doing the rebase, it makes things more efficient for multiple reviewers. 👍

**Pull request closed without merging**
