### PR TITLE
cross port importlib-metadata PR #76

### PR DESCRIPTION
**Pull request by asottile**
https://gitlab.com/python-devs/importlib_metadata/merge_requests/76

### CODE REVIEW

**Comment by asottile** [comment]
(needs backport to 3.8 only)

**Comment by warsaw** [comment]
@Mariatta Interesting buglet: If I add two labels at the same time (i.e. skip-news and skip-issue), it seems like the bot only gets one of them.  I had to unapply skip-news and then reapply it.

**Review by warsaw — APPROVED** [review]

**Comment by Mariatta** [comment]
Hmm this might be a GitHub related issue, a race condition of some sort..

**Comment by warsaw** [comment]
> Hmm this might be a GitHub related issue, a race condition of some sort..

Yeah, probably

**Pull request merged**
