### PR TITLE
GH-93880: Improved conciseness of ipaddress factory functions (GH-93917)

### PR DESCRIPTION
**Pull request by Nougat-Waffle**
```
gh-93880: Improved conciseness of ipaddress factory functions
```

### CODE REVIEW

**Comment by AlexWaygood** [comment]
The issue number needs to be in the title of the PR, not the description of the PR

**Review by AlexWaygood — COMMENTED** [review]
It doesn't seem to me that this PR fixes any bugs, and the extra import might make importing the module slower. Is there a strong rationale for this change?

You should also delete the news entry, since the changes this PR makes wouldn't be visible to end users in any way. I'll add the "skip news" label, which will mean the CI will still pass if you delete the news entry.

**Comment by Nougat-Waffle** [comment]
> It doesn't seem to me that this PR fixes any bugs, and the extra import might make importing the module slower. Is there a strong rationale for this change?

The rationale for this change is purely to increase the readability and elegancy of the code. 

> You should also delete the news entry, since the changes this PR makes wouldn't be visible to end users in any way. I'll add the "skip news" label, which will mean the CI will still pass if you delete the news entry.

Done

**Comment by AlexWaygood** [comment]
> The rationale for this change is purely to increase the readability and elegancy of the code.

This is a worthy goal, but, in this case, I'm not sure it's worth the extra import. But the final decision needs to be made by the `ipaddress` module maintainers; I'm just a triager, I'm afraid, and have no merge privileges :)

**Comment by AlexWaygood** [comment]
> But the final decision needs to be made by the `ipaddress` module maintainers; I'm just a triager, I'm afraid, and don't have merge privileges :)

Sadly there are no active maintainers listed for `ipaddress` on the [experts index](https://devguide.python.org/experts/). @ezio-melotti, would you mind taking a look?

**Review by ezio-melotti — COMMENTED** [review]
The changes seem reasonable, but I'm also not sure if it's worth merging it.

In theory this could be made even more concise with a function that does something like this:
```py
def try_classes(address, classes, type, *args, **kwargs):
    for cls in classes:
        with contextlib.suppress(AddressValueError, NetmaskValueError):
            return cls(address, *args, **kwargs)
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 {type}')
```
or like this (if we want to get rid of the extra import):
```py
def try_classes(address, classes, type, *args, **kwargs):
    for cls in classes:
        try:
            return cls(address, *args, **kwargs)
        except (AddressValueError, NetmaskValueError):
            pass
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 {type}')
```
but again I'm not sure if it's worth the extra complexity just to save a few lines

**Comment by AlexWaygood** [comment]
Closing on the basis that:

- The readability improvement here is relatively small
- The extra import comes with a performance cost
- Using `contextlib.suppress` is slower than using `try`/`except`
- There's no obvious bug being fixed to justify the code churn.

Thanks for the PR, but we'll decline this one :)

**Pull request closed without merging**
