### PR TITLE
gh-119517: Fixes for pasting in pyrepl

### PR DESCRIPTION
**Pull request by godlygeek**
Drastically improve the performance of pyrepl when pasting large amounts of text.

CC: @pablogsal 

* Issue: gh-119517

### CODE REVIEW

**Comment by godlygeek** [comment]
Well hm, that's not what I meant to do. I'm just gonna try that again... 😓

**Comment by hugovk** [comment]
> Well hm, that's not what I meant to do. I'm just gonna try that again... 😓

Don't worry about it, but please don't rebase and force push.

If to want to update from `main`, merge it in. And everything is squash merged at the end, so no need to tidy your commits. 

https://devguide.python.org/getting-started/pull-request-lifecycle/#quick-guide

**Comment by godlygeek** [comment]
> Don't worry about it, but please don't rebase and force push.

Ah, the thing I tried to do that failed horribly wasn't a rebase, it was retargetting the PR to main instead of 3.13 via the GitHub UI - I picked the wrong branch when creating the PR, but because I had based the change on the 3.13 branch, GitHub decided I wanted to merge 3.13 into main.

> so no need to tidy your commits

I realize there will be a squash merge, but tidying the commits makes reviews much easier. Is force pushing _before_ the PR has been reviewed still frowned upon? Or force pushing to draft PRs? It seems wasteful to make reviewers review known buggy commits for problems that CI catches if I can instead fix those problems before anyone ever looks at it.

**Comment by hugovk** [comment]
> it was retargetting the PR to main instead of 3.13 via the GitHub UI

Yep, that'll reliably do it and ping every codeowner too 🙃 We'd disable that option if possible. 

> Is force pushing _before_ the PR has been reviewed still frowned upon? 

My main problem with force pushes is the notification takes you to an empty diff, so it costs an extra click to go to the main PR page, and it's not obvious to see what changed from the last time I checked.

> Or force pushing to draft PRs? It seems wasteful to make reviewers review known buggy commits for problems that CI catches if I can instead fix those problems before anyone ever looks at it.

I feel like marking a PR as draft is enough of a signal to say it's not ready for review yet, but an explicit comment can help. 

I'm not sure how often people review commit-by-commit compared to the whole diff, so I wouldn't worry about small new commits that fix earlier ones.

**Pull request closed without merging**
