### PR TITLE
bpo-NA: Minor optimization/consistency improvement to colorsys.py's rgb_to_hsv()

### PR DESCRIPTION
**Pull request by oaustegard**
Added same minor optimization to rgb_to_hsv() as is found in the existing rgb_to_hls() (see lines 79-89 in current version)
Removed unnecessary comment about int() truncating on line 147

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@oaustegard

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by oaustegard** [comment]
I'll try to get the CLA signed as soon as the bug system finishes migrating so I can register...

**Comment by ambv** [comment]
@oaustegard try filling out the CLA now using the button in the comment above ☝🏻

**Comment by oaustegard** [comment]
CLA signed ✅

**Comment by ambv** [comment]
Thanks, @oaustegard. Unfortunately, you need to make this PR against the `main` branch, not 3.10. Python 3.10 only accepts bug fixes now.

**Pull request closed without merging**
