### PR TITLE
bpo-30709: bad getter from Descriptor#Properties example

### PR DESCRIPTION
**Pull request by anqur**
- The purpose of `obj` in the example is implicit
- As an argument the `obj` will cause errors when using `Cell('b10').value` because it expects more arguments, but 1 given

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by anqur** [comment]
Oops sorry for some mess here I'm just kinda new in this amazing community :pray:

**Review by rhettinger — APPROVED** [review]

**Review by Mariatta — CHANGES_REQUESTED** [review]
Thanks for the PR. I noticed you made this against the 2.7 branch. Can you make the change against the `master` branch first? Once the PR on `master` has been merged, it can be backported to the maintenance branches.

**Comment by anqur** [comment]
@Mariatta Thanks for your reply! I just updated the base branch!

**Comment by Mariatta** [comment]
Simply changing the base branch on GitHub won't work :(

I think you'll need to rebase against the master branch, and then do a force push.

Perhaps it will be easier for you to checkout a branch that is off the master branch, eg by doing `git checkout -b <branchname> master`, make your edit in that branch, commit and push.

**Comment by anqur** [comment]
@Mariatta I'm pretty sorry for my misconception, and perhaps it is heavily due to my direct modification on that file via GitHub webpage, which creates a new `patch-1` branch and simply breaks the normal workflow of this repo itself.

I'm closing this and will new a PR with a link to this conversation. And I will clone my forked repo (which is much outdated seemingly) and use the following commands to make my changes against `master` branch:

```bash
$ # New branch `foo'
$ git fetch origin # updates origin/master
$ # make my changes on `foo'
$ git rebase origin/master
$ git push origin master -f
$ # New a pull request on python/cpython
```

Hope it works out...

**Comment by anqurvanillapy** [comment]
New conversation here: https://github.com/python/cpython/pull/2339

**Pull request closed without merging**
