### PR TITLE
gh-106320: Remove private _PyCrossInterpreterData API

### PR DESCRIPTION
**Pull request by vstinner**
Move private _PyCrossInterpreterData API to the internal C API: add a new pycore_cross_interp.h header file.

Mark _PyCrossInterpreterData_Init() and
_PyCrossInterpreterData_Lookup() functions are static.

Move get_crossinterp_data() and restore_crossinterp_data() from _testcapi to _testinternalcapi.

* Issue: gh-106320

### CODE REVIEW

**Comment by vstinner** [comment]
cc @ericsnowcurrently: FYI

**Comment by ericsnowcurrently** [comment]
The API is required by the _xxsubinterpreters module, which should not use the internal C-API.

**Comment by vstinner** [comment]
> The API is required by the _xxsubinterpreters module, which should not use the internal C-API.

Why should it not use the internal C API? What is the rationale?

If you consider that it's important that 3rd party projects can use this API, it should be made public. No?

**Comment by vstinner** [comment]
By the way, [PEP 684 - A Per-Interpreter GIL](https://peps.python.org/pep-0684/) got accepted: should these ``_xx`` extensions be renamed to have a public name, and be documented?

**Comment by vstinner** [comment]
> I'm publishing this module on PyPI.

Oh, I wasn't aware of that, ok :-) That's what I'm trying to discover by removing private functions: see how they are used.

Well, anyone, I prefer to let you decide what do you: do nothing for now (keep the API as private) and decide later, or make some functions public. You might document in a comment in the header file that these functions are exported to be able to be used in 3rd party projects.

Thanks for your feedback, I close my PR and its issue.

**Comment by ericsnowcurrently** [comment]
Thanks!

**Pull request closed without merging**
