### PR TITLE
GH-103247: bypass the import cache on the _require_loader helper

### PR DESCRIPTION
**Pull request by FFY00**
This is not a fix for the importlib test monkeypatching leakage but it's something that we probably should be doing anyway.

* Issue: gh-103247

### CODE REVIEW

**Comment by FFY00** [comment]
cc @JelleZijlstra as the original reporter

**Review by brettcannon — APPROVED** [review]

**Review by sunmy2019 — APPROVED** [review]

**Comment by FFY00** [comment]
It seems this fell off mental work pool and I only noticed it now. Since we have approvals, I am gonna update the branch and schedule it for merging.

**Comment by carljm** [comment]
Bisection shows that the merge of this PR introduced a reference leak in `test_import`, so all refleak buildbots are red: https://github.com/python/cpython/issues/108696

**Comment by FFY00** [comment]
@carljm thanks for the catch, let's revert then.

**Comment by carljm** [comment]
> @carljm thanks for the catch, let's revert then.

https://github.com/python/cpython/pull/108698

**Pull request merged**
