### PR TITLE
bpo-42686: Enable SQLite math functions in Windows build

### PR DESCRIPTION
**Pull request by erlend-aasland**
https://bugs.python.org/issue42686

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@zooba Could you have a look a this? I won't have any effect until we upgrade to SQLite 3.35.0, but it won't do any harm applying it now.

**Comment by erlend-aasland** [comment]
Is there anyone else from the Windows team who can review this?

**Review by pfmoore — APPROVED** [review]
I can confirm from a quick scan that this looks OK. I haven't built Python with this PR, though, so that's all I can say, sorry.

**Comment by erlend-aasland** [comment]
> I can confirm from a quick scan that this looks OK. I haven't built Python with this PR, though, so that's all I can say, sorry.

Thanks, Paul. The CI should fail for win32 and win64 if it didn't build, right?

**Comment by pfmoore** [comment]
I'd assume so, yes.

**Comment by zware** [comment]
LGTM as well, but I do think we want to hold off on this until we are in fact using a version that it affects.  If we merge this before then, we're giving the impression that the functionality is there when it actually isn't.

You could get fancy and include a version check, but that may be more trouble than it's worth.

**Comment by erlend-aasland** [comment]
> LGTM as well, but I do think we want to hold off on this until we are in fact using a version that it affects. If we merge this before then, we're giving the impression that the functionality is there when it actually isn't.

That depends on how we phrase the NEWS item, I guess. However, adding this now will make it _slightly_ easier to try out the current nightly SQLite builds. OTOH, those who do so are very likely to just add the compile definition themselves, so I guess the real gain is negligible. I'm fine with holding off until 3.35.0. We can include this when we're upgrading the Windows build to 3.35.0.

> You could get fancy and include a version check, but that may be more trouble than it's worth.

Totally agree.

**Comment by erlend-aasland** [comment]
FYI, rebased onto master bco. #24797.

**Comment by erlend-aasland** [comment]
@zooba: now that #25641 is merged, would you mind merging this as well? It's already approved by members of the Windows team.

**Pull request merged**
