### PR TITLE
gh-106320: Remove private pylifecycle.h functions

### PR DESCRIPTION
**Pull request by vstinner**
Remove private pylifecycle.h functions: move them to the internal C API ( pycore_atexit.h, pycore_pylifecycle.h and pycore_signal.h). No longer export most of these functions.

Move _testcapi.test_atexit() to _testinternalcapi.

* Issue: gh-106320

### CODE REVIEW

**Comment by gvanrossum** [comment]
This broke macOS build for me. In Python/specialize.c there's a use of `_PyOS_URandomNonblock` but the file doesn't `#include "pycore_pylifecycle.h"`. How did this pass CI? Anyway, I'll fix it.

**Comment by vstinner** [comment]
It seems like the macOS CI uses gcc. I suppose that you use clang. And clang is more strict about undefined functions. Maybe the CI should use clang?

cc @corona10

**Comment by vstinner** [comment]
It seems like the macOS CI uses gcc. I suppose that you use clang. And clang is more strict about undefined functions. Maybe the CI should use clang?

cc @corona10

**Comment by corona10** [comment]
@vstinner 
Basically, the default gcc of macOS is clang.
We need to check what's happening on GA for this use.
If you meant the compiler option, it would be worth doing it.

cc @ned-deily 

````
$> gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
````

**Comment by vstinner** [comment]
```
$> gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
```

Aha, maybe @gvanrossum LLVM is more recent. LLVM clang 15 made this change: https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html

* The -Wimplicit-function-declaration warning diagnostic **now defaults to an error** in C99 and later

**Comment by dgrisby** [comment]
omniORBpy (which I maintain, https://www.omniorb.net/ ) is using _Py_IsFinalizing to avoid crashes in threads created from C++ during interpreter shutdown, as documented at https://docs.python.org/3.13/c-api/init.html#c.PyEval_RestoreThread

Is there an alternative?

**Comment by dgrisby** [comment]
> Would you mind to open a new separated issue to request a public function replacing the removed private function? Thanks in advance.

Here it is: https://github.com/python/cpython/issues/108014

Thanks.

**Pull request merged**
