### PR TITLE
[2.7] Docs: fix some wrong words (GH-6987)

### PR DESCRIPTION
**Pull request by matrixise**
Fix typos in code comments: bdb.py and configure.ac..
(cherry picked from commit b5c246f)

Co-authored-by: Eitan Adler grimreaper@users.noreply.github.com
Co-authored-by: Stéphane Wirtel <stephane@wirtel.be>

### CODE REVIEW

**Comment by matrixise** [comment]
@Mariatta and @ned-deily I have backported the PR https://github.com/python/cpython/pull/7572 in this PR, and just used the content of `configure.ac`

I have not changed the content of `configure` because this one could be updated with `autoconf` or `autoreconf` but the diff is bigger.

**Comment by matrixise** [comment]
I have updated the `configure` and `aclocal.m4` files with autoreconf (from autoconf 2.65) like described in this paragraph: https://devguide.python.org/setup/#regenerate-configure

**Review by ned-deily — CHANGES_REQUESTED** [review]
While it's important to keep configure.ac and configure in sync, you need to use an up-to-date version of autoconf: note the version you used is older than the one previously used and therefore is causing a lot of unnecessary changes and reverts.  Suggest you revert that most recent commit and add a new one that simply makes the one-line change to the comment by hand.  Also, note that the PR commit message is not accurate in that it refers to changes to bdb.py that were not necessary for 2.7.

**Comment by matrixise** [comment]
Hi @ned-deily 

In fact, I used an older version of autoconf because I have read this paragraph from the devguide

> Python’s configure.ac script typically requires a specific version of Autoconf. At the moment, this reads: AC_PREREQ(2.65).
> If the system copy of Autoconf does not match this version, you will need to install your own copy of Autoconf.

but ok, I am going to update this PR with the last version of autoconf on my fedora 28.

**Comment by matrixise** [comment]
Updated with autoconf 2.69, but maybe we should update the doc and indicate "You have to use a version at least equal to the required version in the `configure.ac` file"

**Comment by ned-deily** [comment]
@matrixise Thanks for the reminder about the devguide.  It appears that the autotools version was recently bumped for master but not for the other branches even though their configure files were all generated with 2.69 :)  I reopened bpo-33486 about it.

**Comment by matrixise** [comment]
Thanks for [bpo-33486](https://bugs.python.org/issue33486).

What's the next step(s) for the approval of this PR?

**Review by ned-deily — APPROVED** [review]

**Pull request merged**
