### PR TITLE
bpo-33524: Fix the behavior when max_line_length is 0 or None in email.policy

### PR DESCRIPTION
**Pull request by Licht-T**
This fixes [bpo-33524](https://bugs.python.org/issue33524).

https://bugs.python.org/issue33524

### CODE REVIEW

**Review by bitdancer — CHANGES_REQUESTED** [review]
This PR needs a news item, otherwise it looks good.

**Comment by DrLuke** [comment]
Please add the news entry, I am desperately awaiting this fix!

**Comment by maxking** [comment]
Ping @Licht-T!

If this PR is abandoned, I can re-submit the patch with the news item (and attribution to original author ofc).

**Comment by DrLuke** [comment]
@maxking I think it can be considered abandoned, it's been over a year. Thank you!

**Pull request closed without merging**
