### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by mishmanners**
Only trivial changes; changed all your (C) copyrights to include the official copyright symbol: © you're welcome 😄

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@MishManners

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by MishManners** [comment]
Says I haven't signed the agreement. But I have:
[Contributor Agreement 2020-09-23 - signed.pdf](https://github.com/python/cpython/files/6348873/Contributor.Agreement.2020-09-23.-.signed.pdf)

**Comment by Mariatta** [comment]
You would need to create an account in bugs.python.org and link that account with your GitHub account.

Though I don't think the change is necessary.

**Comment by MishManners** [comment]
Now it's signed 😄

**Pull request closed without merging**
