### PR TITLE
Updated README for python 3.10

### PR DESCRIPTION
**Pull request by Nishit-Dua**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Nishit-Dua

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by tirkarthi** [comment]
I recall some conversation where this is deliberate but couldn't find the appropriate source. I am happy to be corrected wrong.

**Comment by pablogsal** [comment]
> I recall some conversation where this is deliberate but couldn't find the appropriate source. I am happy to be corrected wrong.

As far as I understand the PR makes sense as 3.9 reached the final release. I assume given that the Readme mentions that this is 3.10, is useful for readers to be linked against the 3.10 release schedule.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks @Nishit-Dua for the PR :)

**Comment by Nishit-Dua** [comment]
> Thanks @Nishit-Dua for the PR :)

Thanks for having such a nice community 😊

**Pull request merged**
