### PR TITLE
bpo-38200: Add itertools.pairwise()

### PR DESCRIPTION
**Pull request by rhettinger**
This is a first draft.  Needs more thought on refcnts.  Needs docs, tests, and a better doctstring.

https://bugs.python.org/issue38200

### CODE REVIEW

**Review by serhiy-storchaka — COMMENTED** [review]
The code LGTM. Needed documentation, tests, and implementation of `__reduce__`.

**Comment by rhettinger** [comment]
I'm intending to leave out `__reduce__`:
* We haven't promised in the docs that all itertools are pickable.
* Experience with the [more-itertools package](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.pairwise) suggests that it isn't needed.
* Experience with the regular itertools module suggests unnecessarily adding pickle support gets in the way of maintenance and is itself a recurring source of bugs.
* Also, I never liked the way this was done for the other itertools where it replays the prior execution history.

**Comment by pylang** [comment]
Greetings.  It's exciting to see new tools added to the Standard Library.

Since `pairwise` is already a recipe, I'm wondering whether **if this is worth generalizing to a sliding-window tool instead, e.g. `window`**?  I saw some rationale in the [original bug post](https://bugs.python.org/issue38200), but in cases where a pairwise operation is needed, I usually implement a quick `list(zip(lst, lst[1:]))` recipe instead.  

If a more general tool is needed (e.g. one that applies to iterators), then I think it's worth generalizing the window size as well.   I understand the topic of sliding-windows has been [discussed in the past](https://mail.python.org/pipermail/python-dev/2006-May/065276.html), but that was prior to officially adopting a windowing tool like `pairwise` into itertools.  Since then I've seen many [sliding-window problems on StackOverflow](https://stackoverflow.com/questions/6822725/rolling-or-sliding-window-iterator?noredirect=1&lq=1) and in more-itertools.  I can give more links on specific use cases if requested.

Many thanks.

**Comment by merwok** [comment]
Hi @pylang — python-dev does not use pull requests for design discussions, only code reviews.
For open tickets, the bug tracker is the right place to discuss design, now that this one is closed, better go to the python-dev mailing list or the https://discuss.python.org/ forum.

**Pull request merged**
