### PR TITLE
bpo-28247: Document Windows executable creation in zipapp

### PR DESCRIPTION
**Pull request by csabella**
Patch by Paul Moore.

https://bugs.python.org/issue28247

### CODE REVIEW

**Comment by pfmoore** [comment]
Thanks for fixing the Travis failures - I saw them in the original version, but hadn't had time to work out what was wrong (I hadn't realised that code blocks were formatted as Python by default, doh). I've added a news file.

**Comment by pfmoore** [comment]
Now all I have to do is work out the appropriate merge dance :-)

**Review by pfmoore — APPROVED** [review]
Not sure it's appropriate to review my own change here, but for what it's worth I think this is OK to go now.

**Comment by csabella** [comment]
I see a lot of core devs approving their own work and sometimes they ping others to ask for a review before merging, so it's totally up to you.

**Comment by terryjreedy** [comment]
If you haven't, you should rebuild the doc on your machine and check the html rendering.

I cannot review the content; I did not even know about the module until now.

Yes, all you have to do is hit the button, fix the title, fix the message, and confirm.

The zipapp page, at least the section affected, appears unchanged from 3.6, so if it applies, as it seems to from the issue, let the bot backport it.  This usually takes a couple of minutes.  All you have to do then is review and approve each backport, and it is a good idea to take at least a quick look, and the merge will be done when CI passes.  Or you can wait until CI passes and then hit merge yourself.  I find 'approve' easier.

**Comment by pfmoore** [comment]
Thanks @terryjreedy

**Pull request merged**
