### PR TITLE
bpo-41292: Windows FAQ dead link fixed

### PR DESCRIPTION
**Pull request by stardust85**
https://bugs.python.org/issue41292

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@stardust85

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by eamanu — APPROVED** [review]
Good catch!

**Review by eamanu — APPROVED** [review]

**Comment by stardust85** [comment]
CLA signed (https://bugs.python.org/user29880) :) Should I add something to Misc/NEWS.d/next/? Is there a documentation how to do so? Or should I just simply get some inspiration from other changelog records?

**Comment by stardust85** [comment]
Hello, any update here?

**Comment by zooba** [comment]
Thanks for the PR, and sorry for taking our time getting to it!

**Pull request merged**
