### PR TITLE
gh-116088: Insert bottom checks after all sym_set_...() calls

### PR DESCRIPTION
**Pull request by gvanrossum**
Looking for reviews from @Fidget-Spinner and @markshannon. See the issue (gh-116088) for discussion.

### CODE REVIEW

**Comment by gvanrossum** [comment]
FWIW I'm lukewarm about this. Likely the policy that all queries return false/NULL for `bottom` is enough. So we could also close this (and the issue) without action. @Fidget-Spinner @markshannon thoughts?

**Comment by gvanrossum** [comment]
Note: `test_type_inconsistency` is failing here -- it triggers one of these tests. It's too bad for the test, but possibly points to an advantage of the `bottom` checks.

**Comment by Fidget-Spinner** [comment]
> Yes, that's correct behavior with these checks. So should I just change that test to assert that the second call doesn't create an executor?

Yes.

**Review by Fidget-Spinner — APPROVED** [review]

**Comment by gvanrossum** [comment]
> Note to future readers: whether the test creates an executor or doesn't create one isn't too important to me IMO. As long as CPython doesn't execute incorrect behavior, everything is fine.

Yeah, all these tests are way over-specified, and we regularly have to adjust them when the implementation changes. They are using internal introspection APIs to verify that the implementation did a specific thing. Unfortunately with optimizers you have to do such things -- if you just test the correct outcome, you'll never catch it when the optimizer just does nothing, and timing tests are out of the question (too flaky).

**Pull request merged**
