### PR TITLE
d_initial is not used by the parser, so no point generating it

### PR DESCRIPTION
**Pull request by tyomitch**

### CODE REVIEW

**Review by pablogsal — CHANGES_REQUESTED** [review]
I think is better to pass the index of the start symbol into the list of dfas down to the grammar and use that when generating the parser input files.

**Comment by tyomitch** [comment]
> I think is better to pass the index of the start symbol into the list of dfas down to the grammar and use that when generating the parser input files.

Could you please clarify?

**Comment by pablogsal** [comment]
> Could you please clarify?

Yup, instead of deleting the `d_initial`, make pgen generate it from the position of the initial symbol. The initial dfa symbol is placed in the grammar in:

https://github.com/python/cpython/blob/e12f56075edc5704c9cfbf69d268474328642fa3/Parser/pgen/pgen.py#L53

The value of `d_initial` has to be the position of that symbol in the list of dfas. It will be 0 as `single_input` is always the first DFA in the list of dfas, but doing programmatically will protect in case the position changes in the future. Basically something on the lines of (for illustrative purposes):

change:

```
"0, {n_states}, states_{dfa_index},\n".format(
```

to

```
start_index = list(self.dfas.keys()).index(self.start)
"{start}, {n_states}, states_{dfa_index},\n".format(start=start_index
```

**Comment by tyomitch** [comment]
Now I see what you mean, but `d_initial` is not about the initial DFA of the grammar, it's about the initial state of a DFA: each DFA has its own `d_initial`, and they're all zeroes.

**Comment by pablogsal** [comment]
> Now I see what you mean, but d_initial is not about the initial DFA of the grammar, it's about the initial state of a DFA: each DFA has its own d_initial, and they're all zeroes.

Oh, right! Sorry, I have mistaken this with the start rule in the old pgen:

https://github.com/python/cpython/blob/79fbcc597dfd039d3261fffcb519b5ec5a18df9d/Parser/pgen.c#L658

But as you indicate, d_initial has been initialized always to 0:

https://github.com/python/cpython/blob/79fbcc597dfd039d3261fffcb519b5ec5a18df9d/Parser/pgen.c#L642

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
@tyomitch Can you rebase to regenerate the `graminit.c` file.

**Comment by tyomitch** [comment]
> @tyomitch Can you rebase to regenerate the `graminit.c` file.

Done!

**Comment by pablogsal** [comment]
Thanks @tyomitch for the contribution! :)

**Pull request merged**
