### PR TITLE
GH-123714: Update JIT compilation to use LLVM 19

### PR DESCRIPTION
**Pull request by savannahostrowski**
This PR updates the JIT to use LLVM 19. My current testing approach does not currently take advantage of any new LLVM features, which we may want to consider.

* Issue: gh-123714

### CODE REVIEW

**Comment by savannahostrowski** [comment]
The CI will all fail 🤣  because 19 isn't available anywhere yet. Carry on...

**Comment by savannahostrowski** [comment]
LLVM 19.1.0 is now available on choco and brew so I'm opting to re-run CI here. Running locally on Windows, Mac and Ubuntu produced no build errors.

It looks like LLVM 19 is still being tested for Fedora 42, so I'll hold off on updating the Devcontainer blurb in the README for now (we'll also want to update the Devcontainer Dockerfile once it's available).

**Comment by picnixz** [comment]
What are the distributions that are actually waited upon? is openSUSE Tumbleweed (the rolling-release one) part of it (currently, it's LLVM 18)? openSUSE 15.5/6 support LLVM 19 as an experimental package so it's not really an issue for me I think but I wonder whether we could identify which LLVm 19 features are really needed (out of interest, I'm not maintaining anything on openSUSE).

**Comment by savannahostrowski** [comment]
Right now, it seems like folks building with the JIT are covered by the distributions covered in the README. This has been sufficient up until this point, especially since the JIT is experimental. 

@brandtbucher and I are also investigating removing the LLVM dependency for folks wanting to build with the JIT. This was discussed at the sprint (Brandt will be posting a summary on Discourse soon) but there's also a related issue covering a piece of this -  #115869.

**Comment by savannahostrowski** [comment]
Closing in favour of https://github.com/python/cpython/pull/125499 to simplify merging PRs.

**Pull request closed without merging**
