### PR TITLE
bpo-47063 Add an index_pages default list and parameter to SimpleHTTPRequestHandler

### PR DESCRIPTION
**Pull request by myronww**
This allows the default indexes pages list to be overridden and makes it easy to set a new index page name
without having to override send_head.

https://bugs.python.org/issue47063

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@myronww

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by myronww** [comment]
So I went through the process of filing the CLA and got a copy of it in my email.  Not sure why i cannot verify it yet.

**Comment by ethanfurman** [comment]
@myronww The CLA has to be reviewed by a human, so it can take a couple days to go through the process.

**Comment by ethanfurman** [comment]
If possible, this will also need a test.

**Comment by myronww** [comment]
> If possible, this will also need a test.

This is the only decision path added.

```if index_pages is not None:
            self.index_pages = index_pages
```
Depends on how much test code you want to maintain.  If there are already tests that utilize this constructor and they passed then I would say no.  The code is either going to use the fixed const on the class or the passed in override which makes self.index_pages into a object instance variable.

A user could pass in an incorrect value, but you cannot test against API misuse.

**Comment by carlbordum** [comment]
Proposed changes look correct to me.

**Pull request merged**
