### PR TITLE
Update Windows library names for the Python version bump

### PR DESCRIPTION
**Pull request by Eclips4**
Seems that's somehow missed

### CODE REVIEW

**Comment by Eclips4** [comment]
cc @Yhg1s

**Review by zooba — COMMENTED** [review]
pyconfig.h changes look good to me. I think the configure changes are fine, but I so rarely touch that script that someone else should check it too.

**Comment by arhadthedev** [comment]
Probably, automation of these changes should also be added into https://github.com/python/release-tools.

**Comment by Eclips4** [comment]
Also, there's a problem with test_enum, but this should be a seperate issue/PR

**Comment by Yhg1s** [comment]
The configure script is being taken care of in #104757, so that can be dropped from this PR.

**Comment by Eclips4** [comment]
> The configure script is being taken care of in #104757, so that can be dropped from this PR.

Done!

**Pull request merged**
