### PR TITLE
gh-94713 - Replacing while 1 with while True

### PR DESCRIPTION
**Pull request by Nougat-Waffle**
gh-94713: Replacing %-formatting and string concatenation with f-strings and replacing `while 1` with `while True`.

I don't think there is a need for a NEWS entry.

### CODE REVIEW

**Comment by ericvsmith** [comment]
Typically we don't accept changes like this, due to the churn involved. Is there any reason these **need** to be f-strings?

**Comment by Nougat-Waffle** [comment]
> Typically we don't accept changes like this, due to the churn involved. Is there any reason these **need** to be f-strings?

These don't **need** to be f-strings. I just though that changing to f-strings would make the code better and so I did. Could u elaborate further on why changes like this aren't welcome ?

**Comment by ericvsmith** [comment]
> Could u elaborate further on why changes like this aren't welcome ?

There's always a chance for an error to be introduced in corner cases, and it makes any existing PRs difficult to apply.

I'd definitely be okay with the `1` -> `True` change, though.

**Comment by Nougat-Waffle** [comment]
> I'd definitely be okay with the `1` -> `True` change, though.
Alright, I reverted back the f-strings changes.

**Review by DanielNoord — APPROVED** [review]
Although the name of this PR should probably be updated.

**Pull request merged**
