### PR TITLE
bpo-39573: Use Py_IS_TYPE to check for types

### PR DESCRIPTION
**Pull request by shihai1991**
https://bugs.python.org/issue39573

### CODE REVIEW

**Comment by shihai1991** [comment]
rough idea: Can we create a review robot to remind committer use the common macros or inline functions?

**Comment by corona10** [comment]
This PR can be part of bpo-39573 which actually introducing and applying Py_IS_TYPE for the first time.

**Review by corona10 — APPROVED** [review]
We often do not accept the PR which can be just refactoring work with insignificant reason.
However, this PR is handling module what https://github.com/python/cpython/pull/18521/ did not.
So I approve of this change as the exception.

But we need to hear @vstinner 's opinion :)

Thanks for the work

**Comment by shihai1991** [comment]
> This PR can be part of [bpo-39573](https://bugs.python.org/issue39573) which actually introducing and applying Py_IS_TYPE for the first time.

yeap. You are the author ;)

**Comment by corona10** [comment]
@shihai1991 
But I approve the current change, so if the PR is updated for the more module.
Please request a review again.

**Comment by shihai1991** [comment]
> @shihai1991
> But I approve the current change, so if the PR is updated for the more module.
> Please request a review again.

Thanks, I have checked all modules, there have no more should be ported.

**Pull request merged**
