### PR TITLE
Add a method is_stopping() to asyncio.BaseEventLoop to access the int…

### PR DESCRIPTION
**Pull request by pbecotte**
…ernal property _stopping

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by asvetlov** [comment]
What is your use case?
Also issue on bugs.python.org is required for such changes.

**Comment by 1st1** [comment]
I'm closing this.  Please open an issue on bugs.python.org to discuss this first.

**Comment by pbecotte** [comment]
Fair enough, when writing up the detailed use case I did figure out another way of accomplishing what I wanted.

**Pull request closed without merging**
