### PR TITLE
bpo-36279: Ensure os.wait3() rusage is initialized

### PR DESCRIPTION
**Pull request by dw**
https://bugs.python.org/issue36279

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by dw** [comment]
CLA was filed long ago. Associated bug indicates user 'dw' on BPO has signed the form

**Comment by Mariatta** [comment]
You need to set the GitHub username in your bpo account. Currently the bpo user dw doesn't have GitHub username associated

**Comment by dw** [comment]
Thanks @Mariatta, fixed now :)

**Comment by dw** [comment]
I've lost interest in seeing this fixed. Patch moved to BPO ticket

**Pull request closed without merging**
