### PR TITLE
Fixed broken link to PyFLTK

### PR DESCRIPTION
**Pull request by mark-summerfield**

### CODE REVIEW

**Review by Fidget-Spinner — APPROVED** [review]
LGTM. Thanks for fixing the link! I've verified that the new links work.

**Review by nanjekyejoannah — APPROVED** [review]

**Review by nanjekyejoannah — COMMENTED** [review]
I just confirmed the current link "http://pyfltk.sourceforge.net" resolves too, i.e it's not broken.
And both links point to the same content, hence no need for this change IMHO.

**Comment by Fidget-Spinner** [comment]
> I just confirmed the current link "http://pyfltk.sourceforge.net" resolves too, i.e it's not broken.
> And both links point to the same content, hence no need for this change IMHO.

Oh yeah you're right. it redirects to the new link.

**Comment by mark-summerfield** [comment]
It didn't redirect when I tried it which is why I reported it broken.

**Comment by nanjekyejoannah** [comment]
Thanks for reporting this @mark-summerfield  but I guess nevertheless, we can just point to the redirected link.

**Pull request merged**
