### PR TITLE
bpo-41746: Cast to typed seqs in CHECK macros to avoid type erasure

### PR DESCRIPTION
**Pull request by lysnikolaou**
https://bugs.python.org/issue41746

### CODE REVIEW

**Comment by pablogsal** [comment]
Ahhh, the beauty of types that are not `void*` : I don't need to review carefully the whole thing because of any of these is wrong it wouldn't compile

**Comment by pablogsal** [comment]
I think we should also type now the ones in the grammars in `test_c_generator` or the test will start showing a bunch of warnings

**Comment by lysnikolaou** [comment]
There are no `CHECK` usages in `test_peg_generator`.

**Comment by pablogsal** [comment]
> There are no `CHECK` usages in `test_peg_generator`. Or do you mean something else?

Hummm, I am must be confusing some stuff. Can you check if running the peg tests do raise any warnings? In case is clean, we are fine, then

**Comment by lysnikolaou** [comment]
No warnings, so I'm merging.

**Pull request merged**
