### PR TITLE
gh-116622: Rename build variable MODULE_LDFLAGS back to LIBPYTHON

### PR DESCRIPTION
**Pull request by mhsmith**
This variable was renamed to MODULE_LDFLAGS in #115780, but as discussed at https://github.com/python/cpython/pull/115780#issuecomment-2254635565, Meson depends on the old name LIBPYTHON. Some other package build scripts probably have the same issue.

* Issue: gh-116622

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thank you for this fix @mhsmith, much appreciated. 

I did do a quick check - this rename is complete, no `MODULE_LDFLAGS left except for the news snippet added here.

**Review by erlend-aasland — APPROVED** [review]
Thanks for fixing this!

**Comment by mhsmith** [comment]
@erlend-aasland: Thanks; are you able to merge this? There will also be a 3.13 backport.

**Comment by lazka** [comment]
Could it be that pkg-config is not used on Android? After this the .pc file contains this under cygwin:

```
Libs: -L${libdir} $(BLDLIBRARY)
```

which is not valid syntax. I'd assume it is broken under Android too.

edit: (or maybe it was the previous change this tried to fix?)

**Comment by lazka** [comment]
yes, also broken for Android, I've filed #138800

**Pull request merged**
