### PR TITLE
[2.7] bpo-33518: Add PEP entry to documentation glossary (GH-6860).

### PR DESCRIPTION
**Pull request by andresdelfino**
(cherry picked from commit d5f144260886959c1fe06bc4506a23fd10f92348)

Co-authored-by: Andrés Delfino <adelfino@gmail.com>

https://bugs.python.org/issue33518

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
There was an issue, maybe a conflict. I clicked on [Update branch] button.

**Comment by vstinner** [comment]
Oh. All tests passed, but I still cannot merge because "This branch is out-of-date with the base branch". Crap. Let me try to click on [Update branch] again :-(

**Comment by vstinner** [comment]
@andresdelfino: I have some troubles to merge this PR. Ping me if I don't merge it.

**Comment by andresdelfino** [comment]
Should I create a new PR from scratch with an up to date 2.7 branch?

**Comment by andresdelfino** [comment]
I have merged the latest commits, perhaps we can try again?

**Comment by vstinner** [comment]
The [Squash and merge] button is still grey. Now it says "Required statuses must pass before merging", GitHub is waiting on AppVeyor: "Pending — Waiting for AppVeyor build to complete"... The build started 1 min ago.

**Comment by vstinner** [comment]
Finally. I succeded to merge this PR. I don't know why it was so hard to merge a simple doc change...

**Pull request merged**
