### PR TITLE
gh-122681: remove m_atan2()/c_atan2() helpers

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-122681

### CODE REVIEW

**Comment by skirpichev** [comment]
could skip news, as no user-visible changes

**Comment by vstinner** [comment]
Can you rebase/merge your branch to avoid the merge conflict? Then I can run buildbots on this PR.

**Comment by skirpichev** [comment]
No failures, related to this pr.

**Review by vstinner — APPROVED** [review]
LGTM.

@skirpichev: Did you just create to see if removing the wrapper would work or not, or do you propose to remove it?

**Comment by skirpichev** [comment]
Yeah, I think we can remove it; testing with buildbots - for additional safety.  But it's not urgent and I would appreciate @mdickinson blessing.

Current workarounds fix only few functions in cmath.  Missing bugreports - another indication, that underlying problems were fixed on affected systems.

**Review by kumaraditya303 — APPROVED** [review]

**Pull request merged**
