### PR TITLE
bpo-42419: Fix typo in "what's new in Python 3.9"

### PR DESCRIPTION
**Pull request by hiqua**
https://bugs.python.org/issue42419

Please skip news.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@hiqua

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by Fidget-Spinner — APPROVED** [review]
Good catch, thanks!

**Comment by vstinner** [comment]
@hiqua: Please sign the Python CLA.

**Review by asvetlov — APPROVED** [review]

**Comment by hiqua** [comment]
@vstinner I did when I opened this PR, I can only wait for the confirmation from the PSF now.

**Comment by vstinner** [comment]
> @vstinner I did when I opened this PR, I can only wait for the confirmation from the PSF now.

Ok, perfect. It can take a few days (especially with the long week day). Ping me next week, so I can try to remove the label, to see when it's done. In the meanwhile, you can check https://bugs.python.org/user36585 to see when "Contributor Form Received" is switched to Yes ;-)

**Comment by terryjreedy** [comment]
A typo fix does not require CLA as there is no creative content in the fix.  And it is Friday night, so I merged.

Quentin, thanks.  We hope to see more from you, perhaps something that *does* require the CLA, so please follow up.

**Pull request merged**
