### PR TITLE
bpo-38792: Remove IDLE shell calltip before new prompt.

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Previously, a calltip might be left after SyntaxError, KeyboardInterrupt, or Shell Restart..

https://bugs.python.org/issue38792

### CODE REVIEW

**Comment by taleinat** [comment]
Hi Zack, thanks for this!

This doesn't go far enough, actually; we should make sure to close the calltip in other cases too, such as after hitting enter and running a statement / block. It is a bit hairy to see where the best place to add this is.

Let me know if you're interested in doing more work on this and testing various edge cases.

**Review by terryjreedy — APPROVED** [review]
I tested interrupts and restarts before, during, and after calltips.  Before and after had no new problems and during now works properly.  I also tested some in editor.  Zack, thanks for report and initial fix.  I plan to merge tomorrow.

@taleinat If you find a way to execute with Enter and have calltip persist, we can try to fix in another PR, making sure to not regress in editor.

**Comment by taleinat** [comment]
Even with this fix, it is still easy and common to get a calltip staying open in other ways. For example, hitting Enter in the shell with a calltip open and a syntax error, as in the following image:

Screen Shot 2020-01-30 at 12 59 57

Removing any open call-tips in `PyShell.resetoutput()` could be a more comprehensive solution to these issues. I'm testing it locally now.

**Comment by taleinat** [comment]
> Removing any open call-tips in PyShell.resetoutput() could be a more comprehensive solution to these issues. I'm testing it locally now.

This look to be working very nicely. I've pushed this change into this PR, I hope you like it!

**Comment by terryjreedy** [comment]
I got the same with `int(',`.  This should be seen as hitting return to continue on a new line, not to run.  But the syntax error causes a new prompt.  It is plausible that the calltip should disappear, though if one follows with Alt-P <<prev>>, then one might want it.  

I like handling this in one place.  Among other reasons, Zack originally used `refresh calltip event` rather than `remove calltip window`.  I switched because I don't believe the extra code in the former is needed.  (refresh_calltip_event is only triggered by <Key-release-parenright> and not by other actions that close a calltip.)  But if I am wrong, the fix would only be needed one place.

**Pull request merged**
