### PR TITLE
bpo-32449: Make MappingView inherit from Collection instead of Sized

### PR DESCRIPTION
**Pull request by DevOpsCraftsman**
https://bugs.python.org/issue32449
https://mail.python.org/pipermail/python-ideas/2017-December/048489.html

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Mariatta** [comment]
This PR does not look right. Did you branch off `master` or `3.6`?
PRs should first be made against the `master` branch. Only once it's been merged into `master` then we can backport it to `3.6`.

**Comment by yahya-abou-imran** [comment]
Yes! My apologies... I wasn't aware about that. I'm doing it soon.

**Comment by terryjreedy** [comment]
With the PR corrected, I reduced the review request list to the collections code owner, Raymond.

**Comment by ned-deily** [comment]
From the discussion on the bug tracker, it was decided not to pursue this change.

**Pull request closed without merging**
