### PR TITLE
[3.11] gh-54781: Relocate and improve NEWS entry for sqlite3 test relocation

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-54781

### CODE REVIEW

**Comment by zware** [comment]
The original PR GH-29304 had a [NEWS entry](https://github.com/python/cpython/pull/29304/files#diff-8fe3e261c1f12b4b3f716ef556ef3cb69f104fa9d339d7a8091aeb1ba053f81b) now enshrined in [Misc/NEWS.d/3.11.0a2.rst](https://github.com/python/cpython/blame/main/Misc/NEWS.d/3.11.0a2.rst#L705-L711).

**Comment by erlend-aasland** [comment]
> The original PR [GH-29304](https://github.com/python/cpython/pull/29304) had a [NEWS entry](https://github.com/python/cpython/pull/29304/files#diff-8fe3e261c1f12b4b3f716ef556ef3cb69f104fa9d339d7a8091aeb1ba053f81b) now enshrined in [Misc/NEWS.d/3.11.0a2.rst](https://github.com/python/cpython/blame/main/Misc/NEWS.d/3.11.0a2.rst#L705-L711). See https://docs.python.org/3.11/whatsnew/changelog.html#id67 (though it does look like it was put in Library rather than Tests).

Right; what a mess I'm making here :) Sorry for all the noise. I'll blame the heat 🥵 Let's move it to the Tests category then; that seems like a better fit for that changelog item

**Comment by erlend-aasland** [comment]
PTAL; moved and improved.

**Review by zware — COMMENTED** [review]
LGTM, but should be done on `main` and backported (this NEWS file also exists on `main`).

**Comment by erlend-aasland** [comment]
Of course; thanks for the heads-up.

**Pull request closed without merging**
