### PR TITLE
gh-113317: Add libclinic.block_parser and libclinic.language modules

### PR DESCRIPTION
**Pull request by vstinner**
* Move Block and BlockParser classes to a new libclinic.block_parser module.
* Move Language and PythonLanguage classes to a new libclinic.language module.

* Issue: gh-113317

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Would it not be better to create a `libclinic.parser` and put all parser-related stuff there? Do we need the `libclinic.block_parser` granularity?

**Comment by erlend-aasland** [comment]
Instead of `libclinic.language`, would it not be better to split things up in _the kinds of language_? For example:

- `libclinic.lang_c` for _C language render data_ and the `CLanguage` class
- `libclinic.lang_python` for the `PythonLanguage` class and its helpers

**Comment by erlend-aasland** [comment]
Should `Block` and `BlockParser` belong to the same submodule? What about `BlockPrinter`? What was the rationale of putting `Block` in the `libclinic.block_parser` submodule?

**Comment by vstinner** [comment]
> What was the rationale of putting Block in the libclinic.block_parser submodule?

I started with very small files to break inter-dependencies, otherwise it's not possible to move any line of code.

Once more more will live in libclinic, it will be easier to move related code together.

CLanguage should live in its on own file, right.

**Comment by vstinner** [comment]
> Should Block and BlockParser belong to the same submodule?

BlockParser creates Block, so they are related, no?

> What about BlockPrinter?

I didn't manage to move it yet. But I would prefer to separate parsing code and code genereration code in different files, if possible.

**Comment by erlend-aasland** [comment]
> [...] I would prefer to separate parsing code and code genereration code in different files, if possible.

Yes, this is something we've been discussing. How about putting the intermediate representation (`Block`) in its own file? After all, it is shared between the parser and the generator. This is why we should discuss changes before merging.

**Pull request merged**
