### PR TITLE
[3.6] bpo-34901 - add isolated (-I) flag to sys.flags (GH-9708)

### PR DESCRIPTION
**Pull request by danishprakash**
(cherry picked from commit 656d52d)

https://bugs.python.org/issue34901

### CODE REVIEW

**Review by tirkarthi — APPROVED** [review]

**Comment by willingc** [comment]
@danishprakash From the [devguide](https://devguide.python.org/gitbootcamp/#backporting-merged-changes), backport commit messages should look similar to:

```
bpo-12345: Improve the spam module (GH-777)

* Add method A to the spam module
* Update the documentation of the spam module

(cherry picked from commit 62adc55)
```

I believe that you need to edit the PR title line using the Edit button to the right of the title to reflect the correct `GH-xxxx`. It would be helpful to add the `cherry picked ...` line by editing the first comment you made in this PR.

@ned-deily Please let us know if my guidance above is incorrect. I haven't done a manual backport so I wasn't sure the best way to clear the bedevere requirements.

**Review by willingc — COMMENTED** [review]
https://github.com/python/cpython/pull/9755#issuecomment-427997003

**Comment by danishprakash** [comment]
thanks a lot, @willingc, I completely forgot about that. However, regarding putting the bug tracker link in the commit message, I was under the impression that one of the bots did the linking back and forth. But it appears that this is not the case for this PR.

> I believe that you need to edit the PR title line using the Edit button to the right of the title to reflect the correct GH-xxxx. It would be helpful to add the cherry picked ... line by editing the first comment you made in this PR.

I'm not really sure if that's how it should be done. Editing a commit message is different from editing PR metadata and should be done manually using git. But thanks anyway, I'd make sure this is fixed.

**Comment by danishprakash** [comment]
On second thought, I don't think adding a `cherry picked ...` message in the commit would be the right thing to do since I didn't really cherry picked the commit from the original PR because it resulted in conflicts.

**Comment by ned-deily** [comment]
@willingc, @danishprakash, There's no need to add the Markdown URL link for the issue into the commit message.  The first line of the PR and or the commit should be something like:

`
[3.6] bpo-12345: Improve the spam module (GH-777)
`

The `[3.6]` in the commit message is kinda optional.  You can view other 3.6 commit messages [here](https://github.com/python/cpython/commits/3.6).  The PR title is edited as @willingc noted.  The commit message can be edited when the PR is merged.

Including cherry-picked info could be useful.  Note that a cherry-picked change may have been manually edited (`git cherry-pick --edit ...`) to resolve merge conflicts.

**Comment by ned-deily** [comment]
Oh, nice!  I see now that the bot is editing the comment to include the URL link!  Sorry, @willingc!  Let's see if I can edit it out.

**Comment by tirkarthi** [comment]
@ned-deily I have opened https://github.com/python/bedevere/issues/136 . This also caused confusion in https://github.com/python/cpython/pull/9906#issuecomment-430177012 where comments are rewritten without notification unless the author re-reads it. I have added a suggestion for bedevere to skip this when bpo-DDDD is inside backticks.

Thanks

**Comment by terryjreedy** [comment]
The bpo number belongs in the title, where it is left alone, not in the commit message.  I think non-master commits should have the branch number in the title so one can immediately tell what branch is affected.  It also appears in the browser tab.  For instance, I see "[3.6] bpo-34901" on this tab.  I agree that 'cherry-picked' (or possibly 'backported') should essentially always be present.

**Comment by ned-deily** [comment]
@terryjreedy "The bpo number belongs in the title, where it is left alone, not in the commit message".  I'm confused by your comment.   The bpo number belongs both in the PR title and the "title" or first line of the commit message.  The PR title is strictly a Github construct and does not end up in the cpython repo, unlike the commit message.

**Pull request merged**
