### PR TITLE
gh-54781: Mention sqlite3 test relocation in What's New

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-54781

### CODE REVIEW

**Comment by zware** [comment]
I'm not sure this is really necessary.  We haven't mentioned other, even major, test changes in whatsnew, and test code is explicitly documented as non-public.

**Review by terryjreedy — APPROVED** [review]

**Comment by terryjreedy** [comment]
The changelog has a `Tests` section.  If there is really a policy against mentioning *anything* about tests in What's New, I won't argue for this.

**Comment by zware** [comment]
> The changelog has a `Tests` section. If there is really a policy against mentioning _anything_ about tests in What's New, I won't argue for this.

A mention in NEWS certainly makes sense, but I don't think it's worth an entry in whatsnew.

**Comment by erlend-aasland** [comment]
> A mention in NEWS certainly makes sense, but I don't think it's worth an entry in whatsnew.

"No sweat, I'll make him into a disciple." 🎨 🖌️

**Comment by erlend-aasland** [comment]
I'll create a new PR against 3.11 for the NEWS entry, then.

**Pull request closed without merging**
