### PR TITLE
gh-93044: No longer convert the database argument of sqlite3.connect() to bytes

### LINKED ISSUE #93044: Unintentional changes in sqlite3.connect()
There are some unintentional consequences of converting `sqlite3.connect()` to Argument Clinic in #40956.

1. The `database` argument always converted to bytes.
2. Keyword arguments are passed as positional arguments to `factory()`.
3. If an argument is not passed to `sqlite3.connect()`, its default value is passed to `factory()`.

It all works with the default `factory=Connection`, but `factory` can be an arbitrary callable, not completely compatible with `Connection()`. There may be a user code which uses a factory which only works with string `database` and does not support the `uri` argument. It worked fine in older versions when it is called with correct arguments, bet will become failing in 3.11.

This is a hypothetical scenario, but we should at least add a note about potential incompatibility. And I think that it is better to get rid of `PyUnicode_FSConverter` here.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Just pass it to the factory as is.

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I wonder if we should run this through the Django test suite as well; they've got a ton of sqlite3 tests there.

**Review by erlend-aasland — APPROVED** [review]

**Comment by felixxm** [comment]
> I wonder if we should run this through the Django test suite as well; they've got a ton of sqlite3 tests there.
> 
> @felixxm, what do you think?

Will check.

**Comment by felixxm** [comment]
Django checked :heavy_check_mark: no issues.

**Comment by erlend-aasland** [comment]
> Django checked :heavy_check_mark: no issues.

Thanks! Highly appreciated 🙏🏻

**Pull request merged**
