### PR TITLE
bpo-45855: document that `no_block` has no use anymore in PyCapsule_Import

### PR DESCRIPTION
**Pull request by birkenfeld**
and also remove the switch in the implementation.

https://bugs.python.org/issue45855

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]
LGTM!

**Comment by birkenfeld** [comment]
Thanks for the review! I'm not up to date on NEWS policy; I don't think this needs an entry, can I just set the "skip news" label?

**Comment by asvetlov** [comment]
One sentence NEWS doesn't harm. Usually, we skip news for very trivial changes only, e.g. typo fixing.

**Comment by asvetlov** [comment]
Superseded by #30046

**Comment by birkenfeld** [comment]
Uh no, it is not superseded. The other PR just changed a couple of calls, among others it "fixed" the location I changed in capsule.c to call the same function twice in an if-else instead of removing the branch.

**Review by asvetlov — APPROVED** [review]
Oh, sorry. 

LGTM, please feel free to merge.

**Comment by birkenfeld** [comment]
Thanks!

**Pull request merged**
