### PR TITLE
gh-96828: Add an `ssl.OP_ENABLE_KTLS` option

### LINKED ISSUE #96828: Add an `ssl.OP_ENABLE_KTLS` option for enabling the use of the kernel TLS
# Feature or enhancement

A new `ssl.OP_ENABLE_KTLS` option for enabling the use of the kernel TLS.

# Pitch

Kernel Transport Layer Security (kTLS) can improve performance of programs using TLS by reducing the number of switches between the user space and the kernel space. kTLS allows using the `sendfile` system call for sending data using TLS. Also, it may offload TLS to network interface controllers.

kTLS is not enabled by default for various reasons which you can find in https://github.com/openssl/openssl/issues/13794. Even if a system supports the feature and OpenSSL was compiled with support for it, Python still has to set an OpenSSL's option `SSL_OP_ENABLE_KTLS` to use it.

In theory, it is possible to enable the kernel TLS in any Python compiled against OpenSSL 3 using this following code. If all other requirements are met, Python should start writing to and reading from a secure socket using the kernel TLS.
```python
import ssl
context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.options |= 8  # SSL_OP_ENABLE_KTLS
```

Since Python's `ssl` module defines a few constants similar to `SSL_OP_ENABLE_KTLS`, it should provide an `ssl.OP_ENABLE_KTLS` option.

# Previous discussion

I created https://discuss.python.org/t/sslsocket-sendfile-and-kernel-tls/18886 previously to discuss benefiting from the OpenSSL's [SSL_sendfile](https://www.openssl.org/docs/manmaster/man3/SSL_sendfile.html) function. An option for enabling kTLS is a base for the work.

### PR DESCRIPTION
**Pull request by illia-v**
Resolves #96828.

* Issue: gh-96828

### CODE REVIEW

**Review by gpshead — APPROVED** [review]
I added @tiran to confirm we want this, otherwise this looks good.

**Comment by smontanaro** [comment]
(I'm working my way through some PRs which have been approved and are labeled "awaiting merge", hence my seemingly bolt from the blue comment. Why? [Read here](https://discuss.python.org/t/prs-awaiting-merge/21313).)

@tiran? Do you have anything to add?

**Comment by tiran** [comment]
Is there any benefit in using KTLS without SSL_sendfile at all? Did you test that the feature actually works with Python's ssl module? It's definitely incompatible with MemoryBIO / asyncio.

**Comment by illia-v** [comment]
@tiran let me [cite your colleagues](https://fedoraproject.org/wiki/Changes/KTLSSupportForGnuTLS) to respond about the benefit 🙂:
> With suitable NIC hardware the encryption operations can be offloaded, freeing time on the main CPUs for application usage. Without offload hardware, kTLS may still improve parallelism for applications as the kernel can perform encryption operations on a differen host CPU to that running the application threads

Also, I posted about `SSL_sendfile` on [Discuss](https://discuss.python.org/t/sslsocket-sendfile-and-kernel-tls/18886/2), your response will be valuable there.

---

I did a test using this code and new methods of `_ssl._SSLSocket`:
https://github.com/python/cpython/commit/a30a9f8c78241005c48c8e9d8c3fbe5d37bf4013
```python
import asyncio
import socket
import ssl

import certifi


def check_ktls(sslobj):
    print(f"kTLS read {sslobj.uses_ktls_for_read()}")
    print(f"kTLS write {sslobj.uses_ktls_for_write()}")


hostname = "example.com"
request = b"GET /\r\n\r\n"

context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.load_verify_locations(certifi.where(), None, None)
context.options |= ssl.OP_ENABLE_KTLS

with socket.create_connection((hostname, 443)) as sock:
    with context.wrap_socket(sock, server_hostname=hostname) as ssock:
        ssock.send(request)
        print(ssock.recv(20))
        print(ssock.cipher())
        check_ktls(ssock._sslobj)


print()


async def check():
    print("asyncio")
    reader, writer = await asyncio.open_connection(hostname, 443, ssl=context)
    writer.write(request)
    print(await reader.read(20))
    ssl_object = writer.transport.get_extra_info("ssl_object")
    print(ssl_object.cipher())
    check_ktls(ssl_object._sslobj)
    writer.close()


asyncio.run(check())
```

This was the result, kTLS was used for writing when asyncio was not used:
```
b'HTTP/1.0 404 Not Fou'
('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
kTLS read False
kTLS write True

asyncio
b'HTTP/1.0 404 Not Fou'
('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
kTLS read False
kTLS write False
```

**Review by gpshead — APPROVED** [review]

**Comment by gpshead** [comment]
Thanks!

**Pull request merged**
