### PR TITLE
gh-90385: Add pathlib.Path.walk what's new section

### PR DESCRIPTION
**Pull request by zmievsa**
* Issue: gh-90385

Automerge-Triggered-By: GH:brettcannon

### CODE REVIEW

**Comment by Ovsyanka83** [comment]
@brettcannon Would you, please, take a look at this PR?

**Review by brettcannon — APPROVED** [review]

**Comment by Ovsyanka83** [comment]
Ping. Somehow automerge didn't work. It might be my fault...

**Comment by AlexWaygood** [comment]
> Ping. Somehow automerge didn't work. It might be my fault...

Not your fault — @brettcannon accidentally removed the "awaiting merge" label when he added "automerge", and @miss-islington is programmed to only merge PRs that have both labels applied :)

**Comment by brettcannon** [comment]
Oops. 😅

**Pull request merged**
