### PR TITLE
gh-124405: Fix `NameError` in `openpty`

### PR DESCRIPTION
**Pull request by sobolevn**
@ambv how can I test this change? This looks very platform specific, but it seems that you have a reproducer :)

* Issue: gh-124405

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks, this looks like the correct inlining of `slave_open` from https://github.com/python/cpython/pull/118826. Adding more test coverage sounds good though!

**Comment by sobolevn** [comment]
> Adding more test coverage sounds good though!

Thanks for the review! I need help adding tests, since I cannot reproduce this on my machine :(

**Review by hauntsaninja — COMMENTED** [review]
I'm going to sleep now, will look tomorrow. Based on typeshed I_PUSH should exist on Linux?

**Comment by hauntsaninja** [comment]
"highly problematic" indeed ;-) https://github.com/python/typeshed/pull/6807/files#diff-f28c4d3b27ed19db8e4154e55b1ad119f6655aad863bd3e92d9aee2d481589d7R72

**Comment by vstinner** [comment]
> On my Fedora 41, I have no /dev/pty* device, only /dev/tty* devices (97 files) that I cannot open (PermissionError) because my user is not in tty or dialout groups.

Same on FreeBSD. On FreeBSD, os.openpty() is implemented with (syscalls recorded by truss):

```
posix_openpt(O_RDWR|O_NOCTTY)                    = 3 (0x3) 
ioctl(3,TIOCPTMASTER,0x0)                        = 0 (0x0)
ioctl(3,TIOCPTMASTER,0x0)                        = 0 (0x0)
ioctl(3,TIOCPTMASTER,0x0)                        = 0 (0x0)
ioctl(3,FIODGNAME,0x820f8bb90)                   = 0 (0x0)
openat(AT_FDCWD,"/dev/pts/1",O_RDWR,00)          = 4 (0x4)
ioctl(3,FIOCLEX,0x0)                             = 0 (0x0)
ioctl(4,FIOCLEX,0x0)                             = 0 (0x0)
```

**Comment by vstinner** [comment]
`pty._open_terminal()` code is quite old, it was added in 1994 when the `pty` module was created by commit 23cb2a83a5e709761e8f649371a935f7b676ea10. The code almost didn't change since 1994: it still tries to open a `/dev/ptyXY` device and then use `/dev/ttyXY` device.

I guess that os.openpty() is now commonly available, and nobody uses the _open_terminal() fallback code path anymore, which looks broken on most platforms.

We should maybe do something with this code. Deprecate it. Remove it. I don't know :-)

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by sobolevn** [comment]
@vstinner thanks a lot for your help! 👍

**Pull request merged**
