### PR TITLE
gh-87264: Convert tarinfo type to stat type

### PR DESCRIPTION
**Pull request by alphavector**
This [PR](https://github.com/python/cpython/pull/29974) seems to be a bit stuck, this is an attempt to resuscitate it

* Issue: gh-87264

### CODE REVIEW

**Review by willingc — DISMISSED** [review]
Flagging this for core dev discussion. Attribution should be shared with #29974

**Comment by willingc** [comment]
Hi @alphavector. I flagged this for core dev discussion since a similar PR was opened earlier on this subject: #29974 

I would like to make sure that the first PR gets attribution/thanks for the change as well as you.

**Comment by ethanfurman** [comment]
This PR appears to be a copy/paste of the other, with only a slight modification of the test.  Since the changes are fairly simple, and @val-shkolnikov claims they signed the CLA with a different email, and @alphavector was kind enough to push for this, I'm happy to accept it and merge (with attribution for both).

**Review by ethanfurman — APPROVED** [review]

**Comment by willingc** [comment]
@ethanfurman Thanks for doing so. I will go ahead and approve and let you handle the merge/attribution. :smile:

**Review by willingc — APPROVED** [review]

**Comment by Mariatta** [comment]
Attribution can be added by including "Co-Authored-by: " at the end of commit message when merging the PR.
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#required-co-author-information

**Comment by alphavector** [comment]
Yes, I had no goal to downplay @val-shkolnikov's contribution, my involvement is minimal, the PR was all set and I gave it a little push

**Comment by willingc** [comment]
Thanks @alphavector. I appreciate the effort. I hope to see more contributions from you in the future. :sunny:

**Pull request merged**
