### PR TITLE
bpo-23325: Turn signal.SIG_DFL and signal.SIG_IGN into functions.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
These singletons are no longer integers.
They are now copyable and pickleable and have docstrings.

https://bugs.python.org/issue23325

### CODE REVIEW

**Comment by pppery** [comment]
Why should SIG_IGN raise an error when called instead of doing nothing?

**Comment by serhiy-storchaka** [comment]
> Why should SIG_IGN raise an error when called instead of doing nothing, which is what happens when SIG_IGN is actually supplied as a signal handler?

Because currently calling `SIG_IGN()` raises a TypeError. But I agree, we can make it callable.

**Comment by pitrou** [comment]
Hmm, the problem is this will break code such as:
```python
handler = signal.getsignal(signum)
if callable(handler):
   # Do something, e.g. call the handler
```

**Review by iritkatriel — CHANGES_REQUESTED** [review]
This has merge conflicts now.

**Comment by encukou** [comment]
Victor closed the issue, so I'll close the PR too.
They can be reopened together.

**Pull request closed without merging**
