### PR TITLE
gh-101819: Prepare to modernize the _io extension

### PR DESCRIPTION
**Pull request by vstinner**
* Add references to static types to _PyIO_State:

  * PyBufferedIOBase_Type
  * PyBytesIOBuffer_Type
  * PyIncrementalNewlineDecoder_Type
  * PyRawIOBase_Type
  * PyTextIOBase_Type

* Add the defining class to methods:

  * _io.BytesIO.getbuffer()
  * _io.FileIO.close()

* Add get_io_state_by_cls() function.
* Add state parameter to _textiowrapper_decode()
* _io_TextIOWrapper___init__() now sets self->state before calling _textiowrapper_set_decoder().

* Issue: gh-101819

### CODE REVIEW

**Comment by vstinner** [comment]
This PR is based on @erlend-aasland's PR #101948. Changes:

* Don't convert static types to heap types: it will be done on a separated PR
* _io_StringIO___init___impl() only calls find_io_state_by_def() once
* _io__WindowsConsoleIO___init___impl() doesn't declare a variable which is only used by an assertion, to avoid the risk of getting a compiler warning. If the line is too long, I can make the declaration conditional on the NDEBUG macro.
* _io_FileIO_close_impl() and _io__WindowsConsoleIO_close_impl(): move variable declaration (minor coding style change).
* Don't add PyIOBase_Type since such change would have no point for now.

I copied the clinic_state() macros.

> Add the defining class to methods: (...)

I was not sure that it works on static types... but it seems like it does :-) I didn't get any crash.

**Comment by vstinner** [comment]
@corona10 @erlend-aasland: Would you mind to review it?

**Comment by vstinner** [comment]
Oh, the Windows change didn't go well:

```
0:20:02 load avg: 8.57 [317/463/2] test_winconsoleio crashed (Exit code 3) -- (...)
Assertion failed: mod != NULL, file D:\a\cpython\cpython\Modules\_io\_iomodule.h, line 192
Fatal Python error: Aborted

Current thread 0x000004a0 (most recent call first):
  File "D:\a\cpython\cpython\Lib\test\test_winconsoleio.py", line 104 in test_conin_conout_names
(...)
```

**Comment by vstinner** [comment]
The failed assertion is:

```
assert(PyObject_TypeCheck(self, find_io_state_by_def(Py_TYPE(self))->PyWindowsConsoleIO_Type));
```

in _io__WindowsConsoleIO___init___impl(). The assertion fails because PyType_GetModuleByDef() returns NULL.

**Comment by vstinner** [comment]
On static types, PyType_GetModuleByDef() always returns NULL, since the function reads ``PyHeapTypeObject.ht_module`` which only exists in heap types:

```
        if(!_PyType_HasFeature((PyTypeObject *)super, Py_TPFLAGS_HEAPTYPE)) {
            // Static types in the MRO need to be skipped
            continue;
        }
```

**Comment by erlend-aasland** [comment]
> in _io__WindowsConsoleIO___init___impl(). The assertion fails because PyType_GetModuleByDef() returns NULL.

That's strange; it should be straight-forward to look up the module by def there.

**Comment by vstinner** [comment]
I reverted changes related to PyWindowsConsoleIO_Type and _io._WindowsConsoleIO.close().

**Review by erlend-aasland — APPROVED** [review]

**Comment by vstinner** [comment]
Aha, now the CI pass. I would feel more comfortable with a review. @erlend-aasland: you are also in to review it if you want, to check if i picked the right parts or tour code 😁

**Review by corona10 — APPROVED** [review]
lgtm, let's wait refleak bot.

**Comment by vstinner** [comment]
> I was not sure that it works on static types... but it seems like it does :-) I didn't get any crash.

I missed something: Erlend already converted multiple _io types to heap types: see commit c00faf79438cc7f0d98af2679c695f747e4369a3. Types used in this PR are heap types, that's why it just works!

**Comment by erlend-aasland** [comment]
No refleaks; good bot 🤖 ✅

**Pull request merged**
