### PR TITLE
Docs: group sqlite3.Connection attributes and methods

### PR DESCRIPTION
**Pull request by erlend-aasland**

### CODE REVIEW

**Review by ezio-melotti — APPROVED** [review]

**Review by CAM-Gerlach — APPROVED** [review]
IMO, it makes sense to list attributes before methods as you do, but just to note, the `Cursor` class right below it has the opposite order. Given it should be consistent (especially in Reference documentation), do you plan to follow this up with a PR moving those as well? Or would you like me to?

**Comment by erlend-aasland** [comment]
> Given it should be consistent (especially in Reference documentation), do you plan to follow this up with a PR moving those as well? Or would you like me to?

Yes, I noticed. Consistency is a good thing. Feel free to submit a PR for that.

**Comment by erlend-aasland** [comment]
Thanks for the reviews!

**Comment by erlend-aasland** [comment]
Reading through the docs in their current form, I wonder if it was a mistake to put the connection attributes before the connection methods; for your everyday sqlite3 programming, I suspect you'll be using the connection methods way more often than you'll be using the connection attributes. I think we should consider putting the methods before the attributes.

**Comment by CAM-Gerlach** [comment]
Yeah, I'd prepped a PR to do the above a few weeks ago when we discussed it, but got second thoughts for the same reason you mention and never went through with it.

**Pull request merged**
