### PR TITLE
Create Shuffle Deck Cards.py

### PR DESCRIPTION
**Pull request by Neetansh**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Neetansh

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by remilapeyre** [comment]
Hi @Neetansh, new features needs to be discussed on https://bugs.python.org first.

**Review by remilapeyre — CHANGES_REQUESTED** [review]
This is not needed, if you want to find ways to contribute, please look at the `newcomer friendly` opened issues in the bug tracker or have a look at the Dev Guide : https://devguide.python.org/.

**Comment by methane** [comment]
See https://blog.domenic.me/hacktoberfest/

We need not only close meaningless pull request, but also add "spam" label.

**Comment by JulienPalard** [comment]
hacktoberfest spam :,-(

**Pull request closed without merging**
