### PR TITLE
gh-95783: Use if+PyErr_Format rather than assert in _testcapi/heaptype.c

### PR DESCRIPTION
**Pull request by encukou**
* Issue: gh-95783

### CODE REVIEW

**Comment by encukou** [comment]
Hm. Is this too verbose?

**Review by erlend-aasland — APPROVED** [review]

**Review by vstinner — COMMENTED** [review]
For C tests, I'm fine with assert(): it's short an explicit. If an assertion fails, you can retrieve the C code from the line number included in the error message. I'm not against this change, it's up to you.

I added that to _testcapimodule.c:

```
/* Always enable assertions */
#undef NDEBUG
```

**Comment by erlend-aasland** [comment]
> ```
> /* Always enable assertions */
> #undef NDEBUG
> ```

That's neat; I'd be fine with that as well :) Up to you, Petr.

**Comment by encukou** [comment]
> `#undef NDEBUG`

Ha! That's what I was missing. Thanks! I'll send an alternate PR.

**Comment by vstinner** [comment]
> That's what I was missing.

I added it to Python 3.9.

I guess that building _testcapimodule.c in release module on Python 3.8 and older just removed assertions: not good.

**Comment by erlend-aasland** [comment]
IMHO, I think this speaks for setting up the test in C, and performing it in Python (unittest, `self.assert*()`). You get better error messages in case something fails (`0 != 1`, etc.), and there is no risk of tests not being run in release mode :)

**Pull request closed without merging**
