### PR TITLE
Fix capitalization of Unix in multiprocessing documentation

### PR DESCRIPTION
**Pull request by hawkinsw**
Fix capitalization of Unix in multiprocessing documentation

### CODE REVIEW

**Review by kumiDa — APPROVED** [review]
I was able to verify this change that corrects the deviation from the convention of addressing `Unix` in the documentation.
The change lgtm.

**Comment by hawkinsw** [comment]
> I was able to verify this change that corrects the deviation from the convention of addressing `Unix` in the documentation. The change lgtm.

Thank you @rahul-kumi!!

**Comment by JelleZijlstra** [comment]
Thanks! Would you mind also changing these:
```
library/os.path.rst:Unlike a unix shell, Python does not do any *automatic* path expansions.
library/test.rst:   Bind a unix socket, raising :exc:`unittest.SkipTest` if
```

And probably also these:
```
library/email.compat32-message.rst:      required by the unix mbox format.  For more flexibility, instantiate a
library/email.compat32-message.rst:      required by the unix mbox format.  For more flexibility, instantiate a
library/email.generator.rst:   *mangle_from_* is intended for use when messages are stored in unix mbox
library/email.generator.rst:   *mangle_from_* is intended for use when messages are stored in unix mbox
```

**Comment by hawkinsw** [comment]
> Thanks! Would you mind also changing these:
> 
> ```
> library/os.path.rst:Unlike a unix shell, Python does not do any *automatic* path expansions.
> library/test.rst:   Bind a unix socket, raising :exc:`unittest.SkipTest` if
> ```
> 
> And probably also these:
> 
> ```
> library/email.compat32-message.rst:      required by the unix mbox format.  For more flexibility, instantiate a
> library/email.compat32-message.rst:      required by the unix mbox format.  For more flexibility, instantiate a
> library/email.generator.rst:   *mangle_from_* is intended for use when messages are stored in unix mbox
> library/email.generator.rst:   *mangle_from_* is intended for use when messages are stored in unix mbox
> ```

All updated! I have changed the title of the commit to better reflect that the change is a little wider than initially suggested. I also rebased against master to make it smoother! I hope that it helps! Thanks for the review!

Will

**Review by kumaraditya303 — APPROVED** [review]

**Pull request merged**
