### PR TITLE
CI: Skip *.md files

### LINKED ISSUE #474: Skip CI for changes in *.md files
In python/cpython#95206, which only changes a single `.md` file, the `.github/workflows/build.yml` CI is run, which is definitely not needed. I'm pretty sure this can be fixed by adding a `path:` rule to `.github/workflows/build.yml` (and probably also `.github/workflows/doc.yml`). Something like this should suffice:

```yml
on:
  pull_request:
    paths:
      - '!**/*.md'
```

### PR DESCRIPTION
**Pull request by erlend-aasland**
Resolves python/core-workflow#474

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@ambv: do we backport workflow stuff to security branches?

**Comment by hugovk** [comment]
`build.yml` doesn't pass validation at https://rhysd.github.io/actionlint/

I think we need `paths` under both `push:` and `pull_request:`

**Comment by erlend-aasland** [comment]
Thanks; PTAL

**Review by hugovk — APPROVED** [review]
Looks good, thanks!

After merge, let's keep an eye on the next relevant PR and verify it's working as expected.

**Comment by erlend-aasland** [comment]
Thanks for the review, Hugo!

**Comment by erlend-aasland** [comment]
I wonder what's up with the CI; I'll try a re-run.

**Comment by erlend-aasland** [comment]
Doh. The CI is stuck because most of the `build.yml` checks are marked as required in the repo settings; this PR skips the `build.yml` checks, so it ends up in limbo.

**Comment by arhadthedev** [comment]
GitHyb docs on Actions [describes](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#example) this scenario using an example:

> [code snippet]
>
> Due to path filtering, a pull request that only changes a file in the root of the repository will not trigger this workflow and is blocked from merging.
>
> You can fix this by creating a generic workflow, with the same name, that will return true in any case similar to the workflow below:
>
> [code snippet]
>
> Now the checks will always pass whenever someone sends a pull request that doesn't change the files listed under paths in the first workflow.

I hope it's applicable here.

**Comment by erlend-aasland** [comment]
Thanks, Oleg, that's worth checking out. I'm still lukewarm to this whole change, though. I'll have a look in a day or two. If you want to give it a try, you could open a competing PR.

**Comment by erlend-aasland** [comment]
I don't think it is worth the added complexity. I'm closing this. If anyone else wants to take a shot at it, feel free to pick it up.

**Comment by ambv** [comment]
> @ambv: do we backport workflow stuff to security branches?

Yes, @erlend-aasland, unless they're overly complex or don't apply (newer compiler, newer OS, etc.). After all, CI still runs on security backports.

**Pull request closed without merging**
