### PR TITLE
gh-9886c: Fixed hls colors going out of bounds 0.0-1.0

### PR DESCRIPTION
**Pull request by kanishkanarch**
Return values of this function were going out of bounds of 0.0 - 1.0, fixed that.
[Parent PR from where this issue is coming from](https://github.com/matplotlib/matplotlib/pull/24885).

### CODE REVIEW

**Comment by kanishkanarch** [comment]
Following is a small experiment I did (as a substitute of calling [this function](https://github.com/python/cpython/blob/main/Lib/colorsys.py#L84)):
image

**Comment by FFY00** [comment]
Hi @kanishkanarch, thank you for the contribution! However, I agree with @jklymak and @tacaswell in https://github.com/matplotlib/matplotlib/pull/24885, that this should be fixed downstream, not here. For that reason, I will close this PR. If you have any questions, or think I overlooked something, feel free to comment.

**Comment by kanishkanarch** [comment]
Hi @FFY00, thank you for reviewing this PR. I believe [this line](https://github.com/python/cpython/blob/main/Lib/colorsys.py#L86) is the source of error, where the value of variable `s` (saturation) is going outside the range of 0.0 - 1.0 (please refer to the small code screenshot above). I haven't tested the function completely, but there are some instances where all three values `h, s, l` are going out of range:
image

**Comment by kanishkanarch** [comment]
Following is complete experiment with some RGB values that [this function](https://github.com/python/cpython/blob/main/Lib/colorsys.py#L75) should convert to HSL values while making sure the returned HSL values should be within 0.0 - 1.0 range.
image

**Comment by ppwwyyxx** [comment]
@FFY00 the top of colorsys.py claims that 
> All inputs and outputs are triples of floats in the range [0.0...1.0]

So I think it can be considered a bug in cpython that some valid inputs will produce outputs slightly outside the range of [0, 1]. 

Though I don't think `round()` is the right fix, I think we can add a `clip` to the outputs to ensure they stay in the range. Do you think that will be acceptable?

**Comment by FFY00** [comment]
If we were to fix this to make sure we are in range, I'd raise an error instead of clipping the output, as if our conversion logic is correct, that means the given input does not have a valid output. Silently clipping the values would be the wrong approach IMO.

However, as that would likely break downstream code, I think we have three viable paths forward:

- 1) Document that the results can go out of the range
- 2) Add an argument to enable clipping and emmit a warning when the value goes out of bounds with the current code

**Pull request closed without merging**
