### PR TITLE
gh-111495: Add tests for PyTuple C API

### PR DESCRIPTION
**Pull request by rawwar**
Adding tests for PyTuple C API - Issue #111495 

* Issue: gh-111495

### CODE REVIEW

**Comment by rawwar** [comment]
Hello @serhiy-storchaka , I am not sure how to write tests for the following C API's. Can you please help me with some ideas. Thanks!

1. `PyTuple_Pack`
2. `PyTuple_SetItem`
3. `PyTuple_SET_ITEM`
4. `PyTuple_Resize`

**Comment by skirpichev** [comment]
@rawwar, are you working on this?  Regarding ideas, you could take look on other tests for C-API, e.g. for lists.

**Comment by rawwar** [comment]
> @rawwar, are you working on this? Regarding ideas, you could take look on other tests for C-API, e.g. for lists.

Thanks. I will go through them. Will be looking into this over the weekend

**Comment by rawwar** [comment]
I won't be able to complete this PR at this time.

**Comment by skirpichev** [comment]
I'll try to finish your work.

**Pull request closed without merging**
