### PR TITLE
[bpo-30916] Pre-build OpenSSL and Tcl/Tk for Windows

### PR DESCRIPTION
**Pull request by zooba**
Not ready to merge yet, but far enough along for @zware and any interested parties to take a look.

Before finally merging this, I'll do releasable/signed builds and upload them to the GitHub repository, which should make the CI pass.

The change to OpenSSL cannot be backported, in my opinion (unless we prove that it is totally safe). While the Tcl/Tk change can be, I'm not sure that it's worth it.

### CODE REVIEW

**Comment by zooba** [comment]
See the binary builds at https://github.com/zooba/cpython-bin-deps/tree/tcltk-8.6.6.0 and https://github.com/zooba/cpython-bin-deps/tree/openssl-bin-1.0.2k.

You can do a test build by running `get_externals.bat --organization zooba` and then `build.bat -e ...`

**Comment by zooba** [comment]
I have successful builds and test runs now when pulling externals from my repo. If there are no suggestions about the layout of the binaries repo, then I'll push release-ready builds to them so the CI build passes.

**Comment by zooba** [comment]
Zach opted not to review right now and said go ahead and he'll fix up my failures later :)

I pushed release bits to our actual repository and triggered another build (hopefully) to test.

**Comment by zooba** [comment]
Build passes fine with the binaries published. Detailed comment on the bug

**Comment by forskning** [comment]
possible typo in https://github.com/python/cpython/commit/68d663cf85d1ac5eaf83482eed39c0a6f8093601

line 27 in PCbuild/find_python.bat

- @set _Py_EXTERNALS_DIR=%EXTERNAL_DIR%
+ @set _Py_EXTERNALS_DIR=%EXTERNALS_DIR%

**Comment by forskning** [comment]
possible typo in https://github.com/python/cpython/commit/68d663cf85d1ac5eaf83482eed39c0a6f8093601

line 27 PCbuild/find_python.bat

````-@set _Py_EXTERNALS_DIR=%EXTERNAL_DIR%
+@set _Py_EXTERNALS_DIR=%EXTERNAL_DIR%````

**Comment by forskning** [comment]
possible typo in https://github.com/python/cpython/commit/68d663cf85d1ac5eaf83482eed39c0a6f8093601

line 27 PCbuild/find_python.bat

**Pull request merged**
