### PR TITLE
bpo-1635741: prepare for multi-phase init for unicodedata

### PR DESCRIPTION
**Pull request by koubaa**
See this [PR](https://github.com/python/cpython/pull/21375) for a discussion of this change

### CODE REVIEW

**Comment by vstinner** [comment]
cc @corona10 @shihai1991

**Comment by shihai1991** [comment]
`ucnhash_CAPI` is a C API, it means other users could calling `PyCapsule_Import()' to use it, we never know the user how to use it.

**Comment by koubaa** [comment]
@shihai1991 In CPython source code, all of the usages are accounted for.  Technically you are right that extension modules outside of CPython could be calling these capsule methods.  I don't know how to measure the likelyhood of that but it would be a runtime error.

I can turn it into a compile-time error by replacing the capsule methods with small wrappers that have one fewer argument.  Then those extension modules if they exist can conditionally compile based on the cpython version.

**Comment by shihai1991** [comment]
> @shihai1991 In CPython source code, all of the usages are accounted for. Technically you are right that extension modules outside of CPython could be calling these capsule methods. I don't know how to measure the likelyhood of that but it would be a runtime error.
> 
> I can turn it into a compile-time error by replacing the capsule methods with small wrappers that have one fewer argument. Then those extension modules if they exist can conditionally compile based on the cpython version.

We need to be careful to break the backward compatibility. Hi, victor, what's your opinion?

**Comment by vstinner** [comment]
> Hi, victor, what's your opinion?

Leave C extensions which expose a capsule unchanged, until the capsule API is modified to pass the module to functions exported as capsule.

I suggest to open an issue to propose to enhance the capsule API for that.

**Comment by koubaa** [comment]
@vstinner In that case I think this PR is ready to be merged

**Review by vstinner — CHANGES_REQUESTED** [review]
I dislike this approach and would prefer to enhance the capsule API to pass the module instance to function exported as a capsule API.

**Pull request closed without merging**
