### PR TITLE
gh-119613: use C99+ functions instead of Py_IS_NAN/INFINITY/FINITE

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-119613

### CODE REVIEW

**Comment by skirpichev** [comment]
This partially address #119613.  I think this part doesn't require a news entry.  CC @Eclips4

**Comment by Eclips4** [comment]
> This partially address #119613. I think this part doesn't require a news entry. CC @Eclips4

Yes, since this is a non-visible user change, I agreed.

**Comment by rhettinger** [comment]
@tim-one is there an on-going reason to have these portability macros?

**Comment by skirpichev** [comment]
Since https://github.com/python/cpython/commit/194a9526d8ee6abbbe58ef48520ec87a7e83f327 these macros are just aliases for isnan, isinf, etc:
https://github.com/python/cpython/blob/3e8b60905e97a4fe89bb24180063732214368938/Include/pymath.h#L30-L40

**Review by vstinner — APPROVED** [review]
LGTM. Simple text replacement.

**Comment by vstinner** [comment]
@rhettinger:
> @tim-one is there an on-going reason to have these portability macros? Are NaN values guaranteed to be supported?

Python 3.10 and older supported platforms without IEEE 754, without NaN, and without C99 `<math.h>`. We had complex macros such as:

```c
#ifndef Py_IS_NAN
#if defined HAVE_DECL_ISNAN && HAVE_DECL_ISNAN == 1
#define Py_IS_NAN(X) isnan(X)
#else
#define Py_IS_NAN(X) ((X) != (X))
#endif
#endif
```

Python 3.11 and newer requires IEEE 754, NaN and C99 `<math.h>`. Macros were kept for backward compatibility only:

```c
#define Py_IS_NAN(X) isnan(X)
```

Issues:

* https://github.com/python/cpython/issues/91073
* https://github.com/python/cpython/issues/90814
* https://github.com/python/cpython/issues/89603
* https://github.com/python/cpython/issues/90798

See also this LWN article: [CPython, C standards, and IEEE 754](https://lwn.net/Articles/886516/).

**Comment by vstinner** [comment]
@mdickinson: Are you ok with this change? You wrote a comment about these macros there: https://github.com/python/cpython/pull/119457#discussion_r1615985599

**Comment by mdickinson** [comment]
> @mdickinson: Are you ok with this change?

Yes, absolutely. I'm fairly sure the macros were born out of (now somewhat ancient) portability needs that no longer apply, now that C99 (and later) adoption is sufficiently widespread.

I'd suggest running all buildbots on this PR, just to be on the safe side.

**Review by mdickinson — APPROVED** [review]
LGTM

**Review by rhettinger — APPROVED** [review]

**Comment by skirpichev** [comment]
There are tests failures, but hardly it's related to the pr.  Something expected, given there are not build bots for non-IEEE-754 platforms, right?

**Comment by mdickinson** [comment]
> There are tests failures, but hardly it's related to the pr.

Agreed - the failures look unrelated.

**Comment by vstinner** [comment]
Merged, thanks.

**Pull request merged**
