### PR TITLE
bpo-36008: Doc update for 3.8 migration

### PR DESCRIPTION
**Pull request by utkarsh2102**
This changes the version to 3.8 when it addresses the newcomers.

https://bugs.python.org/issue36008

### CODE REVIEW

**Review by eamanu — COMMENTED** [review]
Hello @utkarsh2102, thanks for the contribution!

This issue was assigned to @Mariatta  to be solved on the PyCon US Cleveland.

**Comment by utkarsh2102** [comment]
@eamanu, I had asked her (left the comment) about the same and didn't get any reply :(
I am myself at a DevSprint, hence sent a fix.

**Comment by eamanu** [comment]
> @eamanu, I had asked her (left the comment) about the same and didn't get any reply :(
> I am myself at a DevSprint, hence sent a fix.

Ah ok! so, we have wait for Mariatta's comments

**Review by csabella — APPROVED** [review]
LGTM.

**Comment by csabella** [comment]
@utkarsh2102, thank you for the pull request.  Your change has been merged.  :tada: :tada:

**Pull request merged**
