### PR TITLE
gh-96954: Fix `make regen-unicodedata` in out-of-tree builds

### PR DESCRIPTION
**Pull request by hroncok**
This avoids:

    python3.13 Tools/unicode/makeunicodedata.py
    python3.13: can't open file '.../build/debug/Tools/unicode/makeunicodedata.py': [Errno 2] No such file or directory
    make: *** [Makefile:1498: regen-unicodedata] Error 2

* Issue: gh-96954

### CODE REVIEW

**Comment by vstinner** [comment]
I confirm that the fix works as expected, there is no error:

```
git pr 112118

git clean -fdx
mkdir WORKDIR
cd WORKDIR
../configure --with-pydebug
make regen-all
make regen-unicodedata
```

I also tested that other regen commands don't fail:

```
make regen-stdlib-module-names
make regen-limited-abi
make regen-configure
```

**Comment by vstinner** [comment]
Please run `make regen-unicodedata` in the source directory and include changes of generated files in your PR. See: https://github.com/python/cpython/actions/runs/6879727597/job/18712327275?pr=112118

**Comment by hroncok** [comment]
There's a typo in the second commit message. I know you don't like force pushing to PRs, so please correct it when squashing.

**Comment by hroncok** [comment]
Thanks.

**Comment by vstinner** [comment]
Thanks for your fix! We test out-of-free build in the CI, but we don't run `make regen-all` in this out-of-tree CI job. `make regen-all` is tested in a CI job which don't build Python out-of-tree.

**Pull request merged**
