### PR TITLE
Typo fix in file Include/object.h

### PR DESCRIPTION
**Pull request by hansrajdas**
* accross -> across
* Extra space removed in comment

### CODE REVIEW

**Comment by jdemeyer** [comment]
FYI: https://github.com/python/cpython/pull/4944#issuecomment-409157431

**Review by jdemeyer — APPROVED** [review]

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
Thanks!

**Comment by hansrajdas** [comment]
This PR is not backported to 3.8, there was some error while backporting (https://github.com/python/cpython/pull/14556#issuecomment-508866867). Is there something i can do for this?

**Comment by brettcannon** [comment]
@hansrajdas looks like a bot hiccup. It isn't really that important for a spelling fix so I'm not too bothered if it doesn't get backported.

**Comment by hansrajdas** [comment]
Ok, Thanks for writing back!

**Pull request merged**
