### PR TITLE
bpo-2716: add license for audioop module

### PR DESCRIPTION
**Pull request by furkanonder**
https://bugs.python.org/issue2716

### CODE REVIEW

**Review by remilapeyre — CHANGES_REQUESTED** [review]
Hi @furkanonder, I think the bpo issue for this PR is bpo-2716, not bpo-40462.

**Comment by vstinner** [comment]
> The audioop module uses the code base in g771.c file of the SoX project

Which functions were created from SoX code? All of them? Some of them?

**Comment by furkanonder** [comment]
Some of functions,globals variables and list declaritons.

> > The audioop module uses the code base in g771.c file of the SoX project
> 
> Which functions were created from SoX code? All of them? Some of them?
Some of functions,globals variables and array declarations.
Some of them.

**Comment by furkanonder** [comment]
> > The audioop module uses the code base in g771.c file of the SoX project
> 
> Which functions were created from SoX code? All of them? Some of them?

Some of functions,globals variables and array declarations.

**Review by cinarizasyon — APPROVED** [review]

**Comment by AlexWaygood** [comment]
I'm not sure if this PR (and the associated issue) is still relevant now that `audioop` has been deprecated following the acceptance of PEP 594. @brettcannon, what do you think?

**Comment by arhadthedev** [comment]
@AlexWaygood I'm not a core dev but corporate legal matters is not a joke. They need to be taken seriously to avoid any potential problem from Oracle that now owns all Sun's intellectual property. So in my opinion not only this should be merged, it also should be backported as far as possible.

**Comment by hugovk** [comment]
Associated issue: https://bugs.python.org/issue2716 -> https://github.com/python/cpython/issues/46968

**Comment by brettcannon** [comment]
@VanL does this change look good?

**Comment by VanL** [comment]
This license does not match the declared license from the source file (GPL, or possible LGPL later). After looking at all the declared tags, they all are consistently under *GPL licenses. So I would not merge this: 
-The license looks incorrect
- Given the apparent license, it would significantly affect the licensing of Python overall

**Review by brettcannon — CHANGES_REQUESTED** [review]
As per Van's suggestion.

**Comment by AA-Turner** [comment]
Triggering CLA.

A

**Comment by furkanonder** [comment]
> This license does not match the declared license from the source file (GPL, or possible LGPL later). After looking at all the declared tags, they all are consistently under *GPL licenses. So I would not merge this: -The license looks incorrect
> 
>     * Given the apparent license, it would significantly affect the licensing of Python overall
> 
> 
> Update: I see the link to sourcearchive on bpo, but I can't verify the license because that is now down. The sourcearchive license would be compatible with Python's licensing, but the link to sourceforge (which the new patch references) declares this to be under the GPL.
> 
> If you can update this to use the source from https://web.archive.org/web/19970716121258/http://www.spies.com/Sox/Archive/soxgamma.tar.gz, that has a license that could be compatible (with appropriate copying of all copyright information), but I would not merge this as-is. In fact, I would suggest pulling out this module/rewriting this bit.

@VanL @brettcannon I have added the license in the source you mentioned.

**Review by brettcannon — APPROVED** [review]

**Pull request merged**
