### PR TITLE
bpo-32589: Statistics as a result from timeit

### PR DESCRIPTION
**Pull request by DaGuich**
Add stats flag in timeit function. This should
return a dictionary with additional statistics
information.

Resolves [bpo 32589](https://bugs.python.org/issue32589)

https://bugs.python.org/issue32589

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by AraHaan** [comment]
@DaGuich CI fails saying there is an whitespace issue somewhere you might want to fix it.

**Comment by DaGuich** [comment]
@AraHaan Done. I've also added a "News" entry

**Comment by AraHaan** [comment]
ok

**Comment by DaGuich** [comment]
Can be closed, as the issue rejected

**Pull request closed without merging**
