### PR TITLE
bpo-37737: mmap module, track anonymous paging case on macOS

### PR DESCRIPTION
**Pull request by devnexen**
https://bugs.python.org/issue37737

### CODE REVIEW

**Comment by devnexen** [comment]
Allows output as :
image

**Comment by ronaldoussoren** [comment]
What is the use case for this? 

And why one memory tag with a specific value?

**Comment by devnexen** [comment]
If it is you wish the python mmap module mapping standing out to monitor it more accurately.
Otherwise tag ID is allowed up to 255, guaranteed from 240 to be freely available at least.

**Comment by ronaldoussoren** [comment]
I still don't understand what the use case is, why is it useful to track usage of mmap.mmap in this way? 

I'd expect that tracking Python's memory allocator would be more useful to track memory usage patterns and debug production issues.

**Comment by devnexen** [comment]
It is a more native mean ... when it occurs you monitor the whole system and allows to distinguish python from the rest.

**Comment by ronaldoussoren** [comment]
I still don't think this is a useful feature. I'm therefore closing this PR (and the related issue).

**Pull request closed without merging**
