### PR TITLE
gh-111420: Allow type comments in parenthesized `with` statements

### PR DESCRIPTION
**Pull request by tomasr8**
I ran `make regen-pegen` and `make regen-ast`, I hope that's all that is needed :)

I also wanted to add some regression tests, but I I'm not sure where to put them. Should they go in `test_ast.py` or somewhere else? This is what I have in mind:

```python
tree = ast.parse("with (a as b): # type: foo\n    pass", type_comments=True)
self.assertEqual("""\
Module(
    body=[
        With(
            items=[
                withitem(
                    context_expr=Name(id='a', ctx=Load()),
                    optional_vars=Name(id='b', ctx=Store()))],
            body=[
                Pass()],
            type_comment='foo')],
    type_ignores=[])""", ast.dump(tree, indent=4))
        
tree = ast.parse("with (a, b): # type: foo\n    pass", type_comments=True)
self.assertEqual("""\
Module(
    body=[
        With(
            items=[
                withitem(
                    context_expr=Name(id='a', ctx=Load())),
                withitem(
                    context_expr=Name(id='b', ctx=Load()))],
            body=[
                Pass()],
            type_comment='foo')],
    type_ignores=[])""", ast.dump(tree, indent=4))
```

* Issue: gh-111420

### CODE REVIEW

**Comment by pablogsal** [comment]
This is missing a test in `test_type_comments.py`:

https://github.com/python/cpython/blob/main/Lib/test/test_type_comments.py

**Comment by tomasr8** [comment]
Thanks for letting me know! I'll add it

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by tomasr8** [comment]
> LGTM

Damn you're fast :eyes: :smile:

**Pull request merged**
