### PR TITLE
bpo-40600: atexit only loads single time per interpreter

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue40600

### CODE REVIEW

**Review by vstinner — CHANGES_REQUESTED** [review]
I would prefer to move the atexit list of callbacks into PyInterpreterState, and the atexit module would get the list from the current interpreter.

**Comment by corona10** [comment]
@vstinner Ah okay, I will update the PR by tomorrow ;)

**Comment by corona10** [comment]
I have made the requested changes; please review again

**Comment by encukou** [comment]
This is solved in a different way in bpo-42639.
Thank you for working on this issue, even though this PR didn't make it in!

**Pull request closed without merging**
