### PR TITLE
bpo-34782: Check locals is a mapping bdb.run*

### PR DESCRIPTION
**Pull request by ghost**
Check bdb.run and bdb.runeval's locals with __contains__ attribute

https://bugs.python.org/issue34782

### CODE REVIEW

**Review by pppery — CHANGES_REQUESTED** [review]
This doesn't actually fix the bug, just make it crash with a more helpful error message in some (but not all) cases. For example, this check can be bypassed if code being debugged does something like "exec("pass",{},FakeContainer)", there is no eagerly evaluated requirement that locals passed to exec and eval be mappings!

**Review by scotchka — COMMENTED** [review]
Would using f-strings cause problem with earlier versions of Python?

**Comment by scotchka** [comment]
@pppery, what is the desired behavior for the example in your bug report? That, since the statement is "pass", there should be no exception raised?

**Comment by pppery** [comment]
You are correct, and if the code being debugged did something, that that code would run

**Comment by BTaskaya** [comment]
> This doesn't actually fix the bug, just make it crash with a more helpful error message in some (but not all) cases. For example, this check can be bypassed if code being debugged does something like "exec("pass",{},FakeContainer)", there is no eagerly evaluated requirement that locals passed to exec and eval be mappings!

https://github.com/python/cpython/blob/9daecf37a571e98aaf43a387bcc9e41a7132f477/Python/bltinmodule.c#L919

https://github.com/python/cpython/blob/9daecf37a571e98aaf43a387bcc9e41a7132f477/Python/bltinmodule.c#L1021
There is a check in eval and exec about is locals mapping.

**Comment by BTaskaya** [comment]
I agree. It is related with `tp_as_mapping` protocol. I'm closing PR

**Pull request closed without merging**
