### PR TITLE
bpo-41746: Fix CHECK macros to not do type erasure

### PR DESCRIPTION
**Pull request by lysnikolaou**
https://bugs.python.org/issue41746

### CODE REVIEW

**Comment by lysnikolaou** [comment]
@gvanrossum @pablogsal One question on this:

In the macro `#define CHECK(result) (result == NULL ? SET_ERROR(p) : result)` result might be a call to some costly function, which in the positive case will be called twice. Are we confident enough the the compiler is going to optimize those doubled calls away?

**Comment by pablogsal** [comment]
Unfortunately, this does not work because the ternary operator deduces the type as `void*`. From the C99 standard:

> since C does not have a type hierarchy for pointer types, pointer operands may only be used if they are of the same type (ignoring type qualifiers) or one is void or NULL.

**Review by pablogsal — CHANGES_REQUESTED** [review]
Unfortunately, this does not work because the ternary operator deduces the type as `void*`. From the C99 standard:

> since C does not have a type hierarchy for pointer types, pointer operands may only be used if they are of the same type (ignoring type qualifiers) or one is void or NULL.

**Comment by pablogsal** [comment]
The grammar needs to be fixed as well. If you substitute the macro for an identity:

```
# define CHECK(result) result
```

you will start to see these errors:


```
n file included from Parser/pegen.h:7,
                 from Parser/parser.c:2:
./Include/Python-ast.h:647:50: note: expected ‘asdl_expr_seq *’ but argument is of type ‘asdl_seq *’
  647 | expr_ty _Py_BoolOp(boolop_ty op, asdl_expr_seq * values, int lineno, int
      |                                  ~~~~~~~~~~~~~~~~^~~~~~
In file included from Parser/parser.c:2:

```

The reason these errors are not present now is that the macros pass `void*` and that can be cast to anything, but that's what we try to avoid.

**Comment by lysnikolaou** [comment]
I'm closing this.

**Comment by gvanrossum** [comment]
Why?

**Comment by lysnikolaou** [comment]
In a chat I had with @pablogsal, he explained to me why this doesn't work. Basically the different pointer types will get cast to `void *`s with this solution as well. The easiest to grasp solution (Pablo's idea) would be to also pass the return type to the macro and cast to that type. That would require a good amount of changes to the grammar though.

Bottom line is we should probably discuss this a bit more. Another idea Pablo mentioned is to pass the type to the macro in the generator level, but that hardly seems feasible for nested call to `CHECK`.

**Comment by gvanrossum** [comment]
Hm, it's just a bit of work, we should just do it.

**Comment by lysnikolaou** [comment]
Opened #22864.

**Pull request closed without merging**
