### PR TITLE
gh-123189: [`Modules/blake2module.c`]: Move function definitions and their usage under the macros

### PR DESCRIPTION
**Pull request by Eclips4**
* Issue: gh-123189

### CODE REVIEW

**Comment by Eclips4** [comment]
cc @msprotz

**Review by msprotz — COMMENTED** [review]
Is there a more python-idiomatic way of doing this? I remember seeing something like Py_Unused that might have helped with these warnings.

**Comment by Eclips4** [comment]
> Is there a more python-idiomatic way of doing this? I remember seeing something like Py_Unused that might have helped with these warnings.

`Py_UNUSED` is used for arguments in function declarations, so unfortunately we can't use it :(

**Comment by msprotz** [comment]
ok, worst case, you could do `(void)st;` if you wanted to avoid the #ifdef logic, but I don't think it matters too much. thanks for the followup fix

**Review by msprotz — APPROVED** [review]

**Review by sobolevn — APPROVED** [review]
With this fix:

```
» make
gcc  -I./Modules/_hacl/include -fno-strict-overflow -Wsign-compare -g -Og -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include  -fstack-protector-strong -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal -I./Include/internal/mimalloc  -I. -I./Include -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/openssl/include   -c ./Modules/blake2module.c -o Modules/blake2module.o
gcc -bundle -undefined dynamic_lookup -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/openssl/lib    Modules/blake2module.o  Modules/_hacl/libHacl_Hash_Blake2.a  -o Modules/_blake2.cpython-314d-darwin.so
The necessary bits to build these optional modules were not found:
_gdbm                     _tkinter                                         
To find the necessary bits, look in configure.ac and config.log.

Checked 112 modules (34 built-in, 76 shared, 0 n/a on macosx-14.5-arm64, 0 disabled, 2 missing, 0 failed on import)
```

Thank you!

**Pull request merged**
