### PR TITLE
closes bpo-36115: Fix some reference leaks in typeobject.c.

### PR DESCRIPTION
**Pull request by benjaminp**
a24107b04c1277e3c1105f98aff5bfa3a98b33a0 introduced a few refleaks.

https://bugs.python.org/issue36115

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]
Thank you @benjaminp.

**Comment by pablogsal** [comment]
This PR fixes https://bugs.python.org/issue36114 :)

**Comment by benjaminp** [comment]
It fixes `test_multiprocessing` modifying the environment?

**Comment by pablogsal** [comment]
The issue number was wrong, I have edited the comment

**Comment by pablogsal** [comment]
For reference, it fixes refleaks detected on Ctypes:
https://buildbot.python.org/all/#/builders/1/builds/515

OK (skipped=89)
.
test_ctypes leaked [72, 72, 72] references, sum=216
test_ctypes leaked [26, 26, 26] memory blocks, sum=78
2 tests failed again:
    test_ctypes test_inspect
== Tests result: FAILURE then FAILURE ==

https://bugs.python.org/issue36115

**Pull request merged**
