### PR TITLE
gh-109990: Fixed argparser parsing optional arguments with same prefix

### PR DESCRIPTION
**Pull request by rruuaanng**
According to https://github.com/python/cpython/issues/109990, argparser can incorrectly parse arguments when they have the same prefix as other parameters.

* Issue: gh-109990

### CODE REVIEW

**Comment by rruuaanng** [comment]
Why, I can't understand.

**Comment by rruuaanng** [comment]
@getsimonz, Maybe you can check if this PR solves your problem

**Comment by serhiy-storchaka** [comment]
Fixed by #124631.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution, @rruuaanng, but this issue has been fixed in other way by #124631.

**Pull request closed without merging**
