### PR TITLE
Removed ambiguity in __init_subclass__ docs

### PR DESCRIPTION
**Pull request by davidgilbertson**
Reading this for the first time, not knowing what the method does, I couldn't work out which class "that class" referred to (obviously it becomes clear once you know what the method does).

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]

**Review by kumaraditya303 — APPROVED** [review]

**Comment by kumaraditya303** [comment]
@JelleZijlstra This is ready for merge.

**Review by JelleZijlstra — APPROVED** [review]
Another small docs improvement I'd like to merge (cc @gvanrossum).

There is actually a more precise description of what `__init_subclass__` does on line 1982-3 below. The proposed change here is more informal and I think it improves clarity.

**Review by gvanrossum — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
I'm glad @miss-islington listens to backport labels even after a merge :)

**Comment by gvanrossum** [comment]
> I'm glad @miss-islington listens to backport labels even after a merge :)

She's very smart.

**Pull request merged**
