### PR TITLE
gh-78913: modified to return uuid version between 1 to 5 based on RFC 4122

### PR DESCRIPTION
**Pull request by jophinep**
https://bugs.python.org/issue34732

* Issue: gh-78913

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by jophinep** [comment]
@arhadthedev thank you for adding the news entry.

Since this is my first fix and pr :) I am just curious and excited about which release these changes are getting into. Could someone please let me know?

**Comment by arhadthedev** [comment]
@vstinner, @zooba (as committers into `Lib/uuid.py`)

**Comment by jophinep** [comment]
It would be amazing and grateful if someone could point me to a documentation about what is pending to get this pr reviewed.

Looking forward to the community's reply.  Thank you!

**Comment by zooba** [comment]
I think the PR is fine, but I don't think we want this change. There's nothing in the spec that says versions other than 1-5 are _invalid_, just that they aren't currently defined, and our docs say that we will return the version and it may not be meaningful. This change would require us to update the documentation to say that we _may not return the version field_ if it is an undefined value.

I'll cross-post on #78913, which is where this discussion should happen.

**Comment by encukou** [comment]
It is the docs that are wrong, not the implementation.

**Pull request closed without merging**
