### PR TITLE
Fix typo in what's new. bidst_wheel -> bdist_wheel

### PR DESCRIPTION
**Pull request by ravcio**
bidst_wheel -> bdist_wheel

Automerge-Triggered-By: GH:Mariatta

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@ravcio, @AvendiSchool

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by iritkatriel — APPROVED** [review]

**Comment by iritkatriel** [comment]
@ravcio Would you like to sign the CLA?  It's not strictly required for fixing a typo, but it will be necessary when you make larger contributions in the future.

**Review by Mariatta — APPROVED** [review]
Thanks!

**Comment by Mariatta** [comment]
Once CLA is signed this will get merged automatically. Thanks and congrats on your first contribution to CPython!

**Review by ravcio — COMMENTED** [review]
comment

**Comment by Mariatta** [comment]
This PR is authored by @ravcio but the git commit was made by @AvendiSchool.
Both would need to sign the CLA.
Also, is there a reason that the PR was made by a different person than the one who  made the commit?

If the two accounts are owned by one person, would it be possible for you to adjust the PR such that the PR author and the committer are the same?

**Pull request merged**
