### PR TITLE
IDLE: Fix docs URL in the About window

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
It is not guaranteed that the Python version contains exactly 2 dots.
See also `Lib/idlelib/editor.py`.

### CODE REVIEW

**Comment by ambv** [comment]
As mentioned [here](https://github.com/python/cpython/pull/28228#discussion_r710999193), this is unnecessary because `platform.python_version` always returns a version with two periods.

**Comment by ambv** [comment]
This missed the boat for inclusion in Python 3.9 which accepts security fixes only as of today.

**Review by erlend-aasland — APPROVED** [review]
LGTM

**Comment by erlend-aasland** [comment]
(Updating branch to retrigger CLA)

**Comment by terryjreedy** [comment]
Regardless of how IDLE gets the python version and whether it is centralized in the new util.py, I prefer the look of the patch with the url fstring removed from the call.

**Pull request merged**
