### PR TITLE
gh-88233: zipfile: handle extras after a zip64 extra

### LINKED ISSUE #88233: Zipfile lib overwrites the extra field during closing when the archive size is more then ZIP64_LIMIT
BPO | [44067](https://bugs.python.org/issue44067)
--- | :---
Nosy | @Yhg1s, @serhiy-storchaka
Files | <li>[zip_bug.zip](https://bugs.python.org/file50025/zip_bug.zip "Uploaded as application/x-zip-compressed at 2021-05-07.08:18:55 by shaanbhaya")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-05-07.08:18:55.383>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.11', '3.7', 'library']
title = 'Zipfile lib overwrites the extra field during closing when the archive size is more then ZIP64_LIMIT'
updated_at = <Date 2021-11-07.00:34:59.007>
user = 'https://bugs.python.org/shaanbhaya'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-07.00:34:59.007>
actor = 'anadius'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-07.08:18:55.383>
creator = 'shaanbhaya'
dependencies = []
files = ['50025']
hgrepos = []
issue_num = 44067
keywords = []
message_count = 3.0
messages = ['393178', '393179', '405760']
nosy_count = 5.0
nosy_names = ['twouters', 'alanmcintyre', 'serhiy.storchaka', 'shaanbhaya', 'anadius']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44067'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-96161
* gh-102083
* gh-102084
* gh-102086
* gh-102087

### PR DESCRIPTION
**Pull request by thatch**
Previously, any data _after_ the zip64 extra would be removed.

With many new tests.

Fixes #88233

* Issue: gh-88233

Automerge-Triggered-By: GH:jaraco

### CODE REVIEW

**Review by gpshead — APPROVED** [review]

**Comment by gpshead** [comment]
Can you add a NEWS entry (https://pypi.org/project/blurb/ can help) describing the bugfix?

**Comment by thatch** [comment]
Rebased and NEWS entry added.

**Comment by thatch** [comment]
@gpshead would you like me to do anything else on this one?  NEWS entry is added.

**Comment by thatch** [comment]
@gpshead any other changes you'd like to see on this one?

**Comment by smontanaro** [comment]
(I'm working my way through some PRs which have been approved and are labeled "awaiting merge", hence my seemingly bolt from the blue comment. Why? [Read here](https://discuss.python.org/t/prs-awaiting-merge/21313).)

Looks like this is complete. Can someone merge it so it doesn't get too stale?

**Comment by arhadthedev** [comment]
@gpshead (as the zipfile expert), would you mind to review and possibly merge this PR?

**Comment by gpshead** [comment]
This one is likely good, @jaraco is our _real_ zipfile expert though. looping him in before merging.

**Review by jaraco — APPROVED** [review]
Looks good. I had some minor nitpicks with the test, so took the liberty to correct those. I also replaced the literal `1` with ZIP64_EXTRA in the hopes of more clearly communicating that aspect.

**Pull request merged**
