### PR TITLE
gh-92530: Fix an issue that occurred after interrupting threading.Condition.notify

### LINKED ISSUE #92530: Issues when Condition.notify() is interrupted
If `threading.Condition.notify()` is interrupted just after it releases the waiter lock, but before remove it from the queue, the following calls of `notify()` will fail with `RuntimeError: cannot release un-acquired lock`. It can block the waiter threads if they do not use timeout.

https://github.com/python/cpython/blob/5bc2390229bbcb4f13359e867fd8a140a1d5496b/Lib/threading.py#L375-L380

The simplest solution would be to silence a RuntimeError in `waiter.release()`. There may be similar issues in other parts of the code.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Fixes #92530.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Removing the deque entirely undoes the optimisation from https://bugs.python.org/issue17385

**Comment by serhiy-storchaka** [comment]
No, `self._waiters` is still a deque.

**Review by methane — APPROVED** [review]

**Comment by vstinner** [comment]
I reviewed your fix twice. Ok, now it makes sense and the comment is enough to explain the fix and the code.

It might be safe to check if the waiter is already released by calling the .locked() method, but I don't think that it's worth it and it might introduce new subtle concurrency issues. In short, the fix is correct :-)

**Comment by serhiy-storchaka** [comment]
EAFP is so superior to LBYL here, that the latter I did not even consider.

**Pull request merged**
