### PR TITLE
Doc: Builtins functions: faster jump table

### PR DESCRIPTION
**Pull request by JulienPalard**
Having hard time fininding entries in the [builtin functions jump table](https://docs.python.org/3/library/functions.html), told myself many times I should try to enhance it, tried myself at it today, here's what I got:

Screenshot_2020-07-07 Built-in Functions — Python 3 10 0a0 documentation

What do you think?

### CODE REVIEW

**Comment by JulienPalard** [comment]
Hi @ambv, would you like to see this backported to 3.8 and 3.9?

**Comment by merwok** [comment]
(Watching here to get a confirmation if doc changes count as bugfixes!)

**Comment by verhovsky** [comment]
This makes the page scroll left to right when viewed on mobile. The 3.9 docs don't have this issue, you can only scroll them down. I'm not sure if this is the reason, but the table should also still take 100% of the available width, this version has some whitespace around it.

**Comment by JulienPalard** [comment]
Hi @verhovsky, can you please open an issue about this on https://github.com/python/python-docs-theme/issues?

**Pull request merged**
