### PR TITLE
bpo-41255: handle argparse errors with exit_on_error=False consistently

### PR DESCRIPTION
**Pull request by joshmeranda**
[bpo-41255](https://bugs.python.org/issue41255)

When unknown arguments are passed to `parse_args` or required arguments not passed to either `parse_args` or `parse_known_args` argpase exits despite `exit_on_error=False`. This is not very intuitive, instead any error parsing arguments should result in an `ArgumentError` which can be handled by the user.

https://bugs.python.org/issue41255

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@joshmeranda

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by MaxwellDupre — APPROVED** [review]
Works for me:
Ran 1658 tests in 2.516s
OK

Simple bug mentioned case too!
Nice work

**Comment by AA-Turner** [comment]
Trigger CLA.

A

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @joshmeranda. I apologize for the fact that this PR was neglected for a long time. The problem has already been solved in another way.

**Pull request closed without merging**
