### PR TITLE
bpo-41521, typing: Rename _PROTO_WHITELIST to _PROTO_ALLOWLIST

### PR DESCRIPTION
**Pull request by vstinner**
https://bugs.python.org/issue41521

### CODE REVIEW

**Comment by vstinner** [comment]
@gvanrossum @ilevkivskyi:
* Would you mind to review this change?
* Is it ok to rename the **private** `typing._PROTO_WHITELIST` variable?
* Should we keep an alias (`_PROTO_WHITELIST = _PROTO_ALLOWLIST`) during 1 or 2 releases?
* Should I document this change change in a NEWS entry?

**Comment by vstinner** [comment]
FYI I also renamed one test_typing test in commit 0ee0b2938cb606151d8d287472c838044bad4a0e.

**Comment by gvanrossum** [comment]
I prefer not to do this. I find it linguistically awkward, and reading the history of “blacklist” on Wikipedia I don’t see any connection with racism. https://en.m.wikipedia.org/wiki/Blacklisting

**Comment by tiran** [comment]
> I prefer not to do this. I find it linguistically awkward, and reading the history of “blacklist” on Wikipedia I don’t see any connection with racism. [en.m.wikipedia.org/wiki/Blacklisting](https://en.m.wikipedia.org/wiki/Blacklisting)

Yes, the term is not racist. It's more subtle. The negative co-notation of black is death by a thousand paper cuts. The great Muhammad Ali explained this in multiple interviews, e.g. https://www.youtube.com/watch?v=7eXdt1eGgCA

**Comment by gvanrossum** [comment]
Then someone else can approve this. I hope you understand.

**Pull request merged**
