### PR TITLE
bpo-41219: Add audio/webm in mimetypes

### PR DESCRIPTION
**Pull request by cereblanco**
**[bpo-41219](https://bugs.python.org/issue41219): Add audio/webm in mimetypes**

https://bugs.python.org/issue41219

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@cereblanco

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by cereblanco** [comment]
> You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

hello! i just signed but not received/approved yet.

**Review by eamanu — COMMENTED** [review]
Sorry, I don't know mimetypes.py, but just adding  this  line, it's enough?

**Comment by cereblanco** [comment]
> Sorry, I don't know mimetypes.py, but just adding this line, it's enough?

yes, it is added int the dictionary of `_types_map_default`, which is iterated upon initialization, such that each item will be added as type.
 

> Sorry, I don't know mimetypes.py, but just adding this line, it's enough?

**Comment by cereblanco** [comment]
Closing this PR. `audio/webm` also has the same extension as `video/webm`. Might do it in another PR.

**Pull request closed without merging**
