### PR TITLE
bpo-41361: Converting collections.deque methods to Argument Clinic

### PR DESCRIPTION
**Pull request by corona10**
https://bugs.python.org/issue41361

### CODE REVIEW

**Comment by rhettinger** [comment]
Please don't change all the variable names inside the functions — that churns lots of code unnecessarily and it makes it more difficult to see what changed.

Also, is there any advantage to doing all this?  From my point of view, it greatly clutters the code for very little benefit.  It also makes it more difficult to see whether the calling patterns are optimized.

**Comment by rhettinger** [comment]
I've thought about this more and think we should leave the code as-is.  All of these changes interfere with my ability to read and maintain the code.  Without a compelling benefit, we should just skip it.  We already applied vectorcall in the place where it would help.  If we really thought it necessary, we could use text signatures, but most of these methods already have very simple signatures.

**Comment by rhettinger** [comment]
Thank you for your efforts and your understanding :-)

**Comment by corona10** [comment]
> Thank you for your efforts and your understanding :-)

Thank you for your explanation ;)

**Pull request closed without merging**
