### PR TITLE
Docs: structure the ftplib reference

### PR DESCRIPTION
**Pull request by erlend-aasland**
Introduce the following headings and subheadings:

- Reference
  * FTP objects
  * FTP_TLS objects
  * Module variables

----
📚 Documentation preview 📚: https://cpython-previews--114317.org.readthedocs.build/

### CODE REVIEW

**Comment by hugovk** [comment]
Looks fine, the diff is a bit tricky to compare though - does this only add headings and rearrange some chunks, with no other changes?

**Comment by erlend-aasland** [comment]
> Looks fine, the diff is a bit tricky to compare though - does this only add headings and rearrange some chunks, with no other changes?

Let me redo this and check!

**Comment by erlend-aasland** [comment]
Ok, so there's a couple of small changes embedded here:

- Remove the sentence _"The module defines the following items:"_; the header _Reference_ was introduced instead.
- The introduction in the original _FTP Objects_ was changed from:
  > Several methods are available in two flavors: one for handling text files and
  > another for binary files.  These are named for the command which is used
  > followed by ``lines`` for the text version or ``binary`` for the binary version.

  To:
  > Several :class:`!FTP` methods are available in two flavors:
  > one for handling text files and another for binary files.
  > The methods are named for the command which is used followed by
  > ``lines`` for the text version or ``binary`` for the binary version.

**Review by hugovk — APPROVED** [review]
Thanks!

**Pull request merged**
