### PR TITLE
gh-109615: Fix test_tools.test_freeze SRCDIR

### PR DESCRIPTION
**Pull request by vstinner**
* Use sysconfig to get the source directory.
* Use sysconfig.get_config_var() to get CONFIG_ARGS variable.

* Issue: gh-109615

### CODE REVIEW

**Comment by vstinner** [comment]
!buildbot s390x SLES

**Comment by vstinner** [comment]
!buildbot s390x Debian

**Comment by vstinner** [comment]
I'm not sure why previously, a subprocess was spawned to run "python -c sysconfig.get_config_var(...)", rather than using directly sysconfig.get_config_var(). The frozen app can target a different Python program?

**Comment by vstinner** [comment]
@ericsnowcurrently: You added ``Tools/freeze/test/`` in commit 13d9205f4057eeeef80a25d410ad123876dc60cd. Do you recall why you didn't use sysconfig directly?

**Comment by vstinner** [comment]
!buildbot s390x SLES

**Comment by vstinner** [comment]
!buildbot s390x Debian

**Comment by ericsnowcurrently** [comment]
> @ericsnowcurrently: You added `Tools/freeze/test/` in commit [13d9205](https://github.com/python/cpython/commit/13d9205f4057eeeef80a25d410ad123876dc60cd). Do you recall why you didn't use sysconfig directly?

I don't recall.  I may have copied it from somewhere, or had trouble using sysconfig, or something else.  Sorry.  Wish I remembered.

**Comment by vstinner** [comment]
!buildbot wasm32-wasi

**Comment by vstinner** [comment]
!buildbot s390x Debian

**Pull request merged**
