### PR TITLE
gh-107149: Rename PyUnstable_ExecutableKinds to _Py_ExecutableKinds

### PR DESCRIPTION
**Pull request by vstinner**
Rename contants, replace Py with _Py (add underscore prefix):

* PY_EXECUTABLE_KIND_SKIP = > _PY_EXECUTABLE_KIND_SKIP
* PY_EXECUTABLE_KIND_PY_FUNCTION => _PY_EXECUTABLE_KIND_PY_FUNCTION
* PY_EXECUTABLE_KIND_BUILTIN_FUNCTION => _PY_EXECUTABLE_KIND_BUILTIN_FUNCTION
* PY_EXECUTABLE_KIND_METHOD_DESCRIPTOR => _PY_EXECUTABLE_KIND_METHOD_DESCRIPTOR
* PY_EXECUTABLE_KINDS => _PY_EXECUTABLE_KINDS

* Issue: gh-107149

### CODE REVIEW

**Comment by gvanrossum** [comment]
Please hold off at least until we've had a change to discuss this with @markshannon. I expect see him tomorrow.

**Comment by vstinner** [comment]
>  docs/readthedocs.org:cpython-previews — Read the Docs build failed! 

Error:

> There was a problem with Read the Docs while building your documentation. Please try again later. If this problem persists, report this error to us with your build id (21758601).

I rebased my PR on the main branch to re-trigger CI jobs.

**Comment by markshannon** [comment]
These constants are intended for tools like pyspy and austin, which are out-of-process tools.
They need to copy and paste the constants, so it doesn't matter to them whether they are private or unstable.
However, they could be useful for in-process tools as well, so making them "unstable" seems best.

Presumably, that means moving them to `Include/cpython/pyframe.h` and giving them a `PY_UNSTABLE` prefix.

Generally, I think we shouldn't be adding private (ie. `_PY_`) constants to (semi-)public headers, unless we really can't avoid it.

**Comment by vstinner** [comment]
> Presumably that means moving them to Include/cpython/pyframe.h and giving them a PY_UNSTABLE prefix.

Oh, I already wrote PR #108440 for that, the alternative option :-)

**Comment by vstinner** [comment]
@markshannon prefers to add this API to the public C API, so I close this PR. See PR #108440 instead.

**Pull request closed without merging**
