### PR TITLE
[3.12] gh-114053: Fix bad interaction of PEP-695, PEP-563 and ``get_type_hints`` (#118009)

### PR DESCRIPTION
**Pull request by AlexWaygood**
(cherry-picked from commit 1e3e7ce11e3b0fc76e981db85d27019d6d210bbc)

Co-authored-by: Jelle Zijlstra <jelle.zijlstra@gmail.com>

* Issue: gh-114053

----
📚 Documentation preview 📚: https://cpython-previews--118104.org.readthedocs.build/

### CODE REVIEW

**Comment by dimaqq** [comment]
This change causes a regression in some, admittedly rather old code.
Discussion is here: https://discuss.python.org/t/3-12-3-3-12-4-regression-deep-rabbit-hole-warning/59584/12

**Comment by AlexWaygood** [comment]
> This change causes a regression in some, admittedly rather old code. Discussion is here: [discuss.python.org/t/3-12-3-3-12-4-regression-deep-rabbit-hole-warning/59584/12](https://discuss.python.org/t/3-12-3-3-12-4-regression-deep-rabbit-hole-warning/59584/12)

Sorry to hear that. It's pretty unclear to me what exactly the regression is from skimming that Discourse thread, however, and I'm a little low on time right now. Would you be able to create an issue with a minimal, reproducible example?

**Comment by dimaqq** [comment]
I have a rather small MRE here: https://github.com/dimaqq/MRE-sphinx-PurePath

- 3 small user files
- uses Sphinx 6.2.1 + autodoc + basic extensions

I haven't gotten deep into Sphinx and how it uses the type system, there would probably be a lot to learn there...

### MRE summary

Given this code:

```py
import typing
from pathlib import PurePath
from typing import BinaryIO, Optional, TextIO, Union

class Container:
    """blah"""

    # This is OK (assuming intersphinx is set up)
    def another(self, path: Union[str, PurePath], *, encoding: Optional[str] = 'utf-8'):
        """a docstring"""

    # In the type overload specifically, the `path` argument type is broken under py 3.12.4
    @typing.overload
    def pull(self, path: Union[str, PurePath], *, encoding: str = 'utf-8') -> TextIO: ...

    # Sphinx seems to ignore this signature if there is a type overload
    def pull(self, path: Union[str, PurePath], *, encoding: Optional[str] = 'utf-8'):
        """a docstring"""
```

Trying to build docs for this code with Sphinx 6.2.1 works under py 3.12.3 and fails under 3.12.4, whith this PR being the breaking change (confirmed by git bisect).

**Comment by dimaqq** [comment]
Daniel has tracked it down to function signature change for `fr._evaluate` here:

https://discuss.python.org/t/3-12-3-3-12-4-regression-deep-rabbit-hole-warning/59584/14

Whether the change is required or a regression is something I’m not qualified to have an opinion on, and will gladly leave to Python devs.

**Pull request merged**
