### PR TITLE
gh-63882: Adds tests for xml.dom.minidom

### PR DESCRIPTION
**Pull request by karlcow**
This is a *work in progress* not yet ready for review.

https://bugs.python.org/issue19683

* Issue: gh-63882

### CODE REVIEW

**Comment by terryjreedy** [comment]
The merge conflict is a result of new imports for pyexpat and parsers...ExpatError in main.  I could easily fix the conflict, but I really do not not putting multiple imports from one module in separate lines and would undo an revise that change also at the same time.

**Comment by terryjreedy** [comment]
I consider this unreviewable until split into multiple PRs.  See https://github.com/python/cpython/issues/63882#issuecomment-1329959189

**Comment by karlcow** [comment]
I can't work on this anymore. Unfortunately.

**Comment by terryjreedy** [comment]
@karlcow Thank you for this draft.  The docstring additions have been moved to a new issue #128508 and PR #128477 for revisions.  You are listed on the latter as a co-author.

The empty tests should be commented out until replaced, not removed.  A new PR should close the issue.

The revised tests, fixing names and code, should be moved to another new issue.  With this is done, the tests for class methods should be put in separate TestCase classes.  MinidomTest should only have the module function tests.

**Pull request closed without merging**
