### PR TITLE
gh-101766: Fix refleak for _BlockingOnManager resources at test-suite level

### PR DESCRIPTION
**Pull request by corona10**
* Issue: gh-101766

Reverting the change due to https://github.com/python/cpython/pull/101942#discussion_r1109686308

### CODE REVIEW

**Comment by corona10** [comment]
@exarkun Would you like to take a look?

**Comment by corona10** [comment]
FYI,
I verified this PR by running 50 times refleak test suite for the `test_importlib`

**Comment by corona10** [comment]
Oops it doen't solve the issue

**Comment by exarkun** [comment]
> Oops it doesn't solve the issue

I would make one PR that just reverts the original change followed by another PR that fixes the object leak.  That way the eventual fix is not mixed together with remnants of the earlier incomplete fix.  Also, it lets the regression in importlib get fixed immediately while we take what time we need to fix the object leak.

**Pull request closed without merging**
