### PR TITLE
bpo-33083: Add elimination of non-int-like parameters in math.factorial to "What's new"

### PR DESCRIPTION
**Pull request by pablogsal**
https://bugs.python.org/issue33083

### CODE REVIEW

**Review by vstinner — COMMENTED** [review]
I suggest to move the entry to the "Changes in Python behavior" section below.

**Comment by serhiy-storchaka** [comment]
Rather to the "Changes in the Python API" section.

**Comment by pablogsal** [comment]
Done in d6dd9cb

**Review by vstinner — APPROVED** [review]
LGTM.

**Review by serhiy-storchaka — APPROVED** [review]

**Pull request merged**
