### PR TITLE
bpo-42952: Fix the handling of EC_KEY_new_by_curve_name() in _ssl.c

### PR DESCRIPTION
**Pull request by ZackerySpytz**
https://bugs.python.org/issue42952

### CODE REVIEW

**Comment by ZackerySpytz** [comment]
This is a "skip news" PR.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. BTW there is a similar code in `_ssl__SSLContext_set_ecdh_curve()`.

**Review by tiran — CHANGES_REQUESTED** [review]
It's dead code and never used with supported OpenSSL versions.

**Comment by serhiy-storchaka** [comment]
If it is never used, then why not remove it?

If it still can be used on some platforms, it is worth to fix it. The existence of similar code in other place adds confidence in the correctness of the proposed change (it also conforms the documentation).

**Comment by tiran** [comment]
As I explained in the ticket I will remove all unused code in one PR in the future.

**Comment by tiran** [comment]
Code is gone.

**Pull request closed without merging**
