### PR TITLE
gh-60187 Added timeout to queue join function.

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

### CODE REVIEW

**Review by orsenthil — CHANGES_REQUESTED** [review]
Timeout is disruptive in the queue operation. This needs to be discussed before any review and acceptance.

Issue ticket - https://github.com/python/cpython/issues/60187

**Comment by Hadatko** [comment]
No problem with that. Put and get have timeout too. It looks like it is missing requested feature since ~2012. As mentioned no problem to move it into its own function, but this looked more correct to me personally.

**Comment by Hadatko** [comment]
Also to follow other functions we could create 
def join_nowait():
     self.join()

**Comment by rhettinger** [comment]
I appreciate the PR but don't think this should be added.  The need is somewhat rare and we've done fine without it since 2010, nor has it been an issue with [the matching API in multiprocessing](https://bugs.python.org/issue9634).

The put() and get() methods need timeouts because they are more find-grained than *join()* which is used much differently.  See previous discussion at https://bugs.python.org/issue9634   Without likely and compelling use cases, we should leave this out.

During the design discussion for *SimpleQueue*, Guido voiced an objection to having more sophisticated "task management" as part of the Queue API.  Users have many options for communicating task completion including Condition variables, share counters, reply queues, etc.

**Comment by Hadatko** [comment]
It looks like you don't like consistent API. For example thread.join has timeout. I would expect same here.

**Pull request closed without merging**
