### PR TITLE
[3.12] Convert `doc.yml` workflow to be reusable (GH-103914 + GH-105151)

### PR DESCRIPTION
**Pull request by webknjaz**
Co-authored-by: Adam Turner <9087854+AA-Turner@users.noreply.github.com>
Co-authored-by: Hugo van Kemenade <hugovk@users.noreply.github.com>.
(cherry picked from commit 88d14da76f579fe014cbd7c15e42be4234135fe9)

Use CSV-separated outputs @ get-changed-files @ CI (https://github.com/python/cpython/pull/105151)

Co-authored-by: Hugo van Kemenade <hugovk@users.noreply.github.com>
(cherry picked from commit https://github.com/python/cpython/commit/eaa670228066220f08c8d73f80365c50058d40b8)

----
:books: Documentation preview :books:: https://cpython-previews--107042.org.readthedocs.build/

### CODE REVIEW

**Comment by webknjaz** [comment]
@AlexWaygood thanks for fixing the target branch, I overlooked that..

@ambv @pablogsal could you merge the first batch of the backports plz?

**Comment by AlexWaygood** [comment]
> @ambv @pablogsal could you merge the first batch of the backports plz?

None of our CI has yet run on this PR. Since this change is purely focussed on improving our CI, it's important for the CI to run before we can think about merging this :)

**Comment by AlexWaygood** [comment]
> > @ambv @pablogsal could you merge the first batch of the backports plz?
> 
> None of our CI has yet run on this PR. Since this change is purely focussed on improving our CI, it's important for the CI to run before we can think about merging this :)

It passed after closing and reopening the PR.

**Comment by webknjaz** [comment]
> None of our CI has yet run on this PR. Since this change is purely focussed on improving our CI, it's important for the CI to run before we can think about merging this :)

Ah, yeah. It's basically a prerequisite for another backport that will add alls-green to the supported branches too and will help @ambv enable the auto-merge feature.

**Pull request merged**
