### PR TITLE
gh-106948: Add standard external names to nitpick_ignore

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
It includes standard C types, macros and variables like "size_t", "LONG_MAX" and "errno", and standard environment variables like "PATH".

* Issue: gh-106948

----
:books: Documentation preview :books:: https://cpython-previews--106949.org.readthedocs.build/

### CODE REVIEW

**Review by erlend-aasland — APPROVED** [review]
Very nice. Why are you using `:c:texpr:` for `_Bool`?

**Comment by serhiy-storchaka** [comment]
> Why are you using `:c:texpr:` for `_Bool`?

Because it is the correct role for a type expression in C. I prepared a large patch for using `:c:texpr:`, but it depends on this PR. And this PR depends on #107011.

**Comment by erlend-aasland** [comment]
I thought the T in `:texpr:` stood for *text*, not *type*: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#inline-expressions-and-types

**Comment by erlend-aasland** [comment]
Also, `_Bool` is a built-in C type. I don't see why it should be marked up differently from `int`.

**Comment by serhiy-storchaka** [comment]
You are right. I misread the documentation. Thank you, you saved me from opening a new issue.

**Pull request merged**
