### PR TITLE
[3.6] bpo-35257: Avoid leaking LTO linker flags into distutils (GH-10900)

### PR DESCRIPTION
**Pull request by vstinner**
* [bpo-35499](https://bugs.python.org/issue35499): make profile-opt don't override CFLAGS_NODIST (GH-11164)
* [bpo-35257](https://bugs.python.org/issue35257): Avoid leaking LTO linker flags into distutils (GH-10900)

https://bugs.python.org/issue35257

### CODE REVIEW

**Comment by ned-deily** [comment]
Why did you combine the PRs from two separate issues into one?  It would make things much easier to track if you kept them separate, no?

**Comment by vstinner** [comment]
> Why did you combine the PRs from two separate issues into one? It would make things much easier to track if you kept them separate, no?

The first commit isn't important, it's a minor change. But the second commit depends on the first commit. Otherwise, I would get even more conflicts on the backport. So I decided to combine both commits.

**Comment by ned-deily** [comment]
Please separate them.  I spent a couple of hours earlier trying to decipher and document the tangled mess of the several bpo issues and PRs involved in this sequence over the various branches.  Combining these just makes the mess more complicated.

**Comment by vstinner** [comment]
I created PR #11267 for the first change.

**Comment by vstinner** [comment]
@ned-deily: Oh you succeeded to merge it, thanks.

I was trying to create a PR to the second change, but there was a conflict since you already merged this PR :-)

Cool, I'm happy to see this bug fixed in 3.6 as well ;-)

**Pull request merged**
