### PR TITLE
gh-121039: add Floats/ComplexesAreIdenticalMixin to test.support.testcase

### PR DESCRIPTION
**Pull request by skirpichev**
* Issue: gh-121039

### CODE REVIEW

**Comment by skirpichev** [comment]
I think this can skip news.

**Review by sobolevn — APPROVED** [review]
Seems like a good refactoring, thanks!

**Comment by sobolevn** [comment]
Build failure is not related and is reported here https://github.com/python/cpython/issues/121065

**Comment by skirpichev** [comment]
There are more cases, which could be changed, some were mentioned in the issue.  But I'm not sure it worth - stopping reinvent the wheel in new tests seems enough.

**Comment by skirpichev** [comment]
Unfortunately, https://github.com/python/cpython/pull/120894 was merged first.  Yet one place to refactor, fixed.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Comment by serhiy-storchaka** [comment]
I think that `test_capi/test_getargs.py` is a fair case, and pretty simple too.

Cases in `test_math.py` are more complex.

**Comment by skirpichev** [comment]
> I think that test_capi/test_getargs.py is a fair case, and pretty simple too.

Yeah, added this.

> Cases in test_math.py are more complex.

Some seems mechanical too (assertEqualSign helper).  But I'm not sure if this worth it.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by skirpichev** [comment]
I'm working on backports.

**Pull request merged**
