### PR TITLE
gh-85454: Remove distutils documentation

### PR DESCRIPTION
**Pull request by tiran**
Most places now refer to setuptools or link to setuptools documentation.
Some examples like zipapp need to be updated later.

* Issue: gh-85454

### CODE REVIEW

**Comment by merwok** [comment]
Given the numerous external links pointing to our docs, I was thinking of keeping the documents (without toctree reference) to avoid 404 errors and include a file mentioning the removal and linking to packaging.python.org.

**Comment by ambv** [comment]
@merwok, IDK. https://docs.python.org/3/ currently points at 3.10 and includes the deprecation warning at https://docs.python.org/3/library/distutils.html:

> [distutils](https://docs.python.org/3/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12. See the [What’s New](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated) entry for more information.

https://docs.python.org/3/ will link to 3.11 between October 2022 and October 2023. This will include the same deprecation warning on the distutils.html page.

When we remove other deprecations, we remove them from the docs, there is no "Removed in ..." Sphinx directive. Do you feel `distutils.html` is special somehow?

**Comment by ambv** [comment]
Umm, apparently I'm wrong about *"there is no "Removed in ..." Sphinx directive"*. I thought `deprecated-removed` was used for *future* removals but there are two examples where this applies to historical deprecations:
- https://docs.python.org/3/using/cmdline.html
- https://docs.python.org/3/library/hmac.html

Given this precedent, if you feel we should leave the distutils.html file non-404'ing, I'm happy to add a dummy page to the docs to amend this PR.

**Comment by tiran** [comment]
@merwok has a point. A 401 is not user-friendly. Can we have a redirect rule on docs.python.org to ``301 Moved Permanently`` the ``library/distutils.html`` and ``distutils/index.html`` to a page that points the user to setuptools.

**Comment by merwok** [comment]
Re-adding 13 doc files with minimal contents would be more straightforward IMO.  But if you think it’s cruft for the CPython repo, and it’s ok if someone has to chase the docs infra repo to see or change how redirections are done, then I can make a PR there.

**Pull request merged**
